fix bug : The status change of kubelet will cause unnecessary pod mig…
kubernetes/kubernetes pull request #100063
Opened 2021-03-10 06:50 UTC by changshuchao

…ration

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
If kubelet is stopped, pod will migrate between different nodes, which is normal. However, if you just restart the kubelet or modify the kubelet parameters through configz, the status change of the kubelet will cause unnecessary pod migration.
When we restart kubelet, the following code will be executed:
`func (kl *Kubelet) Run(updates <-chan kubetypes.PodUpdate) {
...
	if kl.kubeClient != nil {
		// Start syncing node status immediately, this may set up things the runtime needs to run.
		go wait.Until(kl.syncNodeStatus, kl.nodeStatusUpdateFrequency, wait.NeverStop)
		go kl.fastStatusUpdateOnce()

		// start syncing lease
		go kl.nodeLeaseController.Run(wait.NeverStop)
	}
	go wait.Until(kl.updateRuntimeUp, 5*time.Second, wait.NeverStop)
...
`
The kl.syncNodeStatus method is executed every 10 seconds by default,and the kl.updateRuntimeUp method is executed every 5 seconds by default.They are all executed in goroutine.

kl.syncNodeStatus will do the following thing:

1. kl.registerWithAPIServer()  tip : After the registration is successful, the flag bit will be set and will not be executed in the loop
2. kl.updateNodeStatus()

`func (kl *Kubelet) syncNodeStatus() {
	kl.syncNodeStatusMux.Lock()
	defer kl.syncNodeStatusMux.Unlock()

	if kl.kubeClient == nil || kl.heartbeatClient == nil {
		return
	}
	if kl.registerNode {
		// This will exit immediately if it doesn't need to do anything.
		kl.registerWithAPIServer()
	}
	if err := kl.updateNodeStatus(); err != nil {
		klog.Errorf("Unable to update node status: %v", err)
	}
}`

kl.updateRuntimeUp will read the status information in kl.containerRuntime and update it to kl.runtimeState, and provide it to kl.syncNodeStatus(kl.updateNodeStatus() inside) to use when judging the NodeReady status in node.

Therefore, if the kubelet is restarted, the status of the node is likely to change like this: ready->not ready->ready.

we should execute kl.updateRuntimeUp before execute kl.updateNodeStatus() in syncNodeStatus() when first time we register this node.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-03-10 06:57 UTC, changshuchao commented
/assign @mtaufen

2021-03-10 06:57 UTC, changshuchao commented
/assign @Random-Liu

2021-03-10 08:16 UTC, ping035627 commented
/ok-to-test

2021-03-10 08:37 UTC, ping035627 commented
Actually, restart kubelet when kl.containerRuntime is running normally, the status of the node turns to NotReady because the kl.updateRuntimeUp hasn't been executed yet, and the kl.runtimeState.lastBaseRuntimeSync is nil. The kl.runtimeState.lastBaseRuntimeSync is set at the end of  kl.updateRuntimeUp. When the node is registered successfully, check kl.updateRuntimeUp first to avoid unnecessary state migration.

![image](https://user-images.githubusercontent.com/17894459/110600187-9f38c800-81be-11eb-8a8f-91fbaff131fc.png)

2021-03-12 06:02 UTC, changshuchao commented
/assign @dchen1107

2021-03-13 06:09 UTC, changshuchao commented
@ehashman can you review this pr ? thanks

2021-03-16 11:00 UTC, changshuchao commented
@klueska could you please review this pr , thx!

2021-04-12 17:19 UTC, jsturtevant commented
looks like there are a few unit tests that test the behavior of the nodestatus and runtime status.  Could a test case be added or modified to catch this case?

2021-04-21 17:45 UTC, ehashman requested changes
Agree with the comment above, this needs a test before review.

2021-09-18 20:37 UTC, closed without merging