Update pause image to v3.5
kubernetes/kubernetes pull request #100292
Opened 2021-03-16 12:43 UTC by saschagrunert

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Update dependencies and the test images to use pause 3.5. We also
provide a changelog entry for the new container image version.

#### Which issue(s) this PR fixes:

Refers to https://github.com/kubernetes/kubernetes/pull/97963

#### Special notes for your reviewer:

Previous 3.4.1 update PR: https://github.com/kubernetes/kubernetes/pull/98205

#### Does this PR introduce a user-facing change?

```release-note
Updated pause image to version 3.5, which now runs per default as pseudo user and group `65535:65535`.
This does not have any effect on remote container runtimes like CRI-O and containerd, which setup the pod
sandbox user and group on their own.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

2021-03-16 13:15 UTC, troy0820 requested changes
Change tag in file `build/pause/Makefile` to `3.5` to coincide with the changed dependency.

2021-03-16 13:16 UTC, troy0820 commented
/priority important-soon
/triage accepted

2021-03-16 13:24 UTC, saschagrunert commented
We have to promote the new pause image, see https://github.com/kubernetes/k8s.io/pull/1793

2021-03-16 13:29 UTC, troy0820 commented
@saschagrunert Makes perfect sense.  Do we want to update that tag in a subsequent PR or after [1793](https://github.com/kubernetes/k8s.io/pull/1793) is merged in this PR?

2021-03-16 13:44 UTC, saschagrunert commented
> @saschagrunert Makes perfect sense. Do we want to update that tag in a subsequent PR or after [1793](https://github.com/kubernetes/k8s.io/pull/1793) is merged in this PR?

`build/pause/Makefile` is already on `3.5` :)

/retest

2021-03-16 13:50 UTC, saschagrunert commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-03-16 13:53 UTC, troy0820 commented
> build/pause/Makefile is already on 3.5 :)
🤦🏽  I was comparing locally
/lgtm

2021-03-16 14:07 UTC, saschagrunert commented
/test pull-kubernetes-conformance-kind-ipv6-parallel

2021-03-16 14:18 UTC, saschagrunert commented
/test pull-kubernetes-e2e-aks-engine-windows-containerd-test-images

2021-03-16 14:28 UTC, saschagrunert commented
/test pull-kubernetes-e2e-kind

2021-03-16 14:36 UTC, pacoxu approved these changes
kubernetes/k8s.io#1793 is merged.
/lgtm

2021-03-16 14:44 UTC, troy0820 approved these changes

2021-03-16 15:07 UTC, saschagrunert commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-03-16 15:27 UTC, pacoxu commented
Like #98205
- containerd/kind/cri-o/minikube need update the pause image as well.

I opened the one for containerd. https://github.com/containerd/containerd/pull/5211

2021-03-16 15:46 UTC, troy0820 commented
I opened the one for KinD. https://github.com/kubernetes-sigs/kind/pull/2134

2021-03-16 18:49 UTC, neolit123 commented
hi, is this for 1.21?

2021-03-16 19:02 UTC, saschagrunert commented
> hi, is this for 1.21?

There is no decision available yet, but I guess it would be good to have it in. :)

/retest

2021-03-16 21:05 UTC, saschagrunert commented
/retest

2021-03-16 21:07 UTC, saschagrunert commented
I would need a couple of approvals on this one.

/assign @cblecker @janetkuo @sataqiu @yujuhong

2021-03-17 02:05 UTC, dims commented
/approve

2021-03-17 02:07 UTC, dims commented
/assign @liggitt @smarterclayton 

easier to get root approvers :)

2021-03-17 02:09 UTC, liggitt commented
just to double-check, this is not targeting 1.21, right?

2021-03-17 02:13 UTC, dims commented
let's ask :)

@saschagrunert can you please chime in?

2021-03-17 08:19 UTC, saschagrunert commented
> just to double-check, this is not targeting 1.21, right?

I see pros and cons of having it in 1.21: On one hand we have changed the pause image already and promoted it to k8s.gcr.io, which would make sense from my point of view to add this PR as well.

On the other hand we have to see how much work and CI related changes it will cause, which means I would definitely double check with @kubernetes/release-engineering and @kubernetes/sig-testing.

2021-03-17 13:09 UTC, liggitt commented
> I see pros and cons of having it in 1.21: On one hand we have changed the pause image already and promoted it to k8s.gcr.io, which would make sense from my point of view to add this PR as well.

Even though a new pause image has been built and is available, it isn't actually in use yet. This seems like something that shouldn't be landing post code-freeze.

2021-03-17 13:34 UTC, justaugustus commented
> This seems like something that shouldn't be landing during code-freeze.

Agreed.
/milestone v1.22

2021-03-29 19:18 UTC, BenTheElder commented
Worth noting that containerd moved up to 3.5 already anyhow.

When dockershim goes we're not going to be able to control what version we use in CI from this repo at all.

I attempted to discuss this with SIG node but missed the meeting where this came up (conflicting hosting SIG testing at the same time), IMHO the forward path is moving pause to a k-sigs subproject owned by node and consumed by the CRI implementations on it's own release cycle (same as it having it's own versioning + promotion cycle today) and stop coupling it to k/k releases entirely.

2021-03-30 00:34 UTC, dims commented
@BenTheElder the request in the sig-node meeting was to find OWNER(s) from sig-node community who can take charge of this effort, write down the rollout across the CRI impls and k8s, own the testing strategy, plan any other features that could be added etc.

2021-05-03 11:53 UTC, saschagrunert commented
I still require approval by several people on this PR. Pinging @kubernetes/sig-cli-maintainers, @sig-node-approvers and @hasheddan (for SIG Release)

2021-05-03 11:55 UTC, cpanato approved these changes
/lgtm

2021-05-03 13:57 UTC, hasheddan approved these changes
/lgtm

2021-05-03 15:13 UTC, dims commented
/approve
/lgtm

2021-05-03 16:44 UTC, BenTheElder commented
/lgtm
/approve

2021-05-03 17:02 UTC, justaugustus commented
/lgtm
/approve
/assign @liggitt

2021-05-03 17:27 UTC, liggitt commented on build/pause/CHANGELOG.md
> +# 3.5
should this be 3.4.1?

2021-05-03 17:29 UTC, liggitt commented
/approve

/hold for changelog fix

2021-05-04 06:55 UTC, saschagrunert commented on build/pause/CHANGELOG.md
> +# 3.5
Yep, fixed as suggested :+1:

2021-05-04 06:56 UTC, saschagrunert commented
Fixed the changelog entry :heavy_check_mark:

2021-05-04 07:04 UTC, justaugustus commented
/lgtm

2021-05-04 22:12 UTC, spiffxp commented
As an end user I might find "pause runs as non-root user by default" more informative than "bumped to 3.5" as a release note. I see something like this is on a linked PR so maybe doesn't matter for this. However, does this require action on the part of someone upgrading their cluster if they for whatever reason require the previous behavior?

2021-05-05 04:43 UTC, BenTheElder commented
> As an end user I might find "pause runs as non-root user by default" more informative than "bumped to 3.5" as a release note. 

Has anyone verified that this is actually the end result with any of the runtimes? How pause is used will depend on what runtime you use, e.g. upgrading it here typically only impacts dockershim to begin with.

> ... if they for whatever reason require the previous behavior?

... That shouldn't be possible? ™️

2021-05-05 07:46 UTC, saschagrunert commented
> > As an end user I might find "pause runs as non-root user by default" more informative than "bumped to 3.5" as a release note.
> 
> Has anyone verified that this is actually the end result with any of the runtimes? How pause is used will depend on what runtime you use, e.g. upgrading it here typically only impacts dockershim to begin with.

CRI-O does not pickup the username for the sandbox from the pause container image. It still uses `0:0` as user:group.

2021-05-14 09:11 UTC, saschagrunert commented
Had to rebase this one. Please take a look again @justaugustus @liggitt

2021-05-25 07:05 UTC, saschagrunert commented
Had to rebase again.

2021-05-25 11:47 UTC, dims commented
@saschagrunert we should probably add some release notes on what to expect / what to watch out for given the changes in https://github.com/kubernetes/kubernetes/pull/97963 

/approve

2021-05-25 11:48 UTC, dims commented
/lgtm

2021-05-25 11:52 UTC, cpanato approved these changes
/lgtm

2021-05-25 12:23 UTC, saschagrunert commented
Updated  the changelog to be more descriptive. I also already addressed the changelog file, so:
/hold cancel

2021-05-25 13:24 UTC, merged