pause image: Updates kube-cross image version used
kubernetes/kubernetes pull request #100592
Opened 2021-03-26 18:35 UTC by claudiubelu

#### What type of PR is this?

/sig windows

#### What this PR does / why we need it:

``kube-cross:v1.16.2-1`` contains ``x86_64-w64-mingw32``, which will allow us to build Windows binaries. With this, we won't have to rely on the dockerhub image ``dockcross/windows-static-x64``.

#### Which issue(s) this PR fixes:

Fixes #99360

#### Special notes for your reviewer:

Image Building logs: https://paste.ubuntu.com/p/26QWZXwyP5/

Published image sample: ``claudiubelu/pause:3.6``
Running the image:

```
atuvenie@ubuntu:~/release/images/build/cross$ docker --tlsverify --tlscacert ~/.docker-${os_version}/ca.pem --tlscert ~/.docker-${os_version}/cert.pem --tlskey ~/.docker-${os_version}/key.pem -H "tcp://img-promoter-1809.eastus.cloudapp.azure.com:2376" pull claudiubelu/pause:3.6
3.6: Pulling from claudiubelu/pause
a11c4ca8f1ba: Already exists
8c70accf979e: Pull complete
8a13d1c556cb: Pull complete
9a7a79f01078: Pull complete
Digest: sha256:b8194fced735f5f11958f8fbbf3aa5aa86123283729c35ff1d13ed72bcb86639
Status: Downloaded newer image for claudiubelu/pause:3.6
docker.io/claudiubelu/pause:3.6
atuvenie@ubuntu:~/release/images/build/cross$ docker --tlsverify --tlscacert ~/.docker-${os_version}/ca.pem --tlscert ~/.docker-${os_version}/cert.pem --tlskey ~/.docker-${os_version}/key.pem -H "tcp://img-promoter-1809.eastus.cloudapp.azure.com:2376" run --rm -ti claudiubelu/pause:3.6
Shutting down, got signal
^C

```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-03-26 18:36 UTC, claudiubelu commented
/hold

2021-04-16 11:58 UTC, claudiubelu commented
Using the kube-cross:v1.16.3-1 staging image: https://paste.ubuntu.com/p/HJQX2H88KZ/

Depends On: https://github.com/kubernetes/k8s.io/pull/1936

2021-04-16 23:46 UTC, justaugustus commented
/hold for https://github.com/kubernetes/kubernetes/pull/101206

2021-04-19 11:10 UTC, claudiubelu commented
> 
> 
> /hold for #101206

That PR merged, we can cancel the hold now.

/hold cancel

2021-04-19 11:11 UTC, claudiubelu commented
/kind cleanup
/sig windows

2021-04-19 23:22 UTC, justaugustus requested changes
@claudiubelu -- You'll also need to update the pause image version in `build/dependencies.yaml`:

```console
INFO Validating zeitgeist options...              
ERRO /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml indicates that k8s.gcr.io/pause should be at version 3.5, but the following files didn't match: build/pause/Makefile 
FATA Dependencies are not in sync                 
```

ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100592/pull-kubernetes-dependencies/1384101849711251456

2021-04-28 12:03 UTC, claudiubelu commented
/test pull-kubernetes-e2e-kind

2021-05-06 16:45 UTC, jsturtevant commented
/lgtm

2021-05-06 19:04 UTC, merged