Fix for Flaky test ReplicaSet Replace and Patch tests [Conformance]
kubernetes/kubernetes pull request #100759
Opened 2021-04-01 18:31 UTC by jsturtevant

#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:
`ReplicaSet Replace and Patch tests [Conformance]` Tests for windows and linux were flaking on pod start ups.  https://github.com/kubernetes/kubernetes/pull/100191 introduced a timeout.  This waits longer for the pods to be ready before checking the state.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=ReplicaSet%20Replace%20and%20Patch%20tests#fcd31aadf7e9b5edc7c6

#### Which issue(s) this PR fixes:

Fixes #100725

#### Special notes for your reviewer:
I could have increased the timeout to a longer period of time but the rest of the tests in this suite use this same method (over the list watch method) so I updated it for consistency.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-04-01 18:56 UTC, soltysh requested changes
you're going back to previous solution which fixed a different problem. If need I'd suggest increasing the timeout to 1 minute rather than going back.

2021-04-01 19:12 UTC, jsturtevant commented
it's not quite the same as the previous solution.  The previous solution didn't wait for the pods to start up.  https://github.com/kubernetes/kubernetes/pull/100191/files

2021-04-01 19:35 UTC, jsturtevant commented
I've bumped the timeout instead of waiting for the pods as requested (used the same value from the `VerifyPodsRunning` https://github.com/kubernetes/kubernetes/blob/a651804427dd9a15bb91e1c4fb7a79994e4817a2/test/e2e/framework/pod/wait.go#L54) 

I put the other option on a branch here incase anyone is interested: https://github.com/kubernetes/kubernetes/compare/master...jsturtevant:replica-set-flake-issue-100725-waitforpods?expand=1

2021-04-01 20:32 UTC, jsturtevant commented
`pull-kubernetes-e2e-kind` test failure tracked here: https://github.com/kubernetes/kubernetes/issues/99979
/retest

2021-04-01 21:17 UTC, thejoycekung commented
/milestone 1.21
because this is affecting the 1.21 jobs as well

2021-04-01 21:18 UTC, thejoycekung commented
/milestone v1.21

2021-04-01 22:56 UTC, thejoycekung commented
/retest

` Deployment should run the lifecycle of a Deployment ` is tracked in #100047

2021-04-02 00:11 UTC, jeremyje commented
/lgtm
/approve

2021-04-02 12:10 UTC, soltysh approved these changes
/approve

2021-04-02 12:12 UTC, merged

2021-04-02 14:00 UTC, palnabarun commented
@jsturtevant -- this needs to be cherry-picked to the release-1.21 branch as well. Can you please open PR for that as well?

2021-04-02 14:13 UTC, dims commented
@palnabarun @jsturtevant to save time, i filed the cherry pick https://github.com/kubernetes/kubernetes/pull/100780

2021-04-02 14:25 UTC, palnabarun commented
@dims -- Thank you so much! You are awesome! 🚀