OIDC authentication against API server: allow multiple values in token for requiredClaims
kubernetes/kubernetes pull request #101314
Opened 2021-04-21 11:26 UTC by devkid

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

When using `requiredClaims`, currently only sting values in the OIDC token are accepted. We want to use this so that we can have an array of values in the token and the value in `requiredClaims` must be in that array.

Example:
OIDC token contains claim `roles` with values `["dev", "prod"]`. We want to be able to specify `requiredClaims` as `roles: dev` so that any user that has the `dev` role can be authenticated.

#### Which issue(s) this PR fixes:

Fixes  #101291

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-04-22 20:05 UTC, fedebongio commented
/remove-sig api-machinery

2021-05-03 20:05 UTC, enj requested changes
Overall I am unsure about this change as it changes the meaning of the existing check.

`foo == val` and `foo in [val1 val2 val3]` are not exactly the same thing.

The existing flag based config is really terrible, and I do not want to expand it further but this seems dangerous without opting in somehow.  This also opens the door to wanting stuff like `both foo and bar in [val1, val2, ...]`.  I would like to see this stuff more holistically handled in a proper config format.

/hold

2021-05-20 12:17 UTC, devkid commented on staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go
> +				return resp, true, nil
Fixed

2021-05-20 12:17 UTC, devkid commented on staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go
> +
Fixed

2021-05-20 20:04 UTC, fedebongio commented
/remove-sig api-machinery

2021-10-17 21:51 UTC, closed without merging