Consistently use log.KObj to format pods in logs
kubernetes/kubernetes pull request #101364
Opened 2021-04-22 10:19 UTC by markusthoemmes

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Pulls straight two stray log lines that use a different format for printing the pod into the context of the log. There's one more logline like that, that AFAIK can't be moved for lack of a `WarningS` function.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-04-22 10:21 UTC, markusthoemmes commented
/assign @sjenning

2021-04-26 17:59 UTC, jsturtevant commented
/ok-to-test
/lgtm

2021-04-27 06:40 UTC, markusthoemmes commented
/retest

2021-04-28 17:50 UTC, ehashman requested changes
> Pulls straight two stray log lines that use a different format for printing the pod into the context of the log. There's one more logline like that, that AFAIK can't be moved for lack of a WarningS function.

Please see the [structured logging migration instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#change-log-functions-to-structured-equivalent). Warningf should become InfoS.

Can we migrate everything to `klog.KObj` so we can remove the pod formatting code?

2021-04-28 17:51 UTC, ehashman commented
/triage accepted
/priority backlog
/lgtm cancel

2021-04-28 17:53 UTC, markusthoemmes commented
@ehashman the formatting functions are used in some error formatting, where I guess their usage is legit. I'll add the `Warningf` call though.

2021-04-28 19:10 UTC, markusthoemmes commented
Actually, I think the remaining `Warningf` call is fine, cause the component (node controller) doesn't seem to be moved to structured logging. So I'd think this is complete.

2021-04-28 23:01 UTC, ehashman commented
SGTM, `fmt.Foof` != `klog.Foof`.

/lgtm

2021-05-03 22:34 UTC, mrunalp approved these changes

2021-05-04 00:21 UTC, merged