kubelet_pods.go: clean makeEnvironmentVariables
kubernetes/kubernetes pull request #101633
Opened 2021-04-30 02:34 UTC by llhuii

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
For the simplicity and clarity, I think we can safely delete the
`delete(serviceEnv, envVar.Name)` and the duplicate comments at
function makeEnvironmentVariables of kubelet_pods.go:774-779.

1. `delete(serviceEnv, envVar.Name)` and `if _, present := tmpEnv[k]; !present`
of line 796 are the same logic that is to merge the non-present keys
of serviceEnv into tmpEnv.

2. And the keys deleted from serviceEnv are guarantee to be in tmpEnv,
this doesn't affect mappingFunc.

3. the delete may miss some key from container.EnvFrom
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-04-30 22:09 UTC, ehashman requested changes
I don't think this refactor is this trivial. I see a number of similar comments in other sections of that function. I think this needs a more holistic look than what has been done here. Putting a hold to give you more of a chance to look at this if you'd like... check out https://github.com/kubernetes/kubernetes/blob/ef9d6f8c934ccb89d763e2ff3d459205acbbcda0/pkg/kubelet/kubelet_pods.go#L799-L806 and other TODOs in this file.

/priority backlog
/ok-to-test
/hold

2021-05-06 02:47 UTC, llhuii commented
Hi, @ehashman, thank you for your kind reply. 

> check out https://github.com/kubernetes/kubernetes/blob/ef9d6f8c934ccb89d763e2ff3d459205acbbcda0/pkg/kubelet/kubelet_pods.go#L799-L806 and other TODOs in this file

Sorry, I didn't make it clear, this pr indeed tries to remove one of these two same TODOs with below:
https://github.com/kubernetes/kubernetes/blob/add13090e22c1b3ce5124d8b91a80c6840f82bc2/pkg/kubelet/kubelet_pods.go#L782-L787

And I think the other TODOs have nothing with these two.


Here are more holistic look I have just looked:
1.  https://github.com/kubernetes/kubernetes/pull/39446/commits/13d693d220dfd628df281ff1d47665f8e54afdfc#diff-e81aa7518bebe9f4412cb375a9008b3481b19ec3e851d3187b3021ee94148f0dL473 of pr #39446: move this TODO comment of ` container.Env` to `serviceEnv` loop.

2. https://github.com/kubernetes/kubernetes/commit/4e466040d9c9f556b19a1d5859ee55a96fc944f3#diff-e81aa7518bebe9f4412cb375a9008b3481b19ec3e851d3187b3021ee94148f0dR582 of pr #39981: add this comment to `container.Env` loop again. **And I don't understand this, it looks to me this is unnecessary as I have said in this pr.**

2021-05-10 02:15 UTC, llhuii commented
> 4e46604#diff-e81aa7518bebe9f4412cb375a9008b3481b19ec3e851d3187b3021ee94148f0dR582 of pr #39981: add this comment to container.Env loop again. And I don't understand this, it looks to me this is unnecessary as I have said in this pr.

Hi, @fraenkel sorry to bother you, can you explain this, and help to take a look this pr if you don't mind that? thank you in advance.

2021-05-10 04:26 UTC, fraenkel commented
> Hi, @fraenkel sorry to bother you, can you explain this, and help to take a look this pr if you don't mind that? thank you in advance.

What specifically are you asking about? Please refer to a specific change/line rather than the enitre PR.

2021-05-10 06:33 UTC, llhuii commented
About this comment and code: 
```go
 // Accesses apiserver+Pods. 
 // So, the master may set service env vars, or kubelet may.  In case both are doing 
 // it, we delete the key from the kubelet-generated ones so we don't have duplicate 
 // env vars. 
 // TODO: remove this next line once all platforms use apiserver+Pods. 
 delete(serviceEnv, envVar.Name) 
```

1. I noticed you moved this comment from the ` container.Env` loop to `serviceEnv` loop in https://github.com/kubernetes/kubernetes/pull/39446/commits/13d693d220dfd628df281ff1d47665f8e54afdfc#diff-e81aa7518bebe9f4412cb375a9008b3481b19ec3e851d3187b3021ee94148f0dL473 (with a diff hash in the url, you can directly click up) of pr #39446.
   
   Then **copied** this comment  back into the ` container.Env` loop in this link https://github.com/kubernetes/kubernetes/commit/4e466040d9c9f556b19a1d5859ee55a96fc944f3#diff-e81aa7518bebe9f4412cb375a9008b3481b19ec3e851d3187b3021ee94148f0dR582 of pr #39981, I think this can **be removed**,.

2. More can we do this TODO in this comment now?

2021-05-10 13:23 UTC, fraenkel commented
The TODO can be removed. If you trace back that TODO, it was created 2 years prior to my changes. It all had to do with transitioning from etcd.

2021-05-26 17:50 UTC, ehashman commented
/triage accepted

2021-05-26 17:59 UTC, ehashman commented
/assign @haircommander

2021-05-26 18:18 UTC, haircommander reviewed
Agreed this code block is duplicated and thus unneeded

/lgtm

2021-06-01 16:48 UTC, mrunalp approved these changes

2021-06-02 02:20 UTC, llhuii commented
Thank you all.
Can you /hold cancel? @ehashman

2021-06-02 13:13 UTC, haircommander commented
/hold cancel

2021-06-02 13:46 UTC, haircommander commented
/retest

2021-06-02 20:42 UTC, merged