Structured Logging migration: migrate package pkg/volume/util/operationexecutor for structured logging
kubernetes/kubernetes pull request #101760
Opened 2021-05-06 12:19 UTC by sanwishe

Structured Logging migration: migrate package pkg/volume/util/operationexecutor for structured logging

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Structured Logging migration: migrate package pkg/volume/util/operationexecutor
xref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-05-06 12:32 UTC, yangjunmyfm192085 commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.InfoS("ExpandVolume succeeded for volume %s", util.GetPersistentVolumeClaimQualifiedName(pvc))
```suggestion
			klog.InfoS("ExpandVolume succeeded for volume",  "volume", util.GetPersistentVolumeClaimQualifiedName(pvc))
```

2021-05-06 12:32 UTC, yangjunmyfm192085 commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.InfoS("ExpandVolume.UpdatePV succeeded for volume %s", util.GetPersistentVolumeClaimQualifiedName(pvc))
```suggestion
			klog.InfoS("ExpandVolume.UpdatePV succeeded for volume",  "volume", util.GetPersistentVolumeClaimQualifiedName(pvc))
```

2021-05-06 12:33 UTC, yangjunmyfm192085 commented
/lgtm
/ok-to-test
/triage accepted

2021-05-07 02:21 UTC, yangjunmyfm192085 commented
/lgtm

2021-05-07 05:27 UTC, yangjunmyfm192085 commented
/lgtm

2021-05-26 02:50 UTC, yangjunmyfm192085 commented
/test pull-kubernetes-node-e2e-containerd

2021-05-26 02:52 UTC, yangjunmyfm192085 commented
/assign jingxu97

2021-05-27 15:56 UTC, shubheksha requested changes
Minor comments around clarity and consistency of key names and a question for a few error messages. Thank you for submitting this!

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_executor.go
> +				klog.ErrorS(fmt.Errorf("VerifyVolumesAreAttached: nil spec for volume %s", volumeAttached.VolumeName), "")
Why are we not passing the volume name as an argument of `klog.ErrorS` directly?

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_executor.go
> +					"volume", volumeAttached.VolumeName,
```suggestion
					"volumeName", volumeAttached.VolumeName,
```

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_executor.go
> +					"node", volumeAttached.NodeName)
```suggestion
					"nodeName", volumeAttached.NodeName)
```

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_executor.go
> +					"node", volumeAttached.NodeName)
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_executor.go
> +				"node", node)
Is this the name?

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_executor.go
> +				"volumePlugin", pluginName)
```suggestion
				"volumePluginName", pluginName)
```

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_executor.go
> +				"volumePlugin", pluginName)
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.ErrorS(fmt.Errorf("VerifyVolumesAreAttached.GenerateVolumesAreAttachedFunc: nil spec for volume %s", volumeAttached.VolumeName), "")
Same here - why are we not passing the argument directly?

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.ErrorS(volumeAttached.GenerateErrorDetailed("VolumesAreAttached.FindPluginBySpec failed", err), "")
Same question here

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +					"volumePlugin", pluginName)
```suggestion
					"volumePluginName", pluginName)
```

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +					"volumePlugin", pluginName)
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +					"node", nodeName)
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +						"node", nodeName)
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +				"volumePlugin", pluginName)
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +				"volumePlugin", attachableVolumePlugin.GetPluginName())
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.ErrorS(fmt.Errorf("BulkVerifyVolume failed to type assert attacher %q", bulkVolumeVerifier), "")
Same question as above here

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +						"volume", volumeSpec.Name())
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +						"volume", volumeSpec.Name())
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +					"volume", volumeToAttach.VolumeName)
Here too

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.InfoS("ExpandVolume succeeded", "volume", util.GetPersistentVolumeClaimQualifiedName(pvc))
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.InfoS("ExpandVolume.UpdatePV succeeded", "volume", util.GetPersistentVolumeClaimQualifiedName(pvc))
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			klog.V(4).InfoS("Controller resizing done", "pvc", util.GetPersistentVolumeClaimQualifiedName(pvc))
Same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		klog.V(4).InfoS("Resizing is not enabled", "volume", volumeToMount.VolumeName)
same as above

2021-05-27 15:56 UTC, shubheksha commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		klog.V(3).InfoS("The path isn't device path or doesn't exist. Skip checking device", "path", deviceToDetach.DevicePath)
```suggestion
		klog.V(3).InfoS("The path isn't device path or doesn't exist. Skip checking device", "devicePath", deviceToDetach.DevicePath)
```

2021-05-27 15:56 UTC, shubheksha commented
/lgtm cancel

2021-05-28 06:02 UTC, sanwishe commented
/test pull-kubernetes-integration

2021-05-28 08:22 UTC, sanwishe commented
/test pull-kubernetes-e2e-gce-storage-snapshot

2021-05-31 05:10 UTC, sanwishe commented
/retest

2021-06-03 05:30 UTC, yangjunmyfm192085 commented
/wg structured-logging
/retest
/lgtm

2021-07-26 09:29 UTC, njuptlzf requested changes
There should be `missing`?  `GenerateMsg` returns two parameters.

2021-07-26 09:29 UTC, njuptlzf commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		klog.InfoS(deviceToDetach.GenerateMsg("UnmountDevice succeeded", ""))
```suggestion
		klog.InfoS(deviceToDetach.GenerateMsgDetailed("UnmountDevice succeeded", ""))
```

2021-08-19 15:37 UTC, shubheksha commented
@sanwishe would you be able to take a look at this and rebase please?

2021-12-17 19:18 UTC, jingxu97 commented
@sanwishe sorry for the delay. Will you continue to work on this PR?

2022-01-13 06:18 UTC, yangjunmyfm192085 reviewed
/ping @sanwishe

2022-01-13 06:20 UTC, yangjunmyfm192085 reviewed
Let's rebase this PR, thanks.

2022-01-13 06:32 UTC, sanwishe commented
> Let's rebase this PR, thanks.

sorry  for the  delay， i will rebase it.

2022-01-20 11:04 UTC, yangjunmyfm192085 reviewed
//remove-lifecycle rotten

2022-01-20 11:06 UTC, yangjunmyfm192085 commented
/remove-lifecycle rotten

2022-01-21 03:13 UTC, yangjunmyfm192085 reviewed
/lgtm

2022-01-21 03:14 UTC, yangjunmyfm192085 commented
/cc @jingxu97, could you take a look?

2022-01-21 03:29 UTC, sanwishe commented
/test pull-kubernetes-unit

2022-01-21 03:39 UTC, sanwishe commented
/test pull-kubernetes-conformance-kind-ga-only-parallel

2022-01-21 09:51 UTC, sanwishe commented
/test pull-kubernetes-unit

2022-01-22 15:48 UTC, yangjunmyfm192085 reviewed
/lgtm

2022-07-11 05:38 UTC, yangjunmyfm192085 reviewed
/cc @sanwishe

2022-07-11 05:38 UTC, yangjunmyfm192085 reviewed
Maybe we need rebase this pr.

2022-08-10 06:01 UTC, closed without merging