Migrate pkg/controller/volume/persistentvolume/testing/testing.go to structured logging
kubernetes/kubernetes pull request #101828
Opened 2021-05-08 07:02 UTC by CaoDonghui123

#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
Structured Logging migration:
pkg/controller/volume/persistentvolume/testing/testing.go
xref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
#### Which issue(s) this PR fixes:

part of kubernetes/enhancements#1602

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-05-13 10:09 UTC, CaoDonghui123 commented
/ok-to-test

2021-05-13 13:53 UTC, CaoDonghui123 commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-05-27 15:42 UTC, shubheksha commented
/wg structured-logging
/triage accepted
/priority backlog

2021-05-27 15:45 UTC, shubheksha requested changes
Could you replace "name" with `volumeName` and `claimName` across the PR for greater clarity please? Thank you!

2021-05-27 15:45 UTC, shubheksha commented on pkg/controller/volume/persistentvolume/testing/testing.go
> +		klog.V(4).InfoS("Created volume", "name", volume.Name)
```suggestion
		klog.V(4).InfoS("Created volume", "volumeName", volume.Name)
```

2021-05-27 15:45 UTC, shubheksha commented on pkg/controller/volume/persistentvolume/testing/testing.go
> +		klog.V(4).InfoS("Created claim", "name", claim.Name)
```suggestion
		klog.V(4).InfoS("Created claim", "claimName", claim.Name)
```

2021-05-27 15:45 UTC, shubheksha commented on pkg/controller/volume/persistentvolume/testing/testing.go
> +				klog.V(4).InfoS("Nothing updated volume", "name", volume.Name)
```suggestion
				klog.V(4).InfoS("Nothing updated volume", "volumeName", volume.Name)
```

2021-05-27 15:45 UTC, shubheksha commented on pkg/controller/volume/persistentvolume/testing/testing.go
> +		klog.V(4).InfoS("Saved updated volume", "name", volume.Name)
Same as above

2021-05-27 15:45 UTC, shubheksha commented
/wg structured-logging
/triage accepted
/priority backlog

2021-06-03 05:39 UTC, yangjunmyfm192085 commented
duplicated with 
https://github.com/kubernetes/kubernetes/pull/100831
/wg structured-logging

2021-10-31 07:06 UTC, closed without merging