Migrate pkg/proxy/ipvs/ipset.go logs to structured logging
kubernetes/kubernetes pull request #102031
Opened 2021-05-15 11:41 UTC by Nick-Triller

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

xref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-05-27 15:34 UTC, shubheksha commented
/wg structured-logging
/triage accepted
/priority backlog

2021-05-27 15:39 UTC, shubheksha requested changes

2021-05-27 15:39 UTC, shubheksha commented on pkg/proxy/ipvs/ipset.go
> +		klog.ErrorS(err, "Invalid version string vstring", "version", vstring)
```suggestion
		klog.ErrorS(err, "Invalid version string", "version", vstring)
```

2021-05-27 15:39 UTC, shubheksha commented on pkg/proxy/ipvs/ipset.go
> +		klog.ErrorS(err, "Invalid version string MinCheckVersion", "version", MinIPSetCheckVersion)
```suggestion
		klog.ErrorS(err, "Invalid version string", "minIPSetCheckVersion", MinIPSetCheckVersion)
```

2021-05-27 15:39 UTC, shubheksha commented on pkg/proxy/ipvs/ipset.go
> +				klog.InfoS("Truncated ipset name", "ipsetNameOld", name, "ipsetNameNew", name[:31])
for consistency with the rest of the file
```suggestion
				klog.InfoS("Truncated ip set name", "ipsetNameOld", name, "ipsetNameNew", name[:31])
```

2021-05-28 09:58 UTC, Nick-Triller commented
Hi @shubheksha, thanks for your suggestions. I applied all of them and rebased on master.

2021-06-03 05:51 UTC, yangjunmyfm192085 commented
/wg structured-logging

2021-10-01 06:52 UTC, Nick-Triller commented
/remove-lifecycle rotten

2021-10-14 16:58 UTC, shivanshu1333 commented
Closing as some of the logs are not properly migrated and https://github.com/kubernetes/kubernetes/pull/104932#issuecomment-917808512 got merged which covers migration of this file.
/close

2021-10-14 16:58 UTC, closed without merging