Structured Logging migration: for rest part of package cmd/kube-controller-manager
kubernetes/kubernetes pull request #102173
Opened 2021-05-20 11:57 UTC by sanwishe

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Structured Logging migration: for rest part of package cmd/kube-controller-manager
migration list:
cmd/kube-controller-manager/app/certificates.go
cmd/kube-controller-manager/app/cloudproviders.go
cmd/kube-controller-manager/app/controllermanager.go
cmd/kube-controller-manager/app/core.go
cmd/kube-controller-manager/app/plugins.go
cmd/kube-controller-manager/app/plugins_providers.go
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
ACTION REQUIRED: Exit code changed from 255 to 1
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-05-20 20:11 UTC, fedebongio commented
/assign @cici37 
/triage accepted

2021-05-20 20:17 UTC, cici37 commented
/ok-to-test

2021-05-21 18:48 UTC, cici37 commented on cmd/kube-controller-manager/app/certificates.go
> +		klog.InfoS("Resource is not available now", "resourceName", gvr.String())
minor: Would you consider to use resource as the key since it not only contains resourceName?

2021-05-21 18:49 UTC, cici37 commented on cmd/kube-controller-manager/app/certificates.go
> +		klog.InfoS("Resource is not available now", "resourceName", gvr.String())
Same as above

2021-05-21 18:49 UTC, cici37 commented on cmd/kube-controller-manager/app/controllermanager.go
> +			klog.InfoS("Controller is disabled", "name", controllerName)
Maybe use controllerName?

2021-05-21 18:50 UTC, cici37 commented on cmd/kube-controller-manager/app/controllermanager.go
> +		klog.V(1).InfoS("Starting controller", "name", controllerName)
controllerName?

2021-05-21 18:50 UTC, cici37 commented on cmd/kube-controller-manager/app/controllermanager.go
> +			klog.ErrorS(err, "Error starting controller", "name", controllerName)
same here

2021-05-21 18:50 UTC, cici37 commented on cmd/kube-controller-manager/app/controllermanager.go
> +			klog.InfoS("Skipping controller", "name", controllerName)
same

2021-05-21 18:50 UTC, cici37 commented on cmd/kube-controller-manager/app/controllermanager.go
> +		klog.InfoS("Started controller", "name", controllerName)
same as above

2021-05-21 18:51 UTC, cici37 commented on cmd/kube-controller-manager/app/controllermanager.go
> +		klog.InfoS("Controller is disabled", "name", saTokenControllerName)
Suggest: `klog.InfoS("saTokenController is disabled", "saTokenControllerName", saTokenControllerName)`

2021-05-21 18:52 UTC, cici37 commented on cmd/kube-controller-manager/app/controllermanager.go
> +		klog.InfoS("Controller is disabled because there is no private key", "name", saTokenControllerName)
same here

2021-05-21 18:53 UTC, cici37 commented on cmd/kube-controller-manager/app/core.go
> +		klog.InfoS("Will not configure cloud provider routes for allocate-node-cidrs, configure-cloud-routes", "nodeCIDR", ctx.ComponentConfig.KubeCloudShared.AllocateNodeCIDRs, "configureCloudRoutes", ctx
Maybe use allocateNodeCIDR instead of nodeCIDR as the key to be more specific

2021-05-21 18:53 UTC, cici37 commented on cmd/kube-controller-manager/app/core.go
> +		klog.InfoS("Configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.")
Since configure-cloud-routes is a flag, we could skip using camel case here

2021-05-21 18:54 UTC, cici37 commented on cmd/kube-controller-manager/app/core.go
> +		klog.InfoS("Configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.")
I would suggest to use configure-cloud-routes directly since it is a flag

2021-05-21 18:55 UTC, cici37 commented on cmd/kube-controller-manager/app/plugins.go
> +		klog.ErrorS(err, "Could not create hostpath recycler pod from file", "path", config.PersistentVolumeRecyclerConfiguration.PodTemplateFilePathHostPath)
Maybe use hostPath instead of path?

2021-05-22 09:43 UTC, sanwishe commented
@cici37  Thanks for you review, suggestion applied.

2021-05-23 05:48 UTC, sanwishe commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-05-23 05:48 UTC, sanwishe commented
/test pull-kubernetes-unit

2021-05-24 02:21 UTC, yangjunmyfm192085 commented
/retest

2021-05-24 03:23 UTC, yangjunmyfm192085 commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-05-24 04:55 UTC, yangjunmyfm192085 commented
/retest

2021-05-24 06:21 UTC, sanwishe commented
@cici37 @fedebongio Ready for review, would you please take a look? thanks very much.

2021-05-26 01:55 UTC, yangjunmyfm192085 commented
/lgtm

2021-05-26 03:01 UTC, yangjunmyfm192085 commented
/assign lavalamp

2021-05-27 15:21 UTC, shubheksha commented
/wg-structured-logging

2021-05-27 15:23 UTC, shubheksha commented
/wg structured-logging

2021-05-27 15:33 UTC, shubheksha requested changes
Minor change to remove periods from the end of error messages to ensure consistency

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/core.go
> +		klog.InfoS("configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.")
Could you remove the periods from error messages as per the [migration guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#remove-string-formatting-from-log-message)?
```suggestion
		klog.InfoS("configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes")
```

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/core.go
> +		klog.InfoS("configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.")
Here as well

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/controllermanager.go
> +					klog.InfoS("Leader migration: starting migrated controllers.")
Here too

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/controllermanager.go
> +					klog.InfoS("Leader migration: starting main controllers.")
Here as well

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/certificates.go
> +		klog.V(2).InfoS("Skipping CSR signer controller because specific files were specified for other signers and not this one.", "controllerName", "kubernetes.io/legacy-unknown")
And here

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/certificates.go
> +		klog.V(2).InfoS("Skipping CSR signer controller because specific files were specified for other signers and not this one.", "controllerName", "kubernetes.io/kube-apiserver-client")
Here too

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/certificates.go
> +		klog.V(2).InfoS("Skipping CSR signer controller because specific files were specified for other signers and not this one.", "controllerName", "kubernetes.io/kube-apiserver-client-kubelet")
Here as well

2021-05-27 15:33 UTC, shubheksha commented on cmd/kube-controller-manager/app/certificates.go
> +		klog.V(2).InfoS("Skipping CSR signer controller because specific files were specified for other signers and not this one.", "controllerName", "kubernetes.io/kubelet-serving")
Same as others

2021-05-27 15:33 UTC, shubheksha commented
/lgtm cancel

2021-05-28 01:57 UTC, sanwishe commented
/test pull-kubernetes-unit

2021-05-31 05:12 UTC, sanwishe commented
> /lgtm cancel

suggestion applied, thanks. could you please take a look?

2021-06-03 05:54 UTC, yangjunmyfm192085 commented
/wg structured-logging

2021-09-21 20:45 UTC, cici37 commented
Hi @sanwishe , do you still plan to work on it? Thanks

2021-11-20 21:38 UTC, closed without merging