Disable k/k way of log dumping if test-infra way is enabled
kubernetes/kubernetes pull request #102337
Opened 2021-05-26 12:09 UTC by tosi3k

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Do not invoke k/k log dumping script if the test job already leverages the log dumping mechanism from test-infra repo.

#### Which issue(s) this PR fixes:
No issue is opened for that.

#### Special notes for your reviewer:
/assign @jkaniuk
/assign @marseel 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-05-26 12:11 UTC, tosi3k commented
/sig scalability
/cc @YangLu1031 

Relevant Slack discussion: https://kubernetes.slack.com/archives/C09QZTRH7/p1621986566037600.

2021-05-26 13:24 UTC, marseel commented
/lgtm
/retest

2021-05-26 14:23 UTC, tosi3k commented
/retest

2021-05-26 15:25 UTC, tosi3k commented
/retest

2021-05-26 23:32 UTC, YangLu1031 commented
/lgtm
/retest

2021-05-27 15:00 UTC, jkaniuk commented
/lgtm

2021-06-08 23:40 UTC, pjh commented
@spiffxp perhaps you could review and approve this with your sig-testing-approvers power?

Please see the Slack discussion that Antoni shared, https://kubernetes.slack.com/archives/C09QZTRH7/p1621986566037600.

2021-06-08 23:40 UTC, pjh commented
/priority important-soon

2021-06-09 18:46 UTC, spiffxp requested changes

2021-06-09 18:46 UTC, spiffxp commented on test/e2e/framework/util.go
> +	if TestContext.DisableLogDump || os.Getenv("USE_TEST_INFRA_LOG_DUMPING") == "true" {
I would rather not tangle in test-infra concerns.  Can your script/job not add `--disable-log-dump`?

2021-06-23 00:32 UTC, pjh commented
/close

We submitted https://github.com/kubernetes-sigs/windows-testing/pull/271 so that this is not needed for our test jobs (Windows-on-GCE).

I don't know if other test jobs will need similar changes. If something is being deprecated, we should provide accurate and complete instructions for migrating to the new thing. @tosi3k please address https://github.com/kubernetes/kubernetes/issues/96915#issuecomment-866428399, thanks.

2021-06-23 00:32 UTC, closed without merging