fix 'y' to true when YAML decode to JSON
kubernetes/kubernetes pull request #102445
Opened 2021-05-31 06:02 UTC by CaoDonghui123

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #102308

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-05-31 06:19 UTC, wzshiming requested changes

2021-05-31 06:19 UTC, wzshiming commented on staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go
> +		err := yaml3.Unmarshal(bytes, into)
Patch this piece of logic separately and introduce new dependencies. I don't think this is a good modification.

2021-06-01 20:13 UTC, fedebongio commented
/assign @roycaihw 
/cc @lavalamp @liggitt since there is a version bump of yaml decoder
/triage accepted

2021-06-01 20:30 UTC, lavalamp commented
One does not simply increase the version of the yaml library... 😱 

This appears to have broken many unit tests. Ideally we can fix the bug with a much more lightweight tweak.

2021-06-01 20:45 UTC, roycaihw commented
```
$ kubectl apply -f crd.yaml -v=9
...
Request Body: {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apiextensions.k8s.io/v1\",\"kind\":\"CustomResourceDefinition\",\"metadata\":{\"annotations\":{},\"name\":\"tests.calci.io\"},\"spec\":{\"group\":\"calci.io\",\"names\":{\"kind\":\"Test\",\"plural\":\"tests\",\"shortNames\":[\"tt\"],\"singular\":\"test\"},\"scope\":\"Namespaced\",\"versions\":[{\"name\":\"v1\",\"schema\":{\"openAPIV3Schema\":{\"properties\":{\"spec\":{\"properties\":{\"operation\":{\"enum\":[\"ADD\",\"SUB\",\"DIV\",\"MUL\"],\"type\":\"string\"},\"true\":{\"type\":\"number\"},\"x\":{\"type\":\"number\"}},\"type\":\"object\"}},\"type\":\"object\"}},\"served\":true,\"storage\":true}]}}\n"},"name":"tests.calci.io"},"spec":{"group":"calci.io","names":{"kind":"Test","plural":"tests","shortNames":["tt"],"singular":"test"},"scope":"Namespaced","versions":[{"name":"v1","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"operation":{"enum":["ADD","SUB","DIV","MUL"],"type":"string"},"true":{"type":"number"},"x":{"type":"number"}},"type":"object"}},"type":"object"}},"served":true,"storage":true}]}}
```
so far it looks like the problem happened in kubectl when sending the request. Could you look into fixing kubectl instead?

2021-06-01 20:46 UTC, BenTheElder commented
there's also: https://github.com/kubernetes/kubernetes/issues/78946 which is a bit broader.

2021-06-01 21:59 UTC, liggitt commented on staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go
> +		err := yaml3.Unmarshal(bytes, into)
`sigs.k8s.io/yaml` uses json tags in structs for marshaling/unmarshaling, and does mechanical yaml-json conversion

`gopkg.in/yaml.v3` expects `yaml` struct tags, which none of our API types have, so this switch will not work at all for API types.

2021-06-01 22:25 UTC, roycaihw reviewed
the fundamental issue is https://github.com/kubernetes/kubernetes/issues/34146. It's unclear if someone will eventually pick it up

2021-06-01 22:25 UTC, roycaihw commented on staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go
> -		err := yaml.Unmarshal(bytes, into)
this is `sigs.k8s.io/yaml`. Kubernetes depends on the features that `sigs.k8s.io/yaml` implements on top of `go-yaml`. We cannot simply change `sigs.k8s.io/yaml` to `go-yaml` v3.

Please consider moving forward the `go-yaml` v3 conversation in `sigs.k8s.io/yaml`. Some background:
- https://github.com/kubernetes-sigs/yaml/issues/18
- https://github.com/kubernetes-sigs/yaml/pull/26

/close

2021-06-01 22:26 UTC, closed without merging