[WIP] feature: add unified on CRI to support cgroup v2
kubernetes/kubernetes pull request #102578
Opened 2021-06-04 03:02 UTC by payall4u

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This CRI update is intended to support more cgroupv2 capabilities.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

- [KEP]: [Support memory qos with cgroups v2](https://github.com/kubernetes/enhancements/pull/2571)

2021-06-04 03:18 UTC, pacoxu commented
/cc xiaoxubeii 
https://github.com/kubernetes/enhancements/issues/2570

2021-06-04 03:26 UTC, payall4u commented
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

@k8s-ci-robot ping

2021-06-04 06:42 UTC, pacoxu commented
Should `staging/src/k8s.io/api/core/v1/generated.proto` be updated as well?

2021-06-04 06:50 UTC, payall4u commented
> Should `staging/src/k8s.io/api/core/v1/generated.proto` be updated as well?

We needn't update it now, I think.

2021-06-04 08:14 UTC, xiaoxubeii commented
/ok-to-test

2021-06-15 01:41 UTC, xiaoxubeii commented
/lgtm
/cc mrunalp ping for review.

2021-06-15 06:17 UTC, AkihiroSuda commented on staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
> +    map<string, string> unified = 9;
Could you clarify the string format

2021-06-15 07:36 UTC, payall4u commented on staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
> +    map<string, string> unified = 9;
Done

2021-06-15 07:36 UTC, payall4u commented on staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
> +    map<string, string> unified = 9;
> Could you clarify the string format

Done

2021-06-16 00:30 UTC, ehashman reviewed
/triage accepted
/priority important-soon

Are there e2e tests for this? Won't this need a release note?

2021-06-17 06:45 UTC, payall4u commented
> Won't this need a release note?

Sorry. I had just finished it.

> Are there e2e tests for this? 

I think there is no such e2e test for cri before. We can add the test with [Support memory qos with cgroups v2](https://github.com/kubernetes/enhancements/pull/2571) together.

2021-06-17 07:43 UTC, xiaoxubeii commented
/lgtm

2021-06-17 07:43 UTC, xiaoxubeii approved these changes

2021-06-21 08:26 UTC, payall4u commented
ping @AkihiroSuda @mrunalp

2021-06-21 16:51 UTC, ehashman commented
Note: there is a conflicting CRI protobuf change in https://github.com/kubernetes/kubernetes/pull/102823/files#diff-7a3c2723dedc6b44cf183fc52f84cc4015ffbd65a998a65c3959a953cb63c945

2021-06-21 22:04 UTC, mrunalp requested changes
Could you also add it to the v1/api.proto file?

2021-06-22 02:23 UTC, payall4u commented
> Could you also add it to the v1/api.proto file?

Done.

2021-06-22 08:44 UTC, xiaoxubeii commented
/retest

2021-06-22 11:39 UTC, xiaoxubeii commented
/lgtm

2021-06-22 15:15 UTC, mrunalp approved these changes

2021-06-22 16:37 UTC, xiaoxubeii commented
/retest

2021-06-22 16:40 UTC, xiaoxubeii commented
/retest

2021-06-22 16:43 UTC, xiaoxubeii commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-06-22 16:49 UTC, xiaoxubeii commented
/retest

2021-06-22 17:12 UTC, xiaoxubeii commented
/retest

2021-06-22 19:00 UTC, merged