Pass DeleteOptions down to the Reactor
kubernetes/kubernetes pull request #102945
Opened 2021-06-17 10:05 UTC by chenchun

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #102798

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
client-go: pass `DeleteOptions` down to the `Reactor`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-06-17 20:10 UTC, fedebongio commented
/assign @caesarxuchao 
/triage accepted

2021-09-27 16:13 UTC, enj commented
/assign

2021-09-27 20:37 UTC, enj requested changes

2021-09-27 20:37 UTC, enj commented on staging/src/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_type.go
> +		$else$Invokes($.NewRootDeleteAction|raw$($.type|allLowercasePlural$Resource, name, &opts), &$.type|raw${})$end$
This needs to pass in a `nil` when `opts` is the zero value of the struct.

2021-09-27 20:37 UTC, enj commented on staging/src/k8s.io/client-go/testing/actions.go
> +func NewRootDeleteAction(resource schema.GroupVersionResource, name string, opts *metav1.DeleteOptions) DeleteActionImpl {
Update `DeleteActionImpl` and `DeleteAction` to make it easier to get the options:

```go
type DeleteAction interface {
	Action
	GetName() string
	GetDeleteOptions() *metav1.DeleteOptions
}
```

2021-10-27 15:44 UTC, enj requested changes
Minor stuff.

2021-10-28 14:40 UTC, enj requested changes
Just some extraneous whitespace.

2021-11-01 12:13 UTC, liggitt reviewed
one nit on the uid used in the test, lgtm otherwise

2021-11-01 12:13 UTC, liggitt commented on pkg/controller/bootstrap/common_test.go
> +			UID:             "s1",
make the uid unique by incorporating tokenID (`"uid"+tokenID` or something similar)

2021-11-02 04:00 UTC, enj commented
/lgtm

2021-11-02 04:02 UTC, enj commented
/milestone v1.23
/priority important-longterm

2021-11-02 12:37 UTC, liggitt commented
/approve

2021-11-02 14:14 UTC, merged