add ratelimt for volume_stat_caculator to resovle performance bottleneck
kubernetes/kubernetes pull request #103729
Opened 2021-07-16 03:01 UTC by 249043822

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #103728

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-07-16 11:49 UTC, endocrimes commented
This isn't really a rate limiter (executions / time period), but a semaphore (bounding parallel calls). Rather than implementing one informally with blocking channels, you might want to consider using https://pkg.go.dev/golang.org/x/sync/semaphore instead.

2021-07-21 02:31 UTC, 249043822 commented
> This isn't really a rate limiter (executions / time period), but a semaphore (bounding parallel calls). Rather than implementing one informally with blocking channels, you might want to consider using https://pkg.go.dev/golang.org/x/sync/semaphore instead.
> 
> Thundering herd disk stats collection is kinda expensive, so introducing some bounding is probably a reasonable thing to do here (because there isn't really much we can do to make it significantly cheaper).

@endocrimes thanks, I have added semaphore

2021-07-21 07:30 UTC, 249043822 commented
/assign @tallclair @cheftako

2021-07-23 00:33 UTC, cheftako commented
Sorry couple of silly questions.

You've set the semaphores concurrent call limit to 100. Where did we get that value from? It wasn't clear to me from the original bug how many concurrent du instances you were dealing with. Looking at the issue 100 instances of du look like it will already be using 5-10 cores. Would it make sense for this value to be configurable?

The sync.Once is part of the fsResourceAnalyzer struct so new instance of that struct will have a seperate syncOnce and a separate semaphore. So if you have multiple fsResourceAnalyzer instances your actually concurrent call limit will be a multiple of 100.  

Also if we have multiple fsResourceAnalyzer we won't take advantage of cached values computed while we were blocked. Would it make sense to see if a some other instances have gotten a value while we were blocked?

2021-07-23 01:16 UTC, 249043822 commented
> Sorry couple of silly questions.
> 
> You've set the semaphores concurrent call limit to 100. Where did we get that value from? It wasn't clear to me from the original bug how many concurrent du instances you were dealing with. Looking at the issue 100 instances of du look like it will already be using 5-10 cores. Would it make sense for this value to be configurable?

Yea, making this value configurable may be greater. 100 is from what I have tested that restarting kubelet could be stable and the system loadaverage is within control.  Also the value  maybe arbitrary.  

> the original bug how many concurrent du instances you were dealing with
Actually I could not clearly caculate the num, because while restarting kubelet some time. the os system becomes down.  but the volume num is 1000 * 3 * 3

> The sync.Once is part of the fsResourceAnalyzer struct so new instance of that struct will have a seperate syncOnce and a separate semaphore. So if you have multiple fsResourceAnalyzer instances your actually concurrent call limit will be a multiple of 100.
> 
> Also if we have multiple fsResourceAnalyzer we won't take advantage of cached values computed while we were blocked. Would it make sense to see if a some other instances have gotten a value while we were blocked?

thanks, I didn't know the scene of multiple fsResourceAnalyzer. are multiple fsResourceAnalyzer stat the shared pod volumes all in the kubelet?

2021-07-27 00:01 UTC, tallclair commented
/assign @dashpole

2021-07-27 17:37 UTC, dashpole requested changes
We should be careful here, as this could cause disk stats to stop working correctly, even for users that don't have IO problems.  Also, the bug referenced in this PR describes an issue with `du` calls, which the kubelet doesn't make anymore.  Before we take this approach, we should verify that the problem still persists  after the change: #96115.

2021-07-27 17:37 UTC, dashpole commented on pkg/kubelet/server/stats/fs_resource_analyzer.go
> +// limit burst size
nit: comment should be of the form `// LimitSize ...`

2021-07-27 17:37 UTC, dashpole commented on pkg/kubelet/server/stats/volume_stat_calculator.go
> +	// refer issue #103728 for detail
Doesn't this bound more than just `du` calls, and apply to all volume types?

2021-07-28 00:32 UTC, 249043822 commented
> We should be careful here, as this could cause disk stats to stop working correctly, even for users that don't have IO problems. Also, the bug referenced in this PR describes an issue with `du` calls, which the kubelet doesn't make anymore. Before we take this approach, we should verify that the problem still persists after the change: #96115.

@dashpole I will merge #96115 into my branch and verify again,  thanks

2021-07-29 07:15 UTC, 249043822 commented
> > We should be careful here, as this could cause disk stats to stop working correctly, even for users that don't have IO problems. Also, the bug referenced in this PR describes an issue with `du` calls, which the kubelet doesn't make anymore. Before we take this approach, we should verify that the problem still persists after the change: #96115.
> 
> @dashpole I will merge #96115 into my branch and verify again, thanks

 #96115 can resolve this problem, thanks @dashpole

2021-07-29 07:15 UTC, closed without merging