Update generic_scheduler.go
kubernetes/kubernetes pull request #104072
Opened 2021-08-02 07:57 UTC by wxuedong

What type of PR is this?

/kind bug
/sig scheduling
/release-note-none

What this PR does / why we need it:

An exception occurs when the filter is used to extend the service, and the entire scheduling process fails.

I think this design is not reasonable.

So I think if the schedule filter expansion fails, the default filter nodes should be returned.

2021-08-02 08:00 UTC, wxuedong commented
do-not-merge/release-note-label-needed

2021-08-02 13:01 UTC, cndoit18 requested changes

2021-08-02 13:01 UTC, cndoit18 commented on pkg/scheduler/core/generic_scheduler.go
> +	                        return filtered, failedPredicateMap, filteredNodesStatuses, nil
No offense, I think this should return an error

2021-08-05 17:53 UTC, ahg-g commented
/close

2021-08-05 17:53 UTC, closed without merging