Set default namespace in Event.Regarding if namespace is empty
kubernetes/kubernetes pull request #104395
Opened 2021-08-16 13:13 UTC by chenyw1990

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kube-apisever will rejected event when regarding.Namespace is empty

#### Which issue(s) this PR fixes:

Fixes #104394

#### Special notes for your reviewer:
@thockin @Yuan-Junliang

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-08-16 13:14 UTC, chenyw1990 commented
/sig network

2021-08-16 13:17 UTC, dashpole commented
Would you mind adding a unit test?

2021-08-16 22:55 UTC, aojea commented
seems a duplicate of https://github.com/kubernetes/kubernetes/pull/100125

2021-08-17 20:15 UTC, fedebongio commented
/assign @wojtek-t 
since seems to be very related to #100125. Thank you!
/triage accepted

2021-08-19 19:39 UTC, khenidak requested changes

2021-08-19 19:39 UTC, khenidak commented on staging/src/k8s.io/client-go/tools/events/event_recorder.go
> +	regarding := refRegarding.DeepCopy()
You don't need to `DeepCopy()` here.

2021-08-20 05:40 UTC, thockin commented
How do we end up here with no Namespace set?  That seems like a failing somewhere else in the stack.

2021-08-21 20:33 UTC, jayaddison commented
If it might help to track this down: I've got a local Kubernetes v1.21 cluster which -- after upgrade to Kubernetes v1.22 -- fails to initialize due to this empty/unset namespace issue (reproducible on each of two attempts to upgrade followed by rollback to v1.21).  If there are any debugging steps or configuration settings to check that'd help with investigation, let me know and I'll take a look.

2021-08-21 21:17 UTC, jayaddison commented
Sorry -- I think I got my wires crossed due to an unrelated cluster networking issue that I was debugging in the same cluster.

To clarify: this issue does _not_ prevent `kube-proxy` pods from reaching the 'ready' state, but the following error message does appear in their pod logs:

```
event_broadcaster.go:253] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"<hostname>.<hex>", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, EventTime:v1.MicroTime{Time:time.Time{wall:0xc0407900813cb44b, ext:89927907, loc:(*time.Location)(0x2d81340)}}, Series:(*v1.EventSeries)(nil), ReportingController:"kube-proxy", ReportingInstance:"kube-proxy-<hostname>", Action:"StartKubeProxy", Reason:"Starting", Regarding:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"<hostname>", UID:"<hostname>", APIVersion:"", ResourceVersion:"", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"", Type:"Normal", DeprecatedSource:v1.EventSource{Component:"", Host:""}, DeprecatedFirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedLastTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedCount:0}': 'Event "<hostname>.<hex>" is invalid: involvedObject.namespace: Invalid value: "": does not match event.namespace' (will not retry!)
```

Glad to investigate further if that'll help, and/or mark my comments as off-topic if they're a distraction.

2021-08-23 10:42 UTC, wojtek-t commented
Yes - it's basically a duplicate of https://github.com/kubernetes/kubernetes/pull/100125

I dropped that one on the floor - sorry for that.

Given that one already have tests, let's proceed with that one [it should be backported once merged].

Closing in favor of https://github.com/kubernetes/kubernetes/pull/100125

2021-08-23 10:42 UTC, closed without merging