Add UID to client-go impersonation config
kubernetes/kubernetes pull request #104483
Opened 2021-08-20 17:52 UTC by margocrawf

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Introduces Impersonate-UID to client-go. My previous PR introduced the `Impersonate-UID` header, this PR makes it possible to specify the UID in your impersonation config on the client side in order to pass the `Impersonate-UID` header along with a request.

* Updates ImpersonationConfig in rest/config.go to include UID
  attribute, and pass it through when copying the config
* Updates ImpersonationConfig in transport/config.go to include UID
  attribute
* In transport/round_tripper.go, Set the "Impersonate-Uid" header in
  requests based on the UID value in the config
* Update auth_test.go integration test to specify a UID through the new
  rest.ImpersonationConfig field rather than manually setting the
  Impersonate-Uid header

#### Which issue(s) this PR fixes:

This is another piece of addressing #93699. It is a follow up to #99961. 

#### Does this PR introduce a user-facing change?

```release-note
client-go impersonation config can specify a UID to pass impersonated uid information through in requests.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-08-24 20:06 UTC, caesarxuchao commented
/assign @deads2k 
/triage accepted

2021-09-01 01:01 UTC, enj commented
/ok-to-test
/assign
/priority important-longterm
/milestone v1.23

2021-09-01 01:10 UTC, enj requested changes
Basically the same comment a bunch of times about field ordering to match the rest of the codebase.

2021-09-01 01:10 UTC, enj commented on staging/src/k8s.io/client-go/rest/config.go
> +	UID string
Put this under `UserName` to be consistent with other places in the codebase.

2021-09-01 01:10 UTC, enj commented on staging/src/k8s.io/client-go/rest/config.go
> +			UID:      config.Impersonate.UID,
nit: please sort these fields in the order they appear in the struct (after addressing the first comment).

2021-09-01 01:10 UTC, enj commented on staging/src/k8s.io/client-go/rest/transport.go
> +			UID:      c.Impersonate.UID,
Same comment, move under username.

2021-09-01 01:10 UTC, enj commented on staging/src/k8s.io/client-go/transport/config.go
> +	UID string
Same comment, move under username.

2021-09-01 01:10 UTC, enj commented on staging/src/k8s.io/client-go/transport/round_trippers.go
> +	}
nit: move in-between the username and group logic above.

2021-09-01 01:10 UTC, enj commented on staging/src/k8s.io/client-go/transport/round_trippers.go
> +		len(config.Impersonate.UID) > 0 {
Check this after checking username.

2021-09-07 13:32 UTC, deads2k commented
after Mo's comments, this looks plausible to me.  Ping me on slack once updated.

2021-09-14 14:03 UTC, deads2k commented
/lgtm
/approve

2021-09-15 20:52 UTC, margocrawf commented
/assign @smarterclayton

2021-09-24 21:08 UTC, enj commented
/lgtm

2021-09-24 21:10 UTC, enj commented
/uncc johnSchnake krousey

2021-09-27 13:23 UTC, smarterclayton commented
/approve

2021-09-27 14:33 UTC, merged