add integration tests for cronjob with controllerv2
kubernetes/kubernetes pull request #104570
Opened 2021-08-25 06:22 UTC by RyanAoh

#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:
CronJobControllerV2 is GA in 1.22. But There are no integration tests for it.

#### Which issue(s) this PR fixes:
Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

2021-08-25 12:27 UTC, neolit123 reviewed
Try asking for a reviewer in the #sig-apps channel of k8s slack.

2021-08-25 12:27 UTC, neolit123 commented on test/integration/cronjob/cronjob_controllerv2_test.go
> +Copyright 2018 The Kubernetes Authors.
New files should be current year

2021-08-25 12:27 UTC, neolit123 commented
/sig apps

2021-08-30 09:55 UTC, pacoxu commented
/ok-to-test
/cc mengjiao-liu

2021-08-31 02:50 UTC, RyanAoh commented
/cc @janetkuo @krmayankk PTAL.

2021-08-31 08:12 UTC, mengjiao-liu commented
The test code looks fine, but `CronJobControllerV2 ` has reached GA and according to this KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/19-Graduate-CronJob-to-Stable#release-122 , the old controller needs to be cleaned up.

Does the cronjob integration test code still need to keep the old controller? Can we just switch parts of the integration test code from the old controller to the new CronJobControllerV2 controller? @soltysh

2021-08-31 11:40 UTC, soltysh commented
> Does the cronjob integration test code still need to keep the old controller? Can we just switch parts of the integration test code from the old controller to the new CronJobControllerV2 controller? @soltysh

Yeah, it doesn't make sense to add additional controller. We rather need to switch the existing test to use the new controller instead.

2021-08-31 11:40 UTC, soltysh requested changes
/assign

2021-08-31 13:25 UTC, RyanAoh commented
Updated. I switched the existing test to use the new controller. 
PTAL. @soltysh

2021-08-31 15:13 UTC, RyanAoh commented
/retest

2021-09-02 13:13 UTC, soltysh approved these changes
/lgtm
/approve

2021-09-02 13:13 UTC, soltysh commented
/triage accept
/priority backlog

2021-09-02 14:42 UTC, merged