remove RuntimeClass feaeture GA
kubernetes/kubernetes pull request #105228
Opened 2021-09-24 08:37 UTC by AlpherJang

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

remove RuntimeClass feature GA

#### Special notes for your reviewer:

For my first contribute, i tried to clean some feature gate in kube_features.go, and i found that RuntimeClass has been promoted to GA, but it still exist in kube_features.go. So i cleaned it and fix some description about RuntimeClass with feature word. The file link is: https://github.com/kubernetes/kubernetes/blob/7bff8adaf683dc7e25b5548e2c16e7393ff8a036/pkg/features/kube_features.go#L186

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-09-24 09:11 UTC, AlpherJang commented
/assign @liggitt

2021-09-24 11:24 UTC, pacoxu commented
#95718
/sig node
/cc @SergeyKanzhelev

2021-09-26 08:57 UTC, pacoxu commented
It seems to be duplicated with #103061.

2021-09-27 17:34 UTC, ehashman requested changes
/ok-to-test
/priority backlog
/triage accepted
/label api-review
/assign

https://github.com/kubernetes/api/blob/7036ead253974a37c7aca010f305593a486a253e/core/v1/types.go#L3148

This comment needs to be updated.

2021-09-28 01:30 UTC, AlpherJang commented
/approve

2021-09-28 01:31 UTC, AlpherJang commented
/retest

2021-09-28 11:04 UTC, AlpherJang commented
> It seems to be duplicated with #103061.

yep，by diff two pr i found it's seam change

2021-09-28 11:06 UTC, closed without merging