move iptables from pkg/util to component-helpers, and remove unused pkg/util/ipconfig
kubernetes/kubernetes pull request #105378
Opened 2021-09-30 15:36 UTC by AartiJivrajani

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Removes the pkg/util/ipconfig module as discussed in issue #92369.
This PR also moves the `pkg/util/iptables` module to `k8s.io/component-base/network`
#### Which issue(s) this PR fixes:

Fixes #92369 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-09-30 15:37 UTC, MadhavJivrajani commented
/ok-to-test
/release-note-none
/sig network
/kind cleanup

2021-09-30 17:43 UTC, spiffxp commented
/test pull-kubernetes-node-e2e-containerd
ref: #105381

2021-10-04 13:41 UTC, rikatz commented on pkg/kubelet/kubelet_network.go
> +	v1 "k8s.io/api/core/v1"
vscode linter usually adds this v1, would suggest to remove it and keep as the old entry

2021-10-04 13:42 UTC, rikatz commented on pkg/util/iptablesbkp/testing/fake.go
>  	"strings"
Let's remove this "iptablesbkp" folder

2021-10-04 13:45 UTC, rikatz commented on staging/src/k8s.io/component-helpers/network/utils/iptables/OWNERS
> +# See the OWNERS docs at https://go.k8s.io/owners
This file can be a copy of https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/OWNERS instead (actually it's better to copy it, and we end by using the proper aliases)

2021-10-04 13:48 UTC, rikatz commented
/retitle WIP: move iptables from pkg/util to component-helpers, and remove unused pkg/util/ipconfig

2021-10-27 13:07 UTC, rikatz requested changes
Some minor changes, otherwise lgtm:

* OWNERS file can be consolidated in staging/src/k8s.io/component-helpers/network/OWNERS 
* Please remove the WIP and Draft status as soon as this is ready to review, so the CI can run.

Thanks!

2022-01-14 13:35 UTC, dims commented
/close

2022-01-14 13:37 UTC, dims commented
please reopen if you still need this WIP PR. Trying to declutter the open PR(s)

2022-01-14 13:39 UTC, closed without merging