Wire contexts to Apps controllers
kubernetes/kubernetes pull request #105377
Opened 2021-09-30 15:04 UTC by damemi

#### What type of PR is this?
/kind design

#### What this PR does / why we need it:
This wires a context to Apps controllers in kube-controller-manager, so that KCM can eventually release on cancel.

This originally came from PR https://github.com/kubernetes/kubernetes/pull/101379, which builds on top of https://github.com/kubernetes/kubernetes/pull/101125

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-09-30 15:34 UTC, soltysh requested changes
I found still a few `context.TODO()` instances I've listed above.

/assign
/triage accepted
/priority backlog

2021-09-30 15:34 UTC, soltysh commented on pkg/controller/daemon/daemon_controller.go
>  	burstReplicas int
there are still a few `context.TODO` in pkg/controller/daemon/update.go and in this file too

2021-09-30 15:34 UTC, soltysh commented on pkg/controller/deployment/deployment_controller.go
> +	syncHandler func(ctx context.Context, dKey string) error
still a few `context.TODO` in the following files:
pkg/controller/deployment/progress.go
pkg/controller/deployment/util/deployment_util.go
pkg/controller/deployment/rollback.go
pkg/controller/deployment/sync.go

2021-09-30 15:34 UTC, soltysh commented on pkg/controller/statefulset/stateful_set.go
>  }
a few more in:
pkg/controller/statefulset/stateful_set_status_updater.go
pkg/controller/statefulset/stateful_pod_control.go

2021-09-30 17:40 UTC, spiffxp commented
/test pull-kubernetes-node-e2e-containerd
ref: #105381

2021-09-30 21:18 UTC, damemi commented
/retest

2021-10-01 12:25 UTC, damemi commented
/retest
Sorry for all the test failure spam, I had some trouble finding all of the missing updates locally.

2021-10-07 08:55 UTC, soltysh approved these changes
A few more nits, but we can handle them in a followups.
/lgtm
/approve

2021-10-07 18:57 UTC, alculquicondor commented
Uhm.. kind of tricky, as batch is under sig-apps, but it's listed separately. Maybe you can say core apps (the core API). But it's a nit.

2021-10-11 10:19 UTC, nikhita commented
/kind feature
/remove-kind design

We are removing the `kind/design` label. Please see https://github.com/kubernetes/community/issues/5641 for more details.

2021-10-12 12:08 UTC, soltysh requested changes

2021-10-13 18:51 UTC, soltysh requested changes
One more nit about `adopt` function in `pkg/controller/controller_ref_manager.go` and what about that `wait.UntilWithContext` in `pkg/controller/daemon/daemon_controller.go`

2021-10-14 12:46 UTC, soltysh approved these changes
/lgtm
/approve

2021-10-14 13:59 UTC, merged