Fixed using reference in for loop
kubernetes/kubernetes pull request #105459
Opened 2021-10-04 16:27 UTC by shivanshu1333

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Current code incorrectly uses for loop and passes wrong value as reference
Guide to refer https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/105426

#### Special notes for your reviewer:
Please refer to sample code to understand the bug https://goplay.space/#TIT_IZEAEud

```
package main

import "fmt"

type st struct {
	it []string
}

func main() {
	rp := &st{[]string{"value1", "value2"}}
	ownedReplicaSets1 := make([]*string, 0, len(rp.it))
	ownedReplicaSets2 := make([]*string, 0, len(rp.it))

	// similar to current implementation
	for _, t := range rp.it {
		ownedReplicaSets1 = append(ownedReplicaSets1, &t)
	}

	fmt.Println(ownedReplicaSets1)
	fmt.Println(*ownedReplicaSets1[0], *ownedReplicaSets1[1])

	// similar new change
	for i := range rp.it {
		ownedReplicaSets2 = append(ownedReplicaSets2, &rp.it[i])
	}

	fmt.Println(ownedReplicaSets2)
	fmt.Println(*ownedReplicaSets2[0], *ownedReplicaSets2[1])
}
```

```
output:
value2 value2
[0xc000054020 0xc000054030]
value1 value2
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-10-04 17:41 UTC, shivanshu1333 commented
/retest

2021-10-17 00:43 UTC, shivanshu1333 commented
/retest-required

2021-10-17 01:15 UTC, shivanshu1333 commented
/retest

2021-11-06 17:23 UTC, shivanshu1333 commented
ping @pohly

2021-11-06 18:15 UTC, shivanshu1333 commented
/retest

2021-11-08 08:40 UTC, pohly requested changes

2021-11-08 08:40 UTC, pohly commented on test/e2e/autoscaling/cluster_size_autoscaling.go
> +			err = makeNodeUnschedulable(f.ClientSet, &nodes.Items[i])
You can drop this change.

2021-11-08 08:40 UTC, pohly commented on test/e2e/autoscaling/cluster_size_autoscaling.go
> +		err := makeNodeUnschedulable(f.ClientSet, &nodes[i])
You can drop this change.

2021-11-08 08:40 UTC, pohly commented on test/e2e/autoscaling/cluster_size_autoscaling.go
> +		err = makeNodeSchedulable(f.ClientSet, &nodes[i], false)
You can drop this change.

2021-11-08 08:40 UTC, pohly commented on test/e2e/autoscaling/cluster_size_autoscaling.go
> +		err = makeNodeUnschedulable(f.ClientSet, &nodes[i])
You can drop this change.

2021-11-12 11:54 UTC, shivanshu1333 commented
ping @pohly for approval

2021-11-12 14:44 UTC, pohly approved these changes
/lgtm
/retest

2021-11-12 15:39 UTC, pohly commented
/assign @bskiba

For approval as suggested by bot.

2021-11-12 21:21 UTC, aojea commented
/approve

2021-11-13 00:15 UTC, shivanshu1333 commented
/retest

2021-11-13 01:36 UTC, merged