Wire contexts to Autoscaling controllers
kubernetes/kubernetes pull request #105461
Opened 2021-10-04 16:45 UTC by damemi

#### What type of PR is this?
/kind design

#### What this PR does / why we need it:
This wires a context to Autoscaling controllers in kube-controller-manager, so that KCM can eventually release on cancel.

This originally came from PR https://github.com/kubernetes/kubernetes/pull/101379, which builds on top of https://github.com/kubernetes/kubernetes/pull/101125

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-10-04 18:57 UTC, damemi commented
/retest

2021-10-04 19:32 UTC, damemi commented on pkg/controller/podautoscaler/horizontal_test.go
> +	go hpaController.Run(context.TODO())
I think the failure is related to this, it seems to be panicking on the calls related to here:

```
E1004 19:10:12.992779   52130 runtime.go:76] Observed a panic: Fail in goroutine after TestUpscaleCap has completed
...
created by k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).Run
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:177 +0x4bc
```

which is a call to `wait.UntilWithContext`, so maybe `context.TODO()` doesn't work for that? Or I just be using the same context for this and the stop channel

2021-10-05 20:16 UTC, fedebongio commented
/remove-sig api-machinery

2021-10-07 10:53 UTC, soltysh reviewed
This mostly looks good, although you have one leftover in https://github.com/kubernetes/kubernetes/blob/79ee735badfe457136ee0da51f3783628898a137/pkg/controller/podautoscaler/metrics/client.go#L68
and the unit failure looks legit too

2021-10-12 17:33 UTC, soltysh requested changes

2021-10-12 19:34 UTC, soltysh approved these changes
/triage accepted
/priority backlog
/lgtm
/approve

2021-10-14 12:55 UTC, sttts commented
/approve

2021-10-14 13:59 UTC, merged