Wire contexts to Batch controllers
kubernetes/kubernetes pull request #105491
Opened 2021-10-05 17:33 UTC by damemi

#### What type of PR is this?
/kind design

#### What this PR does / why we need it:
This wires a context to Batch controllers in kube-controller-manager, so that KCM can eventually release on cancel.

This originally came from PR https://github.com/kubernetes/kubernetes/pull/101379, which builds on top of https://github.com/kubernetes/kubernetes/pull/101125

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-10-05 20:20 UTC, fedebongio commented
/remove-sig api-machinery

2021-10-05 21:30 UTC, damemi reviewed
/cc @soltysh 
test failure was a known flake

2021-10-07 11:00 UTC, soltysh requested changes

2021-11-09 20:20 UTC, damemi commented
/retest

2021-11-10 12:17 UTC, soltysh approved these changes
/lgtm
/approve
/label tide/merge-method-squash

2021-11-10 12:18 UTC, soltysh commented
/test pull-kubernetes-unit

2021-11-10 12:18 UTC, soltysh commented
/priority backlog

2021-11-10 12:19 UTC, sttts commented on cmd/kube-controller-manager/app/batch.go
> +
nit: empty lines at the top are evil

2021-11-10 12:22 UTC, sttts commented
/approve

2021-11-10 12:24 UTC, soltysh commented
/hold cancel

2021-11-10 22:56 UTC, merged