Allow the e2e_node runner to receive a KubeletConfiguration rather than requiring flags
kubernetes/kubernetes pull request #105575
Opened 2021-10-08 13:00 UTC by endocrimes

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

This PR is one of the pre-requisites to removing dynamickubeletconfiguration - Currently the e2e_node suite only allowed the Kubelet to be configured using flags, which does not expose all config options, and makes providing per-job configuration relatively difficult.

It introduces the ability to provide a `KubeletConfiguration` file that will be used to source configuration for the tests. This allows us to customize the kubelet across various jobs as things are required for different tests, rather than any test requiring new configuration to update the config at runtime.

#### Which issue(s) this PR fixes:

Related to: #105047 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-10-08 13:29 UTC, endocrimes commented
/test pull-kubernetes-node-e2e-kubetest2

2021-10-11 11:58 UTC, endocrimes commented
/test pull-kubernetes-node-kubelet-serial

2021-10-11 18:54 UTC, endocrimes commented
Something seems to have broken GPU tests ~a week ago (need to investigate, assuming it's an image change). Other failures look like flakes unrelated to this PR

2021-10-12 13:24 UTC, matthyx reviewed
/lgtm

2021-10-14 05:27 UTC, SergeyKanzhelev commented
/priority important-soon
/triage accepted

2021-10-19 23:17 UTC, ehashman requested changes

2021-10-22 05:01 UTC, matthyx approved these changes
/lgtm
great!

2021-11-02 14:31 UTC, endocrimes commented
@ehashman rebased, PTAL

2021-11-02 15:10 UTC, endocrimes commented
/retest-required

2021-11-02 20:36 UTC, SergeyKanzhelev approved these changes

2021-11-02 20:40 UTC, SergeyKanzhelev commented
/assign @spiffxp

Can you please approve for hack and give any other feedback.

2021-11-02 22:33 UTC, spiffxp approved these changes
/approve
/lgtm

2021-11-02 22:33 UTC, spiffxp commented on test/e2e_node/services/kubelet.go
> +	flag.Var(&kubeletArgs, "kubelet-flags", "Kubelet flags passed to kubelet, this will override default kubelet flags in the test. Flags specified in multiple kubelet-flags will be concatenate. Depreca
Historically test binary flags aren't considered an API that adheres to kubernetes' version support policy so I'm OK with abrupt changes

2021-11-02 22:33 UTC, spiffxp commented on hack/make-rules/test-e2e-node.sh
> +kubelet_config_file=${KUBELET_CONFIG_FILE:-"test/e2e_node/jenkins/default-kubelet-config.yaml"}
I forget how much of cluster/ and kube-up.sh this relies on... I could see a case being made that it should move closer to e.g. `config-test.sh`. But I'm also fine with following historical precedent, I know the jenkins dir is basically where (some) node e2e CI config lives (kubernetes/test-infra/jobs/e2e_node being the other historical oddity)

2021-11-02 22:33 UTC, spiffxp commented on test/e2e_node/services/kubelet.go
> +	// --read-only-port
oof

what would it take for the tests not to rely on this? I guess it's always been this way but it feels like a gap we should have a followup issue to close?

2021-11-03 01:00 UTC, merged