Add error handling for Write() function
kubernetes/kubernetes pull request #105995
Opened 2021-10-29 03:55 UTC by NoicFank

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
add error handler when Write() method encounter errors.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

2021-11-03 13:19 UTC, NoicFank commented
@ehashman @vishh PTAL thanks.

2021-11-03 20:16 UTC, wgahnagl commented
/triage accepted
/priority backlog

2021-11-04 22:22 UTC, ehashman requested changes
/ok-to-test

2021-11-04 22:22 UTC, ehashman commented on pkg/kubelet/prober/prober.go
> +			klog.Errorf("Should write %d bytes but only write %d bytes: %v", len(data), p, err)
Please use `ErrorS`.

```suggestion
			klog.ErrorS(err, "Unable to write all bytes from execInContainer", "expectedBytes", len(data), "actualBytes", p)
```

2021-11-05 02:21 UTC, NoicFank commented on pkg/kubelet/prober/prober.go
> +			klog.Errorf("Should write %d bytes but only write %d bytes: %v", len(data), p, err)
ok, done.

2021-11-07 11:04 UTC, NoicFank commented
@ehashman PTAL thanks.

2021-12-02 06:05 UTC, NoicFank commented
@vishh @ehashman please take a look, thanks.

2022-01-05 15:06 UTC, dims commented
/assign @mrunalp @derekwaynecarr 

NOTE: just 3 lines, quick review!

2022-01-11 03:50 UTC, NoicFank commented
@ehashman @vishh please review the code, appreciate for your time.

2022-01-17 13:04 UTC, NoicFank commented
@tallclair please review the code and push it forward, thaks.

2022-04-22 17:51 UTC, tallclair commented
/lgtm
/approve

2022-05-04 00:18 UTC, merged