Replace ioutil with os and io for the test
kubernetes/kubernetes pull request #106015
Opened 2021-10-29 23:09 UTC by ahrtr

The ioutil package has already been deprecated in golang 1.16, please see [go1.16#ioutil](https://golang.org/doc/go1.16#ioutil). So we need to replace all the ioutil with os and io.

This PR is just to update the test. There will be a couple of separate PRs for another SIGs. 

Previously there is a [PR](https://github.com/kubernetes/kubernetes/pull/105994), which is huge. So I am splitting the huge PR into a couple of smaller PRs. This PR is just one of them.

2021-11-02 20:08 UTC, fedebongio commented
/remove-sig api-machinery

2021-11-02 22:46 UTC, spiffxp commented
/ok-to-test

2021-11-03 05:51 UTC, SergeyKanzhelev commented
Tests are not particularly affected by this comment: https://github.com/kubernetes/kubernetes/issues/100367#issuecomment-802591356 so it is probably all right to switch.

/priority backlog
/triage accepted

The PR is huge so already has merge conflicts. Some synchronization will be needed between getting approvals first, then rebasing and lgtm right away.

/approve

for node

2021-11-03 06:13 UTC, ahrtr commented
> Tests are not particularly affected by this comment: [#100367 (comment)](https://github.com/kubernetes/kubernetes/issues/100367#issuecomment-802591356) so it is probably all right to switch.
> 
> /priority backlog /triage accepted
> 
> The PR is huge so already has merge conflicts. Some synchronization will be needed between getting approvals first, then rebasing and lgtm right away.
> 
> /approve
> 
> for node

Thanks for the comment. Rebasing done!

2021-11-03 21:53 UTC, spiffxp commented
/kind cleanup
/release-note-none

2021-11-03 22:04 UTC, spiffxp requested changes
I would suggest removing the test/images/** changes from this PR and doing those in another PR with the VERSION bumps I've asked for. The rest of this LGTM, though I agree its size makes this PR prone to getting stuck in rebases

2021-11-03 22:04 UTC, spiffxp commented on test/images/apparmor-loader/loader.go
> +		infos, err := os.ReadDir(dir)
same thing, you need to update `test/images/apparmor-loader/VERSION`

2021-11-03 22:04 UTC, spiffxp commented on test/images/metadata-concealment/check_metadata_concealment.go
> +	body, err := io.ReadAll(resp.Body)
same thing, you need to update `test/images/metadata-concealment/VERSION`

2021-11-03 22:04 UTC, spiffxp commented on test/images/pets/peer-finder/peer-finder.go
> +	out, err := io.ReadAll(stdout)
same thing, you need to update `test/images/peer-finder/VERSION`

2021-11-04 01:48 UTC, ahrtr commented
> I would suggest removing the test/images/** changes from this PR and doing those in another PR with the VERSION bumps I've asked for. The rest of this LGTM, though I agree its size makes this PR prone to getting stuck in rebases

Thanks for the comment. Removed all changes in test/images/*, and rebased the PR.

2021-11-15 05:00 UTC, ahrtr commented
Rebased.

2021-11-15 05:48 UTC, ahrtr commented
> I would suggest removing the test/images/** changes from this PR and doing those in another PR with the VERSION bumps I've asked for. The rest of this LGTM, though I agree its size makes this PR prone to getting stuck in rebases

@spiffxp  Just submitted a separate PR [pull/106415](https://github.com/kubernetes/kubernetes/pull/106415 )

2021-11-18 17:43 UTC, ehashman commented
/remove-sig instrumentation

2021-11-18 17:44 UTC, ehashman reviewed
/approve

for 
test/e2e/instrumentation/monitoring/stackdriver_metadata_agent.go
test/instrumentation/main.go

2021-11-18 17:51 UTC, marosset commented
/remove-sig windows
Ping me or add sig-windows back if there are any concerns specific to Windows.

2022-01-04 23:26 UTC, dims commented
/retest
/assign

2022-01-06 19:52 UTC, ahrtr commented
> @ahrtr: PR needs rebase.

Just rebased.

2022-01-27 17:20 UTC, marosset commented
/remove-sig windows

2022-02-02 13:48 UTC, dims commented
/assign @MadhavJivrajani 

can you please review this Madhav? same as the last one. should be mostly mechanical changes

2022-02-02 15:15 UTC, MadhavJivrajani requested changes
Assuming changes to `images/` are in a seperate PR, there are a few more instances to cover:

- test/e2e_node/kubeletconfig/kubeletconfig.go
- test/e2e_node/device_manager_test.go
- test/integration/apiserver/openapiv3_test.go
- test/integration/auth/podsecurity_test.go

Please also recheck in any other similar PRs that you may have opened, thanks!

2022-02-02 21:34 UTC, ahrtr commented
> Assuming changes to `images/` are in a seperate PR, there are a few more instances to cover:
> 
>     * test/e2e_node/kubeletconfig/kubeletconfig.go
> 
>     * test/e2e_node/device_manager_test.go
> 
>     * test/integration/apiserver/openapiv3_test.go
> 
>     * test/integration/auth/podsecurity_test.go
> 
> 
> Please also recheck in any other similar PRs that you may have opened, thanks!

Thanks @MadhavJivrajani , just rebased this PR and resolved your comment. PTAL, thanks.

2022-02-02 23:43 UTC, ahrtr commented
/retest

2022-02-03 05:21 UTC, MadhavJivrajani commented
/retest

2022-02-03 05:24 UTC, MadhavJivrajani approved these changes
LGTM
Thanks!
This is good to go @dims :)

2022-02-03 11:24 UTC, dims commented
/skip
/approve
/lgtm

2022-02-03 12:31 UTC, merged