Replace the deprecated io/ioutil with os and io for cmd
kubernetes/kubernetes pull request #106062
Opened 2021-11-02 00:56 UTC by ahrtr

The ioutil package has already been deprecated in golang 1.16, please see [go1.16#ioutil](https://golang.org/doc/go1.16#ioutil). So we need to replace all the io/ioutil with os and io.

This PR is just to update the cmd. There will be a couple of separate PRs for another SIGs.

2021-11-02 17:37 UTC, neolit123 commented
the changes for /cmd/kubeadm SGTM, as long as the project agrees on the change.

2021-11-02 20:14 UTC, fedebongio commented
/remove-sig api-machinery

2021-11-04 02:38 UTC, kerthcet commented
/ok-to-test

2021-11-04 20:06 UTC, fedebongio commented
/remove-sig api-machinery

2021-11-08 06:55 UTC, pacoxu commented
/kind cleanup
/release-note-none

2021-11-08 11:06 UTC, kerthcet commented
the whole changes can be classified by:
```
- b, err := ioutil.ReadFile(args[0])
+ b, err := os.ReadFile(args[0])

- ioutil.Discard
+ io.Discard

- ioutil.ReadFile(path)
+ os.ReadFile(path)

- ioutil.WriteFile(filename, []byte(processedMarkDown), 0644)
+ os.WriteFile(filename, []byte(processedMarkDown), 0644)

- ioutil.TempDir("", "kube-controller-manager")
+ os.MkdirTemp("", "kube-controller-manager")

- ioutil.TempFile(os.TempDir(), "kubeadm-external-etcd-test-cafile")
+ os.CreateTemp(os.TempDir(), "kubeadm-external-etcd-test-cafile")

- ioutil.ReadAll(response.Body)
+ io.ReadAll(response.Body)
```

no logic or parameters changed at all.

2021-11-10 18:55 UTC, wgahnagl commented
/triage accepted 
/priority important-longterm

2021-11-10 19:01 UTC, wgahnagl reviewed
for node
cmd/kubelet/app/server_bootstrap_test.go lgtm :ok_hand: :tada:

2021-11-18 00:27 UTC, ahrtr commented
Rebased.

2022-01-04 23:24 UTC, dims commented
/retest
/assign

2022-01-12 06:15 UTC, ahrtr commented
Just rebased again.

2022-01-19 08:49 UTC, RA489 commented
/test pull-kubernetes-conformance-kind-ga-only-parallel

2022-01-31 19:59 UTC, dims commented
/assign @MadhavJivrajani 

@MadhavJivrajani can you please review this and ping me back?

2022-02-01 05:38 UTC, MadhavJivrajani requested changes
@ahrtr can you please replace instances of `ioutil` that were recently added (present in your branch due to rebase):
- https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade.go (added in https://github.com/kubernetes/kubernetes/pull/107295)
- https://github.com/kubernetes/kubernetes/blob/master/cmd/yamlfmt/yamlfmt.go (added in https://github.com/kubernetes/kubernetes/pull/106458)

2022-02-01 06:01 UTC, ahrtr commented
> @ahrtr can you please replace instances of `ioutil` that were recently added (present in your branch due to rebase):
> 
>     * https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade.go (added in #107295)
> 
>     * https://github.com/kubernetes/kubernetes/blob/master/cmd/yamlfmt/yamlfmt.go (added in #106458)

@MadhavJivrajani  Thanks for the comment, just rebased this PR and resolved your comment.  PTAL, thanks.

2022-02-01 09:58 UTC, MadhavJivrajani approved these changes
LGTM
Thanks!
I think this is good to go @dims :)

2022-02-01 13:51 UTC, dims commented
/approve
/lgtm

/area code-organization

2022-02-01 15:42 UTC, MadhavJivrajani commented
/retest

2022-02-01 19:35 UTC, merged