fix test for CheckpointStateRestore
kubernetes/kubernetes pull request #106244
Opened 2021-11-09 03:36 UTC by cncal

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fix `TestCheckpointStateRestore` test by comparing `expectedError` with the `err` returned by `NewCheckpointState` function.

2021-11-09 05:44 UTC, cncal commented
/retest

2021-11-09 05:59 UTC, cncal commented
CLA signed.

2021-11-10 18:32 UTC, wgahnagl commented
/ok-to-test

2021-11-10 18:33 UTC, wgahnagl commented
make sure you've signed the CLA and that your commits are correctly formatted, and we'll take a look! :ok_hand:

2022-01-04 19:11 UTC, dims commented
@cncal looks like the CLA check is failing.

2022-01-10 17:14 UTC, dims commented
This PR needs a CLA to make progress, please see comments above from the CLA bot(s)

2022-01-14 17:17 UTC, dims commented
There is a cncf-cla:no label on this PR. Can you please see the bot comments above to fix the CLA? This PR cannot progress unless the bot is happy with the CLA situation

2022-01-21 05:35 UTC, cncal commented
/retest-required

2022-04-05 14:29 UTC, endocrimes requested changes

2022-04-05 14:29 UTC, endocrimes commented on pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go
> +				}
```suggestion
				require.NoError(t, err)
```

2022-04-05 14:29 UTC, endocrimes commented on pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go
> +				}
```suggestion
				require.Error(t, err)
```

2022-04-05 14:29 UTC, endocrimes commented on pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go
>  				}
```suggestion
				require.Contains(t, err.Error(), "could not restore state from checkpoint")
				require.Contains(t, err.Error(), tc.expectedError)
```

2022-04-05 14:29 UTC, endocrimes commented
/release-note-none

2022-05-31 12:48 UTC, endocrimes approved these changes
/lgtm

2022-05-31 12:49 UTC, endocrimes commented
/triage accepted
/priority backlog

2022-07-29 18:52 UTC, mrunalp approved these changes

2022-07-29 22:41 UTC, merged