Delete unnecessary judgments for deploymentController
kubernetes/kubernetes pull request #106208
Opened 2021-11-07 14:58 UTC by mysunshine92

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-11-07 15:00 UTC, mysunshine92 commented
/triage accepted

2021-11-08 01:31 UTC, mysunshine92 commented
/test pull-kubernetes-integration

2021-11-10 01:37 UTC, mysunshine92 commented
/assign @janetkuo

2021-11-10 12:27 UTC, soltysh requested changes
/hold

2021-11-10 12:27 UTC, soltysh commented on pkg/controller/deployment/sync.go
> +		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration {
Why do you want to remove a condition that ensure we ignore replicasets which are already marked for deletion?

2022-01-14 13:51 UTC, dims commented
this PR has been on hold for about 2 weeks. Can you please see how to unblock this by reviewing comments etc? or please close this out (Trying to declutter our open list of PRs)

2022-03-29 11:06 UTC, soltysh commented
/close
haven't heard from the author

2022-03-29 11:06 UTC, closed without merging