Revert last-applied-configuration annotation during rollback
kubernetes/kubernetes pull request #106349
Opened 2021-11-11 11:56 UTC by mishamo

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Rollback ignores the `last-applied-config` annotation as per the issues below. When an update happens later, the merge can cause env vars that were intended for removal to persist. This can cause unwanted side effects, including production outages. 

#### Which issue(s) this PR fixes:
Fixes #77058, #94698

#### Special notes for your reviewer:
Looking for feedback as to why this approach may not be appropriate, otherwise happy to add more testing/documentation if it's an acceptable approach.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-11-11 12:37 UTC, mishamo commented
I signed it

2021-12-15 10:23 UTC, mishamo commented
Hi, possibly you mean this https://github.com/kubernetes/kubernetes/issues/94698#issuecomment-899160116? The comment you linked to discusses `kubernetes.io/change-cause`. 

I appreciate the difference between a `kubectl apply` and a `kubectl rollout` in that last-**applied**-configuration refers to something that was _applied_. I think that would be ok if it was only used for reference purposes. However, this annotation is used for 3 way merging during future applies, which means it effectively tracks the state of the last applied or rolled out config (rather than just applied). As such, I consider ignoring it during rollback to be a bug.

2022-01-05 22:49 UTC, dims commented
/assign @soltysh @KnVerey

2022-01-19 17:44 UTC, soltysh requested changes
/hold
we're discussing the approach in https://github.com/kubernetes/kubernetes/issues/94698 although the discussion leads towards not mixing declarative and imperative commands which leads to different outcomes

2022-02-11 15:29 UTC, dims commented
/ok-to-test

2022-07-11 17:10 UTC, closed without merging