Update to runc v 1.0.3
kubernetes/kubernetes pull request #106912
Opened 2021-12-09 13:33 UTC by Letme

#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Current version (1.0.2) of runc prevents Kubernetes from running on RaspberryPi4 with non-hugetlb compiled kernel (standard Raspbian Bullseye). There is a fix inside Runc 1.0.3 for `libct/cg/fs2: fix GetStats for unsupported hugetlb`  (https://github.com/opencontainers/runc/pull/3233), which needs to be delivered to all existing supported Kubernetes versions (I tested v1.21.4 1.21.7 1.22.4 and 1.23.0).

#### Which issue(s) this PR fixes:

Fixes #

https://github.com/opencontainers/runc/issues/3232

#### Special notes for your reviewer:

My first contribution, so I am not sure it is this simple.

#### Does this PR introduce a user-facing change?

```release-note
Fix libct/cg/fs2: fix GetStats for unsupported hugetlb error on Raspbian Bullseye
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-12-09 17:08 UTC, Letme commented
/check-cla

2021-12-10 04:36 UTC, pacoxu commented
/sig node
/ok-to-test

2021-12-10 05:32 UTC, pacoxu commented
You should run   `hack/lint-dependencies.sh` to check dependencies before update.

To pin dependency version, you should try something like below.
```
hack/pin-dependency.sh github.com/coredns/corefile-migration v1.0.13
hack/update-vendor.sh
```

2021-12-10 06:45 UTC, pacoxu commented
I did a quick example like https://github.com/kubernetes/kubernetes/compare/master...pacoxu:runc-v1.0.3?expand=1 that you can follow.

2021-12-10 08:02 UTC, Letme commented
Thanks for the commands - I indeed did it by hand initially. So now with your commands I have cb7ff96e08c and I also ran the lint-dependencies as suggested and that also passed.

2021-12-11 00:24 UTC, ehashman commented
/priority important-longterm
/triage accepted
/assign @kolyshkin

2021-12-13 14:10 UTC, liggitt commented
dep mechanics lgtm, will defer to node approver for review of the change itself

2021-12-13 16:50 UTC, dims commented
/assign @ehashman @SergeyKanzhelev

2021-12-13 20:59 UTC, kolyshkin requested changes
@Letme I think you need to squash the two commits. Having one commit change go.mod and the other go.sum does not make sense.

In general, we do `./hack/pin-dependency.sh <pkg> <version>` followed by `./hack/lint-dependencies.sh`, `./hack/vendor.sh` etc; for example, see my PRs where I update runc, I usually provide all the scripts I ran in the changelog message.

2021-12-13 21:01 UTC, kolyshkin commented
> In general, we do `./hack/pin-dependency.sh <pkg> <version>` followed by `./hack/lint-dependencies.sh`, `./hack/vendor.sh` etc; for example, see my PRs where I update runc, I usually provide all the scripts I ran in the changelog message.

For example, see commit eb5df869baafdf1f74e4514c68f2c67efeb800b7

2021-12-13 21:35 UTC, Letme commented
Squashed as per request into fadb36effb3

2021-12-13 22:39 UTC, Letme commented
/retest

2021-12-27 11:06 UTC, Letme commented
/ping on this... I would love to get it into update, so that I can get more nodes running.

2022-01-07 00:23 UTC, dims commented
@SergeyKanzhelev did you get a chance to peek?

2022-01-12 00:48 UTC, SergeyKanzhelev commented
Reviewed the release notes, looks good for master. I'm not sure about the cherry-picks though.

/lgtm
/assign @mrunalp

2022-01-12 00:49 UTC, SergeyKanzhelev commented
> /kind regression

@Letme do you know what version the issue was introduced in?

2022-01-12 01:33 UTC, kolyshkin approved these changes
/lgtm

2022-01-12 07:47 UTC, Letme commented
@SergeyKanzhelev no, but I tested on all currently supported versions (v1.21.4 1.21.7 1.22.4 and 1.23.0) and it was there in all. So I would expect this to get cherry-picked for those versions.

2022-01-12 14:38 UTC, liggitt commented
/approve
for dep update

/hold for @mrunalp ack if desired

I'm also unsure about the picks, especially to <= 1.21, since that was still on pre-1.0 runc RCs

2022-01-19 01:57 UTC, mrunalp commented
/lgtm
/cancel hold

2022-01-19 01:57 UTC, mrunalp commented
/hold cancel

2022-01-19 07:37 UTC, pacoxu commented
/skip

2022-01-19 07:55 UTC, Letme commented
/retest

2022-01-19 09:11 UTC, Letme commented
/test pull-kubernetes-integration

2022-01-19 09:28 UTC, merged

2022-01-22 12:00 UTC, Letme commented
I am a bit puzzled why this was not added to recent 1.23.2 release. Can someone explain? It would fix and existing bug in all the currently supported versions on RaspberryPi's

2022-02-11 20:16 UTC, Letme commented
/milestone v1.22
/milestone v1.23