Fix a panic when using invalid output format in kubectl create secret command
kubernetes/kubernetes pull request #107221
Opened 2021-12-26 00:29 UTC by rikatz

/kind bug

#### What this PR does / why we need it:
Fixes a panic caused in `kubectl create secret`command due to the lack of returning an error when the selected printer is invalid

#### Which issue(s) this PR fixes:
Fixes: https://github.com/kubernetes/kubectl/issues/1159

```release-note
Fix a panic when using invalid output format in kubectl create secret command
```

2021-12-26 00:30 UTC, rikatz commented
/sig cli
/triage accepted
/priority important-soon

2021-12-26 00:31 UTC, rikatz commented
/assign @eddiezane @lauchokyip @soltysh 

Merry christmas 🎄  🎅  🤶 

Should we cherry pick this as it gets merged? :D

2021-12-26 00:42 UTC, lauchokyip requested changes
there are additional lines that is returning `nil` too
Check https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/staging/src/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go#L156-L165

2021-12-26 00:43 UTC, lauchokyip commented
Related to this 
https://github.com/kubernetes/kubernetes/pull/106317

2021-12-26 00:44 UTC, lauchokyip commented
> /assign @eddiezane @lauchokyip @soltysh
> 
> Merry christmas christmas_tree santa mrs_claus
> 
> Should we cherry pick this as it gets merged? :D

Yup , I did the same thing over this PR https://github.com/kubernetes/kubernetes/pull/106317

2021-12-26 00:48 UTC, rikatz commented
> there are additional lines that is returning `nil` too Check
> 
> https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/staging/src/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go#L156-L165

good catch, fixed. Also I did some additional check in create commands to see if we are returning nil instead of err in places we shouldn't and couldn't find right now

2021-12-26 00:54 UTC, lauchokyip commented
/lgtm

2021-12-27 15:19 UTC, rikatz commented
/retest

2022-01-05 15:47 UTC, rikatz commented
/retest

2022-01-05 16:15 UTC, eddiezane commented
Thank you!

> Should we cherry pick this as it gets merged? :D

Looks like back to 1.21

/approve

2022-01-05 18:26 UTC, soltysh reviewed
Good catch, thx!

2022-01-05 18:34 UTC, merged