Allow greater or equal in storage provisioning check
kubernetes/kubernetes pull request #107408
Opened 2022-01-07 15:11 UTC by awels

Signed-off-by: Alexander Wels <awels@redhat.com>

#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:
The current check enforces that a dynamic provisioner creates persistent volumes of capacity equals to the persistent volume
claim request size. However there are provisioners that will create persistent volumes with a capacity greater than the
request size (cinder comes to mind which increments in 1Gi increments, so if you request 0.5Gi, you get 1Gi). Also
provisioners that have shared storage should be reporting the total space not the request size (nfs/hostpath for instance).

All these will fail the provisioning check currently because the capacity is > than the request size. This modifies the check
to be capacity >= request size.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-01-07 15:16 UTC, awels commented
I signed it

2022-01-09 17:10 UTC, pohly approved these changes
/ok-to-test
/lgtm

2022-01-10 09:40 UTC, pacoxu commented
/hold
https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=107408
The pull-kubernetes-e2e-kind keeps failing. Would you take a look?

2022-01-10 10:54 UTC, pohly commented on test/e2e/storage/testsuites/provisioning.go
> +	gomega.Expect(pvCapacity.Value()).To(gomega.BeNumerically(">=", expectedCapacity.Value), "pvCapacity is not greater or equal to expectedCapacity")
```suggestion
	gomega.Expect(pvCapacity.Value()).To(gomega.BeNumerically(">=", expectedCapacity.Value()), "pvCapacity is not greater or equal to expectedCapacity")
```

2022-01-10 10:54 UTC, pohly commented on test/e2e/storage/testsuites/provisioning.go
> +	gomega.Expect(claimCapacity.Value()).To(gomega.BeNumerically(">=", requestedCapacity.Value), "claimCapacity is not greater or equal to requestedCapacity")
```suggestion
	gomega.Expect(claimCapacity.Value()).To(gomega.BeNumerically(">=", requestedCapacity.Value()), "claimCapacity is not greater or equal to requestedCapacity")
```

2022-01-10 10:55 UTC, pohly requested changes
Some brackets got lost... :sweat_smile:

2022-01-10 12:59 UTC, awels commented
Weird, it compiled for me locally.

2022-01-10 13:57 UTC, awels commented
So I just did a naive go build *file* but obviously that is not correct. If I make more changes to some of these tests. What would be the right command to compile it all properly so I don't have these silly brackets are missing failures.

2022-01-10 15:16 UTC, pohly approved these changes
/lgtm

2022-01-11 11:44 UTC, pohly commented
> So I just did a naive go build file but obviously that is not correct. If I make more changes to some of these tests. What would be the right command to compile it all properly so I don't have these silly brackets are missing failures.

The gomega parameters are untyped (`interface{}`), therefore compilation alone can't catch this. You would have to run the test (`go test -v ./test/e2e -args -ginkgo.focus=<test name>`).

/hold cancel

2022-01-11 16:33 UTC, merged