Ensure static certs in kubeconfig override exec plugin
kubernetes/kubernetes pull request #107410
Opened 2022-01-07 17:02 UTC by margocrawf

Check whether static cert is already configured in UpdateTransportConfig
- Also update test-cmd.sh to pass a signing ca to the kube controller
  manager, so CSRs work properly in integration tests.

fixed #99603

/kind bug

2022-01-07 17:20 UTC, enj commented
/triage accepted
/assign
/ok-to-test
/milestone v1.24
/priority important-longterm

2022-01-07 18:04 UTC, neolit123 commented
> This seems like unexpected behavior because other statically configured credentials (i.e., basic auth, bearer token) take precedent over the stuff returned by the exec plugin.

Dynamic (plugins) taking precedence over static config seems like the more intuative pattern to me. But i am not very familiar with area of the code and it seems that making this alternative switch now can be more breaking.

2022-03-02 14:50 UTC, enj requested changes

2022-03-02 14:50 UTC, enj commented on hack/testdata/auth/testcert.csr
> +-----BEGIN CERTIFICATE REQUEST-----
For all of these new testdata files, add:

1. A comment describing how they were generated 
2. A note saying that this is a test-only credential and that no security vulnerabilities should be reported in regards to them being published to a public repo

2022-03-02 14:50 UTC, enj commented on test/cmd/authentication.sh
> +  request: $(base64 < hack/testdata/auth/testcert.csr | tr -d '\n')
It is unclear what `testcert.csr` encodes.

2022-03-08 16:45 UTC, enj commented
/lgtm
/approve

2022-03-08 17:57 UTC, margocrawf commented
/retest

2022-03-08 19:34 UTC, merged