optimisation ipvs protocol to constants
kubernetes/kubernetes pull request #107587
Opened 2022-01-16 04:52 UTC by soulseen

the field of Protocol in ipvs VirtualServer should not use string type, also should not hard code it, and maybe use the v1.Protocol type is better.

2022-01-16 10:15 UTC, aojea commented
Why so many changes on the repo?

Is this really an optimization?

2022-01-16 16:24 UTC, soulseen commented
> Why so many changes on the repo?
> 
> Is this really an optimization?

because I updated the vendor dir, and lots of changes is in the vendor

2022-01-19 12:19 UTC, soulseen commented
@aojea @johnbelamaric please kindly take a review, thanks

2022-01-27 17:43 UTC, dgrisonnet commented
/remove-sig instrumentation

2022-02-03 19:22 UTC, khenidak commented
/kind cleanup

@andrewsykim @uablrek can you help and take a look at this one?

2022-02-03 20:00 UTC, uablrek commented on pkg/util/ipvs/ipvs.go
> +	return proto != v1.ProtocolUDP && proto != v1.ProtocolSCTP
IMO this simplification itself motivates the PR

2022-02-03 20:02 UTC, uablrek commented
/ok-to-test

2022-02-03 20:15 UTC, uablrek commented
@soulseen Please take a look at the failing tests

2022-02-06 15:08 UTC, soulseen commented
/retest

2022-02-06 15:08 UTC, soulseen commented
/retest-required

2022-02-07 14:40 UTC, soulseen commented
/retest-required

2022-02-07 14:47 UTC, soulseen commented
/test pull-kubernetes-integration

2022-02-08 02:43 UTC, soulseen commented
/test pull-kubernetes-integration

2022-02-08 06:52 UTC, soulseen commented
@uablrek hi, I updated the unit test about ipvs graceful terminition and the CI is passed, pls review it again, thanks a lot.

2022-02-22 06:55 UTC, soulseen commented
@uablrek Please take a look at this PR.

2022-02-22 07:16 UTC, uablrek approved these changes

2022-02-22 07:19 UTC, uablrek commented
You must update the PR header. There is a template that should be used. Always.

If you use the template the "release-note-label-needed" will be fixed.

2022-02-23 09:23 UTC, soulseen commented
fixed "release-note-label-needed", 
@logicalhan @johnbelamaric Please take a look, thanks.

2022-02-23 15:34 UTC, logicalhan reviewed
/lgtm

2022-02-24 03:25 UTC, soulseen commented
/assign @johnbelamaric

2022-03-07 06:58 UTC, soulseen commented
@johnbelamaric pls take a review, thanks.

2022-03-22 02:56 UTC, soulseen commented
/assign @andrewsykim

2022-06-09 14:36 UTC, danwinship requested changes

2022-06-09 14:36 UTC, danwinship commented on pkg/util/ipvs/ipvs.go
> +	return !strings.EqualFold(string(proto), string(v1.ProtocolUDP)) && !strings.EqualFold(string(proto), string(v1.ProtocolSCTP))
If you are going to use `v1.Protocol` then you should only match the actual `v1.Protocol` values. If you need to be case-insensitive, then you shouldn't use `v1.Protocol`.

2022-11-06 15:57 UTC, closed without merging