staging/publishing: update branch rules to reflect new Go versions 1.17.6 and 1.16.13
kubernetes/kubernetes pull request #107616
Opened 2022-01-18 09:17 UTC by palnabarun

#### What type of PR is this?

/kind cleanup
/area dependency

#### What this PR does / why we need it:

Update branch rules for the release-{1.21,1.22,1.23} to reflect new Go versions 1.17.6 and 1.16.13

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/release/issues/2379

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/assign @nikhita @dims @cpanato @justaugustus
cc: @kubernetes/release-engineering

2022-01-18 10:58 UTC, nikhita commented
lgtm, will tag when the PR is removed from the draft status

2022-01-18 14:25 UTC, dims commented
/approve

2022-01-18 16:38 UTC, palnabarun commented
/hold

2022-01-21 01:13 UTC, justaugustus requested changes
@palnabarun -- Needs a rebase:

```console
INFO Validating zeitgeist options...              
ERRO /home/prow/go/src/k8s.io/kubernetes/build/dependencies.yaml indicates that golang: upstream version should be at version 1.17.5, but the following files didn't match: staging/publishing/rules.yaml 
FATA Dependencies are not in sync
```

ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107616/pull-kubernetes-dependencies/1483478982576836608

2022-01-22 17:49 UTC, justaugustus commented
> @palnabarun -- Needs a rebase

Rebased this myself to push things along (since all of the go update PRs have merged).
/lgtm
/approve

2022-01-22 17:49 UTC, justaugustus commented
/hold cancel

2022-01-22 18:51 UTC, merged