e2e: improve formatting of failure messages
kubernetes/kubernetes pull request #107868
Opened 2022-01-30 16:49 UTC by justinsb

We format the output as json, and make the "unexpected count" messages consistent.

Before:

```
Jan 30 09:49:46.963: Expected endpoint in topology-hints-f5vs6 to have hints: {[100.109.32.103] {0xc0044e0c9e 0xc0044e0c9f 0xc0044e0ca0} <nil> &ObjectReference{Kind:Pod,Namespace:topology-hints-1629,Name:topology-serve-hostname-mkn8b,UID:450e8006-37a0-4853-bae3-3493fc6cd916,APIVersion:,ResourceVersion:50994,FieldPath:,} map[] 0xc00245ed70 0xc00245ed80 nil}
```

After:

```
  Jan 30 11:45:50.056: Expected endpoint in topology-hints-9p9hz to have exactly 1 zone hint, got 0: {"addresses":["100.96.1.7"],"conditions":{"ready":true,"serving":true,"terminating":false},"targetRef":{"kind":"Pod","namespace":"topology-hints-6706","name":"topology-serve-hostname-6gpbm","uid":"8695dcf2-8c81-4ed7-8e80-929928b9cf4e","resourceVersion":"23139"},"nodeName":"ip-172-20-88-192.us-east-2.compute.internal","zone":"us-east-2b"}
```

/kind failing-test
```release-note
NONE
```

Example of failing tests: https://testgrid.k8s.io/google-aws#kops-aws-misc-ha-euwest1

(Note _this_ PR does not address the underlying cause of the test failure)

2022-01-30 17:07 UTC, aojea commented
/assign @pohly 
It LGTM.
 @pohly was doing some cleanup and fixing formatting on those tests, he should be the best person to review

2022-01-30 21:46 UTC, justinsb commented
/retest

2022-01-31 11:38 UTC, pohly requested changes
Besides some nits I have a more fundamental question: the helper function isn't specific to e2e testing. Should we add it somewhere else? But where?

`k8s.io/component-base/logs` might be a candidate right now, longer term the `k8s.io/klogr` from https://github.com/kubernetes/enhancements/pull/3078.

2022-01-31 11:38 UTC, pohly commented on test/e2e/framework/format.go
> +// FormatJSON is a helper that prints the inner object in json format.
nit (no need to fix): s/json/JSON/

2022-01-31 11:38 UTC, pohly commented on test/e2e/framework/format.go
> +//  klog.Infof("object is %s", framework.FormatJSON(o))
The purpose becomes clearer when using a different example:
```suggestion
//  klog.V(5).Infof("object is %s", framework.FormatJSON(o))
```

2022-01-31 11:38 UTC, pohly commented on test/e2e/framework/format.go
> +// formatJSON is the helper type that defers json rendering until it is needed.
nit again: s/json/JSON/

2022-02-11 14:08 UTC, dims commented
@justinsb has a couple of nits, please take a look

2022-03-21 10:24 UTC, pohly commented
ping @justinsb

2022-03-21 19:08 UTC, pohly commented
`k8s.io/klogr` is not going to happen. We could add it to klog, but that has very strict API stability guarantees. This code doesn't need to meet those.

I suggest to move it to `k8s.io/component-base/logs`.

2022-03-23 13:10 UTC, pohly commented
One more idea: Endpoint, like all Kubernetes API types, has a String implementation that produces more readable output when used with %s instead of %v:
```
&Endpoint{Addresses:[],Conditions:EndpointConditions{Ready:nil,Serving:nil,Terminating:nil,},Hostname:nil,TargetRef:nil,DeprecatedTopology:map[string]string{},NodeName:*worker,Zone:*east-us,Hints:nil,}
```

Would that be a viable alternative here? Just be sure to pass a pointer, the String method is not usable when passing by value.

2022-06-21 13:37 UTC, pohly commented
/remove-lifecycle stale

2022-10-19 15:01 UTC, pohly commented
/remove-lifecycle stale

2022-10-28 11:38 UTC, pohly requested changes
I think together with https://github.com/kubernetes/kubernetes/pull/113384 it will be better to use gomega.format.Object for formatting. The result will be YAML, with indention as needed for the surrounding failure message when called by Gomega.

@justinsb: WDYT?

2022-11-27 11:42 UTC, closed without merging