Add Ingress Class to kubectl describe ingress output
kubernetes/kubernetes pull request #107921
Opened 2022-02-02 19:32 UTC by mpuckett159

/kind feature

#### What this PR does / why we need it:
This PR adds the Ingress Class to the output of `kubectl describe ingress`

#### Which issue(s) this PR fixes:
Fixes kubernetes/kubectl#1160

#### Special notes for your reviewer:
Based on the Ingress.Spec.IngressClassName comments (linked below) it looks like this should just be blank if the name isn't specified, so I'm setting to an empty string then updating if the name is provided.
https://github.com/kubernetes/kubernetes/blob/2b091f60ca09d3d03923a26b7cd02fb3dc6c47e2/staging/src/k8s.io/api/networking/v1/types.go#L246

#### Does this PR introduce a user-facing change?
```release-note
Ingress Class name is now provided in the kubectl describe ingress output
```

2022-02-04 18:09 UTC, sftim commented
For the changelog, I'd write
```
The output of `kubectl describe ingress` now includes an IngressClass name if available
```

2022-02-04 18:14 UTC, mpuckett159 commented
Yup that's more accurate, thank you.

2022-02-06 16:58 UTC, lauchokyip commented
/ok-to-test
/triage accepted
/priority backlog

2022-02-07 03:01 UTC, brianpursley requested changes
Code looks good.

Can you squash your commits?

2022-02-07 03:12 UTC, brianpursley commented
Question: Is printing an empty string preferable to printing something like `<none>` or even omitting the field entirely from the describe output?

I don't think I have a preference, but wonder if there is already a precedent for this somewhere else in describe.

2022-02-07 03:27 UTC, mpuckett159 commented
From my reading of [the ingress docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class) just before the `Ingress rules` header:

> There are some ingress controllers, that work without the definition of a default IngressClass. For example, the Ingress-NGINX controller can be configured with a [flag](https://kubernetes.github.io/ingress-nginx/#what-is-the-flag-watch-ingress-without-class) --watch-ingress-without-class. It is [recommended](https://kubernetes.github.io/ingress-nginx/#i-have-only-one-instance-of-the-ingresss-nginx-controller-in-my-cluster-what-should-i-do) though, to specify the default IngressClass as shown [below](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class).

An ingress does not technically require a class, which, imo, should result in printing a blank or `<none>` line rather than being ignored in the output. Having no class is important info since it's not recommended but technically possible. Writing `<none>` by default would be a good marker and definitely has precedent in the existing describe code.

I can add that if it sounds good.

2022-02-07 04:32 UTC, brianpursley commented
Hmm, OK.

I don’t really have much experience with ingress.  It sounds like a nil class name could indicate that it is using the default. Or in some cases nil might even be valid for that ingress type.  Maybe `<default>` would be another option, but that might not be the case for all ingress controllers.

The more I think about it, `<none>` seems wrong, because nil means use the default, not that there is no class name.

I’m sort of leaning towards how you have it currently, with an empty string.

2022-02-07 05:08 UTC, mpuckett159 commented
Nor do I unfortunately. The more I read about this the more it looks like I need to write a function to check a few things before populating a value.

[The IngressSpec API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1-networking-k8s-io) show that there is also a deprecated annotation to take into account that takes precedence over the actual `IngressClassName` property value.

Seems similar to kubernetes/kubectl#1133, actually.

2022-02-07 08:19 UTC, mpuckett159 commented
I think what I've landed on after some reading and testing is the following:
1. check for setting by spec
2. check for setting by annotation and add warning if found
3. if IngressClassName is still an empty string, query the api for IngressClass objects and search for one with the default annotation and add notation it was set by cluster default

Something to note, currently when doing a `kubectl get` it returns `<none>`

```bash
❯ kc get ingress
NAME              CLASS    HOSTS              ADDRESS     PORTS   AGE
example-ingress   <none>   hello-world.info   localhost   80      27m
```

I'm not sure if it's desirable to show the inferred class name for get or just stick with what is explicitly set in the Ingress object itself in this situation, however. If we're only fetching what is explicitly set in the config then `<none>` makes sense, however it does look like it overlooks the deprecated annotation when it's used. Seems like a bit of a sharp edge, but updating `describe` to follow this logic at least seems to smooth that out slightly.

2022-02-08 00:58 UTC, brianpursley commented
If `kubectl get ingress` just prints `<none>`, I’d be inclined to just do the same thing in describe.

I’m a little hesitant to try to reimplement the ingress class default/precedence rules inside kubectl.  It seems like this could be tricky, especially since it sounds like some ingress providers can work without a default class name.

I’m open to it, but just want to keep things simple if possible.  I understand if there is value in doing this though.

I’d like to hear from someone else who maybe has more experience than I do with ingress.  @rikatz any thoughts on this?  @eddiezane thoughts?

2022-02-08 01:48 UTC, rikatz commented
tl;dr because I wrote too much: I think having ingress class reflecting the ingressClassName is fine :)

The part where I write too much:

IngressClass is a tricky implementation. 

Right now, we have the "deprecated" annotation, and the new ingressClassName spec field. Users still tends to use (a lot!) the annotation and even in ingress nginx we are thinking on rolling back this "deprecation". It was a really noisy change. 

From my perspective, as the field is the "official" way of saying who "owns" that ingress, it's fine to print that field content and only it. 

Now going to the "how useful this is": some controllers does not implements class, while others implement on different ways. As far as I remember a class can only be used if it exists and was created by the clusteradmin, so users cannot add random things, and it's good on a description to know "who owns that ingress". 

I have a feeling right now that this solves half the problem: we have a description, but we don't have the "feedback" of if a controller from that class properly implemented that ingress but this is another discussion on the lack of status and conditions on ingress objects and I'm done on my KEP quota this year :)

2022-02-08 01:51 UTC, rikatz commented
Just complementing now that I read the whole thread: I wouldn't go with "how ingressA or B does". Stick with the API spec :) 

Annotation is deprecated. An ingressClassName can be empty, so either it's "none" or it's the value on the field. This is my opinion. 

Anything other than that is too specific and can lead to situations like "controller A does this way and you don't cover", etc. The API is our contract, and we should follow it.

2022-02-08 01:58 UTC, mpuckett159 commented
For easier reference re [API for Ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingress-v1-networking-k8s-io):
> IngressClassName is the name of the IngressClass cluster resource. The associated IngressClass defines which controller will implement the resource. This replaces the deprecated `kubernetes.io/ingress.class` annotation. For backwards compatibility, when that annotation is set, it must be given precedence over this field. The controller may emit a warning if the field and annotation have different values. Implementations of this API should ignore Ingresses without a class specified. An IngressClass resource may be marked as default, which can be used to set a default value for this field. For more information, refer to the IngressClass documentation.

Which is how I arrived at:
> 1. check for setting by spec
> 2. check for setting by annotation and add warning if found
> 3. if IngressClassName is still an empty string, query the api for IngressClass objects and search for one with the default annotation and add notation it was set by cluster default

2022-02-08 02:07 UTC, rikatz requested changes
Left some reviews.

2022-02-08 02:17 UTC, brianpursley commented
> tl;dr because I wrote too much: I think having ingress class reflecting the ingressClassName is fine :)

@rikatz Are you saying it is fine to simply display the value of ingressClassName directly, without doing any additional lookup of the default if it is nil?

I think that is where I am headed:  just show the value, if it is set, otherwise if nil then print <none>.

do you think this is good enough?

2022-02-08 02:19 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/describe/describe.go
> +		icl, err := i.client.NetworkingV1().IngressClasses().List(context.TODO(), metav1.ListOptions{})
Agreed.  If there is an error, you need to probably show something here, or else it could be misleading.

2022-02-08 02:53 UTC, rikatz commented
> @rikatz Are you saying it is fine to simply display the value of ingressClassName directly, without doing any additional lookup of the default if it is nil?
> 

Yeap, I'm a +1 to keep it simple right now. It's still confusing for users this annotations vs ingressClass thing, so let's state that ingressClass is the ingressClassName field, and IMHO move on :)

2022-02-08 03:56 UTC, mpuckett159 commented
I just wanted to double check, because I feel like I'm not on the same page as everyone else, but from my understanding of the API docs, it sounds to me like the annotation takes precedence, so if we really wanted to reflect reality back to the user it seems like we should be showing that annotation back if it exists as that's what the ultimate applied class will be.

2022-02-08 17:40 UTC, mpuckett159 commented
After sleeping on it I think what everyone is saying is that k8s.io/api/networking/v1(beta1) is where we should really implement the logic that I've written and have a function made available so that anyone can figure out the actual applied IngressClassName. That sounds correct to me, and if that's the consensus, I can scale back this commit back to where it's just reading the IngressClassName property and make an issue/PR for adding a function to "calculate" the actual applied Ingress Class based on the outlined logic from the docs, and whenever that's pulled in we can update the describe code here to utilize that function properly.

2022-02-10 00:35 UTC, mpuckett159 commented
Alright all that makes sense to me now, thanks everyone for the input. I've basically reset to the original PR commits and updated the Ingress Class output to show `<none>` to ensure that it is explicitly stated that when `ing.Spec.IngressClassName` is a nil pointer we are explicitly showing the user that, and hopefully avoiding any potential confusion there. I'll work on seeing if my proposed function for calculating the actual applied Ingress Class Name for the API is acceptable or not and get something open to which ever repo I need to open it to if so.

2022-02-10 18:17 UTC, brianpursley approved these changes
/lgtm

2022-02-10 19:57 UTC, merged

2022-02-10 20:49 UTC, brianpursley commented
Thanks @mpuckett159 👍