Add PodHealthyPolicy for PDBs
kubernetes/kubernetes pull request #108233
Opened 2022-02-20 22:32 UTC by mortent

#### What type of PR is this?
This PR implements the `PodHealthyPolicy` for PodDisruptionBudgets as described in https://github.com/kubernetes/enhancements/issues/3017

/kind feature
/kind api-change
/sig apps

#### What this PR does / why we need it:
This allows users to specify how PodDisruptionBudget and the eviction API should handle pods that are `Running` but not `Ready`.

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Add PodHealthyPolicy for PodDisruptionBudget
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3017-pod-healthy-policy-for-pdb
```

2022-02-21 00:56 UTC, mortent commented
/test pull-kubernetes-integration

2022-02-21 02:00 UTC, mortent commented
/test pull-kubernetes-conformance-kind-ga-only-parallel
/test pull-kubernetes-conformance-kind-ipv6-parallel

2022-02-22 21:11 UTC, jpbetz commented
cc @deads2k 
/triage accepted

2022-03-28 05:07 UTC, mortent commented
/test pull-kubernetes-e2e-gce-100-performance

2022-03-28 05:09 UTC, mortent commented
/cc @soltysh
/cc @janetkuo

2022-03-28 11:19 UTC, soltysh requested changes
You're missing clearing the `PodHealthyPolicy` field when the feature is disabled, similarly to how we do that for example here: 
- for create https://github.com/kubernetes/kubernetes/blob/a83c97941b63e800805378124a5fab08a051e4d4/pkg/registry/batch/job/strategy.go#L96-L102
- for update https://github.com/kubernetes/kubernetes/blob/a83c97941b63e800805378124a5fab08a051e4d4/pkg/registry/batch/job/strategy.go#L132-L134

2022-03-28 11:24 UTC, soltysh requested changes

2022-03-28 11:24 UTC, soltysh commented on pkg/apis/policy/types.go
> +	PodHealthyPolicy PodHealthyPolicy
Add information this is alpha-level field and that feature flag needs to be enabled for it to work: similarly to https://github.com/kubernetes/kubernetes/blob/a83c97941b63e800805378124a5fab08a051e4d4/pkg/apis/batch/types.go#L246-L251

2022-09-18 13:01 UTC, closed without merging

2022-10-27 01:06 UTC, atiratree commented
hi @mortent, we are building on top of this PR with @ravisantoshgudimetla  -

- https://github.com/kubernetes/kubernetes/pull/113375
- https://github.com/kubernetes/kubernetes/pull/113376