ignoredResources
kubernetes/kubernetes pull request #108321
Opened 2022-02-24 03:49 UTC by niuyueyang1996

events group fix

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-02-24 06:05 UTC, pacoxu commented
/kind bug

2022-02-24 17:41 UTC, fedebongio commented
/assign @lavalamp @deads2k 
/triage accepted

2022-02-25 09:25 UTC, tossmilestone requested changes

2022-02-25 09:25 UTC, tossmilestone commented on pkg/controller/garbagecollector/graph_builder.go
> +	{Group: "v1", Resource: "events"}:               {},
`v1` is the `version` but not `group`, the line should be removed.

2022-02-25 09:25 UTC, tossmilestone commented on pkg/controller/garbagecollector/graph_builder.go
> +	{Group: "events.k8s.io/v1", Resource: "events"}: {},
The group of `events.k8s.io/v1` should be `events.k8s.io`.

2022-03-01 04:06 UTC, tossmilestone approved these changes

2022-03-01 05:51 UTC, ialidzhikov commented
release-v1.20 branch is no longer active. I doubt that there will be a new patch for v1.20. You can check the master branch and check whether the fix is applicable there first.

2022-03-01 06:06 UTC, niuyueyang1996 commented
#108404

2022-03-01 06:54 UTC, pacoxu commented
I think you should merge it to the master branch at first and then do cherry-pick for 1.21-1.23 if needed.
For v1.20, the end of life on the website is yesterday and you may check with @kubernetes/release-managers.

2022-03-01 07:00 UTC, niuyueyang1996 commented
I created a new pr merge it to master.
#108404

2022-03-01 07:40 UTC, pacoxu commented
/retitle ignoredResources should contain events.k8s.io events
/release-note-none

2022-04-13 05:49 UTC, closed without merging

2022-04-13 05:51 UTC, justaugustus commented
(Closing as v1.20 is [no longer a supported Kubernetes release series](https://kubernetes.io/releases/patch-releases/#non-active-branch-history).)