Deba1
kubernetes/kubernetes pull request #108510
Opened 2022-03-04 03:25 UTC by Debanitrkl

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
`client-go` has several instances of `klog.Warningf.`
So, turned these warnings into actual errors that are returned by the functions.

#### Which issue(s) this PR fixes:

Fixes #94428 

#### Special notes for your reviewer:
Already sent a PR but got the branch deleted #104852

/cc @dims

2022-03-04 05:32 UTC, MadhavJivrajani commented
@Debanitrkl thanks for updating the PR, I think we will need a release note here considering we are moving from `klog.Warningf` to either a callback or `klog.Info`.
/triage accepted
/assign

2022-03-04 05:34 UTC, MadhavJivrajani commented
/hold
For squashing commits post reviews.

2022-03-07 05:53 UTC, MadhavJivrajani commented on staging/src/k8s.io/client-go/tools/clientcmd/loader_test.go
> +	klog.Flush()
```suggestion
	klog.Flush()
```
nit

2022-03-07 06:57 UTC, MadhavJivrajani commented on staging/src/k8s.io/client-go/tools/clientcmd/loader_test.go
> +	flags.Set("logtostderr", "false")
```suggestion
	klog.LogToStderr(false)
```

2022-03-07 07:58 UTC, MadhavJivrajani commented on staging/src/k8s.io/client-go/tools/clientcmd/loader_test.go
> +	flags.Set("logtostderr", "false")
Please make the change for the other test as well :)

2022-03-07 09:09 UTC, Debanitrkl commented
/retest-required

2022-03-07 09:20 UTC, MadhavJivrajani requested changes
The unit test failure is because `flag` package is imported but not used. Once fixed, you will still get a failure because the `TestWarningMissingFiles` test requires a level to be set. PTAL at the suggestion :)
Please also try and run these two tests locally to make sure things work as expected.

2022-03-07 09:20 UTC, MadhavJivrajani commented on staging/src/k8s.io/client-go/tools/clientcmd/loader_test.go
> +	klog.SetOutput(buffer)
```suggestion
	flags := &flag.FlagSet{}
	klog.InitFlags(flags)
	flags.Set("v", "1")
	klog.LogToStderr(false)
	klog.SetOutput(buffer)
```

2022-03-07 12:25 UTC, Debanitrkl commented
/test pull-kubernetes-unit

2022-03-07 14:59 UTC, MadhavJivrajani commented
@Debanitrkl now all that's left is squashing commits and adding a release note and we should be good to go!

2022-03-08 16:27 UTC, Debanitrkl commented
/merge-method-squash

2022-03-08 16:29 UTC, Debanitrkl commented
/tide merge-method-squash

2022-03-08 16:30 UTC, Debanitrkl commented
tide/merge-method-squash

2022-03-10 03:55 UTC, Debanitrkl commented
/remove hold

2022-03-10 03:56 UTC, Debanitrkl commented
/remove-hold

2022-03-28 15:48 UTC, MadhavJivrajani commented
/assign @yliaog @caesarxuchao 
for approval

2022-03-28 16:20 UTC, yliaog commented on staging/src/k8s.io/client-go/tools/clientcmd/loader.go
> +		rules.Warner.Warn(fmt.Sprintf("Config not found: %s", missingString))
nit: missingString is only used here, its value could be embedded here directly.

2022-03-28 16:20 UTC, yliaog commented on staging/src/k8s.io/client-go/tools/clientcmd/loader_test.go
> +	klog.LogToStderr(false)
this test confirms that the message is printed out when v=1 is set, but it does not confirm the message is *not* printed out when v=1 is not set.

2022-06-08 16:59 UTC, closed without merging