kubelet: cgroups: be verbose about validation
kubernetes/kubernetes pull request #108568
Opened 2022-03-07 15:26 UTC by stevekuznetsov

Previously, callers of `Exists()` would not know why the cGroup was or
was not existing. In one call-site in particular, the `kubelet` would
entirely fail to start if the cGroup validation did not succeed. In
these cases we MUST explain what went wrong and pass that information
clearly to the caller. Previously, some but not all of the reasons for
invalidation were logged at a low log-level instead. This led to poor
UX.

The original method was retained on the interface so as to make this
diff small.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/kind bug
```release-note
NONE
```

```docs

```

/cc @sjenning @derekwaynecarr @smarterclayton

2022-03-07 15:26 UTC, stevekuznetsov commented
/sig node

2022-03-07 15:28 UTC, smarterclayton commented
@rphillips @mrunalp this lgtm but wanted someone more familiar with cgroup manager (if that's either of you two, or others)

2022-03-07 17:56 UTC, rphillips commented
/assign @kolyshkin

2022-03-07 23:24 UTC, kolyshkin requested changes
Is it possible to not change the API (I don't like two methods with different names that do the same thing, with the only difference is return value)? Say, increase the log level in in `Exists` to a warning, and add logging to the missing places?

If not, maybe it's better to change all instances of `if cm.Exists()` to `if cm.Validate() == nil`.

2022-03-08 01:35 UTC, kolyshkin commented
Also, ideally I'd like this to go on top of https://github.com/kubernetes/kubernetes/pull/107149 since it incorporates some non-trivial changes.

2022-03-08 15:42 UTC, stevekuznetsov commented
@kolyshkin no. I very strongly disagree with you. Logging critical errors that cause the process to exit at a high verbosity level and asking the user to re-run their setup in order to see the error is absolutely not an option.

2022-03-08 15:44 UTC, stevekuznetsov commented
@kolyshkin also while I understand the request re: the other PR, it looks very large, very old and it's not clear the timeline on which it would merge.

2022-03-09 14:56 UTC, stevekuznetsov commented
@rphillips @kolyshkin updated to entirely remove the `Exists()` calls

2022-03-09 15:25 UTC, rphillips commented
This is changing and removing an established API. Exists() should probably stay and Validate be added. Exists() can simply call Validate().

2022-03-10 15:24 UTC, stevekuznetsov commented
Gotcha. @rphillips that was the original factoring. Let me revert to that one...

2022-03-10 15:25 UTC, stevekuznetsov commented
@rphillips reverted to the original state

2022-03-10 18:35 UTC, stevekuznetsov commented
/assign @derekwaynecarr
for approval :)

2022-03-10 18:49 UTC, smarterclayton commented
/approve

2022-03-10 19:59 UTC, merged