Skip scheduling pod that has been assigned node
kubernetes/kubernetes pull request #108667
Opened 2022-03-12 07:06 UTC by houjun41544

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Typically, only Pods with no assigned nodes are added to the scheduler queue. But when the exception is encountered, as mentioned in the issue, the pod is already running and the scheduler is still scheduling the pod.
So, is it possible to check before scheduling and skip scheduling if a pod is already assigned a node.

#### Which issue(s) this PR fixes:
Fixes #108665

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
-->
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

2022-03-12 09:07 UTC, VirrageS requested changes

2022-03-12 09:07 UTC, VirrageS commented on pkg/scheduler/scheduler.go
> +	// Case2: Pod has been assigned node.
```suggestion
	// Case 2: Pod has been assigned node.
```

2022-03-12 09:07 UTC, VirrageS commented on pkg/scheduler/scheduler.go
> +	// Case 3: pod that has been assumed could be skipped.
```suggestion
	// Case 3: Pod that has been assumed could be skipped.
```

2022-03-12 09:07 UTC, VirrageS commented on pkg/scheduler/scheduler.go
> +		klog.Infof("Skip scheduling pod that has been assigned node: %v/%v", pod.Namespace, pod.Name)
```suggestion
		klog.Infof("Skip scheduling pod that has been assigned node: %s/%s", pod.Namespace, pod.Name)
```

2022-03-12 09:54 UTC, houjun41544 commented
@VirrageS Thanks for your review!

2022-03-12 13:44 UTC, denkensk reviewed
1. The root case is why etcd returns `etcdserver:request timed out` but update successfuly and also scheduler did't receive the binding event? It feels like there are errors in multiple component interactions. I think we need to dig into the reasons for that Instead of just patching, right? 

2. IIUC.  We have checked `cachedPod.Spec.NodeName` in `ErrorFunc` before re-enqueue. Right? Why the pod will retry again and again?
https://github.com/kubernetes/kubernetes/blob/45f2c63d6af7d25d2c17a3953a2451340218ef14/pkg/scheduler/factory.go#L234-L239

2022-03-14 01:33 UTC, houjun41544 commented
@denkensk 
The k8s version that had this problem was 1.19.4, and no check for cachedPod.Spec.NodeName was added at that time.
I don't think this problem will arise if we check cachedPod.Spec.NodeName before re-enqueuing. 
I didn't notice that the later version added this check. I will close this pr.

2022-03-15 03:00 UTC, closed without merging