Improvement: Updated the serviceaccount flag for multiple subjects.
kubernetes/kubernetes pull request #108654
Opened 2022-03-11 06:34 UTC by Shubham82

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
This PR  updated the serviceaccont flag for multiple subjects under  `clusterrolebinding`  and `rolebinding`.

#### Which issue(s) this PR fixes:

Fixes #108608

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-03-11 06:35 UTC, pacoxu commented
/sig cli
/release-note-none
/ok-to-test

2022-03-11 06:38 UTC, Shubham82 commented
Hi @dougsland @eddiezane 
Could you please take look!

2022-03-13 17:11 UTC, RichardoC commented
LGTM, thanks for the rapid fix!

2022-03-16 11:22 UTC, Shubham82 commented
/assign @brianpursley

PTAL!

2022-03-19 01:31 UTC, brianpursley requested changes
Wouldn't the same apply to the `--user` and `--group` flags?  If so, I'm thinking they should say the same thing.

Also, I'm not sure if the term "subject" makes sense here, as that terminology is not used anywhere else in the help text.  Maybe just "service accounts" instead, to be consistent.

2022-03-21 06:18 UTC, Shubham82 commented
Thanks, @brianpursley for taking look at this.

> Wouldn't the same apply to the `--user` and `--group` flags? If so, I'm thinking they should say the same thing.

Yes, we can add the same thing for `--user` and` --group` flags.  

> Also, I'm not sure if the term "subject" makes sense here, as that terminology is not used anywhere else in the help text. Maybe just "service accounts" instead, to be consistent.

Adding `service accounts` instead of `subject` make sense.

I will update it.

2022-03-21 06:47 UTC, Shubham82 commented
@brianpursley, The --user flag is not shown under the options when we run `kubectl create clusterrolebinding --help`.

```
$ kubectl create clusterrolebinding --help

Options:
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in
the template. Only applies to golang and jsonpath output formats.
      --clusterrole='': ClusterRole this ClusterRoleBinding should reference
      --dry-run='none': Must be "none", "server", or "client". If client strategy, only print the object that would be
sent, without sending it. If server strategy, submit server-side request without persisting the resource.
      --field-manager='kubectl-create': Name of the manager used to track field ownership.
      --group=[]: Groups to bind to the clusterrole
  -o, --output='': Output format. One of:
json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-as-json|jsonpath-file.
      --save-config=false: If true, the configuration of current object will be saved in its annotation. Otherwise, the
annotation will be unchanged. This flag is useful when you want to perform kubectl apply on this object in the future.
      --serviceaccount=[]: Service accounts to bind to the clusterrole, in the format <namespace>:<name>
      --show-managed-fields=false: If true, keep the managedFields when printing objects in JSON or YAML format.
      --template='': Template string or path to template file to use when -o=go-template, -o=go-template-file. The
template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
      --validate=true: If true, use a schema to validate the input before sending it 
```

This is the same for rolebinding also. 

could you please tell me why it is not shown or if it is a bug(i think it is) then can you point me to code where I can do changes?

2022-03-30 00:46 UTC, eddiezane commented
The user flag here is shadowed by a global flag. You can see this by running `kubectl options`.

https://github.com/kubernetes/kubernetes/blob/699aeb735ff34d81d79817bf613203ac58e6edc3/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L362

I think we have encountered this before. Please search for shadowed flags.

2022-03-30 07:36 UTC, Shubham82 commented
Hi @brianpursley 
I have addressed the comment, PTAL!

2022-03-30 12:55 UTC, brianpursley requested changes

2022-03-30 12:55 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/create/create_clusterrolebinding.go
> +	cmd.Flags().StringArrayVar(&o.ServiceAccounts, "serviceaccount", o.ServiceAccounts, "Service accounts to bind to the clusterrole, in the format <namespace>:<name>. The flag can be repeated to add mu
```suggestion
	cmd.Flags().StringArrayVar(&o.ServiceAccounts, "serviceaccount", o.ServiceAccounts, "Service accounts to bind to the clusterrole, in the format <namespace>:<name>. The flag can be repeated to add multiple service accounts.")
```

2022-03-30 12:55 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/create/create_rolebinding.go
> +	cmd.Flags().StringArrayVar(&o.ServiceAccounts, "serviceaccount", o.ServiceAccounts, "Service accounts to bind to the role, in the format <namespace>:<name>. The flag can be repeated to add multiple
```suggestion
	cmd.Flags().StringArrayVar(&o.ServiceAccounts, "serviceaccount", o.ServiceAccounts, "Service accounts to bind to the role, in the format <namespace>:<name>. The flag can be repeated to add multiple service accounts.")
```

2022-03-30 13:24 UTC, Shubham82 commented
Thanks, @brianpursley for taking look at this.
I will update it.

2022-03-30 13:32 UTC, Shubham82 commented
@brianpursley 
PTAL

2022-03-30 13:59 UTC, brianpursley approved these changes
/lgtm

2022-05-04 01:23 UTC, merged