Volume host refactor
kubernetes/kubernetes pull request #109383
Opened 2022-04-08 01:20 UTC by raphminkyu

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Refactor platform specific code into separate files (*_linux.go / *_windows.go / *_others.go). Referring to #108765

#### Which issue(s) this PR fixes:

Fixes #60338

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-04-08 04:22 UTC, raphminkyu commented
/do-not-merge/work-in-progress

2022-04-08 15:18 UTC, kerthcet commented on pkg/kubelet/volume_host_others.go
> +//go:build !windows
Missed the license.

2022-04-08 15:18 UTC, kerthcet commented on pkg/kubelet/volume_host_windows.go
> +//go:build windows
ditto.

2022-04-08 18:43 UTC, raphminkyu commented
/easycla

2022-04-12 21:36 UTC, ehashman commented
/ok-to-test

2022-04-27 23:47 UTC, sorkinl commented
/easycla

2022-04-28 01:11 UTC, sorkinl commented
/test pull-kubernetes-e2e-kind

2022-04-29 17:34 UTC, raphminkyu commented
/easycla

2022-05-15 09:42 UTC, raphminkyu commented
/retest

2022-07-28 11:51 UTC, endocrimes requested changes
small change, otherwise LGTM

2022-07-28 11:51 UTC, endocrimes commented on pkg/kubelet/volume_host.go
>  	return dir
```suggestion
	return getPodHostsPath(kvh, podUID, pluginName, volumeName)
```

2022-12-25 14:08 UTC, closed without merging