e2e: Deprecated timeout constants migration
kubernetes/kubernetes pull request #109503
Opened 2022-04-15 10:30 UTC by kidlj

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Remove some of e2e framework deprecated timeout constants, use their corresponding framework.TimeContext values instead.

Some timeout constants from the same file are not able to migrate for now, like `Poll` or `PodGetTimeout`, because they are referenced by Framework itself, so they are left out.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-04-15 10:33 UTC, kidlj commented
/sig testing

2022-04-17 04:48 UTC, kerthcet commented
/ok-to-test

2022-04-18 07:06 UTC, aojea commented on test/e2e/kubectl/kubectl.go
> +	for t := time.Now(); time.Since(t) < podListTimeout; time.Sleep(framework.Poll) {
why passed as an argument instead of using the timeout?
we are using `framework.Poll` either way

2022-04-18 07:07 UTC, aojea commented on test/e2e/kubectl/kubectl.go
> +	for t := time.Now(); time.Since(t) < podListTimeout; time.Sleep(framework.Poll) {
ah, nevermind, this is part of the TimeoutContext now

2022-04-18 07:11 UTC, aojea commented on test/e2e/framework/timeouts.go
> +	PodEvent time.Duration
interesting, we should not have any test depending on this https://github.com/kubernetes/kubernetes/issues/71646

2022-04-18 07:15 UTC, aojea commented
I'm in favor of moving away from global variables for timeouts and modify the signature of functions of the format WaitForTimeoutXXXX(a,b,c,... , timeout) to accept the timeout as argument ... but I think that is better to wait for 1.25
/assign @BenTheElder @liggitt

2022-04-19 14:59 UTC, endocrimes requested changes
minor nit in node e2es

2022-07-18 00:05 UTC, closed without merging