do not install docker with curl
kubernetes/kubernetes pull request #109753
Opened 2022-05-02 13:21 UTC by matthyx

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
node e2e test installs docker from https://get.docker.com/ using curl, this is a supply chain security risk

#### Which issue(s) this PR fixes:

Fixes #109577

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-05-02 13:22 UTC, matthyx commented
/sig node
/triage accepted
/priority backlog

2022-05-04 13:56 UTC, endocrimes commented
@matthyx Hmm we probably actually want to update this to tell folks to install containerd + nerdctl now dockershim is gone

2022-05-05 13:07 UTC, matthyx commented
> @matthyx Hmm we probably actually want to update this to tell folks to install containerd + nerdctl now dockershim is gone

But these appear to be for containerd, no?
https://github.com/containerd/containerd/blob/main/docs/getting-started.md#option-2-from-apt-get-or-dnf

Maybe I will split instructions for CentOS, Debian, Fedora and Ubuntu...
(now let's look at `nerdctl`)

2022-05-13 11:48 UTC, matthyx commented
@endocrimes I have completely removed docker installation from the script, and now recommend containerd+nerdctl instead.
I don't know if we should autodetect the Linux distro and launch the instructions automagically, because it would add more toil to maintain, WDYT?

2022-05-13 13:17 UTC, endocrimes requested changes
almost lgtm

2022-05-13 13:17 UTC, endocrimes commented on test/e2e_node/environment/setup_host.sh
>  if ! hash docker 2>/dev/null; then
```suggestion
if ! hash containerd 2>/dev/null; then
```

2022-05-13 13:17 UTC, endocrimes commented on test/e2e_node/environment/setup_host.sh
> +  echo "Please install containerd.io using official packages, depending on your distro: https://docs.docker.com/engine/install/#server"
```suggestion
  echo "Please install containerd, see the getting started guide here: https://github.com/containerd/containerd/blob/main/docs/getting-started.md"
```

2022-05-13 13:25 UTC, matthyx commented
Thanks @endocrimes done.

2022-05-13 13:27 UTC, endocrimes approved these changes
/lgtm
/approve

![](https://media.giphy.com/media/3oEjHV0z8S7WM4MwnK/giphy.gif)

2022-05-13 14:33 UTC, merged