report a condition for job if pod creation or deletion fails
kubernetes/kubernetes pull request #109857
Opened 2022-05-06 11:03 UTC by RyanAoh

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
report a condition for job if an error is encountered while creating or deleting pods

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/100726

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

2022-05-06 11:19 UTC, RyanAoh commented
cc @liggitt

2022-06-30 11:34 UTC, RyanAoh commented
/retest

2022-08-02 16:33 UTC, soltysh requested changes
/hold
I don't think that's the kind of solutions we'd want to go for. At most we can report events that there's a problem, but I don't expect these kind of errors expressed in status. Mostly because this is rather temporary problem, solved as soon as the SA is created.

2022-08-02 16:33 UTC, soltysh commented on pkg/controller/job/job_controller.go
> +	conditionsChanged := false
Please don't change the name, it's explicitly to track job suspension.

2022-08-02 16:33 UTC, soltysh commented on pkg/controller/job/job_controller.go
> +				if action == metrics.JobSyncActionPodsCreated {
That's very specific and only temporary case we don't want to report, because as soon as the SA gets created the job will work just fine.

2022-08-02 16:33 UTC, soltysh commented on staging/src/k8s.io/api/batch/v1/types.go
> +	JobPodFailure JobConditionType = "JobPodFailure"
That kind of error will be confusing to users.

2022-08-03 08:53 UTC, RyanAoh commented
/close
@soltysh Thanks for your advice. I re-tested the case and the event will continue to be reported until the Pod is created successfully. So there is really no need to report it as a condition.

2022-08-03 08:53 UTC, closed without merging