Use typed ImageID for imageutils images
kubernetes/kubernetes pull request #109989
Opened 2022-05-12 00:11 UTC by tallclair

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Add an `ImageID` type for the test imageutils images. Benefits: self documenting code, better static type checking support.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig testing

2022-05-12 05:27 UTC, mkumatag requested changes
Overall looks clean, lgtm.. lets fix the CI..

2022-05-12 16:50 UTC, mkumatag approved these changes
/lgtm
/approve

2022-05-12 23:46 UTC, tallclair commented
/assign @pohly 
for approval

2022-05-13 06:05 UTC, pohly approved these changes
/approve

2022-05-13 07:13 UTC, merged

2022-05-13 07:35 UTC, aojea commented
nice