ease the check-up on ipvs modules
kubernetes/kubernetes pull request #109937
Opened 2022-05-10 11:41 UTC by bigclouds

Ease the check-up on ipvs modules

It is not necessary to check each module, to a large extent, ipvs's modules are built entirely and can load its own module automatically.
Anyway it is hard to cover every environment, for example  kernel and modules are built-in, but no kernel config file, like ipvs proxyer runs in a container.
Check-up on running environment is better than check-up on specific files, it may introduce new dependency.
So this patch take proc-fs into consideration.

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-05-11 01:39 UTC, bigclouds commented
@sig-network-reviewers @anderseknert

2022-05-11 06:01 UTC, uablrek commented
This fixes the problem when running inside a container and ipvs is loaded. But it also short-circuit the module check if ipvs main module is loaded. 

> [ipvs] can load its own module automatically.

This is not entirely accurate. Modules *can* be loaded on demand by the kernel by an upcall to;
```
# cat /proc/sys/kernel/modprobe
/sbin/modprobe
```
Ipvs is not a program and can not load its own module, but `ipvsadm` is. Example;
```
# ls /proc/net/ip_vs
ls: /proc/net/ip_vs: No such file or directory
# ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
# ls /proc/net/ip_vs
/proc/net/ip_vs
```
The use of `ipvsadm` has caused the kernel to load the `ip_vs` module, but not the other "required" modules.

Now, I have argued against the checking of modules since I started with K8s 1.9 in 2018. By then I had a statically built kernel with all necessary functions but could not run K8s because of explicit module checks. Not only in kube-proxy/ipvs but also at many other places.

IMHO these "helpful" checks of modules adds more problems than they solve. Normal users use a Linux distribution and these things "just work". Specialized users who build their own kernel (like myself) don't need help with checking modules. They know about the problem. *A warning can be very helpful though*.

To check the ipvs *function* I would prefer doing some corresponding to the `ipvsadm -L -n` in the example above but in go. E.g:
https://github.com/kubernetes/kubernetes/blob/b74d023e70d6064c7f3f77031e7d26ec38497fc9/pkg/util/ipvs/ipvs.go#L39

If that works, I agree that the other "required" modules does not need checking (especially not the "conntracker" which is used everywhere).

Back to the beginning; since this PR only fixes a minor inconvenience (the log printouts) in containers while potentially short-circuit the original intended check, I will not approve this PR.

2022-05-11 06:04 UTC, uablrek requested changes
Please see general comment

2022-05-11 08:14 UTC, bigclouds commented
@uablrek 
IMHO these "helpful" checks of modules adds more problems than they solve.  I can not agress with you more. 
This patch does not try to load ipvs modules, because existence of  '/proc/net/ip_vs'  means  ip_vs main module is loaded. scheduler modules are loaded by ip_vs automatically.

as for using ipvsadm, it is also not the ultimate solution. because proxyer does not use ipvsadm, patch introduces new dependency,  though ipvsadm is installed normally.

or delete those checks, let document and runtime error to tell,  or just check the existence of  ip_vs main module.

2022-05-11 09:20 UTC, uablrek commented
> To check the ipvs function I would prefer doing some corresponding to the ipvsadm -L -n in the example above but in go.

By "corresponding to ... but in go" I mean not using ipvsadm but doing a similar operation in go.

2022-05-11 09:25 UTC, uablrek commented
> scheduler modules are loaded by ip_vs automatically.

The check is not if they can be loaded, but if they exist.

2022-05-11 12:23 UTC, bigclouds commented
@uablrek 
Kernel  has the capability.  look at "net/netfilter/ipvs/ip_vs_sched.c, function  request_module ". ip_vs can load other ipvs's modules.
also refer to https://github.com/moby/ipvs/blob/d5d89bed3438c8b85db5e5868bb23846ee755ff4/netlink.go#L62.  It has taken it into consideration and loaded ip_vs.

I write some code to test module-auto-load. The result proves i say above.  We just  need to care about only ip_vs module.

`
package main
import (
        "log"
        "fmt"
        "net"
        "github.com/moby/ipvs"
        "golang.org/x/sys/unix"
)
var ip1 net.IP =  net.ParseIP("172.17.1.10")
var ip2 net.IP =  net.ParseIP("172.17.1.11")

var s ipvs.Service = ipvs.Service {
        Address: ip1,
        Protocol: uint16(unix.IPPROTO_TCP),
        Port: 9898,
        SchedName: "rr",
        AddressFamily: unix.AF_INET,
        Netmask : 0xffffffff,
}
var d ipvs.Destination = ipvs.Destination{
        Address: ip2,
        Port: 9876,
}

func main() {
        handle, err := ipvs.New("")
        if err != nil {
                log.Fatalf("ipvs.New: %s", err)
        }
        svcs, err := handle.GetServices()
        if err != nil {
                log.Fatalf("handle.GetServices: %s", err)
        }
        fmt.Println(svcs)

        err = handle.NewService(&s)
        if err != nil {
                log.Fatalf("handle.NewServices: %s", err)
        }
        err = handle.NewDestination(&s, &d)
        if err != nil {
                log.Fatalf("handle.NewDestination: %s", err)
        }
        svcs, err = handle.GetServices()
        if err != nil {
                log.Fatalf("handle.GetServices: %s", err)
        }
        fmt.Println(svcs)
}
`

2022-05-11 12:28 UTC, uablrek commented
**NOTE** I am *not* claiming that the kernel can't load modules. I know it can.

But the test verifies that the submodules ip_vs_rr, ip_vs_wrr, ip_vs_sh *exists on the host*.

2022-05-11 13:25 UTC, bigclouds commented
does verifying ip_vs_rr, ip_vs_wrr, ip_vs_sh make much sense? 
1. ipvs has 17 modules, why do

2022-05-13 05:17 UTC, uablrek commented
Ref https://github.com/kubernetes/kubernetes/pull/110017

2022-05-13 05:40 UTC, uablrek commented
Please see https://github.com/kubernetes/kubernetes/issues/108579#issuecomment-1125675626

2022-08-19 10:57 UTC, closed without merging