hpa: rename rebalanceIgnored to scaleUpWithUnready for understanding
kubernetes/kubernetes pull request #110492
Opened 2022-06-09 15:35 UTC by j2gg0s

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
In #95560, we use `unreadyPods` replace `ignoredPods`, but kept associated variable `rebalanceIgnored`.
This can lead confusion.

Compare to `rebalanceUnready`, `scaleUpWithUnready` will be more clear.

2022-06-09 15:56 UTC, j2gg0s commented
/assign @josephburnett @mwielgus

2022-06-15 04:39 UTC, j2gg0s commented
@josephburnett @mwielgus should i assign this pr to you?

2022-06-15 09:25 UTC, pacoxu commented
/release-note-none
/priority backlog

2022-08-26 07:32 UTC, pbetkier approved these changes
I think it's a good change, indeed helps with understanding. Please fix the typo and we'll proceed with approvals for merge.

2022-08-26 07:32 UTC, pbetkier commented on pkg/controller/podautoscaler/replica_calculator.go
> +	sacleUpWithUnready := len(unreadyPods) > 0 && usageRatio > 1.0
typo

2022-08-26 07:33 UTC, pbetkier requested changes
I think it's a good change, indeed helps with understanding. Please fix the typo and we'll proceed with approvals for merge.

2022-08-26 07:37 UTC, j2gg0s commented on pkg/controller/podautoscaler/replica_calculator.go
> +	sacleUpWithUnready := len(unreadyPods) > 0 && usageRatio > 1.0
done and rebase master

2022-08-26 11:21 UTC, pbetkier approved these changes

2022-08-26 11:21 UTC, pbetkier commented
/ok-to-test
/assign @mwielgus

2022-08-30 16:24 UTC, josephburnett commented
/approve

2022-08-31 02:18 UTC, j2gg0s commented
@pbetkier @josephburnett maybe we still need /lgtm ?

2022-08-31 05:38 UTC, pbetkier commented
/lgtm

2022-08-31 06:10 UTC, pbetkier commented
/retest

2022-08-31 06:43 UTC, merged