feat:add-exchangeWatcher-fix-channelFull-panic
kubernetes/kubernetes pull request #110434
Opened 2022-06-07 17:18 UTC by enaguo

#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
Because of using fake client The program panics with "channel full", panic may not be the best solution, sometimes we don't want the program to panic when it have fake client.
#### Which issue(s) this PR fixes:

Fixes #
https://github.com/kubernetes/kubernetes/issues/110431
#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-06-07 20:11 UTC, fedebongio commented
/help

2022-06-09 16:38 UTC, leilajal commented
/assign @alexzielenski would you please take a look since you are recently looking into client go. feel free to assign to others if you need.
/triage accepted

2022-06-09 16:48 UTC, leilajal commented
/assign @alexzielenski 
would you please take a look since you are recently looking into client go. feel free to assign to others if you need.
/triage accepted

2022-06-13 17:16 UTC, alexzielenski commented
Would it be sufficient for you to just be able to increase the channel size of the fake watcher?

2022-06-13 17:16 UTC, alexzielenski commented
Would it be sufficient for you to just be able to increase the channel size of the fake watcher?

2022-06-15 06:06 UTC, enaguo commented
> @enaguo
> 
> Can you talk more about your use case? Would it be sufficient for your use case to just be able to increase the channel size of the fake watcher?

My program uses the fake client to simulate scheduling, synchronizes the data of the real cluster for simulation, I hope to increase the channel size according to the requirements of the cluster specification and do not want to panic directly after reaching the limit

2022-06-15 16:14 UTC, alexzielenski requested changes
I've reviewed the interface for this change, have not yet looked deeply at implementation details.

I think it is a worthwhile change to make the ObjectTracker more customizable, but I have a few comments about the interface.

I suggest that rather than adding in the `ExchangeWatcher` interface as you have done, we instead pass a new argument `options` as part of the `NewObjectTracker` constructor (a new variant `NewObjectTrackerWithOptions` might be more appropriate).

@enaguo Could you address these comments and we'll do another pass?

2022-06-15 16:14 UTC, alexzielenski commented on staging/src/k8s.io/client-go/testing/fixture.go
> +func (t *tracker) ExchangeWatcher(watcher ExchangeWatcher) {
re: other comment about ExchangeWatcher

This would go away if using the `ObjectTrackerOptions` method.

2022-06-15 16:17 UTC, alexzielenski commented
/ok-to-test

2022-06-17 03:14 UTC, enaguo commented on staging/src/k8s.io/client-go/testing/fixture.go
> +type Watcher interface {
Thanks for your suggestions, I will try to address these comments.

2022-11-14 04:18 UTC, closed without merging