Add unit tests for explain command
kubernetes/kubernetes pull request #110885
Opened 2022-06-30 09:50 UTC by ardaguclu

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR adds unit tests for `explain` command to increase unit test coverage of kubectl.

#### Does this PR introduce a user-facing change?
```release-note
None
```

2022-06-30 09:53 UTC, ardaguclu commented
@brianpursley could you please take a look at this?. Thanks.

2022-07-01 15:27 UTC, brianpursley requested changes
Looks like a good start.  I have a few suggestions for some additional tests while you are adding the tests.  Hopefully it won't be too much extra work to put those in.

2022-07-01 15:27 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/explain/explain_test.go
> +		!strings.Contains(buf.String(), "apiVersion\t<string>") {
I don't think this check is unique to `--recursive` as I see `apiVersion\t<string>` in the explain output, even without recursive specified.

```
$ kubectl explain pod | grep -P "apiVersion\t<string>"
   apiVersion	<string>
```

Maybe change this second check to something that will only be in the output when `--recursive` is specified.

For example:  `!strings.Contains(buf.String(), "annotations\t<map[string]string>") {`

WDYT?

2022-07-01 15:27 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/explain/explain_test.go
> +	cmd.Run(cmd, []string{"pods"})
Can you use something that has multiple version defined in the Open API spec and make sure that it shows the correct version?

So for example, I see in `testdata/openapi/swagger.json` that `cronjobs` has both `batch/v1beta1` and `batch/v1` versions defined.

So maybe test it both ways one with `--api-versions=batch/v1beta1` and then with `--api-versions=batch/v1` and look for the second line where is shows like:
```
VERSION:  batch/v1
```

2022-07-01 15:27 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/explain/explain_test.go
> +}
I guess while you are adding unit tests, might as well check the error message when you ask it to explain something it doesn't know about.

So for example:
```
$ kubectl explain foo
the server doesn't have a resource type "foo"
$ echo $?
1
```

And if the resource exists, but the version doesn't it is slightly different:
```
$ kubectl explain pod --api-version=v99
error: couldn't find resource for "/v99, Kind=Pod"
$ echo $?
1
```

2022-07-01 16:17 UTC, ardaguclu commented
@brianpursley thanks for review. These are all valid and useful points. I made changes according to your suggestions.

2022-07-01 17:19 UTC, ardaguclu commented
/retest

2022-07-15 18:11 UTC, ardaguclu commented
@brianpursley would you mind looking at one last time to this PR?. Thanks.

2022-07-15 21:07 UTC, brianpursley requested changes
Looks good.  Just one comment about a couple of the error messages that I think might refer to the wrong resource type (pod vs cronjob).

2022-07-15 21:14 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/explain/explain_test.go
> +		t.Fatalf("expected output should include pod kind")
Or I guess maybe it should say that it expects the version to be batch/v1 which is really what it looks like it is checking

2022-07-18 14:18 UTC, ardaguclu commented
unit test failures are not related to this PR

/test pull-kubernetes-unit

2022-07-20 15:30 UTC, brianpursley commented
/retest

2022-07-20 15:31 UTC, brianpursley approved these changes
Waiting for unit tests to pass before official lgtm, but this looks good...

2022-07-20 16:03 UTC, ardaguclu commented
> Waiting for unit tests to pass before official lgtm, but this looks good...

unit tests passed :)

2022-07-21 15:37 UTC, brianpursley commented
/lgtm

2022-07-21 21:25 UTC, merged