Avoid leaking lease objects
kubernetes/kubernetes pull request #110834
Opened 2022-06-28 11:19 UTC by uesyn

#### What type of PR is this?

/kind bug
/sig node

#### What this PR does / why we need it:

If a Node object is deleted before the kubelet is stopped, the lease controller in kubelet leaks lease objects which has no ownerReference field. This pr fixes it.

Lease has the special update endpoint which can not only update but also create the new lease objects if it is not found.
In addition, when the lease controller get a conflict error in updating a lease object, it does the complicated operations other than get the latest lease object.
These behavior cause to create lease objects which has no ownerReference, and it is leaked.

For more information, see https://github.com/kubernetes/kubernetes/issues/109777#issuecomment-1168123849 and https://github.com/kubernetes/kubernetes/issues/109777#issue-1225134115.

#### Which issue(s) this PR fixes:

Fixes #109777

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Fix leaking lease objects when a node is deleted before the kubelet is terminated.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-06-30 06:21 UTC, pacoxu commented
/triage accepted
/ok-to-test
/priority important-longterm

2022-06-30 08:33 UTC, uesyn commented
/retest

2022-06-30 10:27 UTC, uesyn commented
Passed the test.
I think the reason why unit-test failed is related to https://github.com/kubernetes/kubernetes/issues/110854.

2022-07-16 03:00 UTC, uesyn commented
ping @caesarxuchao
 @jpbetz

2022-07-25 04:43 UTC, uesyn commented
ping @caesarxuchao @jpbetz

2022-11-18 13:33 UTC, matthyx commented
/remove-lifecycle stale
/lgtm
thanks @uesyn !

2023-07-31 17:44 UTC, dims commented
/reopen

2023-07-31 22:49 UTC, cartermckinnon requested changes

2023-07-31 22:49 UTC, cartermckinnon commented on staging/src/k8s.io/component-helpers/apimachinery/lease/controller.go
> +	}
This doesn't seem like the right approach.

`backoffEnsureLease` will return a `nil` lease if none exists in the API **and** `newLease` returns an error (such as when the `Node` doesn't exist): https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-helpers/apimachinery/lease/controller.go#L168

When that happens, if we *don't* set `c.latestLease` to `nil`, we'll enter the above `if` every time this function is called. `retryUpdateLease` will never succeed with your change below. We'll *then* call `ensureLease` here, with a chance of creating a new lease and stabilizing the state.

I think the approach in #119661 more directly addresses the issue, which is errors from `newLease` being ignored.

2023-08-01 09:25 UTC, closed without merging