Say what pdbs we found on conflicting pdbs and unittest pdb conflict
kubernetes/kubernetes pull request #111473
Opened 2022-07-27 18:21 UTC by paulgmiller

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Conflicting pdbs can easily block automation around upgrade scaledown. Rather than having each tool go rexamine pdbs 

Also there didn't seem to be a UT case for conflicing pdbs so added one. 

#### Which issue(s) this PR fixes:
Relaated  to #75957 
But could probably use a new issue

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
Not sure if wording changes for error messages counts but including. 
```release-note
New error message for pdbs conflicts
```

2022-07-27 22:29 UTC, paulgmiller commented
Maybe /sig apps since thats how the issue was tagged.

2022-08-01 16:58 UTC, paulgmiller commented
@mortent I saw you drove alot of [PDB to GA](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/85-Graduate-PDB-to-Stable) is this something you'd be interested in?

2022-08-01 23:28 UTC, feiskyer commented
/ok-to-test

2022-08-01 23:31 UTC, feiskyer commented
/sig apps

2022-09-22 12:33 UTC, soltysh requested changes

2022-09-22 12:33 UTC, soltysh commented on pkg/registry/core/pod/storage/eviction.go
> +			msg := fmt.Sprintf("This pod has %d PodDisruptionBudgets (%s, %s  ...) and the eviction subresource supports 1.", len(pdbs), pdbs[0].Name, pdbs[1].Name)
The way we currently list pods here is we don't look at ownership nor RBAC, so by just printing random 2 pods you risk that you'll expose information that is not meant for the user seeing that information.

2022-12-12 18:14 UTC, paulgmiller commented
> If you still need this PR then please rebase, if not, please close the PR

Was trying to decide if RBAC checks were worth having better output.

2023-05-11 19:33 UTC, closed without merging