add flag concurrent-daemonset-syncs to kube-controller-manager
kubernetes/kubernetes pull request #111800
Opened 2022-08-11 11:28 UTC by chenk008

#### What type of PR is this?
/kind feature
/kind api-change

#### What this PR does / why we need it:
For now many other controllers like statefulset has flag concurrent-xxx-syncs to set number of workers, the daemonset controller has `DaemonSetControllerOptions` with default value 2, but does not have a flag.  The default value is very slow to create daemonset pod when scaling hundreds of nodes

This PR just export a flag concurrent-daemonset-syncs.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```
Exposes a `--concurrent-daemoset-syncs` flag to allow tuning the number of daemoset workers.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-08-11 16:31 UTC, leilajal commented
/assign @cici37 
/triage accepted

2022-08-30 06:57 UTC, sttts commented
Strange mix of "changing default" and "adding flag" in one commit. These should be separate.

2022-08-30 06:58 UTC, sttts commented
/assign @soltysh

2022-08-30 06:59 UTC, sttts commented
/ok-to-test

2022-08-30 12:04 UTC, chenk008 commented
@sttts Thanks for your reviewing. This commit does not  "changing default", the default value is still 2. It changes test value.

2022-08-30 12:04 UTC, chenk008 commented
/retest

2022-08-30 14:27 UTC, sttts commented
Ack.

Leaving final review to @soltysh

2022-10-14 16:58 UTC, cici37 commented
/lgtm
The changes look good but now sure if we agree on having the flag. Leave for others who have the context :)

2022-11-25 14:50 UTC, soltysh requested changes
/hold
The fact that we are exposing this flag for other controllers doesn't mean we should do it for others, actually we've been trying to not to expose this field anymore, since this configuration has many implications how a controller works. So unless there's an explicit request for our users with sufficient number of up-votes we can consider accepting this addition, if not, I'd prefer not to do it now.

2022-11-26 14:01 UTC, chenk008 commented
@soltysh Please consider this scenario, we scale out 1000 node one time and hope the 1000 node will be ready in 30 seconds. The node ready condition depends on CNI component.  For now,  CNI component always been deployed by daemonset.  We will wait the 1000 CNI pods to be created.

In one reconcile, the controller syncs at most 250(BurstReplicas) nodes, so it will reconcile at lease 4 times, and one reconcile will cost 5~10 seconds. And usually we will deploy 6~8 daemonsets, so the 1000 CNI pods creation maybe delay over 1 minutes.

Indeed we change the concurrent-daemonset-syncs to 8 in my internal cluster by hard coding.

We need this flag explicitly, please help to improve it.

2022-12-20 09:45 UTC, soltysh commented
This situation is similar to the one in https://github.com/kubernetes/kubernetes/pull/110433, where I left identical comment.
There has been some discussions about adding new flags for kubernetes components (https://github.com/kubernetes/kubernetes/pull/111023#discussion_r1017190051). TL;DR is we will be careful exposing new flags to not over-complicate and over-configure the possible behaviours. Every new flag imposes us to support it forever, basically.
Before doing so, or even considering alpha-stage flag, I'd like to see that there's a sufficient community behind this addition. I'd suggest opening an issue similar to https://github.com/kubernetes/kubernetes/issues/80397 and gather feedback from the community. Until we gain confidence this is highly requested I propose we hold merging this functionality. 
/lgtm cancel

2023-03-20 21:26 UTC, lavalamp commented
It seems like the problem is qps/burst settings, not the number of workers (workers share a client and hence share qps limits). The solution is probably to increase those a lot or remove them, now that APF is nearing GA. We already increased the limits for kubelets. We should probably do all controllers together.

@wojtek-t for thoughts on raising controller qps settings?

2023-03-21 10:52 UTC, wojtek-t commented
> @wojtek-t for thoughts on raising controller qps settings?

I would love to do that, but give us a bit more time. This is primarily blocked on: https://github.com/kubernetes/kubernetes/issues/115293

I think that with the recent change adjusting how we compute the APi call latency SLO (excluding wait time), we effectively should be good to go, but it requires adjusting our tests to look at the right metric and verifying that.
It's moving slowly, but we're making some progress here.

2023-03-21 16:10 UTC, lavalamp commented
Thanks. In any case, I think we can close this, since adding worker threads doesn't add qps anyway.

People should be able to manually adjust qps & burst for controller manager in the mean time if they have this problem.

2023-03-21 16:10 UTC, closed without merging