update logtools to support verbosity Zero Check
kubernetes/kubernetes pull request #112215
Opened 2022-09-03 01:19 UTC by yangjunmyfm192085

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
as discussed in https://github.com/kubernetes-sigs/logtools/issues/2 and https://github.com/kubernetes/kubernetes/pull/111708, we should add verbosity Zero Check in logtools
#### Which issue(s) this PR fixes:

Fixes #112206

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
"NONE"
```

2022-09-03 01:20 UTC, yangjunmyfm192085 commented
/cc @pohly

2022-09-03 02:16 UTC, yangjunmyfm192085 commented
/retest

2022-09-05 07:23 UTC, pohly commented on hack/tools/go.mod
> +	sigs.k8s.io/logtools v0.2.1-0.20220830112100-f68289b649a5
Let's do a formal release of logtools first. For that I am waiting for https://github.com/kubernetes-sigs/logtools/pull/1

2022-09-21 14:14 UTC, yangjunmyfm192085 commented
/hold
only for test, don't merge

2022-09-21 14:14 UTC, yangjunmyfm192085 reviewed
/hold
only for test, don't merge

2022-09-21 14:17 UTC, yangjunmyfm192085 commented
/uncc hwdef

2022-09-22 13:57 UTC, pohly requested changes
I released logtools v0.3.0. Can you update Kubernetes to that tagged release?

2022-09-22 14:10 UTC, yangjunmyfm192085 commented
> I released logtools v0.3.0. Can you update Kubernetes to that tagged release?

ok, Let me update to v0.3.0.
But before that, I think we need to merge https://github.com/kubernetes/kubernetes/pull/112671 and https://github.com/kubernetes/kubernetes/pull/112672

2022-09-30 15:18 UTC, yangjunmyfm192085 reviewed
/sig instrumentation

2022-10-01 13:32 UTC, pohly commented
We probably need a list of all pending PRs that address the issues found by this tool update. Here are some that I am aware of:
- https://github.com/kubernetes/kubernetes/pull/112670
- https://github.com/kubernetes/kubernetes/pull/110747

2022-10-06 16:39 UTC, logicalhan commented
/triage accepted

2023-01-17 01:18 UTC, yangjunmyfm192085 reviewed
/unhold

2023-01-17 02:01 UTC, yangjunmyfm192085 commented
/test pull-kubernetes-e2e-kind-ipv6

2023-01-17 02:35 UTC, yangjunmyfm192085 commented
/cc @pohly logcheck will still check for errors.
I'll analyze it later

2023-01-17 06:48 UTC, pohly commented
Oh, I had forgotten about this PR and did my own with the same logtools update.

The errors are keys in existing code that violate our guidelines and now trigger warnings. I fixed them in https://github.com/kubernetes/kubernetes/pull/115060.

2023-01-20 00:59 UTC, yangjunmyfm192085 reviewed
.Closed due to PR expiration

2023-01-20 00:59 UTC, closed without merging