Create a network policy
kubernetes/kubernetes pull request #112432
Opened 2022-09-14 00:37 UTC by dgofman

https://kubernetes.io/docs/concepts/services-networking/network-policies/

NetworkPolicies are an application-centric construct which allow you to specify how a pod is allowed to communicate with various network "entities" (we use the word "entity" here to avoid overloading the more common terms such as "endpoints" and "services", which have specific Kubernetes connotations) over the network. NetworkPolicies apply to a connection with a pod on one or both ends, and are not relevant to other connections.

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Create a network policy using the kubectl create command line:
- Prevents all ingress AND egress traffic
- Create AND rules
- Create OR rules

#### Which issue(s) this PR fixes:
Fixes #
https://github.com/kubernetes/kubectl/issues/914
https://github.com/kubernetes/kubectl/issues/1240

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

2022-09-14 00:38 UTC, dgofman commented
/assign @eddiezane @soltysh @seans3 @thockin @danwinship

2022-09-14 00:38 UTC, dgofman commented
**kubectl create networkpolicies simple** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: simple
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}
```

**kubectl create networkpolicies policy-np --policy-types=egress** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: policy-np
spec:
  podSelector: {}
  policyTypes:
  - Egress
status: {}
```

**kubectl create networkpolicies podselector --pod-selector=app=nginx** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: podselector
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
status: {}
```

**kubectl create networkpolicies and-ingress-np --ingress=ports=udp:53,tcp:53,pod=app:nginx,namespace=kubernetes.io/metadata.name:default** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: and-ingress-np
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    - podSelector:
        matchLabels:
          app: nginx
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}
```

**kubectl create networkpolicies or-ingress-np --ingress=ports=udp:53,tcp:53 --ingress=pod=app:nginx --ingress=namespace=kubernetes.io/metadata.name:default** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: or-ingress-np
spec:
  ingress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: nginx
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}

```
**kubectl create networkpolicies multirules --pod-selector app=nginx --ingress ports=udp:53,tcp:53,pod=app:nginx,app:busybox,namespace=kubernetes.io/metadata.name:default --egress ports=udp:53,pod=app:httpd:2.4-alpine --egress ports=sctp:53,pod=app:busybox** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: multirules
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - podSelector:
        matchLabels:
          app: httpd:2.4-alpine
  - ports:
    - port: 53
      protocol: SCTP
    to:
    - podSelector:
        matchLabels:
          app: busybox
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    - podSelector:
        matchLabels:
          app: nginx
    - podSelector:
        matchLabels:
          app: busybox
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
status: {}

```

2022-09-14 00:44 UTC, dgofman commented
/assign aojea

2022-09-14 07:25 UTC, aojea commented
/ok-to-test

2022-09-14 07:34 UTC, aojea commented
@danwinship @rikatz you have much exposure to network policies than me, can you PTAL?

2022-09-14 11:44 UTC, rikatz commented
/assign

2022-09-14 14:45 UTC, ardaguclu commented
This PR creates a new command. I think it would be preferable to discuss this in sig-cli biweekly meeting.

2022-09-16 18:58 UTC, dgofman commented
@ardaguclu  When is your next bi-weekly sig-cli meeting?

2022-09-19 21:29 UTC, thockin commented
I'm not super keen on this fairly complex stingly-typed syntax.

Is there a doc somewhere on the minimum set of user-stories we want to capture and different ways to express those?

We don't need to support EVERYTHING here, just the most common things.

2022-09-19 21:44 UTC, dgofman commented
@thockin 
Most of the time I only need this command:
**kubectl create networkpolicies simple** -o yaml --dry-run=client

However, it is not clear from the official documentation how to create logical AND and OR connections between ports and namespaceSelector/podSelector, so running with different parameters will help developers.

2022-09-21 14:48 UTC, danwinship commented
That sounds like we need better documentation on the format then, not a way of bypassing it.

2022-09-21 17:55 UTC, dgofman commented
@danwinship I can't help with the documentation. That's a different story. My code allows developers to create a manifest file for NetworkPolicy. And must be approved as soon as possible. It is necessary for CKAD and CKA certification.

2022-09-25 15:44 UTC, dgofman commented
The first 3 commands are basic
**kubectl create networkpolicies simple** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: simple
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}
```

**kubectl create networkpolicies policy-np --policy-types egress** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: policy-np
spec:
  podSelector: {}
  policyTypes:
  - Egress
status: {}
```

**kubectl create networkpolicies podselector --pod-selector app=nginx** -o yaml --dry-run=client
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: podselector
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
status: {}
```

2022-09-25 20:12 UTC, dgofman commented
For other options, the user can run them separately:
**kubectl.go create netpol ingress-ports --ingress ports=udp:53,tcp:53** --dry-run=client -o yaml
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: ingress-ports
spec:
  ingress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
 ```
 **kubectl.go create netpol ingress-ports --ingress pod=app:nginx --egress namespace=kubernetes.io/metadata.name:default* --dry-run=client -o yaml
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: ingress-ports
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
status: {}
 ```
So nothing complicated!

2022-10-07 14:49 UTC, soltysh requested changes
/hold
as discussed during Oct 5th SIG-CLI call (https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#heading=h.bcbxqkuom4wh) this will not be accepted since we're planning to move forward with https://github.com/kubernetes/kubectl/issues/914 which will be targeted replacement for new create sub-commands.

2022-10-17 15:25 UTC, soltysh commented
/close

2022-10-17 15:26 UTC, closed without merging