Fix kube-apiserver flag: master-count -> apiserver-count
kubernetes/kubernetes pull request #112435
Opened 2022-09-14 01:34 UTC by mysunshine92

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-09-14 08:02 UTC, palnabarun requested changes

2022-09-14 08:02 UTC, palnabarun commented on CHANGELOG/CHANGELOG-1.24.md
> +- Kube-apiserver: the `--apiserver-count` flag and `--endpoint-reconciler-type=master-count` reconciler are deprecated in favor of the lease reconciler ([#108062](https://github.com/kubernetes/kubern
I don't think the CHANGELOG should be edited by hand. The change should come as a release note to the next 1.24 patch release.

2022-09-14 08:02 UTC, aojea commented
those flags were called that way at that time, you can't rewrite the name because doesn't match the flag

/close

2022-09-14 08:02 UTC, closed without merging

2022-09-15 16:35 UTC, leilajal commented
/triage accepted