[Flaky test] fix floating point precision error in TestDifferentWidths
kubernetes/kubernetes pull request #113263
Opened 2022-10-21 15:46 UTC by andrewsykim

Signed-off-by: Andrew Sy Kim <andrewsy@google.com>

#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

I noticed this test flakying in several of my PRs. Here's an example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113147/pull-kubernetes-unit/1582531708157169664

It seems like the test fails because of a floating point precision error when comparing the calculated difference in average to the expected margin. Naively opening a PR that just rounds the average to 2 decimal points to fix the flaky test but open to other alternatives.  

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-10-21 15:47 UTC, andrewsykim commented on staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset_test.go
> -			gotFair = math.Abs(relDiff) <= margin
From running the test multiple times, sometimes the value of `relDiff` is something like `-0.15000000066666663`

2022-10-21 15:49 UTC, andrewsykim commented
/assign @MikeSpreitzer

2022-10-27 16:59 UTC, leilajal commented
/triage accepted

2022-11-01 16:52 UTC, MikeSpreitzer requested changes
This is functionally equivalent to a simpler fix: use a larger margin.  For the cited example problem, which was from TestDifferentWidths, the same effect could be gotten from simply changing its margin from 0.15 to 0.155.  0.150001 would be good enough to overcome the cited example.

2022-12-06 15:06 UTC, mfojtik commented
/retest

2022-12-16 13:15 UTC, tkashem commented
/cc

2023-02-06 07:40 UTC, MikeSpreitzer commented
/test pull-kubernetes-e2e-gce-scale-performance-manual

2023-02-15 03:37 UTC, andrewsykim commented
/retest

2023-02-16 18:28 UTC, MikeSpreitzer approved these changes
/lgtm

2023-02-16 19:45 UTC, merged