Clean up testing code of kubectl cmd section
kubernetes/kubernetes pull request #113444
Opened 2022-10-29 15:15 UTC by weikhor

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Clean up testing code of kubectl cmd section
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-11-03 02:13 UTC, brianpursley requested changes
Hi @weikhor thanks for the PR.

I left you one comment.

Also, can you squash your commits to a single commit?  
https://www.kubernetes.dev/docs/guide/github-workflow/#squash-commits

2022-11-03 02:13 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/annotate/annotate_test.go
> +				t.Errorf("buffer should be empty: %s", bufOut.String())
This should be `bufErr` not `bufOut`

2022-11-05 08:29 UTC, weikhor commented
/remove-sig area/apiserver

2022-11-05 08:33 UTC, weikhor commented
/remove-label area/apiserver

2022-11-05 08:50 UTC, weikhor commented
/remove area/apiserver

2022-11-05 08:52 UTC, weikhor commented
/remove-area apiserver

2022-11-05 08:55 UTC, weikhor commented
/remove-area all

2022-11-05 08:56 UTC, weikhor commented
/remove-area cloudprovider code-generation conformance dependency e2e-test-framework ipvs kubeadm kubectl kubelet

2022-11-05 08:58 UTC, weikhor commented
/remove-area area/provider/gcp area/release-eng area/stable-metrics

2022-11-05 08:58 UTC, weikhor commented
/remove-area aprovider/gcp area area

2022-11-05 08:59 UTC, weikhor commented
/remove-area provider/gcp release-eng stable-metrics

2022-11-05 09:01 UTC, weikhor commented
/remove-sig api-machinery  apps architecture auth cloud-provider  cluster-lifecycle network node release scalability scheduling security  storage windows

2022-11-05 09:02 UTC, weikhor commented
/remove-sig  instrumentation testing

2022-11-05 09:05 UTC, weikhor commented
/remove-kind api-change

2022-11-05 09:06 UTC, weikhor commented
/remove-wg structured-logging

2022-11-05 09:08 UTC, weikhor commented
/remove needs-priority  needs-triage

2022-11-05 12:00 UTC, dims commented
/ok-to-test

2022-11-07 19:08 UTC, KnVerey commented
The change looks good to me, but I see that the commit is marked as co-authored by @sss-ng who has not participated on this PR so far. Can you confirm that that is correct?

2022-11-07 19:21 UTC, sss-ng commented
@KnVerey that is correct. I have no idea how my username is listed there. Any ideas?

2022-11-07 19:40 UTC, KnVerey commented
Agreed, it probably happened during the rebase. @weikhor can you please re-do the commit to remove the incorrect co-author? While you're at it, a more specific commit message (closer to your PR description) would be a nice bonus. Thanks!

2022-11-08 14:47 UTC, weikhor commented
> Agreed, it probably happened during the rebase. @weikhor can you please re-do the commit to remove the incorrect co-author? While you're at it, a more specific commit message (closer to your PR description) would be a nice bonus. Thanks!

Have updated changes accordingly, Thank for review.

2022-11-08 16:46 UTC, KnVerey commented
/lgtm
/approve
/test pull-kubernetes-integration

2022-11-08 20:42 UTC, merged

2022-11-08 21:11 UTC, fedebongio commented
/triage accepted