endpoint controller: use contextual logging
kubernetes/kubernetes pull request #113585
Opened 2022-11-03 10:28 UTC by lunhuijie

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Switch the endpoint controller code to use contextual and structured logging.
#### Which issue(s) this PR fixes:
Part of https://github.com/kubernetes/enhancements/issues/3077

Fixes #

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-11-04 01:26 UTC, yangjunmyfm192085 reviewed
/assign @shivanshu1333

2022-11-04 01:32 UTC, yangjunmyfm192085 commented on pkg/controller/endpoint/endpoints_controller.go
> +			logger.V(5).Info("Pod is not included on endpoints for Service", "podNamespace", pod.Namespace, "podName", pod.Name, "svcNamespace", service.Namespace, "svcName", service.Name)
```suggestion
			logger.V(5).Info("Pod is not included on endpoints for Service", "pod",  klog.KRef(pod.Namespace, pod.Name), "service", klog.KRef(service.Namespace, service.Name)
```

2022-11-04 01:32 UTC, yangjunmyfm192085 commented on pkg/controller/endpoint/endpoints_controller.go
> +			logger.V(2).Info("failed to find endpoint for service with ClusterIP on pod with error", "svcName", service.Name, "ClusterIP", service.Spec.ClusterIP, "podName", pod.Name, "err", err)
```suggestion
			logger.V(2).Info("Failed to find endpoint for service with ClusterIP on pod with error", "serviceName", service.Name, "ClusterIP", service.Spec.ClusterIP, "podName", pod.Name, "err", err)
```

2022-11-07 07:54 UTC, yangjunmyfm192085 commented on pkg/controller/endpoint/endpoints_controller.go
> +		logger.V(4).Info("Finished syncing service endpoints.", "service", key, "spendTime", time.Since(startTime))
```suggestion
		logger.V(4).Info("Finished syncing service endpoints", "service", key, "spendTime", time.Since(startTime))
```

2022-11-07 07:54 UTC, yangjunmyfm192085 commented on pkg/controller/endpoint/endpoints_controller.go
> +			logger.V(2).Info("Failed to find endpoint for service with ClusterIP on pod with error", "serviceName", service.Name, "ClusterIP", service.Spec.ClusterIP, "podName", pod.Name, "err", err)
```suggestion
			logger.V(2).Info("Failed to find endpoint for service with ClusterIP on pod with error", "serviceName", service.Name, "ClusterIP", service.Spec.ClusterIP, "pod", klog.KObj(pod), "err", err)
```

2022-11-07 07:56 UTC, yangjunmyfm192085 approved these changes
/lgtm

2022-11-09 00:30 UTC, yangjunmyfm192085 commented
/release-note-none

2022-12-08 15:50 UTC, pohly commented on pkg/controller/endpoint/endpoints_controller.go
> +	logger := klog.LoggerWithName(klog.FromContext(ctx), "Endpoint")
Elsewhere we decided to use WithName in cmd/kube-controller-manager/app/core.go  where it then applies to New and Run. Please move this and use "endpoint" (lowercase) as name for consistency reasons.

/lgtm cancel

2022-12-08 15:52 UTC, pohly requested changes

2022-12-08 15:52 UTC, pohly commented on pkg/controller/endpoint/endpoints_controller.go
> +		klog.FromContext(ctx).V(5).Info("Pod is out of service", "pod", klog.KRef(pod.Namespace, pod.Name))
Please also change this elsewhere.

```suggestion
		klog.FromContext(ctx).V(5).Info("Pod is out of service", "pod", klog.KObj(pod))
```

2023-04-11 07:06 UTC, pohly commented
/remove-lifecycle rotten

@lunhuijie : are you interested in finishing this?

2023-06-05 01:45 UTC, closed without merging