Delete heath data when nodes does not exist in node_lifecycle_controller
kubernetes/kubernetes pull request #113670
Opened 2022-11-07 11:33 UTC by Garrybest

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

In kube-controller-manager, nodeHealthMap in node_lifecycle_controller.go does not have delete function. Memory leak may happen where nodes are created and deleted frequently, e.g., cluster composed of idle cloud cvm. When a node is deleted, its health data must be deleted from nodeHealthMap.

#### Which issue(s) this PR fixes:

Fixes #102630

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-11-07 11:34 UTC, Garrybest commented
Sorry for waiting this late, add test for #102630 which cannot be reopened due to force push. @wzshiming

2022-11-08 02:45 UTC, wzshiming requested changes
https://github.com/kubernetes/kubernetes/blob/aa66cec6fa6e6804669363d54dc8971a6cb59b79/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L189-L195

Since it can be deleted, a nil pointer check needs to be added here, and all callers of the method need to check the return result.

2022-11-08 02:45 UTC, wzshiming commented on pkg/controller/nodelifecycle/node_lifecycle_controller.go
> +
```suggestion
```

2022-11-08 02:45 UTC, wzshiming commented on pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
> +	"k8s.io/utils/pointer"
Move to the bottom of the `import`

2022-11-08 02:55 UTC, wzshiming commented on pkg/controller/nodelifecycle/node_lifecycle_controller.go
> +				// If the node no longer exists, delete the corresponding health data from nodeHealthMap.
I don't think it's necessary here, just remove it uniformly in the infomer's deletion callback function.

2022-11-08 04:02 UTC, Garrybest commented
> Since it can be deleted, a nil pointer check needs to be added here, and all callers of the method need to check the return result.

Done. Note that nil pointer check is in function `func (n *nodeHealthData) deepCopy() *nodeHealthData`. We only need to check the callers which is in `handleDisruption`.

2022-11-08 06:01 UTC, wzshiming requested changes
https://github.com/kubernetes/kubernetes/blob/2aee0f2c3e91c86f5b266032331da09cb8eb8ffc/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1010

It seems that the check is missing here.

2022-11-08 06:15 UTC, wzshiming commented on pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
> +		},
```suggestion
		{
			name:   "delete node0",
			nodes:  nodes,
			delete: []string{"node0"},
			exists: []string{"node1"},
		},
		{
			name:   "delete node1",
			nodes:  nodes,
			delete: []string{"node1"},
			exists: []string{"node0"},
		},
```

2022-11-08 06:16 UTC, wzshiming commented
/ok-to-test

2022-11-08 11:07 UTC, Garrybest commented
> https://github.com/kubernetes/kubernetes/blob/2aee0f2c3e91c86f5b266032331da09cb8eb8ffc/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1010
> 
> It seems that the check is missing here.

I'm afraid not, see [here](https://github.com/kubernetes/kubernetes/blob/2aee0f2c3e91c86f5b266032331da09cb8eb8ffc/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1064-L1070).  The `nodeHealth` will be initialized if it is nil.

2022-11-08 23:44 UTC, logicalhan reviewed
/lgtm

2022-11-09 08:53 UTC, Garrybest commented
/assign @bowei

2022-11-09 09:19 UTC, wzshiming commented
/lgtm
/assgin @bowei @k82cn

2022-11-09 09:22 UTC, wzshiming commented
It seems that the code is frozen today

2022-12-14 02:28 UTC, Garrybest commented
Could you please take a look? @bowei

2023-03-14 10:46 UTC, Garrybest commented
cc @bowei

2024-02-04 01:13 UTC, closed without merging