Creating Ingress IP loadbalancer alone when all the endpoints are teminating
kubernetes/kubernetes pull request #113742
Opened 2022-11-08 15:22 UTC by princepereira

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
These changes are required as per KEP. If all the endpoints are going to deleting state, then an ingress loadbalancer should be present which constitutes serving endpoints.

#### Which issue(s) this PR fixes:
When all the endpoints are terminating, then as per the current design, there are no ingress loadbalancer policies to take care prestop hook traffic.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
NONE
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-11-11 04:52 UTC, sbangari commented
/ok-to-test

2022-11-14 07:59 UTC, princepereira commented
/cc @jsturtevant 
/cc @daschott 
/cc @sbangari 

Hi @jsurtevant, @daschott , @sbangari ,

Please review the code when you get some time.

Regards,
Prince

2022-11-18 01:33 UTC, daschott requested changes
Need to add externalVIP to loadBalancerflags for load balancer ingress ip as well:
https://github.com/kubernetes/kubernetes/pull/113742/files#diff-03419cd19861179be871687a3763ba4440dc39fe688032ecb8e2cbd0efd6f61dL1377

2022-11-18 04:38 UTC, princepereira commented
> Need to add externalVIP to loadBalancerflags for load balancer ingress ip as well: https://github.com/kubernetes/kubernetes/pull/113742/files#diff-03419cd19861179be871687a3763ba4440dc39fe688032ecb8e2cbd0efd6f61dL1377

Thanks @daschott  . Addressed the comments.

2022-11-18 05:00 UTC, princepereira commented
/test pull-kubernetes-e2e-capz-windows-containerd

2022-11-21 08:31 UTC, sbangari commented
/milestone v1.27

2022-11-21 08:40 UTC, sbangari commented
/lgtm
/approve

2022-11-21 08:50 UTC, princepereira commented
/release-note-none

2022-11-21 10:11 UTC, princepereira commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2022-11-21 11:02 UTC, princepereira commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2022-11-23 20:26 UTC, sbangari commented
/lgtm

2022-11-28 23:29 UTC, marosset commented
/milestone v1.27

2022-12-12 05:45 UTC, sbangari commented
/lgtm

2022-12-12 07:59 UTC, princepereira commented
/test pull-kubernetes-integration

2022-12-12 12:23 UTC, merged