clusterroleaggregation: use contextual logging
kubernetes/kubernetes pull request #113910
Opened 2022-11-15 10:09 UTC by mengjiao-liu

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
clusterroleaggregation: use contextual logging

#### Which issue(s) this PR fixes:

 Part of https://github.com/kubernetes/enhancements/issues/3077

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging
```

2022-11-15 10:13 UTC, mengjiao-liu commented
/sig instrumentation
/wg structured-logging
/area logging

2022-11-17 17:37 UTC, dashpole commented
/assign @pohly 
/triage accepted

2022-12-08 08:41 UTC, pohly requested changes

2022-12-08 08:41 UTC, pohly commented on cmd/kube-controller-manager/app/rbac.go
> +
Please remove the blank line.

2022-12-08 14:47 UTC, shivanshu1333 commented
/test pull-kubernetes-unit

2022-12-09 03:04 UTC, mengjiao-liu commented on cmd/kube-controller-manager/app/rbac.go
> +
Updated.

2022-12-13 11:26 UTC, pohly approved these changes
/lgtm

2022-12-29 19:54 UTC, sftim commented
Suggestion for the release note:
```markdown
Migrated the ClusterRole aggregation controller (within `kube-controller-manager`) to use [contextual logging](https://k8s.io/docs/concepts/cluster-administration/system-logs/#contextual-logging).
```

AIUI, end users could observe this change.

2022-12-30 03:24 UTC, mengjiao-liu commented
> Suggestion for the release note:
> 
> ```gfm
> Migrated the ClusterRole aggregation controller (within `kube-controller-manager`) to use [contextual logging](https://k8s.io/docs/concepts/cluster-administration/system-logs/#contextual-logging).
> ```
> 
> AIUI, end users could observe this change.

Comment addressed. Thanks.

2023-01-12 23:37 UTC, atiratree approved these changes

2023-02-22 10:14 UTC, pohly commented
/assign @soltysh 

For approval.

2023-03-08 02:49 UTC, mengjiao-liu commented
ping @soltysh

2023-03-10 10:06 UTC, soltysh approved these changes
/approve

2023-03-10 10:06 UTC, soltysh commented
/priority important-longterm

2023-03-10 12:34 UTC, merged