http code semantizat
kubernetes/kubernetes pull request #114056
Opened 2022-11-22 05:48 UTC by rokkiter

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Make http code semantic
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-11-29 21:14 UTC, fedebongio commented
/assign @MikeSpreitzer 
/triage accepted

2022-11-29 21:45 UTC, MikeSpreitzer requested changes
A couple of copy-and-paste errors noted inline.

2022-11-29 21:45 UTC, MikeSpreitzer commented on staging/src/k8s.io/client-go/util/certificate/certificate_manager_test.go
> +			clientErr:        apierrors.NewGenericServerResponse(http.StatusUnauthorized, "POST", schema.GroupResource{}, "", "", 0, true),
This should be StatusNotFound, right?

2022-11-29 21:45 UTC, MikeSpreitzer commented on staging/src/k8s.io/client-go/util/certificate/certificate_manager_test.go
> +			clientErr:        apierrors.NewGenericServerResponse(http.StatusUnauthorized, "POST", schema.GroupResource{}, "", "", 0, false),
This should be StatusNotFound, right?

2023-02-14 02:38 UTC, MikeSpreitzer commented
@rokkiter : would you like to follow up here?

2023-02-16 19:17 UTC, MikeSpreitzer commented
@rokkiter : thank you for this submission.  I think it just needs a couple of corrections, and it needs the release note filled in (I think NONE is a fine answer there).

2023-05-22 17:22 UTC, MikeSpreitzer commented
/ok-to-test
/release-note-none

2023-05-22 17:50 UTC, sttts commented on staging/src/k8s.io/client-go/discovery/cached/memory/memcache.go
> +	if t, ok := err.(errorsutil.APIStatus); ok && t.Status().Code >= http.StatusInternalServerError {
these`>= constant` cases IMO make the code harder to read. Would revert them. `== constant` is fine.

2024-03-19 09:48 UTC, closed without merging