Fix TestRemoveAPIService test in discovery aggregation
kubernetes/kubernetes pull request #114442
Opened 2022-12-13 08:24 UTC by qingwave

Signed-off-by: qingwave <isguory@gmail.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Block unittestes pipeline sometimes.

#### Which issue(s) this PR fixes:

Fixes #114438 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2022-12-13 15:31 UTC, alexzielenski commented
/sig api-machinery
/triage accepted
/ok-to-test

2022-12-13 16:08 UTC, alexzielenski approved these changes
fixes some goroutine leaks in the tests in addition to the race.

Using [`stress`](https://gist.github.com/liggitt/6a3a2217fa5f846b52519acfc0ffece0#running-unit-tests-to-reproduce-flakes) I was not able to reproduce the flake on my machine, but reading over the code, it's pretty easy to see that waiting for cache sync is not enough to guarantee `fetchPath` reflects the removed services. This PR properly turns that into a wait.

This PR reminds me of https://github.com/kubernetes/kubernetes/pull/113985 but I don't think that feature could have applied here, since this PR is meant to test calling RemoveAPIService after the initial list.

Thanks a ton @qingwave for taking the time to fix this as well as a clean up a few other issues in this code!

/assign @lavalamp

2022-12-13 16:10 UTC, alexzielenski commented
/unassign @lavalamp

2022-12-13 16:16 UTC, alexzielenski requested changes

2022-12-13 16:16 UTC, alexzielenski commented on staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery_test.go
> +	require.True(t, cache.WaitForCacheSync(testCtx.Done(), aggregatedManager.ExternalServicesSynced))
CI is currently failing because the test is stuck waiting at this line for 3 minutes (until testCtx.Done()).

2022-12-13 16:17 UTC, alexzielenski commented on staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery_test.go
> +	require.True(t, cache.WaitForCacheSync(testCtx.Done(), aggregatedManager.ExternalServicesSynced))
/cc @Jefftree

2022-12-13 16:35 UTC, alexzielenski commented on staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery_test.go
> +	require.True(t, cache.WaitForCacheSync(testCtx.Done(), aggregatedManager.ExternalServicesSynced))
Looks like there is a deadlock due to the APIService returning a 304 Not Modified, the aggregator takes the same lock twice. Opening up a follow-up PR to fix

2022-12-14 01:47 UTC, qingwave commented
Hi @alexzielenski, thanks for your detail explaining, this more clear here.

2022-12-14 21:41 UTC, alexzielenski commented
hi @qingwave your PR contains merge commits so GitHub is complaining. Please rebase the PR on the latest upstream/master and force push

/hold cancel

because the fix for the double lock is in, so this pr passes tests reliably now

2022-12-15 01:37 UTC, qingwave commented
> hi @qingwave your PR contains merge commits so GitHub is complaining. Please rebase the PR on the latest upstream/master and force push
> 
> /hold cancel
> 
> because the fix for the double lock is in, so this pr passes tests reliably now

@alexzielenski Thanks, the PR rebased

2022-12-15 21:39 UTC, alexzielenski approved these changes
/lgtm

I expect this should fix the flake that presented again in 114510

thanks again @qingwave

2022-12-15 21:40 UTC, alexzielenski commented
/assign @lavalamp

2022-12-24 10:07 UTC, qingwave commented
/assign @sttts

2023-01-12 06:27 UTC, qingwave commented
Hi @lavalamp and @sttts, the flaking test `TestRemoveAPIService` still occurs recently in https://github.com/kubernetes/kubernetes/issues/114438, could you approve this pr, it should fix the issue.

2023-01-27 01:18 UTC, alexzielenski commented
This test continued to flake after https://github.com/kubernetes/kubernetes/pull/114459, I swept it again for flakes and fixed a race in #115302.

@qingwave I'm not sure these changes to the test are still required. If you are able to reproduce a flake in CI or with stress testing tools that would be helpful to know.

/assign

2023-02-21 07:16 UTC, qingwave commented
Close due to no occurs again.

2023-02-21 07:16 UTC, closed without merging