Migrating `controller-manager` to contextual logging
kubernetes/kubernetes pull request #114612
Opened 2022-12-20 18:43 UTC by Namanl2001

Signed-off-by: Naman <namanlakhwani@gmail.com>

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
It migrates controller-manager to contextual and structured logging which is superior to the current unstructured logging.
#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/issues/3077

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging
```

/wg structured-logging
/cc @pohly @shivanshu1333
/cc @kubernetes/wg-structured-logging-reviews 
/priority important-longterm
/area logging

2022-12-20 18:46 UTC, Namanl2001 commented
I'm working on to migrate `staging/src/k8s.io/controller-manager` to contextual logging, not sure if I'm on right path. @pohly can you please review? thanks :)

2022-12-20 19:09 UTC, pohly requested changes

2022-12-20 19:09 UTC, pohly commented on staging/src/k8s.io/controller-manager/app/helper.go
>  	err := wait.PollImmediate(time.Second, timeout, func() (bool, error) {
Use `wait.PollImmediateWithContext(ctx, time.Second, timeout, func(ctx context.Context) (bool, error) {` here.

The advantage is that if ctx has a timeout or deadline, polling will stop when reaching it.

2022-12-20 19:09 UTC, pohly commented on staging/src/k8s.io/controller-manager/pkg/clientbuilder/client_builder_dynamic.go
> +		klog.FromContext(ctx).Error(err, "error in ConfigOrDie")
This is a change in behavior: it no longer aborts.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#replacing-fatal-calls

2022-12-20 19:09 UTC, pohly commented on staging/src/k8s.io/controller-manager/pkg/clientbuilder/client_builder.go
> +	ConfigOrDie(ctx context.Context, name string) *restclient.Config
I think passing a `logger klog.Logger` is the better choice here because it seems unlikely that these functions will ever need a contxt.

2022-12-20 19:09 UTC, pohly commented on staging/src/k8s.io/controller-manager/pkg/clientbuilder/client_builder_dynamic.go
>  	if err := wait.ExponentialBackoff(backoff, func() (bool, error) {
Use ExponentialBackoffWithContext.

2022-12-20 21:03 UTC, cici37 commented
/remove-sig api-machinery

2022-12-22 12:37 UTC, pohly requested changes
There are still several `klog.Fatal` calls left.

2022-12-22 12:37 UTC, pohly commented on cmd/kube-controller-manager/app/controllermanager.go
> +		controllerContext, err := CreateControllerContext(c, rootClientBuilder, clientBuilder, ctx)
The common convention is to pass the context as first parameter.

2022-12-23 12:09 UTC, Namanl2001 commented
@pohly how to deal with the errors in the vendor directory (due to which all tests are failing)?
 is it acceptable to make changes in `vendor`?

2022-12-23 12:57 UTC, pohly commented
The errors reports are misleading:
```
vendor/k8s.io/client-go/transport/round_trippers.go:295:17: not enough arguments in call to source.Token
```

The actual source here is `staging/src/k8s.io/client-go/transport/round_trippers.go` and thus can be edited. But the question is: should that get done in this PR?

Modifying staging repos has implications far beyond just kube-controller-manager. I think it is better to wait with that, i.e. split out those changes in your commits into a separate, WIP PR and here focus just on changes under pkg/controller and cmd/kube-controller-manager.

2022-12-29 19:34 UTC, sftim commented
I think this does need a release note, as end users could observe this change.

2022-12-29 19:54 UTC, sftim commented
Suggestion for the release note:
```markdown
Migrated the core of the `kube-controller-manager` to use [contextual logging](https://k8s.io/docs/concepts/cluster-administration/system-logs/#contextual-logging).
```

AIUI, end users could observe this change.

2023-01-03 21:10 UTC, fedebongio commented
/remove-sig api-machinery
/sig apps
/assign @pohly

2023-01-06 04:47 UTC, Namanl2001 commented
closing for now, will re-open if required.

2023-01-06 04:47 UTC, closed without merging