apiserver/kmsv2: mv Service interface into kmsv2
kubernetes/kubernetes pull request #114922
Opened 2023-01-09 15:37 UTC by ibihim

Signed-off-by: Krzysztof Ostrowski <kostrows@redhat.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Removes duplicate kms v2 service interface.

It got copied into k8s.io/kms as a first step and it is now being remove from k8s.io/apiserver (but imported).

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP] https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements
```

2023-01-10 11:36 UTC, enj commented
/ok-to-test

2023-01-10 21:10 UTC, cici37 commented
/remove-sig api-machinery

2023-01-11 23:25 UTC, aramase commented
/triage accepted
/cc

2023-01-12 19:28 UTC, aramase commented on staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope_test.go
> +
```suggestion
```

2023-01-12 19:29 UTC, aramase reviewed
Just one small nit!

`pull-kubernetes-unit` failure might just be a flake.

2023-01-13 01:16 UTC, enj requested changes

2023-01-17 16:03 UTC, enj commented
/lgtm
/approve

2023-01-17 17:03 UTC, dims commented
/approve
/lgtm

2023-01-17 18:10 UTC, merged