Contextual logs component base
kubernetes/kubernetes pull request #115212
Opened 2023-01-19 19:16 UTC by freddie400

What type of PR is this?
/kind feature

What this PR does / why we need it:
migrate staging/src/k8s.io/component-base

Which issue(s) this PR fixes:
Part of https://github.com/kubernetes/enhancements/issues/3077

Special notes for your reviewer:

Does this PR introduce a user-facing change?
Migrate `staging/src/k8s.io/component-base` to contextual logging

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

`- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging`

2023-01-20 08:34 UTC, yangjunmyfm192085 reviewed
hi, https://github.com/kubernetes/enhancements/issues/3077 This is to implement contextual logging, not just log structure. You can refer to other prs and https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

2023-01-20 08:36 UTC, yangjunmyfm192085 commented
At this point, all we need to do is the controller part can switch to context logging

2023-01-20 15:40 UTC, liggitt commented on go.mod
> -
this looks like a spurious rebase... you should be able to drop the changes in this file out of this PR

2023-01-24 21:11 UTC, cici37 commented
/remove-sig api-machinery

2023-01-26 17:37 UTC, logicalhan commented
/assign @logicalhan 
/triage accepted

2023-02-16 14:31 UTC, dims commented
@freddie400 please see the comment from Jordan inline and fix accordingly?

2023-02-19 17:44 UTC, dims commented
/ok-to-test
/assign @pohly

2023-02-19 18:07 UTC, freddie400 commented
Hi @dims, yeah, I am working on the changes. Was occupied with merging another PR.

2023-02-21 10:28 UTC, pohly commented
@freddie400: please fix the build errors. Try to verify locally that the code is okay before submitting a PR update, running all jobs is expensive...

2023-02-21 10:35 UTC, pohly requested changes

2023-02-21 10:35 UTC, pohly commented on staging/src/k8s.io/component-base/cli/flag/flags.go
> +		klog.V(2).InfoS("FLAG", "flagName", flag.Name, "flagValue", flag.Value)
It would be good to dump an example of what the new output looks like compared to the old one.

2023-02-21 10:35 UTC, pohly commented on staging/src/k8s.io/component-base/featuregate/feature_gate.go
> +			klog.InfoS("Setting deprecated feature gate. It will be removed in a future release.", "deprecated-feature-gate", k, "value", v)
I think we can use just "featureGate" as key here.

2023-02-21 10:35 UTC, pohly commented on staging/src/k8s.io/component-base/featuregate/feature_gate.go
> +			klog.InfoS("Setting GA feature gate. It will be removed in a future release.", "GA-feature-gate", k, "value", v)
Same here.

2023-04-26 03:12 UTC, mengjiao-liu commented
@freddie400  Do you still work for it? If so, please address the comments above.

2023-04-26 03:48 UTC, freddie400 commented
Hi @mengjiao-liu,
Yes, I am working on it. Actually, I have been going through some health issues. Will take up the work from 29th Apr.

2023-05-03 14:56 UTC, dims commented
Please remove merge commits, rebase and reopen this PR if necessary. It will not be merged as-is.

2023-05-03 14:57 UTC, closed without merging