kmsv2: improve test coverage
kubernetes/kubernetes pull request #116202
Opened 2023-03-02 03:15 UTC by ritazh

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Increase test coverage for kmsv2 changes to above 75%

#### Which issue(s) this PR fixes:

Partially addressing https://github.com/kubernetes/kubernetes/issues/114188

#### Special notes for your reviewer:

k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/metrics coverage: 79.1% of statements
k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig coverage: 75.2% of statements

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP] https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements
```

2023-03-02 03:15 UTC, ritazh commented
/sig auth
/triage accepted
/priority important-soon
/assign @enj

2023-03-02 04:37 UTC, ritazh commented
/test pull-kubernetes-e2e-kind-kms

2023-03-02 07:27 UTC, ritazh commented on staging/src/k8s.io/kms/internal/plugins/mock/go.mod
> +	k8s.io/klog/v2 v2.90.1
Ran `go mod tidy` to fix e2e job failure:
> CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} GO111MODULE=on go build -a -o mock-kms-plugin plugin.go
go: downloading k8s.io/klog/v2 v2.90.0
go: updates to go.mod needed; to update it:
	go mod tidy

2023-03-02 15:58 UTC, enj requested changes

2023-03-02 15:58 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go
> +		return nil, "", fmt.Errorf("decode err: %v", err)
```suggestion
		return nil, "", fmt.Errorf("error decoding encryption provider configuration file %q: %w", filepath, err)
```

2023-03-02 15:58 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go
> +	if err == nil {
```suggestion
	if errString(err) != "expected error message here" {
```

2023-03-02 15:58 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go
> +			}
```suggestion
			if errString(err) != tt.expectedErr {
				t.Errorf("expected err %q, got %q", tt.expectedErr, errString(err))
			}
```

2023-03-02 15:58 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go
> +		{
This is pre-existing but can you fix this test to actually check what the error message is instead of just a `nil` check.

2023-03-02 15:58 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go
> +				if err == nil {
Check that the error matches, and see if this logic can be made simpler by using `errString`.

2023-03-03 00:30 UTC, aramase commented on staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go
> +		},
Maybe i'm misreading it, but aren't both the tests passing the exact same config and expecting the same error? Is the second one a duplicate?

2023-03-03 00:30 UTC, aramase commented on staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go
> +				t.Fatal("expecting error calling prefixTransformersAndProbes")
```suggestion
				t.Fatal("expecting error calling prefixTransformersAndProbes, expected: %s, got: %s", testCase.expectedErr, errString(err))
```

2023-03-03 00:34 UTC, enj commented
/approve

2023-03-03 00:41 UTC, aramase reviewed
/lgtm

2023-03-03 06:58 UTC, pacoxu commented
/retest 
for flake https://github.com/kubernetes/kubernetes/issues/116165

2023-03-03 06:59 UTC, pacoxu commented
/test pull-kubernetes-e2e-gce-100-performance

2023-03-03 07:52 UTC, ritazh commented
/retest

2023-03-03 09:26 UTC, merged