Job controller contextual logging
kubernetes/kubernetes pull request #116910
Opened 2023-03-24 11:32 UTC by fatsheep9146

Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Use contextual logging for pkg/controller/job

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/issues/3077

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Migrated the Job controller (within `kube-controller-manager`) to use [contextual logging](https://k8s.io/docs/concepts/cluster-administration/system-logs/#contextual-logging).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging
```

2023-03-25 06:04 UTC, fatsheep9146 commented
@pohly could you help review this

2023-03-28 20:14 UTC, cici37 commented
/remove-sig api-machinery

2023-03-29 09:39 UTC, kannon92 commented
/ok-to-test

2023-03-29 10:29 UTC, fatsheep9146 commented
/retest

2023-03-29 12:22 UTC, kannon92 commented
Hello @fatsheep9146, it looks like your PR has a real failure in the linter.

```
pkg/controller/job/job_controller.go:1521:5: logging function "Info" should not use format specifier "%d" (logcheck)
				logger.V(2).Info("Slow-start failure. Skipping creation of %d pods, decrementing expectations", skippedPods, "job", klog.KObj(job))
				^
```

2023-03-29 13:50 UTC, fatsheep9146 commented
/retest

2023-03-30 16:36 UTC, cici37 commented
/cc @pohly

2023-04-11 08:16 UTC, pohly requested changes

2023-04-11 08:16 UTC, pohly commented on pkg/controller/job/job_controller.go
> +						logger.V(2).Info("Failed creation, decrementing expectations", "job", klog.KObj(job))
The key "job" is used inconsistently: above it refers to a string, here to an object.

I think I prefer to use "job" for the object and "key" when referring to the string which identifies the work item from the queue.

2023-04-11 08:16 UTC, pohly commented on pkg/controller/job/job_controller_test.go
> +	logger := klog.FromContext(ctx)
```suggestion
	logger, ctx := ktesting.NewTestContext(t)
```

2023-04-11 08:16 UTC, pohly commented on pkg/controller/job/job_controller_test.go
> +	logger := klog.FromContext(ctx)
```suggestion
	logger, ctx := ktesting.NewTestContext(t)
```

2023-04-11 08:16 UTC, pohly commented on pkg/controller/job/job_controller_test.go
> +	logger := klog.FromContext(ctx)
```suggestion
	logger, ctx := ktesting.NewTestContext(t)
```

2023-04-12 06:23 UTC, fatsheep9146 commented
/test pull-kubernetes-e2e-gce

2023-04-12 07:04 UTC, pohly requested changes
Looks good now. Let's clean up and then it is ready:
- remove the exception from https://github.com/kubernetes/kubernetes/blob/5f23f835879b514e9bf16809059b38957d20a486/hack/logcheck.conf#L49
- squash all commits into one, without rebasing

2023-04-12 09:06 UTC, fatsheep9146 commented
> Looks good now. Let's clean up and then it is ready:
> 
> * remove the exception from https://github.com/kubernetes/kubernetes/blob/5f23f835879b514e9bf16809059b38957d20a486/hack/logcheck.conf#L49
> * squash all commits into one, without rebasing

Done

2023-04-12 10:24 UTC, fatsheep9146 commented
/retest

2023-04-12 11:03 UTC, pohly commented
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116910/pull-kubernetes-verify/1646077352406421504 shows that there are klog calls left that still need to be converted in this PR.

2023-04-12 16:55 UTC, fatsheep9146 commented
/retest

2023-04-13 00:47 UTC, fatsheep9146 commented
/retest

2023-04-13 04:35 UTC, fatsheep9146 commented
@pohly could you check this again?

2023-04-13 09:22 UTC, pohly approved these changes
/lgtm
/assign @soltysh 

For approval.

2023-04-18 20:08 UTC, fedebongio commented
/triage accepted

2023-05-09 10:48 UTC, fatsheep9146 commented
@pohly could you help add lgtm label again?

2023-05-16 07:12 UTC, pohly commented
/lgtm

2023-06-14 05:40 UTC, fatsheep9146 commented
@pohly Could we push this pr into merged ASAP? The pr is already added with lgtm label before.

2023-06-14 10:09 UTC, pohly approved these changes
/lgtm

2023-06-14 12:38 UTC, pohly commented
/wg structured-logging

2023-06-14 13:38 UTC, soltysh approved these changes
/approve

2023-06-14 13:38 UTC, soltysh commented
/priority important-longterm

2023-06-14 15:00 UTC, merged