Clean code-generator/generate-internal-groups.sh help info.
kubernetes/kubernetes pull request #117004
Opened 2023-03-30 08:00 UTC by yanggangtony

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Clean the help info m
![image](https://user-images.githubusercontent.com/12080746/228769765-83c9e6b8-1208-4ff3-9a01-ce09064356d3.png)
essage to match the whole key words.

#### Which issue(s) this PR fixes:
Fixes #

```release-note
None
```

2023-03-30 16:55 UTC, cici37 commented
/ok-to-test
/cc @jiahuif would you mind to take a look when have time?
/triage accepted

2023-03-30 17:40 UTC, jiahuif commented
/retst

2023-03-30 17:40 UTC, jiahuif commented
/retest

2023-03-30 18:14 UTC, jiahuif commented
/lgtm
/assign @deads2k 
Trivial cleanup, could you take a look and approve it?

2023-03-30 18:18 UTC, jiahuif commented on staging/src/k8s.io/code-generator/generate-internal-groups.sh
>    ...                 arbitrary flags passed to all generator binaries.
```suggestion
  <generators>               the generators comma separated to run (deepcopy,defaulter,conversion,client,lister,informer,openapi) or "all".
  <output-package>           the output package name (e.g. github.com/example/project/pkg/generated).
  <internal-apis-package>    the internal types dir (e.g. github.com/example/project/pkg/apis).
  <extensiona-apis-package>  the external types dir (e.g. github.com/example/project/pkg/apis or githubcom/example/apis).
  <groups-versions>          the groups and their versions in the format "groupA:v1,v2 groupB:v1 groupC:v2", relative
                             to <api-package>.
  ...                        arbitrary flags passed to all generator binaries.
```

2023-03-30 18:19 UTC, jiahuif requested changes

2023-03-30 18:19 UTC, jiahuif commented on staging/src/k8s.io/code-generator/generate-internal-groups.sh
>    ...                 arbitrary flags passed to all generator binaries.
Add spaces to align the columns

2023-03-30 18:19 UTC, jiahuif commented
/remove-lgtm

2023-03-30 18:23 UTC, jiahuif commented
Could you also fix the typo "extensiona" in both places?

2023-03-31 02:43 UTC, yanggangtony commented
@jiahuif 
Thanks for review.
Rebased.

2023-03-31 22:30 UTC, jiahuif commented
/lgtm
/assign @deads2k

2023-04-08 13:10 UTC, yanggangtony commented
@deads2k 
Would you please take a look?

2023-07-13 23:37 UTC, yanggangtony commented
/close

2023-07-13 23:37 UTC, closed without merging