WIP add `--concurrent-job-syncs` flag to kube-controller-manager
kubernetes/kubernetes pull request #117138
Opened 2023-04-06 10:26 UTC by tosi3k

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

No issue is opened for that.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Add '--concurrent-job-syncs' flag for kube-controller-manager to set the number of job controller workers
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-04-06 11:06 UTC, tosi3k commented
/test pull-kubernetes-integration

2023-04-06 11:15 UTC, tosi3k commented
/assign @wojtek-t

2023-04-06 12:15 UTC, wojtek-t commented
/assign @soltysh 

I know there were some similar discussion about it recently (IIRC in the context of daemonset?)

2023-04-06 16:36 UTC, cici37 commented
/triage accepted

2023-04-06 16:37 UTC, cici37 commented
/sig cli

2023-04-12 10:52 UTC, soltysh requested changes
This proposal is similar to https://github.com/kubernetes/kubernetes/pull/110433 and https://github.com/kubernetes/kubernetes/pull/111800 which both were closed. Especially the last comments in the latter propose increasing qps for controllers which would help in some scenarios, but there are still some issues holding us back. For now I'm going to close this as won't do it in the near term. 

/close

2023-04-12 11:28 UTC, mborsz commented
Thanks @soltysh for review!

The main difference between daemonsets (mentioned by you https://github.com/kubernetes/kubernetes/pull/111800) and jobs is that it is a valid use case to have a lot of tiny jobs (while daemonsets will usually be larger), so the problem is that even with the current qps controller limits there are use cases when we fail to saturate the job's controller qps limit due to insufficient concurrency (think of e.g. 1000 jobs, each with 1 pod to be created, if we have 5 workers, we would have max 5 concurrent pod creations).

With pod creation latency around 10ms (based on performance tests [perf-dash](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadResponsiveness_PrometheusSimple&Resource=pods&Scope=resource&Subresource=&Verb=POST), but technically p99 slo is 1s for such mutating calls), we will get ~50 qps which is far from client-side qps limit of 100 qps.

The reason for adding the flag by @tosi3k is to support such use cases.

I agree that adding such flag will require us to support it in the future, but it's actually hard to imagine an implementation where we won't have a concept of worker (which is now used by nearly all controllers in kube-controller-manager)

You mentioned that we need community support to prove value of the flag and I think we already have quite a lot of use cases:
* this PR
* https://github.com/kubernetes/kubernetes/pull/110433 attempts to add similar flag
* @millerick in https://github.com/kubernetes/kubernetes/issues/80397)

Alternative approach would be to increase default worker count -- in most cases we should be throttled by qps anyway so no difference, cost of additional few goroutines is low, but in some corner cases the default value of 5 may not be sufficient and this is why people are asking for the flag.

2023-04-12 11:38 UTC, mborsz commented
/reopen

2023-04-12 12:20 UTC, tosi3k commented
Per offline discussion - fixed the description and added validation for the flag value.

@soltysh PTAL.

2023-04-12 14:37 UTC, soltysh reviewed
Based on the provided reasoning behind this change, and based on an offline discussion
/lgtm
/approve

2023-04-12 14:37 UTC, soltysh commented
/triage accepted
/priority important-longterm

2023-04-12 16:58 UTC, merged