Remove GA feature gates in 1.28 about advancedAuditing
kubernetes/kubernetes pull request #117549
Opened 2023-04-24 10:34 UTC by wlq1212

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove GA feature gates in 1.28 about advancedAuditing

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-04-25 20:13 UTC, cici37 commented
/sig auth
/remove-sig api-machinery

2023-05-19 09:24 UTC, Shubham82 commented
@wlq1212 
The following test is failing due to the formatting issue(gofmt error).

2023-05-19 09:29 UTC, Shubham82 commented on staging/src/k8s.io/apiserver/pkg/features/kube_features.go
```suggestion
```
@wlq1212, remove line no. 90, may resolve this error. otherwise Run ./hack/update-gofmt.sh

2023-05-25 08:33 UTC, Shubham82 commented
Hi @wlq1212
Please makes the above changes so that it will merge.

2023-06-01 06:42 UTC, Shubham82 commented
Hi @wlq1212
If you are still working on this so could you please address the above comments

2023-06-12 06:40 UTC, Shubham82 commented
@wlq1212 Are you working on this PR?

2023-06-12 18:57 UTC, aramase requested changes
@wlq1212 could you run `hack/update-gofmt.sh` to fix the formatting in the file?

2023-06-12 18:58 UTC, aramase commented
/triage accepted

2023-06-19 05:44 UTC, Shubham82 commented
Hi @aramase should we close this PR and open a new PR for it, if @wlq1212 is not working on this? It is opened for a long time and not gotten any response from him. And also we have to update the corresponding docs after this change.
If you think it seems good then I'm up for it.

WDYT should we wait or open a new PR?

2023-06-19 16:44 UTC, closed without merging

2023-06-19 16:46 UTC, Shubham82 commented
Sure I will open a PR for it soon.

Thanks!