Automated cherry pick of #117712: Set Pod phase to Failed if init container gets OOMKilled but
kubernetes/kubernetes pull request #117788
Opened 2023-05-04 18:29 UTC by ruiwen-zhao

Cherry pick of #117712 on release-1.26.

#117712: Set Pod phase to Failed if init container gets OOMKilled but

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

2023-05-05 18:50 UTC, ruiwen-zhao commented
/retest

2023-05-08 21:46 UTC, bart0sh commented
/kind bug
/triage accepted
/priority important-longterm

@ruiwen-zhao please provide release note

2023-05-08 21:47 UTC, bart0sh commented
/assign @bobbypage

2023-05-08 21:47 UTC, bart0sh commented
/cc

2023-09-20 20:22 UTC, bart0sh commented
/lgtm

2023-09-20 20:23 UTC, bart0sh commented
/assign @mrunalp @derekwaynecarr

2023-10-17 17:09 UTC, derekwaynecarr requested changes
The modified cherry pick makes a validation harder to compare.  I will need time to check locally the validity as the code is different.  If the author can accelerate review with requested pointers, its appreciated.

2023-10-17 17:09 UTC, derekwaynecarr commented on pkg/kubelet/kubelet_pods.go
> +			if containerStatus.State.Terminated.ExitCode != 0 || containerStatus.State.Terminated.Reason == "OOMKilled" {
I am not seeing where the equivalent logic for this is handled in the linked PR.

Could you help point to the equivalent change here? 
see: https://github.com/kubernetes/kubernetes/pull/115331

2023-10-17 18:31 UTC, ruiwen-zhao commented
Yeah i created this cherry-pick without merging the code in main because the issue only happens on 1.26 but not 1.27 and later. 

Since the issue does not repro in 1.27, and we might not want to introduce a behavior change to 1.26, I think we can probably close this PR.

2023-10-17 18:31 UTC, closed without merging