[WIP] Improve encryption transformer lookup performance
kubernetes/kubernetes pull request #118205
Opened 2023-05-23 16:27 UTC by dinhxuanvu

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The current implementation of the transformer lookup for encryption is to loop through the entire list of transformers. For the case, multiple keys with multiple encryption types, it can be inefficient.

The list of transformers can be constructed as a map with encryption prefix as a key to improve lookup time while maintaining the input order via a slice of transformers as map value.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
No

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-05-30 17:09 UTC, enj requested changes
Hi @dinhxuanvu, thanks for the PR.  However, this change is neither necessary nor correct.  Any performance gains here would be theoretical, and make an already difficult part of the code harder to read.  We will keep the existing slice based approach because it is easy to read, and the cost of iterating over a slice or two is dwarfed by the cost of the actual crypto and encoding/decoding required.

These changes break the AES transformer which is easy to observe via:

```
make test-integration WHAT=./test/integration/controlplane/transformation KUBE_TEST_ARGS="-v"
```


In the future, please discuss any changes you want to make in the [#sig-auth-kms-dev](https://kubernetes.slack.com/archives/C03035EH4VB) channel before starting the implementation.

/hold

2023-05-30 17:09 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/storage/value/transformer.go
> +func getDataPrefix(data []byte) string {
This is incorrect, `prefixTransformers` need not be used at only the root, for example see the code in `aesPrefixTransformer`.

2023-06-06 20:10 UTC, alexzielenski commented
/remove-sig api-machinery

2023-10-24 21:26 UTC, dims commented
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

2024-02-03 17:13 UTC, closed without merging