chore: omit comparison to bool constant
kubernetes/kubernetes pull request #118456
Opened 2023-06-05 10:25 UTC by testwill

#### What type of PR is this?
/kind cleanup

Optionally add one or more of the following kinds if applicable:
/kind deprecation

#### What this PR does / why we need it:
should omit comparison to bool constant, can be simplified to found
#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
No

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-06-05 10:51 UTC, bart0sh commented on pkg/kubelet/kubelet_server_journal.go
> -		fmt.Sprintf("%s", service),
How this is related to the PR?

2023-06-05 10:59 UTC, bart0sh requested changes

2023-06-05 10:59 UTC, bart0sh commented on test/e2e/storage/vsphere/vsphere_volume_diskformat.go
>  		}
```suggestion
		isDiskFormatCorrect = eagerlyScrub && !thinProvisioned
```

2023-06-05 10:59 UTC, bart0sh commented on test/e2e/storage/vsphere/vsphere_volume_diskformat.go
>  		}
```suggestion
                isDiskFormatCorrect = !eagerlyScrub && thinProvisioned
```

2023-06-05 10:59 UTC, bart0sh commented on test/e2e/storage/vsphere/vsphere_volume_diskformat.go
>  	if diskFormat == "eagerzeroedthick" {
Would it make sense to convert this `if` into a `switch` ?

2023-06-05 11:02 UTC, bart0sh commented
/triage accepted
/priority important-longterm
/ok-to-test
/release-note-none

2023-06-05 11:19 UTC, bart0sh commented
/remove-kind deprecation
/release-note-none

2023-06-05 11:20 UTC, bart0sh commented
/release-note-none

2023-06-06 09:29 UTC, bart0sh commented
/retest

2023-06-06 17:32 UTC, marosset commented
/test pull-kubernetes-e2e-capz-windows
/approve

2023-06-15 16:57 UTC, marosset approved these changes

2023-06-15 16:57 UTC, marosset commented
/test pull-kubernetes-e2e-capz-windows

2023-06-25 14:59 UTC, testwill commented
/retest

2023-06-28 16:37 UTC, SergeyKanzhelev approved these changes
/lgtm

trivial edit, ok for node

2023-06-29 02:35 UTC, testwill commented
/retest

2023-10-17 18:24 UTC, mrunalp approved these changes

2023-10-17 20:28 UTC, SergeyKanzhelev commented
@msau42 can you approve for storage?

2023-10-26 08:41 UTC, jsafrane commented
/approve

2023-10-26 10:59 UTC, merged