Record failed plugins in Reserver Plugin
kubernetes/kubernetes pull request #118529
Opened 2023-06-07 10:14 UTC by kerthcet

#### What type of PR is this?
/kind feature
/sig scheduling

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

It's still useful to record failed plugins when running reserve plugins, e.g. in DRA plugin, when resource driver hasn't allocated the resource(inside `Reserve()`  function) yet, it will return unschedulable status.
https://github.com/kubernetes/kubernetes/blob/4c40d749006a8895f6718f2b624a3dbe975988ab/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go#L673-L691

Then when watching node update events for rescheduling, it will be more efficient by recording the unschedulable plugins, or we'll move pods to active or backoff queue anyway.

https://github.com/kubernetes/kubernetes/blob/4c40d749006a8895f6718f2b624a3dbe975988ab/pkg/scheduler/internal/queue/scheduling_queue.go#L771-L780

cc @Huang-Wei @pohly 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-06-07 10:20 UTC, kerthcet commented
/hold 
in case of unexpected merge

2023-06-07 15:49 UTC, SataQiu reviewed
/lgtm

2023-06-07 15:49 UTC, SataQiu commented
/triage accepted

2023-06-07 15:56 UTC, sanposhiho requested changes
@kerthcet 

Thanks! It's helpful because this is what I planned to do as part of https://github.com/kubernetes/kubernetes/pull/117844. 
But, recording as `FailedPlugin` in state is not enough to tell the scheduling queue as unschedulableplugins. We only do that when `FitError`. Can you have a change around this as well so that the failed plugin recorded in reserve is handled in the scheduling queue? 
https://github.com/kubernetes/kubernetes/blob/c4f44b3de3a29ea430c67ff83cdaabbdefcac39a/pkg/scheduler/schedule_one.go#L871

2023-06-07 16:04 UTC, Huang-Wei reviewed
Fine with me treating the failure similar as other extension points (PreFilter/Filter/etc.). But I will leave it to @pohly to confirm.

A nit below.

2023-06-08 01:10 UTC, sanposhiho commented
/triage accepted
/priority important-longterm

since it's part of https://github.com/kubernetes/kubernetes/pull/117844.

2023-06-08 01:11 UTC, sanposhiho commented
/remove-lgtm

https://github.com/kubernetes/kubernetes/pull/118529#pullrequestreview-1468062052

2023-06-12 06:35 UTC, pohly commented
> Fine with me treating the failure similar as other extension points (PreFilter/Filter/etc.). But I will leave it to @pohly to confirm.

Do we have this commit as part of a complete branch somewhere? Then I can test that the end result still works.

2023-06-15 05:41 UTC, sanposhiho commented
I believe it won't work due to https://github.com/kubernetes/kubernetes/pull/118529#pullrequestreview-1468062052.
@kerthcet Could you check my comment? Not a super urgent, but it'll block DRA's EnqueueingHint stuff in near future.

2023-06-28 05:56 UTC, kerthcet commented
I'm checking https://github.com/kubernetes/kubernetes/pull/118551 before going through this PR.

2023-06-30 08:02 UTC, kerthcet commented
I think there's a bug about Permit plugin, so I'd like to fix it first.

2023-07-04 14:11 UTC, kerthcet commented
/hold 
for https://github.com/kubernetes/kubernetes/pull/119046 merged first.

2023-07-07 02:48 UTC, kerthcet commented on pkg/scheduler/framework/runtime/framework.go
> +				logger.V(4).Info("Pod rejected by plugin", "pod", klog.KObj(pod), "plugin", pl.Name(), "status", status.Message())
I didn't find where we called it in the caller side, but we do when handling scheduling error, see https://github.com/kubernetes/kubernetes/blob/14bd9bc127eb8309d4c63770e848a07e96c8c30e/pkg/scheduler/schedule_one.go#L928-L930

they're with different log level and what we log in the PR containers more infos like the failed plugin name. So keep this the same with `RunPermitPlugin`? It has the same log.

2023-07-07 02:51 UTC, kerthcet commented
/hold cancel

2023-07-07 05:34 UTC, kerthcet commented
This is quite similar to https://github.com/kubernetes/kubernetes/pull/119046 , but adding support for reserve plugin, would you mind to take another look @ahg-g

2023-07-07 06:57 UTC, kerthcet commented
/retest

2023-07-07 17:07 UTC, ahg-g reviewed
/lgtm

2023-07-07 17:07 UTC, ahg-g commented on pkg/scheduler/framework/runtime/framework.go
> +				logger.V(4).Info("Pod rejected by plugin", "pod", klog.KObj(pod), "plugin", pl.Name(), "status", status.Message())
That is fine, we do log the reason though, which should indicate something about the plugin. I guess the point is being consistent with what we do for Filters, but we can keep this at 4.

2023-07-07 18:09 UTC, merged