shifiting verify publishing bot from python to golang
kubernetes/kubernetes pull request #118727
Opened 2023-06-17 16:24 UTC by sbdtu5498

#### What type of PR is this?
/kind feature /sig release

#### What this PR does / why we need it:
Currently make verify has a script called verify-publishing-bot.py that relies on an external dependency that needs to be downloaded by the end user. This PR replaces verify-publishing-bot.py with verify-publishing-bot.go which eases dependency management.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/publishing-bot/issues/345

#### Does this PR introduce a user-facing change?
None

2023-08-16 04:23 UTC, palnabarun requested changes

2023-08-16 04:23 UTC, palnabarun commented on hack/tools/verify/verify-publishing-bot.go
A general comment on this. Instead of type casting and using `map[interface{}]interface{}`, you can use the types from https://github.com/kubernetes/publishing-bot/blob/master/cmd/publishing-bot/config/rules.go which define the rules.yaml config.

2023-08-16 04:29 UTC, palnabarun commented
/sig release
/priority important-longterm
/triage accepted

2023-08-16 04:29 UTC, palnabarun commented
/release-note none

2023-08-16 04:29 UTC, palnabarun commented
/ok-to-test

2023-08-18 07:37 UTC, akhilerm commented on hack/tools/.gitignore
> +verify/verify-publishing-bot
This may not be needed as we are not committing during the verify stage

2023-08-18 07:37 UTC, akhilerm commented on hack/tools/verify/verify-publishing-bot.go
> +	data := make(map[string]interface{})
https://github.com/kubernetes/publishing-bot/blob/master/cmd/publishing-bot/config/rules.go#L78 can be used for parsing as suggested above.

2023-08-18 07:37 UTC, akhilerm commented on hack/tools/verify/verify-publishing-bot.go
> +			uniqueLines[line] = true
Why do we need `uniqueLines` ?

2023-08-18 07:37 UTC, akhilerm commented on hack/tools/verify/verify-publishing-bot.go
> +		branch := branches[0].(map[interface{}]interface{})
This can be simplified by using the `RepositoryRules` struct mentioned above.

2023-08-18 07:37 UTC, akhilerm commented on hack/tools/verify/verify-publishing-bot.go
> +
Please add a comment why we need this check

2023-09-25 11:48 UTC, akhilerm commented on hack/tools/verify/verify-publishing-bot.go
> +			sourceDir := branchData["source"].(map[interface{}]interface{})["dir"].(string)
The dir field has been deprecated in favour of dirs. That change also have to be accomodated. Ref: https://github.com/kubernetes/publishing-bot/pull/337

2023-10-06 12:20 UTC, akhilerm commented
There are changes in the verify script that has been introduced as part of https://github.com/kubernetes/kubernetes/pull/120822. Can you please take care of that also in this PR?

2023-10-06 12:43 UTC, sbdtu5498 commented
I will take a look on them in the weekends

2023-10-24 19:17 UTC, BenTheElder commented on hack/make-rules/verify.sh
> -run-checks "${KUBE_ROOT}/hack/verify-*.py" python3
And that script is fine because it doesn't have non-stdlib dependencies

2023-10-24 19:18 UTC, BenTheElder commented on hack/make-rules/verify.sh
> +run-checks "${KUBE_ROOT}/hack/tools/verify/verify-publishing-bot" binary
+1, we should have a `verify-publishing-bot.sh` that handles the usual go env setup etc and can be invoked directly without using verify.sh

2024-02-04 08:18 UTC, closed without merging

2024-02-08 09:14 UTC, akhilerm commented
@sbdtu5498  Will you be able to take this up further ?