dra e2e: fix "reallocation works" flake
kubernetes/kubernetes pull request #119195
Opened 2023-07-10 10:23 UTC by pohly

#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

The main problem probably was that
https://github.com/kubernetes/kubernetes/pull/118862 moved creating the first pod before setting up the callback which blocks allocating one claim for that pod. This is racy because allocations happen in the background.

#### Which issue(s) this PR fixes:
Fixes #119175

#### Special notes for your reviewer:

The test also was unnecessarily complex and hard to read:
- The intended effect can be achieved with three instead of four claims.
- It wasn't clear which claim has "external-claim-other" as name. Using the claim variable avoids that.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

2023-07-10 13:10 UTC, pohly commented
/retest

2023-07-12 06:09 UTC, pohly commented
/assign @byako

2023-07-12 06:33 UTC, byako requested changes
So it is enough to fail allocation completely, without succeeding for some claims? Alright, it is also simpler with one claim.

2023-07-12 06:33 UTC, byako commented on test/e2e/dra/dra.go
> +				// Order is relevant here: each pod must be matched with itself
```suggestion
				// Order is relevant here: each pod must be matched with its
```

2023-07-12 09:21 UTC, pohly commented on test/e2e/dra/dra.go
> +				// Order is relevant here: each pod must be matched with itself
Fixed, thanks.

2023-07-12 11:43 UTC, pohly commented
> So it is enough to fail allocation completely, without succeeding for some claims?

Perhaps I don't understand, but of course a driver can fail allocation completely. There's no way how it can guarantee to allocate at least one claim.

2023-07-12 11:55 UTC, byako commented
I meant the test case, original implementation had pod with two claims for same driver, with one getting allocated, the other one failing after no more resources left. So I thought there had to be partial failure (one out of two claims failed allocation) to trigger reallocation.
Never mind.

2023-07-12 11:56 UTC, byako commented
/lgtm

2023-07-12 12:55 UTC, merged