Update cri-tools to v1.27.1
kubernetes/kubernetes pull request #119222
Opened 2023-07-11 08:41 UTC by git-jxj

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Updating cri-tools to the latest release.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```
Updated cri-tools to v1.27.1

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-07-11 08:58 UTC, git-jxj commented
/retest

2023-07-11 09:05 UTC, mengjiao-liu commented
/easycla

2023-07-11 09:11 UTC, saschagrunert commented
@git-jxj I had to update the release bucket to make the artifacts available, now they're there: https://console.cloud.google.com/storage/browser/k8s-artifacts-cri-tools/release/v1.27.1

2023-07-11 09:13 UTC, git-jxj commented
/retest

2023-07-11 09:15 UTC, saschagrunert commented
@git-jxj can you please sign-off the CLA?

2023-07-11 09:58 UTC, git-jxj commented
> @git-jxj can you please sign-off the CLA?

Done, thanks. PTAL

2023-07-11 10:06 UTC, saschagrunert commented
/ok-to-test

2023-07-11 10:07 UTC, saschagrunert requested changes

2023-07-11 10:07 UTC, saschagrunert commented on cluster/gce/gci/configure.sh
> +  local -r crictl_path="https://console.cloud.google.com/storage/browser/k8s-artifacts-cri-tools/release/${crictl_version}/crictl-${crictl_version}-linux-amd64.tar.gz"
We should leave that as-is.

2023-07-11 10:23 UTC, git-jxj commented on cluster/gce/gci/configure.sh
> +  local -r crictl_path="https://console.cloud.google.com/storage/browser/k8s-artifacts-cri-tools/release/${crictl_version}/crictl-${crictl_version}-linux-amd64.tar.gz"
fixed

2023-07-11 10:31 UTC, saschagrunert approved these changes
Thanks! LGTM when CI is happy as well.

2023-07-11 10:45 UTC, pacoxu commented
/lgtm
/assign @BenTheElder

2023-07-11 11:15 UTC, saschagrunert commented
/test pull-kubernetes-e2e-gce

2023-08-14 07:57 UTC, saschagrunert commented
Closing in favor of https://github.com/kubernetes/kubernetes/pull/119933

2023-08-14 07:57 UTC, closed without merging