e2e_apps: stop using deprecated framework.ExpectEqual
kubernetes/kubernetes pull request #119485
Opened 2023-07-21 03:17 UTC by carlory

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

e2e_apps: stop using deprecated framework.ExpectEqual

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/kubernetes/pull/115961

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-07-24 02:10 UTC, carlory commented
/assign @smarterclayton

2023-08-29 03:05 UTC, carlory commented
/retest-required

2023-09-11 02:45 UTC, carlory commented
/retest-required

2023-09-14 07:53 UTC, carlory commented
/test pull-kubernetes-e2e-kind

2023-09-16 13:56 UTC, carlory commented
/test pull-kubernetes-e2e-kind

2023-09-20 07:39 UTC, carlory commented
/assign @pohly

2023-09-25 08:33 UTC, carlory commented
/test pull-kubernetes-e2e-kind

2023-09-25 10:24 UTC, carlory commented
Can you take a look at it?

/cc @pohly

2023-09-27 11:20 UTC, pohly requested changes

2023-09-27 11:20 UTC, pohly commented on test/e2e/apps/rc.go
> +			gomega.Expect(testRcPatched.ObjectMeta.Labels["test-rc"]).To(gomega.Equal("patched"), "failed to patch RC")
`gomega.HaveKeyWithValue` would be useful here, too.

2023-09-30 19:36 UTC, carlory commented
/test pull-kubernetes-node-e2e-containerd
/test pull-kubernetes-node-e2e-containerd

2023-10-01 03:44 UTC, carlory commented
/test pull-kubernetes-e2e-kind-ipv6
/test pull-kubernetes-e2e-kind

2023-10-02 16:59 UTC, pohly approved these changes
/lgtm
/approve

Thanks!

2023-10-02 18:10 UTC, pohly commented
/retest

2023-10-02 18:45 UTC, merged