Hardening LB SourceRanges filtering for IPVS proxier
kubernetes/kubernetes pull request #119791
Opened 2023-08-07 08:11 UTC by aroradaman

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #119656

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-08-07 08:12 UTC, aroradaman commented
/hold code-freeze

2023-08-07 08:25 UTC, aroradaman commented on pkg/proxy/ipvs/proxier.go
> +		)
Tried this locally on kind, every iptables-restore call is creating a duplicate entry in iptable rules. 

After few minutes I ended up with 18 exact same rules 😔 

```
╰─$ docker exec -it kind-worker /bin/bash                                                                                                                                                                       130 ↵
root@kind-worker:/# iptables-save | grep ipvs 
-A INPUT -m comment --comment "kubernetes ipvs access filter" -j KUBE-IPVS-FILTER
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
-A OUTPUT -s 172.18.255.200/32 -m ipvs --vaddr 172.18.255.200 -j DROP
root@kind-worker:/# 
```

Also, checked the `proxier.filterRules` it only has single entry for this rule. I guess duplication has something to do with the flags which we pass to restore call.

2023-10-07 14:23 UTC, aroradaman commented
/test all

2023-10-07 14:27 UTC, aroradaman commented
/test all

2023-10-07 15:25 UTC, aroradaman commented
/test all

2023-10-07 17:30 UTC, aroradaman commented
/test pull-kubernetes-e2e-kind-ipv6

2023-10-08 08:02 UTC, uablrek commented
/retest

2023-10-08 11:52 UTC, uablrek approved these changes

2023-10-08 11:53 UTC, uablrek commented on pkg/proxy/ipvs/proxier.go
> +				} else {
Forget the above. The use is different from iptables

2023-10-08 12:19 UTC, uablrek commented
I have tested that access from the node is rejected if the nodeIp is _not_ in `loadBalancerSourceRanges`, and that it works if the nodeIP CIDR is in it.

I have not tested with a POD with `hostNetwork:true`, but that should be the same as from a node. To use `hostNetwork:true` makes it possible to write an e2e test for this, but IMO it should not be required in this PR, but perhaps in a separate one.

Here are some iptables dumps for info:
```
# iptables -L
...
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-IPVS-OUT-FILTER  all  --  anywhere             anywhere             /* kubernetes ipvs access filter */
KUBE-FIREWALL  all  --  anywhere             anywhere            
...
Chain KUBE-IPVS-OUT-FILTER (1 references)
target     prot opt source               destination         
DROP       all  --  10.0.0.10            anywhere             vaddr 10.0.0.10
# iptables -S
...
-N KUBE-IPVS-OUT-FILTER
...
-A KUBE-IPVS-OUT-FILTER -s 10.0.0.10/32 -m ipvs --vaddr 10.0.0.10 -j DROP
```

2023-10-08 14:12 UTC, uablrek requested changes
Seems like the port must be considered

2023-10-08 14:24 UTC, uablrek commented
Sorry, I was too hasty on the "approve" button. The port must be included. Consider this case:
```yaml
kind: Service
metadata:
  name: alpine2
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine2
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 8001
    name: nc
```
With loadBalancerIP `10.0.0.10`. The service is accessible from a K8s node on address `10.0.0.10:8001`. But if _another_ service is created:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: alpine1
spec:
  loadBalancerSourceRanges:
  - "192.168.2.0/24"
  - "fd00::c0a8:200/120"
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine1
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 7001
    name: nc
```
And is _also_ assigned the loadBalancerIP `10.0.0.10`, then the first service is not accessible any more from K8s nodes.

This works as expected with `proxy-mode=iptables`, access from nodes still works on the firsts service even when the second is created with the same loadBalancerIP.

I am not at all sure that this bug is worth solving. Nobody has complained, and the nft proxier is on the way. But if this is not solved the constraint should be documented with something like:
```
For proxy-mode=ipvs the loadBalancerSourceRanges in can not be used to deny access to the service from
K8s nodes or from PODs with "hostNetwork:true".
```

2023-10-08 14:31 UTC, uablrek commented
It might be worth introducing a new "ipset". But I don't know...

2023-10-08 14:50 UTC, aroradaman commented
> It might be worth introducing a new "ipset". But I don't know...

I initially thought of hash:ip,port,ip set only but I was not sure if could match ipset on ipvs extension.

2023-10-08 15:30 UTC, aroradaman commented
@uablrek I updated the rules to match on IP + Port + Protocol.

2023-10-08 16:56 UTC, aroradaman commented
/retest

2023-10-11 05:57 UTC, uablrek approved these changes

2023-10-11 05:57 UTC, uablrek commented
IMO a very tidy PR :+1: 

/lgtm

2023-10-11 06:01 UTC, uablrek commented
/release-note-none

2023-10-11 08:27 UTC, aroradaman commented
/hold cancel
I added the hold label for code freeze before https://github.com/kubernetes/kubernetes/pull/119791#issuecomment-1667400344

2023-10-11 09:46 UTC, merged