fix link failure for changelog
kubernetes/kubernetes pull request #119781
Opened 2023-08-06 02:55 UTC by huweihuang

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

fix link failure for changelog

2023-08-07 03:05 UTC, deepak4566 requested changes
Hey @huweihuang  thanks for ur contribution 
But I think u need to place an relative link rather than absolute link because some builds doesn't happen without the relative link so I think u can understand the issue

2023-08-07 05:48 UTC, pacoxu commented
/lgtm
/assign saschagrunert
/release-note-none
/priority backlog
/triage accepted

2023-08-07 05:48 UTC, pacoxu approved these changes

2024-05-06 07:17 UTC, saschagrunert approved these changes

2024-05-06 07:52 UTC, pacoxu commented
/test pull-kubernetes-verify-lint

2024-05-06 09:23 UTC, merged