Updated staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
kubernetes/kubernetes pull request #119872
Opened 2023-08-09 19:07 UTC by akash-kumar-saw

Issue Number :  https://github.com/kubernetes/kubectl/issues/1455,

Changed the default kubectl autoscale from using apiVersion: autoscale/v1 to apiVersion: autoscale/v2.

2023-08-14 06:59 UTC, shivanshu1333 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +
can you please relevant API docs here to help review this change, thanks!

2023-08-14 07:00 UTC, shivanshu1333 commented
/ok-to-test

2023-08-14 07:01 UTC, shivanshu1333 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +		}
can you please add links to relevant API docs here to help review this change, thanks!

2023-08-17 08:57 UTC, soltysh requested changes
Lastly, can you make sure to add even a small unit test ensuring that we are creating the correct values for HPA? Have a look at other simple commands (like one of create sub-commands for examples).

Once it's all done, please squash creating a single commit and ping me on slack for another review.

2023-08-17 08:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +            Name: "cpu-percent",
This should be `corev1.ResourceCPU`

2023-08-17 08:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +};
Please make sure this is valid code, you have too many closing brackets.

2023-09-20 22:33 UTC, akash-kumar-saw commented
Hiii @soltysh,

I have successfully added a unit test for the HPA. You can review it and can approve it.

Thanks for your precious time : )

2024-03-21 19:20 UTC, closed without merging