[e2e_apimachinery] stop using deprecated framework.ExpectNotEqual
kubernetes/kubernetes pull request #119961
Opened 2023-08-16 04:51 UTC by bzsuni

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
e2e_apimachinery : stop using deprecated framework.ExpectNotEqual

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/kubernetes/pull/115961

2023-08-17 16:48 UTC, jiahuif commented on test/e2e/apimachinery/custom_resource_definition.go
> +				gomega.Expect(expected).NotTo(gomega.Equal(nil))
There is a special ToBe(NonNil), can save a bit brain power for the reader.

2023-08-22 06:24 UTC, pohly requested changes
Can you do this change in all of `test/e2e` and `test/e2e_node`? Then we only need to review one PR.

2023-08-23 03:11 UTC, bzsuni commented
> Can you do this change in all of `test/e2e` and `test/e2e_node`? Then we only need to review one PR.

Thank you for your comment. I wanted to use the directory module to divide it. Is it more organized?

2023-08-23 06:37 UTC, pohly commented
It depends on owners, complexity and size. In this case the change is more related to SIG Testing than any individual SIG, therefore it makes more sense for me to review and approve. It's ~100 lines that need to be changed, which is manageable for a single PR.

2023-09-05 05:01 UTC, bzsuni commented
/retest-required

2023-09-05 06:04 UTC, bzsuni commented
I have made a modification, and there are some errors reported by ci, but it does not seem to be related to pr? 
If you have the time, please help me rereview this pr, thanks @pohly

2023-09-05 06:42 UTC, bzsuni commented
/retest-required

2023-09-05 07:01 UTC, carlory commented
/test pull-kubernetes-e2e-capz-windows-master

2023-09-05 08:08 UTC, carlory commented
/test pull-kubernetes-e2e-capz-windows-master

2023-09-05 09:12 UTC, closed without merging

2023-09-05 09:12 UTC, bzsuni commented
confilict with other pr