add UT fot storageclass
kubernetes/kubernetes pull request #119948
Opened 2023-08-15 11:11 UTC by liyuerich

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

add UT for kubernetes/pkg/volume/util/storageclass, UT coverage can increase from 30.1% to 32.7%

#### Which issue(s) this PR fixes:

Fixes # NONE

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```
NONE
```

2023-08-15 11:12 UTC, liyuerich commented
/cc @carlory ,  could you please help to review this PR?

2023-08-16 02:02 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +func TestGetDefaultClass(t *testing.T) {
A better pattern to write test cases in go:

```go
func TestXXX(t *testing.T) {
  testCases := []struct {
    name string     // the name of a test case
    xxx XXX         // input args
    expectYYY YYY   // expect something
  }{
    {},
    {}
  }

  for _, testCase := range testCases {
    t.Run(testCase.name, func (t *testing.T){
      // do something
    })
  }
}
```

2023-08-16 02:42 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +type MockLister struct {
An example (mock lister for storageclass):

```go
informerFactory := informers.NewSharedInformerFactory(nil, controller.NoResyncPeriodFunc())
for _, c := range testCase.classes {
  informerFactory.Storage().V1().StorageClasses().Informer().GetStore().Add(c)
}
lister :=  informerFactory.Storage().V1().StorageClasses().Lister()
```

2023-08-17 10:24 UTC, liyuerich commented
/cc @carlory , thanks your comments. could you please help to review again?

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +		sc1 *storagev1.StorageClass = &storagev1.StorageClass{
```suggestion
		sc1 = &storagev1.StorageClass{
```

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +		sc2 *storagev1.StorageClass = &storagev1.StorageClass{
ditto

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +		sc3 *storagev1.StorageClass = &storagev1.StorageClass{
ditto

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +		sc4 *storagev1.StorageClass = &storagev1.StorageClass{
ditto

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +		sc5 *storagev1.StorageClass = &storagev1.StorageClass{
ditto

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +				t.Logf("c %v", c)
remove this message

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +
remove redundant empty line

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +			name:    "three default storage class, newest frist,  class name second",
split this to two. one for different creationTimestamp. another for different name with same creationTimestamp

2023-08-17 10:29 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +				t.Errorf("Expected no error got %v", err)
```suggestion
				t.Errorf("Expected no error, got %v", err)
```

2023-08-17 10:30 UTC, carlory commented
/ok-to-test

2023-08-17 10:31 UTC, carlory commented
/release-label none

2023-08-17 10:32 UTC, carlory commented
/release-note-label none

2023-08-17 10:55 UTC, liyuerich commented
/cc @carlory , thanks your comments. could you please help to review again?

2023-08-18 01:01 UTC, liyuerich commented
/retest

2023-08-18 06:05 UTC, carlory requested changes
some suggesting changes, otherwise LGTM.

2023-08-18 06:05 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +			name:    "two default storage class, same cteate time, return ascending order frist",
```suggestion
			name:    "two default storage class with same creation timestamp",
```

2023-08-18 06:05 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +			name:    "two default storage class, different create time, return  newest frist",
```suggestion
			name:    "two default storage class with different creation timestamp",
```

2023-08-18 06:05 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +			if !reflect.DeepEqual(actual, tc.expect) {
```suggestion
			if tc.expect != actual {
```

2023-08-18 06:45 UTC, carlory commented
/release-note none

2023-08-18 08:24 UTC, carlory commented on pkg/volume/util/storageclass_test.go
> +	)
```suggestion
	var (
	        t1 = time.Now()
	        t2 = time.Now().Add(1 * time.Hour)

		sc1 = &storagev1.StorageClass{
			ObjectMeta: metav1.ObjectMeta{
				Name: "my-storage-class1",
				Annotations: map[string]string{
					"a": "b",
				},
			},
		}
		sc2 = &storagev1.StorageClass{
			ObjectMeta: metav1.ObjectMeta{
				Name: "my-storage-class2",
				Annotations: map[string]string{
					"a": "b",
				},
			},
		}

		sc3 = &storagev1.StorageClass{
			ObjectMeta: metav1.ObjectMeta{
				Name: "my-storage-class3",
				Annotations: map[string]string{
					IsDefaultStorageClassAnnotation: "true",
				},
				CreationTimestamp: metav1.Time{Time: t1},
			},
		}

		sc4 = &storagev1.StorageClass{
			ObjectMeta: metav1.ObjectMeta{
				Name: "my-storage-class4",
				Annotations: map[string]string{
					IsDefaultStorageClassAnnotation: "true",
				},
				CreationTimestamp: metav1.Time{Time: t2},
			},
		}

		sc5 = &storagev1.StorageClass{
			ObjectMeta: metav1.ObjectMeta{
				Name: "my-storage-class5",
				Annotations: map[string]string{
					IsDefaultStorageClassAnnotation: "true",
				},
				CreationTimestamp: metav1.Time{Time: t2},
			},
		}
	)
```

2023-08-21 01:25 UTC, liyuerich commented
/retest-required

2023-08-21 05:26 UTC, carlory commented
/lgtm

/assign @thockin

2023-08-22 02:54 UTC, carlory commented
/release-note-none

2023-08-22 15:59 UTC, thockin reviewed
Thanks!

/lgtm
/approve

2023-08-22 17:03 UTC, merged

2023-08-24 02:45 UTC, liyuerich commented
thanks @carlory  and @thockin