Support multiarch/platfrom in find-release-tars
kubernetes/kubernetes pull request #120100
Opened 2023-08-22 07:23 UTC by ruquanzhao

Signed-off-by: Ruquan Zhao ruquan.zhao@arm.com

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR fixes `find-release-tars` to look for right path when env `KUBE_BUILD_PLATFROMS` is set.
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-08-22 08:02 UTC, ruquanzhao commented
relelated issue: https://github.com/kubernetes-sigs/kubetest2/pull/240

2023-08-22 09:30 UTC, upodroid requested changes
Can you fix these lint errors please? thanks

2023-08-22 09:30 UTC, upodroid commented on cluster/common.sh
> +  OS=$(cut -d'/' -f1 <<< $SERVER_PLATFORM)
```suggestion
  OS=$(cut -d'/' -f1 <<< "${SERVER_PLATFORM}")
```

2023-08-22 09:30 UTC, upodroid commented on cluster/common.sh
> +  SERVER_BINARY_TAR=$(find-tar kubernetes-server-${OS}-${ARCH}.tar.gz)
```suggestion
  SERVER_BINARY_TAR=$(find-tar kubernetes-server-"${OS}"-"${ARCH}".tar.gz)
```

2023-08-22 20:10 UTC, dims commented
/approve
/lgtm

2023-08-22 23:23 UTC, upodroid commented
/sig testing
/triage accepted

2023-08-23 00:08 UTC, upodroid commented
/retest

2023-08-23 00:36 UTC, merged