remove PruneWhitelist, use prune-allowlist instead
kubernetes/kubernetes pull request #120246
Opened 2023-08-30 02:16 UTC by pacoxu

/kind cleanup
/kind deprecation
Follow up of  https://github.com/kubernetes/kubernetes/pull/117573 and https://github.com/kubernetes/kubernetes/pull/113116

```release-note
kubectl: remove deprecated flag prune-whitelist for apply, use flag prune-allowlist instead.
```

2023-08-30 02:18 UTC, pacoxu commented
/priority important-soon
/assign @brianpursley @KnVerey

2023-08-30 03:00 UTC, pacoxu commented
/test pull-kubernetes-node-e2e-containerd

2023-10-20 19:19 UTC, brianpursley requested changes
Found a couple more places in the comments that I noticed, so we might as well change it everywhere to avoid any potential confusion in the future.

Otherwise, looks OK.

2023-10-20 19:19 UTC, brianpursley commented on test/cmd/apply.sh
>    # apply svc and don't prune pod a by overwriting whitelist
```suggestion
  # apply svc and don't prune pod a by overwriting allowlist
```

2023-10-20 19:19 UTC, brianpursley commented on test/cmd/apply.sh
>    # apply svc and prune pod a with default whitelist
```suggestion
  # apply svc and prune pod a with default allowlist
```

2023-11-24 05:05 UTC, ardaguclu commented
This patch looks good to me. Could you please change the `whitelist` in here to `allowlist` https://github.com/kubernetes/kubernetes/blob/eb32969ab8f3d1455c33a595bba5b3ce4d8a03b8/staging/src/k8s.io/kubectl/pkg/cmd/diff/diff.go#L169?

/approve
/triage accepted

2023-12-15 03:51 UTC, pacoxu commented on test/cmd/apply.sh
>    # apply svc and don't prune pod a by overwriting whitelist
Updated.

2023-12-15 03:51 UTC, pacoxu commented
> This patch looks good to me. Could you please change the `whitelist` in here to `allowlist`

Updated.

2023-12-15 05:57 UTC, ardaguclu commented
/lgtm

2023-12-15 06:02 UTC, merged

2024-06-03 09:04 UTC, miss15 commented
的