e2e_network:stop using deprecated framework.ExpectNotEqual
kubernetes/kubernetes pull request #120403
Opened 2023-09-04 12:33 UTC by wlq1212

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
e2e_network:stop using deprecated framework.ExpectNotEqual

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/pull/115961

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

2023-09-04 14:01 UTC, HirazawaUi commented
/ok-to-test

2023-09-05 05:21 UTC, wlq1212 commented
/test pull-kubernetes-verify

2023-09-05 10:09 UTC, wlq1212 commented
/retest

2023-09-05 10:29 UTC, carlory commented on test/e2e/network/ingress.go
> +			gomega.Expect(ing.DeletionTimestamp).ToNot(gomega.BeNil(), fmt.Sprintf("expected deletionTimestamp, got nil on step: %q, ingress: %+v", msg, ing))
```suggestion
			gomega.Expect(ing.DeletionTimestamp).ToNot(gomega.BeNil(), "expected deletionTimestamp, got nil on step: %q, ingress: %+v", msg, ing)
```

2023-09-05 10:31 UTC, carlory commented on test/e2e/network/service.go
> +			gomega.Expect(port.NodePort).ToNot(gomega.HaveValue(gomega.Equal(0)), "NodePort service failed to allocate NodePort for Port %s", port.Name)
why not?

```suggestion
			gomega.Expect(port.NodePort).ToNot(gomega.BeZero(), "NodePort service failed to allocate NodePort for Port %s", port.Name)
```

2023-09-06 02:03 UTC, wlq1212 commented on test/e2e/network/service.go
> +			gomega.Expect(port.NodePort).ToNot(gomega.HaveValue(gomega.Equal(0)), "NodePort service failed to allocate NodePort for Port %s", port.Name)
resolved

2023-09-06 03:43 UTC, wlq1212 commented
/test pull-kubernetes-node-e2e-containerd

2023-09-06 05:37 UTC, wlq1212 commented
/test pull-kubernetes-node-e2e-containerd

2023-09-06 06:41 UTC, carlory commented
/lgtm

/assign caseydavenport

2023-09-12 08:59 UTC, wlq1212 commented
/cc  @caseydavenport could you help to review this PR?

2023-09-12 09:00 UTC, carlory commented
/assign @pohly

2023-09-12 12:13 UTC, pohly requested changes
/lgtm cancel

2023-09-12 12:13 UTC, pohly commented on test/e2e/network/loadbalancer.go
> +		gomega.Expect(acceptPod.Status.PodIP).ToNot(gomega.Equal(""))
The old `framework.ExpectNotEqual` hasn't been removed yet here.

2023-09-13 06:41 UTC, wlq1212 commented
/test pull-kubernetes-e2e-gci-gce-ipvs
/test pull-kubernetes-integration

2023-09-13 07:42 UTC, wlq1212 commented
/test pull-kubernetes-e2e-gci-gce-ipvs

2023-09-13 07:50 UTC, pohly commented on test/e2e/network/loadbalancer.go
> +		gomega.Expect(acceptPod.Status.PodIP).ToNot(gomega.Equal(""))
```suggestion
		gomega.Expect(acceptPod.Status.PodIP).ToNot(gomega.BeEmpty())
```

2023-09-13 10:16 UTC, wlq1212 commented on test/e2e/network/loadbalancer.go
> +		gomega.Expect(acceptPod.Status.PodIP).ToNot(gomega.Equal(""))
thanks

2023-09-14 05:49 UTC, pohly approved these changes
/lgtm
/approve

2023-09-14 08:00 UTC, merged