fix: exclusive CPUs removed from deleted Pod and put back in the defaultCPUSet
kubernetes/kubernetes pull request #120661
Opened 2023-09-14 09:32 UTC by likakuli

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Exclusive CPUs not removed from deleted Pod and put back in the defaultCPUSet.  This will lead to some burstable or besteffort pod can't use spare cpus.
#### Which issue(s) this PR fixes:

Fixes #107074

#### Special notes for your reviewer:
This bug is caused by the pr https://github.com/kubernetes/kubernetes/pull/103979 which is used to fix the issue https://github.com/kubernetes/kubernetes/issues/103952. The root cause is that the result of `GetActivePods` not contains pods in admission stage. So it add a `pendingAdmissionPod` to record it and use it in `removeStaleState`.  

There is another pr #104577 which fixed the problem too and the result of `GetActivePods` will contains pods in admission stage.
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-09-14 09:33 UTC, likakuli commented
/sigs node

2023-09-14 09:49 UTC, fanhaouu commented
LGTM

2023-09-14 09:49 UTC, fanhaouu commented
NB

2023-09-15 06:10 UTC, likakuli commented
kindly ping @smarterclayton, can you please help review this thx

2023-09-15 09:26 UTC, ffromani commented
hi @likakuli thanks for this PR! Could you maybe please elaborate a bit why you want to revert https://github.com/kubernetes/kubernetes/pull/103979 ? Do we know the original issue #103979 fixed is no longer relevant?

2023-09-15 09:49 UTC, likakuli commented
> Do we know the original issue #103979 fixed is no longer relevant?

https://github.com/kubernetes/kubernetes/pull/103979#issuecomment-904836223, the root cause of #103979 bas been fixed by https://github.com/kubernetes/kubernetes/pull/104577 already.

2023-09-15 09:57 UTC, ffromani commented
Is not obvious to me why, though. The scenario outlined in https://github.com/kubernetes/kubernetes/issues/103952 seems still relevant to me, because while a pod is being admitted, its container cannot be active yet, it's just too early still. I'll do my homework and review again the related changes, though

2023-09-15 10:01 UTC, likakuli commented
> I'll do my homework and review again the related changes, though

thx. After https://github.com/kubernetes/kubernetes/pull/104577, the result of `activePods` will contains pods in admission stage.

2023-09-15 10:04 UTC, ffromani commented
right, this should be it:
```
Second, the previous check introduced with the pod worker lifecycle
ownership changes was subtly wrong for the admission use case.
Admission has to include pods that haven't yet hit the pod worker,
which CouldHaveRunningContainers was filtering out (because the
pod worker hasn't seen them). Introduce a weaker check -
IsPodKnownTerminated() - that returns true only if the pod is in
a known terminated state (no running containers AND known to pod
worker). This weaker check may only be called from components that
need admitted pods, not other kubelet subsystems.
```

2023-09-15 10:08 UTC, ffromani commented
/test pull-kubernetes-node-kubelet-serial-cpu-manager

thanks for the patient explanation. I think you are likely right. Let's however make sure the original issue stay fixed, at very least ensuring e2e tests don't regress (extending them if needed)

2023-09-15 15:34 UTC, bart0sh commented
/ok-to-test

2023-09-15 15:35 UTC, bart0sh commented
/triage accepted
/priority important-longterm

2023-09-16 00:13 UTC, likakuli commented
/retest

2023-09-18 10:21 UTC, likakuli commented
kindly ping @ffromani

2023-09-18 10:23 UTC, ffromani commented
I'm more and more convinced the change is good.
The serial test outcome looks good. Need to run the other lanes and do verify we have sufficient coverage to prevent regressions resurfacing.

2023-09-18 10:30 UTC, likakuli commented
Is it possible to involve the old pr authors to verify this? 

I think this is ok and i have also tested it by myself.

2023-09-18 11:03 UTC, ffromani commented
> Is it possible to involve the old pr authors to verify this?

We can tag @cynepco3hahue but I'm afraid they moved to different projects.

> I think this is ok and i have also tested it by myself.

Sure, but the projects needs to be self-sustaining as much as possible, so let's make sure the tests are sufficient - and passing. I'll keep working at quite high priority in this issue and I think we're in a good track to merge.
OFC nothing prevents other contributors to LGTM earlier if they feel so.

2023-09-18 13:14 UTC, ffromani commented
/assign @klueska

2023-09-19 02:16 UTC, likakuli commented
/retest

2023-09-19 07:11 UTC, ffromani commented
neither failures are critical for this PR (actually not related).
xref: https://github.com/kubernetes/kubernetes/issues/120725

2023-09-21 08:40 UTC, swatisehgal commented
/test pull-kubernetes-node-kubelet-serial-topology-manager
https://github.com/kubernetes/kubernetes/pull/120773 is now merged so let's see if that helps.

2023-09-22 03:38 UTC, likakuli commented
seems timeout also. do i need to rebase this pr with master branch before retest?

2023-09-22 06:28 UTC, ffromani commented
> seems timeout also. do i need to rebase this pr with master branch before retest?

we're working on fixing the lanes (esp. the topology manager ones) and having green runs is nice, but nothing suggests the issues are caused by this PR. Atm no action is needed here.

2023-09-25 09:39 UTC, likakuli commented
kindly ping @klueska, could you please help to review this, thx

2023-09-25 13:32 UTC, likakuli commented
kindly ping @smarterclayton, could you please help to review this pr, thx

2023-10-02 11:28 UTC, ffromani commented
/cc @mrunalp

2023-10-23 12:10 UTC, likakuli commented
any update?

2023-10-26 11:19 UTC, ffromani commented
the only update I can provide is that "serial-hugepages" failure is not relevant, and that the topology manager failure should be fixed thanks to https://github.com/kubernetes/kubernetes/pull/121442 . If you resubmit, I'll re-add the LGTM.

2023-10-26 12:33 UTC, swatisehgal commented
/test pull-kubernetes-node-kubelet-serial-topology-manager

2023-12-16 12:18 UTC, likakuli commented
/retest

2024-01-10 04:18 UTC, pacoxu commented
A release note may be needed. 
And this needs a backport. @SergeyKanzhelev @bart0sh

2024-01-17 16:02 UTC, ffromani commented
/lgtm

it seems last change was a rebase. Same caveats per https://github.com/kubernetes/kubernetes/pull/120661#issuecomment-1723386569 apply

2024-04-17 16:28 UTC, ffromani commented
/remove-lifecycle stale

still relevant

2024-04-29 10:03 UTC, likakuli commented
what can i do to push forward this pr?

2024-04-29 10:25 UTC, ffromani commented
> what can i do to push forward this pr?

we need approver review, let's try to gently ping on community channels

2024-06-04 06:23 UTC, ffromani commented
/lgtm

seems like a rebase

2024-06-04 09:23 UTC, pacoxu commented
/assign @mrunalp @klueska @SergeyKanzhelev  
for approval

2024-07-29 13:06 UTC, ffromani commented
ping @SergeyKanzhelev @mrunalp @klueska

2024-09-17 12:07 UTC, ffromani commented
ping

2024-09-17 20:41 UTC, SergeyKanzhelev commented
A few comments:

1. Release note: can you please update in a form of what was the bug and what will be the new behavior. So it will be clear for people reading it what was fixed.
2. Is priority accurate? Is there any need to cherry-pick this fix? Or the bug was there for too long to justify the priority bump?
3. Can any test be added that demonstrates the bug be added? Perhaps some e2e test that will be able to catch a possible regression here. Right now I only see unit tests, which I don't think demonstrate the bug and rather validate some internal details.

2024-09-18 04:13 UTC, ffromani commented
>     2. Is priority accurate? Is there any need to cherry-pick this fix? Or the bug was there for too long to justify the priority bump?

I'm unsure between this priority and `backlog`. I don't think this warrants a backport; I have investigated some user-affected flows (also in RH) and the impacted flows are fairly well defined and relatively rare.
And yes, this bug is present since quite some timew.

>      3. Can any test be added that demonstrates the bug be added? Perhaps some e2e test that will be able to catch a possible regression here. Right now I only see unit tests, which I don't think demonstrate the bug and rather validate some internal details.

This is a good point, I like the direction about adding more e2e tests. I think there's room to crete a valid e2e test and I can help with the details.

2024-09-25 16:02 UTC, ffromani commented
> > ```
> > 2. Is priority accurate? Is there any need to cherry-pick this fix? Or the bug was there for too long to justify the priority bump?
> > ```
> 
> I'm unsure between this priority and `backlog`. I don't think this warrants a backport; I have investigated some user-affected flows (also in RH) and the impacted flows are fairly well defined and relatively rare. And yes, this bug is present since quite some timew.
> 
> > ```
> >  3. Can any test be added that demonstrates the bug be added? Perhaps some e2e test that will be able to catch a possible regression here. Right now I only see unit tests, which I don't think demonstrate the bug and rather validate some internal details.
> > ```
> 
> This is a good point, I like the direction about adding more e2e tests. I think there's room to crete a valid e2e test and I can help with the details.

I got a test which proves the point by side effect in https://github.com/kubernetes/kubernetes/pull/127506. I'm not sure is worth a more targeted test, but I'm open to suggestions.

2024-10-02 07:04 UTC, ffromani commented
@likakuli howdy! we just miss a e2e test here. Can you please maybe borrow this code from me https://github.com/kubernetes/kubernetes/pull/127506/files#diff-897688174d4d6c5ec8b4080a2bbeeddc9e5442781586de6154a32b0b80cfc336R199 and add to your PR?
Or, if you prefer, feel free to reimplement any test to mine. That should be sufficient to demonstrate the bug and the fix.

2024-10-02 07:09 UTC, likakuli commented
> @likakuli howdy! we just miss a e2e test here. Can you please maybe borrow this code from me https://github.com/kubernetes/kubernetes/pull/127506/files#diff-897688174d4d6c5ec8b4080a2bbeeddc9e5442781586de6154a32b0b80cfc336R199 and add to your PR? Or, if you prefer, feel free to reimplement any test to mine. That should be sufficient to demonstrate the bug and the fix.

Thanks! I will do it after holiday

2024-10-02 07:16 UTC, ffromani commented
> > @likakuli howdy! we just miss a e2e test here. Can you please maybe borrow this code from me https://github.com/kubernetes/kubernetes/pull/127506/files#diff-897688174d4d6c5ec8b4080a2bbeeddc9e5442781586de6154a32b0b80cfc336R199 and add to your PR? Or, if you prefer, feel free to reimplement any test to mine. That should be sufficient to demonstrate the bug and the fix.
> 
> Thanks! I will do it after holiday

cool, thanks! Meanwhile I'll work a bit on extracting my own test and validating, so you can easily use it or not as you see fit.

2024-10-02 10:01 UTC, ffromani commented
ok, good news: #120661 fixes the test I added in https://github.com/kubernetes/kubernetes/pull/127506/files#diff-897688174d4d6c5ec8b4080a2bbeeddc9e5442781586de6154a32b0b80cfc336R199 , hence the latter (or an amended version of) can be used to validate the former

2024-10-05 07:09 UTC, SergeyKanzhelev commented
@ffromani @likakuli let me know how you want to proceed on those PRs in terms of ordering

2024-10-08 10:29 UTC, ffromani requested changes
mind adding `Co-authored-by: Francesco Romani <fromani@redhat.com>`  before/after the `Signed-off-by` line in the test commit message?

2024-10-08 10:30 UTC, ffromani commented
/test pull-kubernetes-node-kubelet-serial-containerd
/test pull-kubernetes-node-kubelet-serial-containerd-sidecar-containers
/test pull-kubernetes-node-kubelet-serial-cpu-manager
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2
/test pull-kubernetes-node-kubelet-serial-hugepages
/test pull-kubernetes-node-kubelet-serial-memory-manager
/test pull-kubernetes-node-kubelet-serial-topology-manager

2024-10-08 10:53 UTC, ffromani commented
the test failure is real, investigating

2024-10-08 10:59 UTC, ffromani commented
> the test failure is real, investigating

ok, silly me: the test can't work till we actually add the metric, which is the whole point of my PR in the first place. At this point is probably easier to cherry-pick the fix from @likakuli in my own PR :\

2024-10-08 11:18 UTC, likakuli commented
> ok, silly me: the test can't work till we actually add the metric, which is the whole point of my PR in the first place. At this point is probably easier to cherry-pick the fix from @likakuli in my own PR :\

haha,can cherry-pick this PR If needed

2024-10-09 13:10 UTC, ffromani commented
> > ok, silly me: the test can't work till we actually add the metric, which is the whole point of my PR in the first place. At this point is probably easier to cherry-pick the fix from @likakuli in my own PR :\
> 
> haha,can cherry-pick this PR If needed

sure, done! https://github.com/kubernetes/kubernetes/pull/127506#issuecomment-2399543876

2024-10-31 17:09 UTC, haircommander commented
this looks to be done in https://github.com/kubernetes/kubernetes/pull/127506 should we close this?

2024-10-31 18:50 UTC, ffromani commented
/close

reason: https://github.com/kubernetes/kubernetes/pull/120661#issuecomment-2399530498

2024-10-31 18:50 UTC, closed without merging