set maxLength to longest enum.
kubernetes/kubernetes pull request #121085
Opened 2023-10-09 18:09 UTC by jiahuif

#### What type of PR is this?
/kind bug
/kind feature

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2023-10-09 23:31 UTC, jiahuif commented
/assign @cici37

2023-10-10 20:18 UTC, jiahuif commented
/triage accepted

2023-10-11 03:10 UTC, liggitt commented
does CEL still run if an enum value fails enum validation, or does that short-circuit?

2023-10-11 17:08 UTC, cici37 commented on staging/src/k8s.io/apiserver/pkg/cel/common/schemas.go
> +			if len(s.Enum()) > 0 {
If maxLength had been set by the user, then it should be prioritized over the one we set?

2023-10-12 19:37 UTC, cici37 commented
@jiahuif Could you add `NotSupported` error into the blockingErr list to short-circuit CEL validation for enum err in this PR?
https://github.com/kubernetes/kubernetes/blob/338c3a0fc7a8ad70b4cf4403e6ece222d59bc53b/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/strategy.go#L309-L317

2023-10-17 17:12 UTC, cici37 commented
/lgtm
/approve
/assign @jpbetz 
if you have time to approve? Thank you!

2023-10-17 17:43 UTC, jpbetz requested changes
One very minor request then LGTM

2023-10-17 18:16 UTC, jiahuif commented on staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/compilation_test.go
> +func genEnumWithRuleAndValues(rule string, values ...string) func(maxLength *int64) *schema.Structural {
Short answer is that the rest of the test requires that a function be returned. I've added comments to explain this.

2023-10-17 18:32 UTC, jiahuif commented
/retest

2023-10-17 18:59 UTC, jpbetz commented
/approve

2023-10-17 19:39 UTC, jiahuif commented
/retest

2023-10-17 19:39 UTC, cici37 commented
/lgtm
/test pull-kubernetes-conformance-kind-ga-only-parallel

2023-10-17 21:28 UTC, merged