KEP-4222: Restrict supported media types for new apiservers.
kubernetes/kubernetes pull request #121325
Opened 2023-10-18 15:02 UTC by benluddy

This is to prevent the enablement of new data formats (CBOR) in the early stages of phased implementation.

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/61a31ed7c7be459ab14dc5fe3132d3b4cd3aa00c/keps/sig-api-machinery/4222-cbor-serializer/README.md#phased-implementation
```

2023-10-18 17:20 UTC, deads2k commented
This looks reasonable to me.  If a consumer is broken, we could add a direct code method to skip.  But I doubt people wrote customer serializers before and this is very clear.

2023-10-18 21:43 UTC, benluddy commented
Proof PR https://github.com/kubernetes/kubernetes/pull/121334 job https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121334/pull-kubernetes-e2e-kind/1714750722723024896:

> 2023-10-18T21:27:55.596216356Z stderr F E1018 21:27:55.596086       1 run.go:74] "command failed" err="refusing to create new apiserver \"apiextensions-apiserver\" with support for media type \"foo/bar\" (allowed media types are: application/json, application/yaml, application/vnd.kubernetes.protobuf)"

2023-10-19 11:40 UTC, deads2k commented
Proof looks good.

/kind feature
/approve

2023-10-19 16:43 UTC, Jefftree commented
/triage accepted

2023-10-19 18:40 UTC, deads2k commented
> not sure I have context to lgtm this, happy to defer to @deads2k's review.
> 
> is this guarding the `--storage-media-type` flag or something else?

Added for the storage into etcd.

This starts gating all k8s.io/apiserver that uses our standard serialization flows, we could add a direct code method to skip. But I doubt people wrote customer serializers before and this is very clear.

2023-10-23 13:21 UTC, deads2k commented
Looks like good defense.

/lgtm

2023-10-23 14:41 UTC, jpbetz requested changes
Minor nit then LGTM

2023-10-23 14:41 UTC, jpbetz commented on staging/src/k8s.io/apiserver/pkg/server/config.go
> +var allowedMediaTypes = []string{
nit: Use a const here?

2023-10-23 14:41 UTC, jpbetz commented on staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
> +var storageMediaTypes = sets.New(
nit: Use a const here?

2023-10-23 14:42 UTC, jpbetz commented on staging/src/k8s.io/apiserver/pkg/server/config.go
> +var allowedMediaTypes = []string{
nvm, this can't be a const in Go

2023-10-23 14:42 UTC, jpbetz commented on staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
> +var storageMediaTypes = sets.New(
nvm, this can't be a const in Go

2023-10-23 14:42 UTC, jpbetz commented
/lgtm

2023-10-23 14:43 UTC, jpbetz commented
/hold cancel

2023-10-23 15:27 UTC, merged

2023-10-25 07:41 UTC, sftim commented
Changelog suggestion
```markdown
Updated the generic apiserver library to produce an error if a new API server is configured with support for a data format other than JSON, YAML, or Protobuf.
```

2023-10-25 14:01 UTC, benluddy commented
> Changelog suggestion
> 
> ```
> Updated the generic apiserver library to produce an error if a new API server is configured with support for a data format other than JSON, YAML, or Protobuf.
> ```

Adopted your suggestion, thank you!