add tls-max-version
kubernetes/kubernetes pull request #121618
Opened 2023-10-30 16:32 UTC by pschou

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

We need to add MaxVersion for TLS to enforce configurable options.

#### Which issue(s) this PR fixes:

#81145 

#### Special notes for your reviewer:

Adds a flag for setting the maximum version.  If left off the defaults stay the same as expected by previous versions.

#### Does this PR introduce a user-facing change?

The command line flag is added for fine-tuning the versions supported with TLS sessions.

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
--tls-max-version on kubelet and kube-apiserver allow for configuring maximum TLS versions
```

2023-10-31 20:17 UTC, seans3 commented
/sig auth
/remove-sig api-machinery

2023-11-01 08:13 UTC, RainbowMango reviewed
> We need to add MaxVersion for TLS to enforce configurable options.

Could you please explain a little bit more about why we need to set the max version of TLS?

If the ciphers are concerning, we can set the ciphers by `--tls-cipher-suites` with preferred values or just set `--tls-min-version` to `VersionTLS13`.

2023-11-01 09:28 UTC, pschou commented
Note in the Golang documentation:

"When we implemented TLS 1.3 in Go 1.12, we didn't make TLS 1.3 cipher suites configurable, because they are a disjoint set from the TLS 1.0–1.2"

So, in effect... With crypto/tls: TLS 1.3 ciphers are not configurable

By implementing this update one can enforce the ciphers on the command line-- if the maximum is not set, golang will add all three TLSv1.3 ciphers, effectively making the configuration of which ciphers are allowed not configurable-- it's an all or nothing setup.

This is the only way supported by Golang to fully select the ciphers.

2023-11-04 19:19 UTC, VirrageS requested changes

2023-11-04 19:19 UTC, VirrageS commented on pkg/kubelet/apis/config/types.go
> +	// TLSMaxVersion is the minimum TLS version supported.
```suggestion
	// TLSMaxVersion is the maximum TLS version supported.
```

2023-11-06 15:54 UTC, pschou commented
@VirrageS thank you for that catch

2023-11-07 21:13 UTC, alexzielenski commented
/sig auth
/remove-sig api-machinery

2023-11-24 19:51 UTC, pschou commented on pkg/kubelet/apis/config/types.go
> +	// TLSMaxVersion is the minimum TLS version supported.
Thank you for noticing this, fixed!

2023-11-28 11:08 UTC, bart0sh commented
/ok-to-test
/triage accepted
/priority important-longterm

@pschou please, add a release note, thanks.

2024-04-08 16:40 UTC, enj commented
> Note in the Golang documentation:
> 
> "When we implemented TLS 1.3 in Go 1.12, we didn't make TLS 1.3 cipher suites configurable, because they are a disjoint set from the TLS 1.0–1.2"
> 
> So, in effect... With crypto/tls: TLS 1.3 ciphers are not configurable
> 
> By implementing this update one can enforce the ciphers on the command line-- if the maximum is not set, golang will add all three TLSv1.3 ciphers, effectively making the configuration of which ciphers are allowed not configurable-- it's an all or nothing setup.
> 
> This is the only way supported by Golang to fully select the ciphers.

The reason Go does not let you pick ciphers with TLS 1.3 is because it already picks the best ones for you (from a cryptographic standpoint all of those ciphers are secure).  I see no meaningful reason to make this change, nor would I recommend anyone set such a flag on any API server.

/hold

2024-09-05 18:03 UTC, closed without merging