kubectl: Allow namespaces with prefix
kubernetes/kubernetes pull request #123142
Opened 2024-02-05 23:56 UTC by iCiaran

#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Strip the prefix from the namespace flag if it starts with "namespace/", "namespaces/", or "ns/" (case insensitive), allowing the output of `kubectl get ns -o name` to be used directly in subsequent commands.

This was previously addressed in #50579, but lost in a refactor to config flag parsing (#63373).

#### Which issue(s) this PR fixes:

Fixes #29271

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Fixed a regression in flag parsing, to allow using prefixed namespaces (kubectl -n namespace/example)
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-02-06 00:00 UTC, iCiaran commented
/sig cli

2024-02-06 04:02 UTC, yankay commented
/ok-to-test

2024-02-09 17:04 UTC, iCiaran commented
Hi @pwittrock, @seans3, would be great to get some feedback on this, thanks!

2024-04-17 14:27 UTC, soltysh requested changes
/hold 

At this point in time, I don't consider this regression anymore. 
/remove-kind regression 

The `<resource>/<name>` pattern is good as an argument, where we need to explicitly specify resource type, for explicit flags, like `-n` or especially better visible with `--namespace namespace/xyz` it's overly verbose. Also this part can easily managed through some sort of `cut` invocation to skip the namespace part.

2024-04-18 10:05 UTC, bo0ts commented
@soltysh I really consider this a worthwhile QOL change that improves many of use cases.

2024-04-21 01:21 UTC, iCiaran commented
For me it's about having kubectl work in an intuitive way, in most (all?) other cases the `get xyz -o name` output can be used directly in another command. While the workaround is simple, having to remember that namespaces are an exception is a minor nuisance.

As to the long gap - it's something that's bugged me for a couple of years, I just didn't get round to trying to do something about it until now.

If not merging then a comment on #29271 noting that the original fix no longer works would be appreciated, it's where I (and I'm sure many others) ended up when searching for why you can't use `-n namespace/foo`.

2024-07-30 19:58 UTC, iCiaran commented
/close

2024-07-30 19:58 UTC, closed without merging