Fixed go versions for CI tests in dependency files
kubernetes/kubernetes pull request #123257
Opened 2024-02-13 05:49 UTC by srivastav-abhishek

Kubernetes unit tests are not able to execute due to mismatchedversions in dependency files.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR corrected the versions in different files by replacing `go1.22` with `go.1.22.0`.
#### Which issue(s) this PR fixes:

Fixes #123256

#### Special notes for your reviewer:
This CI runs on `ppc arch`
Failed job link : https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le/1756891004578828288
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

2024-02-13 05:59 UTC, Rajalakshmi-Girish commented
https://github.com/kubernetes/kubernetes/issues/123256 started happening after merge of https://github.com/kubernetes/kubernetes/pull/123217/commits/ddb0b8da9dbcd3d507001c5cf8a01708816f3cd5 @cpanato ^^

2024-02-13 09:31 UTC, Rajalakshmi-Girish commented
@mkumatag^^
We need this for fixing constantly failing https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le.

2024-02-13 09:50 UTC, cpanato requested changes
this image does not exist, i am checking to fix that

2024-02-13 09:55 UTC, mkumatag commented
we need to fix it in the release repository, e.g: https://github.com/kubernetes/release/pull/3454 which pushed 1.22 version

2024-02-14 03:33 UTC, Rajalakshmi-Girish commented
@srivastav-abhishek we may /close this PR now as https://github.com/kubernetes/kubernetes/pull/123262 has merged with the same changes. Also, the related job is passing now.

2024-02-14 04:22 UTC, closed without merging