Update cri-api Readme
kubernetes/kubernetes pull request #123370
Opened 2024-02-19 08:00 UTC by Rei1010

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Update cri-api Readme change history 

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

2024-02-19 18:37 UTC, kannon92 commented
/cc @haircommander @mikebrow

2024-02-19 19:56 UTC, haircommander commented on staging/src/k8s.io/cri-api/README.md
> +- [Add cntainer filesystem to the ImageFsInfoResponse](https://github.com/kubernetes/kubernetes/pull/120914)
container*

2024-02-19 19:57 UTC, haircommander commented
one spelling issue, otherwise LGTM, thanks @Rei1010

2024-02-20 01:45 UTC, Rei1010 commented on staging/src/k8s.io/cri-api/README.md
> +- [Add cntainer filesystem to the ImageFsInfoResponse](https://github.com/kubernetes/kubernetes/pull/120914)
Thanks for catching this

2024-02-22 17:39 UTC, haircommander commented
/retest
/lgtm

2024-02-22 17:39 UTC, haircommander commented
/triage accepted

2024-03-04 15:01 UTC, bart0sh commented
/priority important-longterm

2024-03-04 15:03 UTC, kannon92 commented
/hold cancel

2024-03-04 15:04 UTC, kannon92 commented
/hold

@saschagrunert should your cri change be reflected in here?

2024-03-04 15:37 UTC, saschagrunert requested changes

2024-03-04 22:53 UTC, mikebrow commented on staging/src/k8s.io/cri-api/README.md
> +
and https://github.com/kubernetes/kubernetes/pull/123583/files

2024-05-08 01:35 UTC, Rei1010 commented on staging/src/k8s.io/cri-api/README.md
> +
@saschagrunert @mikebrow sorry for late, please review. thx

2024-05-08 06:39 UTC, saschagrunert approved these changes

2024-05-08 06:40 UTC, saschagrunert commented
/unhold

2024-05-08 08:36 UTC, merged