Automated cherry pick of #123083: refactor type checking to use CompositedCompiler.
kubernetes/kubernetes pull request #124139
Opened 2024-04-01 16:34 UTC by jiahuif

Cherry pick of #123083 on release-1.29.

#123083: refactor type checking to use CompositedCompiler.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

2024-04-01 21:16 UTC, jiahuif commented
/retest

2024-04-04 17:01 UTC, cici37 commented
/triage accepted
/assign

2024-04-05 18:11 UTC, cici37 commented
/lgtm
/approve
this is to fix the bug that variables could not be recognized in VAP status. However, since it is not a security fix or regression bug fix. I'll leave it to release-managers to decide if it is ok to be backported. Thanks :)

2024-04-11 08:29 UTC, saschagrunert approved these changes

2024-04-11 08:30 UTC, saschagrunert requested changes
Ah, the original PR has the /kind feature. We usually do not backport features into release branches. May I ask for a clarification on this?

2024-04-11 18:31 UTC, jiahuif commented
> saschagrunert

Hi @saschagrunert Thank you for reviewing! Let me clarify.

The original PR adds a feature that is planned but missing due to an oversight during development. A missing feature can also be viewed as a bug. We've promised users the feature in question should be completed in beta. That is why we are trying to backport it into every supported release where the feature is at least beta stability.

What would you think? Could you quote a policy on how we deal with backporting missing features? Thank you.

2024-04-12 06:31 UTC, saschagrunert commented
@jiahuif I'm still not convinced we should backport this feature (or any feature). What do @kubernetes/release-managers think?

2024-04-12 11:31 UTC, cpanato commented
i would agree with @saschagrunert , would accept this if that is really low risk and some prove of that

2024-04-12 14:27 UTC, jeremyrickard commented
In wg-lts we have been discussing the topic of cherry pick criteria, specifically around the topic of regressions in patch releases by bringing too much back. 

@liggitt presented some compelling data on the trend of regressions that points toward being very strict about backports, strictly focusing on security bugs, data loss, and  fixing regressions, I’m inclined to reject this one on those grounds.

2024-04-16 23:48 UTC, jiahuif commented
/close
Makes sense. Giving up backport.

2024-04-16 23:48 UTC, closed without merging