Aramase/t/transformation tests parallel
kubernetes/kubernetes pull request #124250
Opened 2024-04-10 01:06 UTC by aramase

#### What type of PR is this?

/kind flake
/kind cleanup

#### What this PR does / why we need it:
-Generate a unique UDS path for each integration test, so there are no conflicts.
- Run some of the tests in parallel.

Test runtime before the change

```shell
➜ make test-integration WHAT=./test/integration/controlplane/transformation KUBE_TEST_ARGS="-v"
...
PASS
ok    k8s.io/kubernetes/test/integration/controlplane/transformation  502.481s
```

Runtime after change 

```shell
➜ make test-integration WHAT=./test/integration/controlplane/transformation KUBE_TEST_ARGS="-v"
...
PASS
ok  	k8s.io/kubernetes/test/integration/controlplane/transformation	375.110s
```

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/124106

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/sig auth
/triage accepted
/priority important-longterm

2024-04-10 02:23 UTC, aramase commented
/assign enj

2024-04-22 07:49 UTC, pacoxu commented
- 9m22s in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124250/pull-kubernetes-integration/1777885074008576000 this presubmit CI with this fix.
- 14m34s in CI without this change https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1782298252922589184

LGTM (non binding)

2024-04-22 13:23 UTC, enj requested changes
Minor comments.

2024-04-22 13:23 UTC, enj commented on test/integration/controlplane/transformation/kms_transformation_test.go
> +			t.Parallel()
Need the `tc := tc` bit above.

2024-04-22 16:49 UTC, aramase commented on test/integration/controlplane/transformation/transformation_test.go
> +	return fmt.Sprintf("@%s.sock", rand.String(10))
the sockets are cleaned up here https://github.com/kubernetes/kubernetes/blob/d8f8c7fae0aecc5b72e1ab0f1b71d75833c6b40c/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2/kms_plugin_mock.go#L146

2024-04-22 17:01 UTC, enj commented
/lgtm
/approve

2024-04-22 18:53 UTC, merged

2024-04-23 12:26 UTC, neolit123 reviewed
the bots pinged me on this PR for review. a checked the diff quickly but didn't comment.
today i logged this ticket due to flakes and remembered this PR:
https://github.com/kubernetes/kubernetes/issues/124476