fix: fixes update CRD check
kubernetes/kubernetes pull request #124877
Opened 2024-05-14 23:56 UTC by nilekhc

#### What type of PR is this?

/kind cleanup
/kind failing-test
/kind flake

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/123921

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig api-machinery

2024-05-14 23:58 UTC, nilekhc commented
/triage accepted
/priority important-soon

/cc @deads2k @jpbetz

2024-05-14 23:59 UTC, nilekhc commented
@benluddy fyi

2024-05-15 21:41 UTC, nilekhc commented
/retest

2024-05-16 16:11 UTC, enj requested changes

2024-05-16 16:11 UTC, enj commented on test/integration/storageversionmigrator/util.go
> -
Undo since third party and kube imports should be separated.

2024-05-16 16:11 UTC, enj commented on test/integration/storageversionmigrator/util.go
> +	// wait for CRD to be updated with desired versions
This is checking the wrong thing.  What you need to check is that the Kube API server has caught up to the config change _in memory_.

2024-05-25 17:24 UTC, enj commented
Linter error is related, otherwise LGTM.

2024-05-28 19:51 UTC, enj commented
/lgtm
/approve

2024-05-28 19:54 UTC, merged