Migrate to structured logging in cluster-bootstrap
kubernetes/kubernetes pull request #124905
Opened 2024-05-16 12:47 UTC by hiroki-it

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

I've worked on migrating to structured logging in cluster-bootstrap :)

In changing loggers and log messages, I read the following documents.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
- [Other doc]: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
```

2024-05-16 12:55 UTC, neolit123 reviewed
it seems cleaner after the diff, but this part of the code is included in community owned tools like kubeadm or external tools that don't benefit from struct logging.

does the KEP actually target cluster-bootstrap or is this your proposal for a change target @hiroki-it ?

/sig insrumentation

2024-05-16 12:56 UTC, neolit123 commented
/sig instrumentation

2024-05-16 16:34 UTC, dgrisonnet commented
/assign @shiva1333 
/triage accepted

2024-05-16 16:34 UTC, dgrisonnet commented
/ok-to-test

2024-05-17 04:50 UTC, hiroki-it commented
@neolit123 

Thanks for checking PR!

Sorry, I thought cluster-bootstrap was a package related to Kubernetes itself, and I didn't realize cluster-bootstrap was a package used by those tools.

I will check the KEP documentation to see if it is a target, so please wait 🙇🏻🙇🏻🙇🏻

2024-06-13 16:42 UTC, dgrisonnet commented
/triage accepted

/assign @shivanshuraj1333

2024-06-27 16:44 UTC, dgrisonnet commented
@mengjiao-liu could you perhaps find someone to look at this PR? I recall Shivanshu changed his github handled and I am not sure my initial ping reached him

2024-06-27 16:46 UTC, rexagod commented
/assign @shivanshuraj1333

2024-06-27 17:43 UTC, shivanshuraj1333 requested changes
Thanks for the PR, can you please use KObj for secrets as it a k8s object. [Ref](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#structured-logging-in-kubernetes)

2024-06-27 17:43 UTC, shivanshuraj1333 commented on staging/src/k8s.io/cluster-bootstrap/util/secrets/secrets.go
> +			"expirationTime", expiration, "secretNamespace", secret.Namespace, "secretName", secret.Name, "error", err)
```suggestion
		klog.V(3).InfoS("Unparseable expiration time",
			"expirationTime", expiration, "secret", klog.KObj(secret), "error", err)
```

2024-06-27 17:43 UTC, shivanshuraj1333 commented on staging/src/k8s.io/cluster-bootstrap/util/secrets/secrets.go
> +			"secretNamespace", secret.Namespace, "secretName", secret.Name, "expirationTime", expiration)
```suggestion
		klog.V(3).InfoS("Expired bootstrap token",
			 "secret", klog.KObj(secret), "expirationTime", expiration)
```

2024-06-28 07:53 UTC, mengjiao-liu reviewed
Why not migrate to contextual logging？

2024-06-28 07:54 UTC, mengjiao-liu commented
/area logging
/wg structured-logging

2024-07-01 09:14 UTC, hiroki-it commented
@dgrisonnet @rexagod @shivanshuraj1333  @mengjiao-liu

I'm really sorry for the delay in replying.

Thank you all so much for your comments and reviews 🤝🏻

Indeed, as @mengjiao-liu say, I needed to work on contextual logging as well!

I will refer to @shivanshuraj1333 's review and work on the contextual logging migration 👍🏻

2024-07-25 16:36 UTC, dgrisonnet commented
/assign @mengjiao-liu

2024-10-23 20:11 UTC, rexagod commented
/remove-lifecycle stale

@hiroki-it Can you please address the pending reviews? We can do contextual logging in a follow up.

2025-01-27 09:07 UTC, hiroki-it commented
@dgrisonnet @rexagod @shivanshuraj1333 @mengjiao-liu

I'm really sorry for the delay in responding to you all. 
As I don't have time to work on this PR, I'd like to hand over the remaining work to @bells17 . 
He's a colleague at work and has experience contributing to migration to structured logging.

2025-01-27 09:08 UTC, hiroki-it commented
@dgrisonnet @rexagod @shivanshuraj1333 @mengjiao-liu

I'm really sorry for the delay in responding to you all 🙇🏻‍♂️
As I don't have time to work on this PR, I'd like to hand over the remaining work to @bells17 !
He's a colleague at work and has experience contributing to migration to structured logging!

2025-03-28 09:54 UTC, closed without merging