fix: fix miss makezero bug
kubernetes/kubernetes pull request #125132
Opened 2024-05-26 13:05 UTC by alingse

#### What type of PR is this?

bug

#### What this PR does / why we need it:

I was running github actions to run a modified  [makezero](https://github.com/ashanbrown/makezero)  linter for top github golang repos.

see issues https://github.com/alingse/go-linter-runner/issues/1 for more detail

the github actions output was run for the repo  https://github.com/kubernetes/kubectl

https://github.com/alingse/go-linter-runner/actions/runs/9242992463/job/25426538273

```
====================================================================================================
append to slice `resources` with non-zero initialized length at https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/create/create_role.go#L121:14
====================================================================================================
```

It's a bug because the `resources = make([]schema.GroupResource, 1)` will add a empty schema.GroupResource struct in the first element of the slice, but when iter from `specialVerbs` it was safely filtered and not cause a real bug.

```go
			if groupResources, ok := specialVerbs[v]; ok {
				match := false
				for _, extra := range groupResources {
					if resource.Resource == extra.Resource && resource.Group == extra.Group {
						match = true
						err = nil
						break
					}
				}
```

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

2024-05-26 14:28 UTC, dims commented
/ok-to-test
/assign @MadhavJivrajani

2024-05-27 01:42 UTC, alingse commented
the linter also report https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/storage/validation/validation.go#L290

but I don't know is it a bug or intend to code like this. the rawTopologies was created empty with len(topologies) length.

```go
// validateAllowedTopology tests that AllowedTopologies specifies valid values.
func validateAllowedTopologies(topologies []api.TopologySelectorTerm, fldPath *field.Path) field.ErrorList {
	allErrs := field.ErrorList{}

	if len(topologies) == 0 {
		return allErrs
	}

	rawTopologies := make([]map[string]sets.Set[string], len(topologies))
	for i, term := range topologies {
		idxPath := fldPath.Index(i)
		exprMap, termErrs := apivalidation.ValidateTopologySelectorTerm(term, fldPath.Index(i))
		allErrs = append(allErrs, termErrs...)

		// TODO (verult) consider improving runtime
		for _, t := range rawTopologies {
			if helper.Semantic.DeepEqual(exprMap, t) {
				allErrs = append(allErrs, field.Duplicate(idxPath.Child("matchLabelExpressions"), ""))
			}
		}

		rawTopologies = append(rawTopologies, exprMap)
	}

	return allErrs
}
```

and report  https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1532

```go
	// We are creating those slices ones here to avoid memory reallocations
	// in every loop. Note that reuse the memory, instead of doing:
	//   slice = <some new slice>
	// you should always do one of the below:
	//   slice = slice[:0] // and then append to it
	//   slice = append(slice[:0], ...)
	// To avoid growing this slice, we arbitrarily set its size to 64,
	// there is never more than that many arguments for a single line.
	// Note that even if we go over 64, it will still be correct - it
	// is just for efficiency, not correctness.
	args := make([]string, 64)

	for _, set := range ipsetWithIptablesChain {
		if _, find := proxier.ipsetList[set.name]; find && !proxier.ipsetList[set.name].isEmpty() {
			args = append(args[:0], "-A", set.from)
...
```

It's correct but with a too long explanation, it can be just simple code `args := make([]string, 0, 64)` 
(maybe this style is later supported by go)

2024-05-28 09:47 UTC, MadhavJivrajani commented
/retest

2024-05-28 10:13 UTC, MadhavJivrajani reviewed
Good catch @alingse!

I don't think any of these bugs ever materialise because of how the surrounding logic is, as you mentioned, nevertheless, its good to fix it. 

Feel free to fix the other two instances that you mentioned as well and we can then discuss more if needed!

2024-05-30 08:49 UTC, MadhavJivrajani commented
ack @alingse 

/assign @soltysh 
for this change ^

2024-05-30 08:50 UTC, MadhavJivrajani commented
/kind cleanup
/priority backlog

2024-09-27 05:30 UTC, alingse commented
@MadhavJivrajani could you review it again?

2024-10-23 00:08 UTC, thockin commented on staging/src/k8s.io/kubectl/pkg/cmd/create/create_role.go
> +		resources = make([]schema.GroupResource, 0, 1)
This is a behavioral change.  We used to have a slice with an empty `[0]` - so either this code is never called or else  someone else is observing the empty item and skipping it?

Before we merge this, we need to know why it doesn't explode with that empty item.

Can you try to track it down?

2024-11-06 10:03 UTC, soltysh requested changes

2024-11-06 10:04 UTC, soltysh commented
/triage accepted

2024-11-11 15:28 UTC, alingse commented
/retest

2024-11-12 16:14 UTC, alingse commented
@soltysh @thockin I have update the commits, would you review it again laterly?

2024-11-12 19:13 UTC, thockin commented on staging/src/k8s.io/kubectl/pkg/cmd/create/create_role.go
> +		resources = make([]schema.GroupResource, 0, 1)
You didn't actually answer my question.  Clearly this is WRONG today, but it's working, so SOMEWHERE we are are either ignoring empty entries in this list or somehow compensating for this bug.

What I would like to see in this PR is an explanation of why this is safe.

If I put a `panic()` inside this test, it triggers during tests.  If I grep for this function (`AddSpecialVerb()`) - there are NO callers of it.  Perhaps the bettr thing to do is delete it?  I am not super aware of kubectl internals

2024-11-25 15:15 UTC, soltysh approved these changes
/lgtm
/approve
/milestone v1.33
/label tide/merge-method-squash

2024-12-10 14:13 UTC, alingse commented
@thockin @MadhavJivrajani  would you merge it ? I think it is ok now.

2024-12-10 16:43 UTC, thockin commented
Context is https://github.com/kubernetes/kubernetes/pull/107083

IMO we should be wary of such code, but we did allow it.

Thanks!

/lgtm
/approve

2024-12-12 02:56 UTC, merged