Disallow `k8s.io` and `kubernetes.io` namespaced extra key in structured authn config
kubernetes/kubernetes pull request #126553
Opened 2024-08-05 23:12 UTC by aramase

#### What type of PR is this?
/kind api-change

#### What this PR does / why we need it:
Disallow `k8s.io` and `kubernetes.io` namespaced extra key in structured authentication configuration

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/126495

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Disallow `k8s.io` and `kubernetes.io` namespaced extra key in structured authentication configuration.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration
```

2024-08-05 23:13 UTC, aramase commented
/sig auth
/triage accepted
/priority important-soon

2024-08-05 23:19 UTC, aramase commented
/uncc mikedanese pwittrock
/assign enj liggitt

2024-08-12 22:58 UTC, aramase commented
/kind bug

2024-08-13 16:22 UTC, enj requested changes
Minor comments, LGTM otherwise.

2024-08-13 16:22 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation.go
> +		if parts := strings.SplitN(mapping.Key, "/", 2); len(parts) == 2 {
```suggestion
		if parts := strings.SplitN(mapping.Key, "/", 2); len(parts) == 2 {  // guaranteed by utilvalidation.IsDomainPrefixedPath
```

2024-08-13 16:22 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation_test.go
> +			name: "extra mapping key prefix is k8.io",
Add tests that show that `ak8s.io`, `*.ak8s.io`, `bkubernetes.io`, `*.bkubernetes.io`, etc still work.

2024-08-13 17:46 UTC, enj commented
/lgtm

2024-08-15 16:44 UTC, liggitt commented
/label api-review

2024-08-15 16:48 UTC, liggitt commented on staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation.go
> +			domainPrefix := strings.ToLower(parts[0])
drop the toLower, maybe use a copy of these verbatim

```
func isKubernetesLabel(key string) bool {
	namespace := getLabelNamespace(key)
	if namespace == "kubernetes.io" || strings.HasSuffix(namespace, ".kubernetes.io") {
		return true
	}
	if namespace == "k8s.io" || strings.HasSuffix(namespace, ".k8s.io") {
		return true
	}
	return false
}

func getLabelNamespace(key string) string {
	if parts := strings.SplitN(key, "/", 2); len(parts) == 2 {
		return parts[0]
	}
	return ""
}
```

2024-08-15 17:00 UTC, liggitt commented
/lgtm
/approve

2024-08-15 18:01 UTC, merged