DRA: test checkpoint structure upgrade
kubernetes/kubernetes pull request #126717
Opened 2024-08-15 14:42 UTC by bart0sh

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Added new test case that emulates upgrade scenario: adding new field to the checkpointed structure and loading checkpoint that was made before the structure was changed.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2024-08-15 15:22 UTC, bart0sh commented
/cc @pohly @klueska @moshe010

2024-08-15 16:02 UTC, bart0sh commented
/triage accepted
/priority important-longterm

2024-08-15 22:38 UTC, bart0sh commented
/retest

2024-08-20 10:09 UTC, pohly requested changes

2024-08-20 10:09 UTC, pohly commented on pkg/kubelet/cm/dra/state/checkpointer_test.go
> +			// Checkpoint content doesn't have RequestNames field, but it shouldn't prevent the checkpoint from being loaded
```suggestion
			// Emulate upgrade scenario by pretending that `Device.RequestNames` is a new field.
			// The checkpoint content doesn't have it and that shouldn't prevent the checkpoint from being loaded.
```

2024-08-20 18:15 UTC, pohly approved these changes
/lgtm
/assign @klueska 

For approval.

2024-08-21 09:51 UTC, bart0sh commented
/assign @mrunalp @SergeyKanzhelev 
for approval

2024-08-29 12:27 UTC, bart0sh commented
@klueska I've added one more test case with updated checkpoint version. PTAL.

2024-08-30 09:15 UTC, klueska commented
Does the new test case only work currently because we don't actually check the version at all and attempt to do any sort of migrations? So we basically put it there so that it will fail if / when we add such support to make sure we are doing things correctly?

2024-08-30 09:20 UTC, bart0sh commented
@klueska Yes, that's how it's implemented.

2024-09-09 10:32 UTC, merged