fix replicaset controller display old msg when `manageReplicasErr` changed
kubernetes/kubernetes pull request #127111
Opened 2024-09-04 07:18 UTC by chengjoey

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
replicaset failure type condition should show the newest message, when `manageReplicasErr` changed

#### Which issue(s) this PR fixes:
Fixes #127081

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
```release-note
replicaset failure type condition will show the newest error message
```

2024-10-15 01:29 UTC, hope792 commented
@chengjoey @alculquicondor @smarterclayton

Any updates on this PR?

2024-10-15 13:03 UTC, alculquicondor commented
I'm no longer a reviewer for this package, can you choose a different one?

2024-10-17 02:17 UTC, hope792 commented
@neolit123, @chengjoey can you help choose a reviewer here so that we can continue with the bug fix?

2024-10-17 05:39 UTC, neolit123 commented
these are the owners https://github.com/kubernetes/community/blob/master/sig-apps/README.md#contact

2024-11-04 09:13 UTC, hope792 commented
@sig-apps-pr-reviews, ping on this PR, can you help assign someone to review this PR?
cc @chengjoey

2024-11-04 09:44 UTC, antonio commented
> @antonio Ojea, ping on this PR, can you help assign someone to review this PR?

Wrong Antonio! No worries, it happens a few times every month. Did you maybe mean @aojea ?

2024-11-04 12:16 UTC, aojea commented on pkg/controller/replicaset/replica_set_utils.go
> +	} else if manageReplicasErr != nil {
is this `manageReplicasErr != nil && failureCond != nil `, right?

2024-11-04 12:19 UTC, aojea commented on pkg/controller/replicaset/replica_set_utils_test.go
> +			fmt.Errorf("new fake manageReplicasErr"),
is the description correct? 
it seems `manageReplicasErr` is not nil here

2024-11-04 12:20 UTC, aojea commented
/ok-to-test

The bug looks legit, if the state is the same (failure) but the error is different, the controller does not update the state to reflect the new error ... I left some comments, I think we should restrict more the `if case` that now handles and other combination

/assign @soltysh

2024-11-06 10:34 UTC, soltysh requested changes
Partially the bug is legit, but at the same time we already check for both status and reason of a condition in `SetCondition` see:
https://github.com/kubernetes/kubernetes/blob/f451aec23787c2b48489eea2377cd13dfa15bded/pkg/controller/replicaset/replica_set_utils.go#L153-L160
and update only if its `Status` and `Reason` are different. This is to ensure we don't overwhelm apiserver with too many conditions updates, which not always will be useful. Like the one described in https://github.com/kubernetes/kubernetes/issues/127081 where the message will be different for the first 40 mins of every hour, and then again different for the remaining 20 mins.  That kind of a bug is rather not something I'd expect in a normal production workload (I'll comment on the bug itself).

Having said that, looking through the `calculateStatus` method it looks like we
only check for missing failure condition in this block: https://github.com/kubernetes/kubernetes/blob/f451aec23787c2b48489eea2377cd13dfa15bded/pkg/controller/replicaset/replica_set_utils.go#L109-L121
which means we can potentially swallow a different condition (with different `Status` and `Condition`, which is what `SetCondition` is checking). I'd suggest starting with writing a test which will prove that this situation exists, and if so I'm open to having that fixed, but the one from the linked issue where we only update message seems like an overkill.

/hold

2024-12-18 01:46 UTC, kenta-iijima commented
@soltysh 

>  I'd suggest starting with writing a test which will prove that this situation exists,

What specific code do you have in mind?
Is [what was discussed in the issue](https://github.com/kubernetes/kubernetes/issues/127081#issuecomment-2328090668) not enough?

2024-12-26 08:56 UTC, hope792 commented
@soltysh
The error message referenced in https://github.com/kubernetes/kubernetes/issues/127081 is intended for illustrative purposes only.

In production workloads, there may be multiple admission checks for pod creation that result in the same Reason value, such as FailedCreate. Whether for human troubleshooting or automated integration handling failed pod creations, it is critical that the error message accurately reflects the underlying cause blocking pod creation. From an API data integrity standpoint, this represents a bug where the ReplicaSet controller fails to update the actual status of the ReplicaSet."

2025-01-08 09:13 UTC, kenta-iijima commented
I also think it is critical that the error message accurately reflects the underlying cause blocking pod creation for any reason.
I think it might be better to examine the probability of this situation occurring in an actual workflow rather than test to prove that it exists.

2025-01-09 12:57 UTC, chengjoey commented on pkg/controller/replicaset/replica_set_utils_test.go
> +			fmt.Errorf("new fake manageReplicasErr"),
done

2025-01-16 03:44 UTC, hope792 commented
> I also think it is critical that the error message accurately reflects the underlying cause blocking pod creation for any reason. I think it might be better to examine the probability of this situation occurring in an actual workflow rather than test to prove that it exists.

@kenta-iijima this actually happens quite a lot in our production workload and I think it is quite common as this bug is determinable, for example, we need to exam the following things before a POD can be created:
1. Perform a image vulnerability check against the POD.
2. Perform some resource quota check against the POD.

Both 1&2 failed, if the check-2 result is reported first, the RS status will have a message like "resource quota limit blocked the POD creation", and after resource quota is allocated, due to this bug, check-1's results will never reported into the RS status. User cannot know the real blocking reason unless search the replica controller log. If we build some automated remediation flow based on the RS status, it generally won't work.

2025-01-28 00:51 UTC, kenta-iijima commented
Thank you for your input. I agree with your point about the importance of error messages accurately reflecting the underlying cause of pod creation failures.

2025-04-28 06:41 UTC, hope792 commented
/remove-lifecycle stale

2025-07-28 01:43 UTC, hope792 commented
/remove-lifecycle stale
@soltysh @chengjoey @kenta-iijima I think we still need to evaluate this PR and issue, any more inputs needed from my side?
@chengjoey would you take a look at @soltysh's comments?

2025-07-28 09:54 UTC, chengjoey commented
> @chengjoey would you take a look at @soltysh's comments?

Yes, I will provide the test in the near future.

2025-12-25 11:11 UTC, closed without merging