Add flag for kubectl version check-version-skew
kubernetes/kubernetes pull request #127365
Opened 2024-09-14 20:18 UTC by omerap12

#### What type of PR is this?
/kind feature 

#### What this PR does / why we need it:
Add an flag for kubectl version which fails if the client version exceeds the supported minor version skew of +/-1
#### Which issue(s) this PR fixes:

Fixes kubernetes/kubectl#1648

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Add a flag for kubectl version. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

2024-09-20 10:34 UTC, pacoxu commented
/ok-to-test

2025-01-26 14:33 UTC, sftim commented
Changelog suggestion
```diff
-Add a flag for kubectl version. 
+Add a flag to `kubectl version` that detects whether a client/server version mismatch is outside the officially supported range.
```

2025-01-26 14:35 UTC, sftim commented
I'd like this in `KUBECONFIG`, actually: for a particular context, I'd like to define the behavior when unsupported version skew is detected:
- nothing
- emit a warning but continue
- abort with an error

To allow gradual adoption, for the first _n_ releases we could start by only supporting the nothing and warning options.

2025-01-26 14:35 UTC, sftim commented
/remove-lifecycle rotten
/lifecycle stale

2025-01-26 15:18 UTC, brianpursley requested changes
Also, it would be nice to have unit tests for this new behavior.

2025-01-26 15:18 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +		}
It seems like this will print both the warning and the error.  Also, `printVersionSkewWarning()` now has two purposes: to print the warning message, but also to return the warning message.  I wonder if we can do some refactoring to simplify it to a single purpose.

Here is a thought...

What if we rename `printVersionSkewWarning()` to `getVersionSkewWarning()` and change its behavior to not print the warning, but only return the warning string, if there is one.

Then the code here could be changed to something like this:

```
if warningMessage != "" {
    if o.CheckVersionSkew {
        // Fail if there is a version skew warning
        return fmt.Errorf("CheckVersionSkew: %q", warningMessage)
    } else {
        // Print the version skew warning, but don't fail
        fmt.Fprint(w, warningMessage)
    }
}
```

This way, the handling of the warning message is kept in one place and `getVersionSkewWarning` has a single purpose.

This is just one idea.

What do you think?

2025-01-26 15:18 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +			return fmt.Errorf("CheckVersionSkew: %q", warningMessage)
I believe the Go standard is for errors to start with lowercase.  I'm not sure we need to indicate anything here,  Would this work?

```suggestion
			return errors.New(warningMessage)
```

Or do you think we need more information in the message?

2025-01-26 15:21 UTC, brianpursley commented on staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go
> +		warningMessage := fmt.Sprintf("WARNING: version difference between client (%d.%d) and server (%d.%d) exceeds the supported minor version skew of +/-%d\n",
We should probably omit the "WARNING:" part of this message, since we don't know are this point whether the command will display it as a warning or an error.

The "WARNING:" part can be added back if it is printed as a warning, otherwise, if it is an error, then we probably should not confuse the user by calling it a warning.

2025-02-07 11:34 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +		}
Yes, I agree this is better. I adjusted it in 58194a4a8b86d3efb1c92a973a47694cac2b19c3

2025-02-07 11:34 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +			return fmt.Errorf("CheckVersionSkew: %q", warningMessage)
You are right, go standard is start with lower case for errors. Adjusted in e70aade49a316bb1df13cfda6a86eddcd9ed7364

2025-02-07 11:34 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go
> +		warningMessage := fmt.Sprintf("WARNING: version difference between client (%d.%d) and server (%d.%d) exceeds the supported minor version skew of +/-%d\n",
Agree. added in e9123f34525aaa30dbc74fa7f45bfce91af1eb84

2025-02-07 11:37 UTC, omerap12 commented
> I'd like this in `KUBECONFIG`, actually: for a particular context, I'd like to define the behavior when unsupported version skew is detected:
> 
> * nothing
> * emit a warning but continue
> * abort with an error
> 
> To allow gradual adoption, for the first _n_ releases we could start by only supporting the nothing and warning options.

Sorry for my ignorance, but can you explain a bit more? Do you mean adding a new field to the KUBECONFIG file for this? How do you see this working?

2025-02-08 20:09 UTC, brianpursley requested changes
Left some more comments.

I've also been thinking about the flag name `--check-version-skew`

Is there any concern that a user might be confused by this?  After all, `kubectl version` will **always** perform the check.  This flag just controls whether it should treat an unsupported version skew as a warning or as an error.

I just want to make sure we get this right, because it will be hard to change a flag name later.

@eddiezane @ardaguclu @mpuckett159 any thoughts on the flag name?

2025-02-09 09:07 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go
> +func getVersionSkewWarning(w io.Writer, clientVersion, serverVersion apimachineryversion.Info) (string, error) {
right, added in: [6387000](https://github.com/kubernetes/kubernetes/pull/127365/commits/6387000fffbfb04db0a71622c34b988e68c162be)

2025-02-09 09:07 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +	cmd.Flags().BoolVar(&o.CheckVersionSkew, "check-version-skew", o.CheckVersionSkew, "If true, returns an error if the client version exceeds the supported minor version skew of +/-1 relative to the s
added in [605f649](https://github.com/kubernetes/kubernetes/pull/127365/commits/605f6495f165071341647cf9ad80b09779f61c52)

2025-02-09 19:58 UTC, rajibmitra commented on staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go
> +		return "", err
Instead of returning the err, can we think of wrapping this with ("server version error: %v", err)

2025-02-09 19:58 UTC, rajibmitra commented on staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go
>  	parsedClientVersion, err := version.ParseSemantic(clientVersion.GitVersion)
Instead of returning the err, can we think of wrapping this with ("Client version error: %v", err)

2025-02-12 17:16 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go
>  	parsedClientVersion, err := version.ParseSemantic(clientVersion.GitVersion)
Adjusted in 1109d9129919e3fd45e409f874a73cf04ac5f406

2025-02-12 17:16 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/skew_warning.go
> +		return "", err
Adjusted in 1109d9129919e3fd45e409f874a73cf04ac5f406

2025-02-12 22:24 UTC, hashim21223445 approved these changes

2025-03-15 10:58 UTC, omerap12 commented
/remove-lifecycle rotten

2025-04-15 18:11 UTC, omerap12 commented
@brianpursley Is this still active, or should I go ahead and close it?

2025-04-22 23:06 UTC, brianpursley commented
> @brianpursley Is this still active, or should I go ahead and close it?

Sorry I have fallen behind on reviews.

I hope this PR is still active.  The issue was accepted and I like this change.  I think it will be helpful especially in automation.

My only question is on the flag name.

The original issue suggested `--error-on-version-mismatch` and this PR proposes `--check-version-skew`

Personally, I find `--check-version-skew` to be a little confusing because it *always* checks the version skew.  The only distinction is whether it prints a warning or fails with an error.  Previously it only printed a warning, but this change adds the option to fail with an error.

For this reason, I find `--error-on-version-skew` to be a little more descriptive, but not perfect. To be precise, this will error on an *unsupported* version skew, not just any version skew.

Is `--error-on-unsupported-version-skew` too long? :sweat_smile:  I was hoping to get some other opinions on the naming.  Let me see if anyone else has any thoughts on this.

2025-04-24 14:55 UTC, soltysh commented
/label tide/merge-method-squash

> For this reason, I find `--error-on-version-skew` to be a little more descriptive, but not perfect. To be precise, this will error on an _unsupported_ version skew, not just any version skew.
> 
> Is `--error-on-unsupported-version-skew` too long? 😅 I was hoping to get some other opinions on the naming. Let me see if anyone else has any thoughts on this.

On Slack @brianpursley mentioned that he's seeing this as somewhat similar to global `--warnings-as-errors` looking at this I'm seeing two possible paths:
1. Don't introduce new flag, and wire it directly to the version skew check.
2. Rename the new, proposed flag to be similar eg. `--version-skew-as-errors`. 

I don't have strong preferences, either of the two should work, imo.

2025-04-27 09:08 UTC, omerap12 commented
Thanks for the input, @soltysh!
I don't have strong preferences either. @brianpursley, do you have any preferences?

2025-04-30 09:48 UTC, soltysh commented
From the [slack conversation](https://kubernetes.slack.com/archives/C2GL57FJ4/p1745364415087019) it seems the first approach is more preferred, try this and if that works we'll go with that.

2025-04-30 20:12 UTC, omerap12 commented
PTAL @brianpursley @soltysh

2025-04-30 20:14 UTC, omerap12 commented
/retitle kubectl: check version skew

2025-05-07 20:56 UTC, brianpursley commented
Unless I misunderstood, I think the ides was to attempt to re-use the existing `--warnings-as-errors` flag for the purpose of determining if a version skew warning should be treated as an error or not.

So I think we still want to preserve the default behavior of treating it as a warning, and use `--warnings-as-errors` as the flag that makes it be treated as an error.

2025-05-08 08:13 UTC, omerap12 commented
@brianpursley , how about that?

It looks like that:
```bash
$ ./_output/bin/kubectl version --warnings-as-errors
Client Version: v1.32.0-alpha.0.743+70b539abdb8d92-dirty
Kustomize Version: v5.4.2
Server Version: v1.26.0
error: version difference between client (1.32) and server (1.26) exceeds the supported minor version skew of +/-1
$ echo $?
1


$ ./_output/bin/kubectl version
Client Version: v1.32.0-alpha.0.743+70b539abdb8d92-dirty
Kustomize Version: v5.4.2
Server Version: v1.26.0
Warning: version difference between client (1.32) and server (1.26) exceeds the supported minor version skew of +/-1
$ echo $?
0
```

2025-05-09 06:32 UTC, omerap12 commented
/retest

2025-05-09 16:18 UTC, soltysh reviewed
One more comment and this will be good to go

2025-05-09 16:18 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +				if flag := cmd.Parent().PersistentFlags().Lookup("warnings-as-errors"); flag != nil {
```golang
cmd.Flags().Lookup("warnings-as-errors")
```
will be sufficient to read that flag. With that change you should be able to move this entire block to `Complete` function, to match how we're completing the options struct.

2025-05-09 16:19 UTC, soltysh commented
/triage accepted
/priority important-longterm

2025-05-13 12:29 UTC, soltysh requested changes

2025-05-13 14:57 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +			}
Fixed in: https://github.com/kubernetes/kubernetes/pull/127365/commits/e6bc278ae46100e81f96140f83a7dbee73da4be0

2025-05-13 14:57 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +	}
Sure, fixed in: https://github.com/kubernetes/kubernetes/pull/127365/commits/e6bc278ae46100e81f96140f83a7dbee73da4be0

2025-05-19 13:32 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +			}
Yeah I forgot we can add this comment.
Done :)

2025-05-19 13:44 UTC, omerap12 commented on staging/src/k8s.io/kubectl/pkg/cmd/version/version.go
> +	}
Done

2025-05-19 14:26 UTC, omerap12 commented
Flake: https://github.com/kubernetes/kubernetes/issues/131834

2025-05-19 14:27 UTC, omerap12 commented
/retest pull-kubernetes-e2e-kind

2025-05-19 14:28 UTC, omerap12 commented
/test pull-kubernetes-e2e-kind

2025-05-19 14:52 UTC, soltysh approved these changes
/lgtm
/approve

2025-05-19 16:34 UTC, omerap12 commented
/test pull-kubernetes-e2e-kind

2025-05-19 16:38 UTC, omerap12 commented
same flake. 
/retest

2025-05-19 17:19 UTC, merged