kubeadm addons: Bump coredns version
kubernetes/kubernetes pull request #128776
Opened 2024-11-13 03:38 UTC by my-git9

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

CoreDns 1.11.4 released: https://github.com/coredns/coredns/releases/tag/v1.11.4

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

2024-11-18 10:46 UTC, my-git9 commented
/test pull-kubernetes-e2e-gce

2024-11-18 11:35 UTC, kl52752 commented
Test is failing with image pull error
```
I1113 05:59:28.390106 65658 dump.go:53] At 2024-11-13 05:48:21 +0000 UTC - event for coredns-74bc44c9bd-lvxml: {kubelet e2e-0db0337a64-674b9-minion-group-21zp} Failed: Error: ErrImagePull
  I1113 05:59:28.390117 65658 dump.go:53] At 2024-11-13 05:48:21 +0000 UTC - event for coredns-74bc44c9bd-lvxml: {kubelet e2e-0db0337a64-674b9-minion-group-21zp} Pulling: Pulling image "registry.k8s.io/coredns/coredns:v1.11.4"
  I1113 05:59:28.390130 65658 dump.go:53] At 2024-11-13 05:48:21 +0000 UTC - event for coredns-74bc44c9bd-lvxml: {kubelet e2e-0db0337a64-674b9-minion-group-21zp} Failed: Failed to pull image "registry.k8s.io/coredns/coredns:v1.11.4": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/coredns/coredns:v1.11.4": failed to resolve reference "registry.k8s.io/coredns/coredns:v1.11.4": registry.k8s.io/coredns/coredns:v1.11.4: not found
  ```

2024-11-18 11:40 UTC, my-git9 commented
> Test is failing with image pull error
> 
> ```
> I1113 05:59:28.390106 65658 dump.go:53] At 2024-11-13 05:48:21 +0000 UTC - event for coredns-74bc44c9bd-lvxml: {kubelet e2e-0db0337a64-674b9-minion-group-21zp} Failed: Error: ErrImagePull
>   I1113 05:59:28.390117 65658 dump.go:53] At 2024-11-13 05:48:21 +0000 UTC - event for coredns-74bc44c9bd-lvxml: {kubelet e2e-0db0337a64-674b9-minion-group-21zp} Pulling: Pulling image "registry.k8s.io/coredns/coredns:v1.11.4"
>   I1113 05:59:28.390130 65658 dump.go:53] At 2024-11-13 05:48:21 +0000 UTC - event for coredns-74bc44c9bd-lvxml: {kubelet e2e-0db0337a64-674b9-minion-group-21zp} Failed: Failed to pull image "registry.k8s.io/coredns/coredns:v1.11.4": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/coredns/coredns:v1.11.4": failed to resolve reference "registry.k8s.io/coredns/coredns:v1.11.4": registry.k8s.io/coredns/coredns:v1.11.4: not found
> ```

The coredns:v1.11.4 image should have been uploaded, thanks

2024-11-18 12:57 UTC, DamianSawicki commented
/retest

2024-11-18 13:24 UTC, aojea commented
the image was promoted recently https://github.com/kubernetes/k8s.io/pull/7519

2024-11-18 14:12 UTC, DamianSawicki requested changes

2024-11-18 14:12 UTC, DamianSawicki commented on cmd/kubeadm/app/phases/addons/dns/dns_test.go
> +			image:          "registry.k8s.io/coredns/coredns:v1.11.4@sha256:a0ead06651cf580044aeb0a0feba63591858fb2e43ade8c9dea45a6a89ae7e5e",
With the new patch version, sha256 should also be updated.

2024-11-29 08:56 UTC, my-git9 commented
dup:https://github.com/kubernetes/kubernetes/pull/128926

2024-11-29 08:56 UTC, closed without merging