feature(kubectl): support mem-percent,cpu-value,cpu-average-value,mem-value,mem-average-value flag to kubectl autoscale
kubernetes/kubernetes pull request #129373
Opened 2024-12-24 02:05 UTC by googs1025

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
- support mem-percent,cpu-value,cpu-average-value,mem-value,mem-average-value flag to kubectl autoscale
#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/kubectl/issues/1481

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
support mem-percent,cpu-value,cpu-average-value,mem-value,mem-average-value flag to kubectl autoscale
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

2024-12-24 14:11 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			if !o.canCreateHPAV1() {
Here we need to determine whether it can be created in V1, because there are different between v1 and v2.

2024-12-24 14:14 UTC, googs1025 commented
ping @soltysh please help this  :)

2025-01-07 15:39 UTC, soltysh requested changes

2025-01-07 15:39 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.MemoryPercent, "mem-percent", -1, "The target average memory utilization (represented as a percent of requested memory) over all the pods. If it's not specified or negative,
I see that in comment https://github.com/kubernetes/kubectl/issues/1481#issuecomment-1738278790 the OP mentioned all the possible values, but I'm definitely against such an approach. I haven't seen any particular preference between the percent and quantity so I'm leaning towards the `--mem-percent` to match the pre-existing `--cpu-percent` flag. So please drop all else and we'll only support that one addition. If users are interested in tweaking the generated HPA they are free to do it outside this command.

2025-01-07 15:40 UTC, soltysh commented
/triage accepted
/priority important-longterm

2025-01-08 02:59 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			if !o.canCreateHPAV1() {
done

2025-01-08 03:00 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.MemoryPercent, "mem-percent", -1, "The target average memory utilization (represented as a percent of requested memory) over all the pods. If it's not specified or negative,
sounds reasonable to me. done

2025-01-08 11:53 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.MemoryPercent, "mem-percent", -1, "The target average memory utilization (represented as a percent of requested memory) over all the pods. If it's not specified or negative,
Apologies for not thinking more about this, but I was considering a better approach for the future. 
The original implementation utilizing `--cpu-percent` was based entirely on autoscaling/v1 types. 
But now that most of our users have the ability to use autoscaling/v2 where we can present both types I'm inclined to deprecate the current `--cpu-percent` flag, and replace it with just `--cpu` where it would accept either a percent value (`10%`, or just a number `10` which would mean it's a percentage), or users could specify a quantity (in case of cpu that'd be `5m`). Now, in a similar fashion we'd add `--memory` flag which would also accept a number (or with `%`), or a quantity. For parsing the first number you can use `intstr.IntOrString` type, and if that fails, it means you were given a quantity, which also have parsing utilities. 

Sorry once again for the changes, but I believe that will better match all the possible use cases. What do you think?

2025-01-08 12:43 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.MemoryPercent, "mem-percent", -1, "The target average memory utilization (represented as a percent of requested memory) over all the pods. If it's not specified or negative,
OK. This is more flexible on the flag, but we need to do more job of verifying the input params. I will adjust it and ping you again when I am done.

2025-01-11 10:22 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.MemoryPercent, "mem-percent", -1, "The target average memory utilization (represented as a percent of requested memory) over all the pods. If it's not specified or negative,
After thinking about the design, maybe we can do this: we provide --cpu, --memory flags. Users can specify ":" to specify the metric type and support multiple units. For cases where units are not specified, the default configuration is used. 🤔  @soltysh PTAL
#### CPU Units:
- m,milli: milliCPU, e.g., 500m means 0.5 cores.
- core: core count, e.g., 1core or 1 means 1 core.
- Default to m if no unit is provided.
#### Memory Units:
- "Mi", "Mib", "MiB": mebibytes, e.g., 512Mi means 512 megabytes.
- "Gi", "Gib", "GiB": gibibytes, e.g., 1Gi means 1 gigabyte.
- Default to Mi if no unit is provided.

Percentage Format: If the value ends with %, it defaults to Utilization.
Quantity Format: If the value is a number or has a unit:
For --cpu, default to m if no unit is provided; parse directly if m or core is specified.
For --memory, default to Mi if no unit is provided; parse directly if Mi or Gi is specified.
Explicit Metric Type: Users can specify :utilization, :value, or :averagevalue explicitly.

### Possible Cases

#### For --cpu
1. Percentage with Default Type (Utilization):
- Example: --cpu=80%
- Description: CPU average utilization of 80%.
2. Quantity with Default Type (Value):
- Example: --cpu=500 (defaults to 500m)
- Description: 500 milliCPU.
- Example: --cpu=1 (defaults to 1core)
- Description: 1 CPU core.
3. Percentage with Explicit Utilization:
- Example: --cpu=80%:utilization
- Description: Explicitly specifies CPU average utilization of 80%.
4. Quantity with Explicit Value:
- Example: --cpu=500m:value
- Description: Explicitly specifies 500 milliCPU.
- Example: --cpu=1core:value
- Description: Explicitly specifies 1 CPU core.
5. Quantity with Explicit AverageValue:
- Example: --cpu=500m:averagevalue
- Description: Explicitly specifies an average of 500 milliCPU.
#### For --memory
1. Percentage with Default Type (Utilization):
- Example: --memory=80%
- Description: Memory average utilization of 80%.
2. Quantity with Default Type (Value):
- Example: --memory=512 (defaults to 512Mi)
- Description: 512 mebibytes of memory.
3. Percentage with Explicit Utilization:
- Example: --memory=80%:utilization
- Description: Explicitly specifies memory average utilization of 80%.
4. Quantity with Explicit Value:
- Example: --memory=512Mi:value
- Description: Explicitly specifies 512 mebibytes of memory.
- Example: --memory=1Gi:value
- Description: Explicitly specifies 1 gibibyte of memory.
5. Quantity with Explicit AverageValue:
- Example: --memory=512Mi:averagevalue
- Description: Explicitly specifies an average of 512 mebibytes of memory.
- Example: --memory=1Gi:averagevalue
- Description: Explicitly specifies an average of 1 gibibyte of memory.

2025-01-15 10:32 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.MemoryPercent, "mem-percent", -1, "The target average memory utilization (represented as a percent of requested memory) over all the pods. If it's not specified or negative,
What you wrote above is close to what I've meant, although introducing `:` in the middle is not expected. I'm worried that it might overly complicate things, and I prefer something a bit simpler. 

So:
1. For both cpu and memory, a percentage number would automatically mean average value in autoscale's metric type (`.target.averageUtilization`).
2. For both cpu and memory passing a unit-based value (ie. with milicores or MiB, etc) or just a number will automatically means the user wants to specify a quantity, so that's the average value (`.target.averageValue`) in autoscale's metric type. This would match what we have in [quantity API](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/).

For no. 2 you don't need to invent any logic for parsing the quantities, since we already have `k8s.io/apimachinery/pkg/api/resource#ParseQuantity` to handle that for you. 

So looking at your examples:

>     1. Percentage with Default Type (Utilization):
>     * Example: --cpu=80%
>     * Description: CPU average utilization of 80%.

:+1: 

>     2. Quantity with Default Type (Value):
>     * Example: --cpu=500 (defaults to 500m)
>     * Description: 500 milliCPU.

:+1: 

>     3. Percentage with Explicit Utilization:
>     * Example: --cpu=80%:utilization
>     * Description: Explicitly specifies CPU average utilization of 80%.

`--cpu=80%:utilization` no need to specify it's utilization. Just `--cpu=80%` should be sufficient.


>     4. Quantity with Explicit Value:
>     * Example: --cpu=500m:value
>     * Description: Explicitly specifies 500 milliCPU.
>     * Example: --cpu=1core:value
>     * Description: Explicitly specifies 1 CPU core.

In both cases no need for `:value`, `--cpu=500m` is correct and `ParseQuantity` will handle that. `--cpu=1core` is not correct. That's not supported by our [quantity API](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/). 

>     5. Quantity with Explicit AverageValue:
>     * Example: --cpu=500m:averagevalue
>     * Description: Explicitly specifies an average of 500 milliCPU.

Again, no need for `:averagevalue`, just ` --cpu=500m` will be sufficient to express 500 milicores. 


>     1. Percentage with Default Type (Utilization):
>     * Example: --memory=80%
>     * Description: Memory average utilization of 80%.

:+1: 

>     2. Quantity with Default Type (Value):
>     * Example: --memory=512 (defaults to 512Mi)
>     * Description: 512 mebibytes of memory.

:+1: 

>     3. Percentage with Explicit Utilization:
>     * Example: --memory=80%:utilization
>     * Description: Explicitly specifies memory average utilization of 80%.

No need for `:utilization`, just `--memory=80%`. 

>     4. Quantity with Explicit Value:
>     * Example: --memory=512Mi:value
>     * Description: Explicitly specifies 512 mebibytes of memory.
>     * Example: --memory=1Gi:value
>     * Description: Explicitly specifies 1 gibibyte of memory.

No need for `:value`, just ` --memory=512Mi` or  `--memory=1Gi` is sufficient. 

>     5. Quantity with Explicit AverageValue:
>     * Example: --memory=512Mi:averagevalue
>     * Description: Explicitly specifies an average of 512 mebibytes of memory.
>     * Example: --memory=1Gi:averagevalue
>     * Description: Explicitly specifies an average of 1 gibibyte of memory.

No need for `:averagevalue`, just `--memory=512Mi` or `--memory=1Gi` is sufficient.

2025-02-01 14:53 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.MemoryPercent, "mem-percent", -1, "The target average memory utilization (represented as a percent of requested memory) over all the pods. If it's not specified or negative,
thanks for feedback. I will handle these days 😄

2025-02-03 01:57 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
>  	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default
If we support --cpu --memory , I'm not sure if we need to deprecate --cpu-percent? 🤔

2025-02-03 02:16 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
Main thought: Use regular expression to separate "value" and "unit". Use different units to return different Quantity.

2025-02-04 12:57 UTC, soltysh requested changes

2025-02-04 12:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
>  	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default
The idea is to limit the amount of flag. If you have both `--cpu-percent` and `--cpu` how will you explain the difference? if you have only `--cpu` allowing you to specify both percent value and a unit, it's easier to remember.

2025-02-04 12:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().StringVar(&o.CPU, "cpu", "", `Target CPU. Specify as a percentage (e.g."70%" for 70% of requested CPU), an absolute value with units (e.g."500m" for 500 milliCPU), or an absolute value w
```suggestion
	cmd.Flags().StringVar(&o.CPU, "cpu", "", `Target CPU utilization over all the pods. When specified as a percentage (e.g."70%" for 70% of requested CPU) it will target average utilization. When specified as quantity (e.g."500m" for 500 milliCPU) it will target average value. Value without units is treated as a quantity with miliCPU being the unit (e.g."500" is "500m").`)
```

2025-02-04 12:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().StringVar(&o.Memory, "memory", "", `Target memory. Specify as a percentage (e.g."60%" for 60% of requested memory), an absolute value in mebibytes (e.g."200Mi" for 200 MiB), or gibibytes
```suggestion
	cmd.Flags().StringVar(&o.Memory, "memory", "", `Target memory utilization over all the pods. When specified  as a percentage (e.g."60%" for 60% of requested memory) it will target average utilization. When specified as quantity (e.g."200Mi" for 200 MiB, "1Gi" for 1 GiB) it will target average value. Value without units is treated as a quantity with mebibytes being the unit (e.g."200" is "200Mi").`)
```

2025-02-04 12:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
Why not use `apiresource.ParseQuantity` instead? It's already there, it's battle tested and proven to work just fine, and consistent with entire API?

2025-02-04 12:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			return fmt.Errorf("failed to create v2 HorizontalPodAutoscaler: %w", err)
You're changing the previous flow here, before we never would fail at this point in time, now you do. The only reason why you're failing here is due to parsing `--cpu` and/or `--memory` flags. Why not invoke `apiresource.ParseQuantity` already in `Validate`, so that at this point in time, it's impossible to get that error.

2025-02-04 12:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +				return fmt.Errorf("failed to create v2 HPA and the configuration is incompatible with v1: %w", err)
No need for double the message, the error will bubble up to the user and that's sufficient information to present to the user.

2025-02-04 12:57 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
>  	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default
Ideally, you want to translate `--cpu-percent` value to CPU field adding `%` (in `Complete` for example). This way it'll be completely transparent to the user, and you'll only handle `o.CPU` in the entire code.

2025-02-17 08:15 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
>  	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default
My thought is, should we keep `--cpu-percent` flag and adapt it with `--cpu flag` as you said? This will be transparent to users and will be more convenient when `--cpu-percent` is removed in the future.

2025-02-17 08:41 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
We still use apiresource.ParseQuantity to parse at the bottom layer. However, we need to judge <value>[<unit>] first. The input here is more complicated. It may be "80%" or "500Mi" (memory unit) or "500m" (cpu unit) or no unit, so we need to distinguish different cases here. 
```go
switch {
 case unit == "%":
  // If it's a percentage, set metricTypeInt to UtilizationMetricType 
  metricType = autoscalingv2.UtilizationMetricType
  return quantity, value, metricType, nil
 case unit == "m" && resourceType == corev1.ResourceCPU: // CPU unit
  metricType = autoscalingv2.ValueMetricType
  quantity = apiresource.MustParse(input)
 case unit == "M" || unit == "Mi" || unit == "Gi" || unit == "Ki": // Memory units
  metricType = autoscalingv2.ValueMetricType
  quantity = apiresource.MustParse(input)
```
In another case, we support --cpu or --memory without inputting units, so we also need to distinguish this case.
```go
default:
  // Default case, no unit specified
  metricType = autoscalingv2.ValueMetricType
  if resourceType == corev1.ResourceCPU {
	// For CPU, use 'm' as the default unit
	quantity = apiresource.MustParse(fmt.Sprintf("%vm", value))
  } else if resourceType == corev1.ResourceMemory {
	// For memory, use 'Mi' as the default unit
	quantity = apiresource.MustParse(fmt.Sprintf("%vMi", value))
  } else {
	return quantity, value, metricType, errors.New("unsupported resource type")
  }
}
```

2025-02-17 08:50 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().StringVar(&o.Memory, "memory", "", `Target memory. Specify as a percentage (e.g."60%" for 60% of requested memory), an absolute value in mebibytes (e.g."200Mi" for 200 MiB), or gibibytes
done

2025-02-17 08:50 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().StringVar(&o.CPU, "cpu", "", `Target CPU. Specify as a percentage (e.g."70%" for 70% of requested CPU), an absolute value with units (e.g."500m" for 500 milliCPU), or an absolute value w
done

2025-02-21 14:58 UTC, soltysh requested changes

2025-02-21 14:58 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
>  	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default
Yes `--cpu-percent` should be marked as deprecated, we can't remove without a proper deprecation period, [which lasts a year. ](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli)

2025-02-21 14:58 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			return fmt.Errorf("failed to create v2 HorizontalPodAutoscaler: %w", err)
This still holds.

2025-02-21 14:58 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +				return fmt.Errorf("failed to create v2 HPA and the configuration is incompatible with v1: %w", err)
This still holds.

2025-02-21 14:58 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	if o.CPUPercent != 0 && o.CPU != "" {
The way you currently have this set is causing to fail when passing `--cpu` flag, because `--cpu-percent` default value is `-1`.

2025-02-21 14:58 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	if o.CPUPercent != 0 && o.CPU != "" {
```suggestion
	if o.CPUPercent < 0 && o.CPU != "" {
```
since in the description of the flag we clearly say that negative value is equal to not specified, and default autoscaling is being used.

2025-02-21 14:58 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
Nowhere in the code I see `apiresource.ParseQuantity` being invoked explicitly. What I'd imagine is the following flow:
1. Check for `%` existence, to set the metric type to average utilization.
2. Invoke `apiresource.ParseQuantity` removing `%`, which will ensure correctness of the value. Your current algorithm is missing several valid units, which are already covered in `apiresource.ParseQuantity`. 

That parsing should be ONLY used for picking the correct metric type and nothing more, we should always pass the unit as provided by the user, at most adding `m` when value was passed w/o units.

2025-05-23 00:39 UTC, googs1025 commented
/remove-lifecycle stale

2025-05-26 17:59 UTC, soltysh commented
@googs1025 any plans to address the missing comments?

2025-05-27 00:50 UTC, googs1025 commented
> @googs1025 any plans to address the missing comments?

@soltysh thanks for this...
sorry for the late.... I hope to address the comment by the end of this week, and if there is any progress, I will ping you on the slack channel, just like before 😄

2025-06-01 15:48 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	if o.CPUPercent != 0 && o.CPU != "" {
change to: 

```go
        // only one of the CPUPercent or CPU param is allowed
	if o.CPUPercent > 0 && o.CPU != "" {
		return fmt.Errorf("--cpu-percent and --cpu are mutually exclusive, CPUPercent: %v, CPU: %v", o.CPUPercent, o.CPU)
	}
```

2025-06-01 15:49 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			return fmt.Errorf("failed to create v2 HorizontalPodAutoscaler: %w", err)
change to use `apiresource.ParseQuantity`

2025-06-01 15:49 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +				return fmt.Errorf("failed to create v2 HPA and the configuration is incompatible with v1: %w", err)
remove `Info` message

2025-06-01 15:51 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
- Case 1: Handle percentage-based metrics like "70%"
- Case 2: Try to interpret input as a bare number (e.g., "500"), and apply default unit
- Case 3: Parse normally if input has a valid unit (e.g., "500m", "2Gi")

2025-06-01 16:07 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			return fmt.Errorf("failed to create v2 HorizontalPodAutoscaler: %w", err)
> Why not invoke apiresource.ParseQuantity already in Validate, so that at this point in time, it's impossible to get that error.

add `validateResourceTarget` to handle this

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
>  	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default
> Yes `--cpu-percent` should be marked as deprecated, we can't remove without a proper deprecation period, [which lasts a year. ](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli)

This still holds, I don't see that flag marked deprecated. Also while doing so make sure to update the example https://github.com/kubernetes/kubernetes/blob/d23407b0e2ed48e573411e4a385bc77acf7e6f2c/staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go#L59-L60 and https://github.com/kubernetes/kubernetes/blob/d23407b0e2ed48e573411e4a385bc77acf7e6f2c/staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go#L112 to use `--cpu` instead.

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +		return fmt.Errorf("--cpu-percent and --cpu are mutually exclusive, CPUPercent: %v, CPU: %v", o.CPUPercent, o.CPU)
```suggestion
		return fmt.Errorf("--cpu-percent and --cpu are mutually exclusive")
```
is sufficient.

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	}
It looks like you're already returning nil inside `validateResourceTarget` if `input` is nil, so:
```golang
if err := validateResourceTarget(o.CPU, corev1.ResourceCPU); err != nil {
	return err
}
```
should be sufficient. Iow. no need for the outer `if o.CPU != "" {` line. Same thing applies below for memory parameter check.

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	input = strings.TrimSpace(input)
You may want to move this trim to the first line, even before the first if check. You can pass `--cpu="  "` and that is not valid, but will only fail later during int parsing.

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	}
This logic here is not quite correct, what if I pass `--memory=5Gi`, the above code will not work correctly, and will fail in the next step when parsing int, because `5Gi` is not the correct value. Why you want to manually parse this value, rather than just trust that `ParseQuantity`?

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	}
In general our API accepts both value with units and without them. You can see that pattern being used even in our [docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics). So I'd drop the part where you're adding units by hand entirely, and just parse the part with `%`, to handle the percentage utilization, and pass the other value as is straight into API.

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			return fmt.Errorf("cannot autoscale a %v: %w", mapping.GroupVersionKind.Kind, err)
Nit: 
```suggestion
			return fmt.Errorf("cannot autoscale a %s: %w", mapping.GroupVersionKind.Kind, err)
```
`.Kind` is a string, so it's better to match the print type with that :wink:

2025-06-03 15:04 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	}
Lastly, please add a unit tests covering all those cases to make sure we won't break anything.

2025-06-16 02:21 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	}
done

2025-06-16 02:21 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +		return fmt.Errorf("--cpu-percent and --cpu are mutually exclusive, CPUPercent: %v, CPU: %v", o.CPUPercent, o.CPU)
removed

2025-06-16 02:25 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
>  	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default
```go
autoscaleExample = templates.Examples(i18n.T(`
      # Auto scale a deployment "foo", with the number of pods between 2 and 10, no target CPU utilization specified so a default autoscaling policy will be used
      kubectl autoscale deployment foo --min=2 --max=10

      # Auto scale a replication controller "foo", with the number of pods between 1 and 5, target CPU utilization at 80%
      kubectl autoscale rc foo --max=5 --cpu=80%

      # Auto scale a deployment "bar", with the number of pods between 3 and 6, target average CPU of 500m and memory of 200Mi
kubectl autoscale deployment bar --min=3 --max=6 --cpu=500m --memory=200Mi

      # Auto scale a deployment "bar", with the number of pods between 2 and 8, target CPU utilization 60% and memory utilization 70%
      kubectl autoscale deployment bar --min=3 --max=6 --cpu=60% --memory=70%`))
```

```go
Use:    "autoscale (-f FILENAME | TYPE NAME | TYPE/NAME) [--min=MINPODS] --max=MAXPODS [--cpu=CPU] [--memory=MEMORY]",
```

Add deprecation description to `--cpu-percent`
```go
cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "Flag deprecated: use --cpu instead with percentage or milliCPU value. The target average CPU utilization (represented as a percent of requested CPU) over all the pods. If it's not specified or negative, a default autoscaling policy will be used.")
cmd.Flags().StringVar(&o.CPU, "cpu", "", `Target CPU utilization over all the pods. When specified as a percentage (e.g."70%" for 70% of requested CPU) it will target average utilization. When specified as quantity (e.g."500m" for 500 milliCPU) it will target average value. Value without units is treated as a quantity with miliCPU being the unit (e.g."500" is "500m").`)
cmd.Flags().StringVar(&o.Memory, "memory", "", `Target memory utilization over all the pods. When specified  as a percentage (e.g."60%" for 60% of requested memory) it will target average utilization. When specified as quantity (e.g."200Mi" for 200 MiB, "1Gi" for 1 GiB) it will target average value. Value without units is treated as a quantity with mebibytes being the unit (e.g."200" is "200Mi").`)
cmd.Flags().StringVar(&o.Name, "name", "", i18n.T("The name for the newly created object. If not specified, the name of the input resource will be used."))
cmd.Flags().MarkDeprecated("cpu-percent",
"Flag deprecated. Use --cpu with percentage or resource quantity format (e.g., '70%' for utilization or '500m' for milliCPU).")

```

2025-06-16 02:25 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +			return fmt.Errorf("cannot autoscale a %v: %w", mapping.GroupVersionKind.Kind, err)
done

2025-06-16 02:29 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	input = strings.TrimSpace(input)
done
move `input = strings.TrimSpace(input)` to front position
```go
input = strings.TrimSpace(input)
if input == "" {
    return apiresource.Quantity{}, 0, "", fmt.Errorf("empty input")
}
```

2025-06-16 02:44 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	}
This code correctly handles various input formats:

Percentages like 70%
Raw numbers like 500 (auto-converted to 500m or 500Mi)
Full quantities with units like 500m, 2Gi, and yes — even 5Gi is handled properly by Kubernetes' quantity parser.

```go
        // Case 1: Percentage
	if strings.HasSuffix(input, "%") {
		trimmed := strings.TrimSuffix(input, "%")
		value, err := strconv.ParseInt(trimmed, 10, 64)
		if err != nil || value < 0 {
			return fmt.Errorf("invalid percentage value: %s", trimmed)
		}
		return nil
	}

	// Case 2: Try parse as pure integer and apply default unit
	var unit string
	switch resourceType {
	case corev1.ResourceCPU:
		unit = "m"
	case corev1.ResourceMemory:
		unit = "Mi"
	default:
		return fmt.Errorf("unsupported resource type: %v", resourceType)
	}

	if _, err := strconv.ParseFloat(input, 64); err == nil {
		input += unit
	}

	// Case 3: Parse full quantity
	if _, err := apiresource.ParseQuantity(input); err != nil {
		return fmt.Errorf("invalid %s target: %w", strings.ToLower(string(resourceType)), err)
	}
```

2025-06-16 02:51 UTC, googs1025 commented
/retest

2025-06-16 11:34 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "Flag deprecated: use --cpu instead with percentage or milliCPU value. The target average CPU utilization (represented as a percent of requeste
Don't change this line, the `MarkDeprecated` is sufficient because it will hide this flag from `--help` output and produce the necessary information for users still relying on that flag.

2025-06-16 11:34 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +		"Flag deprecated. Use --cpu with percentage or resource quantity format (e.g., '70%' for utilization or '500m' for milliCPU).")
```suggestion
		"Use --cpu with percentage or resource quantity format (e.g., '70%' for utilization or '500m' for milliCPU).")
```
What you currently have will produce:
```
Flag --cpu-percent has been deprecated, Flag deprecated. Use --cpu with percentage or resource quantity format (e.g., '70%' for utilization or '500m' for milliCPU).
```
The suggested change will give you:
```
Flag --cpu-percent has been deprecated, Use --cpu with percentage or resource quantity format (e.g., '70%' for utilization or '500m' for milliCPU).
```
So no need to repeat the information about deprecation :wink:

2025-06-16 11:34 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	}
Hmm... maybe I was wrong when testing last time, but I remember it didn't work the way you're describing, but rather I run into the described issue. Anyway, currently it's working as expected.

2025-06-16 11:34 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +		hpaV2, _ := o.createHorizontalPodAutoscalerV2(info.Name, mapping)
Either don't introduce that error returned from `createHorizontalPodAutoscalerV2` or make sure to act on it. Swallowing errors is bad.

2025-06-16 11:34 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +				return fmt.Errorf("failed to create v2 HPA and the configuration is incompatible with v1: %w", err)
```suggestion
				return fmt.Errorf("failed to create autoscaling/v2 HPA and the configuration is incompatible with autoscaling/v1: %w", err)
```

2025-06-16 11:34 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	return (o.CPUPercent >= 0 && o.Memory == "") || (o.Memory == "" && isUtilizationMetricType), nil
```suggestion
	return (o.CPUPercent >= 0 && o.Memory == "") || (o.Memory == "" && metricsType == autoscalingv2.UtilizationMetricType), nil
```
and you can drop that variable, it's simple enough to read :wink:

2025-06-16 11:34 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
I'm confused, you have two functions doing very similar checks, iow. you're duplicating code here and inside `validateResourceTarget`. Can you combine the shared bits of code?

2025-06-16 13:30 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	cmd.Flags().Int32Var(&o.CPUPercent, "cpu-percent", -1, "Flag deprecated: use --cpu instead with percentage or milliCPU value. The target average CPU utilization (represented as a percent of requeste
removed

2025-06-16 13:30 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +		"Flag deprecated. Use --cpu with percentage or resource quantity format (e.g., '70%' for utilization or '500m' for milliCPU).")
got this. 😄  thanks

2025-06-16 13:33 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +		hpaV2, _ := o.createHorizontalPodAutoscalerV2(info.Name, mapping)
Modified to handle this error.

2025-06-16 13:33 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +				return fmt.Errorf("failed to create v2 HPA and the configuration is incompatible with v1: %w", err)
done

2025-06-16 13:33 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +	return (o.CPUPercent >= 0 && o.Memory == "") || (o.Memory == "" && isUtilizationMetricType), nil
done

2025-06-16 13:35 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
Extract `getDefaultUnitForResource` and `parsePercentage` func

2025-06-25 05:26 UTC, googs1025 commented
@soltysh /PTAL 😄

2025-06-25 13:32 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
This comment still holds, I'd just replace both of the invocations of `validateResourceTarget` inside `Validate` with just `parseResourceInput` and just check for returned error to know if it's good or not. No need to repeat the same functionality, even though the `parseResourceInput` does a few additional checks.

2025-06-25 14:50 UTC, googs1025 commented on staging/src/k8s.io/kubectl/pkg/cmd/autoscale/autoscale.go
> +func parseResourceInput(input string, resourceType corev1.ResourceName) (apiresource.Quantity, int32, autoscalingv2.MetricTargetType, error) {
Thanks. Your review is indeed very detailed. It's really helpful! 😄 

change to: 
```go
        // validate CPU target if specified
	if o.CPU != "" {
		if _, _, _, err := parseResourceInput(o.CPU, corev1.ResourceCPU); err != nil {
			return err
		}
	}
	// validate Memory target if specified
	if o.Memory != "" {
		if _, _, _, err := parseResourceInput(o.Memory, corev1.ResourceMemory); err != nil {
			return err
		}
	}
```

2025-06-25 14:57 UTC, soltysh approved these changes
/lgtm
/approve

2025-06-25 21:02 UTC, merged