chore: add more error info for validateResourceSliceSpec
kubernetes/kubernetes pull request #129435
Opened 2024-12-31 03:19 UTC by googs1025

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- add more error info for validateResourceSliceSpec

I encountered this error, but looking at the error output, I can't tell whether it is because no fields are filled or multiple fields are filled.
```
Failed to create a ResourceSlice "fake-node-test-driver": ResourceSlice.resource.k8s.io "fake-node-test-driver" is invalid: spec: Invalid value: "null": exactly one of `nodeName`, `nodeSelector`, or `allNodes` is required
```

we can change to: 
```bash
"exactly one of `nodeName`, `nodeSelector`, or `allNodes` is required, but multiple fields are set: `nodeName`, `allNodes`"
```

#### Which issue(s) this PR fixes:

Fixes #None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

2024-12-31 03:51 UTC, googs1025 commented
/test pull-kubernetes-e2e-kind-ipv6

2024-12-31 13:19 UTC, pohly commented on pkg/apis/resource/validation/validation.go
> +		))
I believe I had implemented something like that myself and then @thockin suggested to simplify it. My implementation created the set while checking fields, in contrast to this one here where the details get collected only when needed.

I'll defer to @thockin.

2024-12-31 13:19 UTC, pohly commented on pkg/apis/resource/validation/validation.go
> +		setFields := make([]string, 0)
Nit:
```suggestion
		setFields := make([]string, 0, 10) // Definitely large enough, avoids allocation on heap.
```

2025-01-01 03:27 UTC, googs1025 commented on pkg/apis/resource/validation/validation.go
> +		setFields := make([]string, 0)
done

2025-01-04 07:22 UTC, googs1025 commented
/assign @thockin /PTAL

2025-01-04 07:23 UTC, googs1025 commented
/assign @thockin
/PTAL

2025-01-21 03:50 UTC, googs1025 commented on pkg/apis/resource/validation/validation.go
> +		))
@thockin Can you help me look at this? Now the error info with no fields and with multiple fields is the same, maybe we need to distinguish the info.

2025-02-15 11:09 UTC, googs1025 commented
friendly ping @thockin

2025-02-21 00:07 UTC, thockin commented on pkg/apis/resource/validation/validation.go
> +		))
I was against it before, but we're also doing it in declarative, so OK.

How about, instead of putting it in the string, you pass it as the `value` argument as `"{ + strings.Join(setFields, ", ") + "}"`  ?

2025-02-21 01:29 UTC, googs1025 commented on pkg/apis/resource/validation/validation.go
> +		))
Sorry, not sure if this is what you meant? 🤔 
`"exactly one of `nodeName`, `nodeSelector`, or `allNodes` is required, but multiple fields are set: {`nodeName`, `nodeSelector`}"`

2025-02-21 01:47 UTC, thockin commented on pkg/apis/resource/validation/validation.go
> +		))
I meant the argument which is currently `nil`:

```
field.Invalid(fldPath, fmt.Sprintf("{%s}", strings.Join(setFields, ", "), "exactly one of `nodeName`, `nodeSelector`, or `allNodes` is required")
```

2025-02-21 02:50 UTC, googs1025 commented on pkg/apis/resource/validation/validation.go
> +		))
done

2025-02-21 06:53 UTC, pohly commented on pkg/apis/resource/validation/validation.go
> +		}
Nit: can you move the collection of `setFields` into the code above?

As it stands now, we check each field twice: once to count them, once to populate `setFields`.

2025-02-21 07:18 UTC, googs1025 commented on pkg/apis/resource/validation/validation.go
> +		}
done

2025-02-21 15:17 UTC, pohly requested changes
/lgtm

2025-02-21 15:21 UTC, pohly commented on pkg/apis/resource/validation/validation.go
> +		setFields = append(setFields, "`nodeSelector`")
/lgtm cancel

2025-02-22 00:52 UTC, googs1025 commented on pkg/apis/resource/validation/validation.go
> +		setFields = append(setFields, "`nodeSelector`")
done

2025-02-23 19:40 UTC, pohly commented on pkg/apis/resource/validation/validation.go
> +		setFields = append(setFields, "`nodeSelector`")
/lgtm
/assign @thockin

2025-03-01 00:33 UTC, thockin reviewed
/approve

2025-03-01 08:54 UTC, pohly commented
/test pull-kubernetes-cmd

2025-03-01 10:16 UTC, merged