feature(printers): support limitrange resource
kubernetes/kubernetes pull request #129428
Opened 2024-12-30 09:52 UTC by googs1025

#### What type of PR is this?
/kind feature
/kind cleanup

#### What this PR does / why we need it:
- support limitrange resource for printers
#### Which issue(s) this PR fixes:

Fixes #None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
support limitrange resource for printers
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

2024-12-30 10:01 UTC, googs1025 commented
/sig cli

2024-12-30 13:16 UTC, googs1025 commented
/test pull-kubernetes-e2e-kind-ipv6

2025-01-02 08:53 UTC, googs1025 commented
friendly ping @ardaguclu @soltysh

2025-01-02 09:25 UTC, ardaguclu commented
`kubectl get limitranges -oyaml` should give the required information and I don't think we should support this. But I'll defer the final decision to @soltysh

2025-01-02 09:55 UTC, googs1025 commented
If there is any problem in my understanding, please help me point it out. I am a little curious why limitrange does not need to support printers. Shouldn't resource objects used externally support printer output?  🤔 
```bash
➜  ~ kubectl get limitrange
NAME                      CREATED AT
cpu-resource-constraint   2024-12-30T09:24:29Z
```

2025-02-04 12:30 UTC, soltysh requested changes

2025-02-04 12:32 UTC, soltysh commented
> `kubectl get limitranges -oyaml` should give the required information and I don't think we should support this. But I'll defer the final decision to @soltysh

`-oyaml` is always the best source of truth, but we try to be mindful and present useful information when invoking `kubectl get <resource>`. That's where the table printers come into play. We're not perfect, nor is the output, but it's better than the  name + creation timestamp, which is the default currently.

2025-02-04 12:32 UTC, soltysh commented
/assign

2025-02-05 03:02 UTC, googs1025 commented on pkg/printers/internalversion/printers.go
> +	}
When using limitrange, the Type, Min, and Max fields are usually the most important info(at least I think). It is enough to know the limit range of a namespace resource, and further details may not be necessary every time, so we can just use `-oyaml` to get those info. 🤔

2025-02-05 03:07 UTC, googs1025 commented on pkg/printers/internalversion/printers.go
> +	limitrangesColumndefinitions := []metav1.TableColumnDefinition{
thanks for reminding

2025-02-21 14:15 UTC, soltysh approved these changes
/lgtm 
/approve

2025-02-21 14:15 UTC, soltysh commented on pkg/printers/internalversion/printers.go
> +	}
I trust your judgement on this one.

2025-02-21 14:37 UTC, googs1025 commented
@smarterclayto @liggitt for approval

2025-02-28 02:33 UTC, googs1025 commented
@wojtek-t  can you help this?

2025-02-28 14:47 UTC, liggitt commented on pkg/printers/internalversion/printers.go
> +		{Name: "Type", Type: "string", Description: "Type of object that this limit applies to"},
a single limit range can contain multiple limits with multiple types, I'm not sure there's a reasonable way to represent a list of `[typeA,min,max], [typeB,min,max], ...` entries in a small flat number of columns

2025-02-28 14:48 UTC, liggitt commented on pkg/printers/internalversion/printers.go
> +			row.Cells = append(row.Cells, "...")
every cell needs to correspond to a column definition, this "..." would be spurious and isn't correct... if we elide content, the eliding needs to be included in one of the elided cell values

2025-02-28 14:51 UTC, liggitt commented on pkg/printers/internalversion/printers_test.go
> +			expected: []metav1.TableRow{{Cells: []interface{}{"test-limitrange", string("0s"), string("Container"), string("cpu=0, memory=100Mi"), string("cpu=100m, memory=10000Mi"), string("Pod"), string("cp
the cells don't correctly map to the columndefinition headers when there's more than one limit

2025-02-28 14:51 UTC, liggitt commented on pkg/printers/internalversion/printers_test.go
> +			expected: []metav1.TableRow{{Cells: []interface{}{"test-limitrange", string("0s"), string("Container"), string("cpu=0, memory=100Mi"), string("cpu=100m, memory=10000Mi"), string("Pod"), string("cp
the "..." cell at the end doesn't correctly map to any columndefinition header

2025-02-28 14:52 UTC, liggitt commented on pkg/printers/internalversion/printers_test.go
> +			expected: []metav1.TableRow{{Cells: []interface{}{"test-limitrange", string("0s"), string("Container"), string("cpu=0, memory=100Mi"), string("cpu=100m, memory=10000Mi"), string("Pod"), string("cp
can you paste what `kubectl get` actually displays for an entry like this?

2025-02-28 18:16 UTC, liggitt commented on pkg/printers/internalversion/printers_test.go
> +			expected: []metav1.TableRow{{Cells: []interface{}{"test-limitrange", string("0s"), string("Container"), string("cpu=0, memory=100Mi"), string("cpu=100m, memory=10000Mi"), string("Pod"), string("cp
mm... are any of those are 3+ item LimitRange objects? I don't see the additional type / min / max cells and `...` cell

2025-02-28 18:17 UTC, googs1025 commented on pkg/printers/internalversion/printers_test.go
> +			expected: []metav1.TableRow{{Cells: []interface{}{"test-limitrange", string("0s"), string("Container"), string("cpu=0, memory=100Mi"), string("cpu=100m, memory=10000Mi"), string("Pod"), string("cp
ohps...  I'll modify this...

2025-02-28 18:18 UTC, googs1025 commented on pkg/printers/internalversion/printers_test.go
> +			expected: []metav1.TableRow{{Cells: []interface{}{"test-limitrange", string("0s"), string("Container"), string("cpu=0, memory=100Mi"), string("cpu=100m, memory=10000Mi"), string("Pod"), string("cp
but what I expected is : 

```yaml
root@VM-0-7-ubuntu:~/go/src/k8s.io/kubernetes/_output/bin# ./kubectl get limitrange -owide
NAME                                 AGE     TYPE                    MIN                                                                MAX
comprehensive-resource-constraints   5m28s   Container               cpu=100m, ephemeral-storage=100Mi, ...   cpu=1, ephemeral-storage=2Gi,...
cpu-resource-constraint              17m     Container               cpu=100m                                                           cpu=1
pvc-resource-constraints             7m42s   PersistentVolumeClaim   storage=1Gi                                                        storage=10Gi
resource-constraints                 14m     Container               cpu=100m, memory=64Mi                                              cpu=1, memory=1Gi
resource-constraints-no-container    9m16s   Pod                     cpu=200m, memory=128Mi                                             cpu=2, memory=2Gi
```

2025-03-01 13:15 UTC, googs1025 commented on pkg/printers/internalversion/printers.go
> +		{Name: "Type", Type: "string", Description: "Type of object that this limit applies to"},
After thinking about it, maybe this approach would be a good approach?
We have a `MIN/MAX` column, and the order is Container -> Pod -> PersistentVolumeClaim. If neither MIN or MAX is set, it is not displayed. If one of them is not set, "-" is used.

```go
// LimitType defines a type of object that is limited
type LimitType string

const (
	// LimitTypePod defines limit that applies to all pods in a namespace
	LimitTypePod LimitType = "Pod"
	// LimitTypeContainer defines limit that applies to all containers in a namespace
	LimitTypeContainer LimitType = "Container"
	// LimitTypePersistentVolumeClaim defines limit that applies to all persistent volume claims in a namespace
	LimitTypePersistentVolumeClaim LimitType = "PersistentVolumeClaim"
)
```


```yaml
NAMESPACE   NAME                  AGE   MIN/MAX
development example-limitrange-1  0s    container.cpu: 20m/200m, container.memory: -/512Mi, pod.cpu: 50m/-, pod.memory: -/1Gi, persistentvolumeclaim.storage: -/50Gi
staging     example-limitrange-2  0s    container.cpu: -/150m, container.memory: 128Mi/768Mi, pod.cpu: -/300m, pod.memory: 256Mi/1.5Gi, persistentvolumeclaim.storage: 5Gi/-
production  example-limitrange-3  0s    container.cpu: 50m/500m, container.memory: 256Mi/2Gi, service.cpu: 20m/100m, service.memory: 128Mi/512Mi, pod.cpu: -/-, pod.memory: -/-, persistentvolumeclaim.storage: 10Gi/200Gi
testing     example-limitrange-4  0s    pod.cpu: 100m/400m, pod.memory: 512Mi/3Gi, persistentvolumeclaim.storage: -/1Ti
qa          example-limitrange-5  0s    container.cpu: 30m/300m, container.memory: 128Mi/1Gi, persistentvolumeclaim.storage: 50Gi/500Gi

```

2025-10-27 15:03 UTC, closed without merging