Support executing command within "kubectl proxy"
kubernetes/kubernetes pull request #31240
Opened 2016-08-23 13:20 UTC by nhlfr

**What this PR does / why we need it**: It allows to execute commands within `kubectl proxy` and replace `{}` with the URL to proxy. Example:
```
$ ./cluster/kubectl.sh proxy --exec "curl {}/api"
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "172.18.48.92:6443"
    }
  ]
}%
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #31178

**Special notes for your reviewer**:

**Release note**:

```release-note
```

Fixes #31178

2016-08-23 13:35 UTC, deads2k commented on pkg/kubectl/cmd/proxy.go
> +func RunProxyExec(execCommand, address string, port int) error {
Shouldn't be exported (lowercase it).

2016-08-23 13:35 UTC, deads2k commented
Needs tests.

2016-08-23 13:36 UTC, deads2k commented
@fabianofranz ptal.  Might be time to formalize some of the validation here.  Doing it in multiple locations makes it a little harder to see all the interactions (at least for me).

2016-08-24 08:32 UTC, nhlfr commented on pkg/kubectl/cmd/proxy.go
> +func RunProxyExec(execCommand, address string, port int) error {
done

2016-08-24 08:32 UTC, nhlfr commented
Test added

2016-08-24 20:22 UTC, fabianofranz commented
I get that the motivation for the syntax comes from `find --exec` but I'm a little concerned about the discoverability of `{}`. What are some use cases of commands where this would be useful, other than `curl`? If it's only curl could we make it similar to what we have now in `get`, like 

```
kubectl get --raw /api

kubectl proxy --curl /api
kubectl proxy --get /api
kubectl proxy --raw /api
```

2016-08-24 20:23 UTC, fabianofranz commented on pkg/kubectl/cmd/proxy.go
> +	cmd.Flags().StringP("exec", "e", "", "Command to be execured with the proxy address.")
*executed

2016-08-24 20:24 UTC, fabianofranz commented on pkg/kubectl/cmd/proxy.go
> +	cmd.Flags().StringP("exec", "e", "", "Command to be execured with the proxy address.")
"Command to be executed with the proxy address. {} will be replaced by the proxy URL." or something like that.

2016-08-24 20:29 UTC, fabianofranz commented
Or, if there are other use cases and we still decide to allow running any command, we could try to use a syntax similar to `kubectl exec` instead of an `--exec` flag:

```
kubectl proxy -- curl {}/api
```

2016-08-29 05:39 UTC, nhlfr commented
@fabianofranz Thanks for suggestions. I don't have any other usecases than curl, so your idea sounds good for me.

@pwittrock do you have any more usecases?

I will raise an another PR with `kubelet proxy --curl`, just in case. I need to write it from scratch anyway.

2016-09-14 06:49 UTC, nhlfr commented
Since there are no more usecases than curl, then I'm closing this PR and I'm going to send another one with an approach proposed by @fabianofranz

2016-09-29 18:14 UTC, pwittrock commented
@nhlfr Kompose used to rely on the proxy to talk to the kube-apiserver so that is another use case.

2016-09-29 18:30 UTC, nhlfr commented
@pwittrock OK, it looks like a good usecase.

2016-09-29 18:33 UTC, fabianofranz commented
> OK, it looks like a good usecase.

+1

2016-10-04 09:43 UTC, nhlfr commented
@pwittrock @fabianofranz ptal

2016-10-04 17:50 UTC, fabianofranz requested changes

2016-10-04 17:50 UTC, fabianofranz commented on pkg/kubectl/cmd/proxy.go
> +	cmd.Flags().StringP("exec", "e", "", "Command to be execured with the proxy address.")
"execured" (typo). Use "Command to be executed with the proxy address. {} will be replaced by the proxy URL." or something like that.

2016-10-04 17:50 UTC, fabianofranz commented on pkg/kubectl/cmd/proxy.go
> +	argv := strings.Split(execCommand, " ")
Does this work if my command has empty spaces? For example, what if the command I want to run is `--exec="echo 'foo bar'"`?

2016-10-04 17:50 UTC, fabianofranz commented on pkg/kubectl/cmd/proxy.go
> +	cmd.Stdout = os.Stdout
I think we need to use here the `io.Writer` you are receiving in `NewCmdProxy`. Store it in `syscallExecutor` when you instantiate it and use what's stored. Same with stdin and stderr, [run](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/run.go#L83) is an example that also takes all three.

2016-10-04 17:50 UTC, fabianofranz commented on pkg/kubectl/cmd/proxy.go
> +	argv := strings.Split(execCommand, " ")
May need a csv parser instead of just splitting.

2017-03-04 14:43 UTC, closed without merging