Clean user agent to reduce metrics cardinality
kubernetes/kubernetes pull request #31783
Opened 2016-08-31 12:59 UTC by dominikschulz

**What this PR does / why we need it**:

This PR is an example implementation for my issue #31781.

```release-note
```

This commit cleans common browser user-agents to reduce the metrics
cardinality in exported prometheus metrics.

Resolves kubernetes/kubernetes#31781

2016-08-31 22:10 UTC, lavalamp commented
ok to test

2016-08-31 22:12 UTC, lavalamp commented
Can you sign the CLA? this LGTM as is.

@deads2k do you guys do anything with user agent that this will mess up?

2016-09-01 13:08 UTC, deads2k commented
> @deads2k do you guys do anything with user agent that this will mess up?

Thanks for the call out.  We do make use of the user agent in a couple spots, but this mutation is contained such that it won't cause us problems.

I am a little surprised to see it stripped so aggressively though.  Pretty much everyone includes that these days, right?  In addition to whatever browser it actually was later in the string.  Seems like this would squash firefox, chrome, and I think safari.  If I found the right doc, this might even squash down IE, right? https://msdn.microsoft.com/en-us/library/ms537503(v=vs.85).aspx

2016-09-01 17:41 UTC, lavalamp commented
If it's that aggressive, replacing it with `browser` might be better. Not
sure if we need to be more clear than that?

On Thu, Sep 1, 2016 at 6:09 AM, David Eads <notifications@github.com> wrote:

> @deads2k <https://github.com/deads2k> do you guys do anything with user
> agent that this will mess up?
>
> Thanks for the call out. We do make use of the user agent in a couple
> spots, but this mutation is contained such that it won't cause us problems.
>
> I am a little surprised to see it stripped so aggressively though. Pretty
> much everyone includes that these days, right? In addition to whatever
> browser it actually was later in the string. Seems like this would squash
> firefox, chrome, and I think safari. If I found the right doc, this might
> even squash down IE, right? https://msdn.microsoft.com/en-
> us/library/ms537503(v=vs.85).aspx
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/31783#issuecomment-244073183>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAngll6XKx3UfS_vzPtcMz3WSIq0NQNuks5qls5vgaJpZM4JxlQj>
> .
>

2016-09-01 17:50 UTC, deads2k commented
> If it's that aggressive, replacing it with `browser` might be better. Not
> sure if we need to be more clear than that?

Replacing it with `Browser` sounds like a good idea.

2016-09-02 18:56 UTC, dominikschulz commented
Changed replacement to "Browser" as per @deads2k suggestion and signed CLA.

Thanks for considering this PR.

2016-09-02 18:59 UTC, deads2k commented
> Changed replacement to "Browser" as per @deads2k suggestion and signed CLA.
> 
> Thanks for considering this PR.

lgtm.  Went ahead and tagged it since lavalamp already said it was ok by him too.

2016-10-03 12:38 UTC, deads2k commented
@k8s-bot test this issue: #IGNORE

2016-10-16 16:58 UTC, wojtek-t commented
@k8s-bot test this, issue: #IGNORE ( Error in queue.)

2016-11-21 08:35 UTC, dominikschulz commented
Any change to get this merged? It's a rather trivial PR.

2016-11-21 14:13 UTC, deads2k commented
@k8s-bot test this, issue: #IGNORE ( Error in queue.)

2016-11-21 14:13 UTC, deads2k commented
> Any change to get this merged? It's a rather trivial PR.

real failures in verify

2016-12-08 06:11 UTC, rmmh commented on pkg/apiserver/metrics/metrics_test.go
> +			Out: "Mozilla",
This should be `Out: "Browser"`

2016-12-08 23:29 UTC, rmmh commented
@dominikschulz this should be able to go in once the test case is fixed

2017-01-26 23:19 UTC, mml requested changes

2017-01-26 23:19 UTC, mml commented on pkg/apiserver/metrics/metrics.go
> +		Monitor(&verb, &resource, cleanUserAgent(utilnet.GetHTTPClient(request.Request)), rw.Header().Get("Content-Type"), delegate.status, now)
Two suggestions.

1. Could we control this behavior with a flag?  I can imagine admins might want to turn it off to debug something.
2. Can we add an extra label to the metric explaining whether or not the client field has been canonicalized?  I vote for a string `clientType` which is either `raw` or `canonicalized`, but we could also do this with a bool.

2017-01-26 23:52 UTC, smarterclayton commented
Could we just output a different field instead of client for canonical
clients?

On Jan 26, 2017, at 6:19 PM, Matt Liggett <notifications@github.com> wrote:

*@mml* requested changes on this pull request.
------------------------------

In pkg/apiserver/metrics/metrics.go
<https://github.com/kubernetes/kubernetes/pull/31783#pullrequestreview-18748752>
:

> @@ -99,10 +100,17 @@ func InstrumentRouteFunc(verb, resource string, routeFunc restful.RouteFunction)
 		response.ResponseWriter = rw

 		routeFunc(request, response)
-		Monitor(&verb, &resource, utilnet.GetHTTPClient(request.Request),
rw.Header().Get("Content-Type"), delegate.status, now)
+		Monitor(&verb, &resource,
cleanUserAgent(utilnet.GetHTTPClient(request.Request)),
rw.Header().Get("Content-Type"), delegate.status, now)

Two suggestions.

   1. Could we control this behavior with a flag? I can imagine admins
   might want to turn it off to debug something.
   2. Can we add an extra label to the metric explaining whether or not the
   client field has been canonicalized? I vote for a string clientType
   which is either raw or canonicalized, but we could also do this with a
   bool.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/31783#pullrequestreview-18748752>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ABG_p5KdJN7w2vseHEjr1-WkDN-n5idbks5rWSoRgaJpZM4JxlQj>
.

2017-02-02 19:49 UTC, dominikschulz commented on pkg/apiserver/metrics/metrics.go
> +		Monitor(&verb, &resource, cleanUserAgent(utilnet.GetHTTPClient(request.Request)), rw.Header().Get("Content-Type"), delegate.status, now)
You could make this depend on a flag, but if you try to turn these metrics into an debugging mechanism you're probably using them wrong.

The same goes for an extra label to tell it has been canonicalized.

If this is necessary to get this merged, ok, but I really think we shouldn't expose our users Prometheus servers to a huger number of (unnecessary) timeseries.

2017-02-02 19:58 UTC, smarterclayton commented
I am 100% behind getting cardinality down.  I don't think reporting the exact value is useful or desired - this is for metrics and general use, not specific tracking of every user on the platform.

2017-02-04 12:59 UTC, dominikschulz commented
Not sure if those failures are real failures or flaky tests. Please advise.

2017-02-06 13:52 UTC, deads2k commented
the dreaded bazel. `hack/update-bazel.sh`

2017-02-06 16:31 UTC, dominikschulz commented
Rebased onto master

2017-02-07 13:41 UTC, dominikschulz commented
@mml @smarterclayton I'd prefer not to introduce an additonal config option/switch to tune this behaviour, instead I'd prefer to keep it as is. WDYT?

2017-02-07 19:38 UTC, smarterclayton commented
Reducing cardinality is the correct thing to do.  This is not supposed to be a replacement for proxy http logging.  I'm ok with not making this configurable.

2017-02-11 07:17 UTC, dominikschulz commented
@mml @smarterclayton Rebased. Please advise on how to continue.

2017-02-14 01:22 UTC, smarterclayton commented
One more time 

/approve

2017-03-06 06:11 UTC, dominikschulz commented
Rebased.

I'm starting to thing that Bazel isn't really suitable for larger projects like this ...

2017-03-06 17:47 UTC, smarterclayton commented
/lgtm

2017-03-06 17:49 UTC, smarterclayton commented
Considering this a bug in that high cardinality causes problems for metrics systems (including those monitoring the cluster), we have unbounded scale there, and this has been on our target list for two releases.  Low risk.

2017-03-06 19:30 UTC, merged

2017-03-07 08:29 UTC, dominikschulz commented
Thanks!