[Controller Manager] Set log level to avoid log spamming
kubernetes/kubernetes pull request #32503
Opened 2016-09-12 15:50 UTC by m1093782566

**What this PR does / why we need it**:

Set controller manager log level to avoid log spamming.

2016-09-12 16:56 UTC, derekwaynecarr commented
@liggitt @pmorie -- can either of you take a quick look at these log levels?  nothing stands out to me as bad per-se, but want to know if we depend on certain pre-existing log levels.

2016-09-13 03:55 UTC, m1093782566 commented
I refer to:

#32462 #32461

2016-09-13 15:18 UTC, m1093782566 commented
code rebased.

2016-09-19 15:08 UTC, derekwaynecarr requested changes
fix the two typos, then lgtm

2016-09-19 15:20 UTC, m1093782566 commented
Typo fixed. PTAL.

2016-09-20 00:15 UTC, m1093782566 commented on pkg/controller/node/nodecontroller.go
> +			glog.V(1).Infof("Initilizing eviction metric for zone: %v", zone)
Fixed

2016-09-20 00:15 UTC, m1093782566 commented on pkg/controller/podautoscaler/horizontal.go
> +		glog.V(2).Infof("Successfull rescale of %s, old size: %d, new size: %d, reason: %s",
Fixed

2016-09-27 02:26 UTC, m1093782566 commented
ping @derekwaynecarr

2016-09-30 18:25 UTC, derekwaynecarr approved these changes

2016-09-30 18:25 UTC, derekwaynecarr commented
please rebase, then LGTM, thanks!

2016-10-01 09:19 UTC, m1093782566 commented
code rebased.

BTW, since this PR changes many files so it's easy to conflict with other PRs.

2016-10-03 08:45 UTC, m1093782566 commented
code rebased ping @derekwaynecarr for final review.

2016-10-08 09:19 UTC, m1093782566 commented
code rebased again!

2016-10-10 15:28 UTC, derekwaynecarr commented
Sorry, this needs another rebase, if we keep hitting problems, maybe split into fewer PRs.

2016-10-18 02:07 UTC, m1093782566 commented
@derekwaynecarr code rebased, PTAL.

Thanks!

2016-10-18 14:45 UTC, derekwaynecarr commented
one more rebase needed

2016-10-19 13:44 UTC, m1093782566 commented
code rebased. BTW, if we hit the code-need-rebase issue again, I will consider split this PR into a few small ones.

2016-10-21 08:27 UTC, m1093782566 commented
@derekwaynecarr PTAL

2016-10-21 19:27 UTC, derekwaynecarr commented
ideally, you would squash your commits, if this gets hit with another need to rebase please do that in the future.

2016-10-22 03:09 UTC, m1093782566 commented
Okay

2016-10-22 06:11 UTC, pmorie commented on pkg/controller/node/nodecontroller.go
> +			glog.V(1).Infof("Initializing eviction metric for zone: %v", zone)
Sorry for the late review, but did you really mean 1 here? @m1093782566

2016-10-23 07:02 UTC, m1093782566 commented on pkg/controller/node/nodecontroller.go
> +			glog.V(1).Infof("Initializing eviction metric for zone: %v", zone)
Yes, but do you have any other ideas?

2016-11-11 00:34 UTC, dims commented
@m1093782566 Please rebase this?

@derekwaynecarr Is this really needed for v1.5? (If not, can you please switch it?)

2016-11-16 21:42 UTC, dims commented
@m1093782566 Please rebase this?

2016-11-17 02:23 UTC, m1093782566 commented
@dims Sure

2016-11-23 13:46 UTC, dims commented
No activity for a while, does not seem super critical for 1.5. moving it to 1.6

2016-12-23 14:22 UTC, closed without merging