[WIP] Encrypt etcd secrets
kubernetes/kubernetes pull request #32579
Opened 2016-09-13 15:23 UTC by stevesloka

This is a first draft code playground to see how I could allow encryption of secrets stored in etcd. 

https://github.com/kubernetes/features/issues/92

2016-09-13 15:31 UTC, erictune commented
@kubernetes/sig-api-machinery 

The OP is trying to encrypt secrets stored in etcd.  He is doing this by adding encryption to the etcd layer.  I think he probably wants to do this in such a way that (1) it only encrypts secrets, and not other resources, and (2) so that it is independent of what storage layer is used (e.g. encrypt the json or proto message, or a portion of it) rather than being built into etcd.  Can someone such as @lavalamp or @smarterclayton or @deads2k who knows this code well suggest where to plug in?

2016-09-13 15:39 UTC, erictune commented
Another consideration: it might be better to have an outer message that is in cleartext, that tells you just metadata about the stored object (name, kind, version), and only encrypt what needs to be encrypted. 

One way to do this is to wrap all storage objects.  I think @lavalamp knows about a plan to do that: not sure if it got implemented. It was needed for protocol buffer storage, I think.

Another way to do it is to add a new field to secrets called `encryptedData`, and to have `data` be set when using the REST api, but move the keys to `encryptedData` when preparing to store the object, in PrepareForCreate and PrepareForUpdate, and move them back to `data` in a new "PrepareForGet" method?

2016-09-13 16:43 UTC, deads2k commented
> Can someone such as @lavalamp or @smarterclayton or @deads2k who knows this code well suggest where to plug in?

I could be modeled as a `storage.Interface` which acts a filter on the original `storage.Interface`.  That could be wired up with a `generic.StorageDecorator` without touching most of the code.

That would let you encrypt before passing to storage and then decrypted before any caching layer saw it.

2016-09-13 17:01 UTC, hongchaodeng commented
I agree that this should be built on top storage layer instead of coupling another encryption field into it.

Another problem is that the interface intends to operate on opaque bytes:
```
	Encrypt(obj string) (string, error)
	Decrypt(encryptedObj string) (string, error)
```
Unfortunately, the storage layer understands k8s objects and operates on objects. If we want to operate on bytes to/from etcd, another KV layer needs to be refactored out.

2016-09-13 18:40 UTC, stevesloka commented
So then there should be 2 approaches to this feature? One is to refactor out the storage layer that understands k8s objects and operates on objects and the second is to create a `generic.StorageDecorator` to handle the encryption / decryption? 

I'm happy to do the work, just need some additional help to get started I think in the codebase. It's getting more clear to me, but still new to it all.

2016-09-13 19:52 UTC, lavalamp commented
@smarterclayton and I have a design (ish) in mind for this already. I haven't looked at this PR yet (very behind on PR reviews right now, sorry), but please don't do a lot of work on it until we agree on the approach. This should be done in the codec/serializer machinery, not the storage layer, and is probably blocked until we start storing in protobuf format (current target 1.5).

2016-09-13 19:56 UTC, stevesloka commented
OK thanks @lavalamp, @smarterclayton and I did have a discussion a week or so ago about it, but I do see how my current implementation needs some love. 

Happy to have a discussion regarding, I think when Clayton and I spoke last, he thought the codec way might of been the wrong place, but again, good to discuss.

What should my next steps be?

2016-09-13 20:04 UTC, lavalamp commented
Can you make it to an API Machinery SIG meeting? That's probably the best
place to talk about this.

On Tue, Sep 13, 2016 at 12:57 PM, Steve Sloka <notifications@github.com>
wrote:

> OK thanks @lavalamp <https://github.com/lavalamp>, @smarterclayton
> <https://github.com/smarterclayton> and I did have a discussion a week or
> so ago about it, but I do see how my current implementation needs some
> love.
>
> Happy to have a discussion regarding, I think when Clayton and I spoke
> last, he thought the codec way might of been the wrong place, but again,
> good to discuss.
>
> What should my next steps be?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/32579#issuecomment-246804015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAnglkD9w0RFQRbXvvs2mf9RGbZRd_8bks5qpwARgaJpZM4J7zZ7>
> .
>

2016-09-13 20:09 UTC, stevesloka commented
Sure thing, I just jointed the google group. When is the next meeting?

2016-09-13 20:17 UTC, lavalamp commented
Tomorrow, 11 AM PDT-- you should have a calendar invite after joining the
group.

On Tue, Sep 13, 2016 at 1:09 PM, Steve Sloka <notifications@github.com>
wrote:

> Sure thing, I just jointed the google group. When is the next meeting?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/32579#issuecomment-246807781>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAnglvEElfQnPtCl7JlftyC8Tj-kK9vCks5qpwMXgaJpZM4J7zZ7>
> .
>

2016-09-14 19:46 UTC, philips commented
Discussion happened today on sig-node. We bounced around a bit. The overall conclusion is that @smarterclayton and I have heard from users that this is desirable and a useful checkbox.

There was further discussion on how to implement it and how the work @hongchaodeng is looking to do with the storage/index design https://github.com/kubernetes/kubernetes/pull/29888.

2016-12-09 16:23 UTC, stevesloka commented
keep open

2016-12-26 18:34 UTC, fernandofederico1984 commented
@stevesloka @philips this is a very desirable feature, what's the status of this PR?, is it forgotten?

2017-01-03 20:02 UTC, stevesloka commented
@fernandofederico1984 No it's not forgotten, the holidays and my time have been distracted by other things.  There's a design doc here: https://docs.google.com/document/d/1lFhPLlvkCo3XFC2xFDPSn0jAGpqKcCCZaNsBAv8zFdE 

I've been working with @andrewsykim on the design doc a bit. I think we need to get it into the sig meeting and have a discussion. I mentioned before I'm happy to do the work. 

I'll bring this up to the SIG group and see if we can have a discussion on it so we can keep it moving.

2017-01-04 14:54 UTC, fernandofederico1984 commented
Thanks! @stevesloka added some comments in the document.

2017-01-27 00:00 UTC, lavalamp commented
Just an FYI, I'm planning on sitting on this PR for a while, sorry... holler if that doesn't work for you. I put the keep open label on.

I'd like to go over the design doc first before I dig into this.

But this quarter is just really packed for me.

2017-01-27 00:28 UTC, andrewsykim commented
@lavalamp @stevesloka and I are currently refactoring the design doc, we agreed that its most likely best if we break this feature up into smaller PRs, we'll report back here when we're done changing up the design doc and if any new PRs come up. :)

2017-01-27 00:39 UTC, smarterclayton commented
I'm going to take and drive this design and ensure it gets review.  So
you can take it off your list - that's my first quarter gift to you!

2017-05-18 03:31 UTC, armstrongli requested changes

2017-05-18 03:31 UTC, armstrongli commented on pkg/storage/etcd/etcd_helper.go
> +	if strings.HasPrefix(key, "/registry/secrets") && h.encryptionProvider != nil {
the prefix is dynamic settings from apiserver.

2017-05-18 03:31 UTC, armstrongli commented on pkg/storage/etcd/etcd_helper.go
> +	if strings.HasPrefix(key, "/registry/secrets") && h.encryptionProvider != nil {
the same on prefix

2017-05-18 04:09 UTC, smarterclayton commented
This PR was rolled up into a newer PR - closing.

2017-05-18 04:09 UTC, closed without merging

2017-06-26 19:27 UTC, pires commented
@smarterclayton which PR?

2017-06-26 19:29 UTC, pires commented
Nevermind. https://github.com/kubernetes/kubernetes/pull/41939