kubelet: eviction: avoid duplicate action on stale stats
kubernetes/kubernetes pull request #32724
Opened 2016-09-14 20:56 UTC by sjenning

Currently, the eviction code can be overly aggressive when synchronize() is called two (or more) times before a particular stat has been recollected by cadvisor.  The eviction manager will take additional  action based on information for which it has already taken actions.

This PR provides a method for the eviction manager to track the timestamp of the last obversation and not take action if the stat has not been updated since the last time synchronize() was run.

@derekwaynecarr @vishh @kubernetes/rh-cluster-infra

2016-09-14 21:42 UTC, vishh commented on pkg/kubelet/eviction/helpers.go
> +		if !found || observed.time.IsZero() || !observed.time.Equal(last.time) {
nit: `!observed.time.After(last.time)` might be more readable.

2016-09-14 21:43 UTC, vishh approved these changes
Just one nit. Otherwise LGTM

2016-09-15 13:57 UTC, sjenning commented
@vishh thanks for the review! nit fixed.

2016-09-19 14:43 UTC, derekwaynecarr commented on pkg/kubelet/eviction/helpers.go
> +func thresholdsUpdatedStats(thresholds []Threshold, observations, lastObservations signalObservations) []Threshold {
can you add a test case for this?

2016-09-19 14:45 UTC, derekwaynecarr commented on pkg/kubelet/eviction/helpers.go
> +			time:      memory.Time,
can you open an issue and add a TODO so we can have a time associated with `FsStats` ?

2016-09-19 14:45 UTC, derekwaynecarr requested changes
test case request, and a follow-on issue to do the same for `FsStats`.

2016-09-19 21:22 UTC, sjenning commented
@derekwaynecarr added todos and test cases (and fixed a bug exposed by the test cases) and opened an issue for FsStats needed a timestamp https://github.com/kubernetes/kubernetes/issues/33049

2016-10-06 16:37 UTC, derekwaynecarr approved these changes

2016-10-06 18:05 UTC, merged