return warning on empty list result in kubectl get
kubernetes/kubernetes pull request #32722
Opened 2016-09-14 20:32 UTC by juanvallejo

**Release note**:
```release-note
NONE
```

The current default behavior of `kubectl get` is to return an empty
output when there are no resources to display. This patch improves
usability by returning a warning through stderr in the case of an empty
list.

##### Before
`$ kubectl get pods`
  - *empty output*

##### After
`$ kubectl get pods`
```
There are no resources to display.
```

2016-09-19 00:30 UTC, smarterclayton commented on pkg/kubectl/cmd/get.go
> +			fmt.Fprintf(errOut, "%s %q %s\n", "No resources found in namespace", cmdNamespace, "that match your criteria.")
Get can be used on cluster scoped or across multiple namespaces so this message is too specific.  I'd recommend just using a more generic message "No resources found".  The alternative is a more complex integration into resource.Builder - you'd need to accumulate and store markers of intent when the resource builder crafts a Result and then have the Result be able to spit out a non-generic message.  Not sure it's worth it.

2016-09-19 00:30 UTC, smarterclayton requested changes

2016-09-19 20:22 UTC, fabianofranz commented on pkg/kubectl/cmd/get.go
> +			fmt.Fprintf(errOut, "%s %q %s\n", "No resources found in namespace", cmdNamespace, "that match your criteria.")
Makes sense, "No resources found" works for me at least for now.

2016-09-22 22:29 UTC, janetkuo commented
Should we print "No resource found" for the `watch` case also?

I'd suggest making this a function (check `len(infos)==0` and print the warning if so), and put the check right after Infos() is called (fail early).

2016-09-22 22:32 UTC, smarterclayton commented
With the watch case can the object show up?  I thought we allowed you to
watch something that does not exist yet.

On Thu, Sep 22, 2016 at 6:30 PM, Janet Kuo <notifications@github.com> wrote:

> Should we print "No resource found" for the watch case also?
>
> I'd suggest making this a function (check len(infos)==0 and print the
> warning if so), and put the check right after Infos() is called (fail
> early).
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/32722#issuecomment-249046981>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p8OJ5kyCvEoeF1ZD3cwsz7sY20Ewks5qswFrgaJpZM4J9Na6>
> .
>

2016-09-22 22:51 UTC, janetkuo commented
Yeah we allow you to do that. Printing `No resource found` doesn't stop you from keep watching. Or maybe it's not needed for `watch`?

2016-09-23 01:14 UTC, smarterclayton commented
It might be ok to print "Resource does not yet exist" but that might be
overthinking it.

On Sep 22, 2016, at 6:51 PM, Janet Kuo <notifications@github.com> wrote:

Yeah we allow you to do that. Printing No resource found doesn't stop you
from keep watching. Or maybe it's not needed for watch?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/32722#issuecomment-249051052>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ABG_p_wCZf80Bi_Luf3NXXXdUiKxVPeHks5qswZ5gaJpZM4J9Na6>
.

2016-09-26 23:05 UTC, janetkuo commented on pkg/kubectl/cmd/get.go
> +			fmt.Fprintf(errOut, "%s\n", "No resources found.")
Abstract this into a function

2016-09-26 23:07 UTC, janetkuo commented on pkg/kubectl/cmd/get.go
> +		fmt.Fprintf(errOut, "%s\n", "No resources found.")
Check for `len(infos)` here, and move both checks right after `infos` is created. 
We can also return right away after no resource found (optional).

2016-09-26 23:07 UTC, janetkuo requested changes

2016-09-27 17:41 UTC, juanvallejo commented
@janetkuo 
> Check for len(infos) here, and move both checks right after infos is created. 
We can also return right away after no resource found (optional).

Thanks for the suggestions! I looked into returning as soon as no resources are found, but this would prevent any additonal errors that may have occurred from printing

2016-09-27 21:35 UTC, janetkuo commented
LGTM. Please squash the commits and I'll apply the tag.

2016-09-27 21:35 UTC, janetkuo approved these changes

2016-09-28 14:42 UTC, juanvallejo commented
@janetkuo 
> LGTM. Please squash the commits and I'll apply the tag.

Done!

2016-10-04 13:54 UTC, juanvallejo commented
@janetkuo or @smarterclayton PTAL

2016-10-12 23:24 UTC, janetkuo commented
Need @smarterclayton's approval on changes

2016-10-12 23:35 UTC, smarterclayton approved these changes

2016-10-13 06:48 UTC, merged