Ready ds
kubernetes/kubernetes pull request #32781
Opened 2016-09-15 12:34 UTC by lukaszo

Fixes #25605

2016-09-15 19:23 UTC, smarterclayton commented
@kubernetes/api-review-team for addition of `ReadyScheduled`.

The code looks correct, can you add two things - unit test to daemoncontroller_test.go, and add this to the existing daemonset e2e tests.

2016-09-19 06:46 UTC, lukaszo commented
@smarterclayton I added unit test and added check to e2e tests. Please take a look

2016-09-20 07:55 UTC, lukaszo commented
@kubernetes/daemonset ping. Please review

2016-09-20 08:21 UTC, mikedanese commented
LGTM

2016-09-20 19:24 UTC, smarterclayton commented
Changes LGTM to me as well, but still needs an API sign off.

2016-09-21 11:12 UTC, lukaszo commented
@smarterclayton: @mikedanese is a member of @kubernetes/api-review-team and he gave lgtm

2016-09-21 21:00 UTC, mikedanese commented on pkg/apis/extensions/types.go
> +	ReadyScheduled int32 `json:"readyScheduled"`
NumberReady is probably a better name for this field.

2016-09-21 21:05 UTC, mikedanese requested changes
I did not give this an API review. I only reviewed the controller code. I would like @davidopp or @bgrant0607 to do a once over once you address my comments.

2016-09-23 00:52 UTC, bgrant0607 commented
cc @pwittrock @janetkuo @erictune @kargakis

2016-09-23 00:54 UTC, bgrant0607 commented
@lukaszo @mikedanese This is ready nodes or ready pods?

2016-09-23 00:55 UTC, bgrant0607 commented on pkg/apis/extensions/types.go
> +	ReadyScheduled int32 `json:"readyScheduled"`
No field names contain the string "Number". I'd like to keep it that way. :-)

2016-09-23 00:57 UTC, bgrant0607 commented on pkg/apis/extensions/types.go
> +	ReadyScheduled int32 `json:"readyScheduled"`
Ok, that's no longer true. But let's not introduce more occurrences.

2016-09-23 00:57 UTC, mikedanese commented on pkg/apis/extensions/types.go
> +	ReadyScheduled int32 `json:"readyScheduled"`
All the other fields in the DaemonSetStatus contain the string "Number".

2016-09-23 00:57 UTC, mikedanese commented
@bgrant0607 This is the number of nodes that should be running the daemon pod and have one or more of the daemon pod running and ready.

2016-09-23 09:43 UTC, kargakis commented
LGTM

2016-09-23 11:23 UTC, lukaszo commented on pkg/apis/extensions/types.go
> +	// The number of ready pods for this daemon set.
I updated the name and description

2016-09-23 11:23 UTC, lukaszo commented on pkg/apis/extensions/types.go
> +	ReadyScheduled int32 `json:"readyScheduled"`
I updated commits and changed to NumberReady

2016-09-27 08:16 UTC, lukaszo commented
Ping. I need it for DaemonSet updates #31693

2016-09-28 02:41 UTC, bgrant0607 commented on pkg/apis/extensions/types.go
> +	ReadyScheduled int32 `json:"readyScheduled"`
My own rule is that consistency trumps most other concerns, so any of NumberReady, ReadyNumberScheduled, or NumberReadyScheduled would be fine.

2016-09-28 11:57 UTC, lukaszo commented
@mikedanese I changed name to NumberReady and @bgrant0607  accepts it. Do you need any more actions from me?

2016-09-28 22:02 UTC, lukaszo commented
@k8s-bot gci gce e2e test this

2016-09-29 07:40 UTC, lukaszo commented
Can someone restart the tests? Tests are passing for me locally.

2016-09-29 10:19 UTC, kargakis commented
@lukaszo you need to rebase

2016-10-03 17:58 UTC, lukaszo commented
@k8s-bot unit test this #33784.

2016-10-03 19:35 UTC, lukaszo commented
@k8s-bot gce e2e test this

2016-10-03 20:27 UTC, lukaszo commented
@k8s-bot gke e2e test this

2016-10-03 20:28 UTC, lukaszo commented
@k8s-bot gci gke e2e test this

2016-10-03 21:59 UTC, lukaszo commented
Ok, now all tests are passing. @kubernetes/daemonset PTAL

2016-10-07 09:14 UTC, lukaszo commented
@mikedanese @kargakis can you add LGTM or do I need to change something more?

2016-10-07 09:19 UTC, kargakis commented
lgtm

General question: how did we manage to mess the daemon status field names like that?:)

2016-10-10 18:10 UTC, lukaszo commented
@k8s-bot gce e2e test this

2016-10-10 18:10 UTC, lukaszo commented
@k8s-bot verify test this

2016-10-11 06:48 UTC, lukaszo commented
@k8s-bot gke e2e test this

2016-10-11 08:36 UTC, lukaszo commented
@kargakis  can you re-lgtm? I had to rebase again

2016-10-11 09:56 UTC, kargakis commented on pkg/controller/daemon/daemoncontroller.go
> +				sort.Sort(podByCreationTimestamp(daemonPods))
Do we need to sort pods here?

2016-10-11 16:29 UTC, lukaszo commented on pkg/controller/daemon/daemoncontroller.go
> +				sort.Sort(podByCreationTimestamp(daemonPods))
I'm using the same approach as here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L458-L460
If `dsc.getNodesToDaemonPods(ds)` returns more than one pod on node I want to get status of the youngest pod.

2016-10-11 17:41 UTC, spxtr commented
@k8s-bot test this

2016-10-11 19:44 UTC, lukaszo commented
@k8s-bot unit test this #34547

2016-10-11 20:09 UTC, lukaszo commented
@k8s-bot gce e2e test this 
I think that it's this flake issue #33867

2016-10-11 20:21 UTC, lukaszo commented on pkg/controller/daemon/daemoncontroller.go
> +				sort.Sort(podByCreationTimestamp(daemonPods))
Ah yes, the oldest. Sorry.

2016-10-11 22:52 UTC, lukaszo commented
@k8s-bot cvm gce e2e test this #33867

2016-10-12 08:11 UTC, lukaszo commented
@k8s-bot unit test this

Looks like downloading etcd failed

2016-10-12 09:51 UTC, lukaszo commented
@kargakis can you one more time add lgtm? I had to rebase to get a fix for this flake #34547

2016-10-12 13:25 UTC, kargakis commented
@lukaszo sorry, you need one more rebase

2016-10-12 15:06 UTC, lukaszo commented
@kargakis rebased

2016-10-13 07:25 UTC, merged

2016-10-17 17:30 UTC, ahakanbaba commented
HI @lukaszo  we are also very interested in benefiting from this change. Thank you for taking this on and seeing it through. 
We were wondering, is there any indication in which api version this change will be a part of. 

I see that the extensions_v1beta1.json file has changed. Does that mean that this change will be in api version v1beta1. 

This change is not in the 1.4.3 release. I also cannot see it in the v1.5.0-alpha.1 tag. 

Does anyone know which kubernetes release is likely to have this new api addition ?

2016-10-18 16:25 UTC, lukaszo commented
Hi @ahakanbaba currently it's available only in master brach. It will be also available in v1.5.0-alpha2 release which should be released in a few days.

Yes, it will be in  api version v1beta1.

2016-10-20 16:52 UTC, ahakanbaba commented
@lukaszo Thank you very much for the clarification.