Adding the option for the system to use the HOME env for windows.
kubernetes/kubernetes pull request #32790
Opened 2016-09-15 14:19 UTC by mayman

Adding the option of checking for the HOME environment on windows. As on a work network, HOMEDRIVE is setup from the Group Policy on a work network.

Initial change was made https://github.com/kubernetes/kubernetes/pull/17590

This change would fix this issue: 
https://github.com/kubernetes/minikube/issues/459

2016-09-15 19:45 UTC, smarterclayton commented
@fabianofranz

2016-10-03 09:24 UTC, mayman commented
@smarterclayton @fabianofranz 

Hello, 

Apologies for bugging, but would somebody be able to have a look at the pull request please.

Kind Regards,

Dilyan

2016-10-06 01:22 UTC, fabianofranz requested changes

2016-10-06 01:22 UTC, fabianofranz commented on pkg/util/homedir/homedir.go
> +	if runtime.GOOS == "windows"; len(os.Getenv("HOME")) <= 0) {
Leave this line as is and do, right below inside the windows condition:

```
if home := os.Getenv("HOME"); len(home) > 0 {
  if _, err := os.Stat(home); err == nil {
    return home
  }
}
```

on Windows we always need a `os.Stat` to make sure it's good to use.

2016-10-06 01:22 UTC, fabianofranz commented on pkg/util/homedir/homedir.go
> +	if runtime.GOOS == "windows"; len(os.Getenv("HOME")) <= 0) {
You will probably need a migration [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/loader.go#L56-L66) (Windows only) to make sure that users get their configs migrated correctly if they are relying on the current approach.

2016-10-19 18:05 UTC, mayman commented on pkg/util/homedir/homedir.go
> +	if runtime.GOOS == "windows"; len(os.Getenv("HOME")) <= 0) {
I thought that I could do something similar as the homedir.go, but then I noticed that 
RecommendedHomeFile is also used [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/loader.go#L134-L149)

I am not entirely sure if this won't break anything further down the line.

Could you please have a look and let me know if you could recommend something else?
~~~Go
if goruntime.GOOS == "windows" {
    if home := os.Getenv("HOME"); len(home) > 0 {
        if _, err := os.Stat(home); err = nill {
            migrationRules[oldRecommendedWindowsHomeFile] = RecommendedHomeFile
        }
    } else {
        migrationRules[RecommendedHomeFile] = oldRecommendedWindowsHomeFile
    }
}
~~~

2016-11-11 14:16 UTC, mayman commented
Hi @fabianofranz, could you please have a look at my latest query?

Kind regards,

Dilyan

2016-12-09 11:39 UTC, mayman commented
@smarterclayton Hey, could you please close/decline this PR as the issue was resolved with #35745.

Kind Regards,

Dilyan

2016-12-09 19:03 UTC, closed without merging