added binding details to design/persistent-storage doc
kubernetes/kubernetes pull request #32817
Opened 2016-09-15 20:44 UTC by jeffvance

Scroll down to "Matching and binding" (there is no TOC).
An issue I see is that this level of detail may get stale quickly and there is no built-in mechanism to update this doc when the binding code changes. However, several people on my team, from time to time, want to know greater details about binding rules, eg. for test writing, updating/creating other docs, etc.

PTAL @jsafrane @pmorie @copejon

2016-09-16 07:44 UTC, jsafrane commented on docs/design/persistent-storage.md
> +
Please add a note that if no PV matches and a storage class is specified (or a default is set), then a volume is dynamically provisioned.

2016-09-16 07:44 UTC, jsafrane requested changes

2016-09-16 07:45 UTC, jsafrane commented
Note that this PR does not "add" a new design, it updates the current one with actual implementation details.

2016-10-07 02:40 UTC, jeffvance commented
@jsafrane _Note that this PR does not "add" a new design, it updates the current one with actual implementation details._
Agree. Changed pr title.  Thanks

2016-10-18 17:08 UTC, jeffvance commented
@saad @eparis I've re-filled out the cla application so hopefully that issue is cleared now. @jsafrane can you LTGM ? Would very much like to get this pr merged and off my plate. Thanks!

2016-10-19 10:11 UTC, jsafrane commented
@jeffvance, I'm waiting for this comment to be addressed: https://github.com/kubernetes/kubernetes/pull/32817#discussion_r79119998

After that, I'll be happy to merge this PR.

2016-10-19 15:40 UTC, jeffvance commented
@jsafrane Sorry I missed your above comment. I just added the note. PTAL and hopefully now it is ok to merge. Thanks!

2016-10-19 16:27 UTC, jeffvance commented
From error log: `E1019 08:53:14.668] FAIL: pull-kubernetes-e2e-gke-gci`.
@k8s-bot gci gke e2e test this

2016-10-19 21:35 UTC, jeffvance commented
@jsafrane @saad-ali  Same CGI GKE smoke e2e error as above: `E1019 09:44:37.206] FAIL: pull-kubernetes-e2e-gke-gci`. Is it ok to ignore this error? If so then can this pr be merged now?  Thanks.

2016-11-16 03:31 UTC, jeffvance commented
Ping @jsafrane @erinboyd @childsb can one of you PTAL? I believe this addition to the doc is still current -- Jan?

2016-11-18 10:46 UTC, jsafrane approved these changes

2016-11-18 10:46 UTC, jsafrane commented
/lgtm

2016-11-28 18:53 UTC, merged