Implement cleanup methods to cleanup underlying cluster resources in federated service tests.
kubernetes/kubernetes pull request #32810
Opened 2016-09-15 18:37 UTC by madhusudancs

cc @kubernetes/sig-cluster-federation @colhom

2016-09-15 18:38 UTC, madhusudancs commented
@k8s-bot federation gce e2e test this

2016-09-15 23:58 UTC, nikhiljindal commented on test/e2e/federated-service.go
> +				By(fmt.Sprintf("Deleting service shards and their provider resources in underlying clusters for service %q in namespace %q", service.Name, nsName))
Move this to AfterEach so that it always runs?

2016-09-15 23:59 UTC, nikhiljindal requested changes

2016-09-16 00:00 UTC, nikhiljindal commented
Also do you want to do the same for ingress test as well?

2016-09-16 00:01 UTC, nikhiljindal commented
That new red cross for changes requested is really big!

2016-09-16 03:31 UTC, madhusudancs commented on test/e2e/federated-service.go
> +				By(fmt.Sprintf("Deleting service shards and their provider resources in underlying clusters for service %q in namespace %q", service.Name, nsName))
Done.

2016-09-16 03:32 UTC, madhusudancs reviewed
> Also do you want to do the same for ingress test as well?

Yeah, but in a follow up PR.

2016-09-16 03:33 UTC, madhusudancs commented
@nikhiljindal Addressed your comments. PTAL.

2016-09-16 04:46 UTC, madhusudancs commented
@k8s-bot federation gce e2e test this

2016-09-19 20:15 UTC, nikhiljindal commented
LGTM, thanks!

2016-09-20 12:56 UTC, merged

2016-09-20 17:29 UTC, nikhiljindal commented
@madhusudancs I assume you want this cherrypicked as well?
Otherwise the new release-1.4 tests that you have setup will keep failing without this.

2016-09-20 21:37 UTC, madhusudancs commented
@nikhiljindal I would like this to be cherry-picked. But I don't mind if it is not cherry-picked right now, i.e. for 1.4.0. It could be cherry-picked later for one of the patch releases.