simplify RC and SVC listers
kubernetes/kubernetes pull request #32888
Opened 2016-09-16 18:42 UTC by deads2k

Make the RC and SVC listers use the common list functions that more closely match client APIs, are consistent with other listers, and avoid unnecessary copies.

2016-09-16 20:37 UTC, smarterclayton commented on pkg/client/cache/listers.go
> +type AppendFunc func(interface{})
Godoc

2016-09-16 20:37 UTC, smarterclayton commented on pkg/client/cache/listers_core.go
> +/*****************************************************************************/
Unusual, we don't do this.  Remove.  Add nice godoc to StoreToReplicationControllerLister instead.

2016-09-16 20:38 UTC, smarterclayton commented on pkg/client/cache/listers_core.go
> +/*****************************************************************************/
Unusual remove

2016-09-16 20:39 UTC, smarterclayton requested changes
Minor changes, godoc on the lister types.

2016-09-16 21:50 UTC, deads2k commented
@smarterclayton what about the changes from shallow copies to pointers?

2016-09-19 14:35 UTC, deads2k commented
comments addressed.

2016-09-19 19:00 UTC, deads2k commented
@k8s-bot test this: issue #31706

2016-09-19 22:26 UTC, smarterclayton commented
Pointers are better than shallow copies in almost every scenario except an specific optimization or for gross user simplicity.

2016-09-20 13:08 UTC, deads2k commented
@smarterclayton any other changes or are you good with this?

2016-09-20 14:53 UTC, deads2k commented
in person lgtm from clayton

2016-09-20 21:32 UTC, smarterclayton approved these changes

2016-09-21 11:13 UTC, merged

2016-09-22 12:34 UTC, sttts commented on pkg/client/cache/listers_core.go
> +func (s storeReplicationControllersNamespacer) Get(name string) (*api.ReplicationController, error) {
any reason to have a non-pointer receiver here and above?

2016-09-22 12:37 UTC, deads2k commented on pkg/client/cache/listers_core.go
> +func (s storeReplicationControllersNamespacer) Get(name string) (*api.ReplicationController, error) {
> any reason to have a non-pointer receiver here and above?

No, cargo-cult.

2016-09-22 12:48 UTC, sttts commented on pkg/client/cache/listers_core.go
> +		ret = append(ret, m.(*api.Service))
this potentially returns non-nil lists for `err != nil`. Intentional?

2016-09-22 12:48 UTC, sttts commented on pkg/client/cache/listers_core.go
> +	})
here again, ret != nil for err != nil.

2016-09-22 12:56 UTC, sttts commented on plugin/pkg/scheduler/algorithm/predicates/predicates.go
> +		if err == nil && len(services) > 0 {
why this additional check? Err should be non-nil in that case.

2016-09-22 12:57 UTC, sttts commented on plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go
> +	if services, err := s.serviceLister.GetPodServices(pod); err == nil && len(services) > 0 {
Like above, err == nil => len(services) > 0