fix upgrade test for 1.2->1.4
kubernetes/kubernetes pull request #32895
Opened 2016-09-16 20:12 UTC by jfrazelle

**What this PR does / why we need it**: fixes #32700 upgrade test since jobs started with --restart=Never after v1.3.0 are considered pods.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```
fix #32700

Signed-off-by: Jess Frazelle <me@jessfraz.com>

2016-09-16 21:22 UTC, janetkuo commented on test/e2e/kubectl.go
> +				Skipf("Skipping test for version >= v1.3.0 since jobs started with --restart=Never are pods")
We're skipping test for version <1.3, right?

2016-09-16 21:25 UTC, janetkuo commented on test/e2e/kubectl.go
> +			isPod, err := serverVersionGTE(version.MustParse("v1.3.0"), c)
Suggest creating `jobGeneratorVersion = version.MustParse("v1.3.0-alpha.5")` (or better name) and change `SkipUnlessServerVersionGTE(jobsVersion, c)` to `SkipUnlessServerVersionGTE(jobGeneratorVersion, c)`. And add comments there as other var xxxVersion does

2016-09-16 21:26 UTC, janetkuo requested changes

2016-09-16 21:28 UTC, jfrazelle commented on test/e2e/kubectl.go
> +				Skipf("Skipping test for version >= v1.3.0 since jobs started with --restart=Never are pods")
the server is 1.4 and the tests being run are the 1.2 tests. So we are skipping if the server version is above 1.3

2016-09-16 21:28 UTC, jfrazelle commented on test/e2e/kubectl.go
> +			isPod, err := serverVersionGTE(version.MustParse("v1.3.0"), c)
that wont work because we need to skip when the server version is greater than 1.3

2016-09-16 21:35 UTC, janetkuo commented on test/e2e/kubectl.go
> +			isPod, err := serverVersionGTE(version.MustParse("v1.3.0"), c)
Ah, I see. So the comment `if the version is <= 1.3.0 the job with --restart=Never is a pod` should be `>1.3.0`? Can we add `SkipUnlessServerVersionLTE` and use that instead?

2016-09-16 21:37 UTC, jfrazelle commented
sure yeah, just didn't know how much I could change old tests haha

On Fri, Sep 16, 2016 at 2:36 PM, Janet Kuo <notifications@github.com> wrote:

> *@janetkuo* commented on this pull request.
> ------------------------------
>
> In test/e2e/kubectl.go
> <https://github.com/kubernetes/kubernetes/pull/32895>:
>
> > @@ -1107,6 +1107,14 @@ var _ = Describe("Kubectl client", func() {
>
>  		It("should create a job from an image when restart is Never [Conformance]", func() {
>  			SkipUnlessServerVersionGTE(jobsVersion, c)
> +			// if the version is <= 1.3.0 the job with --restart=Never is a pod, see: https://github.com/kubernetes/kubernetes/commit/d76fa8a1197a6329da3125c8bfb2202dfead1273
> +			isPod, err := serverVersionGTE(version.MustParse("v1.3.0"), c)
>
> Ah, I see. So the comment if the version is <= 1.3.0 the job with
> --restart=Never is a pod should be >1.3.0? Can we add
> SkipUnlessServerVersionLTE and use that instead?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/32895>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABYNbCT-KQyttZq-2gRqUcoOW5aPmX_zks5qqwvPgaJpZM4J_ThR>
> .
>

2016-09-16 21:39 UTC, janetkuo commented
Or at least update the comment and use `v1.3.0-alpha.5` instead

2016-09-16 21:55 UTC, jfrazelle commented on test/e2e/kubectl.go
> +			isPod, err := serverVersionGTE(version.MustParse("v1.3.0"), c)
added :) will be helpful in the other fix too

2016-09-16 22:14 UTC, janetkuo commented on test/e2e/kubectl.go
> +			// if the version is <= 1.3.0 the job with --restart=Never is a pod, see: https://github.com/kubernetes/kubernetes/commit/d76fa8a1197a6329da3125c8bfb2202dfead1273
`>=`

2016-09-16 22:14 UTC, janetkuo approved these changes

2016-09-16 22:15 UTC, jfrazelle commented on test/e2e/kubectl.go
> +			// if the version is <= 1.3.0 the job with --restart=Never is a pod, see: https://github.com/kubernetes/kubernetes/commit/d76fa8a1197a6329da3125c8bfb2202dfead1273
good catch

2016-09-17 15:58 UTC, pwittrock commented
@k8s-bot test this issue: #IGNORE

2016-09-17 17:42 UTC, merged