Viper direct bindings to TestContext struct with hierarchichal suppor…
kubernetes/kubernetes pull request #32902
Opened 2016-09-16 21:00 UTC by jayunit100

Part of #31030 to support hierarchichal parameters.  This one does so for density, paves way for other tests as well.

2016-09-16 21:07 UTC, timothysc commented
/cc @gmarek

2016-09-16 21:08 UTC, jayunit100 commented
cc @kubernetes/sig-testing -- first hierarchichal test parameter :), this will pave the way for others

2016-09-16 21:08 UTC, jayunit100 commented
Example usage:

```
{ 
        "Density":{
                "AllLatencyTests":"true"
        }
}
```

2016-09-19 19:56 UTC, fejta commented
Neat! Is this documented somewhere? How about giving an example in https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#building-and-running-the-tests

2016-09-20 02:17 UTC, jayunit100 commented
@fejta ok, done , in a separate commit.  Next up i will add a flag description also so that users will always see the viper option when poking at the cmd line #33062 .

2016-09-20 02:24 UTC, jayunit100 commented
Ah, @fejta , i pushed another commit into this branch, just for the viper config.  Might need a refresh on LGTM.

2016-09-20 10:33 UTC, gmarek commented
Sorry - I won't have time to look at this this week.

2016-09-20 13:19 UTC, jayunit100 commented
(these are separate commits based on feature - density, docs, viper flag).

2016-09-20 14:01 UTC, timothysc commented on docs/devel/e2e-tests.md
> +Flags in general fall apart once tests become sufficiently complicated.  So, even if we could use another flag library, it wouldnt be ideal.
s/wouldnt/wouldn't

2016-09-20 14:01 UTC, timothysc commented on docs/devel/e2e-tests.md
> +To use viper, rather than flags, to configure youre tests:
s/youre/your

2016-09-20 14:02 UTC, timothysc commented on docs/devel/e2e-tests.md
> +- Just add "e2e.json" to the current directory you are in, and define parameters in it... i.e. `"kubeconfig":"/tmp/x"`.
could we dump and gobindata it?

2016-09-20 14:02 UTC, timothysc commented on docs/devel/e2e-tests.md
> +In time, it is our intent to add or autogenerate a sample viper configuration that includes all e2e parameters, to ship with kubernetes.
w00t

2016-09-20 14:04 UTC, timothysc commented on test/e2e/density.go
> +		{podsPerNode: 3, runLatencyTest: framework.TestContext.Density.AllLatencyTests || false, interval: 10 * time.Second},
Could we choose a different test + flag that fed-through from input options. 

I think we should treat refactoring of Density with care.

2016-09-20 14:04 UTC, timothysc commented on test/e2e/framework/test_context.go
> +	flag.StringVar(&TestContext.Viper, "viper-config", "e2e", "The name of the viper config i.e. 'e2e' will read values from 'e2e.json' locally.  All e2e parameters are meant to be configurable by viper
awesome

2016-09-20 14:05 UTC, timothysc commented on test/e2e/framework/test_context.go
> +	/** This can be used to overwrite a flag value.
Is there any reason to keep the comment block?

2016-09-20 14:05 UTC, timothysc requested changes
Minor changes then lgtm.

2016-09-20 14:31 UTC, jayunit100 commented
@k8s-bot gce e2e test this.

2016-09-20 14:35 UTC, jayunit100 commented on test/e2e/framework/test_context.go
> +	/** This can be used to overwrite a flag value.
i think so - we havent yet decided what the future of old flags is.  up to u though..

2016-09-20 15:04 UTC, jayunit100 commented on docs/devel/e2e-tests.md
> +- Just add "e2e.json" to the current directory you are in, and define parameters in it... i.e. `"kubeconfig":"/tmp/x"`.
yeah, we could integrate dumping into the binary at some point.  maybe a follow on PR for that as it would be a separate body of work.

2016-09-20 15:55 UTC, jayunit100 commented
@k8s-bot test this issue: #22655

2016-09-20 18:15 UTC, jayunit100 commented
@k8s-bot test this issue: #32770

2016-09-20 18:54 UTC, timothysc commented on test/e2e/framework/test_context.go
> +	flag.StringVar(&TestContext.Viper, "viper-config", "e2e", "The name of the viper config i.e. 'e2e' will read values from 'e2e.json' locally.  All e2e parameters are meant to be configurable by viper
Have you validated the input json feeds through to the tests for cadvisor?

2016-09-20 19:46 UTC, jayunit100 commented
@timothysc below the two jsons variably permute Cadvisor params.  in verifying i realized that this won't work in node-e2e, since they dont yet support viper.  I put this at the top so that viper configs work in both. 

```
{ 
        "e2e-verify-service-account":"true",
        "context":"x",
        "Cadvisor":{
                "MaxRetries":100,
                "SleepDurationMS":2000
        },
        "cadvisor":{
                "maxRetries":100,
                "sleepDurationMS":2000
        }
}
(((((((((((((
{ 
        "e2e-verify-service-account":"true",
        "context":"x"
}
```

2016-09-20 20:13 UTC, timothysc approved these changes

2016-09-20 22:11 UTC, merged