Staging 1.5 client
kubernetes/kubernetes pull request #32906
Opened 2016-09-16 21:38 UTC by caesarxuchao

Created the 1.5 folder and remove the 1.4 folder in the staging area in the master branch.

Content of kubernetes/client-go/1.4 will be pulled from the kubernetes/kubernetes 1.4 branch (https://github.com/kubernetes/contrib/pull/1719)

2016-09-19 17:28 UTC, caesarxuchao commented
@k8s-bot test this, issue #IGNORE

2016-09-20 22:51 UTC, lavalamp commented
Can you make the commit in the middle do a rename instead of having a delete & then recreate commit?

Also test is red?

Then lgtm.

2016-09-21 00:27 UTC, caesarxuchao commented
I merged the commit, but github doesn't show them as renaming, maybe it's because too many files are moved.

2016-09-21 00:32 UTC, lavalamp commented
I think you may have dropped the second commit instead of squashing them, github says only +7 lines right now...

2016-09-21 00:34 UTC, caesarxuchao commented
No, I didn't drop it. Github is broken.

2016-09-21 20:46 UTC, mml commented on test/e2e/disruption.go
> +	release_1_4 "k8s.io/client-go/1.5/kubernetes"
Bad name for this import.

2016-09-21 20:46 UTC, mml requested changes

2016-09-21 20:47 UTC, mml commented
@caesarxuchao Also I think you want release-note-none.

2016-09-21 21:35 UTC, caesarxuchao commented on test/e2e/disruption.go
> +	release_1_4 "k8s.io/client-go/1.5/kubernetes"
Nice catch. I remove the rename.

2016-09-21 21:45 UTC, caesarxuchao commented
Can I get the label? Thanks.

2016-09-21 22:15 UTC, mml approved these changes

2016-09-21 22:18 UTC, mml commented
@lavalamp git doesn't distinguish actually have a way to track file rename/move operations.  Instead it does "rename detection" when it tries to summarize a change to you.

LGTM

2016-09-21 22:51 UTC, caesarxuchao commented
@k8s-bot e2e test this, issue #33175.

2016-09-23 02:55 UTC, merged