CRI: Add missing sandbox in runningPod.
kubernetes/kubernetes pull request #32934
Opened 2016-09-17 02:21 UTC by yifan-gu

Add a container that represents pod sandbox when converting the
pod status to runningPod.

Without the change, `kubeGenericRuntimeManager.killPodWithSyncResult()` will not kill any sandboxes.

cc @feiskyer @Random-Liu @yujuhong

2016-09-17 06:51 UTC, feiskyer commented on pkg/kubelet/container/helpers.go
> +	runningPod.Sandboxes = append(runningPod.Sandboxes, &Container{
Should change this logic to:

```go
for _, sandbox := range podStatus.SandboxStatuses {
		runningPod.Sandboxes = append(runningPod.Sandboxes, &Container{
			ID: sandbox.GetId(),
                        Type: runtimeName,
		})
	}
```

2016-09-17 06:51 UTC, feiskyer requested changes

2016-09-19 19:49 UTC, yifan-gu commented on pkg/kubelet/container/helpers.go
> +	runningPod.Sandboxes = append(runningPod.Sandboxes, &Container{
@feiskyer Fixed.

2016-09-19 19:52 UTC, yifan-gu commented
@feiskyer @yujuhong @Random-Liu Updated the patch. Verified that `kubectl create -f example/pod` works for me now.

2016-09-19 20:01 UTC, yujuhong commented
Thanks for fixing this!

2016-09-19 20:48 UTC, merged