HA master: add firewall rule for etcd cluster.
kubernetes/kubernetes pull request #33094
Opened 2016-09-20 14:36 UTC by jszczepkowski

HA master: add firewall rule for accessing & securing etcd cluster.

2016-09-21 13:43 UTC, fgrzadkowski commented on cluster/gce/util.sh
> +  # Create rule for accessing and securing etcd servers.
I think this should be created in `create-master` method where we also create other firewall rules specific for the master.

2016-09-21 13:44 UTC, fgrzadkowski commented on cluster/gce/util.sh
> +      --source-tags "${MASTER_NAME}" \
s/MASTER_NAME/MASTER_TAG

2016-09-21 13:44 UTC, fgrzadkowski commented on cluster/gce/util.sh
> +      --target-tags "${MASTER_NAME}" &
ditto

2016-09-21 13:45 UTC, fgrzadkowski commented on cluster/gce/util.sh
> +      --allow "tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp" &
This rule means that accessing this port on any machine, including regular nodes, is not allowed. I think we should only limit this to the master. WDYT?

2016-09-21 13:46 UTC, fgrzadkowski requested changes

2016-09-26 07:41 UTC, jszczepkowski commented on cluster/gce/util.sh
> +      --source-tags "${MASTER_NAME}" \
Done

2016-09-26 07:41 UTC, jszczepkowski commented on cluster/gce/util.sh
> +      --target-tags "${MASTER_NAME}" &
Done

2016-09-26 07:42 UTC, jszczepkowski commented on cluster/gce/util.sh
> +  # Create rule for accessing and securing etcd servers.
Done

2016-09-26 07:56 UTC, jszczepkowski commented on cluster/gce/util.sh
> +      --allow "tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp" &
I agree, but I'm not sure how to implement it. Firewall rules on GCE allow only to allow certain tags. So, we can allow nodes as they have NODE_TAG, but we cannot allow everything but MASTER_TAG.

2016-09-26 07:56 UTC, jszczepkowski commented on cluster/gce/util.sh
> +      --allow "tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp" &
I agree, but I'm not sure how to implement it. Firewall rules on GCE allow only to allow certain tags. So, we can allow nodes as they have NODE_TAG, but we cannot allow everything but MASTER_TAG.

2016-09-29 09:35 UTC, jszczepkowski commented
@k8s-bot gci gce e2e test this
issue: #33725

2016-09-29 15:12 UTC, fgrzadkowski commented on cluster/gce/util.sh
> +      --allow "tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp" &
I guess you'd have to have two separate rules:
* for master node something which explicitly lists ports that we want to expose
* for minion nodes something that will open all ports

Would it work?

2016-09-30 12:38 UTC, jszczepkowski commented on cluster/gce/util.sh
> +      --allow "tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp" &
There is a slight semantic different: before we were allowing all the nodes, now only minions and masters.

However, this sounds reasonable. Done

2016-10-03 09:38 UTC, fgrzadkowski requested changes

2016-10-03 09:38 UTC, fgrzadkowski commented on cluster/gce/util.sh
> +      --allow "tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp" \
As explained in my previous email I think we should only expose specific ports. At the very least please leave a TODO to check which ports are actually needed on master.

2016-10-03 09:38 UTC, fgrzadkowski commented on cluster/gce/util.sh
> +      --allow "tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp" \
Also I think it'd be useful to explain in a comment why do you exclude those two ports.

2016-10-03 09:38 UTC, fgrzadkowski commented
LGTM. One minor change. Please make sure this doesn't break e2e tests.

2016-10-03 10:17 UTC, merged

2016-10-03 19:34 UTC, ixdy commented
This PR basically blew up all of our PR testing. The `-internal` firewall was never cleaned up (I'm not sure why), and now we have `-internal`, `internal-ssh`, and `-internal-node` rules, which are completely eating up all of our quota.

It also seems like the `-master-etcd` rule isn't being cleaned up for some reason, and I'm still trying to figure out why.

cc @kubernetes/test-infra-maintainers

2016-10-03 19:36 UTC, ixdy commented on cluster/gce/util.sh
> +    if ! gcloud compute firewall-rules --project "${PROJECT}" describe "${MASTER_NAME}-etcd" &>/dev/null; then
oh, this should not have the `!` in front.

2016-10-03 19:42 UTC, ixdy commented on cluster/gce/util.sh
> +    if ! gcloud compute firewall-rules --project "${PROJECT}" describe "${MASTER_NAME}-etcd" &>/dev/null; then
#33963