Clarify MinAvailable approval semantics.
kubernetes/kubernetes pull request #33148
Opened 2016-09-21 01:46 UTC by mml

Fixes doc comments to be in line with #33143

2016-09-21 04:52 UTC, davidopp commented on pkg/apis/policy/types.go
> +	// This minimum is applicable at all times.  Specifically, when the
This is getting kinda verbose. How about replacing the whole comment with

```
An eviction is allowed if at least "minAvailable" pods selected by "selector" will
still be available after the eviction, i.e. even in the absence of the evicted pod.
So for example you can prevent all voluntary evictions by specifying "100%".
```

2016-09-21 04:53 UTC, davidopp requested changes

2016-09-21 17:09 UTC, mml commented
@davidopp PTAL

2016-09-25 19:50 UTC, davidopp commented
LGTM

2016-10-07 22:45 UTC, mml commented
@k8s-bot verify test this #IGNORE

2016-10-10 21:53 UTC, mml commented
@k8s-bot gke e2e test this #34483

2016-10-11 03:32 UTC, merged