[WIP] refact kubectl Factory make it interface
kubernetes/kubernetes pull request #33180
Opened 2016-09-21 15:34 UTC by AdoHe

refactor kubectl to make Factory interface. @kubernetes/kubectl

2016-09-21 15:46 UTC, deads2k commented
@fabianofranz This ripples downstream.

2016-09-21 15:47 UTC, deads2k commented
I'm in favor of the change, but wow that's big :)

2016-09-21 19:52 UTC, MHBauer commented
related to #31702 ?

2016-09-21 19:54 UTC, deads2k commented
> related to #31702 ?

Looks like it.

2016-09-21 22:05 UTC, smarterclayton commented
Please split the `*cmdutil.Factory` change in each command into its own commit - that will make this much easier to review.

2016-09-22 00:31 UTC, AdoHe commented
yes, sure, I will split this into separate commits.

2016-09-22 00:37 UTC, AdoHe commented
@fabianofranz As we have discussed on email, we will propose a new SIG for kubectl, which gives us a place to discuss the CLI architecture, like this one. So here I want to make sure this is the correct way. I will get this merged asap. @pwittrock ptal.

2016-09-23 09:54 UTC, soltysh commented on pkg/kubectl/cmd/cmd_test.go
> +	tf    *testFactory
Would it make sense to have a general fakeFactory for tests, that will have all the methods implemented, with empty bodies, of course. Then in commands you'd be embedding it and just providing an implementation to whichever method you need. This should simplify testing, imho.

2016-09-23 10:12 UTC, AdoHe commented on pkg/kubectl/cmd/cmd_test.go
> +	tf    *testFactory
@soltysh a general fakeFactory with all methods implemented with empty bodies? what if several commands want to use a same implementation of some methods?

2016-09-23 10:22 UTC, soltysh commented on pkg/kubectl/cmd/cmd_test.go
> +	tf    *testFactory
That shouldn't be a problem for several commands re-using those.

2016-09-25 16:17 UTC, k82cn commented on pkg/kubectl/cmd/cmd_test.go
> +func (f *fakeFactory) PrinterForMapping(cmd *cobra.Command, mapping *meta.RESTMapping, withNamespace bool) (kubectl.ResourcePrinter, error) {
Should we return `t.tf.Printer` ?

2016-09-25 16:23 UTC, k82cn commented on pkg/kubectl/cmd/cmd_test.go
> +	return nil
The `DrainOptions.SetupDrain` in `cmd/drain.go` will use `NewBuidler` of factory, and the default implementation of `NewFactory` will take `Factory::Object`'s return value as parameters. That's what I mean in slack.

But we're luck, it seems `DrainOptions.SetupDrain` is not used by anyone :).

2016-09-25 16:23 UTC, k82cn requested changes

2016-09-25 23:31 UTC, AdoHe commented on pkg/kubectl/cmd/cmd_test.go
> +	return nil
we still need to be careful about this.

2016-09-26 12:17 UTC, deads2k commented on pkg/kubectl/cmd/cmd_test.go
> +func (f *fakeFactory) PrinterForMapping(cmd *cobra.Command, mapping *meta.RESTMapping, withNamespace bool) (kubectl.ResourcePrinter, error) {
> Should we return t.tf.Printer

I think we should keep this pull targeted.  Switch them all to methods on the `Factory` interface and then change signatures later.  This pull is already massive.

2016-09-26 12:20 UTC, deads2k commented on pkg/kubectl/cmd/util/factory.go
> +	Flags() *pflag.FlagSet
This used to be private, right?  Can we keep it private?

2016-09-26 12:20 UTC, deads2k commented on pkg/kubectl/cmd/util/factory.go
> +	Command() string
Why have these been added?

2016-09-26 12:21 UTC, deads2k commented on pkg/kubectl/cmd/util/factory.go
> +	BindFlags(flags *pflag.FlagSet)
If these weren't exposed before, lets keep them hidden.  I don't think we want to encourage access patterns like this.

2016-09-26 12:22 UTC, deads2k commented on pkg/kubectl/cmd/util/factory.go
> +	PrintObject(cmd *cobra.Command, mapper meta.RESTMapper, obj runtime.Object, out io.Writer) error
please remove/hide.  We don't want to the factory accepting the command.  We want specific structs passing the information we need and all of these look be net-new

2016-09-26 12:26 UTC, deads2k commented
Mind squashing into 
 1. update factory.
 1. create test factory
 1. mechanical command updates? - looks like these were mostly just removing the `*`.

I'd like to see the interface slimmed down a little bit.  If that turns out to require rippling changes, just make follow-up issues.  This is a nice improvement over where we are now.

2016-09-26 12:27 UTC, deads2k commented
After squash and green, I'd merge this as-is and we can iterate.

I bumped the priority, once its green, we want this to beat any other `kubectl` changes.

2016-09-28 15:24 UTC, AdoHe commented
```
3. mechanical command updates? - looks like these were mostly just removing the *.
```
yes, so I would like to merge these into one commit, and one commit one command would leave so many commits tests failed.

2016-10-06 15:29 UTC, AdoHe commented
I just go back to this issue, will fix it tomorrow.

2016-10-07 12:38 UTC, deads2k commented
Build issues.  If you think you've got a shot at finishing it up today, ask for a hold on https://github.com/kubernetes/kubernetes/pull/34199 and untag.

2016-10-07 13:46 UTC, AdoHe commented
the build failed because I just update the `Factory` struct in this commit, will send other commits to update various commands.

2016-10-08 13:03 UTC, AdoHe commented on pkg/kubectl/cmd/util/factory.go
> +	Command() string
@deads2k originally `Factory` struct has these methods, and they are exported, so other packages can use. If we make `Factory` interface, and not add these methods to the interface definition, other packages which use this interface can not use theses methods anymore.

2016-10-08 13:24 UTC, AdoHe commented on pkg/kubectl/cmd/util/factory.go
> +	BindFlags(flags *pflag.FlagSet)
@deads2k actually these are methods of `Factory` struct before, and they are exported. The problem is why we add these methods as struct methods, and others as struct fields.

2016-10-13 00:25 UTC, AdoHe commented
@deads2k @fabianofranz @pwittrock I just rebased and fixed the failed tests, please take a look, and give your feedback, I would hope we can get this merged asap. This is just a beginning of `Factory` refactor, eventually we will make `Factory` a collection of interfaces, and finally we will implement something we discussed in #31173 #7311

2016-10-13 09:35 UTC, kargakis commented on pkg/kubectl/cmd/annotate.go
> -	// Common shared fields
shared is correct here

2016-10-13 09:36 UTC, kargakis commented on pkg/kubectl/cmd/drain.go
> +				fmt.Println("get error here")
remove this?

2016-10-13 09:37 UTC, kargakis commented on pkg/kubectl/cmd/util/factory.go
> +	NewBuilder() *resource.Builder
Nice

2016-10-13 12:50 UTC, AdoHe commented on pkg/kubectl/cmd/drain.go
> +				fmt.Println("get error here")
some stupid error, :(

2016-10-13 13:03 UTC, AdoHe commented
@deads2k @fabianofranz @pwittrock @kargakis rebased and update, ptal.

2016-10-13 13:22 UTC, deads2k commented
> @deads2k @fabianofranz @pwittrock @kargakis rebased and update, ptal.

I don't see an obvious, "this doesn't work", so I'm tagging this as-is.  This breaks the back of the problem and I'd like to merge it and take everything else as a follow-up unless someone finds a "this breaks `kubectl`" kind of bug.

2016-10-13 13:32 UTC, kargakis commented
Agreed.

On Thu, Oct 13, 2016 at 3:22 PM, David Eads <notifications@github.com>
wrote:

> @deads2k <https://github.com/deads2k> @fabianofranz
> <https://github.com/fabianofranz> @pwittrock
> <https://github.com/pwittrock> @kargakis <https://github.com/kargakis>
> rebased and update, ptal.
>
> I don't see an obvious, "this doesn't work", so I'm tagging this as-is.
> This breaks the back of the problem and I'd like to merge it and take
> everything else as a follow-up unless someone finds a "this breaks kubectl"
> kind of bug.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/33180#issuecomment-253511265>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADuFf5hZTN1ioeKIpO6xKH8LZn1jWTHYks5qzjCigaJpZM4KC8-K>
> .
>

2016-10-13 14:28 UTC, AdoHe commented
wow~ so glad to see this thanks @deads2k @kargakis @fabianofranz @pwittrock

2016-10-13 14:44 UTC, merged