Fix goroutine leak in federation service controller
kubernetes/kubernetes pull request #33359
Opened 2016-09-23 07:24 UTC by shashidharatd

**What this PR does / why we need it**: Fixes a memory leak

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #33186

**Special notes for your reviewer**: Every second new goroutines are created and are getting blocked waiting for the lock in the event queue. only one worker will get a lock when there are some events to process, so all the goroutines which are created every second waits for the lock forever and causes the memory/goroutine leak.

As a fix the new worker will be created only when there is no worker exist. and only one worker per cluster either waits for the event or processes all the events and goes out of existence.

**Release note**:

```release-note
```

2016-09-23 07:37 UTC, shashidharatd commented
I signed it!

2016-09-23 08:01 UTC, madhusudancs commented on federation/pkg/federation-controller/service/endpoint_helper.go
> +		workerExist, keyFound := sc.endpointWorkerMap[clusterName]
Change `keyFound` to `found`.

2016-09-23 08:02 UTC, madhusudancs commented on federation/pkg/federation-controller/service/endpoint_helper.go
> +		sc.endpointWorkerMap[clusterName] = true
Set this after starting the goroutine, just to be safe.

2016-09-23 08:04 UTC, madhusudancs commented on federation/pkg/federation-controller/service/service_helper.go
> +	for eventPending {
Same comment as above.

2016-09-23 08:04 UTC, madhusudancs commented on federation/pkg/federation-controller/service/service_helper.go
> +		workerExist, keyFound := sc.serviceWorkerMap[clusterName]
Same as above. Change to `found`.

2016-09-23 08:18 UTC, madhusudancs commented on federation/pkg/federation-controller/service/endpoint_helper.go
> -				func() {
This function is important here.

Notice the defer statement inside this block. This `func()` exists for that sole reason. At the end of each loop, we need to say we are done for that key, so we `defer cache.endpointQueue.Done(key)`. If you remove the `func() {}` wrapping, defer will be run at the end of the enclosing goroutine and the keys won't be removed from the queue until then. So I don't think you should be removing the `func() {}` wrapping.

2016-09-23 08:18 UTC, madhusudancs commented on federation/pkg/federation-controller/service/service_helper.go
> -				}()
Same comment as above.

2016-09-23 08:20 UTC, madhusudancs commented on federation/pkg/federation-controller/service/servicecontroller.go
> +	maxNoOfClusters = 256
We have informally talked about this before but we have never established this formally. We plan to support 100 clusters initially. 256 seems too high to start with.

2016-09-23 08:20 UTC, madhusudancs requested changes
This PR drives home the urgency to move the federated service controller to the new `FederatedInformer` architecture.

2016-09-23 08:42 UTC, shashidharatd commented on federation/pkg/federation-controller/service/endpoint_helper.go
> +	eventPending := true
the break statement in default case will only break the select loop, and the goroutine will get stuck in for loop forever, so we need this variable to come out of for loop

2016-09-23 08:43 UTC, shashidharatd commented on federation/pkg/federation-controller/service/endpoint_helper.go
> -				func() {
agreed, missed that, will change

2016-09-23 08:45 UTC, shashidharatd commented on federation/pkg/federation-controller/service/servicecontroller.go
> +	maxNoOfClusters = 256
sure will change that to 100

2016-09-23 08:49 UTC, madhusudancs commented on federation/pkg/federation-controller/service/endpoint_helper.go
> +	eventPending := true
Oops, you are right. This isn't a common idiom which is why it threw me off the guard. 

What you have is fine, but if you want to stay with a commonly used idiom, please see https://golang.org/ref/spec#Break_statements.

2016-09-23 09:46 UTC, shashidharatd commented
@madhusudancs handled the review comments in the second commit, plz check

2016-09-23 19:20 UTC, madhusudancs commented
@k8s-bot federation gce e2e test this

2016-09-24 05:10 UTC, madhusudancs commented
@k8s-bot federation gce e2e test this

2016-09-24 06:53 UTC, madhusudancs commented
Federation tests that are failing are known failures. These changes seem to not have caused any regressions, so LGTM'ing the PR.

@shashidharatd thanks for these changes!

2016-09-24 06:56 UTC, madhusudancs commented
1.4.0 train has already left, so this must be cherry-picked to v1.4.1+.

2016-09-24 08:30 UTC, merged

2016-09-24 15:44 UTC, shashidharatd commented
Thanks @madhusudancs

2016-09-24 17:02 UTC, quinton-hoole commented
Added cherrypick-candidate label.  As @madhusudancs mentions above, this can wait for v1.4.1.  Not sure what labelling/milestone convention we're using to represent that.

2016-10-06 00:46 UTC, jessfraz commented
@shashidharatd can you open the PR to cherry-pick this into the release-1.4 branch

2016-10-06 03:36 UTC, madhusudancs commented
@jessfraz are we not doing automated cherry-picks any more?