kubelet: eviction: allow minreclaim as percentage
kubernetes/kubernetes pull request #33392
Opened 2016-09-23 21:17 UTC by sjenning

Fixes #33354 

xref #32537

@derekwaynecarr @vishh @mtaufen

2016-09-26 19:58 UTC, derekwaynecarr commented on pkg/kubelet/eviction/helpers_test.go
> +			thresholds:       specifiecThresholds,
typo: specificThresholds

2016-09-26 20:02 UTC, derekwaynecarr requested changes
A few things
1. the kubelet -h text needs updating
2. this should have a release-note
3. it would be good if you can update kubelet-eviction.md design doc
4. we will need a doc follow-on.

2016-09-27 02:09 UTC, sjenning commented
@derekwaynecarr I pushed the typo fix and updated the PR description with a release note.

From a documentation perspective (-h, design doc, kube docs) I don't think anything needs to be updated.  The soft and hard thresholds don't call out explicitly that they support absolute values and percentages either.

If anything the docs should have said that ```--eviction-minimum-reclaim``` didn't support percentages before.  With this PR, they are all uniform, accepting both percentages and absolute values.

2016-09-30 15:50 UTC, derekwaynecarr commented
@sjenning - squash then lgtm, @ronnielai fyi

2016-09-30 16:13 UTC, sjenning commented
@derekwaynecarr rebased and squashed

2016-09-30 16:49 UTC, sjenning commented
flaked https://github.com/kubernetes/kubernetes/issues/33838

2016-09-30 17:57 UTC, derekwaynecarr commented
@k8s-bot unit test this

2016-09-30 17:57 UTC, derekwaynecarr commented
@k8s-bot gke e2e test this

2016-09-30 17:58 UTC, derekwaynecarr approved these changes

2016-10-03 17:53 UTC, mtaufen commented
I think this is the fix for the `TestNamespaceController` unit test flake: #33866

2016-10-06 14:27 UTC, sjenning commented
@k8s-bot unit test this

2016-10-06 16:25 UTC, merged

2016-10-06 17:00 UTC, mtaufen commented
Yay!