Move Kubelet pod-management code into kubelet_pods.go
kubernetes/kubernetes pull request #33432
Opened 2016-09-24 13:16 UTC by pmorie

Finish the kubelet code moves started during the 1.3 dev cycle -- move pod management code into a file called `kubelet_pods.go`.

2016-09-26 14:03 UTC, pmorie commented
@k8s-bot gke e2e test this

2016-09-26 19:46 UTC, derekwaynecarr commented on pkg/kubelet/kubelet.go
> +Copyright 2016 The Kubernetes Authors.
why does this change?

2016-09-26 19:47 UTC, derekwaynecarr commented on pkg/kubelet/kubelet.go
> -var masterServices = sets.NewString("kubernetes")
need to work down why this moved....

2016-09-26 19:48 UTC, derekwaynecarr commented on pkg/kubelet/kubelet.go
> -var masterServices = sets.NewString("kubernetes")
ignore above, now i see...

2016-09-26 19:49 UTC, derekwaynecarr requested changes
just the one nit/question.

i do not look forward to rebases.

2016-09-26 19:50 UTC, pmorie commented on pkg/kubelet/kubelet.go
> +Copyright 2016 The Kubernetes Authors.
Why shouldn't it?

2016-09-26 21:17 UTC, pmorie commented
@derekwaynecarr nit addressed

2016-09-27 04:14 UTC, pmorie commented on pkg/kubelet/kubelet.go
> -var masterServices = sets.NewString("kubernetes")
Consider it ignored

2016-09-27 13:10 UTC, pmorie commented
@k8s-bot kubemark gci e2e test this

2016-09-27 14:56 UTC, derekwaynecarr approved these changes

2016-09-27 15:59 UTC, merged