Store RequestInfo in Context instead of RequestInfoResolver dependency injection
kubernetes/kubernetes pull request #33490
Opened 2016-09-26 15:27 UTC by sttts

The `RequestInfoResolver` is used in the proxy handler and in the authorization code. It is passed through half of the apiserver code base to be available at those locations. This PR used the context, which is our natural dependency injection mechanism in the handlers.

2016-09-26 20:10 UTC, liggitt commented on pkg/apiserver/filters/authorization_test.go
>  	for k, tc := range testcases {
reset attribs and err at the beginning of each loop

2016-09-26 20:22 UTC, liggitt requested changes
I only looked at the last two commits

2016-09-27 08:16 UTC, sttts commented on pkg/apiserver/filters/requestinfo.go
> +		if err == nil {
fixed

2016-09-27 08:16 UTC, sttts commented on pkg/apiserver/filters/requestinfo.go
> +			forbidden(w, req)
fixed

2016-09-27 08:18 UTC, sttts commented on pkg/apiserver/proxy.go
> -	if err != nil || !requestInfo.IsResourceRequest {
good spot. fixed.

2016-09-27 08:23 UTC, sttts commented on pkg/apiserver/request/requestinfo.go
> +const requestInfoKey requestInfoKeyType = iota
It's what the go context package suggests: https://github.com/golang/net/blob/master/context/context.go#L100

2016-09-27 08:30 UTC, sttts commented on pkg/apiserver/request/requestinfo.go
> +const requestInfoKey requestInfoKeyType = iota
That's why I was asking on irc yesterday about moving `Context` out of `pkg/api`. But keys are interfaces and interfaces are equal if the type and the value are equal. So this private type idea actually works.

Will add a comment.

2016-09-27 16:11 UTC, sttts commented
@k8s-bot unit test this

2016-09-27 16:28 UTC, sttts commented
@k8s-bot test this issue: #IGNORE

2016-09-28 08:17 UTC, sttts commented on pkg/apiserver/filters/authorization_test.go
>  	for k, tc := range testcases {
fixed

2016-09-28 08:17 UTC, sttts commented
@liggitt addressed your comments and squashed. ptal.

2016-09-28 09:02 UTC, sttts commented
@k8s-bot gke e2e test this issue: #28721

2016-09-28 14:12 UTC, liggitt requested changes

2016-09-28 14:12 UTC, liggitt commented on pkg/genericapiserver/config.go
> +		GrouplessAPIPrefixes: sets.NewString(strings.Trim(c.APIPrefix, "/")),                                      // APIPrefixes that won't have groups (legacy)
make sure c.APIPrefix and c.APIGroupPrefix are not empty strings before including them in the sets. When we eventually start up a generic API server that is only serving grouped APIs, I *think* I would expect `APIPrefix` to be empty

2016-09-28 14:16 UTC, sttts commented on pkg/apiserver/proxy.go
> +		internalError(w, req, errors.New("Error getting request context"))
No context means it's not wired correctly.

2016-09-28 14:19 UTC, sttts commented on pkg/genericapiserver/config.go
> +		GrouplessAPIPrefixes: sets.NewString(strings.Trim(c.APIPrefix, "/")),                                      // APIPrefixes that won't have groups (legacy)
Certainly true. But it's only moved code here. I have added a note to https://github.com/kubernetes/kubernetes/issues/32792 for a follow-up.

2016-09-28 14:20 UTC, sttts commented on pkg/apiserver/filters/requestinfo.go
> +			internalError(w, req, fmt.Errorf("failed to create RequestInfo: %v", err))
good spot.

2016-09-28 14:21 UTC, liggitt commented on pkg/apiserver/proxy.go
> +		internalError(w, req, errors.New("Error getting request context"))
right, so don't we need to set `httpCode = http.StatusInternalServerError`?

2016-09-28 14:53 UTC, sttts commented on pkg/apiserver/filters/requestinfo.go
> +			internalError(w, req, fmt.Errorf("failed to create RequestInfo: %v", err))
fixed

2016-09-28 14:55 UTC, sttts commented on pkg/apiserver/proxy.go
> +		internalError(w, req, errors.New("Error getting request context"))
sure. fixed.

2016-09-28 14:59 UTC, sttts commented on pkg/apiserver/filters/requestinfo.go
> +			internalError(w, req, fmt.Errorf("failed to create RequestInfo: %v", err))
fixed

2016-09-28 14:59 UTC, sttts commented
@liggitt addressed your comments.

2016-09-28 15:32 UTC, liggitt approved these changes

2016-09-28 15:32 UTC, liggitt commented
LGTM, squash in fix commit

2016-09-28 16:51 UTC, sttts commented
Rebased.

2016-09-28 23:09 UTC, merged