Allow building experimenta etcd images
kubernetes/kubernetes pull request #33556
Opened 2016-09-27 13:30 UTC by wojtek-t

Ref #20504

Once this PR is in, I would like to build and push: "etcd:3.0.10-experimental" image to:
- start testing it
- to make it possible to build a different "3.0.10" image in the future (we will most probably built in some loging into it.

@lavalamp - FYI

2016-09-27 20:38 UTC, timothysc commented
lgtm.

2016-09-27 21:18 UTC, lavalamp requested changes
Please fix.

2016-09-27 21:18 UTC, lavalamp commented on cluster/images/etcd/Makefile
> +REGISTRY_TAG?=3.0.4
It should default to TAG. Otherwise someone setting TAG from the command line is going to blow away a 3.0.4 container.

2016-09-28 05:48 UTC, wojtek-t commented on cluster/images/etcd/Makefile
> +REGISTRY_TAG?=3.0.4
Good point. Done.

2016-09-28 05:48 UTC, wojtek-t commented
I fixed the comment. Reapplying lgtm label.

2016-09-28 10:39 UTC, merged