clean up the tmp Cert data
kubernetes/kubernetes pull request #33566
Opened 2016-09-27 14:40 UTC by guangxuli

2016-09-27 14:52 UTC, justinsb commented on pkg/kubectl/cmd/config/config_test.go
> +	defer os.RemoveAll(fakeCertFile.Name())
I believe os.RemoveAll removes a directory, so os.Remove is the more normal choice.  But it turns out os.RemoveAll calls os.Remove first anyway, so ...

2016-09-27 14:54 UTC, justinsb requested changes
Suggest using os.Remove - unless there's a reason to use os.RemoveAll?

2016-09-27 15:13 UTC, guangxuli commented
@justinsb thanks, yes, I made a mistake, I use the wrong function. I have modified the code.

2016-09-27 15:52 UTC, justinsb approved these changes
Thanks for fixing!

2016-09-27 15:53 UTC, justinsb commented
@k8s-bot ok to test

2016-09-27 18:46 UTC, foxish commented
@janetkuo Looks the jenkins bot didn't start one of the required tests and the bot continued to try and trigger it in every cycle (10 mins or so.). 
@fejta, is this a case that the mungegithub bot should take care of?

2016-09-27 21:00 UTC, janetkuo commented
@k8s-bot gke e2e test this #33361

2016-09-28 00:45 UTC, justinsb commented
@k8s-bot gke e2e test this

2016-09-28 08:46 UTC, merged