Enable kubernetes_metadata by default for ELK stack
kubernetes/kubernetes pull request #33584
Opened 2016-09-27 17:04 UTC by kayrus

Looks like it was accidentally removed and was not restored back in this PR https://github.com/kubernetes/kubernetes/pull/29883
Because actually this plugin still exists in the image, but new ELK deployment don't allow you to index namespaces, pod names, etc.

2016-09-28 15:51 UTC, piosz commented
ok to test

2016-09-28 15:56 UTC, piosz commented
I don't think it was remove by accident. Take a look to https://github.com/kubernetes/kubernetes/pull/26652#issuecomment-236713747

@aledbf could you please provide more context?
@Crassirostris do you understand the change?

2016-09-28 16:10 UTC, aledbf commented
> could you please provide more context?

The `kubernetes_metadata` plugin was commented because the pod starts without the service account and token mounted which avoid the normal initialization of the fluentd process.

https://github.com/kubernetes/kubernetes/pull/26652#issuecomment-236713747

2016-09-28 16:17 UTC, Crassirostris commented
Yes, sure, the fact that this plugin is needed is out of question.

But just turning it on doesn't seem like a good idea, since it was turned off not without a reason.

Maybe we should provide this filter plugin with explicit path to cert?

2016-09-28 16:25 UTC, Crassirostris commented
My point is, let's solve this problem

@aledbf Do you have any idea right now as for how to fix the problem, mentioned in #26652 ?

2016-09-28 17:39 UTC, Crassirostris commented
Well, if this pr passes gce suite for elasticsearch logging, sounds reasonable

2016-09-28 18:12 UTC, kayrus commented
@aledbf yep, actually I created my own daemonset for fluentd, and it works fine. didn't know the issue related to pure pod.

2016-09-29 09:28 UTC, piosz commented
In tests the old image is used. Let's wait for #32088 to be merged. I'll prioritize it on my list.

2016-12-06 20:57 UTC, keglevich3 commented
@piosz Do you mind If we will add a comment in the td-agent.conf to "enable" the metadata-plugin in a case of daemon-set usage?.

2016-12-06 21:03 UTC, Crassirostris commented
@keglevich3 Yes, absolutely, go ahead, we will be grateful!

2016-12-09 13:34 UTC, piosz commented
Sorry for the delay. I'm pretty close to merge #32088 (hopefully will be done within next few days) and then we can disable move forward with this one.

2017-01-11 09:00 UTC, piosz commented
We are now ready to merge it since fluentd was migrated to DS. @kayrus could you please rebase?

2017-01-11 09:09 UTC, kayrus commented
@piosz done.
JFYI: I already implemented full EFK stack in my private repo: https://github.com/kayrus/elk-kubernetes

2017-01-11 12:38 UTC, Crassirostris commented
@kayrus LGTM, thanks for your efforts!

Just a small thing: could you please bump an image version? I will push it and then you can create another PR using the new image.

2017-01-11 12:39 UTC, crassirostris requested changes
Please bump fluentd image version

2017-01-11 13:08 UTC, kayrus commented
@Crassirostris done

2017-01-11 13:23 UTC, crassirostris approved these changes
LGTM

2017-01-11 14:22 UTC, Crassirostris commented
@k8s-bot unit test this

2017-01-11 20:19 UTC, merged