Cherrypick: Update cAdvisor godeps for v1.4.1
kubernetes/kubernetes pull request #33806
Opened 2016-09-30 01:05 UTC by timstclair

Fixes 2 issues:

- https://github.com/kubernetes/kubernetes/issues/32917
- https://github.com/kubernetes/kubernetes/issues/30069

Includes commits:

1. Moved google.golang.org/cloud/compute/metadata to cloud.google.com/go/compute/metadata - https://github.com/google/cadvisor/commit/159f002f9a9bfd3af56070f435a7f4287ff6b24b
2. Look at all cgroup mounts -https://github.com/google/cadvisor/commit/ac9388cf76723ef432e655a7f3ac6d67a926f64f
3. Update runc libcontainer dependency - https://github.com/google/cadvisor/commit/1e013abde8892d3ecc8b6aac6650af7ccf78c321

/cc @eparis @derekwaynecarr @pwittrock

2016-09-30 02:06 UTC, timstclair commented
Hmm, something's not right here. Will reassign once it's fixed.

2016-09-30 02:09 UTC, dchen1107 commented
Are we sure we want to cherrypick this to 1.4 branch?

2016-09-30 17:18 UTC, timstclair commented
These were both fixes that were at some point targeted for v1.4, but we decided to hold for v1.4.1

2016-09-30 17:56 UTC, derekwaynecarr requested changes
we need to pass true in container manager.

2016-09-30 17:56 UTC, derekwaynecarr commented on pkg/kubelet/cm/helpers_linux.go
> -	allCgroups, err := libcontainercgroups.GetCgroupMounts()
i think for containerized kubelet, we will also need this value to be true.

2016-09-30 18:00 UTC, timstclair commented on pkg/kubelet/cm/helpers_linux.go
> -	allCgroups, err := libcontainercgroups.GetCgroupMounts()
Done. Can you think of any possible adverse affects of this that I should test for?

2016-09-30 18:11 UTC, derekwaynecarr commented on pkg/kubelet/cm/helpers_linux.go
> -	allCgroups, err := libcontainercgroups.GetCgroupMounts()
no.  basically, the reason we needed to pass true in cadvisor is the same reason we need to pass true in kubelet.  we need to ensure we have the right mount points (from the host) and not local to the container.  this code is not really activated until kube 1.5 with the pod level cgroup work i am doing.

2016-09-30 18:12 UTC, derekwaynecarr approved these changes

2016-09-30 18:12 UTC, derekwaynecarr commented
LGTM

2016-09-30 18:15 UTC, timstclair commented
@dchen1107 Can you approve the cherry-pick request, or should I reassign to Phil?

2016-10-04 18:47 UTC, jessfraz commented
@k8s-bot verify test this

2016-10-04 18:47 UTC, jessfraz commented
@k8s-bot kubemark e2e test this

2016-10-04 18:58 UTC, jessfraz commented
@timstclair is this only adding the 3 commits you mentioned to cadvisor or is it adding more? an 1,000 line diff into a point release is a little scary

2016-10-04 19:16 UTC, jessfraz commented
ah I think the test failure is real

2016-10-04 23:32 UTC, timstclair commented
> is this only adding the 3 commits you mentioned to cadvisor or is it adding more? an 1,000 line diff into a point release is a little scary

To clarify, those are the three commits from the cAdvisor godeps update, but we're transitively updating runc & gcloud deps. There are actually quite a few (124) commits in the runc update, so that is understandably concerning.

The total delta of runc is:
```
17 files changed, 124 insertions(+), 151 deletions(-)
```

We should probably switch to tracking a tagged runc version in the next release, otherwise we're going to run into this problem everytime a serious bug is found with runc.

The rest of the changes are in the new `cloud.google.com/go/...` dependency, which replaces `google.golang.org/cloud/...`. The diffs are small, but non-zero:
```
$ for f in $(find vendor/cloud.google.com/go/ -type f -name "*.go" | sed 's|vendor/cloud.google.com/go/||'); do echo -n "$f:  "; diff vendor/google.golang.org/cloud/$f vendor/cloud.google.com/go/$f | diffstat -s; done
compute/metadata/metadata.go:   1 file changed, 74 insertions(+), 18 deletions(-)
internal/cloud.go:   1 file changed, 5 insertions(+), 69 deletions(-)
```

> I think the test failure is real

When I rerun the test locally I get the opposite error:
```
hack/verify-godeps.sh 
Checking for 'Godeps/' changes against 'origin/master'
Starting to download all kubernetes godeps. This takes a while
# cd /tmp/gopath.1AXUwC/src/google.golang.org/cloud; git checkout eb47ba841d53d93506cfbfbc03927daf9cc48f88
godep: error restoring dep (google.golang.org/cloud/compute/metadata): chdir /tmp/gopath.1AXUwC/src/google.golang.org/cloud: no such file or directory
# cd /tmp/gopath.1AXUwC/src/google.golang.org/cloud; git checkout eb47ba841d53d93506cfbfbc03927daf9cc48f88
godep: error restoring dep (google.golang.org/cloud/internal): chdir /tmp/gopath.1AXUwC/src/google.golang.org/cloud: no such file or directory
godep: Error restoring some deps. Aborting check.
```

This error is what the cherrypick is working on fixing so I'll keep investigating

2016-10-04 23:33 UTC, timstclair commented
In summary, I recognize the concerns, but I'm also not sure what the alternative is aside from cherrypicking directly into our vendored libs.

2016-10-04 23:39 UTC, jessfraz commented
thanks for clarifying!

2016-10-05 00:09 UTC, timstclair commented
@k8s-bot verify test this

2016-10-05 00:45 UTC, timstclair commented
That latest verify failure makes more sense. It's the issue (https://github.com/kubernetes/kubernetes/issues/30069) this PR is partially fixing (the other half of the fix is in https://github.com/kubernetes/kubernetes/pull/32592)

2016-10-05 02:09 UTC, timstclair commented
I can open a new PR which cherry-picks only the specific commits needed, based on the discussion in https://groups.google.com/d/topic/kubernetes-dev/GCvf664vVTg/discussion

What do we want to do about the cloud deps though? I suppose if we're not going to be using godep it doesn't matter that `google.golang.org/cloud` no longer exists.

2016-10-05 02:30 UTC, jessfraz commented
I think thats ok :) and thanks so much, sorry this PR became a rabbit hole

On Tue, Oct 4, 2016 at 7:10 PM, Tim St. Clair <notifications@github.com>
wrote:

> I can open a new PR which cherry-picks only the specific commits needed,
> based on the discussion in https://groups.google.com/d/
> topic/kubernetes-dev/GCvf664vVTg/discussion
>
> What do we want to do about the cloud deps though? I suppose if we're not
> going to be using godep it doesn't matter that google.golang.org/cloud no
> longer exists.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/33806#issuecomment-251564361>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABYNbJ9KKrAdd7YWWOMRNag7gpthIRooks5qwwcAgaJpZM4KKof3>
> .
>

2016-10-05 17:47 UTC, timstclair commented
> I think thats ok

Sorry, which part were you referring to?

2016-10-05 18:20 UTC, jessfraz commented
Both parts sgtm!

2016-10-07 21:25 UTC, jessfraz commented
@timothysc what would be easiest is to ignore the google cloud stuff and have cadvisor cut a tag with just the patches we need, then update godep to use that

2016-10-07 21:33 UTC, timothysc commented
s/timothysc/timstclair

2016-10-07 21:35 UTC, jessfraz commented
ah so sorry!

2016-10-07 21:57 UTC, timstclair commented
We can ignore the google cloud deps. We still need to decide what to do about runc though. Don't hold v1.4.1 for this, if it slips to 1.4.2 it's not a big deal.

2016-10-07 22:06 UTC, jessfraz commented
I bet if we ask nicely they might make us a custom tag as well :)

On Fri, Oct 7, 2016 at 2:58 PM, Tim St. Clair <notifications@github.com>
wrote:

> We can ignore the google cloud deps. We still need to decide what to do
> about runc though. Don't hold v1.4.1 for this, if it slips to 1.4.2 it's
> not a big deal.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/33806#issuecomment-252371038>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABYNbJP8_yyV0P5_uQW6KPYd3ci0vZqtks5qxsCGgaJpZM4KKof3>
> .
>

2016-10-28 18:59 UTC, jessfraz commented
can we pull the google cloud dep changes in here as well so the verification passes

2016-10-28 19:23 UTC, timstclair commented
Do you mean https://github.com/kubernetes/kubernetes/pull/32592 ?

2016-10-28 19:23 UTC, jessfraz commented
yes :)

2016-10-28 20:17 UTC, timstclair commented
Done, but the cherrypick wasn't clean. I manually ignored the conflicting cAdvisor updates.

/cc @dims

2016-10-28 20:18 UTC, jessfraz commented
thanks!

2016-10-28 20:55 UTC, jessfraz commented
oh I know the problem w verify-godeps, i can fix it but ill wait for the other tests to pass and merge this one by hand when they are green

2016-10-28 21:19 UTC, merged

2016-10-28 21:24 UTC, timstclair commented
Thanks!

2016-10-31 11:40 UTC, soltysh commented on vendor/github.com/google/cadvisor/metrics/prometheus.go
> +			}, {
How this got in, it's not part of the linked cadvisor version, @derekwaynecarr @smarterclayton?