refactor controller as posthook when configured and enabled
kubernetes/kubernetes pull request #33841
Opened 2016-09-30 16:18 UTC by deads2k

builds on https://github.com/kubernetes/kubernetes/pull/33785 .

Models the bootstrap controller as a PostHook which is added when its API group is available and its configured.

@liggitt Stefan is out for a while.

2016-10-05 19:37 UTC, deads2k commented
@liggitt @ncdc its big, but all the prereqs have gone in.  Using a `poststarthook` to start this should help us re-use `master.go` downstream.

2016-10-05 19:38 UTC, ncdc commented
I'll take a look tonight or tomorrow morning.

2016-10-06 15:23 UTC, ncdc requested changes
Mostly LGTM. Just a couple of minor issues.

2016-10-07 12:18 UTC, deads2k commented
comments addressed.

2016-10-07 13:15 UTC, ncdc commented on pkg/master/controller.go
> +// NewBootstrapController returns a controller for watching the core capabilities of the maste
missing r at eol

2016-10-10 13:54 UTC, merged