stop plumbing options to start
kubernetes/kubernetes pull request #33846
Opened 2016-09-30 17:16 UTC by deads2k

The API server should have sufficient information to start itself without relying on an `options` object from a different packages focused on CLI interaction.  This provides that separation

@liggitt distinct from other changes

2016-10-03 12:21 UTC, deads2k commented
@k8s-bot kubemark e2e test this

2016-10-03 12:21 UTC, deads2k commented
@k8s-bot gci gke e2e test this

2016-10-03 15:13 UTC, liggitt requested changes

2016-10-03 15:13 UTC, liggitt commented on pkg/genericapiserver/genericapiserver.go
> +		alternateDNS := []string{"kubernetes.default.svc", "kubernetes.default", "kubernetes", "localhost"}
move inside the block where the cert is created... not needed otherwise

2016-10-03 15:13 UTC, liggitt commented on pkg/genericapiserver/genericapiserver.go
> +		if !certutil.CanReadCertOrKey(s.SecureServingInfo.ServerCert.CertFile, s.SecureServingInfo.ServerCert.KeyFile) {
this changes the behavior to generate a self-signed cert if you typo the cert/key filename in the args... previously we only did that if they were unspecified

2016-10-03 15:13 UTC, liggitt commented on pkg/genericapiserver/config.go
> +		if options.TLSCertFile == "" && options.TLSPrivateKeyFile == "" {
this is the point at which we know whether we should generate a self-signed one or not

2016-10-03 17:35 UTC, deads2k commented
Fixed.

2016-10-03 18:23 UTC, deads2k commented
@k8s-bot  test this: issue #33880

2016-10-03 18:36 UTC, deads2k commented
@k8s-bot test this: issue #33880

2016-10-03 22:11 UTC, deads2k commented
@k8s-bot gce e2e test this

2016-10-04 12:13 UTC, deads2k commented
@k8s-bot test this: issue #33880

2016-10-04 14:28 UTC, liggitt approved these changes

2016-10-04 14:29 UTC, liggitt commented
LGTM

2016-10-04 15:46 UTC, merged