CRI: Implement temporary ImageStats in kuberuntime_manager, and
kubernetes/kubernetes pull request #33870
Opened 2016-10-01 00:16 UTC by Random-Liu

For #33048 and #33189.

This PR:
1) Implement a temporary `ImageStats` in kuberuntime_manager.go
2) Add container name label on infra container to make the current summary api logic work with dockershim.

@yujuhong @feiskyer

2016-10-01 03:29 UTC, Random-Liu commented
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/33784.

2016-10-03 19:35 UTC, yujuhong requested changes

2016-10-03 19:35 UTC, yujuhong commented on pkg/kubelet/dockershim/docker_sandbox.go
> +	labels[types.KubernetesContainerNameLabel] = dockertools.PodInfraContainerName
Don't refer `dockertools.PodInfraContainerName` directly in all the files. It'd be a hassle to change all of them.
Suggestion:
1. In `naming.go`, set `sandboxContainerName`  to `leaky.PodInfraContainerName`, and add comments there.
2. Use only `sandboxContainerName` in the rest of the files in the docekrshim package.

2016-10-03 19:35 UTC, yujuhong commented on pkg/kubelet/dockershim/docker_sandbox.go
> +	delete(labels, types.KubernetesContainerNameLabel)
Move this to `extractLabels`, where similar logic resides.

2016-10-03 19:35 UTC, yujuhong commented on pkg/kubelet/kuberuntime/kuberuntime_image.go
> +// TODO: Get imagefs stats directly from CRI.
ImageStats lgtm.

2016-10-03 19:35 UTC, yujuhong commented on pkg/kubelet/dockershim/convert.go
> +	delete(labels, types.KubernetesContainerNameLabel)
Move this to `extractLabels`, where the similar logic lives.

2016-10-03 20:14 UTC, Random-Liu commented on pkg/kubelet/dockershim/docker_sandbox.go
> +	delete(labels, types.KubernetesContainerNameLabel)
The only problem is that, we should only delete the label for pod sandbox.
If we want to move this inside `extractLabels`, we may need to add some special logic to and and remove labels for sandbox, or add a separate `makeSandboxLabels` and `extractSandboxLabels`.

2016-10-03 20:21 UTC, Random-Liu commented on pkg/kubelet/dockershim/docker_sandbox.go
> +	labels[types.KubernetesContainerNameLabel] = dockertools.PodInfraContainerName
ACK

2016-10-03 20:39 UTC, Random-Liu commented
@yujuhong Addressed comments.

2016-10-03 21:02 UTC, yujuhong approved these changes

2016-10-03 22:29 UTC, Random-Liu commented
@k8s-bot gci gce e2e test this
@k8s-bot gke e2e test this

2016-10-03 23:17 UTC, Random-Liu commented
@k8s-bot gci gce e2e test this

2016-10-04 06:55 UTC, Random-Liu commented
Just rebased, apply LGTM again.

2016-10-04 11:54 UTC, feiskyer commented
LGTM

2016-10-04 15:21 UTC, yujuhong commented
@k8s-bot unit test this.

2016-10-04 17:13 UTC, yujuhong commented
@k8s-bot node e2e test this

2016-10-04 21:15 UTC, merged