Switch kubectl to use watch.Until
kubernetes/kubernetes pull request #33942
Opened 2016-10-03 15:20 UTC by kargakis

Squashed version of https://github.com/kubernetes/kubernetes/pull/30235 - no additions to it

@ncdc PTAL

cc: @kubernetes/kubectl

2016-10-03 15:24 UTC, ncdc requested changes

2016-10-03 15:24 UTC, ncdc commented on pkg/kubectl/cmd/get.go
> +		intr.Run(func() error {
Do you want to add a 2nd commit to return the result of this call instead of nil, as you suggested in the previous PR?

2016-10-03 15:24 UTC, ncdc commented on pkg/kubectl/cmd/rollout/rollout_status.go
> +	intr.Run(func() error {
Same question here

2016-10-03 15:38 UTC, kargakis commented
Sure, will do here

On Mon, Oct 3, 2016 at 5:24 PM, Andy Goldstein <notifications@github.com>
wrote:

> *@ncdc* requested changes on this pull request.
> ------------------------------
>
> In pkg/kubectl/cmd/get.go
> <https://github.com/kubernetes/kubernetes/pull/33942#pullrequestreview-2543283>
> :
>
> > @@ -266,17 +267,22 @@ func RunGet(f *cmdutil.Factory, out io.Writer, errOut io.Writer, cmd *cobra.Comm
>
>  		first := true
>  		filteredResourceCount = 0
> -		kubectl.WatchLoop(w, func(e watch.Event) error {
> -			if !isList && first {
> -				// drop the initial watch event in the single resource case
> -				first = false
> -				return nil
> -			}
> -			err := printer.PrintObj(e.Object, out)
> -			if err == nil {
> +		intr := interrupt.New(nil, w.Stop)
> +		intr.Run(func() error {
>
> Do you want to add a 2nd commit to return the result of this call instead
> of nil, as you suggested in the previous PR?
> ------------------------------
>
> In pkg/kubectl/cmd/rollout/rollout_status.go
> <https://github.com/kubernetes/kubernetes/pull/33942#pullrequestreview-2543283>
> :
>
> > @@ -125,18 +126,22 @@ func RunStatus(f *cmdutil.Factory, cmd *cobra.Command, out io.Writer, args []str
>  	}
>
>  	// if the rollout isn't done yet, keep watching deployment status
> -	kubectl.WatchLoop(w, func(e watch.Event) error {
> -		// print deployment's status
> -		status, done, err := statusViewer.Status(cmdNamespace, info.Name)
> -		if err != nil {
> -			return err
> -		}
> -		fmt.Fprintf(out, "%s", status)
> -		// Quit waiting if the rollout is done
> -		if done {
> -			w.Stop()
> -		}
> -		return nil
> +	intr := interrupt.New(nil, w.Stop)
> +	intr.Run(func() error {
>
> Same question here
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/33942#pullrequestreview-2543283>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADuFf0gqJywC4ykMtZ4axsq8MBM5hS_Sks5qwR4vgaJpZM4KMszi>
> .
>

2016-10-03 15:52 UTC, ncdc approved these changes

2016-10-03 16:12 UTC, ncdc commented
```
=== RUN   TestWatchSelector
error: timed out waiting for the condition
```

@kargakis I don't see any flakes for this... maybe it was introduced by this PR?

2016-10-03 17:00 UTC, kargakis commented
> @kargakis I don't see any flakes for this... maybe it was introduced by this PR?

Yes, this is real. It was happening because of checkErr being hardcoded in cmd.Run for `get`. 

I restored the behavior of `kubectl get` - I don't think people will need to check exit codes when watching with `-w`.  We can re-iterate once somebody asks for it.

2016-10-05 11:31 UTC, kargakis commented
@ncdc ping

2016-10-05 13:21 UTC, ncdc commented
Giving it a final look now, sorry for the delay.

2016-10-05 14:20 UTC, kargakis commented
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/kubectl/cmd/get.go, line 271 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33942#-KTA7N-aJh7rfKGsn0sn-r1-271:-KTKC3rgTzg_pjFRZbtU:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/5ad518cd2b180db8be9c0f4be341b896b6778101/pkg/kubectl/cmd/get.go#L271)):*
<details><summary><i>Previously, ncdc (Andy Goldstein) wrote…</i></summary>
> Do you want to add a 2nd commit to return the result of this call instead of nil, as you suggested in the previous PR?
</details>
Done.

---

*[pkg/kubectl/cmd/rollout/rollout_status.go, line 130 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33942#-KTA7N-aJh7rfKGsn0so-r1-130:-KTKC57h6jehrK27sNfH:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/5ad518cd2b180db8be9c0f4be341b896b6778101/pkg/kubectl/cmd/rollout/rollout_status.go#L130)):*
<details><summary><i>Previously, ncdc (Andy Goldstein) wrote…</i></summary>
> Same question here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33942)*
<!-- Sent from Reviewable.io -->

2016-10-05 14:21 UTC, kargakis commented
@ncdc not sure what else Reviewable needs from me:)

2016-10-05 14:24 UTC, ncdc commented
@kargakis nothing; it doesn't block merging.

2016-10-05 15:29 UTC, merged

2017-03-09 19:49 UTC, kargakis commented
@sttts @janetkuo @kubernetes/sig-cli-bugs we may want to revert this

2017-03-09 19:50 UTC, ncdc commented
@kargakis why?

2017-03-09 19:53 UTC, kargakis commented
@ncdc we have had problems recently in e2e tests that turned out to be related to watch.Until and I've also had issues related to `rollout status` timing out (it should never time out)
https://github.com/kubernetes/kubernetes/pull/41112
https://github.com/kubernetes/kubernetes/issues/40224
https://github.com/kubernetes/kubernetes/issues/41336

2017-03-09 19:54 UTC, ncdc commented
I don't imagine this is going to be a clean revert and it would likely have to be done by hand instead. Can we fix the problem instead of just reverting?

2017-03-09 19:56 UTC, kargakis commented
Not sure about it and personally I don't have the bandwidth. Even reverting is going to be manual and requires some work, otherwise I would have done it already.

2017-03-09 19:56 UTC, ncdc commented
As @smarterclayton wrote in https://github.com/kubernetes/kubernetes/issues/31345#issuecomment-244958711:

> We should be renewing the watch. However that's not enough - you really need Get then Watch. So there has to be something that abstracts watcher creation (a watch wrapper).

That doesn't sound all that bad to write?

2017-03-09 20:03 UTC, smarterclayton commented
Logically a lot of "gets" are hard to model (you'd need to do preconditions
on UID, like if someone deleted the pod and then recreated)

On Thu, Mar 9, 2017 at 2:57 PM, Andy Goldstein <notifications@github.com>
wrote:

> As @smarterclayton <https://github.com/smarterclayton> wrote in #31345
> (comment)
> <https://github.com/kubernetes/kubernetes/issues/31345#issuecomment-244958711>
> :
>
> We should be renewing the watch. However that's not enough - you really
> need Get then Watch. So there has to be something that abstracts watcher
> creation (a watch wrapper).
>
> That doesn't sound all that bad to write?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/33942#issuecomment-285462983>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p9Oz1243g0yo3zrw4ftWgGkaMB6Iks5rkFmPgaJpZM4KMszi>
> .
>

2017-03-10 16:58 UTC, ymqytw commented
> you really need Get then Watch. So there has to be something that abstracts watcher creation (a watch wrapper).

> Logically a lot of "gets" are hard to model (you'd need to do preconditions
on UID, like if someone deleted the pod and then recreated)

I can help fix this issue. But how and why the wrapper can fix this is not clear to me.
Why Get then Watch will fix this issue? Do we stop watching when the UID has changed?

2017-05-29 09:04 UTC, mfojtik commented
@mengqiy I think the watch is closed after certain number of events is passed (1000?). In that case we need to to get the resource using the last known resource version and re-open the watch with the current resource version.

@kargakis is this already fixed or we need to plumb it in the helper?

2017-06-02 15:16 UTC, kargakis commented
@mfojtik no, `rollout status` still uses watch.Until which is broken.