Add global timeout flag
kubernetes/kubernetes pull request #33958
Opened 2016-10-03 19:16 UTC by juanvallejo

**Release note**:
```release-note
release-note-none
```

This patch adds a global timeout flag (viewable with `oc options`) with
a default value of `0s` (meaning no timeout). It renames all local
`timeout` flags previously declared in specific commands, such as
`kubectl delete` and `kubectl scale`, to avoid conflict with the new
global timeout flag.

No new functionality is added to enforce a timeout. The timeout value is
added to the default http client, so that zero values and default behavior
is enforced by the http client.

Adding a global timeout ensures that user-made scripts won't hang for an
indefinite amount of time while performing remote calls (right now, remote
calls are re-tried up to 10 times when each attempt fails, however, there is
no option to set a timeout in order to prevent any of these 10 attempts from
hanging indefinitely).

**Example**
```
$ kubectl get pods # no timeout flag set - default to 0s (which means no
timeout)
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-1-h7etw   1/1       Running   1          2h
router-1-uv0f9            1/1       Running   1          2h

$ kubectl get pods --timeout=0 # zero means no timeout no timeout flag set
NAME                      READY     STATUS    RESTARTS   AGE
docker-registry-1-h7etw   1/1       Running   1          2h
router-1-uv0f9            1/1       Running   1          2h

$kubectl get pods --timeout=1ms
Unable to connect to the server: net/http: request canceled while
waiting for connection (Client.Timeout exceeded while awaiting headers)
```

2016-10-03 19:18 UTC, deads2k commented on pkg/kubectl/cmd/rollingupdate.go
> -	cmd.Flags().Duration("timeout", timeout, `Max time to wait for a replication controller to update before giving up. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".`)
You cannot change these flag names without breaking existing scripts.

2016-10-03 19:40 UTC, juanvallejo commented on pkg/kubectl/cmd/rollingupdate.go
> -	cmd.Flags().Duration("timeout", timeout, `Max time to wait for a replication controller to update before giving up. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".`)
reverted local flag names back to `timeout`. Updated global flag to `--request-timeout` https://github.com/kubernetes/kubernetes/pull/33958/commits/396551ba76ea7b3c13d875b09c955f2c6762671f

2016-10-05 15:44 UTC, kargakis commented
cc: @kubernetes/kubectl

2016-10-05 18:26 UTC, juanvallejo commented
@deads2k or @fabianofranz could you take a look please?

2016-10-05 19:34 UTC, deads2k commented on pkg/client/unversioned/clientcmd/overrides.go
> +	FlagTimeout      = "request-timeout"
@kubernetes/kubectl Any comments on the flag name?  `--timeout` was already take by commands that use reapers for a different meaning.

2016-10-05 19:35 UTC, deads2k commented
Squash and lgtm.

I'll leave it open a day for comments on the flag name.

2016-10-05 19:35 UTC, deads2k commented
Oh, and test-cmd test.  A `kubectl get -w --request-timeout` ought to return, right?

2016-10-05 19:53 UTC, juanvallejo commented
@deads2k 
> A kubectl get -w --request-timeout ought to return, right?

Yes, when using the default `0` value, it behaves as usual (watches a resource until a user terminates the process).

When used with a non-zero `request-timeout` value, it does timeout after the time specified:
```
$ oc get pod zookeeper-1 -w --request-timeout=10s
NAME          READY     STATUS    RESTARTS   AGE
zookeeper-1   1/1       Running   2          6h

```

After `10s`, the complete output from the command above is:
```
NAME          READY     STATUS    RESTARTS   AGE
zookeeper-1   1/1       Running   2          6h
E1005 15:50:25.125415   11319 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```

2016-10-05 20:11 UTC, deads2k commented
> Yes, when using the default 0 value, it behaves as usual (watches a resource until a user terminates the process).

Right, just pointed that out for your test-cmd.sh test.

2016-10-06 00:11 UTC, AdoHe commented on pkg/client/unversioned/clientcmd/overrides.go
> +	FlagTimeout      = "request-timeout"
`request-timeout` sounds good to me.

2016-10-06 00:11 UTC, AdoHe commented
@juanvallejo any priority between local timeout flag and global flag?

2016-10-06 09:20 UTC, soltysh commented
> @juanvallejo any priority between local timeout flag and global flag?

I guess, since `request-timeout` is applied at transport layer it'll have priority over local timeout, which is usually applied to a bigger chunk of operation (ie. for reapers it's applied while waiting for scale down operation).

The changes LGTM, but since this is a new feature, release not is needed @juanvallejo,

2016-10-06 14:13 UTC, juanvallejo commented
Thanks for the feedback, release note added!

2016-10-06 16:34 UTC, soltysh commented
If there are no objections I'm gonna tag it for merge later today.

2016-10-06 19:30 UTC, soltysh commented
@k8s-bot ok to test

2016-10-06 19:48 UTC, soltysh commented
Flake #32430

@k8s-bot node e2e test this

2016-10-06 20:16 UTC, fabianofranz requested changes

2016-10-06 20:16 UTC, fabianofranz commented on pkg/client/unversioned/clientcmd/overrides.go
> +func (f FlagInfo) BindDurationFlag(flags *pflag.FlagSet, target *time.Duration) {
I still believe `--request-timeout` should support values without units, which defaults to seconds like every other timeout flag out there. Like in `ssh`, `timeout`, `scp`, `curl`, and so on. 

You'd probably have to use string and parse it by yourself like in [here](https://play.golang.org/p/LgfIAgEvDC).

2016-10-06 20:17 UTC, fabianofranz commented on pkg/client/unversioned/clientcmd/overrides.go
> +func (f FlagInfo) BindDurationFlag(flags *pflag.FlagSet, target *time.Duration) {
Like `--request-timeout=30` is the first thing I'll try.

2016-10-06 21:51 UTC, juanvallejo commented on pkg/client/unversioned/clientcmd/overrides.go
> +func (f FlagInfo) BindDurationFlag(flags *pflag.FlagSet, target *time.Duration) {
Done! Thanks for providing the example

2016-10-07 00:23 UTC, fabianofranz commented
LGTM

2016-10-07 12:40 UTC, soltysh commented
@juanvallejo can you look into those test failures and link to flakes?

2016-10-07 22:18 UTC, soltysh requested changes
@juanvallejo can you link the actual client-go PR here, as well

2016-10-07 22:18 UTC, soltysh commented on staging/src/k8s.io/client-go/1.5/rest/config.go
> +
What about actually setting this field like you do in the core k8s code? I'd expect this patch looks identical to the other `config.go` file.

2016-10-07 22:25 UTC, juanvallejo commented on staging/src/k8s.io/client-go/1.5/rest/config.go
> +
Definitely, will do right now

2016-10-07 22:27 UTC, juanvallejo commented
Linking bump of `k8s.io/client-go/1.5/rest/config.go`: https://github.com/kubernetes/client-go/pull/10

2016-10-10 12:35 UTC, deads2k commented
@juanvallejo `test-cmd` doesn't often flake.  Try it locally.

2016-10-10 20:28 UTC, juanvallejo commented
@soltysh Finally getting tests to pass, however I'm not sure if the `GKE smoke e2e` is a flake or not

> What about actually setting this field like you do in the core k8s code? I'd expect this patch looks identical to the other config.go file.

I went ahead and added the rest of the changes from the core k8s code to the v1.5 config patchhttps://github.com/kubernetes/kubernetes/pull/33958/commits/2e0865356b524d62a787c48721a04ca8a485b91b

2016-10-10 20:52 UTC, juanvallejo commented
gke e2e test flaked on https://github.com/kubernetes/kubernetes/issues/33388

2016-10-11 21:33 UTC, juanvallejo commented
tests flaking on https://github.com/kubernetes/kubernetes/issues/32428

2016-10-12 10:24 UTC, soltysh commented
@k8s-bot test this issue #32428

2016-10-12 10:25 UTC, soltysh approved these changes

2016-10-13 14:46 UTC, juanvallejo commented
@soltysh or @deads2k PTAL

2016-10-13 23:26 UTC, AdoHe commented
LGTM.

2016-10-14 11:45 UTC, deads2k commented
@caesarxuchao is the "bump(k8s.io/client-go): add Timeout field to 1.5 restclient" commit well formed?  I haven't looked at how staging is supposed to be populated.

2016-10-14 11:49 UTC, deads2k commented
squash your non-bump commits, get confirmation you've done the right thing for staging, and this lgtm.

2016-10-14 20:13 UTC, caesarxuchao commented
@juanvallejo did you manually copy the exact changes in the first commit to the staging area? If so, I'm fine with doing it manually this time. (sorry for the trouble we are causing by the restructuring of client-go)

Also, could keep the commits separate for this PR? Just in case we need to revert the changes to the staging area.

2016-10-14 21:24 UTC, juanvallejo commented
@caesarxuchao 
>  did you manually copy the exact changes in the first commit to the staging area?

Yes, this was done manually. I'll keep both commits separate. Thanks!

2016-10-15 05:25 UTC, caesarxuchao commented
LGTM. Thanks!

2016-10-15 06:29 UTC, merged