[WIP] update deployment controller and lister
kubernetes/kubernetes pull request #34024
Opened 2016-10-04 17:13 UTC by deads2k

Updates the deployment lister to avoid copies and updates the deployment controller to use shared informers.

Pushing WIP to see which tests are broken.

2016-10-04 17:55 UTC, deads2k commented
@derekwaynecarr This got unexpectedly large.  Let's start with this and I'll do the informer in another step.

2016-10-05 12:04 UTC, deads2k commented
@ncdc you got review bandwidth?  We will be using these downstream eventually (backing a DC by an RS is needed to help a migration) and this is also groundwork for fixing up more duplicate listwatches.

2016-10-05 12:21 UTC, ncdc commented
Yes, in an hour or so

On Wednesday, October 5, 2016, David Eads <notifications@github.com> wrote:

> @ncdc <https://github.com/ncdc> you got review bandwidth? We will be
> using these downstream eventually (backing a DC by an RS is needed to help
> a migration) and this is also groundwork for fixing up more duplicate
> listwatches.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/34024#issuecomment-251655556>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAABYhqMGGTulMf1H_u63oluIFgPOo8Wks5qw5KGgaJpZM4KN7fZ>
> .
>

2016-10-05 14:39 UTC, ncdc requested changes

2016-10-05 14:39 UTC, ncdc commented on pkg/client/cache/listers_extensions.go
> +// StoreToDeploymentLister gives a store List and Exists methods. The store must contain only Deployments.
You didn't migrate Exists. Change comment to only mention List?

2016-10-05 14:39 UTC, ncdc commented on pkg/client/cache/listers_extensions.go
> +
There is some godoc for this type here if you want it: https://github.com/kubernetes/kubernetes/pull/34024/commits/25f42a23721dec67af3492eba087170bd1993bb8#diff-53f28720440ab4b589ef2273346cecfcL197

2016-10-05 14:39 UTC, ncdc commented on pkg/client/cache/listers_extensions.go
> +		err = fmt.Errorf("no deployments found for Deployment %v because it has no labels", pod.Name)
The original error was "no deployments found for Pod" - change it back?

2016-10-05 14:39 UTC, ncdc commented on pkg/client/cache/listers_extensions.go
> +		err = fmt.Errorf("could not find deployments set for Deployment %s in namespace %s with labels: %v", pod.Name, pod.Namespace, pod.Labels)
Deployment -> Pod

2016-10-05 14:39 UTC, ncdc commented on pkg/controller/deployment/deployment_controller.go
> +	rsLister cache.StoreToReplicaSetLister
I assume the rs changes in this commit should really be in the rs commit, but I'm not going to make you change them 😄

2016-10-05 14:39 UTC, ncdc commented on pkg/controller/informers/extensions.go
> +// Deployment is type of SharedIndexInformer which watches and lists all pods.
is a type

2016-10-05 14:39 UTC, ncdc commented on pkg/controller/informers/extensions.go
> +// Interface provides constructor for informer and lister for pods
Did you intend to write "Interface" here, as in "the interface", or did you mean "Deployment"?

2016-10-05 14:39 UTC, ncdc commented on pkg/controller/informers/extensions.go
> +	Informer() cache.SharedIndexInformer
Godoc?

2016-10-05 15:01 UTC, kargakis commented
cc: @mfojtik 

Ref: https://github.com/kubernetes/kubernetes/issues/31780

2016-10-05 15:10 UTC, ncdc requested changes

2016-10-05 15:10 UTC, ncdc commented on pkg/controller/informers/extensions.go
>  // Deployment is type of SharedIndexInformer which watches and lists all pods.
Deployment->DeploymentInformer

2016-10-05 17:24 UTC, deads2k commented on pkg/client/cache/listers_extensions.go
> +// StoreToDeploymentLister gives a store List and Exists methods. The store must contain only Deployments.
> You didn't migrate Exists. Change comment to only mention List?

Looks I caught it later.

2016-10-05 17:24 UTC, deads2k commented on pkg/client/cache/listers_extensions.go
> +
> There is some godoc for this type here if you want it: 25f42a2#diff-53f28720440ab4b589ef2273346cecfcL197

I don't think it adds much, do you?  It's boilerplate on all of these.

2016-10-05 17:25 UTC, deads2k commented on pkg/client/cache/listers_extensions.go
> +		err = fmt.Errorf("no deployments found for Deployment %v because it has no labels", pod.Name)
> The original error was "no deployments found for Pod" - change it back?

done

2016-10-05 17:25 UTC, deads2k commented on pkg/client/cache/listers_extensions.go
> +		err = fmt.Errorf("could not find deployments set for Deployment %s in namespace %s with labels: %v", pod.Name, pod.Namespace, pod.Labels)
> Deployment -> Pod

done

2016-10-05 17:26 UTC, deads2k commented on pkg/controller/informers/extensions.go
> +	Informer() cache.SharedIndexInformer
> Godoc?

boilerplate

2016-10-05 17:29 UTC, ncdc commented on pkg/client/cache/listers_extensions.go
> +// StoreToDeploymentLister gives a store List and Exists methods. The store must contain only Deployments.
Yup

2016-10-05 17:29 UTC, ncdc commented on pkg/controller/informers/extensions.go
> +	Informer() cache.SharedIndexInformer
Fine to omit

2016-10-05 17:31 UTC, deads2k commented
comments addressed.

2016-10-05 18:28 UTC, deads2k commented
@ncdc did you make it through?

2016-10-05 18:34 UTC, ncdc commented
@deads2k I did. It looks like there are 2 small outstanding typos.

2016-10-05 19:20 UTC, deads2k commented
> @deads2k I did. It looks like there are 2 small outstanding typos.

Got them.

2016-10-05 19:20 UTC, ncdc approved these changes

2016-10-06 07:02 UTC, merged