add --dry-run flag to `oc apply`
kubernetes/kubernetes pull request #34028
Opened 2016-10-04 17:31 UTC by juanvallejo

**Release note**:
```release-note
release-note-none
```

Related StackOverflow:
http://stackoverflow.com/questions/38824409/validate-openshift-objects-defined-in-yaml-before-actually-applying-or-executing

This patch adds a `--dry-run` flag to the `apply` command in order to
allow validation of objects, without actually creating them. If a
`--dry-run` flag is present and no validation errors are found, the
command will exit before sending objects to the server.

@ncdc @fabianofranz

2016-10-04 17:36 UTC, ncdc commented
I'd recommend that you read through the history of #11488 to see if this meshes with the suggestions there.

2016-10-04 17:44 UTC, juanvallejo commented
@ncdc 
> I'd recommend that you read through the history of #11488 to see if this meshes with the suggestions there.

Thanks! It partially addresses some comments from that thread where `--validate=true --dry-run` is wanted

2016-10-06 08:32 UTC, soltysh commented
cc @kubernetes/kubectl

2016-10-06 08:36 UTC, AdoHe commented
I will comment more when I back to office.

2016-10-06 08:48 UTC, soltysh commented
The change itself looks good, but my expectations from using `--dry-run` are that the command works  almost identical to regular (non-dry-runned) in the output. This means you should create a visitor and call `PrintSuccess` with `dryRun` flag set to `true`. Expected output:
```
$ kubectl apply -f --dry-run pod.yaml
pod "nginx" created (dry run)
```
vs
```
$ kubectl apply -f pod.yaml
pod "nginx" created
```

Additionally, since you're at it can you also add this to `kubectl create` it looks quite similar.

2016-10-06 14:36 UTC, juanvallejo commented
@soltysh 
> The change itself looks good, but my expectations from using --dry-run are that the command works almost identical to regular (non-dry-runned) in the output. This means you should create a visitor and call PrintSuccess with dryRun flag set to true

Sounds good, will do

> Additionally, since you're at it can you also add this to kubectl create it looks quite similar.

Definitely, [currently working on this downstream](https://github.com/openshift/origin/pull/11238), I'll open it upstream once I have a bit more progress on it

2016-10-06 15:15 UTC, AdoHe commented
since we have `dry-run` on several commands, I am considering whether we should add a normal proposal for this.

2016-10-11 20:44 UTC, juanvallejo commented
@soltysh or @AdoHe PTAL. Went ahead and updated `apply`'s `--dry-run` option to behave like other `--dry-run` options and added it to `kubectl complete as well`

2016-10-11 23:51 UTC, AdoHe commented on pkg/kubectl/cmd/apply.go
> +	cmd.Flags().Bool("dry-run", false, "If true, only print validation for objects that would be created.")
since we will add this flag in multiple commands, please create a helper method like `AddDryRunFlag` in `cmdutil`

2016-10-11 23:54 UTC, AdoHe commented on pkg/kubectl/cmd/apply.go
> +			cmdutil.PrintSuccess(mapper, shortOutput, out, info.Mapping.Resource, info.Name, dryRun, "created")
what's output of this? The resource is not actually created.

2016-10-11 23:54 UTC, AdoHe commented on pkg/kubectl/cmd/apply.go
> +		cmdutil.PrintSuccess(mapper, shortOutput, out, info.Mapping.Resource, info.Name, dryRun, "configured")
the same.

2016-10-12 10:19 UTC, soltysh requested changes
Generally looks good, one nit from @AdoHe I'd like to see addressed before letting this in.

2016-10-12 10:19 UTC, soltysh commented on pkg/kubectl/cmd/apply.go
> +	cmd.Flags().Bool("dry-run", false, "If true, only print validation for objects that would be created.")
:+1:

2016-10-12 10:19 UTC, soltysh commented on pkg/kubectl/cmd/apply.go
> +			cmdutil.PrintSuccess(mapper, shortOutput, out, info.Mapping.Resource, info.Name, dryRun, "created")
The use of this function is my suggestion. Generally, you'll get a similar output to running that command without `--dry-run` flag, iow. it'll print you `resource X created` w/wo `(dry run)` at the end.

2016-10-12 18:22 UTC, juanvallejo commented
@AdoHe @soltysh Thanks for the review! Turns out there was already a helper function for adding a DryRun flag. Went ahead and updated this PR to use it.

2016-10-12 20:28 UTC, soltysh commented
LGTM, can you please squash your changes and I'll tag it for merge.

2016-10-12 20:28 UTC, soltysh approved these changes

2016-10-13 20:56 UTC, juanvallejo commented
@soltysh 
> can you please squash your changes and I'll tag it for merge.

Done!

2016-10-15 10:25 UTC, soltysh commented
@k8s-bot ok to test

2016-10-15 12:30 UTC, merged

2016-11-22 22:49 UTC, ymqytw commented
@juanvallejo It seems that `kubectl create` won't respect flag `--output` when using `--dry-run`.
```
$ kubectl create -f ../pod.yaml --dry-run -o yaml
pod "test-pod" created (dry run)
```
Can you open an issue or a followup PR for it?

2016-11-22 23:05 UTC, ymqytw commented
@juanvallejo `kubectl apply` doesn't work well.
```
$ kubectl apply -f ../pod.yaml --dry-run -o yaml
error: Unexpected -o output mode: yaml. We only support '-o name'.
```

I think we should make `create` and `apply` work similar as `kubectl create configmap --dry-run -o yaml`.

2016-11-23 18:03 UTC, juanvallejo commented
@ymqytw
> It seems that kubectl create won't respect flag --output when using --dry-run.

Thanks, I'll go ahead and open an issue and followup PR for this

> kubectl apply doesn't work well.

I'll update `kubectl apply` to support more than just `-o name` in the same PR

2016-11-23 18:07 UTC, ymqytw commented
@juanvallejo Thanks. Hopefully we can fix it before 1.5 get released.