Fix kubectl run --dry-run with -i or --attach
kubernetes/kubernetes pull request #34152
Opened 2016-10-05 23:19 UTC by ivan4th

Don't attempt to attach to the pod in dry run mode.
Fixes #30081

2016-10-11 13:52 UTC, ivan4th commented
ping...

2016-10-12 23:21 UTC, janetkuo commented
I'd suggest moving this part from `generateService` to `createGeneratedObject`:
```go
	if cmdutil.GetFlagString(cmd, "output") != "" || cmdutil.GetDryRunFlag(cmd) {
		return f.PrintObject(cmd, mapper, obj, out)
	}
	cmdutil.PrintSuccess(mapper, false, out, mapping.Resource, args[0], cmdutil.GetDryRunFlag(cmd), "created")
```
and then we no longer need this in `Run`. We can then just return on dry-run right after expose. Please also add a test for this `-i --dry-run` case (in hack/make-rules/test-cmd.sh for example).

If we can abstract the `attach` part to its own function that'd also be great (optional).

2016-10-13 18:59 UTC, ivan4th commented
@janetkuo made these changes. As of extracting `attach` part, I think something along the lines of `ExecOptions` in [exec.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/exec.go) needs to be done, i.e. extracting flags etc. into a struct to make the code cleaner. Multiple functions pulling cmd flags don't look good IMO. I can fix this in a followup PR.

2016-10-18 22:12 UTC, janetkuo requested changes

2016-10-18 22:12 UTC, janetkuo commented on pkg/kubectl/cmd/run.go
> +func createGeneratedObject(f cmdutil.Factory, cmd *cobra.Command, args []string, generator kubectl.Generator, names []kubectl.GeneratorParam, params map[string]interface{}, overrides, namespace strin
Just pass resource name (`string`) instead of passing `args []string`

2016-10-18 22:12 UTC, janetkuo commented on pkg/kubectl/cmd/run.go
> +		cmdutil.PrintSuccess(mapper, false, out, mapping.Resource, args[0], cmdutil.GetDryRunFlag(cmd), "created")
just use `dryRun`

2016-10-18 22:14 UTC, janetkuo commented
We print a redundant message now. Just need to remove the print message from the bottom of `Run`

```console
$ kubectl run nginx --image=nginx 
deployment "nginx" created
deployment "nginx" created
```

2016-10-18 22:55 UTC, ivan4th commented
Fixed. Also, I'll try to make it all prettier in a followup PR.

2016-10-18 23:21 UTC, ivan4th commented
#35064
@k8s-bot unit test this

2016-10-18 23:22 UTC, ivan4th commented
Will retry e2e a bit later

2016-10-21 11:14 UTC, ivan4th commented
@k8s-bot unit test this

2016-10-24 15:30 UTC, ivan4th commented
@k8s-bot gci gke e2e test this

2016-10-27 23:11 UTC, janetkuo approved these changes

2016-10-27 23:19 UTC, ivan4th commented
@k8s-bot gci gke e2e test this

2016-10-28 08:07 UTC, ivan4th commented
@k8s-bot node e2e test this

2016-10-29 12:19 UTC, ivan4th commented
@k8s-bot node e2e test this

2016-10-30 21:02 UTC, ivan4th commented
Failed to merge due to CI infra problems :( #35732 is merged now, it makes `kubectl run` fail with these flag combinations. I think that adding `--dry-run` ignoring `--attach` / `-i` is more intuitive, e.g. when I add `--dry-run -o yaml` to a long `kubectl run` command I typed before I expect it to display objects it generates without making me remove some of the other flags. Still, I expect such discussion to be difficult so I'm inclined to give up on this PR.

2016-11-16 01:21 UTC, janetkuo commented
> I'm inclined to give up on this PR.

Ah, agree. Since #35732 already fixed #30081, we can close this one.

2016-11-16 01:21 UTC, closed without merging