WIP: add RuntimeManagerService
kubernetes/kubernetes pull request #34276
Opened 2016-10-06 22:10 UTC by freehan

TL;DR: RuntimeManagerService provides an interface for kubelet to pass a set of configurations to runtime.

This PR adds RuntimeManagerService for runtime level operations. The use case is for kubelet to pass configs to runtime. Kubelet holds some config/information which runtime does not have, such as PodCIDR and HairpinMode. I expect some of kubelet configurations will gradually move to runtime, but I believe cases like PodCIDR, which can dynamically assigned by k8s master, need to stay for a while.

2016-10-07 15:54 UTC, yujuhong commented
/cc @kubernetes/sig-node @yifan-gu @euank @feiskyer @mrunalp

2016-10-07 16:02 UTC, yujuhong requested changes

2016-10-07 16:02 UTC, yujuhong commented on pkg/kubelet/api/services.go
> +	PushRuntimeConfig(config *runtimeApi.RuntimeConfig) error
Shouldn't this just be part of the `RuntimeService`?

2016-10-07 16:02 UTC, yujuhong commented on pkg/kubelet/api/v1alpha1/runtime/api.proto
> +    required ConfigKey key = 1;
The convention is to not use any `required` fields, which has been removed in proto3.

2016-10-07 16:02 UTC, yujuhong commented on pkg/kubelet/api/v1alpha1/runtime/api.proto
> +message RuntimeConfig {
Is this `NetworkConfig` or a more generic `RuntimeConfig`? i think `PushRuntimeConfig` should be a general purpose call that can be used to update a single config object (not restricted to network).

2016-10-07 16:02 UTC, yujuhong commented on pkg/kubelet/api/v1alpha1/runtime/api.proto
> +    // PUshRuntimeConfig pushes a RuntimeConfig to runtime.
nit: s/PUsh/Push

2016-10-07 21:22 UTC, mrunalp commented
:+1:

2016-10-08 00:17 UTC, feiskyer commented
@freehan Will the pushed configs be changed over time? If not, I suggest rename it to `InitRuntimeConfig` and pass those configs to runtime at initialization stage.

2016-10-10 17:00 UTC, freehan commented
@feiskyer 
PodCIDR is assigned by master after kubelet registers. It is not determined upon initialization. Hence need a way for kubelet to pass it down to runtime. I suspect there are other cases like this.

2016-10-11 01:41 UTC, feiskyer commented on pkg/kubelet/api/v1alpha1/runtime/api.proto
> +    optional string podCIDR = 1;
Please use CamelCase for field names and add doc comments for it, e.g. `pod_cidr`.

2016-10-11 01:41 UTC, feiskyer commented on pkg/kubelet/api/v1alpha1/runtime/api.proto
> +    optional NetworkConfig networkConfig = 1;
same here, `network_config`

2016-10-11 01:41 UTC, feiskyer commented on pkg/kubelet/api/v1alpha1/runtime/api.proto
> +    optional RuntimeConfig runtimeConfig = 1;
same here,`runtime_config`

2016-10-11 16:21 UTC, euank commented
cc @squeed

2016-10-11 20:32 UTC, freehan commented on pkg/kubelet/api/v1alpha1/runtime/api.proto
> +    optional string podCIDR = 1;
@squeed Currently, this is a one time update when podCIDR become available. 
Later if we support the concept of multiple networks, then we need to figure out if we want to pass that information at RunPodSandbox.

2016-10-11 22:23 UTC, freehan commented
@k8s-bot test this

2016-10-12 21:10 UTC, yujuhong approved these changes

2016-10-12 21:31 UTC, yujuhong commented
@freehan, `verify-flags-underscore.py` is failing
```
Verifying hack/make-rules/../../hack/verify-test-images.sh
[0;32mSUCCESS[0m  hack/make-rules/../../hack/verify-test-images.sh	0s
Verifying hack/make-rules/../../hack/verify-flags-underscore.py
Found illegal 'flag' usage. If these are false negatives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
pkg/kubelet/api/v1alpha1/runtime/api.pb.go:	PodCidr          *string `protobuf:"bytes,1,opt,name=pod_cidr,json=podCidr" json:"pod_cidr,omitempty"`
pkg/kubelet/api/v1alpha1/runtime/api.pb.go:	RuntimeConfig    *RuntimeConfig `protobuf:"bytes,1,opt,name=runtime_config,json=runtimeConfig" json:"runtime_config,omitempty"`
pkg/kubelet/api/v1alpha1/runtime/api.proto:    optional RuntimeConfig runtime_config = 1;
pkg/kubelet/api/v1alpha1/runtime/api.proto:    optional string pod_cidr = 1;
[0;31mFAILED[0m   hack/make-rules/../../hack/verify-flags-underscore.py	59s
Makefile:99: recipe for target 'verify' failed
```

2016-10-12 21:32 UTC, yujuhong commented
LGTM. 

@euank @yifan-gu, anymore question?

2016-10-12 22:46 UTC, euank commented
LGTM, though we probably could have also included the remote_runtime implementation in this PR without trouble. I assume that'll follow soon enough.

2016-10-13 16:57 UTC, freehan commented
Tests passed. Applying lgtm based on comments.

2016-10-14 06:10 UTC, merged