Node status updater should SetNodeStatusUpdateNeeded if it fails to
kubernetes/kubernetes pull request #34368
Opened 2016-10-07 23:41 UTC by jingxu97

update status

When volume controller tries to update the node status, if it fails to
update the nodes status, it should call SetNodeStatusUpdateNeeded so
that the volume list could be updated next time.

2016-10-12 22:02 UTC, jingxu97 commented
@k8s-bot gci gce e2e test this

@saad-ali PTAL

2016-10-19 03:29 UTC, saad-ali requested changes

2016-10-19 03:29 UTC, saad-ali commented on pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go
> +		//updateNode, _ := nsu.kubeClient.Core().Nodes().Get(string(nodeName))
Remove debug comment

2016-10-19 03:29 UTC, saad-ali commented on pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go
> +		node, err = nsu.kubeClient.Core().Nodes().PatchStatus(string(nodeName), patchBytes)
Is `node` used anywhere? If not, replace with `_`.

2016-10-24 20:54 UTC, jingxu97 commented on pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go
> +		node, err = nsu.kubeClient.Core().Nodes().PatchStatus(string(nodeName), patchBytes)
done

2016-10-24 21:00 UTC, jingxu97 commented on pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go
> +		//updateNode, _ := nsu.kubeClient.Core().Nodes().Get(string(nodeName))
done

2016-10-24 21:00 UTC, jingxu97 commented
@saad-ali PTAL

2016-10-25 00:13 UTC, saad-ali commented
LGTM

2016-10-25 00:14 UTC, saad-ali commented
Let's cherry pick this to v1.4

2016-10-26 17:02 UTC, jingxu97 commented
@saad-ali Could you please take a look of this PR? It shows reviewer request changes?

2016-10-26 17:43 UTC, saad-ali approved these changes

2016-10-26 18:09 UTC, merged

2016-10-26 21:13 UTC, jessfraz commented
cherrypicked in https://github.com/kubernetes/kubernetes/pull/35653