Revert "Revert "Add kubelet awareness to taint tolerant match calculator.""
kubernetes/kubernetes pull request #34400
Opened 2016-10-08 21:21 UTC by resouer

A revert revert of https://github.com/kubernetes/kubernetes/pull/26501

Aiming at adding kubelet awareness to taint tolerant match calculator.

Ref: #25320

This is required by TaintEffectNoScheduleNoAdmit & TaintEffectNoScheduleNoAdmitNoExecute, so that node will know if it should expect the taint&tolerant

There's a NOTE that the e2e test here will add taint to node, so please don't add more cases to that spec.

cc @davidopp for scheduling part
cc @dchen1107 @Random-Liu for node & node e2e part

2016-10-13 18:43 UTC, yujuhong commented
Assigning to @davidopp and @dchen1107 (based on https://github.com/kubernetes/kubernetes/pull/34350#issuecomment-252375470).

2016-10-13 18:55 UTC, yujuhong commented
Also cc @vishh based on https://github.com/kubernetes/kubernetes/pull/34350#issuecomment-252369687

2016-10-18 20:03 UTC, aveshagarwal requested changes

2016-10-18 20:41 UTC, davidopp commented
I hate to say this, but I think we shouldn't target this to 1.5. We definitely want this feature but it is not a top priority and we are limited on review bandwidth.

2016-10-19 06:17 UTC, resouer commented
I am not against that @davidopp

2016-10-19 06:19 UTC, davidopp commented
Thanks, and apologies for the delay.

2016-10-20 02:36 UTC, resouer commented on plugin/pkg/scheduler/algorithm/predicates/predicates.go
> +	return fits, someUntoleratedTaintIsNoAdmit
I think I've checked this in above lines

2016-10-21 07:45 UTC, resouer commented
Fixed nits, is it looks good now? Or do you still have question about `someUntoleratedTaintIsNoAdmit ` logic?

2016-10-24 09:19 UTC, resouer commented
kindly ping @aveshagarwal

2016-10-24 13:01 UTC, aveshagarwal commented
@resouer I will review it today.

2016-10-31 08:08 UTC, resouer commented
ping @aveshagarwal any update?

2016-11-13 03:39 UTC, resouer commented
ping @aveshagarwal any update from your side?

2016-11-16 03:07 UTC, resouer commented
@davidopp any way to make a progress in this PR? this is definitely lost ...

2016-11-16 20:20 UTC, aveshagarwal commented
@resouer sorry for not getting back to it. Since it is not going to be in 1.5 as I understand, and if the plan is to move away from annotations,  there are 2 options in future:

1. go ahead with this and switch taints/tolerations to api fields from annotations.
2. switch taints/tolerations to api fields from annotations, and then modify it accordingly and go forward with it.

My guess is that beyond 1.5, its better to switch taints/tolerations to api field first rather doing more work that is based on taints/tolerations annotations. so I would say option lets go 2. But that said I would be ok with option 1 too.

@kubernetes/sig-scheduling thoughts?

2016-11-20 21:48 UTC, davidopp commented
Unfortunately #34825 didn't make it into 1.5. I'd like us to wait until that merges before merging this.

2016-11-21 03:03 UTC, resouer commented
@davidopp @aveshagarwal agreed, I added a keep-open label

Just note for me: wait after switch taints/tolerations to api field and use those field instead.

2017-02-24 00:44 UTC, timothysc commented
ping @davidopp @aveshagarwal just checking to see if this is on folks radar...

2017-02-24 01:49 UTC, resouer commented
@timothysc @davidopp I noticed #34825 is not completely finished, I am not sure if we can begin to re-activate this PR?

2017-02-24 01:50 UTC, davidopp commented
For sure let's not do this for 1.6, there's too many other changes in 1.6.

2017-05-26 19:45 UTC, dchen1107 commented
I am closing since it is stale.

2017-05-26 19:45 UTC, closed without merging