Minor fixed to migrate-if-needed script
kubernetes/kubernetes pull request #34438
Opened 2016-10-10 08:30 UTC by wojtek-t

Ref #22448 #20504

@lavalamp

2016-10-11 07:23 UTC, wojtek-t commented
@mml - friendly ping

2016-10-11 19:43 UTC, mml requested changes
LG otherwise.  Feel free to apply label after you fix the test.

2016-10-11 19:43 UTC, mml commented on cluster/images/etcd/migrate-if-needed.sh
> +if [ ! "$(ls -A ${DATA_DIRECTORY})" ]; then
I don't think we want `[ !` here... I think we want `[ -z`.

2016-10-11 20:05 UTC, mml commented
@k8s-bot gci gce e2e test this issue: #33388

2016-10-12 07:00 UTC, wojtek-t commented
Comment applied, adding lgtm label based on above comment.

2016-10-12 08:02 UTC, merged