Change legacy API resource registration
kubernetes/kubernetes pull request #34551
Opened 2016-10-11 17:00 UTC by deads2k

Updates the legacy API resource registration to emphasize its different-ness and to simplify supporting objects.  The option has to remain in the genericapiserverconfig for multiple prefixes to enable cases where composers/extenders had composed additional groupless APIs. See OpenShift as an example.

However this is now transparent to "normal" composers.

@ncdc since sttts is out.

2016-10-12 14:42 UTC, deads2k commented
@k8s-bot unit test this: issue #34580

2016-10-12 14:43 UTC, deads2k commented
@ncdc prereqs made it in, so this is smaller now.

2016-10-12 16:22 UTC, ncdc requested changes

2016-10-12 16:22 UTC, ncdc commented on pkg/genericapiserver/genericapiserver_test.go
> +	s.InstallLegacyAPIGroup("/api", &APIGroupInfo{
This fails because /api isn't a valid api group prefix as defined on line 109. If you check the returned error, you'll see it's non-nil.

2016-10-12 19:32 UTC, deads2k commented
comments addressed.

2016-10-13 11:41 UTC, deads2k commented
@mml `Error waiting for build`

@k8s-bot test this: issue #IGNORE

2016-10-13 15:08 UTC, ncdc approved these changes

2016-10-13 15:23 UTC, merged