build: Fix version generation.
kubernetes/kubernetes pull request #34612
Opened 2016-10-12 14:31 UTC by jellonek

This PR provides update to version string generation procedure to handle additional case - working on branch delivered from release tag, instead of working on `-(alpha|beta).no` suffixed tag.

Reason of it is that actually if someone would start working on branch forked from release tag (`v1.4.1` for example), will add some commits and then would try to build k8s/run conformance tests - will end up with broken version string in form similar to `v1.4.1.X+YYYY` where `X` is a dictance/number of commits from base tag and `YYYY` will be first 14 characters from commit hash.
Such version - containing four dotted parts is rejected during conformance tests with error similar to:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:843
Oct 11 12:38:33.726: Failed to get server version: Unable to parse server version "v1.4.1.5+somecommithash": Invalid character(s) found in patch number "1.5"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:413
```

This PR provides a cure for this situation creating version string in form `v1.4.1-X+YYYY` which then should be readable for version validation checks. 

Release note:
```release-note
Fix version string generation for local version different from release and not based on `-alpha.no` or `-beta.no` suffixed tag.
```

2016-10-12 17:47 UTC, zmerlynn requested changes
Fix nit, then LGTM

2016-10-12 17:47 UTC, zmerlynn commented on hack/lib/version.sh
> +	# We have distance to base tag (v1.1.0-1-gCommitHash)
Fix indentation

2016-10-17 07:14 UTC, jellonek commented on hack/lib/version.sh
> +	# We have distance to base tag (v1.1.0-1-gCommitHash)
Done.

2016-10-18 09:07 UTC, jellonek commented
Bumping up.

2016-10-18 17:26 UTC, zmerlynn approved these changes

2016-10-19 04:11 UTC, merged

2016-10-28 09:31 UTC, pigmej commented
I created cherry pick on release-1.4 (#35775). Can we have `cherrypick-approved` label on this PR? I'd like to have it in 1.4 because it affects it too.

cc @zmerlynn