filter lastAppliedConfig annotation for describe secret
kubernetes/kubernetes pull request #34664
Opened 2016-10-13 00:22 UTC by ymqytw

Temporarily addresses: #23564.
This patch only filters out the lastAppliedConfig annotation when describing a secret. It doesn't fix secret leak from root cause which is the API server gives the unencrypted secret to the client.

2016-10-24 19:08 UTC, ymqytw commented
@brendandburns  Rebased. PTAL

2016-10-25 22:52 UTC, pwittrock commented
@fabianofranz Reassigned to you.  LMK if you don't have time.

2016-10-26 20:11 UTC, fabianofranz requested changes

2016-10-31 23:07 UTC, ymqytw commented
@fabianofranz PTAL

2016-11-01 13:32 UTC, fabianofranz commented
@kubernetes/kubectl @lavalamp PTAL at the proposed strategy since there was some debate in the original issue. This fixes `describe` but the issue still exists once it's exposed by the api, returns in `get -o yaml`, etc.

2016-11-04 01:23 UTC, ymqytw commented
Any update?

2016-11-11 02:37 UTC, fabianofranz commented
@deads2k @lavalamp comments? Trying to figure out if we should go on with this, or not consider an issue based on https://github.com/kubernetes/kubernetes/issues/23564#issuecomment-252776810.

2016-11-11 21:52 UTC, andronat commented
I believe by just not printing a field in kubectl hides the real problem. I'm also afraid that we might forget about it, thus I don't think this is a good approach.

2016-11-19 00:21 UTC, lavalamp commented
I agree, I don't think we should do this. @pwittrock's call, I guess.

2016-11-19 01:12 UTC, pwittrock commented
@andronat @lavalamp kubectl already hides the secret value field in describe, but just missed the value stored in the annotation.  IMHO we should be consistent w.r.t whether or not we hide the secret body in describe.  This wasn't intended as a general fix to access control of secret data, but instead to make the implementation of kubectl describe secret match the original intent - which is don't print the body of the secret data to a user's console when it is returned by the server.

I don't think this is really urgent.  I plan to revisit in a few days.

2017-02-01 01:04 UTC, pwittrock commented
Revisiting this, I think it provides a better end user experience and we should go ahead with it.

@ymqytw When you have some free time would you rebase and we can merge it?

2017-02-01 01:06 UTC, pwittrock commented on pkg/kubectl/describe.go
> +func printLabelsMultilineWithIndent(out io.Writer, initialIndent, title, innerIndent string, labels map[string]string, skipMap map[string]bool) {
The name of this function is terrible since it isn't just about labels.  Fine for now though.

2017-02-01 01:07 UTC, pwittrock commented on pkg/kubectl/describe.go
> +	printLabelsMultilineWithIndent(out, "", title, "\t", labels, nil)
Why not pass in an empty map?

2017-02-01 01:07 UTC, pwittrock commented on pkg/kubectl/describe.go
> +		if skipMap != nil {
If we always pass in an empty map, the logic is simpler

2017-02-03 23:03 UTC, ymqytw commented on pkg/kubectl/describe.go
> +		filterMap := map[string]bool{annotations.LastAppliedConfigAnnotation: true}
Done

2017-02-03 23:20 UTC, ymqytw commented
Addressed comments. PTAL

2017-02-04 01:31 UTC, pwittrock commented
/lgtm

2017-02-04 04:27 UTC, AdoHe commented
LGTM. Will add the approval label.

2017-02-04 04:27 UTC, AdoHe commented
/approved

2017-02-04 04:30 UTC, AdoHe commented
/approve

2017-02-04 21:02 UTC, ymqytw commented
@AdoHe @pwittrock Any idea why it's not working?

2017-02-05 08:11 UTC, AdoHe commented
@ymqytw could be the case sensitivity problem? my id is AdoHe

2017-02-05 16:54 UTC, pwittrock commented
/approved

2017-02-05 16:54 UTC, pwittrock commented
@AdoHe Missing a 'd': `approved` vs `approve`

2017-02-05 16:55 UTC, pwittrock commented
Hm, maybe I am wrong.

2017-02-05 16:55 UTC, pwittrock commented
/approve

2017-02-05 16:56 UTC, pwittrock commented
@apelisse Approval doesn't seem to be working :(

2017-02-15 20:52 UTC, fabianofranz commented
@k8s-bot cvm gce e2e test this

2017-02-15 20:53 UTC, fabianofranz commented
@k8s-bot cri e2e test this

2017-02-16 19:20 UTC, fabianofranz commented
@k8s-bot bazel test this

2017-02-16 21:40 UTC, fabianofranz approved these changes

2017-02-16 21:40 UTC, fabianofranz commented
@k8s-bot gce etcd3 e2e test this

2017-02-17 01:05 UTC, merged