Move the common test functions from cmd_test.go to cmd/testing/fake.go
kubernetes/kubernetes pull request #34683
Opened 2016-10-13 03:28 UTC by asalkeld

**What this PR does / why we need it**:
This is so that we can use NewAPIFactory() from cmd/set/*test.go
Up until now we would get a import loop error.

This commit also adds a basic unit test case for cmd/set/set_image.go

**Which issue this PR fixes**
partial #34592

**Special notes for your reviewer**:
None

**Release note**:
```release-note
NONE
```

2016-10-13 12:03 UTC, deads2k commented
This needs to hold for https://github.com/kubernetes/kubernetes/pull/33180

2016-10-14 12:24 UTC, deads2k commented
@fabianofranz I think this has implications downstream.  If the pattern works well, this could give you command line unit tests.

2016-10-14 12:24 UTC, deads2k commented
@soltysh fyi, since you've bugged me about them before. :)

2016-10-14 19:12 UTC, fabianofranz commented
Nice move.

2016-10-18 07:15 UTC, asalkeld commented
@fabianofranz PTAL

2016-10-18 18:23 UTC, fabianofranz requested changes
Minor nits about things that were here already, otherwise LGTM.

2016-10-18 18:23 UTC, fabianofranz commented on pkg/kubectl/cmd/testing/fake.go
> +type internalType struct {
Once you are here, should we make all these types exported? Like `InternalType`, `ExternalType`, and `ExternalType2`. Unless they are embedded in public structs, there isn't much sense in having unexported structs with exported fields.

2016-10-18 18:23 UTC, fabianofranz commented on pkg/kubectl/cmd/testing/fake.go
> +var UnlikelyGV = unversioned.GroupVersion{Group: "apitest", Version: "unlikelyversion"}
Same here, make all these vars exported?

2016-10-18 18:23 UTC, fabianofranz commented on pkg/kubectl/cmd/testing/fake.go
> +// TODO move to fake.go
This TODO can be removed?

2016-10-18 18:23 UTC, fabianofranz commented on pkg/kubectl/cmd/testing/fake.go
> +type testFactory struct {
Same for this one?

2016-10-18 22:54 UTC, asalkeld commented
@fabianofranz I made the changes you suggested.

2016-10-19 14:12 UTC, fabianofranz commented
LGTM, @deads2k mind tagging?

2016-10-19 15:03 UTC, merged