Implement kubeadm reset
kubernetes/kubernetes pull request #34807
Opened 2016-10-14 09:27 UTC by luxas

@kubernetes/sig-cluster-lifecycle

2016-10-14 13:55 UTC, dgoodwin reviewed
This worked great on CentOS, just a few questions and one very minor request for changes.

2016-10-14 13:55 UTC, dgoodwin commented on cmd/kubeadm/app/cmd/init.go
> +		fmt.Println("Running pre-flight checks")
Intentional?

2016-10-14 13:55 UTC, dgoodwin commented on cmd/kubeadm/app/preflight/checks.go
> -		PortOpenCheck{port: 10252},
Did these turn out to not be necessary?

2016-10-14 13:55 UTC, dgoodwin commented on cmd/kubeadm/app/cmd/reset.go
> +	fmt.Printf("Deleting the stateful directories: [%v]\n", dirsToRemove)
This shows up as: Deleting the stateful directories: [[/var/lib/kubelet /var/lib/etcd /etc/kubernetes]]

Can probably drop the [] in code.

2016-10-14 13:55 UTC, dgoodwin commented on cmd/kubeadm/app/cmd/reset.go
> +		fmt.Printf("failed to stop the running containers")
Should we actually clean these up or just kill? My reset script I'd been clearing them out entirely.

Also should we only hit containers with a k8s prefix?

2016-10-14 14:01 UTC, dgoodwin commented on cmd/kubeadm/app/cmd/reset.go
> +		fmt.Printf("failed to stop the running containers")
Thinking we may want to filter to k8s containers only, I could envision a developer deciding to init master on their workstation.

2016-10-14 14:27 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> +		fmt.Println("Running pre-flight checks")
Yep, I think we decided to drop it
At least it was dropped in join

2016-10-14 14:28 UTC, luxas commented on cmd/kubeadm/app/cmd/reset.go
> +		fmt.Printf("failed to stop the running containers")
I thought about that, leads to more work, but is probably worth it

Not sure if we should remove them though... the user might want to read logs

2016-10-14 16:04 UTC, pires commented on cmd/kubeadm/app/cmd/init.go
> +		fmt.Println("Running pre-flight checks")
Drop it.

2016-10-14 17:23 UTC, luxas commented on cmd/kubeadm/app/preflight/checks.go
> -		PortOpenCheck{port: 10252},
This is for the node, 10251 and 10252 for cm and scheduler and 8080 for unsecured apiserver

2016-10-14 19:25 UTC, errordeveloper requested changes

2016-10-14 19:25 UTC, errordeveloper commented on cmd/kubeadm/app/cmd/reset.go
> +		fmt.Printf("no supported init system detected, skipping service checks for %s. kubeadm reset may not have full effect now.\n", serviceToStop)
Why doesn't `initsystem.GetInitSystem()` return that string as an error?

2016-10-14 19:25 UTC, errordeveloper commented on cmd/kubeadm/app/cmd/reset.go
> +	exec.Command("sh", "-c", "cat /proc/mounts | awk '{print $2}' | grep '/var/lib/kubelet' | xargs umount").Run()
I think `find /var/lib/kubelet | xargs -n 1 findmnt -n -t tmpfs -o TARGET -T | uniq | xargs -r umount ` is cleaner.

2016-10-14 19:25 UTC, errordeveloper commented on cmd/kubeadm/app/cmd/reset.go
> +	exec.Command("sh", "-c", "cat /proc/mounts | awk '{print $2}' | grep '/var/lib/kubelet' | xargs umount").Run()
If you depend on `awk`, you don't have to use `grep`, i.e. `awk '$2 ~ /\/var\/lib\/kubelet { print $2 }' | xargs umount`, or even `awk '$2 ~ /\/var\/lib\/kubelet { system("umount "$2) }`, on the other hand you don't even have to shell out...

2016-10-14 19:25 UTC, errordeveloper commented on cmd/kubeadm/app/cmd/reset.go
> +		fmt.Printf("failed to stop the running containers")
I think we should use `docker rm --force --volumes` here.

> the user might want to read logs

Maybe, but more user will complain about disk space used up by those containers.

2016-10-14 21:44 UTC, luxas commented
PTAL @pires @mikedanese @dgoodwin @errordeveloper

2016-10-14 21:45 UTC, luxas commented
I'd like to get this lgtm'd ASAP, if @mikedanese could do it, it would be awesome! (Ilya is offline now)

2016-10-14 22:23 UTC, dgoodwin approved these changes
LGTM

2016-10-15 07:57 UTC, luxas commented
Applying @dgoodwin's LGTM

2016-10-15 08:38 UTC, pires requested changes

2016-10-15 08:38 UTC, pires commented on cmd/kubeadm/app/cmd/reset.go
> +
Why the empty line?

2016-10-15 08:38 UTC, pires commented on cmd/kubeadm/app/cmd/reset.go
> +			return err
This will break pre-flight checks. It should be `return &preflight.PreFlightError{Msg: err.Error()}}` instead.

2016-10-15 09:04 UTC, luxas commented
Fixed @pires' comments, waiting for the build to be green before applying lgtm again

2016-10-15 09:07 UTC, pires approved these changes
LGTM

2016-10-15 13:10 UTC, merged