glog non-fatal, usually unimportant error instead of fmt
kubernetes/kubernetes pull request #34981
Opened 2016-10-17 20:34 UTC by deads2k

Fixes https://github.com/kubernetes/kubernetes/issues/34977

This particular message isn't usually important, so demote it to glog.

2016-10-17 20:38 UTC, fabianofranz requested changes

2016-10-17 20:38 UTC, fabianofranz commented on pkg/kubectl/cmd/util/factory.go
> +			glog.V(1).Infof("Unable to register third party resources: %v\n", err)
In `glog` you don't want the line break.

2016-10-18 11:59 UTC, deads2k commented
> In glog you don't want the line break.

fixed up.

2016-10-18 12:59 UTC, merged

2016-10-18 13:36 UTC, fabianofranz commented
LGTM