filter out secrets of command for rollout
kubernetes/kubernetes pull request #35030
Opened 2016-10-18 10:01 UTC by xilabao

this pr is used to hide user's secret information from "kubectl rollout histroy ..."

The current is someone create a pod specified the username and password, others can see the secrets.
for example:
```
ubuntu@kube-master:~$ kubectl create -f nginx.yaml --record -s https://127.0.0.1:6443 --insecure-skip-tls-verify=true --username=test --password=123456
deployment "my-nginx" created

ubuntu@kube-master:~$ kubectl rollout history deployment/my-nginx
deployments "my-nginx"
REVISION	CHANGE-CAUSE
1		kubectl create -f nginx.yaml --record -s https://127.0.0.1:6443 --insecure-skip-tls-verify=true --username=test--password=123456
```

username&password will be exposed
so this pr plan to hide token、username and password, such as:

use username/password
```

ubuntu@kube-master:~$ kubectl create -f nginx.yaml --record -s https://127.0.0.1:6443 --insecure-skip-tls-verify=true --username=test --password=123456
deployment "my-nginx" created

ubuntu@kube-master:~$ kubectl rollout history deployment/my-nginx
deployments "my-nginx"
REVISION	CHANGE-CAUSE
1		kubectl create -f nginx.yaml --record -s https://127.0.0.1:6443 --insecure-skip-tls-verify=true --username=****** --password=******

```
use token

```
ubuntu@kube-master:~$ kubectl edit deployment/my-nginx  -s https://127.0.0.1:6443 --insecure-skip-tls-verify=true --token=123456
deployment "my-nginx" edited

ubuntu@kube-master:~$ kubectl rollout history deployment/my-nginx
deployments "my-nginx"
REVISION	CHANGE-CAUSE
1		kubectl create -f nginx.yaml --record -s https://127.0.0.1:6443 --insecure-skip-tls-verify=true --username=****** --password=******
2		kubectl edit deployment/my-nginx -s https://127.0.0.1:6443 --insecure-skip-tls-verify=true --token=******
```

2016-10-18 10:08 UTC, xilabao commented
@k8s-bot ok to test

2016-10-18 17:27 UTC, kargakis commented
@kubernetes/kubectl

2016-10-19 02:18 UTC, smarterclayton commented
This is unfortunately not all flags that could be secrets.  The best option would be to add support in `spf13/pflag` to tag a flag as a secret, and then use that bit to determine the list.

Also, `Command()` could be used in contexts that need exact parameters (for subshell execution), so we would need to add a new method or extend the signature here to allow exact flags to be retrieved.

2016-10-19 02:39 UTC, xilabao commented
@smarterclayton you are right. I can volunteer to finish the feature if you haven't already started on that.

2016-11-22 14:09 UTC, eparis commented
If you want to solve this, generically, in cobra/pflag we can, but we don't "need" to. Solving it generically in cobra/pflag would mean adding a function like "GetCmdLine()" or something to cobra. That would run all of the flags in the flagset, ignoring those which were unset, and printing those which were set. We would stop doing `os.Args` parsing at all in kubernetes (maybe a good thing). Given that the flags are in a map we are going to lose the ordering (and maybe predictability)...  which stinks...

But it would mean that cobra/pflag would know you are trying to get the command line which would mean that things like 'secret' would make sense to those tools. They would do some ****** type transformation before printing. Normally cobra/pflag would have no idea when the calling code wants the actual value or ******. Which is why i've been hesitant of your work in pflag. I've never understood how pflag was supposed to know what to do.

2016-11-22 14:15 UTC, eparis requested changes
You can take 2 paths.  1 replace all of this with a new function in Cobra/pflag.

Follow these comments to simplify things here. I don't love that "short flags" are ignored, but its a step in a better direction....

2016-11-22 14:15 UTC, eparis commented on pkg/kubectl/cmd/util/factory.go
> +		if strings.HasPrefix(args[i], "--") {
This does not handle 'short' flags. Which stinks. Should we find a way to library-ify the command line parsing logic in pflag? `spf13/pflag/flags.go::parseArgs()` is quite complex to get right...

2016-11-22 14:15 UTC, eparis commented on pkg/kubectl/cmd/util/factory.go
> +func GetFlagValue(flags *pflag.FlagSet, name string, enableSecret bool) (string, error) {
I do not believe this function serves any value....

2016-11-22 14:15 UTC, eparis commented on pkg/kubectl/cmd/util/factory.go
> +			if flag != nil && flag.Secret {
I do not think that we need `flag.Secret` / changes to pflag. Instead set an annotation on the flag back when it was created and check for that annotation here.

2016-11-22 14:15 UTC, eparis commented on pkg/kubectl/cmd/util/factory.go
> +				value, err := GetFlagValue(f.flags, name, enableSecret)
Why do we need `GetFlagValue()` ?
```
If enableSecret {
    args[i] = "--" + name + "=***********"
} else {
   // do nothing, args already fine
}
````

2016-11-22 14:15 UTC, eparis commented on pkg/kubectl/cmd/util/factory.go
> +func (f *factory) Command(enableSecret bool) string {
maybe `printSecret`, `displaySecret`, or `showSecret` instead? Is there ever a case where we'd want to display the secret? Do we need to have that option?

2016-11-23 06:59 UTC, xilabao commented on pkg/kubectl/cmd/util/factory.go
> +		if strings.HasPrefix(args[i], "--") {
@eparis I need to get flag.NoOptDefVal to make a distinction between "--flag" and "--flag arg". I can use flags.Lookup() to handle 'long' flags. but I can't find a way to handle 'short' flag. Do I ignore something?

2017-01-19 07:37 UTC, xilabao commented
@eparis After the work (https://github.com/spf13/pflag/pull/107) has been done, I update the patch to use new function. PTAL.

2017-01-19 07:41 UTC, xilabao commented
The new result will be
```
# ./cluster/kubectl.sh create --record=true -f ~/nginx.yaml --token=test/system:masters
deployment "my-nginx" created
# ./cluster/kubectl.sh  rollout history deployment/my-nginx                            
deployments "my-nginx"
REVISION	CHANGE-CAUSE
1		kubectl --record true --filename /home/nfs/nginx.yaml --token XXX
```

2017-02-27 01:48 UTC, closed without merging