Eliminate half-baked multi-architecture support
kubernetes/kubernetes pull request #35124
Opened 2016-10-19 14:02 UTC by errordeveloper

**What this PR does / why we need it**:

We have release `kubeadm` with half-baked support for clusters with nodes of different CPU architectures. The problem with the code as it stand is that user will notice pending daemonsets of `kube-proxy` for machines with architectures that they don't have. At the same time, the code as it stand did not pick up correct images for architectures it wanted to allow. This removes multiple daemonesets, but ensures that whichever resources we deploy have node affinity set to the architecture native to the master. Users wishing to use mixed architectures can still create extra daemonsets via the API.

**Which issue this PR fixes**: fixes #33916

**Release note**:
```release-note
Remove support for multi-architecture code in `kubeadm`, which was released untested.
```

2016-10-19 14:22 UTC, pires commented
@luxas you're the ARM ninja around, care to test?

2016-10-19 18:34 UTC, jbeda requested changes
Looks reasonable to me with some small nits.  Would love to get @luxas's take.

2016-10-19 18:34 UTC, jbeda commented on cmd/kubeadm/app/master/apiclient.go
> +func MonoArchitectureNodeAffinity() api.NodeSelectorRequirement {
The term "Mono" here makes me think of [Mono](http://www.mono-project.com/) and windows and such.  Perhaps just "ArchitectureNodeAffinity"?  If we add multi-arch support in the future we can rename/rework this.

2016-10-19 18:34 UTC, jbeda commented on cmd/kubeadm/app/master/apiclient.go
> +func SetNodeAffinity(meta *api.ObjectMeta, expr ...api.NodeSelectorRequirement) {
We don't have documentation on public functions here and we should probably start.  Can you start documenting some of this stuff as you touch it?

2016-10-19 18:34 UTC, jbeda commented on cmd/kubeadm/app/master/apiclient.go
> +func MasterNodeAffinity() api.NodeSelectorRequirement {
Doc?

2016-10-19 18:34 UTC, jbeda commented on cmd/kubeadm/app/master/apiclient.go
> +func MonoArchitectureNodeAffinity() api.NodeSelectorRequirement {
Doc?

2016-10-20 14:45 UTC, errordeveloper commented on cmd/kubeadm/app/master/apiclient.go
> +func MonoArchitectureNodeAffinity() api.NodeSelectorRequirement {
Haha, happy to rename. What about `NativeArchitectureNodeAffinity()`?

2016-10-20 14:45 UTC, errordeveloper commented on cmd/kubeadm/app/master/apiclient.go
> +func SetNodeAffinity(meta *api.ObjectMeta, expr ...api.NodeSelectorRequirement) {
Ack.

2016-10-20 17:47 UTC, jbeda commented on cmd/kubeadm/app/master/apiclient.go
> +func MonoArchitectureNodeAffinity() api.NodeSelectorRequirement {
`NativeArchitectureNodeAffinity` SGTM

2016-10-21 13:56 UTC, errordeveloper commented
@jbeda I've addressed your comments and rebased.

2016-10-21 22:19 UTC, merged