Eviction manager evicts based on inode consumption
kubernetes/kubernetes pull request #35137
Opened 2016-10-19 17:06 UTC by dashpole

Integrate Cadvisor per-container inode stats into the summary api.  Make the eviction manager act based on inode consumption to evict pods using the most inodes.

This PR is pending on a cadvisor godeps update which will be included in PR #35136

2016-10-19 17:36 UTC, derekwaynecarr commented
@dashpole can you add a test case that evicts based on inodes similar to the other test cases that work on disk?

2016-10-19 17:45 UTC, dashpole commented
yes, the test is going out in a seperate PR #33955.  I will be testing 3 pods: one creates empty files in it's container, one creates empty files in an emptydir volume, and another creates one, large file.  The eviction manager should hit inodepressure and evict both of the containers making empty files.  I still need to look into making the test skip the "empty files in container" pod when using devicemapper.  I also want to run the test more, to make sure it isnt flaky before adding the test.

2016-10-19 17:55 UTC, derekwaynecarr commented
@dashpole -- the e2e test is good, but we should also be able to mock the test in unit testing as well via https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager_test.go#L315

2016-10-19 18:02 UTC, dashpole commented
@derekwaynecarr ill add a unit test to this commit

2016-10-24 21:01 UTC, dashpole commented
I found a bug in the eviction manager tests.  We were not assigning pods a UID, so the cached stats function was always returning the last (in order of when pods were added) pod's statsFunc.  This meant that all calls to statsFunc returned the same value.  This did not break tests because we always passed in the pod we wanted to fail as the first pod, and the eviction manager would leave that ordering intact when pods tie in their consumption.  Changing the order of pods broke all tests in eviction_manager_test.go.  Changing the newPod function in helpers_test.go to include a UID based on the name fixed the problem.

2016-10-28 00:17 UTC, dashpole commented
@derekwaynecarr @dchen1107 this all ready to go as soon as one of you has the chance to review it.

2016-10-28 16:39 UTC, dashpole commented
*[pkg/kubelet/eviction/eviction_manager_test.go, line 103 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137#-KVB94UyiTJE2ttAD2Sf:-KVB94UyiTJE2ttAD2Sg:b89vpfc) ([raw file](https://github.com/kubernetes/kubernetes/blob/08456255561bd61341526d185430126ac155ca2d/pkg/kubelet/eviction/eviction_manager_test.go#L103)):*
> ```Go
> 		memoryWorkingSet string
> 	}{
> 		{name: "guaranteed-low", requests: newResourceList("100m", "1Gi"), limits: newResourceList("100m", "1Gi"), memoryWorkingSet: "200Mi"},
> ```

Changed ordering to prevent regression on bug described in git comments.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137)*
<!-- Sent from Reviewable.io -->

2016-10-28 16:39 UTC, dashpole commented
*[pkg/kubelet/eviction/eviction_manager_test.go, line 117 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137#-KVB9ESxbpHTt7t2qRAt:-KVB9ESyBNZDKXXiLgmC:bqhgbs8) ([raw file](https://github.com/kubernetes/kubernetes/blob/08456255561bd61341526d185430126ac155ca2d/pkg/kubelet/eviction/eviction_manager_test.go#L117)):*
> ```Go
> 		podStats[pod] = podStat
> 	}
> 	podToEvict := pods[5]
> ```

Eviction manager reorders pods when choosing which pod to evict, so grab a reference to the correct pod to evict now...

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137)*
<!-- Sent from Reviewable.io -->

2016-10-28 16:41 UTC, dashpole commented
*[pkg/kubelet/eviction/helpers_test.go, line 1570 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137#-KVB9fysxjkTU-gQvGXe:-KVB9fyt-DJZVl5LuFMC:b-30egn9) ([raw file](https://github.com/kubernetes/kubernetes/blob/08456255561bd61341526d185430126ac155ca2d/pkg/kubelet/eviction/helpers_test.go#L1570)):*
> ```Go
> 		ObjectMeta: api.ObjectMeta{
> 			Name: name,
> 			UID:  types.UID(name),
> ```

This is to fix the bug described in the git comments.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137)*
<!-- Sent from Reviewable.io -->

2016-10-31 17:57 UTC, derekwaynecarr commented
/lgtm

2016-10-31 18:04 UTC, dashpole commented
*[pkg/kubelet/server/stats/summary.go, line 118 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137#-KVQuSKlGWNkuQ73D8P0:-KVQuSKmM4IgLg7iV9BK:beyowup) ([raw file](https://github.com/kubernetes/kubernetes/blob/08456255561bd61341526d185430126ac155ca2d/pkg/kubelet/server/stats/summary.go#L118)):*
> ```Go
> 	}
> 
> 	nodeFsInodesUsed := *sb.rootFsInfo.Inodes - *sb.rootFsInfo.InodesFree
> ```

Is this safe to do?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137)*
<!-- Sent from Reviewable.io -->

2016-10-31 18:26 UTC, derekwaynecarr requested changes
i missed this originally, thx for pointer.

2016-10-31 18:26 UTC, derekwaynecarr commented on pkg/kubelet/server/stats/summary.go
> +	nodeFsInodesUsed := *sb.rootFsInfo.Inodes - *sb.rootFsInfo.InodesFree
you will need to check for nil on both values.  for imagefs, it will be nil for both inodes and inodesfree values.

2016-10-31 19:11 UTC, dashpole commented
*[pkg/kubelet/server/stats/summary.go, line 118 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137#-KUSuDIVxqrkE4X63xCg-r1-118:-KVR8l9PQDTAQwJnHBfB:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/08456255561bd61341526d185430126ac155ca2d/pkg/kubelet/server/stats/summary.go#L118)):*
<details><summary><i>Previously, derekwaynecarr (Derek Carr) wrote…</i></summary>
> you will need to check for nil on both values.  for imagefs, it will be nil for both inodes and inodesfree values.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35137)*
<!-- Sent from Reviewable.io -->

2016-10-31 19:59 UTC, dashpole commented
@k8s-bot gci gke e2e test this

2016-10-31 20:01 UTC, derekwaynecarr approved these changes

2016-10-31 20:02 UTC, derekwaynecarr commented
@k8s-bot gci gke e2e test this

2016-10-31 20:59 UTC, dashpole commented
@k8s-bot gci gke e2e test this

2016-10-31 21:49 UTC, dchen1107 commented
LGTM

2016-11-01 01:12 UTC, dashpole commented
@k8s-bot unit test this

2016-11-01 14:47 UTC, dashpole commented
@k8s-bot unit test this

2016-11-01 17:32 UTC, merged