Use replace instead of patch for kubectl edit
kubernetes/kubernetes pull request #35171
Opened 2016-10-20 04:32 UTC by ymqytw

Use replace instead of patch for `kubectl edit`.
Fixes: #35016, #32398
But the root cause of #32398, which is related to strategic patch, is not fixed by this PR.
@pwittrock

2016-10-20 23:32 UTC, ymqytw commented
@k8s-bot cvm gke e2e test this

2016-10-20 23:32 UTC, ymqytw commented
@k8s-bot gci gke e2e test this

2016-10-24 20:08 UTC, fabianofranz requested changes

2016-10-24 20:08 UTC, fabianofranz commented on pkg/kubectl/cmd/edit.go
> +		ok, err := checkAPiVersionKindName(currOriginalObj, info.Object)
Or try a more meaningful name, something like 

```
valid, err := validateImmutableAPIFields(currOriginalObj, info.Object)
```

2016-10-24 20:08 UTC, fabianofranz commented on pkg/kubectl/cmd/edit.go
> +	goerrors "errors"
Just leave this as `"errors"`.

2016-10-24 20:08 UTC, fabianofranz commented on pkg/kubectl/cmd/edit.go
> +			return goerrors.New("At least one of apiVersion, kind and name was changed")
Not very clear, try something like "The following fields must not be changed: apiVersion, kind, and metadata.name".

2016-10-25 12:23 UTC, zefciu commented
According to the discussion in https://github.com/kubernetes/kubernetes/issues/32398 this is not the preferred way to fix this bug. We should rather fix the PATCH verb.

2016-10-25 16:09 UTC, ymqytw commented
We are actively fixing the strategic patch that used by PATCH.

2016-10-25 23:03 UTC, pwittrock commented
@zefciu Why should we be using PATCH for kubectl edit since the whole config is read into the editor and visible?  Since this is consumed by an end user, wouldn't we prefer getting an optimistic lock exception if something changes anyway?

What was the original rationale for using patch for kubectl edit?

2016-10-26 22:52 UTC, ymqytw commented
@zefciu I created a PR #35647 to fix the root cause of #32398.

2016-10-26 22:56 UTC, ymqytw commented
@fabianofranz Updated. PTAL

2016-10-27 18:27 UTC, fabianofranz commented
I'm not completely confident about this. 

Replace seems to be a better fit than patch for `edit` since you have the entire object marshalled in the editor in front of you, and I understand that when you hit `:wq` you are deliberately saying "take it, this is how my object should look like", not "take this piece I just changed, not the whole of what's in the screen". If the entire object could not be replaced because it changed in the meantime, you get an error (optimistic lock failure).

On the other hand, @smarterclayton has a point in https://github.com/kubernetes/kubernetes/issues/32398#issuecomment-250620305 when saying there are objects that change rapidly and multiple times which would in some cases even prevent you from using `edit` if we do a full replace. Which may be the correct thing to do, just annoying.

@ymqytw does https://github.com/kubernetes/kubernetes/pull/35647 completely fix editing when you remove elements from a list (https://github.com/kubernetes/kubernetes/issues/32398)?

2016-10-27 21:14 UTC, ymqytw commented
> there are objects that change rapidly and multiple times which would in some cases even prevent you from using edit if we do a full replace. Which may be the correct thing to do, just annoying.

This is safe, but sometimes could be annoying.

> does #35647 completely fix editing when you remove elements from a list (#32398)?

I still working on #35647. But I believe it will completely fix the commands using strategicMergePatch, i.e. apply, edit and patch.

2016-10-27 22:27 UTC, smarterclayton commented
We explicitly put patch in because the experience of edit without it was
unusable on anything that was under active controller action.

Replace should never really be used in most clients.  I'm ok with making it
be an option to edit, but it's not a great story in general.

On Thu, Oct 27, 2016 at 5:14 PM, Mengqi Yu <notifications@github.com> wrote:

> there are objects that change rapidly and multiple times which would in
> some cases even prevent you from using edit if we do a full replace. Which
> may be the correct thing to do, just annoying.
>
> This is safe, but sometimes could be annoying.
>
> does #35647 <https://github.com/kubernetes/kubernetes/pull/35647>
> completely fix editing when you remove elements from a list (#32398
> <https://github.com/kubernetes/kubernetes/issues/32398>)?
>
> I still working on #35647
> <https://github.com/kubernetes/kubernetes/pull/35647>. But I believe it
> will completely fix the commands using strategicMergePatch, i.e. apply,
> edit and patch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35171#issuecomment-256771850>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p6M8T5mhM_9a6FbTylfyqh55dnU1ks5q4RREgaJpZM4KbtgO>
> .
>

2016-10-29 23:02 UTC, ymqytw commented
Closed this PR.
Ref: #35016

2016-10-29 23:02 UTC, closed without merging