client: update WasCreated to HasStatusCode and pass status code
kubernetes/kubernetes pull request #35209
Opened 2016-10-20 15:55 UTC by kargakis

@smarterclayton @krousey ptal

2016-10-20 16:14 UTC, smarterclayton commented
I prefer just allowing the status code to be accessed.  We aren't hiding
the fact that we are talking to an HTTP server.

On Thu, Oct 20, 2016 at 11:56 AM, Michail Kargakis <notifications@github.com
> wrote:

> @smarterclayton <https://github.com/smarterclayton> @krousey
> <https://github.com/krousey> ptal
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/kubernetes/kubernetes/pull/35209
> Commit Summary
>
>    - client: update WasCreated to HasStatusCode and pass status code
>
> File Changes
>
>    - *M* pkg/client/restclient/client_test.go
>    <https://github.com/kubernetes/kubernetes/pull/35209/files#diff-0> (8)
>    - *M* pkg/client/restclient/request.go
>    <https://github.com/kubernetes/kubernetes/pull/35209/files#diff-1> (8)
>    - *M* pkg/client/restclient/request_test.go
>    <https://github.com/kubernetes/kubernetes/pull/35209/files#diff-2> (4)
>
> Patch Links:
>
>    - https://github.com/kubernetes/kubernetes/pull/35209.patch
>    - https://github.com/kubernetes/kubernetes/pull/35209.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35209>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p5pZDRpWSD2hBarBADbRFf8LSP_dks5q148UgaJpZM4KcTH6>
> .
>

2016-10-20 16:21 UTC, krousey commented
The fact that `WasCreated` even exists irks me a little, and I would entertain the idea of removing it if it doesn't break clients. And we certainly don't need a `HasStatusCode`. That need can be completely fulfilled by the `StatusCode` accessor and a comparison.

2016-10-22 10:54 UTC, kargakis commented
I just removed WasCreated and used [StatusCode](https://github.com/kubernetes/kubernetes/blob/eeae8b59752a0420138e3a47013a9def8080fee5/pkg/client/restclient/request.go#L1080) which does what I want without the need to export the field.

2016-10-22 17:47 UTC, smarterclayton commented
@kargakis in the next rebase you get to fix this usage in openshift

2016-10-23 13:22 UTC, kargakis commented
> @kargakis in the next rebase you get to fix this usage in openshift

We don't use WasCreated anywhere and I am fixing our client in https://github.com/openshift/origin/pull/11500. Not sure if you want something more.

2016-10-25 18:16 UTC, smarterclayton commented
Why does it irk you?  That it's too specific (when status code is more
general)?

Update is one fourth of the http verbs, and PUT to create is part of the
intent of the verb.  Just not common in our use because we don't really
ever do idempotent updates or have a reason to use blind update today.

On Oct 20, 2016, at 12:21 PM, krousey <notifications@github.com> wrote:

The fact that WasCreated even exists irks me a little, and I would
entertain the idea of removing it if it doesn't break clients. And we
certainly don't need a HasStatusCode. That need can be completely fulfilled
by the StatusCode accessor and a comparison.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/35209#issuecomment-255155100>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ABG_p7TxUUx88xmnntxVyHCd7UwOijluks5q15ULgaJpZM4KcTH6>
.

2016-10-25 18:24 UTC, smarterclayton commented
Hrm, looks like Jordan refactored the rest of it out.

On Sun, Oct 23, 2016 at 9:23 AM, Michail Kargakis <notifications@github.com>
wrote:

> @kargakis <https://github.com/kargakis> in the next rebase you get to fix
> this usage in openshift
>
> We don't use WasCreated anywhere and I am fixing our client in
> openshift/origin#11500 <https://github.com/openshift/origin/pull/11500>.
> Not sure if you want something more.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35209#issuecomment-255588338>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_pzOiVSSSU6QrqwtpA7ts6h9nCmDcks5q21-1gaJpZM4KcTH6>
> .
>

2016-10-25 18:41 UTC, krousey commented
>Why does it irk you?  That it's too specific (when status code is more
general)?

That's pretty much it. It needlessly expands the API surface of the client without really adding any new functionality.

```go
created := false
err = c.Put().Namespace("ns").Resource("pods").Name("foo").Body(pod).Do().WasCreated(&created)
...
if !created {
   // stuff
}
```

is not a huge win over

```go
var status int
err = c.Put().Namespace("ns").Resource("pods").Name("foo").Body(pod).Do().StatusCode(&status)
...
if status != http.StatusCreated {
   // stuff
}
```

>Update is one fourth of the http verbs, and PUT to create is part of the
intent of the verb.  Just not common in our use because we don't really
ever do idempotent updates or have a reason to use blind update today.

I can't find a single use of it in our code base outside of tests. I suspect many others don't use the restclient directly, rather they probably use the generated clients or dynamic client on top of the restclient. However I can't guarantee this, which is why I added "if it doesn't break clients."

2016-10-25 21:56 UTC, smarterclayton commented
I'm fine with removing it, just pointing out it had a purpose originally
that we ended up not doing (because blind update is less useful than PATCH)

On Tue, Oct 25, 2016 at 2:41 PM, krousey <notifications@github.com> wrote:

> Why does it irk you? That it's too specific (when status code is more
> general)?
>
> That's pretty much it. It needlessly expands the API surface of the client
> without really adding any new functionality.
>
> created := false
> err = c.Put().Namespace("ns").Resource("pods").Name("foo").Body(pod).Do().WasCreated(&created)
> ...if !created {
>    // stuff
> }
>
> is not a huge win over
>
> var status int
> err = c.Put().Namespace("ns").Resource("pods").Name("foo").Body(pod).Do().StatusCode(&status)
> ...if status != http.StatusCreated {
>    // stuff
> }
>
> Update is one fourth of the http verbs, and PUT to create is part of the
> intent of the verb. Just not common in our use because we don't really
> ever do idempotent updates or have a reason to use blind update today.
>
> I can't find a single use of it in our code base outside of tests. I
> suspect many others don't use the restclient directly, rather they probably
> use the generated clients or dynamic client on top of the restclient.
> However I can't guarantee this, which is why I added "if it doesn't break
> clients."
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35209#issuecomment-256133678>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p-T-sVoSeEQwqOz5vtqFenSOmcX5ks5q3k1mgaJpZM4KcTH6>
> .
>

2016-10-27 18:59 UTC, krousey requested changes

2016-10-27 18:59 UTC, krousey commented on pkg/client/restclient/client_test.go
> -func TestDoRequestCreated(t *testing.T) {
Why remove these tests? Couldn't you just change them to check the status code?

2016-10-27 18:59 UTC, krousey commented on pkg/client/restclient/request_test.go
> -func TestWasCreated(t *testing.T) {
I think this is probably the only test that should be removed.

2016-10-28 15:36 UTC, kargakis commented
@krousey updated ptal

2016-11-01 18:28 UTC, krousey requested changes
There seem to be some tests that had broken logic.

2016-11-01 18:28 UTC, krousey commented on pkg/client/restclient/request_test.go
> +	if statusCode == 202 {
minor nit: use `http.StatusCreated`

2016-11-01 18:28 UTC, krousey commented on pkg/client/restclient/client_test.go
> +	body, err := c.Get().Prefix("test").Do().StatusCode(&statusCode).Raw()
Ok. Now I'm really confused. `created` and now `statusCode` don't really seem to be used/validated ANYWHERE. In `validate`, there's a check against `testParam.actualCreated`, and I can't find anywhere where that variable is set.

Shouldn't these `TestParam`s have a field initializer `actualCreate: statusCode == http.StatusCreated,` in them?

2016-11-21 10:08 UTC, kargakis commented
Won't get to this anytime soon since it's not a high priority.

2016-11-21 10:08 UTC, closed without merging