enhance join arguments generation logic using template
kubernetes/kubernetes pull request #35265
Opened 2016-10-21 07:50 UTC by redhatlinux10

**What this PR does / why we need it**:
this PR enhances kubeadm join arguments generation logic using template, this makes code more readable and adding arguments more  easier.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

Signed-off-by: 欧阳钦华10079130 <ouyang.qinhua@zte.com.cn>

2016-10-21 07:59 UTC, redhatlinux10 commented
I signed it!

2016-10-21 09:10 UTC, redhatlinux10 commented
hi, i have already signed CNCF, why this PR still say that redhatlinux10 needs CLA ?
please help!

2016-10-21 17:55 UTC, jbeda requested changes

2016-10-22 03:46 UTC, redhatlinux10 commented
hi @jbeda  , i have modified the codes as you suggested, would you like to review again ?

2016-10-22 21:51 UTC, jbeda requested changes
Looking good!  Just one typo.

2016-10-22 21:51 UTC, jbeda commented on cmd/kubeadm/app/cmd/init.go
> +		{{" --discovery-port=="}}{{.Cfg.Discovery.BindPort -}}
I think there is an extra `=` here.

2016-10-22 22:48 UTC, redhatlinux10 commented
@jbeda sorry for the typo, i have fixed it, please review, thanks !

2016-10-22 22:51 UTC, jbeda approved these changes

2016-10-22 22:51 UTC, jbeda commented
Looks good!  Thanks!

2016-10-23 00:15 UTC, merged