CRI: Add cri e2e test
kubernetes/kubernetes pull request #35266
Opened 2016-10-21 07:57 UTC by xlgao-zju

This pr use e2e framework to validate a CRI (grpc) server alone. Since we haven't merged #33988, so I tested this pr via frakti with sandbox and image APIs(since container APIs are not implemented yet). It works fine.

I will add container API tests when we merge  #33988.

**How to run cri e2e test**
```sh
cd $GOPATH/src/k8s.io/kubernetes
export CONTAINER_RUNTIME_ENDPOINT=/var/run/frakti.sock  # The socket to talk to.
make test-e2e-cri
```

Close #34040

/cc @Random-Liu @yujuhong @resouer 

Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>

2016-10-21 19:31 UTC, yujuhong commented
/cc @kubernetes/sig-node @dchen1107

2016-10-22 16:22 UTC, feiskyer commented on test/e2e/framework/framework.go
> +func NewCriFramework(baseName string, options FrameworkOptions, client *InternalApiClient) *Framework {
nit: replace `Cri` with `CRI` (also other places)

2016-10-24 04:13 UTC, xlgao-zju commented on test/e2e/framework/framework.go
> +func NewCriFramework(baseName string, options FrameworkOptions, client *InternalApiClient) *Framework {
@feiskyer updated

2016-10-24 09:46 UTC, feiskyer commented
@xlgao-zju Could this test package be installed by `go get` (e.g. `go get -u k8s.io/kuernetes/test/e2e_cri`)? This could make the validation procedure much easier for runtime maintainers.

2016-10-25 04:39 UTC, xlgao-zju commented
It can't be installed by `go get` for now. I will work on it.

2016-10-25 09:37 UTC, xlgao-zju commented
@feiskyer Updated. We can run this command to run CRI e2e test for now.
```sh
go run test/e2e_cri/runner/run.go --server-address=/var/run/frakti.sock
```
If we don't need to build dependencies, we can add this flag `--build-dependencies=false`.

2016-10-25 15:23 UTC, resouer commented on test/e2e/framework/framework.go
> +		f.Namespace = namespace
nit: extra spaces

2016-10-25 17:56 UTC, pskrzyns commented
@xlgao-zju I dont think it should close #34040 cause this missing i.e. pod tests (blocked by other PR).
I think we should use #34040 as umbrella issue for e2e CRI testing (maybe tracking implemented/unimplemented tests).

What about stopping/removing/listing sandbox/image which doesn't exist ?

2016-10-26 02:43 UTC, xlgao-zju commented on test/e2e/framework/framework.go
> +		f.Namespace = namespace
Cause this line is in the `if !f.cri{}`, so I add a tab.

2016-10-26 04:14 UTC, xlgao-zju commented
@pskrzyns Sounds reasonable. This pr only implements the framework, and it is the beginning of #34040. I will use #34040 to track other related prs in the future. And the test cases in this pr actually prove that the framework works fine. So, I will add more test cases in following prs.

2016-10-26 05:25 UTC, feiskyer commented
@xlgao-zju nit: #33988 has been in.

2016-10-26 11:24 UTC, xlgao-zju commented
@feiskyer will run this pr via dockershim and add container related test cases.

2016-10-26 20:24 UTC, yujuhong commented
@Random-Liu's #35561 will turn on grpc for dockershim by default. @xlgao-zju you should be able to test dockershim after that.

2016-10-27 13:25 UTC, xlgao-zju commented
@feiskyer @yujuhong updated.
I test this pr against dockershim, and it works fine.

2016-11-02 01:48 UTC, yujuhong commented
@xlgao-zju sorry for the delay. We've been busy trying to get the api/docker integration completed before the code freeze. This PR is a nice-to-have, but is not mandatory for 1.5. We'll try to get to this PR this week, but don't be surprised if it didn't happen.

2016-11-02 02:45 UTC, xlgao-zju commented
@yujuhong get it.

2016-11-02 07:20 UTC, feiskyer requested changes

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/container.go
> +	runtimeApi "k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime"
nit:  replace internalApi -> internalapi, runtimeApi -> runtimeapi

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/container.go
> +		Metadata: &runtimeApi.PodSandboxMetadata{Name: &podName},
CRI assumes all fields in PodSandboxMetadata are set by kubelet, maybe extract a helper for default metadata?

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/container.go
> +		Metadata: &runtimeApi.ContainerMetadata{Name: &containerName},
CRI assumes all fields in ContainerMetadata are set by kubelet, maybe extract a helper for default metadata?

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/e2e_cri_test.go
> +	more_reporters "github.com/onsi/ginkgo/reporters"
nit: rename `more_reporters` to `morereporters`, maybe just not alias instead?

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/image.go
> +func ClearAllImages(client internalApi.ImageManagerService) {
nit: rename to RemoveAllImages and only remove images related to the tests.

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/image.go
> +		imageList, err := c.ListImages(nil)
nit: Should add a filter here

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/image.go
> +		imageList, err := c.ListImages(nil)
same here, add a filter. maybe check RepoTags instead of counts?

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/pod.go
> +		Metadata: &runtimeApi.PodSandboxMetadata{
nit: set all fields of PodSandboxMetadata

2016-11-02 07:20 UTC, feiskyer commented on test/e2e_cri/runner/run.go
> +var serverAddress = flag.String("server-address", "/var/run/dockershim.sock", "CRI server address which is tested.")
should also add a image-service-address, and set it same with runtime-address if not specified.

2016-11-03 13:19 UTC, xlgao-zju commented
@feiskyer updated.

2016-11-03 17:14 UTC, pskrzyns commented on test/e2e_cri/container.go
> +		defer func() {
I think that removing sandbox should be done in AfterEach, and creation of sandbox should be in BeforeEach

2016-11-04 06:42 UTC, xlgao-zju commented on test/e2e_cri/container.go
> +		defer func() {
@pskrzyns Yes, it is clean. But it is not flexible in some test cases(maybe added in the future), such as a test case requires two pods.
I think these basic test cases about container will only require one pod. So, I will warp these cases with a 'Context()'. I will move removing sandbox into 'AfterEach', and creation of sandbox into 'BeforeEach' .

2016-11-04 17:58 UTC, pskrzyns commented
@yujuhong can we merge it to branch other than master ?
It would be nice to have it in main repo but i don't think it should be master yet.

@jayunit100 PTAL

2016-11-07 02:55 UTC, xlgao-zju commented on test/e2e_cri/container.go
> +			By("get container status")
@pskrzyns Any thing else would you like to refact, maybe I could do it in my pr directly.

2016-11-07 02:58 UTC, xlgao-zju commented
> @yujuhong can we merge it to branch other than master ?
It would be nice to have it in main repo but i don't think it should be master yet.

@pskrzyns why this pr should not be in master yet?

2016-11-07 03:51 UTC, feiskyer commented
> @yujuhong can we merge it to branch other than master ?
> It would be nice to have it in main repo but i don't think it should be master yet.

@pskrzyns Why this? We don't merge PRs to non-master branch except cherry-picks.

2016-11-07 14:27 UTC, pskrzyns commented
@xlgao-zju as this pr is for implementing framework I'm missing some test primitives/helpers, i.e. 
```go
func createPodSandbox(c internalapi.RuntimeService, prefix string ) (string, error) {
	By("create a PodSandbox with name")
	name := prefix + string(uuid.NewUUID())
	config := &runtimeapi.PodSandboxConfig{
		Metadata: buildPodSandboxMetadata(&name),
	}

	return c.RunPodSandbox(config)
}

func createPodSandboxOrFail(c internalapi.RuntimeService, prefix string ) string {
	podId, err := createPodSandbox(c, prefix)
	framework.ExpectNoError(err, "Failed to create PodSandbox: %v", err)
	framework.Logf("Created PodSandbox %s\n", podId)
	return podId
}

func getPodSandboxStatus(c internalapi.RuntimeService, podId string) (*runtimeapi.PodSandboxStatus, error) {
	By("get PodSandbox status")
	return c.PodSandboxStatus(podId)

}

func getPodSandboxStatusOrFail(c internalapi.RuntimeService, podId string) *runtimeapi.PodSandboxStatus {
	status, err := getPodSandboxStatus(c, podId)
	framework.ExpectNoError(err, "Failed to get PodSandbox %s status: %v", podId, err)
	return status
}

func verifyPodSandboxStatus(c internalapi.RuntimeService, podId string, expectedStatus *runtimeapi.PodSandboxStatus, statusName string) {
	status := getPodSandboxStatusOrFail(c, podId)
	Expect(*status.State).To(Equal(expectedStatus), "PodSandbox state should be " + statusName)
}

func testCreatePodSandbox(c internalapi.RuntimeService) string {
	podId := createPodSandboxOrFail(c, "PodSandbox-for-create-test-")
	verifyPodSandboxStatus(c, podId, runtimeapi.PodSandboxState_SANDBOX_READY, "ready")
	return podId
}

func stopPodSandbox(c internalapi.RuntimeService, podID string) (error) {
	By("stop pod PodSandbox with podId")
	return c.StopPodSandbox(podID)
}

func removePodSandbox(c internalapi.RuntimeService, podID string) (error) {
	By("remove pod PodSandbox with podId")
	return c.RemovePodSandbox(podID)
}

func stopPodSandboxOrFail(c internalapi.RuntimeService, podID string) {
	err := stopPodSandbox(c, podID)
	framework.ExpectNoError(err, "Failed to stop PodSandbox: %v", err)
	framework.Logf("Stopped PodSandbox %s\n", podID)
}

func removePodSandboxOrFail(c internalapi.RuntimeService, podID string) {
	err := removePodSandbox(c, podID)
	framework.ExpectNoError(err, "Failed to remove PodSandbox: %v", err)
	framework.Logf("Removed PodSandbox %s\n", podID)
}
```

I think they should be implemented in ```util.go``` so they can be used in both ```pod.go``` and ```container.go`` files, cause at this moment there is a lot of code duplication in those tests.
Sorry for nagging so much, but from my experience refactoring framework after people start using it is real pain in the neck.

2016-11-07 15:34 UTC, pskrzyns commented
> @pskrzyns Why this? We don't merge PRs to non-master branch except cherry-picks.

@feiskyer true, I still have some problems with differences betwen github flow and git flow ;)

2016-11-07 23:18 UTC, resouer commented
@pskrzyns I think there's misunderstand, yuju just means node team doesn't have enough bandwidth for a quick review at now. This PR is definitely still under review (and far from merge actually), so you can just start a review to post your suggestions :)

2016-11-08 13:46 UTC, xlgao-zju commented
>I think they should be implemented in util.go so they can be used in both pod.go and `container.go files, cause at this moment there is a lot of code duplication in those tests.
Sorry for nagging so much, but from my experience refactoring framework after people start using it is real pain in the neck.

@pskrzyns Thank you for your suggestions, I would like to reduce code duplication too. So I implement some functions in `util.go`, maybe its good for the following test cases :)

2016-11-15 18:55 UTC, pskrzyns commented on test/e2e_cri/pod.go
> +		pods = listPodSanboxWithIDOrFail(c, podID)
should we use ```ListPodSandbox```  or ```PodSandboxStatus``` with speciffic error to validate if pod doesn't exist ? @yujuhong

2016-11-15 18:55 UTC, pskrzyns commented on test/e2e_cri/util.go
> +// testStopPodSandbox stops the PodSandbox with podID and make sure it be not ready.
it's not

2016-11-15 18:55 UTC, pskrzyns commented on test/e2e_cri/util.go
> +
empty line

2016-11-15 18:55 UTC, pskrzyns commented on test/e2e_cri/util.go
> +	return c.StopContainer(containerID, 60)
move timeout to constant

2016-11-15 18:55 UTC, pskrzyns commented on test/e2e_cri/container.go
> +			By("test remove container")
This is one big test case, if ```By("test start container")``` fails it won't check if removing container works correctly.
It should be split to five independent test cases

2016-11-15 19:07 UTC, Random-Liu commented on test/e2e/framework/framework.go
> +	CRIClient *InternalApiClient
Why you need e2e framework for cri validation test? I think we should add another util or framework.

2016-11-15 19:07 UTC, Random-Liu commented on test/e2e/framework/test_context.go
> +	CRITestContextType
ditto, no need to change e2e framework.

2016-11-15 19:07 UTC, Random-Liu commented on test/e2e/framework/util.go
> +func loadCRIClient() (*InternalApiClient, error) {
ditto.

2016-11-16 02:53 UTC, xlgao-zju commented on test/e2e/framework/framework.go
> +	CRIClient *InternalApiClient
@Random-Liu True, CRI validation test is not associated with existing e2e test framework. So should we add another independent framework(which is specially for CRI validation test) like e2e framework? And should we put these files in `/test` or in `/kubelet`?

2016-11-16 03:00 UTC, xlgao-zju commented on test/e2e_cri/container.go
> +			By("test remove container")
@pskrzyns Thank you for your suggestions.  I will fix these in next update. :)

2016-11-16 06:56 UTC, Random-Liu commented on test/e2e/framework/framework.go
> +	CRIClient *InternalApiClient
I think put it in `test/e2e_cri` is fine. :)

2016-11-17 12:50 UTC, xlgao-zju commented
@Random-Liu updated.

2016-12-20 05:23 UTC, xlgao-zju commented on test/e2e_cri/container.go
> +			podID, podConfig = createPodSandboxForContainer(c)
@Crazykev Since we don't clean up images after testing, so we don't need to pull the image before each test case.

2016-12-20 05:43 UTC, Crazykev commented on test/e2e_cri/container.go
> +			podID, podConfig = createPodSandboxForContainer(c)
@xlgao-zju Frakti(or HyperContainer) won't pull image at container creation time, if that image doesn't exist, there will be an error, so for safety maybe we still need a pull here.

2016-12-26 19:27 UTC, jawnsy commented on test/e2e/framework/pods.go
> +// Convenient method for getting a pod client interface in the framework's namespace,
I think the previous form "[Convenience method](http://wiki.c2.com/?ConvenienceMethods)" was better, but that's just one opinion :)

2016-12-26 19:27 UTC, jawnsy commented on test/e2e/kubectl.go
> +	// Reustable cluster state function.  This won't be adversely affected by lazy initialization of framework.
Reustable -> Reusable as well

2016-12-27 06:10 UTC, xlgao-zju commented on test/e2e/framework/pods.go
> +// Convenient method for getting a pod client interface in the framework's namespace,
Will revert this.

2016-12-27 06:10 UTC, xlgao-zju commented on test/e2e/kubectl.go
> +	// Reustable cluster state function.  This won't be adversely affected by lazy initialization of framework.
ACK

2017-01-31 15:18 UTC, feiskyer commented
@xlgao-zju We should close this PR and move on to https://github.com/kubernetes-incubator/cri-tools.

2017-01-31 15:19 UTC, feiskyer commented
/close

2017-02-01 02:45 UTC, xlgao-zju commented
@feiskyer Yes, we can close this pr now.

2017-02-01 02:45 UTC, closed without merging