Proxy min sync period
kubernetes/kubernetes pull request #35334
Opened 2016-10-21 21:57 UTC by timothysc

**What this PR does / why we need it**:
Gives the proxy the option to set a lower bound on the sync period when there are a high number of endpoint changes.  This prevents excessive iptables re-writes under a number of conditions.

fixes #33693
and alleviates the symptoms of #26637

**NOTE:** 
There are other minor fixes that I'm working on but keeping the PRs separate. 

**Release note**:

```Added iptables-min-syn-period(10) to proxy to prevent excessive iptables writes```

2016-10-21 22:40 UTC, timothysc commented
I'll fix up the minor stuff in a bit.

2016-10-24 13:27 UTC, timothysc commented
ug, the splitting of component config + go client is a mess.

2016-10-24 18:48 UTC, thockin requested changes

2016-10-24 18:48 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +	if expired := time.Since(proxier.lastSync); expired > proxier.minsyncPeriod {
This isn't right.  If I am 10ms short of being able to refresh, I now have to wait for another event or for the longer sync-period.  Don't you want a timer to wake up in `proxier.minsyncPeriod - expired` ?

2016-10-24 18:48 UTC, thockin commented on pkg/proxy/userspace/proxier.go
> +	minsyncPeriod  time.Duration
s/minsync/minSync/

2016-10-24 21:49 UTC, timothysc commented
@thockin comments addressed, rebased, tests now passing.

2016-10-24 22:07 UTC, thockin commented on cmd/kube-proxy/app/options/options.go
> +	fs.DurationVar(&s.IPTablesMinSyncPeriod.Duration, "iptables-min-sync-period", s.IPTablesMinSyncPeriod.Duration, "The minimum interval of how often the iptables rules can be refreshed as endpoints an
What if this is > iptables-sync-period?  Comment should say it can';t be and should be validated

2016-10-24 22:12 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +		proxier.timer.Reset(proxier.syncPeriod)
comments say `proxier.timer` is mutex protected.  This doesn't take the mutex.

2016-10-24 22:14 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +		glog.V(4).Infof("Service update resetting synch period %v", remaining)
s/synch/sync

2016-10-24 22:21 UTC, thockin commented
Here's what is going to happen.  A Service update (create) will arrive.  We sync it.  Then an Endpoints update will arrive very soon thereafter.  It will get stuck behind this delay.  In practice, this adds at least 2 seconds to every Service creation.  More if anyone tweaks that flag.  Maybe not a huge deal, but worth thinking about.  Can we do better?

We could do a semaphore thing and start with something like 3 tokens.  Add a new token every interval up to max 3.  This would give low-load systems enough freedom to enact changes right away and would bandwidth-limit high-load systems.

I'm just spitballing here...

2016-10-25 02:09 UTC, timothysc commented
> It will get stuck behind this delay. In practice, this adds at least 2 seconds to every Service creation. More if anyone tweaks that flag. Maybe not a huge deal, but worth thinking about. Can we do better?

It will add 2 seconds to the last service, not every, as they will be batched, but I'm not terribly concerned about that.  I'm far more concerned about controlling the thrashing at this point, and this puts an simple control knob on that. 

> We could do a semaphore thing and start with something like 3 tokens. Add a new token every interval up to max 3. This would give low-load systems enough freedom to enact changes right away and would bandwidth-limit high-load systems.

I'd like to profile before adding any more complexity.  For us, the largest concern is the high amount of churn on large clusters, not the update-SLO on endpoints.  In profiling, the longest delay is typically on the docker pull which is orders of magnitude greater the this delay.  So keeping it simple makes the most sense, unless there is a use case that I'm missing.?.?

2016-10-25 02:19 UTC, timothysc commented on cmd/kube-proxy/app/options/options.go
> +	fs.DurationVar(&s.IPTablesMinSyncPeriod.Duration, "iptables-min-sync-period", s.IPTablesMinSyncPeriod.Duration, "The minimum interval of how often the iptables rules can be refreshed as endpoints an
Error + sane default, or fatal? 

I always wax and wain on that.

2016-10-25 02:25 UTC, timothysc commented on pkg/proxy/userspace/proxier.go
> +		minSyncPeriod:  minSyncPeriod,
plumbed if needed, but I should probably commend to denote.

2016-10-25 02:31 UTC, timothysc commented on cmd/kube-proxy/app/options/options.go
> +	fs.DurationVar(&s.IPTablesMinSyncPeriod.Duration, "iptables-min-sync-period", s.IPTablesMinSyncPeriod.Duration, "The minimum interval of how often the iptables rules can be refreshed as endpoints an
Added logic check.

2016-10-25 02:31 UTC, timothysc commented on pkg/proxy/iptables/proxier.go
> +		proxier.timer.Reset(proxier.syncPeriod)
fixed.

2016-10-25 02:31 UTC, timothysc commented on pkg/proxy/iptables/proxier.go
> +		glog.V(4).Infof("Service update resetting synch period %v", remaining)
derp.

2016-10-25 15:11 UTC, thockin commented
>> It will get stuck behind this delay. In practice, this adds at least 2 seconds to every Service creation. More if anyone tweaks that flag. Maybe not a huge deal, but worth thinking about. Can we do better?

>It will add 2 seconds to the last service, not every, as they will be batched, but I'm not terribly concerned about that. I'm far more concerned about controlling the thrashing at this point, and this puts an simple control knob on that.

Maybe I am misunderstanding the flow.  The Service create will trigger OnServiceUpdate(), which will sync.  That sets the timestamp.  10ms later, the Endpoints update will trigger OnEndpointsUpdate(), which will set a timer for 1990 ms later.  If the normal pattern is these two operations being highly temporally coupled, it seems we should design for that case, no?

2016-10-25 15:40 UTC, timothysc commented
> 10ms later, the Endpoints update will trigger OnEndpointsUpdate(), which will set a timer for 1990 ms later. If the normal pattern is these two operations being highly temporally coupled, it seems we should design for that case, no?

In a slow churn single operator environment, perhaps.  
Ours is a high-churn, dense, multi-tenant environment, and tuning for that case doesn't make a lot of sense.  Because within that window there are literally be 100s or 1000s of updates.  As daniel points out here: https://github.com/kubernetes/kubernetes/issues/26637#issuecomment-253013758

2016-10-25 16:59 UTC, dcbw commented
@timothysc @thockin I did a patch yesterday to cut down on non-important Service/Endpoint changes, which does seem to reduce the need for resyncs somewhat.  I'm currently looking into how to do an iptables diff to figure out if we really need to resync for the periodic loop, but that's a lot harder as Kube doesn't write rules in the same way as iptables-save reads them back, so we effectively have to create an iptables-save rule parser.

I know Tim said at one point that "by the time we get to iptables-restore the work is all pretty much done", but that's not the case.  The Go side is fine, but it's the kernel contention of iptables-restore that is the problem for most of our customers.  When I benchmarked with 4.7 kernels and 6 or 8000 iptables rules, I was getting hundreds of ms runtime for a single iptables-restore.  The Go-side time for generating those rules was incidental.  So I think we can get some good mileage from simply not calling iptables-restore when we don't need to.

2016-10-25 17:05 UTC, timothysc commented
It's far worse then what simple benchmarks show on large loaded environments: https://bugzilla.redhat.com/show_bug.cgi?id=1387149 . 

We literally have about 6-7 BZ's all pointing to the same thing.

2016-10-25 18:28 UTC, thockin commented
That's why I proposed something that would allow both cases.

On Tue, Oct 25, 2016 at 8:41 AM, Timothy St. Clair <notifications@github.com
> wrote:

> 10ms later, the Endpoints update will trigger OnEndpointsUpdate(), which
> will set a timer for 1990 ms later. If the normal pattern is these two
> operations being highly temporally coupled, it seems we should design for
> that case, no?
>
> In a slow churn single operator environment, perhaps.
>
> Ours is a high-churn, dense, multi-tenant environment, and tuning for that
> case doesn't make a lot of sense. Because within that window there are
> literally be 100s or 1000s of updates. As daniel points out here: #26637
> (comment)
> <https://github.com/kubernetes/kubernetes/issues/26637#issuecomment-253013758>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35334#issuecomment-256073053>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVKEkf736d7Gx6xPCUVMYJP0XOfs3ks5q3iMSgaJpZM4KdoNR>
> .
>

2016-10-25 21:56 UTC, thockin commented
Could this be a kernel regression?  On my older Debian (3.something kernel)
I could save/restore 10s of thousands of rules in 120 ms every time,
usually more like 80ms.

Can someone send me an iptables-save dump that they claim takes > 200 ms to
restore?

On Tue, Oct 25, 2016 at 10:00 AM, Dan Williams <notifications@github.com>
wrote:

> @timothysc <https://github.com/timothysc> @thockin
> <https://github.com/thockin> I did a patch yesterday to cut down on
> non-important Service/Endpoint changes, which does seem to reduce the need
> for resyncs somewhat. I'm currently looking into how to do an iptables diff
> to figure out if we really need to resync for the periodic loop, but that's
> a lot harder as Kube doesn't write rules in the same way as iptables-save
> reads them back, so we effectively have to create an iptables-save rule
> parser.
>
> I know Tim said at one point that "by the time we get to iptables-restore
> the work is all pretty much done", but that's not the case. The Go side is
> fine, but it's the kernel contention of iptables-restore that is the
> problem for most of our customers. When I benchmarked with 4.7 kernels and
> 6 or 8000 iptables rules, I was getting hundreds of ms runtime for a single
> iptables-restore. The Go-side time for generating those rules was
> incidental. So I think we can get some good mileage from simply not calling
> iptables-restore when we don't need to.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35334#issuecomment-256095573>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVJXJZbGBIoyZTPQKcnWflRiSKtlAks5q3jWigaJpZM4KdoNR>
> .
>

2016-10-27 15:37 UTC, timothysc commented
@thockin signaling with a channel full+backoff would only cause a back-off once iptables completely saturates between signals, meaning you can still call it excessively.  

I'd much prefer to default to something smaller for the common use case say (1) or even .5s.

2016-10-27 15:41 UTC, timothysc commented
We "could" use the token binning similar to qps, but that seems like overkill.

2016-10-31 19:46 UTC, thockin commented
It's not the same as decreasing the period for the average case (he says without any real data).  The average case will process 2 updates in sequence, until/unless we fix that.  This means I can actually set a default holdoff period of O(seconds) and still not impact the experience for most clusters.

A channel of 2, serving as a semaphore, plus a short goroutine loop around Tick().  You still only need one param - the period.  If we assume the channel is fixed at 2, the tick is period/2.

2016-10-31 20:02 UTC, timothysc commented
> It's not the same as decreasing the period for the average case (he says without any real data). The average case will process 2 updates in sequence, until/unless we fix that. This means I can actually set a default holdoff period of O(seconds) and still not impact the experience for most clusters. 

k, at point where min-period >1 I'd probably agree.  <=1 (which it is now) I think we're splitting hairs on undefined SLOs, but I don't care enough to make a argument either way.  I'll simply make a 2 token update at this point.

2016-10-31 20:06 UTC, thockin commented
Thanks.  I hate to be a PITA.  I think a 2-second window seems like a good
idea, so we can have sane defaults.

On Mon, Oct 31, 2016 at 9:02 PM, Timothy St. Clair <notifications@github.com
> wrote:

> It's not the same as decreasing the period for the average case (he says
> without any real data). The average case will process 2 updates in
> sequence, until/unless we fix that. This means I can actually set a default
> holdoff period of O(seconds) and still not impact the experience for most
> clusters.
>
> k, at point where min-period >1 I'd probably agree. <=1 (which it is now)
> I think we're splitting hairs on undefined SLOs, but I don't care enough to
> make a argument either way. I'll simply make a 2 token update at this
> point.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35334#issuecomment-257404070>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVI0BcI6lAcD--iLG6slNUbRV_Dofks5q5klogaJpZM4KdoNR>
> .
>

2016-11-03 11:24 UTC, bogdando commented on pkg/proxy/iptables/proxier.go
> +	// check valid user input
As you do divide by the minSyncPeriod, please add a check for a zero value to return an error.

2016-11-03 11:28 UTC, bogdando commented
LGTM, but a minor issue with the inputs checking. I vote to add that knob first, for those ops folks, then think on design changes.

2016-11-03 13:56 UTC, timothysc commented on pkg/proxy/iptables/proxier.go
> +	if proxier.throttle != nil && !proxier.throttle.TryAccept() {
@thockin - Only question is if we should block on Accept() or put back in the timer adjustment jiggery?

2016-11-03 14:33 UTC, timothysc commented on pkg/proxy/iptables/proxier.go
> +	// check valid user input
Done.

2016-11-03 16:38 UTC, timothysc commented
@thockin updated, PTAL.

2016-11-04 04:35 UTC, thockin approved these changes
LGTM, comment request, but you can race the bot

2016-11-04 04:35 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +	if minSyncPeriod == 0 || minSyncPeriod > syncPeriod {
I'm curious why min == 0 is disallowed - the semantic seems to be "no rate limit".  It's not important, but curious.  Just to avoid div-by-zero ?

2016-11-04 04:35 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +		throttle:       flowcontrol.NewTokenBucketRateLimiter(syncsPerSecond, 2),
comment on the literal `2`?

2016-11-04 13:23 UTC, timothysc commented on pkg/proxy/iptables/proxier.go
> +	if minSyncPeriod == 0 || minSyncPeriod > syncPeriod {
div-by-zero.

2016-11-04 21:06 UTC, merged

2016-11-05 06:46 UTC, wojtek-t commented
@k8s-oncall @thockin @timothysc - it seems that this PR broke gke-slow suite (it's mostly red since then and nothing is merging)

2016-11-05 07:16 UTC, wojtek-t commented
@saad-ali ^^

2016-11-05 08:05 UTC, saad-ali commented
@bprashanth I merged your PR https://github.com/kubernetes/kubernetes/pull/36282. Does this need to be reverted as well?

2016-11-05 08:28 UTC, wojtek-t commented
@saad-ali - I didn't see that PR, maybe that one actually fix the problem.

2016-11-05 20:20 UTC, timothysc commented
Looks like #36282 just needs a timing shift, which makes sense, but I'm wondering how the assortment of other suites didn't catch this?

2016-11-05 20:50 UTC, bprashanth commented
It's still very likely this broke slow suite. My pr was supposed to be a short term mitigation till we've had a chance to debug https://github.com/kubernetes/kubernetes/issues/36281 (suite is still flaking), @MrHohn

2016-11-05 21:42 UTC, saad-ali commented
Yes, looks like PR #36282 took care of it.  https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke-slow/ has been green since.

2016-11-05 21:45 UTC, bprashanth commented
are you sure? akf right now but last I checked it flaked this morning and the pr went in last night. I just don't want to cry wolf without evidence :)

2016-11-05 22:24 UTC, saad-ali commented
There are multiple slow suites, the one I looked at, [kubernetes-e2e-gci-gke-slow](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke-slow/), has been green since PR #36282 went in at 12:37 AM PDT. Same with [kubernetes-e2e-gce-slow](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow). However, [kubernetes-e2e-gke-slow](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow) failed as recently as 2016-11-05 1:23 PM PDT.  So it's possible PR #36282 just reduced the frequency of failure, but need a smoking gun to revert this PR.

2016-11-06 02:27 UTC, bprashanth commented
Did I just forget to read time? I see 8 flakes since 12:30 AM last night. 
This pr is surely contributing to the janky performance observed in https://github.com/kubernetes/kubernetes/issues/36281

Because of the way kubeproxy is structured, we're inserting a token into the bucket every 2 seconds for the iptables update, and sending a no-op update down the watch every second (2 every 2 seconds, scheduler and kube-controller-manager). So we end up filling the queue with no-op endpoint updates and blocking an interesting service update. 

@timothysc if you're interested in doing this right you should look at the watch processing pipeline. This pr calls Accept() holding the syncProxyRules lock (https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L782, https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L422), which is effective a time.Sleep(1 or 2 seconds) given what I described above.  The on update functions receive a snapshot of endpoints/services on *every* update. Meaning: 
```
t:1 (bucket empty)
no-op update
no-op snapshot
lock
accept () <- sleep(2)

next no-op update
next no-op snapshot
lock <- block

svc update
svc snapshot
lock <- block

t:3 (bucket has a token)
t:1 process no-op snapshot
next no-op update
next no-op snapshot
lock <- block
```

this can essentially go on forever just processing no-op updates from the endpoint handler because go's locks aren't fair. Note that the "burst" will only help if you actually get 0 updates for a while such that you accumulate enough tokens. 

What we were doing previous is also bad, but the no-op updates would run asap leaving the channel empty for more important updates. 

I will probably send a pr to default it to the old behavior soonish. We can fix this as a bug during code freeze.

2016-11-06 02:27 UTC, bprashanth commented
Ah, @MrHohn has empirical evidence https://github.com/kubernetes/kubernetes/issues/36281#issuecomment-258656079