Let release_1_5 clientset include multiple versions of a group
kubernetes/kubernetes pull request #35471
Opened 2016-10-24 23:25 UTC by caesarxuchao

Fix #35237 

This PR make versioned clientset to include multiple versions of a group. Currently only `batch` has `v1` and `v2alpha1`. The clientset interface now looks like:
```go
	BatchV2alpha1() v2alpha1batch.BatchV2alpha1Interface
	BatchV1() v1batch.BatchV1Interface
	// Deprecated: please explicitly pick a version if possible.
	Batch() v1batch.BatchV1Interface
```

Commit "update client-gen to say internalversion rather than unversioned" fixes https://github.com/kubernetes/kubernetes/issues/24481. 

cc @kubernetes/sig-api-machinery @soltysh @deads2k

2016-10-26 15:16 UTC, soltysh requested changes
Some comments. Additionally the deprecation part could squashed into the main parts where the codegen is changed.

2016-10-26 15:16 UTC, soltysh commented on cmd/libs/go2idl/client-gen/types/helpers_test.go
> +	expected := []string{"v2alpha1", "v2beta1", "v4beta1", "v1", "v3"}
The order here doesn't seem to be correct. I'd expect following:
```
{"v1", "v2alpha1", "v2beta1", "v4beta1", "v3"}
```

2016-10-26 15:16 UTC, soltysh commented on test/e2e/generated_clientset.go
> +func observeJobCreation(w watch.Interface) {
observeScheduledJobCreation

2016-10-26 15:16 UTC, soltysh commented on test/e2e/generated_clientset.go
> +func observeJobCreation(w watch.Interface) {
OT: instead of having multiple observe* why not having single generic function doing this, especially you're using `watch.Interface` as an argument.

2016-10-26 22:40 UTC, mml commented on test/e2e/generated_clientset.go
> +	It("should create v2alpha1 scheduleJobs, delete scheduleJobs, watch scheduleJobs", func() {
This is a good specific test to watch for regression in the 1.5 clientset.  Nice job.

A more general test of this functionality would be good eventually, but seems like a big project.

2016-10-26 22:40 UTC, mml commented
LGTM once you address soltysh changes.

2016-10-26 22:46 UTC, caesarxuchao commented on cmd/libs/go2idl/client-gen/types/helpers_test.go
> +	expected := []string{"v2alpha1", "v2beta1", "v4beta1", "v1", "v3"}
I'd like to keep the default referring to a stable version. (e.g., .Batch() returns v1, not v2alpha1, which is behavior before this change)

2016-10-26 22:50 UTC, caesarxuchao commented on test/e2e/generated_clientset.go
> +func observeJobCreation(w watch.Interface) {
Ack.

2016-10-27 16:49 UTC, caesarxuchao commented on cmd/libs/go2idl/client-gen/types/helpers_test.go
> +	expected := []string{"v2alpha1", "v2beta1", "v4beta1", "v1", "v3"}
@soltysh do you think it's reasonable?

2016-10-27 20:43 UTC, soltysh commented on cmd/libs/go2idl/client-gen/types/helpers_test.go
> +	expected := []string{"v2alpha1", "v2beta1", "v4beta1", "v1", "v3"}
Discussed on slack - ok.

2016-10-27 22:37 UTC, caesarxuchao commented on test/e2e/generated_clientset.go
> +func observeJobCreation(w watch.Interface) {
Done. Combined the functions.

2016-10-27 22:38 UTC, caesarxuchao commented
Squashed and addressed the comments. Self apply the lgtm. Thank you for the quick review for a monster PR.

2016-10-27 23:49 UTC, liggitt commented
I thought this was intended to drop after code freeze. This seems enormously disruptive for things working toward code freeze.

2016-10-27 23:59 UTC, caesarxuchao commented
@liggitt client-go currently passively copy the contents from the main repo, we don't develop in client-go. I need this PR to go in so that during code freeze I can have a client-go that's in the right shape for the migration.

By "disruptive" do you mean it will cause people to rebase? It shouldn't. I keep the original method like "Batch()", which returns the same interface as it used to do.

2016-10-28 00:26 UTC, caesarxuchao commented
@k8s-bot node e2e test this

2016-10-28 04:15 UTC, caesarxuchao commented
Rebased due to a PR renamed petset. REapply the lgtm.

2016-10-28 04:26 UTC, smarterclayton commented on pkg/client/clientset_generated/internalclientset/typed/batch/internalversion/scheduledjob.go
> +func newScheduledJobs(c *BatchInternalversionClient, namespace string) *scheduledJobs {
InternalVersionClient

2016-10-28 04:27 UTC, liggitt commented on pkg/client/clientset_generated/internalclientset/typed/batch/internalversion/scheduledjob.go
> +func newScheduledJobs(c *BatchInternalversionClient, namespace string) *scheduledJobs {
why not leave the internal one unqualified?

2016-10-28 04:27 UTC, smarterclayton commented
Several `FooInternalversion` fields showing up, should be `FooInternalVersion`

2016-10-28 04:28 UTC, liggitt commented
> By "disruptive" do you mean it will cause people to rebase? 

I mean the package, type, and field name changes

2016-10-28 04:28 UTC, smarterclayton commented
One naming thing - removed label.

2016-10-28 04:31 UTC, caesarxuchao commented on pkg/client/clientset_generated/internalclientset/typed/batch/internalversion/scheduledjob.go
> +func newScheduledJobs(c *BatchInternalversionClient, namespace string) *scheduledJobs {
Thanks. Will fix.

2016-10-28 04:35 UTC, caesarxuchao commented
@liggitt the changes that will bother other developers is changing "unversioned" to "internalversion", but the conflicts will be easy to solve.

2016-10-28 04:38 UTC, smarterclayton commented
InternalVersion is 100x better than unversioned.

2016-10-28 08:06 UTC, caesarxuchao commented on pkg/client/clientset_generated/internalclientset/typed/batch/internalversion/scheduledjob.go
> +func newScheduledJobs(c *BatchInternalversionClient, namespace string) *scheduledJobs {
@liggitt I finally made a local commit that kept the internal one unqualified. It made the client-gen code difficult to read. Given that not many callers need to refer to the these types, and we are going to migrate to using versioned client, can you live with the long name?

2016-10-28 08:07 UTC, caesarxuchao commented on pkg/client/clientset_generated/internalclientset/typed/batch/internalversion/scheduledjob.go
> +func newScheduledJobs(c *BatchInternalversionClient, namespace string) *scheduledJobs {
Fixed the CamelCase.

2016-10-28 13:18 UTC, liggitt commented on cmd/kube-controller-manager/app/controllermanager.go
> +				CoreInternalVersionClient: kubeClient.Core(),
keep the field name `CoreClient`?

2016-10-28 13:20 UTC, liggitt commented
yeah, the changes were smaller than I thought at first glance. I would keep field names the same though (e.g. https://github.com/kubernetes/kubernetes/pull/35471#discussion_r85527947)

2016-10-28 19:22 UTC, caesarxuchao commented
@liggitt Done, field name/method name are changed back for internalversion clientset.

I also took this chance to cleanup the logic that translates empty APIVersion in client-gen. The code should be easier to maintain now.

2016-10-28 19:52 UTC, mml commented
Are we planning to change those names after 1.5?

2016-10-28 20:16 UTC, caesarxuchao commented
No, internalversion clientset will stay like this.

2016-10-28 20:46 UTC, caesarxuchao commented
@k8s-bot node e2e test this

2016-10-28 20:54 UTC, mml commented
Still LGTM with changes.

2016-10-28 21:29 UTC, caesarxuchao commented
Thanks for the reviews. Applying the lgtm label.

2016-10-29 05:48 UTC, caesarxuchao commented
test/test_owners.csv causes rebase. This file is causing too many rebases.

2016-10-29 18:55 UTC, fejta commented
BTW Given the scope of this PR I recommend you consider bumping up the priority.

2016-10-29 19:13 UTC, caesarxuchao commented
I'll add the milestone. The PR shouldn't cause many conflicts. Most changes are import lines.

2016-10-29 19:48 UTC, caesarxuchao commented
@k8s-bot node e2e test this

2016-10-29 20:25 UTC, caesarxuchao commented
@k8s-bot node e2e test this, issue #34990

2016-10-29 20:31 UTC, caesarxuchao commented
Got conflict in test_owners.csv again. This is too much. I'm bumping the priority.

2016-10-29 22:17 UTC, caesarxuchao commented
@k8s-bot node e2e test this

2016-10-29 22:40 UTC, merged

2016-10-29 23:42 UTC, caesarxuchao commented
ScheduleJob is not enabled on gke. So gke tests are failing now. I'll send a fix soon.

2016-10-29 23:59 UTC, caesarxuchao commented
Sent #35855.