specify custom ca file to verify the keystone server
kubernetes/kubernetes pull request #35488
Opened 2016-10-25 03:33 UTC by dixudx

**What this PR does / why we need it**:

Sometimes the keystone server's certificate is self-signed, mainly used for internal development, testing and etc.

For this kind of ca, we need a way to verify the keystone server.

Otherwise, below error will occur.

> x509: certificate signed by unknown authority

This patch provide a way to pass in a ca file to verify the keystone server when starting `kube-apiserver`.

**Which issue this PR fixes** : fixes #22695, #24984

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2016-10-25 03:39 UTC, liggitt commented on pkg/genericapiserver/options/server_run_options.go
> +	fs.StringVar(&s.KeystoneCAFile, "experimental-keystone-ca-file", s.KeystoneCAFile, ""+
Use the OIDCCAFile flag description as a starting point instead

2016-10-25 03:55 UTC, liggitt requested changes

2016-10-25 03:55 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
Load the cert pool from the given file here if cafile is set, rather than loading it for every request

2016-10-25 03:55 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	config := &tls.Config{}
Skip this whole block if the capool is nil?

2016-10-25 03:55 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +
`return openstack.Authenticate(…)`

2016-10-25 03:55 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	client.HTTPClient.Transport = &http.Transport{TLSClientConfig: config, }
Needs gofmt

2016-10-25 03:55 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	client.HTTPClient.Transport = &http.Transport{TLSClientConfig: config, }
is this equivalent to the transport set up by default by `openstack.AuthenticatedClient` (with respect to proxy settings, dial settings, timeouts, etc)?

2016-10-25 05:26 UTC, dixudx commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	client.HTTPClient.Transport = &http.Transport{TLSClientConfig: config, }
The client created by default `openstack.AuthenticatedClient` is `*gophercloud.ProviderClient`.

```
	return &gophercloud.ProviderClient{
		IdentityBase:     base,
		IdentityEndpoint: "",
	}, nil
```

The default `HTTPClient.Transport` is `nil`, and `DefaultTransport` is used instead.

```
var DefaultTransport RoundTripper = &Transport{
	Proxy: ProxyFromEnvironment,
	Dial: (&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
	}).Dial,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}
``` 

The `client.HTTPClient.Transport` I used here is quite a new `Transport` with only `TLSClientConfig ` configured.

Do you suggest that we should merge these two together ?

2016-10-25 05:26 UTC, dixudx commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	config := &tls.Config{}
`certutil.NewPool` will return an error if the file could not be read, a certificate could not be parsed, or if the file does not contain any certificates.

So I think it is okay to remain the codes here unchanged.

2016-10-25 05:26 UTC, dixudx commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +
I did not get the actual use of this return.

2016-10-25 06:48 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	config := &tls.Config{}
I mean, leave `client.HTTPClient.Transport` untouched unless we want to customize the ca pool

2016-10-25 06:49 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	client.HTTPClient.Transport = &http.Transport{TLSClientConfig: config, }
`util/net#SetOldTransportDefaults(&http.Transport{TLSClientConfig: config})` will set the default dialer, proxy, and timeouts

2016-10-25 06:50 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +
the function already returns `client, err`, so just return the result directly, instead of `if err != nil ...`

2016-11-03 07:23 UTC, dixudx commented on pkg/genericapiserver/options/server_run_options.go
> +	fs.StringVar(&s.KeystoneCAFile, "experimental-keystone-ca-file", s.KeystoneCAFile, ""+
Already fix this.

2016-11-03 14:17 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	if keystoneAuthenticator.caFile != "" {
```
if keystoneAuthenticator.transport != nil {
  client.HTTPClient.Transport = keystoneAuthenticator.transport
}
```

2016-11-03 15:09 UTC, liggitt requested changes
squash and rebase as well

2016-11-03 15:09 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +	transport *http.Transport
`http.RoundTripper`

2016-11-03 15:09 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +		client.HTTPClient.Transport = netutil.SetOldTransportDefaults(keystoneAuthenticator.transport)
`client.HTTPClient.Transport = keystoneAuthenticator.transport`

2016-11-03 15:09 UTC, liggitt commented on plugin/pkg/auth/authenticator/password/keystone/keystone.go
> +		transport := &http.Transport{TLSClientConfig: config}
`netutil.SetOldTransportDefaults(&http.Transport{TLSClientConfig: config})`

2016-11-03 15:27 UTC, liggitt approved these changes

2016-11-03 15:28 UTC, liggitt commented
LGTM, did you test it against your keystone install (since we don't have e2e's for this yet)?

also, can you open a doc PR to http://kubernetes.io/docs/admin/authentication/ to describe the new flag?

2016-11-03 15:34 UTC, dixudx commented
@liggitt Yeah, I've already tested this patch on my local env.

Will submit another PR to clarify this new flag.

Thanks so much.

2016-11-03 16:10 UTC, dixudx commented on hack/verify-flags/known-flags.txt
> +experimental-mounter-rootfs-path
I don't know where it comes from. Seems rebase from previous commits. I did not add this. Quite weird.

Already removed this. Fixed.

2016-11-03 16:15 UTC, liggitt commented
also needs 
```
I1103 08:44:17.892] Run ./hack/update-bazel.sh
I1103 08:44:17.893] FAILED   hack/make-rules/../../hack/verify-bazel.sh	22s
```

2016-11-03 16:52 UTC, dixudx commented
@k8s-bot verify test this

2016-11-04 02:18 UTC, dixudx commented
@k8s-bot verify test this

2016-11-04 07:55 UTC, dixudx commented
Hi @liggitt I retest this patch on my local env. All works well. 

And the corresponding doc PR has also been submitted.

Need lgtm label again. Thanks.

2016-11-08 05:55 UTC, saad-ali commented
Release-czar approved post-code freeze merge--This was LGTMed and in the merge-queue at code freeze time for 1.5. Adding 1.5 milestone to let it gets merged after code freeze.

2016-11-08 21:13 UTC, merged