Fix migration script
kubernetes/kubernetes pull request #35503
Opened 2016-10-25 08:22 UTC by wojtek-t

Ref #22448

There is no bash in etcd image, so the script needs to be "sh-friendly".

Also, few fixes to the script.

2016-10-26 06:33 UTC, wojtek-t commented
@mml - friendly ping

2016-10-26 21:21 UTC, mml requested changes
LG once you add a comment.

I would like to restructure this loop into two shell functions to improve readability, but it's a minor detail and I'll send you a PR after this merges.

2016-10-26 21:21 UTC, mml commented on cluster/images/etcd/migrate-if-needed.sh
> +SKIP_STEP=true
Can you add a comment explaining the logic here?  I think it goes like this:  by default, we skip "start then stop etcd" for all versions.  We don't start doing the "start then stop etcd" section until we're one step *past* the current version.

2016-10-27 08:18 UTC, wojtek-t commented on cluster/images/etcd/migrate-if-needed.sh
> +SKIP_STEP=true
Yes - this is exactly how you wrote added a comment.

2016-10-27 09:12 UTC, wojtek-t commented
Adding label based on comment above.

2016-10-27 09:59 UTC, merged