add script to check for updates to the files for generation
kubernetes/kubernetes pull request #35648
Opened 2016-10-26 20:29 UTC by deads2k

Adds a verify script to help people writing APIs remember to wire all the individual pieces up.  Eventually it will be better to avoid this altogether, but this is a start.

@ncdc fyi

2016-10-27 12:57 UTC, deads2k commented
switching to @eparis since Daniel is out.

2016-10-27 16:59 UTC, deads2k commented on pkg/apis/abac/register.go
> +	scheme.AddKnownTypes(SchemeGroupVersion,
This is how we've done it all register files since this list can get pretty long.

2016-10-27 16:59 UTC, deads2k commented on hack/verify-api-groups.sh
> +			if [ ${group_without_codegen} == ${group_dirname} ]; then
Ok, but what's the difference?

2016-10-27 17:07 UTC, deads2k commented
comments addressed

2016-10-27 19:48 UTC, deads2k commented
@eparis must have accidentally closed this.  Reopened because I'd still like it.

2016-11-01 12:50 UTC, deads2k commented
@ncdc this will help people trying to introduce new API groups.

2016-11-01 16:59 UTC, ncdc commented
I think you probably want @stevekuznetsov to review the bash

2016-11-01 17:28 UTC, stevekuznetsov requested changes
Many missing quotes. Mostly reasonable.

2016-11-01 17:28 UTC, stevekuznetsov commented on hack/lib/init.sh
> + abac.authorization.kubernetes.io/v0 \
You don't need the ending `\` unless you want the string to not contain newlines

2016-11-01 17:28 UTC, stevekuznetsov commented on hack/verify-api-groups.sh
> +	package=${register_file#${prefix}}
You went through all the effort in your `find` step to handle whitespace in file names, but it is lost if you don't quote things after that:
```sh
package="${register_file#"${prefix}"}"
        ^                ^         ^ ^
```

2016-11-01 17:28 UTC, stevekuznetsov commented on hack/verify-api-groups.sh
> +	if ( $(grep -q "GroupName = \"" "${register_file}") ); then
```sh
if grep -q 'GroupName = "' "${register_file}"; then
```

2016-11-01 17:28 UTC, stevekuznetsov commented on hack/verify-api-groups.sh
> +	if ( $(grep -q "GroupName = \"" "${register_file}") ); then
If you're going to use the output later you can also do
```sh
if group_name="$( grep -q 'GroupName = "' "${register_file}" )"; then
```

2016-11-01 17:28 UTC, stevekuznetsov commented on hack/verify-api-groups.sh
> +		echo "${register_file} is missing \"const GroupName =\""
mismatch between error message and what you are searching for

2016-11-01 17:28 UTC, stevekuznetsov commented on hack/verify-api-groups.sh
> +		fi
broken indenting

2016-11-01 19:20 UTC, stevekuznetsov commented on hack/lib/init.sh
> + abac.authorization.kubernetes.io/v0 \
That is surprising, why do you have that requirement?

2016-11-01 19:21 UTC, deads2k commented on hack/verify-api-groups.sh
> +		echo "${register_file} is missing \"const GroupName =\""
> mismatch between error message and what you are searching for

It's a statement of desire.  They aren't all like that yet.

2016-11-01 20:00 UTC, deads2k commented
quotes added.

2016-11-02 11:46 UTC, deads2k commented
@k8s-bot verify test this

build never finished.

2016-11-02 11:47 UTC, deads2k commented
@k8s-bot verify test this

2016-11-04 08:16 UTC, merged