Rename PetSet to StatefulSet in docs and examples.
kubernetes/kubernetes pull request #35776
Opened 2016-10-28 09:20 UTC by jimmycuadra

**What this PR does / why we need it**: Addresses some of the pre-code-freeze changes for implementing the PetSet --> StatefulSet rename.

**Special notes for your reviewer**: This PR only changes docs and examples, as #35731 hasn't been merged yet and I don't want to create merge conflicts. I'll open another PR for any remaining code changes needed after that PR is merged. /cc @erictune @janetkuo @chrislovecnm

2016-10-28 17:38 UTC, janetkuo requested changes

2016-10-28 17:38 UTC, janetkuo commented on examples/cockroachdb/cockroachdb-statefulset.yaml
> +  # can resolve # each other's IP addresses. It does not create a load-balanced ClusterIP and
remove redundant #

2016-10-28 17:38 UTC, janetkuo commented on examples/cockroachdb/cockroachdb-statefulset.yaml
> +  # should not be used # directly by clients in most circumstances.
remove #

2016-10-28 17:38 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +  - [Step 2: Use a StatefulSet to create Cassandra Ring](#step-2-create-a-cassandra-statefulset)
The link should be `#step-2-use-a-statefulset-to-create-cassandra-ring`

2016-10-28 17:38 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +- [_StatefulSets_](http://kubernetes.io/docs/user-guide/statefulset/)
We don't have `http://kubernetes.io/docs/user-guide/statefulset/` yet. To do this we need to rename the file in the docs repo and redirect http://kubernetes.io/docs/user-guide/petset/ to http://kubernetes.io/docs/user-guide/statefulset/ 

We can leave this link as-is for now

2016-10-28 17:38 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +scope of this documentation.  [Please refer to the StatefulSet documentation.](http://kubernetes.io/docs/user-guide/statefulset/)
same here wrt the url

2016-10-28 17:38 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +There are some limitations with the Alpha release of StatefulSet in 1.3. From the [documentation](http://kubernetes.io/docs/user-guide/statefulset/):
ditto

2016-10-28 17:38 UTC, janetkuo commented on hack/make-rules/test-cmd.sh
> +  kubectl create -f hack/testdata/nginx-statefulset.yaml "${kube_flags[@]}"
I guess you forgot to commit hack/testdata/nginx-statefulset.yaml?

2016-10-28 17:40 UTC, janetkuo commented
@jimmycuadra thanks for the work! I have a few comments. Please address them in a separate commit so that it's easier to review changes. Then you can squash commits after it's ready to be merged.

2016-10-28 17:44 UTC, janetkuo commented
cc @kow3ns

2016-10-28 17:46 UTC, janetkuo commented
@k8s-bot ok to test

2016-10-28 18:06 UTC, kow3ns commented on examples/storage/cassandra/README.md
> +For the Alpha release of Kubernetes 1.3 the StatefulSet resource does not have `kubectl scale`
Should this updated to reflect that StatefulSet will be a beta feature in 1.5?
The scale limitation remains true.

2016-10-28 18:07 UTC, kow3ns requested changes
Aside from 1 nit and comment LGTM

2016-10-28 19:09 UTC, jimmycuadra commented
Thanks for the review! I'm gonna be on a plane most of today but will push up some fixes later tonight or tomorrow morning.

2016-10-28 22:09 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +        # the pod volumes.
This part (from `<!-- BEGIN MUNGE -->` to `<!-- END MUNGE -->`) is auto-generated, so you'll need to modify `cassandra-statefulset.yaml` and then run `hack/update-munge-docs.sh` to update it

2016-10-28 22:51 UTC, chrislovecnm requested changes
Thanks, please go through my changes.  Also what is the status of the e2e tests?

2016-10-28 22:51 UTC, chrislovecnm commented on docs/design/indexed-job.md
> +#### Comparison to StatefulSets
We should reference that this feature was called PetSet.  Otherwise, people are lacking context and may see this as a new feature.

2016-10-28 22:51 UTC, chrislovecnm commented on examples/cockroachdb/cockroachdb-statefulset.yaml
>  apiVersion: apps/v1alpha1
@janetkuo is this alpha or beta?

2016-10-28 22:51 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
> +## Step 2: Use a StatefulSet to create Cassandra Ring
Also is it StatefulSet or Stateful Set?  The object is called StatefulSet, but in English how are we defining it?  Again please mention that this feature was previously named PetSet.

2016-10-28 22:51 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
> +scope of this documentation.  [Please refer to the StatefulSet documentation.](http://kubernetes.io/docs/user-guide/statefulset/)
So we need to link the Pet Set docs and add file an issue to update.  Please explain why we are linking the Pet Set docs.

2016-10-28 22:51 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
>  apiVersion: apps/v1alpha1
Again is this beta?

2016-10-28 22:51 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
> +  selfLink: /apis/apps/v1alpha1/namespaces/default/statefulsets/cassandra
Again what does this `selfLink` look like off of a 1.5 cluster?

2016-10-28 22:51 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
> +The StatefulSet will now contain four pods.
These are not pods.  What are we calling them?  We have replicas in a deployment.  But each replica contains a pod, also you can have multiple pods in a single Pet.

2016-10-28 22:51 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
> +"Deleting the StatefulSet will not delete any pods. You will either have to manually scale it down to 0 pods first, or delete the pods yourself.
Again not a pod.

2016-10-28 22:51 UTC, chrislovecnm commented on hack/make-rules/test-cmd.sh
> +  kubectl create -f hack/testdata/nginx-statefulset.yaml "${kube_flags[@]}"
Nope he removed it.  Please add it back in.

2016-10-28 22:53 UTC, chrislovecnm commented
There is a release-note-none label on this.  @janetkuo should we mention that all of the examples have changed in the release notes?  Pretty big change, not just single line saying hey we changed PetSet -> StatefulSet.  But list out the areas of change.

2016-10-29 00:36 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +The StatefulSet will now contain four pods.
I'm not sure if I understand this. Aren't those "pets" also pods? StatefulSet's status.replicas is calculated from the number of pods the controller sees, and the type of pets in the code is `api.Pod`

2016-10-29 08:43 UTC, jimmycuadra commented on examples/cockroachdb/cockroachdb-statefulset.yaml
>  apiVersion: apps/v1alpha1
I intend for this PR to be merged only after #35731 is merged.

2016-10-29 08:51 UTC, jimmycuadra commented
How do we plan to manage the migration of http://kubernetes.io/docs/user-guide/petset/ to http://kubernetes.io/docs/user-guide/statefulset/? Do we want to change the URL and text of the guide in the docs repo before changing references to in the main repo? How will these changes be coordinated with the release of 1.5?

Regarding mentioning the name change in individual examples and guides, I don't think we want to do that. Having an item in the changelog that the feature was renamed is enough. Saying "this used to be called PetSet" everywhere somewhat defeats the purpose of having renamed it. The point is to not use that name anymore. It's only been in alpha—people that used it will learn quickly that it changed. And of course, people that weren't aware of it before won't be confused that it's a different feature if they didn't know about PetSet to begin with.

2016-10-29 08:58 UTC, jimmycuadra commented on examples/storage/cassandra/README.md
> +The StatefulSet will now contain four pods.
I'm not clear on this either. I understood "pet" to be stateful pod, but it does seem they are not equivalent: From the user guide:

> **Relationship between Pets and Pods**: PetSet requires there be {0..N-1} Pets. Each Pet has a deterministic name - PetSetName-Ordinal, and a unique identity. Each Pet has at most one pod, and each PetSet has at most one Pet with a given identity.

Yet the example shown seems to only contain one pod template, so I'm not sure what a multi-pod pet would look like. Chris, do you have an example that explains this better?

2016-10-29 16:44 UTC, chrislovecnm commented on examples/cockroachdb/cockroachdb-statefulset.yaml
>  apiVersion: apps/v1alpha1
You need to mark the PR as WIP so someone will not accidentally merge it.

2016-10-29 16:47 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
> +The StatefulSet will now contain four pods.
My mistake, I am incorrect ;)

2016-10-29 16:47 UTC, chrislovecnm commented on examples/storage/cassandra/README.md
> +"Deleting the StatefulSet will not delete any pods. You will either have to manually scale it down to 0 pods first, or delete the pods yourself.
Ignore this mistake, carry on ;)

2016-10-29 16:52 UTC, chrislovecnm commented
Ah I disagree. People are expecting this feature to be called PetSet. A change log cannot be the only place that references the name change. We need one mention per doc. We are going to confuse people without a simple mention to the previous name. Hell it would confuse me and I maintain the Cassandra example.

Please open another issue in the website repo about transitioning the name and the url. We are going to need to keep the old page, without the content, with a reference to the new page.

2016-10-29 16:59 UTC, chrislovecnm commented
Also in 3-6 mo then we can start removing the reference to the previous name. Once people have been educated that the name has been changed.

2016-10-30 00:05 UTC, jimmycuadra commented
You're right, that seems reasonable. I've updated the two docs to mention the name change.

Regarding using "StatefulSet" as opposed to "stateful set" or "Stateful Set" when writing about the feature in English, I don't have a preference either way. Happy to change it if more people thing it should be written differently when talking about the feature in general rather than referring to the actual resource.

I opted not to change any code in this PR (including e2e tests) to make it easier to merge the non-code stuff in while the alpha to beta PR is pending. We can deal with additional code changes later.

2016-10-30 00:06 UTC, chrislovecnm approved these changes

2016-10-31 18:13 UTC, janetkuo commented
> There is a release-note-none label on this. @janetkuo should we mention that all of the examples have changed in the release notes? Pretty big change, not just single line saying hey we changed PetSet -> StatefulSet. But list out the areas of change.

I think release note for this PR is optional, since we already have release note for "Rename PetSet to StatefulSet" in the API change PR (merged). Is that enough?

2016-10-31 21:50 UTC, janetkuo commented on examples/cockroachdb/cockroachdb-statefulset.yaml
>  apiVersion: apps/v1alpha1
I put do-not-merge label :)

2016-10-31 21:53 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +## Step 2: Use a StatefulSet to create Cassandra Ring
I vote for `Stateful Set`. I saw similar use in the docs of `Replica Set`, `Scheduled Job`, etc

2016-10-31 21:59 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +- [_PetSets_](http://kubernetes.io/docs/user-guide/petset/)
I'd say we change the text to StatefulSets, and update the url / filename later

2016-10-31 21:59 UTC, janetkuo commented on examples/storage/cassandra/README.md
> +  selfLink: /apis/apps/v1alpha1/namespaces/default/statefulsets/cassandra
The `selfLink` will look like this in 1.5, except that version should be `v1beta1`

2016-10-31 22:02 UTC, janetkuo commented
Since this depends on #35731, we can safely change apps/v1alpha1 to apps/v1beta1 (include `apiVersion` and `selfLink` in config files). I prefer `Stateful Set` over `StatefulSet`, but the change is optional.

2016-11-03 13:59 UTC, jimmycuadra commented
Now that #35731 is merged, this is ready for final review and merge.

2016-11-03 18:37 UTC, janetkuo approved these changes

2016-11-03 18:38 UTC, janetkuo commented
Mostly LGTM. Would you address these comments also? https://github.com/kubernetes/kubernetes/pull/35776#pullrequestreview-6533653

You may squash commits now.

2016-11-04 00:53 UTC, jimmycuadra commented
Done!

2016-11-04 20:16 UTC, janetkuo commented
LGTM. Thanks much!

2016-11-04 21:04 UTC, janetkuo commented
@k8s-bot unit test this #36262

2016-11-04 23:05 UTC, janetkuo commented on hack/testdata/nginx-statefulset.yaml
> +apiVersion: apps/v1alpha1
Unit test failed. This needs to be apps/v1beta1 as well

2016-11-04 23:05 UTC, janetkuo commented
@jimmycuadra would you update hack/testdata/nginx-statefulset.yaml to pass the unit test. I'll apply the tag afterwards

2016-11-05 07:17 UTC, jimmycuadra commented
Done.

2016-11-06 19:57 UTC, janetkuo commented
@k8s-bot unit test this

2016-11-06 21:30 UTC, merged