fix inconsistent util package import
kubernetes/kubernetes pull request #35777
Opened 2016-10-28 09:38 UTC by redhatlinux10

What this PR does / why we need it:

this PR makes sure `kubeadmutil.CheckErr()` other than `cmdutil.CheckErr()` is called in `kubeadm version` subcommand. 
in `version.go`, `RunVersion()` function only returns `nil`, `kubeadmutil.CheckErr()` is enough for this

this PR also fix a typo in AlphaWarningOnExit message.

Signed-off-by: redhatlinux10 <ouyang.qinhua@zte.com.cn>

2016-10-28 19:19 UTC, jbeda requested changes

2016-10-28 19:19 UTC, jbeda commented on cmd/kubeadm/app/util/error.go
> +	kubeadm: I am at alpha version, my authors welcome your feedback and bug reports
Actually, to me, the previous version reads better.

2016-10-28 20:15 UTC, redhatlinux10 commented
@jbeda modified as you suggested, would you please verify again ?

2016-10-29 00:26 UTC, jbeda approved these changes

2016-10-29 00:26 UTC, jbeda commented
@k8s-bot ok to test

2016-10-29 03:45 UTC, redhatlinux10 commented
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

2016-10-29 09:23 UTC, redhatlinux10 commented
@jbeda anything i can do for the failure of smoke e2e ?

2016-10-29 14:30 UTC, redhatlinux10 commented
@k8s-bot cvm gke e2e test this

2016-10-31 01:08 UTC, merged