Support events in restore script
kubernetes/kubernetes pull request #35784
Opened 2016-10-28 12:01 UTC by wojtek-t

Ref #20504

2016-10-28 15:08 UTC, roberthbailey commented on cluster/restore-from-backup.sh
> +  echo "${VERSION_CONTENTS}" > "${VERSION_FILE}"
will this fail if version.txt already exists?

2016-10-28 15:08 UTC, roberthbailey commented on cluster/restore-from-backup.sh
> +if [ "${RESTORE_EVENT_ETCD:-}" == "true" ]; then
since this doesn't restore, it just resets, maybe we could name this `RESET_EVENT_ETCD` or something that is more closely aligned with the effect.

2016-10-28 19:23 UTC, wojtek-t commented on cluster/restore-from-backup.sh
> +  echo "${VERSION_CONTENTS}" > "${VERSION_FILE}"
No. Should it?

2016-10-28 22:07 UTC, mml requested changes

2016-10-28 22:07 UTC, mml commented on cluster/restore-from-backup.sh
> +if [ ! -z "${VERSION_CONTENTS:-}" ]; then
Might just be me, but I find `if [ -n "$blah" ]; then` more idiomatic.

2016-10-28 22:07 UTC, mml commented on cluster/restore-from-backup.sh
> +  echo "TARGET_STORAGE variable unset - skipping migration"
Why this message?  We haven't even checked `TARGET_STORAGE`.

2016-10-28 22:07 UTC, mml commented on cluster/restore-from-backup.sh
> +  rm -rf "${MNT_DISK}/var/etcd-events-corrupted"
Maybe put this directory name in a variable, since we repeat it three times.

2016-10-31 07:18 UTC, wojtek-t reviewed
PTAL

2016-10-31 07:18 UTC, wojtek-t commented on cluster/restore-from-backup.sh
> +if [ ! -z "${VERSION_CONTENTS:-}" ]; then
done

2016-10-31 07:18 UTC, wojtek-t commented on cluster/restore-from-backup.sh
> +  echo "TARGET_STORAGE variable unset - skipping migration"
Copy-paster error.

2016-10-31 07:18 UTC, wojtek-t commented on cluster/restore-from-backup.sh
> +  rm -rf "${MNT_DISK}/var/etcd-events-corrupted"
done

2016-10-31 07:18 UTC, wojtek-t commented on cluster/restore-from-backup.sh
> +if [ "${RESTORE_EVENT_ETCD:-}" == "true" ]; then
done

2016-10-31 17:36 UTC, mml approved these changes

2016-10-31 17:40 UTC, mml commented
@k8s-bot gci gke e2e test this ISSUE: #35913

2016-10-31 17:43 UTC, mml commented
LGTM, but it looks like @roberthbailey still has one outstanding question.

2016-11-02 07:39 UTC, wojtek-t commented
Talked with @roberthbailey offline and discussed his comment. He agreed that what is now is ok.

So applying lgtm label.

2016-11-02 07:44 UTC, roberthbailey commented
lgtm

2016-11-02 10:08 UTC, merged