Fix zone on relelease-1.3
kubernetes/kubernetes pull request #35830
Opened 2016-10-28 22:22 UTC by jessfraz

Cherrypick of ee6e92473d24c30417f49ca261fa7c436551fc48

fix #35654 ping @wonderfly @fabioy for release-1.3

2016-10-28 22:25 UTC, ixdy requested changes
The flag changed to `--zones` only for list operations. Everything else should remain `--zone`.

2016-10-28 22:29 UTC, jessfraz commented
crap sorry the original patch didnt apply right so i changed them all, I
will fix

On Fri, Oct 28, 2016 at 3:26 PM, Jeff Grafton <notifications@github.com>
wrote:

> *@ixdy* requested changes on this pull request.
>
> The flag changed to --zones only for list operations. Everything else
> should remain --zone.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/35830#pullrequestreview-6328917>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABYNbCYnCA-KLU6ivjHcLW3LrYzfabcnks5q4naBgaJpZM4Kj6wV>
> .
>

2016-10-28 22:35 UTC, jessfraz commented on cluster/gce/util.sh
> +        "${group}" --zones "${ZONE}" --project "${PROJECT}" \
@ixdy is it for list-instances too?

2016-10-28 22:51 UTC, jessfraz commented on cluster/gce/util.sh
> +        "${group}" --zones "${ZONE}" --project "${PROJECT}" \
the failing build answered my question lol nevermind

2016-10-28 22:56 UTC, wonderfly commented on cluster/gce/util.sh
> +        "${group}" --zones "${ZONE}" --project "${PROJECT}" \
Yeah, the gcloud release notes aren't very helpful... They say command line flag abbreviations are no longer supported, but don't mention what "command line flag abbreviations" are. Google search doesn't show anything either.

2016-10-28 22:56 UTC, wonderfly commented
LGTM as long as tests pass

2016-10-31 16:42 UTC, wonderfly commented
@jessfraz I can't apply labels. Can you ping someone else for a LGTM?

2016-10-31 16:50 UTC, merged

2016-10-31 16:50 UTC, fabioy commented
Manually merged.