[RFC] CRI: Add Status into CRI.
kubernetes/kubernetes pull request #35839
Opened 2016-10-29 00:03 UTC by Random-Liu

For https://github.com/kubernetes/kubernetes/issues/35701.

This PR added a `Status` call in CRI, and the `RuntimeStatus` is defined as following:
``` protobuf
message RuntimeCondition {
    // Type of runtime condition.
    optional string type = 1;
    // Status of the condition, one of true/false.
    optional bool status = 2;
    // Brief reason for the condition's last transition.
    optional string reason = 3;
    // Human readable message indicating details about last transition.
    optional string message = 4;
}

message RuntimeStatus {
    // Conditions is an array of current observed runtime conditions.
    repeated RuntimeCondition conditions = 1;
}
```

Currently, only `conditions` is included in `RuntimeStatus`, and the definition is almost the same with `NodeCondition` and `PodCondition` in K8s api.

@yujuhong @feiskyer @bprashanth 
/cc @kubernetes/sig-node

2016-11-01 00:56 UTC, euank commented
I don't think there's an issue with this from the rkt perspective. The same hostNetwork thing shhould behave pretty much identically here.

I do question the original choice of hostNetworkOnly being a condition though... thinking about it more, being able to reject a pod with a status like "networkNotReady" or "runtimeNotReady" as a reason would allow the kubelet to know to retry things in those cases and might be a more reliable way to handle these things.

2016-11-01 01:15 UTC, bprashanth commented
rkt can just piggyback on kubenet's status(), which is a synthetic api to begin with (meaning it's not actually a part of CNI). 

Status does 2 things:     

1. checks if the cni binary exists at pluginDir
2. checks if the cni conf has been initialized with podCIDR

If either of those is false, the node remains notready. 
If --runtime=rkt --plugin=!kubenet, the rkt cri will have to implement a status() that effectively does the above.

2016-11-01 01:17 UTC, bprashanth commented
@kubernetes/sig-network

2016-11-01 01:31 UTC, bprashanth commented on pkg/kubelet/dockershim/remote/docker_service.go
> +	return nil, fmt.Errorf("not implemented")
Please add godoc. how are we planning to integrate this into the `defaultNodeStatusFuncs`? I'm guessing it needs to make its way into `runtimeState.networkErrors`?

2016-11-01 01:31 UTC, bprashanth commented on pkg/kubelet/api/v1alpha1/runtime/api.pb.go
> +//   * NetworkReady: NetworkReady means the runtime network is up and ready to
so if any required condition is unmet the node remains notready (please elaborate comment)? 
we will probably have to conditionally start hostnetwork pods if NetworkReady == false but everything else checks out.

2016-11-01 18:54 UTC, yujuhong requested changes
Need to update the internal interface in `pkg/kubelet/api/services.go` and add an implementation stub in `dockershim/docker_service.go`

2016-11-01 18:54 UTC, yujuhong commented on pkg/kubelet/dockershim/remote/docker_service.go
> +	return nil, fmt.Errorf("not implemented")
Yes, we probably need to change [`syncNetworkStatus`](https://github.com/kubernetes/kubernetes/blob/2941aea88e80e94f2698241a4ac9925145664470/pkg/kubelet/kubelet_network.go#L193) to pipe this information.

2016-11-01 19:01 UTC, Random-Liu commented
Will finish the following part today.

2016-11-01 21:57 UTC, Random-Liu commented on pkg/kubelet/api/v1alpha1/runtime/api.pb.go
> +//   * NetworkReady: NetworkReady means the runtime network is up and ready to
ACK

2016-11-02 00:58 UTC, feiskyer commented
> Need to update the internal interface in pkg/kubelet/api/services.go and add an implementation stub in dockershim/docker_service.go

Besides, also add `Status()` calling at `pkg/kubelet/remote` and `pkg/kubelet/api/testing`.

2016-11-02 01:01 UTC, bprashanth commented on pkg/kubelet/dockershim/remote/docker_service.go
> +	return nil, fmt.Errorf("not implemented")
Shouldn't the kubelet parses out network/runtime status directly from the response of this rpc in syncRuntimeStatus?

2016-11-02 03:50 UTC, Random-Liu commented
Addressed comments and implement the initial version of `Status`.

I'll send another PR to expose RuntimeReady and NetworkReady from runtime interface https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L73.

2016-11-02 03:51 UTC, Random-Liu commented
@k8s-bot cri test this.

2016-11-02 04:00 UTC, Random-Liu commented on pkg/kubelet/api/testing/fake_runtime_service.go
> +func (r *FakeRuntimeService) SetFakeRuntime(set func(*FakeRuntimeService)) {
Notice that this is not used, but will be used in the future unit test.

2016-11-02 04:00 UTC, Random-Liu commented
@k8s-bot cri test this.

2016-11-02 06:24 UTC, feiskyer commented on pkg/kubelet/api/testing/fake_runtime_service.go
> +	Errors     map[string]error
what is this for?

2016-11-02 06:24 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
>  	}
nit: do we need to report node events if there are other not ready conditions?

2016-11-02 17:41 UTC, Random-Liu commented on pkg/kubelet/api/testing/fake_runtime_service.go
> +	Errors     map[string]error
This is for injecting errors.

2016-11-02 17:42 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
>  	}
The code is temporary, I'll send another PR/commit soon to really use the conditions. I'll deal with then.

2016-11-03 04:12 UTC, Random-Liu commented
@k8s-bot cri test this.

2016-11-03 04:12 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
>  	}
LGTM

2016-11-03 04:14 UTC, Random-Liu commented
PR is ready for review.

2016-11-03 06:04 UTC, Random-Liu commented
@k8s-bot cri test this.

2016-11-03 07:27 UTC, feiskyer commented
LGTM. needs @yujuhong take another look, and confirm review changes.

2016-11-04 00:44 UTC, yujuhong approved these changes
LGTM.

2016-11-04 00:44 UTC, yujuhong commented on pkg/kubelet/kubelet.go
> +	if kl.kubeletConfiguration.ExperimentalRuntimeIntegrationType == "cri" {
Never mind. I decided to send in #36201 to enforce that all integration using CRI should specify --experimental-runtime-integration-type=cri for now to simplify the code.

2016-11-04 01:14 UTC, Random-Liu commented
@yujuhong Add the `networkPlugin=nil` back.

2016-11-04 17:44 UTC, Random-Liu commented
Just rebase, apply LGTM again.

2016-11-06 12:16 UTC, merged