Expose etcd version.
kubernetes/kubernetes pull request #35896
Opened 2016-10-31 12:40 UTC by wojtek-t

Ref #20504

2016-10-31 13:41 UTC, wojtek-t commented
@k8s-bot test this, issue: #IGNORE (Unable to get latest version from build tree.  Exiting...)

2016-10-31 17:32 UTC, mml requested changes
I think we need to explain, either in the PR or commit message (or both) how we're changing the semantics of ETCD_VERSION and why we needed to introduce the new ETCD_IMAGE variable.

It would also be good to document the meaning of the two variables somewhere in the code.

2016-10-31 17:32 UTC, mml commented on cluster/common.sh
> +ETCD_IMAGE: $(yaml-quota ${ETCD_IMAGE})
s/quota/quote

2016-11-02 07:28 UTC, wojtek-t commented on cluster/common.sh
> +ETCD_IMAGE: $(yaml-quota ${ETCD_IMAGE})
done

2016-11-02 07:30 UTC, wojtek-t commented
@mml - comments applied, PTAL

2016-11-02 13:24 UTC, wojtek-t commented
@kubernetes/test-infra-maintainers - I'm getting the following error in all suites:
```
Unable to get latest version from build tree. Exiting...
```
anything I can do with it (I have no idea what is happening - retesting doesn't help).

2016-11-02 13:44 UTC, mtaufen commented
Interesting, I ran into this same issue yesterday on https://github.com/kubernetes/kubernetes/pull/32530, but things are ok on that PR now. It's been 6 hours since these failed, try re-running?

2016-11-02 13:45 UTC, wojtek-t commented
@k8s-bot test this, issue: #IGNORE (Unable to get latest version from build tree. Exiting...)

2016-11-02 14:05 UTC, wojtek-t commented
@mtaufen - it didn't help

2016-11-02 15:39 UTC, mtaufen commented
Hmmmm. This is where that error comes from: https://github.com/kubernetes/release/blame/master/push-build.sh#L104

2016-11-02 15:45 UTC, mtaufen commented
Try running cluster/kubectl.sh version --client and paste the output here to see if it matches: http://regexr.com/3eij0

2016-11-02 15:48 UTC, wojtek-t commented
@mtaufen - how can I run it? It's working for me locally.

2016-11-02 15:54 UTC, ixdy commented on cluster/common.sh
> +    if [ -n "${ETCD_IMAGE:-}" ]; then
this appears to be missing the `fi`.

2016-11-02 15:54 UTC, mtaufen commented
Ok. Just wanted to make sure nothing super strange was going on.

2016-11-02 16:07 UTC, wojtek-t commented on cluster/common.sh
> +    if [ -n "${ETCD_IMAGE:-}" ]; then
heh - I must have added it after last test. but the error is really misleading btw

2016-11-02 17:43 UTC, mml approved these changes

2016-11-02 17:44 UTC, mml commented
LGTM

2016-11-02 18:44 UTC, ixdy commented on cluster/common.sh
> +    if [ -n "${ETCD_IMAGE:-}" ]; then
I agree. I'll fix it.

2016-11-02 18:46 UTC, wojtek-t commented on cluster/common.sh
> +    if [ -n "${ETCD_IMAGE:-}" ]; then
thanks!

2016-11-02 19:13 UTC, merged