Add tests for deepcopy of structs
kubernetes/kubernetes pull request #35912
Opened 2016-10-31 17:02 UTC by liggitt

Until https://github.com/kubernetes/kubernetes/pull/35728 merges, we want to at least fuzz/test that deepcopy isn't shallow-copying problematic fields

2016-11-02 05:15 UTC, liggitt commented
#35898 flake
@k8s-bot unit test this

2016-11-02 12:26 UTC, kargakis commented
> #35898 flake

I assume this was older than the fix (https://github.com/kubernetes/kubernetes/pull/36003) for the flake

2016-11-02 15:36 UTC, erictune commented
@caesarxuchao can you review or reassign please.

2016-11-02 17:30 UTC, caesarxuchao requested changes

2016-11-02 17:30 UTC, caesarxuchao commented on pkg/api/copy_test.go
> +		if err == nil || strings.Contains(err.Error(), "must pass addressable value") {
`If err!=nil && strings.Contains(...`

2016-11-02 17:30 UTC, caesarxuchao commented on pkg/api/copy_test.go
> +		if reflect.DeepEqual(itemStruct, itemStructCopy) {
I thought we should compare `itemStructPreFuzz` with `itemStructPostFuzz` here.

2016-11-03 14:48 UTC, liggitt commented
removed the struct copy stanza, still working on that, the rest is ready

2016-11-05 03:31 UTC, liggitt commented
comments addressed, PTAL

2016-11-05 03:48 UTC, caesarxuchao commented
LGTM. Thanks!

2016-11-08 05:57 UTC, saad-ali commented
Release-czar approved post-code freeze merge--This was LGTMed and in the merge-queue at code freeze time for 1.5. Adding 1.5 milestone to let it gets merged after code freeze.

2016-11-09 08:48 UTC, merged