Restore old apiserver cert CN
kubernetes/kubernetes pull request #36068
Opened 2016-11-02 15:49 UTC by sttts

This patch got lost during rebase of https://github.com/kubernetes/kubernetes/pull/35109:

- set `host@<unix-timestamp>` as CN in self-signed apiserver certs
- skip non-domain CN in getNamedCertificateMap

2016-11-02 15:58 UTC, liggitt commented on pkg/genericapiserver/serve.go
> +		if !strings.HasPrefix(s, "*.") {
only need to do this once, certs can only wildcard a single level

2016-11-02 16:01 UTC, sttts commented on pkg/genericapiserver/serve.go
> +		if !strings.HasPrefix(s, "*.") {
true

2016-11-02 16:03 UTC, sttts commented on pkg/genericapiserver/serve.go
> +		if !strings.HasPrefix(s, "*.") {
fixed

2016-11-02 16:28 UTC, sttts commented
@k8s-bot node e2e test this

2016-11-02 17:12 UTC, liggitt commented
LGTM, squash

2016-11-02 21:40 UTC, dims commented
Looks good to me 👍

2016-11-02 21:47 UTC, liggitt requested changes

2016-11-02 21:47 UTC, liggitt commented on pkg/genericapiserver/serve.go
> +		if strippedCN == "*" || len(validation.IsDNS1123Subdomain(strippedCN)) == 0 {
Not quite right, this would match `"*.*"`

2016-11-02 21:47 UTC, liggitt commented on pkg/genericapiserver/serve.go
> +		if strippedCN == "*" || len(validation.IsDNS1123Subdomain(strippedCN)) == 0 {
`cn == "*" || len(validation.IsDNS1123Subdomain(strings.TrimPrefix(cn, "*.")) == 0`?

2016-11-03 08:00 UTC, sttts commented on pkg/genericapiserver/serve.go
> +		if strippedCN == "*" || len(validation.IsDNS1123Subdomain(strippedCN)) == 0 {
good catch

2016-11-03 08:03 UTC, sttts commented on pkg/genericapiserver/serve.go
> +		if strippedCN == "*" || len(validation.IsDNS1123Subdomain(strippedCN)) == 0 {
fixed

2016-11-03 14:31 UTC, liggitt approved these changes

2016-11-04 11:45 UTC, sttts commented
@k8s-bot test this issue

2016-11-06 09:01 UTC, sttts commented
@k8s-bot cvm gce e2e test this

2016-11-06 20:25 UTC, sttts commented
@k8s-bot cvm gce e2e test this

2016-11-07 08:37 UTC, merged