fix nodeport service no endpoints
kubernetes/kubernetes pull request #36130
Opened 2016-11-03 03:47 UTC by m1093782566

**Which issue this PR fixes**

Fixes 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

Change-Id: I3d0cfcbcc4c366af97046f535ad65f73d68d4412

2016-11-03 03:59 UTC, thockin commented
ok to test

2016-11-03 04:09 UTC, thockin reviewed
This looks OK overall.  What can we do for testing?

2016-11-03 04:09 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +				lp := localPort{
Even if we don't have any endpoints, we should hold the port open.  We don't want someone coming along later thinking they can use it.

2016-11-03 09:35 UTC, m1093782566 commented on pkg/proxy/iptables/proxier.go
> +				lp := localPort{
Oh, yes. I will fix it.

2016-11-03 09:40 UTC, m1093782566 commented
@thockin 

> What can we do for testing?

For e2e, I added test cases(PR was updated) for veifying REJECT nodeport in iptables nat table when NodePort type service has no endpoints.

2016-11-04 11:26 UTC, m1093782566 commented
@thockin @freehan 

PR updated for adding test cases(UT & e2e), please take a look.

Thanks!

2016-11-30 05:56 UTC, thockin requested changes
Thanks for the tests.  I tried to find a real problem with this but couldn't.  Just a nit on log-levels.

2016-11-30 05:56 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +				glog.V(2).Infof("Reject NodePort type service %s has no endpoints", svcName.String())
V(3) please - this is not important enough for default.

2016-12-01 01:23 UTC, thockin commented
W1130 04:19:00.512] test/e2e/service.go:502: undefined: api in api.ServiceTypeClusterIP
W1130 04:19:00.512] test/e2e/service.go:535: undefined: api in api.Service
W1130 04:19:00.512] test/e2e/service.go:536: undefined: api in api.ServiceTypeNodePort
W1130 04:19:00.512] test/e2e/service.go:538: undefined: api in api.ServiceTypeNodePort

2016-12-01 01:31 UTC, m1093782566 commented
@thockin I am tring to fix them.

2016-12-01 15:04 UTC, m1093782566 commented
@thockin It seems that I have some trouble in e2e test. I need a little time to figure it out. :)

2016-12-28 00:22 UTC, thockin commented
verify failed:

```
W1201 07:29:05.132] test/e2e/service.go:537: arg nodePort for printf verb %s of wrong type: int
```

Ping me when this is ready.

2017-01-28 22:52 UTC, thockin commented
ping?

2017-02-03 07:15 UTC, m1093782566 commented on pkg/proxy/iptables/proxier.go
> +				glog.V(2).Infof("Reject NodePort type service %s has no endpoints", svcName.String())
fixed.

2017-02-05 01:41 UTC, m1093782566 commented
ping @thockin

2017-02-16 01:46 UTC, m1093782566 commented
@thockin 

Sorry for the delay. CI passed.

2017-02-16 04:19 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +		if len(proxier.endpointsMap[svcName]) != 0 {
remind me why this part is correct?

2017-02-28 00:39 UTC, thockin commented on pkg/proxy/iptables/proxier.go
> +		if len(proxier.endpointsMap[svcName]) != 0 {
ping?

2017-03-02 00:29 UTC, ethernetdan commented
Removing issue from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

2017-03-02 08:11 UTC, m1093782566 commented on pkg/proxy/iptables/proxier.go
> +		if len(proxier.endpointsMap[svcName]) != 0 {
oom, I think this part is wrong...

2017-03-11 13:45 UTC, m1093782566 commented
@thockin Comments fixed. PTAL.

2017-04-05 20:41 UTC, grodrigues3 commented
@k8s-bot bazel test this

2017-04-05 20:41 UTC, grodrigues3 commented
@k8s-bot unit test this

2017-04-25 06:00 UTC, thockin commented
This seems fixed in upstream now?  Please confirm?

2017-04-25 06:00 UTC, closed without merging

2017-05-23 21:09 UTC, bhiggins commented
@thockin: pardon my ignorance but what is upstream in this case? I see the associated issue #31435 is still open, should the issue be closed as well, or this PR reopened?

2017-05-30 05:35 UTC, thockin commented
Thanks!  Yes, I think this is fixed in master, to be released in 1.7