Create admission controller to set Node Conditions
kubernetes/kubernetes pull request #36209
Opened 2016-11-04 06:14 UTC by justinsb

This controller allows us to set Node Conditions without needing to be
aware of all of them in the kubelet.

2016-11-04 06:17 UTC, justinsb commented
Related: we should not hard-code a list of conditions, but rather treat them as blocking.  This allows splitting more logic out of the core / out of kubelet, and into external controllers #36210

2016-11-04 06:19 UTC, justinsb commented on plugin/pkg/admission/node/condition/admission.go
> +			Status:             api.ConditionTrue,
Maybe we should set Unknown here instead?

2016-11-04 06:20 UTC, justinsb commented
cc @thockin @dcbw

2016-11-04 14:29 UTC, justinsb commented
Also cc @wlan0 as this is the approach I was suggesting for splitting off the kubelet

2016-11-04 14:48 UTC, wlan0 commented
@justinsb this is perfect. I was thinking of doing the same with annotations. But this seems better.

2016-11-04 15:01 UTC, wlan0 commented
@justinsb did you have to make a corresponding PR for scheduler to block scheduling if this condition is seen?

2016-11-04 15:14 UTC, wlan0 commented
Found it https://github.com/kubernetes/kubernetes/pull/36210

2016-11-04 21:03 UTC, dcbw commented
Seems reasonable to me.  I'm not hugely familiar with the AC code but I couldn't find anything obviously wrong with it.

2016-11-04 21:10 UTC, wlan0 commented on plugin/pkg/admission/node/condition/admission.go
> +		node.Status.Conditions = append(node.Status.Conditions, api.NodeCondition{
We seem to allow duplicate conditions. Should we stop that? Consider an example, if there are dups, then the external controller will remove **only one** of the many duplicate conditions, and object will still remain unschedulable.

2016-11-04 22:06 UTC, justinsb commented on plugin/pkg/admission/node/condition/admission.go
> +		node.Status.Conditions = append(node.Status.Conditions, api.NodeCondition{
I don't think we do, unless they are preexisting conditions.

a.conditions was built from a set, so has no duplicates.

2016-11-05 02:34 UTC, wlan0 commented on plugin/pkg/admission/node/condition/admission.go
> +		node.Status.Conditions = append(node.Status.Conditions, api.NodeCondition{
oh right, looks good then.

2016-11-05 19:31 UTC, derekwaynecarr requested changes
Can you give an example on the set of conditions you want to use this to set?

2016-11-05 19:31 UTC, derekwaynecarr commented on plugin/pkg/admission/node/condition/admission.go
> +		return apierrors.NewBadRequest("Resource was marked with kind Node but was unable to be converted")
Nit: Typically we start with a lower case error.

2016-11-05 19:31 UTC, derekwaynecarr commented on plugin/pkg/admission/node/condition/admission.go
> +		node.Status.Conditions = append(node.Status.Conditions, api.NodeCondition{
We should stop duplicates in validation

2016-11-07 04:24 UTC, justinsb commented on plugin/pkg/admission/node/condition/admission.go
> +		return apierrors.NewBadRequest("Resource was marked with kind Node but was unable to be converted")
Fixed - thanks!

2016-11-07 04:27 UTC, justinsb commented on plugin/pkg/admission/node/condition/admission.go
> +		node.Status.Conditions = append(node.Status.Conditions, api.NodeCondition{
I'm not sure whether you mean that the validation code will block duplicate Conditions, or that this code should avoid duplicates.  This code does avoid it by use of `sets.NewString`, and we do have unit test coverage of that.  (But let me know if I've missed a case!)

I added a comment to `newNodeCondition` to document that the list of conditions should have been de-duplicated.

2016-11-07 04:27 UTC, justinsb commented
@derekwaynecarr in terms of what this will be used for, the big one is NetworkUnavailable, cf https://github.com/kubernetes/kubernetes/pull/33573.  But the idea of doing this in an admission controller is that we need only reconfigure masters to set a list of Node Status Conditions.  The intention is that external controllers (e.g. TPM check) need not be in core, but could instead just clear a Node Status Condition once they had completed validation.

2016-11-07 19:35 UTC, justinsb commented
ping @derekwaynecarr as I'd like to get this merged pre feature freeze, but I'm not sure I've addressed all your questions yet?

2016-11-07 23:37 UTC, justinsb commented
@derekwaynecarr do you think we can get this in before feature freeze please :-) ?

2016-11-08 08:45 UTC, derekwaynecarr requested changes
@justinsb I understand how this helps the networking case, but I wonder if we have other cases where this very generic solution is appropriate.  If not, I just wonder if we are better served by a networking specific plugin that has fewer input knobs for admins to tweak/configure and get wrong.

The generic solution like this makes me anxious if it introduces problems with upgrade scenarios in the future.  You may upgrade your masters at a different rate than your nodes, or not all your nodes will report a uniform set of conditions (which is possible today).  For example, some nodes could run node-problem-detector, but some nodes may not.  That would mean that not all nodes will report a uniform set of conditions, which makes me think this would need potentially some way of carving up different sets of default conditions for different classes of nodes.  Given that, do we need the uber generic option, or should we just do a focused networking specific fix.

WDYT?

2016-11-08 22:49 UTC, wlan0 commented
@derekwaynecarr This PR is are useful for another feature that I'm working on - https://github.com/kubernetes/features/issues/88. Having this approach that @justinsb has proposed here is the best way for me to move cloudprovider dependencies out of kubelet. 

Kubelet uses cloudprovider to query for node labels and IP addresses of a node before creating the node object. These fields need to filled into a node before it can be used to schedule pods on. With this PR, I can set the Status as "CloudProviderProcessed" : "false", until an external controller fetches this information asynchronously, and removes this label when done.

2016-11-14 19:32 UTC, justinsb commented
@derekwaynecarr Updated the copyright - nice spot.

I think that this actually helps the scenario you described, because it means everything is now done centrally on the master(s).  This pulls the logic away from the node, so it doesn't need to know what controllers are acting centrally.

Also, I'm not entirely sure what a more cut-down admission controller would look like - I guess you're saying it could hard-code a list of "permitted" conditions, but in general I think we trust the administrator if they are configuring flags.

2016-11-18 05:50 UTC, liggitt commented on plugin/pkg/admission/node/condition/admission.go
> +	flagNodeInitialConditions = flag.String("node-initial-conditions", "", "Comma-separated list of conditions to apply on newly created Nodes.")
admission plugins shouldn't be registering global flags for config...

2016-11-18 05:59 UTC, liggitt commented
it appears that this splits the responsibility for reporting initial node conditions between the apiservers and the nodes, which I find sort of odd. is there a reason this couldn't be an option to the node for custom conditions to add to the initial node object?

2016-11-21 15:44 UTC, liggitt commented
I think the change in https://github.com/kubernetes/kubernetes/pull/36210 is a mistake... I would rather see the scheduler be able to require or forbid a particular condition when scheduling. If a required condition was missing, the node would be considered unschedulable. That would remove the need for an admission plugin on node creation, and avoid the limitation https://github.com/kubernetes/kubernetes/pull/36210 places on all future node conditions that "False" be the "ok" value

2016-11-21 22:28 UTC, dchen1107 commented
We plan to convert existing NodeConditions to Taints once it is beta since Taint is better structed with key, value and effect. Not all Taints map to NoSchedule effect anyway. 

xref: https://github.com/kubernetes/kubernetes/issues/25773#issuecomment-262034716

2016-11-21 23:56 UTC, bgrant0607 commented
See also #31647

2016-11-22 00:27 UTC, justinsb commented
So are we saying we should have this PR, but creating taints instead @dchen1107 ?

@liggitt the node/server split is awkward ... and I think we should pull logic out of the node because of things like #33573 .  So I feel like this is a step in the right direction

2016-11-22 01:28 UTC, dchen1107 commented
I understood that  #33573  should be addressed for route-not-ready issue for aws particularly, and you are trying to resolve this similar to how we did for GCE / GKE, but more generic. I just briefly chatted with @thockin and he will take another look at the pr and help identifying the short-term solution.

Also please take a look at #31647 which introducing a flag to Kubelet: --register-with-taints. I understood that pr doesn't help in your case directly here since route is created separately through AWS cloud provider API. 

In a long term, we are in the progress of converting existing NodeConditions to Taints. I will try to avoid introducing a easy way (a.k.a new admission controller here) to populate more node conditions to the ecosystem.

2016-11-22 06:23 UTC, davidopp commented
IIUC this isn't enabled by default, is that correct?

2016-11-22 16:09 UTC, liggitt commented
Until taints are ready, would it make sense to switch the way the scheduler pays attention to particular node conditions to use a generic condition predicate like https://github.com/kubernetes/kubernetes/pull/37224?

That could effectively replace `getNodeConditionPredicate` internally with scheduler predicates like this:
```
{"name": "RequireReady",  "argument": {"requireCondition": {"conditionType": "Ready", "conditionStatuses":["True"]}}}
{"name": "ForbidOutOfDisk",  "argument": {"forbidCondition": {"conditionType": "OutOfDisk", "conditionStatuses":["True","Unknown"]}}}
{"name": "ForbidNetworkUnavailable",  "argument": {"forbidCondition": {"conditionType": "NetworkUnavailable", "conditionStatuses":["True","Unknown"]}}}
```

Third-party conditions could be required/forbidden in the same way via a custom scheduler config

2016-11-22 19:13 UTC, thockin commented
OK.  I am confused now between this, initializers, and taints.  This is in service of fixing up the need for routes to be established before scheduling, right?

If we add this, and then get generic initializers, are we going to be unhappy to also have to carry this?

Is this really going to be easier to use/configure than forcing Kubelet to set the condition when nodes are created?  At least that is more self-contained.

Do we have an over-arching doc that explains this tangle?

Can I maybe agitate for a slack meeting or a hangout to cut through this?  It has been running for too long...

2016-11-24 09:33 UTC, davidopp commented
@justinsb Is there something here you urgently need for 1.5? Can we pare it down to something very simple, and then work on understanding the issue more thoroughly for 1.6?

2017-01-13 19:10 UTC, derekwaynecarr commented
this has lingered.  @justinsb - do you want to close this or keep open?

2017-01-31 01:11 UTC, smarterclayton commented
As the duly represented arbitrary bot insanity assignee - I'd suggest we close until we reach closure on this.  Reopen if changed

2017-01-31 01:11 UTC, closed without merging