tighten and document the genericapiserver.Config
kubernetes/kubernetes pull request #36257
Opened 2016-11-04 20:14 UTC by deads2k

This re-organizes and documents the `genericapiserver.Config` in the order which composers are likely to need the fields.  The second commit further tightens the API to a spot that should be good for 1.5.

@ncdc @sttts

2016-11-07 16:57 UTC, ncdc requested changes
Generally LGTM but some small changes needed.

2016-11-07 16:57 UTC, ncdc commented on pkg/genericapiserver/config.go
> +// GetMasterAddress checks for an unset master address and then attempts to use the first
s/GetMasterAddress/defaultExternalAddress/

2016-11-07 16:57 UTC, ncdc commented on pkg/genericapiserver/config.go
> +	if err == nil {
Do you mean `!=` here?

2016-11-07 16:57 UTC, ncdc commented on pkg/genericapiserver/config.go
>  //   PublicAddress
Removed?

2016-11-07 16:57 UTC, ncdc commented on pkg/master/master.go
> +	// kube-proxy, services, etc.) can reach the GenericAPIServer.
s/GenericAPIServer/master/ ?

2016-11-07 16:57 UTC, ncdc commented on pkg/master/master_test.go
> +	config.APIResourceConfigSource = DefaultAPIResourceConfigSource()
Dupe of line 89?

2016-11-08 13:47 UTC, deads2k commented
@k8s-bot unit test this: issue #36351

2016-11-08 14:23 UTC, deads2k commented
I must have broken something.  This can wait until next release.

2016-12-05 19:07 UTC, deads2k commented
This is too far out of date to bring back.  I'll open new pulls to address the need.

2016-12-05 19:07 UTC, closed without merging