Make pvc storage class annotation immutable after create
kubernetes/kubernetes pull request #36251
Opened 2016-11-04 18:13 UTC by screeley44

Fixes #34516

Added immutable check in validation.go

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# persistentvolumeclaims "gce-claim-storageclass" was not valid:
# * metadata.annotations.volume.beta.kubernetes.io/storage-class: Invalid value: "slow2": field is immutable
#

```

2016-11-04 18:14 UTC, screeley44 commented
@eparis @erinboyd @derekwaynecarr - how does this look?

2016-11-04 18:54 UTC, smarterclayton commented
Add a test case.

2016-11-04 19:58 UTC, screeley44 commented
@smarterclayton - test case added

2016-11-04 20:07 UTC, screeley44 commented
@smarterclayton - what is that verify-bazel.sh and update-bazel.sh ?  I ran that and it modified a ton of files, am I supposed to commit each of those to get past that test?

2016-11-04 20:52 UTC, smarterclayton commented
Yes, you must commit the bazel files.  Those are build system metadata files that go with each package.

2016-11-05 22:44 UTC, screeley44 commented
@k8s-bot test this issue: #31776

2016-11-08 19:14 UTC, screeley44 commented
@eparis @smarterclayton - PTAL

2016-11-14 21:10 UTC, eparis commented
@kubernetes/sig-storage

2016-11-16 13:01 UTC, jsafrane requested changes

2016-11-16 13:01 UTC, jsafrane commented on pkg/api/validation/validation.go
> +	if !api.Semantic.DeepEqual(oldVal, newVal) {
annotation values are strings, no need for generic `interface{}` and `DeepEqual` here. Use `string` and simple `==`.

2016-11-16 13:01 UTC, jsafrane commented on pkg/api/validation/validation_test.go
> +		"invalid-update-change-storage-class-annotation-after-creation": {
Please add a test that updates another (=allowed) annotation - such update should be valid.

2016-11-16 17:08 UTC, screeley44 commented on pkg/api/validation/validation_test.go
> +		"invalid-update-change-storage-class-annotation-after-creation": {
@jsafrane 

I updated the tests - added a valid change to annotation and a test to make sure an annotation could be added

```
+++ [1116 12:03:37] Running tests without code coverage
ok  	k8s.io/kubernetes/pkg/api/validation	0.341s
```

2016-11-18 08:02 UTC, jsafrane approved these changes

2016-11-18 08:05 UTC, jsafrane commented
lgtm. @smarterclayton PTAL, I'm going to merge it if you don't have any remarks.

2016-11-29 15:09 UTC, screeley44 commented
@jsafrane @smarterclayton - can this be merged?

2016-11-29 15:13 UTC, jsafrane commented
/lgtm

2016-11-29 15:55 UTC, smarterclayton commented
Please squash - you've got a merge commit in there and we don't want merge commits in the normal tree.  Removing lgtm

2016-11-30 11:12 UTC, jsafrane commented
@k8s-bot verify test this

2016-11-30 13:17 UTC, jsafrane commented
/lgtm

2016-11-30 22:47 UTC, screeley44 commented
@smarterclayton - we good now?

2016-12-01 02:23 UTC, smarterclayton commented
Yes

2016-12-01 15:17 UTC, screeley44 commented
@jsafrane - can we merge this now?

2016-12-01 15:35 UTC, jsafrane commented
@screeley44, it's waiting in merge queue. Click on "Submit Queue" in the window with test results to see how it stands. It's a long queue!

2016-12-03 02:42 UTC, merged