[Federation] Make federation etcd PVC size configurable
kubernetes/kubernetes pull request #36310
Opened 2016-11-06 13:42 UTC by irfanurrehman

This PR is on top of https://github.com/kubernetes/kubernetes/pull/36048, which is being reviewed separately.
This one implements one of the many TODO items pending in the previous set of kubefed PRs.
Please review only the last 2 commits of this one.
The design doc PR is at https://github.com/kubernetes/kubernetes/pull/34484

cc  @kubernetes/sig-cluster-federation  @madhusudancs

2016-11-06 13:46 UTC, irfanurrehman commented
I signed it! However I did sign the CNCF CLA quite some time back, thinking that CNCF CLA is what is only required now.

2016-11-06 19:41 UTC, nikhiljindal commented on federation/pkg/kubefed/init/init_test.go
> +			etcdPVCapacity:     "10Gi",
Will be good to have 2 tests: one where you do not specify any value and verify that it picks up 10Gi and one where you specify something other than the default value.

2016-11-06 20:53 UTC, madhusudancs requested changes
@irfanurrehman thank you very much for taking this up. Code looks good to me. I agree with @nikhiljindal's comment on tests. Please make that change and we will get this in.

2016-11-06 20:53 UTC, madhusudancs commented
@k8s-bot ok to test

2016-11-07 11:33 UTC, irfanurrehman commented
@madhusudancs @nikhiljindal please take a look at updated tests.

2016-11-10 08:50 UTC, irfanurrehman commented
rebased the commits of this PR on top of https://github.com/kubernetes/kubernetes/pull/36492.

2016-11-14 22:53 UTC, madhusudancs requested changes

2016-11-14 22:53 UTC, madhusudancs commented on federation/pkg/kubefed/init/init_test.go
> +	if "" != etcdPVCapacity {
This is a strange way to write this. Please make this the more idiomatic `etcdPVCapacity != ""` version.

2016-11-14 22:53 UTC, madhusudancs commented on federation/pkg/kubefed/init/init_test.go
> +	} else {
Drop the else and just hoist this outside the condition. This entire thing then looks like:

```go
pvCap := "10Gi"
if etcdPVCapacity != "" {
    pvCap = etcdPVCapacity
}
```

2016-11-14 22:54 UTC, madhusudancs commented
@irfanurrehman Can you please rebase this on master now?

2016-11-14 22:55 UTC, madhusudancs commented
@irfanurrehman Nevermind, the PR on which this depends (#36492) was already merged, so git/Github automatically does that in the display.

2016-11-16 15:44 UTC, irfanurrehman commented
@madhusudancs thanks for the comments; fixed them, PTAL!

2016-11-16 22:48 UTC, madhusudancs approved these changes

2016-11-16 22:48 UTC, madhusudancs commented on federation/pkg/kubefed/init/init.go
> +
Remove the unnecessary blank line.

2016-11-17 10:00 UTC, irfanurrehman commented
@madhusudancs updated; also if you still find some nits in this PR (I skimmed through the code again), then please take a look at the fix commit (last commit) in the next PR also -> https://github.com/kubernetes/kubernetes/pull/36447

additionally do i need to manually add the new flag names to hack/verify-flags/known-flags.txt ( I see one jenkins build failure repeating for the same), or is there an automated way!
Thanks for all the help!

2016-11-17 18:25 UTC, madhusudancs commented
@irfanurrehman there is no automated way. Run ` hack/verify-flags/known-flags.txt` locally and it tells you what to add where.

2016-11-17 18:26 UTC, madhusudancs commented
LGTM! Thanks for your work @irfanurrehman

2016-11-17 18:44 UTC, madhusudancs commented
@irfanurrehman could you please add a release note for this one too?

2016-11-17 19:58 UTC, irfanurrehman commented
updated hack/verify-flags/known-flags.txt and release note added.
@madhusudancs, you may please update the labels appropriately now.
also, if you find the title more suitable for the rel notes, u can probably remove the one that i did add and put a label "release-note" to use the title.

2016-11-17 22:25 UTC, madhusudancs commented
@irfanurrehman can you please change the tone of the release note to be more informative. Think how you would want to read this if you were a user learning about the changes in the release.

Example:

"""
[Federation] `kubefed init` learned a new flag, `--etcd-pv-capacity`, which can be used to configure the persistent volume capacity for etcd. 
"""

Or something like that.

2016-11-18 07:14 UTC, irfanurrehman commented
@madhusudancs updated as per your suggestions.

2016-12-08 18:50 UTC, madhusudancs commented
LGTM!

2016-12-08 21:03 UTC, merged