Curating Owners: cmd/kube-apiserver
kubernetes/kubernetes pull request #36397
Opened 2016-11-07 23:05 UTC by apelisse

cc @lavalamp @smarterclayton @krousey @nikhiljindal

In an effort to expand the existing pool of reviewers and establish a
two-tiered review process (first someone lgtms and then someone
experienced in the project approves), we are adding new reviewers to
existing owners files.

If You Care About the Process:
------------------------------

We did this by algorithmically figuring out who’s contributed code to
the project and in what directories.  Unfortunately, that doesn’t work
well: people that have made mechanical code changes (e.g change the
copyright header across all directories) end up as reviewers in lots of
places.

Instead of using pure commit data, we generated an excessively large
list of reviewers and pruned based on all time commit data, recent
commit data and review data (number of PRs commented on).

At this point we have a decent list of reviewers, but it needs one last
pass for fine tuning.

Also, see https://github.com/kubernetes/contrib/issues/1389.

TLDR:
-----

As an owner of a sig/directory and a leader of the project, here’s what
we need from you:

1. Use PR https://github.com/kubernetes/kubernetes/pull/35715 as an example.

2. Use the following commit as a suggestion: b89a69d4b4a72322b7d40a5917d71f9ebd6eac60

3. The pull-request is made editable, please edit the `OWNERS` file to
add the names of people that should be reviewing code in the future in
the **reviewers** section. You probably do NOT need to modify the **approvers**
section.

4. Notify me if you want some OWNERS file to be removed.  Being an
approver or reviewer of a parent directory makes you a reviewer/approver
of the subdirectories too, so not all OWNERS files may be necessary.

5. Please use ALIAS if you want to use the same list of people over and
over again (don't hesitate to ask me for help, or use the pull-request
above as an example)

2016-11-09 17:19 UTC, krousey approved these changes

2016-11-09 17:33 UTC, apelisse commented
@krousey no names to remove from the list?

2016-11-09 17:35 UTC, krousey commented
Huh. I was viewing an out of date version where the reviewers was empty. I will go back over this.

2016-11-09 17:43 UTC, krousey requested changes
I'm basing this mostly off the API machinery group.

2016-11-09 17:43 UTC, krousey commented on cmd/kube-apiserver/OWNERS
> +- krousey
Actually. Remove this.

2016-11-09 17:43 UTC, krousey commented on cmd/kube-apiserver/OWNERS
> +- thockin
Remove.

2016-11-09 17:43 UTC, krousey commented on cmd/kube-apiserver/OWNERS
> +- brendandburns
Remove.

2016-11-09 17:43 UTC, krousey commented on cmd/kube-apiserver/OWNERS
> +- mikedanese
Remove.

2016-11-09 17:43 UTC, krousey commented on cmd/kube-apiserver/OWNERS
> +- bprashanth
Remove this and everyone following except `ncdc`

2016-11-09 17:43 UTC, krousey commented on cmd/kube-apiserver/app/OWNERS
> +reviewers:
This should match the other file.

2016-11-09 17:43 UTC, krousey commented on cmd/kube-apiserver/OWNERS
> +approvers:
Add @mml and @caesarxuchao

2016-11-09 17:44 UTC, krousey commented
And now reading the instructions.. I will go back and make the changes I requested.

2016-11-09 17:45 UTC, apelisse commented on cmd/kube-apiserver/app/OWNERS
> +reviewers:
Or actually, we can just remove this file if we want to use the owners file from the parent directory

2016-11-09 17:45 UTC, apelisse commented
Thanks @krousey!

2016-11-09 17:46 UTC, krousey commented on cmd/kube-apiserver/app/OWNERS
> +reviewers:
api-machinery-{reviewers,approvers} ?

2016-11-09 17:47 UTC, apelisse commented on cmd/kube-apiserver/app/OWNERS
> +reviewers:
Sounds good to me! I'll create the alias

2016-11-09 22:33 UTC, apelisse commented
his name is missing from the list, but consider adding "AdoHe"

2016-11-18 23:08 UTC, lavalamp commented on cmd/kube-apiserver/app/OWNERS
> +reviewers:
I vote remove this file and inherit from parent directory.

2016-12-13 00:04 UTC, apelisse commented
@krousey @lavalamp I've made the changes and removed the sub-file. Please lgtm if you're ok with this.

2017-01-07 01:15 UTC, lavalamp commented
/lgtm

@krousey you're still marked as wanting changes, not sure if the bot will care about that.

2017-01-13 18:03 UTC, apelisse commented
@k8s-bot bazel test this

2017-01-13 18:07 UTC, apelisse commented
@k8s-bot kops aws e2e test this

2017-01-13 18:56 UTC, merged