Add `clusterid` optional parameter to storageclass.
kubernetes/kubernetes pull request #36437
Opened 2016-11-08 12:47 UTC by humblec

At present, admin doesn't have the privilege to chose the
trusted storage pool from which persistent gluster volume
has to be provided.

This patch introduce a new storage class parameter which allows
the admin to specify storage pool/cluster if required.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2016-11-08 19:24 UTC, zmerlynn commented
@k8s-bot ok to test

2016-11-14 12:56 UTC, jsafrane requested changes

2016-11-14 12:56 UTC, jsafrane commented on pkg/volume/glusterfs/glusterfs.go
> +	clusterid       string
camel case please, i.e. `clusterId`

2016-11-14 12:56 UTC, jsafrane commented on pkg/volume/glusterfs/glusterfs.go
> +	annGlusterClusterId       = "glusterfs.kubernetes.io/clusterid"
This annotation is not used anywhere, please remove it.
[Also, if you like, you can trim the other unused annotations too]

2016-11-14 12:56 UTC, jsafrane commented on pkg/volume/glusterfs/glusterfs.go
> +	clusterids := dstrings.Split(p.clusterid, ",")
camel xase please

2016-11-15 02:52 UTC, humblec commented on pkg/volume/glusterfs/glusterfs.go
> +	annGlusterClusterId       = "glusterfs.kubernetes.io/clusterid"
Done.

2016-11-15 02:52 UTC, humblec commented on pkg/volume/glusterfs/glusterfs.go
> +	clusterid       string
Done.

2016-11-15 02:52 UTC, humblec commented on pkg/volume/glusterfs/glusterfs.go
> +	clusterids := dstrings.Split(p.clusterid, ",")
Done

2016-11-15 03:00 UTC, humblec commented
@jsafrane Thanks ! Addressed your comments and also rebased the patch.

2016-11-16 15:06 UTC, jsafrane approved these changes

2016-11-16 15:07 UTC, jsafrane commented
/lgtm for 1.6

2016-11-18 15:03 UTC, humblec commented
@jsafrane Rebased the patch to master.

2016-11-18 15:57 UTC, jsafrane commented
/lgtm

2016-11-23 07:29 UTC, humblec commented
@jsafrane once again rebased :) , it removed LGTM.

2016-11-23 12:18 UTC, jsafrane commented
/lgtm

2016-11-23 14:03 UTC, jsafrane commented
/lgtm
!!!

2016-11-28 12:09 UTC, jsafrane commented
@k8s-bot kubemark e2e test this

2016-12-01 14:31 UTC, merged