Curating Owners: pkg/api
kubernetes/kubernetes pull request #36525
Opened 2016-11-09 18:18 UTC by apelisse

cc @lavalamp @smarterclayton @erictune @thockin @bgrant0607

In an effort to expand the existing pool of reviewers and establish a
two-tiered review process (first someone lgtms and then someone
experienced in the project approves), we are adding new reviewers to
existing owners files.

If You Care About the Process:
------------------------------

We did this by algorithmically figuring out who’s contributed code to
the project and in what directories.  Unfortunately, that doesn’t work
well: people that have made mechanical code changes (e.g change the
copyright header across all directories) end up as reviewers in lots of
places.

Instead of using pure commit data, we generated an excessively large
list of reviewers and pruned based on all time commit data, recent
commit data and review data (number of PRs commented on).

At this point we have a decent list of reviewers, but it needs one last
pass for fine tuning.

Also, see https://github.com/kubernetes/contrib/issues/1389.

TLDR:
-----

As an owner of a sig/directory and a leader of the project, here’s what
we need from you:

1. Use PR https://github.com/kubernetes/kubernetes/pull/35715 as an example.

2. The pull-request is made editable, please edit the `OWNERS` file to
remove the names of people that shouldn't be reviewing code in the
future in the **reviewers** section. You probably do NOT need to modify
the **approvers** section. Names asre sorted by relevance, using some
secret statistics.

3. Notify me if you want some OWNERS file to be removed.  Being an
approver or reviewer of a parent directory makes you a reviewer/approver
of the subdirectories too, so not all OWNERS files may be necessary.

4. Please use ALIAS if you want to use the same list of people over and
over again (don't hesitate to ask me for help, or use the pull-request
above as an example)

2016-11-09 22:39 UTC, apelisse commented
his name is missing from the list, but consider adding "ArtfulCoder"

2016-11-15 07:55 UTC, thockin commented
This needs some work.

On Fri, Nov 11, 2016 at 2:19 PM, grodrigues3 <notifications@github.com>
wrote:

> Assigned #36525 <https://github.com/kubernetes/kubernetes/pull/36525> to
> @thockin <https://github.com/thockin>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/36525#event-856502346>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVJONukdcipeM05VYJ0bj3ElhQSiwks5q9OoKgaJpZM4Kt1Bz>
> .
>

2016-11-18 23:13 UTC, thockin commented
I'm going to approve and fixup later

2016-11-18 23:17 UTC, thockin commented
@apelisse actually, can you just keep the top-level OWNERS here, and nix the rest?

2016-11-18 23:39 UTC, lavalamp requested changes

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/annotations/OWNERS
> +- david-mcmahon
remove, add lavalamp

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/endpoints/OWNERS
> +- david-mcmahon
remove, add lavalamp

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/errors/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/errors/OWNERS
> +- goltermann
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/events/OWNERS
> +- kargakis
add lavalamp

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/install/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/meta/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/meta/OWNERS
> +- smarterclayton
add lavalamp

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/pod/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/resource/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/rest/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/rest/OWNERS
> +- smarterclayton
add lavalamp

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/service/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/service/OWNERS
> +- girishkalele
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/testapi/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/unversioned/OWNERS
> +- brendandburns
remove, add lavalamp

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/unversioned/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/util/OWNERS
> +- david-mcmahon
remove

2016-11-18 23:39 UTC, lavalamp commented on pkg/api/v1/OWNERS
> +- brendandburns
remove

2016-11-19 00:00 UTC, thockin commented
@lavalamp - you can hand edit the PR but it is tedious.  Or we can just use
top-level OWNERS for this dir

On Fri, Nov 18, 2016 at 3:40 PM, Daniel Smith <notifications@github.com>
wrote:

> *@lavalamp* requested changes on this pull request.
> ------------------------------
>
> In pkg/api/annotations/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,4 @@
> +reviewers:
> +- dims
> +- david-mcmahon
>
> remove, add lavalamp
> ------------------------------
>
> In pkg/api/endpoints/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,8 @@
> +reviewers:
> +- thockin
> +- smarterclayton
> +- mikedanese
> +- sttts
> +- eparis
> +- resouer
> +- david-mcmahon
>
> remove, add lavalamp
> ------------------------------
>
> In pkg/api/errors/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > +- liggitt
> +- nikhiljindal
> +- gmarek
> +- erictune
> +- saad-ali
> +- janetkuo
> +- timstclair
> +- eparis
> +- timothysc
> +- dims
> +- spxtr
> +- hongchaodeng
> +- krousey
> +- satnam6502
> +- cjcullen
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/errors/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > +- nikhiljindal
> +- gmarek
> +- erictune
> +- saad-ali
> +- janetkuo
> +- timstclair
> +- eparis
> +- timothysc
> +- dims
> +- spxtr
> +- hongchaodeng
> +- krousey
> +- satnam6502
> +- cjcullen
> +- david-mcmahon
> +- goltermann
>
> remove
> ------------------------------
>
> In pkg/api/events/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,2 @@
> +reviewers:
> +- kargakis
>
> add lavalamp
> ------------------------------
>
> In pkg/api/install/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,11 @@
> +reviewers:
> +- lavalamp
> +- smarterclayton
> +- deads2k
> +- caesarxuchao
> +- liggitt
> +- nikhiljindal
> +- dims
> +- krousey
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/meta/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > +- derekwaynecarr
> +- caesarxuchao
> +- mikedanese
> +- liggitt
> +- nikhiljindal
> +- gmarek
> +- kargakis
> +- janetkuo
> +- ncdc
> +- eparis
> +- dims
> +- krousey
> +- markturansky
> +- fabioy
> +- resouer
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/meta/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,26 @@
> +reviewers:
> +- thockin
> +- smarterclayton
>
> add lavalamp
> ------------------------------
>
> In pkg/api/pod/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,4 @@
> +reviewers:
> +- smarterclayton
> +- kargakis
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/resource/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > +reviewers:
> +- thockin
> +- lavalamp
> +- smarterclayton
> +- wojtek-t
> +- derekwaynecarr
> +- mikedanese
> +- saad-ali
> +- janetkuo
> +- timstclair
> +- eparis
> +- timothysc
> +- jbeda
> +- xiang90
> +- mbohlool
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/rest/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > +- justinsb
> +- roberthbailey
> +- ncdc
> +- eparis
> +- timothysc
> +- dims
> +- hongchaodeng
> +- krousey
> +- jszczepkowski
> +- euank
> +- markturansky
> +- fgrzadkowski
> +- satnam6502
> +- fabioy
> +- ingvagabund
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/rest/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,35 @@
> +reviewers:
> +- thockin
> +- smarterclayton
>
> add lavalamp
> ------------------------------
>
> In pkg/api/service/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,5 @@
> +reviewers:
> +- justinsb
> +- girishkalele
> +- freehan
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/service/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,5 @@
> +reviewers:
> +- justinsb
> +- girishkalele
>
> remove
> ------------------------------
>
> In pkg/api/testapi/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > +- smarterclayton
> +- wojtek-t
> +- deads2k
> +- caesarxuchao
> +- mikedanese
> +- liggitt
> +- nikhiljindal
> +- bprashanth
> +- erictune
> +- timstclair
> +- eparis
> +- soltysh
> +- madhusudancs
> +- markturansky
> +- mml
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/unversioned/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,33 @@
> +reviewers:
> +- thockin
> +- smarterclayton
> +- wojtek-t
> +- deads2k
> +- brendandburns
>
> remove, add lavalamp
> ------------------------------
>
> In pkg/api/unversioned/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > +- sttts
> +- quinton-hoole
> +- kargakis
> +- luxas
> +- janetkuo
> +- justinsb
> +- ncdc
> +- timothysc
> +- soltysh
> +- dims
> +- madhusudancs
> +- hongchaodeng
> +- krousey
> +- mml
> +- mbohlool
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/util/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,3 @@
> +reviewers:
> +- caesarxuchao
> +- david-mcmahon
>
> remove
> ------------------------------
>
> In pkg/api/v1/OWNERS
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>
> :
>
> > @@ -0,0 +1,41 @@
> +reviewers:
> +- thockin
> +- lavalamp
> +- smarterclayton
> +- wojtek-t
> +- deads2k
> +- yujuhong
> +- brendandburns
>
> remove
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/36525#pullrequestreview-9327421>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVKbKoZnMzbNTyPe3u7F5mZ24ypD_ks5q_jdwgaJpZM4Kt1Bz>
> .
>

2016-11-28 19:44 UTC, merged