Fixing spark e2e test failures.
kubernetes/kubernetes pull request #36548
Opened 2016-11-10 00:40 UTC by foxish

**What this PR does / why we need it**: Fixes e2e test failures in the spark tests. These failures were caused by an update to the examples in https://github.com/kubernetes/kubernetes/pull/33604

**Which issue this PR fixes** : fixes https://github.com/kubernetes/kubernetes/issues/36102

**Release note**:
```release-note
NONE
```

cc @calebamiles @elsonrodriguez

2016-11-10 00:43 UTC, foxish commented
@jimmycuadra @elsonrodriguez PTAL

2016-11-10 01:13 UTC, foxish commented
@k8s-bot cvm gke e2e test this

2016-11-10 01:27 UTC, jimmycuadra commented
Did you mean to assign me on this one? I don't have any context for this code.

2016-11-10 01:58 UTC, foxish commented
@k8s-bot kubemark e2e test this

2016-11-10 01:59 UTC, foxish commented
@jimmycuadra Unassigned. I assigned you as you dealt with the e2e tests for cassandra recently.

2016-11-10 02:20 UTC, jimmycuadra commented
Ah. That was just a follow up to a previous PR I made finishing some of the petset rename stuff.

2016-11-10 02:30 UTC, elsonrodriguez commented
@foxish looks good, but next time don't shy away from asking for an example fix if it makes sense.

2016-11-10 02:44 UTC, foxish commented
@elsonrodriguez I felt that the way the examples are written right now makes sense, with the namespace. Perhaps we could have kept the namespace from the example YAMLs, and just changed the instructions to specify `--namespace=` with each kubectl command. I'm not sure which I prefer.

2016-11-10 18:30 UTC, chrislovecnm requested changes
A couple of recommendation.  Thank for addressing this!!

2016-11-10 18:30 UTC, chrislovecnm commented on test/e2e/examples.go
> +			err := c.Core().Namespaces().Delete(nsSpark, nil)
We just throwing a pain here if the build framework is borked?

2016-11-10 18:30 UTC, chrislovecnm commented on test/e2e/examples.go
> +			nsYaml := mkpath("namespace-spark-cluster.yaml")
Can we check that this file exists.  This bit me in a C* e2e test.

2016-11-11 18:52 UTC, janetkuo commented
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/e2e/examples.go, line 145 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36548#-KWJgiwbCljhvdoi81UV:-KWJgiwbCljhvdoi81UW:b-wx87ll) ([raw file](https://github.com/kubernetes/kubernetes/blob/81dde54c17f88484c44eeb1da03d45f62e2ab2f3/test/e2e/examples.go#L145)):*
> ```Go
> 
> 	framework.KubeDescribe("Spark", func() {
> 		nsSpark := "spark-cluster" // TODO: find a way to infer this from the yaml.
> ```

Can we just remove the namespace in all spark yaml files? In the examples, the namespace is already set to `spark-cluster`, therefore, specifying namespace in the yaml isn't necessary. Plus the namespace used in test should be unique.

---

*[test/e2e/examples.go, line 148 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36548#-KWJiy-AQ3ZDPAJZ12WS:-KWJiy-AQ3ZDPAJZ12WT:bnouga) ([raw file](https://github.com/kubernetes/kubernetes/blob/81dde54c17f88484c44eeb1da03d45f62e2ab2f3/test/e2e/examples.go#L148)):*
> ```Go
> 		AfterEach(func() {
> 			// clean up the spark namespace.
> 			err := c.Core().Namespaces().Delete(nsSpark, nil)
> ```

Need to change this if removing nsSpark

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36548)*
<!-- Sent from Reviewable.io -->

2016-11-11 19:46 UTC, foxish commented
@janetkuo I misunderstood how the example worked. You're right, this change would be unnecessary; and removing the `namespace` from the example YAMLs should suffice. Will update. Thanks!

2016-11-11 20:00 UTC, foxish commented
@janetkuo PTAL. Updated.

2016-11-11 20:22 UTC, chrislovecnm commented on test/e2e/examples.go
> +			err := c.Core().Namespaces().Delete(nsSpark, nil)
Panic not pain ...

2016-11-11 21:11 UTC, janetkuo commented
/lgtm

2016-11-11 21:57 UTC, merged