Add CONTRIBUTING section on build
kubernetes/kubernetes pull request #36590
Opened 2016-11-10 18:06 UTC by thockin

@kubernetes/contributor-experience

2016-11-10 18:22 UTC, chrislovecnm commented
YAY ... assigned to a PR :)

2016-11-10 18:24 UTC, grodrigues3 commented
lgtm

2016-11-10 18:25 UTC, dims commented on CONTRIBUTING.md
> +WHAT="pkg/kubelet"`.
"cmd/kubectl" may be a better example as it generates a binary folks can use!

2016-11-10 18:26 UTC, chrislovecnm requested changes
A couple of tweaks to talk about.  Excited that we are improving this!!!

2016-11-10 18:26 UTC, chrislovecnm commented on CONTRIBUTING.md
> +There are a few things you need to build and test Kubernetes:
> Build and test Kubernetes

This project?

2016-11-10 18:26 UTC, chrislovecnm commented on CONTRIBUTING.md
> +   recent version of the Go toolchain installed.
Which platforms does this work on?  Windows?  Also should we link a n00b doc that has links to install instructions for each.  I always approach this as a really really dumb perspective :)

2016-11-10 18:26 UTC, chrislovecnm commented on CONTRIBUTING.md
> +WHAT="pkg/kubelet"`.
```console
$ make
```

2016-11-10 18:26 UTC, chrislovecnm commented on CONTRIBUTING.md
> +To build Kubernetes, simply type `make`.  This should figure out what it needs
Type on a command line...

2016-11-10 18:26 UTC, chrislovecnm commented on CONTRIBUTING.md
> +can pass the `WHAT` variable to `make`: e.g. `make test WHAT=pkg/kubelet`.
> variable

environment variable :)

2016-11-10 18:36 UTC, philips reviewed
Improvement

2016-11-10 18:36 UTC, philips commented on CONTRIBUTING.md
> +   need a relatively recent version of Docker installed, and available to you.
this needs a link to our recommendation. I would suggest minikube onboarding and docker-env.

2016-11-10 18:36 UTC, philips commented on CONTRIBUTING.md
> +To build Kubernetes, simply type `make`.  This should figure out what it needs
You will need to git clone it first too :)

2016-11-10 18:46 UTC, spxtr commented
It might be worth adding a line saying that we are investigating bazel with a link to the doc about that.

2016-11-10 19:30 UTC, chrislovecnm commented
@spxtr I don't want to talk about how the build runs, I would recommend talking about how to run the build :)  Bazel is awesome, but can we document that separately.

2016-11-10 19:34 UTC, spxtr commented on CONTRIBUTING.md
> +There are a few things you need to build and test Kubernetes:
You need a newline after this or the list won't render properly.

2016-11-10 19:34 UTC, spxtr commented
@chrislovecnm that's reasonable.

2016-11-10 20:46 UTC, pigmej commented
I have some suggestion can we somehow recommend using https://github.com/Mirantis/k8s-devbox and/or https://github.com/Mirantis/kubeadm-dind-cluster as a *fast* way to test your stuff? devbox is supposed to create reproducible development environment for working on Kubernetes project and there are some plans to add kubeadm to it which will allow to play with remote clusters too. I'm open to suggestions there. (cc @ivan4th author of these).

2016-11-10 21:04 UTC, ivan4th commented on CONTRIBUTING.md
> +   need a relatively recent version of Docker installed, and available to you.
[According to Dan Lorenc](https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/XFODRr_TXgE/hmJ_5v5LCgAJ), minikube is targeting k8s end users. Using it for development of Kubernetes may be [not very convenient](https://github.com/kubernetes/minikube/blob/master/UPDATE_KUBERNETES.md). Or did I miss something here? Also, minikube by itself is probably overkill if the developer just wants to have docker.

2016-11-10 21:11 UTC, ivan4th commented
@jnowak: to be more precise, k8s-devbox tries to help getting k8s development environment up&running quickly and also tries to help new developers getting acquinted with k8s development workflow. As of now it uses [kubernetes-dind-cluster](https://github.com/sttts/kubernetes-dind-cluster) as a fast method of *multinode* test cluster startup, but it will support [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) soon. The latter uses kubeadm to create docker-in-docker-based cluster and supports workflows based on remote docker engine (copy binaries directly from the build data container & run the test cluster on the same remote docker where they were built). Both of these projects support running e2e tests locally, including ones requiring multiple nodes (unlike local-up-cluster). They're also much faster than VM-based clusters.

2016-11-10 21:14 UTC, pigmej commented on CONTRIBUTING.md
> +   need a relatively recent version of Docker installed, and available to you.
+1 for Ivan, minikube is *not* for developers, for developers look at https://github.com/kubernetes/kubernetes/pull/36590#issuecomment-259802736 or https://github.com/kubernetes/kubernetes/pull/36590#issuecomment-259808686

2016-11-11 07:20 UTC, thockin commented on CONTRIBUTING.md
> +WHAT="pkg/kubelet"`.
Done

2016-11-11 07:20 UTC, thockin commented on CONTRIBUTING.md
> +There are a few things you need to build and test Kubernetes:
Done

2016-11-11 07:33 UTC, thockin commented on CONTRIBUTING.md
> +To build Kubernetes, simply type `make`.  This should figure out what it needs
ok, adding some words about downloads.

2016-11-11 07:33 UTC, thockin commented on CONTRIBUTING.md
> +WHAT="pkg/kubelet"`.
disagree - this is a commandline, not a console log.

2016-11-11 07:34 UTC, thockin commented on CONTRIBUTING.md
> +can pass the `WHAT` variable to `make`: e.g. `make test WHAT=pkg/kubelet`.
This is not an env var, it is a make var.  I think env vars also work, but that is not what is being shown here

2016-11-11 07:37 UTC, thockin commented
All, this doc is NOT an encyclopedic listing of everythign you need to know about how to use kube.  It is an intro doc.  Feel free to send followups that link to more details.

2016-11-11 20:26 UTC, chrislovecnm commented on CONTRIBUTING.md
> +can pass the `WHAT` variable to `make`: e.g. `make test WHAT=pkg/kubelet`.
Touche

2016-11-11 20:27 UTC, chrislovecnm commented on CONTRIBUTING.md
> +WHAT="pkg/kubelet"`.
Sounds good

2016-11-11 20:28 UTC, chrislovecnm commented
@thockin do we need an issue for an encyclopedic version of this doc?

2016-11-11 22:59 UTC, thockin commented
Probably.  I am on mobile now, can do later

On Nov 11, 2016 12:29 PM, "Chris Love" <notifications@github.com> wrote:

> @thockin <https://github.com/thockin> do we need an issue for an
> encyclopedic version of this doc?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/36590#issuecomment-260048374>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVFwMq_KokVih5hyMSsV2We8DUdJvks5q9NAKgaJpZM4Ku9rn>
> .
>

2016-11-14 23:37 UTC, bgrant0607 commented
@thockin It shouldn't block this PR, but I'd like this doc to be very brief, with links to more information, which won't live in the kubernetes repo.

2016-11-14 23:39 UTC, bgrant0607 commented on CONTRIBUTING.md
> +To build Kubernetes, simply type `make`.  This should figure out what it needs
#36655 claims that this doesn't work.

2016-11-14 23:39 UTC, bgrant0607 commented
cc @sebgoa

2016-11-14 23:40 UTC, bgrant0607 commented
Let's merge and iterate.
LGTM.

2016-11-15 08:46 UTC, sebgoa commented on CONTRIBUTING.md
> +To build Kubernetes, simply type `make`.  This should figure out what it needs
it does not work, if you don't have a go environment setup and use the documented `build-tools.sh/make`

2016-11-22 19:56 UTC, philips reviewed
Overall I am not going to fight this Docker version thing but we are honestly too close to the tech here to think "just install some known good version of Docker" is good enough as a developer onramp.

2016-11-22 19:56 UTC, philips commented on CONTRIBUTING.md
> +   need a relatively recent version of Docker installed, and available to you.
Sure "but pretty much any recent version" is not sufficient and I would really just like us to punt to somewhere where we know a known good version is being maintained. For cross-platform availability for workstations the closest thing we got is minikube.

@ivan4th @pigmej Also, it isn't for k8s developer but it is a known good version of the Docker engine that the k8s community tests and packages as VMs.

2016-11-22 20:02 UTC, thockin commented
If I knew where to punt, I would

On Tue, Nov 22, 2016 at 11:57 AM, Brandon Philips <notifications@github.com>
wrote:

> *@philips* commented on this pull request.
>
> Overall I am not going to fight this Docker version thing but we are
> honestly too close to the tech here to think "just install some known good
> version of Docker" is good enough as a developer onramp.
> ------------------------------
>
> In CONTRIBUTING.md
> <https://github.com/kubernetes/kubernetes/pull/36590#pullrequestreview-9745074>
> :
>
> > @@ -82,6 +82,27 @@ some bugs or smaller features.  We have a [feature development
>  process](https://github.com/kubernetes/features/blob/master/README.md), but
>  navigating the Kubernetes system as a newcomer can be very challenging.
>
> +### Building the project
> +
> +There are a few things you need to build and test Kubernetes:
> +1. `make` - the human interface to the Kubernetes build is `make`, so you must
> +   have this tool installed on your machine.  We try not to use too many crazy
> +   features of `Makefile`s and other tools, so most commonly available versions
> +   should work.
> +1. `docker` - some parts of the build/test system depend on `docker`.  You
> +   need a relatively recent version of Docker installed, and available to you.
>
> Sure "but pretty much any recent version" is not sufficient and I would
> really just like us to punt to somewhere where we know a known good version
> is being maintained. For cross-platform availability for workstations the
> closest thing we got is minikube.
>
> @ivan4th <https://github.com/ivan4th> @pigmej <https://github.com/pigmej>
> Also, it isn't for k8s developer but it is a known good version of the
> Docker engine that the k8s community tests and packages as VMs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/36590#pullrequestreview-9745074>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVFODNXFc9BHHMWXzbVWdDpsh1fIFks5rA0kbgaJpZM4Ku9rn>
> .
>

2016-11-22 22:48 UTC, philips commented
@thockin I am suggesting we punt to minikube and force minikube to have a good docker install story on all platforms.

2016-11-28 19:42 UTC, merged