[Federation][Bugfix] Fix some flakes with kubefed init
kubernetes/kubernetes pull request #36597
Opened 2016-11-10 18:55 UTC by irfanurrehman

this PR is the fix for https://github.com/kubernetes/kubernetes/issues/36587

cc @kubernetes/sig-cluster-federation @madhusudancs @nikhiljindal

2016-11-10 19:26 UTC, madhusudancs requested changes

2016-11-10 19:26 UTC, madhusudancs commented on federation/pkg/kubefed/init/init.go
> +								fmt.Sprintf("--master=https://%s-apiserver", name),
The fix for this is already here - https://github.com/kubernetes/kubernetes/pull/36294

2016-11-10 19:26 UTC, madhusudancs commented on federation/pkg/kubefed/init/init.go
> +	hyperkubeImageName = "gcr.io/google_containers/hyperkube-amd64:v1.5.0-beta.0"
See my comment on the issue.

2016-11-15 08:54 UTC, irfanurrehman commented
as the fix for one of the issues already exists at https://github.com/kubernetes/kubernetes/pull/36294
and the fix in this PR for the second is not the best one, closing this PR

2016-11-15 08:54 UTC, closed without merging