kubectl: add create pdb subcommand
kubernetes/kubernetes pull request #36646
Opened 2016-11-11 10:59 UTC by kargakis

@mwielgus @mml @kubernetes/kubectl

2016-11-11 11:33 UTC, mwielgus commented
This is a new feature and, as it is feature freeze, requires an exception to get into 1.5. 
See: https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md

2016-11-11 11:44 UTC, kargakis commented
> This is a new feature and, as it is feature freeze, requires an exception to get into 1.5.
> See: https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md

Not required to get into 1.5, there is no milestone in the PR.

2016-11-11 12:05 UTC, mwielgus commented
Can we review/merge it as soon as the 1.5 release is cut and fully branched?

2016-11-11 12:06 UTC, kargakis commented
SGTM

2016-11-11 16:59 UTC, ymqytw commented on pkg/kubectl/cmd/create_pdb.go
> +	cmd.Flags().String("min-available", "1", "The minimum number of available pods this budget requires.")
Cloud be percentage.

2016-11-11 17:18 UTC, smarterclayton commented
Primary name should be full resource name, acronym should be the alias.

On Nov 11, 2016, at 8:59 AM, Mengqi Yu <notifications@github.com> wrote:

*@ymqytw* commented on this pull request.
------------------------------

In pkg/kubectl/cmd/create_pdb.go
<https://github.com/kubernetes/kubernetes/pull/36646#pullrequestreview-8229681>
:

> +		Use:     "pdb NAME --selector=SELECTOR --min-available=N [--dry-run]",
+		Aliases: []string{"poddisruptionbudget"},
+		Short:   "Create a pod disruption budget with the specified name.",
+		Long:    pdbLong,
+		Example: pdbExample,
+		Run: func(cmd *cobra.Command, args []string) {
+			err := CreatePodDisruptionBudget(f, cmdOut, cmd, args)
+			cmdutil.CheckErr(err)
+		},
+	}
+
+	cmdutil.AddApplyAnnotationFlags(cmd)
+	cmdutil.AddValidateFlags(cmd)
+	cmdutil.AddPrinterFlags(cmd)
+	cmdutil.AddGeneratorFlags(cmd, cmdutil.PodDisruptionBudgetV1GeneratorName)
+	cmd.Flags().String("min-available", "1", "The minimum number of
available pods this budget requires.")

Cloud be percentage.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/36646#pullrequestreview-8229681>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ABG_p6Tt46MamhAShH-a0vKjNr0xgZAuks5q9J7pgaJpZM4KvpBN>
.

2016-11-15 09:19 UTC, soltysh requested changes
Plus what Clayton asked about naming.

2016-11-15 09:19 UTC, soltysh commented on pkg/kubectl/cmd/create_pdb.go
> +	cmd.Flags().String("min-available", "1", "The minimum number of available pods this budget requires.")
Generally, both values should be allowed, similarly to what we have in the spec.

2016-11-15 09:19 UTC, soltysh commented on pkg/kubectl/pdb.go
> +/*
Thinking out loud, with the number of generators we should have a separate package for them, created #36805 to discuss the idea further.

2016-11-15 14:21 UTC, kargakis commented on pkg/kubectl/cmd/create_pdb.go
> +	cmd.Flags().String("min-available", "1", "The minimum number of available pods this budget requires.")
Updated the flag text to reflect it, percentages are already handled.

2016-11-15 14:29 UTC, kargakis commented
Updated primary name to be the full resource name and set alias for poddisruptionbudget to pdb.

2016-11-15 15:00 UTC, soltysh commented on pkg/kubectl/cmd/create_pdb.go
> +		$ kubectl create poddisruptionbudget my-pdb --selector=app=rails --min-available=1`)
Can you please add percentage example, so that it's obvious how to do it? Some people might wonder if `.2` or `20%` is preferred :wink:

2016-11-15 15:00 UTC, soltysh approved these changes

2016-11-15 15:01 UTC, soltysh commented
One nit, otherwise LGTM. When updating the PR, mind splitting this into 2 commits, first adding create pdb, and 2nd with the generated stuff?

2016-11-18 12:48 UTC, kargakis commented on pkg/kubectl/cmd/create_pdb.go
> +		$ kubectl create poddisruptionbudget my-pdb --selector=app=rails --min-available=1`)
Done

2016-11-21 09:10 UTC, soltysh reviewed
One more nit. Besides you can squash the alias commit into the first one.

2016-11-21 09:10 UTC, soltysh commented on hack/make-rules/test-cmd.sh
> +  kube::test::get_object_assert 'pdb/test-pdb --namespace=test-kubectl-describe-pod' "{{$pdb_min_available}}" '2'
Can we have one another test for the percentage value as well?

2016-11-21 09:42 UTC, kargakis commented
> One more nit. Besides you can squash the alias commit into the first one.

I prefer to keep them separate.

2016-12-02 17:42 UTC, kargakis commented on hack/make-rules/test-cmd.sh
> +  kube::test::get_object_assert 'pdb/test-pdb --namespace=test-kubectl-describe-pod' "{{$pdb_min_available}}" '2'
done

2016-12-03 18:09 UTC, soltysh commented
@k8s-bot kops aws e2e test this

2016-12-03 18:10 UTC, soltysh commented
This LGTM, I'm tagging for merge.

2016-12-03 18:58 UTC, soltysh commented
@k8s-bot kops aws e2e test this

2016-12-03 22:20 UTC, merged