allow auth proxy to set groups and extra
kubernetes/kubernetes pull request #36774
Opened 2016-11-14 21:19 UTC by deads2k

This allows a trusted front proxy to set headers on requests to the API server which will set groups and extra information on the resulting user.Info.

I got here by building a apifederation server which terminated TLS and thus terminated client cert authentication.  Once you've done that, you have to proxy the request the final API server, but identify that request as being for a different user.  I initially built that using impersonation and it worked quite well.  Unfortunately, that exposes a bearer token which has the power to impersonate all users.  

The proxy always has the power to do anything on the cluster (I can say I'm anyone), but using a request header approach means that I don't have to propagate those powers to every constituent API server.  This does mean that the initial config is a little more difficult since you have to create CAs and communicate those to pods which should live in different namespaces.

@kubernetes/sig-auth

2016-11-15 13:13 UTC, deads2k commented
@k8s-bot unit test this: issue #36814

2016-11-15 15:21 UTC, liggitt requested changes

2016-11-15 15:21 UTC, liggitt commented on plugin/pkg/auth/authenticator/request/headerrequest/requestheader_test.go
> +				"X-Remote-Extra-2-key2": {"golf", "hotel"},
Mix-case the header names to test normalization. Test the edge case where the header name is exactly the prefix (would we allow an extra key of ""?)

2016-11-15 15:21 UTC, liggitt commented on plugin/pkg/auth/authenticator/request/headerrequest/requestheader.go
> +			if !strings.HasPrefix(headerName, prefix) {
this assumes exact case match between the normalized header off the request and the configured prefix... have to normalize both to lower-case, I think

2016-11-16 15:42 UTC, deads2k commented on plugin/pkg/auth/authenticator/request/headerrequest/requestheader_test.go
> +				"X-Remote-Extra-2-key2": {"golf", "hotel"},
yeah, I would.

2016-11-16 15:43 UTC, deads2k commented
comments addressed.

2016-11-16 16:05 UTC, liggitt approved these changes

2016-11-16 16:06 UTC, liggitt commented
LGTM, attach the release note to the bit that actually exposes the option to enable it?

2016-12-04 02:03 UTC, merged