improve readme for contributor experience
kubernetes/kubernetes pull request #36817
Opened 2016-11-15 14:05 UTC by sebgoa

**What this PR does / why we need it**:

This improves the top-level README. Removes broken links, removes links to make you bounce to another page, adds proper links to docs.
Shuffles things around a bit and improves reading.

@kubernetes/contributor-experience

2016-11-15 15:43 UTC, metral commented
This PR removes links to external community efforts around k8s, e.g. Awesome-Kubernetes & CoreKube etc. - (I started CoreKube).

Is it worth it to place these efforts in a separate page dedicated for community resources as folks still find these sorts of efforts helpful?

2016-11-15 15:50 UTC, sebgoa commented
To plead my case, as I mentioned on twitter, I was doing a review of the README and when I hit the bottom I saw those links. CoreKube is really nice but the collections page is empty.

I pondered a lot on what to do with them, and then decided to remove them.

I think they would be better on the website. there is a big community page that needs lots of love. There is also a big Tools page that needs love as well.

2016-11-15 15:53 UTC, metral commented
Makes total sense 👍 .

I'll defer to Sarah to suggest a more appropriate home for these sorts of pages.

2016-11-15 17:47 UTC, bgrant0607 commented
cc @kubernetes/docs

2016-11-15 18:01 UTC, bgrant0607 commented
Copying from slack:

I don't think we should link to community resources from kubernetes/README.md. We should find a place on kubernetes.io for them. 

Files to remove:
* CONTRIB.md
* DESIGN.md
* contrib/README.md
* docs/warning.png
* docs/roadmap.md
* docs/troubleshooting.md
* docs/whatisk8s.md
* www/README.md

2016-11-15 18:28 UTC, bgrant0607 requested changes

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
>  Kubernetes is:
Please remove these bullets.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +### Kubernetes is ready for Production !
I'd just remove this subsection.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +### Kubernetes can run anywhere !
I'd just remove this subsection.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +  * Interested in hacking on the core Kubernetes code base, developing tools using the Kubernetes API or helping in anyway possible ?  Keep reading!
or helping with the project

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +## Concepts Overview
Please remove this subsection.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +Do you want to help " shape the evolution of technologies that are container packaged, dynamically scheduled and microservices oriented? ". If you are a company, you should consider joining the [CNCF
container-packaged
microservices-oriented

English is right-associative.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +Join us on social media and read our blog:
I'd prefer to link to kubernetes.io (e.g., http://kubernetes.io/community/) and keep this simpler. If some of this info isn't easily found there, we should fix that.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +* [kubecon](http://events.linuxfoundation.org/events/kubecon)
Hmm. I don't see info about kubecon on kubernetes.io. That would be useful to fix.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +*  The community [expectations](docs/devel/community-expectations.md)
@michelleN We'll need to update these links when the developer docs are moved.

2016-11-15 18:28 UTC, bgrant0607 commented on README.md
> +## Documentation
There's a link to the doc site above, so I think we can just remove this section.

2016-11-15 18:29 UTC, bgrant0607 commented
Thanks for the cleanup, @sebgoa!

2016-11-15 19:40 UTC, michelleN commented on README.md
> +*  The community [expectations](docs/devel/community-expectations.md)
Will do

2016-11-15 19:58 UTC, sebgoa commented
Ok addressed all comments.

I kept some links in the community section, just made it a bit more compact. I will make sure to revisit once the kubernetes.io/community page gets in a better state.

Ideally I would like to add a simple build section once I get passed https://github.com/kubernetes/kubernetes/issues/36655 , showing how you can build k8s in two bash commands will be powerful.

2016-11-15 20:01 UTC, sebgoa commented
I think we could also remove code-of-conduct.md since it is now a link to cncf. I am linking directly to it in the readme.

2016-11-15 22:18 UTC, bgrant0607 commented
@sebgoa code-of-conduct.md is currently part of the repo template. If we remove it here, we should make a similar change to the template. philips may have an opinion on that.

2016-11-15 22:19 UTC, bgrant0607 commented
Verify checks failed. 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36817/pull-kubernetes-verify/4754/

2016-11-15 22:21 UTC, bgrant0607 commented
LGTM other than the check failures.

2016-11-17 16:50 UTC, sebgoa commented
ok tests are passing now. hadn't run munge-docs so fixed some broken links in docs/ docs/devel and examples/ folders.

2016-11-17 21:44 UTC, bgrant0607 commented
@saad-ali Would you mind if this were merged now?

2016-11-17 21:44 UTC, bgrant0607 approved these changes

2016-11-18 05:12 UTC, saad-ali commented
> @saad-ali Would you mind if this were merged now?

Doc changes are ok for post-code-freeze merge.

2016-11-18 05:30 UTC, merged

2016-11-22 19:41 UTC, philips commented
I am fine with the code-of-conduct move. I will do the same for the template project.