Eviction Thresholds Update
kubernetes/kubernetes pull request #36911
Opened 2016-11-16 19:45 UTC by dashpole

Sets the defaults for the eviction-hard threshold and adds a default value for eviction minimum reclaim.

2016-11-16 19:46 UTC, dashpole commented
wait on this until I check out what the GKE defaults are.

2016-11-16 21:20 UTC, derekwaynecarr requested changes

2016-11-16 21:20 UTC, derekwaynecarr commented on pkg/apis/componentconfig/v1alpha1/defaults.go
> +		temp := "memory.available<300Mi,nodefs.available<10%,nodefs.inodesFree<5%"
how was this reached?  i left kubecon thinking we did not have good defaults in mind?

@sjenning

2016-11-16 21:24 UTC, derekwaynecarr commented
I think we should separate a GKE / GCE default separate from the open source default?

2016-11-16 21:44 UTC, dashpole commented
Sorry, this isnt gce/gke specific at all.  Because of #33444, we added some special handling for these flags in GKE, and I wanted to take a look at that before merging.
These values simply are what we have been using on e2e tests.

2016-11-16 22:15 UTC, dashpole commented
@k8s-bot kubemark e2e test this

2016-11-16 23:30 UTC, dashpole commented on pkg/apis/componentconfig/v1alpha1/defaults.go
> +		temp := "memory.available<300Mi,nodefs.available<10%,nodefs.inodesFree<5%"
This is what we have been using for e2e and e2e_node tests

2016-11-17 15:36 UTC, derekwaynecarr commented
Moving the defaults for node_e2e to be the defaults for the kubelet itself seems like a decision that needs to be well-reasoned.  Those defaults are maybe appropriate for node_e2e workload, but they are not really defaults you would want in production.  

For example, doing any default for disk resources should also have the minimum reclaim value set for those values.  I thought we would roll out defaults for disk once we removed the image-gc thresholds.  Until then, I thought we were saying disk eviction is opt-in.

2016-11-17 19:57 UTC, vishh commented
> For example, doing any default for disk resources should also have the minimum reclaim value set for those values. I thought we would roll out defaults for disk once we removed the image-gc thresholds. Until then, I thought we were saying disk eviction is opt-in.

Good catch. We should remove image-gc thresholds right away. Disk evictions will be useful for almost all users since disk usage often bricks a node. So it might be useful to start with some conservative defaults that do not break existing users. We can continue refining the defaults as we gain more signals from production.

2016-11-17 21:57 UTC, dchen1107 commented
+1 on @derekwaynecarr above. The Kubelet provides knobs to configure the node, including the resource management, but the value for those knobs should be subjected to the cluster admin. One set of values cannot work for everyone. For example, if the node is using the devicemapper as the graph driver, the configuration of nodefs.inodesFree<5% doesn't matter much here.

2016-11-17 22:16 UTC, dashpole commented
Eviction flags were already being used on GCE, but I changed them to match what we were using in our tests.  I also added minimum reclaim flags to our testing so that we can start running with that enabled.  This PR now makes no change to the kubelet defualts.

2016-11-18 19:44 UTC, dashpole commented
@derekwaynecarr @vishh @dchen1107 Do these changes sound good?  They only affect GCE defaults, and test defaults, and do not modify the kubelet defaults.

2016-11-18 20:45 UTC, derekwaynecarr commented
I am going to remove myself as an approver since I cannot speak for GCE.

I have allocated time for 1.6 to help inform what defaults we would like in open source project.  For the e2e tests, it looks fine to me.

2016-11-18 20:45 UTC, derekwaynecarr approved these changes

2016-11-18 22:30 UTC, mtaufen commented
This LGTM

2016-11-19 08:21 UTC, merged