bumped the C* version to 3.9. Exposed most of the important Cassandra…
kubernetes/kubernetes pull request #37145
Opened 2016-11-19 08:50 UTC by mstump

Fix for #34422

2016-11-19 20:53 UTC, dims commented
@k8s-bot ok to test

2016-11-20 03:19 UTC, mstump commented
It seems from the logs that the Jenkins automation failed in a way that's unrelated to the PR. What are the next steps?

2016-11-20 05:15 UTC, foxish commented
> W1119 13:16:25.878] FAIL: changes needed but not made due to --verify
> I1119 13:16:25.880] /go/src/k8s.io/kubernetes/examples/ is out of date. Please run hack/update-munge-docs.sh
> I1119 13:16:25.882] FAILED   hack/make-rules/../../hack/verify-munge-docs.sh	16s

@mstump, looks like the failure is related this PR

2016-11-20 05:16 UTC, foxish commented
cc @kubernetes/sig-apps

2016-11-20 18:10 UTC, chrislovecnm requested changes
Maven file updates for the new version? Looks great otherwise.

2016-11-20 18:10 UTC, chrislovecnm commented on examples/storage/cassandra/image/Dockerfile
> +RUN apt-get -y purge curl localepurge \
Please only use one RUN ;) any reason you have two. Less layers ;)

2016-11-20 18:11 UTC, chrislovecnm commented
@foxish can u push the docker? Otherwise the e2e tests are borked.

2016-11-20 18:12 UTC, chrislovecnm requested changes
Please let's do one RUN

2016-11-20 18:12 UTC, chrislovecnm commented on examples/storage/cassandra/image/Dockerfile
> +  && echo "$DI_SHA  /sbin/dumb-init" | sha1sum -c -
And just one Run. Every run is another layer :P

2016-11-21 07:46 UTC, mstump commented
I incorporated the feedback about the RUN statement in the docker file. I also took out the version bump in the statefulset example, I believe that was that cause of the original build error. Someone with privileges will need to bump that version and push to docker as a followup action.

2016-11-21 14:29 UTC, chrislovecnm requested changes
Still missing the maven Pom file updates. We need to bump the dependency version for the jar as well.

2016-11-21 14:30 UTC, chrislovecnm commented
We need to maven pom updated and the jar built before we push the docker version.

2016-11-21 21:07 UTC, kow3ns commented
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/storage/cassandra/image/files/kubernetes-cassandra.jar, line 0 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37145#-KX7gh8I1-tmEcb6_man:-KX7gh8I1-tmEcb6_mao:bx6h5ha) ([raw file](https://github.com/kubernetes/kubernetes/blob/d80c1df221b14d9fdad447a5e7478560f86797f6/examples/storage/cassandra/image/files/kubernetes-cassandra.jar#L0)):*
I believe chris already commented on this but Kubernetes SeedProvider needs to be rebuilt against cassandra-all 3.9. The cassandra-version property needs to be set in the projects pom.  The SeedProvider needs to be rebuilt and copied into the Docker image.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37145)*
<!-- Sent from Reviewable.io -->

2016-11-23 23:43 UTC, mstump commented
Ok, hopefully this is the last update. Bumped the version in the POM and rebuilt the jar.

2016-11-28 16:49 UTC, chrislovecnm commented
@janetkuo can you deploy the new container for this PR?

@mstump LGTM, let's get the container changed, and then you can put another PR in  for the manifests.

2016-11-28 23:22 UTC, kow3ns commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.kubernetes.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37145#-:-KXhEhQjwulOhspTFCeo:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2016-11-29 19:29 UTC, chrislovecnm commented
@kow3ns who can upload the container to gcr.io?

2016-12-01 20:06 UTC, kow3ns commented
I should be able to

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37145#-:-KXvzT_xIvsHyK_2Zvi1:b2pbotx)*
<!-- Sent from Reviewable.io -->

2016-12-03 00:14 UTC, kow3ns commented
/lgtm

root@cassandra-0:/# nodetool version
ReleaseVersion: 3.9

root@cassandra-0:/# nodetool status
Datacenter: DC1-K8Demo
======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.244.3.4  83.17 KiB  32           71.2%             6d79d831-16c6-49ff-8b92-22d6dd20e48c  Rack1-K8Demo
UN  10.244.1.4  65.61 KiB  32           65.0%             b269337d-6503-43f5-b67d-d697e4926839  Rack1-K8Demo
UN  10.244.2.9  103.84 KiB  32           63.8%             d442393d-99db-4fc9-85ff-d43c73f4bae7  Rack1-K8Demo

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37145#-:-KY10Z2LZpHvKz_z4KwX:b-e5xwyj)*
<!-- Sent from Reviewable.io -->

2016-12-03 00:19 UTC, kow3ns commented
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37145)*
<!-- Sent from Reviewable.io -->

2016-12-03 22:17 UTC, chrislovecnm commented
/lgtm

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/37145#-:-KY5kxepXAXOVjSOuWBz:b-8ks5qa)*
<!-- Sent from Reviewable.io -->

2016-12-08 05:50 UTC, rmmh commented
@k8s-bot unit test this

2016-12-08 12:39 UTC, merged