Add unversioned.MicroTime type
kubernetes/kubernetes pull request #37212
Opened 2016-11-21 13:34 UTC by gmarek

Ref. #36752

cc @smarterclayton @wojtek-t @dchen1107 @timothysc @bgrant0607

2016-11-21 13:52 UTC, dims commented
@gmarek : why RFC3339 (instead of ISO 8601?)

2016-11-21 14:46 UTC, gmarek commented
Because XYZ - in other words, I have no idea, and I don't care, it's just the thing we have now:)

2016-11-21 14:47 UTC, dims commented
LOL

2016-11-21 16:23 UTC, smarterclayton commented
RFC3339 is much more commonly used in the REST space than ISO8601, and more libraries and clients (unscientific study) use it or expect it.

2016-11-21 16:24 UTC, smarterclayton commented
Changes are ok to me - we can dry them up later.

2016-11-21 16:24 UTC, dims commented
Thanks @smarterclayton

2016-11-29 14:59 UTC, timothysc commented on pkg/api/unversioned/generated.proto
> +message MicroTime {
Isn't this ~= https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto 

Just wondering why we're duping.

2016-11-29 15:09 UTC, gmarek commented on pkg/api/unversioned/generated.proto
> +message MicroTime {
For consistency with the rest of the system. I didn't want to spend time to check what I'd need to do to serialize our custom go/json to this proto.

2016-11-29 15:19 UTC, smarterclayton commented
We can't change the proto serialization anyway (now that it's locked).

On Tue, Nov 29, 2016 at 10:09 AM, Marek Grabowski <notifications@github.com>
wrote:

> *@gmarek* commented on this pull request.
> ------------------------------
>
> In pkg/api/unversioned/generated.proto
> <https://github.com/kubernetes/kubernetes/pull/37212>:
>
> > @@ -232,6 +232,24 @@ message ListMeta {
>    optional string resourceVersion = 2;
>  }
>
> +// MicroTime is version of Time with microsecond level precision.
> +//
> +// +protobuf.options.marshal=false
> +// +protobuf.as=Timestamp
> +// +protobuf.options.(gogoproto.goproto_stringer)=false
> +message MicroTime {
>
> For consistency with the rest of the system. I didn't want to spend time
> to check what I'd need to do to serialize our custom go/json to this proto.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/37212>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p5Tfc9cgBzn9HdJy9VP-yx-shREVks5rDEAtgaJpZM4K4NM0>
> .
>

2016-11-29 15:19 UTC, smarterclayton commented
Also, there are bugs in go-proto with google types and they were only
recently fixed.

On Tue, Nov 29, 2016 at 10:19 AM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> We can't change the proto serialization anyway (now that it's locked).
>
> On Tue, Nov 29, 2016 at 10:09 AM, Marek Grabowski <
> notifications@github.com> wrote:
>
>> *@gmarek* commented on this pull request.
>> ------------------------------
>>
>> In pkg/api/unversioned/generated.proto
>> <https://github.com/kubernetes/kubernetes/pull/37212>:
>>
>> > @@ -232,6 +232,24 @@ message ListMeta {
>>    optional string resourceVersion = 2;
>>  }
>>
>> +// MicroTime is version of Time with microsecond level precision.
>> +//
>> +// +protobuf.options.marshal=false
>> +// +protobuf.as=Timestamp
>> +// +protobuf.options.(gogoproto.goproto_stringer)=false
>> +message MicroTime {
>>
>> For consistency with the rest of the system. I didn't want to spend time
>> to check what I'd need to do to serialize our custom go/json to this proto.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/kubernetes/kubernetes/pull/37212>, or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/ABG_p5Tfc9cgBzn9HdJy9VP-yx-shREVks5rDEAtgaJpZM4K4NM0>
>> .
>>
>
>

2016-12-14 08:14 UTC, gmarek commented
@lavalamp @smarterclayton - can we move forward with this?

2016-12-15 10:30 UTC, gmarek commented
@smarterclayton - done.

2017-01-03 19:52 UTC, gmarek commented
@smarterclayton @lavalamp PTAL

2017-01-10 03:00 UTC, smarterclayton approved these changes

2017-01-10 03:00 UTC, smarterclayton commented
Rebase otherwise lgtm

2017-01-11 13:44 UTC, gmarek commented
GKE tests are broken now.

2017-01-11 19:03 UTC, lavalamp requested changes
Why do you need this type at all? If it is really necessary, then please make it behave the way the name advertises (or change the name).

2017-01-11 19:03 UTC, lavalamp commented on pkg/api/unversioned/time.go
> +// BeforeMicro reports whether the time instant t is before micro instance u.
What is a "micro instance"?

2017-01-11 19:03 UTC, lavalamp commented on pkg/api/unversioned/time.go
> +	return t.Time.Before(u.Time)
Shouldn't this round (er, truncate?) to nearest microsecond before comparing? Same for below function. If this function doesn't do anything special then maybe just delete it?

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/micro_time.go
> +// Rfc3339Copy returns a copy of the MicroTime at second-level precision.
second-level?

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time.Unix(sec, nsec)}
shouldn't you truncate to microseconds?

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time.Now()}
shouldn't you truncate to microseconds?

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time.Date(year, month, day, hour, min, sec, nsec, loc)}
shouldn't you truncate to microseconds?

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time}
shouldn't you truncate to microseconds?

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/micro_time.go
> +	// Allow for about 1000 years of randomness.  Leave off nanoseconds
Update this. It should randomize to microseconds.

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/generated.proto
> +  optional int32 nanos = 2;
Why do you store nanoseconds for a microtime type? That doesn't make much sense.

2017-01-11 19:03 UTC, lavalamp commented on pkg/apis/meta/v1/time.go
> +// BeforeMicro reports whether the time instant t is before micro instance u.
Same comment as other file, delete these or make them round correctly to micros.

2017-01-11 19:04 UTC, lavalamp commented
And very sorry for delay in review. I was OOO for a long time last month.

2017-01-12 12:48 UTC, gmarek commented on pkg/api/unversioned/time.go
> +// BeforeMicro reports whether the time instant t is before micro instance u.
Rephrased.

2017-01-12 12:52 UTC, gmarek commented on pkg/api/unversioned/time.go
> +	return t.Time.Before(u.Time)
This shouldn't be needed - both Time and MicroTime, as go-structs have full precision. The only difference is that when serialized to JSON the latter is more precise.

2017-01-12 12:53 UTC, gmarek commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time}
We're not doing it in normal 'Time' which has a second precision. I don't see why we should do it here.

2017-01-12 12:54 UTC, gmarek commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time.Date(year, month, day, hour, min, sec, nsec, loc)}
We're not doing it in normal 'Time' which has a second precision. I don't see why we should do it here.

2017-01-12 12:54 UTC, gmarek commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time.Now()}
We're not doing it in normal 'Time' which has a second precision. I don't see why we should do it here.

2017-01-12 12:54 UTC, gmarek commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time.Unix(sec, nsec)}
We're not doing it in normal 'Time' which has a second precision. I don't see why we should do it here.

2017-01-12 12:55 UTC, gmarek commented on pkg/apis/meta/v1/micro_time.go
> +// Rfc3339Copy returns a copy of the MicroTime at second-level precision.
Sorry, I missed that.

2017-01-12 12:57 UTC, gmarek commented on pkg/apis/meta/v1/micro_time.go
> +	// Allow for about 1000 years of randomness.  Leave off nanoseconds
Thx.

2017-01-12 13:00 UTC, gmarek commented on pkg/apis/meta/v1/time.go
> +// BeforeMicro reports whether the time instant t is before micro instance u.
I don't think we should do that. Unversioned Time is used internally as normal timestamp with nanosecond precision, the only thing that I'm not happy with is that when serialized it truncates time to second. The second 'MicroTime' is designed to be exactly the same, but serialized differently. Hence actually we should compare 'full' representations.

2017-01-12 13:02 UTC, gmarek commented on pkg/apis/meta/v1/generated.proto
> +  optional int32 nanos = 2;
Again - this is exactly the same thing as we have for Time.

2017-01-12 13:03 UTC, gmarek commented
Applied few comments and replied to the rest - @lavalamp PTAL.

2017-01-20 01:41 UTC, lavalamp commented
I still don't understand-- why do you need this type at all?

2017-01-20 01:42 UTC, lavalamp commented on pkg/apis/meta/v1/micro_time.go
> +	return MicroTime{time}
If you don't want to round to micros, then I really don't understand why you want a separate type at all.

2017-01-20 01:43 UTC, lavalamp commented on pkg/apis/meta/v1/time.go
> +// BeforeMicro reports whether the time instant t is before micro instance u.
What bad thing happens if you update the normal time to store micros instead of seconds?

2017-02-03 02:27 UTC, smarterclayton commented on pkg/apis/meta/v1/time.go
> +// BeforeMicro reports whether the time instant t is before micro instance u.
We break API compatibility with v1.

2017-02-06 15:05 UTC, gmarek commented on pkg/apis/meta/v1/time.go
> +// BeforeMicro reports whether the time instant t is before micro instance u.
@lavalamp - as @smarterclayton we can't do that, however tempting it would be.

2017-02-07 00:19 UTC, lavalamp commented
I still don't understand why we need this type at all?

2017-02-07 00:31 UTC, lavalamp commented
I feel really bad for sitting on this PR for so long. I guess primarily two things:
a) Why do we need this type? I guess you probably have a good reason to store micros? But is there any way to e.g. parameterize the current type instead of copying it?
b) I still don't like the fact that this has got "micro" in the name but most of the methods actually don't constrain anything to micros. As in, it will behave drastically differently depending on whether you use times that you generated locally vs after they've been through a serialization/deserialization loop.

I almost feel bad enough (about the delay in me looking at this) to approve it anyway, but not quite :)

2017-02-07 08:47 UTC, gmarek commented
The reason why we need micros is that second granularity is by far not enough to allow... well pretty much anything on big clusters (you get unsorted blob of hundreds of things that happened in a given second). For me personally it's problematic because I need to use those timestamps to trace e2e pod startup latency.

The problem you mention (not being micro everywhere) already exists with default time, which has exactly the same property, but with second granularity. I don't think it ever caused problems, so I don't really think that solving it in some elaborate way makes a lot of sense.

2017-02-08 15:53 UTC, gmarek commented
@lavalamp

2017-02-13 23:19 UTC, lavalamp commented
Last question, still would like an answer to "but is there any way to e.g. parameterize the current type instead of copying it?"

I'm going to remove myself from this PR and stop blocking it, I have too many other priorities.

2017-02-13 23:20 UTC, lavalamp approved these changes

2017-03-02 00:45 UTC, ethernetdan commented
Removing PR from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

2017-05-16 15:06 UTC, timothysc commented
@gmarek I'd like to restart this PR if possible, given our inability to trace across components easily. 

/cc @kensimon

2017-05-16 15:48 UTC, gmarek commented
Yes, I agree - I was planning to restart this, but I was busy with reviews and playing with OT (I can trace API requests from client to the API server and back, so I'll probably start sending PRs soon).

2017-05-22 15:36 UTC, gmarek commented
@timothysc @lavalamp @smarterclayton - can we come back to this PR and try to get at least microsecond-timestamps in Events in 1.7?

2017-05-22 16:09 UTC, timothysc commented
> can we come back to this PR and try to get at least microsecond-timestamps in Events in 1.7?

+1 from me.

2017-05-23 05:48 UTC, gmarek commented
@smarterclayton

2017-05-25 10:16 UTC, gmarek commented
@k8s-bot pull-kubernetes-unit test this

2017-05-25 11:09 UTC, gmarek commented
@k8s-bot pull-kubernetes-unit test this

2017-05-25 14:31 UTC, timothysc approved these changes
/lgtm

2017-05-25 14:38 UTC, wojtek-t commented
/lgtm

2017-05-25 16:22 UTC, gmarek commented
Adding do-not-merge label, as @wojtek-t lgtm acts as approve.

2017-05-25 17:58 UTC, thockin reviewed
I don't see obvious problems with this...

@smarterclayton

2017-05-25 17:58 UTC, thockin commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time.go
> +func (t MicroTime) Rfc3339MicroCopy() MicroTime {
How is this different from DeepCopy?

2017-05-29 12:22 UTC, gmarek commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time.go
> +func (t MicroTime) Rfc3339MicroCopy() MicroTime {
Frankly, I don't remember. Probably copied it from 'Time' at some point in time. Removed.

2017-05-29 14:01 UTC, gmarek commented
@k8s-bot pull-kubernetes-unit test this

2017-05-30 03:56 UTC, thockin commented
/lgtm

2017-05-30 05:12 UTC, wojtek-t commented
@k8s-bot pull-kubernetes-unit test this

2017-05-30 07:12 UTC, gmarek commented
@k8s-bot pull-kubernetes-unit test this

2017-05-30 08:11 UTC, gmarek commented
@k8s-bot pull-kubernetes-unit test this

2017-05-30 08:58 UTC, gmarek commented
@k8s-bot pull-kubernetes-unit test this

2017-05-30 09:23 UTC, gmarek commented
@k8s-bot pull-kubernetes-unit test this

2017-05-30 11:46 UTC, merged