When --grace-period=0 is provided, wait for deletion
kubernetes/kubernetes pull request #37263
Opened 2016-11-22 03:24 UTC by smarterclayton

The grace-period is automatically set to 1 unless --force is provided,
and the client waits until the object is deleted.

This preserves backwards compatibility with 1.4 and earlier. It does not
handle scenarios where the object is deleted and a new object is created
with the same name.

Fixes #37117 by relaxing the guarantees provided.

2016-11-22 03:34 UTC, smarterclayton commented
Proposed for 1.5 to avoid backwards compatibility.

2016-11-22 05:11 UTC, smarterclayton commented
@k8s-bot bazel test this

2016-11-22 14:58 UTC, fabianofranz commented
@smarterclayton so both `--grace-period=0` and `--now` will set `gracePeriod` to `1`, but the difference is that the first waits?

2016-11-22 15:04 UTC, fabianofranz commented on pkg/kubectl/cmd/delete.go
> +			gracePeriod = 1
`--grace-period=0` may now be mutually exclusive with `--timeout`

2016-11-22 15:50 UTC, smarterclayton commented on pkg/kubectl/cmd/delete.go
> +			gracePeriod = 1
It's not, timeout is still respected.

2016-11-22 15:51 UTC, smarterclayton commented
> so both --grace-period=0 and --now will set gracePeriod to 1, but the difference is that the first waits?

To avoid breaking old scripts, --grace-period=0 continues to not return (waits) until the object is gone.  --now continues to behave as it did before.

2016-11-22 17:12 UTC, fabianofranz commented
LGTM

2016-11-22 18:43 UTC, krousey requested changes

2016-11-22 18:43 UTC, krousey commented on pkg/client/restclient/request.go
> +				if resp.Body != nil {
This check should not be required.

```
        // The http Client and Transport guarantee that Body is always
        // non-nil, even on responses without a body or responses with
        // a zero-length body.
```

2016-11-22 18:43 UTC, krousey commented on pkg/kubectl/cmd/delete_test.go
> +					return &http.Response{StatusCode: 404, Header: defaultHeader(), Body: nil}, nil
This should provide a non-nil body, even if it is empty.

2016-11-22 20:29 UTC, smarterclayton commented on pkg/client/restclient/request.go
> +				if resp.Body != nil {
Test cases were passing nil in, and we guard against it in other places.  I'll remove both guards and hunt down the bug.

2016-11-22 22:57 UTC, krousey commented
cc @roberthbailey

2016-11-23 21:02 UTC, smarterclayton commented
Updated with all comments.

2016-11-23 21:46 UTC, saad-ali commented
@k8s-bot test this

2016-11-23 21:48 UTC, dchen1107 commented
This pr might need more attention, and I decided not manually merge it for holiday code freeze in favor to merge two large prs: https://github.com/kubernetes/kubernetes/pull/36673
and https://github.com/kubernetes/kubernetes/pull/36782

2016-11-23 21:50 UTC, smarterclayton commented
Yes, that's fine with me.

2016-11-28 21:09 UTC, eparis commented
@k8s-bot gce node e2e test this

2016-11-28 21:17 UTC, krousey approved these changes

2016-11-28 21:23 UTC, eparis commented
@k8s-bot node e2e test this

2016-11-29 02:21 UTC, saad-ali commented
@foxish can you review. Let's get this merged ASAP, so we can unblock upgrade testing

2016-11-29 10:33 UTC, foxish commented
LGTM except for the one comment.

2016-11-29 11:09 UTC, foxish commented on pkg/kubectl/cmd/replace.go
>  		err = DeleteResult(r, out, ignoreNotFound, shortOutput, mapper)
It seems like this should go through ReapResult as well? Currently, we would print out "pod is deleted" prior to its actual deletion, and then eventually hit the timeout condition a few lines below.

2016-11-29 11:43 UTC, foxish commented on pkg/kubectl/cmd/delete.go
> +	return wait.PollImmediate(objectDeletionWaitInterval, timeout, func() (bool, error) {
I think in the timeout case, we should return a better error than "timed out waiting for the condition" because we surface 
that error to the user.

2016-11-29 16:15 UTC, smarterclayton commented on pkg/kubectl/cmd/replace.go
>  		err = DeleteResult(r, out, ignoreNotFound, shortOutput, mapper)
We don't actually even do graceful deletion in this code path (we use the server default) so it's not backwards incompatible.  Definitely something we need to fix in the future, but not for 1.5

2016-11-29 16:42 UTC, foxish commented
/lgtm

2016-11-29 17:28 UTC, smarterclayton commented
Follow up issue opened as
https://github.com/kubernetes/kubernetes/issues/37637

On Tue, Nov 29, 2016 at 11:59 AM, Kubernetes Submit Queue <
notifications@github.com> wrote:

> @k8s-bot <https://github.com/k8s-bot> test this
>
> Tests are more than 96 hours old. Re-running tests.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/37263#issuecomment-263630227>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p1MjqpuojUbmyGcoHXo4GfP_ZN4pks5rDFn9gaJpZM4K494f>
> .
>

2016-11-29 19:29 UTC, dims commented
@k8s-bot node e2e test this

2016-11-29 19:30 UTC, dims commented
@k8s-bot unit test this

2016-11-30 02:47 UTC, saad-ali commented
@k8s-bot node e2e test this

2016-11-30 02:47 UTC, saad-ali commented
@k8s-bot kops aws e2e test this

2016-11-30 17:29 UTC, dims commented
@k8s-bot node e2e test this

2016-11-30 19:15 UTC, merged