Update quota scope descriptions
kubernetes/kubernetes pull request #37288
Opened 2016-11-22 14:54 UTC by juanvallejo

```release-note
release-note-none
```

This patch improves the help text descriptions for quota scopes.

@kubernetes/kubectl

2016-11-22 15:36 UTC, deads2k commented on pkg/kubectl/describe.go
> +		return "Affects pods that have an active deadline. These pods usually include builds, deployers, and jobs."
I don't think is appropriate for kubernetes.  The concept of builds and deployers don't exist in kube and `Affects` seems like the wrong verb.  The old description read accurately to me and this one does not.

2016-11-22 15:37 UTC, deads2k commented on pkg/kubectl/describe.go
> +		return "Affects pods that do not have an active deadline. These pods usually include those which host an application."
"host an application", is really vague.  Also, this is specifically for matching, why are you switching to "Affects"?

2016-11-22 15:37 UTC, deads2k commented
@derekwaynecarr for phrasing since its quota related.

2016-11-22 18:43 UTC, juanvallejo commented on pkg/kubectl/describe.go
> +		return "Affects pods that do not have an active deadline. These pods usually include those which host an application."
I based these on https://github.com/openshift/origin-web-console/pull/887

2016-11-22 18:48 UTC, juanvallejo commented on pkg/kubectl/describe.go
> +		return "Affects pods that do not have an active deadline. These pods usually include those which host an application."
I will switch this back to "matching". 
I was not sure if I should mention "application" here, maybe something like "These pods usually include services, application components, etc."

2016-11-22 19:05 UTC, deads2k commented on pkg/kubectl/describe.go
> +		return "Matches all pods that have an active deadline. These pods usually include jobs."
Why not explain it based on what active deadlines are for.

2016-11-22 19:18 UTC, juanvallejo commented on pkg/kubectl/describe.go
> +		return "Matches all pods that have an active deadline. These pods usually include jobs."
`Matches all pods that have an active deadline. These pods have a limited lifespan on a node before being actively terminated by the system` WDYT?

2016-11-22 19:21 UTC, deads2k commented on pkg/kubectl/describe.go
> +		return "Matches all pods that do not have an active deadline. These pods usually include long running pods such as web servers and databases."
are you trying to say that the container command is not expected to terminate?

2016-11-22 19:44 UTC, juanvallejo commented on pkg/kubectl/describe.go
> +		return "Matches all pods that do not have an active deadline. These pods usually include long running pods such as web servers and databases."
`These pods usually include long running pods whose container command is not expected to terminate` Would that sound better?

2017-01-05 21:18 UTC, deads2k commented on pkg/kubectl/describe.go
> +		return "Matches all pods that have at least one resource limit set. These pods do not have a best effort quality of service."
ask @derekwaynecarr for a positive way to phrase this, then lgtm.

2017-01-09 16:30 UTC, derekwaynecarr requested changes
resource limits is an overloaded term since we have limit and request that make up a resource requirement.

2017-01-09 16:30 UTC, derekwaynecarr commented on pkg/kubectl/describe.go
> +		return "Matches all pods that do not have resource limits set. These pods have a best effort quality of service."
Matches all pods that do not have resource requirements set.  These pods have a best effort quality of service.

2017-01-09 16:30 UTC, derekwaynecarr commented on pkg/kubectl/describe.go
> +		return "Matches all pods that have at least one resource limit set. These pods do not have a best effort quality of service."
Matches all pods that have at least one resource requirement set.  These pods have a burstable or guaranteed quality of service.

2017-01-09 16:37 UTC, juanvallejo commented
@derekwaynecarr @deads2k thanks for the feedback, review comments addressed

2017-01-09 19:57 UTC, derekwaynecarr approved these changes

2017-01-10 22:33 UTC, merged