Moved node affinity from annotations to api fields. #35518
kubernetes/kubernetes pull request #37299
Opened 2016-11-22 18:32 UTC by rrati

Converted node affinity from annotations to api fields

2016-11-24 00:33 UTC, davidopp commented
I didn't look at the PR yet but I'm adding Daniel and Tim as reviewers because we need to make sure this uses the mechanism we're going to use in general for moving stuff to beta.

2016-11-29 21:15 UTC, timothysc commented
2 things 
 
1 - needs release note 
2 - breakup commits. 

/cc @derekwaynecarr @aveshagarwal

2016-11-30 17:49 UTC, rrati commented
@timothysc Updates completed

2016-11-30 20:08 UTC, timothysc reviewed
Just did a quick pass.  We need buy in from @kubernetes/sig-api-machinery on the blessed decoration for alpha/beta fields.

2016-11-30 20:08 UTC, timothysc commented on pkg/api/types.go
> +	// +optional
@smarterclayton @lavalamp What is the official decoration needed?  
xref: #34508

2016-11-30 20:08 UTC, timothysc commented on pkg/api/v1/types.go
> +	Affinity *Affinity `json:"affinity,omitempty" protobuf:"bytes,18,opt,name=affinity"`
same comment re: decoration

2016-11-30 20:08 UTC, timothysc commented on pkg/client/record/event.go
> +
seems unrelated, no need.

2016-12-01 02:24 UTC, smarterclayton commented on pkg/api/types.go
> +	// +optional
omitempty and +optional, and if you need to support empty vs nil arrays or maps you should not set omitempty and instead use the same construct that ExtraValues in authorization uses.

2016-12-01 09:16 UTC, davidopp commented
Not to sound like a broken record but can you check with @lavalamp or @bgrant0607 or @thockin to make sure this conforms to #34508 ? (I'm not saying this because I think it doesn't -- in fact I haven't even looked at the PR. But I think it would be good to check with them.)

2016-12-01 15:45 UTC, smarterclayton commented
The only take away that applies here is:

1. Add fields
2. During decoding (preferable) continue to honor annotations as higher priority than the field.

If you can't do it during decoding you'll need to do it in all client code and in server conversions.

2016-12-01 17:23 UTC, rrati commented
@smarterclayton Are you suggesting that we should try to be backwards compatible with the annotations implementation?  If so then I disagree.  This is an alpha feature that has not moved to beta.  Providing backwards compatibility would needlessly complicate the code in order to maintain an undesirable alpha implementation.  I think a clean break from the annotations implementation is best.  No one should be relying upon an alpha implementation since it can change.

2016-12-01 20:20 UTC, smarterclayton commented
It's questionable whether alpha -> GA requires back compat.  beta -> GA
definitely does.

On Thu, Dec 1, 2016 at 12:23 PM, Rob Rati <notifications@github.com> wrote:

> @smarterclayton <https://github.com/smarterclayton> Are you suggesting
> that we should try to be backwards compatible with the annotations
> implementation? If so then I disagree. This is an alpha feature that has
> not moved to beta. Providing backwards compatibility would needlessly
> complicate the code in order to maintain an undesirable alpha
> implementation. I think a clean break from the annotations implementation
> is best. No one should be relying upon an alpha implementation since it can
> change.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/37299#issuecomment-264236305>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_pyimV50nMhLlVU0rdwYdwp9JTgBYks5rDwKogaJpZM4K5yRM>
> .
>

2016-12-02 14:20 UTC, rrati commented
@smarterclayton I agree beta->GA would likely require backwards compat and there could be cases where alpha->GA would need it as well.  In this case though, I don't think we should attempt backwards compat.

2016-12-07 17:46 UTC, timothysc commented
From sig-scheduling mtg on Monday, @davidopp would like @lavalamp to once...

2016-12-08 00:19 UTC, lavalamp commented
I have no objections. I do recommend your update code should be tolerant to old clients dropping this field when they do updates, or at least you should think about that case.

2016-12-12 16:18 UTC, timothysc commented on pkg/api/validation/validation.go
> +			na := affinity.NodeAffinity
you can probably do the variable swap trick on the if line: 

if na := affinity.NodeAffinity; na != nil {

2016-12-12 17:21 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/metadata.go
> +	annotationAffinity, err := v1.GetAffinityFromPodAnnotations(pod.Annotations)
This gets converted in your next PR correct?

2016-12-12 17:26 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/node_affinity_test.go
> +								Values:   []string{"value"},
Is there an example where this is actually a string array vs. just a string?  Just wondering if we should rationalize the field types.

2016-12-12 17:28 UTC, timothysc requested changes
Only minor comments to address.  I would like @davidopp to once over as well, but 90% of this PR is just translation so lgtm for the most part.

2016-12-12 18:16 UTC, rrati commented on pkg/api/validation/validation.go
> +			na := affinity.NodeAffinity
Done

2016-12-12 18:17 UTC, rrati commented on plugin/pkg/scheduler/algorithm/priorities/metadata.go
> +	annotationAffinity, err := v1.GetAffinityFromPodAnnotations(pod.Annotations)
Once both annotation conversations are in that function gets removed.

2016-12-12 18:25 UTC, rrati commented on plugin/pkg/scheduler/algorithm/priorities/node_affinity_test.go
> +								Values:   []string{"value"},
Yes.  Look at node affinity in scheduler_predicates.go

2016-12-13 22:25 UTC, rrati commented
@k8s-bot test this #18620

2016-12-14 07:12 UTC, davidopp commented on pkg/api/types.go
> +	// If specified, the pod's scheduling preferences
"Scheduling preferences" is too vague. Also preferences doesn't imply that it can be hard constraints or soft preferences.

2016-12-14 07:15 UTC, davidopp commented
IIUC you removed the tests for the annotation version, but didn't remove the code for it. Was that intentional? What is the upgrade plan here? This was one of the things I think we were debating in the discussion about how to move things from annotations to fields (i.e. what do you do when you have both, or one but then upgrade/downgrade, etc.).

2016-12-14 13:48 UTC, rrati commented
@davidopp All the code for dealing with node affinity in annotations should have been removed.  The annotations based affinity is there for the pod affinity and anti-affinity definitions, which will be handled in a separate PR.

There is no upgrade plan and imo there shouldn't be one.  This was an alpha feature.  Maintaining backwards compatibility increases code complexity and opens up potential issue for no solid reason.  I think a clean break with the original implementation is best.  Slight more heartache for anyone who used the feature, but they also should expect that with an alpha feature.

2016-12-14 13:49 UTC, rrati commented on pkg/api/types.go
> +	// If specified, the pod's scheduling preferences
What term would you prefer instead?  maybe say constraints and preferences?

2016-12-14 14:50 UTC, timothysc approved these changes

2016-12-14 14:56 UTC, timothysc commented
> There is no upgrade plan and imo there shouldn't be one. This was an alpha feature. Maintaining backwards compatibility increases code complexity and opens up potential issue for no solid reason. I think a clean break with the original implementation is best. Slight more heartache for anyone who used the feature, but they also should expect that with an alpha feature. 

@davidopp We evaluated node-affinity via annotations, and found it to be a UX-pain.  It was easy to make a single character mistake and be lost in, "Why is this not working?".  As a result, we surmised:  

1. It's alpha, so no guarantees  
2. It's not strongly typed, which can lead to UX pain scenarios
3. We don't want to maintain it into beta 
... 

Therefore, we should pay the breaking price on the move to beta, and not be stuck with supporting annotations all the way through.  

As @rrati mentioned the existing annotation code is for inter-pod affinity, and he has a follow on PR to convert that as well.

2016-12-14 19:29 UTC, timothysc commented on pkg/api/types.go
> +	// If specified, the pod's scheduling preferences
+1 to constraints.

2016-12-15 14:16 UTC, timothysc commented on pkg/api/types.go
> +	// If specified, the pod's scheduling preferences
@davidopp do you have any opinion on comment?

2016-12-15 22:03 UTC, davidopp commented
@wojtek-t

2016-12-16 08:02 UTC, davidopp commented on pkg/api/v1/types_swagger_doc_generated.go
> +	"affinity":                      "If specified, the pod's scheduling preferences",
I'm not sure how this ended up as "preferences" but it should be "constraints" (mostly I just want the terminology to be consistent)

2016-12-16 08:22 UTC, davidopp commented
I just had one minor comment, otherwise LGTM, so feel free to LGTM once you fix that. If @wojtek-t has a chance to review this today to double-check the PR, that would be great, but if not, I think it is OK to self-LGTM it since you mentioned you are going to be OOO soon and I don't see a good reason to hold this up over the holidays.

2016-12-16 08:22 UTC, davidopp commented
Oh and thanks a lot for doing this!

2016-12-16 08:50 UTC, davidopp commented
Should we label the field name as "beta" somehow?

2016-12-16 15:00 UTC, timothysc commented
> Should we label the field name as "beta" somehow? (to indicate the feature is beta) 

This is where "policy" comes in, and api-machinery folks said it's ok.  

Should that change, we'll happily change, but folks "**really need to write down the policy**" and update the docs...

2016-12-16 18:46 UTC, merged