kubernetes attempts to unmount a wrong vSphere volume and stops making any progress after that
kubernetes/kubernetes pull request #37413
Opened 2016-11-24 00:34 UTC by BaluDontu

This is in reference to the bug #37332 which was accidentally closed. So created this new PR.

The code is already reviewed as part of PR #37332 

@saad-ali @jingxu97 @abrarshivani @kerneltime

2016-11-24 00:53 UTC, saad-ali commented
@k8s-bot ok to test

2016-11-24 00:56 UTC, BaluDontu commented
Once this is merged, we will also cherrypick this change into release 1.4.

2016-11-24 02:44 UTC, kerneltime commented
This PR is all set with rebase

2016-11-28 17:33 UTC, kerneltime commented
@k8s-bot unit test this

2016-11-28 17:43 UTC, BaluDontu commented
@k8s-bot cvm gke e2e test this

2016-11-28 18:12 UTC, kerneltime commented
@k8s-bot cvm gke e2e test this

2016-11-28 22:16 UTC, BaluDontu commented
@saad-ali : I think this is now ready for merge. Can you take the appropriate action.

2016-11-28 23:32 UTC, saad-ali requested changes

2016-11-28 23:32 UTC, saad-ali commented on pkg/volume/vsphere_volume/vsphere_volume.go
> +	volumePath, _ := mounter.GetDeviceNameFromMount(mountPath, pluginDir)
Why is the error swallowed here?

2016-11-28 23:59 UTC, BaluDontu commented on pkg/volume/vsphere_volume/vsphere_volume.go
> +	volumePath, _ := mounter.GetDeviceNameFromMount(mountPath, pluginDir)
I have added the changes to use the error. Please see the new commit.

2016-11-29 00:26 UTC, saad-ali commented
LGTM please squash your commits.

2016-11-29 01:36 UTC, saad-ali commented
You should leave the commit message something useful (not "squashed commits"). Also, looks like this PR needs a rebase.

2016-11-29 06:23 UTC, kerneltime commented
@k8s-bot kops aws e2e test this

2016-11-29 19:25 UTC, BaluDontu commented
@saad-ali : Any update on this.

2016-11-29 22:03 UTC, saad-ali approved these changes

2016-11-29 22:04 UTC, saad-ali commented
/lgtm

2016-11-29 22:04 UTC, saad-ali commented
@k8s-bot node e2e test this

2016-11-30 01:38 UTC, saad-ali commented
@kubernetes/test-infra-admins All tests are green for this PR but "Submit Queue" still thinks "Github CI tests are not green", what's going on here?

2016-11-30 21:19 UTC, fejta commented
@ixdy any thoughts on why this isn't getting merged? Did we run all the right tests? @foxish may be able to help.

2016-11-30 21:21 UTC, ixdy commented
@saad-ali it looks like it's because this test is missing etc3 results, which SQ requires.
@k8s-bot gce etcd3 e2e test this

2016-11-30 21:22 UTC, zmerlynn commented
We really need to fix #37191, given the PR builder proliferation. :(

2016-11-30 21:23 UTC, ixdy commented
In some thread there was discussion about synchronizing the list of "required" tests in the kubernetes/kubernetes GitHub settings with the SQ configmap (which would've made this more obvious).

I'm not sure why we lost the etcd3 results, but I'm guessing a missed webhook by prow.

We should probably update the SQ commit line to have more details than "Github CI tests are not green.", i.e. include what builds it's unhappy about. This also would've made the issue more obvious.

2016-11-30 21:27 UTC, foxish commented
> In some thread there was discussion about synchronizing the list of "required" tests in the kubernetes/kubernetes GitHub settings with the SQ configmap (which would've made this more obvious).

@eparis is making that change in mungegithub IIRC.

2016-11-30 21:29 UTC, fejta commented
Thanks so much for resolving this @ixdy. @saad-ali you said there were other instances of this class of failure. Can you hand this list to @ixdy?

2016-11-30 21:34 UTC, ixdy commented
Updating SQ to include the failing statuses in its status line seems like a non-trivial amount of refactoring in `contrib/mungegithub/github/github.go` (i.e. I can't do it right now), so I opened https://github.com/kubernetes/contrib/issues/2102 to track.

2016-11-30 21:37 UTC, ixdy commented
I just noticed that the merge requirements tab on http://submit-queue.k8s.io/#/info shows you what builds are needed. No need for humans to read the configmap!

2016-11-30 21:43 UTC, eparis commented
yeah, I wrote the code yesterday. I'll get it posted tomorrow for review for the bot to auto-manage branch protection.

2016-11-30 22:31 UTC, saad-ali commented
> Thanks so much for resolving this @ixdy. @saad-ali you said there were other instances of this class of failure. Can you hand this list to @ixdy?

https://github.com/kubernetes/kubernetes/pull/37629 and https://github.com/kubernetes/kubernetes/pull/37593 were the other two that folks complained about in Slack, but looks like they are both being re-run now.

2016-12-01 05:21 UTC, saad-ali commented
@k8s-bot cvm gce e2e test this

2016-12-01 07:26 UTC, merged