pod evictor could leave completed pod
kubernetes/kubernetes pull request #37440
Opened 2016-11-24 10:22 UTC by sandflee

**What this PR does / why we need it**:
pod evictor in node controller will delete all pods on node,  seems not nessesary to delete completed pods, because it may created by a job controller, we may analyze the completed pod

2016-11-24 10:45 UTC, sandflee commented
I signed it!

2016-11-26 22:58 UTC, dims commented
@k8s-bot ok to test

2016-11-28 20:49 UTC, derekwaynecarr commented
The use case makes sense to me, but I think we should have a test case for this as well.

FYI @smarterclayton @gmarek

2016-11-28 21:46 UTC, gmarek commented
We also should have different way of monitoring job status... @soltysh

2016-11-30 12:21 UTC, soltysh commented
@gmarek yes, there's https://github.com/kubernetes/kubernetes/issues/28486 to address the problem. I just need time 😉

2017-01-13 19:03 UTC, derekwaynecarr commented
@sandflee -- are you able to add the test case requested?  if so, this looks good.

2017-01-13 19:03 UTC, derekwaynecarr commented
@k8s-bot test this

2017-02-06 14:55 UTC, gmarek commented
@k8s-bot test this

2017-03-08 22:52 UTC, sandflee commented
@derekwaynecarr , sorry for the delay, I will add a test.

2017-03-10 19:23 UTC, derekwaynecarr commented
@sandflee -- please let me know when this is addressed.  is there an issue open that we can point as fixed by this change?  this seems like a reasonable bug fix for 1.6 if we have an issue opened.

2017-03-10 19:26 UTC, derekwaynecarr requested changes
just poke when test is added.

if done soon, this may make 1.6 milestone.

2017-03-11 02:51 UTC, sandflee commented
there is no issue to address this, I'll add a test this weekend

2017-03-12 22:58 UTC, sandflee commented
@derekwaynecarr ,test added

2017-04-03 08:33 UTC, gmarek commented on pkg/controller/node/nodecontroller_test.go
> +	succPod := testutil.NewPod("pod0", "node0")
Can you please create a separate test case for this? We're getting close to 1000-line test case, and I really don't want to get there...

2017-07-08 17:48 UTC, closed without merging