Report the Pod name and namespace when kubelet fails to sync the container
kubernetes/kubernetes pull request #37680
Opened 2016-11-30 11:03 UTC by mfojtik

This helps debugging problems with SELinux (and other problems related to the Docker failed to run the container) as currently only the UUID of the Pod is reported:

```
Error syncing pod 670f607d-b5a8-11a4-b673-005056b7468b, skipping: failed to "StartContainer" for "deployment" with RunContainerError: "runContainer: Error response from daemon: Relabeling content in /usr is not allowed."
```

Here it would be useful to know what pod in which namespace is trying to mount the "/usr".

2016-11-30 11:04 UTC, soltysh commented
@derekwaynecarr fyi
LGTM

2016-12-01 22:26 UTC, derekwaynecarr requested changes

2016-12-01 22:26 UTC, derekwaynecarr commented on pkg/kubelet/pod_workers.go
> +			glog.Errorf("Error syncing pod %s (%s/%s), skipping: %v", update.Pod.UID, update.Pod.Namespace, update.Pod.Name, err)
this should use https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/format/pod.go#L32

2017-01-13 18:58 UTC, derekwaynecarr commented
@mfojtik -- want to make the quick change?

2017-01-16 15:45 UTC, mfojtik commented
@derekwaynecarr @soltysh updated

2017-01-17 07:09 UTC, soltysh commented
Thanks, I'm approving based on previous approval and comments being addressed.

2017-01-17 07:59 UTC, merged