Refactor REST storage to use generic defaults
kubernetes/kubernetes pull request #37770
Opened 2016-12-01 02:21 UTC by enj

This removes the repetition in the REST storage builders by moving the logic to `restoptions.ApplyOptions`.  `registry.StorageWithCacher`/`generic.StorageDecorator` no longer assume that they can build the `keyFunc` for arbitrary objects.  `restoptions.ApplyOptions` uses the `registry.Store`'s `KeyFunc` for its call to `generic.StorageDecorator`.

Signed-off-by: Monis Khan <mkhan@redhat.com>

2016-12-01 02:21 UTC, enj commented
@liggitt PTAL

2016-12-01 15:01 UTC, liggitt commented
@k8s-bot ok to test

2016-12-02 08:52 UTC, sttts commented on pkg/util/restoptions/helpers.go
> +func defaultKeyFunctions(store *registry.Store, prefix string) {
this is what we call "completion" in the genericapiserver. Suggestion: rename to `completeKeyFunctions`

2016-12-02 08:58 UTC, sttts commented on pkg/util/restoptions/helpers.go
> +	store.DeleteCollectionWorkers = opts.DeleteCollectionWorkers
What I don't like is that `ApplyOptions` partly expects values in `Store` to be set, some are overwritten, some are completed (= set with defaults if they are unset). In other words: it's a hybrid of a constructor and a completer. This makes it semantics hard to reason about. I would prefer to either make it a constructor of a registry.Store **or** a completer.

2016-12-02 11:22 UTC, soltysh requested changes

2016-12-02 11:22 UTC, soltysh commented on pkg/registry/core/event/etcd/etcd.go
> +func NewREST(optsGetter genericapiserver.RESTOptionsGetter, ttl uint64) *REST {
Is there any particular reason you didn't apply this same pattern here?

2016-12-02 11:22 UTC, soltysh commented on pkg/registry/extensions/controller/etcd/etcd.go
> +func NewStorage(optsGetter genericapiserver.RESTOptionsGetter) ContainerStorage {
Isn't the fact we're reusing storage from RS causing your problem?

2016-12-02 11:22 UTC, soltysh commented on pkg/util/restoptions/helpers.go
> +	store.DeleteCollectionWorkers = opts.DeleteCollectionWorkers
I'm not sure constructor is what we look for here. I'm rather seeing here a validation of the `Store` object and a defaulter/completer. Renaming it to something more appropriate would be ok ;)

2016-12-02 21:19 UTC, enj commented on pkg/util/restoptions/helpers.go
> +func ApplyOptions(optsGetter genericapiserver.RESTOptionsGetter, store *registry.Store, triggerFn storage.TriggerPublisherFunc) {
@liggitt Thoughts?

2016-12-02 21:21 UTC, enj commented on pkg/util/restoptions/helpers.go
> +	store.DeleteCollectionWorkers = opts.DeleteCollectionWorkers
IMO a constructor would constrain things too much here.  Not all `NewREST` implementations follow the exact same pattern (the variation is slight but it is there).

2016-12-02 21:26 UTC, enj commented
@liggitt @soltysh Any idea why [pull-kubernetes-e2e-kops-aws](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/37770/pull-kubernetes-e2e-kops-aws/2545/) is failing?

2016-12-05 07:02 UTC, sttts commented
@enj you can ignore the aws kops job. It's failing for days. It's not necessary to get this merged.

2016-12-05 22:45 UTC, enj commented
@liggitt @soltysh @sttts PTAL; ready for merge if tests pass / you guys are good.

2016-12-06 16:17 UTC, soltysh reviewed
Nits, but overall LGTM. Get Jordan approval and merge.

2016-12-06 16:17 UTC, soltysh commented on federation/registry/cluster/etcd/etcd.go
> +		panic(err) // TODO: Propagate error up
Why this TODO, isn't panic sufficient error propagation?

2016-12-06 16:17 UTC, soltysh commented on federation/registry/cluster/etcd/etcd.go
> +		panic(err) // TODO: Propagate error up
This applies to all other TODOs as well.

2016-12-06 16:17 UTC, soltysh commented on pkg/master/master.go
> +		return nil, fmt.Errorf("Unable to find storage destination for %v, due to %v", resource, err.Error())
Why not having the `glog.Fatalf` here as before?

2016-12-06 16:17 UTC, soltysh commented on pkg/master/master.go
> +		return nil, fmt.Errorf("Unable to find storage destination for %v, due to %v", resource, err.Error())
Actually, not returning error here but `glog.Fatalf` would drop all those panics from `*/etcd.go` files?

2016-12-06 17:18 UTC, liggitt requested changes

2016-12-06 17:18 UTC, liggitt commented on pkg/registry/generic/registry/store.go
> +func (e *Store) completeKeyFunctions(prefix string) {
inline this function

2016-12-06 17:18 UTC, liggitt commented on pkg/registry/generic/registry/store.go
> +	if e.CreateStrategy.NamespaceScoped() {
use computed isNamespaced

2016-12-06 19:00 UTC, enj commented on pkg/master/master.go
> +		return nil, fmt.Errorf("Unable to find storage destination for %v, due to %v", resource, err.Error())
This was on purpose -- it is very strange to me to call a method with perfectly valid input and have it `panic`.  Standard Go code returns an error in such cases.

2016-12-06 21:52 UTC, enj commented on pkg/registry/extensions/rest/storage_extensions.go
> -		hpaStorage, hpaStatusStorage := horizontalpodautoscaleretcd.NewREST(restOptionsGetter(extensions.Resource("horizontalpodautoscalers")))
`extensions.Resource("horizontalpodautoscalers")` -> `autoscaling.Resource("horizontalpodautoscalers")`

2016-12-06 21:55 UTC, enj commented on pkg/registry/extensions/rest/storage_extensions.go
> -		jobsStorage, jobsStatusStorage := jobetcd.NewREST(restOptionsGetter(extensions.Resource("jobs")))
`extensions.Resource("jobs")` -> `batch.Resource("jobs")`

2016-12-06 21:56 UTC, enj commented on federation/cmd/federation-apiserver/app/core.go
> -	serviceStore, serviceStatusStore := serviceetcd.NewREST(restOptionsFactory.NewFor(api.Resource("service")))
`api.Resource("service")` -> `api.Resource("services")`

2016-12-06 21:57 UTC, enj commented on pkg/registry/extensions/rest/storage_extensions.go
> -		podSecurityExtensionsStorage := pspetcd.NewREST(restOptionsGetter(extensions.Resource("podsecuritypolicy")))
`extensions.Resource("podsecuritypolicy")` -> `extensions.Resource("podsecuritypolicies")`

2016-12-06 22:04 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	controllerStorage := controlleretcd.NewStorage(restOptionsGetter(api.Resource("replicationControllers")))
`api.Resource("replicationControllers")` -> `api.Resource("replicationcontrollers")`

2016-12-06 22:06 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	configMapStorage := configmapetcd.NewREST(restOptionsGetter(api.Resource("configMaps")))
`api.Resource("configMaps")` -> `api.Resource("configmaps")`

2016-12-06 22:07 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	persistentVolumeClaimStorage, persistentVolumeClaimStatusStorage := pvcetcd.NewREST(restOptionsGetter(api.Resource("persistentVolumeClaims")))
`api.Resource("persistentVolumeClaims")` -> `api.Resource("persistentvolumeclaims")`

2016-12-06 22:08 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	podTemplateStorage := podtemplateetcd.NewREST(restOptionsGetter(api.Resource("podTemplates")))
`api.Resource("podTemplates")` -> `api.Resource("podtemplates")`

2016-12-06 22:09 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	limitRangeStorage := limitrangeetcd.NewREST(restOptionsGetter(api.Resource("limitRanges")))
`api.Resource("limitRanges")` -> `api.Resource("limitranges")`

2016-12-06 22:09 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	resourceQuotaStorage, resourceQuotaStatusStorage := resourcequotaetcd.NewREST(restOptionsGetter(api.Resource("resourceQuotas")))
`api.Resource("resourceQuotas")` -> `api.Resource("resourcequotas")`

2016-12-06 22:10 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	serviceAccountStorage := serviceaccountetcd.NewREST(restOptionsGetter(api.Resource("serviceAccounts")))
`api.Resource("resourceQuotas")` -> `api.Resource("resourcequotas")`

2016-12-06 22:10 UTC, enj commented on pkg/registry/core/rest/storage_core.go
> -	persistentVolumeStorage, persistentVolumeStatusStorage := pvetcd.NewREST(restOptionsGetter(api.Resource("persistentVolumes")))
`api.Resource("persistentVolumes")` -> `api.Resource("persistentvolumes")`

2016-12-06 22:13 UTC, enj commented
Flake on #38198

2016-12-06 22:15 UTC, enj commented on pkg/registry/extensions/rest/storage_extensions.go
> -		hpaStorage, hpaStatusStorage := horizontalpodautoscaleretcd.NewREST(restOptionsGetter(extensions.Resource("horizontalpodautoscalers")))
@liggitt not sure what to do here since the package changes.

2016-12-06 22:15 UTC, enj commented on pkg/registry/extensions/rest/storage_extensions.go
> -		jobsStorage, jobsStatusStorage := jobetcd.NewREST(restOptionsGetter(extensions.Resource("jobs")))
@liggitt same issue as above.

2016-12-06 22:33 UTC, enj commented on pkg/genericapiserver/storage_factory.go
>  var specialDefaultResourcePrefixes = map[schema.GroupResource]string{
@liggitt please validate this.

2016-12-07 02:13 UTC, liggitt commented on pkg/registry/core/rest/storage_core.go
> -	configMapStorage := configmapetcd.NewREST(restOptionsGetter(api.Resource("configMaps")))
fortunately, DefaultStorageFactory lowercased the resource (`etcdResourcePrefix = strings.ToLower(chosenStorageResource.Resource)`) so you don't need these

2016-12-07 02:22 UTC, liggitt commented on pkg/registry/extensions/rest/storage_extensions.go
> -		jobsStorage, jobsStatusStorage := jobetcd.NewREST(restOptionsGetter(extensions.Resource("jobs")))
same answer

2016-12-07 03:14 UTC, liggitt commented on pkg/registry/extensions/rest/storage_extensions.go
> -		podSecurityExtensionsStorage := pspetcd.NewREST(restOptionsGetter(extensions.Resource("podsecuritypolicy")))
this was already in etcd under /podsecuritypolicies... you need to create these objects against a server running from master to see the current etcd paths before adding an exception mapping to specialDefaultResourcePrefixes

2016-12-07 03:21 UTC, liggitt commented on pkg/registry/extensions/rest/storage_extensions.go
> -		podSecurityExtensionsStorage := pspetcd.NewREST(restOptionsGetter(extensions.Resource("podsecuritypolicy")))
edit: I take it back... this was a good catch. I had a fix for the ResourceEnabled check locally and had changed the restOptionsGetter call accidentally as well

2016-12-07 03:24 UTC, liggitt commented on pkg/genericapiserver/storage_factory.go
>  var specialDefaultResourcePrefixes = map[schema.GroupResource]string{
running from master, here are the calls to get resource prefixes:
```
ResourcePrefix: schema.GroupResource{Group:"", Resource:"configMaps"}=configmaps
ResourcePrefix: schema.GroupResource{Group:"", Resource:"endpoints"}=services/endpoints
ResourcePrefix: schema.GroupResource{Group:"", Resource:"events"}=events
ResourcePrefix: schema.GroupResource{Group:"", Resource:"limitRanges"}=limitranges
ResourcePrefix: schema.GroupResource{Group:"", Resource:"namespaces"}=namespaces
ResourcePrefix: schema.GroupResource{Group:"", Resource:"nodes"}=minions
ResourcePrefix: schema.GroupResource{Group:"", Resource:"persistentVolumeClaims"}=persistentvolumeclaims
ResourcePrefix: schema.GroupResource{Group:"", Resource:"persistentVolumes"}=persistentvolumes
ResourcePrefix: schema.GroupResource{Group:"", Resource:"podTemplates"}=podtemplates
ResourcePrefix: schema.GroupResource{Group:"", Resource:"pods"}=pods
ResourcePrefix: schema.GroupResource{Group:"", Resource:"replicationControllers"}=controllers
ResourcePrefix: schema.GroupResource{Group:"", Resource:"resourceQuotas"}=resourcequotas
ResourcePrefix: schema.GroupResource{Group:"", Resource:"secrets"}=secrets
ResourcePrefix: schema.GroupResource{Group:"", Resource:"serviceAccounts"}=serviceaccounts
ResourcePrefix: schema.GroupResource{Group:"", Resource:"services"}=services/specs
ResourcePrefix: schema.GroupResource{Group:"apps", Resource:"statefulsets"}=statefulsets
ResourcePrefix: schema.GroupResource{Group:"autoscaling", Resource:"horizontalpodautoscalers"}=horizontalpodautoscalers
ResourcePrefix: schema.GroupResource{Group:"batch", Resource:"jobs"}=jobs
ResourcePrefix: schema.GroupResource{Group:"certificates.k8s.io", Resource:"certificatesigningrequests"}=certificatesigningrequests
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"daemonsets"}=daemonsets
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"deployments"}=deployments
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"horizontalpodautoscalers"}=horizontalpodautoscalers
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"ingresses"}=ingress
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"jobs"}=jobs
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"networkpolicies"}=networkpolicies
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"podsecuritypolicy"}=podsecuritypolicy
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"replicasets"}=replicasets
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"thirdpartyresources"}=thirdpartyresources
ResourcePrefix: schema.GroupResource{Group:"policy", Resource:"poddisruptionbudgets"}=poddisruptionbudgets
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"clusterrolebindings"}=clusterrolebindings
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"clusterroles"}=clusterroles
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"rolebindings"}=rolebindings
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"roles"}=roles
ResourcePrefix: schema.GroupResource{Group:"storage.k8s.io", Resource:"storageclasses"}=storageclasses
```

2016-12-07 03:42 UTC, liggitt commented on federation/cmd/federation-apiserver/app/core.go
> -	serviceStore, serviceStatusStore := serviceetcd.NewREST(restOptionsFactory.NewFor(api.Resource("service")))
oh... this is the federation-apiserver... it's going to be really painful to get the serviceetcd to use different etcd prefixes for different servers. opened https://github.com/kubernetes/kubernetes/issues/38262 to see if we can fix it. if not, federation will need to override the etcd location for services specially

2016-12-07 03:43 UTC, liggitt commented on pkg/genericapiserver/storage_factory.go
> +	schema.GroupResource{Group: "", Resource: "service"}:                       "services/specs",
remove this, this was federation only and they need `schema.GroupResource{Group: "", Resource: "services"}` to map to `service`, which we can't do here

2016-12-07 03:43 UTC, liggitt commented on pkg/genericapiserver/storage_factory.go
> +	schema.GroupResource{Group: "", Resource: "configmaps"}:                    "configMaps",
remove all the mixed-case mappings you added... those were correctly being lowercased before

2016-12-07 22:05 UTC, enj commented on pkg/registry/extensions/rest/storage_extensions.go
> -		hpaStorage, hpaStatusStorage := horizontalpodautoscaleretcd.NewREST(restOptionsGetter(extensions.Resource("horizontalpodautoscalers")))
[This](https://github.com/kubernetes/kubernetes/blob/f92039175526c0d359eaa4e887e938904870ec41/cmd/kube-apiserver/app/server.go#L195-L196) seems to handle that case?

2016-12-08 00:19 UTC, enj commented
@liggitt this is ready to merge other than (which I do not have rights to do):

>Please add a release-note-action-required label and add release note saying that this changes the etcd prefix and users need to recreate their services. They need to first read all services, store the YAMLs somewhere and delete the services. Then upgrade the cluster and finally write the services YAMLs back.

2016-12-08 16:24 UTC, enj commented
@liggitt everything seems to be the same:

```
ResourcePrefix: schema.GroupResource{Group:"", Resource:"configmaps"}=configmaps
ResourcePrefix: schema.GroupResource{Group:"", Resource:"endpoints"}=services/endpoints
ResourcePrefix: schema.GroupResource{Group:"", Resource:"events"}=events
ResourcePrefix: schema.GroupResource{Group:"", Resource:"limitranges"}=limitranges
ResourcePrefix: schema.GroupResource{Group:"", Resource:"namespaces"}=namespaces
ResourcePrefix: schema.GroupResource{Group:"", Resource:"nodes"}=minions
ResourcePrefix: schema.GroupResource{Group:"", Resource:"persistentvolumeclaims"}=persistentvolumeclaims
ResourcePrefix: schema.GroupResource{Group:"", Resource:"persistentvolumes"}=persistentvolumes
ResourcePrefix: schema.GroupResource{Group:"", Resource:"pods"}=pods
ResourcePrefix: schema.GroupResource{Group:"", Resource:"podtemplates"}=podtemplates
ResourcePrefix: schema.GroupResource{Group:"", Resource:"replicationcontrollers"}=controllers
ResourcePrefix: schema.GroupResource{Group:"", Resource:"resourcequotas"}=resourcequotas
ResourcePrefix: schema.GroupResource{Group:"", Resource:"secrets"}=secrets
ResourcePrefix: schema.GroupResource{Group:"", Resource:"serviceaccounts"}=serviceaccounts
ResourcePrefix: schema.GroupResource{Group:"", Resource:"services"}=services/specs
ResourcePrefix: schema.GroupResource{Group:"apps", Resource:"statefulsets"}=statefulsets
ResourcePrefix: schema.GroupResource{Group:"autoscaling", Resource:"horizontalpodautoscalers"}=horizontalpodautoscalers
ResourcePrefix: schema.GroupResource{Group:"batch", Resource:"jobs"}=jobs
ResourcePrefix: schema.GroupResource{Group:"certificates.k8s.io", Resource:"certificatesigningrequests"}=certificatesigningrequests
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"daemonsets"}=daemonsets
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"deployments"}=deployments
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"ingresses"}=ingress
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"networkpolicies"}=networkpolicies
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"podsecuritypolicies"}=podsecuritypolicy
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"replicasets"}=replicasets
ResourcePrefix: schema.GroupResource{Group:"extensions", Resource:"thirdpartyresources"}=thirdpartyresources
ResourcePrefix: schema.GroupResource{Group:"policy", Resource:"poddisruptionbudgets"}=poddisruptionbudgets
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"clusterrolebindings"}=clusterrolebindings
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"clusterroles"}=clusterroles
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"rolebindings"}=rolebindings
ResourcePrefix: schema.GroupResource{Group:"rbac.authorization.k8s.io", Resource:"roles"}=roles
ResourcePrefix: schema.GroupResource{Group:"storage.k8s.io", Resource:"storageclasses"}=storageclasses
```

2016-12-08 16:26 UTC, liggitt commented on pkg/registry/extensions/rest/storage_extensions.go
>  	if apiResourceConfigSource.ResourceEnabled(version.WithResource("podsecuritypolicy")) {
I would check either:
```
if apiResourceConfigSource.ResourceEnabled(version.WithResource("podsecuritypolicy")) || apiResourceConfigSource.ResourceEnabled(version.WithResource("podsecuritypolicies")) {
...
```

2016-12-08 17:47 UTC, enj commented
@k8s-bot gci gce e2e test this

2016-12-08 17:49 UTC, liggitt commented
@k8s-bot gci gce e2e test this

2016-12-08 18:06 UTC, liggitt commented on cmd/kubernetes-discovery/pkg/registry/apiservice/etcd/etcd.go
> +func NewREST(optsGetter generic.RESTOptionsGetter) *REST {
@deads2k PTAL at this file

2016-12-08 18:10 UTC, liggitt commented on examples/apiserver/rest/reststorage.go
>  func NewREST(config *storagebackend.Config, storageDecorator generic.StorageDecorator) *REST {
change the signature to match what we want... passing in a RESTOptionsGetter

2016-12-08 18:10 UTC, liggitt commented on examples/apiserver/rest/reststorage.go
> +		QualifiedResource: api.Resource("testtype"),
plural `testtypes`

2016-12-08 18:11 UTC, liggitt commented on examples/apiserver/rest/reststorage.go
> +	getAttrs := func(obj runtime.Object) (labels.Set, fields.Set, error) {
separate the GetAttrs func and a Matcher func that uses it and reference them

2016-12-08 18:24 UTC, liggitt commented on pkg/registry/extensions/controller/etcd/etcd.go
> +	"k8s.io/kubernetes/pkg/registry/generic"
order is wrong

2016-12-08 18:38 UTC, liggitt commented on pkg/registry/generic/registry/store.go
> +
make sure prefix is not just `/`

2016-12-08 18:40 UTC, liggitt commented on pkg/registry/generic/registry/store.go
> +		if e.KeyRootFunc == nil {
I think if someone wants to customize keyfuncs, they should customize both... check at the top and err in this case:
```
if (e.KeyRootFunc == nil) != (e.KeyFunc == nil) {
...
}
```

2016-12-08 18:41 UTC, liggitt commented on pkg/registry/generic/registry/store.go
> +		if e.KeyRootFunc == nil {
and here, invert the check:
```
if e.KeyRootFunc == nil && e.KeyFunc == nil {
  if isNamespaced {
    ...
  } else {
    ...
  }
}
```

2016-12-08 18:47 UTC, liggitt commented on pkg/registry/rbac/rest/storage_rbac.go
move the construction of the storage objects up... we want to share them between the rule resolver and the rest storage so we share watch caches

2016-12-08 18:49 UTC, liggitt commented on pkg/registry/rbac/rest/storage_rbac.go
be careful not to initialize storage if all types are disabled

2016-12-08 23:56 UTC, enj commented
@liggitt merge?

2016-12-09 07:05 UTC, liggitt commented
@k8s-bot kubemark e2e test this

2016-12-09 07:06 UTC, liggitt approved these changes

2016-12-09 07:08 UTC, liggitt commented
/lgtm

2016-12-09 07:09 UTC, liggitt commented
would like to see the follow up e2e that checks registered types against known paths in etcd

2016-12-09 08:25 UTC, merged

2016-12-12 09:33 UTC, wojtek-t commented
It seems that this PR significantly broke performance in large clusters. My feeling is that the main reason for that was enabling cacher for "events" resource. I will send out a PR to fix it (hopefully it will help).

2016-12-12 09:33 UTC, wojtek-t commented
@smarterclayton @kubernetes/sig-scalability ^^

2016-12-12 09:38 UTC, wojtek-t commented
Actually, I was wrong, cacher seems still be switched off for events. 
```
opts.Decorator = generic.UndecoratedStorage // TODO use watchCacheSize=-1 to signal UndecoratedStorage
```
But it still seems that this PR is breaking performance - will try to dig deeper.

2016-12-12 09:56 UTC, wojtek-t commented
And to clarify - we are observing significantly higher (even more than 2x) latencies mostly (but not only) on LIST pods calls.

2016-12-12 11:40 UTC, wojtek-t commented
I filed https://github.com/kubernetes/kubernetes/issues/38610 for debugging and fixing it

2016-12-12 12:35 UTC, liggitt commented
The resulting stores should be the same as they were before with the exception of the storage decorator's keyfunc delegating to the store's keyfunc.

2016-12-12 12:42 UTC, wojtek-t commented
@liggitt - yeah, I went through the whole PR and it looks ok to me. Though the timing of merge matches timing of regression. We will try to debug deeper.