improve the result of checking role name
kubernetes/kubernetes pull request #37934
Opened 2016-12-02 09:26 UTC by xilabao

Get all error message before return.

2016-12-04 16:10 UTC, dims commented
@k8s-bot ok to test

2016-12-10 03:29 UTC, liggitt commented on pkg/api/validation/path/name.go
> +	message := []string{}
declaring a slice var starts it out as nil, avoids the allocation in error-free cases, and removes the need to check for length:
```
var errors []string
...
for ... {
  errors = append(errors, ...)
}
return errors
```

2016-12-10 03:30 UTC, liggitt commented on pkg/api/validation/path/name.go
> +	message := []string{}
same here

2016-12-10 03:30 UTC, liggitt requested changes
small tweak on allocation and length check, looks good otherwise. a unit test would probably be good as well.

2016-12-12 02:24 UTC, xilabao commented
@liggitt PTAL

2016-12-12 03:35 UTC, liggitt commented on pkg/api/validation/path/name_test.go
> +			ExpectedMsg: "/%",
This is odd… I expected the list of expected messages

2016-12-12 03:35 UTC, liggitt commented on pkg/api/validation/path/name_test.go
> +func TestValidateWithMutliErrors(t *testing.T) {
Typo "Multi"

2016-12-12 03:46 UTC, xilabao commented on pkg/api/validation/path/name_test.go
> +func TestValidateWithMutliErrors(t *testing.T) {
fixed

2016-12-12 03:55 UTC, liggitt commented
/lgtm

2016-12-12 05:08 UTC, merged