add --manifest-url-headers
kubernetes/kubernetes pull request #38089
Opened 2016-12-05 07:27 UTC by chentao1596

**What this PR does / why we need it**:
Only support one header parameter when getting pod from HTTP source, it's not work very well when server need multi header parameters.
1，Add one run parameter for kubelet: "manifest-url-headers" - to be used to supporting more than one HTTP header
2，Commit some auto-generated codes

**Release note**:
# master

[Documentation](http://kubernetes.github.io) & [Examples](http://releases.k8s.io/master/examples)

## Changelog since v1.5.0-alpha.2

### Action Required

* Deprecate extensions/v1beta1.Jobs (#36355, @soltysh)
* Rename ScheduledJobs to CronJobs. (#36021, @soltysh)
* Read the federation controller manager kubeconfig from a filesystem path (#30601, @madhusudancs)
* Node controller to not force delete pods (#35235, @foxish)
* Add perma-failed deployments API (#19343, @kargakis)

### Other notable changes

* Curating Owners: pkg/api (#36525, @apelisse)
* Reduce verbosity of volume reconciler when attaching volumes (#36900, @codablock)
* Federated Ingress Proposal (#29793, @quinton-hoole)
* Collect installation and configuration service logs for tests (#37401, @mtaufen)
* Fix a bug in scheduler happening after retrying unsuccessful bindings (#37293, @wojtek-t)
* Use shasum if sha1sum doesn't exist in the path (#37362, @roberthbailey)
* Modify GCI mounter to enable NFSv3 (#36610, @jingxu97)
* Guard the ready replica checking by server version (#37303, @krousey)
* Include serial port output in GCP log-dump (#37248, @mtaufen)
* Filter out non-RestartAlways mirror pod in restart test. (#37203, @Random-Liu)
* Third party resources are now deleted when a namespace is deleted. (#35947, @brendandburns)
* kube-dns (#36775, @bowei)
    * Added --config-map and --config-map-namespace command line options. 
    * If --config-map is set, kube-dns will load dynamic configuration from the config map 
    * referenced by --config-map-namespace, --config-map. The config-map supports
    * the following properties: "federations".
    * --federations flag is now deprecated. Prefer to set federations via the config-map.
    * Federations can be configured by settings the "federations" field to the value currently 
    * set in the command line.
    * Example:
    *   kind: ConfigMap
    *   apiVersion: v1
    *   metadata:
    *     name: kube-dns
    *     namespace: kube-system
    *   data:
    *     federations: abc=def
* azure: support multiple ipconfigs on a NIC (#36841, @colemickens)
* Fix issue in converting AWS volume ID from mount paths (#36840, @jingxu97)
* Change image-puller restart policy to OnFailure (#37070, @gmarek)
* fix leaking memory backed volumes of terminated pods (#36779, @sjenning)
* Default logging subsystem's resiliency was greatly improved, fluentd memory consumption and OOM error probability was reduced. (#37021, @Crassirostris)
* Federation: allow specification of dns zone by ID (#36336, @justinsb)
* Replace controller presence checking logic (#36924, @krousey)
* K8s 1.5 keeps container-vm as the default node image on GCE for backwards compatibility reasons. Please beware that container-vm is officially supported with security patches only and you should replace it with GCI if at all possible. You can review the migration guide here for more detail: https://cloud.google.com/container-engine/docs/node-image-migration (#36822, @mtaufen)
* Add a flag allowing contention profiling of the API server (#36756, @gmarek)
* Rename `--cgroups-per-qos` to `--experimental-cgroups-per-qos` in Kubelet (#36767, @vishh)
* Implement CanMount() for gfsMounter for linux (#36686, @rkouj)
* Default host user namespace via experimental flag (#31169, @pweil-)
* Use generous limits in the resource usage tracking tests (#36623, @yujuhong)
* Update Dashboard UI version to 1.4.2 (#35895, @rf232)
* Add support for service load balancer source ranges to Azure load balancers. (#36696, @brendandburns)
* gci-dev-56-8977-0-0: (#36681, @mtaufen)
    * Date:           Nov 03, 2016
    * Kernel:         ChromiumOS-4.4
    * Kubernetes:     v1.4.5
    * Docker:         v1.11.2
    * Changelog (vs 55-8872-18-0)
            * Updated kubernetes to v1.4.5
            * Fixed a bug in e2fsprogs that caused mke2fs to take a very long time. Upstream fix: http://git.kernel.org/cgit/fs/ext2/e2fsprogs.git/commit/?h=next&id=d33e690fe7a6cbeb51349d9f2c7fb16a6ebec9c2
* Fix strategic patch for list of primitive type with merge sementic (#35647, @ymqytw)
* Fix issue in reconstruct volume data when kubelet restarts (#36616, @jingxu97)
* Ensure proper serialization of updates and creates in federation test watcher (#36613, @mwielgus)
* Add support for SourceIP preservation in Azure LBs (#36557, @brendandburns)
* Fix fetching pids running in a cgroup, which caused problems with OOM score adjustments & setting the /system cgroup ("misc" in the summary API). (#36551, @timstclair)
* federation: Adding support for DeleteOptions.OrphanDependents for federated replicasets and deployments. Setting it to false while deleting a federated replicaset or deployment also deletes the corresponding resource from all registered clusters. (#36476, @nikhiljindal)
* kubectl: show node label if defined (#35901, @justinsb)
* Migrates addons from RCs to Deployments (#36008, @MrHohn)
* Avoid setting S_ISGID on files in volumes (#36386, @sjenning)
* federation: Adding support for DeleteOptions.OrphanDependents for federated daemonsets and ingresses. Setting it to false while deleting a federated daemonset or ingress also deletes the corresponding resource from all registered clusters. (#36330, @nikhiljindal)
* Add authz to psp admission (#33080, @pweil-)
* Better messaging for missing volume binaries on host (#36280, @rkouj)
* Add Windows support to kube-proxy (#36079, @jbhurat)
* Support persistent volume usage for kubernetes running on Photon Controller platform (#36133, @luomiao)
* GCI nodes use an external mounter script to mount NFS & GlusterFS storage volumes (#36267, @vishh)
* Add retry to node scheduability marking. (#36211, @brendandburns)
* specify custom ca file to verify the keystone server (#35488, @dixudx)
* AWS: Support default value for ExternalHost (#33568, @justinsb)
* HPA: Consider unready pods separately (#33593, @DirectXMan12)
* Node Conformance Test: Containerize the node e2e test (#31093, @Random-Liu)
* federation: Adding support for DeleteOptions.OrphanDependents for federated secrets. Setting it to false while deleting a federated secret also deletes the corresponding secrets from all registered clusters. (#36296, @nikhiljindal)
* Deploy kube-dns with cluster-proportional-autoscaler (#33239, @MrHohn)
* Adds support for StatefulSets in kubectl drain. (#35483, @ymqytw)
    * Switches to use the eviction sub-resource instead of deletion in kubectl drain, if server supports.
* azure: load balancer preserves destination ip address (#36256, @colemickens)
* LegacyHostIP will be deprecated in 1.7. (#36095, @caesarxuchao)
* Fix LBaaS version detection in openstack cloudprovider (#36249, @sjenning)
* Node Conformance Test: Add system verification (#32427, @Random-Liu)
* kubelet bootstrap: start hostNetwork pods before we have PodCIDR (#35526, @justinsb)
* Enable HPA controller based on autoscaling/v1 api group (#36215, @piosz)
* Remove unused WaitForDetach from Detacher interface and plugins (#35629, @kiall)
* Initial work on running windows containers on Kubernetes (#31707, @alexbrand)
* Per Volume Inode Accounting (#35132, @dashpole)
* [AppArmor] Hold bad AppArmor pods in pending rather than rejecting (#35342, @timstclair)
* Federation: separate notion of zone-name & dns-suffix (#35372, @justinsb)
* In order to bypass graceful deletion of pods (to immediately remove the pod from the API) the user must now provide the `--force` flag in addition to `--grace-period=0`.  This prevents users from accidentally force deleting pods without being aware of the consequences of force deletion.  Force deleting pods for resources like StatefulSets can result in multiple pod [...]

2016-12-05 13:28 UTC, liggitt requested changes

2016-12-05 13:28 UTC, liggitt commented on cmd/kubelet/app/options/options.go
> +	fs.MarkDeprecated("manifest-url-header", "Use --manifest-url-headers instead. Will be removed in a future version.")
Use string array var and specify multiple times. We don't want to use stringslicevar with data that could contain commas

2016-12-05 13:33 UTC, vishh commented
Why is this change necessary?

2016-12-05 13:43 UTC, liggitt commented on cmd/kubelet/app/options/options.go
> +	fs.MarkDeprecated("manifest-url-header", "Use --manifest-url-headers instead. Will be removed in a future version.")
Actually, you can make the existing arg a string array var, repeat it if needed and avoid depreciation altogether

2016-12-06 06:49 UTC, chentao1596 commented
@liggitt I changed the type of "--manifest-url-header" to "stringArray", i think you are right: using exist param is better, rather than adding the other one. PTAL, thx!

2016-12-06 06:49 UTC, chentao1596 commented
@vishh hi, my HTTP server need multi headers when getting pods from it, but kubelet just support one until now. In this case, i must change implemention of HTTP server to get used to it, it's not very convenient, so i think it's better if support multi headers, thx!

2016-12-06 18:46 UTC, yujuhong commented
Please remove the k8s release note that's not relevant to this PR in https://github.com/kubernetes/kubernetes/pull/38089#issue-193428543

2016-12-06 20:51 UTC, timstclair commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.ManifestURLHeader = *(*[]string)(unsafe.Pointer(&in.ManifestURLHeader))
why is this cast necessary?

2016-12-06 20:51 UTC, timstclair commented on pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
> +			in, out := &in.ManifestURLHeader, &out.ManifestURLHeader
don't need to use pointers here

2016-12-07 04:23 UTC, chentao1596 commented
@timstclair This code was generated by the script "hack/update-codecgen.sh", i should not to edit them, whether my understanding is right？thank you!

2016-12-07 04:24 UTC, chentao1596 commented
@yujuhong I removed it, thank you!

2016-12-07 18:48 UTC, timstclair commented
> @timstclair This code was generated by the script "hack/update-codecgen.sh", i should not to edit them, whether my understanding is right？thank you! 

I'm sorry, I didn't notice they were generated files. You're right.

2016-12-12 03:46 UTC, chentao1596 commented
@liggitt @vishh @yujuhong @timstclair hi, can someone take another look? thx!

2017-01-01 08:06 UTC, roberthbailey commented on cmd/kubelet/app/options/options.go
> +	fs.StringArrayVar(&s.ManifestURLHeader, "manifest-url-header", s.ManifestURLHeader, "HTTP header to use when accessing the manifest URL, with the key separated from the value with a ':', as in 'key:
is this change backwards compatible?

2017-01-03 00:52 UTC, chentao1596 commented on cmd/kubelet/app/options/options.go
> +	fs.StringArrayVar(&s.ManifestURLHeader, "manifest-url-header", s.ManifestURLHeader, "HTTP header to use when accessing the manifest URL, with the key separated from the value with a ':', as in 'key:
Yes, it is.

2017-01-04 06:09 UTC, liggitt commented
can you split the generated files into their own commit so the actual changes are easier to review? also, https://github.com/kubernetes/kubernetes/pull/37557 will greatly reduce the generated file diff

2017-01-04 09:04 UTC, chentao1596 commented
@liggitt commit has been splited, all the auto-generated codes have been moved into the second commit, PTAL, thank you!

2017-01-04 16:54 UTC, liggitt commented on pkg/kubelet/kubelet.go
> +	if len(kubeCfg.ManifestURLHeader) > 0 {
just range over the slice, no length check is needed

2017-01-04 16:55 UTC, liggitt commented on pkg/kubelet/kubelet.go
> +			manifestURLHeader.Set(pieces[0], pieces[1])
should this be Add, not Set, in case you repeat a header?

2017-01-04 17:08 UTC, liggitt commented
@k8s-bot ok to test

2017-01-05 02:44 UTC, chentao1596 commented on pkg/kubelet/kubelet.go
> +	if len(kubeCfg.ManifestURLHeader) > 0 {
it is really no need, i have delete this check, thank you!

2017-01-05 02:44 UTC, chentao1596 commented on pkg/kubelet/kubelet.go
> +			manifestURLHeader.Set(pieces[0], pieces[1])
you are right, some headers with the same name may be appears, i changed it, thank you!

2017-01-05 15:19 UTC, liggitt approved these changes

2017-01-05 15:19 UTC, liggitt commented on cmd/kubelet/app/options/options.go
> +	fs.StringArrayVar(&s.ManifestURLHeader, "manifest-url-header", s.ManifestURLHeader, "HTTP header to use when accessing the manifest URL, with the key separated from the value with a ':', as in 'key:
Update the help text to indicate the arg can be specified multiple times to set multiple headers.

2017-01-05 15:20 UTC, liggitt commented
Need to update the flag help text, LGTM otherwise

2017-01-06 07:25 UTC, chentao1596 commented
@liggitt I have changed it, PTAL, thank you!

2017-01-14 01:19 UTC, liggitt commented
@k8s-bot unit test this

2017-01-31 15:47 UTC, liggitt commented
/lgtm /approve

2017-02-08 03:16 UTC, chentao1596 commented
@liggitt  I rebased this branch because of conflict, I am sorry for this trouble with you, PTAL, thank you!

2017-04-03 14:53 UTC, liggitt commented
@k8s-bot verify test this

2017-04-13 03:42 UTC, liggitt commented
@k8s-bot please test this

2017-04-24 02:25 UTC, liggitt commented
/lgtm

2017-08-04 04:29 UTC, liggitt commented
need to regenerate files, see output of verify test

2017-09-25 06:40 UTC, chentao1596 commented
@liggitt 
I am sorry for this delay.
Files has been generated, and my code has been rebased to the latest version, thank you!

2017-09-25 13:23 UTC, liggitt commented
/ok-to-test

LGTM, cc @kubernetes/sig-node-api-reviews @mtaufen for kubelet config change

2018-02-26 19:16 UTC, mtaufen commented
closing this, as equivalent work was completed in #54643 and #55254

2018-02-26 19:16 UTC, closed without merging