Remove redundant conditional statement
kubernetes/kubernetes pull request #38181
Opened 2016-12-06 08:30 UTC by tanshanshan

**What this PR does / why we need it**:

1. remove redundant conditional statement
2. replace  errors.New(fmt.Sprintf with fmt.Errorf 

Thanks.

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2016-12-06 09:08 UTC, resouer commented
@k8s-bot ok to test

2016-12-06 12:15 UTC, resouer requested changes

2016-12-06 12:15 UTC, resouer commented on pkg/kubectl/cmd/drain_test.go
> +				return nil, fmt.Errorf("%q: not found", name)
This looks cleaner, thanks

2016-12-06 12:15 UTC, resouer commented on pkg/kubectl/cmd/drain.go
> +	return o.deletePods(pods, getPodFn)
I'm sorry, but could you please leave this and below as it is? I'm afraid the modification you made here makes the logic non-readable.

2016-12-07 00:44 UTC, tanshanshan commented
cc @resouer , PTAL

2016-12-07 07:12 UTC, resouer commented
/lgtm

2016-12-07 07:12 UTC, resouer approved these changes

2016-12-07 07:19 UTC, tanshanshan commented
> Adding do-not-merge because the release note process has not been followed.
One of the following labels is required "release-note", "release-note-action-required", "release-note-experimental" or "release-note-none".
Please see: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes.

cc @resouer , Could you give  one of these labels?

2016-12-07 11:09 UTC, merged