Avoid exporting fluentd-gcp own logs
kubernetes/kubernetes pull request #38213
Opened 2016-12-06 21:01 UTC by Crassirostris

To prevent fluentd from exporting its own logs, redirect the output to a file. Ability to read fluentd logs remains, but because these logs will not be exported, we can increase the verbosity of these logs.

CC @piosz

2016-12-09 13:13 UTC, piosz requested changes

2016-12-09 13:13 UTC, piosz commented on cluster/addons/fluentd-gcp/fluentd-gcp-image/Makefile
> +TAG = 1.30
Let's do not bump the image right now but rather from time to time with a batch of changes.

2016-12-09 13:13 UTC, piosz commented on cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml
> +      - '/run.sh $FLUENTD_ARGS 2>&1 >>/var/log/fluentd.log'
Do we have any args here to pass?

2016-12-09 13:13 UTC, piosz commented on cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml
> +      - '/run.sh $FLUENTD_ARGS 2>&1 >>/var/log/fluentd.log'
Also could you please add a comment why fluentd logs are redirected to a file?

2016-12-09 13:22 UTC, Crassirostris commented on cluster/addons/fluentd-gcp/fluentd-gcp-image/Makefile
> +TAG = 1.30
ACK

2016-12-09 13:23 UTC, Crassirostris commented on cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml
> +      - '/run.sh $FLUENTD_ARGS 2>&1 >>/var/log/fluentd.log'
> Do we have any args here to pass?

We might have, e.g. config file or verbosity

> Also could you please add a comment why fluentd logs are redirected to a file?

ACK

2016-12-09 15:08 UTC, Crassirostris commented
@piosz PTAL

2016-12-09 18:58 UTC, piosz commented on cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml
> +      - '/run.sh $FLUENTD_ARGS 2>&1 >>/var/log/fluentd.log'
But no args are being passed here, so we can expect there is no args. Did I miss something? Once they will be introduced you can add them either by expanding the command or introducing them as args

2016-12-11 19:16 UTC, jbeda commented
I'm no longer reviewing this, but, just for curiosity's sake, why not have fluentd capture its own logs?

2016-12-11 23:38 UTC, Crassirostris commented
@jbeda I've mentioned this in the commentary, but the short version is this: consuming its own logs can create a nasty loops, where temporary backend outage or fluentd problem can create significant amount of trash being ingested, influencing meaningful logs.

2016-12-12 19:30 UTC, jbeda commented
@Crassirostris That makes sense.  Thanks!

2016-12-14 13:43 UTC, Crassirostris commented
Discussed offline and decided to keep the version bump

2016-12-14 13:44 UTC, piosz commented
LGTM

2016-12-14 13:45 UTC, piosz approved these changes

2016-12-14 15:09 UTC, merged