cinder attacher GetDeviceMountPath
kubernetes/kubernetes pull request #38374
Opened 2016-12-08 09:56 UTC by NickrenREN

add function to test GetDeviceMountPath func return value

2016-12-08 10:14 UTC, NickrenREN commented
@k8s-merge-robot   no one was assigned

2016-12-12 09:03 UTC, NickrenREN commented
@dims  @resouer  Could you please ask the bot to test ? thanks

2016-12-14 08:56 UTC, resouer commented
@k8s-bot ok to test

2016-12-14 09:56 UTC, NickrenREN commented
/cc @resouer  Checks passed. Could you help with the review?

2016-12-15 06:07 UTC, resouer commented
There're some nits, suggest you to follow the best practices of other tests in this file.

2016-12-15 06:07 UTC, resouer requested changes

2016-12-15 06:07 UTC, resouer commented on pkg/volume/cinder/attacher_test.go
> +	spec := createVolSpec("cinder-volume-id", false)
please change `"cinder-volume-id"` to a variable, and use this variable instead of hard coded string below

2016-12-15 06:07 UTC, resouer commented on pkg/volume/cinder/attacher_test.go
> +		t.Errorf("device mount path error: got %s", path)
a test should report both got and expected like ` expected %s, got %s"`

2016-12-15 06:07 UTC, resouer commented on pkg/volume/cinder/attacher_test.go
> +	host := volumetest.NewFakeVolumeHost("/var/lib/kubelet/", nil, nil)
the same, `"/var/lib/kubelet/"` to a variable

2016-12-15 06:07 UTC, resouer commented on pkg/volume/cinder/attacher_test.go
> +	if path != "/var/lib/kubelet/plugins/kubernetes.io/cinder/mounts/cinder-volume-id" {
so this `path` should be a string constructed by variables you defined above

2016-12-15 06:25 UTC, NickrenREN commented
@resouer   Thanks a lot. I have modified the codes as you suggest.

2016-12-19 01:18 UTC, NickrenREN commented
/cc @resouer Thanks.  Codes were modified as you suggest.

2016-12-19 11:43 UTC, NickrenREN commented
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/volume/cinder/attacher_test.go, line 61 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38374#-KYSrIu3Y_oOA7T2Tusa-r1-61:-KZLsqV7WKYTuANaaZBi:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e8788fb2d5167a3fb1cb50e8179194600f790e5e/pkg/volume/cinder/attacher_test.go#L61)):*
<details><summary><i>Previously, resouer (Harry Zhang) wrote…</i></summary><blockquote>

please change `"cinder-volume-id"` to a variable, and use this variable instead of hard coded string below
</blockquote></details>

Done.

---

*[pkg/volume/cinder/attacher_test.go, line 62 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38374#-KYSrIu3Y_oOA7T2Tusa-r1-62:-KZLssIAQ6mplEish7PR:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e8788fb2d5167a3fb1cb50e8179194600f790e5e/pkg/volume/cinder/attacher_test.go#L62)):*
<details><summary><i>Previously, resouer (Harry Zhang) wrote…</i></summary><blockquote>

the same, `"/var/lib/kubelet/"` to a variable
</blockquote></details>

Done.

---

*[pkg/volume/cinder/attacher_test.go, line 73 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38374#-KYSrIu3Y_oOA7T2Tusa-r1-73:-KZLssvopnozoJayXl5o:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e8788fb2d5167a3fb1cb50e8179194600f790e5e/pkg/volume/cinder/attacher_test.go#L73)):*
<details><summary><i>Previously, resouer (Harry Zhang) wrote…</i></summary><blockquote>

so this `path` should be a string constructed by variables you defined above
</blockquote></details>

Done.

---

*[pkg/volume/cinder/attacher_test.go, line 74 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38374#-KYSrIu3Y_oOA7T2Tusa-r1-74:-KZLstrh0a76t_Xa-oBa:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e8788fb2d5167a3fb1cb50e8179194600f790e5e/pkg/volume/cinder/attacher_test.go#L74)):*
<details><summary><i>Previously, resouer (Harry Zhang) wrote…</i></summary><blockquote>

a test should report both got and expected like ` expected %s, got %s"`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38374)*
<!-- Sent from Reviewable.io -->

2016-12-19 13:36 UTC, resouer commented on pkg/volume/cinder/attacher_test.go
> +		t.Errorf("device mount path error: expected /var/lib/kubelet/plugins/kubernetes.io/cinder/mounts/cinder-volume-id, got %s ", path)
replace this "/var/lib/kubelet/plugins/kubernetes.io/cinder/mounts/cinder-volume-id" to `expectedPath`

others looks good

2016-12-20 02:58 UTC, NickrenREN commented
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/volume/cinder/attacher_test.go, line 77 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38374#-KYSrIu3Y_oOA7T2Tusa-r2-77:-KZP9_Qeyc_4Wac5vBa8:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e1db1b1373a214e6b5e1660e2a8adeb344c0ef71/pkg/volume/cinder/attacher_test.go#L77)):*
<details><summary><i>Previously, resouer (Harry Zhang) wrote…</i></summary><blockquote>

replace this "/var/lib/kubelet/plugins/kubernetes.io/cinder/mounts/cinder-volume-id" to `expectedPath`

others looks good
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38374)*
<!-- Sent from Reviewable.io -->

2016-12-20 03:01 UTC, NickrenREN commented
@resouer  Done

2016-12-20 07:00 UTC, resouer approved these changes

2016-12-20 07:01 UTC, resouer commented
/lgtm

2016-12-20 10:51 UTC, NickrenREN commented
@resouer   Could you help add the  release-note-label? Thanks

2016-12-21 03:16 UTC, merged