scheduler: refactor main entry Run()
kubernetes/kubernetes pull request #38572
Opened 2016-12-11 04:58 UTC by hongchaodeng

The kube-scheduler/app.Run() is the main entry of scheduler program.
It's enormous.
This PR tries to clean it up.

2016-12-11 05:18 UTC, hongchaodeng commented
cc @timothysc @xiang90 
Can you help review this?

2016-12-11 07:34 UTC, hongchaodeng commented
@k8s-bot cri e2e test this

2016-12-11 16:28 UTC, hongchaodeng commented
@k8s-bot cri e2e test this

2016-12-11 18:35 UTC, hongchaodeng commented
@k8s-bot cri e2e test this.

On Sun, Dec 11, 2016 at 9:38 AM k8s-ci-robot <notifications@github.com>
wrote:

> Jenkins CRI GCE e2e *failed*
> <https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38572/pull-kubernetes-e2e-gce-cri/124/>
> for commit f3efab4
> <https://github.com/kubernetes/kubernetes/commit/f3efab49df8e6b4e9904f5bd811e07ac5bcb1f7e>.
> Full PR test history <http://pr-test.k8s.io/38572>.
>
> The magic incantation to run this job again is @k8s-bot cri e2e test this.
> Please help us cut down flakes by linking to an open flake issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+label:kind/flake+is:open>
> when you hit one in your PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/38572#issuecomment-266295457>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA4NNIAzNaQHK5uTtUxCv8pcc75mwDvaks5rHDUXgaJpZM4LJ1x6>
> .
>

2016-12-11 19:32 UTC, xiang90 commented on plugin/cmd/kube-scheduler/scheduler.go
> +		glog.Errorf("scheduler app failed to run: %v", err)
glog.Fatal here? or we can reach line 43.

2016-12-11 19:32 UTC, xiang90 commented on plugin/cmd/kube-scheduler/scheduler.go
> +	glog.Fatal("this statement shouldn't be reached")
we should panic on a unreachable line not fatal. usually fatal on unrecoverable external error, and panic on unrecoverable internal error.

2016-12-11 19:34 UTC, xiang90 commented on plugin/cmd/kube-scheduler/app/server.go
> +		return nil
probably should still panic internally.

2016-12-11 19:34 UTC, xiang90 commented on plugin/cmd/kube-scheduler/app/server.go
> +		return nil, fmt.Errorf("Invalid API configuration: %v", err)
invalid API configuration: %v

2016-12-11 19:35 UTC, xiang90 commented on plugin/cmd/kube-scheduler/app/server.go
> +		glog.Errorf("unable to build config from flags: %v", err)
we should log error in the caller?

2016-12-11 19:35 UTC, xiang90 commented
Minor issues. LGTM after fixing them.

2016-12-12 00:35 UTC, hongchaodeng commented
Fixed minor issues

2016-12-12 00:38 UTC, xiang90 commented
@hongchaodeng Awesome. Thanks!

2016-12-12 02:24 UTC, hongchaodeng commented
@k8s-bot unit test this #38594

2016-12-12 02:25 UTC, hongchaodeng commented
@k8s-bot cri e2e test this #38556

2016-12-12 06:36 UTC, hongchaodeng commented
@k8s-bot cri e2e test this

2016-12-12 16:44 UTC, hongchaodeng commented
@wojtek

Can you help review?

2016-12-12 19:38 UTC, timothysc commented on plugin/cmd/kube-scheduler/app/server.go
> +	if c, err := configz.New("componentconfig"); err == nil {
It's difficult to tell, but did you ensure this was the 1st place configz was used in the shuffling.  B4 it was the 1st line before refactoring.

2016-12-12 19:50 UTC, timothysc commented on plugin/cmd/kube-scheduler/scheduler.go
> +	panic("this statement shouldn't be reached")
could we change this panic to be "unreachable" to match the rest of the codebase?  It's the only outlier.

2016-12-12 19:53 UTC, timothysc commented on plugin/cmd/kube-scheduler/scheduler.go
> +	panic("this statement shouldn't be reached")
I don't think this logic makes much sense.. of course we can reach this point via a number of ways.  Shouldn't we just exit gracefully?

2016-12-12 19:55 UTC, timothysc commented on plugin/cmd/kube-scheduler/app/server.go
> +		return fmt.Errorf("unable to create kube client: %v", err)
Does it make sense to re-wrap the error or just return them?   I just debate the utility if we're refactoring.

2016-12-12 19:57 UTC, timothysc requested changes
Please answer the minor comments, otherwise lgtm

2016-12-12 21:17 UTC, hongchaodeng commented on plugin/cmd/kube-scheduler/app/server.go
> +		return fmt.Errorf("unable to create kube client: %v", err)
The previous code usually Fatalf() right there. Now We Fatalf() outside, and thus it's better to wrap them.

2016-12-12 21:21 UTC, hongchaodeng commented on plugin/cmd/kube-scheduler/scheduler.go
> +	panic("this statement shouldn't be reached")
I will remove this one.

> of course we can reach this point via a number of ways.

IIRC, no way to reach here? Can you clarify?

2016-12-12 21:25 UTC, hongchaodeng commented on plugin/cmd/kube-scheduler/app/server.go
> +	if c, err := configz.New("componentconfig"); err == nil {
Not sure why it needs to be put 1st line.
cc original author @mikedanese

2016-12-12 21:28 UTC, timothysc commented on plugin/cmd/kube-scheduler/app/server.go
> +		return fmt.Errorf("unable to create kube client: %v", err)
k.

2016-12-12 21:29 UTC, timothysc approved these changes

2016-12-12 22:16 UTC, timothysc commented
lgtm.

2016-12-13 03:42 UTC, merged