Interrupt/Terminate all child processes on timeout. Auto-gen stepName
kubernetes/kubernetes pull request #38576
Opened 2016-12-11 12:03 UTC by fejta

2016-12-11 21:42 UTC, fejta commented
@k8s-bot cri e2e test this

2016-12-12 19:49 UTC, krousey requested changes

2016-12-12 19:49 UTC, krousey commented on hack/e2e.go
> +			errs = appendError(errs, xmlWrap("get nodes", func() error {
To make this easier to read, could you make this anonymous function a named one defined elsewhere on its own and just call it here?

2016-12-12 20:02 UTC, fejta commented on hack/e2e.go
> +			errs = appendError(errs, xmlWrap("get nodes", func() error {
Done

2016-12-12 20:56 UTC, krousey approved these changes

2016-12-12 22:16 UTC, merged