remove unnecessary path.Join
kubernetes/kubernetes pull request #38677
Opened 2016-12-13 08:17 UTC by bruceauyeung

**What this PR does / why we need it**:

1. remove unnecessary path.Join call in `pki.go`
2. fix some typos and comment errors

Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>

2016-12-14 02:51 UTC, dims commented
@k8s-bot ok to test

2016-12-16 16:54 UTC, jbeda requested changes

2016-12-16 16:54 UTC, jbeda commented on cmd/kubeadm/app/master/pki.go
> +	pkiPath := kubeadmapi.GlobalEnvParams.HostPKIPath
This isn't equivalent.  `path.Join` will also clean the path.  If you want to remove the Join, you should replace it with `path.Clean`.  See: https://play.golang.org/p/jLUuVGBBSy

2016-12-17 18:45 UTC, jbeda commented
@k8s-bot cvm gke e2e test this
@k8s-bot cvm gke e2e test this
Flake #35913

2016-12-17 18:45 UTC, jbeda commented
/lgtm

2016-12-17 20:16 UTC, merged