Support systemd based pod qos in CRI dockershim
kubernetes/kubernetes pull request #38673
Opened 2016-12-13 07:18 UTC by resouer

This PR makes pod level QoS works for CRI dockershim for systemd based cgroups. And will also fix #36807
- [x] Add cgroupDriver to dockerService and use docker info api to set value for it
- [x] Add a NOTE that detection only works for docker 1.11+, see [CHANGE LOG](https://github.com/docker/docker/blob/master/CHANGELOG.md#1110-2016-04-13)
- [x] Generate cgroupParent in syntax expected by cgroupDriver
- [x] Set cgroupParent to hostConfig for both sandbox and user container
- [x] Check if kubelet conflicts with cgroup driver of docker

cc @derekwaynecarr

2016-12-14 20:35 UTC, derekwaynecarr requested changes
looks pretty good, just a few requests to update.

2016-12-14 20:35 UTC, derekwaynecarr commented on pkg/kubelet/dockershim/docker_service.go
> +func (ds *dockerService) GenereateExpectedCgroupParent(cgroupParent string) (string, error) {
typo: GenerateExpectedCgroupParent

2016-12-15 04:04 UTC, resouer commented
nits fixed, thanks for quick review

2016-12-15 18:21 UTC, derekwaynecarr requested changes
one more nit, then squash commits, and this will be good to go.

2016-12-15 18:21 UTC, derekwaynecarr commented on pkg/kubelet/dockershim/docker_service.go
> +		return nil, fmt.Errorf("Failed to execute Info() call to the Docker client: %v", err)
errors should start in lower form.

i think if we are unable to make the client call, we can default to cgroupfs.

2016-12-15 18:21 UTC, derekwaynecarr commented on pkg/kubelet/dockershim/docker_service.go
> +			return nil, fmt.Errorf("Misconfiguration: kubelet cgroup driver: %q is different from docker cgroup driver: %q", kubeCgroupDriver, cgroupDriver)
s/Misconfiguration/misconfiguration

2016-12-17 07:59 UTC, resouer commented
Fixed and updated :) @derekwaynecarr

2016-12-19 13:44 UTC, vishh commented
lgtm

2016-12-20 07:02 UTC, resouer commented
kindly ping @derekwaynecarr :)

2016-12-21 13:55 UTC, derekwaynecarr commented
/lgtm

2016-12-21 13:55 UTC, derekwaynecarr approved these changes

2016-12-21 15:01 UTC, resouer commented
@k8s-bot bazel test this

2016-12-21 16:01 UTC, merged

2016-12-23 06:48 UTC, resouer commented
ref #27204