AWS: Obsolete and remove the bash deployment
kubernetes/kubernetes pull request #38772
Opened 2016-12-14 18:45 UTC by zmerlynn

**What this PR does / why we need it**:  Obsolete and remove the bash deployment. It was deprecated in the documentation during the v1.5 timeframe, and there's been very little community maintenance.

**Release note**:

```release-note
The bash AWS deployment via kube-up.sh has been removed. See http://kubernetes.io/docs/getting-started-guides/aws/ for alternatives.
```

2016-12-14 19:23 UTC, zmerlynn commented
@k8s-bot cvm gke e2e test this

2016-12-14 19:42 UTC, zmerlynn commented
@k8s-bot cvm gke e2e test this

2016-12-16 10:41 UTC, kris-nova commented
This LGTM - especially if we are torching deprecated code!

2016-12-16 10:41 UTC, krisnova approved these changes

2016-12-16 10:41 UTC, kris-nova commented
/lgtm

2016-12-19 20:54 UTC, chrislovecnm approved these changes
Makes me happy

2016-12-19 20:54 UTC, chrislovecnm commented
LGTM

2016-12-19 20:55 UTC, zmerlynn commented
Self-applying after two LGTM comments.

2016-12-19 22:04 UTC, zmerlynn commented
@k8s-bot cvm gke e2e test this

2016-12-19 22:23 UTC, zmerlynn commented
@k8s-bot gci gke e2e test this

2016-12-19 22:29 UTC, chrislovecnm commented
@zmerlynn to @justinsb's point we probably need to bring this up on our sig and sig-cluster-lifecycle.  I really want this merged, but I also don't want to shoot ourselves in the foot either.

2016-12-19 22:30 UTC, chrislovecnm requested changes
We need to do a bit more due diligence on this.  It is deprecated, but not scheduled for removal.  I really want to do it, but I want to do it with a little more information.

2016-12-19 22:41 UTC, zmerlynn commented
@chrislovecnm: Ok, but I'd like to do it early in the stream so anyone running on `master` sees it. I had an alternate PR that used similar language but kept the code and forced you to set an env variable to continue at all. (But used "deprecated" instead of obsolete.) Would that be less contentious? I still want to turn down the test infrastructure or ignore it until someone steps forward to maintain it, because I think it's a waste to keep both up.

2016-12-20 06:14 UTC, chrislovecnm commented
@zmerlynn we also will need to update the website.  Currently it is listed as deprecated, not being removed in 1.6

2016-12-28 01:07 UTC, chrislovecnm commented
@justinsb what is your take on this?

2017-01-03 22:03 UTC, zmerlynn commented
@justinsb @chrislovecnm @kris-nova: I changed this PR to only announce the deprecation, with a scheduled-to-be-removed in v1.7. I'll send a separate doc PR shortly.

2017-01-24 21:08 UTC, zmerlynn commented
@chrislovecnm @justinsb: Ping. I'd like to get this warning in, at least. We can gut it in a separate PR.

2017-01-31 05:53 UTC, justinsb commented
I actually think we should still try to remove it in 1.6, but this LGTM.

2017-01-31 05:53 UTC, justinsb approved these changes
LGTM

2017-01-31 07:03 UTC, roberthbailey commented
/lgtm /approve

2017-01-31 07:11 UTC, chrislovecnm commented
This makes me happy.

2017-01-31 19:00 UTC, merged

2017-02-27 22:56 UTC, zmerlynn commented
c.f. #42196 and #42194 - after a brief discussion, we're looking at nuking the bash deployment completely. No one has stepped up to fix master, and I'm not sure any of us have time right now.