add err info to authorize in psp
kubernetes/kubernetes pull request #38805
Opened 2016-12-15 09:58 UTC by xilabao

It's unwise to ignore the err in my view.

2016-12-21 08:03 UTC, xilabao commented
@derekwaynecarr PTAL

2017-01-13 18:56 UTC, derekwaynecarr commented
@k8s-bot ok to test

2017-01-13 18:57 UTC, derekwaynecarr requested changes

2017-01-13 18:57 UTC, derekwaynecarr commented on plugin/pkg/admission/security/podsecuritypolicy/admission.go
> +		glog.V(4).Infof("authorized for policy error: %v", err)
can you bump this to V(5) ?

2017-01-16 01:04 UTC, xilabao commented on plugin/pkg/admission/security/podsecuritypolicy/admission.go
> +		glog.V(4).Infof("authorized for policy error: %v", err)
Done, PTAL

2017-01-19 01:31 UTC, xilabao commented
@derekwaynecarr PTAL

2017-01-23 07:58 UTC, xilabao commented
@derekwaynecarr PTAL

2017-02-25 13:20 UTC, xilabao commented
@derekwaynecarr PTAL

2017-02-27 02:18 UTC, xilabao commented
@derekwaynecarr

2017-02-27 02:21 UTC, liggitt commented on plugin/pkg/admission/security/podsecuritypolicy/admission.go
> +		glog.V(5).Infof("authorized for policy error: %v", err)
Why not include reason as well at this verbosity?

2017-02-27 02:28 UTC, xilabao commented on plugin/pkg/admission/security/podsecuritypolicy/admission.go
> +		glog.V(5).Infof("authorized for policy error: %v", err)
fixed.

2017-03-08 13:28 UTC, xilabao commented
@derekwaynecarr PTAL

2017-03-10 19:29 UTC, derekwaynecarr approved these changes

2017-03-10 19:29 UTC, derekwaynecarr commented
i think this is safe for 1.6 milestone as it helps debuggability of the platform.

2017-03-10 19:29 UTC, derekwaynecarr commented
/lgtm
/approve

2017-03-10 21:32 UTC, merged