Disable 1.4 ScheduledJob tests when master >= 1.5
kubernetes/kubernetes pull request #38828
Opened 2016-12-15 19:00 UTC by krousey

**What this PR does / why we need it**: To skip expected failures in upgrade testing.

**Which issue this PR fixes**: fixes #38232

**Special notes for your reviewer**: This is a direct commit. Not a cherry-pick.

2016-12-15 19:01 UTC, krousey commented
@jessfraz This doesn't belong in the master and 1.5 as it does not apply. So this isn't exactly a cherry-pick. Please let me know if there is a better way to go about this than a direct PR to the 1.4 release.

2016-12-15 20:13 UTC, soltysh requested changes

2016-12-15 20:13 UTC, soltysh commented on test/e2e/scheduledjob.go
> +
Why not using `framework.SkipUnlessServerVersionGTE`, like [here](https://github.com/kubernetes/kubernetes/blob/29d10a817ae6eadfd271447a2ab6bbe50856d458/test/e2e/kubectl.go#L262) ?

2016-12-15 22:22 UTC, soltysh commented on test/e2e/scheduledjob.go
> +
But that's exactly what it does, it checks if the server version is at least X. Though I agree, the naming is unfortunate. Compare [these lines](https://github.com/kubernetes/kubernetes/blob/29d10a817ae6eadfd271447a2ab6bbe50856d458/test/e2e/framework/util.go#L410-L418) with your code.

2016-12-15 22:33 UTC, soltysh commented on test/e2e/scheduledjob.go
> +
Or that 😉

2016-12-15 22:33 UTC, soltysh approved these changes

2016-12-15 22:33 UTC, soltysh commented
LGTM

2016-12-15 22:33 UTC, soltysh commented
Thank you!

2016-12-16 08:02 UTC, krousey commented
@k8s-bot unit test this

2016-12-16 15:50 UTC, krousey commented
@k8s-bot unit test this

2016-12-16 17:26 UTC, merged