Clarify test validate ok
kubernetes/kubernetes pull request #38837
Opened 2016-12-15 21:55 UTC by jayunit100

Minor cleanup for these tests so that they point you directly to the bug if swagger specs arent up to date..

2016-12-15 21:57 UTC, jayunit100 commented
one of many very minor PR's ill issue to make api unit testing less painful  :)

2017-01-04 22:38 UTC, jayunit100 commented
@k8s-bot unit test this please

2017-01-09 21:16 UTC, mbohlool requested changes

2017-01-09 21:16 UTC, mbohlool commented on pkg/api/validation/schema_test.go
> +	_, err := loadSwaggerSchemaForTest()
test are failing and they are real failing. "loadSwaggerSchemaForTest" is not defined.

2017-01-16 20:24 UTC, closed without merging