Fix variable shadowing in exponential backoff when deleting volumes
kubernetes/kubernetes pull request #38855
Opened 2016-12-16 04:10 UTC by gnufied

While https://github.com/kubernetes/kubernetes/pull/38339 implemented exponential backoff on
volume deletion, that PR suffers from a minor bug when error thrown on volume deletion is anything other than `VolumeInUse` errors - in which case exponential backoff will not work.

This PR fixes that. This PR also makes unit tests more deterministic because exponential backoff changed the way operations are permitted.

CC @jsafrane @childsb @wongma7

2016-12-16 17:27 UTC, wongma7 commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +			if _, err2 := ctrl.updateVolumePhaseWithEvent(volume, v1.VolumeFailed, v1.EventTypeWarning, "VolumeFailedDelete", err.Error()); err2 != nil {
I think you can just add a colon, no need to create err2 https://play.golang.org/p/tgrIrB8hmZ

2016-12-16 20:41 UTC, childsb commented
@k8s-bot ok to test

2016-12-16 21:47 UTC, rootfs commented on pkg/util/goroutinemap/goroutinemap.go
> +	// Wait blocks until all operations is empty. This is typically
-> are empty

2016-12-16 22:54 UTC, saad-ali requested changes

2016-12-16 22:54 UTC, saad-ali commented on pkg/util/goroutinemap/goroutinemap.go
> +	WaitForCompletion()
Please add unit tests to `goroutinemap_test.go`

2016-12-19 14:18 UTC, gnufied commented on pkg/util/goroutinemap/goroutinemap.go
> +	WaitForCompletion()
Added test.

2016-12-19 14:18 UTC, gnufied commented on pkg/util/goroutinemap/goroutinemap.go
> +	// Wait blocks until all operations is empty. This is typically
fixed

2016-12-19 19:51 UTC, gnufied commented
@saad-ali @jsafrane fixed. PTAL.

2016-12-21 00:49 UTC, saad-ali approved these changes
LGTM.

One minor nit, feel free to self LGTM after that is fixed.

2016-12-21 00:49 UTC, saad-ali commented on pkg/util/goroutinemap/goroutinemap_test.go
> +func generateOpWithError(done <-chan interface{}) func() error {
super nit: how about `generateErrorFunc` to align with the existing naming?

2016-12-21 02:32 UTC, gnufied commented on pkg/util/goroutinemap/goroutinemap_test.go
> +func generateOpWithError(done <-chan interface{}) func() error {
ack, fixed.

2016-12-21 03:07 UTC, saad-ali commented
/lgtm

2016-12-21 04:33 UTC, merged