Made multi-scheduler graduated to Beta and then v1.
kubernetes/kubernetes pull request #38871
Opened 2016-12-16 13:31 UTC by k82cn

fixes #25318

2016-12-18 01:03 UTC, davidopp commented
Please remove the code that handles the annotation in this PR.

2016-12-19 11:52 UTC, k82cn commented
@k8s-bot cvm gke e2e test this

2017-01-06 03:35 UTC, k82cn commented
I'm working on the rebase; but it `update-all.sh` will also update docs unexpected, traced at https://github.com/kubernetes/kubernetes/issues/39505 .

2017-01-07 01:48 UTC, k82cn commented
cc @davidopp , if any more comments, please let me know :).

2017-01-16 06:02 UTC, davidopp commented
Please remove all the code that handles the annotation for scheduler name, e.g
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L496
should be reading from the field rather than the annotation.

Also make sure the tests are setting scheduler name using the new field you introduced, and not the annotation. (I don't understand how the tests passed without you changing factory.go)

2017-01-16 06:26 UTC, k82cn commented
@davidopp , the annotation was removed as you mentioned, e.g. https://github.com/kubernetes/kubernetes/pull/38871/files#diff-77bdee21550bc698bfa654de11c64324L496 .

2017-01-16 06:26 UTC, k82cn commented
In the PR, the scheduler name was set to default if empty.

2017-01-16 06:29 UTC, davidopp commented
Ah OK, sorry I missed that! I will review the PR in the next couple of days.

2017-01-17 01:47 UTC, timothysc approved these changes
Only needs release note from the looks of it.

2017-01-17 02:12 UTC, timothysc requested changes
$ grep -r "scheduler[.]alpha" * | grep name 

still shows a fair number of results, in fact, I need to do some other cleanup work now too.

2017-01-17 04:53 UTC, k82cn commented
@timothysc , thanks for your comments; the PR was updated accordingly :).

2017-01-17 17:53 UTC, timothysc commented
@k82cn please squash to 2 commits.. 1 - generated code, 2 - everything else.

2017-01-18 08:30 UTC, k82cn commented
@k8s-bot bazel test this

2017-01-18 13:33 UTC, k82cn commented
@timothysc, the code was updated accordingly; PTAL: add a default test for default scheduler name; removed the UT case that with empty scheduler name.

2017-01-18 15:12 UTC, timothysc approved these changes

2017-01-18 15:15 UTC, timothysc commented
Thanks for the cleanup. 

lgtm, but I'm slightly concerned that we don't have a multi-scheduler e2e.  Meaning we could be flying blind from a support perspective. 

I'll let @davidopp make final comments b/c of my comment.  I would propose that we create a multi-scheduler set of e2es in a separate PR.

2017-01-18 15:39 UTC, k82cn commented
I think the integration test for multiple-scheduler at `scheduler_test.go:TestMultiScheduler` is ok; or do you want to also confirm the feature interaction with scheduler's priority/predicates?

2017-01-18 17:30 UTC, timothysc commented
@k82cn needs release note..

2017-01-18 18:55 UTC, timothysc commented
> I think the integration test for multiple-scheduler at scheduler_test.go:TestMultiScheduler is ok 

There are a bunch of edges around multiple schedulers that have not been vetted. 
 e.g. b2b binding to a host that runs out of resources... 

As of today we have a basic level stuff, I'm just saying we should open another issue around e2e tests to properly vet mutli-scheduling.  But there is no reason atm to block this.  

/lgtm

2017-01-18 23:58 UTC, k82cn commented
> There are a bunch of edges around multiple schedulers that have not been vetted.
e.g. b2b binding to a host that runs out of resources...

Wow, agree with the example case :). e2e cases seems necessary.

> @ k82cn needs release note..

I'll rebase it today.

2017-01-19 04:37 UTC, k82cn commented
@timothysc , the code was re-based. PTAL :).

2017-01-19 05:12 UTC, davidopp commented
We decided to defer e2e tests when this feature went to alpha because we thought we were going to do a "next step" for this feature (an admission controller that would take a high-level policy configuration, and based on that, add the scheduler name annotations to the incoming pods), and I thought the integration test was sufficient until then. Well, we ended up not doing the next step, and I who knows if/when it will ever be done, so I think now is a very good time to do one or more e2e tests. @k82cn do you think you can do it in a follow-up PR?

As for back-to-back bindings from different schedulers, which @timothysc mentioned: the kubelet does admission control that checks for sufficient resources etc., so we are relying on that to ensure the node doesn't become overcomitted with respect to request. Unfortunately non-node-local properties aren't checked by the kubelet, but I think the only one that matters right now is non-node TopologyKey for pod anti-affinity (e.g. "don't put this pod in the same zone as any pods that match label selector X"), and we said we were probably going to disable that when it goes to beta in 1.6...

2017-01-19 05:44 UTC, k82cn commented
@davidopp , sure; I'd like to add more e2e for this feature.
The follow-up PR will trace at #40125; please feel free to assign to me :).

2017-01-19 15:58 UTC, merged

2017-02-20 23:09 UTC, smarterclayton commented on pkg/api/v1/types.go
> +	SchedulerName string `json:"schedulername,omitempty" protobuf:"bytes,19,opt,name=schedulername"`
This is wrong - this should have been `schedulerName`

Please ensure this is fixed pre 1.6.0 - this is a release blocker.

2017-02-20 23:09 UTC, smarterclayton commented
This has an incorrect JSON serialization for `schedulername` - must be `schedulerName`.  Please fix that ASAP, it may not go out in 1.6.

2017-02-20 23:58 UTC, k82cn commented on pkg/api/v1/types.go
> +	SchedulerName string `json:"schedulername,omitempty" protobuf:"bytes,19,opt,name=schedulername"`
sure, I'll create a PR today :).