Adapt loadbalancer deleting/updating when using cloudprovider openstack in openstack/liberty
kubernetes/kubernetes pull request #38959
Opened 2016-12-19 12:42 UTC by daconstenla

**What this PR does / why we need it**:
Make an extra verification on the returned listeners and pools because gophercloud query doesn't filter the results by loadbalancerID / listenerID respectively when using **openstack/librerty**.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
#33759 
**Special notes for your reviewer**:
#33759 it's supposed to have a pull request which fixes this problem but in the release  1.5 loadbalancers doesn't use that patched code.
**Release note**:

NONE
```release-note
```

2016-12-19 14:06 UTC, daconstenla commented
_cla/linuxfoundation — commit missing GitHub user_
Corrected, can the checks be re-launched or should I made a new commit to trigger it?

2016-12-20 23:31 UTC, anguslees commented
@k8s-bot ok to test

Wat? I swear this is the 3rd time I've reviewed a fix for this issue :/
@daconstenla: Can you make this PR look the same as https://github.com/kubernetes/kubernetes/commit/95eef6e4220923e4be41e0ebd576a4429c4bc54d so at least we only have one variant of this bit of code floating around.

Now off to do some git archaeology to see where this is/isn't merged...

2016-12-20 23:57 UTC, anguslees requested changes

2016-12-20 23:57 UTC, anguslees commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +			if len(listener.Loadbalancers) > 0 && listener.Loadbalancers[0].ID == loadbalancer.ID {
This whole surrounding code should be replaced with a call to `getListenersByLoadBalancerID`

2016-12-20 23:57 UTC, anguslees commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +			for _, listenerID := range listenerIDs {
Replace surrounding code by `getPoolByListenerID`

2016-12-21 13:00 UTC, kiall commented
@anguslees yea, it looks like I missed a case in my last PR for this. No clue how we haven't hit this one :(

2016-12-21 17:42 UTC, kiall commented
Can we apply the 1.5 milestone and cherrypick-candidate label? Over eager deletions is defiantly worth pushing into the 1.5 releases!

2016-12-23 16:44 UTC, daconstenla commented
@anguslees I have made the changes you suggested (and some more), now I'm waiting confirmation from my organization to sign the cncf agreement.

2016-12-30 16:31 UTC, xsgordon commented
@idvoretskyi can you please add the sig/openstack label?

2017-01-16 13:57 UTC, daconstenla commented
Sorry for the delay, we have already signed the _**"cla/linuxfoundation"**_ as company after reviewing the bases, now the pull request can pass again the tests :+1:

2017-02-07 09:18 UTC, daconstenla commented
Hi @anguslees, what happend with this PR? :)

/approve

2017-02-13 23:26 UTC, anguslees approved these changes
/approve

2017-02-13 23:29 UTC, anguslees commented
@idvoretskyi As has been mentioned before, this PR should be cherrypicked onto 1.5.  No idea if that's a process you kick off with github label magic, or ...

2017-02-14 22:56 UTC, idvoretskyi commented
cc @saad-ali on comment above.

2017-03-03 17:31 UTC, daconstenla commented
I have made a _rebase_ and now tests fails, I'm not sure what's the problem, can someone help me?

2017-03-20 19:08 UTC, xsgordon commented
@k8s-bot test this

2017-03-21 01:58 UTC, FengyunPan commented
This PR may addresses my issue #43055

2017-03-21 02:08 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +	listenerList, err := getListenersByLoadBalancerID(lbaas.network, loadbalancer.ID)
I think this change should also update UpdateLoadBalancer(), like #43056.

2017-03-21 02:11 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +		pool, err := getPoolByListenerID(lbaas.network, loadbalancer.ID, listener.ID)
same here.

2017-03-21 02:12 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +		membersList, err := getMembersByPoolID(lbaas.network, pool)
same here, like #43056.

2017-03-29 13:30 UTC, daconstenla commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +	listenerList, err := getListenersByLoadBalancerID(lbaas.network, loadbalancer.ID)
Thank you for your comment @FengyunPan, I'll change UpdateLoadBalancer as soon as posible 👍

2017-03-30 08:13 UTC, daconstenla commented
Some _*\lgtm*_ around? @grahamhayes @anguslees ? 

Thanks

2017-04-24 00:30 UTC, anguslees commented
/lgtm

(Sorry this PR has dragged out so long, thanks for your persistence!)

2017-04-24 00:32 UTC, anguslees commented
/release-note-none

2017-04-24 02:02 UTC, anguslees commented
@k8s-bot cvm gce e2e test this

2017-04-28 04:09 UTC, FengyunPan commented
@daconstenla Maybe you should combine 4 commits into 1 commit? I find that the first commit is wrong and there are two commits is empty.

2017-05-05 05:37 UTC, FengyunPan commented
@erictune  @grahamhayes @anguslees @daconstenla
Hi everyone，the pr addresses a big bug and has been submited 5 month ago, but it has not been merged. I think the reason is there are two invaild commit in pr, and the contributor did not remove them.
I can not wait to fix the big bug anymore. Can you merge my pr (#43056)?  #43056

2017-05-05 14:13 UTC, dims commented
@k8s-bot ok to test

2017-05-06 14:50 UTC, daconstenla commented
@k8s-bot bazel test this

2017-05-06 14:52 UTC, daconstenla commented
@k8s-bot bazel test this

2017-05-07 19:54 UTC, daconstenla commented
Can somebody mark as /lgtm? @erictune @grahamhayes @anguslees 
By the way, it seems like a test is failing, I had to launch 3 times bazel test before ends with a valid result.

2017-05-11 10:30 UTC, daconstenla commented
Can somebody please, attend this pull-request and mark it as lgtm?

2017-05-16 16:56 UTC, anguslees commented
/lgtm

2017-05-21 10:22 UTC, merged