Set qos field
kubernetes/kubernetes pull request #38989
Opened 2016-12-19 21:13 UTC by sjenning

This PR continues the work for https://github.com/kubernetes/kubernetes/pull/37968

It converts all local usage of the `qos` package class types to the new API level types (first commit) and sets the pod status QOSClass field in the at pod creation time on the API server in `PrepareForCreate` and in the kubelet in the pod status update path (second commit).  This way the pod QOS class is set even if the pod isn't scheduled yet.

Fixes #33255

@ConnorDoyle @derekwaynecarr @vishh

2017-01-10 16:23 UTC, derekwaynecarr reviewed
one nit, then i will tag.

2017-01-10 16:23 UTC, derekwaynecarr commented on pkg/kubelet/kubelet_pods.go
> +	apiPodStatus.QOSClass = qos.GetPodQOS(pod)
just add a note that this is needed to ensure upgrade from 1.5 to 1.6 to set the field on upgrade.

2017-01-10 16:58 UTC, sjenning commented
@derekwaynecarr @vishh rebased and added comment about why we also set the field in the kubelet

2017-01-10 20:23 UTC, derekwaynecarr requested changes
thought a little bit more, and think we should have a unit test and e2e test before merging.

2017-01-10 20:23 UTC, derekwaynecarr commented on pkg/registry/core/pod/strategy.go
> +		QOSClass: qos.InternalGetPodQOS(pod),
i think we should have a test case for this in strategy_test.go

it also would be good if we had a e2e that verified qos class is set as well for each qos tier.  maybe in e2e pods.go?

2017-01-10 20:24 UTC, vishh commented on pkg/registry/core/pod/strategy.go
> +		QOSClass: qos.InternalGetPodQOS(pod),
+1

2017-01-10 20:25 UTC, vishh approved these changes
LGTM for me. Derek's comments have to be addressed though.

2017-01-10 20:54 UTC, sjenning commented on pkg/registry/core/pod/strategy.go
> +		QOSClass: qos.InternalGetPodQOS(pod),
I'm pretty sure the unit test would basically be the same as `TestGetPodQOS()` in `qos_test.go`.  I can work on an e2e test.

2017-01-10 22:45 UTC, derekwaynecarr approved these changes

2017-01-10 22:46 UTC, derekwaynecarr commented
assuming bazel and all are happy, this is LGTM

2017-01-11 00:30 UTC, rmmh commented
@k8s-bot bazel test this

2017-01-11 02:14 UTC, sjenning commented
@k8s-bot kops aws e2e test this

2017-01-11 06:24 UTC, merged