[Proposal][WIP] Core Metrics Pipeline API
kubernetes/kubernetes pull request #39051
Opened 2016-12-21 00:03 UTC by dashpole

Included is a proposal for only collecting what we use in the kubelet, and (eventually) leaving metrics collection for users to third parties.

My analysis of what metrics we use and dont use in the kubelet can be [https://docs.google.com/document/d/1Zt1lkb-U7MxI2bg9X2T77MWzhP1FcgppxoplaHr9QVY/edit?usp=sharing](found here).

Open questions are:
Do any other k8s components (outside the kubelet) use the summary api?  In that case we would want to include whatever they use in the core metrics API.

Should this API be versioned, or unversioned?  It would have to be versioned if another component relies on the summary API, which I am not sure of.

Are there any metrics that we will need in the Q1 timeframe that should be included?

Are there any sections missing from this proposal?

cc: @kubernetes/sig-node

2016-12-27 23:59 UTC, thockin commented
I don't think I have enough context to review this properly.  Dawn, can you assign?

2017-01-04 18:58 UTC, piosz commented
@dashpole I haven't read the whole proposal yet. In the meantime did you have a chance to read [the new monitoring architecture](https://github.com/kubernetes/kubernetes/blob/master/docs/design/monitoring_architecture.md)?

cc @fgrzadkowski

2017-01-04 19:09 UTC, dashpole commented
@piosz I will take a look.  Thus far, there appears to be a lot of overlap between the two proposals.

2017-01-04 19:25 UTC, dashpole commented
@piosz For the most part, these two proposals look pretty consistent with each other.  This proposal deals with how to collect the core metrics, and which metrics are required, and the other proposal deals with how to create the full pipeline given core metrics.

2017-01-04 19:26 UTC, luxas commented
Then I guess we can merge them together?

2017-01-04 19:49 UTC, DirectXMan12 requested changes
this needs to talk explicitly about how it fits with the monitoring vision (as discussed above), plus some nits and naming questions.

2017-01-04 19:49 UTC, DirectXMan12 commented on docs/proposals/core-metrics-pipeline.md
> + - Horizontal-Pod-AutoScalar (HPA)
Horizontal Pod Auto**scaler**

2017-01-04 19:49 UTC, DirectXMan12 commented on docs/proposals/core-metrics-pipeline.md
> +Methods for pushing these metrics to various kubernetes components will not be covered.  This proposal does not cover any future "metrics-server", but these metrics could easily be pushed to whatever
This *really*  needs to discuss it's place in the monitoring vision in more concrete terms -- if you're referencing the monitoring vision, you could just say here "this proposal does not cover exposing the metrics to components -- that is discussed in more details by the metrics-server"

2017-01-04 19:49 UTC, DirectXMan12 commented on docs/proposals/core-metrics-pipeline.md
> +
nit: might want to use fenced code blocks here (like

    ```go
    type FooBar
    ```

so it comes out with syntax highlighting, etc

2017-01-04 19:49 UTC, DirectXMan12 commented on docs/proposals/core-metrics-pipeline.md
> +      Time metav1.Time `json:"time"`
this should probably be `Timestamp` (and elsewhere in this proposal) so it's not confused with CPU time (plus, we use `Timestamp` elsewhere IIRC)

2017-01-04 19:50 UTC, DirectXMan12 commented
> Then I guess we can merge them together?

I think this should just be trimmed down to not talk about the third-party stuff as much (just reference the monitoring vision).  I think an overhaul of the kubelet part deserves to be it's own sub-proposal, it just needs to be written in terms of the monitoring vision.

2017-01-04 19:57 UTC, DirectXMan12 commented
P.S. this probably needs to be moved to the kubernetes/community repo.

2017-01-04 22:59 UTC, dashpole commented
@DirectXMan12 Ill trim down the vague references to third party integration.  At the time of writing, I was not aware of the other doc which has a much more fully fleshed out story around monitoring architecture.

2017-01-04 23:27 UTC, dashpole commented on docs/proposals/core-metrics-pipeline.md
> +Methods for pushing these metrics to various kubernetes components will not be covered.  This proposal does not cover any future "metrics-server", but these metrics could easily be pushed to whatever
done.

2017-01-04 23:29 UTC, dashpole commented on docs/proposals/core-metrics-pipeline.md
> +      Time metav1.Time `json:"time"`
done

2017-01-05 01:03 UTC, dashpole commented
@DirectXMan12 Do you think the proposal has the appropriate scope now?  Can you, or someone else who is familiar with the future plans of HPA confirm that the given set of metrics meet the HPA's requirements?

2017-01-05 06:41 UTC, luxas commented
@dashpole In any case, all proposals should be directed to kubernetes/community. 
Please reopen this PR there

2017-01-05 15:15 UTC, DirectXMan12 commented on docs/proposals/core-metrics-pipeline.md
> +This Core Metrics API be versioned to account for version-skew between kubernetes components.
> This Core Metrics API **will** be versioned

2017-01-05 15:17 UTC, DirectXMan12 commented
scope looks better.  please tag me once you open the new PR

2017-01-05 15:59 UTC, luxas commented
New PR up, great!

2017-01-05 15:59 UTC, closed without merging