fix --no-header help description
kubernetes/kubernetes pull request #39053
Opened 2016-12-21 00:51 UTC by tanshanshan

**What this PR does / why we need it**:

the current description is
>  --no-headers=false: When using the default or custom-column output format, don't print headers.

but ,

>  kubectl get po

 the header has been printing , so  the default condition is printing headers.

> kubectl get po --no-headers=true

 the header  has been not printing

> kubectl get po --no-headers=false

 the header  has been printing

So , I  fixed the help description

Thanks.

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2016-12-21 19:23 UTC, janetkuo commented
@k8s-bot ok to test

2016-12-21 19:41 UTC, janetkuo commented
@tanshanshan thanks for the PR. However, the flag description isn't wrong. It describes the flag `--no-headers`, not `--no-headers=false` (here, `false` is the default value). 

If you feel the description is confusing, I suggest you update it to mention what the default behavior is.

2016-12-21 19:42 UTC, janetkuo requested changes

2016-12-21 19:42 UTC, janetkuo commented on pkg/kubectl/cmd/util/printing.go
> +	cmd.Flags().Bool("no-headers", false, "When using the default or custom-column output format, print headers.")
@tanshanshan thanks for the PR. However, the flag description isn't wrong. It describes the flag `--no-headers`, not `--no-headers=false` (here, `false` is the default value). 

If you feel the description is confusing, I suggest you update it to mention what the default behavior is.

2016-12-28 03:46 UTC, tanshanshan commented
hi, @janetkuo  , PTAL

2016-12-29 00:40 UTC, janetkuo approved these changes

2016-12-29 00:41 UTC, janetkuo commented
/lgtm

2016-12-29 03:07 UTC, merged