WIP api: well-known-labels redo the master / node labels
kubernetes/kubernetes pull request #39112
Opened 2016-12-22 00:02 UTC by philips

The setup of the kubernetes.io/role labels makes it impossible to have a
node be both "master" and "normal" at the same time. If possible I want
to enable people to use Kubernetes in single node configurations for
development and match production as close as possible.

For example if these labels are used to make decisions say using
nodeSelectors then this is troublesome in single node cases.

Alternatives:

- Create kubernetes.io/role=master+node for these combined role
- Ask users to select role=master OR role=node

Both of these force the complexity on the user and creates problems if
we come up with some future role like perhaps role=federation or
something.

Thanks to @jbeda for discussing this with me.

2016-12-22 00:03 UTC, philips commented
cc @smarterclayton @justinsb @jbeda @caesarxuchao @bgrant0607 @davidopp

2016-12-22 00:06 UTC, philips commented
xref https://github.com/kubernetes/kubernetes/pull/35975

2016-12-22 02:41 UTC, justinsb commented
Link to the discussion with @jbeda?

Single node is not a great idea though IMO: the master is a security boundary, not just a performance boundary.

In any case, I think what you are saying is true, but I think the solution is to label it as a master, and not apply the master taint.  I probably made a mistake here, but let's make breaking API changes only when we need to.

2016-12-22 04:01 UTC, philips commented
On Wed, Dec 21, 2016 at 6:41 PM Justin Santa Barbara <
notifications@github.com> wrote:

> Link to the discussion with @jbeda <https://github.com/jbeda>?
>
Sorry, offline conversation.

> Single node is not a great idea though IMO: the master is a security
> boundary, not just a performance boundary.
>
Umm, it isn't a _great_ idea but minikube is existence proof that it is a
compelling use case.

> In any case, I think what you are saying is true, but I think the solution
> is to label it as a master, and not apply the master taint. I probably made
> a mistake here, but let's make breaking API changes only when we need to.
>
How is this a breaking API change? kubeadm is alpha and is the only user
currently, right?

Honestly, I would rather break it 1 month after merging and get it right
than have this confusing "nodes can only have one role at a time" semantic
forever.

2016-12-22 05:04 UTC, justinsb commented
So I don't particularly understand the problem you're trying to solve.  In particular, does my proposal work for your use case - and if not, can you explain further?

It's a breaking API change because we've released it.  kubeadm uses it, kops uses it, and we have no idea if others use it also.

I can see two approaches though:

Option A:

* in 1.6 we can suggest that nodes are labeled with both the 1.5 labels and the 1.6 labels, and we can recognize both forms, just as we recognize the kubeadm form and the unprefixed form.  kops can add both labels pretty easily, and I'm sure other tools can do the same.
* we can start targeting manifests to the 1.6 labels, if we know they are being used with nodes using the 1.6 labels (i.e. if you're creating the apiserver manifest and labeling the nodes, you can target the new labels)
* in 1.7/1.8 we can probably switch generic manifests we provide to use the 1.6 labels

Option B:

* You could also promote role to a field on the Node, `role: []NodeRole`
* I believe we have api machinery to convert from labels <-> fields which we've used in the past for similar situations
* Not sure how this interacts with the nodeSelector though here?

Given the options, I think a feature proposal is needed.

I'm also pretty sure we had this discussion previously, though I can't find it now :-(

Finally, I'm not sure if there's something coming in taints that actually covers this - some sort of magic taint affinity logic that we should be using instead!

2016-12-22 05:47 UTC, philips commented
On Wed, Dec 21, 2016 at 9:04 PM Justin Santa Barbara <
notifications@github.com> wrote:

> So I don't particularly understand the problem you're trying to solve. In
> particular, does my proposal work for your use case - and if not, can you
> explain further?
>
If we label something with a kubernetes.io brand people will start using it
in creative ways via NodeSelectors or when doing ad-hoc stuff on kubectl.

The use case is bootkube has a "master=true" label to land control plane
pods on master nodes. And also a number of people want to use single-node
clusters. For example, I would like to get minikube using self-hosted to
make it a better k8s dev environment next year.

> It's a breaking API change because we've released it. kubeadm uses it,
> kops uses it, and we have no idea if others use it also.
>
Agreed, it is a breaking change. But, it was merged less than 60 days ago
in a major release less than 14 days ago.

> I can see two approaches though:
>
> Option A:
>
I agree with this plan to not fix the breaking change issue; thank you for
putting it together. I will update the PR to add new labels and we can
transition.

>
>    - I'm also pretty sure we had this discussion previously, though I
>    can't find it now :-(
>
> Where is the original proposal? Happy to provide something else

Thanks Justin!

2016-12-28 04:43 UTC, justinsb requested changes
Also need to update kubectl logic (in pkg/kubectl/resource_printer.go).  A PR to kops (and I suspect kubeadm) also would be welcomed :-)

2016-12-28 04:43 UTC, justinsb commented on pkg/apis/meta/v1/well_known_labels.go
> +	// NodeLabelNodeRoleMaster is set to the value "true" indicating a master node.
Comment `NodeLabelNodeRoleMaster` doesn't match code `LabelNodeRoleMaster`

2016-12-28 04:43 UTC, justinsb commented on pkg/apis/meta/v1/well_known_labels.go
> +	// NodeLabelNodeRoleMaster is set to the value "true" indicating a master node.
Perhaps say what happens if the value is not `true`

2016-12-28 04:43 UTC, justinsb commented on pkg/apis/meta/v1/well_known_labels.go
> +// worked but enables Nodes to take on multiple roles. For example, a
I think you mean `did not allow Nodes to take on multiple roles` or similar

2017-01-10 00:15 UTC, bgrant0607 commented
cc @roberthbailey

2017-01-17 12:14 UTC, luxas commented
@philips Ping. Are we going to try to get this in for v1.6?
I think it would be good to get rid of the `kubeadm.alpha.kubernetes.io/role=master` label from kubeadm as soon as possible, WDYT?

2017-01-17 20:14 UTC, philips commented
cc @Quentin-M

2017-01-17 20:15 UTC, philips commented
@luxas yes, I want to do it in v1.6. I was on vacation for the last two weeks so I hope to finish this off today/tomorrow and get it merged soonish.

2017-01-20 04:08 UTC, philips commented
@luxas @justinsb addressed feedback and taught kubectl how to print out the new labels.

2017-01-20 04:28 UTC, philips commented
cc @kubernetes/sig-cli-misc for the kubectl change

2017-01-20 23:08 UTC, calebamiles commented
@k8s-bot cvm gke e2e test this

2017-01-22 18:55 UTC, philips commented
@roberthbailey @justinsb Can someone please put the v1.6 label on this?

2017-01-22 19:05 UTC, luxas commented
I'm not sure it matters; but here you go ;)

Maybe we could get the change for kubeadm as well?

2017-01-23 03:21 UTC, philips commented
@luxas I will do it in a separate PR.

2017-01-23 21:37 UTC, philips commented
@k8s-bot smoke e2e test this

2017-01-23 21:38 UTC, philips commented
@k8s-bot cvm gke e2e test this

2017-01-23 21:38 UTC, philips commented
@k8s-bot gci gce e2e test this

2017-01-23 23:11 UTC, philips commented
@k8s-bot gci gke e2e test this

2017-01-24 00:17 UTC, philips commented
@justinsb can you remove your change request block? I updated kubectl.

2017-01-24 06:14 UTC, roberthbailey commented
/lgtm

2017-01-24 18:26 UTC, philips commented
@k8s-bot cri e2e test this

2017-01-24 19:03 UTC, justinsb commented on pkg/kubectl/resource_printer.go
> +		return fmt.Sprintf("[%s]", strings.Join(roles, ","))
Do we want one role to be printed differently based on the annotation in use?

2017-01-24 19:26 UTC, philips commented on pkg/kubectl/resource_printer.go
> +		return fmt.Sprintf("[%s]", strings.Join(roles, ","))
@justinsb well, the role is now a list of roles so I put it into square brackets to make that clear. Open to doing it differently.

2017-01-24 20:15 UTC, philips commented on pkg/kubectl/resource_printer.go
> +		return fmt.Sprintf("[%s]", strings.Join(roles, ","))
removed the `[%s]` as kubectl get nodes looks funny. Good catch justin.

2017-01-24 20:18 UTC, philips commented
New output after 4704e92247e6c9fe091fb9ed56c7a8c3c3150a56

```
NAME                                       STATUS              AGE       VERSION           LABELS
ip-10-0-46-58.us-west-2.compute.internal   Ready,master,node   32d       v1.4.7+coreos.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m3.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2b,kubernetes.io/hostname=ip-10-0-46-58.us-west-2.compute.internal,node-role.kubernetes.io/master=true,node-role.kubernetes.io/node=true
```

2017-01-24 20:40 UTC, roberthbailey commented on pkg/kubectl/resource_printer.go
> +		return fmt.Sprintf("%s", strings.Join(roles, ","))
at this point you can just return strings.Join() since the fmt string doesn't do anything extra

2017-01-24 20:40 UTC, roberthbailey commented
any reason not to squash your commits?

2017-01-24 20:43 UTC, philips commented
@roberthbailey they are two different logical changes, one updates the logic in kubectl and the other adds the new constants. I can squash, just trying to make it easier to review as I assumed the kubectl team would only care about kubectl commits.

2017-01-24 20:44 UTC, philips commented on pkg/kubectl/resource_printer.go
> +		return fmt.Sprintf("%s", strings.Join(roles, ","))
@roberthbailey good point, fixed in c42e976

2017-01-24 20:44 UTC, justinsb approved these changes
LGTM

2017-01-24 20:45 UTC, justinsb commented
/lgtm

2017-01-24 21:44 UTC, philips commented
@k8s-bot cvm gce e2e test this

2017-01-24 22:32 UTC, philips commented
"Submit Queue — Required Github CI test is not green: Jenkins GCE e2e" but "Jenkins GCE e2e — Build succeeded.". Head scratch...

2017-01-24 22:45 UTC, roberthbailey commented
/lgtm

2017-01-25 06:19 UTC, philips commented
Can someone /approve the change in c4d1b78e48ed9d3b91fda0b174f8e2bfd501c14a in apimachinery OWNERS @caesarxuchao @smarterclayton @deads2k @lavalamp ?

2017-01-25 06:31 UTC, philips commented
Can someone please approve trivial kubectl improvement in c42e97602fe33dbefa41293a388bab2420759c7c from kubectl OWNERS? cc @pwittrock @janetkuo @fabianofranz @deads2k @brendandburns

2017-01-25 13:25 UTC, deads2k commented
In its current state, I'm disinclined to approve.  I can see that the old API made with labels is sub-par, but breaking compatibility seems unnecessary.  The new API doesn't seem significantly better and in some ways is worse since it requires custom, not really blessed labels to be used if someone wants to describe their role differently.

In addition, I don't see compatibility advice in the docs or even a release note in the description.  Beyond that, if any later decisions are made to respect these roles there are permissions implications for setting the labels.  And I haven't seen why the existing API couldn't simply allow a delimited list as an option.

2017-01-25 13:26 UTC, deads2k commented
@kubernetes/api-reviewers

2017-01-25 17:06 UTC, philips commented
On Wed, Jan 25, 2017 at 5:26 AM David Eads <notifications@github.com> wrote:

> In its current state, I'm disinclined to approve. I can see that the old
> API made with labels is sub-par, but breaking compatibility seems
> unnecessary.
>
@deads2k can we discuss this on a hangout? The old labels were used for one
release, in no non-alpha tools, and found to be troublesome because it is
impossible to describe single-node clusters ala minikube.

https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-268713324

Plus, the primary stakeholders of all known users: kubeadm (rep @jbeda),
bootkube (rep @philips), and kops (rep @justinsb) all agree with this
change.

> The new API doesn't seem significantly better and in some ways is worse
> since it requires custom, not really blessed labels to be used if someone
> wants to describe their role differently.
>
That was a problem in the old setup as well, there would be non-blessed
values if the user decided to do that.

https://github.com/philips/kubernetes/blob/c4d1b78e48ed9d3b91fda0b174f8e2bfd501c14a/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/well_known_labels.go#L84-L90

 The real problem is that a node can only have one role which as we
identified above is not going to truly reflect the truth of various cluster
configurations.

> In addition, I don't see compatibility advice in the docs or even a
> release note in the description. Beyond that, if any later decisions are
> made to respect these roles there are permissions implications for setting
> the labels. And I haven't seen why the existing API couldn't simply allow a
> delimited list as an option.
>
See the discussion on this PR on why the existing API doesn't work. It is
about label selectors:
https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-268723992

Brandon

2017-01-25 17:23 UTC, jbeda commented
This change is obviously the right way to go.  In many placers in k8s we've tried to avoid creating "mini languages" in strings and represent things in a way that works with our existing tools.  If we keep the current scheme it is hard to say "show me all the nodes that are part of the node role" without putting logic of all the combos in to the client or doing filtering client side after parsing label values.  This goes against the purpose of labels.

It is troublesome that this is a change that may potentially break people.  But these labels are not widely used.  And this isn't going to get any easier.

I think that the *biggest* problem is going to be the networking daemonsets that are built to work with kubeadm.  A quick google search pulls up stuff like this: https://raw.githubusercontent.com/tigera/canal/master/k8s-install/kubeadm/canal.yaml.  But that set up may be broken for other reasons when doing small clusters.

I'm happy to approve this assuming that kops and kubeadm folks are on board.  @deads2k -- do you care enough to try and block this?

2017-01-25 18:39 UTC, deads2k commented
> I'm happy to approve this assuming that kops and kubeadm folks are on board. @deads2k -- do you care enough to try and block this?

I think I do.  The new API as written here is effectively two inextensible special cases which will prevent reasonable categorization by anyone who can't get a commit into kube.  The API it half replaces (no attempt at conversion for instance), at least allowed for that use-case.

I'm not defending the old API as something we need to stick with, but I'd like to see a replacement that can keep the good things about the old API and provide additional power on top.  In addition, since this was shipped, backwards compatibility should be maintained.  That should be possible in many cases.

About having mini-languages inside of labels.  Having encoded json inside of labels and annotations has unintended consequences with regard to conversion and deprecation, but a backwards compatible delimited list is something I could live with.  If you were to create a new API and wanted compatibility with the old, supporting a delimited list in that label is a way to achieve that.  New clients could use the new thing you created, old clients wouldn't necessarily be hosed.  The value was either enumerated or opaque for them anyway, I'm not sure how it was spec'ed.

@smarterclayton @liggitt

2017-01-25 18:49 UTC, philips commented
@deads2k Can you provide a concrete example of how you can solve your issues without pushing complexity onto other parts of the system like node selectors, etc. See the original description for ideas I had but fall down in those scenarios.

Alternatives:

- Create kubernetes.io/role=master+node for these combined role. Problem: Every combination and ordering needs to be expressed in a giant OR statement for node selectors because labels are strict k/v matches.
- Ask users to select role=master OR role=node OR ... . Problem: It becomes really hard to express new roles like federation-master and have a machine run both federation-master components and local cluster master components without updating all of the selectors everywhere to have this new role.

In summary: It is hard to express a set with labels, and this feels like the best solution because it puts complexity on the labeler of a small number of objects (nodes) instead of pushing complexity onto a large number of objects (kubernetes component deployments, external networking systems daemonsets, federation systems deployments, etc).

2017-01-25 18:53 UTC, deads2k commented
@philips `role.kubelet.k8s.io/<value>` is a pattern that comes to mind, though deletion is hard. It's close to what you have here, but you didn't support conversion (backwards compatibility) and you didn't treat it or document it here as a prefix.

2017-01-25 19:11 UTC, philips commented
@deads2k Can you have a label without a value in your `role.kubelet.k8s.io/<value>` example?

The backwards compatibility I am happy to document and I did so in a comment and in the GoDoc header of the constant which is where the alpha label backwards compatible stuff is too. Where else should it be documented do you feel?

2017-01-25 19:18 UTC, philips commented
@deads2k how have we supported conversion of labels in the past?

2017-01-25 19:19 UTC, deads2k commented
> @deads2k Can you have a label without a value in your role.kubelet.k8s.io/<value> example?

I'm not 100% what validation allows and doesn't.  Really any marker would work.  I'm more concerned about actually treating it as a prefix so we can have external participation even if there's a set of well-known options.





> The backwards compatibility I am happy to document and I did so in a comment and in the GoDoc header of the constant which is where the alpha label backwards compatible stuff is too. Where else should it be documented do you feel?

I don't think that simply documenting "I broke it" is enough.  The label itself isn't clearly labeled or doc'ed in place as alpha.  I think this is a case where you actually handle backwards compatibility explicitly as a manual conversion, perhaps with a sunset in a couple versions.

2017-01-25 19:21 UTC, philips commented
@deads2k I doc'd it in the GoDoc string for the API package and explained the priority thinking in a comment on kubectl. Where else do we doc these things? 

This label isn't widely used today as it made it into 1.5 but we identified the issue here before it got widely deployed. So although I get your concern the urgency is rather low.

2017-01-25 19:22 UTC, deads2k commented
> @deads2k how have we supported conversion of labels in the past?

Ones with alpha (`alpha.k8s.io/something`) in the name have been broken before, but this isn't in this category.  Other labels haven't been broken.



> @deads2k I doc'd it in the GoDoc string for the API package and explained the priority thinking in a comment on kubectl. Where else do we doc these things?

I don't see this as a case of "doc it".  I see this as a case of "fix it".  Add the manual conversion logic.

2017-01-25 19:24 UTC, philips commented
@deads2k Add conversion logic where? The only place in tree using the label is kubectl which I fixed. Otherwise the intention is to use the label in kops, bootkube, and kubeadm which are either out of tree or moving out of tree.

2017-01-25 19:45 UTC, deads2k commented
> @deads2k Add conversion logic where? The only place in tree using the label is kubectl which I fixed. Otherwise the intention is to use the label in kops, bootkube, and kubeadm which are either out of tree or moving out of tree.

Inside of the API conversions when nodes are converted (maybe defaulted).  Once it became a well-known label in kube, it became API for nodes.

2017-01-25 19:48 UTC, philips commented
@deads2k But, only _external_ tools are applying the label (bootkube, kops, kubeadm). It seems dangerous that the API server starts silently converting external labels. Is there precedent for that?

2017-01-25 20:20 UTC, liggitt commented
> @deads2k But, only external tools are applying the label (bootkube, kops, kubeadm). It seems dangerous that the API server starts silently converting external labels.

my strong preference would be to keep the labels external, which would mean no special display treatment in kubectl and no special scheduling behavior based on those labels

my concern is that "well-known" means that these labels are special, and that people assume that all kubernetes deployments will use these keys

2017-01-25 20:42 UTC, deads2k commented
> my strong preference would be to keep the labels truly external, which would mean no special display treatment in kubectl and no special scheduling behavior hardcoded to those labels
> 
> my concern is that "well-known" means that these labels are special, and that people assume that all kubernetes deployments will use these keys

I could agree with that.  Remove all traces from kubectl, any source in k8s.io/kubernetes, make the external tool using something other than k8s.io (or strongly namespace it to your project), and then it doesn't need API review at all.

2017-01-25 21:55 UTC, philips commented
@deads2k @liggitt The idea of a "master" and "node" role is well defined ([docs example](https://kubernetes.io/docs/admin/master-node-communication/)) that defining a label for it inside of the kubernetes.io namespace is the right thing to do; these labels and concepts are not something that belong in a kops, kubeadm, or bootkube namespace because it is labeling a Kubernetes concept.

This is one of those leap of faith things where we provide a little metadata to enable people to query nodes to assist in debugging, schedule pods in different privileged parts of the cluster, and land daemonsets based on role.

I feel less passionate about the kubectl feature as I don't think it necessarily adds value over the labels themselves.

tl;dr I am fine removing the code from kubectl to display node role; but I feel the labels should be owned and defined by Kubernetes to encourage tooling.

2017-01-25 22:03 UTC, liggitt commented
> I feel the labels should be owned and defined by Kubernetes to encourage tooling.

I really thought labels were supposed to be opaque to kubernetes, and user-owned. From https://kubernetes.io/docs/user-guide/labels/:

> Labels are key/value pairs that are attached to objects, such as pods. Labels are intended to be used to specify identifying attributes of objects that are meaningful and relevant to users, but which do not directly imply semantics to the core system. 

Blessing first-class label keys for these roles seems like a change in direction. I'm also concerned about declaring certain labels as special without accompanying controls around setting and targeting them, and without a clear understanding of what setting those labels will actually *do*.

2017-01-25 22:21 UTC, philips commented
On Wed, Jan 25, 2017 at 2:03 PM Jordan Liggitt <notifications@github.com>
wrote:

> @philips <https://github.com/philips>: I feel the labels should be owned
> and defined by Kubernetes to encourage tooling.
>
> I really thought labels were supposed to be opaque to kubernetes, and
> user-owned. From https://kubernetes.io/docs/user-guide/labels/:
>

That isn't the full context of what I am saying. I am saying _these_ labels
should belong in the kubernetes.io namespace because they represent a
Kubernetes concept. We have other Kubernetes concepts in the kubernetes.io
namespace which I believe are useful for the same reasons that these labels
are useful: they enable other tools.

Examples: arch=amd64,instance-type=m3.medium,os=linux


> Labels are key/value pairs that are attached to objects, such as pods.
> Labels are intended to be used to specify identifying attributes of objects
> that are meaningful and relevant to users, but which do not directly imply
> semantics to the core system.
>
> Blessing first-class label keys for these roles seems like a change in
> direction. I'm also concerned about declaring certain labels as special
> without accompanying controls around setting and targeting them, and
> without a clear understanding of what setting those labels will actually
> *do*.
>

Should we remove kubernetes.io/arch, kubernetes.io/instance-type,
kubernetes.io/os? I feel these are generically useful for a variety of
administrative and debugging purposes and aren't explicitly defined as
having a "use case".

2017-01-25 23:31 UTC, jbeda commented
It seems like we are talking about 3 things here:

1. What is the correct way to model this going forward?
2. Is this a "kubernetes" concept or a "user" concept.
3. How do we deal with migrating from the existing system to the next system.

Wrt (1) I think that we have no other reasonable proposal on the table that satisfies the (very reasonable) requirements that Brandon is proposing.  That is that they must be usable with standard label queries and allow for a machine to play both the master and node roles.  @deads2k -- you said that we have encoded json in labels in other places but I think that is incorrect.  I'm not aware of us putting that kind of structure in labels anywhere.

Wrt (2) We haven't been super disciplined in terms of how we allocate and extend the `kubernetes.io` namespace for labels (and annotations, secret types, resource names.  `types.go` says "The "kubernetes.io/" prefix is reserved for use by kubernetes components."  Is `kubeadm` a Kubernetes component? In addition, none of the talk about alpha talks about using it for labels.  Our usage there has been spotty.

With that in mind, this is a well defined enough concept across Kubernetes that it isn't crazy to canonize it as official.  But, to play devils advocate, what would the right prefix be for `kubeadm` specific version of this?  Would you be happier if we made this be `node-role.kubeadm.kubernetes.io/<foo>`?  We already have `kubeadm.alpha.kubernetes.io/role` which should probably be deprecated as part of this change also.

Wrt (3) while these labels are not marked as alpha (we don't have guidelines for alpha naming for nodes) they are essentially unused.  I couldn't find any usage that would break if we just nuked these and repaved them.  Even kubeadm just sets them.  The real work is being done with taints and tolerances.

*My proposal:* We declare all the stuff that is currently there as "alpha" and repave it with `node-role.kubernetes.com/{master,node}=true`.  We change the support in kubectl to just look for the prefix `node-role.kubernetes.com/XXX` and return a list of these values.  In that way we can add more roles in the future without modifying kubectl.

Also -- when researching this I came across #35904 (cc @justinsb).  Also https://github.com/kubernetes/kubeadm/issues/124 (cc @luxas @runningman84)

2017-01-26 00:32 UTC, deads2k commented
I think that if your label is so "blessed" that it lives inside the k8s.io/kubernetes code base, it's effectively an API and we respect API backwards compatibility.  Your label lives in the k8s.io/kubernetes code base, it can have conversions to maintain backwards compatibility as you "version" your label.   That's effectively what this is doing.

If your label is not so blessed or you don't want to treat it as an API, then it doesn't get to live in the k8s.io/kubernetes code base (easiest) or it has alpha or some such in the name.  In this case, you don't have to maintain backwards compatibility and you don't count as an API in the kube backward compatibility sense.

By having something in the well-known label field without any alpha in the name, this is essentially a new field that someone created in the API without creating it in the API.  That's how it looks to API consumers.  We cannot provide a set of well-known labels and then simply change our mind about them without keeping them compatible unless they have been explicitly listed as alpha (and including API version status in names has been around a while).



> @deads2k -- you said that we have encoded json in labels in other places but I think that is incorrect. I'm not aware of us putting that kind of structure in labels anywhere.

Fair.  I was thinking about annotations.  Still, try to avoid that.  It has made a mess.

2017-01-26 00:34 UTC, deads2k commented
> Would you be happier if we made this be node-role.kubeadm.kubernetes.io/<foo>? We already have kubeadm.alpha.kubernetes.io/role which should probably be deprecated as part of this change also.

If that were name, I'd boot the constant from k8s.io/kubernetes and remove the describer, but I'd view the API as effectively owned by kubeadm, not k8s.io/kubernetes.  If they make the decision to break compatibility, so be it.

2017-01-26 00:38 UTC, deads2k commented
> My proposal: We declare all the stuff that is currently there as "alpha" and repave it with node-role.kubernetes.com/{master,node}=true. We change the support in kubectl to just look for the prefix node-role.kubernetes.com/XXX and return a list of these values. In that way we can add more roles in the future without modifying kubectl.

I'm ok with the prefix idea, though if its generic kube, I'm against limiting it to purely master or node.  If you have a prefix that lives in k8s.io/kubernetes as a well-known label though, I expect backwards compatibility to be a consideration.

If you move the annotation to `node-role.kubeadm.kubernetes.io/<foo>` (or something under kubeadm.kubernetes.io), then I'm willing to say that the existing one was just a mistake and we simply purge it from the codebase (including describer handling).  No conversion or API compatibility required.

I don't think this is a case where you can have your cake and eat it too.

2017-01-26 17:43 UTC, roberthbailey commented
@deads2k - note that there is a similar discussion happening w.r.t. cluster addons. See 40108#issuecomment-275452533.

2017-01-26 18:22 UTC, philips commented
Clickable version of Robert's link: https://github.com/kubernetes/kubernetes/pull/40108#issuecomment-275452533

My thoughts: Add-ons using kubernetes.io namespace is the right thing because addons are central to making a usable system and will need debugging/administration. Similarly using kubernetes.io namespace labels that reflect _central_ architecture of Kubernetes like node role is the right thing too.

2017-01-26 18:56 UTC, smarterclayton commented
So anything in kubernetes.io that is versioned falls under API approval - @kubernetes/api-approvers copied to weigh in.

2017-01-26 19:07 UTC, lavalamp commented
My $.02: the change is obviously correct. However labels in `kubernetes.io` need to have an api review and if that already happened, then we can't break compat. If that didn't happen then they were rogue usage and we shouldn't have had them in kubectl.

2017-01-26 20:54 UTC, philips commented
Thanks @lavalamp.

The original PR adding this label was in
https://github.com/kubernetes/kubernetes/pull/35975. It involved
@bgrant0607 @smarterclayton and @justinsb and was LGTM'd by @bgrant0607.

I agree that we need to be careful about adding stuff to the API but there
are two things we need to sort out:

1. The review process isn't documented in the [API Changes](
https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md)
documentation. Where is the process?
2. The API Changes documentation doesn't talk about labels

Happy to make the process better, etc. But, I would like to resolve this
particular label situation one way or the other soon because it is an
integration point between kubeadm, bootkube, kops, and hopefully other
tooling. And right now all of these tools are using ad-hoc project specific
labels needlessly.

On Thu, Jan 26, 2017 at 11:08 AM Daniel Smith <notifications@github.com>
wrote:

> My $.02: the change is obviously correct. However labels in kubernetes.io
> need to have an api review and if that already happened, then we can't
> break compat. If that didn't happen then they were rogue usage and we
> shouldn't have had them in kubectl.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-275480984>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AACDCIUgT4XU6w015SHXXlvdD4fzzvl1ks5rWO8fgaJpZM4LTgWX>
> .
>

2017-01-26 22:08 UTC, bgrant0607 commented
@philips There is no documented process yet.

Labels are discussed here:
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#label-selector-and-annotation-conventions

@thockin @brendandburns and @smarterclayton have been discussing annotation conventions, but not process AFAIK

2017-01-26 22:09 UTC, philips commented
@bgrant0607 OK, so the original PR followed the process as it is today, right?

2017-01-26 22:14 UTC, bgrant0607 commented
@philips PR #35975 ? Yes.

2017-01-26 22:21 UTC, philips commented
@smarterclayton @lavalamp OK, so the original PR followed the right process. And I think everyone agrees that the labels merged in _November_ are not good and this is the right change. 

So, I need @thockin @bgrant0607 @erictune or @smarterclayton to LGTM? 

@smarterclayton how does someone become an @kubernetes/api-approvers ? It seems this group doesn't match https://github.com/kubernetes/kubernetes/blob/master/pkg/api/OWNERS which includes @lavalamp and doesn't include @bgrant0607.

2017-01-26 22:33 UTC, deads2k commented
> However labels in kubernetes.io need to have an api review and if that already happened, then we can't break compat.

@philips For backwards compatibility, if you could fill out a table of reading and writing patterns of old clients and new clients separately and then intermingled (old updates, new reads, new updates, old reads) and we can try to get it right.

2017-01-26 22:36 UTC, philips commented
@deads2k I appreciate the discipline about doing changelog and backward compat stuff on all API changes. However, the labels we are discussing merged November 7th 2016 (merge commit 15fa0df93e5e40e82fe2002db45b54c7648b7a26) and there are no known production users. Adding a doc will just create long-term cruft. I can write the doc if it is the only way to unblock this however.

2017-01-26 22:44 UTC, philips commented
@deads2k where should I put a table with backwards compatibility? Is there some part of the [API changes](https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md) docs that tell me where this stuff is recorded? Is there an API changelog file I don't know about?

2017-01-26 22:54 UTC, deads2k commented
> @deads2k where should I put a table with backwards compatibility? Is there some part of the API changes docs that tell me where this stuff is recorded? Is there an API changelog file I don't know about?

The table is so that you can update the code to make the change backwards compatible with the previous API that merged (as myself and @lavalamp noted we do do for APIs).  Not to document a break.  It'll help reviewers reason through the safety of your updates.

Also, the new API needs to go through review so I think that handling prefixes (not baked names) is going to be important.

2017-01-26 23:00 UTC, philips commented
On Thu, Jan 26, 2017 at 2:54 PM David Eads <notifications@github.com> wrote:

> @deads2k <https://github.com/deads2k> where should I put a table with
> backwards compatibility? Is there some part of the API changes docs that
> tell me where this stuff is recorded? Is there an API changelog file I
> don't know about?
>
> The table is so that you can update the code to make the change backwards
> compatible with the previous API that merged (as myself and @lavalamp
> <https://github.com/lavalamp> noted we do do for APIs). Not to document a
> break. It'll help reviewers reason through the safety of your updates.
>
Is there an example of what you would like somewhere?

> Also, the new API needs to go through review so I think that handling
> prefixes (not baked names) is going to be important.
>
Is there precedent for "label prefixes"? The Kubernetes label API isn't
designed to allow for querying of labels by prefix so I am confused on what
you would like to see.

Thank You,

Brandon

2017-01-26 23:51 UTC, smarterclayton commented
Re: prefixes I believe this is the idea that the key represents the role:

role.kubelet.kubernetes.io/master=1
role.kubelet.kubernetes.io/node=1

So that multiple keys can coexist, since as you noted you want
duplicates.  But, who gets to decide who owns /*?  We generally
reserve parts of the namespace for things we can by fiat (in this
project) allocate, so some way of ensuring others could extend without
limiting our future moves.  Unfortunately this kind of new territory -
we've never really declared a value like this where we will be locked
in to that decision.

2017-01-27 00:30 UTC, deads2k commented
@smarterclayton right and the old value said the value was the role and did not restrict it in any way.  If the new scheme does not allow a similar name-space for roles it is less powerful and far more prescriptive.

2017-01-27 00:39 UTC, philips commented
On Thu, Jan 26, 2017 at 3:52 PM Clayton Coleman <notifications@github.com>
wrote:

> Re: prefixes I believe this is the idea that the key represents the role:
>
> role.kubelet.kubernetes.io/master=1
> role.kubelet.kubernetes.io/node=1
>
> So that multiple keys can coexist, since as you noted you want
> duplicates.


I understand the concept. But, how practically do we implement this? Do I
make the prefix a constant here? I don't understand the value of the prefix
because you can't _query_ by prefix.

Brandon

2017-01-27 12:37 UTC, deads2k commented
> Do I
> make the prefix a constant here?

The prefix would be a constant and the special cases for master and node are removed.  The existing annotation allows `role=awesome-role-from-startup`, the new ones you've made are purely prescriptive currently.  Since the names are predictable, they're just as easy to use in a label selector as anything else.

Documented as a prefix, it means anyone writing code to deal with roles would understand the intent and we wouldn't lose the extensible power of the roles as they are today.

2017-01-27 16:34 UTC, philips commented
@deads2k But a prefix cannot be in a label query! Can we please do a Google Hangout because I don't understand how a prefix helps anyone. A concrete user must know an EXACT label to do anything useful.

2017-01-27 16:41 UTC, philips commented
@deads2k is this all you are asking for? https://github.com/philips/kubernetes/commit/1093be21334ab626508b8dfe181af5ae59e9b726

2017-01-27 16:48 UTC, deads2k commented
> @deads2k is this all you are asking for? philips@1093be2

Close, you don't get to take the old label value constants.  Those are related to a kubeadm API (see the comment in master https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/well_known_labels.go#L66) , so they shouldn't be in this file at all.

I think the new API should be agnostic to role names (just like the existing one).  The master and node roles could be added in particularly deployment methods, but they shouldn't be blessed in the k8s.io/kubernetes API.

2017-01-27 19:46 UTC, smarterclayton commented
So from a design perspective, can we answer the following questions:

1. Do we believe that all future clusters will adopt these role labels?
Including existing clusters, existing installers, tops, cluster-up, cargo,
and any home rolled ones implemented already?  I think some of the concern
is pre-designing things we don't know
2. Would it be better for kubeadm to totally own this API, drive it to
completion and show a working system, before we impose it on other systems?

The original PR as merged was not sufficiently ready to satisfy all the
possible growth (hence the concerns on both sides here about getting away
from it ASAP).

If we said "let's make this kubeadm's responsibility to determine in their
own api space, and not a kubernetes API problem for the next 2 releases",
would we be in a better spot?  In that case, kubeadm would own the
responsibility of dealing with the break in compatibility, and enact its
own conventions, and we would scrub these roles from the history books in
the Kube API side?

If we want to scale the project, making kubeadm the owners of this API
problem, and not kube, is a good way forward.  We can always come back
later and codify this, but until then I'd rather kubeadm own the
responsibility as a project around kube.  Sometimes we drop APIs into the
core that in order to scale we need to move out.


On Fri, Jan 27, 2017 at 11:49 AM, David Eads <notifications@github.com>
wrote:

> @deads2k <https://github.com/deads2k> is this all you are asking for?
> philips@1093be2 <https://github.com/philips/kubernetes/commit/1093be2>
>
> Close, you don't get to take the old label value constants. Those are
> related to a kubeadm API (see the comment in master
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/
> apimachinery/pkg/apis/meta/v1/well_known_labels.go#L66) , so they
> shouldn't be in this file at all.
>
> I think the new API should be agnostic to role names (just like the
> existing one). The master and node roles could be added in particularly
> deployment methods, but they shouldn't be blessed in the k8s.io/kubernetes
> API.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-275713102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_pxlvCY9qpuoMv7VO7YACVduAr0o1ks5rWh_9gaJpZM4LTgWX>
> .
>

2017-01-27 20:15 UTC, philips commented
On Fri, Jan 27, 2017 at 11:47 AM Clayton Coleman <notifications@github.com>
wrote:

> 1. Do we believe that all future clusters will adopt these role labels?
> Including existing clusters, existing installers, tops, cluster-up, cargo,
> and any home rolled ones implemented already? I think some of the concern
> is pre-designing things we don't know
>

Yes. Tools like bootkube, kops, and kubeadm all need well-known labels for
their use case of landing pods on nodes with well understood Kubernetes
architecture roles: node and master. Today bootkube, kops, and kubeadm are
all using different labels and we wanted to fix this.

https://github.com/kubernetes-incubator/bootkube/pull/263
https://github.com/kubernetes/kubernetes/commit/1c132fe974c563cdfb5c1bc70d6a7d4c14c9d806#diff-f2f9bc504cba22e1b01c036b5973fa09R150


> 2. Would it be better for kubeadm to totally own this API, drive it to
> completion and show a working system, before we impose it on other systems?
>

We are trying to create a label that is "well known" so that _external_
tools that want to interact with clusters launched via one of these tools
can land daemonsets or pods based on their Kubernetes cluster role.


> The original PR as merged was not sufficiently ready to satisfy all the
> possible growth (hence the concerns on both sides here about getting away
> from it ASAP).
>

I had a long discussion with @deads2k on this and it is clear that we have
different perspectives on what labels are good at.

My thoughts: labels are primarily useful when you know the _exact_ label
k/v so you can write those labels into pod/daemonset specs. Anything in the
kubernetes.io namespace should be explicitly documented as a k/v. And
anything in kubernetes.io should represent Kubernetes concepts or
architecture.

@deads2k thoughts: labels should be interpretable by users using
enumeration and string matching. The kubernetes.io namespace may define
label prefixes where a user can put anything they wish after the prefix. In
his example node-role.kubernetes.io/build-worker=true is valid. This is OK
even though build-worker is not a Kubernetes concept today; a user should
have the freedom to define new roles without coordination inside of a
Kubernetes project.


> If we said "let's make this kubeadm's responsibility to determine in their
> own api space, and not a kubernetes API problem for the next 2 releases",
> would we be in a better spot? In that case, kubeadm would own the
> responsibility of dealing with the break in compatibility, and enact its
> own conventions, and we would scrub these roles from the history books in
> the Kube API side?
>

This discussion is something I want to move to the SIG API machinery
mailing list. At no point have we ever created backwards compatibility and
conversion code for labels. We need to have this discussion as we have a
ton of labels in the kubernetes.io namespace that have changed meaning and
been dropped over time.


> If we want to scale the project, making kubeadm the owners of this API
> problem, and not kube, is a good way forward. We can always come back
> later and codify this, but until then I'd rather kubeadm own the
> responsibility as a project around kube. Sometimes we drop APIs into the
> core that in order to scale we need to move out.
>

The original intention was to have a single Go package for kubeadm, kops,
and bootkube to share the labels these projects should use and this seemed
like the right place.

Perhaps the kubernetes.io well known labels should not be an API concern.
Idea: we move well known Kubernetes labels elsewhere so projects like kops,
kubeadm, and bootkube can scale collaboration. What about creating a
k8s.io/well-known-labels pkg which is an easy registry for projects with
light rules around number of github.com/kubernetes-*/ users and namespacing.

2017-01-27 21:14 UTC, liggitt commented
>> 1. Do we believe that all future clusters will adopt these role labels? Including existing clusters, existing installers, tops, cluster-up, cargo, and any home rolled ones implemented already? I think some of the concern is pre-designing things we don't know
>
> Yes. Tools like bootkube, kops, and kubeadm all need well-known labels for
their use case of landing pods on nodes with well understood Kubernetes
architecture roles: node and master. Today bootkube, kops, and kubeadm are
all using different labels and we wanted to fix this.
>
> We are trying to create a label that is "well known" so that _external_ tools that want to interact with clusters launched via one of these tools can land daemonsets or pods based on their Kubernetes cluster role.

This goes back to the "what is core?" question.

If someone is writing an integration depending on labels that are only set by specific deployers, shouldn't the label names make them aware of that? Documenting what appear to be deployment-independent labels for steering workloads toward/away from masters, while counting on deployers to set those labels, is concerning.

If the labels appear deployment-independent, I'd expect the kubelet or node controller or some core component to be responsible for setting them (like the kubelet does with `beta.kubernetes.io/arch`). If not, doesn't this encourage people to write manifests they think are deployment-neutral that will actually break on most existing deployments?

> At no point have we ever created backwards compatibility and conversion code for labels.

I agree that's a pain, but once we represent deployer- or core-created labels as the proper way to steer workloads, it becomes a de-facto API, and either the deployer or the core becomes responsible for maintaining that meaning (excepting alpha and possibly beta labels).

Either we give people control over labels themselves (e.g. `kops create cluster --master-label=master=true --node-label=node=true`) and they can lock in their own meaning, or we sign up for keeping selectors compatible.

2017-01-27 21:32 UTC, smarterclayton commented
We've definitely had backwards compatibility for labels - it hit us several times with both jobs and deployments, and we use it for the core kubelet node labels.  Agree the conversion logic is net new - I think there's room in folks opinions that we might be able to avoid that compatibility, as long as it looks like the new labels are well designed.

Having dealt with several rounds of backwards compatibility of labels and how we handle them on deployments and replica sets I can guarantee that once they are baked they are nigh impossible to change.  Once you use a label from a controller, if you want to change it you have to build controller code that reads two sets of labels and merges the results for many releases afterwards (we're still doing it in places from 1.1).  So I agree on the desire to define them exactly once... if I had any confidence in our collective ability to get them right the first time. :)

2017-01-27 21:33 UTC, philips commented
On Fri, Jan 27, 2017 at 1:15 PM Jordan Liggitt <notifications@github.com>
wrote:

> If the labels appear deployment-independent, I'd expect the kubelet or
> node controller or some core component to be responsible for setting them
> (like the kubelet does with beta.kubernetes.io/arch). If not, doesn't
> this encourage people to write manifests they think are deployment-neutral
> that will actually break on most existing deployments?
>
How will it break on existing deployments? We are talking about documenting
a consensus in our well-known labels to enable easier collaboration.

Existing users wishing to label their Nodes have two supported existing
options to utilize these labels:

kubectl label node 1.compute.internal node-role.kubernetes.io/master=true

OR

kubelet --node-labels node-role.kubernetes.io/master=true

I have no clue what well_known_labels.go is for if not to encourage useful
community wide consensus on labelling for use by applications and users.

> Either we give people control over labels themselves (e.g. kops create
> cluster --master-label=master=true --node-label=node=true) and they can
> lock in their own meaning, or we sign up for keeping selectors compatible.
>
Users have control over the label themselves. This is a well-known label
not a must-use label.

2017-01-31 22:20 UTC, roberthbailey commented
This discussion is beginning to block multiple other PRs. Is there a way that we can reach a consensus soon? Maybe a quick meeting with the relevant stakeholders (@deads2k, @smarterclayton, @philips, @jbeda) would be the most expedient?

2017-02-06 23:01 UTC, philips commented
@roberthbailey Happy to jump on a call and figure it out.

My current plan, as this PR is at an impasse, was to use the label as proposed here in kops, kubeadm, and bootkube and figure out the situation with making the const part of the API package at some later time. I was going to email SIG Cluster Lifecycle about that later today.

Happy to jump on a call too but I don't see a clear way pass the impasse.

2017-02-08 01:02 UTC, smarterclayton commented
If sig-cluster-lifecycle owns the relevant old usage (and can manage that
transition), and the new label is considered to be owned by
sig-cluster-lifecycle and limited in scope (define master and node sub
labels, and have a clear statement about future extension of that label), I
think it's ok for the sig to decide to deprecate the old label without
conversion.

I'm ok with leaving this in the current location as long as the language is
tightened (define that either no one should add to this, or that it's a
free for all and no future label will be added).

On Mon, Feb 6, 2017 at 6:01 PM, Brandon Philips <notifications@github.com>
wrote:

> @roberthbailey <https://github.com/roberthbailey> Happy to jump on a call
> and figure it out.
>
> My current plan, as this PR is at an impasse, was to use the label as
> proposed here in kops, kubeadm, and bootkube and figure out the situation
> with making the const part of the API package at some later time. I was
> going to email SIG Cluster Lifecycle about that later today.
>
> Happy to jump on a call too but I don't see a clear way pass the impasse.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-277842784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p69WF03xNgoTX87CZq9MnbSjd18-ks5rZ6ZMgaJpZM4LTgWX>
> .
>

2017-02-08 14:08 UTC, luxas commented
I'm in favor for removing the old alpha label for the master that has been used in kubeadm so far.
Since kubeadm was alpha in v1.5, we have no backwards-compatible guarantees, so it's safe to break this.

But I want something we can actually provide forwards-compability on now that we're targeting beta, and this seems reasonable for that. Further, I think this is generic enough to adopt in all kube deployments (kubeadm, kops, kargo, minikube, kube-up, etc). For that purpose (being a core notation of specifying where the master is, and maybe other k8s core roles in the future) it seems like having it in the core is one ok way of saying "hey, this is a thing we've standardized on and official k8s deployments should mark the master this way".

Please comment here if you think the above statements are totally unreasonable. In any case, we absolutely should remove the label we're using in kubeadm (and maybe bootkube), because that's something I definitely don't want for beta.

TL;DR; Whatever label we settle on exactly, it should be an extensible way of defining a role of a given node, and we should get rid of the current `kubeadm.alpha.kubernetes.io/role`. Just my 2c :)

2017-02-14 08:22 UTC, roberthbailey commented
@thockin for comments based on https://github.com/kubernetes/community/issues/300

2017-02-14 08:22 UTC, roberthbailey commented
I'd like to come to an agreement about this PR soon as it will unblock a few other things we want to land to make kubeadm beta in 1.6.

2017-02-15 07:04 UTC, sttts commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/well_known_labels.go
> +	LabelNodeRoleMaster = "node-role.kubernetes.io/master"
We need a different place for these node labels. The concept of a node does not exist on the level of apimachinery. Would you mind moving the new labels and the old ones below to `pkg/api/types.go`, i.e. next to the definition of `type Node`?

2017-02-15 07:06 UTC, sttts commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/well_known_labels.go
> +	LabelNodeRoleMaster = "node-role.kubernetes.io/master"
And better make them consistent with the naming of the existing labels, i.e. `NodeLabelMasterRole`.

2017-02-15 07:08 UTC, sttts commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/well_known_labels.go
> +	LabelNodeRoleMaster = "node-role.kubernetes.io/master"
And now we have: `NodeLabelRoleMaster` and `LabelNodeRoleMaster`. At least, I am confused now :-) If one is the successor of the other, maybe let's rename the old one to something with `Legacy`.

2017-02-22 20:02 UTC, davidopp commented
Trying to understand this PR (and the associated controversy).

IIUC, every cluster has at least one computer (I'm intentionally not using "node"!) that serves as master. Depending on your cluster configuration, the master(s) may run user workloads or not. The idea in this PR is to distinguish three kinds of computers
1. computers that run only master components
2. computers that run only user workloads
3. computers that can run both

Computers in category (1) will get the `node-role.kubernetes.io/master` label. Computers in category (2) will get the `node-role.kubernetes.io/node` label. Computers in category (3) will get both labels. Is that correct?

BTW life would be so much simpler if we hadn't gotten rid of the "minion" terminology... :(

2017-02-22 20:07 UTC, smarterclayton commented
There's another category:

4. computers that run components that aren't officially part of "the master" but an outside observer would consider them part of the master.  For instance - a computer that only runs a shared ingress for the cluster, or a computer that runs an oauth server that is the authority for the entire cluster.

2017-02-22 20:34 UTC, justinsb commented
My opinion:

1. Masters are machines that run only pods that have been trusted by the cluster administrator to run on the master and that the administrator has said must run on the master.  The administrator does this because they are sensitive (e.g. etcd) or need more IAM permissions (e.g. kube-controller-manager) or are just critical to the smooth operation of the cluster (e.g. kube-scheduler) etc.  It is the "secure enclave" of k8s.
2. We taint the master nodes to enforce that user pods don't run on the master.
3. We need _also_ to label the master nodes so that master pods _only_ run on master nodes.
4. But now we have the problem that not all administrators will want to isolate masters (e.g. minikube), and now we need to change the node selectors based on whether we are isolating masters or not.   This proposal changes the labels so that you can mark an instance as being both master & non-master (aka node).  For non-isolated masters we simply won't taint the master, but the equivalent option is not available for labels.

@smarterclayton your examples are still master-only pods, I believe.  Or they might be a new category - master-tolerant but not master-required, which can also be expressed as just a toleration.

2017-02-22 20:36 UTC, philips commented
@davidopp Correct. These are the three concrete use cases we are trying to solve with these labels.

2017-02-22 21:20 UTC, smarterclayton commented
For clarification, nodes with apiservers have far more privileges than other master components.  Only apiservers need access to etcd, whereas all other components can be limited via RBAC and admission.  Someone wanting to ensure that security distinction (this is how openshift has shipped since launch) would need a new role label and new taints?

2017-02-22 21:42 UTC, justinsb commented
@smarterclayton how do you do this in OpenShift today?

2017-02-22 21:49 UTC, smarterclayton commented
We have three sets of nodes:

* masters, which are unschedulable (run apiserver, etcd, controllers but not in pods)
* infra nodes, which are schedulable but only contain highly privileged components like the registry and ingress routers
* nodes, which regular apps run on

Enforced node selectors are used and will eventually transition to tolerations.  The distinction is that to an outsider infra nodes are probably "master", but in the strict definition you guys gave above I would probably not include them.  I would probably say that there is a taint on the masters that is even stronger than the role label described here, which would be role apiserver or etcd that excludes everything else.  One of the points of discussion above was how many more roles might exist - you helped me articulate that that would be one new one.

2017-02-22 21:53 UTC, luxas commented
@smarterclayton But with this design marking "infra nodes" would be pretty straight-forward, right?
`node-role.kubernetes.io/infra-node=""`

2017-02-22 22:16 UTC, luxas commented
Regardless; it seems like we don't have many arguments _against_ this label/taint key anymore...
Can we get https://github.com/kubernetes/kubernetes/issues/41835 approved?

The actual kubeadm implementation will still be of alpha stability in v1.6, so _it's even possible_ to use something else in v1.7 (absolutely not saying we should, though).

kops/bootkube is waiting for a resolution here as well

2017-02-24 23:33 UTC, philips commented
@smarterclayton Can we simply enumerate the roles then and get this merged:

master:
- MUST run the API server
- MAY run etcd member
- MAY run scheduler, controller manager, and other key components
- MAY run an AuthN provider or AuthZ webhook server

infra:
- MAY run a container registry
- MAY run an ingress controller
- MAY run storage systems
- MAY run DNS and other addons

nodes:
- MUST all non-infra and non-master workloads

And a given node can be a master, infra, and node or any combination at any time given the roles.

Honestly I am fine with this categorization. But, I do feel we need to make some sort of call here for the community.

2017-02-28 19:39 UTC, philips commented
Brian Grant formalized some of this architecture here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture.md#architecture

2017-03-23 17:48 UTC, bgrant0607 commented
@philips @smarterclayton @justinsb @deads2k @liggitt @luxas 

Is there a TL;DR to this? What is the current state?

@philips Linked to the architecture.md doc above. Other relevant docs:

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/taint-toleration-dedicated.md

"Infra" sounds like special case of dedicated.

Architectural roadmap (aka layers doc):

https://docs.google.com/document/d/1XkjVm4bOeiVkj-Xt1LgoGiqWsBfNozJ51dyI-ljzt1o/edit#

If/when we break up our monolithic components and self-host more of them, this will necessarily become more complex. I've given up trying to stamp it out but, fwiw, the "master" terminology is inherently linked to a monolithic implementation, inherited from the "master/worker" pattern.

2017-04-25 04:06 UTC, roberthbailey commented
This PR was discussed at the last cluster lifecycle SIG meeting so I'm adding a comment to keep it open a while longer.

2017-05-30 07:36 UTC, luxas commented
ping @philips @jbeda @roberthbailey @deads2k etc

kubeadm, kops and bootkube (I think) have used this label/taint for a release cycle already.
I think that's approval enough. Exists in beta and stable code.

Would be good to get this officially into v1.7

2017-05-30 12:02 UTC, deads2k commented
> ping @philips @jbeda @roberthbailey @deads2k etc
> 
> kubeadm, kops and bootkube (I think) have used this label/taint for a release cycle already.
> I think that's approval enough. Exists in beta and stable code.
> 
> Would be good to get this officially into v1.7

The question here is more about where such things should live, both in terms of source code and namespaces in which the labels are scoped.  As noted in this pull, the decisions about whose deployment topology is "in" and whose is "out" is rather arbitrary.  Building "API" on top of labels belongs to the components building the API, not to core kube.

2017-05-30 13:10 UTC, justinsb commented
I think it's clear at this point that this isn't going to get merged until the council of elders / steering committee weighs in.

I think this would be a great question to ask during candidate hustings :-)

2017-06-08 18:06 UTC, marun commented
I'm assuming this won't be decided for v1.7, bumping to v1.8.

2017-07-19 19:42 UTC, jescarri commented
Hi, this is some feedback regarding this PR.

I've been running into some trouble with prometheus sd and `node-role.kubernetes.io/master=""` which is implemented in tectonic 1.6.x https://github.com/coreos/tectonic-installer/issues/1439

Can we make sure that we always use key/value pairs for labels?, I think will make SD easier in the long run.

Or is there any specific reason to not set values to a label?
Thanks!.

2017-07-31 02:14 UTC, FengyunPan commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/well_known_labels.go
> +	LabelNodeRoleMaster = "node-role.kubernetes.io/master"
It is better to move these labels below to pkg/api/types.go.

2017-08-22 15:24 UTC, thockin commented
This thread is long.  Can we get an up-to-the-minute recap of the current state, proposals, and pros/cons ?

2017-08-22 15:32 UTC, luxas commented
@jbeda @philips @justinsb @smarterclayton ^

2017-08-22 15:41 UTC, justinsb commented
I believe it has been implemented by everything other than openshift, and agreed in the responsible sig.

2017-08-22 20:57 UTC, thockin commented
If all implementations have agreed to this, why do you need such high-level approval?  Is someone still withholding consent and you need to break a logjam?  Is there some massive ripple that you want air-cover for?

2017-08-22 21:01 UTC, justinsb commented
PR has do-not-merge, yes.

2017-08-22 21:07 UTC, thockin commented
At risk of bikeshedding, shouldn't this say "node" somewhere?  `node.kubernetes.io/role` or `kubernetes.io/node-role` ?  Is that ship too far out to sea to fix?

@deads2k You have a hold on this.  Can you please update us on your position?

2017-08-22 21:21 UTC, justinsb commented
`node-role.kubernetes.io/master` and `node-role.kubernetes.io/node` are the current values :-)

If we were to change this again, it would break any manifest that include something targeted at the master.  I believe includes basically all networking providers, because most of them have a central agent.  Most of the installers changed this in 1.6, because taints & tolerations were moving from annotations to fields in a backwards incompatible manner from 1.5 -> 1.6, so every manifest needed changing anyway.

2017-08-22 21:24 UTC, thockin commented
LOL, sorry.  I got mixed up :)

I am LGTM on the naming.   I'd like @deads2k to ACK, but won't wait forever
:)

On Tue, Aug 22, 2017 at 2:22 PM, Justin Santa Barbara <
notifications@github.com> wrote:

> node-role.kubernetes.io/master and node-role.kubernetes.io/node are the
> current values :-)
>
> If we were to change this again, it would break any manifest that include
> something targeted at the master. I believe includes basically all
> networking providers, because most of them have a central agent. Most of
> the installers changed this in 1.6, because taints & tolerations were
> moving from annotations to fields in a backwards incompatible manner from
> 1.5 -> 1.6, so every manifest needed changing anyway.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-324155363>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVOZjohNmg9aWWcmozy80yRcQLPJ6ks5sa0Z_gaJpZM4LTgWX>
> .
>

2017-08-22 21:33 UTC, liggitt commented
> If we were to change this again, it would break any manifest that include something targeted at the master

manifests that target masters based on these labels are depending on something that is not part of the kubernetes API, is only set up by some installers, and is not (to my knowledge) actively added to old existing nodes that were created prior to these labels emerging as a concept.

I think it's good to figure out a pattern for labeling nodes by role. I think it's less good to make de facto API guarantees around specific role labels that are not actually set up by kubernetes, and without taking migration into consideration.

2017-08-23 12:21 UTC, deads2k commented
> I am LGTM on the naming.   I'd like @deads2k to ACK, but won't wait forever
> :)

What @liggitt said one comment up.

2017-08-23 14:56 UTC, luxas commented
> and without taking migration into consideration.

What migration do you envision should happen here? Everyone were forced to do this kind of for the v1.5->v1.6 upgrade anyway, where this label was standardized on.

> manifests that target masters based on these labels are depending on something that is not part of the kubernetes API

Which means we had A LOT of sprawl before this label. There is still some sprawl, but we want to minimize that with this effort.

> I think it's less good to make de facto API guarantees around specific role labels that are not actually set up by kubernetes

Remember that there are various 3rd party providers that implicitely rely on the behavior of the deployment. That is an API. If all or most deployments standardized on a common label, we could _actually_ promise something as a community and provide a sane set of known labels to the system available to consumers of both deployment (kubeadm, kops, kargo, GKE, tectonic, etc etc) and integrations on top of k8s (network providers, logging solutions, etc), we would not have the problem we were seeing with 10 different APIs.

I agree we shouldn't bloat core with anything. But this is an inofficial standard already, and the community would benefit of some clarity here.

We have a chance to tell others outside of the core maintaining group of k8s "this is a best practice, do this" instead of "do whatever you feel for, but it's definitely gonna break if you move provider".

We have _a lot_ of different Kubernetes providers [1]. Do you think it's productive to let each of them figure out a label of taste for their own? This kind of scenario leads to lock-in, and an endless battle for k8s consumers. Imagine a network provider's docs:

```
Please set up <product-here> depending on how you started your cluster:
1. <provider-1>: <link-to-provider-1-specific-yaml-installation-file-here>
2. <provider-2>: <link-to-provider-2-specific-yaml-installation-file-here>
...
75. <provider-75>: <link-to-provider-75-specific-yaml-installation-file-here>
...
```

To me, this sounds like not creating any RBAC rules at all by default, and just say "hey, come up with whatever roles you find useful".

We've passed the proposal stage already 6 months ago. Now it's actually implemented.
Can't we just get this as a best practice for k8s?

[1]: https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0

2017-08-23 15:28 UTC, liggitt commented
> What migration do you envision should happen here?

This is being positioned as something kubernetes users should rely on, without any accompanying API guarantees:
* these labels are not known to or added by any fundamental kubernetes components (apiserver/kubelet/controller-manager, etc)
* nothing monitors nodes to ensure these labels are maintained and readded if removed
* nothing ensures the old form of the label is migrated to the new form, or removed (or kept in sync with the new form)

> Remember that there are various 3rd party providers that implicitly rely on the behavior of the deployment. That is an API.

That is *not* an API. That characterization is exactly why we should be reluctant to start dictating labeling schemes.

> We have a lot of different Kubernetes providers. Do you think it's productive to let each of them figure out a label of taste for their own?

I don't think the answer is dictating label topology centrally. I'd rather see us make it trivial to shape any daemonset/deployment/replicaset's label selector and tolerations to let it deploy to any cluster's topology (e.g. `kubectl set selector`, `kubectl set tolerations`, etc).

The more opinionated kubernetes becomes about what labels must or must not be set on objects, the less flexible of a tool it becomes. Recommending a prefix for labels that indicate node role seems like a good balance, and can help people avoid the mistakes we made in the past with labeling approaches that would only allow a single role, etc.

2017-08-29 17:32 UTC, thockin commented
@liggitt I am not sure I grok your point about a prefix.

WRT this overall, there's a lot to digest.  If we expect people to depend on this, we need to centralized the definition of it.  That's sort of what this is, but are labels the best mechanism?  Labels are the only real "query" we have, expect a handful of special cases.  They are generally "optional" things, though we have examples in the form of the topological labels (hostname, zone, region) and probably others.  AFAIK nothing is re-setting those if they get removed (I could be wrong).  Those seem to be legitimately intrinsic properties, though - you can't really change which region you are in and still be the same node.  Role, on the other hand is not intrinsic - it is intentional.  It is a statement of someone's intentions for how the cluster should be used.

If we declare a *convention* around this topic, can people 100% rely on it?  Probably not. Is that good enough?  If not, do we think this needs to be more formal (a required label?  Eww) or less formal (nobody should rely on it)?

There's too much in this thread for anyone to reasonably absorb it.  Can someone please volunteer to summarize (in an even-handed way) the root problem statement, the current state of the proposal, and pros/cons of the arguments?  This is at risk of missing 1.8, and I'm tired of it lingering.  There's a concrete proposal (this PR) and some arguments against it, but there's no clear problem statement and no clear counter-proposals.

Sorry to make work.  Only so many hours in the day :)

2017-09-02 02:22 UTC, calebamiles commented
removing this from the 1.8 milestone, per https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-325737345

2018-01-03 20:11 UTC, timothysc commented
What's the plan for this PR?  I'm triaging a backlog and this looks to have stalled.

2018-01-18 15:49 UTC, timothysc commented
closing to prune backlog, please reopen should you deem otherwise.

2018-01-18 15:49 UTC, closed without merging

2018-10-29 13:46 UTC, andrewsykim commented
I agree with @liggitt and prefer that we don't place API guarentees on these labels. However, it seems there are already some uses cases of these labels that force us to reconsider putting _some_ guarentees on these labels. The first that comes to mind is how service controller [excludes nodes with the master label as part of a loadbalancers backend](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L596-L600). I think thise usecase in itself warrants some API guarentees. 

> The more opinionated kubernetes becomes about what labels must or must not be set on objects, the less flexible of a tool it becomes. Recommending a prefix for labels that indicate node role seems like a good balance, and can help people avoid the mistakes we made in the past with labeling approaches that would only allow a single role, etc.

It seems like today, we already have this as users can set `node-role.kubernetes.io/<any-role>` in which case I think a good middle ground is to only put API guarentees on the labels that are actively used in kubernetes core and prevent any other role labels from being added if possible. There's already a PR to do this [here](https://github.com/kubernetes/kubernetes/pull/69716), PTAL @liggitt @deads2k @thockin!

2018-10-29 13:49 UTC, liggitt commented
> The first that comes to mind is how service controller [excludes nodes with the master label as part of a loadbalancers backend](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L596-L600). I think thise usecase in itself warrants some API guarentees.

I think that code in particular should be removed. Without stronger guarantees around when that label is set, it is not appropriate for core code to rely on it.

2018-10-29 13:51 UTC, andrewsykim commented
@liggitt from code perspective I'm okay with that, but I'm not sure what the implications are for users. Would automatically allowing LB traffic to master nodes in v1.13 be fine? Also there's a similar discussion for this here https://github.com/kubernetes/kubernetes/issues/65618

2018-10-29 15:22 UTC, andrewsykim commented
I only see two paths from here: 

1) support _only_ existing labels that we are stuck supporting because there are lots of users depending on this behavior for things like loadbalancerse This means moving only _select_ role labels like `node-role.kubernetes.io/control-plane`, `node-role.kubernetes.io/master` and `node-role.kubernetes.io/node` into `pkg/apis/core`. We should prevent any more role labels being put into the core API unless absolutely necessary and even consider future deprecation. 

2) Start a deprecation process for the node labels now and push users to instead use the `alpha.service-controller.kubernetes.io/exclude-balancer` label (though this means this label should then be in the core APIs eventually?). Perhaps a deprecation process is not necessary here because there were no guarentees in the first place. 

I see the appeal for both and I would be okay with any of the two solutions we decide on. It seems @liggitt is advocating for 2), so unless anyone has strong opinions about going with 1), I'm okay with going foward with 2). I'm not sure we need a KEP here but I'm happy to put one together if we can't get consensus here :)

2018-10-29 16:04 UTC, justinsb commented
I think option 1 is the pragmatic choice - it acknowledges reality, and I'd suggest it helps get us to option 2.

For option 2 - I think we need to be sure we are building a full end-state - there's more than just services.  Two additional things that come to mind: users today want to target their masters, and users want to see their master nodes identified as such in kubectl (if they show up at all).   Also I think some CNI providers provide network isolation for pods on the master, so probably there's some additional network policy work.

I know that we have hypothesized a world where we don't have separate node roles, but we need useful clusters in the meantime.  Labels are serving that purpose today.

I have no objection to moving to something better, but I think we want a complete proposal so we can be see that where we are going is, in fact, better.

2018-10-30 13:51 UTC, andrewsykim commented
@justinsb good points :). I will try to get a KEP started on this then, if anyone else would like to work on this please ping me!