Improve error messages for ValidateObject method.
kubernetes/kubernetes pull request #39135
Opened 2016-12-22 07:42 UTC by xingzhou

Improved error messages for #ValidateObject method
in pkg/api/validation/schema.go.

Fixed #39110

2017-01-11 01:05 UTC, lavalamp commented
@k8s-bot ok to test

Sorry for delay, I was OOO. I think @mbohlool is best suited to review this.

2017-01-21 01:22 UTC, mbohlool commented on pkg/api/validation/schema.go
> +			return append(allErrs, fmt.Errorf("expected object '%s' of type 'map[string]interface{}', but the actual type is '%T'", fieldName, obj))
I tried to not be picky, but not sure what value those single quote characters adds. What appears between them does not have spaces and can be easily identified in the error message.

2017-01-21 01:25 UTC, mbohlool requested changes

2017-01-21 01:25 UTC, mbohlool commented on pkg/api/validation/schema.go
> +			allErrs = append(allErrs, fmt.Errorf("field '%s%s' is required, but not provided", fieldName, requiredKey))
A validation error "is required" implies "not provided".

2017-01-21 01:25 UTC, mbohlool commented on pkg/api/validation/schema.go
> +			return append(allErrs, fmt.Errorf("expected object '%s' of type 'map[string]interface{}', but the actual type is '%T'", fieldName, obj))
I tried to not be picky, but not sure what value those single quote characters adds. What appears between them does not have spaces and can be easily identified in the error message. ditto for the rest of the change.

2017-01-23 04:03 UTC, xingzhou commented
thanks @mbohlool for the review, have updated the code according to the comments, please take a look

2017-01-24 01:13 UTC, xingzhou commented
rebased

2017-01-24 10:17 UTC, mbohlool approved these changes

2017-01-26 00:10 UTC, xingzhou commented
@erictune, would you please help to review and approve this patch? thanks

2017-01-27 11:21 UTC, mbohlool approved these changes

2017-01-29 12:44 UTC, xingzhou commented
@k8s-bot bazel test this

2017-01-29 12:58 UTC, xingzhou commented
@k8s-bot bazel test this

2017-01-29 14:02 UTC, merged