optimize getPullSecretsForPod() and syncPod()
kubernetes/kubernetes pull request #39231
Opened 2016-12-26 11:48 UTC by NickrenREN

Since getPullSecretsForPod() will never return err,we do not need the second return value,and modify syncPod() function.
@feiskyer  @yujuhong  @caesarxuchao

2017-01-08 01:43 UTC, NickrenREN commented
@vishh  @caesarxuchao  Could you spend some time asking k8s-bot to test? Thanks

2017-01-08 02:14 UTC, NickrenREN commented on pkg/kubelet/kubelet.go
> +		glog.Warningf("Get no pull secrets for pod %q", format.Pod(pod))
getPullSecretsForPod() will never return error. and if len(pullSecrets) == 0,just print warning info not err

2017-01-20 01:28 UTC, NickrenREN commented
@vishh  Sorry to bother you. Do you have time to help with the review? Thanks

2017-01-31 13:41 UTC, NickrenREN commented
@k8s-bot ok to test

2017-01-31 14:10 UTC, k82cn commented
@k8s-bot ok to test

2017-01-31 15:43 UTC, NickrenREN commented
@k8s-bot kops aws e2e test this

2017-02-01 18:06 UTC, derekwaynecarr requested changes
remove the warning statement, its not necessary.

2017-02-01 18:06 UTC, derekwaynecarr commented on pkg/kubelet/kubelet.go
> +		glog.Warningf("Get no pull secrets for pod %q", format.Pod(pod))
why is it a warning at all?  the `getPullSecretsForPod` call already warns when a secret is not found.

2017-02-02 02:36 UTC, NickrenREN commented
Done Thanks

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39231#-:-KbwfN2o-ZiUCXdY7NsI:b5sp6v6)*
<!-- Sent from Reviewable.io -->

2017-02-02 07:46 UTC, NickrenREN commented
@derekwaynecarr  I have remove the warning log. PTAL

2017-02-07 04:38 UTC, NickrenREN commented
@k82cn @derekwaynecarr I have removed the warning log. PTAL

2017-02-09 09:39 UTC, k82cn approved these changes
LGTM :). thanks.

2017-02-20 06:03 UTC, NickrenREN commented
/release-note-none

2017-03-10 20:18 UTC, derekwaynecarr approved these changes

2017-03-10 20:20 UTC, derekwaynecarr commented
/lgtm
/approve

2017-03-10 23:49 UTC, k82cn commented
@k8s-bot gci gce e2e test this

2017-03-25 03:06 UTC, NickrenREN commented
/assign

2017-03-25 03:19 UTC, NickrenREN commented
Nothing was changed. I do not know why it needs rebase.
re-add  /lgtm  @derekwaynecarr

2017-03-25 03:21 UTC, NickrenREN commented
/lgtm

2017-03-25 05:56 UTC, NickrenREN commented
@k8s-bot cvm gce e2e test this

2017-03-27 01:53 UTC, NickrenREN commented
/assign @fejta

2017-03-27 05:19 UTC, fejta commented
/lgtm

2017-03-27 06:59 UTC, merged