Refactor the certificate and kubeconfig code in the kubeadm binary into two phases
kubernetes/kubernetes pull request #39280
Opened 2016-12-28 15:19 UTC by luxas

**What this PR does / why we need it**:

First stab at refactoring kubeadm code into logically independent phases.
This defines two phases in the kubeadm init process:
 - certs: Takes some API values as input (the API will be refactored in a later PR), and generates certificates in the pki directory
 - kubeconfig: Takes the pki directory and the endpoint where the master is located and produces two kubeconfig files: admin.conf and kubelet.conf

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Required long-term for graduating our API

**Special notes for your reviewer**:

### Old sample output
The earlier kubeconfig code had a bug in it; see this example:
_admin.conf:_
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <data>
    server: https://192.168.200.x:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: admin@kubernetes
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: <data>
    client-key-data: <data>
- name: kubelet
  user:
    client-certificate-data: <data>
    client-key-data: <data>
```
kubelet.conf:
```ỳaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <data>
    server: https://192.168.200.x:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: admin@kubernetes
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: <data>
    client-key-data: <data>
- name: kubelet
  user:
    client-certificate-data: <data>
    client-key-data: <data>
```
```console
$ shasum /etc/kubernetes/*.conf
2b22b25cc4c97e5619ece6c43badf42b87c4970a  /etc/kubernetes/admin.conf
2b22b25cc4c97e5619ece6c43badf42b87c4970a  /etc/kubernetes/kubelet.conf
```

#### New output
admin.conf
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <data>
    server: https://192.168.200.x:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: admin@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: <data>
    client-key-data: <data>
```
kubelet.conf
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <data>
    server: https://192.168.200.x:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet@kubernetes
current-context: kubelet@kubernetes
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate-data: <data>
    client-key-data: <data>
```

**Release note**:

```release-note
Refactor the certificate and kubeconfig code in the kubeadm binary into two phases
```

PTAL @dgoodwin @jbeda @mikedanese @errordeveloper @pipejakob @lukemarsden

2016-12-28 21:08 UTC, mikedanese commented on pkg/util/cert/io.go
> +	if len(file) == 0 {
This is a weird check. It doesn't seem necessary.

2016-12-28 21:10 UTC, mikedanese commented on cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
> +		return fmt.Errorf("couldn't read or parse the ca cert file %s: %v", caCertPath, err)
Do the err check separately so we don't print couldnt read file because: <nil>

2016-12-28 21:11 UTC, mikedanese commented on cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
> +		return fmt.Errorf("the CA private key file %s isn't in RSA format", caCertPath)
We support ecdsa everywhere but here?

2016-12-28 21:12 UTC, mikedanese commented on cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
> +	err = WriteKubeconfigToDisk(filepath, config)
just `return WriteKubeconfigToDisk(filepath, config)`

2016-12-29 12:34 UTC, luxas commented on cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
> +	err = WriteKubeconfigToDisk(filepath, config)
fixed

2016-12-29 12:35 UTC, luxas commented on cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
> +		return fmt.Errorf("the CA private key file %s isn't in RSA format", caCertPath)
added a TODO for this and a comment why it can't be supported right away
deferring to the future

2016-12-29 12:35 UTC, luxas commented on pkg/util/cert/io.go
> +	if len(file) == 0 {
fixed, I didn't understand why this was present in CertsFromFile from where I took it, removed now

2016-12-29 12:37 UTC, luxas commented on cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
> +		return fmt.Errorf("couldn't read or parse the ca cert file %s: %v", caCertPath, err)
will do

2016-12-29 13:28 UTC, luxas commented on cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
> +		return fmt.Errorf("couldn't read or parse the ca cert file %s: %v", caCertPath, err)
at a closer look, err will be non-nil if `len(caCerts) == 0` so that check didn't make sense

2016-12-29 20:31 UTC, luxas commented
@mikedanese Updated and comments fixed.
PTAL

Would be great if you could approve this so I can continue working on this refactoring job tomorrow and next week.

2016-12-29 20:45 UTC, luxas commented
Hmm, @mikedanese is the bazel build failing constantly now?

2016-12-29 21:31 UTC, luxas commented
Everything but bazel passed, please retest when you've got it working again

2017-01-03 16:57 UTC, pires requested changes
Overall LGTM.

2017-01-03 16:57 UTC, pires commented on cmd/kubeadm/app/cmd/init.go
> -
Why was this removed? Doesn't seem related to the PR title and description.

2017-01-03 16:57 UTC, pires commented on cmd/kubeadm/app/cmd/init.go
> +	client, err := kubemaster.CreateClientAndWaitForAPI(path.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, "admin.conf"))
Can we move filename to a constant?

2017-01-03 16:57 UTC, pires commented on cmd/kubeadm/app/cmd/join.go
> +	err = kubeconfigphase.WriteKubeconfigToDisk(path.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, "kubelet.conf"), cfg)
Can we move filename to a constant?

2017-01-03 17:30 UTC, mikedanese commented
@k8s-bot bazel test this

2017-01-03 17:33 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> -
This should have been done in an earlier PR, but it seems like it was missed.
This will and should only be doable from the API

2017-01-03 17:33 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> +	client, err := kubemaster.CreateClientAndWaitForAPI(path.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, "admin.conf"))
Will do in a follow up

2017-01-03 17:33 UTC, luxas commented on cmd/kubeadm/app/cmd/join.go
> +	err = kubeconfigphase.WriteKubeconfigToDisk(path.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, "kubelet.conf"), cfg)
Will do in a follow up

2017-01-03 17:37 UTC, mikedanese commented
What do you envision happening in cmd/kubeadm/phases/? Can you name some other functionalities that will move into a phases/ subfolder?

2017-01-03 18:15 UTC, pires commented
> What do you envision happening in cmd/kubeadm/phases/? Can you name some other functionalities that will move into a phases/ subfolder?

Are phases supposed to eventually be extracted to commands other binaries can re-use?

2017-01-03 18:15 UTC, luxas commented
@mikedanese I talked about this in the call today.
Basically these phases (copied from the meeting notes):

Identification of the kubeadm phases so that we can define an "API" (interface) (configfile + commandline) so that we can split kubeadm into separate independently-runnable phases, rough outline:
 - 1: Generating certificates
 - 2: Generating the admin.conf and the temporary kubelet.conf for bootstrapping the kubelet
 - 3: Bootstrapping the control plane
 - 4: API Configuration
 - 5: Discovery
 - 6: Create essential addons

This makes kubeadm ~support running the first two individually (but no CLI support added yet or API changes, that will come later)

Also see https://github.com/kubernetes/kubeadm/pull/100 once I have had time to write things there.

However, this is only the first PR in a series of a few for this to happen. This is just work for making it possible to run individual phases in the future, code changes that have to happen and cleanup generally in the codebase.

I would be grateful if you lgtm'd this now so I can move forward, right now I'm blocked on this.

2017-01-03 18:17 UTC, luxas commented
@pires Yes, this is the initial code that will make that possible.
Now the code in the codebase doesn't talk with each other back and forth, instead the code that does the individual phase is isolated in a package from the rest. It also makes the source more understandable long-term

2017-01-03 18:20 UTC, mikedanese commented on cmd/kubeadm/app/cmd/init.go
> +	client, err := kubemaster.CreateClientAndWaitForAPI(path.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, "admin.conf"))
Why not now? It seems like a small enough fix.

2017-01-03 18:20 UTC, mikedanese commented
This looks fine but I think you should just address @pires comments since they are so small.

2017-01-03 18:57 UTC, pires commented
@luxas great, you already have my LGTM.

2017-01-03 21:26 UTC, mikedanese commented
can you rebase and run gofmt and update-bazel

2017-01-03 21:42 UTC, luxas commented
Rebased, gofmt'd and bazel updated

2017-01-04 02:25 UTC, merged