Check if pathExists before performing Unmount
kubernetes/kubernetes pull request #39311
Opened 2016-12-29 22:50 UTC by rkouj

Unmount operation should not fail if path does not exist

2016-12-30 01:58 UTC, saad-ali requested changes
Also add the check to emptyDir itself

2016-12-30 02:16 UTC, rkouj commented
Ack

2016-12-30 02:41 UTC, rkouj commented
@k8s-bot unit test this

2016-12-30 02:41 UTC, rkouj commented
@k8s-bot cvm gke e2e test this

2016-12-30 03:03 UTC, rkouj commented
@saad-ali 
Added the check for empty_dir.

On second thoughts, please hold off on the review, I'll add changes to the remainder plugins in this PR itself.

2016-12-30 03:31 UTC, rkouj commented
@saad-ali PTAL

2017-01-04 02:20 UTC, saad-ali approved these changes

2017-01-04 02:20 UTC, saad-ali commented
/lgtm

2017-01-04 02:21 UTC, saad-ali commented
Can you make sure to cherry-pick this and https://github.com/kubernetes/kubernetes/pull/38547 to 1.5 and possibly 1.4

2017-01-04 23:11 UTC, rkouj commented
@k8s-bot aws e2e test this

2017-01-05 02:10 UTC, merged