add some specifications on the top command
kubernetes/kubernetes pull request #39359
Opened 2017-01-03 02:57 UTC by tianshapjq

**What this PR does / why we need it**:
the top command is available when heapster works fine on the server, but the specifications doesn't mention about this. So I added some specifications here.

2017-01-03 14:37 UTC, fabianofranz requested changes

2017-01-03 14:37 UTC, fabianofranz commented on pkg/kubectl/cmd/top.go
> +		This command is available only if the Heapster works fine on the server. `)
"This command requires Heapster to be correctly configured and working on the server."

2017-01-03 14:37 UTC, fabianofranz commented on pkg/kubectl/cmd/top.go
> +		Short: "Display Resource (CPU/Memory/Storage) usage, available only if Heapster works fine on the server.",
No need to mention it in the short description, long desc should be enough.

2017-01-04 01:32 UTC, tianshapjq commented on pkg/kubectl/cmd/top.go
> +		Short: "Display Resource (CPU/Memory/Storage) usage, available only if Heapster works fine on the server.",
ok, done :)

2017-01-04 14:47 UTC, fabianofranz commented
@k8s-bot ok to test

2017-01-04 14:47 UTC, fabianofranz approved these changes

2017-01-04 14:47 UTC, fabianofranz commented
@tianshapjq looks good, thanks!

2017-01-04 16:45 UTC, merged