log cfgzErr if err happened
kubernetes/kubernetes pull request #39370
Opened 2017-01-03 14:12 UTC by NickrenREN

We need to log err info when err info returned by initConfigz(),no matter what the result of utilconfig.DefaultFeatureGate.DynamicKubeletConfig() is and
whether s.RunOnce is true or not.
We should log the initKubeletConfigSync() err info too.

2017-01-07 04:23 UTC, NickrenREN commented
@mtaufen  Could you spend some time helping to ask k8s-bot to test and review ? Thanks

2017-01-10 17:24 UTC, mtaufen commented
Sure, I'll take a look at this right now. Just got to it after post-vacation catch-up.

2017-01-10 17:40 UTC, mtaufen requested changes

2017-01-10 17:40 UTC, mtaufen commented on cmd/kubelet/app/server.go
> +				glog.Warningf("failed to init kubelet configure sync : %v", err)
nit: can you reword this to `failed to init dynamic Kubelet configuration sync: %v`, and make it an error instead of a warning?

2017-01-10 17:40 UTC, mtaufen commented on cmd/kubelet/app/server.go
> +		} else if cfgzErr != nil {
This additional logging is not necessary. Errors during the configz setup are already logged by the `initConfigz` function. If the "unable to register configz" error is unclear, feel free to reword it.

2017-01-11 01:43 UTC, NickrenREN commented
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/kubelet/app/server.go, line 357 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39370#-K_Zf53G595hy_FDQ8fa-r1-357:-KaABIeDa1AClfV_iVJX:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/95f3a5b640c1b1730d879eef7fb034e7eb0efc91/cmd/kubelet/app/server.go#L357)):*
<details><summary><i>Previously, mtaufen (Michael Taufen) wrote…</i></summary><blockquote>

nit: can you reword this to `failed to init dynamic Kubelet configuration sync: %v`, and make it an error instead of a warning?
</blockquote></details>

Done.

---

*[cmd/kubelet/app/server.go, line 359 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39370#-K_Zf53G595hy_FDQ8fa-r1-359:-KaABJ4pg9gxF8oWt8Yn:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/95f3a5b640c1b1730d879eef7fb034e7eb0efc91/cmd/kubelet/app/server.go#L359)):*
<details><summary><i>Previously, mtaufen (Michael Taufen) wrote…</i></summary><blockquote>

This additional logging is not necessary. Errors during the configz setup are already logged by the `initConfigz` function. If the "unable to register configz" error is unclear, feel free to reword it. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39370)*
<!-- Sent from Reviewable.io -->

2017-01-11 01:44 UTC, NickrenREN commented
@mtaufen   Thanks for you review and advice. I have modified. PTAL

2017-01-14 01:32 UTC, mtaufen commented on cmd/kubelet/app/server.go
> +				glog.Errorf("failed to init dynamic Kubelet configuration sync : %v", err)
Thanks for the updates, snip the space between "sync" and ":" and I'll LGTM.

2017-01-14 09:10 UTC, NickrenREN commented
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/kubelet/app/server.go, line 360 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39370#-K_Zf53G595hy_FDQ8fa-r2-360:-KaRETdjFJEnACOpe7M5:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/66da1545ea99508646989a3128d105bab1ae2e02/cmd/kubelet/app/server.go#L360)):*
<details><summary><i>Previously, mtaufen (Michael Taufen) wrote…</i></summary><blockquote>

Thanks for the updates, snip the space between "sync" and ":" and I'll LGTM.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39370)*
<!-- Sent from Reviewable.io -->

2017-01-14 09:12 UTC, NickrenREN commented
@mtaufen  Thanks for you review. I have snipped the space. PTAL

2017-01-17 00:51 UTC, mtaufen approved these changes

2017-01-17 00:51 UTC, mtaufen commented
/lgtm

2017-01-17 00:52 UTC, mtaufen commented
Thanks for this work :)

2017-01-17 02:05 UTC, NickrenREN commented
@mtaufen  Sorry to bother you. Do you have time to help add  "release-note" label .  Thanks

2017-01-17 18:17 UTC, mtaufen commented
Sure thing.

2017-01-17 20:44 UTC, merged