refactor delete to remove cobra dependency
kubernetes/kubernetes pull request #39401
Opened 2017-01-04 03:19 UTC by AdoHe

FYI. As part of CLI Q1 roadmap, we would like to reduce the dependency of Cobra from actual commands implementations. In this PR, I tried to refactor delete command to achieve this. @kubernetes/sig-cli-misc a quick review is quite welcome, and I am just working on more PRs.

2017-01-05 16:10 UTC, AdoHe commented
@ymqytw I just notice this, bot is not smart enough.

2017-01-07 13:50 UTC, AdoHe commented
@kubernetes/sig-cli-misc could someone give a quick review? I would like to move this forward.

2017-01-10 01:00 UTC, fabianofranz requested changes
One minor nit otherwise LGTM.

2017-01-10 01:00 UTC, fabianofranz commented on pkg/kubectl/cmd/delete.go
> +	cmd.Flags().StringVarP(&options.Output, "output", "o", "", "Output mode. Use \"-o name\" for shorter output (resource/name).")
Can you add `AddOutputVarFlagsForMutation` for this, the same way you did `AddInclude3rdPartyVarFlags`?

2017-01-11 05:56 UTC, AdoHe commented on pkg/kubectl/cmd/delete.go
> +	cmd.Flags().StringVarP(&options.Output, "output", "o", "", "Output mode. Use \"-o name\" for shorter output (resource/name).")
sure.

2017-01-15 07:32 UTC, AdoHe commented on pkg/kubectl/cmd/delete.go
> +	cmd.Flags().StringVarP(&options.Output, "output", "o", "", "Output mode. Use \"-o name\" for shorter output (resource/name).")
Done. @fabianofranz could you please help review this PR? The bot just assign myself as the reviewer.

2017-01-15 09:50 UTC, AdoHe commented
@k8s-bot gci gce e2e test

2017-01-16 14:39 UTC, fabianofranz commented
@k8s-bot gci gce e2e test this

2017-01-16 18:23 UTC, fabianofranz approved these changes

2017-01-16 21:41 UTC, merged