[scheduling] Moved pod affinity and anti-affinity from annotations to api fields #25319
kubernetes/kubernetes pull request #39478
Opened 2017-01-05 19:11 UTC by rrati

Converted pod affinity and anti-affinity from annotations to api fields

Related: #25319
Related: #34508

**Release note**:
```Node affinity has moved from annotations to api fields in the pod spec.  Node affinity that is defined in the annotations will be ignored.```

2017-01-09 19:24 UTC, timothysc requested changes
We should really try to eliminate the forced additions.

2017-01-09 19:24 UTC, timothysc commented on pkg/api/validation/validation_test.go
> +				Containers:    []api.Container{{Name: "ctr", Image: "image", ImagePullPolicy: "IfNotPresent"}},
So I'm guessing this section is a copy<>paste of validPodSpec?  b/c it's repeated.

2017-01-09 19:24 UTC, timothysc commented on pkg/api/validation/validation_test.go
> +								TopologyKey: "",
Does this need to be here if unused?

2017-01-09 19:24 UTC, timothysc commented on pkg/api/validation/validation_test.go
> +								TopologyKey: "",
same comment re: empty string

2017-01-09 19:24 UTC, timothysc commented on pkg/api/validation/validation_test.go
> +									TopologyKey: "",
same comment re: empty strings.

2017-01-09 19:24 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/balanced_resource_allocation_test.go
> +		Affinity: &v1.Affinity{},
Why is this not omit_if_empty?  It seems like we're filling in blanks in a lot of locations. 

We don't do that with other fields.

2017-01-10 13:38 UTC, rrati commented on plugin/pkg/scheduler/algorithm/priorities/balanced_resource_allocation_test.go
> +		Affinity: &v1.Affinity{},
It is omit_empty.  Issue is in the scheduler and has been addressed.

2017-01-10 13:38 UTC, rrati commented on pkg/api/validation/validation_test.go
> +				Containers:    []api.Container{{Name: "ctr", Image: "image", ImagePullPolicy: "IfNotPresent"}},
Fixed

2017-01-10 13:53 UTC, rrati commented on pkg/api/validation/validation_test.go
> +								TopologyKey: "",
What empty string?

2017-01-10 13:54 UTC, rrati commented on pkg/api/validation/validation_test.go
> +								TopologyKey: "",
Original test has an empty value for topologyKey.  I would think it shouldn't matter if it is there and empty vs not there at all.  I will test and if there's no difference just remove it

2017-01-10 13:57 UTC, rrati commented on pkg/api/validation/validation_test.go
> +									TopologyKey: "",
Same reply.  Original had it so I kept it.  I will test with it removed and if same results will push update with it removed

2017-01-11 15:33 UTC, rrati commented
@k8s-bot bazel test this

2017-01-11 16:00 UTC, rrati commented
@k8s-bot unit test this

2017-01-11 16:51 UTC, rrati commented
@k8s-bot unit test this

2017-01-11 17:02 UTC, timothysc commented on plugin/pkg/admission/antiaffinity/admission_test.go
> +			/*
What's with the comment blob?

2017-01-11 17:02 UTC, timothysc commented on plugin/pkg/admission/antiaffinity/admission_test.go
> +			/*
same

2017-01-11 17:08 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/predicates/predicates_test.go
> +					/*
same.

2017-01-11 17:10 UTC, timothysc commented
@rrati only comments now are to remove the commented legacy blobs and get the tests fixed, then lgtm.  thx for the cleanup work, it looks a lot cleaner!

2017-01-11 17:14 UTC, rrati commented on plugin/pkg/admission/antiaffinity/admission_test.go
> +			/*
missed cleanup.  Removed

2017-01-11 17:14 UTC, rrati commented on plugin/pkg/admission/antiaffinity/admission_test.go
> +			/*
missed cleanup.  Removed

2017-01-11 17:15 UTC, rrati commented on plugin/pkg/scheduler/algorithm/predicates/predicates_test.go
> +					/*
Missed cleanup.  Removed

2017-01-11 22:31 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/predicates/predicates_test.go
> +					/*
still there and in a couple of other places.

2017-01-12 15:04 UTC, timothysc requested changes
2 main themes.. 
- Still more comment blocks. 
- Empty namespace args.

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/admission/antiaffinity/admission_test.go
> +								Namespaces:  []string{""},
Similar comment around name-spacing.  Why do we need to provide it if it's empty?  nil = default namespace right.

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/admission/antiaffinity/admission_test.go
> +							Namespaces:  []string{""},
same comment

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +						Namespaces:  []string{},
same comment.

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +						Namespaces:  []string{},
why do we need empty namespaces?  Need to check * LabelSelectors.

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go
> +	/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on test/e2e/scheduler_predicates.go
> +							Namespaces:  []string{},
empty namespace on label selector

2017-01-12 15:04 UTC, timothysc commented on test/e2e/scheduler_predicates.go
> +			/*
remove comment block

2017-01-12 15:04 UTC, timothysc commented on test/e2e/scheduler_predicates.go
> +			/*
remove comment block.

2017-01-12 15:04 UTC, timothysc commented on test/e2e/scheduler_predicates.go
> +			/*
remove comment block.

2017-01-12 15:04 UTC, timothysc commented on test/e2e/scheduler_predicates.go
> +			/*
same.

2017-01-12 15:04 UTC, timothysc commented on test/e2e/scheduler_predicates.go
> +			/*
same.

2017-01-12 15:04 UTC, timothysc commented on test/e2e/scheduler_predicates.go
> +		/*
same.

2017-01-12 16:20 UTC, rrati commented
@k8s-bot bazel test this

2017-01-12 20:00 UTC, timothysc approved these changes

2017-01-12 20:02 UTC, timothysc commented
needs rebase and re-test run (likely from me) :-/  

/lgtm

2017-01-12 23:06 UTC, merged