Upgrade Hazelcast example with the latest hazelcast-kubernetes-bootst…
kubernetes/kubernetes pull request #39580
Opened 2017-01-08 11:40 UTC by oscerd

…rapper 0.7.0, using Deployments instead of Replication Controller.

**What this PR does / why we need it**:
This PR upgrade the Hazelcast example in storage folder. It would be great to be aligned with the latest version of hazelcast-kubernetes-bootstrapper

2017-01-08 11:45 UTC, oscerd commented
I signed it

2017-01-28 22:47 UTC, thockin commented
@pires can you take a look?

2017-01-29 17:16 UTC, pires commented
@thockin I will first thing tomorrow.

@oscerd I'm about to release a new version, will ping you here when I release it tomorrow. Thanks for picking this!

2017-01-29 17:20 UTC, pires requested changes

2017-01-29 17:20 UTC, pires commented on examples/storage/hazelcast/README.md
"its set"

2017-01-29 17:20 UTC, pires commented on examples/storage/hazelcast/README.md
Where is "1 cpu core" requirement/limit defined?

2017-01-29 17:20 UTC, pires commented on examples/storage/hazelcast/image/Dockerfile
>  CMD java -jar /bootstrapper.jar
Why is the Dockerfile included if the image used here is from my quay.io repo?

2017-01-30 09:04 UTC, oscerd commented
@pires @thockin I'll update soon the PR and wait for the next release

2017-01-30 09:44 UTC, oscerd commented
PR updated.

2017-01-30 12:48 UTC, pires commented
@oscerd version 0.8.0 released and updated instructions.

2017-01-30 12:50 UTC, oscerd commented
I will align to 0.8.0

2017-01-30 13:02 UTC, oscerd commented
@pires @thockin it should be fine

2017-01-30 13:15 UTC, pires approved these changes
/lgtm

2017-01-30 13:16 UTC, pires commented
@thockin need you or someone to remove the release-note-label-needed label.

2017-01-30 13:17 UTC, pires commented
/approve

2017-01-31 03:28 UTC, thockin commented
/approve

On Mon, Jan 30, 2017 at 5:18 AM, Kubernetes Submit Queue <
notifications@github.com> wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> The following people have approved this PR: *pires*
>
> Needs approval from an approver in each of these OWNERS Files:
>
>    - *examples/OWNERS
>    <https://github.com/kubernetes/kubernetes/blob/master/examples/OWNERS>*
>
> We suggest the following people:
> cc @brendandburns <https://github.com/brendandburns>
> You can indicate your approval by writing /approve in a comment
> You can cancel your approval by writing /approve cancel in a comment
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/39580#issuecomment-276060130>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVMaHzn9e_wfbQaFSBgEWXV2TUJD3ks5rXeMUgaJpZM4Ldqy4>
> .
>

2017-01-31 08:01 UTC, pires commented
Will the bot ignore `release-note-label-needed`? /cc @apelisse

2017-02-01 07:09 UTC, thockin commented
@k8s-bot ok to test

2017-02-01 07:52 UTC, pires commented
@oscerd seems you have to add/update a test.

2017-02-01 09:06 UTC, oscerd commented
I hope now it's fine

2017-02-03 12:34 UTC, oscerd commented
We need just the lgtm label

2017-02-08 09:49 UTC, oscerd commented
Any news?

2017-02-08 10:01 UTC, pires commented
/lgtm

2017-02-08 12:09 UTC, oscerd commented
Not sure, but the test error doesn't look something related to this PR

2017-02-08 14:37 UTC, pires commented
@k8s-bot kops aws e2e test this

2017-02-08 21:52 UTC, oscerd commented
It's OK now

2017-02-08 22:14 UTC, merged

2017-02-10 23:47 UTC, yujuhong commented
The Hazelcast tests have been consistently failing since this PR was merged: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-examples/
Could you please check the failures? @oscerd @pires

2017-02-13 09:18 UTC, oscerd commented
The hazelcast e2e test is fixed with this PR: https://github.com/kubernetes/kubernetes/pull/41310