WIP: Do not list CronJob unmet starting times beyond deadline
kubernetes/kubernetes pull request #39608
Opened 2017-01-09 13:11 UTC by peay

**What this PR does / why we need it**:

See #36311. `getRecentUnmetScheduleTimes` gives up after 100 unmet times to avoid wasting too much CPU or memory generating all the times, as it generates them sequentially.

When concurrency is forbidden, this is conceptually un-necessary: we only need the last unmet start time. This suggests that when concurrency is forbidden, we could generate times by going backward in time from now. This is not very practical as CronJob currently relies on a package that only provides `Next` and no `Prev`. Hand-cooking a `Prev` does not seem like a good idea. I could submit a PR to the cron library to add a `Prev` method, and use that when concurrency is forbidden through something like `getLastUnmetScheduleTime`. This would be `O(1)` and there would be no limit involved.

cc @soltysh what do you think?

In the meantime, I would suggest to do something simple. Currently, the user has no way to configure anything to ensure that his CronJob will not get stuck if one job takes more that 100 unmet times.

 `getRecentUnmetScheduleTimes` starts with an initial time corresponding to the last start (or to the creation of the CronJob, if nothing has started yet). However, when `StartingDeadlineSeconds` is set, the controller will not start anything that is older than the deadline, so if the last start is way beyond the deadline, we are generating potentially lots of unmet start times that will not be considered by the scheduler for scheduling anyway.

Consider a job running every minute, where the last instance has taken 120 minutes. This means there are more than 100 unmet times when we start counting from the last start time.

**The PR makes `getRecentUnmetScheduleTimes` only consider times that do not fall beyond the deadline.** Here, the CronJob can be configured with a `StartingDeadlineSeconds` of, say, 10 minutes. After the 120min job has run, `getRecentUnmetScheduleTimes` will only consider the times in the last 10 minutes from now, and will not get stuck.

As a side note on the max. number of unmet times to use as limits in terms of CPU used by the controller: I have run a quick benchmark on my i7 mac. Schedules corresponding to "once a week" tend to be more expensive to generate unmet times for. Just FYI.

```
+--------------+---------------+--------------+
|   SCHEDULE   | MISSED STARTS |    TIMING    |
+--------------+---------------+--------------+
| */1 * * * ?  |           100 | 383.645µs    |
| */30 * * * ? |           100 | 354.765µs    |
| 30 1 * * ?   |           100 | 1.065124ms   |
| 30 1 * * 0   |           100 | 1.80034ms    |
| */1 * * * ?  |           500 | 1.341365ms   |
| */30 * * * ? |           500 | 1.814441ms   |
| 30 1 * * ?   |           500 | 8.475012ms   |
| 30 1 * * 0   |           500 | 10.020613ms  |
| */1 * * * ?  |          1000 | 2.551697ms   |
| */30 * * * ? |          1000 | 4.075813ms   |
| 30 1 * * ?   |          1000 | 17.674945ms  |
| 30 1 * * 0   |          1000 | 19.149324ms  |
| */1 * * * ?  |         10000 | 25.725531ms  |
| */30 * * * ? |         10000 | 87.520022ms  |
| 30 1 * * ?   |         10000 | 174.29216ms  |
| 30 1 * * 0   |         10000 | 196.565748ms |
+--------------+---------------+--------------+
```

using

```.go
package main

import (
    "fmt"
    "time"
    "os"
    "strconv"

    "github.com/robfig/cron"
    "github.com/olekukonko/tablewriter"
)

func timeSchedule(schedule string, iterations int) (time.Duration) {
    sched, err := cron.ParseStandard(schedule)

    if err != nil {
        panic(fmt.Sprintf("Unparseable schedule: %s", err))
    }

    start := time.Now()
    t := time.Now()

    for i := 1; i <= iterations; i++ {
        t = sched.Next(t)
    }

    return time.Since(start)
}

func main() {
    table := tablewriter.NewWriter(os.Stdout)
    table.SetHeader([]string{"Schedule", "Missed starts", "Timing"})

    schedules := []string{"*/1 * * * ?", "*/30 * * * ?", "30 1 * * ?", "30 1 * * 0"}
    iteration_nums := []int{100, 500, 1000, 10000}

    for _, iterations := range iteration_nums {
        for _, schedule := range schedules {
            table.Append([]string{schedule,
                                  strconv.Itoa(iterations),
                                  timeSchedule(schedule, iterations).String()})
        }
    }
    table.Render()
}
```

**Which issue this PR fixes**: fixes #36311

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-01-12 11:39 UTC, soltysh commented
@peay sorry for the long waiting time. I like your idea, esp. that we explicitly say that anything above `startingDeadlineSeconds` is considered as [failed](https://github.com/kubernetes/kubernetes/blob/1b6d17da24943225058d311898f28e4bd0e97b1d/pkg/apis/batch/v2alpha1/types.go#L239).

2017-01-12 11:41 UTC, soltysh requested changes

2017-01-12 11:41 UTC, soltysh commented on pkg/controller/cronjob/utils.go
> +	}
Can you prepare test cases covering this new flow?

2017-01-12 11:41 UTC, soltysh commented on pkg/controller/cronjob/utils.go
> +			return []time.Time{}, fmt.Errorf("Too many missed start times (decrease StartingDeadlineSeconds or check clock)")
If you're touching this I'd suggest something like:

```
Too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew.

2017-01-12 11:42 UTC, soltysh commented
@kubernetes/sig-apps-misc fyi

2017-01-12 13:35 UTC, peay commented on pkg/controller/cronjob/utils.go
> +	}
Yes, will do

2017-01-16 12:53 UTC, peay commented on pkg/controller/cronjob/utils.go
> +	}
I have updated the PR with tests.

2017-01-16 13:34 UTC, soltysh approved these changes

2017-01-16 13:34 UTC, soltysh commented
This LGTM, I've updated the title, to drop the WIP prefix.

@k8s-bot ok to test

2017-01-16 14:40 UTC, soltysh commented
@k8s-bot kubemark e2e test this

2017-01-17 07:07 UTC, soltysh commented
@k8s-bot kubemark e2e test this

2017-01-17 08:41 UTC, merged