move federation etcd to etcd3
kubernetes/kubernetes pull request #39646
Opened 2017-01-10 01:08 UTC by shashidharatd

**What this PR does / why we need it**: move federation etcd to etcd3

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #39594

**Special notes for your reviewer**: here is the [link](https://github.com/kubernetes/features/issues/44#issuecomment-270772674) to announcement making etcd3 as default

**Release note**:

```release-note
```

2017-01-10 02:12 UTC, shashidharatd commented
@madhusudancs @nikhiljindal please review this PR

2017-01-10 04:47 UTC, madhusudancs requested changes

2017-01-10 04:47 UTC, madhusudancs commented on federation/manifests/federation-apiserver-deployment.yaml
> +          - /usr/local/bin/etcd
I don't think this is sufficient. Federated Service is in beta, which means we need to provide an upgrade path. I think we should be doing what kubernetes is doing. See the manifest template here - https://github.com/kubernetes/kubernetes/blob/84df0679671e719971734be09e954c28f7febaf9/cluster/saltbase/salt/etcd/etcd.manifest#L42

2017-01-10 04:47 UTC, madhusudancs commented on federation/pkg/kubefed/init/init.go
> +								"/usr/local/bin/etcd",
Same as above.

2017-01-10 05:11 UTC, shashidharatd commented on federation/manifests/federation-apiserver-deployment.yaml
> +          - /usr/local/bin/etcd
So @madhusudancs, what is your suggestion for federation, we should make etcd3 as default, but still provide support for etcd2 or we should support etcd2 as default but optionally support etcd3?

2017-01-10 10:37 UTC, shashidharatd commented on federation/manifests/federation-apiserver-deployment.yaml
> +          - /usr/local/bin/etcd
@madhusudancs, I have made the federation-apiserver to use etcd2 as storage-backend.  going forward we need to migrate to etcd3 asap. also probably document the etcd migration procedure w.r.t federation.

2017-01-10 10:38 UTC, shashidharatd commented on federation/pkg/kubefed/init/init.go
> +								"/usr/local/bin/etcd",
updated the PR, just to solve the failing test cases for now. we need to migrate to etcd3 asap.

2017-01-10 18:49 UTC, madhusudancs commented on federation/manifests/federation-apiserver-deployment.yaml
> +          - /usr/local/bin/etcd
Fair enough, to get the tests passing. But I see that you made `etcd2` the default backend in `kubefed init`, but I don't see the corresponding change in this manifest. Our current test infra still uses this manifest. Shouldn't there be an equivalent change in this file?

2017-01-11 00:58 UTC, shashidharatd commented on federation/manifests/federation-apiserver-deployment.yaml
> +          - /usr/local/bin/etcd
@madhusudancs , the change is done in federation/manifests/federation-apiserver-deployment.yaml also.
The federation-apiserver now is called with `--storage-backend=etcd2` [here](https://github.com/kubernetes/kubernetes/pull/39646/files#diff-292011a5f785a3eb1dfc13fe070ab8ffR17) is the change.

2017-01-11 01:09 UTC, shashidharatd commented
@k8s-bot unit test this

2017-01-11 09:56 UTC, madhusudancs approved these changes
@shashidharatd thanks! LGTM!

Also, could you please update the issue about the work that still needs to be done?

2017-01-11 09:56 UTC, madhusudancs commented on federation/manifests/federation-apiserver-deployment.yaml
> +          - /usr/local/bin/etcd
Oh weird! I am only seeing it now.

2017-01-11 10:00 UTC, madhusudancs commented
I am adding `release-note-none` label here. I really think we should get the `etcd3` migration part done before v1.6 goes out and that should have a release note. There is no need to have one here since the one here will be superseded by the release note in the `etcd3` migration PR.

2017-01-11 16:00 UTC, merged