Add mulitpath support to iscsi plugin
kubernetes/kubernetes pull request #39928
Opened 2017-01-15 19:53 UTC by humblec

#issue https://github.com/kubernetes/kubernetes/issues/39345
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2017-01-15 19:57 UTC, humblec commented
@rootfs PTAL.  I havent updated the references ( `update-all.sh`)  in apis. Once this looks good, I will add it as a seperate commit.

2017-01-16 13:29 UTC, rootfs commented
@k8s-bot ok to test

2017-01-16 13:32 UTC, rootfs commented on pkg/api/types.go
> +	BackupPortal []string
inconsistent with those defined in `pkg/api/v1/types.go`

2017-01-17 04:59 UTC, humblec commented on pkg/api/types.go
> +	BackupPortal []string
done.

2017-01-17 17:41 UTC, rootfs commented
```
W0116 21:02:34.943] errors in package "k8s.io/kubernetes/pkg/generated/openapi":
W0116 21:02:34.944] output for "openapi/zz_generated.openapi.go" differs; first existing/expected diff: 
W0116 21:02:34.944]   "iqn\": {\n\t\t\t\t\t\tSchemaProps: spec.SchemaProps{\n\t\t\t\t\t\t\tDescription: \"Target iSCSI Qualified Name.\",\n\t\t\t"
W0116 21:02:34.944]   "backupPortal\": {\n\t\t\t\t\t\tSchemaProps: spec.SchemaProps{\n\t\t\t\t\t\t\tDescription: \"iSCSI target portal List."
W0116 21:02:34.944] 
W0116 21:02:34.975] make[1]: *** [verify_gen_openapi] Error 1
W0116 21:02:34.976] make: *** [verify_generated_files] Error 2
I0116 21:02:35.076] Makefile.generated_files:502: recipe for target 'verify_gen_openapi' failed
```

2017-01-17 17:42 UTC, rootfs commented on pkg/api/v1/types.go
> +	BackupPortal []string `json:"backupPortal" protobuf:"bytes,7,opt,name=backupPortal"`
reorder the new param

2017-01-17 17:48 UTC, rootfs requested changes

2017-01-17 17:48 UTC, rootfs commented on pkg/volume/iscsi/iscsi_util.go
> +	reqExist := false
you can skip this boolean by check if `len(devicePaths) > 0`

2017-01-17 17:48 UTC, rootfs commented on pkg/volume/iscsi/iscsi_util.go
> +			glog.Infof("iscsi: devicepath (%s) exist", devicePath)
glog.V(4)
exist -> exists

2017-01-17 17:48 UTC, rootfs commented on pkg/volume/iscsi/iscsi_util.go
> +	if !reqExist {
len(devicePaths) == 0

2017-01-17 17:48 UTC, rootfs commented on pkg/volume/iscsi/iscsi_util.go
> +		if path == "" {
why empty path exists?

2017-01-17 17:48 UTC, rootfs commented on pkg/volume/iscsi/iscsi_util.go
> +	devicePath = devicePaths[0]
if empty path exists, this is not safe!

2017-01-17 17:51 UTC, rootfs commented
this needs release note update too,

2017-01-18 11:59 UTC, humblec commented on pkg/volume/iscsi/iscsi_util.go
> +		if path == "" {
It wont or very very rare chance, that check is added while considering the scenario where admin logged out from one path in between our fetch and use of that path.

2017-01-18 12:03 UTC, humblec commented on pkg/volume/iscsi/iscsi_util.go
> +	devicePath = devicePaths[0]
devicePath array entry will not be empty. The devicepath would be  filled with a valid path in any case. It shouldnt be empty path as we are populating the array by validating the path.

2017-01-18 12:03 UTC, humblec commented on pkg/volume/iscsi/iscsi_util.go
> +	if !reqExist {
sure. Removed the flag.

2017-01-18 12:03 UTC, humblec commented on pkg/volume/iscsi/iscsi_util.go
> +			glog.Infof("iscsi: devicepath (%s) exist", devicePath)
Done.

2017-01-18 12:04 UTC, humblec commented on pkg/volume/iscsi/iscsi_util.go
> +	reqExist := false
Done.

2017-01-18 15:00 UTC, rootfs commented
have you run `hack/verify-openapi-spec.sh`

2017-01-19 02:02 UTC, tobad357 commented
Looking at the logic the iscsi implementation will always try the BackupPortal event if the primary Portal succeeds. This is something which I think is the best option, however if it always uses BackupPortal then it isn't really a Backup.

Wouldn't it be better to have a list for configurations which would be called Portals
If the user configures both Portal and Portals then just append Portal to Portals
Validation should be that either Portal or Portals has been configured

2017-01-19 12:53 UTC, humblec commented
@tobad357 Thanks for the comment. The implementation has been done by considering the suggestions made in issue # https://github.com/kubernetes/kubernetes/issues/21306 .  If everyone think for a different name than `backupportal`, I can definitely change it.

2017-01-19 13:28 UTC, tobad357 commented
@humblec When I wrote that issue my thinking was more in line with try the first portal and if it fails then try the backup. As it now is a list of portals and all will be used I vote to call the list "portals" and keep "portal" for backwards compatibility and ease of use

2017-01-19 16:09 UTC, humblec commented
@rootfs `hack/verify-openapi-spec.sh` gives error. Looking into it.

2017-01-23 20:26 UTC, rootfs commented
@k8s-bot verify test this

2017-01-23 21:13 UTC, humblec commented
Looks like now, `codecgen` is going wrong, checking

2017-01-24 12:32 UTC, humblec commented
@rootfs the ` ./hack/verify-bazel.sh` works fine at my end, however failing here. Not sure, what is missing.  do you have any pointer ?

2017-01-25 07:09 UTC, humblec commented
`upate-all.sh` and each individual verification scripts works perfectly in local copy. However it fails here.  

Also the errors on 'generated go files` looks really awkward to me.

~~~
W0124 16:50:10.657] cmd/kubernetes-discovery/pkg/apis/apiregistration/zz_generated.deepcopy.go:46: undefined: "k8s.io/kubernetes/pkg/conversion".Cloner
W0124 16:50:10.658] cmd/kubernetes-discovery/pkg/apis/apiregistration/zz_generated.deepcopy.go:61: undefined: "k8s.io/kubernetes/pkg/conversion".Cloner
W0124 16:50:10.658] cmd/kubernetes-discovery/pkg/apis/apiregistration/zz_generated.deepcopy.go:79: undefined: "k8s.io/kubernetes/pkg/conversion".Cloner
~~~

2017-01-25 13:23 UTC, humblec commented
@rootfs  Finallly all the tests are passed 👍 .  I am squashing the commits.

2017-01-25 14:01 UTC, rootfs commented
@k8s-bot test this

2017-01-25 14:11 UTC, rootfs commented
@humblec @tobad357 let use `portals` for the new API object. The logic is to make a string array, starting from `portal` and followed by those in `portals`. 

One thing I haven't figured out is that what if `portal` and new `portals` happen to map to different LUNs (vs. the same mpio LUN)? Is there any way to identify this misconfiguration?

2017-01-25 14:31 UTC, rootfs requested changes

2017-01-25 14:31 UTC, rootfs commented on pkg/api/v1/types.go
> +	// is other than default (typically TCP ports 860 and 3260).
`+optional`

2017-01-25 14:38 UTC, humblec commented
@rootfs @tobad357 sure. I can `s/backupPortal/portals` at user input side and keep the internal reference in the code as is.  
Regarding  multiportal with different lun numbers: our current volume spec has to be considered/projected  as a spec for single `IQN` with choices of having `>=1` portal and `single lun ` number, which is the most common method afaict.  As we login using the `IQN`, I feel  it should actually avoid  the misconfigurations.  If we want to support more combinations ( multiple portals with different lun numbers..etc) we have to really think about and get more details about the setups then consider a common solution. As per me, the further improvements  can be considered later after analysing different scenarios. Atleast multiple TP support looks to be an immediate ask from many users.

2017-01-25 14:40 UTC, rootfs commented
@humblec sounds good!

2017-01-25 14:42 UTC, humblec commented
Thanks @rootfs , I am replacing `backupPortal with portals`, will update the PR.

2017-01-25 19:32 UTC, humblec commented on pkg/api/v1/types.go
> +	// is other than default (typically TCP ports 860 and 3260).
Done.

2017-01-25 19:33 UTC, humblec commented
@rootfs  comments are addressed and  tests are passed. 👍

2017-01-26 21:50 UTC, rootfs commented
@humblec thanks! almost there, one last comment

2017-01-26 21:50 UTC, rootfs commented on pkg/volume/iscsi/iscsi.go
>  	portal  string
Since it is an array now, you can consolidate `portal` and `portals` into `portals`.

2017-01-28 04:42 UTC, humblec commented
@rootfs rebased and also addressed your  comment. The AWS failure looks to be spurious one. Can you please review/merge this?

2017-01-30 14:04 UTC, rootfs commented on federation/apis/swagger-spec/extensions_v1beta1.json
> +     "shortNames": {
where does this change come from?

2017-01-30 15:38 UTC, humblec commented on federation/apis/swagger-spec/extensions_v1beta1.json
> +     "shortNames": {
@rootfs looks to be from `update-federation-swagger-spec`.

2017-01-30 17:07 UTC, humblec commented
@rootfs once the change looks good, I will update the spec.

2017-01-30 17:57 UTC, rootfs commented on examples/volumes/iscsi/README.md
> +Once you have configured the iSCSI initiator, you can create a pod based on the example *iscsi.yaml*. In the pod YAML, you need to provide *targetPortal* (the iSCSI target's **IP** address and *port*
"more than one target portals"

2017-01-31 13:57 UTC, rootfs commented
/lgtm

2017-02-01 08:05 UTC, humblec commented
@childsb looks like this is not going to submit queue, do we need to trigger `@k8s-bot node e2e test this` ?

2017-02-01 08:47 UTC, humblec commented
@childsb looks like my last comment triggered the failed test and it has passed now. Is there any special flag ( `approved` )  required on this PR to get this merged?

2017-02-02 16:31 UTC, humblec commented
@k8s-bot gci gce e2e test this

2017-02-02 16:42 UTC, humblec commented
@rootfs can u restore LGTM and also do the needful for getting this merged ?

2017-02-02 18:40 UTC, rootfs commented
@humblec please rebase and i'll lgtm

2017-02-06 12:53 UTC, humblec commented
@rootfs rebased and tests are green. Can you please restore LGTM and provide `approved` flag ?

2017-02-06 14:17 UTC, rootfs commented
/lgtm

2017-02-09 10:44 UTC, humblec commented
@rootfs thanks! @childsb can you please put `approved` flag on this PR ?

2017-02-13 20:18 UTC, merged