add test for service controller sync
kubernetes/kubernetes pull request #39944
Opened 2017-01-16 11:12 UTC by NickrenREN

2017-01-31 13:38 UTC, NickrenREN commented
@k8s-bot ok to test

2017-02-01 18:11 UTC, derekwaynecarr requested changes
one minor nit to update.

2017-02-01 18:11 UTC, derekwaynecarr commented on pkg/controller/service/servicecontroller_test.go
> +	_, exsit := controller.cache.get(keyExpected)
nit: typo, should be exist

2017-02-02 02:33 UTC, NickrenREN commented
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/controller/service/servicecontroller_test.go, line 326 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39944#-KaayXzllzJgq9Xth0YC-r1-326:-KbweadA-V_z0_6kg2U1:bxoqmz4) ([raw file](https://github.com/kubernetes/kubernetes/blob/73fb34c431af80df33732627f436b70a58a64379/pkg/controller/service/servicecontroller_test.go#L326)):*
<details><summary><i>Previously, derekwaynecarr (Derek Carr) wrote…</i></summary><blockquote>

nit: typo, should be exist
</blockquote></details>

Done.  Thanks

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/39944)*
<!-- Sent from Reviewable.io -->

2017-02-02 02:38 UTC, NickrenREN commented
@k8s-bot unit test this

2017-02-02 05:36 UTC, NickrenREN commented
@k8s-bot unit test this

2017-02-02 08:18 UTC, NickrenREN commented on pkg/controller/service/servicecontroller_test.go
> +	_, exsit := controller.cache.get(keyExpected)
Oh, Thanks @derekwaynecarr . Modified

2017-02-07 04:36 UTC, NickrenREN commented
@derekwaynecarr  Sorry to bother you. Do you have time to review the test codes again? Thanks

2017-02-14 01:55 UTC, NickrenREN commented
@derekwaynecarr  @mikedanese  PTAL. Thanks a lot

2017-03-10 20:02 UTC, derekwaynecarr approved these changes

2017-03-10 20:02 UTC, derekwaynecarr commented
/lgtm
/approve

2017-03-10 20:17 UTC, derekwaynecarr commented
looks like bazel needs an update.

can you update and poke?

2017-03-13 02:39 UTC, NickrenREN commented
@k8s-bot unit test this

2017-03-13 03:21 UTC, NickrenREN commented
@derekwaynecarr  I have updated the codes and tested locally. Have no idea why unit test failed

root@nickren-ubuntu14:/home/nickren/GoProjects/src/k8s.io/kubernetes# make test WHAT=./pkg/controller/service/
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0313 10:39:10] Running tests without code coverage
ok      k8s.io/kubernetes/pkg/controller/service        0.064s

root@nickren-ubuntu14:/home/nickren/GoProjects/src/k8s.io/kubernetes# make test WHAT=./pkg/controller/service KUBE_GOFLAGS="-v" KUBE_TEST_ARGS='-run ^TestSyncService$'
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0313 11:13:19] Running tests without code coverage
=== RUN   TestSyncService
--- PASS: TestSyncService (0.00s)
PASS
ok      k8s.io/kubernetes/pkg/controller/service        0.066s

2017-03-13 03:46 UTC, NickrenREN commented
@k8s-bot unit test this

2017-03-13 05:28 UTC, NickrenREN commented
@derekwaynecarr Done. PTAL ,thanks in advance.

2017-03-25 03:31 UTC, NickrenREN commented
@derekwaynecarr  Done. PTAL. Thanks in advance

2017-03-28 17:50 UTC, mikedanese commented
/lgtm
/approve

2017-03-28 19:10 UTC, NickrenREN commented
@k8s-bot unit test this

2017-03-29 00:40 UTC, NickrenREN commented
@k8s-bot unit test this

2017-03-29 01:15 UTC, NickrenREN commented
@mikedanese  Thanks for your lgtm label. But Jenkins unit/integration failed. Rebase the codes. PTAL

2017-03-30 02:15 UTC, NickrenREN commented
@k8s-bot unit test this

2017-04-05 01:48 UTC, NickrenREN commented
@k8s-bot unit test this

2017-04-13 03:02 UTC, NickrenREN commented
@k8s-bot bazel test this

2017-04-13 04:12 UTC, NickrenREN commented
@k8s-bot bazel test this

2017-04-13 05:22 UTC, NickrenREN commented
ping @mikedanese  for approval

2017-04-17 23:00 UTC, mikedanese commented
@k8s-bot ok to test

2017-04-18 00:38 UTC, NickrenREN commented
@k8s-bot verify test this

2017-04-18 01:15 UTC, merged

2017-04-18 02:12 UTC, NickrenREN commented
Thanks @mikedanese