Improve code coverage for scheduler/algorithm/priorities
kubernetes/kubernetes pull request #39999
Opened 2017-01-17 09:12 UTC by tanshanshan

**What this PR does / why we need it**:

Improve code coverage for scheduler/algorithm/priorities from #39559 

This is my first unit test  for kubernetes , thanks for your review.

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-01-18 04:02 UTC, k82cn commented
@k8s-bot ok to test

2017-01-18 04:03 UTC, k82cn commented
@tanshanshan , please update BUILD file by `./hack/update-bazel.sh`.

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +	assert "github.com/stretchr/testify/assert"
Let's just use `t.Errorf` for now.
There's several discussion on whether introduce some UT libs, but please do not introduce it in a single PR.

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +		test   string
filed is not used?

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +		pMdata interface{}
let's use some meaningful words, e.g. `expected`.

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +
un-neccessary empty line.

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +			Containers: []v1.Container{
Add a case for no zero request of container.

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +
un-neccessary empty line.

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +Copyright 2016 The Kubernetes Authors.
s/2016/2017

2017-01-18 04:14 UTC, k82cn commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +	"k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache"
please run `gofmt -w -s`

2017-01-20 23:15 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/priorities/metadata_test.go
> +				affinity:       nil,
You should probably add an affinity check as well.

2017-01-20 23:18 UTC, timothysc requested changes
Please add a minor check on affinity too then lgtm

2017-01-23 03:29 UTC, timothysc commented
@tanshanshan looks like you will need to update your bazel files.  

run ./hack/update-bazel.sh

2017-01-23 06:38 UTC, tanshanshan commented
@timothysc 
I have run hack/update-bazel.sh , and update the plugin/pkg/scheduler/algorithm/priorities/BUILD

but , Jenkins Bazel Build failed.

2017-01-23 14:18 UTC, timothysc commented
@k8s-bot bazel test this

2017-01-23 14:26 UTC, k82cn commented
@tanshanshan , please fix the following error because of api-machinery refactor.

```
I0123 14:21:31.715] k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities/metadata_test.go:73: cannot use "k8s.io/kubernetes/pkg/api/v1".ObjectMeta literal (type "k8s.io/kubernetes/pkg/api/v1".ObjectMeta) as type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
I0123 14:21:31.722] k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities/metadata_test.go:90: cannot use "k8s.io/kubernetes/pkg/api/v1".ObjectMeta literal (type "k8s.io/kubernetes/pkg/api/v1".ObjectMeta) as type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
```

2017-01-26 22:28 UTC, timothysc approved these changes

2017-01-27 02:07 UTC, merged