Do not swallow error in asw.updateNodeStatusUpdateNeeded
kubernetes/kubernetes pull request #40126
Opened 2017-01-19 06:34 UTC by resouer

Fixes #39056

Bubble the error up to `SetNodeUpdateStatusNeeded` and log it out.

NOTE: This does not modify interface of `SetNodeUpdateStatusNeeded`

2017-01-19 19:00 UTC, rkouj requested changes
Thanks for taking up this issue and working on it!

Please add a unit test for the function that covers both the behaviors (returning error and nil) and address couple of minor comments.

2017-01-19 19:00 UTC, rkouj commented on pkg/controller/volume/attachdetach/cache/actual_state_of_world.go
> +		glog.Errorf("failed to update node status in actual world state: %v", err)
Please change the message to:

glog.Errorf("Failed to update statusUpdateNeeded field in actual state of world: %v", err)

2017-01-19 19:00 UTC, rkouj commented on pkg/controller/volume/attachdetach/cache/actual_state_of_world.go
> +			glog.Errorf("failed to update node status when getting volumes: %v", err)
Failed to update statusUpdateNeeded field when getting volumes

2017-01-19 19:00 UTC, rkouj commented on pkg/controller/volume/attachdetach/cache/actual_state_of_world.go
> +		return fmt.Errorf(
Let's log it here as well, we don't want to depend on the caller for logging.

2017-01-20 08:44 UTC, resouer commented
@rkouj Seems this method is not easy to test. It's a private method and its caller does not return value ...

2017-01-20 11:23 UTC, resouer commented
@k8s-bot gci gke e2e test this

2017-01-20 11:23 UTC, resouer commented
@k8s-bot cvm gke e2e test this

2017-01-20 14:37 UTC, rkouj commented
@resouer The method is still visible within the package and a test can be added to [asw_test](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/cache/actual_state_of_world_test.go)

You can create a test by creating a fake instance of asw, `fakeAsw := &asw{...}`
Then the fields inside the struct can be initialized by you. What needs to be taken care of is that both the code paths are tested (so we can vary the fields inside fakeAsw accordingly).

And the test for error case can be`if fakeAsw.updateNodeStatusUpdateNeeded(...) == nil { t.Fatalf(...) }`
and for the nil case can be `if fakeAsw.updateNodeStatusUpdateNeeded(...) != nil { t.Fatalf(...) }`

2017-01-22 15:17 UTC, resouer commented
@rkouj Thank you so much for your patient explanation. Just updated the test cases.

2017-01-23 02:12 UTC, resouer commented
@k8s-bot cvm gke e2e test this

2017-01-23 22:42 UTC, rkouj requested changes
One last comment.
Otherwise LGTM

cc @saad-ali to add the appropriate labels and sign-off once the comment has been addressed

2017-01-23 22:42 UTC, rkouj commented on pkg/controller/volume/attachdetach/cache/actual_state_of_world_test.go
> +	asw.updateNodeStatusUpdateNeeded(nodeName, false)
Please also check here that is should not return an error

2017-01-25 13:30 UTC, resouer commented on pkg/controller/volume/attachdetach/cache/actual_state_of_world_test.go
> +	asw.updateNodeStatusUpdateNeeded(nodeName, false)
ack, updated. Thanks.

2017-01-25 19:07 UTC, saad-ali commented
@jingxu97 made this change in https://github.com/kubernetes/kubernetes/pull/32807/files#diff-24ba5bb87df94b8b68b6fbd13ef972b0R444

I'd like to understand if it was intentional or not. And if it is safe to revert. @jingxu97 could you take a look please.

2017-01-25 19:16 UTC, saad-ali commented
Ah, looks like Jing's change was a bug that was fixed in https://github.com/kubernetes/kubernetes/pull/37727. We wanted to make the change in this PR, but punted on it (see https://github.com/kubernetes/kubernetes/pull/37727/files#r90370711), because truly bubbling up the error would require modifying `SetNodeStatusUpdateNeeded` (which this PR doesn't do either). So, this PR is fine as is. If you really want extra credit make sure that the error is not swallowed in `SetNodeStatusUpdateNeeded` (ok to do in follow up PR).

2017-01-25 19:16 UTC, saad-ali commented
/lgtm

2017-01-26 02:38 UTC, resouer commented
@saad-ali Thanks for bring them together. Yes, I avoided modify SetNodeStatusUpdateNeeded interface here, but since we just made the decision, I will send a follow up PR to solve the issue completely.

2017-01-26 13:07 UTC, resouer commented
@saad-ali Emm, it seems the new rule requrie approve label from your side

2017-01-27 09:34 UTC, merged