Set docker opt separator correctly for SELinux options
kubernetes/kubernetes pull request #40179
Opened 2017-01-19 21:42 UTC by pmorie

**What this PR does / why we need it**:

The current code for the security context provider uses a hard-coded `:` separator for the docker security options, while newer versions of docker require `=` for a separator.  There is code the apparmor and seccomp that sets the separator correctly based on the docker API version, but it is not applied to SELinux options.

**Which issue this PR fixes** 

fixes #37807

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-01-19 22:08 UTC, pweil- requested changes

2017-01-19 22:08 UTC, pweil- commented on pkg/securitycontext/provider.go
>  // of name:value
comment is now incorrect

2017-01-19 22:08 UTC, pweil- commented on pkg/kubelet/dockertools/docker_manager.go
> +func (dm *DockerManager) fmtDockerOpts(opts []dockerOpt) ([]string, error) {
make this also take the separator so we don't parse twice? (call to fmtDockerOpts and ModifyHostConfig are in the same method)

2017-01-19 22:08 UTC, pmorie commented on pkg/securitycontext/provider.go
>  // of name:value
Good catch

2017-01-19 22:08 UTC, pmorie commented on pkg/kubelet/dockertools/docker_manager.go
> +func (dm *DockerManager) fmtDockerOpts(opts []dockerOpt) ([]string, error) {
I can do that.

2017-01-19 22:48 UTC, spxtr commented
@k8s-bot test this
https://github.com/kubernetes/test-infra/issues/1598

2017-01-23 20:04 UTC, pmorie commented
@pweil- updated, PTAL

2017-01-23 20:08 UTC, pweil- approved these changes

2017-01-23 22:33 UTC, yujuhong commented
@Random-Liu could you take a look at this PR and also see if we can reuse it for dockershim? Thanks!

2017-01-23 23:10 UTC, Random-Liu commented
There seems to be something wrong:
```
event for pod-785acb44-e1ac-11e6-a2dd-0242ac110002: {kubelet e2e-gce-agent-pr-53-0-minion-group-xht2} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: Invalid --security-opt 2: \"label:level=s0\""
```

2017-01-24 02:47 UTC, pmorie commented
@yujuhong it's not necessary to do anythingmore for dockershim, unless we expect to support versions older than 1.11 (API version 1.23); dockershim is set to use the new delimiter currently.

2017-01-24 02:48 UTC, pmorie commented
Forgot to say, this is WIP.  I still have some testing to do.

2017-01-24 16:54 UTC, yujuhong commented
> @yujuhong it's not necessary to do anything more for dockershim unless we expect to support versions older than 1.11 (API version 1.23); dockershim is set to use the new delimiter currently.

Yes. We are going to decide whether we need to support docker 1.10 in CRI in the sig-node meeting.


BTW, @pmorie your WIP PR helped reliably reproduce a bug in docker for CRI... :-(  Thanks!

2017-01-24 19:32 UTC, pmorie commented
@yujuhong okay - I can port to dockershim in a follow-up if we decide to support it

> BTW, @pmorie your WIP PR helped reliably reproduce a bug in docker for CRI... :-( Thanks!

Anything I can do :)

2017-01-24 22:30 UTC, pmorie commented
Welp, I totally made this do the wrong thing.  Fixing now :)

2017-01-25 00:55 UTC, pmorie commented
cc @jessfraz

2017-01-25 00:55 UTC, pmorie commented
@dgoodwin PTAL - if you have some time I would appreciate you pulling this branch and seeing if this addresses your bug.

2017-01-25 01:26 UTC, jessfraz commented
this looks sane to me!

2017-01-25 02:52 UTC, feiskyer commented
This PR also closes #36136.

2017-01-25 13:34 UTC, pweil- commented on pkg/securitycontext/provider.go
> +// which are themselves key-value pairs.  For example, the
were you meaning to add more to this comment?

2017-01-25 16:16 UTC, pmorie commented on pkg/securitycontext/provider.go
> +// which are themselves key-value pairs.  For example, the
oops.

2017-01-25 16:18 UTC, pmorie commented on pkg/securitycontext/provider.go
> +// which are themselves key-value pairs.  For example, the
I moved it to another place and forgot to delete the remnants.

2017-01-25 19:20 UTC, dgoodwin commented
@pmorie might need some guidance on deploying the fix, is this isolated to the kubelet binary or do I need control plane components carrying parts of the fix? I tried recompiling kubelet and bringing the binary over to my test env but the problem still appears.

Docker 1.12, CentOS 7 in enforcing, kubeadm init makes it's static etcd manifest with spc_t specified, pod gets permission denied with scontext svirt_lxc_net_t (not spc_t as requested), and inspecting the container shows the mixed syntax for security opts:

```
           "SecurityOpt": [
                "seccomp=unconfined",
                "label:type:spc_t",
                "label=user:system_u",
                "label=role:system_r",
                "label=type:svirt_lxc_net_t",
                "label=level:s0:c803,c806"
            ],
```
Am I missing some components to get the fix deployed? I've also tried creating that pod with a "local-up-cluster" but that doesn't seem to like me specifying selinux options.

2017-01-25 21:40 UTC, yujuhong commented on pkg/kubelet/dockertools/docker_manager.go
> +	dockerApiVersion, err := dm.APIVersion()
Hmm...why not just use `checkDockerAPIVersion()`? It uses the cached api version and also provide logic to compare versions.

2017-01-25 21:40 UTC, yujuhong commented on pkg/kubelet/dockertools/docker_manager.go
> +		return ':', err
Why defaulting to the old separator?

2017-01-26 14:10 UTC, dgoodwin commented
I got a hack cluster up on F25 devel system and can confirm that the labeling now looks correct in security options:

```
            "SecurityOpt": [
                "seccomp=unconfined",
                "label=type:spc_t",
                "label=user:system_u",
                "label=role:system_r",
                "label=type:container_t",
                "label=level:s0:c239,c939"
            ],
```

This looks like it fixes the separator issue.

2017-01-26 15:09 UTC, eparis commented
But something is still wrong since we have both `type:container_t` and `type:spc_t` which is unpossible.

2017-01-26 15:26 UTC, dgoodwin commented
May explain why I'm still getting denials: 

```
type=AVC msg=audit(1485444109.058:607): avc:  denied  { create } for  pid=11534 comm="etcd" name=".touch" scontext=system_u:system_r:container_t:s0:c497,c629 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file permissive=0
```

@rhatdan @lsm5 @pmorie is this a separate bug?

The pod I'm creating to reproduce, which is just a lightly modified (don't use host network or ports) version of the kubeadm one: https://gist.githubusercontent.com/dgoodwin/1c19d2ad184ff792f786fec3cd137d0b/raw/beaaaa466b1073cacf4ec92f8ade9da28ad3233e/etcd.json

2017-01-26 15:51 UTC, jasonbrooks commented
@dgoodwin there'll soon be a newer container-selinux in updates-testing: https://bodhi.fedoraproject.org/updates/FEDORA-2017-10e18545ae

2017-01-26 16:13 UTC, rhatdan commented
There is a bug in kubeadm that is causing etcd to run as a confined container rather then as an spc_t container.

2017-01-26 16:38 UTC, dgoodwin commented
@jasonbrooks problem still occurring with that new container-selinux.

@rhatdan I do not agree that there is a kubeadm bug here, I'm not even using kubeadm in the above question, just creating a pod similar to how kubeadm would to expose the problem. The pod specifies spc_t: https://gist.githubusercontent.com/dgoodwin/1c19d2ad184ff792f786fec3cd137d0b/raw/beaaaa466b1073cacf4ec92f8ade9da28ad3233e/etcd.json

I think I need to open another issue, I suspect this could be the third selinux problem in a row. :(

2017-01-27 05:43 UTC, rhatdan commented
I guess this could be a docker issue, although I have no idea on how it is triggered.  Getting two TYPE fields into the security opt field.

2017-01-27 19:06 UTC, jessfraz commented
That might actually be a docker issue, I can check

On Thu, Jan 26, 2017 at 9:43 PM Daniel J Walsh <notifications@github.com>
wrote:

> I guess this could be a docker issue, although I have no idea on how it is
> triggered. Getting two TYPE fields into the security opt field.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/40179#issuecomment-275593431>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABYNbBjmdMS6fruGKrmykDINn_sS7DDyks5rWYP_gaJpZM4LopAH>
> .
>

2017-01-27 20:32 UTC, jessfraz commented
fwict there is no validation in docker for not applying more than one "type" label https://github.com/docker/docker/blob/50a72c7467ec92cb20b9ec72fd4de2d5e9761347/daemon/oci_linux.go#L759

2017-01-28 09:46 UTC, rhatdan commented
Yes we should block that.
It seems to be that 

func InitLabels(options []string) (processLabel string, mountLabel string, err error) {

is being called twice?

Or being called without passing in the security options?

2017-02-03 02:19 UTC, yujuhong commented
I posted a new PR #40903 since my previous PR moved a lot of code used by this one.

2017-02-06 22:49 UTC, yujuhong commented
Discussed with @pmorie on slack. Closing in favor of #40903.

2017-02-06 22:49 UTC, closed without merging