Create skeleton default config file
kubernetes/kubernetes pull request #40275
Opened 2017-01-22 17:06 UTC by rthallisey

Ref issue #38967

To make kubemark less provider specific, add a config-default.sh for the skeleton (external) provider.  The assumption is that the developer will use an existing vm(s) with a running kubernetes cluster to point kubemark at.

2017-01-22 18:22 UTC, rthallisey commented
cc @shyamjvs @timothysc

2017-01-22 18:30 UTC, spxtr commented
@k8s-bot ok to test

2017-01-23 14:59 UTC, timothysc requested changes
@rthallisey I don't see a problem with it, so long as we are not too hooked into kube_up scriptery.  

Ideally we would not use kube_up scriptery at all and could leverage against a cluster that has already been provisioned.

2017-01-23 14:59 UTC, timothysc commented on cluster/skeleton/config-default.sh
> +VM_USER="${VM_USER:-kubernetes}"
I don't think I would call this VM_USER

2017-01-23 14:59 UTC, timothysc commented
/cc @gmarek

2017-01-30 14:33 UTC, rthallisey commented
Going to come back to this once https://github.com/kubernetes/kubernetes/pull/40622 is merged.  This patch needs to use an 'external' provider and not the 'skeleton'. So it needs to be reworked.

2017-02-06 14:51 UTC, gmarek commented
@shyamjvs - can you take a look?

2017-02-16 22:42 UTC, rthallisey commented
Going to close this and revisit in another PR.

2017-02-16 22:42 UTC, closed without merging