[WIP] Use new conversions in patch
kubernetes/kubernetes pull request #40522
Opened 2017-01-26 15:20 UTC by wojtek-t

Ref #39017

2017-02-10 17:14 UTC, smarterclayton commented
And for reminder for others reviewing we said we would add something equivalent to the CACHE_MUTATION_DETECTOR that would verify both paths (when the env var is on) generate the same resulting struct and we would enable that in all the core CI tests but disable in kubemark.

2017-02-10 17:59 UTC, wojtek-t commented
@smarterclayton - yes sorry, I should have moved the comment here. It's basically still assigned to me, as this is one of the things that's not yet done.

2017-02-20 10:34 UTC, wojtek-t commented
@k8s-bot etcd3 test this, issue: #IGNORE (cluster didn't start)

2017-02-20 12:30 UTC, wojtek-t commented
@smarterclayton - this should be ready for review. PTAL

2017-02-21 13:53 UTC, wojtek-t commented
@k8s-bot bazel test this, issue: #IGNORE

2017-02-21 21:33 UTC, smarterclayton commented on staging/src/k8s.io/apimachinery/pkg/conversion/unstructured/converter.go
> +				if sv.Float() == math.Trunc(sv.Float()) {
Add a test case for this

2017-02-21 21:34 UTC, smarterclayton commented on staging/src/k8s.io/apimachinery/pkg/conversion/unstructured/converter.go
> +		glog.Errorf("Couldn't parse '%s' as bool for unstructured mismatch detection", key)
utilruntime.HandleError

2017-02-21 21:34 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				currentVersionedObject, err := convertor.ConvertToVersion(currentObject, gvk.GroupVersion())
You should pass `gvks` to ConvertToVersion

2017-02-21 21:35 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				currentVersionedObject, err := convertor.ConvertToVersion(currentObject, gvk.GroupVersion())
Is current object throwaway?  If it is, use UnsafeConvertToVersion

2017-02-21 21:36 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				originalMap, patchMap, err := strategicPatchObject(codec, currentVersionedObject, patchJS, versionedObjToUpdate, versionedObj)
Have you measured these changes?  It's entirely possible ConvertToVersion here and below loses all the benefits you got from the more efficient method

2017-02-21 21:37 UTC, smarterclayton requested changes
Some comments and questions

2017-02-22 08:58 UTC, wojtek-t reviewed
@smarterclayton - PTAL

2017-02-22 08:58 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				originalMap, patchMap, err := strategicPatchObject(codec, currentVersionedObject, patchJS, versionedObjToUpdate, versionedObj)
Even without unsafe conversion, the conversions should be pretty much the same what we have now.
Basically, the input/output objects here are unversioned. And the codec we are using is the "versioning" codec, which is also doing the conversion (the safe one) + marshaling/unmarshaling.

So if we change to unsafe (which unless I'm completely missing something we can do), this should be even better (+ the savings from more performant conversion to unstructured).

2017-02-22 08:58 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				currentVersionedObject, err := convertor.ConvertToVersion(currentObject, gvk.GroupVersion())
I don't understand how to pass gvks to it - it's a different type (it just doesn't compile for me).

Regarding UnsafeConvert - yes, this object is throwaway, but to do it:
- I would need access to runtime.Scheme (which I don't have now) or extend Convertor interface (both are not super easy)
- it shouldn't be worse that what we have now - see my comment below).

So I just dropped a TODO for it. I can work on it in a subsequent PR (though it probably won't hit 1.6).

2017-02-22 08:58 UTC, wojtek-t commented on staging/src/k8s.io/apimachinery/pkg/conversion/unstructured/converter.go
> +		glog.Errorf("Couldn't parse '%s' as bool for unstructured mismatch detection", key)
done

2017-02-22 08:58 UTC, wojtek-t commented on staging/src/k8s.io/apimachinery/pkg/conversion/unstructured/converter.go
> +				if sv.Float() == math.Trunc(sv.Float()) {
Done (unfortunately I should have done it explicitly, to force the map[string]interface{] to really contain float).

2017-02-22 09:27 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				originalMap, patchMap, err := strategicPatchObject(codec, currentVersionedObject, patchJS, versionedObjToUpdate, versionedObj)
It seems I was wrong and versioning Codec is using unsafe conversions...

2017-02-22 11:55 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				originalMap, patchMap, err := strategicPatchObject(codec, currentVersionedObject, patchJS, versionedObjToUpdate, versionedObj)
OK - so I managed to changed it to use unsafe conversions, which should pretty much be the same as before (when serializing/deserializing to json).

2017-02-22 12:49 UTC, wojtek-t commented
@k8s-bot gci gce test this, issue: #IGNORE

2017-02-22 19:09 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +			// However, to do that, we need to pass runtime.Scheme here.
We can pass an unsafe convertor in on the request.Scope.  But this is fine.

2017-02-22 19:10 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +			unversionedObjToUpdate, err := unsafeConvertor.ConvertToVersion(versionedObjToUpdate, gvk.GroupVersion())
Pass `gvks` here

2017-02-22 19:11 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +			currentVersionedObject, err := unsafeConvertor.ConvertToVersion(currentObject, gvk.GroupVersion())
Pass `gvks` here

2017-02-22 19:11 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				unversionedObjToUpdate, err := unsafeConvertor.ConvertToVersion(versionedObjToUpdate, gvk.GroupVersion())
`gvks`

2017-02-22 19:11 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				currentVersionedObject, err := unsafeConvertor.ConvertToVersion(currentObject, gvk.GroupVersion())
`gvks`

2017-02-22 19:23 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +			// However, to do that, we need to pass runtime.Scheme here.
Fixed in the next commit.

2017-02-22 19:23 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +			unversionedObjToUpdate, err := unsafeConvertor.ConvertToVersion(versionedObjToUpdate, gvk.GroupVersion())
I don't understand it - it doesn't compile for me.
[]GVK doesn't implement GroupVersioner.

2017-02-22 19:32 UTC, smarterclayton approved these changes

2017-02-22 19:33 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +			unversionedObjToUpdate, err := unsafeConvertor.ConvertToVersion(versionedObjToUpdate, gvk.GroupVersion())
Discussed offline - added TODO (in all places).

2017-02-22 19:35 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				currentVersionedObject, err := unsafeConvertor.ConvertToVersion(currentObject, gvk.GroupVersion())
Hrm, I was wrong - you need: `scope.Kind.GroupVersion()` here

2017-02-22 19:36 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				versionedObjToUpdate, err := creater.New(gvk)
scope.Kind

2017-02-22 19:36 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
> +				unversionedObjToUpdate, err := unsafeConvertor.ConvertToVersion(versionedObjToUpdate, gvk.GroupVersion())
Oops, this should be scope.Kind.GroupVersion()

2017-02-22 21:27 UTC, smarterclayton commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
> +	if err := unstructured.DefaultConverter.ToUnstructured(originalObject, &originalObjMap); err != nil {
I'd like the comment on this method to indicate that this expects a versioned object, not the internal object like it did before.  Also, no other callers in this package?

2017-02-23 08:09 UTC, wojtek-t commented on staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
> +	if err := unstructured.DefaultConverter.ToUnstructured(originalObject, &originalObjMap); err != nil {
Added comment. And yes - this is the only caller.

2017-02-23 09:10 UTC, wojtek-t commented
@smarterclayton - PTAL

2017-02-23 16:57 UTC, smarterclayton commented
/lgtm
/approve

2017-02-26 19:13 UTC, merged