pkg/kubelet/dockertools/docker_manager.go: removing unused stuff
kubernetes/kubernetes pull request #40527
Opened 2017-01-26 16:06 UTC by php-coder

**What this PR does / why we need it**:
This PR removes unused stuff (function, constants and variables). I checked that neither kubernetes nor openshift code aren't using them.

Let me know if you need to squash the commits (they're separated to simplify removing any of them).

**Release note**:
```release-note
NONE
```

2017-01-30 23:11 UTC, mtaufen requested changes

2017-01-30 23:11 UTC, mtaufen commented on pkg/kubelet/dockertools/docker_manager.go
> -	ErrNoPodInfraContainerInPod = errors.New("NoPodInfraContainerInPod")
@yujuhong ok to remove these error reasons, or were you planning on using them?
Seemed usage of `ErrNoContainersInPod` stopped in bb417e82d7e40bb94d1928a01e06b8d7b1e6fa00 -- `pkg/kubelet/dockertools/manager.go` and `ErrNoPodInfraContainerInPod` doesn't look like it was ever in use as far as I can tell (note I haven't searched back before the origin of `pkg/kubelet/dockertools/manager.go`).

2017-01-30 23:12 UTC, mtaufen commented
@php-coder If there is no release note, you can just omit that entire section from the initial comment.

2017-01-30 23:27 UTC, yujuhong commented on pkg/kubelet/dockertools/docker_manager.go
> -	ErrNoPodInfraContainerInPod = errors.New("NoPodInfraContainerInPod")
Don't think we are going to use them, especially now that we are transitioning to CRI. Most of the code in this package (especially those mentioning "infra container") will be deprecated eventually.

2017-01-31 11:43 UTC, php-coder commented on pkg/kubelet/dockertools/docker_manager.go
> -func PodInfraContainerEnv(env map[string]string) kubecontainer.Option {
Thanks for the info. I've removed this commit.

2017-01-31 13:54 UTC, mtaufen approved these changes

2017-01-31 13:55 UTC, mtaufen commented
/lgtm

Thanks for this work :)

2017-01-31 19:42 UTC, Random-Liu commented
/approve

2017-01-31 23:49 UTC, merged