Updating kubectl to send delete requests with orphanDependents=false if --cascade is true
kubernetes/kubernetes pull request #40576
Opened 2017-01-27 03:31 UTC by nikhiljindal

Ref https://github.com/kubernetes/kubernetes/issues/40568 #38897

Updating kubectl to always set `DeleteOptions.orphanDependents=false` when deleting a resource with `--cascade=true`.
This is primarily for federation where we want to use server side cascading deletion.

Impact on kubernetes: kubectl will do another GET after sending a DELETE and wait till the resource is actually deleted. This can have an impact if the resource has a finalizer. kubectl will wait till the finalizer is removed and then the resource is deleted, which is the right thing to do but a notable change in behavior.

cc @caesarxuchao @lavalamp @smarterclayton @kubernetes/sig-federation-pr-reviews @kubernetes/sig-cli-pr-reviews

2017-01-27 03:34 UTC, nikhiljindal commented
I am considering this a bug fix and hence am not adding any release notes.
I dont mind adding a release note if anyone thinks that it will help.

2017-01-27 03:38 UTC, liggitt commented
kubectl should not be doing any GETs for deletion unless required by a client side reaper when --cascade=true

2017-01-27 04:15 UTC, liggitt commented
Would this (for example) make namespace deletion block the CLI?

2017-01-27 04:17 UTC, liggitt commented
Similar issues raised in https://github.com/kubernetes/kubernetes/issues/1899

I'm not sure --cascade is the same thing as "wait for server-side finalizers"

2017-01-27 06:11 UTC, nikhiljindal commented
> kubectl should not be doing any GETs for deletion unless required by a client side reaper when --cascade=true

Doing a `GET` or not is an internal detail imo. What matters is what is the user expectation from `kubectl delete`. Does it guarantee that the resource was deleted if it returns success (without timing out)? If yes, then we need the GET request.

DeploymentReaper uses server side cascading deletion and waits for deployment to be deleted (does a `GET`) after issuing `DELETE` with `DeleteOptions.OrphanDependents=false`. I assume this is the pattern we will follow for other resources as we replace Reapers with server side cascading deletion.

2017-01-27 06:16 UTC, smarterclayton commented
A random point before i even look at the code - will a 1.5 server properly answer orphanDependencies=false in all cases?

2017-01-27 06:21 UTC, nikhiljindal commented
> Would this (for example) make namespace deletion block the CLI?

Yes. And I agree that we should not do that. I guess then we cannot say that kubectl guarantees that the resource is deleted when kubectl delete returns success.

2017-01-27 06:25 UTC, nikhiljindal commented
> A random point before i even look at the code - will a 1.5 server properly answer orphanDependencies=false in all cases?

What do you mean by "properly answers". It will ignore it for resources that do not implement ownerRef.

2017-01-27 08:17 UTC, nikhiljindal commented
> > Would this (for example) make namespace deletion block the CLI?
> 
> Yes. And I agree that breaks current user expectation and hence we should not do that. I guess then we cannot say that kubectl guarantees that the resource is deleted when kubectl delete returns success.

Based on this discussion, I can update the PR to remove the `GET` request at the end. Then the change will just be to send `DeleteOptions.orphanDependents=false`. Does that sound fine?

2017-01-30 19:34 UTC, nikhiljindal commented
Removed the change to wait after deletion.
Now the only change is to send `DeleteOptions.orphanDependents=false` when `--cascade=true`.
@liggitt @smarterclayton PTAL.

2017-01-30 19:57 UTC, liggitt commented
> A random point before i even look at the code - will a 1.5 server properly answer orphanDependencies=false in all cases?

did you test this against a 1.5 server with various resource types?

cc @caesarxuchao @deads2k any feedback on clients always sending this?

2017-01-31 06:30 UTC, nikhiljindal commented
@k8s-bot gce etcd3 e2e test this

2017-02-03 08:35 UTC, caesarxuchao commented on pkg/kubectl/cmd/delete.go
> +				return cascadingDeleteResource(info, out, shortOutput, mapper)
Is it only the federation resources that are missing reapers? Is it possible that users are relying on kubectl not cascading delete federation resources?

2017-02-03 23:07 UTC, nikhiljindal commented on pkg/kubectl/cmd/delete.go
> +				return cascadingDeleteResource(info, out, shortOutput, mapper)
> Is it only the federation resources that are missing reapers?

Kubernetes resources are also missing reapers for resources where there is nothing to reap (for ex: secrets, configmaps). In federation, we need to reap them from underlying clusters. This change should not have any impact on any kubernetes resource.

> Is it possible that users are relying on kubectl not cascading delete federation resources?

Cascading deletion should happen when users use `kubectl delete --cascading=true` with federation. Right now, it cascading deletes some resources (like namespaces, rs and deployments) and does not cascading deletes others resources (like secrets, configmaps). This is a bug that this PR fixes.

Default behavior is being discussed in https://github.com/kubernetes/kubernetes/issues/38897. The consensus seems to be to be consistent with kubernetes (i.e cascading delete by default).

2017-02-06 10:07 UTC, caesarxuchao commented on pkg/kubectl/cmd/delete.go
> +				return cascadingDeleteResource(info, out, shortOutput, mapper)
Thank you for the explanation. I don't have further questions. @liggitt @smarterclayton do you have more comments?

2017-02-08 17:46 UTC, nikhiljindal commented
cc @smarterclayton Can you please take a look?

2017-02-08 19:49 UTC, smarterclayton commented on pkg/kubectl/cmd/delete.go
> +				return cascadingDeleteResource(info, out, shortOutput, mapper)
We should probably be cascading even for things that have reapers (reaper is a client implementation of cascade, so the intent is to cascade).  Do all existing reapers cascade?  If no, they should also orphan: false.

2017-02-08 19:49 UTC, smarterclayton commented on pkg/kubectl/cmd/delete.go
> +func cascadingDeleteResource(info *resource.Info, out io.Writer, shortOutput bool, mapper meta.RESTMapper) error {
Add a test case.

2017-02-08 19:49 UTC, smarterclayton commented
Can you verify against 1.5 that kubectl still works?  Also, would like to see an e2e test that covers this now that we're fundamentally changing e2e.  With that and the comments above addressed I'd be ok with this change.

2017-02-08 19:50 UTC, smarterclayton requested changes
Comment

2017-02-09 00:28 UTC, nikhiljindal commented
>  Also, would like to see an e2e test that covers this now that we're fundamentally changing e2e

Sorry not sure what you are referring to in "now that we're fundamentally changing e2e". Can you please elaborate?
All existing kubectl tests (make test-cmd) that run `kubectl delete` execute this code path already.

2017-02-22 01:42 UTC, nikhiljindal commented on pkg/kubectl/cmd/delete.go
> +				return cascadingDeleteResource(info, out, shortOutput, mapper)
Done

2017-02-22 01:42 UTC, nikhiljindal commented on pkg/kubectl/cmd/delete.go
> +func cascadingDeleteResource(info *resource.Info, out io.Writer, shortOutput bool, mapper meta.RESTMapper) error {
Done

2017-02-22 01:44 UTC, nikhiljindal commented
Rebased and updated the PR as per comments.
Updated all reapers to set OrphanDependents=false and added a unit test.
Also verified that this works with 1.5 apiserver.

@smarterclayton PTAL.

2017-02-22 01:52 UTC, smarterclayton commented
> Also, would like to see an e2e test that covers this now that we're fundamentally changing e2e

Re test-cmd it doesn't stress GC in a meaningful way at least when I'm looking.  You're changing how GC works from client reaper, I'd like to see a test that passes before and after that ensures this change works as designed.

2017-02-22 06:38 UTC, nikhiljindal commented
@smarterclayton Pushed a new commit with more cascading deletion test cases for deployment and rs.
For non controllers (configmaps, secrets), we already have simple deletion tests.
Let me know if this is not what you were expecting.

2017-02-22 22:27 UTC, nikhiljindal commented
@k8s-bot unit test this
@k8s-bot verify test this

2017-02-23 20:05 UTC, nikhiljindal commented
Fixed the failing unit test and rebased.
@smarterclayton Can I have LGTM and approval?

2017-02-23 20:20 UTC, smarterclayton commented
/approve
/lgtm

thanks, tests are good

2017-02-23 21:27 UTC, nikhiljindal commented
@k8s-bot kubemark e2e test this
@k8s-bot kops aws e2e test this
@k8s-bot node e2e test this
@k8s-bot gce e2e test this
@k8s-bot gce etcd3 e2e test this

2017-02-26 20:58 UTC, merged