Optionally avoid evicting critical pods in kubelet
kubernetes/kubernetes pull request #40655
Opened 2017-01-28 23:05 UTC by vishh

For #40573

2017-01-31 15:52 UTC, derekwaynecarr commented
I would like to review this PR prior to its merging.

2017-01-31 17:38 UTC, mikedanese commented
/approve

2017-02-01 17:50 UTC, derekwaynecarr requested changes
one question, and a nit

2017-02-01 17:50 UTC, derekwaynecarr commented on pkg/features/kube_features.go
> +	// Ensures guaranteed scheduling of pods marked with a special pod annotation `scheduler.alpha.kubernetes.io/critical-pod`
i would also clarify here that its restricted to the kube-system namespace.

2017-02-02 17:34 UTC, vishh commented on pkg/kubelet/eviction/eviction_manager.go
> +		if notBestEffort {
Yeah. I don't think it makes sense to run "Critical" BestEffort pods

2017-02-02 17:34 UTC, vishh commented on pkg/features/kube_features.go
> +	// Ensures guaranteed scheduling of pods marked with a special pod annotation `scheduler.alpha.kubernetes.io/critical-pod`
Ack. I will add the additional comments.

2017-02-02 18:28 UTC, vishh commented on pkg/features/kube_features.go
> +	// Ensures guaranteed scheduling of pods marked with a special pod annotation `scheduler.alpha.kubernetes.io/critical-pod`
Done

2017-02-02 21:10 UTC, eparis commented
/approve

2017-02-03 19:48 UTC, derekwaynecarr approved these changes

2017-02-03 19:48 UTC, derekwaynecarr commented
/lgtm

2017-02-03 20:06 UTC, vishh commented
@dchen1107 has some concerns with this PR being cherrypicked. She is yet to post her concerns. For that reason, I have removed the cherrypick request label for now.
This PR is ready to go otherwise.

2017-02-03 23:40 UTC, dchen1107 commented
Like what we discussed offline, I am ok to have this to HEAD, and it is what we discussed offline. @dashpole is going to have some simple preemption logic in Kubelet for 1.6 to cover the rest. Letting Kubelet do some preemption is the direction I tried to push forward, and luckily we reached the agreement now. 

But I am concerned to cherrypick it to either 1.4 or 1.5 branch unless we made some other changes too:

* This one avoid evicting critical pods, no matter which is static or not. This is good. But fluentd is not marked as critical pod yet and running as static pod too. In this case, it might be evicted, and Kubelet never admit it again. You might have to mark fluentd as critical for now to workaround this issue.

* You revert the commit of kube-proxy oom score change. kube-proxy is running as burstable. Without proper preemption logic, it might become the victim by system OOM on the overloaded node all the time. One can argue that before we have the system OOM, the eviction manager can evict some other non-critical pods to prevent such situations. But there are two caveats:

  * We know we disabled on-demand memory notification for 1.5 by default. Without that feature, system OOM will be triggered a lot before the eviction manager can take any action. 
  * Scheduler might pack critical pods to the same node. With your changes, the eviction manager is effectively disabled, thus, kube-proxy might become the victim here. 

I suggested you only cherrypick the feature-gate flag pieces to 1.4 and 1.5. Actually that is what we agreed upon if I remembered it correctly. Or you can either

* Mark fluentd as critical one or
* cherrypick to-be-done preemption handling to 1.4 and 1.5. But I think that would be too risk here. 

cc/ @bprashanth @thockin @kubernetes/sig-network-bugs

2017-02-04 00:22 UTC, merged

2017-02-06 19:43 UTC, vishh commented
@dchen1107 

> Mark fluentd as critical one 

Thanks for this tip. I will update fluentd too.

> You revert the commit of kube-proxy oom score change. kube-proxy is running as burstable. Without proper preemption logic, it might become the victim by system OOM on the overloaded node all the time. One can argue that before we have the system OOM

I don't think system OOMs should be an issue because kube-proxy container will get restarted. Only evictions are terminal.

> We know we disabled on-demand memory notification for 1.5 by default. Without that feature, system OOM will be triggered a lot before the eviction manager can take any action.

This is true. But, I'm hoping that kube-proxy does not consume too much above its request. If it does, we should bump its request.

> Scheduler might pack critical pods to the same node. With your changes, the eviction manager is effectively disabled, thus, kube-proxy might become the victim here.

Can you explain a bit more? We might have issues with admission, which we agreed is a `known issue` and we do not intend to fix until we have preemptions. IIUC `Kube-proxy` will never be evicted once admitted and so I don't see any issue.

2017-02-06 23:28 UTC, vishh commented
I chatted with @bprashanth and cherry-picking this change without preemptions into v1.5 & has the following issues:
1. It makes dashboard, heapster, kube-dns, etc. unevictable. We are not sure if pods other can kube-proxy can be trusted as of now.
2. System OOMs leading to crash loop backoff - System OOMs cannot be reliably avoided using oom score adjust setting unless we disable system OOMs all together for critical pods. This is dangerous because critical pods can also have memory leak bugs

If we include preemptions, then `1` will no longer be an issue, but `2` will continue to remain an issue. We need to solve `2` in v1.6.
I'm inclined towards not meddling with oom score adjust, which is known to be unreliable, and instead reduce max backoff for crash looping critical pods. 

As for v1.5 and v1.4, the easiest option is to flag gate all the changes that were made to protect kube-proxy using a separate flag. Cherrypicking all the new features is more risky when compared to just adding a flag.