Move TryStartKubelet after is being configured
kubernetes/kubernetes pull request #40716
Opened 2017-01-31 00:31 UTC by GheRivero

**What this PR does / why we need it**: kubeadm tries to start the kubelet service in the preflight phase before writing is configuration

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```NONE
```

2017-01-31 15:55 UTC, dgoodwin approved these changes

2017-02-01 10:35 UTC, pires requested changes

2017-02-01 10:35 UTC, pires commented on cmd/kubeadm/app/preflight/checks.go
>  		}
This change doesn't make sense to me.

And honestly, this function doesn't even belong here. @luxas where can we move this? `utils/kubelet`? We can have a check here that returns an error but not kubelet or any other binary/service execution code.

2017-02-01 11:31 UTC, GheRivero commented
After some thinking, this change is more aesthetic than functional. Kubeadm starts the kubelet service before configuring it. It will fail because it's called with "--require-kubeconfig=true", and systemd will try to respawn it forever every 10 sec. Eventually, kubeadm will place the configuration file and kubelet will start properly. So the idea is to move the "start kubelet" out of the preflight phase, and place it just after the service is properly configured.

2017-02-01 11:38 UTC, pires commented
@GheRivero correct and correct.

2017-02-02 11:07 UTC, pires commented
@GheRivero after checks are green, please squash your commits and I'll approve.

2017-02-02 11:07 UTC, pires approved these changes

2017-02-02 13:44 UTC, luxas reviewed
Thanks for this PR!

Hmm, I'm not sure I like the ordering of the function calls change... Why not do this in the beginning so it's visible if it fails? I actually think of it as a kind of preflight check; check if kubelet is enabled and try to take action if not.

The kubelet is in the crashloop anyway, so it doesn't matter when we try to start it. In most cases, kubelet should be running before kubeadm init is executed, this was just something that was implemented as a convenience thing because one often forgots to start it.

What's the motivation for changing the order given the kubelet is crashlooping in any case?
I'm ok with moving this to the util package though.

2017-02-02 13:44 UTC, luxas commented on cmd/kubeadm/app/util/kubelet.go
> +Copyright 2016 The Kubernetes Authors.
2017

2017-02-02 16:10 UTC, GheRivero commented
The change of the order of functions call is mostly aesthetic, and to keep the host as clean as possible. It's true that kubelet is crashlooping in any case, but if there are some errors in kubeadm (I'm just facing one: failed to request signed certificate ....) kubelet will be continuously restarting. The impact on the hosts is really small (some log lines every 10 sec... forever) but is not really a best practice.

2017-02-07 08:55 UTC, pires commented
@GheRivero after checks are green, please squash your commits and I'll approve.

2017-02-07 09:03 UTC, GheRivero commented
@minikube-bot OK to test

2017-02-27 15:50 UTC, pires commented
/lgtm

2017-03-15 12:21 UTC, mikedanese commented
/approve

2017-03-16 13:08 UTC, pires commented
@GheRivero rebase please. This has been LGTM'ed before 1.6 so I believe it should be merged.

2017-04-28 17:46 UTC, closed without merging