Upgrade test for deployments
kubernetes/kubernetes pull request #40854
Opened 2017-02-02 10:51 UTC by kargakis

Upgrade test for Deployments. Should prevent issues like https://github.com/kubernetes/kubernetes/issues/40415 in the future.

@krousey @janetkuo @soltysh 

Haven't managed to run it locally... 
```
$ go run hack/e2e.go  --up --test --test_args="--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci"
2017/02/02 11:43:22 e2e.go:946: Running: ./hack/e2e-internal/e2e-down.sh
2017/02/02 11:43:22 e2e.go:948: Step './hack/e2e-internal/e2e-down.sh' finished in 7.278236ms
2017/02/02 11:43:22 e2e.go:946: Running: ./hack/e2e-internal/e2e-up.sh
2017/02/02 11:43:22 e2e.go:948: Step './hack/e2e-internal/e2e-up.sh' finished in 5.286328ms
2017/02/02 11:43:22 e2e.go:946: Running: ./cluster/kubectl.sh version --match-server-version=false
2017/02/02 11:43:22 e2e.go:948: Step './cluster/kubectl.sh version --match-server-version=false' finished in 213.847259ms
2017/02/02 11:43:22 e2e.go:946: Running: ./hack/e2e-internal/e2e-status.sh
2017/02/02 11:43:22 e2e.go:948: Step './hack/e2e-internal/e2e-status.sh' finished in 103.253183ms
2017/02/02 11:43:22 e2e.go:230: Something went wrong: encountered 2 errors: [exit status 1 exit status 1]
exit status 1
```

@krousey any eta for when the upgrade framework will be integrated in the pr builder?

2017-02-02 15:17 UTC, kargakis commented
@k8s-bot unit test this issue: https://github.com/kubernetes/kubernetes/issues/37982

2017-02-02 19:14 UTC, krousey commented
@kargakis I can start putting one together, but unfortunately I won't be able to turn it on until https://github.com/kubernetes/kubernetes/issues/40110 is fixed.

2017-02-03 02:30 UTC, kargakis commented
@krousey it would be great to have it before 1.6 is released.

2017-02-03 17:56 UTC, krousey commented
@kargakis It will be. That bug would constitute a release blocker anyway... so it won't be a permanent barrier.

2017-02-08 22:35 UTC, krousey commented
/lgtm

@kargakis Sorry I've been out for a while. I ran this locally and it works.

2017-02-08 23:31 UTC, janetkuo requested changes

2017-02-08 23:31 UTC, janetkuo commented on test/e2e/upgrades/deployments.go
> +// Test runs a connectivity check to the service.
This comment needs to be updated

2017-02-09 10:19 UTC, kargakis commented on test/e2e/upgrades/deployments.go
> +// Test runs a connectivity check to the service.
updated

2017-02-09 10:20 UTC, kargakis commented
Updated with @janetkuo's comment, reapplying lgtm

2017-02-09 18:50 UTC, janetkuo approved these changes

2017-02-09 18:50 UTC, janetkuo commented
/lgtm

2017-02-09 18:51 UTC, janetkuo commented
@k8s-bot verify test this

2017-02-09 18:51 UTC, janetkuo commented
/lgtm

2017-02-10 01:41 UTC, merged