kubeadm: added tests cert/pkiutil pkg
kubernetes/kubernetes pull request #40888
Opened 2017-02-02 22:07 UTC by dmmcquay

raised coverage from ~37% to ~77%

**What this PR does / why we need it**: added tests to cert/pkiutil pkg and raised coverage from ~37% to ~77%

Adding unit tests is a WIP from #34136

**Special notes for your reviewer**: /cc @luxas @pires 

**Release note**:
```release-note
NONE
```

2017-02-06 16:24 UTC, dmmcquay commented
@mikedanese mind reviewing this PR?

2017-02-06 16:39 UTC, pires requested changes

2017-02-06 16:39 UTC, pires commented on cmd/kubeadm/app/phases/certs/pkiutil/pki_helpers_test.go
> +	defer os.Remove(tmpdir)
Use `os.RemoveAll`.

2017-02-06 16:39 UTC, pires commented on cmd/kubeadm/app/phases/certs/pkiutil/pki_helpers_test.go
> +	defer os.Remove(tmpdir)
Use `os.RemoveAll`.

2017-02-06 21:01 UTC, luxas commented
I let @pires once he's happy with this

/approve

2017-02-06 21:24 UTC, dmmcquay commented
@pires can I get your lgtm for this?

2017-02-07 08:27 UTC, pires commented
@dmmcquay please squash.

2017-02-07 17:26 UTC, pires commented
@k8s-bot cvm gce e2e test this

2017-02-07 18:36 UTC, pires commented
/lgtm

2017-02-08 07:06 UTC, merged