add an nrpe-external-master relation to the kubernetes-worker and kubernetes-master charms
kubernetes/kubernetes pull request #40897
Opened 2017-02-02 23:48 UTC by axinojolais

**What this PR does / why we need it**:
This PR adds an an nrpe-external-master relation to the kubernetes-worker and kubernetes-master charms. This is needed to monitor the state of the workers and the masters via Nagios.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Original PR at https://github.com/juju-solutions/kubernetes/pull/102

**Release note**:

```
The kubernetes-master and kubernetes-worker charms have gained an nrpe-external-master relation, allowing the integration of their monitoring in an external Nagios server.
```

2017-02-03 00:09 UTC, axinojolais commented
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/165

2017-02-03 11:36 UTC, marcoceppi requested changes

2017-02-03 11:36 UTC, marcoceppi commented on cluster/juju/layers/kubernetes-worker/layer.yaml
> +  - 'interface:nrpe-external-master'
These explicit calls aren't needed as they are included in `layer:nagios` (which we should rename to `layer:external-nagios`, tbh.

2017-02-03 13:31 UTC, axinojolais commented on cluster/juju/layers/kubernetes-worker/layer.yaml
> +  - 'interface:nrpe-external-master'
Done.

2017-02-03 15:29 UTC, eparis commented
@jbeda @mikedanese @roberthbailey @zmerlynn  wasn't there a push to stop doing new things in `cluster/`  this also feels way outside the bailiwick of what we'd want to do in `cluster/` even if it wasn't destined for the dust bin. I just want other OWNERs thought on where this should go...

2017-02-03 16:48 UTC, marcoceppi commented
This certainly isn't a new thing, and as for way outside the bailiwick for `/cluster`, it resides alongside a slew of other components which turn up a kubernetes. If you're suggesting this pull request, to add monitoring support to a kubernetes deployment turned up by charms is way outside, I'd challenge that those kinds of operational practices - logging, monitoring, etc - are things we should be modeling for clusters being turned up.

2017-02-04 04:58 UTC, roberthbailey commented
@eparis -- what "new things" do you object to in the PR? It's modifying a bunch of existing files to productionize the k8s deployment. I think everyone agrees that we should find a new home for cluster provisioning solutions outside of the cluster directory in the main repo, but to me this looks like a maintenance update for a solution that we already let in. 

@axinojolais -- can you please squash your 5 commits into a single commit?

2017-02-04 06:18 UTC, chuckbutler commented
Aside from the squash request, the code performed as expected. 

Once this has been squashed I'm happy to approve it. I do believe axino might have left on vacation and if that's the case, I'll be happy to squash on his behalf and re-propose as a piggyback commit.

2017-02-07 16:49 UTC, eparis commented
As long as others are fine with continuing to grow the functionality in `cluster/` (I'm not saying this is bad work, I'm so sorry if it seemed that way!) then I good with it too. I'll flag for merge after you squash.

2017-02-22 21:09 UTC, Cynerva commented
I've opened up a follow-up PR with squashed commits here: https://github.com/kubernetes/kubernetes/pull/41923

2017-03-02 17:38 UTC, chuckbutler commented
This branch is now woefully out of date. The squashed rebase has already been merged. I think its safe to close this pr @axinojolais

2017-03-03 06:10 UTC, closed without merging