Added the first TPR unit test.
kubernetes/kubernetes pull request #40956
Opened 2017-02-04 00:24 UTC by ahakanbaba

We are applying the Kind:ThirdPartyResource object.
and making sure the kubectl code created the GET and PATCH requests
correctly.

**What this PR does / why we need it**:
Adds the first unit test for apply operations using ThirdPartyResources. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
References: https://github.com/kubernetes/kubernetes/issues/40841 

**Special notes for your reviewer**:
This PR supersedes https://github.com/kubernetes/kubernetes/pull/40775. 
This is the same test but on master branch. The previous one was written on 1.4.7 

**Release note**:

```release-note
```

2017-02-04 00:26 UTC, ahakanbaba commented
@ymqytw  Could you take a look at this review. 
This supersedes the other TPR unit test in #40775.

2017-02-04 21:22 UTC, ymqytw commented on pkg/kubectl/cmd/apply_test.go
> +				bodyTPR := ioutil.NopCloser(bytes.NewReader(currentTPR))
`currentTPR ` you return doesn't have the `last-applied-config`. Apply need to that annotation. Please check other test cases.

I suggest you have at least 2 approaches:
1) use json to manipulate that field.
2) create a TPR obj with `last-applied-config` in the test yaml file.

2017-02-04 22:10 UTC, liggitt requested changes

2017-02-04 22:10 UTC, liggitt commented on staging/src/k8s.io/client-go/rest/fake/fake.go
> +			GroupVersion:         &c.APIRegistry.GroupOrDie(c.GroupName).GroupVersion,
I think switching to the configured group makes sense

2017-02-04 22:10 UTC, liggitt commented on staging/src/k8s.io/client-go/rest/fake/fake.go
> +	defaultContentConfig := restclient.ContentConfig{}
Why is the default config insufficient?

2017-02-04 22:10 UTC, liggitt commented on pkg/kubectl/cmd/testing/fake.go
> +					{Name: "thirdpartyresources", Namespaced: false, Kind: "ThirdPartyResource"},
If a third party resource was registered, we would expect it to show up in discovery. Add another API group stanza for "mygroup.com" with a single version and a single namespaced resource "foos" of kind Foo

2017-02-04 22:10 UTC, liggitt commented on pkg/kubectl/cmd/testing/fake.go
> +					{Name: "thirdpartyresources", Namespaced: false, Kind: "ThirdPartyResource"},
No need to simulate submission of the actual ThirdPartyResource definition object…

2017-02-04 22:10 UTC, liggitt commented on pkg/kubectl/cmd/testing/fake.go
> +	if f.tf.JSONEncoder != nil {
I would not expect this to be needed

2017-02-04 22:10 UTC, liggitt commented on pkg/kubectl/cmd/apply_test.go
> +func TestApplyTPR(t *testing.T) {
Submission of the ThirdPartyResource is not the important part to test. Submission of the kind that is not compiled in (e.g. A "Foo" object in group "example.com" and version "v1") multiple times (once to create and once to patch/apply)

2017-02-05 01:50 UTC, ahakanbaba commented on pkg/kubectl/cmd/apply_test.go
> +func TestApplyTPR(t *testing.T) {
I understand. The unit test implementations for applying the entires for the ThirdPartyResources are on their way. 
We have seen some flaky behavior with respect to the Kind: ThirdPartyResource objects too. 
There were unexpected behavior if there are multiple Kind: ThirdPartyResource objects. Deletion and recreation of them caused unexpected behavior. Those were in v1.3.9.
To reproduce more use cases of ThirdPartyResources, I hope you can see that this unit test still adds value.

2017-02-05 01:50 UTC, ahakanbaba commented on pkg/kubectl/cmd/apply_test.go
> +		NegotiatedSerializer: ns,
Sure, will do the changes

2017-02-05 01:50 UTC, ahakanbaba commented on pkg/kubectl/cmd/apply_test.go
> +				bodyTPR := ioutil.NopCloser(bytes.NewReader(currentTPR))
I see. Good catch thanks for pointing that out. 

The annotateRuntimeObject function was already doing that. However in this PR I have implemented my own readTPRFromFile function. The annotateRuntimeObject was using the testapi.Default.Codec(). I need testapi.extensions.Codec(). 

I will either use a similar approach to the annotateRuntimeObject function or try to re-use the annotateRuntimeObject funciton.

2017-02-05 01:50 UTC, ahakanbaba commented on pkg/kubectl/cmd/testing/fake.go
> +	if f.tf.JSONEncoder != nil {
I need to use testapi.Extension.Codec() for the encoder. By default the fakeAPIFactory uses the testapi.Default.Codec and that causes this error 

```
=== RUN   TestApplyTPR
Path: /thirdpartyresources/test-tpr.unit-test.test.com, Method: GET--- FAIL: TestApplyTPR (0.01s)
	cmd_test.go:50: Error running command (exit code 1): error: error when applying patch:

		to:
		&{0xc4204de0e0 0xc4204debd0  test-tpr.unit-test.test.com ../../../test/fixtures/pkg/kubectl/cmd/apply/third-party-resource.yaml &ThirdPartyResource{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:test-tpr.unit-test.test.com,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Description:A TPR definition used for unit tests,Versions:[{v1}],} &TypeMeta{Kind:,APIVersion:,}  false}
		for: "../../../test/fixtures/pkg/kubectl/cmd/apply/third-party-resource.yaml": error when serializing current configuration from:
		&TypeMeta{Kind:,APIVersion:,}
		for: "../../../test/fixtures/pkg/kubectl/cmd/apply/third-party-resource.yaml": extensions.ThirdPartyResource is not suitable for converting to ["v1"]
FAIL
exit status 1
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd	0.039s
```

2017-02-05 01:50 UTC, ahakanbaba commented on pkg/kubectl/cmd/testing/fake.go
> +					{Name: "thirdpartyresources", Namespaced: false, Kind: "ThirdPartyResource"},
I did not quite understand this comment 
 > Add another API group stanza for "mygroup.com" with a single version and a single namespaced resource "foos" of kind Foo


In this PR I have also added a test/fixtures/pkg/kubectl/cmd/apply/third-party-resource-entry.yaml file. 
Next I will add unit tests for applying entries to this ThirdPartyResource. 
I think you may be referring to those.

I have responded to your previous comments about this unit test. I hope you do not object the incremental test coverage this adds.

2017-02-05 01:50 UTC, ahakanbaba commented on staging/src/k8s.io/client-go/rest/fake/fake.go
> +	defaultContentConfig := restclient.ContentConfig{}
This was one way I have found to use extensions.GroupName for a Decoder deep in the callstack of kubectl calls.

The decoder created here: 
https://github.com/kubernetes/kubernetes/pull/40956/files#diff-5a429dbc4e41abe93cb1915987b2d66eL107

I want the internalVersion parameter to the `ns.DecoderToVersion` function contain "extensions" in the Group field. 

I am setting the GroupName to "extensions" from the test function here
https://github.com/kubernetes/kubernetes/pull/40956/files#diff-fff79b71b1ff7d6cfb18f869abbc62d5R314

Without this a Decoder is giving me this error:

```
[vagrant@k8s-env cmd]$ go test . -v -run TestApplyTPR
=== RUN   TestApplyTPR
Path: /thirdpartyresources/test-tpr.unit-test.test.com, Method: GET--- FAIL: TestApplyTPR (0.00s)
	cmd_test.go:50: Error running command (exit code 1): error: error when retrieving current configuration of:
		&{0xc42038a7e0 0xc42029e850  test-tpr.unit-test.test.com ../../../test/fixtures/pkg/kubectl/cmd/apply/third-party-resource.yaml &ThirdPartyResource{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:test-tpr.unit-test.test.com,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Description:A TPR definition used for unit tests,Versions:[{v1}],} &TypeMeta{Kind:,APIVersion:,}  false}
		from server for: "../../../test/fixtures/pkg/kubectl/cmd/apply/third-party-resource.yaml": v1beta1.ThirdPartyResource is not suitable for converting to "__internal"
FAIL
exit status 1
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd	0.034s
```

If you have a better way to use "extensions" I can change this impl.

2017-02-05 01:50 UTC, ahakanbaba commented on staging/src/k8s.io/client-go/rest/fake/fake.go
> +			GroupVersion:         &c.APIRegistry.GroupOrDie(c.GroupName).GroupVersion,
Do you want me change anything  related to this comment ?

2017-02-05 02:09 UTC, liggitt commented on pkg/kubectl/cmd/apply_test.go
> +func TestApplyTPR(t *testing.T) {
The behavior was likely in the server-side aspect of registering/updating a TPR (which this doesn't test), not the basic client CRUD of ThirdPartyResource. I'd rather see the apply tests around the third party resource instance data

2017-02-05 02:12 UTC, liggitt commented on pkg/kubectl/cmd/testing/fake.go
> +					{Name: "thirdpartyresources", Namespaced: false, Kind: "ThirdPartyResource"},
I don't think more coverage of CRUD of known objects is needed. The gap we have is in testing unknown objects (e.g. third party resource instance objects)

2017-02-05 02:13 UTC, liggitt commented on pkg/kubectl/cmd/testing/fake.go
> +	if f.tf.JSONEncoder != nil {
Try with the unstructuredSerializer. We already have apply tests that persist deployments, which are also in the extensions group, that do not need to do this

2017-02-05 02:14 UTC, liggitt commented on staging/src/k8s.io/client-go/rest/fake/fake.go
> +	defaultContentConfig := restclient.ContentConfig{}
See the unit test that applies deployment objects (also in the extensions group)

2017-02-05 02:15 UTC, liggitt commented on pkg/kubectl/cmd/apply_test.go
> +				bodyTPR := ioutil.NopCloser(bytes.NewReader(currentTPR))
For stubbing return data, I would hardcode the result as much as possible for ease of inspection

2017-02-05 02:26 UTC, ahakanbaba commented on pkg/kubectl/cmd/testing/fake.go
> +					{Name: "thirdpartyresources", Namespaced: false, Kind: "ThirdPartyResource"},
Ok. Do you want me to abandon this ? or address the final reviews and bring it to a mergeable state ?

2017-02-05 02:47 UTC, liggitt commented on pkg/kubectl/cmd/testing/fake.go
> +					{Name: "thirdpartyresources", Namespaced: false, Kind: "ThirdPartyResource"},
I'd rather see the tests for applying instances of unknown objects.

2017-02-05 02:50 UTC, liggitt commented on pkg/kubectl/cmd/testing/fake.go
> +					{Name: "thirdpartyresources", Namespaced: false, Kind: "ThirdPartyResource"},
(Specifically, the tests mentioned in https://github.com/kubernetes/kubernetes/issues/40841#issue-204769102)

2017-05-08 20:04 UTC, spiffxp commented
@k8s-bot ok to test

2017-07-10 17:26 UTC, liggitt commented
The ThirdPartyResource APIs have been deprecated in 1.7 and removed in 1.8, replaced with CustomResourceDefinitions

2017-07-10 17:26 UTC, closed without merging