fix kubeadm reset error
kubernetes/kubernetes pull request #41002
Opened 2017-02-06 07:55 UTC by xilabao

fix #41001

2017-02-06 08:55 UTC, luxas requested changes

2017-02-06 08:55 UTC, luxas commented on cmd/kubeadm/app/cmd/reset.go
> -	kubeConfigPath := filepath.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, kubeconfig.KubeletKubeConfigFileName)
Sorry, but this won't work.
`kubeadm reset` should work on every node, and admin.conf only exists on the master.

2017-02-07 05:15 UTC, xilabao commented on cmd/kubeadm/app/cmd/reset.go
> -	kubeConfigPath := filepath.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, kubeconfig.KubeletKubeConfigFileName)
@luxas fixed. add --kubeconfig option. Allow run `sudo kubeadm reset --kubeconfig=./admin.conf` or use default kubeconfig on every node.

2017-02-07 15:28 UTC, resouer commented
@k8s-bot ok to test

2017-02-09 08:57 UTC, xilabao commented
@luxas PTAL

2017-02-09 12:29 UTC, luxas commented
I'm sorry, but this is the wrong approach to solving https://github.com/kubernetes/kubeadm/issues/142.
The `admin.conf` file doesn't exist on nodes, so if we should do this, we should grant `kubelet.conf` to drain itself instead.

2017-02-10 01:45 UTC, xilabao commented
```
#./cluster/kubectl.sh drain 127.0.0.1 --kubeconfig=/var/run/kubernetes/kubelet.kubeconfig
Error from server (Forbidden): User "system:node:127.0.0.1" cannot update nodes at the cluster scope. (put nodes 127.0.0.1)
```
Maybe we should need to allow update nodes for system:node? @luxas @liggitt @deads2k PTAL

2017-02-10 01:48 UTC, liggitt commented
nodes have the ability to update their status, not their spec.

2017-02-10 01:48 UTC, liggitt commented
draining a node is not an operation I would expect a node to run on itself, but one a cluster administrator would run on the node

2017-02-10 07:24 UTC, xilabao commented
> draining a node is not an operation I would expect a node to run on itself, but one a cluster administrator would run on the node

@luxas Could we create admin.conf on nodes?

2017-02-10 13:52 UTC, liggitt commented
>> draining a node is not an operation I would expect a node to run on itself, but one a cluster administrator would run on the node
>
> @luxas Could we create admin.conf on nodes?

I meant that the  admin performs on the node API object, not literally on the node machine we should not push  cluster admin credentials to the nodes.

2017-02-13 06:02 UTC, xilabao commented
@liggitt Thanks for your so detailed explain. Does it mean that `drain node` is not necessary when run `kubeadm reset` in node machine?

2017-02-13 21:04 UTC, liggitt commented
after further discussion, the ability for a node to update itself will be added in https://github.com/kubernetes/kubernetes/pull/41345

2017-02-14 07:08 UTC, xilabao commented
fixed in #41345, closed

2017-02-14 07:08 UTC, closed without merging