PV E2E:  dynamically provisioned volume should not create in unmanaged zone
kubernetes/kubernetes pull request #41049
Opened 2017-02-06 23:36 UTC by copejon

**What this PR does / why we need it**:
Adds e2e test to that attempts to provision a volume in an unmanaged zone and fails on success.  This is to catch regressions of #31948.

cc @jeffvance 
```release-note
NONE
```

2017-02-06 23:52 UTC, jeffvance commented on test/e2e/volume_provisioning.go
> +			compSvc := gceCloud.GetComputeService()
Is there a helper func to get all zones and/or get a specific zone?

2017-02-06 23:53 UTC, jeffvance commented on test/e2e/volume_provisioning.go
> +			call := compSvc.Zones.List(framework.TestContext.CloudConfig.ProjectID)
Is there a helper func to get all zones and/or get a specific zone?

2017-02-08 12:35 UTC, jsafrane requested changes

2017-02-08 12:35 UTC, jsafrane commented on test/e2e/volume_provisioning.go
> +	"k8s.io/apimachinery/pkg/util/sets"
this belongs to the chunk of k8s imports above.

2017-02-08 12:35 UTC, jsafrane commented on test/e2e/volume_provisioning.go
> +				framework.Failf("No unmanaged zones found.")
I'd skip the test in this case - it's not a failure.

2017-02-08 12:35 UTC, jsafrane commented on test/e2e/volume_provisioning.go
> +			defer Ω(c.Storage().StorageClasses().Delete(sc.Name, nil)).Should(Succeed())
Please use `Expect` syntax instead of `Ω`.

2017-02-08 12:35 UTC, jsafrane commented
@k8s-bot ok to test

2017-02-08 13:15 UTC, jsafrane commented
```
I0208 04:53:19.259] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I0208 04:53:28.013] !!! 'gofmt -s -w' needs to be run on the following files: 
I0208 04:53:28.013] ./test/e2e/volume_provisioning.go
I0208 04:53:28.022] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	9s
```

2017-02-10 13:01 UTC, jsafrane commented
now it looks fine, @copejon please squash the commits and I'll lgtm it (is it a verb?)

2017-02-13 22:41 UTC, spxtr commented
/approve

2017-02-14 08:30 UTC, jsafrane approved these changes

2017-02-14 08:32 UTC, jsafrane commented
@copejon, hack/verify-gofmt.sh is still not happy, please reformat test/e2e/volume_provisioning.go

2017-02-15 09:37 UTC, jsafrane commented
@k8s-bot gce etcd3 e2e test this
@k8s-bot kops aws e2e test this

2017-02-15 09:38 UTC, jsafrane commented
/lgtm

2017-02-15 13:58 UTC, merged