test: dump more info for cleanup test
kubernetes/kubernetes pull request #41145
Opened 2017-02-08 17:44 UTC by kargakis

For https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/3569

@ncdc will make the output of the test cleaner

2017-02-08 17:48 UTC, ncdc commented
/lgtm

2017-02-08 17:56 UTC, kargakis commented
The change in worth since the new output will be better than the old but based on the discussion in https://github.com/kubernetes/kubernetes/issues/36379 it is probably not a Deployment issue.

2017-02-08 18:29 UTC, kargakis commented
@k8s-bot cvm gce e2e test this https://github.com/kubernetes/kubernetes/issues/33702

2017-02-08 18:30 UTC, ncdc commented
@kargakis 33702 is a relatively useless catchall :-p

2017-02-08 19:07 UTC, kargakis commented
So the replica set seems to have a deletion timestamp but it's added almost in the end of the test... Added a few more logs in the controller during the cleanup phase.

2017-02-08 19:39 UTC, ncdc commented
cc @janetkuo

2017-02-09 09:06 UTC, kargakis commented
@k8s-bot gce etcd3 e2e test this https://github.com/kubernetes/kubernetes/issues/36821

2017-02-09 09:10 UTC, sttts commented on pkg/controller/deployment/sync.go
> +		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration || rs.DeletionTimestamp != nil {
this is not about logging, isn't it?

2017-02-09 09:14 UTC, kargakis commented on pkg/controller/deployment/sync.go
> +		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration || rs.DeletionTimestamp != nil {
Nope, but it seems like a possible source of the problem for the flaky test - see https://github.com/kubernetes/kubernetes/pull/41163#issuecomment-278526438

2017-02-09 09:16 UTC, sttts commented on pkg/controller/deployment/sync.go
> +		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration || rs.DeletionTimestamp != nil {
Can you move it to its own commit? And mention it in the PR. Otherwise, it looks like this only changes some logging.

2017-02-09 09:17 UTC, sttts commented on pkg/controller/deployment/sync.go
> +		glog.V(2).Infof("Trying to cleanup replica set %q for deployment %q", rs.Name, deployment.Name)
V(2) looks like pretty low. With which level are e2e tests run?

2017-02-09 09:21 UTC, soltysh requested changes

2017-02-09 09:21 UTC, soltysh commented on pkg/controller/deployment/sync.go
> +		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration || rs.DeletionTimestamp != nil {
Shouldn't there be accompanying unit test update to cover this case as well?

2017-02-09 09:22 UTC, soltysh commented on pkg/controller/deployment/sync.go
> +		glog.V(2).Infof("Trying to cleanup replica set %q for deployment %q", rs.Name, deployment.Name)
I wouldn't expect it be high :/

2017-02-09 09:23 UTC, kargakis commented on pkg/controller/deployment/sync.go
> +		glog.V(2).Infof("Trying to cleanup replica set %q for deployment %q", rs.Name, deployment.Name)
From AWS I can get back V(2) - I will open an issue to bump these once I get a clean run

2017-02-09 09:33 UTC, kargakis commented on pkg/controller/deployment/sync.go
> +		glog.V(2).Infof("Trying to cleanup replica set %q for deployment %q", rs.Name, deployment.Name)
https://github.com/kubernetes/kubernetes/issues/41187

2017-02-09 09:33 UTC, kargakis commented
> Shouldn't there be accompanying unit test update to cover this case as well?

Added a test case and split the commit with that diff into a separate one, ptal

2017-02-09 09:44 UTC, mfojtik commented on test/e2e/framework/util.go
> +		pollErr = fmt.Errorf("%d old replica sets were not cleaned up for deployment %q", len(oldRSs)-desiredRSNum, deploymentName)
do we not want to print the namespace for the deployment?

2017-02-09 09:46 UTC, soltysh approved these changes

2017-02-09 09:46 UTC, soltysh commented
LGTM

2017-02-09 09:47 UTC, sttts commented on pkg/controller/deployment/sync.go
> +		glog.V(2).Infof("Trying to cleanup replica set %q for deployment %q", rs.Name, deployment.Name)
lgtm

2017-02-09 09:47 UTC, kargakis commented on test/e2e/framework/util.go
> +		pollErr = fmt.Errorf("%d old replica sets were not cleaned up for deployment %q", len(oldRSs)-desiredRSNum, deploymentName)
Not needed here, the ns is available via other means (events for example)

2017-02-09 18:23 UTC, janetkuo commented on pkg/controller/deployment/sync.go
> +		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration || rs.DeletionTimestamp != nil {
Shouldn't we do this before the for loop so that we get accurate `diff`?

2017-02-09 19:14 UTC, kargakis commented
Doesn't look like it makes a difference in the end result. Am I missing
something?

On Thu, Feb 9, 2017 at 7:23 PM, Janet Kuo <notifications@github.com> wrote:

> *@janetkuo* commented on this pull request.
> ------------------------------
>
> In pkg/controller/deployment/sync.go
> <https://github.com/kubernetes/kubernetes/pull/41145#pullrequestreview-21081353>
> :
>
> >
>  	var errList []error
>  	// TODO: This should be parallelized.
>  	for i := int32(0); i < diff; i++ {
>  		rs := oldRSs[i]
>  		// Avoid delete replica set with non-zero replica counts
> -		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration {
> +		if rs.Status.Replicas != 0 || *(rs.Spec.Replicas) != 0 || rs.Generation > rs.Status.ObservedGeneration || rs.DeletionTimestamp != nil {
>
> Shouldn't we do this before the for loop so that we get accurate diff?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/41145#pullrequestreview-21081353>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADuFfzerwmRI0EKL902ZlGp6x5ZLownPks5ra1mggaJpZM4L7Is9>
> .
>

2017-02-09 21:34 UTC, merged

2017-02-09 23:30 UTC, janetkuo commented
@kargakis Sure, eventually the old RSes will become zero replica and get cleaned up, but `cleanupDeployment` does not delete old RSes as fast as it can. The `diff` should've been calculated with old RSes that can actually be cleaned up. 

An edge case is that a deployment was paused during rolling update. `cleanupDeployment` could fail to clean up any old RSes if the oldest RS have >0 replica (it's possible in the rollback case).

2017-02-10 09:29 UTC, kargakis commented
> @kargakis Sure, eventually the old RSes will become zero replica and get cleaned up, but cleanupDeployment does not delete old RSes as fast as it can. The diff should've been calculated with old RSes that can actually be cleaned up.

The only problem this can lead to is a case where old replica sets are not getting cleaned up and the new replica set cannot be created due to quota but this assumes that soft-deleted replica sets continue to count against quota (@derekwaynecarr a question for you I guess).

> An edge case is that a deployment was paused during rolling update. cleanupDeployment could fail to clean up if the oldest RS have >0 replica and diff == 1 (it's possible in the rollback case).

I don't understand your example. Why `cleanupDeployment` "fails" when the old replica set has >0 replicas? Isn't that normal?

2017-02-10 19:49 UTC, janetkuo commented
> I don't understand your example. Why `cleanupDeployment` "fails" when the old replica set has >0 replicas? Isn't that normal?

Not the old replicaset, the oldest one. In this case, other old replicaset with 0 replica should be cleaned up instead.

2017-02-12 14:00 UTC, kargakis commented
Yes, let's merge your PR

On Fri, Feb 10, 2017 at 8:50 PM, Janet Kuo <notifications@github.com> wrote:

> I don't understand your example. Why cleanupDeployment "fails" when the
> old replica set has >0 replicas? Isn't that normal?
>
> Not the old replicaset, the oldest one. In this case, other old replicaset
> with 0 replica should be cleaned up instead.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/41145#issuecomment-279048307>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADuFf4xDkzqfzbJjtk2igXAFdfANVMvlks5rbL9qgaJpZM4L7Is9>
> .
>