Switch RBAC subject apiVersion to apiGroup
kubernetes/kubernetes pull request #41184
Opened 2017-02-09 08:05 UTC by liggitt

When referencing a subject from a role binding, the API group and kind of the subject is needed to fully-qualify the reference.

The version is not, and adds complexity around re-writing the reference when returning the binding from different versions of the API, and when reconciling subjects.

This PR:
* changes the subject apiVersion field to apiGroup in v1beta1 (yet unreleased)
* converts apiVersion in v1alpha1 bindings to apiGroup
* adds validation to the field so we can count on the data in etcd being good until we decide to relax the apiGroup restriction

@deads2k @kubernetes/sig-auth-api-reviews @kubernetes/sig-auth-pr-reviews

2017-02-09 12:56 UTC, deads2k commented on pkg/apis/rbac/types.go
> +	APIGroup string
I'm in favor, even though most places stuff groups into the version field.

2017-02-09 18:11 UTC, ericchiang commented on pkg/apis/rbac/types.go
> +	APIGroup string
Can we articulate that setting this value isn't required for "normal" uses and defaults to a reasonable value? We've had users consistently be confused by this field.

2017-02-10 20:35 UTC, liggitt commented
@ericchiang this better?

```
// APIGroup holds the API group of the referenced subject.
// Defaults to "" for ServiceAccount subjects.
// Defaults to "rbac.authorization.k8s.io" for User and Group subjects.
```

also added validation so that if you fat-finger some other value, it won't get persisted and it'll tell you what it expected

2017-02-10 20:39 UTC, liggitt commented
cc @kubernetes/api-approvers for approval

2017-02-10 20:51 UTC, ericchiang commented
@liggitt looks great.

2017-02-10 21:22 UTC, smarterclayton commented on pkg/apis/rbac/validation/validation.go
> +		if subject.APIGroup != "" {
nit: use len() for consistency with the rest of this method

2017-02-10 21:26 UTC, liggitt commented on pkg/apis/rbac/validation/validation.go
> +		if subject.APIGroup != "" {
done

2017-02-11 01:48 UTC, smarterclayton requested changes
Code looks fine, API looks fine.  One comment

2017-02-11 01:48 UTC, smarterclayton commented on pkg/apis/rbac/v1alpha1/zz_generated.conversion.go
> +	// WARNING: in.APIVersion requires manual conversion: does not exist in peer-type
Set the conversion=false tag to avoid this warning

2017-02-11 01:54 UTC, liggitt commented on pkg/apis/rbac/v1alpha1/zz_generated.conversion.go
> +	// WARNING: in.APIVersion requires manual conversion: does not exist in peer-type
fixed

2017-02-11 02:05 UTC, smarterclayton commented
Any other comments folks want to add?

2017-02-13 16:31 UTC, smarterclayton approved these changes

2017-02-13 22:10 UTC, liggitt commented
tagging per https://github.com/kubernetes/kubernetes/pull/41184#pullrequestreview-21374999

2017-02-14 05:07 UTC, merged