StatefulSet Upgrade Test
kubernetes/kubernetes pull request #41221
Opened 2017-02-09 23:21 UTC by kow3ns

Adds StatefulSet upgrade tests and moves common functionality into the framework package. This removes the potential for cyclic dependencies while allowing for code reuse.
```release-note
NONE
```

2017-02-10 03:40 UTC, kow3ns commented
@k8s-bot test this

2017-02-10 06:10 UTC, kow3ns commented
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221)*
<!-- Sent from Reviewable.io -->

2017-02-10 09:48 UTC, sttts commented on test/e2e/framework/statefulset_utils.go
> +	apierrs "k8s.io/apimachinery/pkg/api/errors"
new line

2017-02-10 09:50 UTC, sttts commented on test/e2e/framework/statefulset_utils.go
> +func getPodNameAtIndex(index int, ss *apps.StatefulSet) string {
put some StatefulSet into the name

2017-02-10 09:50 UTC, sttts commented on test/e2e/framework/statefulset_utils.go
> +func IsInitialized(pod v1.Pod) bool {
put some StatefulSet into the name

2017-02-10 09:50 UTC, sttts commented on test/e2e/framework/statefulset_utils.go
> +func SetInitializedAnnotation(ss *apps.StatefulSet, value string) {
put some StatefulSet into the name

2017-02-10 09:51 UTC, sttts commented
Looks good. Just some naming issues.

2017-02-10 16:50 UTC, kow3ns commented
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/e2e/framework/statefulset_utils.go, line 28 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221#-Kc_AxTCyof-u-KHhEhn-r1-28:-KcctBoQbdC84-xFDtRN:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/c2c7f74c403321d3bd1132eda9eb3b103506fc46/test/e2e/framework/statefulset_utils.go#L28)):*
<details><summary><i>Previously, sttts (Dr. Stefan Schimanski) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[test/e2e/framework/statefulset_utils.go, line 192 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221#-Kc_AxTCyof-u-KHhEhn-r1-192:-Kcctd-VbjqOYA8FY0v5:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/c2c7f74c403321d3bd1132eda9eb3b103506fc46/test/e2e/framework/statefulset_utils.go#L192)):*
<details><summary><i>Previously, sttts (Dr. Stefan Schimanski) wrote…</i></summary><blockquote>

put some StatefulSet into the name
</blockquote></details>

Done.

---

*[test/e2e/framework/statefulset_utils.go, line 463 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221#-Kc_AxTCyof-u-KHhEhn-r1-463:-Kcctds847_hmCkLAXfn:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/c2c7f74c403321d3bd1132eda9eb3b103506fc46/test/e2e/framework/statefulset_utils.go#L463)):*
<details><summary><i>Previously, sttts (Dr. Stefan Schimanski) wrote…</i></summary><blockquote>

put some StatefulSet into the name
</blockquote></details>

Done.

---

*[test/e2e/framework/statefulset_utils.go, line 556 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221#-Kc_AxTCyof-u-KHhEhn-r1-556:-Kccv_OpBpygXlLuKjio:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/c2c7f74c403321d3bd1132eda9eb3b103506fc46/test/e2e/framework/statefulset_utils.go#L556)):*
<details><summary><i>Previously, sttts (Dr. Stefan Schimanski) wrote…</i></summary><blockquote>

put some StatefulSet into the name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221)*
<!-- Sent from Reviewable.io -->

2017-02-10 17:41 UTC, krousey requested changes

2017-02-10 17:41 UTC, krousey commented on test/e2e/upgrades/statefulset.go
> +	By("Verifying statefulset mounted data directory is usable")
This and subsequent tests are repeated verbatim in the `Test` method. You could put them in a private method that both `Setup` and `Test` call.

2017-02-10 18:20 UTC, kow3ns commented
Reviewed 2 of 2 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/e2e/upgrades/statefulset.go, line 65 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221#-Kc_AxTCyof-u-KHhEho-r2-65:-KcdFCrkd-EanOrpMGdZ:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/88a677f1909eeb69d32d5ac1c3bb9859f6ad7001/test/e2e/upgrades/statefulset.go#L65)):*
<details><summary><i>Previously, krousey wrote…</i></summary><blockquote>

This and subsequent tests are repeated verbatim in the `Test` method. You could put them in a private method that both `Setup` and `Test` call.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221)*
<!-- Sent from Reviewable.io -->

2017-02-10 19:52 UTC, kow3ns commented
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41221)*
<!-- Sent from Reviewable.io -->

2017-02-14 19:05 UTC, krousey commented
I'm not a big fan of moving everything into test/e2e/framework. I would much rather see something like test/e2e/util/statefulsetutil/ (and others).

2017-02-14 19:40 UTC, kow3ns commented
@k8s-bot gci gke e2e test this

2017-02-14 19:56 UTC, kow3ns commented
"I'm not a big fan of moving everything into test/e2e/framework. I would much rather see something like test/e2e/util/statefulsetutil/ (and others)."

I concur, but that is the way its currently being done for Pods, Services, Deployments, Nodes, Federation, ..., and the canonical example for upgrade tests is supposed to be Services. In this instance, I think that consistency, for the sake of maintenance, is the right approach. Perhaps we should have a larger discussion about the package structure of e2e in the context of go package naming and organization best practices.

2017-02-14 21:12 UTC, krousey approved these changes

2017-02-14 21:13 UTC, krousey commented
/approve

I'll let @sttts have the final lgtm.

2017-02-16 20:59 UTC, kow3ns commented
@stts are there any further comments that need to be addressed.

2017-02-17 10:45 UTC, sttts commented
/lgtm

2017-02-17 12:34 UTC, merged