default to discovered server resources
kubernetes/kubernetes pull request #41354
Opened 2017-02-13 20:14 UTC by juanvallejo

Fixes #41353

When expanding "kubectl get all", this patch defaults the list of resources returned from shortcut_restmapper to those discovered on the server (if any). This allows "kubectl get all" to be successfully used against servers that do not have defined any of these hardcoded [UserResources](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/shortcut_restmapper.go#L105-L114) resources.

**Special notes for your reviewer**:
Relevant when using kubectl against the [service catalog](https://github.com/kubernetes-incubator/service-catalog) api-server

**Release note**:
```release-note
release-note-none
```

cc @pmorie @pwittrock

2017-02-13 21:10 UTC, janetkuo commented
@juanvallejo if no release note is required, put `NONE` in the release note block

2017-02-14 01:27 UTC, k82cn reviewed
Please add unit test for this case.

Just an overall review; I'll check its functional part later :).

2017-02-14 01:27 UTC, k82cn commented on pkg/kubectl/cmd/util/shortcut_restmapper.go
> +		r := availableResource.GroupResource()
AFAIK, range slice will return index if only one lvalue, and int did not have `GroupResource` funcs. may be:

```
  for _, availableResource := range availableResources {
    ...
  }
```

2017-02-14 03:13 UTC, liggitt commented on pkg/kubectl/cmd/util/shortcut_restmapper.go
> +func (e ShortcutExpander) getAll() ([]schema.GroupResource, []schema.GroupResource) {
this signature for a shortcut expander doesn't make sense

2017-02-14 03:20 UTC, liggitt requested changes

2017-02-14 03:20 UTC, liggitt commented on pkg/kubectl/cmd/util/shortcut_restmapper.go
> +	for availableResource := range availableResources {
not sure defaulting to all discovered resources is correct, given the [current definition of "all"](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all)

2017-02-14 15:29 UTC, juanvallejo commented on pkg/kubectl/cmd/util/shortcut_restmapper.go
> +		r := availableResource.GroupResource()
@k82cn Thanks for the feedback, although I am using the index, in this case the map `availableResources` contains the actual groupVersionResource as the key, and an empty struct as the value

2017-02-14 15:32 UTC, juanvallejo commented on pkg/kubectl/cmd/util/shortcut_restmapper.go
> +func (e ShortcutExpander) getAll() ([]schema.GroupResource, []schema.GroupResource) {
hm, maybe it'd be better to check if any of the hardcoded `UserResources` matched any of the  available server resources here and if the final list is empty, return `availableResources` as the only slice?

2017-02-14 15:36 UTC, juanvallejo commented on pkg/kubectl/cmd/util/shortcut_restmapper.go
> +	for availableResource := range availableResources {
Hm, this just became a bit more tricky. Other than maybe specifying the contents of `UserResources` as part of a client config, I am not sure how else to handle cases where none of the resources in `UserResources` match any of the discovered ones.

2017-02-14 21:18 UTC, juanvallejo commented on pkg/kubectl/cmd/util/shortcut_restmapper.go
> +	for availableResource := range availableResources {
Added a second commit that filters out discovered resources that are not namespaced, however still need to filter out admin-level and potentially unrecoverable resources from the list

2017-03-03 22:00 UTC, fabianofranz commented
Closing in favor of the one I'm about to open.

2017-03-03 22:00 UTC, closed without merging