Update kube-proxy support for Windows
kubernetes/kubernetes pull request #41487
Opened 2017-02-15 16:50 UTC by anhowe

The kube-proxy is built upon the sophisticated iptables NAT rules.  Windows does not have an equivalent capability.  This introduces a change to the architecture of the user space mode of the Windows version of kube-proxy to match the capabilities of Windows.

The proxy is organized around service ports and portals.  For each service a service port is created and then a portal, or iptables NAT rule, is opened for each service ip, external ip, node port, and ingress ip.  This PR merges the service port and portal into a single concept of a "ServicePortPortal" where there is one connection opened for each of service IP, external ip, node port, and ingress IP.

This PR only affects the Windows kube-proxy.  It is important for the Windows kube-proxy because it removes the limited portproxy rule and RRAS service and enables full tcp/udp capability to services.

2017-02-15 19:33 UTC, anhowe commented
cla is now signed

2017-02-15 21:12 UTC, thockin commented on pkg/proxy/types.go
> +type ServicePortPortalName struct {
if this is only for windows, should it live in Windows code?

2017-02-22 04:32 UTC, anhowe commented on pkg/proxy/types.go
> +type ServicePortPortalName struct {
Thanks, I've moved this to the windowuserspace.

2017-02-22 05:09 UTC, brendandburns requested changes
Mostly small stuff.

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +		serviceIP := net.ParseIP(listenIP)
Add a `nil` check here in case the parse fails?

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	sock, err := newProxySocket(protocol, net.ParseIP(listenIP), port)
`nil` check for `ParseIP` here too?

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	err := proxier.stopProxy(servicePortPortalName, info)
inline the if:

`if err := ...; err != nil {`

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	listenIP := info.portal.ip
nit: this assignment feels unnecesary, just use `info.portal.ip` in both places.

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +				servicePortPortalName := ServicePortPortalName{NamespacedName: types.NamespacedName{Namespace: service.Namespace, Name: service.Name}, Port: servicePort.Name, PortalIPName: listenIP}
Format this as a multi-line initializer.

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +					err := proxier.closeServicePortPortal(servicePortPortalName, info)
`if err := ... ; err != nil {`

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +				glog.V(4).Infof("info: %#v", info)
This log feels spammy, if you think its worth keeping maybe increase the log level?

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +				servicePortName := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: service.Namespace, Name: service.Name}, Port: servicePort.Name}
multi-line initializer here.

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
>  			if err != nil {
inline `if` w/ above.

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	if info.sessionAffinityType != service.Spec.SessionAffinity {
It feels kind of wierd to have this be a separate condition.

Either three different `if` or one large `if` but in between feels weird.

2017-02-22 05:09 UTC, brendandburns commented on pkg/proxy/winuserspace/proxysocket.go
> +		servicePortName := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: service.Namespace, Name: service.Name}, Port: service.Port}
multi-line initilizer here for readability.

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	sock, err := newProxySocket(protocol, net.ParseIP(listenIP), port)
fixed, I changed it to one check at the top.

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	err := proxier.stopProxy(servicePortPortalName, info)
fixed

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	listenIP := info.portal.ip
fixed

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +				servicePortPortalName := ServicePortPortalName{NamespacedName: types.NamespacedName{Namespace: service.Namespace, Name: service.Name}, Port: servicePort.Name, PortalIPName: listenIP}
fixed

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +					err := proxier.closeServicePortPortal(servicePortPortalName, info)
fixed

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +				glog.V(4).Infof("info: %#v", info)
increased to 10

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +				servicePortName := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: service.Namespace, Name: service.Name}, Port: servicePort.Name}
fixed

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
>  			if err != nil {
fixed

2017-02-23 03:57 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	if info.sessionAffinityType != service.Spec.SessionAffinity {
fixed

2017-02-24 05:03 UTC, brendandburns requested changes

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxysocket.go
> +				Name:      service.Name},
nit: line break before '}'

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +		servicePortName := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: name.Namespace, Name: name.Name}, Port: name.Port}
multi-line inline formatting here.

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	for name := range servicePortNameMap {
this seems weird to have this second loop. Why not just do the cleanup above instead of adding `true` to the map?

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	if serviceIP = net.ParseIP(listenIP); serviceIP == nil && listenIP != allAvailableInterfaces {
I feel link this construction is a little odd, I would do:
```go
if listenIP != allAvailableInterfaces {
   if serviceIP = ...; serviceIP == nil {
       ...
   }
}
```

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +		args := proxier.netshIpv4AddressAddArgs(serviceIP)
and then you could move this up under the `if` above.

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +		existed, err := proxier.netsh.EnsureIPAddress(args, serviceIP)
this might be a little cleaner as:

```go
if existed, err := ...; err != nil {
   ...
} else if !existed {
   ...
}
```

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +						Name:      service.Name},
nit: line-break before '}'

2017-02-24 05:03 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	if info.protocol != protocol || info.portal.port != listenPort || info.sessionAffinityType != service.Spec.SessionAffinity {
you've stumbled over one of my favorite programming nits...

Just:
```go
return info == protocol && info.portal.port == listenPort && ...
```
```go
if (condition) {
  return false
}
return true
```

is overly verbose.

2017-02-24 21:31 UTC, anhowe reviewed
thanks for the review, everything is fixed

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +		servicePortName := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: name.Namespace, Name: name.Name}, Port: name.Port}
fixed

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	for name := range servicePortNameMap {
I was able to eliminate the second loop

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	if serviceIP = net.ParseIP(listenIP); serviceIP == nil && listenIP != allAvailableInterfaces {
fixed

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +		args := proxier.netshIpv4AddressAddArgs(serviceIP)
done

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +		existed, err := proxier.netsh.EnsureIPAddress(args, serviceIP)
fixed

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +						Name:      service.Name},
I did a search through all my changes and fixed '},' that didn't have line break

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	if info.protocol != protocol || info.portal.port != listenPort || info.sessionAffinityType != service.Spec.SessionAffinity {
ah, yes, I've been continuously reducing this one, and I missed this on the last iteration

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxier.go
> +	if info.protocol != protocol || info.portal.port != listenPort || info.sessionAffinityType != service.Spec.SessionAffinity {
fixed now

2017-02-24 21:31 UTC, anhowe commented on pkg/proxy/winuserspace/proxysocket.go
> +				Name:      service.Name},
I've gone through all my changes and fixed all similar occurences

2017-02-24 21:53 UTC, brendandburns commented
/lgtm
/approve

2017-02-25 00:07 UTC, thockin commented
LGTM.

We should eventually have a discussion about making this a different binary.  kube-proxy is AN implementation of services, but it doesn't have to be the only one.  The windows path shares so little with the linux path, maybe we'd be better off splitting them.

2017-02-25 00:24 UTC, brendandburns commented
@anhowe you have compile failures.

2017-02-28 21:33 UTC, brendandburns approved these changes

2017-03-01 04:16 UTC, merged