K8swin
kubernetes/kubernetes pull request #41618
Opened 2017-02-17 04:51 UTC by JiangtianLi

**What this PR does / why we need it**:
In Windows container networking, --dns-search is not currently supported on Windows Docker. Besides, even with --dns-suffix, inside Windows container DNS suffix is not appended to DNS query names. That makes unqualified domain name or partially qualified domain name in DNS query not able to resolve.

This PR provides a solution to resolve unqualified domain name or partially qualified domain name in DNS query for Windows container in Windows kube-proxy. It uses well-known Kubernetes DNS suffix as well host DNS suffix search list to append to the name in DNS query. DNS packet in kube-proxy UDP stream is modified as appropriate.

This PR affects the Windows kube-proxy only.

**Special notes for your reviewer**:
This PR is based on top of Anthony Howe's commit 049185b which is already included in the PR 41487. Please only review commit e78a5d2.

**Release note**:

```release-note
```

2017-02-17 22:33 UTC, JiangtianLi commented
I signed it! Thanks.

2017-02-20 19:04 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	//utilerrors "k8s.io/apimachinery/pkg/util/errors"
Delete this if its no longer used.

2017-02-20 19:04 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	//nodePort      int
delete these if the are no longer used.

2017-02-20 19:04 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	//listenIP       net.IP
here too.

2017-02-20 19:04 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	//proxyPorts     PortAllocator
and here

2017-02-20 19:13 UTC, brendandburns requested changes

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	/*proxier.mu.Lock()
delete this block.

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +	for name := range spnMap {
This indirection seems weird, why not just `proxier.loadBalancer.CleanupStaleStickySessions(name)` where you set `spnMap[spn]=true`

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +			/*for _, ip := range service.Spec.ExternalIPs {
delete dead code.

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +						glog.Errorf("Failed to stop service %q: %v", serviceName, err)
bail out here?

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +						// TODO(ajh) release the node port
Address this todo?

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +					// TODO(ajh) handle the node port
as above.

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +					portal:              portal{ip: listenIP, port: int(servicePort.Port), isExternal: false},
Multi-line initializer.

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +			proxier.loadBalancer.DeleteService(k)
As above seems like you could inline this in the previous loop.

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> -	if !info.portal.ip.Equal(net.ParseIP(service.Spec.ClusterIP)) {
Why did you delete all of this?

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxier.go
> +/*
Delete commented out code.

2017-02-20 19:13 UTC, brendandburns commented on pkg/proxy/winuserspace/proxysocket.go
> +type dnsHeader struct {
This code could really use some unit tests.

2017-02-22 01:19 UTC, JiangtianLi commented on pkg/proxy/winuserspace/proxier.go
> +	//utilerrors "k8s.io/apimachinery/pkg/util/errors"
Sorry for the confusion. My commit is based on Anthony's commit 302fa44 and 1410e06 so I had to include his commits here. In previous PR, the second commit 1410e06 was lost when I merge his and squash my commits. Now I did rebase and it looked fine. Please skip reviewing diff in commit 302fa44 and 1410e06.

2017-02-22 01:31 UTC, JiangtianLi commented on pkg/proxy/winuserspace/proxysocket.go
> +type dnsHeader struct {
Thanks for the suggestion. I will add unit tests.

2017-02-23 07:49 UTC, JiangtianLi commented on pkg/proxy/winuserspace/proxysocket.go
> +type dnsHeader struct {
I added unit tests in a new commit.

2017-02-28 00:08 UTC, brendandburns commented
/lgtm
/approve

2017-02-28 00:14 UTC, brendandburns commented
@k8s-bot bazel test this

2017-02-28 04:43 UTC, brendandburns commented
@JiangtianLi can you add a descriptive title for this PR (e.g. "support dns search in windows proxy")

Thanks
--brendan

2017-02-28 04:51 UTC, JiangtianLi commented
@brendandburns Thanks for the reminder. I have modified the title.

2017-02-28 13:14 UTC, michmike commented
cc: @pires as well for a review

2017-02-28 21:33 UTC, brendandburns commented
/lgtm

2017-02-28 21:33 UTC, brendandburns approved these changes

2017-02-28 23:13 UTC, brendandburns commented
@k8s-bot kops aws e2e test this

2017-03-01 15:48 UTC, merged