Refactor glusterfs code for pv creation and fetching cluster nodes.
kubernetes/kubernetes pull request #41628
Opened 2017-02-17 07:52 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2017-02-17 07:53 UTC, humblec commented
@jsafrane @rootfs PTAL.

2017-02-17 17:11 UTC, gnufied commented
@k8s-bot test this

2017-02-17 22:49 UTC, rootfs commented
/approve

2017-02-20 04:03 UTC, humblec commented
@k8s-bot test this

2017-02-20 09:39 UTC, jsafrane commented
@k8s-bot test this

2017-02-20 12:41 UTC, humblec commented
@jsafrane Thanks :)..

2017-02-20 16:25 UTC, humblec commented
@thockin can you please take a look at this PR ?

2017-02-22 09:02 UTC, jsafrane commented
@k8s-bot test this

2017-02-22 10:59 UTC, humblec commented
Looks to be a spurious failure.. I will resend the patchset and trigger the tests again. Thanks @jsafrane

2017-02-22 11:45 UTC, jsafrane commented
@k8s-bot test this

2017-02-22 12:34 UTC, obnoxxx requested changes
The actual content looks good. But I suggest the following changes to be made:
- I suggest a slightly different commit message: IMHO It should read something like "Factor new GetClusterNodes() out of CreateVolume()".
- The newline removals (and additions) are not related to the description of this patch and should be a different patch (if at all). We should not sneak in changes under the hood!
- I would argue that the newlines were added for readability and should remain, except for very few that I marked in my comment.

2017-02-22 12:34 UTC, obnoxxx commented on pkg/volume/glusterfs/glusterfs.go
> -
First of all, these empty-line removals are not related to the change described in the commit message, and should not be sneaked in. *If* they are to be applied, they should be a patch of their own.

Secondly, I put several of those newlines into the text to increase readability. I think grouping blocks and lines of code by inserting newlines *greatly* increases the readability of code. I therefore request most of them to remain. If there is a "formatting policy I don't know of", I would be willing to disuss... :-)

2017-02-22 12:34 UTC, obnoxxx commented on pkg/volume/glusterfs/glusterfs.go
> +
This newline after the function head is imho extra and should *not* be added.

2017-02-22 12:34 UTC, obnoxxx commented on pkg/volume/glusterfs/glusterfs.go
> -
ack. on this removal. but in a different commit.

2017-02-22 12:34 UTC, obnoxxx commented on pkg/volume/glusterfs/glusterfs.go
> +}
empty line after the funtion is missing.

2017-02-22 15:35 UTC, jsafrane commented
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this

2017-02-22 17:17 UTC, humblec commented on pkg/volume/glusterfs/glusterfs.go
> +}
Done.

2017-02-22 17:18 UTC, humblec commented
Addressed the comments. I will send a separate PR for empty line cleanup.

2017-02-22 22:32 UTC, obnoxxx commented
Thanks @humblec , this patch looks clean now to me.

2017-02-23 08:57 UTC, jsafrane commented
@k8s-bot test this

2017-02-23 09:18 UTC, humblec commented
@jsafrane the unit integration failure looks be a spurious one to me. :(

2017-02-23 11:27 UTC, jsafrane commented
@k8s-bot unit test this

2017-02-23 12:40 UTC, humblec commented
@jsafrane Thanks.. All the tests are passed.!

2017-02-23 12:42 UTC, jsafrane commented
/lgtm

2017-02-26 16:10 UTC, merged