Update kubeadm token to work as expected
kubernetes/kubernetes pull request #41663
Opened 2017-02-17 21:46 UTC by luxas

**What this PR does / why we need it**:

Follows up: https://github.com/kubernetes/kubernetes/pull/41509

Updates `kubeadm token` to work as discussed in https://docs.google.com/document/d/1deJYPIF4LmhGjDVaqrswErIrV7mtwJgovtLnPCDxP7U/edit#
Promotes the command from the `ex` subcommand which now is named `alpha` for clarity. (This will later become `kubeadm alpha phase`)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@dmmcquay @jbeda @mikedanese @errordeveloper @pires

2017-02-17 22:22 UTC, dmmcquay requested changes
Need to update tests and some minor comments.

2017-02-17 22:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +			kubeadmutil.CheckErr(err)
same

2017-02-17 22:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +	td := &kubeadmapi.TokenDiscovery{}
Why don't you try to create the token using `td.ID, td.Secret, err = tokenutil.ParseToken(token)`, and if it returns an err, you then try to create the token using generate.  Too many checks, you could make it read more clearly.

2017-02-17 22:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +			// Skip those that hasn't this usage set to true
Edit comment "Skip those that don't have this usage set to true"

2017-02-17 22:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +	fmt.Fprintf(out, "bootstrap token with id %q deleted\n", tokenId)
are we moving away from having [foo] labels?

2017-02-17 22:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +		"usages", kubeadmconstants.DefaultTokenUsages, "The functions this token can be used for.")
I don't like the word 'usages' here. Sounds strange. Anyone agree?

2017-02-17 22:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +				continue
Why don't we return an error if the time parsing fails? It seems like this function never returns an error that isn't nil inside the iteration of Secret Items.

2017-02-17 22:22 UTC, dmmcquay commented on cmd/kubeadm/app/util/token/tokens.go
> +	TokenRegexpString   = "^([a-z0-9]{6})\\.([a-z0-9]{16})$"
You need to update the tests. They fail because they were expecting a ':'

2017-02-17 22:26 UTC, dmmcquay requested changes

2017-02-17 22:26 UTC, dmmcquay commented on cmd/kubeadm/app/phases/token/bootstrap.go
> +	secretName := kubeadmconstants.BootstrapTokenSecretPrefix + d.ID
I prefer fmt.Sprintf, it scales better with codebase.

2017-02-17 22:32 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +		"usages", kubeadmconstants.DefaultTokenUsages, "The functions this token can be used for.")
It builds on the terminology used for x509 certs -- https://en.wikipedia.org/wiki/X.509#Extensions_informing_a_specific_usage_of_a_certificate.

2017-02-17 22:36 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +		"usages", kubeadmconstants.DefaultTokenUsages, "The functions this token can be used for.")
fair enough! I just thought the plural of it sounded strange. But, if there is support, totally fine.

2017-02-17 22:51 UTC, jbeda requested changes
Looks pretty good to me.  The biggest problem I have is that we are making assumptions on the secret name.  The spec currently says that name is suggested but not required.

The signer and authenticator don't make this assumption.  In addition, `kubeadm token list` doesn't either.

So -- we should do one of the following:
1) Check this in as-is and have a bug/TODO to fix it.  Let's not let that go too long.
2) Fix it now.
3) Redefine it so that the name is required.  We'd probably want to make the server side code validate things too.  And have `kubeadm token list` warn if the name doesn't match the contents.

I prefer 2 but could live with 1.  3 seems wonky.

2017-02-17 22:51 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +			kubeadmutil.CheckErr(err)
Regardless, it is a common pattern in many of the utilities in k8s.  I see this in `kubectl` and `kubefed` also.  If we want to change it it should probably be done in a different PR.

2017-02-17 22:51 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +	td := &kubeadmapi.TokenDiscovery{}
If someone passes in a malformed token we should error explicitly.  If we instead ignore that and generate a random token they may think that everything worked until they try and used their malformed token elsewhere.

I'd rather fail early with clear message if the user passes a malformed token.

2017-02-17 22:51 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +				continue
IMO, if one secret is malformed we want to be able to print out the rest of them.  If we return an error here then one bad secret spoils everything.

2017-02-17 22:51 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +	tokenSecretName := kubeadmconstants.BootstrapTokenSecretPrefix + tokenId
I'd rather not take a dependency on the name and instead iterate over the secrets finding the token.  The name of the secret is really just a suggestion.  If someone uses another tool to create secrets we may end up in a situation where a secret shows up with `kubeadm token list` but `kubeadm token delete` won't delete it.  That would be frustrating and confusing.

2017-02-17 22:51 UTC, jbeda commented on cmd/kubeadm/app/phases/token/bootstrap.go
> +	secretName := kubeadmconstants.BootstrapTokenSecretPrefix + d.ID
Same thing here -- we should really make this look at all secrets vs making assumptions about name.

2017-02-17 22:56 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/token.go
> +	td := &kubeadmapi.TokenDiscovery{}
I don't mean to not error out, I just didn't like the logic of the code. Just use the error checking built into the function calls.

2017-02-21 08:47 UTC, pires commented
The only question I have is about dropping `:` for `.` as this was causing problems when parsing URLs. Also, the tests don't pass so I'm sure you are not running them on your side and you should.

2017-02-21 15:44 UTC, jbeda commented
@pires -- where was the token showing up in URLs?  Sensitive secrets should generally not show up in a URL as they have a history of being cached and exposed.  Or was this with the fake-o `token://` URL?  On going talk of kubeadm UX in this area is happening in https://github.com/kubernetes/community/pull/381.

2017-02-21 15:49 UTC, luxas commented
@jbeda It was just a note that what we're proposing in https://github.com/kubernetes/community/pull/381 isn't implemented for `kubeadm join` yet. 
But @dmmcquay is on that. He will come up with a PR for that soon I think.

@pires Of course I'm running tests, and I'm implementing new ones as well.
On the other hand I'm sorry for not marking this WIP during the time we discussed the details in  https://github.com/kubernetes/community/pull/381. Will do so now. Soon, a new changeset of this PR will be up with all the latest and greatest content.

2017-02-21 16:16 UTC, pires commented
@jbeda `kubeadm join --discovery token://<token>@node`.

2017-02-22 18:26 UTC, jbeda approved these changes
This LGTM.  Only real problem is where we pull kubeconfig from.  We will want to allow `kubeadm token` to run against a remote cluster.  But that can be another PR.

2017-02-22 18:26 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +	tokenSecretName := kubeadmconstants.BootstrapTokenSecretPrefix + tokenId
This is stale now as we decided to make the name required.

2017-02-22 22:08 UTC, luxas commented
@jbeda Rebased and updated to implement the latest design decisions in https://github.com/kubernetes/community/pull/381

Even though a single test or something might fail -- please give your lgtm if possible and I'll self-apply later

(Jenkins is overloaded atm, so we don't have a clue about tests currently)

2017-02-23 08:05 UTC, luxas commented
@k8s-bot test this

2017-02-23 20:46 UTC, luxas commented
I'll rebase as soon as https://github.com/kubernetes/kubernetes/pull/41857 merges.

@jbeda PTAL and please /lgtm, I'll take care of rebasing tomorrow, but the faster you can lgtm the better

2017-02-23 22:41 UTC, luxas commented on cmd/kubeadm/app/cmd/token.go
> +	fmt.Fprintf(out, "bootstrap token with id %q deleted\n", tokenId)
not generally, but it doesn't make sense to have it for only one line

2017-02-23 22:44 UTC, jbeda approved these changes
Mostly nits.  LGTM

2017-02-23 22:44 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +		"description", "", "A human-friendly description what this token is used for.")
reword? "A human friendly description of how this token is used."

2017-02-23 22:44 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +		"usages", kubeadmconstants.DefaultTokenUsages, "The functions this token can be used for.")
reword? "functions" sounds like programing language function. "The ways in which this token can be used"

2017-02-23 22:44 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +		Use:   "create [token]",
The `[token]` parameter is undefined in the help text.  I'd do `create [token-value]` and then change the description to document that "The token-value is the actual token to write.  This should be a securely generated random token of the form [a-z0-9]{6}.[a-z0-9]{16}."

2017-02-23 22:44 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +		Use:   "delete [token]",
nit: Same comment on token param here.

2017-02-23 22:44 UTC, jbeda commented on cmd/kubeadm/app/cmd/token.go
> +	for _, secret := range secrets.Items {
nit+: We should skip/ignore/warn on tokens that don't match our naming requirement.

2017-02-23 22:44 UTC, jbeda commented
/lgtm

2017-02-24 16:37 UTC, dmmcquay approved these changes
/lgtm

2017-02-27 14:03 UTC, luxas commented
@k8s-bot non-cri e2e test this

2017-02-27 14:31 UTC, luxas commented
@k8s-bot cvm gce e2e test this

2017-02-27 16:53 UTC, dmmcquay commented
@k8s-bot non-cri e2e test this

2017-02-27 20:45 UTC, merged

2017-10-30 17:21 UTC, alexellis commented
@luxas is there a way to generate the whole join command? I feel like I have to reset the entire cluster to be able to "reach" the magic string i.e.

```
  kubeadm join --token TOK MASTER_IP:6443 --discovery-token-ca-cert-hash sha256:HASH
```

This is very easy with Swarm - `docker swarm join-token worker`... would be great if you could document or provide a way to do this with `kubeadm`.

2017-10-30 20:25 UTC, luxas commented
@alexellis Please open a new issue for this and cc @mattmoyer and @jamiehannaford please.
TL;DR; the token can be fetched from `kubeadm token list`, the CA hash with `openssl` (as documented) and the master IP from the cluster.

Room for improvement indeed.

2017-11-04 22:11 UTC, 1605200517 commented
https://github.com/kubernetes/kubernetes/issues/55108 @luxas @alexellis