kubeadm: Add a --ca-cert-path flag to kubeadm join
kubernetes/kubernetes pull request #41721
Opened 2017-02-19 19:01 UTC by luxas

**What this PR does / why we need it**:

This PR makes it possible to customize where the CA file is written

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```
@pires @mikedanese @dmmcquay @jbeda @errordeveloper

2017-02-20 00:16 UTC, mikedanese commented
What issue is this related to? Have people requested customizing this?

2017-02-20 19:04 UTC, luxas commented
> Have people requested customizing this?

@mikedanese No, because no one is using this yet. But I think it makes sense to drop the envparam dependency of `kubeadm join` and have this CA cert path configurable.
Is it possible for you to approve this? I have the full proposal for kubeadm here: https://github.com/kubernetes/kubeadm/pull/156

2017-02-20 19:18 UTC, luxas commented
@pires @mikedanese Updated

2017-02-21 08:45 UTC, pires requested changes

2017-02-21 08:45 UTC, pires commented on cmd/kubeadm/app/cmd/join.go
> +		"path where the ca certificate for the master should be stored",
CA certificate for the cluster not the master.

2017-02-21 14:12 UTC, luxas commented
@k8s-bot unit test this

2017-02-21 16:18 UTC, pires approved these changes
The code looks good but I agree we're adding functionality that originated in a WIP document (kubeadm phases design proposal) and not from actual need.

2017-02-21 17:14 UTC, mikedanese commented on hack/verify-flags/exceptions.txt
> +cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py:    ca_cert_path = layer_options.get('ca_certificate_path')
??? where did these come from?

2017-02-21 17:14 UTC, mikedanese commented
/lgtm

2017-02-21 17:18 UTC, luxas commented on hack/verify-flags/exceptions.txt
> +cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py:    ca_cert_path = layer_options.get('ca_certificate_path')
No idea. Autogenerated code, verify failed on this :)

2017-02-21 18:19 UTC, luxas commented
@k8s-bot verify test this

2017-02-21 21:15 UTC, ixdy commented on hack/verify-flags/exceptions.txt
> +cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py:    ca_cert_path = layer_options.get('ca_certificate_path')
oh, probably adding the `ca-cert-path` flag made the script think that these old usages were incorrect.

I kinda hate `verify-flags`. its behavior is quite mysterious.

2017-02-21 21:43 UTC, luxas commented
@k8s-bot verify test this
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

2017-02-21 21:51 UTC, luxas commented on hack/verify-flags/exceptions.txt
> +cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py:    ca_cert_path = layer_options.get('ca_certificate_path')
Yeah, maybe we should just remove it... don't know even what it's used for...

2017-02-21 21:52 UTC, luxas commented
@ixdy Do you know why the verify test constantly fails like this:
```
I0221 13:33:40.386]   godep: dirty working tree (please commit changes): /tmp/verify-staging-client-go.YCzei/src/k8s.io/kubernetes/pkg/client/listers/policy/v1beta1
I0221 13:33:40.899]   godep: dirty working tree (please commit changes): /tmp/verify-staging-client-go.YCzei/src/k8s.io/kubernetes/pkg/client/listers/rbac/v1alpha1
I0221 13:33:40.899]   godep: dirty working tree (please commit changes): /tmp/verify-staging-client-go.YCzei/src/k8s.io/kubernetes/pkg/client/listers/rbac/v1beta1
I0221 13:33:40.900]   godep: dirty working tree (please commit changes): /tmp/verify-staging-client-go.YCzei/src/k8s.io/kubernetes/pkg/client/listers/storage/v1beta1
I0221 13:33:40.901]   godep: dirty working tree (please commit changes): /tmp/verify-staging-client-go.YCzei/src/k8s.io/kubernetes/pkg/util
I0221 13:33:40.902]   godep: dirty working tree (please commit changes): /tmp/verify-staging-client-go.YCzei/src/k8s.io/kubernetes/pkg/util/parsers
I0221 13:33:40.904]   godep: error loading dependencies
I0221 13:33:45.406] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	221s
```

cc @deads2k @sttts @kubernetes/sig-api-machinery-misc

2017-02-21 22:02 UTC, ixdy commented
no idea. cc @caesarxuchao

2017-02-22 10:36 UTC, luxas commented
@k8s-bot cvm gke e2e test this
@k8s-bot verify test this
@k8s-bot unit test this
@k8s-bot non-cri e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gke e2e test this

2017-02-22 18:05 UTC, caesarxuchao commented
Can you add a `git diff` at the beginning of hack/verify-staging-client-go.sh to see what files are changed? I guess another verification script didn't clean up the changes it made.

cc @sttts

2017-02-22 18:07 UTC, sttts commented
@caesarxuchao will take a look tomorrow.

2017-02-23 08:03 UTC, luxas commented
@k8s-bot ok to test

2017-02-23 20:20 UTC, luxas commented
rebased once again... hopefully https://github.com/kubernetes/kubernetes/issues/41986 fixes the verification flake

2017-02-23 20:22 UTC, ixdy commented
/approve

I still hate verify-flags

2017-02-23 20:24 UTC, luxas commented
@ixdy Yeah. What's wrong with Jenkins BTW?

2017-02-23 20:25 UTC, ixdy commented
@luxas too many builds that take too long and too many open PRs.

2017-02-23 20:27 UTC, luxas commented
@ixdy I see

2017-02-24 08:49 UTC, sttts commented
I believe to have found why the godep call fails: we have the following unstaged change in the tree. Not sure we have any error reporting for that in CI. We should. But of course hack/verify-update-client-go.sh should not fall over it.
```
+ git status
I0223 16:54:14.760]   On branch test
I0223 16:54:14.760]   Changes not staged for commit:
I0223 16:54:14.760]     (use "git add <file>..." to update what will be committed)
I0223 16:54:14.760]     (use "git checkout -- <file>..." to discard changes in working directory)
I0223 16:54:14.760]   
I0223 16:54:14.761]   	modified:   ../../../../cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.defaults.go
I0223 16:54:14.761]   
I0223 16:54:14.761]   Untracked files:
I0223 16:54:14.761]     (use "git add <file>..." to include in what will be committed)
```

2017-02-24 09:19 UTC, luxas commented
@sttts I'm so grateful for that finding! Thank you!
Now this should be fixed... :)

2017-02-24 12:53 UTC, luxas commented
@k8s-bot gce etcd3 e2e test this

2017-02-24 17:13 UTC, luxas commented
@k8s-bot kubemark e2e test this

2017-02-25 11:56 UTC, merged