Be able to specify the timeout to wait for pod for kubectl logs/attach
kubernetes/kubernetes pull request #41813
Opened 2017-02-21 16:20 UTC by shiywang

Fixes https://github.com/kubernetes/kubernetes/issues/41786
@soltysh @kargakis ptal, thanks

2017-02-21 16:32 UTC, kargakis commented
@kubernetes/sig-cli-api-reviews

2017-02-21 20:51 UTC, fabianofranz commented
I'd suggest `--pod-running-timeout`, `--pod-wait-timeout`, `--first-pod-timeout`, `--pod-readiness-timeout`.

2017-02-21 20:52 UTC, fabianofranz commented on pkg/kubectl/cmd/attach.go
>  	// TODO support UID
This TODO is about the ContainerName flag.

2017-02-21 20:55 UTC, fabianofranz commented on pkg/kubectl/cmd/attach.go
> +	if p.GetPodTimeOut == 0 {
Make it check for `> 0` and the message something like "... must be higher than zero".

2017-02-21 20:56 UTC, fabianofranz commented on pkg/kubectl/cmd/attach.go
> +	cmd.Flags().Int64Var(&options.GetPodTimeOut, "get-pod-timeout", 60, "Specify the timeout (in seconds) of get first pod")
"The length of time (in seconds) to wait until at least one pod is running"

2017-02-22 03:19 UTC, shiywang commented
flag change to first one, all comments updated
> I'd suggest --pod-running-timeout, --pod-wait-timeout, --first-pod-timeout, --pod-readiness-timeout.

2017-02-22 18:17 UTC, fabianofranz commented
@k8s-bot ok to test

2017-02-22 18:45 UTC, fabianofranz commented
@k8s-bot bazel test this

2017-02-23 06:08 UTC, shiywang commented
@fabianofranz @kargakis @soltysh updated, PTAL, thanks

2017-02-23 20:43 UTC, soltysh requested changes

2017-02-23 20:43 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> -	// TODO support UID
I'm not sure this TODO is not valid anymore, I'd leave it here.

2017-02-23 20:43 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> +	cmd.Flags().Int64Var(&options.GetPodTimeOut, "pod-running-timeout", 60, "The length of time (in seconds) to wait until at least one pod is running")
Turn this into a helper, see: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/helpers.go

2017-02-23 20:43 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> +	if p.GetPodTimeOut <= 0 {
Again, helper, which would save changing this, again see: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/helpers.go

2017-02-24 06:23 UTC, shiywang commented on pkg/kubectl/cmd/attach.go
> -	// TODO support UID
see comments above
>  fabianofranz 2 days ago Contributor
This TODO is about the ContainerName flag.

2017-02-24 06:24 UTC, shiywang commented on pkg/kubectl/cmd/attach.go
> +	if p.GetPodTimeOut <= 0 {
ok, will do that

2017-02-24 10:51 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> -	// TODO support UID
Ok, sorry for the noise.

2017-02-26 08:57 UTC, shiywang commented
@soltysh add a `GetValidatedPodRunningTimeOut` functions in helper, PTAL

2017-02-27 11:24 UTC, soltysh requested changes
Still not quite what I imagined.

2017-02-27 11:24 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> +	cmd.Flags().DurationVar(&options.GetPodTimeOut, "pod-running-timeout", defaultPodAttachTimeout, "The length of time (like 5s, 2m, or 3h, higher than zero) to wait until at least one pod is running")
I wanted this being a helper function, as well. This will make sure we have the same name everywhere.

2017-02-27 11:24 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> +	p.GetPodTimeOut, err = cmdutil.GetValidatedPodRunningTimeOut(cmd, p.GetPodTimeOut)
This needs to be:
```go
p.GetPodTimeOut, err = cmdutil.GetPodRunningTimoutFlag(cmd)
```

2017-02-27 11:24 UTC, soltysh commented on pkg/kubectl/cmd/clusterinfo_dump.go
> +	timeout, err := cmdutil.GetValidatedPodRunningTimeOut(cmd, timeout)
This needs to look like this:
```go
timeout, err := cmdutil.GetPodRunningTimeoutFlag(cmd)
if err != nil {
    return cmd.UsageError(cmd, err.Error())
}
```

2017-03-04 15:49 UTC, shiywang commented
@soltysh sorry for my misunderstood, updated, please take a look again, thanks

2017-03-05 06:27 UTC, shiywang commented
@k8s-bot bazel test this

2017-03-05 06:27 UTC, shiywang commented
@k8s-bot unit test this

2017-03-05 06:27 UTC, shiywang commented
@k8s-bot gci gce e2e test this

2017-03-05 10:23 UTC, shiywang commented
@soltysh updated, ptal

2017-03-08 08:47 UTC, soltysh approved these changes

2017-03-08 08:47 UTC, soltysh commented
/lgtm

2017-03-08 19:32 UTC, fabianofranz commented on pkg/kubectl/cmd/attach.go
> +	p.GetPodTimeOut, err = cmdutil.GetPodRunningTimoutFlag(cmd)
*Timeout

2017-03-08 19:34 UTC, fabianofranz commented on pkg/kubectl/cmd/attach.go
> +	GetPodTimeOut time.Duration
Make camel case concise with `GetPodRunningTimeoutFlag`, e.g. change it here to `GetPodTimeout`.

2017-03-08 19:35 UTC, fabianofranz commented on pkg/kubectl/cmd/util/helpers.go
> +func AddPodRunningTimeOutFlag(cmd *cobra.Command, defaultTimeout time.Duration) {
Same camel case comment here.

2017-03-08 19:36 UTC, fabianofranz commented
nits then it's good to go.

2017-03-11 08:07 UTC, shiywang commented
@fabianofranz  updated, ptal, thanks

2017-03-13 19:44 UTC, fabianofranz commented on pkg/kubectl/cmd/logs.go
> +	o.GetPodTimeout, err = cmdutil.GetPodRunningTimoutFlag(cmd)
This fits better in `Complete` instead of here in `Validate`. In which case you'll not need to pass `cmd` to the `Validate` method.

2017-03-13 19:45 UTC, fabianofranz commented on pkg/kubectl/cmd/logs.go
> +	if err != nil {
Since this is the last thing you do you don't need this check, just `return err`.

2017-03-13 19:45 UTC, fabianofranz commented on pkg/kubectl/cmd/util/helpers.go
> +func GetPodRunningTimoutFlag(cmd *cobra.Command) (time.Duration, error) {
Typo

2017-03-13 19:46 UTC, fabianofranz commented on pkg/kubectl/cmd/attach_test.go
> +			name:        "invaild get pod timeout value",
typo

2017-03-14 14:47 UTC, shiywang commented
@k8s-bot bazel test this

2017-03-14 14:47 UTC, shiywang commented
@k8s-bot unit test this

2017-03-14 14:52 UTC, shiywang commented
@k8s-bot bazel test this

2017-03-14 14:53 UTC, shiywang commented
@k8s-bot kops aws e2e test this

2017-03-14 15:50 UTC, shiywang commented
@k8s-bot kops aws e2e test this

2017-03-14 17:33 UTC, fabianofranz commented
/approve
/lgtm

2017-03-25 02:04 UTC, merged