kubelet: cm: refactor QoS logic into seperate interface
kubernetes/kubernetes pull request #41833
Opened 2017-02-21 20:24 UTC by sjenning

This commit has no functional change.  It refactors the QoS cgroup logic into a new `QOSContainerManager` interface to allow for better isolation for QoS cgroup features coming down the pike.

This is a breakout of the refactoring component of my QoS memory limits PR which will need to be rebased on top of this:
https://github.com/kubernetes/kubernetes/pull/41149

@vishh @derekwaynecarr

2017-02-21 20:57 UTC, derekwaynecarr commented
Per our chat @vishh , I will take over review of this PR.

2017-02-21 21:29 UTC, derekwaynecarr requested changes
few minor nits, update then I will tag.

2017-02-21 21:29 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager.go
> +	Start(*v1.Node, func() []*v1.Pod) error
can you create a type in kubelet/cm that is 

```
// ActivePodsFunc returns pods bound to the kubelet that are active (i.e. non-terminal state)
type ActivePodsFunc func() []*v1.Pod
```

so the signature is clear about the call expects?

2017-02-21 21:29 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager.go
> +	// UpdateQOSCgroups returns the names of top level QoS containers
godoc is wrong, it performs housekeeping updates to ensure that the top level QoS containers have their desired state.  also note that this operation is thread-safe.

2017-02-21 21:29 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager.go
> +	// UpdateQOSCgroups returns the names of top level QoS containers
or needs to be.

2017-02-21 21:29 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager_linux.go
> +func (cm *containerManagerImpl) setupNode(getPods func() []*v1.Pod) error {
activePodsFn ActivePodsFunc as argument.

2017-02-21 21:29 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager_linux.go
> +func (cm *containerManagerImpl) Start(node *v1.Node, getPods func() []*v1.Pod) error {
same here, take an ActivePodsFunc, and make sure active name propagates.

2017-02-21 21:29 UTC, derekwaynecarr commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +func (m *qosContainerManagerImpl) Start(nodeInfo *v1.Node, getPods func() []*v1.Pod) error {
same here..

2017-02-21 21:29 UTC, derekwaynecarr commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +	getPods           func() []*v1.Pod
activePods

2017-02-21 22:19 UTC, derekwaynecarr commented
@k8s-bot -- lets try now!

2017-02-22 02:09 UTC, derekwaynecarr commented
@k8s-bot test this

2017-02-22 15:01 UTC, sjenning commented
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this

2017-02-22 22:26 UTC, sjenning commented
@k8s-bot test this

2017-02-23 00:49 UTC, sjenning commented
@k8s-bot gce etcd3 e2e test this

2017-02-23 21:54 UTC, derekwaynecarr commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +	qosConfigs := map[v1.PodQOSClass]*CgroupConfig{
do you mind if we add this in a follow-on and just have this return nil after the lock/defer lock call?

2017-02-23 21:55 UTC, sjenning commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +	qosConfigs := map[v1.PodQOSClass]*CgroupConfig{
sure

2017-02-23 21:55 UTC, derekwaynecarr commented
one minor request so the change is entirely structural, we can do the writes in our follow-on for memory/cpu but at least we can get the scaffolding in asap.

2017-02-24 02:14 UTC, sjenning commented
@k8s-bot gce etcd3 e2e test this
@k8s-bot non-cri e2e test this
@k8s-bot non-cri node e2e test this

2017-02-24 03:23 UTC, derekwaynecarr commented on pkg/kubelet/kubelet.go
> +			if err := kl.containerManager.UpdateQOSCgroups(); err != nil {
@sjenning -- this is the wrong order... this should be before EnsureExists, not after.  sorry for just catching this.

2017-02-24 03:27 UTC, derekwaynecarr commented on pkg/kubelet/kubelet.go
> +			if err := kl.containerManager.UpdateQOSCgroups(); err != nil {
i also wonder if we should change the pcm.EnsureExists step for now to the following:

if !pcm.Exists {
  updateQOSCgroups()
  pcm.EnsureExists()
}

in this way we don't attempt any update when its not necessary.

2017-02-24 03:29 UTC, derekwaynecarr commented on pkg/kubelet/kubelet_pods.go
> +	if err := kl.containerManager.UpdateQOSCgroups(); err != nil {
this needs to be after KillPod(), not before.

2017-02-24 04:35 UTC, sjenning commented
@derekwaynecarr updated

2017-02-24 08:41 UTC, vishh reviewed
I like the general structure this PR is introducing. Nice work @sjenning 👍 
Added a few comments.

2017-02-24 08:41 UTC, vishh commented on pkg/kubelet/cm/container_manager.go
> +	Start(*v1.Node, ActivePodsFunc) error
I don't like this cyclic dependency.
Kubelet object <-> container manager object

2017-02-24 08:41 UTC, vishh commented on pkg/kubelet/cm/container_manager.go
> +	UpdateQOSCgroups() error
nit: I'd avoid including Cgroups in here. How about `UpdateQoSContainers` ?

2017-02-24 08:41 UTC, vishh commented on pkg/kubelet/cm/container_manager_unsupported.go
>  var _ ContainerManager = &unsupportedContainerManager{}
I wonder if we can use the `Stub` implementation instead of having to maintain an `unsupported` version

2017-02-24 08:41 UTC, vishh commented on pkg/kubelet/cm/container_manager.go
> +	Start(*v1.Node, ActivePodsFunc) error
Let's also group the input arguments into a struct. Makes it easy to add fields in the future.

2017-02-24 08:41 UTC, vishh commented on pkg/kubelet/cm/container_manager.go
> +	UpdateQOSCgroups() error
Is this method meant to synchronous?

2017-02-24 16:52 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager.go
> +	Start(*v1.Node, ActivePodsFunc) error
i am confused on why it is cyclic?  the type is local to this package?

2017-02-24 17:54 UTC, vishh commented
I'd prefer https://github.com/kubernetes/kubernetes/pull/41234 to go in before this.

2017-02-24 17:56 UTC, derekwaynecarr commented
@vishh -- as long as we realize they all need to go in before we ship, i am fine staging in any order.  its a lot of prs to land, so if we can just get them tagged by mon and we can then rebase, that is fine w/ me too.

2017-02-27 20:40 UTC, sjenning commented
rebased on top of https://github.com/kubernetes/kubernetes/pull/41234 that will hopefully merge soon

2017-02-27 21:15 UTC, derekwaynecarr approved these changes

2017-02-27 21:15 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager.go
> +	UpdateQOSCgroups() error
i know @vishh asked that this be called "Containers".

similar to the discussion on node allocatable, i am not going to hold up this pr on naming conventions.

we can fix that across the board in a later pr.

right now "Cgroups" is consistent with "PodContainerManager" terminology.

2017-02-27 21:15 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager.go
> +	UpdateQOSCgroups() error
i also want to go on the record that "container" is not defined in the kernel, but "cgroup" is.  and container is an overloaded term in a project like this.

2017-02-27 21:15 UTC, derekwaynecarr commented on pkg/kubelet/cm/container_manager.go
> +	Start(*v1.Node, ActivePodsFunc) error
i think we can move this to a struct in a follow-on.  i do not want to hold this pr on that change.

2017-02-27 21:15 UTC, derekwaynecarr commented
any nits can be handled in a follow-on.  i am tagging this /lgtm and marking do-not-merge to ensure that node allocatable pr lands first.

2017-02-28 01:51 UTC, sjenning commented
Rebased on top of node alloc PR w/ systemd fixes and it works.  Add to add new commit to work with new node allocatable code https://github.com/kubernetes/kubernetes/pull/41833/commits/ee2dcce48c5599734aaebc72aed20f97c8924122

The changes mostly center around the `cgroupRoot` being modified from `nodeConfig.CgroupRoot` and the `kubepods` cgroup not being created at constructor time, but rather at `setupNode()` time, meaning the sanity checks in `NewQOSContainerManager()` needed to move to `Start()`.

2017-02-28 19:34 UTC, derekwaynecarr commented
/approve
/lgtm

2017-03-01 09:44 UTC, merged