bump version numbers for heapster/influxdb/grafana images
kubernetes/kubernetes pull request #41925
Opened 2017-02-22 21:51 UTC by KarolKraskiewicz

**What this PR does / why we need it**:
It updates version of monitoring components (heapster/influxdb/grafana) to the latest one used by heapster

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
[e2e/monitoring.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/monitoring.go) test seems to be passing without modifications

**Release note**:

```release-note
```

2017-02-23 05:50 UTC, piosz commented
Can you please bump the version for other configurations (google, googleinfluxdb, standalone)?

It would be great to bump also InfluxDB client in [godeps](https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json#L1616) (this may require changes in monitoring.go e2e), though this can be done in a follow up PR assuming monitoring e2e test will pass.

2017-02-23 05:50 UTC, piosz commented
@k8s-bot ok to test

2017-02-23 21:20 UTC, piosz requested changes
Please squash commits.

2017-02-23 21:20 UTC, piosz commented on cluster/addons/cluster-monitoring/google/heapster-controller.yaml
> +        - image: gcr.io/google_containers/heapster:v1.3.0-beta.1
Should be `gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1`. The same in the other places.

2017-02-23 22:05 UTC, KarolKraskiewicz commented on cluster/addons/cluster-monitoring/google/heapster-controller.yaml
> +        - image: gcr.io/google_containers/heapster:v1.3.0-beta.1
Thanks for pointing this. It is ready.

2017-02-24 08:59 UTC, piosz approved these changes

2017-02-24 08:59 UTC, piosz commented
/lgtm
/approve

2017-02-24 09:00 UTC, piosz commented
As a follow up can you please bump [InfluxDB client version](https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json#L1616) to 1.1.1?

2017-02-24 09:01 UTC, piosz commented
Thanks for the change!

2017-02-25 19:51 UTC, piosz commented
/lgtm

2017-02-27 02:08 UTC, merged