PV upgrade test
kubernetes/kubernetes pull request #42019
Opened 2017-02-23 22:25 UTC by msau42

**What this PR does / why we need it**:
This PR adds a PV upgrade test to the new upgrade test framework.  Before, this test had to be done manually.  Currently the upgrade test framework only works on the GCE environment, so I plan to add support for other providers later.  In order to write the test, I had to modify and refactor some volume test util libraries.  I reran the impacted tests to make sure they still passed.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
It's probably easier to review the two commits separately.  I split it up into the refactor changes, and the upgrade test changes.

**Release note**:

NONE

cc @saad-ali @krousey

2017-02-23 22:33 UTC, krousey requested changes

2017-02-23 22:33 UTC, krousey commented on test/e2e/upgrades/persistent_volumes.go
> +	framework.SkipUnlessProviderIs("gce")
Could this also work with GKE? If not, we have to still run this test manually for GKE.

2017-02-23 22:33 UTC, krousey commented on test/e2e/upgrades/persistent_volumes.go
> +	PVTestFile string = "/mnt/pv_upgrade_test"
Any reason for these identifiers to be exported from the package?

2017-02-23 22:33 UTC, krousey commented on test/e2e/upgrades/persistent_volumes.go
> +func (t *PersistentVolumeUpgradeTest) createGCEVolume() *v1.PersistentVolumeSource {
There's no need for this to be a method.

2017-02-23 22:46 UTC, msau42 commented on test/e2e/upgrades/persistent_volumes.go
> +func (t *PersistentVolumeUpgradeTest) createGCEVolume() *v1.PersistentVolumeSource {
When I add AWS support, I think it will be better to separate them into separate methods.

2017-02-24 00:28 UTC, msau42 commented
@k8s-bot verify test this

2017-02-24 01:31 UTC, msau42 commented
@k8s-bot gce etcd3 e2e test this

2017-02-24 18:27 UTC, krousey commented
/approve
/lgtm

2017-02-24 18:28 UTC, krousey approved these changes

2017-02-27 08:16 UTC, merged