Ingress-glbc upgrade tests
kubernetes/kubernetes pull request #42020
Opened 2017-02-23 23:24 UTC by nicksardo

Basically #41676 but with some fixes and added comments.  @bprashanth has been away this week and it's desirable to have this in before code freeze.

2017-02-23 23:53 UTC, krousey requested changes
There were a lot of names in the moved utility file that should be changed to be more specific now that they're in framework. Like createSecret should probably be something like "createIngressTLSSecret".

There were too many to comment on each and I couldn't comment on ones where there was no change.

2017-02-23 23:53 UTC, krousey commented on test/e2e/framework/ingress_utils.go
> +func CleanupGCE(gceController *GCEIngressController) {
Since this is moving to the framework package, it probably needs a more descriptive name. Like CleanupGCEIngressController.

2017-02-23 23:53 UTC, krousey commented on test/e2e/upgrades/ingress.go
> +	// jig handles all Kubernetes testing logic
Looks like you might need a `framework.SkipUnlessProviderIs("gce", "gke")`

2017-02-23 23:53 UTC, krousey commented on test/e2e/upgrades/ingress.go
> +	framework.ExpectNoError(framework.PollURL(fmt.Sprintf("https://%v/", t.ip), "", framework.LoadBalancerPollTimeout, t.jig.PollInterval, t.httpClient, false))
Doesn't this poll continuously like on 106 above? Shouldn't it just check once?

2017-02-24 21:47 UTC, nicksardo commented on test/e2e/upgrades/ingress.go
> +	framework.ExpectNoError(framework.PollURL(fmt.Sprintf("https://%v/", t.ip), "", framework.LoadBalancerPollTimeout, t.jig.PollInterval, t.httpClient, false))
I'm not sure if I'm understanding what you're asking - I'm also new to this polling package.  Looks like `framework.PollURL` utilizes `wait.PollImmediate` with the passed loadbalancer timeout and interval.

However, this logic is identical to the `test` func in `upgrades/service.go` - it calls `jig.TestReachableHTTP` which utilizes `wait.PollImmediate` with the default `Poll` default of 2 seconds. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/service_util.go#L668

2017-02-24 21:56 UTC, krousey requested changes

2017-02-24 21:56 UTC, krousey commented on test/e2e/upgrades/ingress.go
> +	framework.ExpectNoError(framework.PollURL(fmt.Sprintf("https://%v/", t.ip), "", framework.LoadBalancerPollTimeout, t.jig.PollInterval, t.httpClient, false))
No I'd want them to behave the same in this regard. But this does answer my question. This stops after one successful poll. So the problem is on 106.

2017-02-24 21:56 UTC, krousey commented on test/e2e/upgrades/ingress.go
> +		framework.ExpectNoError(framework.PollURL(fmt.Sprintf("https://%v/", t.ip), "", framework.LoadBalancerPollTimeout, t.jig.PollInterval, t.httpClient, false))
After reading your comment below, the problem is that this stops polling after one successful response. What you should do is poll until the the disruption is complete. The service test does this by doing this one-shot polls inside a `wait.Until` call that stops when `done` is closed.

2017-02-24 21:59 UTC, nicksardo commented on test/e2e/upgrades/ingress.go
> +		framework.ExpectNoError(framework.PollURL(fmt.Sprintf("https://%v/", t.ip), "", framework.LoadBalancerPollTimeout, t.jig.PollInterval, t.httpClient, false))
Ah, understood! Thanks

2017-02-24 22:21 UTC, nicksardo commented on test/e2e/framework/ingress_utils.go
> +func gcloudComputeResourceList(resource, regex, project string, out interface{}) {
These gcloud funcs are ugly and removing them in this PR would be time consuming. Reckon I create an issue about consuming the cloud provider pkg instead.

2017-02-24 22:33 UTC, krousey commented
/lgtm

Cool. Could you run it again and make sure it still passes. Once it does, I'll approve.

2017-02-24 22:36 UTC, nicksardo commented
Will fix that bazel file and ping you when I'm done testing locally. Thanks

2017-02-28 01:19 UTC, nicksardo commented
This PR is waiting on issue #42199 to be resolved.

2017-03-01 07:52 UTC, nicksardo commented
@k8s-bot bazel test this

2017-03-01 17:39 UTC, krousey approved these changes

2017-03-01 18:24 UTC, spxtr commented
@k8s-bot ok to test

2017-03-01 21:30 UTC, krousey commented
@k8s-bot unit test this

2017-03-01 22:21 UTC, krousey commented
/lgtm

2017-03-01 23:30 UTC, merged