Feature/hpa upscale downscale delay configurable
kubernetes/kubernetes pull request #42101
Opened 2017-02-25 13:58 UTC by Dmitry1987

**What this PR does / why we need it**:
Makes "upscale forbidden window" and "downscale forbidden window"  duration configurable in arguments of kube-controller-manager. Those are options of horizontal pod autoscaler.
**Special notes for your reviewer**:
Please have a look @DirectXMan12 , the PR as discussed in Slack.
**Release note**:
```
Make "upscale forbidden window" and "downscale forbidden window"  duration configurable in arguments of kube-controller-manager. Those are options of horizontal pod autoscaler. Right now are hardcoded 3 minutes for upscale, and 5 minutes to downscale.  But sometimes cluster administrator might want to change this for his own needs.
```

2017-02-27 14:58 UTC, dannyz29 commented
+ 1

2017-02-27 15:03 UTC, Dmitry1987 commented
Hi  @DirectXMan12 ,  one of the commits was made from ubuntu VM where I was testing. And other commits from windows.  So, the commit from ubuntu has an "X", it thinks no CLA signed  (the username of commit "Dmitry Shmakov" different from account username "Dmitry1987"...),  is it ok and will be possible to merge, or I should fix this somehow?

2017-02-27 15:43 UTC, DirectXMan12 commented
> is it ok and will be possible to merge, or I should fix this somehow?

You'll need to fix it.  You can amend the commit while using the `--author` flag to do so.

2017-02-27 15:45 UTC, DirectXMan12 requested changes
A couple of minor changes, otherwise looks good in general.  Thanks for doing this! :-)

2017-02-27 15:45 UTC, DirectXMan12 commented on pkg/apis/componentconfig/types.go
> +        // horizontalPodAutoscalerUpscaleForbiddenWindow is a period after which next upscale allowed.
you appear to have some indentation issues here

2017-02-27 15:45 UTC, DirectXMan12 commented on pkg/controller/podautoscaler/horizontal.go
> +		rescale = shouldScale(a, hpa, currentReplicas, desiredReplicas, timestamp)
just make this a method of the HPA controller instead of passing the HPA as the first argument.

2017-02-27 15:47 UTC, DirectXMan12 commented
cc @jszczepkowski

2017-02-27 16:02 UTC, timothysc commented
Punting to @piosz and @DirectXMan12.  It doesn't appear that sig-instrumentation has their kubernetes team configured properly.

2017-02-27 16:12 UTC, snirad commented
Very nice !

2017-02-27 21:29 UTC, Dmitry1987 commented
Did the changes. @DirectXMan12  please have a look :) , 
P.S. thanks for patience and explaining stuff in slack 👍

2017-02-28 15:16 UTC, jszczepkowski commented on pkg/apis/componentconfig/types.go
> +    HorizontalPodAutoscalerDownscaleForbiddenWindow metav1.Duration
Wrong indentation: should be tab instead of spaces.

2017-02-28 15:17 UTC, jszczepkowski commented
Good job!

This issue has been discussed in #32408 (adding the link for reference).

2017-03-01 09:27 UTC, Dmitry1987 commented
Thanks @jszczepkowski . I've read the thread, but not sure if it means that this PR is needed or not. like, will it be merged, or this functionality will not be accepted?

2017-03-01 15:25 UTC, jszczepkowski commented
> I've read the thread, but not sure if it means that this PR is needed or not. like, will it be merged, or this functionality will not be accepted?

The PR should be merged (after LGTM) and this functionality will be accepted.

2017-03-02 16:19 UTC, DirectXMan12 requested changes
Small nit, otherwise LGTM.  Please squash the fixup commits together before merge.

2017-03-02 16:19 UTC, DirectXMan12 commented on cmd/kube-controller-manager/app/options/options.go
> +	fs.DurationVar(&s.HorizontalPodAutoscalerUpscaleForbiddenWindow.Duration, "horizontal-pod-autoscaler-upscale-delay", s.HorizontalPodAutoscalerUpscaleForbiddenWindow.Duration, "The period since last
this should probably not have the "in minutes" part.

2017-03-02 17:12 UTC, Dmitry1987 reviewed
commits squashed :)

2017-03-02 17:27 UTC, DirectXMan12 commented
/lgtm

2017-03-02 18:18 UTC, DirectXMan12 commented
Whoops, you'll have to update the tests so that they pass
/lgtm cancel

2017-03-05 11:22 UTC, Dmitry1987 commented
@k8s-bot bazel test this

2017-03-07 12:27 UTC, Dmitry1987 commented
Can someone please run the tests?  I fixed tests file where it failed last time, and local tests passed, with "./build/run.sh make test"

2017-03-08 08:21 UTC, jszczepkowski commented
@k8s-bot test this

2017-03-08 08:23 UTC, jszczepkowski commented
Do we want to merge this on 1.6? Technically, we have a code freeze.

2017-03-08 09:07 UTC, Dmitry1987 commented
gosh, I updated "horizontal_test.go" but not "legacy_horizontal_test.go"... but my "./build/run.sh make test" passed :(  .. how can I know what are all the test files which may fail?  step by step?

2017-03-08 16:29 UTC, Dmitry1987 commented
rebased and added needed params to "legacy_horizontal_test.go" (this file didn't yet exist in my branch), so test shouldn't fail now, i hope =) .

2017-03-09 07:18 UTC, jszczepkowski commented
@k8s-bot test this

2017-03-09 12:33 UTC, Dmitry1987 commented
Hi guys, from latest failed tests I found and fixed all "gofmt" needed files with "gofmt -s -w".  But why "kops" test failed and where to fix what, I don't understand :( , can someone take a quick look at the log here:  https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42101/pull-kubernetes-e2e-kops-aws/16450/?log#log
there are errors like ```build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory``` which I have no idea how to fix or if they're related to my changes at all (or did those fail as chain reaction following 'bazel build'?).

The 3d test "/hack/verify-flags-underscore.py" failure I fixed too, added flags like it says to "hack/verify-flags/known-flags.txt"...  so I just need help with kops test. Thanks :)

2017-03-16 13:50 UTC, Dmitry1987 commented
Hi @jszczepkowski , can you help with the bot?  it doesn't run test after my last push... and I don't know what is the failure in 'kops' test, maybe you can help?

2017-03-16 14:52 UTC, jszczepkowski commented
@k8s-bot test this

2017-03-24 18:31 UTC, DirectXMan12 commented
as long as the tests pass, looks good!

2017-03-24 19:18 UTC, DirectXMan12 commented
@k8s-bot ok to test

2017-03-26 15:43 UTC, DirectXMan12 commented
/lgtm /approve

2017-04-03 07:28 UTC, Dmitry1987 commented
Hi @deads2k, @mikedanese , do you have a minute to have a look at this PR? 
 It's really small, but we need this feature, and I don't want to rebuild the controller-manager myself with every k8s release we upgrade :P  .  Thanks in advance! :)

2017-04-11 17:09 UTC, deads2k commented
/approve

2017-04-25 00:10 UTC, mtaufen commented
/approve
the changes in componentconfig lgtm

2017-04-25 02:39 UTC, merged