Eviction Manager Enforces Allocatable Thresholds
kubernetes/kubernetes pull request #42204
Opened 2017-02-28 00:27 UTC by dashpole

This PR modifies the eviction manager to enforce node allocatable thresholds for memory as described in kubernetes/community#348.
This PR should be merged after #41234. 

cc @kubernetes/sig-node-pr-reviews @kubernetes/sig-node-feature-requests @vishh

2017-02-28 00:40 UTC, dashpole commented
@k8s-bot test this

2017-02-28 00:41 UTC, dashpole commented
@k8s-bot test this

2017-02-28 00:49 UTC, dashpole commented
@k8s-bot test this

2017-02-28 04:30 UTC, derekwaynecarr commented
I would like a chance to review this as well prior to merge

2017-02-28 16:58 UTC, dashpole commented
/release-note-none

2017-02-28 19:22 UTC, dashpole commented
This is an overview of this solution:
AllocatableMemory.Capacity = node.Status.Allocatable  (which has already subtracted the eviction threshold)
AllocatableMemory.Available = SignalObservation.Capacity - sum_over_pods(pod.usage)
Threshold:  AllocatableMemory.Available, LessThanOp, Resource(0)

2017-02-28 19:40 UTC, dashpole commented
I think this is ready for you to take a look at.  Builds appear to have failed because it failed to pull kube-proxy
I am not sure what the best way to add the "Zero available threshold" is, and the way I did it is a bit ugly.  Feel free to make suggestions.

2017-02-28 19:52 UTC, vishh commented on pkg/kubelet/eviction/api/types.go
> +	SignalAllocatableMemoryAvailable Signal = "allocatableMemory.available"
make this private

2017-02-28 19:52 UTC, vishh commented on pkg/kubelet/eviction/helpers.go
> +		results = append(results, evictionapi.Threshold{
Don't turn this on by default. Instead tie allocatable limits to `memory.available` signal.

2017-02-28 19:52 UTC, vishh commented on pkg/kubelet/kubelet.go
> +	addAllocatableEvictionThreshold := !kubeCfg.ExperimentalNodeAllocatableIgnoreEvictionThreshold && len(kubeCfg.EnforceNodeAllocatable) > 0
You need to check that `kubeCfg.EnforceNodeAllocatable` contains `pods` in its value.

2017-02-28 19:52 UTC, vishh commented
an e2e will be helpful

2017-02-28 20:07 UTC, dashpole commented on pkg/kubelet/eviction/api/types.go
> +	SignalAllocatableMemoryAvailable Signal = "allocatableMemory.available"
I would have to move it out of eviction api, since this is used within the eviction package.

2017-02-28 20:07 UTC, dashpole commented on pkg/kubelet/eviction/helpers.go
> +		results = append(results, evictionapi.Threshold{
I am not sure I understand either point.
The threshold here on or off based on includeAllocatableThreshold.
Why would I tie allocatable limits to available memory?

2017-02-28 21:02 UTC, dashpole commented on pkg/kubelet/kubelet.go
> +	addAllocatableEvictionThreshold := !kubeCfg.ExperimentalNodeAllocatableIgnoreEvictionThreshold && len(kubeCfg.EnforceNodeAllocatable) > 0
Done.  I reworked this by passing kubeCfg to the thresholds parser.  It adds the threshold if "pods"  (cm.NodeAllocatableEnforcementKey) is found.

2017-02-28 23:00 UTC, derekwaynecarr requested changes
i would like some more test cases for TestParseThresholdConfig.  i also would like to see the documented behavior for memory.available here to have some text that says how memory.available has two meanings.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-eviction.md#eviction-signals

2017-02-28 23:00 UTC, derekwaynecarr commented on pkg/kubelet/eviction/api/types.go
> +	SignalAllocatableMemoryAvailable Signal = "allocatableMemory.available"
is this a user-facing?

2017-02-28 23:00 UTC, derekwaynecarr commented on pkg/kubelet/eviction/api/types.go
> +	SignalAllocatableMemoryAvailable Signal = "allocatableMemory.available"
seeing that this is not user-facing, this should be private.  agreed.

2017-02-28 23:00 UTC, derekwaynecarr commented on pkg/kubelet/eviction/helpers.go
> +	allocatableThresholds := getAllocatableThreshold(allocatableConfig)
i would like a test case for this use case.

2017-02-28 23:00 UTC, derekwaynecarr commented on pkg/kubelet/eviction/helpers_test.go
> +		thresholds, err := ParseThresholdConfig([]string{}, testCase.evictionHard, testCase.evictionSoft, testCase.evictionSoftGracePeriod, testCase.evictionMinReclaim)
we need tests that exercise not passing [] into the Parse call..

2017-03-01 00:19 UTC, dashpole commented on pkg/kubelet/eviction/api/types.go
> +	SignalAllocatableMemoryAvailable Signal = "allocatableMemory.available"
Just to clarify, in-case I wasnt clear:  This is now in a separate package from the rest of the eviction code, so I have 2 options:
1. I can move this signal (or all of them) to eviction/types.go, and make it private.  However, then it is separated from the rest of the signals.
2. I can leave it public.

I am happy to do either, just let me know.

2017-03-01 00:21 UTC, vishh commented on pkg/kubelet/eviction/api/types.go
> +	SignalAllocatableMemoryAvailable Signal = "allocatableMemory.available"
Existing code is fine by me as long as we don't add support for parsing it.

2017-03-01 00:22 UTC, vishh commented on pkg/kubelet/eviction/helpers.go
> +		results = append(results, evictionapi.Threshold{
Redacted. Talked to @dashpole offline.

2017-03-02 00:57 UTC, ethernetdan commented
Removing PR from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

2017-03-02 01:26 UTC, dashpole commented on pkg/kubelet/eviction/helpers.go
> +	allocatableThresholds := getAllocatableThreshold(allocatableConfig)
done.

2017-03-02 01:28 UTC, dashpole commented
@derekwaynecarr @vishh PTAL.  The eviction test reuses a large portion of the inode eviction test, but changes the pressure condition, input pods, and kubelet flags.  I have placed it in the flaky suite, as it will likely encounter the same eviction issues as the inode eviction test.

2017-03-02 01:34 UTC, dashpole commented
@k8s-bot bazel test this

2017-03-02 02:34 UTC, vishh approved these changes
a few nits. would prefer addressing them soon not necessarily in this PR though

2017-03-02 02:34 UTC, vishh commented on pkg/kubelet/eviction/eviction_manager_test.go
> +func newMockNodeProvider(allocatableCapacity v1.ResourceList) *mockNodeProvider {
nit: I'd name it a fake. with mocks u get to control function invocations

2017-03-02 02:34 UTC, vishh commented on pkg/kubelet/eviction/helpers.go
> +		if key == cm.NodeAllocatableEnforcementKey {
I'd prefer exposing this logic as a containermanager method instead. why should evictions care about allocatable configuration excepting knowing if it needs to evict at allocatable level

2017-03-02 02:37 UTC, vishh commented
@calebamiles OK to lift merge restriction as per sig-node slack conversation?

2017-03-02 03:31 UTC, dashpole commented
@k8s-bot cvm gke e2e test this

2017-03-02 03:31 UTC, dashpole commented
@k8s-bot gci gke e2e test this

2017-03-02 05:35 UTC, dashpole commented
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

2017-03-02 15:37 UTC, dashpole commented
ingress failures seem unrelated, but I rebased to be sure, since the testgrid for that test is green.

2017-03-02 16:32 UTC, dashpole commented
`Mar  2 08:06:36.589: INFO: Error creating firewall-rules, output: ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:`
`  - The resource 'projects/k8s-jkns-pr-gke/global/networks/jenkins-e2e' was not found`

This seems unrelated...

2017-03-02 16:52 UTC, dashpole commented
this issue appears plauge other PRs as well: #42362, so I think it is safe to ignore.

2017-03-02 18:20 UTC, vishh commented
@k8s-bot cvm gke e2e test this

2017-03-02 18:20 UTC, vishh commented
@k8s-bot gci gke e2e test this

2017-03-02 18:41 UTC, ethernetdan commented
@vishh could an exception request please be put in for this PR?

2017-03-02 19:00 UTC, vishh commented
@ethernetdan an exception request has already been posted - https://groups.google.com/forum/#!topic/kubernetes-milestone-burndown/NgpKrBm2gcA/discussion

2017-03-02 19:01 UTC, vishh commented
@calebamiles As per https://kubernetes.slack.com/archives/sig-node/p1488417902001532 can I go ahead and un block this PR?

2017-03-02 19:05 UTC, ethernetdan commented
Missed that, thanks!

On Thu, Mar 2, 2017, 11:01 AM Vish Kannan <notifications@github.com> wrote:

> @calebamiles <https://github.com/calebamiles> As per
> https://kubernetes.slack.com/archives/sig-node/p1488417902001532 can I go
> ahead and un block this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/42204#issuecomment-283746444>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AD1BORN1BsE2Ck59e5UobQWmNE6TbawGks5rhxIagaJpZM4MNz5y>
> .
>

2017-03-02 19:06 UTC, ethernetdan commented
Please wait until a decision is made at the burndown tomorrow

On Thu, Mar 2, 2017, 11:05 AM Dan Gillespie <dan.gillespie@coreos.com>
wrote:

> Missed that, thanks!
>
> On Thu, Mar 2, 2017, 11:01 AM Vish Kannan <notifications@github.com>
> wrote:
>
> @calebamiles <https://github.com/calebamiles> As per
> https://kubernetes.slack.com/archives/sig-node/p1488417902001532 can I go
> ahead and un block this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/42204#issuecomment-283746444>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AD1BORN1BsE2Ck59e5UobQWmNE6TbawGks5rhxIagaJpZM4MNz5y>
> .
>
>

2017-03-02 19:11 UTC, vishh commented
@ethernetdan we already had a long chat with @calebamiles about this and a couple other PRs in that exception request yesterday. Can you sync up with him?

2017-03-02 20:03 UTC, derekwaynecarr approved these changes

2017-03-02 20:05 UTC, vishh commented
Given that this PR is a bug fix (as described above), I'm lifting the merge blocker.

2017-03-04 04:20 UTC, merged