Fixed the #42412 issue.
kubernetes/kubernetes pull request #42560
Opened 2017-03-06 08:49 UTC by jianzhangbjz

The origin issue is here [GPU allocation failed after container in Pod restart](https://github.com/kubernetes/kubernetes/issues/42412), I added the [UpdateDevice interface](https://github.com/jianzhangbjz/kubernetes/blob/fix-42412/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go#L132) to update the mapping cache when the container crashed. I test it manually and now it works well, comments are welcome! Example:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu
  labels:
    name: gpu
spec:
  containers:
  - name: gpu
    image: nvidia/cuda:jian
    command: ["/bin/sh", "-c"]
    #args: ["tail -f /dev/null"]
    args: ["sleep 10"]
    resources:
      limits:
        cpu: 0.5
        memory: 128Mi
        alpha.kubernetes.io/nvidia-gpu: 4
    ports:
    - containerPort: 6379
```
After task completed, restart successfully.
```
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
gpu       1/1       Running   0          11s
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS      RESTARTS   AGE
gpu       0/1       Completed   0          12s
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
gpu       1/1       Running   1          14s
```

2017-03-08 01:33 UTC, jianzhangbjz commented
@k8s-ci-robot I signed it!

2017-03-08 21:13 UTC, timstclair requested changes

2017-03-08 21:13 UTC, timstclair commented on pkg/kubelet/kubelet.go
> +			kl.gpuManager.UpdateDevices(string(podId), exitedContainerID)
Make UpdateDevices take a types.UID for the podID rather than casting to string here

2017-03-08 21:13 UTC, timstclair commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +		glog.Errorf("SyncPod Inspect JSON container:%v, error:%v", exitedContainerID, err)
I think this method should return the error, and handle it in the caller instead. Also change the text to `failed to inspect exited container %q: %v`

2017-03-08 21:13 UTC, timstclair commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +			if containsInt(deviceMap.PathOnHost) {
This seems very hacky... what is the actual intent here? What kinds of paths are you testing? I think this should at least be a regex...

2017-03-08 21:13 UTC, timstclair commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +				if value, ok := ngm.allocated.podGPUMapping[podUID]; ok {
need to lock the mutex

2017-03-08 21:13 UTC, timstclair commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +				if value, ok := ngm.allocated.podGPUMapping[podUID]; ok {
Move this check to outside the forloop.

2017-03-08 21:13 UTC, timstclair commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +			if containsInt(deviceMap.PathOnHost) {
Can you just remove this, since you're already testing against the mapped value?

2017-03-08 21:13 UTC, timstclair commented on test/e2e_node/gpus.go
> +	gpuverificationCmd := fmt.Sprintf("if [[ %d -ne $(ls /dev/ | egrep '^nvidia[0-9]+$') ]]; then echo Failure; sleep 30; exit 1; fi; echo Success; sleep 30 ", gpus)
Why did you add the echo & sleep? Just check the exit code?

2017-03-09 01:23 UTC, jianzhangbjz commented on test/e2e_node/gpus.go
> +	gpuverificationCmd := fmt.Sprintf("if [[ %d -ne $(ls /dev/ | egrep '^nvidia[0-9]+$') ]]; then echo Failure; sleep 30; exit 1; fi; echo Success; sleep 30 ", gpus)
Yes, I need to check the output of the container.

2017-03-09 01:30 UTC, jianzhangbjz commented on pkg/kubelet/kubelet.go
> +			kl.gpuManager.UpdateDevices(string(podId), exitedContainerID)
Well, I will use types.UID instead of string.

2017-03-09 01:32 UTC, jianzhangbjz commented on pkg/kubelet/gpu/gpu_manager_stub.go
> +	fmt.Printf("update GPUs devices mapping.")
Ok, will modify it.

2017-03-09 01:32 UTC, jianzhangbjz commented on pkg/kubelet/gpu/types.go
> +	UpdateDevices(podUID string, exitedContainerID string)
Ok.

2017-03-09 02:55 UTC, jianzhangbjz commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +		glog.Errorf("SyncPod Inspect JSON container:%v, error:%v", exitedContainerID, err)
Well, the method can return the desired output as long as we invoke it before the container destroyed. I have followed your advice and moved it into the caller.

2017-03-09 03:31 UTC, jianzhangbjz commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +				if value, ok := ngm.allocated.podGPUMapping[podUID]; ok {
Done.

2017-03-09 03:31 UTC, jianzhangbjz commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +				if value, ok := ngm.allocated.podGPUMapping[podUID]; ok {
Done.

2017-03-09 03:33 UTC, jianzhangbjz commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +			if containsInt(deviceMap.PathOnHost) {
Sure, removed it and used `isValidPath` func instead. Thx.

2017-03-09 03:56 UTC, jianzhangbjz commented on test/e2e_node/gpus.go
> +			if len(statuses) > 1 {
Yeah... modified it. Thx. :)

2017-03-09 19:55 UTC, vishh commented
I'm not in favor of this change. A better approach would be that of keeping track of `pod + container` mapping.
`AllocateGPU(pod, container)` can store a mapping from `pod` + `container` to GPUs. Whenever `AllocateGPU` is invoked for the same pod + container combination, it can return the original GPU already allocated.

2017-03-09 19:56 UTC, vishh commented
I don't think v1.6 will be patched to fix this bug. This will have to wait for a v1.7 alpha release.

2017-03-10 01:53 UTC, jianzhangbjz commented
@vishh Sure, we can use a better way in v1.7, but for the v1.6, this is a serious issue in our practical use.

2017-03-10 02:00 UTC, vishh commented
@JiangtianLi This PR is not acceptable as-is for v1.6.
On top of that, IIUC, this issue can be worked around by setting pod restart policy to be `RestartNever` for now.
If you were to fix up this PR the way I mentioned in https://github.com/kubernetes/kubernetes/pull/42560#issuecomment-285462604, we will have to justify why this bug is worth fixing in v1.6.

2017-03-10 02:30 UTC, jianzhangbjz commented
@vishh Yeah... you're right. But in many scenarios, we need the container restart automatically.
@cmluciano @seelam Can you help to give a details description for the value of fixed the bug?

2017-03-10 03:10 UTC, vishh commented
I'm not denying that a fix is necessary. I'm only arguing that it might be
too late to fix it in v1.6. And even if we were to fix it, this PR is not
acceptible

On Thu, Mar 9, 2017 at 6:30 PM, Jian Zhang <notifications@github.com> wrote:

> @vishh <https://github.com/vishh> Yeah... you're right. But in many
> scenarios, we need the container restart automatically.
> @cmluciano <https://github.com/cmluciano> @seelam
> <https://github.com/seelam> Can you help to give a details description
> for the value of fixed the bug?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/42560#issuecomment-285555432>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGvIKIgUUphpEIll61Rv-Klbe1LT-1xwks5rkLXigaJpZM4MT3ip>
> .
>

2017-03-10 03:37 UTC, jianzhangbjz commented
@vishh Sorry for the misunderstanding, well, I think we have to maintain the fixed version in our internal for the present, thanks your interpretation.

2017-03-10 17:43 UTC, nqbao commented
I think this is a serious bug fix :(, will we have 1.6.1 or something that contains this patch? 1.7 will be too long.

2017-03-10 21:50 UTC, seelam commented
@vishh This bug makes the cluster unusable if there are dead containers with GPUs. When a container that has an allocated GPU goes into an exit or dead state, the Kublet reports that those GPUs are free to schedule additional pods but when the new container actually starts, kublet fails to mount those GPUs so the container starts normally. As a result, the end user code crashes when it tries to access the gpus. This problem is hard to debug in production and a strange one for users. 

One option to get around this is to always delete the container as soon as it fails or completes the work (sometimes you don't delete so you can debug app failures). Another option is that If there are dead containers, cordon the node, and delete them, and uncrodon the node. 

I think it is worth getting this fix in 1.6, we will come back with a PR that will address your concerns.

2017-03-11 02:44 UTC, vishh commented
I opened https://github.com/kubernetes/kubernetes/pull/42942 to fix this issue.

There are some more corner cases which will not be fixed in v1.6.

If you wouldn't mind @jianzhangbjz can you close this PR?

2017-03-11 02:45 UTC, vishh commented
@seelam post your thoughts on #42942

2017-03-11 09:06 UTC, jianzhangbjz commented
@vishh No problem, closed it.

2017-03-11 09:06 UTC, closed without merging