matchPredicate does not fit findByClaim()
kubernetes/kubernetes pull request #42629
Opened 2017-03-07 08:20 UTC by NickrenREN

matchPredicate has two args which are type of PV,and is not used in function findByClaim(),remove it

**Release note**:
```release-note
NONE
```

2017-03-07 09:10 UTC, NickrenREN commented
@k8s-bot kops aws e2e test this

2017-03-07 18:02 UTC, jingxu97 commented
/approve

2017-03-08 01:47 UTC, NickrenREN commented
@jingxu97  Could you help add lgtm label ?

2017-03-26 14:25 UTC, NickrenREN commented
@jingxu97 Could you help add lgtm label ? @saad-ali PTAL . Thanks

2017-04-05 18:28 UTC, jingxu97 commented
@msau42 could you help take a look?

2017-04-05 18:40 UTC, msau42 commented
/lgtm

2017-04-06 00:03 UTC, NickrenREN commented
@k8s-bot gce etcd3 e2e test this

2017-04-06 03:18 UTC, saad-ali requested changes

2017-04-06 03:18 UTC, saad-ali commented on pkg/controller/volume/persistentvolume/index.go
>  // matchStorageCapacity is a matchPredicate used to sort and find volumes
I think you can get rid of `matchStorageCapacity(...)` now too?

2017-04-06 03:24 UTC, NickrenREN commented on pkg/controller/volume/persistentvolume/index.go
>  // matchStorageCapacity is a matchPredicate used to sort and find volumes
matchStorageCapacity() is called by Less(i,j) in pkg/controller/volume/persistentvolume/index_test.go

2017-04-06 21:13 UTC, saad-ali commented on pkg/controller/volume/persistentvolume/index.go
>  // matchStorageCapacity is a matchPredicate used to sort and find volumes
Ack. Maybe move `matchStorageCapacity(...)` to `persistentvolume/index_test.go` then?

2017-04-07 02:21 UTC, NickrenREN commented on pkg/controller/volume/persistentvolume/index.go
>  // matchStorageCapacity is a matchPredicate used to sort and find volumes
OK, done

2017-04-07 22:29 UTC, saad-ali commented
Thanks!

/lgtm
/approve

2017-04-07 22:29 UTC, saad-ali approved these changes

2017-04-08 00:44 UTC, merged