[e2e] Scheduler priority test
kubernetes/kubernetes pull request #42890
Opened 2017-03-10 15:55 UTC by wanghaoran1988

Fix https://github.com/kubernetes/kubernetes/issues/42439
In order to reduce the interfere of the balanced least-requested priority function, I create a balance pod to make the node have same mem/cpu use rate, not sure it's a correct way, but it did good, I have not cover all the scenarios yet, want to get feedback whether I am in the right way.
@k82cn @bsalamat Would you please help review ?

2017-03-11 02:14 UTC, bsalamat commented
@k8s-bot ok to test

2017-03-13 02:08 UTC, k82cn commented
@wanghaoran1988 , thanks for your PR :). I'll take some to review it this or next week.

2017-03-15 07:20 UTC, k82cn commented
@kubernetes/sig-scheduling-pr-reviews 

Propose to be **1.7** candidates.

2017-03-16 19:52 UTC, bsalamat commented
/assign

2017-03-16 21:02 UTC, timothysc commented
@wanghaoran1988 per-policy please /cc @kubernetes/sig-scheduling-pr-reviews in case folks decide to go on vacation etc.

2017-03-17 03:03 UTC, wanghaoran1988 commented
@timothysc Seems cannot /cc the private group :)

2017-03-18 00:24 UTC, bsalamat requested changes
First of all sorry for the delay in reviewing your PR and thanks a lot for taking the time to write the tests. This is very valuable and I really appreciate it. As our leads also said in a separate discussion, we should all try harder to improve our code coverage.
I have a few comments which are mostly nits.

2017-03-18 00:24 UTC, bsalamat commented on test/e2e/scheduler_priorities.go
> +	It("Pods Belong to same StatefulSet should spread to different node", func() {
nit: Please add a blank line before the test and remove the one after

2017-03-18 00:24 UTC, bsalamat commented on test/e2e/scheduler_priorities.go
> +		framework.PrettyPrintJSON(testPods)
Is this line needed?

2017-03-18 00:24 UTC, bsalamat commented on test/e2e/scheduler_priorities.go
> +				testTaint := v1.Taint{
Optional: I would create a function to for this block, as it is repeated below and may be useful in the future, but up to you.

2017-03-20 07:18 UTC, wanghaoran1988 commented
@k8s-bot unit test this

2017-03-20 07:57 UTC, wanghaoran1988 commented
@bsalamat Thanks for your comments, they are addressed now, PTAL.

2017-03-20 18:46 UTC, bsalamat commented
Review status: 0 of 4 files reviewed at latest revision, 23 unresolved discussions.

---

*[test/e2e/framework/util.go, line 2663 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KfgxOxG6_Y4Ei6DP3Vi:-KfgxOxG6_Y4Ei6DP3Vj:b-fk6n8q) ([raw file](https://github.com/kubernetes/kubernetes/blob/5bbc86a640ddcd9cef93950aca2b318f5087398d/test/e2e/framework/util.go#L2663)):*
> ```Go
> 			}
> 		}
> 		time.Sleep(100 * time.Millisecond)
> ```

Why the hard sleep is needed here? Hard sleeps usually introduce flakes. Can we remove/replace it?

---

*[test/e2e/scheduling/priorities.go, line 161 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-Kfgy9ZbWzG2JKafxzOm:-Kfgy9ZbWzG2JKafxzOn:b-56xtix) ([raw file](https://github.com/kubernetes/kubernetes/blob/5bbc86a640ddcd9cef93950aca2b318f5087398d/test/e2e/scheduling/priorities.go#L161)):*
> Pods NO. are not corrected
Unexpected number of pods, ...

---

*[test/e2e/scheduling/priorities.go, line 517 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-Kfh1TNlcsbABQjTR0OQ:-Kfh1TNlcsbABQjTR0OR:b-zi3ant) ([raw file](https://github.com/kubernetes/kubernetes/blob/5bbc86a640ddcd9cef93950aca2b318f5087398d/test/e2e/scheduling/priorities.go#L517)):*
> ```Go
> })
> 
> //This function create pod on each node to request enough resource to make the nodes have same mem/cpu usage ratio
> ```

// createBalancedPodForNodes creates a pod per node that asks for enough resources to make all nodes have the same mem/cpu usage ratio.

---

*[test/e2e/scheduling/priorities.go, line 692 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-Kfh0sfZY3-0tG1Ij6rY:-Kfh0sf_Wbc634URwK5j:b-dahnp4) ([raw file](https://github.com/kubernetes/kubernetes/blob/5bbc86a640ddcd9cef93950aca2b318f5087398d/test/e2e/scheduling/priorities.go#L692)):*
> v1.Taint

This is a test and we probably don't care much about performance and avoiding copies, but as a good practice, we should probably return a pointer: *v1.Taint

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890)*
<!-- Sent from Reviewable.io -->

2017-03-20 18:47 UTC, bsalamat commented
Thanks again, Haoran! We are almost there.

---

Review status: 0 of 4 files reviewed at latest revision, 23 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-:-Kfh1po4PtBvBdBW2F6m:b-j3slzs)*
<!-- Sent from Reviewable.io -->

2017-03-21 07:49 UTC, wanghaoran1988 commented
@bsalamat The comments are addressed, thanks for your comments and careful review, and the sentences you correct for me, my English is not good, but I am on my way learning English. :)

2017-03-21 07:53 UTC, wanghaoran1988 commented
Review status: 0 of 4 files reviewed at latest revision, 23 unresolved discussions.

---

*[test/e2e/framework/util.go, line 2607 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZMJ-r1-2607:-KfjVeUN_TDYIcsv0hAh:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/framework/util.go#L2607)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Core() is deprecated. Please use CoreV1() for new code (here and the rest of the PR).
</blockquote></details>

Done.

---

*[test/e2e/framework/util.go, line 2629 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZMJ-r1-2629:-KfjqGBrua1XmsSAphxJ:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/framework/util.go#L2629)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Please remove the blank line.
</blockquote></details>

Done.

---

*[test/e2e/framework/util.go, line 2632 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZMJ-r1-2632:-KfjqH8LN1H7mOyTaxg8:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/framework/util.go#L2632)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

This function removes all the AvoidPods annotations regardless of their temporary lifespan. So, the following might better reflect what it does:

// RemoveAnnotationOffNode removes AvoidPods annotations from the node. It does not fail if no such annotation exists.
</blockquote></details>

Done.

---

*[test/e2e/framework/util.go, line 2655 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZMJ-r1-2655:-KfjqJhjazZrNnOJKru_:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/framework/util.go#L2655)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Please remove the blank line.
</blockquote></details>

Done.

---

*[test/e2e/framework/util.go, line 2663 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KfgxOxG6_Y4Ei6DP3Vi:-KfjqILHoHnu93-XtMG6:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/5bbc86a640ddcd9cef93950aca2b318f5087398d/test/e2e/framework/util.go#L2663)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Why the hard sleep is needed here? Hard sleeps usually introduce flakes. Can we remove/replace it?
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 1 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-1:-KfjW6FsUU8FEcgeAM-Y:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L1)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

After the recent changes, you should move the file to test/e2e/scheduling/priorities.go
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 71 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-71:-KfjW337m28q2Vfomw2L:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L71)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

nit: Please remove the blank line. There are a few other cases throughout the file where blank lines are added right after "{" or before "}". Please remove all of them.
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 90 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-90:-KfjVyoElZOtG6HYFnL6:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L90)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

nit: `// Make sure all the schedulable nodes are balanced (have the same cpu/mem usage ratio)`
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 91 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-91:-KfjW-gFWSuf7f7rc_6z:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L91)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

nit: `By("Create pods on each node except the last one to raise cpu and memory usage to the same high level")`
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 118 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-118:-KfjW5pGUUozZFRxAZPl:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L118)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Sorry for being pedantic. Feel free to ignore my nit comments. I just try to make the sentences a bit more clear.

nit: By("Create an RC with the same number of replicas as the schedualble nodes. One pod should be scheduled on each node.")
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 166 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-166:-KfjW6qo3ZDVYq4r_sY4:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L166)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Please add a check: len(pods) == len(nodeList.Items)
This is not strictly needed, but will help find the problem before the check at line 179 fails.
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 185 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-185:-KfjW7FsXYimsNFtB1nO:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L185)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Please add a blank line before this test! :-)

nit: Pods of the same service should spread to different nodes.
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 190 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-190:-KfjW888K99AF63JyFbR:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L190)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Please remove // from the end
</blockquote></details>

Done.

---

*[test/e2e/scheduling/priorities.go, line 191 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KesvdDx9pfzGb9B3ZML-r1-191:-KfjW8ZaQz1u90P4B6sU:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/780625caa1c0699c138bea058d6e5f043b1afb5d/test/e2e/scheduling/priorities.go#L191)):*
<details><summary><i>Previously, bsalamat (Bobby (Babak) Salamat) wrote…</i></summary><blockquote>

Similar nit as the test ab [...]

2017-03-21 08:24 UTC, wanghaoran1988 commented
@k8s-bot unit test this

2017-03-22 00:31 UTC, bsalamat commented
Review status: 0 of 4 files reviewed at latest revision, 24 unresolved discussions.

---

*[test/e2e/scheduling/priorities.go, line 515 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890#-KfnPqeMSeH1vvxLEX8l:-KfnPqeMSeH1vvxLEX8m:b-8djzj3) ([raw file](https://github.com/kubernetes/kubernetes/blob/259abaa0ae9037536e11bc5140f5ac9d29a999a7/test/e2e/scheduling/priorities.go#L515)):*
> Create a pod tolerate all the taits of the first node
Create a pod that tolerates all the taints of the first node.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42890)*
<!-- Sent from Reviewable.io -->

2017-03-22 04:39 UTC, wanghaoran1988 commented
@k8s-bot gce etcd3 e2e test this

2017-03-22 05:08 UTC, bsalamat commented
Thanks again, Haoran!

2017-03-22 05:08 UTC, bsalamat commented
/lgtm

2017-03-22 23:24 UTC, ixdy commented
/assign @k82cn
/approve

2017-03-23 02:56 UTC, k82cn requested changes

2017-03-23 02:56 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +			Name:      "priority-least-requested-mem",
s/priority-least-requested-mem/priority-least-requested/

as both cpu and mem are included.

2017-03-23 02:56 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +	It("Pods created by ReplicationController should spread to different node", func() {
I think one case for `ReplicationController`, `ReplicaSet`, `StatefulSet` and `Service` is enough, as the scheduling logic is same; the only different is how to get selector (we can cover it in unit test.)

Less cases will not impact the coverage; but reduce e2e time.

2017-03-23 02:56 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +							Preference: v1.NodeSelectorTerm{
Why two selector here (hostname + k=v)?

2017-03-23 02:56 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +		framework.AddOrUpdateLabelOnNode(cs, nodeName, k, v)
Why add label to node? It's testing pod affinity.

2017-03-23 02:56 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +		framework.ExpectNodeHasLabel(cs, nodeName, k, v)
ditto

2017-03-23 02:56 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +		By(fmt.Sprintf("Scale the RC: %s to len(nodeList.Iten)-1 : %v.", rc.Name, len(nodeList.Items)-1))
s/Iten/Items

2017-03-23 02:56 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, ns string, nodes []v1.Node, requestedResource *v1.ResourceRequirements, ratio float64) {
Why we need this func? Suppose all nodes has similar allocatable.

2017-03-23 06:09 UTC, wanghaoran1988 commented on test/e2e/framework/util.go
> +		node, err := c.CoreV1().Nodes().Get(nodeName, metav1.GetOptions{})
@k82cn Thanks, will update all to use CoreV1() per comment here: https://github.com/kubernetes/kubernetes/pull/42890#discussion_r105520490

2017-03-23 06:10 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +	It("Pods created by ReplicationController should spread to different node", func() {
@k82cn I just want to make sure all of them are covered

2017-03-23 06:13 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +		framework.AddOrUpdateLabelOnNode(cs, nodeName, k, v)
@k82cn For the topologyKey in the podAffinity iterm

2017-03-23 06:40 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +		framework.AddOrUpdateLabelOnNode(cs, nodeName, k, v)
Yes, prefer to add two nodes in this topology; current case is "similar" to node affinity.

2017-03-23 06:42 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +	It("Pods created by ReplicationController should spread to different node", func() {
prefer to just keep one case which is enough to cover the "selector" priority's logic; for how to get selector, I'd like to dependent on unit test :).

2017-03-26 05:33 UTC, k82cn commented
/cancel-lgtm

2017-03-26 05:34 UTC, k82cn commented
/lgtm-cancel

2017-03-26 05:35 UTC, k82cn commented
/lgtm cancel

2017-03-26 05:38 UTC, k82cn commented
@wanghaoran1988 , please help to address comments, and then we can merge this PR :).

2017-03-26 06:30 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +	It("Pods created by ReplicationController should spread to different node", func() {
@k82cn Yeah, sounds reasonable, I can remove it.

2017-03-26 06:52 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +							Preference: v1.NodeSelectorTerm{
@k82cn No, just add two item to match the affinity, but we can using one selector if you don't like.

2017-03-26 07:04 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +		framework.AddOrUpdateLabelOnNode(cs, nodeName, k, v)
@k82cn nodeAffinity don't have this key, this is just use to filter out the pods that on the node with that label

2017-03-26 07:06 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, ns string, nodes []v1.Node, requestedResource *v1.ResourceRequirements, ratio float64) {
Similar does not mean same, as before we run the test, there really have a lot system pods make the resource not balanced.

2017-03-27 05:36 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +							Preference: v1.NodeSelectorTerm{
I'm OK with that.

2017-03-27 05:37 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, ns string, nodes []v1.Node, requestedResource *v1.ResourceRequirements, ratio float64) {
Can we remove pods after each cases?

2017-03-27 06:09 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, ns string, nodes []v1.Node, requestedResource *v1.ResourceRequirements, ratio float64) {
@k82cn The namespaces will be deleted so the pods will be deleted also.

2017-03-28 13:58 UTC, wanghaoran1988 commented
@k82cn Comments are addressed, would you mind add lgtm lable?

2017-03-30 01:10 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, ns string, nodes []v1.Node, requestedResource *v1.ResourceRequirements, ratio float64) {
I means deleting Pods after each test cases (If the pods was deleted, why we need this?). 

The ratio seems different from cases, e.g. 0.5, 0.6, 0.9, how did you define it? and how other contributor define it for other e2e cases?

2017-03-30 01:11 UTC, k82cn commented on test/e2e/scheduling/priorities.go
> +		framework.AddOrUpdateLabelOnNode(cs, nodeName, k, v)
I'm OK with that; not a block comments :).

2017-03-30 01:28 UTC, wanghaoran1988 commented on test/e2e/scheduling/priorities.go
> +func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, ns string, nodes []v1.Node, requestedResource *v1.ResourceRequirements, ratio float64) {
@k82cn Every test case will have a new namespace before start and deleted after finished. the balanced pods are created for each cases, and will be deleted after each case. For the ratio, just set the value you want to is ok.

2017-03-30 02:23 UTC, k82cn commented
/lgtm

Echo bsalamat's lgtm, although I have concern on `createBalancedPodForNodes`: `ratio` seems magic number to me: it need to know e2e environment (static pods), test cases and code of `createBalancedPodForNodes`. IMO, it's better to run those test on no-master/management nodes to avoid impact of static pods.

2017-03-30 08:37 UTC, k82cn commented
/lgtm

2017-03-30 09:33 UTC, merged