Handle container restarts while allocating GPUs
kubernetes/kubernetes pull request #42942
Opened 2017-03-11 02:43 UTC by vishh

Fixes #42412

**Background**
Support for multiple GPUs is an experimental feature in v1.6. Container restarts were handled incorrectly which resulted in stranding of GPUs

**What does this PR do**
This PR tracks assignment of GPUs to containers and returns pre-allocated GPUs instead of (incorrectly) allocating new GPUs.
Node e2e has been extended to validate this failure scenario.

**Risk**
Minimal/None since support for GPUs is an experimental feature that is turned off by default. The code is also isolated to GPU manager in kubelet.

**Workarounds**
In the absence of this PR, users can mitigate the original issue by setting `RestartPolicyNever`  in their pods.

cc @jianzhangbjz @seelam @kubernetes/sig-node-pr-reviews 

Replaces #42560

2017-03-11 03:50 UTC, dashpole commented
Unrelated to the changes here, but the GPU manager likely has the same problem that #42585 had, since this also uses "runningPods".

2017-03-11 04:00 UTC, dashpole commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +		return devices.List(), nil
Just to make sure I understand this: AllocateGPU is only called when either none of the GPUs for a container have been allocated, or all of the GPUs for a container have been allocated.  There would never arise a situation where we find 3 GPUs already allocated, but require 4, right?

2017-03-11 04:03 UTC, dashpole commented
Ill finish my review of the tests later, but the changes to the GPU manger look good.

2017-03-11 18:27 UTC, vishh commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +		return devices.List(), nil
Yes. Its all or nothing

2017-03-11 18:44 UTC, vishh commented
@dashpole Running pods vs active pods is a good catch. I incorrectly assumed that gpu manager was using active pods. Fixed it now.

2017-03-12 13:48 UTC, dashpole commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
>  func (ngm *nvidiaGPUManager) gpusInUse() (*podGPUs, error) {
no longer can return an error

2017-03-12 14:03 UTC, dashpole commented
lgtm after nit.  The unit test looks like a flake.

2017-03-12 18:26 UTC, vishh commented
@dashpole fixed the nit

2017-03-12 18:58 UTC, dashpole commented
/lgtm

2017-03-13 06:12 UTC, jianzhangbjz requested changes

2017-03-13 06:12 UTC, jianzhangbjz commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +		return devices.List(), nil
@vishh There should be return `append(devices.List(), ngm.defaultDevices...)` instead, right?

2017-03-13 16:13 UTC, dchen1107 commented
@vishh one you addressed @jianzhangbjz's comment, I will apply approval to the pr.

2017-03-13 17:59 UTC, vishh commented
Good catch @JiangtianLi. @dchen1107 fixed the bug and added unit tests.

2017-03-13 18:17 UTC, dashpole commented
took another quick look
/lgtm

2017-03-13 18:35 UTC, vishh commented
@k8s-bot gci gce e2e test this

2017-03-13 20:34 UTC, dchen1107 commented
/lgtm
/approve

2017-03-14 01:52 UTC, jianzhangbjz commented
@vishh I think you misspelled my name on the above.  \*(^_^)\*

2017-03-14 02:32 UTC, vishh commented
@k8s-bot unit test this

2017-03-14 02:33 UTC, vishh commented
@k8s-bot kops aws e2e test this

2017-03-14 02:33 UTC, vishh commented
@k8s-bot gce etcd3 e2e test this

2017-03-14 02:33 UTC, vishh commented
@jianzhangbjz Ah sorry about that.

2017-03-14 04:17 UTC, vishh commented
@k8s-bot kops aws e2e test this

2017-03-14 05:17 UTC, vishh commented
@justinsb kops e2e has been failing consistently. Is this a known issue? 

@k8s-bot kops aws e2e test this

2017-03-14 15:43 UTC, dashpole commented
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/
looks like it was failing, but is fixed now.
@k8s-bot kops aws e2e test this

2017-03-14 16:59 UTC, cmluciano commented
@vishh I think it should be fixed with this change https://github.com/kubernetes/kops/commit/2a44aa0c05ccfa0beb6d96ee21a7883947664f76. It seems that a rate-limit was hit and caused a ton of builds to fail.

2017-03-14 17:19 UTC, merged

2019-01-27 17:54 UTC, tedyu commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go
> +	if devices := ngm.allocated.getGPUs(string(pod.UID), container.Name); devices != nil {
Is it possible that devices is empty ?