Extract long strings and make available for translation.
kubernetes/kubernetes pull request #42978
Opened 2017-03-13 05:19 UTC by brendandburns

@fabianofranz

2017-03-13 14:18 UTC, fabianofranz commented
@k8s-bot verify test this

2017-03-13 19:56 UTC, fabianofranz commented on pkg/kubectl/cmd/create_secret.go
> +	secretForDockerRegistryLong = templates.LongDesc(i18n.T(`
@brendandburns looks like the description and examples from generic secrets are being used in the tls and docker registry subcommands here, maybe the script is not safe for files with more than one description and examples?  ;)

2017-03-13 19:57 UTC, fabianofranz commented on pkg/kubectl/cmd/create_service.go
> +	serviceNodePortLong = templates.LongDesc(i18n.T(`
Same here.

2017-03-13 19:57 UTC, fabianofranz commented on pkg/kubectl/cmd/drain.go
> +		Mark node as unschedulable.`))
...and here.

2017-03-13 19:59 UTC, fabianofranz commented on pkg/kubectl/cmd/replace.go
> +		kubectl get pod mypod -o yaml | sed 's/\(image: myimage\):.*$/Examples(:v4/' | kubectl replace -f -
Was this intended?

2017-03-14 10:55 UTC, soltysh requested changes

2017-03-14 10:55 UTC, soltysh commented on pkg/kubectl/cmd/drain.go
> +	drain_long = templates.LongDesc(i18n.T(`
I'm not sure we want to shorten this description, and if so please move it to docs and leave a link about that here.

2017-03-14 10:55 UTC, soltysh commented on pkg/kubectl/cmd/drain.go
> +		Mark node as unschedulable.`))
Additionally cordon/unschedulable and uncordon/schedulable is messed up as well.

2017-03-15 03:33 UTC, brendandburns commented
I'm guessing my script isn't safe. I will retest and fix...

2017-03-15 04:35 UTC, brendandburns commented
@fabianofranz @soltysh 

Fixed up my script and rebased.

Please take another look.

2017-03-15 12:28 UTC, soltysh approved these changes

2017-03-15 12:29 UTC, soltysh commented
/lgtm

2017-03-15 17:54 UTC, fabianofranz commented
@k8s-bot verify test this

2017-03-19 03:21 UTC, brendandburns commented
Self-lgtm as the change was just an `update-bazel.sh` run.

2017-03-24 17:27 UTC, fabianofranz commented
@k8s-bot gce etcd3 e2e test this

2017-04-07 07:20 UTC, soltysh commented
/lgtm

2017-04-07 09:32 UTC, merged