Log instead of fail on GLBCs tendency to leak resources
kubernetes/kubernetes pull request #43018
Opened 2017-03-13 21:27 UTC by nicksardo

**What this PR does / why we need it**:
Stops upgrade tests from failing because the GLBC does not cleanup all resources due to a race condition.

**Which issue this PR fixes**: fixes #38569

**Special notes for your reviewer**:
To be reviewed by @mml 

```release-note
NONE
```

2017-03-13 21:30 UTC, ncdc commented
/assign @mml

2017-03-13 22:21 UTC, nicksardo commented
@k8s-bot cvm gce e2e test this

2017-03-13 22:28 UTC, mml requested changes
LG otherwise.  Thanks!

2017-03-13 22:28 UTC, mml commented on test/e2e/framework/ingress_utils.go
> +	// See kubernetes/ingress #431
Delete whitespace before the `#` and I think github will linkify this for us.

2017-03-13 22:38 UTC, nicksardo commented on test/e2e/framework/ingress_utils.go
> +	// See kubernetes/ingress #431
Removed, but it's not linking: https://github.com/nicksardo/kubernetes/blob/3e85c0f758fd31d7e39611694cd1d58424739374/test/e2e/framework/ingress_utils.go I'm not sure if that feature is markdown specific.  Would you prefer if I paste the whole link?

2017-03-13 22:59 UTC, mml commented on test/e2e/framework/ingress_utils.go
> +	// See kubernetes/ingress #431
Nah.  NBD.

2017-03-13 23:00 UTC, mml approved these changes

2017-03-13 23:00 UTC, mml commented
/lgtm

2017-03-13 23:11 UTC, nicksardo commented
@k8s-bot kops aws e2e test this

2017-03-14 16:52 UTC, nicksardo commented
@k8s-bot kops aws e2e test this

2017-03-14 18:59 UTC, nicksardo commented
@kubernetes/kubernetes-release-managers Can this PR get the 1.6 milestone?

2017-03-14 20:12 UTC, nicksardo commented
/assign @ncdc 
PTAL

2017-03-14 20:18 UTC, ncdc commented
It looks like #38569 was moved to v1.6.1. Can we move this to match?

2017-03-14 20:30 UTC, nicksardo commented
@ncdc, that issue was moved to 1.6.1 because we don't want it to block the release. This PR will close that issue, so its milestone won't matter. Getting a clearer signal of other flakes on testgrid does matter, which is why we'd like this merged now.

2017-03-14 20:33 UTC, ncdc commented
@nicksardo ok, what makes sense to me is if you have a PR to fix an issue, and you want the PR to merge for 1.6, it doesn't make sense to move the issue to 1.6.1... but no big deal:

/approve

2017-03-14 20:47 UTC, nicksardo commented
@ncdc Agreed - I didn't expect the issue to be moved.

2017-03-14 22:59 UTC, merged