Sandbox gc
kubernetes/kubernetes pull request #43053
Opened 2017-03-14 04:32 UTC by feiskyer

**What this PR does / why we need it**:

Currently, kuberuntime garbage collection can't distinguish just-created sandboxes from failed sandboxes. Especially when the time from sandbox creation to ready is longer than GC's minAge. In such cases, those sandboxes may be garbage collected early before they are ready.

This PR removes `sandboxMinGCAge` and only garbage collect sandboxes when 

* they are containing no containers at all
* and not the latest sandbox if it is belonging to an existing pod.

**Which issue this PR fixes** 

Fixes #42856.

**Release note**:

```release-note
NONE
```

cc @yujuhong @Random-Liu

2017-03-14 04:32 UTC, feiskyer commented
/assign @yujuhong @Random-Liu

2017-03-14 06:06 UTC, feiskyer commented
@k8s-bot kops aws e2e test this

2017-03-15 03:47 UTC, feiskyer commented
@k8s-bot kops aws e2e test this

2017-03-30 02:44 UTC, feiskyer commented
ping @yujuhong @Random-Liu

2017-04-14 02:30 UTC, feiskyer commented
ping @Random-Liu @yujuhong

2017-04-14 04:36 UTC, Random-Liu commented
Will take a look tomorrow.

2017-04-15 00:35 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +		cgc.removeSandbox(sandboxes[i].id)
Why don't we log error here?

2017-04-15 00:35 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			// Keep latest one if pod is still exist.
s/is still exist/still exists

2017-04-15 00:35 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +
nit: Unnecessary empty line.

2017-04-15 00:35 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +				makeGCSandbox(pods[2], 0, runtimeapi.PodSandboxState_SANDBOX_READY),
Not sure whether we should remove READY sandbox. `SyncLoop` may be stopping the sandbox, too. This may introduce race that sandbox is stopped twice.

2017-04-15 00:35 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
>  	for _, sandbox := range sandboxes {
Why not skip running sandbox?

2017-04-15 00:35 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +		if pod.Name != "deleted" {
Why not introduce an arguement to indicate whether to add the pod into pod getter?

2017-04-15 00:35 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +				makeGCSandbox(pods[0], 1, runtimeapi.PodSandboxState_SANDBOX_READY),
I don't understand, why the `2` is not deleted here? We only keep the latest sandbox right?

2017-04-17 22:20 UTC, yujuhong commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +// containing no containers at all and not the latest sandbox if it is belonging to
Reword a little bit to make this more clear:
```
// evictSandboxes remove all evictable sandboes. An evictable sandbox must
// meet the following requirements:
//   1. contains no containers.
//   2. belong to a non-existent (i.e., already removed) pod, or is not the
//      most recently created sandbox for the pod.
```

2017-04-17 22:21 UTC, yujuhong commented
It's a shame because I actually like the original implementation which removes the podsandbox only when there are no associated containers in it. I think that'd be the right model as we *slowly* move away from using dead container bodies as tombstones.

2017-04-18 05:55 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +		cgc.removeSandbox(sandboxes[i].id)
There is already such log inside `cgc.removeSandbox`

2017-04-18 05:58 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
>  	for _, sandbox := range sandboxes {
The new logic only keeps the latest sandbox for each pod, all other sandboxes (including running ones) should be removed.

2017-04-18 06:02 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +				makeGCSandbox(pods[2], 0, runtimeapi.PodSandboxState_SANDBOX_READY),
Yes, didn't notice this problem. Will update to omit the ready sandbox.

2017-04-18 07:43 UTC, feiskyer commented
@Random-Liu @yujuhong Addressed comments. PTAL.

> It's a shame because I actually like the original implementation which removes the podsandbox only when there are no associated containers in it. I think that'd be the right model as we slowly move away from using dead container bodies as tombstones.

@yujuhong That's also my initial proposal,  but it needs a new sandbox state (and of course new sandbox APIs) to do that way, see [here](https://github.com/kubernetes/kubernetes/issues/42856#issuecomment-286012484). I think keeping  latest pod sandbox (in this PR) is better because it follows same logic as we do for container GC.

2017-04-18 08:37 UTC, feiskyer commented
@k8s-bot cvm gce e2e test this

2017-04-18 21:45 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +		cgc.removeSandbox(sandboxes[i].id)
I see.

2017-04-18 21:56 UTC, Random-Liu requested changes

2017-04-18 21:56 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +// evictSandboxes remove all evictable sandboes. An evictable sandbox must
I believe this function is wrong.

For container garbage collection, what we are doing:
1) get `evictableContainers` (prune out running ones);
2) remove all or keep latest `evictableContainers` based on whether the pod is deleted.

I quite don't understand what the PR is doing now.

2017-04-18 21:56 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +		if cgc.isPodDeleted(podUID) || len(activeSandboxes[podUID]) > 0 {
1) Why remove all sandboxes when there is active sandbox?
2) Are you sure `sandboxes` is "evictable sandboxes"?

2017-04-19 01:23 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +		if cgc.isPodDeleted(podUID) || len(activeSandboxes[podUID]) > 0 {
Sorry, this logic is actually wrong.

2017-04-19 01:34 UTC, feiskyer commented
> For container garbage collection, what we are doing:
> 
> * get evictableContainers (prune out running ones);
> * remove all or keep latest evictableContainers based on whether the pod is deleted.

Yep, but sandboxes are slightly different: 

* sandboxes should not be removed if there are still containers belonging to it. 

Added a new commit, which changed the logic to:

* Get all sandboxes by podUID first, mark sandboxes as active which is ready or with containers
* Sort sandboxes by creation time
* Remove inactive sandboxes
    * remove all inactive sandboxes if pod has been removed
   * else, keep the latest one (regardless of its state)

@Random-Liu PTAL. Feel free to file a new PR if you have different opinions.

2017-04-24 18:22 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +// evictSandboxes remove all evictable sandboes. An evictable sandbox must
s/sandboes/sandboxes

2017-04-24 18:22 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			cgc.removeSandbox(sandboxes[i].id)
If there is an active sandbox here, returning `sandboxes[:numToKeep]` doesn't make sense to me.

Although we don't use the return value, but the code may confuse people.

2017-04-24 18:22 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			// Remove all evictable sandboxes if the pod has been removed.
Why not keeping the logic the same with container? I didn't see difference except that sandbox with containers is not evictable.

We could still generate an evictable sandboxes list, and use it here.

2017-04-25 01:51 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			// Remove all evictable sandboxes if the pod has been removed.
> In you comment, you said that "keep the latest one (regardless of its state)", but here I didn't see that.

I think you are reviewing an old commit. There is no such comment in latest commit.

2017-04-25 01:56 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			cgc.removeSandbox(sandboxes[i].id)
Yep, will remove the return value

2017-04-25 01:57 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			// Remove all evictable sandboxes if the pod has been removed.
> In you comment, you said that "keep the latest one (regardless of its state)", but here I didn't see that.

Sorry, it is in the previous comment. I mean the latest one should be kept, whether it is ready or not. And other active ones are also kept. Will make an update to the comment:

* remove all inactive sandboxes if pod has been removed
* else
  * keep active sandboxes
  * keep the latest sandbox whether it is active or not
  * remove other inactive sandboxes

2017-05-03 06:00 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +	// Remove from oldest to newest (last to first).
Is this `oldest to newest`? Seems to be newest to oldest...

And also the same question for the container remove function.

2017-05-03 06:00 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			cgc.removeOldestNSandboxes(sandboxes, len(sandboxes)-1)
Maybe explain that we don't need to keep the latest dead sandbox if there is an active one? Since this is different from container gc behavior.

2017-05-03 06:00 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +			// initialize the pod getter, explicitly exclude deleted pod
Update the comment.

2017-05-03 06:00 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +				makeGCSandbox(pods[0], 0, runtimeapi.PodSandboxState_SANDBOX_NOTREADY, true),
s/true/false

Or else sandbox will not be removed because there is corresponding pod.

2017-05-03 06:00 UTC, Random-Liu commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +				makeGCSandbox(pods[0], 1, runtimeapi.PodSandboxState_SANDBOX_READY, true),
Should have another exit `pods[0]` to make sure we don't keep latest exit if there is a running one.

2017-05-03 06:14 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +	// Remove from oldest to newest (last to first).
ACK. Would fix this.

2017-05-03 06:14 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			cgc.removeOldestNSandboxes(sandboxes, len(sandboxes)-1)
ACK

2017-05-03 06:30 UTC, feiskyer commented on pkg/kubelet/kuberuntime/kuberuntime_gc_test.go
> +				makeGCSandbox(pods[0], 1, runtimeapi.PodSandboxState_SANDBOX_READY, true),
ACK.

2017-05-03 06:30 UTC, feiskyer commented
@Random-Liu Updated. PTAL.

2017-05-03 06:36 UTC, Random-Liu approved these changes

2017-05-03 06:36 UTC, Random-Liu commented
/lgtm
/approve

2017-05-03 06:38 UTC, feiskyer commented
> @feiskyer Please keep an eye on the test grid to make sure this doesn't introduce flake. :)

Sure.

2017-05-03 08:07 UTC, merged