use healthz api in WaitForAPI
kubernetes/kubernetes pull request #43282
Opened 2017-03-17 09:13 UTC by xilabao

finish TODO

2017-03-20 20:17 UTC, dmmcquay requested changes
I think that we don't want to have both the `/healthz` checks and the `ComponentStatuses` being checked. 

@luxas am I correct in my logic?

2017-03-20 20:17 UTC, dmmcquay commented on cmd/kubeadm/app/master/apiclient.go
> +		healthStatus := 0
It seems we want to do something like this instead of what using `ComponentStatuses`, not both of them.

2017-04-06 13:38 UTC, luxas commented
@jbeda @mikedanese @krousey What do you think of this in general?
Should we switch to querying `/healthz` or stick to ComponentStatuses?
This PR per se needs reworking but I'd like to know where we want to go here...

2017-04-06 17:37 UTC, mikedanese commented
/healthz sounds more appropriate to me then componentstatus so I approve.

2017-04-06 17:43 UTC, krousey commented
/healthz is the appropriate check for the API being available.

2017-04-13 17:22 UTC, dmmcquay commented
@xilabao can you rebase and make the suggested changes?

2017-04-13 22:00 UTC, grodrigues3 commented
@k8s-bot ok to test

2017-04-17 03:17 UTC, xilabao commented
@k8s-bot unit test this

2017-04-17 05:33 UTC, xilabao commented
@dmmcquay PTAL

2017-04-17 14:04 UTC, luxas reviewed
We should check /healthz of the controller manager and scheduler as well, but good progress!

2017-04-17 18:12 UTC, mikedanese commented
We shouldn't check /healthz on those components in WaitForAPI. In WaitForAPI, we should wait for only the API.

2017-04-17 18:20 UTC, mikedanese commented
This change lgtm

2017-04-17 21:10 UTC, dmmcquay approved these changes

2017-04-17 21:10 UTC, dmmcquay commented
/lgtm

2017-04-17 21:12 UTC, dmmcquay commented
@xilabao Please edit your PR comment

2017-04-18 02:14 UTC, xilabao commented
@k8s-bot gce etcd3 e2e test this

2017-04-18 04:52 UTC, dmmcquay commented
/lgtm

2017-04-18 05:50 UTC, luxas commented
/approve

2017-04-18 05:52 UTC, luxas commented
We should still make sure the controller manager and scheduler comes up properly by checking their `/healthz`, but as @mikedanese pointed out, not in this specific function `WaitForAPI`

2017-04-18 07:17 UTC, merged