Update flex volume 1.6 documentation.
kubernetes/kubernetes pull request #43326
Opened 2017-03-17 20:51 UTC by chakri-nelluri

**What this PR does / why we need it**:
Update documentation for 1.6 flex volume changes.

2017-03-17 20:53 UTC, chakri-nelluri commented
@saad-ali @rootfs PTAL

2017-03-20 10:55 UTC, klausenbusk commented on examples/volumes/flexvolume/README.md
> +Flexvolume enables users to write their own drivers and add support for their volumes in Kubernetes. Vendor drivers should be installed in the volume plugin path on every Kubelet node and on master n
Missing hyphen (-) `--enable-controller-attach-detach`?

2017-03-20 10:56 UTC, klausenbusk commented on examples/volumes/flexvolume/README.md
> +#### Volume is Attached:
Only relevant if `--enable-controller-attach-detach` is set correct?

2017-03-20 17:12 UTC, saad-ali requested changes

2017-03-20 17:12 UTC, saad-ali commented on examples/volumes/flexvolume/README.md
> +#### Init:
When is this called by kubernetes? From what component (kubelet?)? What is it expected to do?

2017-03-20 17:12 UTC, saad-ali commented on examples/volumes/flexvolume/README.md
> +#### Init:
These questions should be answered for each callout.

2017-03-20 17:12 UTC, saad-ali commented on examples/volumes/flexvolume/README.md
> +This call-out does not pass "secrets" specified in Flexvolume spec. If your driver requires secrets, do not implement this call-out and instead use "mount" call-out and implement attach and mount in
This is the mount call?

2017-03-20 17:12 UTC, saad-ali commented on examples/volumes/flexvolume/README.md
> +Attach the volume specified by the given spec on the given host. On success, returns the device path where the device is attached on the node. Nodename param is only valid if "-enable-controller-atta
>  Nodename param is only valid if "-enable-controller-attach-detach" Kubelet option is enabled.

When attach/detach controller is disabled, kubelet calls attach, and I believe still provides the node name, no?

2017-03-20 18:02 UTC, chakri-nelluri commented
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/volumes/flexvolume/README.md, line 3 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43326#-KfT1UHmzB-euEalW4lW-r1-3:-KfgqYTant_KuWPryj3Z:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/522cf1876e3edc7b560e8e3b8d3c65cb6ebc95f9/examples/volumes/flexvolume/README.md#L3)):*
<details><summary><i>Previously, klausenbusk (Kristian Klausen) wrote…</i></summary><blockquote>

Missing hyphen (-) `--enable-controller-attach-detach`?
</blockquote></details>

Done.

---

*[examples/volumes/flexvolume/README.md, line 18 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43326#-KfT1UHmzB-euEalW4lW-r1-18:-KfgqPimLutsCsXeHvTK:b-ex66us) ([raw file](https://github.com/kubernetes/kubernetes/blob/522cf1876e3edc7b560e8e3b8d3c65cb6ebc95f9/examples/volumes/flexvolume/README.md#L18)):*
<details><summary><i>Previously, saad-ali (Saad Ali) wrote…</i></summary><blockquote>

These questions should be answered for each callout.
</blockquote></details>

Added "Called from Kubelet & Controller manager" for relevant callouts

---

*[examples/volumes/flexvolume/README.md, line 33 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43326#-KfT1UHmzB-euEalW4lW-r1-33:-KfglfLT-91rdRjJFTOc:bh6vzbw) ([raw file](https://github.com/kubernetes/kubernetes/blob/522cf1876e3edc7b560e8e3b8d3c65cb6ebc95f9/examples/volumes/flexvolume/README.md#L33)):*
<details><summary><i>Previously, saad-ali (Saad Ali) wrote…</i></summary><blockquote>

>  Nodename param is only valid if "-enable-controller-attach-detach" Kubelet option is enabled.

When attach/detach controller is disabled, kubelet calls attach, and I believe still provides the node name, no?
</blockquote></details>

Trying to signify it still provides but nodename but it not valid/relevant.

---

*[examples/volumes/flexvolume/README.md, line 54 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43326#-KfT1UHmzB-euEalW4lW-r1-54:-Kfgmelt2LY-96Wm7MFG:bwmh4pf) ([raw file](https://github.com/kubernetes/kubernetes/blob/522cf1876e3edc7b560e8e3b8d3c65cb6ebc95f9/examples/volumes/flexvolume/README.md#L54)):*
<details><summary><i>Previously, klausenbusk (Kristian Klausen) wrote…</i></summary><blockquote>

Only relevant if `--enable-controller-attach-detach` is set correct?
</blockquote></details>

It is getting called from both Kubelet & Controller manager right.

---

*[examples/volumes/flexvolume/README.md, line 64 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43326#-KfT1UHmzB-euEalW4lW-r1-64:-KfgntSJPtgnzN-vnqQI:b-rbd8cq) ([raw file](https://github.com/kubernetes/kubernetes/blob/522cf1876e3edc7b560e8e3b8d3c65cb6ebc95f9/examples/volumes/flexvolume/README.md#L64)):*
<details><summary><i>Previously, saad-ali (Saad Ali) wrote…</i></summary><blockquote>

This is the mount call?
</blockquote></details>

this is the mountdevice call-out.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43326)*
<!-- Sent from Reviewable.io -->

2017-03-20 18:30 UTC, devin-donnelly commented
@saad-ali Does this need to be documented on kubernetes.io (the web documentation)?

2017-03-20 19:29 UTC, saad-ali commented
> @saad-ali Does this need to be documented on kubernetes.io (the web documentation)?

Good question. Intended audience for Flex volume plugin is Kubernetes volume plugin developers. So maybe not?

2017-03-20 19:35 UTC, saad-ali commented
Other than the concern's @devin-donnelly raised about the correct place for this doc, LGTM

2017-03-20 21:21 UTC, chakri-nelluri commented
Thanks @saad-ali 

@devin-donnelly I agree with @saad-ali. This is only intended for volume plugin drivers. I don't think we need to update documentation on kubernetes.io.

2017-03-22 16:05 UTC, saad-ali commented
/lgtm
/approve

2017-03-22 16:05 UTC, saad-ali approved these changes

2017-03-23 18:25 UTC, saad-ali commented
/lgtm

2017-03-23 18:30 UTC, brendandburns commented
/approve

2017-03-23 19:45 UTC, merged