Add readme for fluentd addons
kubernetes/kubernetes pull request #43379
Opened 2017-03-20 12:57 UTC by crassirostris

/cc @steveperry-53

2017-03-22 08:25 UTC, piosz requested changes

2017-03-22 08:25 UTC, piosz commented on cluster/addons/fluentd-gcp/README.md
> +that reads logs, generated by kubelet, container engine and containers
what is container engine? is kubelet a part of container engine? is docker a part of container engine?

2017-03-22 10:24 UTC, crassirostris commented on cluster/addons/fluentd-gcp/README.md
> +that reads logs, generated by kubelet, container engine and containers
I meant container runtime, thanks for noticing

As for the specifying, what logs fluentd collects, on the one hand I want to give an idea about all sources, on the other hand, I don't want to go into details, explaining that it collects logs from docker daemon, vm creation scripts, salt and so on. It's not a right place for such details IMO.

2017-03-22 10:56 UTC, crassirostris commented
@k8s-bot unit test this

2017-03-22 10:56 UTC, crassirostris commented
@piosz PTAL

2017-03-22 12:37 UTC, crassirostris commented
@k8s-bot cvm gce e2e test this

2017-03-22 15:41 UTC, piosz approved these changes

2017-03-22 15:41 UTC, piosz commented
please squash commits

2017-03-22 15:46 UTC, crassirostris commented
@piosz I deliberately separated them. They both represent a clearly separable, complete unit of work.

2017-03-22 16:15 UTC, piosz commented
Is there any value from having them separately especially when there is gazillion of commits in the repo? Do you want to be able revert one of them independently? Does it help with review?

2017-03-22 16:20 UTC, crassirostris commented
@piosz I don't see why not and it looks cleaner to me :) If you feel strong about squashing them, I'm also fine with that

2017-03-23 09:08 UTC, piosz commented
/lgtm
/approve

2017-03-23 09:08 UTC, merged