Add stackdriver monitoring option [WIP]
kubernetes/kubernetes pull request #43381
Opened 2017-03-20 14:17 UTC by aleksandra-malinowska

2017-03-23 08:31 UTC, piosz commented
Please update Heaspter to `v1.3.0`. The previous version `v1.3.0-beta.1` doesn't have stackdriver sink. And the new one doesn't support `-disable_export` flag so you need to remove it and add TODO to introduce it with the next version bump.

Then please test that the newly introduced configuration actually works.

2017-03-24 12:54 UTC, piosz requested changes

2017-03-24 12:54 UTC, piosz commented on cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
> +        - image: gcr.io/google_containers/heapster-amd64:v1.3.0
we do not want to have eventer here

2017-03-27 11:00 UTC, aleksandra-malinowska commented on cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
> +        - image: gcr.io/google_containers/heapster-amd64:v1.3.0
Removed

2017-03-27 11:12 UTC, piosz commented
/lgtm
/approve

2017-03-27 11:12 UTC, piosz approved these changes

2017-03-27 18:43 UTC, mikedanese commented
/approve

2017-03-27 19:49 UTC, merged