add set rolebinding/clusterrolebinding command
kubernetes/kubernetes pull request #43436
Opened 2017-03-21 08:45 UTC by xilabao

add command to set user/group/serviceaccount in rolebinding/clusterrolebinding /cc @liggitt @deads2k

2017-03-22 02:49 UTC, liggitt commented
cc @kubernetes/sig-cli-pr-reviews @kubernetes/sig-auth-pr-reviews

2017-03-30 02:15 UTC, liggitt requested changes

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +		if reflect.DeepEqual(v, item) {
Can do a direct `==`, right?

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +			return o.PrintObject(o.Cmd, o.Mapper, info.Object, o.Out)
local only lets you output a single object?

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +		if obj, err = resource.NewHelper(info.Client, info.Mapping).Replace(info.Namespace, info.Name, false, obj); err != nil {
What is this doing? I don't see any recording supported that would make us need to update the object

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +		cmdutil.PrintSuccess(o.Mapper, o.ShortOutput, o.Out, info.Mapping.Resource, info.Name, false, "resource requirements updated")
Update message… we're not updating resource requirements

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +		cmdutil.PrintSuccess(o.Mapper, o.ShortOutput, o.Out, info.Mapping.Resource, info.Name, false, "resource requirements updated")
Does this print the right thing for all output formats? (Name, JSON, yaml, etc)

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +			return o.PrintObject(o.Cmd, o.Mapper, info.Object, o.Out)
Does this print correctly for output formats like JSON?

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +	cmd := &cobra.Command{
subjects or subject?

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +	kubectl set subject clusterrolebinding admin --serviceaccount1=namespace:serviceaccount1
--serviceaccount

2017-03-30 02:15 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subjects.go
> +	kubectl set subject rolebinding admin --user=user1,user2 --group=group1
--user=user1 --user=user2

2017-03-30 03:14 UTC, xilabao commented
@liggitt  Thanks for your review. I fixed the problems. PTAL

2017-03-31 05:26 UTC, xilabao commented
@liggitt @deads2k I use `kubectl unset` instead of `kubectl set --remove`. PTAL

2017-04-13 22:00 UTC, grodrigues3 commented
@k8s-bot ok to test

2017-04-14 15:39 UTC, kargakis commented
@kubernetes/sig-cli-api-reviews fyi, this PR introduces `kubectl unset`

2017-04-17 05:34 UTC, xilabao commented
@k8s-bot bazel test this
@k8s-bot verify test this

2017-04-18 05:57 UTC, xilabao commented
@k8s-bot cvm gce e2e test this

2017-04-18 08:19 UTC, xilabao commented
@liggitt @deads2k @kargakis PTAL

2017-04-25 01:53 UTC, xilabao commented
ping @liggitt

2017-04-25 02:02 UTC, liggitt commented
let's separate the `unset` command into a separate PR, I'm hesitant to introduce that pattern for this

2017-04-25 02:05 UTC, liggitt commented on pkg/kubectl/cmd/set/set_subject.go
> +		if len(tokens) != 2 {
`|| tokens[0] == "" || tokens[1] == ""`

2017-04-26 00:44 UTC, xilabao commented
@liggitt PTAL

2017-04-27 01:37 UTC, xilabao commented
@liggitt @deads2k kindly ping

2017-04-28 18:37 UTC, deads2k commented on pkg/kubectl/cmd/set/set_subject.go
> +	o.PrintObject = f.PrintObject
if you made this a closure, you could include `cmd` but not have in options, right?

```go
o.PrintObject= func(mapper meta.RESTMapper, obj runtime.Object, out io.Writer) error{
    return f.PrintObject(cmd, mapper, obj, out)
}
```

2017-04-28 18:38 UTC, deads2k commented on pkg/kubectl/cmd/set/set_subject.go
> +			return fmt.Errorf("serviceaccount must be <namespace>:<name>")
TODO: I'd like to find a way to allow `:name` for `roles`, but not `clusterroles`.  For roles it indicates, "use the current namespace"

2017-04-28 18:39 UTC, deads2k commented on pkg/kubectl/cmd/set/set_subject.go
> +	o.Infos, err = builder.Do().Infos()
Seems like this call should be down in Run so that we only contact the server during run.

2017-04-28 18:40 UTC, deads2k commented on pkg/kubectl/cmd/set/set_subject.go
> +		if o.Local || cmdutil.GetDryRunFlag(o.Cmd) {
dry run should be a bool on `options`

2017-04-28 18:41 UTC, deads2k commented on pkg/kubectl/cmd/set/set_subject.go
> +func updateSubjectForObject(obj runtime.Object, subjects []rbac.Subject, fn updateSubjects) (bool, error) {
note that this mutates `obj`

2017-04-28 18:42 UTC, deads2k commented on pkg/kubectl/cmd/set/set_subject.go
> +	resourceTypesWithPodTemplate := []string{}
This looks weird.  Why is it here?

2017-04-28 18:43 UTC, deads2k commented
a few minor comments and this lgtm.  Great command.

2017-05-02 08:27 UTC, xilabao commented
@k8s-bot unit test this

2017-05-03 08:23 UTC, xilabao commented
@k8s-bot unit test this

2017-05-05 08:35 UTC, xilabao commented
@deads2k PTAL

2017-05-05 11:58 UTC, deads2k commented
/lgtm
/release-note-none

2017-05-05 12:06 UTC, deads2k commented
@fabianofranz seems like the kubectl group may need approver rights in docs.

2017-05-05 14:21 UTC, merged