Add the support of volumes in Kubelet runonce
kubernetes/kubernetes pull request #43675
Opened 2017-03-26 19:41 UTC by JulienBalestra

**What this PR does / why we need it**:

This PR allows to create and mount volumes when the kubelet is started with `--runonce` flag.

**Which issue this PR fixes** 

Fixes #42909

**Special notes for your reviewer**:

During the `--runonce` process, the volumeManager have to be started and triggered by the `podManager.UpdatePod`

**Release note**:

 `NONE`

2017-04-26 18:33 UTC, JulienBalestra commented
keep-open

2017-04-26 18:33 UTC, JulienBalestra commented
We really need this PR, actually waiting for a reviewer @derekwaynecarr ?

2017-05-08 15:34 UTC, spiffxp commented
@k8s-bot ok to test
/cc @kubernetes/sig-node-pr-reviews

2017-05-11 15:28 UTC, JulienBalestra commented
Rebased the PR

2017-05-12 00:46 UTC, derekwaynecarr commented
@k8s-bot pull-kubernetes-cross test this

2017-05-12 00:49 UTC, derekwaynecarr requested changes

2017-05-12 00:49 UTC, derekwaynecarr commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +	var pods []*v1.Pod
i am confused on this change... can you explain why this was needed?

2017-05-12 00:49 UTC, derekwaynecarr commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +	var pods []*v1.Pod
for example, if there is a code block that has a nil active pods func, can we instead pass in a no-op version that just returns an empty list?

2017-05-12 00:50 UTC, derekwaynecarr commented
/cc @vishh -- do you have any concerns with volumes and run once kubelets?

2017-05-12 12:40 UTC, JulienBalestra commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +	var pods []*v1.Pod
This changes was introduced in 1.6 and still on master today.
Running the kubelet with `--runonce` give you this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdfefeb]

goroutine 171 [running]:
panic(0x30b3260, 0xc4200120f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/pkg/kubelet/cm.(*qosContainerManagerImpl).setCPUCgroupConfig(0xc4200b7180, 0xc420cfe300, 0xc420cc9228, 0xc420cc9220)
	/home/jb/go/src/github.com/JulienBalestra/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/qos_container_manager_linux.go:142 +0x5b
k8s.io/kubernetes/pkg/kubelet/cm.(*qosContainerManagerImpl).UpdateCgroups(0xc4200b7180, 0x0, 0x0)
	/home/jb/go/src/github.com/JulienBalestra/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/qos_container_manager_linux.go:268 +0x28c
k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).UpdateQOSCgroups(0xc42024e960, 0xc4207a4f00, 0xc420cbab00)
	/home/jb/go/src/github.com/JulienBalestra/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:480 +0x3a
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0xc42079c000, 0x0, 0xc4207a4f00, 0x1, 0xc420b10d90, 0x0, 0x7, 0xc420b10d90)
	/home/jb/go/src/github.com/JulienBalestra/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1473 +0x1695
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).runPod(0xc42079c000, 0xc4207a4f00, 0x3b9aca00, 0x0, 0x0)
	/home/jb/go/src/github.com/JulienBalestra/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/runonce.go:139 +0x411
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).runOnce.func1(0xc42079c000, 0x3b9aca00, 0xc420bf25a0, 0xc4207a4f00)
	/home/jb/go/src/github.com/JulienBalestra/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/runonce.go:87 +0x43
created by k8s.io/kubernetes/pkg/kubelet.(*Kubelet).runOnce
	/home/jb/go/src/github.com/JulienBalestra/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/runonce.go:89 +0x1dc
```

2017-05-12 16:53 UTC, JulienBalestra commented on pkg/kubelet/cm/qos_container_manager_linux.go
> +	var pods []*v1.Pod
> for example, if there is a code block that has a nil active pods func, can we instead pass in a no-op version that just returns an empty list?
Yes, I'll try this way and get back to you.

2017-08-11 08:03 UTC, closed without merging

2019-04-05 19:01 UTC, mdaniel commented
I can confirm this still panics as of 1.14.0; can we please land this PR just to stop kubelet from panicking? Even if it were to just `os.Exit(1)` with some "this is an unsupported configuration" message, that would be a better experience than a SIGSEGV