Add SuccessfulMountVolume message to the events of pod
kubernetes/kubernetes pull request #43852
Opened 2017-03-30 10:20 UTC by ailusazh

When creating a pod with volume, the volume mount may failed at first, but eventually succeed after retry several times. kubectl describe pod can only see the failed messages, so i think it will be better to add the SuccessfulMountVolume message to the pod events too.

2017-03-31 10:12 UTC, ailusazh commented
cc @justinsb PTAL

2017-04-01 08:41 UTC, NickrenREN commented
@k8s-bot ok to test

2017-04-01 08:41 UTC, NickrenREN commented
/assign

2017-04-01 08:52 UTC, NickrenREN commented
/lgtm

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43852#-:-Kgchjef-0gZHzgyh7tP:b-8ks5qa)*
<!-- Sent from Reviewable.io -->

2017-04-01 09:21 UTC, NickrenREN commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43852)*
<!-- Sent from Reviewable.io -->

2017-04-01 09:22 UTC, NickrenREN commented
/release-note-none

2017-04-05 02:00 UTC, ailusazh commented
@saad-ali all checks have passed, please add approved label. Thx

2017-04-19 05:38 UTC, justinsb commented
@k8s-bot non-cri e2e test this

2017-04-19 05:39 UTC, justinsb commented
This is a common source of confusion - thanks for fixing!

2017-05-03 02:39 UTC, ailusazh commented
@k8s-bot unit test this

2017-05-03 02:39 UTC, ailusazh commented
@k8s-bot cvm gce e2e test this

2017-05-18 01:48 UTC, msau42 commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		mountMsg := volumeToMount.GenerateMsgDetailed("MountVolume.SetUp succeeded", "")
Can you use the simple msg for the event, and detailed msg for logging?

2017-05-18 01:50 UTC, msau42 commented
Also please add "Fixes #42867" to your first comment.

2017-05-18 10:54 UTC, ailusazh commented
@msau42 thank you for your suggestion. I have already modified the mountedEventMsg, is this ok?

2017-05-18 16:16 UTC, msau42 commented on pkg/volume/util/operationexecutor/operation_generator.go
>  		glog.Infof(volumeToMount.GenerateMsgDetailed("MountVolume.SetUp succeeded", ""))
There's a GenerateMsg() call that returns both a simple and detailed msg.

2017-05-19 06:53 UTC, ailusazh commented
@msau42 how about this time？

2017-05-19 17:24 UTC, msau42 commented
lgtm, but looks like you need to fix some formatting first

2017-05-22 06:44 UTC, ailusazh commented
Is there anything else that i need to do except execute gofmt of this file?

2017-05-22 17:18 UTC, msau42 commented
No, it looks fine.  Thanks for taking care of this!

/lgtm

2017-05-28 09:46 UTC, ailusazh commented
@NickrenREN @justinsb @msau42 the log message on the master has changed, please review again.

2017-05-30 16:25 UTC, msau42 commented
LGTM, please fix the failed tests.

2017-05-31 08:03 UTC, ailusazh commented
@msau42 the rest of the error seems to have nothing to do with my pr. Can this be merged?

2017-05-31 17:00 UTC, msau42 commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-05-31 17:00 UTC, msau42 commented
/lgtm

2017-05-31 17:00 UTC, msau42 commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-31 17:33 UTC, saad-ali requested changes

2017-05-31 17:33 UTC, saad-ali commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		og.recorder.Eventf(volumeToMount.Pod, v1.EventTypeNormal, kevents.SuccessfulMountVolume, simpleMsg)
Don't generate the event if `isRemount` is true (otherwise the event logs will be spammed).

2017-06-01 10:57 UTC, ailusazh commented
@saad-ali how about midified like this?

2017-06-01 18:54 UTC, msau42 commented
/lgtm

2017-06-01 21:56 UTC, saad-ali approved these changes

2017-06-01 21:56 UTC, saad-ali commented
/lgtm
/approve

2017-06-02 16:46 UTC, msau42 commented
@k8s-bot pull-kubernetes-unit test this

2017-06-05 06:07 UTC, NickrenREN commented
@k8s-bot kops aws e2e test this
@k8s-bot pull-kubernetes-unit test this

2017-06-05 08:46 UTC, merged