Reduce the number of calculating usage
kubernetes/kubernetes pull request #44149
Opened 2017-04-06 10:53 UTC by FengyunPan

The quotaEvaluator call Usage() to calculate usage twice for every
admission attributes, and calculating usage will waste much time.

2017-04-12 03:16 UTC, FengyunPan commented
/release-note-none

2017-04-24 22:55 UTC, derekwaynecarr requested changes
if we move the code as noted, i think we need to make sure the block here is also moved above.

https://github.com/kubernetes/kubernetes/pull/44149/files#diff-1622c871bcd912b43639c9d3d441e713L445

2017-04-26 05:25 UTC, FengyunPan commented
@derekwaynecarr Alright, I will update it soon.

2017-04-26 05:29 UTC, FengyunPan commented
@derekwaynecarr Thank for your review, I have updated it.

2017-05-26 14:08 UTC, derekwaynecarr commented
@k8s-bot ok to test

2017-05-26 14:15 UTC, derekwaynecarr requested changes
this appears to calculate usage even if there is no interesting quota or limited resource.  we should only calculate usage if there is an interesting quota or a limited resource.

2017-05-26 14:15 UTC, derekwaynecarr commented on plugin/pkg/admission/resourcequota/controller.go
> +	// if we have limited resources enabled for this resource, always calculate usage
this issue i have with the code now is that usage is calculated all the time.  we should only need to calculate use if there is a matching limited resource (which is an alpha feature at moment) or if there is an actually interesting covering quota.  can this be structured to ensure that usage is only calculated if the above constraints are satisfied?

2017-05-26 16:29 UTC, closed without merging