De-Flake Volume E2E:  force GCEPD detach to prevent timeout
kubernetes/kubernetes pull request #44356
Opened 2017-04-11 19:23 UTC by copejon

**What this PR does / why we need it**:
Fix flake`[k8s.io] Volumes [Volume] [k8s.io] PD should be mountable [Flaky] 5m38s.  

Flake occurs as a result of an automated detach taking longer than 5 minutes, which exceeds the timeout limit of the delete function.

This PR adds explicit detach and wait func calls before the deletion.  By forcing the detach and giving GCE an appropriate timeout limit, this should squash the timeout flake.  This also significantly shortens cleanup time.

This PR does not remove the [Flaky] tag.  Once this PR is merged, I'll keep an eye on the test grid for ~1 week.  If no flakes surface, I'll submit a PR to pull the tag off.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes  #43977

**Release note**:

```release-note
NONE
```

2017-04-11 19:26 UTC, copejon commented
/assign @jeffvance

2017-04-11 19:33 UTC, copejon commented
@k8s-bot ok to test

2017-04-11 19:56 UTC, jeffvance commented
/approve

2017-04-11 20:11 UTC, jeffvance commented
@k8s-bot test this

2017-04-11 20:58 UTC, jeffvance commented
@k8s-bot test this

2017-04-11 22:36 UTC, jeffvance commented
/lgtm

2017-04-12 11:18 UTC, gmarek commented
/approve

2017-04-12 19:25 UTC, copejon commented
kops AWS e2e shows the same failure for all tests:
> client: etcd cluster is unavailable or misconfigured

@jeffvance can you rerun?

2017-04-12 21:58 UTC, saad-ali requested changes

2017-04-12 21:58 UTC, saad-ali commented on test/e2e/volumes.go
> +				Expect(err).NotTo(HaveOccurred(), "Timeout waiting for PD %q to detach from client %q on node %q", volumeName, pod.Name, pod.Spec.NodeName)
Should delete disk even if `waitForPDDetach` fails

2017-04-12 21:58 UTC, saad-ali commented on test/e2e/volumes.go
> +				Expect(err).NotTo(HaveOccurred(), "Timeout waiting for PD %q to detach from client %q on node %q", volumeName, pod.Name, pod.Spec.NodeName)
Better yet, just use the `detachAndDeletePDs(...)` method which does all the heavy lifting for you.

2017-04-12 21:58 UTC, saad-ali commented on test/e2e/volumes.go
> +				Expect(err).NotTo(HaveOccurred(), "Failed getting pod %q.", config.Prefix+"-client")
Should delete disk even if getting pod fails, to prevent leaking disks.

2017-04-13 14:02 UTC, copejon commented on test/e2e/volumes.go
> +				Expect(err).NotTo(HaveOccurred(), "Timeout waiting for PD %q to detach from client %q on node %q", volumeName, pod.Name, pod.Spec.NodeName)
Ah, I missed that func!  Thanks, will add.

2017-04-19 04:03 UTC, jeffvance commented on test/e2e/storage/volumes.go
> +				Expect(err).NotTo(HaveOccurred(), "Failed getting pod %q.", config.Prefix+"-client")
Question: if the pod Get() fails is there a way to detatch / delete the PD without having a current copy of the pod? Eg. if the pod's name and ns are known, is there a func that detatches/deletes based on those fields?

2017-04-19 04:03 UTC, jeffvance commented
/approve

2017-04-20 21:57 UTC, saad-ali commented
@k8s-bot ok to test

2017-04-20 21:57 UTC, saad-ali commented
/lgtm
/approve

2017-04-21 00:05 UTC, merged