nodecontroller eventsource is not accurate
kubernetes/kubernetes pull request #44431
Opened 2017-04-13 03:05 UTC by knightXun

as this title,i change the eventsource.

2017-04-13 03:26 UTC, xiangpengzhao requested changes

2017-04-13 03:26 UTC, xiangpengzhao commented on pkg/controller/node/nodecontroller.go
> +	recorder := eventBroadcaster.NewRecorder(api.Scheme, clientv1.EventSource{Component: "node-controller"})
It makes sense. Would you please check EventSource of other controllers in pkg/controller ?

2017-04-13 03:30 UTC, xiangpengzhao commented on pkg/controller/node/nodecontroller.go
> +	recorder := eventBroadcaster.NewRecorder(api.Scheme, clientv1.EventSource{Component: "node-controller"})
and it'd better to fix them in one single PR.

2017-04-13 03:33 UTC, knightXun commented on pkg/controller/node/nodecontroller.go
> +	recorder := eventBroadcaster.NewRecorder(api.Scheme, clientv1.EventSource{Component: "node-controller"})
yep,i will notice this next time.

2017-04-13 03:41 UTC, xiangpengzhao commented on pkg/controller/node/nodecontroller.go
> +	recorder := eventBroadcaster.NewRecorder(api.Scheme, clientv1.EventSource{Component: "node-controller"})
[here](https://github.com/knightXun/kubernetes/blob/b939199fcf05584624ae734b57122c5a17539751/pkg/controller/node/taint_controller.go#L155) and other possible places.

2017-04-13 05:36 UTC, gmarek commented on pkg/controller/node/nodecontroller.go
> +	recorder := eventBroadcaster.NewRecorder(api.Scheme, clientv1.EventSource{Component: "node-controller"})
Yeah, we use `controllermanager` in all places I know of. This change kind of makes sense, but only if we change it everywhere.

2017-04-13 06:29 UTC, xiangpengzhao commented on pkg/controller/node/nodecontroller.go
> +	recorder := eventBroadcaster.NewRecorder(api.Scheme, clientv1.EventSource{Component: "node-controller"})
I simply search `EventSource` in pkg/controller and find that there are only four places using `controllermanager` and other places using more accurate names such as [job-controller](https://github.com/knightXun/kubernetes/blob/b939199fcf05584624ae734b57122c5a17539751/pkg/controller/job/jobcontroller.go#L92), [persistentvolume-controller](https://github.com/knightXun/kubernetes/blob/b939199fcf05584624ae734b57122c5a17539751/pkg/controller/volume/persistentvolume/pv_controller_base.go#L75) :)

2017-04-13 18:17 UTC, grodrigues3 commented
@k8s-bot ok to test

2017-04-17 12:46 UTC, knightXun commented
ok,i will find every suspicious mistake and commit with one pr.

2017-04-17 12:47 UTC, knightXun commented
i am going to close this pr,thx all.

2017-04-17 12:49 UTC, closed without merging