Fix attach volume to instance repeatedly
kubernetes/kubernetes pull request #44537
Opened 2017-04-16 07:34 UTC by FengyunPan

When volume's status is 'attaching', volume's attachments will
be "", and kubernetes will attach it repeatedly.
So it is necessary to check status before attach/detach volume.

Fix bug: #44536

2017-04-16 07:48 UTC, FengyunPan commented
/release-note-none

2017-04-17 15:02 UTC, derekwaynecarr commented
is there a test case that can demonstrate the problem that was fixed?

2017-04-18 09:25 UTC, FengyunPan commented
@derekwaynecarr Hi, I have added a test case for it.

2017-04-18 22:59 UTC, gnufied requested changes

2017-04-18 22:59 UTC, gnufied commented on pkg/volume/cinder/attacher.go
> +	HasDone, VolumeStatus, err := attacher.cinderProvider.OperateHasDone(volumeID)
Fix the naming of these variables please. Make sure they start with lower case letters.

2017-04-18 22:59 UTC, gnufied commented on pkg/volume/cinder/attacher.go
> +	HasDone, _, err = attacher.cinderProvider.OperateHasDone(volumeID)
same as before about naming.

2017-04-18 22:59 UTC, gnufied commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +func (os *OpenStack) OperateHasDone(diskName string) (bool, string, error) {
Can you rename this function to something like - `OperationPending` ?

2017-04-18 22:59 UTC, gnufied commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +)
Lets be consistent about naming. Constants generally start with upper case letter.

2017-04-18 22:59 UTC, gnufied commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +		glog.Errorf("volume's status is %s", VolumeStatus)
Can you log the disk name when we are logging the error? Without disk name, this error log will be probably useless

2017-04-18 22:59 UTC, gnufied commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +		errmsg := fmt.Sprintf("volume %s status is %s, not %s, can not be attached to instance %s.", volume.Name, volume.Status, volumeAvailableStatus, instanceID)
Please use ` fmt.Errorf`

2017-04-18 22:59 UTC, gnufied commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
>  }
typo?

2017-04-19 05:16 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +)
Done.

2017-04-19 05:20 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +		glog.Errorf("volume's status is %s", VolumeStatus)
Done.

2017-04-19 05:20 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +func (os *OpenStack) OperateHasDone(diskName string) (bool, string, error) {
Done.

2017-04-19 05:28 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +		errmsg := fmt.Sprintf("volume %s status is %s, not %s, can not be attached to instance %s.", volume.Name, volume.Status, volumeAvailableStatus, instanceID)
the errmsg of errors.New(errmsg) should be a string not a error

2017-04-19 06:17 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
>  }
Done

2017-04-19 06:18 UTC, FengyunPan commented on pkg/volume/cinder/attacher.go
> +	HasDone, VolumeStatus, err := attacher.cinderProvider.OperateHasDone(volumeID)
Done

2017-04-19 06:18 UTC, FengyunPan commented on pkg/volume/cinder/attacher.go
> +	HasDone, _, err = attacher.cinderProvider.OperateHasDone(volumeID)
Done

2017-04-19 06:19 UTC, FengyunPan commented on pkg/volume/cinder/attacher.go
> +	HasDone, _, err = attacher.cinderProvider.OperateHasDone(volumeID)
Have updated it.

2017-04-19 15:27 UTC, idvoretskyi commented
cc @kubernetes/sig-openstack-pr-reviews

2017-05-05 14:01 UTC, dims commented
@k8s-bot ok to test

2017-05-05 14:25 UTC, dims commented
@FengyunPan Can  you please check on the failed jobs?

2017-05-12 10:42 UTC, FengyunPan commented
@k8s-bot bazel test this
@k8s-bot unit test this

2017-05-13 07:55 UTC, FengyunPan commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-13 08:24 UTC, FengyunPan commented
@k8s-bot kops aws e2e test this

2017-05-13 09:05 UTC, FengyunPan commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-13 09:44 UTC, FengyunPan commented
@dims I have checked the failed jobs, we can ignore "pull-kubernetes-federation-e2e-gce" jobs because it is federation's jobs.

2017-05-13 12:07 UTC, dims commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-13 12:07 UTC, dims commented
/assign @dims

2017-05-13 12:08 UTC, dims commented
/approve
/lgtm

2017-05-13 12:37 UTC, FengyunPan commented
@jsafrane  @mikedanese Hi,  I'd like you to do a code review, thank you.

2017-05-13 12:38 UTC, FengyunPan commented
/assign @jsafrane @mikedanese

2017-05-14 01:50 UTC, FengyunPan commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-15 09:54 UTC, jsafrane commented
/approve

2017-05-15 10:01 UTC, dims commented
/assign @mikedanese

2017-05-15 14:56 UTC, FengyunPan commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-16 17:45 UTC, mikedanese commented
/approve

2017-05-17 01:10 UTC, merged

2017-06-05 22:46 UTC, saad-ali commented
This PR broke Flex volumes. See https://github.com/kubernetes/kubernetes/issues/46882#issuecomment-306331570. Proposing reverting (at least partially this PR). Please discuss on that issue.