kubectl create ingress command
kubernetes/kubernetes pull request #44534
Opened 2017-04-16 05:09 UTC by justinsb

`kubectl create ingress` is a subcommand of `kubectl create` which creates
an ingress.

It takes a name positional argument, which is the name of the ingress to
create.

It also takes a repeated --host parameter, which is the hostname to use
in the ingress.

If --service-name or --service-port are specified, those values will be
used for the backend service name and port.  Otherwise we default the
name to the same as the ingress name, and the port to 80 (because
ingress is primarily an HTTP concept).

If --tls-acme is specified, TLS will also be configured on the ingress,
with the annotations as used by the kube-lego LetsEncrypt controller,
and a secret named `tls-<ingress name>`, configured for all the
specified hosts.

Close #43667

```release-note
`kubectl create ingress` subcommand added
```

2017-04-16 14:48 UTC, xiangpengzhao commented on pkg/kubectl/cmd/create_ingress.go
> +	cmd.Flags().String("service-port", "80", "Port of backend service.")
Give a explicit tip of default service-port for users? Such as `Port of backend service. Default to 80.`

2017-04-16 14:48 UTC, xiangpengzhao commented on pkg/kubectl/ingress.go
> +func (g *IngressV1Beta1) validate() error {
If `service-port` is specified, should we validate if the `service-port` has a valid name or be in a valid range?

2017-04-16 15:56 UTC, xiangpengzhao requested changes

2017-04-16 15:56 UTC, xiangpengzhao commented on pkg/kubectl/ingress.go
> +// StructuredGenerate outputs a ResourceQuota object using the configured fields
s/a ResourceQuota/an Ingress

2017-04-25 06:08 UTC, justinsb commented on pkg/kubectl/cmd/create_ingress.go
> +	cmd.Flags().String("service-port", "80", "Port of backend service.")
Done!

2017-04-25 06:08 UTC, justinsb commented on pkg/kubectl/ingress.go
> +func (g *IngressV1Beta1) validate() error {
We would normally hit k8s API validation, anyway, but I added it

2017-04-25 06:08 UTC, justinsb commented on pkg/kubectl/ingress.go
> +// StructuredGenerate outputs a ResourceQuota object using the configured fields
Thanks - nice spot

2017-04-25 06:08 UTC, justinsb commented
Made fixes per review

2017-04-25 06:14 UTC, xiangpengzhao commented on pkg/kubectl/ingress.go
> +// StructuredGenerate outputs a ResourceQuota object using the configured fields
:)

2017-04-26 21:57 UTC, justinsb commented
@fabianofranz ping for /approve

2017-04-28 17:20 UTC, fabianofranz commented
@kubernetes/sig-cli-misc

2017-05-04 14:36 UTC, fabianofranz commented on pkg/kubectl/cmd/create_ingress.go
> +	cmd.Flags().StringSlice("host", []string{}, "Host name for the ingress record")
Looks like this flag is required, so it needs `cmd.MarkFlagRequired`.

2017-05-04 14:39 UTC, fabianofranz commented on pkg/kubectl/cmd/create_ingress.go
> +	cmd.Flags().Bool("tls-acme", false, "Enables ACME (LetEncrypt) support for automatic TLS")
Let’s Encrypt

2017-05-04 14:41 UTC, fabianofranz commented
@justinsb Sorry about the delay! Just a couple minor comments, make sure you squash then this is good to go.

2017-05-08 03:30 UTC, justinsb commented
Thanks @fabianofranz - should be all fixed up & squashed

2017-05-08 15:58 UTC, fabianofranz commented on pkg/kubectl/cmd/create_ingress.go
> +    # Create a new ingress named my-ingress supporting TLS with LetsEncrypt
Let’s Encrypt

2017-05-08 15:58 UTC, fabianofranz commented
> should be all fixed up & squashed

not yet, forgot to `git push`?  ;)

2017-05-09 14:54 UTC, justinsb commented
@k8s-bot bazel test this

Weird git error

2017-05-09 15:32 UTC, justinsb commented
Thanks @fabianofranz - I had indeed failed to push!  Should be fixed now!

2017-05-09 16:33 UTC, fabianofranz commented
LGTM from a CLI perspective, @smarterclayton mind taking a conceptual look at this?

2017-05-10 14:02 UTC, justinsb commented
/assign @smarterclayton

2017-05-24 02:38 UTC, justinsb commented
ping @smarterclayton

2017-06-01 04:15 UTC, justinsb commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this

@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-01 05:56 UTC, justinsb commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-06 18:32 UTC, grodrigues3 commented
@justinsb this looks like a feature that was not lgtm'd prior to code freeze.  Removing from the milestone.

2017-06-13 06:06 UTC, justinsb commented
ping @smarterclayton

2017-06-13 06:22 UTC, xiangpengzhao reviewed
`pull-kubernetes-bazel` failed.

2017-06-13 06:22 UTC, xiangpengzhao commented on pkg/kubectl/cmd/create_ingress_test.go
> +	tf.Printer = printer
```
I0613 06:12:09.973] pkg/kubectl/cmd/create_ingress_test.go:53: cannot use printer (type *testIngressPrinter) as type printers.ResourcePrinter in assignment:
I0613 06:12:09.974] 	*testIngressPrinter does not implement printers.ResourcePrinter (missing IsGeneric method)
```

2017-07-10 23:54 UTC, justinsb commented
@smarterclayton appears to have turned off all github notifications.

/unassign smarterclayton

2017-07-10 23:57 UTC, justinsb commented
/unassign ghodds
/unassign ericchiang

2017-07-10 23:57 UTC, justinsb commented
/unassign ghodss

2017-07-13 04:15 UTC, smith commented
I would like to shadow this code review

2019-02-26 14:59 UTC, liggitt commented
given the [in progress move to networking.k8s.io](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md), and the impending removal of extensions/v1beta1, let's avoid adding new uses of extensions/v1beta1, especially in clients like kubectl that have longer skew support

2019-03-15 16:12 UTC, liggitt commented
closing this for now, can revisit once ingress v1 plans are completed in 1.15

/closew

2019-03-15 16:12 UTC, closed without merging