Liveness check starts after container is ready
kubernetes/kubernetes pull request #44595
Opened 2017-04-18 02:34 UTC by fraenkel

Allow liveness to begin probing when there is no initial delay once the
container is ready. Any non-zero initial delay will behave as it did
previously which starts probing when the container starts.

fixes #27114

```release-note
Liveness probe begins after the container is marked ready when the initial delay is 0 seconds.
```

2017-04-18 11:16 UTC, fraenkel commented
@k8s-bot gce etcd3 e2e test this
@k8s-bot verify test this
@k8s-bot cvm gce e2e test this

2017-04-24 17:27 UTC, dims commented
/approve

2017-05-19 17:22 UTC, mtaufen commented on pkg/kubelet/prober/worker.go
> +	dependentManager results.Manager
Why not call this `readinessManager`, if that's what it's used for?

2017-05-19 20:46 UTC, fraenkel commented on pkg/kubelet/prober/worker.go
> +	dependentManager results.Manager
Only because there was no guarantee you passed in a readiness manager.  You could have others.
I will rename it.

2017-05-19 21:00 UTC, yujuhong requested changes
This PR would change the meaning of the readiness and liveness checks. A container can be alive but not ready, or not alive and not ready. With this PR, a container may never be killed and restarted if it's not ready. I don't think this should be allowed.

2017-05-19 21:23 UTC, fraenkel commented
There is only 1 case where the behavior does change, otherwise it is exactly the same.
If you have readiness set and a liveness delay of 0, you get the waiting behavior. One can argue that is configuration doesn't even make sense in the current world since liveness begins regardless of readiness.

2017-05-19 21:25 UTC, yujuhong commented
IIUC, liveness was intended to start before readiness in many cases. A process is running doesn't mean it's ready to serve traffic. It won't be restarted (since it passes liveness checks), but will not be listed as endpoints in a service.

2017-05-19 21:33 UTC, fraenkel commented
I guess it all depends on how you do liveness. Many people were using probes so you need the process to be ready.
I was trying to avoid adding yet another flag to allow this behavior. I assume we should discuss how one can have liveness begin after readiness when that makes senses.

2017-05-22 20:09 UTC, dims commented
/unassign

2017-05-22 20:24 UTC, yujuhong commented
@fraenkel, I think we all agree that changing the semantics liveness/readiness checks may cause undesirable surprises to existing users. If you don't mind, let's close this PR and continue discussing on the issue to find a better solution.

2017-05-22 20:38 UTC, fraenkel commented
Closing for further discussion.

2017-05-22 20:38 UTC, closed without merging