Setting default size unit to Gib when unit is not specified in the PVC request
kubernetes/kubernetes pull request #44611
Opened 2017-04-18 13:50 UTC by divyenpatel

**What this PR does / why we need it**:
This PR is allowing PV provisioning without specifying unit in the PVC request

Customer reported issue  https://github.com/kubernetes/kubernetes/issues/43319 - "Unable to provision vSphere volume if PVC's requested size does not have unit"

With this change, when unit is not specified in the PVC request, we are defaulting to Gib for Volume Provisioning. 

**Which issue this PR fixes**
fixes # 43319, https://github.com/vmware/kubernetes/issues/130

**Special notes for your reviewer**:
Verified provisioning PVs using following YAML, able to provision PV in Gib.

```
$ cat thin_pvc_no_units.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thinclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: thin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2
```

Also verified creating StatefulSet without setting units in the volumeClaimTemplates

```
.
.
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: thin
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1
.
.
```
Also verified with specifying binary SI units in the request size to confirm change is not breaking existing functionality.
  
cc: @tusharnt @BaluDontu @pdhamdhere

**Release note**:

```release-note
None
```

2017-04-18 16:11 UTC, xiangpengzhao commented on pkg/volume/vsphere_volume/vsphere_volume_util.go
> +		volSizeKB = int(volSizeBytes) * 1048576
use `1024*1024` instead of `1048576` to be more readable?

2017-04-18 16:26 UTC, xiangpengzhao reviewed
Can this default be applied to other volume type? We may also need to document this somewhere.

2017-04-18 19:08 UTC, divyenpatel commented on pkg/volume/vsphere_volume/vsphere_volume_util.go
> +		volSizeKB = int(volSizeBytes) * 1048576
fixed.

2017-04-18 19:19 UTC, divyenpatel commented
> Can this default be applied to other volume type? We may also need to document this somewhere.
@childsb reported other provisioners allow a number only size for provisioning and assumes a default (usually gigs). This doesn't work in vsphere provisioned volumes. 

for vsphere, even if no unit is specified, current code allows provisioning with considering capacity specified in kb, which leads to the fault - vim.hostd.vdisksvc.diskSizeTooSmall

This error is not visible to user, and its confusing, kubernetes keeps trying to provision pv with such small size.

defaulting to Gi is good for users who do not know binary SI symbols for units.

2017-04-18 21:22 UTC, BaluDontu commented on pkg/volume/vsphere_volume/vsphere_volume_util.go
> -			fstype = value
Why is this removed ? Can you please fix it.

2017-04-18 21:22 UTC, BaluDontu commented on pkg/volume/vsphere_volume/vsphere_volume_util.go
> +		// if no unit is specified, convert to GiB
Can you specify it clearly that the default will be Gi when no unit specified. Also update the documentation for this. Add the documentation change as a part of this fix.

2017-04-18 22:26 UTC, divyenpatel commented on pkg/volume/vsphere_volume/vsphere_volume_util.go
> +		// if no unit is specified, convert to GiB
fixed. provided note in the examples/volumes/vsphere/README.md

2017-04-18 22:26 UTC, divyenpatel commented on pkg/volume/vsphere_volume/vsphere_volume_util.go
> -			fstype = value
fixed

2017-04-18 22:28 UTC, divyenpatel commented
@derekwaynecarr @saad-ali @bprashanth can you approve this PR?

2017-04-19 02:25 UTC, xiangpengzhao requested changes

2017-04-19 02:25 UTC, xiangpengzhao commented on examples/volumes/vsphere/README.md
> +      if unit is not specified, Default will be Gi.
nits: s/if/If , s/Default/default

2017-04-19 02:42 UTC, xiangpengzhao commented
>Can this default be applied to other volume type? We may also need to document this somewhere.

I mean could you check if other volume types, such as `aws_ebs` and so on, have the same issue? AFAIK, they do have. We may want to set default size unit to Gib for all the volume types besides vsphere.

@jingxu97

2017-04-20 16:39 UTC, divyenpatel commented on examples/volumes/vsphere/README.md
> +      if unit is not specified, Default will be Gi.
fixed.

2017-04-21 02:33 UTC, derekwaynecarr requested changes
This is wrong.  Defaulting the unit notation is not something that should be volume type specific.  The whole point of a pvc is it should have a common meaning across all volume types.

2017-04-21 02:37 UTC, derekwaynecarr commented
This also breaks quota by size if I am not mistaken as quota assumes the same meaning across all pvc.  Unitless values that have different meanings is a big problem.  Quota does not look at the size of the resultant pv just the pvc.

@eparis

2017-04-21 02:46 UTC, smarterclayton commented
We don't accept underspecified unitless values anywhere else - not sure why we should allow it here?

2017-04-21 02:48 UTC, smarterclayton commented
If we are allowing this behavior in other parts of the storage API that's concerning - is there a concrete reason that is allowed elsewhere?

2017-04-21 02:49 UTC, smarterclayton commented
@kubernetes/sig-storage-misc

2017-04-22 12:38 UTC, eparis commented
assigning to @childsb to get consistency across plugins. Either enforcing units or making sure all plugins consistently interpret unitless.

2017-04-22 12:45 UTC, liggitt commented
The volume plugins all interpret unitless as bytes today, which is correct, but they round up to the nearest allocation unit (usually GB) which is both confusing (asking for 1,2,or 3 all get you a 1GB volume) and breaks quota's view of the world 

This PR is definitely not correct. Unitless storage and memory requests always mean bytes.

2017-04-23 05:24 UTC, thockin commented
I appreciate the ...uhhh... creative interpretation here, but Quantities are used throughout the system.  We're not going to special case like this.

@lavalamp FYI as owner of quantity

2017-04-23 05:24 UTC, closed without merging