Update kubelet to use the network-plugin-dir if the cni-bin-dir flag is not set.
kubernetes/kubernetes pull request #44692
Opened 2017-04-20 00:22 UTC by dnardo

This is a fix for the regession raised in issue #44683

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-04-20 00:23 UTC, dnardo commented
/fix #44683

2017-04-20 00:23 UTC, freehan commented
@k8s-bot ok to test

2017-04-20 15:38 UTC, dashpole commented
/unassign

2017-04-20 16:45 UTC, dnardo commented
@k8s-bot ok to test

2017-04-20 16:45 UTC, MrHohn commented
@k8s-bot ok to test

2017-04-20 17:38 UTC, freehan commented
/lgtm
/approve

2017-04-20 17:39 UTC, freehan commented
@Random-Liu please approve

2017-04-20 17:41 UTC, tmrts requested changes

2017-04-20 17:41 UTC, tmrts commented on cmd/kubelet/app/plugins.go
> +	if binDir == "" {
Can you add a simple regression test for it?

2017-04-20 20:45 UTC, freehan commented on cmd/kubelet/app/plugins.go
> +	if binDir == "" {
The plan is to deprecate `network-plugin-dir` flag. And this PR is mainly fixing the regression.

2017-04-21 05:46 UTC, dchen1107 commented
/lgtm

2017-04-21 07:27 UTC, merged