Display GPU requests and limits
kubernetes/kubernetes pull request #44836
Opened 2017-04-24 07:36 UTC by mYmNeo

Signed-off-by: thomassong <thomassong@tencent.com>

**What this PR does / why we need it**:
Display GPU requests and limits in `kubectl describe`, like this
```
Non-terminated Pods:		(1 in total)
  Namespace			Name					CPU Requests	CPU Limits	Memory Requests	Memory Limits	GPU Requests	GPU Limits
  ---------			----					------------	----------	---------------	-------------	------------	----------
  kube-system			kube-dns-806549836-45kg7		260m (6%)	0 (0%)		110Mi (1%)	170Mi (2%)	0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
 CPU Requests	CPU Limits	Memory Requests	Memory Limits	GPU Requests	GPU Limits
  ------------	----------	---------------	-------------	------------	----------
  260m (6%)	0 (0%)		110Mi (1%)	170Mi (2%)	0 (0%)		0 (0%)
```

2017-04-24 16:45 UTC, cmluciano requested changes
I do not believe that GPU requests will provide useful information since limits are not supported. 

Some of the type declarations do not feel appropriate for the current GPU implementation.

2017-04-24 16:45 UTC, cmluciano commented on pkg/printers/internalversion/describe.go
> +	w.Write(LEVEL_1, "Namespace\tName\t\tCPU Requests\tCPU Limits\tMemory Requests\tMemory Limits\tGPU Requests\tGPU Limits\n")
I don't think that we support GPU requests, only limits

2017-04-24 16:45 UTC, cmluciano commented on pkg/printers/internalversion/describe.go
> +			gpuReq.String(), int64(fractionGPUReq), gpuLimit.String(), int64(fractionGPULimit))
Fractional GPU requests are not support, nor will the probably be supported for a long time.

2017-04-24 16:45 UTC, cmluciano commented on pkg/printers/internalversion/describe.go
> +			gpuReq.String(), int64(fractionGPUReq), gpuLimit.String(), int64(fractionGPULimit))
Nit: Int64 seems unnecessary since only whole numbers are supported at the moment.

2017-04-24 17:30 UTC, dims commented
@k8s-bot ok to test

2017-04-25 01:51 UTC, mYmNeo commented on pkg/printers/internalversion/describe.go
> +	w.Write(LEVEL_1, "Namespace\tName\t\tCPU Requests\tCPU Limits\tMemory Requests\tMemory Limits\tGPU Requests\tGPU Limits\n")
The document says it should be set by using limits, but actually k8s help to [complete the requests](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/defaults.go#L126) and give a guarantee of [check](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/validation/validation.go#L50)

2017-04-25 01:54 UTC, mYmNeo commented on pkg/printers/internalversion/describe.go
> +			gpuReq.String(), int64(fractionGPUReq), gpuLimit.String(), int64(fractionGPULimit))
Yeah, I know. But there'll be no need to change the code again if we support share the GPU in the future?

2017-05-01 11:37 UTC, dims commented
/unassign

2017-05-01 11:37 UTC, dims commented
/unassign @dims

2017-07-31 00:03 UTC, closed without merging