#44203
kubernetes/kubernetes pull request #44840
Opened 2017-04-24 08:38 UTC by spradeepv

Fix for invoking UpdateLoadBalancer() for a service with type=LoadBalancer when pods are added/deleted

**What this PR does / why we need it**:
 This PR compares the endpoints of a old service object with a new service object, inside a watcher in servicecontroller.go. If there is a difference in the count, UpdateLoadBalancer() function of the provider's loadbalancer implementation is invoked for a service of type=LoadBalancer.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44203

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-04-24 08:50 UTC, spradeepv commented
Signed CLA

2017-04-24 12:33 UTC, xiangpengzhao commented
@spradeepv Could you please amend your PR title and commit message to make them meaningful?

2017-04-24 20:42 UTC, MrHohn commented
/release-note-none

@k8s-bot ok to test

cc @freehan @nicksardo

2017-04-24 22:00 UTC, MrHohn reviewed
There is currently no requirement on any other cloud providers to call UpdateLoadBalancer when endpoints are updated. I could imagine in future we may want endpoints changes to trigger some sort of LB updates as well. Though this might be very much diverged in each cloud provider, I'm not sure if UpdateLoadBalancer() is the right entry for this functionality.

For now, this seems to introduce unnecessary function calls to all other cloud providers.

2017-04-24 22:00 UTC, MrHohn commented on pkg/controller/service/servicecontroller.go
> +				newEndpoints := s.getNumberOfEndpoints(oldSvc)
I don't think comparing number of endpoints is enough. What if one endpoint is removed while another is added?

2017-04-25 06:34 UTC, sudhakso requested changes

2017-04-25 06:34 UTC, sudhakso commented on pkg/controller/service/servicecontroller.go
> +				newEndpoints := s.getNumberOfEndpoints(oldSvc)
We may not want to check endpoints when the service is being created first time. Services that gets updated less frequently should see no additional overhead.

2017-04-25 06:34 UTC, sudhakso commented on pkg/controller/service/servicecontroller.go
>  				curSvc, ok2 := cur.(*v1.Service)
Can these checks be includes as part of 'needsUpdate' function? That way we consolidate the decision making through that interface.

2017-04-25 06:34 UTC, sudhakso commented on pkg/controller/service/servicecontroller.go
> +				} else if wantsLoadBalancer(curSvc) && endpointsChanged {
Can we move the calling part of UpdateLoadBalancer into createLoadBalancerIfNeeded(..) function? That would consolidate code that does action at one place.

2017-04-25 06:34 UTC, sudhakso commented on pkg/controller/service/servicecontroller.go
> +							"Updated load balancer with new Endpoints")
Can we handle event description in more generic way to handle 'add' and 'delete' members? This gives me an impression that it is considering addition of new endpoints only.

2017-04-25 06:44 UTC, sudhakso commented on pkg/controller/service/servicecontroller.go
> +				newEndpoints := s.getNumberOfEndpoints(oldSvc)
@MrHohn We need this implementation to handle updates for services of type=loadbalancer. And that's a choice that each Cloud Provider would have to make (that should be made configurable), if it uses 'nodeIPs' versus 'podIPs' as the LB members for such services.

I think it is reasonable to implement a check to decide whether the implementation uses NodeIp versus PodIp, and design the corse of this implementation.

2017-06-16 08:11 UTC, spradeepv commented on pkg/controller/service/servicecontroller.go
>  				curSvc, ok2 := cur.(*v1.Service)
Done

2017-06-16 08:11 UTC, spradeepv commented on pkg/controller/service/servicecontroller.go
> +				newEndpoints := s.getNumberOfEndpoints(oldSvc)
@MrHohn I have addressed your comment

2017-06-16 08:12 UTC, spradeepv commented on pkg/controller/service/servicecontroller.go
> +				} else if wantsLoadBalancer(curSvc) && endpointsChanged {
Done

2017-06-16 08:12 UTC, spradeepv commented on pkg/controller/service/servicecontroller.go
> +							"Updated load balancer with new Endpoints")
Done

2017-06-23 04:54 UTC, spradeepv commented
Closing this pull request for now

2017-06-23 04:54 UTC, closed without merging

2017-10-10 02:13 UTC, andelwu commented
This is helpful.