Added Bind method to Scheduler Extender
kubernetes/kubernetes pull request #44883
Opened 2017-04-24 22:38 UTC by ravigadde

- only one extender can support the bind method
- if an extender supports bind, scheduler delegates the pod binding to the extender

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-04-24 22:40 UTC, ravigadde commented
Implementation for #41447

2017-04-24 22:42 UTC, ravigadde commented
cc @davidopp @timothysc @k82cn 

Preserved multiple extender support while making sure only one extender can implement the Bind method.

2017-04-25 19:18 UTC, timothysc commented
I'm going to let @k82cn help drive this one, b/c you 2 are the primary consumers.

2017-04-26 05:35 UTC, k82cn commented
sure, I'll review it :).

2017-04-27 02:18 UTC, k82cn reviewed
Thanks very much :). Overall, it's OK to me; just some minor comments.

2017-04-27 02:18 UTC, k82cn commented on plugin/pkg/scheduler/api/validation/validation_test.go
> +		t.Errorf("Expected multiple extenders with bind to fail")
prefer to `Expected failure when multiple extenders with bind`.

2017-04-27 02:18 UTC, k82cn commented on test/integration/scheduler/extender_test.go
> +		decoder := json.NewDecoder(req.Body)
seems duplicate with the code here: https://github.com/kubernetes/kubernetes/pull/44883/files#diff-e26062541162f29fe82d7476af847a3eL74

2017-04-27 02:18 UTC, k82cn commented on test/integration/scheduler/extender_test.go
> +	return e.Client.Core().RESTClient().Post().Namespace(genericapirequest.NamespaceValue(ctx)).Resource("bindings").Body(b).Do().Error()
prefer to `return b.Client.CoreV1().Pods(binding.Namespace).Bind(binding)`

2017-04-27 20:48 UTC, ravigadde reviewed
@k82cn thank you for the review. Addressed your comments, PTAL.

2017-04-27 20:48 UTC, ravigadde commented on plugin/pkg/scheduler/core/extender.go
> +		return nil
Yes, its an artifact from earlier implementation. It shouldn't happen, but I will leave the safeguard.

2017-04-27 20:48 UTC, ravigadde commented on plugin/pkg/scheduler/factory/factory.go
> +	var binder scheduler.Binder
There is another call to CreateFromKeys from CreateFromProvider

2017-04-27 20:48 UTC, ravigadde commented on test/integration/scheduler/extender_test.go
> +		decoder := json.NewDecoder(req.Body)
Merge issue, fixed it

2017-04-28 01:51 UTC, k82cn commented on plugin/pkg/scheduler/factory/factory.go
> +	var binder scheduler.Binder
ok, thanks :).

2017-04-28 01:51 UTC, k82cn commented
/lgtm

2017-04-28 01:52 UTC, k82cn commented
/release-note-none

2017-04-28 01:52 UTC, k82cn commented
hmm, I think it's better to add a release note for this PR.

2017-04-28 06:40 UTC, ravigadde commented
@k8s-bot bazel test this

2017-04-28 06:43 UTC, ravigadde commented
@k82cn Rebased and squashed, could you please kick off tests?

2017-04-28 06:57 UTC, k82cn commented
@k8s-bot ok to test

2017-04-28 14:09 UTC, timothysc commented
need to update ./hack/update-bazel.sh

2017-04-28 14:40 UTC, ravigadde commented
Thanks @timothysc could you please kick off the test again?

2017-04-28 21:49 UTC, ravigadde commented
@k82cn lost lgtm label, could you add it back? Tests pass now.

2017-04-28 22:31 UTC, k82cn commented
/lgtm

2017-04-28 22:54 UTC, ravigadde commented
@davidopp PTAL and approve the PR

2017-05-03 18:17 UTC, ravigadde commented
@davidopp ping :)

2017-05-05 07:37 UTC, davidopp commented
@bsalamat Can you review this? If you have questions about how scheduler extender works, ask me or @ravigadde

2017-05-10 09:06 UTC, gyliu513 reviewed
Do you have plan to add the `unbind` for delete operations?

BTW: I found that there is no user guide for this and I have go through the original [github issue](https://github.com/kubernetes/kubernetes/issues/11470) and [design document](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduler_extender.md) here to get some detail, it would be great to have some user guide for this.

2017-05-10 09:06 UTC, gyliu513 commented on test/integration/scheduler/extender_test.go
> +	failPodName = "extender-fail-pod"
This does not seem to be used?

2017-05-11 01:34 UTC, bsalamat requested changes
Thanks, Ravi!

2017-05-11 01:34 UTC, bsalamat commented on plugin/pkg/scheduler/core/extender.go
> +	if h.bindVerb == "" {
Here you could call `IsBinder` if you added the method.

2017-05-11 01:34 UTC, bsalamat commented on plugin/pkg/scheduler/factory/factory.go
> +func (f *ConfigFactory) CreateFromKeys(predicateKeys, priorityKeys sets.String, extenders []algorithm.SchedulerExtender, extBinder scheduler.Binder) (*scheduler.Config, error) {
If you added `IsBinder` to the SchedulerExtender interface, you wouldn't need to pass `extBinder` to this method. You could go over the array of extenders and  create a new binder (`binder{f.client}`) only when none of the extenders is a binder.

2017-05-11 01:34 UTC, bsalamat commented on plugin/pkg/scheduler/api/v1/types.go
> +	PodUID types.UID
Do we actually need all the three pieces of information about pod? Isn't PodUID enough to uniquely identify the pod?

2017-05-23 01:21 UTC, k82cn commented
ping @ravigadde :).

2017-05-23 04:39 UTC, ravigadde commented
@k82cn plan to get to it this week. Been busy, new addition to the family :)

2017-05-23 05:07 UTC, k82cn commented
@ravigadde , sure; congrats :).

2017-05-24 21:16 UTC, ravigadde commented on plugin/pkg/scheduler/api/v1/types.go
> +	PodUID types.UID
In order to post the binding to apiserver, the Binding object in pkg/api/types.go needs to be filled with pod name, namespace also.

2017-05-24 21:24 UTC, ravigadde commented on plugin/pkg/scheduler/factory/factory.go
> +func (f *ConfigFactory) CreateFromKeys(predicateKeys, priorityKeys sets.String, extenders []algorithm.SchedulerExtender, extBinder scheduler.Binder) (*scheduler.Config, error) {
This is also called from CreateFromProvider, where there is no extender config.

2017-05-24 21:24 UTC, ravigadde commented on plugin/pkg/scheduler/core/extender.go
> +// Bind delegates the action of binding a pod to a node to the extender.
Sure, this is a good idea.

2017-05-24 22:56 UTC, bsalamat commented on plugin/pkg/scheduler/factory/factory.go
> +func (f *ConfigFactory) CreateFromKeys(predicateKeys, priorityKeys sets.String, extenders []algorithm.SchedulerExtender, extBinder scheduler.Binder) (*scheduler.Config, error) {
Sure, but you could still do what I said. In this function, you loop over the array of `extenders` to find if any of them is a binder. When `CreateFromKeys` is called from `CreateFromProvider`, the array will be empty and your code will not find any binder.

2017-05-25 05:39 UTC, ravigadde commented
@bsalamat Thanks for the review. Rebased and updated with your comments.

2017-05-25 20:22 UTC, bsalamat commented
/lgtm

Thanks, @ravigadde, and congratulations on the new addition to the family! :-)

2017-05-25 20:28 UTC, ravigadde commented
Thanks @bsalamat 

@davidopp Can you approve the PR?

2017-05-25 20:29 UTC, ravigadde commented
The federation-e2e failure looks like a setup issue.

@k82cn can you kick off the test again?

2017-05-25 20:32 UTC, bsalamat commented
pull-kubernetes-federation-e2e-gce is broken, but it is not required. So, your PR can be merged without it.

2017-05-30 06:04 UTC, ravigadde commented
ping @davidopp @timothysc to approve the PR

2017-05-30 07:07 UTC, k82cn commented
@k8s-bot test this

2017-05-30 07:14 UTC, ravigadde commented
rebased and squashed

2017-05-31 01:07 UTC, k82cn commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-31 02:11 UTC, k82cn commented on plugin/pkg/scheduler/api/validation/validation.go
> +		if extender.BindVerb != "" {
Can we reuse `IsBinder`?

2017-05-31 02:12 UTC, k82cn commented on plugin/pkg/scheduler/factory/factory.go
> +	var binderToUse scheduler.Binder
Move it into a helper func, e.g. `getBinder`

2017-05-31 04:58 UTC, ravigadde commented on plugin/pkg/scheduler/api/validation/validation.go
> +		if extender.BindVerb != "" {
This is actually the config, not the extender implementation. The config doesn't have an equivalent method.

2017-05-31 05:04 UTC, ravigadde commented
@k82cn Thanks for the review, updated with some changes.

2017-05-31 06:24 UTC, k82cn commented on plugin/pkg/scheduler/scheduler.go
> +			ObjectMeta: metav1.ObjectMeta{Namespace: pod.Namespace, Name: pod.Name, UID: pod.UID},
I think `pod.UID` is not necessary for default binder.

2017-05-31 06:26 UTC, k82cn commented
/approve

Overall, it's OK to me; @bsalamat do you have more comments?

2017-05-31 21:23 UTC, ravigadde commented
/assign @eparis for examples and test

2017-05-31 22:57 UTC, davidopp commented
/lgtm

@bsalamat is out this week so I'll lgtm it

2017-06-01 00:52 UTC, k82cn commented
/assign @eparis

2017-06-01 00:53 UTC, k82cn commented
@eparis , would you help to approve example & test part :).

2017-06-03 16:29 UTC, ravigadde commented
ping @eparis

2017-06-03 18:18 UTC, eparis commented on test/integration/scheduler/extender_test.go
> +	failPodName = "extender-fail-pod"
I don't see `failPodName` in this PR either...

2017-06-04 05:15 UTC, ravigadde commented
Thanks @eparis, removed unused variable

2017-06-04 05:50 UTC, k82cn commented
/lgtm

2017-06-04 14:59 UTC, eparis commented
/approve
But the unit tests are failing
```
W0510 02:21:54.732] # k8s.io/kubernetes/plugin/pkg/scheduler
W0510 02:21:54.732] plugin/pkg/scheduler/scheduler_test.go:184: cannot use configurator (type *FakeConfigurator) as type Configurator in argument to NewFromConfigurator:
W0510 02:21:54.733] 	*FakeConfigurator does not implement Configurator (wrong type for CreateFromKeys method)
W0510 02:21:54.733] 		have CreateFromKeys(sets.String, sets.String, []algorithm.SchedulerExtender) (*Config, error)
W0510 02:21:54.733] 		want CreateFromKeys(sets.String, sets.String, []algorithm.SchedulerExtender, Binder) (*Config, error)
W0510 02:21:54.733] plugin/pkg/scheduler/scheduler_test.go:521: cannot use configurator (type *FakeConfigurator) as type Configurator in argument to NewFromConfigurator:
W0510 02:21:54.733] 	*FakeConfigurator does not implement Configurator (wrong type for CreateFromKeys method)
W0510 02:21:54.733] 		have CreateFromKeys(sets.String, sets.String, []algorithm.SchedulerExtender) (*Config, error)
W0510 02:21:54.733] 		want CreateFromKeys(sets.String, sets.String, []algorithm.SchedulerExtender, Binder) (*Config, error)
W0510 02:21:54.733] plugin/pkg/scheduler/scheduler_test.go:561: cannot use configurator (type *FakeConfigurator) as type Configurator in argument to NewFromConfigurator:
W0510 02:21:54.733] 	*FakeConfigurator does not implement Configurator (wrong type for CreateFromKeys method)
W0510 02:21:54.734] 		have CreateFromKeys(sets.String, sets.String, []algorithm.SchedulerExtender) (*Config, error)
W0510 02:21:54.734] 		want CreateFromKeys(sets.String, sets.String, []algorithm.SchedulerExtender, Binder) (*Config, error)
I0510 02:21:54.926] +++ [0510 02:21:54] Saved JUnit XML test report to /workspace/artifacts/junit_a9308e5199d66c4eb1553a4ec233c5882b1bfb35_20170510-020949.xml
I0510 02:21:54.931] Makefile:164: recipe for target 'test' failed
W0510 02:21:55.031] make: *** [test] Error 1
W0510 02:21:56.082] Traceback (most recent call last):
W0510 02:21:56.083]   File "/var/lib/jenkins/workspace/pull-kubernetes-unit/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 108, in <module>
W0510 02:21:56.083]     main(ARGS.branch, ARGS.script, ARGS.force)
W0510 02:21:56.083]   File "/var/lib/jenkins/workspace/pull-kubernetes-unit/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 92, in main
W0510 02:21:56.083]     'bash', '-c', 'cd kubernetes && %s' % script,
W0510 02:21:56.083]   File "/var/lib/jenkins/workspace/pull-kubernetes-unit/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 52, in check
W0510 02:21:56.083]     subprocess.check_call(cmd)
W0510 02:21:56.083]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0510 02:21:56.084]     raise CalledProcessError(retcode, cmd)
W0510 02:21:56.084] subprocess.CalledProcessError: Command '('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-unit/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-unit/go/src/k8s.io/kubernetes/_artifacts:/workspace/artifacts', '-e', 'KUBE_FORCE_VERIFY_CHECKS=n', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'REPO_DIR=/var/lib/jenkins/workspace/pull-kubernetes-unit/go/src/k8s.io/kubernetes', 'gcr.io/k8s-testimages/kubekins-test:1.7-v20170418-f54c7fbd', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/test-dockerized.sh')' returned non-zero exit status 2
```

2017-06-04 16:54 UTC, ravigadde commented
Thank you @eparis 

This seems to be the only failure (unrelated to this PR):
I0604 00:24:50.571] FAIL	k8s.io/kubernetes/vendor/k8s.io/kube-apiextensions-server/test/integration	34.614s

2017-06-05 14:18 UTC, k82cn commented
/retest

2017-06-05 21:36 UTC, ravigadde commented
@k82cn Can you trigger a retest of e2e-kops-aws test?

2017-06-05 22:40 UTC, k82cn commented
/retest

2017-06-05 23:43 UTC, ravigadde commented
@k82cn All tests passed finally, can you please add back the lgtm label?

2017-06-05 23:53 UTC, bsalamat commented
/lgtm

2017-06-06 01:43 UTC, merged

2017-06-06 01:54 UTC, k82cn commented
aha, merged!

2017-06-06 04:36 UTC, ravigadde commented
Thanks @k82cn for your help