daemoncontroller.go: avoid panic
kubernetes/kubernetes pull request #44946
Opened 2017-04-26 07:51 UTC by zhangxiaoyu-zidif

add Comma-ok to avoid panic.

2017-04-26 08:17 UTC, lukaszo commented
@k8s-bot test this

2017-04-26 08:20 UTC, lukaszo commented
@zhangxiaoyu-zidif did you hit a panic or is this just a bug prevention?

2017-04-26 08:22 UTC, lukaszo commented
@k8s-bot ok to test

2017-04-26 08:26 UTC, zhangxiaoyu-zidif commented
@lukaszo I just want to prevent bug now :).  
I am interested in daemonset deployment and plan to apply it to work. I need to review all relative codes to make sure it could works well without some bugs. =)

2017-04-27 02:56 UTC, zhangxiaoyu-zidif commented
@lukaszo @janetkuo 
could you approve this PR?

2017-04-27 06:09 UTC, k82cn commented on pkg/controller/daemon/daemoncontroller.go
> +		return
please also log error message if it's failed. ignore is worse than panic, it's hard to admin/dev to investigate issue if any.

2017-04-27 06:33 UTC, zhangxiaoyu-zidif commented on pkg/controller/daemon/daemoncontroller.go
> +		return
yes, you are right. I will add them soon.

2017-04-27 08:14 UTC, k82cn commented on pkg/controller/daemon/daemoncontroller.go
> +		utilruntime.HandleError(fmt.Errorf("cur is not a pod %#v", cur))
The `HandleError` will also panic :).

2017-04-27 08:15 UTC, k82cn commented
> I am interested in daemonset deployment and plan to apply it to work. I need to review all relative codes to make sure it could works well without some bugs. =)

Welcome to k8s :). I think you can also find some "help-wanted" issues which is also a good start for newbee :).

2017-04-27 10:24 UTC, zhangxiaoyu-zidif commented
@k82cn Thanks for your reminding and advisement. I will start to deal with issues binding "help-wanted" label.  :)

2017-04-27 10:35 UTC, zhangxiaoyu-zidif commented
@k8s-bot gce etcd3 e2e test this

2017-04-27 10:39 UTC, zhangxiaoyu-zidif commented
/release-note-none

2017-05-02 21:29 UTC, janetkuo commented
@zhangxiaoyu-zidif thanks a lot for the fix! Such check is generally good but isn't necessary here, because DaemonSet controller uses pod informer which makes sure that the passed in objects are `v1.Pod` already. 

Controller manager calls [`startDaemonSetController`](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.2/cmd/kube-controller-manager/app/extensions.go#L30-L41) and sets informers (including pod informer). The pod informer is created by calling [`NewSharedIndexInformer`](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.2/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L76-L90) and sets `objectType` to [`v1.Pod`](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.2/staging/src/k8s.io/client-go/informers/core/v1/pod.go#L54). The only exception is `DeleteFunc` which sometimes gets an `cache.DeletedFinalStateUnknown` object.

2017-05-02 21:30 UTC, janetkuo requested changes
@zhangxiaoyu-zidif thanks a lot for the fix! Such check is generally good but isn't necessary here, because DaemonSet controller uses pod informer which makes sure that the passed in objects are `v1.Pod` already: 

Controller manager calls [`startDaemonSetController`](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.2/cmd/kube-controller-manager/app/extensions.go#L30-L41) and sets informers (including pod informer). The pod informer is created by calling [`NewSharedIndexInformer`](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.2/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L76-L90) and sets `objectType` to [`v1.Pod`](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.2/staging/src/k8s.io/client-go/informers/core/v1/pod.go#L54). The only exception is `DeleteFunc` which sometimes gets a `cache.DeletedFinalStateUnknown` object.

2017-05-03 00:41 UTC, zhangxiaoyu-zidif commented
@janetkuo Thank you for you explaining. I close it. :)

2017-05-03 00:41 UTC, closed without merging