Refactor volume operation log and error messages
kubernetes/kubernetes pull request #44969
Opened 2017-04-26 20:11 UTC by ianchakeres

What this PR does / why we need it:
Adds wrappers for volume-specific error and log messages. Each message has a simple version that can be displayed to the user and a detailed version that can be used in logs. The messages that are used for events was also cleaned up. @msau42 

Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #40905

Special notes for your reviewer:
pkg/kubelet/volumemanager/reconciler/reconciler.go can be refactored. I can do that refactoring after this one.

Release note:

NONE

2017-04-26 20:57 UTC, ianchakeres commented
Please recheck CLA status.

2017-04-26 22:39 UTC, ianchakeres commented
Please recheck CLA status.

2017-04-26 23:00 UTC, ianchakeres commented
Please recheck CLA status.

2017-04-26 23:14 UTC, msau42 commented
@k8s-bot ok to test

2017-04-27 20:14 UTC, msau42 commented on pkg/volume/util/operationexecutor/operation_executor.go
> +	volumeVolumeSpecName := "nil"
I would probably just call it volumeSpecName.

This nil check should be added for the other interface implementations too.

2017-04-27 20:21 UTC, msau42 commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		if err != nil {
This looks out of place compared to the original code

2017-04-27 21:23 UTC, ianchakeres commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		if err != nil {
@msau42 It looks like the error message printing got lost in #34242 commit a1c7b8ff841aa9539fa7df04bf5ffc02dbc4342c

2017-04-27 22:36 UTC, msau42 commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		if err != nil {
@tsmetana did you intentionally not want to check the error here and have it proceed further?

2017-04-28 00:45 UTC, ianchakeres commented on pkg/volume/util/operationexecutor/operation_executor.go
> +	volumeVolumeSpecName := "nil"
@msau42 - fixed throughout.

2017-04-28 06:35 UTC, tsmetana commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		if err != nil {
No, this is an apparent mistake in my patch. The error should not have been ignored.

2017-04-29 00:13 UTC, msau42 commented
/lgtm

Asking @saad-ali to take a final look.

2017-05-02 18:12 UTC, saad-ali requested changes
Some minor comments, otherwise LGTM

2017-05-03 01:33 UTC, ianchakeres commented on pkg/volume/util/operationexecutor/operation_generator.go
>  		}
@saad-ali & @tsmetana - I went ahead and added an error for this particular situation.

2017-05-03 06:07 UTC, tsmetana commented on pkg/volume/util/operationexecutor/operation_generator.go
>  		}
Sorry for the late response -- I missed the notification. GenereateDetachVolumeFunc is being called from OperationExecutor's DetachVolume which is being called by reconciler and the error is being passed up... So any error in this function should be logged by the reconciler. However it's safer not to rely on the callers to log the error (OperationExecutor doesn't do that too...) and rather print it several times than miss it altogether. So I think @ianchakeres' solution is correct.

2017-05-03 06:52 UTC, krmayankk commented on pkg/volume/util/operationexecutor/operation_executor.go
> +	return detailedMsg
nit: combine the above two lines

2017-05-03 16:37 UTC, msau42 commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		detailedErr := volumeToAttach.GenerateErrorDetailed("AttachVolume.FindAttachablePluginBySpec failed", err)
Nit: For all these places where the error is just being immediately returned, the lines could be combined.

2017-05-03 16:39 UTC, msau42 commented
Thanks for handling this!  I think it looks almost ready to go.  Please squash all the commits once you've made all the changes.

2017-05-04 17:52 UTC, msau42 commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		glog.Infof(detailedMsg)
A few places like this can be combined too.

2017-05-05 17:41 UTC, saad-ali approved these changes

2017-05-05 17:42 UTC, saad-ali commented
/lgtm
/approve

2017-05-05 21:08 UTC, merged