Skip inspecting pod network if unknown namespace
kubernetes/kubernetes pull request #44991
Opened 2017-04-27 03:04 UTC by aaronlevy

**What this PR does / why we need it**:

If we fail to determine the network namespace of a container we still try to inspect the state - even though there is no way for it to succeed. This leads to errors like:

> NetworkPlugin cni failed on the status hook for pod "X": Unexpected command output nsenter: cannot open : No such file or directory

Instead, if we cannot determine the network namespace, we should just exit with a (hopefully) more clear error message.

I left the wording as assuming a terminated pod, based on:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/helpers.go#L208-L211

ref: 
https://github.com/kubernetes-incubator/bootkube/issues/475
https://github.com/coreos/coreos-kubernetes/issues/856

2017-04-27 04:15 UTC, xiangpengzhao requested changes

2017-04-27 04:15 UTC, xiangpengzhao commented on pkg/kubelet/network/cni/cni.go
> +		return nil, fmt.Errorf("Cannot find network namespace for the terminated container %q", id)
Finally we will get two same log info with different log levels, right? So I think we'd better modify the error info here.

2017-04-27 16:36 UTC, aaronlevy commented on pkg/kubelet/network/cni/cni.go
> +		return nil, fmt.Errorf("Cannot find network namespace for the terminated container %q", id)
Yes, if you had `--v=4` you would see this message twice (once as info and ultimately once as a warning).

Maybe changing this to something like `Cannot find the network namespace, skipping pod network status` ?

2017-04-27 21:22 UTC, xiangpengzhao commented
SGTM:)

2017-04-28 18:14 UTC, aaronlevy commented
Updated the wording of the error messages.

2017-04-30 05:07 UTC, bowei commented
/assign @dnardo PTAL

2017-05-01 18:06 UTC, dcbw commented
See also https://github.com/kubernetes/kubernetes/pull/44067 which is related but at a higher level.

There are two issues; this PR fixes one (don't inspect if we know we can't) while 44067 tries to fix the higher level issue, which is that kubelet shouldn't print an error if it knows that the pod doesn't actually exist (due to the PLEG race).

In any case, /lgtm.

2017-05-01 18:08 UTC, dnardo commented
/lgtm

2017-05-01 18:13 UTC, bowei commented
/LGTM

2017-05-01 18:48 UTC, aaronlevy commented
Probably doesn't need a release note.

Then also, after this merges I'd like to propose cherry-picking this into the v1.6 release branch

2017-05-03 16:40 UTC, aaronlevy commented
Test failure seems to be unrelated. ping @bowei

2017-05-05 17:47 UTC, bowei commented
@k8s-bot verify test this

2017-05-08 23:40 UTC, aaronlevy commented
Bump

2017-05-09 18:27 UTC, aaronlevy commented
@bowei @dnardo Sorry to keep bugging you guys - hoping to try and get this cherry-picked back into a v1.6 release -- it's tripping people up fairly consistently.

2017-05-09 19:30 UTC, bowei commented
/release-note-none

2017-05-09 19:32 UTC, bowei commented
@freehan need approval

2017-05-09 20:36 UTC, merged

2017-05-10 00:46 UTC, aaronlevy commented
Thanks! @bowei possible to add `cherrypick-candidate` label  (for v1.6.x)?