fix cert dir in kubeadm
kubernetes/kubernetes pull request #45008
Opened 2017-04-27 08:31 UTC by xilabao

1.fixes https://github.com/kubernetes/kubeadm/issues/232
2. use manifests as a constant

2017-05-08 15:43 UTC, spiffxp commented
@k8s-bot ok to test

2017-05-11 01:52 UTC, xilabao commented
@dmmcquay @mikedanese kindly ping

2017-05-11 20:36 UTC, fabriziopandini commented
@xilabao, could you kindly confirm if this PR fixes the behaviour of kubeadm flags currently insensible to KUBE_KUBERNETES_DIR env var, and more specifically:
- CertificatesDir which always defaults to /etc/kubernetes/pk,
- CACertPath  which always defaults to "/etc/kubernetes/pki/ca.crt"

If yes this would be great, because this was one of the planned activities for [Kubeadm phase implementation checklist](https://github.com/kubernetes/kubeadm/issues/267)

2017-05-11 20:39 UTC, mikedanese commented on cmd/kubeadm/app/cmd/phases/kubeconfig.go
> +	cmd.Flags().StringVar(&config.CertDir, "cert-dir", "", "The path to the directory where the certificates are.")
Why default to the current directory?

2017-05-12 02:36 UTC, xilabao commented on cmd/kubeadm/app/cmd/phases/kubeconfig.go
> +	cmd.Flags().StringVar(&config.CertDir, "cert-dir", "", "The path to the directory where the certificates are.")
Restored. PTAL

2017-05-12 02:37 UTC, xilabao commented
@fabriziopandini I think this PR has fixed it.

2017-05-12 16:22 UTC, dmmcquay requested changes
Can you be more descriptive in you PR comments of what your change does?

2017-05-12 16:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/init.go
> +	if len(cfg.CertificatesDir) == 0 {
Shouldn't this happen in apis/kubeadm/v1alpha1/defaults.go?

2017-05-12 16:22 UTC, dmmcquay commented on cmd/kubeadm/app/cmd/join.go
> +	if len(cfg.CACertPath) == 0 {
same

2017-05-15 08:15 UTC, xilabao commented on cmd/kubeadm/app/cmd/init.go
> +	if len(cfg.CertificatesDir) == 0 {
Done. PTAL

2017-05-15 08:15 UTC, xilabao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-19 07:36 UTC, xilabao commented
@mikedanese @dmmcquay kindly ping

2017-05-30 07:31 UTC, luxas requested changes
One important thing to realize is that KubernetesDir and CertificatesDir should be able to be in two different roots, they should be able to be decoupled.
i.e. KubernetesDir could be in /etc/kubernetes (the default) but CertificatesDir /var/lib/kube-certificates

Please revert the changes touching /etc/kubernetes/pki.
I'm open to making "manifests" a constant though

2017-05-30 07:31 UTC, luxas commented on cmd/kubeadm/app/apis/kubeadm/v1alpha1/defaults.go
> +	"path"
use filepath instead

2017-05-30 07:31 UTC, luxas commented on cmd/kubeadm/app/apis/kubeadm/v1alpha1/defaults.go
> +		obj.CertificatesDir = path.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, kubeadmconstants.CertificatesDirName)
We strive to phase out kubeadmapi.GlobalEnvParams.KubernetesDir and try to use it as little as possible, please revert this

2017-05-30 07:31 UTC, luxas commented on cmd/kubeadm/app/apis/kubeadm/v1alpha1/defaults.go
> +		obj.CACertPath = path.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, kubeadmconstants.CertificatesDirName, kubeadmconstants.CACertName)
dito

2017-05-30 07:31 UTC, luxas commented on cmd/kubeadm/app/cmd/phases/kubeconfig.go
> +	certificatesDir := filepath.Join(kubeadmapi.GlobalEnvParams.KubernetesDir, kubeadmconstants.CertificatesDirName)
One important thing to realize is that KubernetesDir and CertificatesDir should be able to be in two different roots, they should be able to be decoupled.
i.e. KubernetesDir could be in /etc/kubernetes (the default) but CertificatesDir /var/lib/kube-certificates

2017-05-30 07:31 UTC, luxas commented on cmd/kubeadm/app/constants/constants.go
> +	CertificatesDirName = "pki"
See comment above, these are not coupled to each other.

2017-05-30 07:31 UTC, luxas commented
also needs a rebase

2017-05-31 06:49 UTC, xilabao commented
@luxas @dmmcquay PTAL

2017-05-31 19:18 UTC, luxas reviewed
LGTM but one nit

2017-05-31 19:18 UTC, luxas commented on cmd/kubeadm/app/constants/constants.go
> +	ManifestsDirName = "manifests"
nit: I think I'd prefer `ManifestsSubDirName`, sorry for not catching that the first pass

2017-06-01 01:53 UTC, xilabao commented on cmd/kubeadm/app/constants/constants.go
> +	ManifestsDirName = "manifests"
Done. PTAL

2017-06-01 05:22 UTC, luxas approved these changes
LGTM

2017-06-01 05:22 UTC, luxas commented
/lgtm

@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-01 16:44 UTC, luxas commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-03 10:48 UTC, merged