Remove service on termination when exec 'kubectl run' command with flags "--rm" and "--expose"
kubernetes/kubernetes pull request #45012
Opened 2017-04-27 08:55 UTC by xiangpengzhao

**What this PR does / why we need it**:
As the title says and issue #40504 mentioned.
cc @tanapoln

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #40504 

**Special notes for your reviewer**:
Related to: #44915

**Release note**:

```release-note
NONE
```

2017-05-04 13:58 UTC, soltysh requested changes

2017-05-04 13:58 UTC, soltysh commented on pkg/kubectl/cmd/run.go
> +var runObjectMap = map[string]*RunObject{}
Do not use global vars, if you need to pass this between methods either do it directly, or create a struct methods and update the internal state of it, similarly to how it's done in other commands.

2017-05-04 14:02 UTC, xiangpengzhao commented on pkg/kubectl/cmd/run.go
> +var runObjectMap = map[string]*RunObject{}
Thanks @soltysh ! I also didn't think global vars is a good solution. Will address.

2017-05-06 01:36 UTC, xiangpengzhao commented
@soltysh inline comments addressed. PTAL. Thanks!

2017-05-08 15:44 UTC, spiffxp commented
@k8s-bot ok to test

2017-05-10 06:31 UTC, xiangpengzhao commented
@k8s-bot bazel test this

2017-05-11 11:57 UTC, soltysh approved these changes

2017-05-11 11:57 UTC, soltysh commented
Thanks!
/lgtm

2017-05-16 00:55 UTC, xiangpengzhao commented
ping @adohe for approve :)

2017-05-20 03:09 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot kops aws e2e test this

2017-05-20 05:52 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-31 03:40 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-01 03:09 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this

2017-06-23 03:37 UTC, xiangpengzhao commented
rebased. @soltysh PTAL
and
ping @adohe for approval
Thanks!

2017-07-06 08:35 UTC, xiangpengzhao commented
ping @soltysh and @adohe for lgtm and approval. Thanks!

2017-07-19 06:56 UTC, xiangpengzhao commented
Since didn't receive any response from @adohe 
/unassign @adohe 
and
/assign @deads2k 
for approval

Thanks!

2017-07-19 11:58 UTC, deads2k commented
/lgtm (based on @soltysh )
/approve

2017-07-19 12:31 UTC, xiangpengzhao commented
Thanks @deads2k for approval!
Seems like bot only recognizes a `/lgtm` without any strings following it, so please give another `/lgtm` :)

2017-07-19 12:35 UTC, xiangpengzhao commented
@deads2k Wow, thanks for so quick response!

2017-07-19 14:59 UTC, merged