fix AWS tagging to add missing tags only
kubernetes/kubernetes pull request #45168
Opened 2017-05-01 15:34 UTC by redbaron

It seems that intention of original code was to build map of missing
tags and call AWS API to add just them, but due to typo full
set of tags was always (re)added

```release-note
NONE
```

2017-05-01 19:22 UTC, justinsb commented
@k8s-bot ok to test

Error introduced (by me) in 0b5ae5391ef9eeba337f1dfa62b6f3125e28c86c

/assign

2017-05-01 19:27 UTC, justinsb requested changes
Thanks for the fix!  But I don't think we can drop buildTags from createTags, when it is not called from readRepairClusterTags

2017-05-01 19:27 UTC, justinsb commented on pkg/cloudprovider/providers/aws/tags.go
> +	if err := c.createTags(client, resourceID, lifecycle, addTags); err != nil {
Nice spot

2017-05-01 19:27 UTC, justinsb commented on pkg/cloudprovider/providers/aws/tags.go
> -	tags := t.buildTags(lifecycle, additionalTags)
createTags is called in two (?) places in aws.go, and I think we do need buildTags in those cases.

2017-05-02 05:35 UTC, redbaron commented
@justinsb , you are right. I restored call to `buildTags` in `createTags` so other users are not affected. It kinda defeated the purpose of microoptimization in `readRepairClustertags`  as all the tags will be created,so I add len(addTask) check to not call `createTags` if there is nothing to do

2017-05-02 05:39 UTC, redbaron commented
BTW, if `additionalTags` is meant to be coming lets say from user at some point, then logic in `readRepairClusterTags` is broken as it wont let additional tags to change values. 

It is not a bug currently as `readRepairClusterTags` is called only once and that call is with `additionalTags=nil`

2017-05-30 14:45 UTC, justinsb commented
/lgtm

2017-05-31 08:21 UTC, wojtek-t commented
@k8s-bot pull-kubernetes-unit test this

2017-06-01 05:10 UTC, justinsb commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this

2017-06-01 10:02 UTC, jsafrane commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this

2017-06-01 12:43 UTC, merged