Fetch VM UUID from - /sys/class/dmi/id/product_serial
kubernetes/kubernetes pull request #45311
Opened 2017-05-03 22:50 UTC by divyenpatel

**What this PR does / why we need it**:
Current code fetch VM uuid using uuid reported at `'/sys/devices/virtual/dmi/id/product_uuid'.` This doesn't work with all the distros like Ubuntu 16.04 and Fedora. 

updating code to fetch VM uuid from `/sys/class/dmi/id/product_serial`

**Which issue this PR fixes**
fixes #

**Special notes for your reviewer**:
Verified UUID  is matching with VM UUID on ubuntu 16.04, Cent OS 7.3 , and Photon OS

@BaluDontu @tusharnt

**Release note**:

```release-note
NONE
```

2017-05-04 02:34 UTC, xiangpengzhao requested changes

2017-05-04 02:34 UTC, xiangpengzhao commented on pkg/cloudprovider/providers/vsphere/vsphere.go
> +		return "", fmt.Errorf("cannot find this VM's UUID")
How about recording the `uuidstr` in error info?

2017-05-04 02:34 UTC, xiangpengzhao commented on pkg/cloudprovider/providers/vsphere/vsphere.go
> +	uuidstr = fmt.Sprintf("%s-%s-%s-%s", uuidstr[0:8], uuidstr[8:12], uuidstr[12:21], uuidstr[21:])
Validate the length of `uuidstr` in case it's shorter than expected by accident.

2017-05-04 10:01 UTC, dims commented
@k8s-bot ok to test

2017-05-04 18:16 UTC, divyenpatel commented on pkg/cloudprovider/providers/vsphere/vsphere.go
> +		return "", fmt.Errorf("cannot find this VM's UUID")
added uuid in the error.
`return "", fmt.Errorf("Failed to match Prefix, UUID read from the file is %v", uuidFromFile)`

2017-05-04 18:16 UTC, divyenpatel commented on pkg/cloudprovider/providers/vsphere/vsphere.go
> +	uuidstr = fmt.Sprintf("%s-%s-%s-%s", uuidstr[0:8], uuidstr[8:12], uuidstr[12:21], uuidstr[21:])
verified length
```
if len(uuid) != 32 {
		return "", fmt.Errorf("Length check failed, UUID read from the file is %v", uuidFromFile)
	}
```

2017-05-05 22:25 UTC, divyenpatel commented
@k8s-bot gce etcd3 e2e test this

2017-05-07 18:14 UTC, divyenpatel commented
@k8s-bot gce etcd3 e2e test this

2017-05-08 17:20 UTC, divyenpatel commented
@dims all tests passed. Can you help merging this change to master?

2017-05-08 18:01 UTC, dims commented
/assign @luomiao

2017-05-08 18:01 UTC, dims commented
/approve
/lgtm

2017-05-08 18:09 UTC, luomiao commented
/approve

2017-05-08 22:46 UTC, merged