allow setting of dirMode and fileMode when mounting azure file volume in pod
kubernetes/kubernetes pull request #45337
Opened 2017-05-04 08:52 UTC by andyzhangx

**Which issue this PR fixes**:
Fixes [#37005: azure_file volumes should allow setting of dir_mode and file_mode](https://github.com/kubernetes/kubernetes/issues/37005)

**What this PR does / why we need it**:
This PR is to allow setting of dirMode and fileMode when mounting azure file volume in pod. 

**Special notes for your reviewer**:
This PR will add two more fields(dirMode, fileMode) in azure_file/azure.yaml, as json file only supports decimal, 511(0777 oct) is the default value.
- *dirMode*: Directory permission code that gives rwx permissions to all users. Must be a value between 0 and 511(0777). Defaults to 511(0777).
- *fileMode*: File permission code that gives rwx permissions to all users. Must be a value between 0 and 511(0777). Defaults to 511(0777).

```
  name: myvolume
  azureFile:
    secretName: supersecret
    shareName: myshare
    readOnly: false
    dirMode: 511
    fileMode: 511
```
**Release note**:

2017-05-08 15:06 UTC, spiffxp commented
@k8s-bot ok to test

2017-05-08 21:34 UTC, timstclair requested changes
Please review https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md, it lists all the changes you need to make.

@kubernetes/sig-storage-api-reviews @kubernetes/api-approvers

2017-05-08 21:34 UTC, timstclair commented on staging/src/k8s.io/client-go/pkg/api/types.go
> +	DirMode int32
Type should be `*int32`, same below.

2017-05-08 21:34 UTC, timstclair commented on staging/src/k8s.io/client-go/pkg/api/types.go
> +	// Directory permission code that gives rwx permissions to all users. Must be a value between 0 and 511(0777). Defaults to 511(0777).
Valid range should be enforced in [validation.go](https://github.com/kubernetes/kubernetes/blob/448f8501596ef0c14e2720583385d5172f209105/pkg/api/validation/validation.go#L997) and default should be set in [defaults.go](https://github.com/kubernetes/kubernetes/blob/448f8501596ef0c14e2720583385d5172f209105/pkg/api/v1/defaults.go#L229)

2017-05-12 06:35 UTC, andyzhangx commented on staging/src/k8s.io/client-go/pkg/api/types.go
> +	// Directory permission code that gives rwx permissions to all users. Must be a value between 0 and 511(0777). Defaults to 511(0777).
fixed

2017-05-12 06:35 UTC, andyzhangx commented on staging/src/k8s.io/client-go/pkg/api/types.go
> +	DirMode int32
fixed

2017-05-12 06:36 UTC, andyzhangx commented on staging/src/k8s.io/client-go/pkg/api/types.go
> +	// Directory permission code that gives rwx permissions to all users. Must be a value between 0 and 511(0777). Defaults to 511(0777).
I have done the validation in validation.go and set default in defaults.go

2017-05-12 06:40 UTC, andyzhangx commented
@timstclair Thanks for your instructions, I am a newbie for k8s, just took me a lot of efforts to fix all this, while I think it's only a very tiny fix in the begging. Would you take a review of all this? thanks.

2017-05-12 12:31 UTC, rootfs commented
dirMod and fileMod are among the end user visible options, there are still others users want to change. Making api changes for mount options is not scalable.

[Mount option](https://github.com/kubernetes/features/issues/168) support makes it possible to set these options without changing api object

2017-08-11 08:06 UTC, closed without merging