Add support to delete specified pods when scaling a deployment
kubernetes/kubernetes pull request #45340
Opened 2017-05-04 09:13 UTC by hex108

Ref issue #45339

2017-05-04 09:36 UTC, kargakis commented
Although on a first glance this doesn't look optimal (eg. what if you want to apply a deletionPolicy on 1000 pods?), this PR brings up an interesting use case which is having the ability to customize the deletionPolicy (I am assuming that when we do this, we will have some precanned policies that will be applied on the ReplicaSet/Deployment level). 

@kubernetes/sig-apps-pr-reviews

2017-05-04 11:09 UTC, xiangpengzhao requested changes

2017-05-04 11:09 UTC, xiangpengzhao commented on pkg/controller/controller_utils.go
> +	// 0. Pod with label 'TO_DELETE=true' is smaller
s/TO_DELETE=true/POD_TO_DELETE=true

2017-05-04 14:14 UTC, hex108 commented on pkg/controller/controller_utils.go
> +	_, exists1 := s[i].Labels[POD_DELETE_LABEL]
As described in #45339, set POD_DELETE_LABEL to pods that we want to delete before scaling deployment.

2017-05-04 14:23 UTC, xiangpengzhao commented on pkg/controller/controller_utils.go
> +	_, exists1 := s[i].Labels[POD_DELETE_LABEL]
yeah, just see that. I think it might be hard to make this label be well known to users. Documented? or give a hint in which command?

2017-05-04 14:25 UTC, xiangpengzhao commented on pkg/controller/controller_utils.go
> +	_, exists1 := s[i].Labels[POD_DELETE_LABEL]
and as is mentioned by @kargakis , if the replicas is very large, users will feel painful to label pods manually.

2017-05-04 14:29 UTC, hex108 commented
@kargakis Yes, this PR is just for deleting specified pods. What deletionPolicy are planed to support? Maybe we could implement it by the same way.

2017-05-04 14:34 UTC, kargakis commented
@hex108 it has been mentioned in the doc I linked [here](https://github.com/kubernetes/kubernetes/issues/45339#issuecomment-299134835) - I am not aware if anybody else is working actively on it.

Such a change will need a proposal in the [community repo](https://github.com/kubernetes/community/tree/master/contributors/design-proposals) and an issue in the [features repo](https://github.com/kubernetes/features#feature-tracking-and-backlog). Note that the deadline for 1.7 features ended last Monday if I am not mistaken cc: @idvoretskyi

2017-05-04 14:36 UTC, hex108 commented on pkg/controller/controller_utils.go
> +	_, exists1 := s[i].Labels[POD_DELETE_LABEL]
For most cases, we could get those pods in a list, then it is easy to label them by script, e.g. `cat pod_list | xargs -I{} kubectl label pod {} POD_DELETE_LABEL=TRUE`.

2017-05-04 14:51 UTC, hex108 commented
@kargakis Thanks for it. I still do not have permission to see it, I applied it with account heixia108@gmail.com, could you please help me with this?

2017-05-04 14:57 UTC, kargakis commented
@hex108 I don't have permissions for that kind of stuff - can someone from @kubernetes/sig-contributor-experience-misc help or route this to the appropriate people? Also, which repo are you not able to see?

2017-05-04 14:59 UTC, kargakis commented
> Also, which repo are you not able to see?

Ah, you likely are not able to see the google doc. Sorry about that, somebody should accept your request soon later today.

2017-05-04 15:12 UTC, hex108 commented
Yes, I could not see the google doc. Thanks! I'll wait for it.

2017-05-04 15:23 UTC, xiangpengzhao commented
Seems like some google docs are accessible for specified google sig group. After you join the group, you will be able to view the doc. But I dont know which sig is for this doc...

2017-05-04 15:28 UTC, thockin commented
There's a proto-proposal somewhere to use a Probe or similar to extract
"cost" or similar from pods so that controllers could know which pods in a
set are least expensive to kill.

On Thu, May 4, 2017 at 8:23 AM, Peter Zhao <notifications@github.com> wrote:

> Seems like some google docs are accessible for specified google sig group.
> After you join the group, you will be able to view the doc. But I dont know
> which sig is for this doc...
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/45340#issuecomment-299219004>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVC2_mmP2_cl_HVwQ_yq46oKdZVMsks5r2e1tgaJpZM4NQaG7>
> .
>

2017-05-04 21:23 UTC, davidopp commented
Yes we were planning to address this in a manner like what @thockin described. Issue is #4301

2017-05-17 20:34 UTC, kargakis commented
Closing - we need to have a proposal for fixing this one.

2017-05-17 20:34 UTC, closed without merging