Move TaintBasedEvictions feature from alpha to beta (core part).
kubernetes/kubernetes pull request #45402
Opened 2017-05-05 08:41 UTC by gyliu513

**What this PR does / why we need it**:

This is the first patch of https://github.com/kubernetes/features/issues/166 , it is changing name from `alpha` to `beta`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-05-05 08:44 UTC, gyliu513 commented
/release-note-action-required

2017-05-05 08:45 UTC, gyliu513 commented
/cc @gmarek

2017-05-07 23:13 UTC, gyliu513 commented
Here I have a question for the policy of moving features from alpha to beta: Just rename the annotation from alpha to beta or keep both alpha and beta annotations?

I found an example here by @erictune https://github.com/kubernetes/kubernetes/pull/31026/files , my thinking is that for some internal annotation, we can just rename it; for some annotations used in YAML/JSON template, we may need to copy and keep both alpha and beta, comments?

/cc @gmarek @davidopp

2017-05-09 13:21 UTC, jsafrane commented
I know nothing about taints..
/unassing @jsafrane

2017-05-09 13:22 UTC, jsafrane commented
/unassign @jsafrane

2017-05-10 09:43 UTC, gmarek commented on pkg/api/validation/validation_test.go
> +			Spec: extendPodSpecwithTolerations(validPodSpec(nil), []api.Toleration{{Key: "node.beta.kubernetes.io/notReady", Operator: "Exists", Effect: "NoExecute", TolerationSeconds: &[]int64{-2}[0]}}),
This probably should use `TaintNodeNotReady` constant as a key. Same below.

2017-05-10 09:44 UTC, gmarek commented
One nit. Generally looks good.

2017-05-10 10:23 UTC, gyliu513 commented on pkg/api/validation/validation_test.go
> +			Spec: extendPodSpecwithTolerations(validPodSpec(nil), []api.Toleration{{Key: "node.beta.kubernetes.io/notReady", Operator: "Exists", Effect: "NoExecute", TolerationSeconds: &[]int64{-2}[0]}}),
Done

2017-05-10 11:08 UTC, gmarek commented
/lgtm

@davidopp - do you know who approves such changes?

2017-05-11 19:40 UTC, davidopp commented
I think we need to wait to merge this. Please see my comments in kubernetes/features#166

2017-05-15 13:13 UTC, gmarek commented
@gyliu513 - in the time being I think you can start working on tests. This should actually be the last step of the work.

2017-05-19 08:04 UTC, gmarek commented
@gyliu513 - when we can expect PR with changes in tests and documentation?

2017-05-25 03:29 UTC, gyliu513 commented
@gmarek sorry for late, I saw that this was removed from 1.7 scope, but I will continue work on this to prepare the test and documentation in coming two weeks, hope it is OK.

2017-05-25 08:42 UTC, gmarek commented
Sure - I just need to limit number of things that I look at before the freeze. I'm very happy to review changes afterwards.

2017-05-26 19:49 UTC, dchen1107 commented
Thanks for the pr, and I will review this after 1.7 code freeze since it is out of 1.7 scope

2017-05-27 08:41 UTC, gmarek commented
@dchen1107 - I don't think we need to bug you with this one.

2017-06-28 02:44 UTC, gyliu513 commented
/keep-open

2017-08-04 07:32 UTC, gmarek commented
@gyliu513 - any progress on tests?

2017-08-04 13:13 UTC, gyliu513 commented
Synced with @gmarek offline, will work for this in the middle of Aug, sorry for late response.

2017-08-04 16:20 UTC, xiangpengzhao requested changes

2017-08-04 16:20 UTC, xiangpengzhao commented on pkg/features/kube_features.go
> +	// beta: v1.7
It should be 1.8 now :)

2017-11-03 08:11 UTC, closed without merging

2017-11-04 02:02 UTC, k82cn commented
We're going to close this one (upgrading to beta) until enough user of this feature.

2017-11-22 18:45 UTC, redbaron commented
@k82cn how do you measure usage of this feature? how do you know that enough is enough? Feels like features are promoted very randomly :(