master: override watch cache capacity with origin default
kubernetes/kubernetes pull request #45403
Opened 2017-05-05 09:21 UTC by sttts

2017-05-05 11:52 UTC, deads2k commented on staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
> +	// A zero integer will disable caching.
above you're testing for `> 0`, not `>= 0`, so I think zero currently does `defaultWatchCacheSize`

2017-05-05 11:53 UTC, deads2k commented
one comment, then lgtm

2017-05-05 11:55 UTC, sttts commented on staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
> +	// A zero integer will disable caching.
Good spot. `>=0` (= off) is correct.

2017-05-05 20:42 UTC, sttts commented
@deads2k ptal. I added a possibility to inject the default value via EtcdOptions. IMO this is much cleaner than wrapping the default decorator.

2017-05-07 23:29 UTC, enj requested changes

2017-05-08 12:39 UTC, deads2k commented
/lgtm

2017-05-09 05:14 UTC, sttts commented
@smarterclayton approved?

2017-05-09 13:38 UTC, deads2k commented
api extensions again. approved.  Pull to add owners here: https://github.com/kubernetes/kubernetes/pull/45490

2017-05-09 14:27 UTC, merged