Add lock type flags for controller-manager leadership election
kubernetes/kubernetes pull request #45415
Opened 2017-05-05 12:04 UTC by jamiehannaford

**What this PR does / why we need it**:

Adds `--lock-type` flags to controller manager to allow users to use configmaps for leadership election. Related PRs which accommodates this:

https://github.com/kubernetes/kubernetes/pull/42666
https://github.com/kubernetes/kubernetes/pull/33387

**Which issue this PR fixes**:

https://github.com/kubernetes/kubernetes/issues/44857

**Special notes for your reviewer**:

**Release note**:
```release-note
Controller manager now supports multiple locking types for leadership election
```

2017-05-05 12:05 UTC, jamiehannaford commented
Reviewers: I wasn't sure where I could add integration/e2e to verify behaviour. The closest I came to was `test/kubemark`, but it doesn't allow a list of test cases. Is there anywhere I can add tests for this feature?

Also, this PR introduces the flag for `controller-manager` for now. Once it's approved, I can either add similar logic for the scheduler as an addon commit to this PR or in a separate PR.

2017-05-07 07:10 UTC, luxas commented
@mikedanese @timothysc @jbeda PTAL

2017-05-08 15:51 UTC, spiffxp commented
@k8s-bot ok to test

2017-05-08 19:16 UTC, timothysc requested changes
Minor comment.

2017-05-08 19:16 UTC, timothysc commented on cmd/kube-controller-manager/app/controllermanager.go
> +	switch s.LockType {
Could we wrap this behind a utility function in leaderelection?  This will likely be a repeating pattern.

2017-05-08 19:34 UTC, timothysc commented on cmd/kube-controller-manager/app/controllermanager.go
> +	switch s.LockType {
I think you could probably plumb it through https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/leaderelection.go#L291

2017-05-12 15:00 UTC, smarterclayton commented on pkg/client/leaderelection/leaderelection.go
> +	name := "kube-controller-manager"
This doesn't belong in this package.  This has nothing to do with the generic leader election package.

2017-05-12 15:01 UTC, smarterclayton commented on pkg/client/leaderelection/leaderelection.go
> +				Namespace: metav1.NamespaceSystem,
This doesn't belong in this package.  This has nothing to do with the generic leader election package.

2017-05-12 15:04 UTC, timothysc commented
I'm reworking this into a PR I'll put up today...  This needs several changes.

2017-05-12 19:45 UTC, timothysc commented
Closing this one as there are issues, but I made sure to baseline from this PR to give @jamiehannaford credit.

2017-05-12 19:45 UTC, closed without merging