Replace  Annotaions: volume.alpha.kubernetes.io/storage-class with Spec StorageClassName
kubernetes/kubernetes pull request #45468
Opened 2017-05-08 04:48 UTC by billy2180

Replace  statefulset_utils.go  NewStatefulSetPVC function ,Annotaions: volume.alpha.kubernetes.io/storage-class with Spec StorageClassName,since k8s 1.6.x,StorageClassName attribute has been added to PersistentVolume and PersistentVolumeClaim objects and should be used instead of annotation volume.beta.kubernetes.io/storage-class.

2017-05-08 04:54 UTC, billy2180 commented
/assign @ncdc

2017-05-08 15:00 UTC, spiffxp commented on test/e2e/framework/statefulset_utils.go
> +    classAnything := "anything"
gofmt

2017-05-08 15:00 UTC, spiffxp commented
@k8s-bot ok to test

2017-05-08 16:36 UTC, gnufied commented on test/e2e/framework/statefulset_utils.go
>  		},
But for this `anything` class to work - unlike alpha annotations this `anything` class must exist in the system. Did something create this class? If nobody created that class, it won't work.

2017-05-08 16:38 UTC, gnufied commented
alpha annotations and `StorageClass` attribute of PVC are not equivalent. Alpha annotations work without storageclasses while storageclass requires class to exist.

2017-05-08 23:22 UTC, pwittrock commented
Is this going to break any version skew or upgrade tests?

2017-05-10 12:44 UTC, gnufied commented
@pwittrock it shouldn't break tests if done carefully. But afaik - sig-storage doesn't have priority of removing alpha annotations for 1.7 release. We obviously do want to get rid of it, but we haven't decided on timeline yet.

2017-05-11 03:46 UTC, billy2180 commented
@k8s-bot unit test this

2017-05-11 06:10 UTC, billy2180 commented
@k8s-bot kops aws e2e test this

2017-05-11 06:49 UTC, billy2180 commented
@k8s-bot pull-kubernetes-cross test this

2017-05-11 07:09 UTC, billy2180 commented
@gnufied Can I use the default storage class instead of Alpha annotations, and I think it makes more sense

2017-05-17 08:44 UTC, billy2180 commented
@k8s-bot pull-kubernetes-cross test this

2017-05-18 00:27 UTC, billy2180 commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-22 16:40 UTC, ncdc commented
/unassign
/assign @kow3ns

2017-06-05 16:20 UTC, kow3ns requested changes
If you leave the storage class unspecified and remove the annotation altogether, won't the default storage class be applied anyway?

2017-06-05 16:20 UTC, kow3ns commented on test/e2e/framework/statefulset_utils.go
> +func NewStatefulSet(c clientset.Interface, name, ns, governingSvcName string, replicas int32, statefulPodMounts []v1.VolumeMount, podMounts []v1.VolumeMount, labels map[string]string) *apps.StatefulS
You shouldn't pass the clientset here. Instead, parameterize this function with the storage class, and retrieve the storage class prior to invoking this method.

2017-06-05 16:20 UTC, kow3ns commented on test/e2e/framework/statefulset_utils.go
> +func NewStatefulSetPVC(c clientset.Interface, name string) v1.PersistentVolumeClaim {
Make the storage class a parameter and retrieve the default prior to invoking this method. We shouldn't be calling retrieving the default storage class every time we create a new StatefulSet.

2017-06-08 01:02 UTC, billy2180 commented
/retest

2017-06-08 03:48 UTC, billy2180 commented
You are right,I remove the annotation and leave the storage class unspecified,e2e test ok,the cluster gived it a default pv  @kow3ns

2017-07-10 08:00 UTC, closed without merging