If pod reason is "NodeLost", set the count of ready containers as 0.
kubernetes/kubernetes pull request #45465
Opened 2017-05-08 02:46 UTC by xiangpengzhao

**What this PR does / why we need it**:
If pod reason is "NodeLost", we don't know the real state of containers. Setting the count of ready containers as 0 would be better user friendly.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #45016

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-05-08 14:23 UTC, deads2k commented
I don't know what this should or shouldn't do.

@derekwaynecarr

2017-05-08 15:02 UTC, spiffxp commented
@k8s-bot ok to test

2017-05-10 00:53 UTC, xiangpengzhao commented
/assign @derekwaynecarr

2017-05-12 13:46 UTC, soltysh commented
@kubernetes/sig-scheduling-pr-reviews ptal

2017-05-26 14:30 UTC, derekwaynecarr requested changes
This reason is applied when the node controller is not able to contact the node.  It does not mean that the container is not running on that node at this time.  In fact, the node controller does not know that information.  The behavior in my opinion should not differ from any other pod termination flow.

2017-05-27 02:30 UTC, xiangpengzhao commented
Thanks @derekwaynecarr !

This PR doesn't change any behavior of pod flow. It just changes the result display that users can see by `kubectl get pods`. Yes the container might (or not) be running when the node controller cannot contact the node. But users would be confused when they see a pod with `NodeLost` status but still has running containers.

2017-05-27 02:35 UTC, xiangpengzhao commented
When the node controller recovers to contact the lost node, `pod.Status.Reason` will not be 
 `NodeUnreachablePodReason` any longer. Then `kubectl get pods` can still display the real number of running  containers. This PR doesn't affect this case.

2017-06-03 01:47 UTC, derekwaynecarr commented
@xiangpengzhao -- what happens in this scenario when you describe a pod?

i understand that you feel it may confuse users, but if a node is lost, it doesn't mean the container is not running.  if the node controller fences the pod, eventually the pod will have a deletion timestamp, and you actually need to know if the containers were ever running previously in order to make safe decisions.

2017-06-03 03:23 UTC, xiangpengzhao commented
@derekwaynecarr I don't have env to reproduce now. I remembered that when I first saw the scenario, I can see something like `Reason: NodeLost`. And all other info of the pod is as normal as a running pod on a ready node.

>if the node controller fences the pod, eventually the pod will have a deletion timestamp, and you actually need to know if the containers were ever running previously in order to make safe decisions.

I don't understand this point very well :( Did you mean this PR will affect the behavior of node controller of something else? I don't think this will affect the node controller.

OTOH, unfortunately, no matter what the "READY" field displays for this scenario, `0/1` or `1/1`, this field is not trustable, IMO. It cannot reflect the real status of the containers on the unreachable node. They might be actually running or not.

2017-07-08 20:31 UTC, xiangpengzhao commented
/keep-open

2017-07-09 17:52 UTC, xiang90 commented
@xiangpengzhao 

What we should let users know is when node status is `Lost`, the pod/container status wont be trustable. Changing it from 0 to 1 or from 1 to 0 does not solve this problem.

If you want to justify this change, you have to prove that in x% node lost == pod dies and in y% node lost != pod dies, and x >> y (which may be true!).  I, personally, do not think it worth the effort. It is hard to consume the result anyway...

2017-07-10 00:28 UTC, xiangpengzhao commented
Thanks @xiang90!

>What we should let users know is when node status is Lost, the pod/container status wont be trustable.

Agreed. That's exactly what we should do. Maybe we can show "READY" column as `<unknown>` when "NodeLost". Makes sense?

2017-07-10 01:35 UTC, xiang90 commented
@xiangpengzhao 

That would be inconsistent with other places. I am not sure.

2017-07-22 15:35 UTC, xiangpengzhao commented
xref: #48920

cc @smarterclayton

2017-07-22 16:44 UTC, smarterclayton commented
I don't think this is appropriate - the pod may very will be ready, and it may also be exposed via a load balanced to other pods.  NodeLost doesn't make the pod not ready, so we have to indicate that the pod is available to users potentially.  We should emphasize the node lost condition through.

2017-07-22 16:44 UTC, smarterclayton commented
"May very well"

2017-07-22 17:00 UTC, xiang90 commented
> the pod may very well be ready

node lost == failed to report to API server in time, right? when this happens, how do you know tell if the node is dead from partitioned? 

> NodeLost doesn't make the pod not ready, so we have to indicate that the pod is available to users potentially. We should emphasize the node lost condition through.

it makes we uncertain about the pod status, right? pod can be unavailable to users potentially too. users should be aware of that.

2017-07-22 18:00 UTC, xiangpengzhao commented
Agree with Xiang. 

We may want to mark pod phase as `Unknown` for those pods on the lost node. That means these pods status aren't trustable. Users should decide whether to consider these pods as ready or not by themselves.

2017-07-24 22:11 UTC, smarterclayton commented
> it makes we uncertain about the pod status, right? pod can be unavailable to users potentially too. users should be aware of that.

Users should be aware of it, but automated processes that follow "ready" status will continue treat that node as reachable.  So we have to be careful to not imply that the pod is not ready because as far as most components on the system are concerned, it is.

Unknown may make sense, but describe should convey that as well so that a user can figure out what it means.

2017-07-26 02:25 UTC, xiangpengzhao commented
>Users should be aware of it, but automated processes that follow "ready" status will continue treat that node as reachable. So we have to be careful to not imply that the pod is not ready because as far as most components on the system are concerned, it is.
Unknown may make sense, but describe should convey that as well so that a user can figure out what it means.

Agreed. I will think about how to show it better again. Thanks!

2017-09-25 08:15 UTC, jayunit100 commented
I believe I see both sides here. As a user it really sucks if you have a container running that is unreachable or on a dead node, it's confusing and leads to messed up behaviour in your apps.

But It's true you don't want a split brain if the max number of containers is == 1, and if > 1 can cause corruption somehow.

If we can somehow reconcile these two
Issues it would be great.

2017-09-25 08:27 UTC, xiangpengzhao commented
@jayunit100 reconciliation sounds like a great idea.

2017-10-27 02:52 UTC, xiangpengzhao commented
/test pull-kubernetes-bazel-build
/test pull-kubernetes-bazel-test
/test pull-kubernetes-e2e-gce

2017-10-27 02:54 UTC, xiangpengzhao commented
/hold

2017-10-27 02:57 UTC, xiangpengzhao commented
/retest

2017-12-25 00:38 UTC, zhangxiaoyu-zidif commented
Is there some more discuss here？

2018-05-24 02:22 UTC, closed without merging