Display same fields of Status.Conditions of different resources in 'kubectl describe'
kubernetes/kubernetes pull request #45477
Opened 2017-05-08 09:19 UTC by xiangpengzhao

**What this PR does / why we need it**:
Display same fields of Status.Conditions of different resources in 'kubectl describe'

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44948

**Special notes for your reviewer**:
@kargakis @smarterclayton @soltysh 

**Release note**:

```release-note
NONE
```

2017-05-08 14:06 UTC, rootfs commented
/assign @soltysh
/unassign
@k8s-bot ok to test

2017-05-10 02:56 UTC, xiangpengzhao commented
@k8s-bot bazel test this

2017-05-10 05:31 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-12 13:31 UTC, soltysh requested changes

2017-05-12 13:31 UTC, soltysh commented on pkg/printers/internalversion/describe.go
> +				w.Write(LEVEL_1, "%v \t%v\t%v\n", c.Type, c.Status, c.Reason)
Turn those entire for-loops into helper methods instead of copy&pasting it over and over again.

2017-05-12 13:31 UTC, soltysh commented on pkg/printers/internalversion/describe.go
> -					c.Message)
This is modifying current behavior significantly, and is not expected by the users, please leave as is.

2017-05-15 12:26 UTC, xiangpengzhao commented on pkg/printers/internalversion/describe.go
> +				w.Write(LEVEL_1, "%v \t%v\t%v\n", c.Type, c.Status, c.Reason)
Will address. Thanks @soltysh !

2017-05-15 12:26 UTC, xiangpengzhao commented on pkg/printers/internalversion/describe.go
> -					c.Message)
I wonder if such `LastHeartbeatTime` of node status is really something useful for users. What will users want them for ?Thanks @soltysh !

2017-05-15 13:06 UTC, soltysh commented on pkg/printers/internalversion/describe.go
> -					c.Message)
I'm just saying that users might have some tools build around that and that will fail if we change it.

2017-05-15 13:30 UTC, xiangpengzhao commented on pkg/printers/internalversion/describe.go
> -					c.Message)
Basically agree with your concern. But I don't think user tools should depend on the output of describe. They'd better get what they want from apiserver.

2017-05-15 13:40 UTC, soltysh commented on pkg/printers/internalversion/describe.go
> -					c.Message)
Totally agree, but we need to mindful, at the same time. That's why I'm insisting on leaving it as is.

2017-05-15 14:09 UTC, xiangpengzhao commented on pkg/printers/internalversion/describe.go
> -					c.Message)
Thanks @soltysh ! So do we also need to keep cluster.Status.Conditions as is for the same reason?

2017-05-15 20:24 UTC, soltysh commented on pkg/printers/internalversion/describe.go
> -					c.Message)
Yup, this entire section should be left as is for now.

2017-05-20 03:49 UTC, xiangpengzhao commented
@soltysh inline comments addressed. PTAL. Seems like that the PR title also should be modified?

2017-05-20 05:51 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-24 01:38 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-07-08 20:30 UTC, xiangpengzhao commented
/keep-open

2017-07-25 11:35 UTC, xiangpengzhao commented
close for now due to a type cast issue.
/close

2017-07-25 11:36 UTC, closed without merging