Fix lint errors in juju kubernetes master and e2e charms
kubernetes/kubernetes pull request #45494
Opened 2017-05-08 14:33 UTC by ktsakalozos

**What this PR does / why we need it**: Fixes style error in the Juju charms

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
Code style fixes in Juju charms
```

2017-05-08 14:54 UTC, spiffxp commented
@k8s-bot ok to test

2017-05-08 15:41 UTC, chuckbutler commented
@k8s-bot bazel test this

@k8s-bot verify test this

2017-05-08 15:43 UTC, lazypower requested changes
I had one check inline that I'd like clarification on before approval.

Otherwise this cleanup looks good. Thanks for the effort Kos!

2017-05-08 15:43 UTC, chuckbutler commented on cluster/juju/layers/kubernetes-master/Makefile
> +	@sudo apt-get install -y python-pip python-flake8 python3-flake8 flake8
is python pip required here? we're also calling pip install tox above with the possibility that pip isn't installed.

2017-05-12 17:53 UTC, Cynerva commented
Rather than including tox.ini in our charms, would it make more sense to open a bug against layer-snap? I don't think it's reasonable for layer-snap to break the charms that include it.

2017-05-12 18:00 UTC, thockin commented
/approve

I have no context to weigh in on the questions

2017-05-15 12:37 UTC, chuckbutler commented
/lgtm

2017-05-15 14:49 UTC, merged