Update instructions for client staging copy
kubernetes/kubernetes pull request #45503
Opened 2017-05-08 17:44 UTC by verb

Following the existing instructions results in:

```
% ./staging/copy.sh
Do not run this script directly, but via hack/update-staging-client-go.sh.
```

Also format README.md as markdown.

**What this PR does / why we need it**: Updates docs to match reality

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-05-08 17:58 UTC, cblecker commented
/cc @cblecker

2017-05-08 18:56 UTC, verb commented
@k8s-bot ok to test

2017-05-08 20:44 UTC, caesarxuchao commented on staging/README.md
> +latest code in your local k8s.io/kubernetes, you need to run `godep restore` in
s/`godep restore`/hack/godep-restore.sh

2017-05-08 20:45 UTC, caesarxuchao commented on staging/README.md
> +This staging/src/k8s.io/client-go directory is the staging area of the client
This paragraph needs to be updated as well, there are many staging repos now, not just client-go.

2017-05-08 21:01 UTC, verb commented on staging/README.md
> +latest code in your local k8s.io/kubernetes, you need to run `godep restore` in
Done

2017-05-08 21:03 UTC, verb commented on staging/README.md
> +This staging/src/k8s.io/client-go directory is the staging area of the client
I attempted a generic rewrite of this and the first paragraph based on my (very) naive understanding of how this works. I'm happy to incorporate any specific suggestions from the experts or roll back this second commit as we've reached the limit of my knowledge in this area.

2017-05-12 18:13 UTC, cblecker requested changes

2017-05-12 18:13 UTC, cblecker commented on staging/README.md
> +"vendor/client-go/<package-name>", as if the package were vendored. Packages
`"vendor/k8s.io/<package-name>"`

2017-05-12 19:12 UTC, verb commented on staging/README.md
> +"vendor/client-go/<package-name>", as if the package were vendored. Packages
Done, thanks.

2017-05-12 19:15 UTC, cblecker approved these changes

2017-05-12 19:29 UTC, caesarxuchao commented on staging/README.md
> +The staged content is copied from the main repo, i.e., k8s.io/kubernetes, with
Something like this:

Most code in the staging/ is authoritative, i.e., the only copy of the code. You can directly modify such code. However, the packages in staging/src/k8s.io/client-go/pkg, which are copied from pkg/. If you modify the original copy of the code, you need to run`hack/godep-restore.sh` in k8s root directory, then run `hack/update-staging-client-go.sh`. We are working towards making all code in staging/ authoritative.

2017-05-12 19:30 UTC, caesarxuchao commented
Thanks. Two comments, otherwise lgtm.

2017-05-12 20:21 UTC, verb commented on staging/README.md
> +The staged content is copied from the main repo, i.e., k8s.io/kubernetes, with
That's much more clear, thanks.

2017-05-12 20:21 UTC, verb commented on staging/README.md
> +"vendor/k8s.io/<package-name>", as if the package were vendored. Packages will
Done.

2017-05-12 23:09 UTC, verb commented
@k8s-bot gce etcd3 e2e test this

2017-05-12 23:11 UTC, cblecker commented
/lgtm

/assign @smarterclayton
for approval

2017-05-12 23:30 UTC, cblecker commented
@k8s-bot gce etcd3 e2e test this

2017-05-15 18:01 UTC, caesarxuchao commented
@smarterclayton could you help approve the change? thanks.

2017-05-16 20:12 UTC, smarterclayton commented
/approve

2017-05-16 20:59 UTC, merged