Add Japanese translation for kubectl
kubernetes/kubernetes pull request #45562
Opened 2017-05-09 21:32 UTC by girikuncoro

**What this PR does / why we need it**:
This PR provides first attempt to translate kubectl in Japanese (related to #40645 and #40591). 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
No issues

**Special notes for your reviewer**:
Should be reviewed by member of Japanese k8s community (I stayed in Japan for 4 years, but my language is not as good as native Japanese)

2017-05-09 21:42 UTC, girikuncoro commented
I've just sign up the CLA

2017-05-09 21:59 UTC, soltysh commented
@kubernetes/sig-cli-pr-reviews do we have someone who knows Japanese to verify this?

2017-05-10 04:20 UTC, brendandburns commented
Calling @IanLewis who knows Japanese afaik...

2017-05-10 04:24 UTC, brendandburns commented
@k8s-bot ok to test

2017-05-10 04:26 UTC, brendandburns commented
@girikuncoro Thanks for the contribution!

Spot checks via Google Translate look ok.  We'll wait a couple days to see if another Japanese speaker can do a check, then I'll LGTM.

2017-05-10 04:31 UTC, vfreex commented
Shouldn't the language code of Japanese be ja_JP?

2017-05-10 04:32 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "リソースでのあのテーショーンを更新する"
リソースのアノテーションを更新する

2017-05-10 04:40 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +"リソース　%d　が見つかった"
%d個のリソースが見つかりました

2017-05-10 04:41 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +"リソース　%d　が見つかった"
%d個のリソースが見つかりました

2017-05-10 04:43 UTC, TakanariKo commented on pkg/util/i18n/i18n.go
> +		"jp_JP",
jp_JP

2017-05-10 04:43 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "kubeconfigに現在のコンテキストを設定する"
kubeconfigにカレントコンテキストを設定する

2017-05-10 04:44 UTC, vfreex requested changes

2017-05-10 04:44 UTC, vfreex commented on pkg/util/i18n/i18n.go
> +		"jp_JP",
The [ISO 639 language code of Japanese language](https://www.loc.gov/standards/iso639-2/php/code_list.php) is `ja`, so this should be changed to `ja_JP`.

2017-05-10 04:47 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +"Language: jp\n"
ja

2017-05-10 04:48 UTC, girikuncoro commented
Thanks for the reviews and comments! I'll wait until tomorrow in case more comments come up, and make changes accordingly tomorrow (Pacific Time)

2017-05-10 04:49 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "現在のコンテキストを表示する"
カレントコンテキストを表示する

2017-05-10 04:56 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "kubeconfig設定または指示したkubeconfigファイルを表示する"
マージされたkubeconfigの設定または指定されたkubeconfigファイルを表示する

2017-05-10 05:01 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +"watchは単一リソース及びリソースコレクションでのみサポートされている - "
watchは単一リソース及びリソースコレクションのみサポートしています

2017-05-10 05:01 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +"watchは単一リソース及びリソースコレクションでのみサポートされている - "
watchは単一リソース及びリソースコレクションのみサポートしています

2017-05-10 05:02 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "１つまたは複数のコンテキストを記述する"
1つまたは複数のコンテキストを記述する

2017-05-10 05:33 UTC, superbrothers commented
I reviewed the translation. Nice PR! 👍

2017-05-10 05:39 UTC, superbrothers commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "１つまたは複数のコンテキストを記述する"
I prefer to use Hankaku (half-width) for numbers.

2017-05-10 16:39 UTC, chumaltd commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "ファイル名または標準入力でリソースにコンフィグを適用する"
ファイル名を指定または標準入力経由でリソースにコンフィグを適用する

2017-05-10 16:52 UTC, chumaltd commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "kubeconfigファイルに単一値を設定する"
kubeconfigファイル内の変数を個別に設定する

2017-05-10 16:52 UTC, chumaltd commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "kubeconfigに単一値の設定を削除する"
kubeconfigファイルから変数を個別に削除する

2017-05-10 17:01 UTC, chumaltd commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "kubeconfigファイルに単一値を設定する"
if "an individual value" is some technical term, there may be better translation. but I don't see "単一値" in everyday life.

2017-05-10 17:04 UTC, chumaltd commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "kubeconfigファイルを編集する"
kubeconfigファイルを変更する

2017-05-10 17:08 UTC, chumaltd commented on translations/kubectl/jp_JP/LC_MESSAGES/k8s.po
> +msgstr "kubeconfigファイルを編集する"
I think "変更" is more suitable for atomic change nuance. "編集" has emphasis on authoring aspect like with vi.

2017-05-11 23:11 UTC, girikuncoro commented
@superbrothers @chumaltd @vfreex @TakanariKo I made changes, can you check?

2017-05-11 23:15 UTC, girikuncoro commented
@brendandburns for some reason my jenkins bazel build and verification are failing, any guidance on this?

for bazel build I might need to clean up something (this was passing in my first push)
```
W0511 20:33:28.654] fatal: Unable to create '/root/.cache/git/k8s.io/kubernetes/index.lock': File exists.
```

for jenkins verification I have no idea what went wrong in my changes

2017-05-11 23:40 UTC, superbrothers commented
lgtm 👍

2017-05-12 00:09 UTC, chumaltd commented
lgtm. Thanks for great work!

On 2017年5月12日 8:12:29 JST, Giri Kuncoro <notifications@github.com> wrote:
>@superbrothers @chumaltd @vfreex @TakanariKo I made changes, can you
>check?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kubernetes/kubernetes/pull/45562#issuecomment-300941169

2017-05-13 07:24 UTC, shiywang commented on translations/kubectl/ja_JP/LC_MESSAGES/k8s.po
> +# https://github.com/kubernetes/kubernetes/blob/masterpkg/kubectl/cmd/apply.go#L98
Seems those url all pointing to the wrong line. Does that matters ? also I saw there's a `template.pot` file. Does this file auto-generate content when command changed ?  @brendandburns

2017-05-16 21:39 UTC, brendandburns commented on translations/kubectl/ja_JP/LC_MESSAGES/k8s.po
> +# https://github.com/kubernetes/kubernetes/blob/masterpkg/kubectl/cmd/apply.go#L98
I can update the script.

template.pot does not automatically get updated (yet) but this PR shouldn't affect `template.pot`

2017-05-16 21:39 UTC, brendandburns commented
@k8s-bot bazel test this
@k8s-bot verify test this

2017-05-19 03:22 UTC, brendandburns commented
Ah, @girikuncoro you need to run `./hack/generate-bindata.sh`

Sorry about that...

2017-05-19 07:29 UTC, girikuncoro commented
@brendandburns ready for lgtm now, thanks for the suggestion 😄

2017-05-23 12:27 UTC, warmchang commented
It's look like ready to lgtm & merge, and then I'll commit the Simplified Chinese translation PR.

2017-05-23 14:17 UTC, shiywang commented
@warmchang sorry, I think I already made that https://github.com/kubernetes/kubernetes/pull/45573, you could have a review if you want : )

2017-05-24 00:49 UTC, warmchang commented
@shiywang , glad to see your PR and good translation! Maybe i should submit the Traditional Chinese version. :smile:

2017-05-24 20:21 UTC, brendandburns commented
/lgtm
/approve

THanks again.

2017-05-28 04:34 UTC, brendandburns commented
@girikuncoro Sorry, this now needs a rebase...

Appologies I will shepard this in asap once it's rebased...

2017-06-01 05:54 UTC, warmchang commented
@girikuncoro , 2565 files changed, It look like better to rebase the PR.

2017-06-01 06:08 UTC, shiywang commented
seems you "rebased" too much

2017-06-01 06:25 UTC, girikuncoro commented
@brendandburns sorry my bad, I messed up the PR. I've moved it to the new one at #46756. closing this for now

2017-06-01 06:25 UTC, closed without merging

2017-06-01 06:26 UTC, girikuncoro commented
@shiywang my bad, accidentally pushed some mistake 😓  moved to #46756