check err
kubernetes/kubernetes pull request #45578
Opened 2017-05-10 08:05 UTC by YuPengZTE

Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-05-10 09:14 UTC, gmarek commented on pkg/cloudprovider/providers/gce/gce.go
> +}
This looks wrong.

2017-05-10 09:27 UTC, YuPengZTE commented on pkg/cloudprovider/providers/gce/gce.go
> +}
@gmarek , are you mean it is same with [client, err := newOauthClient(tokenSource)](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L179)?

2017-05-10 09:37 UTC, gmarek commented on pkg/cloudprovider/providers/gce/gce.go
> +}
No - I meanadding additional closing bracket.

2017-05-11 01:40 UTC, zhangxiaoyu-zidif commented on pkg/cloudprovider/providers/gce/gce.go
> +}
Hi, @gmarek , is it right to delete line 189?

2017-05-11 12:07 UTC, gmarek requested changes

2017-05-11 12:07 UTC, gmarek commented on pkg/cloudprovider/providers/gce/gce.go
> +}
No, we need separate alpha client. I guess - I'm not the one who wrote this code. @bowei

2017-05-12 06:46 UTC, YuPengZTE commented
@gmarek , I know the useage, Thanks. Close it.

2017-05-12 06:46 UTC, closed without merging