[WIP] Add Simplified Chinese translation for kubectl
kubernetes/kubernetes pull request #45573
Opened 2017-05-10 06:02 UTC by shiywang

What this PR does / why we need it:
This PR provides first attempt to translate kubectl in Simplified Chinese.

Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #
No issues

Special notes for your reviewer:
Although I'm a native speaker for Mandarin Chinese, but I think translation is a whole different knowledge which I'm not good at it, so this pr absolutely need be polished.
@adohe @mengqiy @resouer @k82cn @caesarxuchao @wanghaoran1988 sorry I think there's so many folks who is good at Chinese I haven't mention, but could you guys take a look first ?
also cc @brendandburns

2017-05-10 06:40 UTC, vfreex requested changes

2017-05-10 06:40 UTC, vfreex commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "通过文件或者标准输入的读取方式apply一个资源"
通过文件名或标准输入流(stdin)对资源进行配置。

2017-05-10 06:40 UTC, vfreex commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "从kubeconfig文件中删除指定的集群"
“删除 kubeconfig 文件中指定的集群”
中英文混排时用空格隔开。

2017-05-10 06:40 UTC, vfreex commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "描述一个或更多上下文"
更多->多个

2017-05-10 06:40 UTC, vfreex commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "从kubeconfig配置文件中显示指定的集群"
显示 kubeconfig 文件中指定的集群

2017-05-10 06:40 UTC, vfreex commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr[0] "watch 仅在单独的一个资源或者一个资源集合上被支持 -资源 %d 被发现"
建议改为主动语态，如
watch 仅支持单独的资源或者资源集合 - 找到了 %d 个资源

2017-05-10 07:45 UTC, vabc3 commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "从kubeconfig配置文件中显示指定的集群"
显示kubeconfig配置文件中定义的集群

2017-05-10 07:48 UTC, shiywang commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "从kubeconfig配置文件中显示指定的集群"
specified cluster -> 指定的集群
clusters defined -> 定义的集群 ?

2017-05-10 07:50 UTC, vabc3 commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "显示合并的集群或者指定的kubeconfig配置文件"
合并的kubeconfig配置？

2017-05-10 13:45 UTC, rootfs commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "取消设置 kubeconfig 文件中的一个单独值"
`单独值` sounds odd, anything better?

2017-05-10 22:38 UTC, pwittrock commented
I was actually joking when I said I could review this  :P 

Looks like this doesn't impact non-chinese aspects of kubectl, so I can approve once @rootfs lgtm's

2017-05-19 08:19 UTC, shiywang commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "取消设置 kubeconfig 文件中的一个单独值"
updated, how about now ?

2017-05-19 08:19 UTC, shiywang commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +# https://github.com/kubernetes/kubernetes/blob/masterpkg/kubectl/cmd/apply.go#L98
updated

2017-05-23 23:22 UTC, mengqiy commented
LGTM
@rootfs Any more comments?

2017-05-23 23:41 UTC, rootfs commented
/lgtm

2017-05-23 23:42 UTC, rootfs commented
great work @shiywang @mengqiy

2017-05-23 23:42 UTC, rootfs commented
/release-note-action-required
Add Simplified Chinese translation for kubectl

2017-05-23 23:44 UTC, mengqiy commented
/release-note

2017-05-23 23:46 UTC, mengqiy commented
@pwittrock ping for approval

2017-05-24 20:25 UTC, brendandburns commented
/approve

2017-05-25 04:03 UTC, brendandburns commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-25 07:43 UTC, shiywang commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-25 08:23 UTC, shiywang commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this

2017-05-25 10:13 UTC, merged

2017-05-26 05:30 UTC, CaoShuFeng commented
I would like invate you to review this change:
https://github.com/kubernetes/kubernetes/pull/46487