Fix #45213: Syncing jobs would return error when podController exception
kubernetes/kubernetes pull request #45664
Opened 2017-05-11 15:05 UTC by tacy

**What this PR does / why we need it**:
Jobcontroller:  Syncing jobs would return error when podController exception
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes #45213 
**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-05-12 10:19 UTC, soltysh requested changes

2017-05-12 10:19 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +					defer wait.Done()
You don't need to do it 2nd time, it's already done 2 lines above.

2017-05-12 10:19 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +					glog.V(2).Infof("Failed to delete %v, job %q/%q deadline exceeded", activePods[ix].Name, job.Namespace, job.Name)
Please leave the `utilruntime.HandleError`, it does glog, but can additionally feed other error handlers with information.

2017-05-12 10:19 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +func (jm *JobController) manageJob(activePods []*v1.Pod, succeeded int32, job *batch.Job) (active int32, err error) {
Drop named return parameters, you're not using it at all.

2017-05-12 10:19 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +					glog.V(2).Infof("Failed to delete %v, decrementing expectations for job %q/%q", activePods[ix].Name, job.Namespace, job.Name)
Same, leave `utilruntime.HandleError`.

2017-05-12 10:19 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +		// all errors have been reported before and they're likely to be the same, so we'll only return the first one we hit.
That is not a good assumption. Not every error will be the same.

2017-05-12 10:32 UTC, soltysh commented
@tacy reading through the PR I'm not quite sure how this will help you with resolving your problem from #45213. You reported you've had problems with creating pods, but you've only fixed pod removal part, was the removal blocking you? I'd expect [this place](https://github.com/kubernetes/kubernetes/blob/7b0dee89f29c4c9e645f3d66c98aeb2250783e0a/pkg/controller/job/jobcontroller.go#L609) to handle creation failure and do not increase the active count until one of the currently running pods finishes. Lemme try that example of yours and see what I'm getting...

2017-05-12 10:32 UTC, soltysh commented
@derekwaynecarr fyi

2017-05-12 11:48 UTC, soltysh commented
Nvmd my last comment, I think I got blind when reading your PR and missed the part wrt to pod creation, sorry 😊

2017-05-12 11:50 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +		// all errors have been reported before and they're likely to be the same, so we'll only return the first one we hit.
I'd drop this comment. Generally what we need is to inform the controller that there was an error and it should re-try this job once more next time.

2017-05-12 11:52 UTC, soltysh commented
@tacy you need to make sure to sign the CLA, as well

2017-05-12 11:52 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> -					defer utilruntime.HandleError(err)
Same, leave `utilruntime.HandleError`.

2017-05-13 15:52 UTC, tacy commented
Thanks for the review @soltysh, comments addressed,  please take a look.

I have signed the CLA.

2017-05-15 07:21 UTC, soltysh approved these changes

2017-05-15 07:23 UTC, soltysh commented
@tacy - awesome, thanks! Can you please squash your changes into a single commit?
@k8s-bot ok to test

2017-05-15 07:27 UTC, soltysh commented
@tacy wrt to CLA can you comment in https://github.com/kubernetes/kubernetes/issues/27796 and ping `@sarahnovotny` and `@foxish`

2017-05-15 07:59 UTC, soltysh commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-15 15:04 UTC, tacy commented
@soltysh  - Squash done

2017-05-15 20:21 UTC, soltysh commented
/lgtm
/approve

@tacy all is left is the CLA.

2017-05-16 03:19 UTC, tacy commented
I have signed, and will call helpdesk<helpdesk@rt.linuxfoundation.org> to find why

thanks @soltysh

2017-05-16 03:52 UTC, soltysh commented
@tacy you're fast, right after your comment the bot added the cla approved label, yay! Thanks once again, it should merge shortly :)

2017-05-16 03:53 UTC, soltysh commented
@tacy mind cherry-picking this one onto 1.6 branch?

2017-05-16 04:08 UTC, merged

2017-05-16 04:33 UTC, tacy commented
Cherry-pink done.

/cc @soltysh