modify the file.go
kubernetes/kubernetes pull request #45714
Opened 2017-05-12 09:08 UTC by jianglingxia

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-05-12 16:08 UTC, dmmcquay requested changes

2017-05-12 16:08 UTC, dmmcquay commented on cmd/kubeadm/app/discovery/file/file.go
> +	fmt.Println("[discovery] Synced cluster-info information from the API Server so we have got the latest information.")
Similar to other PR (https://github.com/kubernetes/kubernetes/pull/45708) I don't think we should add periods here.

2017-05-12 19:05 UTC, cblecker commented
I'm not sure this PR is necessary.

2017-05-15 15:58 UTC, wojtek-t commented on cmd/kubeadm/app/discovery/file/file.go
> +		return nil, fmt.Errorf("Couldn't parse the kubeconfig file in the %s ConfigMap: %v", bootstrapapi.ConfigMapClusterInfo, err)
errors should start with small letter - that's the convention (because they can be appended to other errors)

2017-05-15 16:15 UTC, dmmcquay commented
I do not think this PR is not necessary.

2017-05-15 16:27 UTC, krousey commented
Adding a period to that line would make it inconsistent with the rest of the tool, and it is Go's style to not capitalize error messages. Closing this PR.

2017-05-15 16:27 UTC, closed without merging