support --dry-run in kubectl patch command
kubernetes/kubernetes pull request #45712
Opened 2017-05-12 09:00 UTC by xilabao

2017-05-12 13:13 UTC, eparis commented
@k8s-bot ok to test
/release-note-none

2017-05-17 22:52 UTC, monopole commented on pkg/kubectl/cmd/patch.go
> +		}
originalObj := determineOriginalObj(info)

2017-05-17 23:02 UTC, monopole commented on pkg/kubectl/cmd/patch.go
> +		if !reflect.DeepEqual(obj, targetObj) {
if equal (i.e. no patch) is the call to info.Refresh still needed?

2017-05-18 02:14 UTC, xilabao commented on pkg/kubectl/cmd/patch.go
> +		}
> Did this just blow up before if VersionedObject was nil?

`--local` and `--dry-run` can not use together. I think yes. PTAL

2017-05-18 20:32 UTC, monopole requested changes

2017-05-19 02:21 UTC, xilabao commented on pkg/kubectl/cmd/patch.go
> +	return obj
Done. PTAL @monopole

2017-05-19 18:22 UTC, monopole approved these changes
/lgtm

2017-05-25 12:11 UTC, xilabao commented
@monopole @eparis approve?

2017-05-26 21:03 UTC, fabianofranz commented
Dupe of https://github.com/kubernetes/kubernetes/pull/45920?

2017-06-06 08:00 UTC, xilabao commented
@fabianofranz I think  `--dry-run` is not same with `--local`. maybe it's a dupe of #45920 ?  PTAL

2017-06-07 19:04 UTC, fabianofranz commented
/lgtm
/approve

2017-06-07 19:05 UTC, fabianofranz commented
@xilabao bot will probably ask for the link to an issue.

2017-06-08 09:59 UTC, xilabao commented
@k8s-bot pull-kubernetes-node-e2e test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-09-09 11:59 UTC, dims commented
Do we need this for 1.8? please rebase.

2017-09-10 11:25 UTC, xilabao commented
rebased @eparis @fabianofranz @monopole ptal

2017-09-18 18:54 UTC, dims commented
/test all

2017-09-18 19:23 UTC, fabianofranz commented
/lgtm

2017-09-18 19:24 UTC, fabianofranz commented
/kind enhancement

2017-09-22 01:53 UTC, eparis commented
/retest
just so the bots will leave us alone!!!

2017-09-22 01:53 UTC, eparis commented
@fejta I think the bots are angry...

2017-10-23 23:28 UTC, timoreimann commented
I'd love to see this PR crossing the finishing line.

@xilabao, anything in your power you could do to drive the PR to completion?

2017-10-26 08:46 UTC, xilabao commented
rebased. @fabianofranz @eparis @monopole @dims PTAL

2017-12-21 17:07 UTC, fabianofranz commented
/unassign

2017-12-22 01:39 UTC, timoreimann commented
Still super interested in seeing this one getting pushed through.

@xilabao any chance for another rebase? :-)

2018-01-09 17:42 UTC, timoreimann commented
The PR seems to have gone stale. If nobody objects, then I'll carry it over to a PR of my own.

2018-01-29 00:14 UTC, dims commented
@timoreimann +1 i'll close this one out

/close

2018-01-29 00:14 UTC, closed without merging