Allow kcm and scheduler to lock on ConfigMaps.
kubernetes/kubernetes pull request #45739
Opened 2017-05-12 18:14 UTC by timothysc

**What this PR does / why we need it**:
Plumbs through the ability to lock on ConfigMaps through the kcm and scheduler.  

**Which issue this PR fixes** 
Fixes: #44857
Addresses issues with: #45415

**Special notes for your reviewer**:

**Release note**:

```
Add leader-election-lock-type support to kcm and scheduler to allow for locking on ConfigMaps as well as Endpoints(default) 
```
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews @jamiehannaford @bsalamat

2017-05-12 18:27 UTC, jamiehannaford requested changes
Is it also possible to cherry pick my commit and add in your new fn signature? It's very similar to what I originally submitted :)

2017-05-12 18:27 UTC, jamiehannaford commented on pkg/client/leaderelection/resourcelock/interface.go
> +func Manufacture(lockType string, ns string, name string, client *cs.Clientset, rlc ResourceLockConfig) (Interface, error) {
ns, name string

2017-05-12 18:44 UTC, timothysc commented
> Is it also possible to cherry pick my commit and add in your new fn signature? It's very similar to what I originally submitted 

Yes.

2017-05-12 22:29 UTC, mikedanese commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
Technically, "endpoints" and "configmaps" are Kinds in our API. Types also include a version.

2017-05-12 22:30 UTC, mikedanese commented on pkg/client/leaderelection/resourcelock/interface.go
> +func Manufacture(lockType string, ns string, name string, client *cs.Clientset, rlc ResourceLockConfig) (Interface, error) {
Why not just call this New? What is the significance of Manufacture in this context?

2017-05-12 23:52 UTC, timothysc commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
I'm fine with changing the name. 

- LockKind (sounds weird)
- ResourceLock
- LockType

... I don't really care.

2017-05-12 23:53 UTC, timothysc commented on pkg/client/leaderelection/resourcelock/interface.go
> +func Manufacture(lockType string, ns string, name string, client *cs.Clientset, rlc ResourceLockConfig) (Interface, error) {
New works for me.

2017-05-14 00:45 UTC, smarterclayton commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
I would prefer `LockResource`.  It also needs to be a group and resource, not just one or the other.  You probably don't want to perform discovery, so I'd recommend doing `LockResource` and `LockResourceGroup` or similar.

2017-05-14 00:45 UTC, smarterclayton commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
`endpoints` is a resource (addressable via the API) and is what most external components should use.  Kind (`Endpoints`) is a schema, and multiple resources can have that schema.

2017-05-14 00:45 UTC, smarterclayton commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
We're gradually phasing out use of GroupVersionKind in internal code, but it will take a while.

2017-05-14 00:47 UTC, smarterclayton commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
I was making this switch in openshift the other day and used:

https://github.com/openshift/origin/pull/14094/files#diff-3788994f990386b63387ece5c3b5dc33R1418 for the componentconfig equivalent and https://github.com/openshift/origin/pull/14094/files#diff-9eadaa7b7aac3bc9ea7ed27cb8908d52R86 for the CLI flag equivalent.

2017-05-15 13:28 UTC, timothysc commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
I'll change the name to LockResource. 

Re: grouping, that's done a layer above and passed into the Manufacture/New function, which keeps the library generic enough for general reuse.

2017-05-15 16:30 UTC, timothysc commented
@k8s-bot gce etcd3 e2e test this

2017-05-15 16:56 UTC, timothysc commented
@mikedanese I believe I've addressed the comments, PTAL.

2017-05-15 17:16 UTC, mikedanese commented on pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
> +	out.LockType = in.LockType
LockResource SGTM

2017-05-15 17:18 UTC, mikedanese commented
/lgtm

2017-05-15 21:17 UTC, ravilr commented
@timothysc @deads2k the default `system:..` rbac bootstrap policies for controller-manager and scheduler also needs update to allow create/update/delete on configmap resource here?

2017-05-15 21:49 UTC, timothysc commented
@ravilr - Do we not have RBAC on any of our e2es?

2017-05-15 22:07 UTC, mikedanese commented
Should be on in all e2e tests. You can add the policy here:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L299

2017-05-15 22:08 UTC, timothysc commented
Ahh I see the issue, I'll create a fast-follow on PR there.

2017-05-16 18:16 UTC, timothysc commented
So the other change hits a different space, so I'm going to push this one through and follow up with a RBAC PR.

2017-05-17 01:10 UTC, merged