kubectl: fixes issues #45736 and #45737
kubernetes/kubernetes pull request #45781
Opened 2017-05-13 23:15 UTC by robertojrojas

**What this PR does / why we need it**:
This PR improves the help displayed by the `kubectl proxy` command.

**Which issue this PR fixes**: 
fixes #45736, fixes #45737 

**Special notes for your reviewer**:
NONE

**Release note**:
NONE

```release-note
```

2017-05-13 23:22 UTC, cblecker commented
@k8s-bot ok to test
/release-note-none

2017-05-13 23:26 UTC, chrislovecnm requested changes
Noticed you accidentally replaced short with long.

2017-05-13 23:26 UTC, chrislovecnm commented on pkg/kubectl/cmd/proxy.go
> +		Short:   proxyLong,
You need to leave short in and set Long to proxyLong.

2017-05-14 00:35 UTC, cblecker commented
@k8s-bot kops aws e2e test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-14 14:10 UTC, chrislovecnm commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-14 14:12 UTC, chrislovecnm approved these changes
Looks great

2017-05-14 18:01 UTC, robertojrojas commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-15 17:13 UTC, cblecker commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-15 17:15 UTC, cblecker commented
/lgtm

2017-05-15 17:21 UTC, robertojrojas commented
/assign @smarterclayton

2017-05-16 19:58 UTC, ahmetb commented
@robertojrojas it looks like #45902 was also opened after this, we can go with your PR. #45902 has a bit more detailed explanation, should we incorporate that in this PR?

2017-05-16 20:11 UTC, robertojrojas commented
@ahmetb sure, no problem. I like that description better than what I have. I can take that description and update my PR. does that sound good to you?

2017-05-16 20:14 UTC, ahmetb commented
@robertojrojas I am not sure about the correctness. Make sure somebody verifies its contents :)

2017-05-17 02:02 UTC, smarterclayton commented
/approve

2017-05-17 02:03 UTC, cblecker commented
/lgtm cancel

2017-05-17 03:25 UTC, ahmetb commented
/approve cancel

2017-05-17 03:28 UTC, ahmetb commented
Is there a way to stop this from getting merged?

2017-05-17 03:33 UTC, ahmetb commented
/release-note-action-required

2017-05-17 03:38 UTC, cblecker commented
@ahmetb Yup :) `/lgtm cancel` does that. We're good.

2017-05-19 17:46 UTC, ahmetb commented
@robertojrojas do you have time to follow up with the changes on this PR

2017-05-19 17:53 UTC, robertojrojas commented
@ahmetb sorry, but I'm not sure I understand what you're asking me.

2017-05-19 18:02 UTC, ahmetb commented
@robertojrojas so we cancelled merging above (normally this was approved) because we're waiting on you to add the detailed explanation for `kubectl proxy` in the pull request #45902.

2017-05-19 19:30 UTC, robertojrojas commented
@ahmetb ah yeah. I'll do that today.

2017-05-19 20:16 UTC, robertojrojas commented
@ahmetb @cblecker let me know if you need to change anything.

2017-05-19 20:49 UTC, ahmetb commented
likely a flake
@k8s-bot kops aws e2e test this

2017-05-22 03:58 UTC, cblecker commented
@robertojrojas The indentation is not quite right for lines 38 through 41. Can you ensure there are two tab characters proceeding each of those lines, with no white spaces?

2017-05-22 22:29 UTC, cblecker commented
@robertojrojas Fantastic! One last thing before merge.. can you please swash the 4 commits into one?

2017-05-22 22:47 UTC, ahmetb commented
@cblecker is this necessary? I'm trying to see if squashing commits is documented anywhere on the contributor guide.

2017-05-22 22:53 UTC, cblecker commented
It isn't strictly necessary, but it provides a more useful history when the commits are all fixups based on feedback, rather than discrete features that we'd want a history for:
https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#6-squashing-and-commit-titles

2017-05-22 23:02 UTC, cblecker commented
@robertojrojas Thanks for your contribution! Once tests pass (don't worry about the federation test -- it's a known issue and is being worked on), the Submit Queue should automatically merge your PR.

/lgtm

2017-05-22 23:15 UTC, robertojrojas commented
@cblecker happy to help!

2017-05-22 23:52 UTC, cblecker commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this

2017-05-23 00:03 UTC, cblecker commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-05-23 02:07 UTC, merged