add test in kubectl set resource
kubernetes/kubernetes pull request #46084
Opened 2017-05-19 08:21 UTC by zjj2wry

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-05-21 17:17 UTC, soltysh reviewed
Small nits, otherwise looks good.

2017-05-21 17:17 UTC, soltysh commented on pkg/kubectl/cmd/set/set_resources_test.go
> +		if err == nil && (testCase.expectErr != "") {
Parentheses not needed.

2017-05-21 17:17 UTC, soltysh commented on pkg/kubectl/cmd/set/set_resources_test.go
> +		if err != nil {
Can you combine the two ifs together?

2017-05-22 06:38 UTC, zjj2wry commented on pkg/kubectl/cmd/set/set_resources_test.go
> +		if err != nil {
i attempt it, but **cmdutil.CheckErr(options.Validate())** will exit(code). i cannot get error to compare with my expectOut.
```
admindeMacBook-Pro:set admin$ go test
error: you must specify an update to requests or limits (in the form of --requests/--limits)
exit status 1
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/set	0.097s
```

2017-06-02 02:29 UTC, zjj2wry commented
@soltysh has rebase

2017-06-08 10:10 UTC, zjj2wry commented
@fabianofranz can you help review this? think you :)

2017-06-08 21:48 UTC, fabianofranz commented
@k8s-bot ok to test

2017-06-09 03:52 UTC, zjj2wry commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-09 21:48 UTC, fabianofranz commented
/approve
I'll let @soltysh do the lgtm.
Thanks @zjj2wry

2017-06-09 21:48 UTC, fabianofranz commented
/approve no-issue

2017-07-31 13:28 UTC, soltysh requested changes

2017-07-31 13:28 UTC, soltysh commented on pkg/kubectl/cmd/set/set_resources_test.go
> +		if err != nil {
@zjj2wry sorry for my long silence, I was OOO for quite a while. Anyway, I've tried this:
```go
		if err != nil && err.Error() != testCase.expectErr {
			t.Errorf("[%s]:expect err:%s got err:%s", testCase.name, testCase.expectErr, err.Error())
		}
```
here and it works like expected. Mind updating?

2017-08-04 02:15 UTC, zjj2wry commented
@soltysh ok, i will fix this. thank you reply 😊

2017-08-04 02:16 UTC, zjj2wry commented
@soltysh ok, i will fix this. thank you 😊

2017-08-10 08:45 UTC, closed without merging