Add CephFS volume source to describe printer.
kubernetes/kubernetes pull request #46124
Opened 2017-05-19 18:51 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

2017-05-19 18:53 UTC, humblec commented
/release-note-none

2017-05-19 18:56 UTC, humblec commented
@rootfs PTAL .

2017-05-19 19:06 UTC, childsb commented
@k8s-bot ok to test

2017-05-19 19:28 UTC, humblec commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-19 20:09 UTC, humblec commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-19 20:10 UTC, humblec commented
@k8s-bot kops aws e2e test this

2017-05-19 20:47 UTC, rootfs commented on pkg/printers/internalversion/describe.go
> +	w.Write(LEVEL_2, "Type:\tRBD (a Rados Block Device mount on the host that shares a pod's lifetime)\n"+
Cephfs

2017-05-19 20:52 UTC, humblec commented on pkg/printers/internalversion/describe.go
> +	w.Write(LEVEL_2, "Type:\tRBD (a Rados Block Device mount on the host that shares a pod's lifetime)\n"+
Done :). Thanks

2017-05-20 00:23 UTC, rootfs commented on pkg/printers/internalversion/describe.go
> +	w.Write(LEVEL_2, "Type:\tRBD (a CephFS mount on the host that shares a pod's lifetime)\n"+
still rbd :)

2017-05-20 05:12 UTC, humblec commented on pkg/printers/internalversion/describe.go
> +	w.Write(LEVEL_2, "Type:\tRBD (a CephFS mount on the host that shares a pod's lifetime)\n"+
Done. :)

2017-05-20 06:57 UTC, humblec commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-22 11:43 UTC, xiangpengzhao requested changes

2017-05-22 11:43 UTC, xiangpengzhao commented on pkg/printers/internalversion/describe.go
> +			printCephFSVolumeSource(volume.VolumeSource.CephFS, w)
Also need to add `printCephFSVolumeSource` in `describePersistentVolume`. And I sent a PR #46210 to add other volume sources.

2017-05-22 13:08 UTC, rootfs commented on pkg/printers/internalversion/describe.go
> +			printCephFSVolumeSource(volume.VolumeSource.CephFS, w)
good catch @xiangpengzhao

2017-05-22 14:36 UTC, humblec commented on pkg/printers/internalversion/describe.go
> +			printCephFSVolumeSource(volume.VolumeSource.CephFS, w)
Thanks @xiangpengzhao . I added to pv describe as well.

2017-05-22 18:12 UTC, fabianofranz commented
/unassign @fabianofranz

2017-05-22 18:27 UTC, humblec commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-22 18:50 UTC, rootfs commented
/lgtm

2017-05-22 18:54 UTC, rootfs commented
/assign @adohe

2017-05-23 03:23 UTC, humblec commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-23 16:12 UTC, rootfs commented
/lgtm 
/assign @adohe

2017-05-24 14:37 UTC, humblec commented
@adohe Can you please review/approve this PR ?

2017-05-25 15:30 UTC, fabianofranz commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-25 16:25 UTC, rootfs commented
/lgtm

2017-05-25 16:48 UTC, droot reviewed
LGTM

2017-05-25 17:53 UTC, droot approved these changes

2017-05-25 18:42 UTC, fabianofranz commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-25 22:56 UTC, fabianofranz commented
/approve

2017-05-26 01:46 UTC, xiangpengzhao commented
@k8s-bot pull-kubernetes-unit test this

2017-05-26 02:13 UTC, xiangpengzhao commented
The fix of unit test flake is #46383

2017-05-26 04:39 UTC, merged