Updates hostport pkg for IPv6
kubernetes/kubernetes pull request #46292
Opened 2017-05-23 16:29 UTC by danehans

**What this PR does / why we need it**:
Previously, the hostport pkg hardcoded the IPv4 version of
iptables. This PR adds support for the hostport pkg to select
either iptables or ip6tables based on the kubelet bind address
for the kubenet plugin.

**Which issue this PR fixes**: fixes #46291

**Special notes for your reviewer**:
This PR is part of a larger effort, Issue #1443 to add IPv6 support to k8s.

**Release note**:
<!--  Steps to write your release note:
```None
```

2017-05-23 18:14 UTC, danehans commented
/sig network /area ipv6

2017-05-23 18:41 UTC, danehans commented
/release-note-none

2017-05-23 18:43 UTC, danehans commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-23 19:57 UTC, dcbw commented
@danehans actually, we hope to remove this code from Kubelet and instead use the CNI hostports plugin instead: https://github.com/containernetworking/plugins/pull/1

@squeed for his thoughts too

2017-05-23 20:03 UTC, danehans commented
@dcbw I saw that point somewhere when I was coding this PR up. Either way, I thought it was required for kubenet though. Is that not the case?

2017-05-24 15:07 UTC, dcbw commented
@danehans yeah, it's currently required for kubenet, but the medium-term plan is to move most of kubenet's functionality to CNI plugins, so that we can replace kubenet with a CNI JSON config chain that does everything kubenet currently does, and then delete kubenet entirely.

2017-05-24 15:08 UTC, dcbw commented
@danehans would you mind looking over the referenced CNI hostports plugin and see if it looks reasonable to you from an IPv6 perspective?

2017-05-24 15:25 UTC, danehans commented
@dcbw happy to take a look at the CNI hostports plugin

2017-05-24 16:24 UTC, danehans commented
@dcbw Are you aware of any discussions for creating a CNI plugin that supersedes kube-proxy? @leblancd is starting to audit ipv6 for kube-proxy. I want to make he's aware of any upcoming changes.

2017-05-24 19:56 UTC, danehans commented
@dcbw I have another PR that I was going to submit for the kubelet to support v4/v6 iptables. I assume this will also be superseded by https://github.com/containernetworking/plugins/pull/1

Here are the changes I was going to propose: https://github.com/danehans/kubernetes/commit/9854a2a1313d6b4b6b21e44222386ee5ff50ac9a

Let me know if that's not the case.

2017-05-25 14:35 UTC, pmichali requested changes

2017-05-25 14:35 UTC, pmichali commented on pkg/kubelet/network/kubenet/kubenet_linux.go
> +	if addr.To16() != nil {
I think you need to place this in an else clause, as To16() will return non-nil, for IPv4 addresses.

2017-05-25 21:33 UTC, danehans commented
@pmichali I have updated the PR based on your feedback. However, I'm unsure if this gets merged due to the CNI hostport plugin that @dcbw referenced above.

2017-06-09 14:08 UTC, pmichali requested changes

2017-06-09 14:08 UTC, pmichali commented on pkg/kubelet/network/hostport/hostport_manager_test.go
> +	err := iptables.SaveInto(utiliptables.TableNAT, raw)
Forgive my ignorance on the operation here... are there cleanup operations that should be deferred t handle cases where a failure occurs with one of the host ports? E.g. closing ports, iptables restoration, hostport removal?

2017-06-09 14:08 UTC, pmichali commented on pkg/kubelet/network/hostport/hostport_syncer_test.go
> +		mapping *PodPortMapping
Same comment here, about a test case name to indicate which one failed, and use it in the Fatalf() calls below.

2017-06-13 18:40 UTC, danehans commented
@pmichali since https://github.com/containernetworking/plugins/pull/1 merged and supports IPv6, I think this PR is no longer valid. The kubelet hostport pkg will need to be updated to use cni/portmapper.

@squeed were you planning on adding cni/portmapper to the kubelet at a future date?

2017-06-16 16:29 UTC, squeed commented
@danehans I was not planning on doing the kubelet work at this time.

2017-06-16 17:32 UTC, danehans commented
@squeed OK. I want to make sure we're not stepping on each other toes :-)

I'll add it to the list for the k8s v6 working group. Thanks!

2017-09-15 08:04 UTC, closed without merging