clear init container status annotations when cleared in status
kubernetes/kubernetes pull request #46305
Opened 2017-05-23 20:42 UTC by sjenning

When I pod with an init container is terminated due to exceeding its active deadline, the pod status is phase `Failed` with reason `DeadlineExceeded`.  All container statuses are cleared from the pod status.

With init containers, however, the status is being regenerated from the status annotations.  This is causing kubectl to report the pod state as `Init:0/1` instead of `DeadlineExceeded` because the kubectl printer observes a running init container, which in reality is not running.

This PR clears out the init container status annotations when they have been removed from the pod status so they are not regenerated on the apiserver.

xref https://bugzilla.redhat.com/show_bug.cgi?id=1454674

@derekwaynecarr

2017-05-23 20:50 UTC, derekwaynecarr commented
@sjenning -- can we have a test?

2017-05-23 20:54 UTC, derekwaynecarr requested changes
need a test.

2017-05-23 22:12 UTC, wmengRH commented
bug link should be https://bugzilla.redhat.com/show_bug.cgi?id=1453180

2017-05-23 23:32 UTC, sjenning commented
@derekwaynecarr test added

2017-05-24 15:24 UTC, derekwaynecarr commented
/lgtm

2017-05-24 15:24 UTC, derekwaynecarr approved these changes

2017-05-24 15:25 UTC, derekwaynecarr commented
@smarterclayton -- can you approve?

2017-05-24 19:33 UTC, smarterclayton commented
/approve

2017-05-24 20:17 UTC, sjenning commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-24 21:18 UTC, merged