cleancode: Make test logic simple
kubernetes/kubernetes pull request #46334
Opened 2017-05-24 09:31 UTC by zhangxiaoyu-zidif

**What this PR does / why we need it**:
Put return err forward, that make the code much readable.

**Release note**:

```release-note
NONE
```

2017-05-31 18:01 UTC, derekwaynecarr commented on pkg/kubelet/config/file_linux_test.go
> +	err = f.Close()
this may not get called if there was a write error.

2017-05-31 18:02 UTC, derekwaynecarr requested changes

2017-05-31 18:02 UTC, derekwaynecarr commented on pkg/kubelet/config/file_linux_test.go
>  	if err == nil && n < len(data) {
this err check is redundant with the earlier return.

2017-05-31 22:03 UTC, zhangxiaoyu-zidif commented
@derekwaynecarr 
Thank you for review , sir.
I learn much from you. 
I change it. PTAL. =)

2017-08-11 15:32 UTC, xiangpengzhao commented on pkg/kubelet/config/file_linux_test.go
> +	n, _ := f.Write(data)
Why ignoring the error of `f.Write`?

2017-08-11 15:32 UTC, xiangpengzhao commented on pkg/kubelet/config/file_linux_test.go
> +	f.Close()
and here.

2017-08-11 15:52 UTC, xiangpengzhao requested changes

2017-08-11 15:52 UTC, xiangpengzhao commented on pkg/kubelet/config/file_linux_test.go
>  	return err
I'd prefer the logic like this:
```go
 func writeFile(filename string, data []byte) error {
 	f, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE, 0666)
  	if err != nil {
  		return err
  	}
	defer func() {
                err1 := f.Close()
		if err == nil {
			err = err1
		}
	}()
 	n, err := f.Write(data)
	if err != nil {
		return err
	}
  	if n < len(data) {
  		err = io.ErrShortWrite
  	}
  	return err
  }






```

2017-08-11 15:52 UTC, xiangpengzhao commented
/ok-to-test

2017-08-12 07:11 UTC, zhangxiaoyu-zidif commented on pkg/kubelet/config/file_linux_test.go
> +	n, _ := f.Write(data)
derekwaynecarr thinks it is redundant, it is impossible to occur error.

2017-08-12 07:11 UTC, zhangxiaoyu-zidif commented on pkg/kubelet/config/file_linux_test.go
>  	return err
well, let me see, and do some amend~

2017-08-14 05:49 UTC, zhangxiaoyu-zidif commented
/test pull-kubernetes-unit

2017-08-28 05:57 UTC, closed without merging