Move MountVolume.SetUp succeeded to debug level
kubernetes/kubernetes pull request #46367
Opened 2017-05-24 17:31 UTC by bobveznat

This message is verbose and repeated over and over again in log files
creating a lot of noise. Leave the message in, but require a -v in
order to actually log it.

**What this PR does / why we need it**: Moves a verbose log message to actually be verbose.

**Which issue this PR fixes** fixes #46364

2017-05-24 17:33 UTC, crassirostris commented
/cc @kubernetes/sig-storage-bugs

2017-05-24 17:34 UTC, crassirostris commented
@k8s-bot ok to test

2017-05-24 17:38 UTC, bobveznat commented
@k8s-bot I signed it!

2017-05-24 17:43 UTC, crassirostris commented
@bobveznat Thanks for your contribution!

@saad-ali Could you please take a look at this as an owner?

To both: I took a quick look over this file and it seems that all of the Info messages in this file can have higher verbosity, what about setting `V(3)` on all of them?

2017-05-24 18:16 UTC, saad-ali commented
@crassirostris Looks like this issue was originally raised in https://github.com/kubernetes/kubernetes/issues/29059. I'm sad to see we didn't get around to fixing it. Thank you for taking a crack at it.

The problem is that the configmap, secret, and downwardAPI volumes all require remount after successful mount to ensure that the contents of these volumes remains fresh. The volumemanager reconciler, which triggers the mount already ensures that it suppresses the success log message for these cases (see [`remountingLogStr`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L254)).

The operation executor, as you've discovered, does not. That said instead of decreasing the verbosity across the board for all volume mounts in operation executor, let's modify `operationExecutor.MountVolume(...)` to take a boolean, `isRemount`, and only decrease verbosity for that case.

2017-05-24 18:16 UTC, saad-ali commented
Also please add `Fixes #29059` to your original comment so that issue is resolved when this is merged.

2017-05-24 18:27 UTC, bobveznat commented
I'm not familiar with this code at all. As I'm looking at adding an isRemount flag I'm curious to know if we should instead just query "actualStateOfTheWorld" to decide if we're doing a remount or not? I don't know if that object can be queried quickly and efficiently? If it can should I make this code infer isRemount based on state?

Otherwise I'll work on passing isRemount around.

2017-05-24 18:42 UTC, saad-ali commented
> I'm not familiar with this code at all. As I'm looking at adding an isRemount flag I'm curious to know if we should instead just query "actualStateOfTheWorld" to decide if we're doing a remount or not? I don't know if that object can be queried quickly and efficiently? If it can should I make this code infer isRemount based on state?
> 
> Otherwise I'll work on passing isRemount around.

The reconciler already does that, and at [this point](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L239) it realizes that it has to do a remount. So at that point you can set your new boolean (which would be defaulted to `false`) to `true`. And then pass the boolean into `operationExecutor.MountVolume(...)`, you'll have to modify that interface accordingly to take the new boolean. All other calls to `operationExecutor.MountVolume(...)` should just set the value to false.

2017-05-24 21:55 UTC, bobveznat commented
Are these tests that are failing simply flaky tests? They don't seem to have anything to do with my change.

2017-05-25 04:56 UTC, thockin commented
/approve

2017-05-26 00:42 UTC, saad-ali commented
> Are these tests that are failing simply flaky tests? They don't seem to have anything to do with my change.

Unrelated -- I believe these test suites were broken today

2017-05-26 00:43 UTC, saad-ali commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-05-26 00:43 UTC, saad-ali commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-05-26 00:46 UTC, saad-ali requested changes
One minor change otherwise LGTM

2017-05-26 00:46 UTC, saad-ali commented on pkg/volume/util/operationexecutor/operation_generator.go
> +			verbosity = glog.Level(3)
Let's drop that to `.Level(7)` I think a lot of people log everything >4

2017-05-26 18:42 UTC, msau42 commented
/lgtm

2017-05-26 18:42 UTC, msau42 commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this

2017-05-26 23:26 UTC, saad-ali approved these changes

2017-05-26 23:27 UTC, saad-ali commented
/lgtm
/approve

2017-05-27 01:49 UTC, merged