Refactoring taint functions to reduce sprawl
kubernetes/kubernetes pull request #46514
Opened 2017-05-26 15:31 UTC by ravisantoshgudimetla

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #45060

**Special notes for your reviewer**:
@gmarek @timothysc @k82cn @jayunit100 - I moved some fn's to helpers and some to utils. LMK, if you are ok with this change.

**Release note**:

```release-note
NONE
```

2017-05-26 15:33 UTC, ravisantoshgudimetla commented
/cc @jayunit @gmarek @timothysc

2017-05-26 15:49 UTC, ravisantoshgudimetla commented
/cc @jayunit100

2017-05-26 17:15 UTC, cblecker commented
@ravisantoshgudimetla PR needs rebase

2017-06-07 16:20 UTC, gyliu513 commented
ping @ravisantoshgudimetla any update for this?

2017-06-07 16:32 UTC, ravisantoshgudimetla commented
@gyliu513 I am holding off the rebase till 1.7 release is out, so that I don't have to rebase it again later but if you think that this could be part of 1.7, I can rebase this PR now.

2017-06-07 16:35 UTC, gyliu513 commented
make sense, thanks @ravisantoshgudimetla , let's wait this after 1.7 release.

2017-07-02 20:33 UTC, ravisantoshgudimetla commented
/sig scheduling

Rebased the files. This is up for review now.

2017-07-05 00:56 UTC, gyliu513 commented on pkg/api/v1/helper/helpers.go
> +func ReorganizeTaints(node *v1.Node, overwrite bool, taintsToAdd []v1.Taint, taintsToRemove []v1.Taint) (string, []v1.Taint, error) {
@ravisantoshgudimetla Can you please show more detail for what is the intention of putting those functions such as `ReorganizeTaints`, `addTaints`, `deleteTaints` and `ValidateNoTaintOverwrites` to the `helper` folder but not the `taintutil` like `ParseTaints`?

Is there are policy for this such as when to update `helper` and when to update `util`?

2017-07-05 01:29 UTC, ravisantoshgudimetla commented on pkg/api/v1/helper/helpers.go
> +func ReorganizeTaints(node *v1.Node, overwrite bool, taintsToAdd []v1.Taint, taintsToRemove []v1.Taint) (string, []v1.Taint, error) {
> Is there are policy for this such as when to update helper and when to update **util?**

I am not aware of anything like that.


So, there is no consensus on where these fns have to be put and both places seemed reasonable. Please look at https://github.com/kubernetes/kubernetes/issues/45060#issuecomment-299125377

The following are the reasons that I chose those respective places.
- /pkg/util/taints/taints.go already had the fns that are needed for taint operations like Set, string conversion etc which are kind of basic operations on taints(I saw them more like primitive operations. For ex, all the fn's here operate on string, []string etc).
- /pkg/v1/helper operates only on the taints on node and fn's in this package may need some fn's from util package.

Again, these are my views and I am fine with making changes.

2017-07-05 02:11 UTC, k82cn commented on pkg/api/v1/helper/helpers.go
> +	added := addTaints(oldTaints, &newTaints)
why using list/slice pointer?

2017-07-05 02:36 UTC, gyliu513 commented on pkg/api/v1/helper/helpers.go
> +func ReorganizeTaints(node *v1.Node, overwrite bool, taintsToAdd []v1.Taint, taintsToRemove []v1.Taint) (string, []v1.Taint, error) {
Thanks @ravisantoshgudimetla for the explain, I was thinking put all of the functions to `taint util` maybe better as I can get all of the util fns for taint in one place and do not need to switch to other places. 

Let us wait what other's point for this issue.

2017-07-05 02:38 UTC, gyliu513 commented on pkg/api/v1/helper/helpers.go
> +	added := addTaints(oldTaints, &newTaints)
This is just a refactor and do not touch the old logic, if needed, I think that this should be handled in a separated PR.

2017-07-05 04:03 UTC, k82cn commented on pkg/api/v1/helper/helpers.go
> +	allErrs, deleted := deleteTaints(taintsToRemove, &newTaints)
will `taintsToAdd` and `taintsToRemove` have the same item? what's expected behaviour?

2017-07-05 04:06 UTC, k82cn commented on pkg/api/v1/helper/helpers.go
> +func ValidateNoTaintOverwrites(node *v1.Node, taints []v1.Taint) error {
this func is too specific to cli's requirement, prefer something like `Intersection`.

2017-07-05 04:07 UTC, k82cn commented on pkg/api/v1/helper/helpers.go
> +	MODIFIED  = "modified"
Those const seems only used by cli; can we just keep them in cli?

2017-07-05 04:21 UTC, k82cn commented
@ravisantoshgudimetla , comments overall:
1. some func are specific to cli's logic, prefer to make them more general, e.g.  `ValidateNoTaintOverwrites` can change to check intersection of node.Taints and newTains, if intersection is not 0 & overwrite is true, report error.
2. some func in v1helper and some func in util.taint, any guidance for that
3. related to # 2, it seems we did not include `pkg/util` in client-go; if using client-go in future, do we need another PR for that? cc/ @caesarxuchao for input

2017-07-05 14:04 UTC, ravisantoshgudimetla commented on pkg/api/v1/helper/helpers.go
> +func ValidateNoTaintOverwrites(node *v1.Node, taints []v1.Taint) error {
Makes sense. I will change it.

2017-07-05 14:06 UTC, ravisantoshgudimetla commented on pkg/api/v1/helper/helpers.go
> +	MODIFIED  = "modified"
These are needed for the reflecting node changes. So, I guess these are needed here.

2017-07-05 14:19 UTC, ravisantoshgudimetla commented on pkg/api/v1/helper/helpers.go
> +	allErrs, deleted := deleteTaints(taintsToRemove, &newTaints)
They are different. For example when someone wants to delete taints and add taints in single command like
` kubectl taint node1 dedicated1=sample=a dedicated-`

dedicated1 will be taintsToAdd and dedicated will be taintsToRemove.

2017-07-05 18:38 UTC, caesarxuchao commented
We talked about creating a k8s.io/util repo. @monopole @pwittrock is k8s.io/util on your radar?

2017-07-06 12:56 UTC, k82cn commented on pkg/api/v1/helper/helpers.go
> +	allErrs, deleted := deleteTaints(taintsToRemove, &newTaints)
Did not test; but what's the action if we run `kubectl taint node1 dedicated1=sample=a dedicated1-`?

2017-07-06 13:38 UTC, ravisantoshgudimetla commented on pkg/api/v1/helper/helpers.go
> +	allErrs, deleted := deleteTaints(taintsToRemove, &newTaints)
We will get an error like this:

error: can not both modify and remove the following taint(s) in the same command: {"sample":""}

2017-07-06 16:01 UTC, ravisantoshgudimetla commented
@k82cn I made the 1st change suggested but with small refining. Instead of returning bool, I am returning a string which has taintKeys seperated by `,` , so that we can tell the user what all keys are already existing.

Regarding points 2&3, I will wait for others to comment on.

Friendly ping @timothysc @gmarek @aveshagarwal

2017-07-07 01:25 UTC, k82cn commented
@monopole @pwittrock , what's the plan of `k8s.io/util`? when we do some refactor work, e.g. this PR, prefer to align with your plan, e.g. moving all helper funcs in to `pkg/api/helper`; so we can avoid missing as much as possible :).

2017-07-07 02:01 UTC, k82cn commented
Regarding 1st comments, honestly, I'd like to have a Taint Set operations, e.g. merge, sub/delete; this kind of helper is more general for other to use.

2017-07-07 18:23 UTC, ravisantoshgudimetla commented
> Regarding 1st comments, honestly, I'd like to have a Taint Set operations, e.g. merge, sub/delete; this kind of helper is more general for other to use.

So, if I understood correctly, you are suggesting to have some util package which has set operations on not only taints but for other items as well(like labels etc).

2017-07-08 11:54 UTC, k82cn commented
nop, export set operation for taints; NO other items, e.g. label.

2017-07-14 21:12 UTC, timothysc requested changes
I'm  against moving common code into api-helpers.  

The code should be in some common utility library either in the scheduler or other location.

2017-07-14 21:12 UTC, timothysc commented on pkg/api/v1/helper/helpers.go
> +	MODIFIED  = "modified"
I would prefer consts to be in a common location of a scheduling library, not sprinkled into the apimachinery.  This defeats the purpose.

2017-07-14 21:12 UTC, timothysc commented on pkg/api/v1/helper/helpers.go
> +func ReorganizeTaints(node *v1.Node, overwrite bool, taintsToAdd []v1.Taint, taintsToRemove []v1.Taint) (string, []v1.Taint, error) {
same

2017-07-15 01:28 UTC, k82cn commented
@timothysc , I'm thinking 'api/helper' is the 'common utility library' :).

2017-07-17 19:48 UTC, timothysc commented
> I'm thinking 'api/helper' is the 'common utility library' 

Please no... api should be touched so sparingly if/when possible.

2017-07-17 21:43 UTC, ravisantoshgudimetla commented
> Please no... api should be touched so sparingly if/when possible.

Would pkg/uti/taints.go be a good place? @timothysc

2017-07-17 21:45 UTC, timothysc commented
> Would pkg/uti/taints.go be a good place? @timothysc 

Yes please.

2017-07-17 21:48 UTC, ravisantoshgudimetla commented
Ok, I will move the fn's to that location. Thnx.

2017-07-18 22:43 UTC, ravisantoshgudimetla commented
@timothysc @k82cn @gyliu513 Moved the fn's as suggested.

2017-07-18 22:44 UTC, ravisantoshgudimetla commented
Accidentally closed the PR and re-opened it.

2017-07-19 00:21 UTC, ravisantoshgudimetla commented
/retest

2017-07-19 03:40 UTC, k82cn commented on pkg/util/taints/taints.go
> +// Tries to remove a taint from annotations list. Returns a new copy of updated Node and true if something was updated
start with `RemoveTaint`.

2017-07-19 03:41 UTC, k82cn commented on pkg/util/taints/taints.go
> +// Tries to add a taint to annotations list. Returns a new copy of updated Node and true if something was updated
ditto

2017-07-19 03:41 UTC, k82cn commented on pkg/util/taints/taints.go
> +func TaintExists(taints []v1.Taint, taintToFind *v1.Taint) bool {
please add comments for it.

2017-07-20 12:30 UTC, ravisantoshgudimetla commented
Any other comments?

2017-07-21 14:01 UTC, timothysc commented on pkg/util/taints/taints.go
> +func ParseTaints(spec []string) ([]v1.Taint, []v1.Taint, error) {
Are there unit tests for these functions?  If not we should add them.

2017-07-21 14:02 UTC, timothysc approved these changes

2017-07-21 14:02 UTC, ravisantoshgudimetla commented on pkg/util/taints/taints.go
> +func ParseTaints(spec []string) ([]v1.Taint, []v1.Taint, error) {
As of now, none, I want to add them in a separate PR as this is just for moving the fn's.

2017-07-21 14:26 UTC, timothysc commented
/lgtm

2017-07-21 14:38 UTC, ravisantoshgudimetla commented
Thanks for the review @timothysc. 

/assign @smarterclayton

2017-07-22 05:23 UTC, merged