Make "kubectl version" json format output more readable.
kubernetes/kubernetes pull request #46598
Opened 2017-05-29 16:08 UTC by xiangpengzhao

**What this PR does / why we need it**:
##39858 adds a flag --output to `kubectl version`, but the json format output is displayed in one line. It's not so readable. This PR fixes it.

and

- adds a shorthand for `output`
- refactors that: if `--short` is specified, `--output` will be ignored

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #43750

**Special notes for your reviewer**:
/cc @php-coder @alejandroEsc 

**Release note**:

```release-note
NONE
```

2017-05-29 16:14 UTC, php-coder commented
@xiangpengzhao Thanks! Could you post output of `kubectl version` after this change?

2017-05-29 16:34 UTC, xiangpengzhao commented
@php-coder I have shut down my laptop (it's midnight my local time). Will post tomorrow morning:)

2017-05-30 03:24 UTC, supereagle commented on pkg/kubectl/cmd/version.go
> +	cmd.Flags().StringP("output", "o", "", "output format, options available are yaml and json")
The first character of usage message should be upper case.

2017-05-30 03:24 UTC, supereagle commented on pkg/kubectl/cmd/version.go
>  	cmd.Flags().MarkShorthandDeprecated("client", "please use --client instead.")
Same error here. Please fix together.

2017-05-30 04:07 UTC, xiangpengzhao commented on pkg/kubectl/cmd/version.go
> +	cmd.Flags().StringP("output", "o", "", "output format, options available are yaml and json")
Addressed. Thanks Robin! @supereagle

2017-05-30 04:10 UTC, xiangpengzhao commented on pkg/kubectl/cmd/version.go
>  	cmd.Flags().MarkShorthandDeprecated("client", "please use --client instead.")
When we run `kubectl version -c`, the output will be `Flag shorthand -c has been deprecated, please use --client instead.` So we should leave it as is.

2017-05-30 04:17 UTC, xiangpengzhao commented
@php-coder FYI.

# kubectl version
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.635+8857d47607577c", GitCommit:"8857d47607577c0ddd4bf8b45b229d8e3008b898", GitTreeState:"clean", BuildDate:"2017-05-30T03:53:43Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.322+95a6f108bda5c4-dirty", GitCommit:"95a6f108bda5c4af79e78e4ebf613252c8c0fd5f", GitTreeState:"dirty", BuildDate:"2017-05-24T03:38:13Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```

# kubectl version -c
```
Flag shorthand -c has been deprecated, please use --client instead.
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.635+8857d47607577c", GitCommit:"8857d47607577c0ddd4bf8b45b229d8e3008b898", GitTreeState:"clean", BuildDate:"2017-05-30T03:53:43Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```

# kubectl version -o json
```
{
  "clientVersion": {
    "major": "1",
    "minor": "7+",
    "gitVersion": "v1.7.0-alpha.4.635+8857d47607577c",
    "gitCommit": "8857d47607577c0ddd4bf8b45b229d8e3008b898",
    "gitTreeState": "clean",
    "buildDate": "2017-05-30T03:53:43Z",
    "goVersion": "go1.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "7+",
    "gitVersion": "v1.7.0-alpha.4.322+95a6f108bda5c4-dirty",
    "gitCommit": "95a6f108bda5c4af79e78e4ebf613252c8c0fd5f",
    "gitTreeState": "dirty",
    "buildDate": "2017-05-24T03:38:13Z",
    "goVersion": "go1.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

# kubectl version -o yaml
```
clientVersion:
  buildDate: 2017-05-30T03:53:43Z
  compiler: gc
  gitCommit: 8857d47607577c0ddd4bf8b45b229d8e3008b898
  gitTreeState: clean
  gitVersion: v1.7.0-alpha.4.635+8857d47607577c
  goVersion: go1.8
  major: "1"
  minor: 7+
  platform: linux/amd64
serverVersion:
  buildDate: 2017-05-24T03:38:13Z
  compiler: gc
  gitCommit: 95a6f108bda5c4af79e78e4ebf613252c8c0fd5f
  gitTreeState: dirty
  gitVersion: v1.7.0-alpha.4.322+95a6f108bda5c4-dirty
  goVersion: go1.8
  major: "1"
  minor: 7+
  platform: linux/amd64
```

# kubectl version -o foo
`error: invalid output format: foo`

# kubectl version --short
```
Client Version: v1.7.0-alpha.4.635+8857d47607577c
Server Version: v1.7.0-alpha.4.322+95a6f108bda5c4-dirty
```

# kubectl version --short -o json
```
Client Version: v1.7.0-alpha.4.635+8857d47607577c
Server Version: v1.7.0-alpha.4.322+95a6f108bda5c4-dirty
```

2017-05-30 08:13 UTC, supereagle commented on pkg/kubectl/cmd/version.go
>  	cmd.Flags().MarkShorthandDeprecated("client", "please use --client instead.")
I see, thanks.

2017-05-30 10:24 UTC, php-coder commented
I see that this PR doesn't change the format of `kubectl version` command. This PR is adding a good improvements but they're a bit different.

If someone say to me that it's impossible to modify `kubectl version` output (because of backwards compatibility, for example) then I'd agree that this PR is fixing the original issue.

2017-05-30 13:49 UTC, alejandroEsc commented
I am a bit confused here. I thought I had resolved this issue earlier. Can i get an explanation of what is going on?

2017-05-30 13:52 UTC, alejandroEsc requested changes

2017-05-30 13:52 UTC, alejandroEsc commented on pkg/kubectl/cmd/version.go
> +	if cmdutil.GetFlagBool(cmd, "short") {
Why is this logic moved around? This was part of a very long discussion. Can i get some reasoning for this?

2017-05-30 15:42 UTC, xiangpengzhao commented
>I am a bit confused here. I thought I had resolved this issue earlier. Can i get an explanation of what is going on?

@alejandroEsc I think the PR description already explains this. 

>#39858 adds a flag --output to kubectl version, but the json format output is displayed in one line. It's not so readable. This PR fixes it.

After #39858, `kubectl version --output json` is as below.
```
{"clientVersion":{"major":"1","minor":"7+","gitVersion":"v1.7.0-alpha.4.662+cc432dbc779b43-dirty","gitCommit":"cc432dbc779b4318476e725d945933c08970548a","gitTreeState":"dirty","buildDate":"2017-05-30T07:38:09Z","goVersion":"go1.8","compiler":"gc","platform":"linux/amd64"},"serverVersion":{"major":"1","minor":"7+","gitVersion":"v1.7.0-alpha.4.322+95a6f108bda5c4-dirty","gitCommit":"95a6f108bda5c4af79e78e4ebf613252c8c0fd5f","gitTreeState":"dirty","buildDate":"2017-05-24T03:38:13Z","goVersion":"go1.8","compiler":"gc","platform":"linux/amd64"}}
```

After this PR, `kubectl version --output json` is as below.
```
{
  "clientVersion": {
    "major": "1",
    "minor": "7+",
    "gitVersion": "v1.7.0-alpha.4.635+8857d47607577c",
    "gitCommit": "8857d47607577c0ddd4bf8b45b229d8e3008b898",
    "gitTreeState": "clean",
    "buildDate": "2017-05-30T03:53:43Z",
    "goVersion": "go1.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "7+",
    "gitVersion": "v1.7.0-alpha.4.322+95a6f108bda5c4-dirty",
    "gitCommit": "95a6f108bda5c4af79e78e4ebf613252c8c0fd5f",
    "gitTreeState": "dirty",
    "buildDate": "2017-05-24T03:38:13Z",
    "goVersion": "go1.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

The latter is more readable.

2017-05-30 15:50 UTC, xiangpengzhao commented on pkg/kubectl/cmd/version.go
> +	if cmdutil.GetFlagBool(cmd, "short") {
I saw that discussion but it's too long. I didn't go through the detail. What I see the result of specifying both `--short` and `--output` is the full version. So my reason of the change here is ignore `--output` might be better for user experience. However, I don't have strong opinions on this. If there was enough reason in your former discussion, I'm open to leave the logic as is. Thanks for reviewing, Alejandro !

2017-05-30 16:41 UTC, pwittrock commented
I can't prioritize this for 1.7.

2017-05-31 02:12 UTC, xiangpengzhao commented
@pwittrock No problem, since it's non-critical fix.

2017-05-31 02:49 UTC, xiangpengzhao commented
@alejandroEsc inline comment addressed, I leave the `--short` logic as is. PTAL

2017-05-31 20:19 UTC, alejandroEsc commented
@xiangpengzhao thank you, we can talk about the additional change later, otherwise 
lgtm

2017-05-31 21:21 UTC, xiangpengzhao commented
Thanks @alejandroEsc!

2017-06-13 16:53 UTC, pwittrock commented
/assign alexandercampbell

2017-06-13 16:53 UTC, pwittrock commented
/unassign

2017-06-13 16:55 UTC, alexandercampbell commented
/assign

2017-07-10 21:45 UTC, spiffxp commented
/ok-to-test

2017-07-18 01:53 UTC, xiangpengzhao commented
/retest

2017-07-18 09:03 UTC, xiangpengzhao commented
/retest

2017-07-20 20:55 UTC, alexandercampbell commented
/lgtm

2017-07-21 01:32 UTC, xiangpengzhao commented
Thanks @alexandercampbell !

ping @fabianofranz for approval :)

2017-07-21 20:39 UTC, fabianofranz commented
/approve

2017-07-22 00:00 UTC, merged

2020-01-05 00:10 UTC, itkroplis commented
How is possible for shell command "kubectl version -o json" from output get only  1.15.2 and 1.13.2 ?
{
  "clientVersion": {
    "major": "1",
    "minor": "15",
    "gitVersion": "v1.15.2",
    "gitCommit": "f6278300bebbb750328ac16ee6dd3aa7d3549568",
    "gitTreeState": "clean",
    "buildDate": "2019-08-05T09:23:26Z",
    "goVersion": "go1.12.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "13",
    "gitVersion": "v1.13.2",
    "gitCommit": "cff46ab41ff0bb44d8584413b598ad8360ec1def",
    "gitTreeState": "clean",
    "buildDate": "2019-01-10T23:28:14Z",
    "goVersion": "go1.11.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}