Highlight nodeSelector when checking nodeSelector for Pod.
kubernetes/kubernetes pull request #46621
Opened 2017-05-30 12:33 UTC by gyliu513

**What this PR does / why we need it**:
Currently, we are using function name as `PodSelectorMatches` to check if `nodeSelector` matches for a Pod, it is better update the function name a bit to reflect it is checking `nodeSelector` for a Pod.

The proposal is rename `PodSelectorMatches` as `PodMatchNodeSelector`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-05-30 12:36 UTC, gyliu513 commented
/sig scheduling

2017-05-30 12:58 UTC, gyliu513 commented
/cc @kubernetes/sig-scheduling-pr-reviews

2017-05-30 13:23 UTC, gyliu513 commented
@k8s-bot pull-kubernetes-unit test this

2017-05-30 15:06 UTC, gyliu513 commented
@k8s-bot pull-kubernetes-unit test this

2017-06-03 04:54 UTC, timothysc requested changes
Minor comment then /lgtm

2017-06-03 04:54 UTC, timothysc commented on plugin/pkg/scheduler/algorithm/predicates/predicates.go
> +func PodMatchNodeSelector(pod *v1.Pod, meta interface{}, nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {
Could you add a godoc comment to this exported function seeing how you're cleaning it up?

2017-06-03 05:04 UTC, timothysc approved these changes

2017-06-03 05:05 UTC, timothysc commented
It appears this whole file could use a godoc update, I'll green light this and feel free to follow on with an update.

2017-06-03 05:08 UTC, gyliu513 commented on plugin/pkg/scheduler/algorithm/predicates/predicates.go
> +func PodMatchNodeSelector(pod *v1.Pod, meta interface{}, nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {
Sure, I will make a follow up PR for this.

@timothysc can you please add milestone 1.7 for this so that it can be in the submit queue?

2017-06-04 19:56 UTC, timothysc commented
This is minor cleanup work, so fine for 1.7

2017-06-04 21:54 UTC, gyliu513 commented
/retest

2017-06-04 22:38 UTC, gyliu513 commented
/retest

2017-06-05 00:43 UTC, gyliu513 commented
/retest

2017-06-05 01:29 UTC, gyliu513 commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-05 01:52 UTC, k82cn commented
There's an issue https://github.com/kubernetes/kubernetes/issues/46937 for the failed test :).

2017-06-05 09:01 UTC, gyliu513 commented
/retest

2017-06-05 09:01 UTC, gyliu513 commented
/retest

2017-06-05 20:27 UTC, timothysc commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-05 22:17 UTC, gyliu513 commented
/retest

2017-06-06 02:06 UTC, timothysc commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-06 09:21 UTC, merged