Azure cloudprovider retry using flowcontrol
kubernetes/kubernetes pull request #46660
Opened 2017-05-31 00:13 UTC by jackfrancis

An initial attempt at engaging exponential backoff for API error responses.

Uses k8s.io/client-go/util/flowcontrol; implementation inspired by GCE
cloudprovider backoff.

**What this PR does / why we need it**:

The existing azure cloudprovider implementation has no guard rails in place to adapt to unexpected underlying operational conditions (i.e., clogs in resource plumbing between k8s runtime and the cloud API). The purpose of these changes is to introduce exponential backoff wrapping around API calls. Inspired by the GCE's use of `k8s.io/client-go/util/flowcontrol`, this PR likewise uses `flowcontrol` to thinly wrap retry attempts to the API.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Pay especial note to the declaration of retry-able conditions from an unsuccessful HTTP request:
- `429` and `500` HTTP responses
- non-nil error responses

And the declaration of retry success conditions:
- `200` and `201` and `202` HTTP responses

Those may be incomplete, or in other ways non-representative.

**Release note**:

Added exponential backoff to Azure cloudprovider
```release-note
```

2017-05-31 08:24 UTC, jsafrane commented
I know very little about azure API behavior.

/unassign
/assign @colemickens

2017-05-31 08:24 UTC, jsafrane commented
@k8s-bot ok to test

2017-05-31 17:09 UTC, brendandburns requested changes

2017-05-31 17:09 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +Copyright 2016 The Kubernetes Authors.
nit: 2017

2017-05-31 17:09 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +	if resp.StatusCode == 429 || resp.StatusCode == 500 {
Should this be 5xx instead of just 500?

Also, please use http.StatusServerError etc. rather than hard constants.

2017-05-31 17:09 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +	if resp.StatusCode == 200 || resp.StatusCode == 201 || resp.StatusCode == 202 {
use `http.StatusOK` etc instead of constants.

2017-05-31 17:09 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure.go
> +	az.operationPollRateLimiter = flowcontrol.NewTokenBucketRateLimiter(1, 5)
You don't ever use this as far as I can tell.

I think we really want this to be used.

2017-05-31 17:09 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +	return wait.Poll(operationPollInterval, operationPollTimeoutDuration, func() (bool, error) {
How is this exponential backoff? Poll always just waits for Interval

2017-05-31 18:54 UTC, jackfrancis commented
@brendandburns thanks for keeping me honest, review notes incorporated

2017-06-01 20:22 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure.go
> +	az.operationPollRateLimiter = flowcontrol.NewTokenBucketRateLimiter(1, 5)
Let's make this configurable (and disable-able) via config file.

2017-06-01 20:26 UTC, brendandburns requested changes

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +	r, err := regexp.Compile(`^5\d\d$`)
Use numeric comparisons

eg

```
code >= http.StatusInternalError
```

Do this for the 2xx below too.

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +	r, err := regexp.Compile(`^2\d\d$`)
As above

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +				return nil, retryErr
Do we want to return here? Or just set `err = retryErr` and let the code below handle both err cases?

I think I prefer that approach.

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +				if retryErr != nil {
As above

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +					retryErr := az.CreateOrUpdateLBWithRetry(lb)
As above

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +					if retryErr != nil {
Here too

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +		if retryErr != nil {
And here

2017-06-01 20:26 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +			if retryErr != nil {
You get the point, I'm going to stop commenting on all of them

2017-06-01 20:42 UTC, jackfrancis commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +				return nil, retryErr
Yeah, your approach is better. The purpose of the novel `retryErr` reference (as opposed to reusing the existing `err` reference prior to checking for retry-ability is to be able to facilitate logging/debug in the retry execution branch. We can still do that by reusing the `err` reference and eliminate an unnecessary `return`.

2017-06-01 20:42 UTC, jackfrancis commented on pkg/cloudprovider/providers/azure/azure_loadbalancer.go
> +			if retryErr != nil {
I was enjoying how many variations you could come up with. :)

2017-06-01 21:30 UTC, fejta commented
@k8s-bot pull-kubernetes-e2e-kops-aws test this
ref: kubernetes/test-infra#2932

2017-06-01 21:44 UTC, jackfrancis commented on pkg/cloudprovider/providers/azure/azure.go
> +	az.operationPollRateLimiter = flowcontrol.NewTokenBucketRateLimiter(1, 5)
@brendandburns  @colemickens would the `--cloud-config` --> `Config` struct be the best configuration vector for this?

2017-06-02 01:45 UTC, brendandburns commented
Looks like you need to run `./hack/update-bazel.sh` otherwise, LGTM.

/lgtm
/approve

2017-06-05 17:08 UTC, grodrigues3 commented
@jackfrancis can you reference the issue that this PR addresses (it may be in this repo or features or another repo)?

2017-06-05 18:05 UTC, seanknox commented
@grodrigues3 here is the issue the ACS team is using to track this work: https://github.com/Azure/acs-engine/issues/635

2017-06-05 18:29 UTC, jdumars commented
@grodrigues3 I had asked this question during the leadership summit, but didn't get an answer.  Do we need to create a separate issue in k/k that references our issue in ACS?

2017-06-05 19:03 UTC, brendandburns commented on pkg/cloudprovider/providers/azure/azure.go
> +	az.operationPollRateLimiter = flowcontrol.NewTokenBucketRateLimiter(1, 5)
yes.

2017-06-05 19:04 UTC, brendandburns commented
@jackfrancis thanks for looking into this, it would be great to get this merged asap.

@grodrigues3 Do you us to file a specific kubernetes issue for this, or is the referenced issue sufficient?

Thanks

2017-06-06 00:04 UTC, jackfrancis commented
@brendandburns see `Config` updates in latest commit.

Both backoff and rate limiting can be configured therefrom, as well as enabled/disabled entirely.

2017-06-06 13:38 UTC, wojtek-t commented
@jackfrancis - this PR is marked as 1.7 milestone. However, according to the new policy, all non-trivial PRs has to link some issue, so if you want this in 1.7, please attach this PR to some issue.

2017-06-06 14:07 UTC, jdumars commented
/retest 

Also, I'm going to open an issue for this one referencing the ACS issue.

2017-06-06 14:39 UTC, jdumars commented
@wojtek-t @grodrigues3 Please see issue [47048](https://github.com/kubernetes/kubernetes/issues/47048)

2017-06-07 04:48 UTC, brendandburns commented
@jackfrancis this looks like it has some `go vet` errors.

You can run `go vet k8s.io/kubernetes/pkg/cloudprovider/providers/azure` to generate the errors.

2017-06-07 05:13 UTC, jackfrancis commented
@brendandburns thx, addressed

2017-06-07 13:34 UTC, jdumars commented
/retest

2017-06-07 13:36 UTC, jdumars commented
/sig-azure

2017-06-07 13:49 UTC, jdumars commented
/sig azure

2017-06-07 13:59 UTC, jdumars commented
@grodrigues3 @wojtek-t this should have the 1.7 milestone attached

2017-06-07 15:17 UTC, jdumars commented
@brendandburns LGTM needed

2017-06-07 15:21 UTC, brendandburns commented
Will look soon.

--brendan

________________________________
From: Jaice Singer DuMars <notifications@github.com>
Sent: Wednesday, June 7, 2017 8:17:41 AM
To: kubernetes/kubernetes
Cc: Brendan Burns; Mention
Subject: Re: [kubernetes/kubernetes] Azure cloudprovider retry using flowcontrol (#46660)


@brendandburns<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrendandburns&data=02%7C01%7Cbburns%40microsoft.com%7Cf8da174c34094b61590e08d4adb858d9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636324454654072622&sdata=8FMGW5GCDO49QqNDjYqu%2B0PeyCP99pW4aEj1%2BN6NNdg%3D&reserved=0> LGTM needed

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes%2Fpull%2F46660%23issuecomment-306827481&data=02%7C01%7Cbburns%40microsoft.com%7Cf8da174c34094b61590e08d4adb858d9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636324454654072622&sdata=hRjGv%2FLJiS2o0vpYCscbhOrQT8CucPYj0mvMTycLcjY%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFfDglQ3yFCPhZqDIOYAyORASDTfw5fcks5sBr8VgaJpZM4NrAPC&data=02%7C01%7Cbburns%40microsoft.com%7Cf8da174c34094b61590e08d4adb858d9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636324454654072622&sdata=XdJV8LkvG%2B6COOD7dPE1SS6pCF63y9JuZ5MwmZ4O8MQ%3D&reserved=0>.

2017-06-07 17:18 UTC, brendandburns commented
/lgtm
/approve

2017-06-07 17:20 UTC, brendandburns commented
/approve #47048

2017-06-07 17:21 UTC, brendandburns commented
/approve

2017-06-07 19:26 UTC, yangl900 reviewed
Looks good, just a few comments.

2017-06-07 19:26 UTC, yangl900 commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +	if 399 < resp.StatusCode && resp.StatusCode < 600 {
400 is not a retry-able error in Azure, I think should only retry status code == 429 or status code > 500

2017-06-07 19:26 UTC, yangl900 commented on pkg/cloudprovider/providers/azure/azure.go
> +	rateLimitQPSDefault    = 1.0
read quota is much higher than write, I don't know if you want to differentiate in this change. that potentially give you higher quota. we can improve this later too.

2017-06-07 19:26 UTC, yangl900 commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +			glog.Errorf("backoff: failure, will retry,err=%v", retryErr)
there is a Retry-After header returned from 429 requests, probably helpful if we trace that.

2017-06-07 19:44 UTC, jackfrancis commented on pkg/cloudprovider/providers/azure/azure_backoff.go
> +	if 399 < resp.StatusCode && resp.StatusCode < 600 {
@brendandburns I'm happy to incorporate this feedback if you're willing to go through the lgtm approval obstacle course all over agin. @yangl900 the other two remarks I believe we can justify tackling later on as part of a more holistic effort to pair k8s cloudprovider code with specific API idioms

2017-06-07 20:30 UTC, merged

2017-06-08 03:47 UTC, brendandburns commented
@jackfrancis can you address @yangl900's comments in a follow on PR?

Thanks!