StatefulSet upgrade test - replicated database (mysql)
kubernetes/kubernetes pull request #46738
Opened 2017-06-01 00:03 UTC by bdbauer

**What this PR does / why we need it**:
Adds a new upgrade test. The test creates a statefulset with a replicated mysql database. It populates the database and then continually polls the data while performing an upgrade. 

Ultimately, this PR increases confidence of reliability during upgrades. It helps show that StatefulSets and Pod Disruption Budgets are doing what they're supposed to.

Also vendors in a golang mysql client driver, for use in the test.

**Release note**:
```release-note
NONE
```

2017-06-01 23:07 UTC, maisem requested changes

2017-06-01 23:07 UTC, maisem commented on test/e2e/upgrades/mysql.go
> +	// upgrade interferes).
I think above 75%. @mml wdyt?

2017-06-02 00:17 UTC, mml commented on test/e2e/upgrades/mysql.go
> +	// upgrade interferes).
That's fine as a starting point.  I would pick a value in that neighborhood and leave the TODO comment.  We should look at what real life failure/success rates are after it's run for awhile.

2017-06-02 20:13 UTC, bdbauer commented on vendordiff.patch
> +Only in vendor/k8s.io/apiserver/pkg/registry/generic/registry: 127.0.0.1:21049114087
Done

2017-06-02 20:13 UTC, bdbauer commented on test/e2e/testing-manifests/statefulset/mysql-upgrade/configmap.yaml
> +piVersion: v1
Done

2017-06-02 20:13 UTC, bdbauer commented on test/e2e/upgrades/mysql.go
> +	minVersion := version.MustParseSemantic("1.4.0") // Which value here?
Done

2017-06-02 20:13 UTC, bdbauer commented on test/e2e/upgrades/mysql.go
> +	t.failure = 0
Done

2017-06-02 20:13 UTC, bdbauer commented on test/e2e/upgrades/mysql.go
> +	db, err := sql.Open("mysql", "root@tcp("+ip+":3306)/")
Done

2017-06-02 20:13 UTC, bdbauer commented on test/e2e/upgrades/mysql.go
> +	framework.Logf("res was: %v", res)
Done

2017-06-02 20:14 UTC, bdbauer commented on test/e2e/upgrades/mysql.go
> +	// upgrade interferes).
Agreed, .75 seems reasonable for now. Done.

2017-06-03 00:35 UTC, kargakis commented
@kubernetes/sig-apps-pr-reviews

2017-06-03 00:35 UTC, kargakis commented on test/e2e/testing-manifests/statefulset/mysql-upgrade/configmap.yaml
> +        name: mysql
fix indentation

2017-06-03 00:36 UTC, kargakis commented
Hrm, not sure if we want to start importing deps just for examples and we are in the middle of moving examples into their own repo (https://github.com/kubernetes/examples)

2017-06-05 18:35 UTC, mml commented
This is a test, not just an example.

On Fri, Jun 2, 2017 at 5:36 PM, Michail Kargakis <notifications@github.com>
wrote:

> Hrm, not sure if we want to start importing deps just for examples and we
> are in the middle of moving examples into their own repo (
> https://github.com/kubernetes/examples)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/46738#issuecomment-305937835>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAMK8B-0mgo38f7yRqxMQHFYi0uwqyRks5sAKqhgaJpZM4NsV3A>
> .
>

2017-06-05 23:07 UTC, kargakis commented
> This is a test, not just an example.

Sure, though 1. it doesn't seem that it tests a Kubernetes feature that is unetested (cc @kow3ns who is planning to work on statefulset upgrade e2e tests), and 2. the imported dependency seems unnecessary to me.

2017-06-06 18:05 UTC, bdbauer commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-06 18:06 UTC, bdbauer commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-10 01:13 UTC, bdbauer commented
Woops, totally messed this up, my bad. Will fix

2017-06-15 05:33 UTC, enisoc commented
@kargakis wrote:
> it doesn't seem that it tests a Kubernetes feature that is unetested (cc @kow3ns who is planning to work on statefulset upgrade e2e tests)

As far as I can tell, this is the first cluster upgrade test that checks what happens during the node rollout. All the ones I've seen just wait until the `done` channel is closed before checking anything. So this is definitely testing something novel: application availability during node rollouts. I thought @kow3ns was working on tests for rolling update of StatefulSet itself, not rolling update of nodes?

2017-06-15 20:09 UTC, enisoc commented
> I am still wondering why can't we test app availability w/o pulling in extra dependencies?

If by dependencies you mean specifically godeps, we could avoid that by building an image that serves a simple HTTP interface to run a query on MySQL. Then we launch that in a Deployment+Service and hit it from the e2e binary over HTTP. It would become an e2e test of both FE and BE availability during node rollouts.

Of course, that just converts the dependency from a godeps one to a Docker image. Does that sound better to you?

2017-06-22 23:26 UTC, mml requested changes
Also, please extract the image to examples as discussed elsewhere.

Oh, you may want to reference #38336 to get the appropriate milestone on this PR.

2017-06-22 23:26 UTC, mml commented on test/images/pets/mysql/main.go
> +	rows, err := db.Query("SELECT * FROM testing.users;")
Minor nit, but why not SELECT COUNT(*) and trust the database?  Maybe because we're trying to simulate more throughput?

2017-06-29 21:11 UTC, mml commented
/retest

2017-06-29 21:11 UTC, mml commented
@bdbauer Is this ready to go?

2017-06-29 21:29 UTC, bdbauer commented
I think this is good to go. The one possibly unresolved issue is being discussed in #47200 , deciding where to put the vendoring and image building.

2017-07-05 18:33 UTC, mml commented
/lgtm

/assign @lavalamp for approval

2017-07-05 21:21 UTC, mml commented
@bdbauer oh also plz squash before merge

2017-07-05 22:33 UTC, bdbauer commented
Squashed. @mml @lavalamp @maisem ptal.

2017-07-06 21:02 UTC, lavalamp commented
/approve

2017-07-10 18:51 UTC, bdbauer commented
/retest

2017-07-10 20:23 UTC, mml commented
@bdbauer 

```
W0707 21:24:10.685] test/e2e/upgrades/mysql.go:37: manifestPath redeclared in this block
W0707 21:24:10.685] 	previous declaration at test/e2e/upgrades/etcd.go:37
W0707 21:24:10.686] test/e2e/upgrades/mysql.go:60: kubectlCreate redeclared in this block
W0707 21:24:10.686] 	previous declaration at test/e2e/upgrades/etcd.go:57
```

2017-07-12 20:50 UTC, bdbauer commented
/retest

2017-07-12 22:41 UTC, merged