fix parse pairs
kubernetes/kubernetes pull request #46760
Opened 2017-06-01 08:57 UTC by xilabao

**What this PR does / why we need it**:
add check to `-`
```
# kubectl label pod foo -               
error: at least one label update is required
See 'kubectl label -h' for help and examples.
```

**Which issue this PR fixes**: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-06-01 21:56 UTC, fabianofranz commented
@k8s-bot ok to test

2017-06-02 01:05 UTC, xilabao commented
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-02 02:56 UTC, fabianofranz commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-02 11:48 UTC, soltysh requested changes
A few nits.

2017-06-02 11:48 UTC, soltysh commented on pkg/kubectl/cmd/util/helpers.go
> +		nonResource := strings.Contains(s, "=") || (strings.HasSuffix(s, "-") && s != "-")
If you're fixing this for hyphen (`-`) can you also add similar to check for the equal sign (`=`). I'm guessing the same error will appear if you use it.

2017-06-02 11:48 UTC, soltysh commented on pkg/kubectl/cmd/util/helpers.go
> +		} else if supportRemove && strings.HasSuffix(pairArg, "-") && pairArg != "-" {
Same here, although applied to a previous if.

2017-06-05 05:19 UTC, xilabao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-05 08:51 UTC, xilabao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-05 09:22 UTC, xilabao commented
/retest

2017-06-06 01:08 UTC, xilabao commented
/retest

2017-06-07 13:25 UTC, xilabao commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-07 13:26 UTC, xilabao commented
seems I cann't test it. @soltysh PTAL

2017-06-13 22:05 UTC, fabianofranz commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-07-20 01:44 UTC, xilabao commented
@soltysh kindly ping. ptal

2017-07-25 01:25 UTC, xilabao commented
@soltysh ptal

2017-08-04 14:10 UTC, soltysh approved these changes
lgtm

2017-08-04 14:10 UTC, soltysh commented
Sorry, was on PTO.
/lgtm

2017-08-04 14:10 UTC, soltysh commented
@fabianofranz mind approving?

2017-08-07 19:32 UTC, fabianofranz commented
/approve no-issue

2017-08-07 19:34 UTC, fabianofranz commented
Needs additional approvers.

2017-08-07 20:51 UTC, merged