Remove timestamps from docs/api-reference/*/*.html
kubernetes/kubernetes pull request #46857
Opened 2017-06-02 13:00 UTC by dims

**What this PR does / why we need it**:

If there are 2 or more PR(s) in the queue, they will end up with
conflicts (and rechecks). So let us remove the timestamp entirely
when we generate the files.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #46814

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-06-02 15:50 UTC, cblecker commented
/cc

2017-06-02 17:11 UTC, cblecker requested changes

2017-06-02 17:11 UTC, cblecker commented on hack/lib/swagger.sh
> +      sed -i 's/^Last updated.*$//' "${output_tmp}/${file}"
If we're using sed, we should use something like https://github.com/kubernetes/kubernetes/blob/master/staging/copy.sh#L64-L71 to ensure that we don't have flag issues between macOS/Linux

2017-06-02 19:13 UTC, fejta commented
/unassign
/assign @cblecker 

Please add me back if my help is needed!

2017-06-02 19:33 UTC, cblecker commented
This looks good, although please revert the change to `api/openapi-spec/swagger.json`. We shouldn't be downgrading the spec version here.

2017-06-02 19:38 UTC, cblecker commented
/lgtm

/unassign @brendandburns 
/assign @thockin 

@thockin As this is a docs improvement and small change to a single hack/ script, do you think this should be merged for 1.7?

2017-06-02 21:30 UTC, dims commented
@k8s-bot pull-kubernetes-federation-e2e-gce test this

2017-06-03 22:59 UTC, thockin commented on hack/lib/swagger.sh
> +      $SED -i 's/^Last updated.*$//' "${output_tmp}/${file}"
How sure are we that this is precise enough?  Maybe "^Last updated.*UTC$" ?

2017-06-03 22:59 UTC, thockin commented
AWESOME.  YOU ARE A HERO.

2017-06-03 23:00 UTC, thockin commented
As soon as you rebase this and get a green test run, we should merge ASAP.  Everyone will have to rebase one last time.

2017-06-03 23:01 UTC, thockin commented
@dchen1107 FYI - this will make things move faster after the initial pain.

@dims - poke me by slack or something when good

2017-06-03 23:01 UTC, thockin commented
/approve

2017-06-19 21:54 UTC, dchen1107 commented
@dims Can you rebase this pr? Thanks!

2017-06-19 23:25 UTC, dims commented
yes of course @dchen1107 coming up in a few

2017-06-20 00:54 UTC, cblecker commented
Failing verify because of some new lines in the diff.

Is it possible to split this out into two commits.. one with the changes to `hack/lib/swagger.sh`, and one with the `make update` after that change? Might make rebasing easier.

2017-06-20 00:58 UTC, dims commented
@cblecker one last try and then i'll split things up

2017-06-20 01:01 UTC, cblecker commented
@dims if it passes this time, then I'm fine with just leaving it as one and getting it merged. If you need to go back and make changes anyways because verify fails again, then yeah, two commits is easier to review :)

Thanks for this change.. excited to get it in!

2017-06-20 01:09 UTC, dims commented
@cblecker thanks. sorry, on a plane, so just doing the minimum and using the CI to run stuff :)

2017-06-20 01:14 UTC, cblecker commented
@dims No worries -- I've been there ✈️! As soon as verify goes green, I'll LGTM this :)

2017-06-20 01:40 UTC, dims commented
regular one worked, next stop - federation

2017-06-20 02:22 UTC, cblecker commented
/lgtm

2017-06-20 02:22 UTC, dims commented
yay, passed verify

2017-06-20 02:56 UTC, cblecker commented
/retest

2017-06-20 04:53 UTC, merged

2017-06-23 06:17 UTC, cblecker commented
Commenting for gubernator to update this PR's status :)