Enhanced the network policy describer.
kubernetes/kubernetes pull request #46951
Opened 2017-06-05 05:26 UTC by aanm

**Which issue this PR fixes**: Fixes https://github.com/kubernetes/kubectl/issues/17

**Special notes for your reviewer**: I need help to set up the right clientset for the unt tests

@kubernetes/sig-network-pr-reviews 

ping @adohe 

As suggested in https://github.com/kubernetes/kubectl/issues/17 , the output is similar to:
```
Name:           access-backend
Namespace:      default
Created on:     2017-06-04 21:45:56 -0700 PDT
Labels:         <none>
Annotations:    <none>
Spec:
  Pod Selector:     foo in (bar1,bar2),foo2 notin (bar1,bar2),id=app1,id2=app3
  Allowing ingress traffic:
    To Port: 80/TCP
    To Port: 82/TCP
    From Pod Selector: id=app2,id2=app3
    From Namespace Selector: id=app2,id2=app3
    From Namespace Selector: foo in (bar1,bar2),id=app2,id2=app3
    ----------
    To Port: <any> (traffic allowed to all ports)
    From: <any> (traffic not restricted by source)
```

2017-06-05 05:40 UTC, xiangpengzhao requested changes

2017-06-05 05:40 UTC, xiangpengzhao commented on pkg/printers/internalversion/describe_test.go
> +	port82 := intstr.FromInt(80)
intstr.FromInt(82)

2017-06-05 05:47 UTC, aanm commented
/retest

2017-06-05 06:02 UTC, xiangpengzhao commented
Failure info as below. Check your test case please.

```
I0605 05:50:54.155] pkg/printers/internalversion/describe_test.go:1556: cannot use versionedFake (type *"k8s.io/kubernetes/pkg/client/clientset_generated/clientset/fake".Clientset) as type internalclientset.Interface in field value:
I0605 05:50:54.156] 	*"k8s.io/kubernetes/pkg/client/clientset_generated/clientset/fake".Clientset does not implement internalclientset.Interface (wrong type for Admissionregistration method)
I0605 05:50:54.157] 		have Admissionregistration() "k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/admissionregistration/v1alpha1".AdmissionregistrationV1alpha1Interface
I0605 05:50:54.157] 		want Admissionregistration() "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/admissionregistration/internalversion".AdmissionregistrationInterface
W0605 05:50:56.232] ____Building complete.
W0605 05:50:56.316] ____Elapsed time: 203.982s, Critical Path: 162.01s
W0605 05:50:56.323] make: *** [bazel-build] Error 1
I0605 05:50:56.423] Makefile:506: recipe for target 'bazel-build' failed
E0605 05:50:56.780] Build failed
I0605 05:50:56.780] process 471 exited with code 2 after 3.5m
E0605 05:50:56.781] FAIL: pull-kubernetes-bazel
```

2017-06-14 14:38 UTC, danwinship commented
Note that currently (until we fix #46626) there are two basically-identical NetworkPolicy describers; one for networking.NetworkPolicy (describeNetworkPolicy, which you updated here) and one for extensions.NetworkPolicy (describeExtensionsNetworkPolicy). They differ only in type names. You should probably update both of them.

2017-06-21 20:59 UTC, aanm commented
@xiangpengzhao everything fixed! :)

2017-06-26 04:39 UTC, aanm commented
@smarterclayton can we merge this?

2017-06-28 13:24 UTC, danwinship commented
/release-note

2017-06-28 13:34 UTC, danwinship commented on pkg/printers/internalversion/describe.go
> +		(nps.PodSelector.MatchExpressions == nil || len(nps.PodSelector.MatchExpressions) == 0) {
I don't know if we have style guide recommendations about this, but `len(nil)==0`, so this is redundant. You only need

    if len(nps.PodSelector.MatchLabels) == 0 && len(nps.PodSelector.MatchExpressions) == 0 {

(likewise below inprintNetworkPolicySpecIngressFrom)

2017-06-28 13:34 UTC, danwinship commented on pkg/printers/internalversion/describe.go
> +		w.Write(LEVEL_2, "<none> (Allowing all traffic to all pods in this namespace)\n")
"all traffic" makes it sound like this has `ingress: [{}]`. Maybe something like "Allowing the specified traffic to all pods in this namespace"

2017-06-28 13:34 UTC, danwinship commented on pkg/printers/internalversion/describe_test.go
> +	VerifyDatesInOrder(out, "\n" /* rowDelimiter */, "	" /* columnDelimiter */, t)
why is this change here (and likewise the other tab/space-related changes)?

2017-06-28 14:06 UTC, aanm commented on pkg/printers/internalversion/describe.go
> +		(nps.PodSelector.MatchExpressions == nil || len(nps.PodSelector.MatchExpressions) == 0) {
Fixed!

2017-06-28 14:06 UTC, aanm commented on pkg/printers/internalversion/describe.go
> +		w.Write(LEVEL_2, "<none> (Allowing all traffic to all pods in this namespace)\n")
Fixed!

2017-06-28 14:06 UTC, aanm commented on pkg/printers/internalversion/describe_test.go
> +	VerifyDatesInOrder(out, "\n" /* rowDelimiter */, "	" /* columnDelimiter */, t)
This is a surprise to me as well, I've no idea where this came from...
Fixed!

2017-06-28 14:26 UTC, aanm commented
/retest

2017-10-05 01:28 UTC, aanm commented
/lgtm

2017-10-05 01:48 UTC, smarterclayton commented
/approve

On Wed, Oct 4, 2017 at 9:29 PM, Kubernetes Submit Queue <
notifications@github.com> wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> This pull-request has been approved by: *aanm
> <https://github.com/kubernetes/kubernetes/pull/46951#>*
> We suggest the following additional approver: *fabianofranz*
>
> Assign the PR to them by writing /assign @fabianofranz in a comment when
> ready.
>
> Associated issue: *17*
>
> The full list of commands accepted by this bot can be found here
> <https://github.com/kubernetes/test-infra/blob/master/commands.md>.
> Needs approval from an approver in each of these OWNERS Files:
>
>    - *pkg/printers/OWNERS
>    <https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/OWNERS>*
>
> You can indicate your approval by writing /approve in a comment
> You can cancel your approval by writing /approve cancel in a comment
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/46951#issuecomment-334334539>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p2PcDaj22IrGYvj6rfB7wBCEZrMrks5spDDxgaJpZM4Nvp7V>
> .
>

2017-10-29 00:54 UTC, caseydavenport commented
@aanm this LGTM - sorry it's been such a long time!

Are you planning on adding in support for egress + ipblock policies available in v1.8?

2017-10-30 16:16 UTC, cmluciano commented
/lgtm

2017-10-30 22:38 UTC, merged

2018-07-19 09:01 UTC, zdtsw commented
Hi, 
in which version the implementation is merged?
I currently have kube client v1.8.3 server v1.8.2-beta.0.510+cfa2424cf0f326,and I still get return  from "kubectl describe networkpolicy" not showing any information of ports or ip