Remove duplicate errors from an aggregate error input.
kubernetes/kubernetes pull request #47003
Opened 2017-06-05 23:35 UTC by aveshagarwal

This PR, in general, removes duplicate errors from an aggregate error input, and returns unique errors with their occurrence count. Specifically,  this PR helps with some scheduler errors that fill the log enormously. For example, see the following `truncated` output from a 300-plus nodes cluster, as there was a same error from almost all nodes.

[SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected., SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found.........

After this PR, the output looks like (on a 2-node cluster):

SchedulerPredicates failed due to persistentvolumeclaims "mongodb" not found, which is unexpected.(Count=2)

@derekwaynecarr @smarterclayton @kubernetes/sig-scheduling-pr-reviews

2017-06-05 23:50 UTC, aveshagarwal commented
I will add unit tests soon.

2017-06-06 00:56 UTC, caesarxuchao commented
The code looks fine. Do we see big aggregated error other than in the scheduler?

2017-06-06 01:21 UTC, aveshagarwal commented
I have output from only from scheduler, not from other components so can't say for sure. But it seems a high possibility. Simple grep (`grep -ri newaggregate . --exclude-dir={_output,vendor,test,kubectl} --exclude=*test.go`) shows many places where k8s.io/apimachinery/pkg/util/errors.NewAggregate is being called, though haven't verified what kind of aggregation they are.

2017-06-06 01:27 UTC, smarterclayton commented
We use aggregate a lot - unfortunately I think it's going to have to be
case by case.  However, we *should* vet every place we send an event that
contains the error output naively and chop / limit it.

On Mon, Jun 5, 2017 at 9:21 PM, Avesh Agarwal <notifications@github.com>
wrote:

> I have output from only from scheduler, not from other components so can't
> say for sure. But it seems a high possibility. Simple grep (grep -ri
> newaggregate . --exclude-dir={_output,vendor,test,kubectl}
> --exclude=*test.go) shows many places where k8s.io/apimachinery/pkg/util/
> errors.NewAggregate is being called, though haven't verified what kind of
> aggregation they are.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/47003#issuecomment-306354647>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_p-b4Ag12I92zcLMBJKxqQXhKO80cks5sBKmzgaJpZM4NwsQq>
> .
>

2017-06-06 13:24 UTC, aveshagarwal commented
I have added unit tests. PTAL.

2017-06-06 15:10 UTC, aveshagarwal commented
@k8s-bot pull-kubernetes-unit test this

2017-06-06 15:45 UTC, aveshagarwal commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-unit test this

2017-06-06 15:46 UTC, ncdc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +		result = append(result, errors.New(fmt.Sprintf("%v(Count=%v)", errStr, count)))
Use `fmt.Errorf` instead of `errors.New(fmt.Sprintf`

2017-06-06 15:46 UTC, ncdc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +	result := []error{}
You know that `len(errorCountMap)` is # of keys that you have, so I would do `result := make([]error, 0, len(errorCountMap))`

2017-06-06 15:46 UTC, ncdc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors_test.go
> +			t.Errorf("%d: expected %v, got %v", i, testCase.expected, agg)
I'd recommend using go1.7's subtests (see e.g. https://github.com/kubernetes/kubernetes/blob/0c516c3ac216cca8be8b033a712069d4d0336ec0/pkg/auth/nodeidentifier/default_test.go#L58)

2017-06-06 16:24 UTC, aveshagarwal commented
@ncdc thanks for review. Updated. PTAL.

2017-06-06 16:31 UTC, ncdc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors_test.go
> +				t.Errorf("%d: expected %v, got %v", i, testCase.expected, agg)
Because you're using subtests, you don't need to include `%d` (`i`) in the output.

2017-06-06 16:31 UTC, ncdc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +		result = append(result, fmt.Errorf("%v(Count=%v)", errStr, count))
I would at least put a space in between the error text and the count information. I wonder if `(Count=n)` is the best way to show this, or if something like `(repeated n times)` would look better? WDYT @timothysc @derekwaynecarr?

Also, if we keep the `Count=` format, I would make it lowercase `count`.

2017-06-06 16:46 UTC, aveshagarwal commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +		result = append(result, fmt.Errorf("%v(Count=%v)", errStr, count))
I am fine with `(repeated n times)` too.

2017-06-06 19:14 UTC, derekwaynecarr commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +		result = append(result, fmt.Errorf("%v(Count=%v)", errStr, count))
I am fine with `(repeated n times)`  as well.

2017-06-06 19:37 UTC, aveshagarwal commented
Following updates to this PR: 1) minor change in code to print repeated string only if count > 1. 2) changed unit tests to compare results on sorted slices of []errors, otherwise I noticed unit tests were flaking due to different orders of errors in output. 

@ncdc PTAL.

2017-06-06 21:23 UTC, ncdc requested changes

2017-06-06 21:23 UTC, ncdc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +			countStr = fmt.Sprintf("(repeated %v times)", count)
Please add an initial space to the string

2017-06-06 21:31 UTC, aveshagarwal commented
@ncdc updated, PTAL.

2017-06-06 21:50 UTC, ncdc commented
LGTM (please squash once you get the ok from all reviewers)

2017-06-07 01:28 UTC, timothysc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +	errs := Flatten(agg).Errors()
given that you already have the original err[] list from the predicates function you are doing an extra N operations here.  So it's 2N+Y where Y is the reduction.  I'd almost list to change it at the source to bin the errors.  I swear @jayunit100 did just that but it must have been in a different section of code.

2017-06-07 01:55 UTC, smarterclayton commented
I thought that was in the scheduler for the fit error

2017-06-07 13:09 UTC, aveshagarwal commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +	errs := Flatten(agg).Errors()
If your concern is why I am calling Flatten, then the reason is that this function is not specific to scheduler and so the need to call Flatten. Also what @jayunit100 had done was for specific to the fit errors where these are other (atleast previously) unexpected errors.

2017-06-07 14:39 UTC, timothysc commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +	errs := Flatten(agg).Errors()
The point is you can bin on insertion and prevent the need to re-run through it, the append is only a couple of lines above -  

https://github.com/kubernetes/kubernetes/pull/47003/files#diff-a9420b7e5a53a445d54a716d341874abR192 

If you bin there, then you could have a NewAggregate overload that passes in the error map and you don't need a 2N+Y it's just 2Y.

2017-06-07 14:46 UTC, aveshagarwal commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +	errs := Flatten(agg).Errors()
But as I said that this function UniqueAggregateWithCoun is not specific to scheduler.

2017-06-07 15:21 UTC, timothysc requested changes

2017-06-07 15:21 UTC, timothysc commented on plugin/pkg/scheduler/core/generic_scheduler.go
> +			return []*v1.Node{}, FailedPredicateMap{}, errors.UniqueAggregateWithCount(errors.NewAggregate(errs))
Please bin on insertion above.  
https://github.com/kubernetes/kubernetes/pull/47003/files#diff-a9420b7e5a53a445d54a716d341874abR192

2017-06-07 17:38 UTC, aveshagarwal commented on plugin/pkg/scheduler/core/generic_scheduler.go
> +			return []*v1.Node{}, FailedPredicateMap{}, errors.UniqueAggregateWithCount(errors.NewAggregate(errs))
I have separated functionality in 2 functions: one that calls flatten and one doesn't where it is known that the input is flattened already.

2017-06-07 17:49 UTC, aveshagarwal commented on plugin/pkg/scheduler/core/generic_scheduler.go
> +			return []*v1.Node{}, FailedPredicateMap{}, errors.UniqueAggregateWithCount(errors.NewAggregate(errs))
Hold on, I am changin it another way.

2017-06-07 19:32 UTC, aveshagarwal commented
@timothysc Updated PR. PTAL.

2017-06-07 21:13 UTC, timothysc approved these changes
Thx for making the change!  much better. 
/lgtm

2017-06-07 21:16 UTC, ncdc approved these changes

2017-06-07 21:16 UTC, ncdc commented
/lgtm too

2017-06-07 21:32 UTC, derekwaynecarr commented
/assign @davidopp

2017-06-07 21:33 UTC, derekwaynecarr commented
/lgtm

2017-06-07 21:51 UTC, timothysc commented
I approve of the scheduler changes.. 

@caesarxuchao or @smarterclayton want to approve the api changes?

2017-06-07 22:01 UTC, smarterclayton commented
/approve

2017-06-07 22:05 UTC, ncdc commented
@aveshagarwal can you please create a GitHub issue for this problem, then edit the description of this PR to say that it fixes said issue? Thanks!

2017-06-07 22:31 UTC, aveshagarwal commented
@ncdc done. thanks.

2017-06-07 23:14 UTC, gyliu513 commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go
> +// MessagesgCountMap contains occurance for each error message.
s/MessagesgCountMap/MessageCountMap

2017-06-07 23:14 UTC, gyliu513 commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors_test.go
> +		mcp      MessageCountMap
How about s/mcp/mcm ?

2017-06-07 23:14 UTC, gyliu513 commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors_test.go
> +			MessageCountMap{"abc": 2, "ghi": 1},
How about adding a new case only switching the order of `abc` andn `ghi` to test sort?

```
MessageCountMap{"ghi": 1, "abc": 1},
```

2017-06-08 00:55 UTC, merged

2017-06-08 13:36 UTC, aveshagarwal commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors_test.go
> +			MessageCountMap{"abc": 2, "ghi": 1},
As it is already merged, if you want, you could do a follow-up PR for this.

2017-06-08 13:36 UTC, aveshagarwal commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors_test.go
> +		mcp      MessageCountMap
sorry I saw your comment when this was already merged.

2017-06-09 00:43 UTC, gyliu513 commented on staging/src/k8s.io/apimachinery/pkg/util/errors/errors_test.go
> +			MessageCountMap{"abc": 2, "ghi": 1},
@aveshagarwal a PR here https://github.com/kubernetes/kubernetes/pull/47206 as a follow up