Allow to specify tls config for coredns provider
kubernetes/kubernetes pull request #47049
Opened 2017-06-06 14:51 UTC by dshulyak

Closes: https://github.com/kubernetes/kubernetes/issues/42995

2017-06-06 17:36 UTC, colhom requested changes

2017-06-06 17:36 UTC, colhom commented on federation/pkg/dnsprovider/providers/coredns/coredns.go
> +		return nil, err
nit: scope error `error creating tls client config: %v`

2017-06-06 17:36 UTC, colhom commented on federation/pkg/dnsprovider/providers/coredns/coredns.go
> +	etcdTransport, err := newTransportForETCD2(certFile, keyFile, caFile)
`newTransportForETCD2` will only succeed in creating an HTTPS transport- there should still be an option to use default HTTP transport as well (perhaps if certs paths are all blank?)

2017-06-06 17:36 UTC, colhom commented on federation/pkg/dnsprovider/providers/coredns/coredns.go
> +func newTransportForETCD2(certFile, keyFile, caFile string) (*http.Transport, error) {
name should be more along lines of `etcdTLSTransport()`? I'm not sure the fact that it's the etcd v2 API specifically is relevant at the transport layer.

2017-06-06 17:36 UTC, colhom commented on federation/pkg/dnsprovider/providers/coredns/coredns.go
> +		return nil, fmt.Errorf("Can't create transport for etcd2. Err: %v", err)
nit: lower case error messages

2017-06-06 20:25 UTC, fejta commented
/retest

2017-06-07 07:26 UTC, dshulyak commented on federation/pkg/dnsprovider/providers/coredns/coredns.go
> +func newTransportForETCD2(certFile, keyFile, caFile string) (*http.Transport, error) {
for etcdv3 TLSConfig is a part of etcd.Config - https://github.com/coreos/etcd/blob/master/clientv3/config.go#L37

2017-06-07 07:32 UTC, dshulyak commented
@colhom fixed all issues, please take a look

2017-06-08 09:31 UTC, dshulyak commented
I will add a note when I will finish testing

2017-07-21 10:48 UTC, dshulyak commented
@colhom can you please take a look again? I think it is ready to be merged

2017-07-21 15:03 UTC, colhom approved these changes

2017-07-21 15:03 UTC, colhom commented on federation/pkg/dnsprovider/providers/coredns/coredns.go
> +		cfg = nil
This is more of a nit: so we can go ahead without this change and pehaps you could clean this up in a follow-up PR?

2017-07-21 15:05 UTC, colhom commented
lgtm

2017-07-21 15:19 UTC, colhom approved these changes

2017-07-21 15:20 UTC, colhom commented
/approve

thanks @dshulyak

2017-07-21 15:31 UTC, colhom commented
/assign @csbell

2017-07-24 16:47 UTC, colhom commented
/approve

2017-07-24 16:49 UTC, colhom commented
\cc @csbell

2017-07-26 08:41 UTC, pigmej commented
Folks, could we please merge this? Or maybe at least have another set of reviews?

2017-08-14 16:28 UTC, dshulyak commented
@csbell hi, can you take a look on this change?

2017-08-14 16:49 UTC, csbell commented
/assign @shashidharatd

2017-08-14 17:32 UTC, shashidharatd commented
/lgtm
Thanks @dshulyak !

2017-08-21 08:40 UTC, dshulyak commented
/retest

2017-08-21 14:35 UTC, dshulyak commented
/test pull-kubernetes-kubemark-e2e-gce

2017-08-22 06:59 UTC, dshulyak commented
@shashidharatd would you add release-note label?

2017-08-22 07:04 UTC, dshulyak commented
@shashidharatd would you add release-note label?

2017-08-22 09:19 UTC, shashidharatd commented
/release-note CoreDNS provider config allows to set TLS certificates for etcd client.

2017-08-22 11:54 UTC, shashidharatd commented
@dshulyak please update the release note according to the instructions here https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#write-release-notes-if-needed

@csbell, PTAL and approve this pr.

2017-08-22 16:40 UTC, quinton-hoole commented
/approve

2017-08-24 19:09 UTC, quinton-hoole commented
/retest

2017-08-27 19:21 UTC, dshulyak commented
/test pull-kubernetes-unit

2017-08-28 03:47 UTC, shashidharatd commented
@quinton-hoole, request to remove `do-not-merge` label for this pr.

2017-09-05 12:09 UTC, dshulyak commented
@quinton-hoole take a look please

2017-09-23 00:09 UTC, spiffxp commented
/retest

2017-09-23 04:20 UTC, merged