Map a resource to multiple signals in eviction manager
kubernetes/kubernetes pull request #47080
Opened 2017-06-06 21:09 UTC by jingxu97

It is possible to have multiple signals that point to the same type of
resource, e.g., both SignalNodeFsAvailable and
SignalAllocatableNodeFsAvailable refer to the same resource NodeFs.
Change the map from map[v1.ResourceName]evictionapi.Signal to
map[v1.ResourceName][]evictionapi.Signal

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-06-08 20:40 UTC, jingxu97 commented
@dashpole PTAL

2017-06-12 14:55 UTC, dashpole commented
/release-note-none

2017-06-12 15:08 UTC, dashpole commented
Code changes look good.  Im not sure having resourceNodeFs map to both SignalAllocatableNodeFsAvailable and SignalNodeFsAvailable makes sense. This implies that all reclaim functions which free SignalAllocatableNodeFsAvailable also free SignalNodeFsAvailable, and vice versa.  I dont think is true for our reclaim functions.  We have two reclaim functions: Image GC, and Container GC.   But [we only count active (non-terminated) container logs, volumes, and rootfs](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/helpers.go#L739) towards allocatable.  So cleaning up dead containers, or unused images should **not** increase SignalAllocatableNodeFsAvailable, but only SignalNodeFsAvailable if my reasoning is correct.

What we could do instead would be to have the reclaim functions return a `map[signal]resource.Quantity`  to allow it to specify per-signal the amount that was reclaimed.  Other things may work as well.

2017-07-12 01:07 UTC, jingxu97 commented
I think the storage resource freed by cleaning up dead containers, or unused images should also increase SignalAllocatableNodeFsAvailable, is there a reason it should not be counted? 

cc @vishh Could you please confirm?

2017-07-24 23:04 UTC, jingxu97 commented
@vishh Could you please review and approve this? Thanks!

2017-07-24 23:28 UTC, vishh requested changes
Can you add unit tests please?

2017-09-01 19:57 UTC, jingxu97 commented
@dashpole I changed the code based on you comments. I agree that reclaim nodefs resource should not accounted as allocatable resource.
@vishh I added the unit tests for allocatable resources.

2017-09-01 20:16 UTC, dashpole commented
lgtm!

2017-09-01 21:55 UTC, vishh approved these changes

2017-09-01 21:55 UTC, vishh commented
/approve

2017-09-01 22:23 UTC, jingxu97 commented
/retest

2017-09-11 17:13 UTC, jingxu97 commented
/retest

2017-09-15 18:48 UTC, jingxu97 commented
/retest

2017-09-19 17:52 UTC, saad-ali commented
/test pull-kubernetes-node-e2e

2017-09-19 17:52 UTC, saad-ali commented
/test pull-kubernetes-e2e-gce-gpu

2017-09-20 00:31 UTC, merged