[GCE] Decouple Nvidia GPU driver installer from the COS base image
kubernetes/kubernetes pull request #47091
Opened 2017-06-06 23:42 UTC by vishh

Attempt to consume kernel commit ID from /etc/os-release while installing Nvidia drivers on COS

This is GCE only and does not affect Kubernetes proper. Once the GCE cluster setup logic moves off of the core, such PRs will not show up post code freeze.

cc @dchen1107 @mindprince @ameyd

2017-06-06 23:44 UTC, vishh commented
/approve no-issue

2017-06-06 23:51 UTC, rohitagarwal003 requested changes
Can you also cherry-pick: https://github.com/mindprince/kubernetes/commit/b2e9c58d9b889d774d822940dbcd5ddefa3ef828

2017-06-06 23:51 UTC, mindprince commented on cluster/gce/gci/nvidia-gpus/installer.sh
> +# LAKITU_KERNEL_SHA1 (Optional) - If not set, the script will attempt to auto-detect kernel commit ID from `/etc/os-release`
Let's change this to:
```
If set, it should be set to the HEAD of the kernel version used on the host. If not set, the script will attempt to auto-detect kernel commit ID from `/etc/os-release`.
```

2017-06-06 23:51 UTC, mindprince commented on cluster/gce/gci/nvidia-gpus/installer.sh
> +
Nit: get rid of the trailing whitespace.

2017-06-06 23:54 UTC, mindprince commented on cluster/gce/gci/nvidia-gpus/installer.sh
>      echo "Downloading kernel source at tag ${kernel_version_stripped} ..."
This and the lines above can be removed.

2017-06-07 01:10 UTC, mindprince commented on cluster/gce/gci/nvidia-gpus/cos-installer-daemonset.yaml
> +      - image: gcr.io/google_containers/cos-nvidia-driver-install@292ffa20322805cc98a2622d0437ab48d86cb585caf2ca0671126b877536b2ea
Missing `sha256`.

2017-06-07 01:10 UTC, mindprince commented
/lgtm
/approve

2017-06-07 01:30 UTC, vishh commented on cluster/gce/gci/nvidia-gpus/cos-installer-daemonset.yaml
> +      - image: gcr.io/google_containers/cos-nvidia-driver-install@292ffa20322805cc98a2622d0437ab48d86cb585caf2ca0671126b877536b2ea
Good catch. Fixed.

2017-06-07 15:54 UTC, mindprince commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-07 18:59 UTC, cmluciano reviewed
/lgtm

2017-06-07 19:50 UTC, rohitagarwal003 approved these changes

2017-06-07 20:58 UTC, mindprince commented
@dchen1107 @vishh Can you add lgtm label, so that this gets merged.

2017-06-07 21:19 UTC, Amey-D commented on cluster/gce/gci/nvidia-gpus/installer.sh
> +    git pull origin
I'd suggest wrap this in a sleep-retry logic to avoid any flakes.

2017-06-07 21:19 UTC, Amey-D commented on cluster/gce/gci/nvidia-gpus/installer.sh
>      git checkout ${LAKITU_KERNEL_SHA1}
`git checkout` will not throw error if `${LAKITU_KERNEL_SHA1}` is empty.  explicitly check if `$LAKITU_KERNEL_SHA1` is not empty or add `set -o nounset` at the top.

2017-06-08 16:58 UTC, vishh commented on cluster/gce/gci/nvidia-gpus/installer.sh
> +    git pull origin
Good idea. Testing changes.

2017-06-08 16:58 UTC, vishh commented on cluster/gce/gci/nvidia-gpus/installer.sh
>      git checkout ${LAKITU_KERNEL_SHA1}
Done

2017-06-08 18:50 UTC, vishh commented
@Amey-D PTAL

2017-06-08 21:02 UTC, Amey-D commented
/lgtm

2017-06-08 22:41 UTC, vishh commented
@dchen1107 mentioned that the `COS` base image versions tied to OSS k8s aren't expected to be updated frequently. Due to that restriction and the fact that the installer is currently tied to specific versions of COS, I decided to create a new copy of installation scripts in a [new github repo](https://github.com/ContainerEngine/accelerators)
This PR may not make it into K8s v1.7 and that's OK since the COS version for v1.7 is not expected to change.

2017-06-15 14:56 UTC, mindprince commented
This can be closed now.

2017-06-15 15:43 UTC, closed without merging