validate nonResourceURL in create clusterrole
kubernetes/kubernetes pull request #47171
Opened 2017-06-08 09:54 UTC by xilabao

**Release note**:

```release-note
NONE
```

2017-06-14 02:18 UTC, CaoShuFeng requested changes

2017-06-14 02:18 UTC, CaoShuFeng commented on pkg/kubectl/cmd/create_clusterrole.go
> +			if !strings.HasPrefix(nonResourceURL, "/") {
A single "*" is also allowed nonResourceURL.
But "*" is allowed in the tail, so this is invalid: /foo/*bar

2017-06-14 02:45 UTC, xilabao commented
/assign @liggitt
/cc @liggitt

2017-06-14 02:47 UTC, liggitt commented on pkg/kubectl/cmd/create_clusterrole.go
> +				return fmt.Errorf("invalid nonResourceURL: '%s'", nonResourceURL)
make the message a little more helpful (like "nonResourceURL should start with /")

2017-06-14 02:50 UTC, xilabao commented on pkg/kubectl/cmd/create_clusterrole.go
> +			if !strings.HasPrefix(nonResourceURL, "/") {
add validate of '*', does it neccesary to validate '/foo/*bar' ?
the server side doesn't validate the nonResourceURL, should we validate in the server side too? @liggitt

2017-06-14 02:53 UTC, liggitt commented on pkg/kubectl/cmd/create_clusterrole.go
> +			if !strings.HasPrefix(nonResourceURL, "/") {
no server side validation, just make sure there's no more than one `*` here, and if there is one, it is at the end

2017-06-14 03:16 UTC, xilabao commented
Done. PTAL

2017-06-14 03:21 UTC, CaoShuFeng commented on pkg/kubectl/cmd/create_clusterrole.go
> +			if count > 1 || (count == 1 && !strings.HasSuffix(nonResourceURL, "/*")) {
I think something like /logs/kube* is also allowed.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/audit/policy/checker.go#L123

2017-06-14 03:35 UTC, xilabao commented on pkg/kubectl/cmd/create_clusterrole.go
> +			if count > 1 || (count == 1 && !strings.HasSuffix(nonResourceURL, "/*")) {
fixed. thx

2017-06-23 09:22 UTC, CaoShuFeng commented on pkg/kubectl/cmd/create_clusterrole.go
> +			if count > 1 || (count == 1 && !strings.HasSuffix(nonResourceURL, "*")) {
nit: a better way of expressing line 147,148 would be
strings.ContainsRune(url[:len(url)-1], '*')

2017-08-11 16:10 UTC, xiangpengzhao commented
/ok-to-test

2017-08-18 04:54 UTC, liggitt commented on pkg/kubectl/cmd/create_clusterrole.go
> +				return fmt.Errorf("nonResourceURL not support more than one '*', and if there is one, it is at the end")
`nonResourceURL only supports wildcard matches when '*' is at the end`

2017-08-18 04:54 UTC, liggitt commented
nit on text, lgtm otherwise

2017-08-21 02:41 UTC, xilabao commented on pkg/kubectl/cmd/create_clusterrole.go
> +				return fmt.Errorf("nonResourceURL not support more than one '*', and if there is one, it is at the end")
updated. @liggitt PTAL

2017-08-25 06:04 UTC, liggitt commented
/lgtm

2017-08-25 06:04 UTC, liggitt commented
/approve no-issue

2017-08-25 19:31 UTC, merged