Fix cross-repo link
kubernetes/kubernetes pull request #47223
Opened 2017-06-09 06:08 UTC by sttts

Fixing https://github.com/kubernetes/kubernetes/issues/47211

2017-06-09 06:09 UTC, sttts commented
Not sure there is a better solution. The link must work inside of staging and in the client-go repo. Making in-project+cross-project links seems to be impossible.

2017-06-09 17:35 UTC, ahmetb commented
@sttts still 404 for me: https://github.com/kubernetes/apiextensions-apiserver/ Is this repo private?

2017-06-09 19:26 UTC, sttts commented
@ahmetb it doesn't exist yet ;-) Compare by kubernetes-dev mail from yesterday.

2017-06-09 20:50 UTC, cblecker requested changes

2017-06-09 20:50 UTC, cblecker commented on staging/src/k8s.io/client-go/examples/custom-resources/README.md
> +  [k8s.io/apiextensions-apiserver/examples/client-go](https://github.com/kubernetes/apiextensions-apiserver/tree/master/examples/client-go).
@thockin created https://git.k8s.io for stuff like this.
Try https://git.k8s.io/apiextentions-apiserver/examples/client-go

2017-06-09 21:00 UTC, ahmetb commented
This directory probably should not have been merged in the first place if it doesn't exist yet? 😕

2017-06-10 22:35 UTC, thockin commented on staging/src/k8s.io/client-go/examples/custom-resources/README.md
> +  [k8s.io/apiextensions-apiserver/examples/client-go](https://github.com/kubernetes/apiextensions-apiserver/tree/master/examples/client-go).
that's a dead link right now...

2017-06-12 07:40 UTC, sttts commented on staging/src/k8s.io/client-go/examples/custom-resources/README.md
> +  [k8s.io/apiextensions-apiserver/examples/client-go](https://github.com/kubernetes/apiextensions-apiserver/tree/master/examples/client-go).
done

2017-06-12 17:28 UTC, cblecker approved these changes
This looks good to me, except that `kubernetes/apiextensions-apiserver` is empty. Once there is content here, then this can be merged.

2017-06-12 17:35 UTC, sttts commented
Repo exists, but is still empty. @caesarxuchao is updating the bot now.

2017-06-16 20:39 UTC, spiffxp commented
/retest

2017-06-16 20:53 UTC, ahmetb commented
pull-kubernetes-federation-e2e-gce is flaky: #47672

2017-06-16 22:51 UTC, spiffxp commented
OK, there's content here https://github.com/kubernetes/apiextensions-apiserver
Going to lgtm based on @cblecker's review
/assign

2017-06-16 22:52 UTC, spiffxp commented
/lgtm

2017-06-16 23:13 UTC, merged

2017-06-19 19:05 UTC, nikhita commented on staging/src/k8s.io/client-go/examples/custom-resources/README.md
> +  [k8s.io/apiextensions-apiserver/examples/client-go](https://git.k8s.io/apiextentions-apiserver/examples/client-go).
s/apiextentions/apiextensions. fix in #47684