Validate if service has duplicate targetPort
kubernetes/kubernetes pull request #47284
Opened 2017-06-10 05:00 UTC by xiangpengzhao

**What this PR does / why we need it**:
Validate if a service has dup targetport

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47222

**Special notes for your reviewer**:
/cc @thockin 
@kubernetes/sig-network-pr-reviews

**Release note**:

```release-note
NONE
```

2017-06-10 05:07 UTC, odeke-em requested changes

2017-06-10 05:07 UTC, odeke-em commented on pkg/api/validation/validation.go
> +	for i := range service.Spec.Ports {
```go
for i, port := range service.Spec.Ports {
```

2017-06-10 05:07 UTC, odeke-em commented on pkg/api/validation/validation.go
> +		var key api.ServicePort
```go
key := api.ServicePort{TargetPort: port.TargetPort}
```

2017-06-10 05:08 UTC, odeke-em commented on pkg/api/validation/validation.go
> +	for i := range service.Spec.Ports {
That way you don't have to do the `port := &service.Spec.Ports[i]`

2017-06-10 07:43 UTC, xiangpengzhao commented
inline comments addressed. Thanks @odeke-em !

2017-06-10 09:02 UTC, feiskyer commented
@k8s-bot ok to test

2017-06-10 14:26 UTC, kargakis commented
@kubernetes/sig-network-api-reviews

2017-06-10 22:27 UTC, thockin reviewed
just a small point, then LGTM.

THANKS!!!

2017-06-10 22:27 UTC, thockin commented on pkg/api/validation/validation.go
> +	targetPorts := make(map[api.ServicePort]bool)
This should just be `map[intstr.IntOrString]bool` for obviousness reasons. or `struct{}` instead of bool.

2017-06-10 22:29 UTC, thockin commented
Tests fail because you're not special-casing the zero-value.  You should not de-dup number 0 or string ""
```
--- FAIL: TestServiceRegistryCreateMultiNodePortsService (0.00s)
	rest_test.go:230: Unexpected error: Service "foo1" is invalid: spec.ports[1].targetPort: Duplicate value: intstr.IntOrString{Type:0, IntVal:6503, StrVal:""}
FAIL
```

Assigning bowei to lgtm when done

/approve

2017-06-12 03:29 UTC, xiangpengzhao commented
zero-value issue addressed. But I don't think it's the cause of the test failure. The failure was because I take "same targetport with different protocols" as dup and invalid. We should take this as valid, right?

2017-06-12 03:31 UTC, xiangpengzhao commented on pkg/api/validation/validation.go
> +	targetPorts := make(map[api.ServicePort]bool)
We should also respect protocol, so I still use ServicePort here.

2017-06-12 03:32 UTC, xiangpengzhao commented
@thockin @bowei PTAL.

2017-06-12 04:20 UTC, thockin commented
/lgtm

2017-06-30 05:53 UTC, xiangpengzhao commented
/test pull-kubernetes-federation-e2e-gce

2017-06-30 08:28 UTC, xiangpengzhao commented
/test pull-kubernetes-federation-e2e-gce

2017-06-30 09:50 UTC, merged