[WIP] Added golint check for pkg/kubelet.
kubernetes/kubernetes pull request #47316
Opened 2017-06-12 02:05 UTC by k82cn

**What this PR does / why we need it**:
Added golint check for pkg/kubelet, and make golint happy.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47315 

**Release note**:
```release-note-none
```

2017-06-12 02:06 UTC, k82cn commented
WIP PR, I'll make golint happy in this PR :).

2017-06-12 02:43 UTC, ixdy commented
/unassign
/assign @k82cn 

Please reassign when this is ready for review.

2017-06-12 02:55 UTC, k82cn commented
sure, np :).

2017-06-12 03:25 UTC, cblecker commented
👍🏻👍🏻 to better code comments :)

2017-06-14 04:45 UTC, k82cn commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-14 05:48 UTC, k82cn commented
/assign @ixdy @fejta

2017-06-14 17:09 UTC, ixdy commented
`hack/` changes look fine.
/approve

We definitely should have a reviewer in `pkg/kubelet` look at this, though.
/unassign @ixdy @fejta @k82cn

2017-06-15 00:54 UTC, k82cn commented
/assign @shyamjvs @vishh

2017-06-15 01:05 UTC, k82cn commented
@kubernetes/sig-node-pr-reviews

2017-06-15 02:03 UTC, shyamjvs commented
/approve

2017-06-15 03:03 UTC, vishh commented on pkg/kubelet/reason_cache.go
> +type Reason struct {
Why is it public?

2017-06-15 07:07 UTC, k82cn commented on pkg/kubelet/reason_cache.go
> +type Reason struct {
golint report a warning that the `error` has to be the latest one of return value at https://github.com/kubernetes/kubernetes/pull/47316/files#diff-ade44c0052b07470763ef431d55210ceL95 .
Compare to moving `error` to the latest one (the latest return value indicates whether found reason in cache), so prefer to use an object as the result value.

2017-06-23 02:46 UTC, k82cn commented
ping for approve & lgtm :).

2017-06-27 00:54 UTC, k82cn commented
@vishh , do you have more comments?

2017-07-10 00:47 UTC, k82cn commented
/retest

2017-07-11 03:34 UTC, k82cn commented
/retest

2017-07-11 20:13 UTC, fejta commented
/test pull-kubernetes-e2e-kops-aws

2017-07-12 07:57 UTC, k82cn commented
@vishh , do you have more comments?

2017-07-12 15:49 UTC, yujuhong requested changes

2017-07-12 15:49 UTC, yujuhong commented on pkg/kubelet/kubelet.go
> +		ips = []net.IP{cfgAddress}
This line should only be run if `cfgAddress == nil || cfgAddress.IsUnspecified()` is not true. Now it always runs regardless.

2017-07-12 15:49 UTC, yujuhong commented on pkg/kubelet/reason_cache.go
> +type Reason struct {
You still don't need to export `Reason` since it's only used in this package, right?

2017-07-19 03:33 UTC, k82cn commented on pkg/kubelet/kubelet.go
> +		ips = []net.IP{cfgAddress}
wow, good catch :), thanks very much.

2017-07-19 03:34 UTC, k82cn commented on pkg/kubelet/reason_cache.go
> +type Reason struct {
agree, renamed to `reasonItem` (reason is used by other var).

2017-07-19 16:21 UTC, yujuhong approved these changes

2017-07-19 16:22 UTC, yujuhong commented
/lgtm

Thanks for cleaning this up!

2017-07-19 18:21 UTC, merged