Validate if service has duplicate port
kubernetes/kubernetes pull request #47336
Opened 2017-06-12 11:41 UTC by xiangpengzhao

**What this PR does / why we need it**:
Validate if a service has duplicate Spec.Ports.Port (same number with same protocol)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: partially fixes #47221 
fixes this part: 
>It is possible to express a Service with multiple ports blocks with the same number. This is not very useful and may cause trouble for implementations of Services.

**Special notes for your reviewer**:
/cc @thockin @liggitt @mengqiy 
@kubernetes/sig-network-pr-reviews

**Release note**:

```release-note
NONE
```

2017-06-30 14:59 UTC, pmichali requested changes
Looks good overall. Just wondering if additional coverage should be added.

2017-06-30 14:59 UTC, pmichali commented on pkg/api/validation/validation_test.go
> +		{
Should you have a test case with port==0 to cover that case?

2017-06-30 17:00 UTC, mengqiy commented on pkg/api/validation/validation.go
> +			allErrs = append(allErrs, field.Duplicate(portPath.Child("port"), port.Port))
This error message may be misleading, since it only talks about `port`. We should include protocol as well.

2017-06-30 17:00 UTC, mengqiy commented on pkg/api/validation/validation.go
> +		if port.Port == 0 {
why we treat port 0 differently?

2017-07-02 15:59 UTC, xiangpengzhao commented on pkg/api/validation/validation.go
> +		if port.Port == 0 {
I thought port can be unspecified. That's incorrect. Thanks for pointing this out!

2017-07-02 15:59 UTC, xiangpengzhao commented on pkg/api/validation/validation.go
> +			allErrs = append(allErrs, field.Duplicate(portPath.Child("port"), port.Port))
Good point! Will fix.

2017-07-02 15:59 UTC, xiangpengzhao commented on pkg/api/validation/validation_test.go
> +		{
will remove the port==0 case as per @mengqiy comment.

2017-07-04 01:49 UTC, xiangpengzhao commented
inline comments addressed. PTAL.

2017-07-05 22:38 UTC, mengqiy commented
/ok-to-test

2017-07-06 02:12 UTC, xiangpengzhao commented
/retest

2017-07-25 02:59 UTC, xiangpengzhao commented
@ping @liggitt and @derekwaynecarr for reviewing 
and 
/assign @thockin 
for approval

thanks!

2017-08-01 02:38 UTC, liggitt commented on pkg/api/validation/validation.go
> +			allErrs = append(allErrs, field.Duplicate(portPath.Child("port"), port.Port))
I'm not sure two errors make sense either... a single error that included both the protocol and the port number is what I would expect - `field.Duplicate(portPath, key)`

2017-08-01 05:49 UTC, xiangpengzhao commented
Thanks @liggitt ! Inline comment addressed. PTAL.

2017-08-01 07:55 UTC, xiangpengzhao commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-01 08:18 UTC, xiangpengzhao commented
/test pull-kubernetes-e2e-kops-aws

2017-08-01 15:42 UTC, thockin commented
/lgtm
/approve

2017-08-01 15:52 UTC, xiangpengzhao commented
/retest

2017-08-01 21:31 UTC, merged