Adds IPv6 test cases for kubeadm certs.
kubernetes/kubernetes pull request #47480
Opened 2017-06-14 01:22 UTC by danehans

**What this PR does / why we need it**:
Adds IPv6 test cases in support of kubeadm certificate functionality. It's needed to ensure test cases cover IPv6 related networking scenarios.

**Which issue this PR fixes**
This PR is in support of Issue #1443

**Special notes for your reviewer**:
Additional PR's will follow to ensure kubeadm supports IPv6.

**Release note**:
```NONE
```

2017-06-14 01:22 UTC, danehans commented
/area ipv6

2017-06-14 16:06 UTC, danehans commented
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

2017-06-20 11:35 UTC, pmichali requested changes
Looks like thorough additions to the tests. Requesting that we improve them to make debugging failures easier.

2017-06-20 11:35 UTC, pmichali commented on cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
> +		{"", false},               // not valid
Coverage looks great. My main nit is that, when a failure occurs, there is no way to tell which one of the test cases has failed (a problem with the original code). Suggest either displaying the "ip" field, or add a "name" field, which could indicate what is being tested specifically (e.g. no IP, # too large, too short, including mask, ...).

2017-06-20 11:35 UTC, pmichali commented on cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
> +		{"16.0.1.1", true},        // valid
What condition is this testing, that is not tested by L131? Seems like a duplicate test in the original code.

2017-06-20 11:35 UTC, pmichali commented on cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
> +		{"", 0, false},                // not valid
Same comment about difficulty in tracking what test failed.

2017-06-20 11:35 UTC, pmichali commented on cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
> +				ServiceSubnet: "2001:db8::1/98",
Ditto here. Would be best served by a name field, IMHO, where you could indicate things like "missing token".

2017-06-20 11:35 UTC, pmichali commented on cmd/kubeadm/app/phases/certs/certs_test.go
> +			// IPv4 CIDR too short
The comments could be used in a new "name" field, to identify the test and make it more self documenting.

2017-06-20 11:35 UTC, pmichali commented on cmd/kubeadm/app/phases/certs/certs_test.go
> +			// IPv4 equal
Ditto with test names.

2017-06-20 11:35 UTC, pmichali commented on cmd/kubeadm/app/phases/certs/certs_test.go
> +			expectedDNSNames: []string{"my-node", "kubernetes", "kubernetes.default", "kubernetes.default.svc", "kubernetes.default.svc.cluster.external", "foo", "bar.baz"},
Same here, even though the Errorf() shows the expected values and not true/false, both test cases have the same expected DNS names, so it's hard to tell the failing test.

2017-06-20 15:47 UTC, danehans commented
/test pull-kubernetes-e2e-gce-etcd3

2017-06-23 23:13 UTC, danehans commented on cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
> +		{"16.0.1.1", true},        // valid
It's the same test. The only reason changes to the original test cases appear is b/c comments have been further indented.

2017-06-26 12:11 UTC, pmichali commented on cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
> +		{"16.0.1.1", true},        // valid
Right, but question is... do we need both L131 and L132 (in original test)? What different condition is being tested?

2017-07-07 08:08 UTC, luxas commented
@pmichali Ping me when this looks good to you and I'll take a look

2017-07-07 12:38 UTC, pmichali commented
@luxas I'll re-review, once @danehans addresses the comments from the most recent commit. Since we are touching this code, it is a good time to address issues with the test failure output. Right now, there is no way to tell what test case has failed.

2017-07-24 21:56 UTC, luxas commented
ping @danehans

2017-07-26 15:23 UTC, danehans commented
@luxas sorry for the delay. I'm having problems running unit tests, even ones unassociated to my PR. I'm hoping to have the unit test issue resolved today.

2017-08-02 10:56 UTC, pmichali commented
@danehans Can you rebase and update the tests?

2017-08-15 17:33 UTC, danehans commented on cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
> +		{"16.0.1.1", true},        // valid
Go it. That is correct, we do not need the `{"1.2.3.4", true}` and `{"1.2.3.4", true}` tests. I will remove the `{"1.2.3.4", true}`.

2017-08-15 17:36 UTC, danehans commented on cmd/kubeadm/app/phases/certs/certs_test.go
> +			// IPv4 CIDR too short
I'll add a name field to this test case struct too.

2017-08-15 22:18 UTC, danehans commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-16 11:16 UTC, pmichali commented
/lgtm

2017-08-16 12:19 UTC, luxas approved these changes
/approve

Approving as @pmichali also has LGTM'd it

2017-08-16 13:27 UTC, merged