Allow UDP for kubectl create service.
kubernetes/kubernetes pull request #47485
Opened 2017-06-14 03:14 UTC by sandoracs

**What this PR does / why we need it**:
TCP is hardcoded in 'kubectl create service' however UDP should be supported too.
**Which issue this PR fixes**: 
fixes #47337

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-06-14 10:02 UTC, CaoShuFeng commented
I personally prefer adding a new --udp. Because this break backword compatibility.

2017-06-14 10:46 UTC, sandoracs commented
I see. I can rewrite to use '--udp' if it is the preferred way.

2017-06-14 14:05 UTC, xiangpengzhao commented
Glad to see this PR! Thanks @sandoracs !
TBH, I prefer the `--port` implementation in this PR and we'd better also mark `--tcp` as deprecated in order not to break compatibility.

@thockin WDYT?

2017-06-14 14:25 UTC, xiangpengzhao requested changes

2017-06-14 14:25 UTC, xiangpengzhao commented on pkg/kubectl/cmd/create_service_test.go
> +	cmd.Flags().Set("ports", "tcp:8080:8000")
refactor the test case to table-driven tests for testing multiple scenarios (tcp/udp/invalid) ?

2017-06-14 14:25 UTC, xiangpengzhao commented on pkg/kubectl/cmd/create_service.go
> -	cmd.Flags().StringSlice("tcp", []string{}, "Port pairs can be specified as '<port>:<targetPort>'.")
mark flag `tcp` as deprecated instead of removing it.

2017-06-14 14:25 UTC, xiangpengzhao commented on pkg/kubectl/service_basic.go
> +		portName := strings.Replace(portsString[separatorPos+1:], ":", "-", -1)
since we support specifying protocol, it'd be good to put protocol into the port name.

2017-06-14 14:28 UTC, sandoracs commented
Thank you! I will work on it.

2017-06-14 15:25 UTC, sandoracs commented on pkg/kubectl/service_basic.go
> +		portName := strings.Replace(portsString[separatorPos+1:], ":", "-", -1)
so you suggest to remove protocol field from ServicePort struct?

2017-06-14 15:31 UTC, xiangpengzhao commented on pkg/kubectl/service_basic.go
> +		portName := strings.Replace(portsString[separatorPos+1:], ":", "-", -1)
nope. I meant we might want to generate portName as `protocol-port-targetPort`, e.g. `tcp-456-9898`.

2017-06-17 11:05 UTC, sandoracs commented
I've found an issue (https://github.com/kubernetes/kubectl/issues/35), which currently breaks testing.

2017-07-18 23:27 UTC, xiangpengzhao commented
/keep-open

2017-08-10 10:48 UTC, xiangpengzhao commented
Hi @sandoracs , are you still working on this?

2017-11-08 21:34 UTC, closed without merging