update HostAliases' json keys to be hostAlias instead of hostMapping
kubernetes/kubernetes pull request #47512
Opened 2017-06-14 10:40 UTC by rickypai

**What this PR does / why we need it**: a rename was introduce during the middle of #44641 to change from `hostMappings` to `hostAliases`. the Go structs were updated, but I neglected to update the json keys. They should be in sync.

**Special notes for your reviewer**:  I messed up. This is an API change. I hope this is still ok to be in the 1.7 release.

**Release note**:
```release-note
HostAliases should now be parsed with `hostAliases` json keys as originally intended.
```

2017-06-14 10:41 UTC, rickypai commented
@kubernetes/kubernetes-release-managers this is an API change

2017-06-14 10:41 UTC, rickypai commented
/assign @thockin

2017-06-15 01:09 UTC, cblecker requested changes

2017-06-15 01:09 UTC, cblecker commented on api/openapi-spec/swagger.json
> +   "version": "v1.4.0"
Why is this changing? It shouldn't.

2017-06-15 01:09 UTC, cblecker commented on federation/apis/openapi-spec/swagger.json
> +   "version": "v1.4.0"
Same here

2017-06-15 01:17 UTC, nikhiljindal commented
@k8s-bot ok to test.

Keeping actual changes and autogenerated changes in different commits makes it easier to review.
This is an API change so it will break existing users.

Will let Tim do the review.

2017-06-15 03:10 UTC, liggitt commented on pkg/api/v1/types.go
> +	HostAliases []HostAlias `json:"hostAliases,omitempty" patchStrategy:"merge" patchMergeKey:"IP" protobuf:"bytes,23,rep,name=hostAliases"`
should the patch merge key should be lowercase `ip` as well?

2017-06-15 17:42 UTC, rickypai commented on api/openapi-spec/swagger.json
> +   "version": "v1.4.0"
not sure. i ran this on a new development environment. will manually remove the change

2017-06-15 17:49 UTC, rickypai commented on federation/apis/openapi-spec/swagger.json
> +   "version": "v1.4.0"
fixed

2017-06-15 17:49 UTC, rickypai commented on pkg/api/v1/types.go
> +	HostAliases []HostAlias `json:"hostAliases,omitempty" patchStrategy:"merge" patchMergeKey:"IP" protobuf:"bytes,23,rep,name=hostAliases"`
thanks for catching this also!

2017-06-20 20:49 UTC, cblecker commented
@k8s-bot ok to test

2017-06-20 21:02 UTC, dchen1107 commented
@erictune I am assigning this to you since @thockin is out. Please let me know you couldn't review this. Thanks!

cc/ @kubernetes/api-reviewers

2017-06-20 22:26 UTC, erictune approved these changes

2017-06-20 22:45 UTC, rickypai commented
thank you!

2017-06-20 23:15 UTC, rickypai commented
/test pull-kubernetes-federation-e2e-gce

2017-06-21 05:02 UTC, rickypai commented
@erictune I think you need to explicitly /lgtm this PR or else it won't be picked up by submit queue.

thanks a lot!

2017-06-21 19:18 UTC, dchen1107 commented
/lgtm

2017-06-21 22:34 UTC, rickypai commented
recent merge introduced conficts in the generated protobuf files. rebased and regenerating the files.

2017-06-21 23:46 UTC, caesarxuchao commented
Thanks for the rebasing. lgtm.

2017-06-22 01:05 UTC, smarterclayton commented
@caesarxuchao we should probably open an issue in 1.8 to track API changes and make sure they conform to conventions.

2017-06-22 01:23 UTC, caesarxuchao commented
> we should probably open an issue in 1.8 to track API changes and make sure they conform to conventions.

@mbohlool i heard you had started an API convention checker?

2017-06-22 01:27 UTC, rickypai commented
API convention checker would be nice. i was also thinking requiring e2e test for every API change to mitigate mistakes like this

2017-06-22 04:14 UTC, caesarxuchao commented
Adding queue/blocks-others because it's blocking lifting code freeze.

2017-06-22 04:29 UTC, rickypai commented
thanks and sorry that this is blocking folks :(

2017-06-22 05:13 UTC, merged

2017-06-22 05:26 UTC, rickypai commented
yay!

2017-06-22 20:50 UTC, mbohlool commented
> we should probably open an issue in 1.8 to track API changes and make sure they conform to conventions.
> @mbohlool i heard you had started an API convention checker?

#44005