WIP: chinese for kubectl translate
kubernetes/kubernetes pull request #47584
Opened 2017-06-15 09:33 UTC by zjj2wry

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-06-15 09:36 UTC, zjj2wry commented
@brendandburns maybe ```hack/update-translations.sh``` need  do in docker ?

2017-06-15 09:38 UTC, zjj2wry commented
@shiywang hey, the translate work maybe not complete. did you have interest continue or help review？

2017-06-15 10:08 UTC, zhangxiaoyu-zidif requested changes

2017-06-15 10:08 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "修改 kubeconfig 文件中的一个上下文名称"
上下文 能否换个词，很奇怪。
或者直接参考 zh_TW中的翻译，直接就是context

2017-06-15 10:20 UTC, shiywang commented
@zjj2wry sorry, I don't have time working on this right now : )

2017-06-15 10:33 UTC, zjj2wry commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "修改 kubeconfig 文件中的一个上下文名称"
嗯嗯，关键字保留可能更好，WDYT? @shiywang

2017-06-15 10:34 UTC, zjj2wry commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "修改 kubeconfig 文件中的一个上下文名称"
@zhangxiaoyu-zidif 你有没有兴趣一起翻译？

2017-06-15 11:57 UTC, dims commented
/unassign

2017-06-17 06:02 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +msgstr "修改 kubeconfig 文件中的一个上下文名称"
It is hard to refuse a request from a girl. :)

2017-09-03 20:07 UTC, zjj2wry commented
@xiangpengzhao @shiywang @zhangxiaoyu-zidif hey, i will compele this recently. and i will appreciate if you can help review :)

2017-09-05 05:30 UTC, zjj2wry commented
/ok-to-test

2017-09-05 05:41 UTC, zhangxiaoyu-zidif commented
@xiangpengzhao 
would you mind adding ok-to-test?

2017-09-05 05:49 UTC, xiangpengzhao commented
/ok-to-test

2017-09-24 15:27 UTC, zjj2wry commented
/retest

2017-09-26 03:05 UTC, zjj2wry commented
/test pull-kubernetes-e2e-gce-etcd3

2017-09-26 15:13 UTC, zjj2wry commented
/assign @zhangxiaoyu-zidif @xiangpengzhao @shiywang

2017-09-27 08:38 UTC, zjj2wry commented
/test pull-kubernetes-e2e-kops-aws

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t  # 创建一个 名称为 my-config 的 configmap 并指定 keys 而不是使用磁盘上所在的文件名\n"
多了一个空格

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t  # 创建一个 名称为 my-config 的 configmap 并指定 keys 而不是使用磁盘上所在的文件名\n"
创建一个 名称为
->
创建一个名称为

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t  # 通过目录 bar 创建一个名称为 my-config 的 configmap\n"
目录
->
文件夹

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# 将 ’pod.yaml' 转换为最新版本并打印到 stdout.\n"
’pod.yaml'
这个是中英文标点混用？

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# 将 ‘pod.yaml' 指定的资源的实时状态转换为最新版本\n"
’pod.yaml'
这个是中英文标点混用？

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# 创建一个名为 \"pod-reader\" 的 ClusterRole, 允许用户在 pods 上执行 “get\", \"watch\" 和 “list\"\n"
“get\", \"watch\" 和 “list\"\n"
标点混用？

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# Describe 一个 node\n"
这里被误修改了？

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# 清理节点 \"foo\", 即使很多 pods 没有被一个在 node 上的 ReplicationController, ReplicaSet, Job, DaemonSet 或者 StatefulSet 管理.\n"
这个drain，是不是‘’驱逐‘’更合适？@tenqm

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# Get output from ruby-container from pod 123456-7890\n"
遗漏了?未翻译

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# 显示所有的 replication controllers 和 services 并格式化 输出.\n"
并格式化 输出
->
并格式化输出

2017-10-20 06:35 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\t# 在本地监听端口 5000 和 6000 , forwarding 数据 to/from 在 pod 5000 和 6000 端口上n\t\tkubectl port-forward mypod 5000 6000\n"
这个是误翻译吗？
这是id的位置

2017-11-10 09:45 UTC, zjj2wry commented
@zhangxiaoyu-zidif thank you review this, updated. ptal

2017-11-11 00:31 UTC, zjj2wry commented
/test pull-kubernetes-unit
/test pull-kubernetes-e2e-gce

2017-11-11 08:05 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\tThe edit comm
Those lines are not translated？

2017-11-11 08:07 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\tThe edit comm
Do you prepare to translate them later in other PR?

2017-11-11 08:08 UTC, zhangxiaoyu-zidif commented on translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
> +"\t\tThe edit comm
current-context ?

2017-11-11 08:19 UTC, zhangxiaoyu-zidif commented
It's really a huge PR.
From CN translation viewpoint it deserves a LGTM label.
I do not know this PR containing some untranslated lines, is that OK to merge.
But for translated part, that looks good to me.
Thanks for your contributions ! @zjj2wry

2017-11-11 11:21 UTC, zjj2wry commented
plan create another PR translate some new command. when chinese coverage majority command, we will have more volunteer for contributor and reviewer : )

@zhangxiaoyu-zidif thank you review this, ptal
/assign @brendanburns for approve, thanks

2017-11-13 01:32 UTC, zhangxiaoyu-zidif approved these changes

2017-11-13 01:32 UTC, zhangxiaoyu-zidif commented
/lgtm from me

2017-11-13 02:39 UTC, zjj2wry commented
/assign @brendandburns

2017-11-15 01:38 UTC, brendandburns commented
/lgtm
/approve

2017-11-15 01:38 UTC, brendandburns commented
/approve no-issue

2017-11-15 05:35 UTC, DiamondYuan commented
/approve

2017-11-16 07:57 UTC, merged