Adding proxier test that uses "iptables-restore --test" to validate i…
kubernetes/kubernetes pull request #47662
Opened 2017-06-16 15:58 UTC by yuval-k

…ptables rules.

fixes kubernetes/kubernetes/#36850

**What this PR does / why we need it**:
This PR tests iptable rules of the proxier on a live node, to make sure they are syntactically valid.

**Which issue this PR fixes**: 

fixes #36850

**Special notes for your reviewer**:

**Release note**:

```release-note
Adding an e2e test to test the iptables proxier tools
```

2017-06-16 16:06 UTC, yuval-k commented
as far as i know the CLA should be signed.. i'm checking this right now..

2017-06-19 11:13 UTC, deads2k commented
@thockin or @eparis maybe

2017-06-28 20:06 UTC, yuval-k commented
CLA signed

2017-07-20 17:28 UTC, cmluciano commented
@k8s-bot ok to test

2017-07-21 11:42 UTC, yuval-k commented
working on this

2017-07-27 03:25 UTC, dcbw commented on test/e2e/proxier.go
> +			makeTestService(svcPortName.Namespace, svcPortName.Name, func(svc *api.Service) {
Might be nice to see the other Service types (LoadBalancer, NodePort, etc) also get tested.  I don't think that would be a bunch of work, but I could be wrong.

2017-07-27 03:28 UTC, dcbw requested changes

2017-07-27 03:28 UTC, dcbw commented on pkg/ssh/ssh.go
> +func runSSHCommand(dialer sshDialer, cmd, user, host string, input io.Reader, signer ssh.Signer, retry bool) (string, string, int, error) {
You'll need to update pkg/ssh/ssh_test.go as well, this is why the bazel and verify tests are failing:

```
W0720 17:30:18.719] Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
I0720 17:30:18.819] pkg/ssh/ssh_test.go:307: not enough arguments in call to runSSHCommand
I0720 17:30:18.820] 	have (*mockSSHDialer, string, string, string, ssh.Signer, bool)
I0720 17:30:18.821] 	want (sshDialer, string, string, string, io.Reader, ssh.Signer, bool)
W0720 17:30:20.296] ____Building complete.
```

2017-07-27 03:29 UTC, dcbw commented
The verify test failed on the bazel updates as well, either run:

`hack/update-bazel.sh`

or if you do per-project GOPATHs (or just rely on the automatic GOPATH in the kube make scripts) you can:

`docker run -it -v $(pwd):/go/src/k8s.io/kubernetes -w /go/src/k8s.io/kubernetes golang:1.8 /bin/bash -c "hack/update-bazel.sh"`

2017-08-02 20:16 UTC, cmluciano commented
@yuval-k Need anymore input from us on this?

2017-10-20 19:22 UTC, cmluciano commented
cc @dougbtv would you be interested in carrying this PR forward?

2017-10-20 19:25 UTC, dougbtv commented
Absolutely, I'll take a look thanks @cmluciano !

2017-10-31 18:07 UTC, dougbtv commented
@cmluciano -- tl;dr -- Where I could use some help is -- how should I submit these changes? Should I create a new pull request with my fork of these changes? I'll happily take any advice here. Thanks!!

The whole story...

I've been able to create some fixes to this PR so that it passes the bazel build (at least `make bazel-build` exits 0 and doesn't otherwise complain) -- you'll see that there's a commit from my fork that references this issue, and available in that reference here.

In short, the basics for the fix were to: 

* Update moved `k8s.io/kubernetes/pkg/util/exec` to `k8s.io/utils/exec/testing`
* Update `ssh_test.go` to add parameter when calling `RunSSHCommand(...)`

Also, I had to rebase the commit to account for other changes elsewhere in the codebase to get the bazel builds to complete (e.g. there were [mismatched checksums when I ran bazel](http://pasteall.org/644069))

2017-10-31 19:29 UTC, cmluciano commented
@dougbtv Yep, we can close this PR and refer to your new PR with the fixes. Thanks!

2017-11-01 13:45 UTC, cmluciano commented
/close

commits included in #54884

2017-11-01 13:45 UTC, closed without merging