Output TYPE for getting service
kubernetes/kubernetes pull request #47694
Opened 2017-06-17 06:17 UTC by FengyunPan

**What this PR does / why we need it**:
Now service already supported 4 ServiceTypes, ServiceTypes is
friendly to distinguish services, so outputing service type better
when running 'kubectl get service'.

**Release note**:
```release-note
  NONE
```

2017-06-17 07:00 UTC, xiangpengzhao requested changes

2017-06-17 07:00 UTC, xiangpengzhao commented on pkg/printers/internalversion/printers_test.go
> +			"test2\tNodePort\t10.9.8.7\t<nodes>\t8888:9999/tcp\t<unknown>\n",
nodes?

2017-06-17 07:00 UTC, xiangpengzhao commented on pkg/printers/internalversion/printers_test.go
>  					ClusterIP: "0.0.0.0",
in fact, this is not a valid Cluster IP. since you are here, can you modify it?

2017-06-17 09:28 UTC, FengyunPan commented on pkg/printers/internalversion/printers_test.go
>  					ClusterIP: "0.0.0.0",
Ok, Done.

2017-06-17 09:34 UTC, FengyunPan commented on pkg/printers/internalversion/printers_test.go
> +			"test2\tNodePort\t10.9.8.7\t<nodes>\t8888:9999/tcp\t<unknown>\n",
Yes, I have run unit test.

2017-06-17 09:47 UTC, xiangpengzhao commented on pkg/printers/internalversion/printers_test.go
> +			"test2\tNodePort\t10.9.8.7\t<nodes>\t8888:9999/tcp\t<unknown>\n",
Why is it not `<none>` but `<nodes>`? I don't think `<nodes>` is a right and meaningful output here.

2017-06-17 09:56 UTC, FengyunPan commented on pkg/printers/internalversion/printers_test.go
> +			"test2\tNodePort\t10.9.8.7\t<nodes>\t8888:9999/tcp\t<unknown>\n",
I see. I update it soon.

2017-06-18 01:43 UTC, dims commented
@k8s-bot ok to test

2017-06-19 01:06 UTC, dims commented
/assign @fabianofranz 
/unassign

2017-06-19 18:48 UTC, fabianofranz commented
/lgtm
/approve no-issue

2017-06-23 13:03 UTC, FengyunPan commented
/test pull-kubernetes-e2e-gce-etcd3

2017-06-23 15:29 UTC, merged