Adds merge command
kubernetes/kubernetes pull request #47730
Opened 2017-06-19 14:51 UTC by henriquetruta

Adds command that, given source and target kubeconfig
files, merge the contents of a source into the target.

Fixes https://github.com/kubernetes/kubernetes/issues/46381 

**Release note**:

```release-note
kubectl merge command - merge the contents of a given source kubeconfig file into a given target file.
```

2017-06-29 17:02 UTC, mengqiy commented
/ok-to-test

2017-06-29 19:01 UTC, kargakis commented
cc: @kubernetes/sig-api-machinery-pr-reviews

2017-07-03 09:01 UTC, sttts commented on pkg/kubectl/cmd/config/merge_configs.go
> +		files, this entry is ignored.`)
s/is ignored/of the target file is preserved/

2017-07-03 09:05 UTC, sttts commented on pkg/kubectl/cmd/config/merge_configs.go
> +		Merges kubecontext files
<bikeshed>`merge` sounds symmetric. `import` would probably be more appropriate</bikeshed>.

2017-07-03 13:37 UTC, henriquetruta commented on pkg/kubectl/cmd/config/merge_configs.go
> +		files, this entry is ignored.`)
done

2017-07-03 13:38 UTC, henriquetruta commented on pkg/kubectl/cmd/config/merge_configs.go
> +		Merges kubecontext files
liked the suggestion. Will apply. Thanks

2017-07-03 15:03 UTC, sttts commented
/cc @kubernetes/sig-cli-maintainers

2017-07-13 00:37 UTC, mengqiy commented
/assign @shiywang @alexandercampbell 
Do you have bandwidth to review this?

2017-07-13 21:05 UTC, alexandercampbell commented
@mengqiy yep, I'm doing CRs this afternoon.

2017-07-13 21:18 UTC, alexandercampbell requested changes
The code looks mostly fine. My biggest concern is: is it a good idea to add this feature in this way? I'll defer to @bgrant0607.

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs.go
> +	return (len(config.Clusters) == 0) && len(config.Contexts) == 0 && len(config.AuthInfos) == 0
You've got some redundant parens here on the first len check.

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs_test.go
> +			fmt.Sprintf("Copied cluster entry %q to target file.", "federatedkube")},
Why not just put the string literal in here?

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs_test.go
> +			t.Errorf("Did not get %v", test.expectedErr)
I might clarify this string: `"Expected error %v but no error was returned."`

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs_test.go
> +		return
Why the return?

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs.go
> +	cmd.Flags().String("target", "", "the file that will receive the entries. Defaults to the regular kubeconfig file")
If this defaults to the "regular kubeconfig" file, then why is the default a blank string?

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs.go
> +func (o ImportConfigsOptions) RunImportConfigs(out io.Writer) error {
I think this method is just supposed to be called "Run"

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs.go
> +	o.target = ""
You don't need this line.

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs.go
> +		cmd.Help()
I don't think help should be printed here. It's inconsistent with the other commands.

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs.go
> +		return fmt.Errorf("Unexpected args: %v", args)
I think this error message might be clearer if it read: `"import source expects only one argument"`

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs_test.go
> +	targetContextName = "target-context"
Might be worth throwing quick comments on these constants.

2017-07-13 21:18 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs_test.go
> +func (test importConfigsTest) run(t *testing.T) {
I would move this method definition next to the struct definition.

2017-07-13 21:28 UTC, lavalamp commented
> My biggest concern is: is it a good idea to add this feature in this way? I'll defer to @bgrant0607.

@pwittrock Do you think this is a good idea?

2017-07-14 19:26 UTC, fabianofranz commented
I didn't check here how you decided to implement the solution for naming conflicts, but I have the same concerns expressed [here](https://github.com/kubernetes/kubernetes/pull/38861#issuecomment-273865070). 

The outcome of running a command like this on sets of large config files is hard to understand/predict so I suggest to adopt the most conservative approach possible. E.g. in case of any naming conflict or "suspicious" merging (e.g a context with cluster from one file and credentials from another), error out and do nothing.

2017-08-09 14:56 UTC, henriquetruta reviewed
@fabianofranz thanks for the comment. I haven't considered the "suspicious" merging. I'll treat it in my next commit. Don't you think it's worth to merge all 'safe' entries? i.e. ignore the ones with any issue and apply the ones that are safe. Not the most conservative approach, but seems enough for me

2017-08-09 17:41 UTC, liggitt commented
is this the equivalent of `kubectl config view --raw` with multiple kubeconfig files specified?

`KUBECONFIG=file1:file2 kubectl config view --raw`

2017-08-09 17:48 UTC, henriquetruta commented
@liggitt It is similar, except that I don't expect that `view --raw` deals with naming conflicts somehow

2017-08-09 17:52 UTC, liggitt commented
dealing with naming conflicts differently than the merging logic that is actually applied when you combine files doesn't seem like a good idea

2017-08-09 19:18 UTC, henriquetruta commented
@liggitt just made some tests here. Copied a file into kube1 and kube2 files. Then, changed some entries values on kube2, like cluster IP and user passwords and ran:
```
export KUBECONFIG=kube1:kube2
k config view [--raw]
```

In this case, I see only the values of kube1. A similar behaviour to the one I adopted

2017-08-09 19:33 UTC, liggitt commented
> A similar behaviour to the one I adopted

Similar, but implemented separately. We should have a single implementation.

2017-08-09 23:31 UTC, alexandercampbell commented on pkg/kubectl/cmd/config/import_configs.go
> +func (o ImportConfigsOptions) RunImportConfigs(out io.Writer) error {
Gotcha. Thanks.

2017-11-08 08:12 UTC, closed without merging