Get rid of 30s ResyncPeriod in endpoint controller
kubernetes/kubernetes pull request #47788
Opened 2017-06-20 14:32 UTC by shyamjvs

Ref: #47597 
This should fix one of the demons of endpoint controller.

/cc @smarterclayton @gmarek

2017-06-20 14:34 UTC, shyamjvs commented
cc @jsravn

2017-06-20 14:59 UTC, seh requested changes

2017-06-20 14:59 UTC, seh commented on pkg/controller/endpoint/endpoints_controller.go
> +	// If we reached here it means the pod was deleted but it's final state is unrecorded.
- [ ] s/it's/its/

2017-06-20 14:59 UTC, seh commented on pkg/controller/endpoint/endpoints_controller.go
> +		utilruntime.HandleError(fmt.Errorf("Tombstone contained object that is not a Pod %#v", obj))
- [ ] s/a Pod /a Pod: /  
  (Add an intervening colon.)

2017-06-20 15:06 UTC, shyamjvs commented on pkg/controller/endpoint/endpoints_controller.go
> +	// If we reached here it means the pod was deleted but it's final state is unrecorded.
Done.

2017-06-20 15:06 UTC, shyamjvs commented on pkg/controller/endpoint/endpoints_controller.go
> +		utilruntime.HandleError(fmt.Errorf("Tombstone contained object that is not a Pod %#v", obj))
Done.

2017-06-20 15:14 UTC, shyamjvs commented
/test pull-kubernetes-bazel
(seems unrelated)

2017-06-20 15:34 UTC, seh approved these changes
Thanks for addressing those nits.

It's not clear to me how to remove my earlier objection in a GitHub review without approving the change. I defer to @smarterclayton and @gmarek to review the change as well.

2017-06-20 15:56 UTC, shyamjvs commented
I'm adding v1.7 milestone. Feel free to remove if you have a good reason.

2017-06-20 20:45 UTC, jsravn commented
@shyamjvs I think with moving to using the endpoints informer, the resync is much less of a problem. It will basically just be CPU overhead now.

2017-06-20 23:48 UTC, smarterclayton commented
A proper informer driven controller should never need to resync unless it
deals with external "non-informer" data.  So any change to use informers
should work without a 30s resync, and we should increase the resync to
ensure we aren't broken without it.

On Jun 20, 2017, at 11:57 AM, Shyam JVS <notifications@github.com> wrote:

I'm adding v1.7 milestone. Feel free to remove if you have a good reason.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/47788#issuecomment-309804729>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ABG_pyfWZTChyUvoYlFr8j0vXd8W87kSks5sF-vVgaJpZM4N_rG6>
.

2017-06-21 00:18 UTC, seh commented
@smarterclayton, for a controller that creates Kubernetes objects, should it react to changes in those same objects it creates? Ideally we'd like to detect when some other agent tampered with the objects this controller creates (and maintains) and correct them if they differ from our intended state, but then we'll wind up reacting to this controller's own changes too. Is there a way around that reacting to and inspecting of your own induced changes, or do you consider that to be a worthwhile tax that's too hard to avoid?

I ask because I'm working on a controller of my own that faces this same conundrum. It creates, modifies, and deletes _ResourceQuota_ objects, and those objects change frequently (the admission control plugin changes the status, at least) as other objects get created and deleted. If my controller watches _ResourceQuota_ objects, I'll be reacting both to my own controller's changes and those to the status, neither of which I care about. What do you say there? Watch them, or don't watch them?

2017-06-21 03:33 UTC, smarterclayton commented
I think this is important, but not quite important enough to risk release over.  We could consider a cherry-pick post release if this goes smoothly in master and we get good soak time on it.

@kubernetes/release-reviewers

2017-06-21 08:19 UTC, shyamjvs commented
@liggitt @wojtek-t fyi

2017-06-23 09:33 UTC, gmarek commented
/lgtm

2017-06-23 09:53 UTC, mikedanese commented
Get rid of it entirely? Why not just make it really big?

2017-06-23 09:55 UTC, gmarek commented
Get rid entirely. We don't have it anywhere else (or rather we should not have it anywhere else).

2017-06-23 10:01 UTC, jsravn commented
Isn't there a race condition in the way the endpoint controller handles items on the work queue that could cause missed updates?

1. endpoint update A arrives on workqueue
2. worker wakes up, processes item
3. worker almost finishes syncing service
4. endpoint update B arrives on workqueue
5. worker finishes processing A, removes key from workqueue
6. endpoint update B is missed

In this case if we remove the resync we could miss endpoint updates entirely. That could be catastrophic for production services. I think removing the resync is high risk unless we're sure all data races are fixed. But it's hard to get right (see the attach_detach_controller for example, which has just recently added resync logic).

2017-06-23 10:09 UTC, kargakis commented
Doesn't the attach-dettach controller deal with external to k8s resources? Clayton's [comment](https://github.com/kubernetes/kubernetes/pull/47788#issuecomment-309922888) applies in that case.

2017-06-23 10:09 UTC, mikedanese commented
@jsravn the workqueue ack checks if the object is dirty and readds it to the queue if it is.

2017-06-23 10:11 UTC, jsravn commented
Yeah, ignore me, I read the work queue and saw the dirty set which covers that case.

2017-06-23 10:12 UTC, mikedanese commented
Can someone explain to me how we are not in violation of: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/principles.md#control-logic point one if we don't occasionally resync/relist? Do we not care about that anymore?

2017-06-23 10:15 UTC, gmarek commented
That's a good question - I believe we stopped treating Informers as 'cache'. @kubernetes/sig-api-machinery-misc

2017-06-23 10:18 UTC, jsravn commented
@kargakis I'm mostly familiar with the aws implementation of it. But I believe the attach_detach_controller deals exclusively in k8s resources. It's kubelet that updates those resources based on external state, like whether the volume is mounted locally etc. The known data races in the attach detach controller have been purely code bugs, but there have been so many of them due to complexity that the resync was added as a catch all.

2017-06-23 10:50 UTC, shyamjvs commented
Just to clarify, we still have a resync period but it's quite high (~21 hrs
iirc). AddResourceHandler internally calls
AddResourceHandlerWithResyncPeriod, but with this default high value.

On Jun 23, 2017 12:18 PM, "James Ravn" <notifications@github.com> wrote:

> @kargakis <https://github.com/kargakis> I'm mostly familiar with the aws
> implementation of it. But I believe the attach_detach_controller deals
> exclusively in k8s resources. It's kubelet that updates those resources
> based on external state, like whether the volume is mounted locally etc.
> The known data races in the attach detach controller have been purely code
> bugs, but there have been so many of them due to complexity that the resync
> was added as a catch all.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/47788#issuecomment-310629310>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEIhk3E0ymNPelkysGCsvGDjS8N13koVks5sG5EKgaJpZM4N_rG6>
> .
>

2017-06-23 11:03 UTC, shyamjvs commented
Correction: AddEventHandler
Ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L265

2017-06-23 11:52 UTC, shyamjvs commented
@mikedanese Could you approve the PR? Thanks.

2017-06-26 07:35 UTC, mikedanese commented
/approve

2017-06-26 09:10 UTC, gmarek commented
/test pull-kubernetes-federation-e2e-gce

2017-06-26 11:20 UTC, merged