make fluentd liveness probe more generic
kubernetes/kubernetes pull request #47836
Opened 2017-06-21 11:42 UTC by widgetpl

It makes fluentd livenessprobe much more generic, if buffering to files is not used but in-memory instead it allows to use this liveness probe which is based on gcp-containers.log.pos which I think is changed most often because of the amount of logs from all containers on the node. I have removed first condition to be compatible with people which are not using file buffering.

Don't know what is the purpose of two differen envs as with default values the last condition will never occur even if we will set LIVENESS_THRESHOLD_SECONDS it will be barely possible, please correct me if I am wrong.

I have added extra `env` variable `POS_FILE` which allows to set specific `.pos` file or even overwrite it with buffer file like `/var/log/fluentd-buffers` if anyone like.

CC @piosz @crassirostris

2017-06-21 14:18 UTC, crassirostris commented
@widgetpl 

```
              POS_FILE=${POS_FILE:-/var/log/gcp-containers.log.pos}
              LAST_MODIFIED_DATE=`stat ${POS_FILE} | grep Modify | sed -r "s/Modify: (.*)/\1/"`;
```

There are more than one .pos files. It's possible that application container are quite (or are exporting logs in a different way) and only system components are exporting logs.

2017-06-21 14:43 UTC, widgetpl commented
@crassirostris I know but as default value I have used values from default configs for each fluent deployment:
fluentd-elasticsearch - `pos_file /var/log/es-containers.log.pos`
fluentd-gcp - `pos_file /var/log/gcp-containers.log.pos`

so if anyone would like to use own configuration there is possibility to overwite `POS_FILE` with custom value.
You are right that there can be very low number of logs from containers especially when you are setting up new cluster and there is no deployment yet.
In this case it is possible to overwrite `POS_FILE` with buffer file like `/var/log/fluentd-buffers` or even better set this value as a default one.
What do you think ?

2017-07-06 14:48 UTC, crassirostris requested changes

2017-07-06 14:48 UTC, crassirostris commented on cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml
> +                if [ ! -e /var/log/fluentd-buffers ];
If it doesn't exist, then delete?

2017-07-06 14:48 UTC, crassirostris commented on cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml
> +              POS_FILE=${POS_FILE:-/var/log/gcp-containers.log.pos}
Mb replace with taking the latest timestamp of all among `.pos` files by default?

2017-07-06 14:49 UTC, crassirostris commented
@widgetpl I had in mind instead of checking one file, going over all .pos files. Anyway, let's discuss it in-place using this review mechanism :)

2017-10-05 08:07 UTC, closed without merging