Add unit test coverage for nvidiaGPUManager initialization
kubernetes/kubernetes pull request #47918
Opened 2017-06-22 18:22 UTC by jiayingz

Part of #47750 

```release-note
NONE
```

2017-06-22 18:46 UTC, jiayingz commented
CLA should be signed now.

2017-06-22 19:52 UTC, jiayingz commented
/assign @vishh

2017-06-23 22:04 UTC, vishh approved these changes
/lgtm

2017-06-23 22:06 UTC, vishh commented
/approve

2017-06-23 22:06 UTC, vishh commented
/test all

2017-06-28 14:24 UTC, cmluciano commented
@k8s-bot ok to test

2017-06-28 14:31 UTC, cmluciano commented
@jiayingz The bazel build is claiming a merge conflict ```CONFLICT (content): Merge conflict in pkg/kubelet/gpu/nvidia/nvidia_gpu_manager_test.go```

2017-06-28 17:23 UTC, jiayingz commented
/retest

2017-06-28 18:17 UTC, rohitagarwal003 requested changes
`pkg/kubelet/gpu/nvidia/BUILD` needs to be updated with a new test dependency on:

```
//pkg/kubelet/dockershim/libdocker:go_default_library
```

2017-06-28 18:17 UTC, mindprince commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager_test.go
> +	"k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker"
Please run `go fmt` on this file. This seems unordered.

2017-06-28 18:18 UTC, mindprince commented
/assign

2017-06-28 18:22 UTC, cmluciano commented on pkg/kubelet/gpu/nvidia/nvidia_gpu_manager_test.go
> +		gpus := reflect.ValueOf(testGpuManager2).Elem().FieldByName("allGPUs").Len()
Can you put a note of how many we do expect as a comment? Also will testGpuManager2.Start try to go through the discovery logic or do we want to hardcode it more?

2017-06-30 21:14 UTC, cmluciano commented
/lgtm

2017-07-01 01:42 UTC, merged