Updated rbd volume example to use yaml configs with better readability
kubernetes/kubernetes pull request #48032
Opened 2017-06-25 18:47 UTC by farcaller

**What this PR does / why we need it**:

It turns barely-readable poorly formatted json to more compact yaml in the examples, that are supposed to be consumed by humans.

**Release note**:
```release-note
NONE
```

2017-06-28 03:34 UTC, xiangpengzhao requested changes

2017-06-28 03:34 UTC, xiangpengzhao commented on examples/volumes/rbd/README.md
> +Once you have installed Ceph and new Kubernetes, you can create a pod based on my examples [rbd.yaml](rbd.yaml)  [rbd-with-secret.ymal](rbd-with-secret.ymal). In the pod YAML, you need to provide the
s/ymal/yaml

2017-06-28 09:34 UTC, farcaller commented on examples/volumes/rbd/README.md
> +Once you have installed Ceph and new Kubernetes, you can create a pod based on my examples [rbd.yaml](rbd.yaml)  [rbd-with-secret.ymal](rbd-with-secret.ymal). In the pod YAML, you need to provide the
Done.

2017-06-30 18:27 UTC, spiffxp commented
examples have been moved over to https://github.com/kubernetes/examples, please close this PR and open over there

FYI @kubernetes/sig-storage-misc since you seem like potential owners of volume-related examples

2017-06-30 23:49 UTC, closed without merging