[WIP] Add support for externaladmissionhookconfigurations and initializerco…
kubernetes/kubernetes pull request #48040
Opened 2017-06-26 06:09 UTC by shiywang

Fixes https://github.com/kubernetes/kubernetes/issues/48010
/assign @liggitt 

> It's a missing printer. There are two issues:
> 1. the printer is missing
> 2. kubectl should fall back to a generic printer for types without registered printers

this pr now addressed 1, for 2, still wip

2017-06-26 09:43 UTC, shiywang commented
/retest

2017-06-27 02:22 UTC, shiywang commented
@liggitt @smarterclayton will rebase after https://github.com/kubernetes/kubernetes/pull/48033 get merged

2017-07-08 21:25 UTC, smarterclayton requested changes

2017-07-08 21:25 UTC, smarterclayton commented on pkg/printers/internalversion/printers.go
> +	h.Handler(initializerConfigurationColumns, nil, printInitializerConfiguration)
Please add a new style printer (table) rather than old style.  See other examples in this file

2017-07-13 04:48 UTC, shiywang commented on pkg/printers/internalversion/printers.go
> +	h.Handler(initializerConfigurationColumns, nil, printInitializerConfiguration)
for now, `initializerConfigurationColumns` only print NAME and AGE, isn't it already covered by  AddDefaultHandlers ?

2017-10-11 08:07 UTC, closed without merging