[WIP] [API] Feature/job failure policy
kubernetes/kubernetes pull request #48075
Opened 2017-06-26 15:58 UTC by clamoriniere1A

**What this PR does / why we need it**: Implements the Backoff policy and failed pod limit defined in https://github.com/kubernetes/community/pull/583

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This is a WIP PR, I updated the api batchv1.JobSpec in order to prepare the backoff policy implementation in the JobController.

**Release note**:

```release-note
```

2017-06-26 16:45 UTC, kargakis commented
@kubernetes/sig-apps-api-reviews

2017-06-27 06:14 UTC, clamoriniere1A commented
CLA signed

2017-06-30 18:24 UTC, spiffxp commented
/ok-to-test

2017-07-20 13:34 UTC, clamoriniere1A commented
Hi @soltysh 

This PR is linked to the proposal “Backoff policy and failed pod limit”: https://github.com/kubernetes/community/pull/583

I started to update the jobcontroller.syncJob() logic, and I have 2 questions regarding the attended behaviours:
**1) Do we need to delete all the active running Pod in case the ```Backofflimit``` have been reached?** like it is done when we cross the “Job Deadine”.
(code link: https://github.com/clamoriniere1A/kubernetes/blob/feature/job_failure_policy/pkg/controller/job/jobcontroller.go#L521 )

**2) In order to handle properly the deletion of failed pods when the ```Job.Spec. FailedPodsLimit``` is reached.** 
I needed to add a new counter ```FailedAndDeleted``` in the ```Job.Status struct``` ( https://github.com/clamoriniere1A/kubernetes/blob/feature/job_failure_policy/pkg/apis/batch/types.go#L179 ). The new counter allows me to calculate the total number of failed Pod: “Failed and Active” + “Failed and deleted”.
**Do you think is a good approach?**

2017-07-27 09:20 UTC, clamoriniere1A commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-18 15:19 UTC, soltysh commented
/assign

2017-08-18 15:26 UTC, soltysh commented
@clamoriniere1A

> 1) Do we need to delete all the active running Pods in case the Backofflimit have been reached? like it is done when the Job cross the “Job Deadine”.

Yes. We need to stop whatever is already running. 

> 2) In order to handle properly the deletion of failed pods when the Job.Spec. FailedPodsLimit is reached.
> I needed to add a new counter FailedAndDeleted in the Job.Status struct ( https://github.com/clamoriniere1A/kubernetes/blob/feature/job_failure_policy/pkg/apis/batch/types.go#L179 ). The new counter allows me to calculate the total number of failed Pod: “Failed and Active” + “Failed and deleted”.
> Do you think it is a good approach?

I don't think it's needed. The `Job.Status.Failed` value should have all the pods that failed during the overall run. Not just currently available.

2017-08-18 15:37 UTC, soltysh requested changes

2017-08-18 15:37 UTC, soltysh commented on pkg/apis/batch/v1/defaults_test.go
> +					FailedPodsLimit: newInt32(1),
That seems wrong, if you set it explicitly to 2, why you're expecting 1, here?

2017-08-18 15:37 UTC, soltysh commented on pkg/apis/batch/types.go
> +	// The number of pods which reached phase Failed and deleted.
Not needed, the above `Failed` field should hold information about all the failed pods. Currently it's the job controller that is broken, see https://github.com/kubernetes/kubernetes/issues/28486 for details.

2017-08-18 15:47 UTC, clamoriniere1A commented on pkg/apis/batch/types.go
> +	// The number of pods which reached phase Failed and deleted.
Ok I will remove this field

2017-08-18 15:55 UTC, clamoriniere1A commented on pkg/apis/batch/v1/defaults_test.go
> +					FailedPodsLimit: newInt32(1),
Right, 
The fact is that I mess up some commits split. I did include in this commit the test logic update that is checking the value: BackoffLimit and FailedPodsLimit.

2017-08-22 21:51 UTC, clamoriniere1A commented
/test pull-kubernetes-e2e-kops-aws

2017-08-23 07:09 UTC, clamoriniere1A commented
/test pull-kubernetes-e2e-kops-aws

2017-08-24 15:16 UTC, clamoriniere1A commented
/test pull-kubernetes-verify

2017-08-24 17:00 UTC, clamoriniere1A commented
/test pull-kubernetes-unit

2017-08-29 10:20 UTC, soltysh approved these changes

2017-08-29 10:21 UTC, soltysh commented
/lgtm
/approve

2017-08-29 10:21 UTC, soltysh commented
@erictune needs your sign-off for the API changes

2017-08-30 11:27 UTC, kargakis commented
/test pull-kubernetes-bazel-build 
/test pull-kubernetes-bazel-test

2017-08-31 15:14 UTC, smarterclayton commented
Based on reading of the proposal and conventions this is API approved.  The PR that enables failedpodslimit will still need API review, although I confirmed it matches the proposal.

/approve

2017-09-01 19:03 UTC, soltysh commented
/lgtm

2017-09-01 20:04 UTC, soltysh commented
/retest

2017-09-01 21:21 UTC, clamoriniere1A commented
/test pull-kubernetes-kubemark-e2e-gce

2017-09-01 22:45 UTC, soltysh commented
/test pull-kubernetes-kubemark-e2e-gce

2017-09-01 23:03 UTC, soltysh commented
/test pull-kubernetes-kubemark-e2e-gce

2017-09-02 12:39 UTC, soltysh commented
/retest

2017-09-02 14:06 UTC, CaoShuFeng commented
/test pull-kubernetes-verify

2017-09-03 01:18 UTC, merged

2017-09-03 10:02 UTC, kargakis commented
Is there a PR with the controller changes?

2017-09-03 19:45 UTC, cedriclam commented
@kargakis, yes #51153 contains controller changes

2017-09-03 19:48 UTC, kargakis commented
merci