Allow Kubenet with ipv6
kubernetes/kubernetes pull request #48091
Opened 2017-06-26 19:36 UTC by rpothier

When running kubenet with IPv6, there is a panic as there
is IPv4 specific code the Event function.
With this change, Event will support IPv4 and IPv6

**What this PR does / why we need it**:
This PR allows kubenet to use IPv6. Currently there is a panic in kubenet_linux.go
as there is IPv4 specific code.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48089

**Special notes for your reviewer**:

**Release note**:

```release-note-NONE
```

2017-06-26 19:39 UTC, rpothier commented
/area ipv6

2017-06-26 20:07 UTC, rpothier commented
/release-note-none

2017-06-27 00:02 UTC, freehan commented
@k8s-bot ok to test

2017-06-27 12:21 UTC, pmichali commented
/sig network

2017-06-27 13:12 UTC, pmichali requested changes

2017-06-27 13:12 UTC, pmichali commented on pkg/kubelet/network/kubenet/kubenet_linux_test.go
> +		kubenet.podIPs[existingContainerID] = tc.ip
Can you elaborate on what this line is doing? Is it used later on? Should it be done by Event() logic?

2017-06-27 13:12 UTC, pmichali commented on pkg/kubelet/network/kubenet/kubenet_linux_test.go
> +		expectIP string
I don't see this field used. Missing an assertion during test case processing?

2017-06-27 14:59 UTC, rpothier commented on pkg/kubelet/network/kubenet/kubenet_linux_test.go
> +		expectIP string
Will use this as the expected gateway, see the nelow comment

2017-06-27 14:59 UTC, rpothier commented on pkg/kubelet/network/kubenet/kubenet_linux_test.go
> +		kubenet.Event(network.NET_PLUGIN_EVENT_POD_CIDR_CHANGE, details)
Will add a check for these

2017-06-27 14:59 UTC, rpothier commented on pkg/kubelet/network/kubenet/kubenet_linux_test.go
> +		kubenet.podIPs[existingContainerID] = tc.ip
This adds an IP to the podIPs, then in the teardown function, the podIP is checked for and deleted. This test function checks that the DelNetwork is called correctly.

2017-06-27 18:25 UTC, freehan commented
Thanks! There is a lot more changes needed for kubenet to understand IPv6. But this is a start.

2017-06-27 20:08 UTC, rpothier commented
/test pull-kubernetes-federation-e2e-gce

2017-06-28 01:32 UTC, rpothier commented
/test pull-kubernetes-e2e-gce-etcd3

2017-06-28 11:05 UTC, pmichali reviewed
/lgtm

2017-06-28 13:36 UTC, cmluciano commented
/assign @dnardo

2017-06-30 13:49 UTC, rpothier commented
@freehan @dnardo Any comment on this?

2017-06-30 15:17 UTC, dnardo commented
/lgtm

2017-07-03 18:56 UTC, cmluciano commented
/assign @freehan 

Can we get an approve?

2017-07-03 19:39 UTC, rpothier commented
/test pull-kubernetes-unit

2017-07-05 18:13 UTC, freehan commented
/approve

2017-07-05 19:37 UTC, merged