Introduced fake docker client to add the testcase for gpusInUse() in …
kubernetes/kubernetes pull request #48133
Opened 2017-06-27 11:54 UTC by abdasgupta

In reference to https://github.com/kubernetes/kubernetes/issues/47750, this PR is raised to increase the test coverage for gpu package. This PR increases the coverage to 68% from 50%.

@vishh @jiayingz 
-->
```NONE
```

2017-06-28 14:28 UTC, cmluciano requested changes
This replicates tests in the following open PRs #46644 #47918

2017-06-28 14:28 UTC, cmluciano commented
/assign

2017-06-28 18:32 UTC, jiayingz commented
Hi @abdasgupta, thanks a lot for the PR.

I haven't looked at your code very closely, but as cmluciano@ mentioned, this PR may have some overlapping with PR #47918. In PR #47918, I mostly added test coverage for NewNvidiaGPUManager() and Start(). With that, I think the left functions with most missing test coverage are gpusInUse() and isValidPath(). I saw your PR did test gpusInUse(), but it also added several helper functions. Are they all necessary to test gpusInUse()? One concern is we may change gpu_manager to use CRI later, so we may want to avoid adding too much specific test code.

2017-06-29 06:17 UTC, abdasgupta commented
Hi @cmluciano , Thank you for your review.
Explanation for the overlap with PR #47918 is explained below. But for the overlap with PR #46644, I raised this PR to cover the unit test cases. Does that PR increase the unit test coverage? If yes, then there would be very little use for this PR.

2017-06-29 06:30 UTC, abdasgupta commented
Hi @jiayingz, Thank you for your review.
So,in this PR, the following helper functions were needed to add - InitiateActivePods, makeDevices, makeTestPodWithStatuses

Out of them, only InitiateActivePods is associated with ActivePodLister. And rest of them just enhance the POD specifications. None of the helper functions are depending on gpu_manager. 
This test was for gpu_in_use(). In the earlier tests of gpu_in_use(), most of the statements inside the functions are being skipped as container status is not added to POD specs. We may reduce one helper function from this PR if we form all the PODs with container statuses, but that will need to update the docker clients in other test cases as well. In the test for gpu_in_use, gpu_manager is only provided with the fake docker client which was necessary to test most of the statements inside gpu_in_use(). Only two other AllocateGpu can  be called redundant but actually they are also testing gpu_in_use() in a slightly different way.

2017-06-29 15:40 UTC, cmluciano commented
@jiayingz 's PR raises the coverage to 59.8%

2017-06-29 16:09 UTC, abdasgupta commented
@cmluciano This one to 68%. So if both combined, I am expecting upto 80% almost. This PR and @jiayingz 's cover different  functions.

2017-06-30 18:21 UTC, spiffxp commented
/ok-to-test

2017-07-06 18:26 UTC, vishh commented
@mindprince can you review this PR?

2017-07-10 17:39 UTC, mindprince commented
Yeah, I will take a look later today.

2017-10-09 08:08 UTC, closed without merging