Add corrupt docker image check for e2e reboot test
kubernetes/kubernetes pull request #48153
Opened 2017-06-27 21:06 UTC by ajitak

At times reboot results in corrupt docker image. Adding a test for docker corrupt image while waiting for pods to be ready will make this test less flaky.

2017-06-27 21:06 UTC, ajitak commented
/assing @dchen1107 
/assign @Random-Liu

2017-06-27 21:50 UTC, ajitak commented
/assign @dchen1107

2017-06-29 03:26 UTC, xiangpengzhao requested changes

2017-06-29 03:26 UTC, xiangpengzhao commented on test/e2e/reboot.go
> +			framework.Logf("Docker image corruption detected for ndoe %s, ignoring pod not ready error", name)
s/ndoe/node

2017-06-29 05:36 UTC, ajitak commented on test/e2e/reboot.go
> +			framework.Logf("Docker image corruption detected for ndoe %s, ignoring pod not ready error", name)
Updated.

2017-06-29 17:43 UTC, Random-Liu commented
/lgtm

2017-06-29 19:51 UTC, ajitak commented
/assign @spxtr

2017-06-29 19:59 UTC, spxtr reviewed
I'm a little confused. Sometimes a reboot causes docker image corruption... isn't that a bad thing? Shouldn't we fix that rather than paper over the issue in e2e tests?

2017-06-29 19:59 UTC, spxtr commented on test/e2e/reboot.go
> +		if item.Reason == "CorruptDockerImage" {
Where is this string from? A search for it in this repo yields nothing.

2017-06-29 20:15 UTC, ajitak commented on test/e2e/reboot.go
> +		if item.Reason == "CorruptDockerImage" {
This string comes from node problem detector https://github.com/kubernetes/node-problem-detector/pull/117

2017-06-29 20:19 UTC, ajitak commented
@dchen1107 What is the plan for addressing the root cause?

2017-06-29 21:37 UTC, Random-Liu commented
> I'm a little confused. Sometimes a reboot causes docker image corruption... isn't that a bad thing? Shouldn't we fix that rather than paper over the issue in e2e tests?

In GKE, auto-repair should remedy properly e.g. clean up the docker image once that happens. That's also the original plan.
For open source, since it's a docker problem, and we don't have remedy system, we can't do anything except waiting for docker to fix this and ignore the problem in our test for now.

2017-10-11 19:25 UTC, closed without merging