pkg/volume: delete duplicated PathExists function
kubernetes/kubernetes pull request #48197
Opened 2017-06-28 13:39 UTC by alexandercampbell

There was already a function named FileExists in "pkg/util". Make use of this function instead of keeping identical logic in pkg/volume.

**Which issue this PR fixes**: No Issue

**Release note**:

```release-note
NONE
```

2017-06-29 03:05 UTC, xiangpengzhao requested changes

2017-06-29 03:05 UTC, xiangpengzhao commented on pkg/volume/aws_ebs/aws_util.go
> -	volumeutil "k8s.io/kubernetes/pkg/volume/util"
I guess you need to run `hack/update-bazel.sh` to update BUILD files.

2017-06-29 16:32 UTC, alexandercampbell commented on pkg/volume/aws_ebs/aws_util.go
> -	volumeutil "k8s.io/kubernetes/pkg/volume/util"
Good call. Updated. Thanks!

2017-06-30 18:02 UTC, spiffxp commented
/ok-to-test

2017-07-05 22:45 UTC, alexandercampbell commented
Looks like there's an intermittent failure popping up, but I needed to rebase onto master anyway. Let's see what the CI robot thinks now.

2017-07-11 02:26 UTC, mengqiy commented
/unassign @bprashanth 
/assign @shiywang

2017-07-11 03:15 UTC, shiywang commented
/lgtm

2017-07-11 03:18 UTC, shiywang commented
@rootfs  PTAL

2017-07-11 20:13 UTC, fejta commented
/test pull-kubernetes-e2e-kops-aws

2017-07-12 15:50 UTC, alexandercampbell commented
Had to fix merge conflicts and rebase. PTAL. Thanks!

2017-07-12 17:37 UTC, rootfs commented
/approve 
/lgtm

2017-07-14 16:14 UTC, pwittrock commented
/assign @vishh

2017-07-14 17:47 UTC, alexandercampbell commented
Had to rebase due to merge conflicts. PTAL. Thanks!

2017-07-14 18:57 UTC, alexandercampbell commented
/test pull-kubernetes-verify

2017-07-18 20:51 UTC, alexandercampbell commented
Fixed merge conflicts once more.

2017-07-19 22:33 UTC, mengqiy commented
@kubernetes/sig-node-pr-reviews Can one of the node approvers approve this?

2017-07-21 00:44 UTC, alexandercampbell commented
Nice, conflicts in every file. I may just redo my changes against master.

2017-07-21 03:03 UTC, mengqiy commented
I guess the conflict is cause by my PR https://github.com/kubernetes/kubernetes/pull/49234, which updated a lot of import paths.

2017-07-21 15:44 UTC, alexandercampbell commented
@mengqiy no problem :)
I expected plenty of merge conflicts when I opened this PR.

2017-07-21 17:13 UTC, mengqiy commented
@yujuhong @tallclair Can you approve this for `pkg/kubelet/` change?

2017-07-21 18:56 UTC, tallclair commented
Looks like the util was moved to `pkg/util/file`.

2017-07-21 19:09 UTC, xiangpengzhao commented
yeah that's introduced by #48256

2017-07-21 19:11 UTC, xiangpengzhao commented
@alexandercampbell sorry for the painful rebase

2017-07-21 20:21 UTC, alexandercampbell commented
Closing until I have time to revisit this.

2017-07-21 20:21 UTC, closed without merging

2017-07-21 20:22 UTC, alexandercampbell commented
@xiangpengzhao no worries man! Rebasing is my favorite activity :)

2017-07-21 20:26 UTC, xiangpengzhao commented
:smile: