check job ActiveDeadlineSeconds
kubernetes/kubernetes pull request #48454
Opened 2017-07-04 06:10 UTC by weiwei04

**What this PR does / why we need it**:

enqueue a sync task after ActiveDeadlineSeconds

**Which issue this PR fixes** *: 

fixes #32149

**Special notes for your reviewer**:

**Release note**:

```release-note
enqueue a sync task to wake up jobcontroller to check job ActiveDeadlineSeconds in time
```

2017-07-04 06:21 UTC, weiwei04 commented
/assign @janetkuo PTAL

2017-07-07 02:50 UTC, weiwei04 commented
@janetkuo  please take a look, thanks.

2017-07-31 13:54 UTC, soltysh commented
@weiwei04 sorry, was out for quite a long, will look into it today or tomorrow.

2017-08-01 01:25 UTC, weiwei04 commented
@soltysh thanks:)

2017-08-02 12:04 UTC, soltysh commented
/assign

2017-08-02 12:18 UTC, soltysh requested changes
Mostly nits, overall looks good.

2017-08-02 12:18 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +	key, _ := controller.KeyFunc(curJob)
There's no point in re-trying if there was an error. Check error and just return if that happens.

2017-08-02 12:18 UTC, soltysh commented on pkg/controller/job/jobcontroller.go
> +		curSeconds := curJob.Spec.ActiveDeadlineSeconds
Can you please use `currentADS` and `oldADS` it's less confusing name :)

2017-08-02 12:18 UTC, soltysh commented on staging/src/k8s.io/api/batch/v1/types.go
> +const (
Not needed, drop it. It'll cause only confusion wrt to our API.

2017-08-02 12:18 UTC, soltysh commented on test/e2e/apps/job.go
> +	batch "k8s.io/api/batch/v1"
Use `batchv1` as the name alias, to make it clear it's that version.

2017-08-02 12:18 UTC, soltysh commented on test/e2e/apps/job.go
> +		var activeDeadlineSeconds int64 = 10
Make it shorter, this will cause the entire test suite longer by 10 seconds. I'd propose 1-2 seconds max.

2017-08-08 06:13 UTC, weiwei04 commented on pkg/controller/job/jobcontroller.go
> +		curSeconds := curJob.Spec.ActiveDeadlineSeconds
yes ADS would be a more meaningful name:)

2017-08-08 06:13 UTC, weiwei04 commented on test/e2e/apps/job.go
> +		var activeDeadlineSeconds int64 = 10
changed to 2 seconds.

2017-08-08 06:15 UTC, weiwei04 commented
@soltysh modified code according to your comments, please take a look, thanks:)

2017-08-09 20:27 UTC, dims commented
/ok-to-test

2017-08-10 05:16 UTC, weiwei04 commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-14 02:47 UTC, weiwei04 commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-14 04:01 UTC, weiwei04 commented
@soltysh modified code according to your comments, and all the test are passed, please take a look, thanks:)

2017-08-17 09:24 UTC, weiwei04 commented
ping @soltysh :)

2017-08-25 03:25 UTC, weiwei04 commented
ping @soltysh :)

2017-08-29 08:19 UTC, weiwei04 commented
ping @soltysh :)

2017-08-29 11:08 UTC, soltysh commented
@weiwei04 sorry for the long silence, looking at it right now...

2017-08-29 11:32 UTC, soltysh approved these changes
LGTM

2017-08-29 11:32 UTC, soltysh commented
@weiwei04 mind squashing these changes into a single commit and I'll apply all the necessary labels for merge

2017-08-29 12:36 UTC, soltysh commented
/test pull-kubernetes-node-e2e

2017-08-29 12:36 UTC, soltysh commented
/lgtm
/approve

2017-08-29 13:08 UTC, weiwei04 commented
Thanks:)

2017-08-29 15:25 UTC, merged