update release notes for 1.7
kubernetes/kubernetes pull request #48562
Opened 2017-07-06 19:40 UTC by krmayankk

update release notes for 1.7

2017-07-06 19:41 UTC, krmayankk commented
@dchen1107 @idvoretskyi @luxas @enisoc @caesarxuchao

2017-07-06 20:13 UTC, idvoretskyi requested changes

2017-07-06 20:13 UTC, idvoretskyi commented on CHANGELOG.md
> +* [beta] Previously, PodDisruptionBudget Controller used selector-based listers to determine which controller is managing a given Pod. Now ControllerRef proposal is implemented across all controllers
Please, remove an indent, together with "[beta]" mentioning.

2017-07-06 22:36 UTC, enisoc commented
This seems a bit too technical for a user-facing release note. I would make it something like:

```
* PodDisruptionBudget now uses [ControllerRef](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md) to make the right decisions about Pod eviction even if controllers have overlapping selectors.
```

2017-07-06 23:02 UTC, dchen1107 commented
+1 on what @enisoc's comment above.

2017-07-07 02:31 UTC, krmayankk commented
fixed @dchen1107 @enisoc

2017-07-07 18:51 UTC, enisoc commented
/lgtm

2017-07-10 20:12 UTC, krmayankk commented
/test pull-kubernetes-kubemark-e2e-gce
/test pull-kubernetes-e2e-gce-etcd3

2017-07-12 03:35 UTC, krmayankk commented
@jbeda can you approve. @enisoc is there any other blocker to get this merged ?

2017-07-12 18:07 UTC, enisoc commented
It just needs OWNERS approval.

/assign @dchen1107

2017-07-14 01:50 UTC, merged