Prepare to introduce websockets for exec and portforward
kubernetes/kubernetes pull request #48641
Opened 2017-07-07 21:55 UTC by smarterclayton

Refactor the code in remotecommand to better represent the structure of
what is common between portforward and exec.

Ref #48633

2017-07-07 21:56 UTC, smarterclayton commented
@ncdc this is the great refactor, long in the making!  I'm just going to do some small cleanup and code movement before I add the abstraction for websocket.

2017-07-08 01:10 UTC, ncdc requested changes
LGTM overall

2017-07-08 01:10 UTC, ncdc commented on staging/src/k8s.io/client-go/transport/spdy/spdy.go
> +// spdyDialer implements the httpstream.Dialer interface.
s/spdyDialer/dialer/

2017-07-08 01:10 UTC, ncdc commented
/assign

2017-07-08 01:11 UTC, ncdc commented
/release-note-none

2017-07-08 01:11 UTC, ncdc commented
Need to fix bazel

2017-07-09 21:22 UTC, smarterclayton commented
Updated (except for the kubefed issue which is not related)

2017-07-10 16:24 UTC, smarterclayton commented
/retest

2017-07-10 19:48 UTC, smarterclayton commented
/retest

2017-07-11 22:37 UTC, smarterclayton commented
/retest

2017-07-12 15:01 UTC, smarterclayton commented
Applying label per comments and green (andy correct me if you wanted more)

2017-07-12 15:06 UTC, ncdc approved these changes

2017-07-12 15:06 UTC, ncdc commented
Good to go, thanks

2017-07-12 21:08 UTC, merged