[WIP] Fix sort-by output problem
kubernetes/kubernetes pull request #48659
Opened 2017-07-08 06:13 UTC by shiywang

Fixes https://github.com/kubernetes/kubectl/issues/43

This bug was original introduced in pr here: https://github.com/kubernetes/kubernetes/pull/46265, I think next time if we touch something printer related package, should let @smarterclayton have a review, although he is pretty busy I guess : ) and that package also changed a lot recently since he's been working on refactoring.
 
this is a quick and dirty fix, not sure if there's better way, I will add some regression test soon...

@kubernetes/sig-cli-pr-reviews 

```release-note
NONE
```

/assign @mengqiy 
/assign @smarterclayton

2017-07-08 15:48 UTC, liggitt commented
Definitely needs tests to prove this fixes the issue and to prevent regression

2017-07-11 03:00 UTC, mengqiy commented
/cc @waseem

2017-07-11 07:30 UTC, shiywang commented
@mengqiy @liggitt  cmd-test added, I also submit a test pr to show if we don't change the code, the test will failed

2017-07-11 09:30 UTC, shiywang commented
/retest

2017-07-11 20:10 UTC, fejta commented
/test pull-kubernetes-e2e-kops-aws

2017-07-12 15:09 UTC, shiywang commented
@kubernetes/sig-cli-pr-reviews

2017-07-12 18:24 UTC, mengqiy commented
/assign @alexandercampbell

2017-07-13 01:45 UTC, xingzhou commented on pkg/kubectl/cmd/util/printing.go
> +			printer = humanReadablePrinter
Any reason to keep this line? as I think printer is already a pointer in this case

2017-07-13 03:23 UTC, shiywang commented on pkg/kubectl/cmd/util/printing.go
> +			printer = humanReadablePrinter
thanks, updated, ptal

2017-07-13 06:25 UTC, xingzhou commented on pkg/kubectl/cmd/util/printing.go
> +			printer = humanReadablePrinter
thx, /lgtm

2017-07-13 20:50 UTC, alexandercampbell reviewed
Looks good. Minor comments.

2017-07-13 20:50 UTC, alexandercampbell commented on hack/make-rules/test-cmd-util.sh
> +  # Chcek output of sor-by
Chcek --> Check
sor-by --> sort-by

2017-07-13 20:50 UTC, alexandercampbell commented on pkg/kubectl/cmd/util/printing.go
> +		if humanReadablePrinter, ok := printer.(*printers.HumanReadablePrinter); ok {
Why do you need both `if` statements?

2017-07-13 20:50 UTC, alexandercampbell commented on pkg/kubectl/cmd/util/printing.go
> +	// need to use delegatePrinter convert again outsider when it's a SortingPrinter
What is "outsider"?

2017-07-14 06:22 UTC, shiywang commented on pkg/kubectl/cmd/util/printing.go
> +		if humanReadablePrinter, ok := printer.(*printers.HumanReadablePrinter); ok {
I had a thinking about keep only one `if`, but I think we should check printer.IsGeneric() first, then do that convert, do you mean this way: 
```
if humanReadablePrinter, ok := printer.(*printers.HumanReadablePrinter); ok && !printer.IsGeneric(){
	printersinternal.AddHandlers(humanReadablePrinter)
}
```
or this way ?
```
if !printer.IsGeneric() {
          humanReadablePrinter, ok := printer.(*printers.HumanReadablePrinter);
          printersinternal.AddHandlers(humanReadablePrinter)
}
```

2017-07-14 06:23 UTC, shiywang commented on hack/make-rules/test-cmd-util.sh
> +  # Chcek output of sor-by
done

2017-07-14 06:32 UTC, shiywang commented on pkg/kubectl/cmd/util/printing.go
> +	// need to use delegatePrinter convert again outsider when it's a SortingPrinter
outsider means ring2Factory.PrinterForMapping this line:https://github.com/kubernetes/kubernetes/pull/48788/files#diff-a9b5082d3df09126fbcd118712148907R113,

2017-07-14 20:08 UTC, alexandercampbell requested changes

2017-07-14 20:08 UTC, alexandercampbell commented on pkg/kubectl/cmd/util/printing.go
> +		if humanReadablePrinter, ok := printer.(*printers.HumanReadablePrinter); ok {
To continue our previous conversation: I would write this:

```go
if humanReadablePrinter, ok := printer.(*printers.HumanReadablePrinter); ok {
    printersinternal.AddHandlers(humanReadablePrinter)
}
```

Why do you need the IsGeneric check? If the printer is HumanReadable, you know the printer is nongeneric.

2017-07-17 02:18 UTC, shiywang commented on pkg/kubectl/cmd/util/printing.go
> +		if humanReadablePrinter, ok := printer.(*printers.HumanReadablePrinter); ok {
ok, updated

2017-07-20 02:32 UTC, shiywang commented
@alexandercampbell @mengqiy ptal, thanks

2017-07-20 20:54 UTC, alexandercampbell commented
+1

2017-07-20 20:54 UTC, alexandercampbell commented
/lgtm

2017-07-28 04:23 UTC, mengqiy commented
/retest
/assign @pwittrock
Assign to you for approval.

2017-08-04 00:52 UTC, shiywang commented
/test pull-kubernetes-e2e-kops-aws

2017-08-06 02:48 UTC, shiywang commented
/test pull-kubernetes-e2e-kops-aws

2017-08-06 02:49 UTC, shiywang commented
ping @pwittrock for approval

2017-08-09 05:03 UTC, shiywang commented
ping @smarterclayton for approval

2017-08-09 16:05 UTC, pwittrock commented
/approve

2017-08-09 16:06 UTC, pwittrock commented
/approve cancel

2017-08-09 16:15 UTC, pwittrock commented
/approve

2017-08-09 17:56 UTC, merged

2017-09-05 10:39 UTC, munnerz commented
Does anyone know what release this will make it into? It'd be great to see in the next patch release of 1.7!