Add new option "envFrom" for `kubectl run` command.
kubernetes/kubernetes pull request #48684
Opened 2017-07-10 07:29 UTC by xingzhou

Propose to add new option "envFrom" for `kubectl run` command so that user
can config ConfigMap or Secret env variables from run command.

Fixed #48361 

**Release note**:
```
None
```

2017-07-11 02:06 UTC, pwittrock commented
/unassign

2017-07-11 02:06 UTC, pwittrock commented
/assign @shiywang

2017-07-11 02:06 UTC, pwittrock commented
/assign @mengqiy

2017-07-11 02:07 UTC, pwittrock commented
/assign @alexandercampbell

2017-07-11 02:07 UTC, pwittrock commented
@alexandercampbell FYI, this should probably wait until your refactor is finished.

2017-07-11 10:19 UTC, shiywang commented on pkg/kubectl/run.go
> +			envFroms = append(envFroms, envFrom)
this line and line952 is same, could move out of code block and merge to one ?

2017-07-11 10:19 UTC, shiywang commented on pkg/kubectl/run.go
> +		if refType == "ConfigMapRef" {
I would prefer switch instead of `if else if else`

2017-07-11 10:22 UTC, shiywang commented
/ok-to-test

2017-07-11 16:29 UTC, alexandercampbell requested changes
Thanks!

2017-07-11 16:29 UTC, alexandercampbell commented on pkg/kubectl/cmd/run.go
> +	cmd.Flags().StringSlice("envFrom", []string{}, "Environment variables to set from ConfigMap or Secret in the container")
This flag should be named "env-from" to fit with our standard.
I can find the specific documentation requiring this if you want.

2017-07-11 16:29 UTC, alexandercampbell commented on pkg/kubectl/cmd/run_test.go
> +	}
This test doesn't test any of our code.

2017-07-11 16:29 UTC, alexandercampbell commented on pkg/kubectl/run.go
> +			return nil, fmt.Errorf("expected []string, found: %v", envFromStrings)
Why not `%T`?

2017-07-12 05:33 UTC, xingzhou commented on pkg/kubectl/cmd/run.go
> +	cmd.Flags().StringSlice("envFrom", []string{}, "Environment variables to set from ConfigMap or Secret in the container")
yeap, let me correct it

2017-07-12 05:34 UTC, xingzhou commented on pkg/kubectl/cmd/run_test.go
> +	}
This is just a test to get the flag from cmd, I saw there is a similar one for env, so added this one, I can remove this.

2017-07-12 05:36 UTC, xingzhou commented on pkg/kubectl/run.go
> +			return nil, fmt.Errorf("expected []string, found: %v", envFromStrings)
will update the code then.

2017-07-12 05:36 UTC, xingzhou commented on pkg/kubectl/run.go
> +		if refType == "ConfigMapRef" {
ok, let me update the code

2017-07-12 09:21 UTC, xingzhou commented
@alexandercampbell and @shiywang, updated the patch according to your comments, PTAL, thx

2017-07-13 20:58 UTC, alexandercampbell commented on pkg/kubectl/run_test.go
> +			t.Errorf("\nexpected:\n%#v\nsaw:\n%#v (%s)", test.expected, envFroms, test.test)
Nice, I like this test style.

2017-07-13 20:58 UTC, alexandercampbell commented
/lgtm

2017-07-24 02:40 UTC, xingzhou commented
Have rebased the patch, PTAL, thanks. Besides, @alexandercampbell, can you please also `APPROVE` the patch to get it merged?

2017-07-26 00:45 UTC, alexandercampbell commented
@xingzhou sorry, I don't have the authority to approve PRs. @pwittrock @fabianofranz?

/retest

2017-07-26 13:30 UTC, lev-kuznetsov commented
/assign @pwittrock

2017-07-31 21:13 UTC, pwittrock commented
Kubectl run already has a ton of flag options.  I don't think we should be continuing to add them until we have clarity on what the relationship with the "set" commands are.

2017-08-01 02:43 UTC, xingzhou commented
I think environment variables is not something that we can change after a pod is created right now, besides, paired with `--env` option in the run command, it's more easier for the end user to create a pod. I would suggest that we have this option in the command

2017-08-01 18:30 UTC, alexandercampbell commented
@pwittrock so do we close this pending updates to `set` or continue review?

2017-08-02 15:35 UTC, lev-kuznetsov commented
I made the original ticket #48361 as a bug with the overrides not working off of kubectl run. Obviously this particular solution is much preferred over the overrides but I can manage with overrides - so fix that instead then. Providing each env var to kubectl is not something practicable in my use case.

2017-08-03 18:31 UTC, pwittrock commented
What is the use case you are targeting for this?  Why not do this through config instead of run?

2017-08-03 19:16 UTC, lev-kuznetsov commented
I'm trying to run integrated tests in the cluster and inject secrets via k8 means (configmap or secret).

Conceptually this is closer to a job than a service. Except there's currently no facilities to block on a job from kubectl; not that I found anyhow. If there were I'd submit a job, block until it completes, print logs. This is still messier than the solution this PR provides.

Run with envFrom at command line solves my use case exactly. My current workaround is to create a pod from my image with integrated tests and envFrom clause and a long sleep as command and run the tests in an exec to the same pod. It's not pretty but it works.

Supplying env vars on command line one by one makes it difficult to add more variables, if that's the case I'd rather use my ugly workaround

2017-08-03 20:41 UTC, nurus commented
I'd like to describe our use case as well.

We sometimes want to run one off tasks such as loading an interactive console for a rails application or running a script. The container which is spun up should have the exact same configuration as the k8s deployment for the application and should be identical to it.

Using `--env-from` makes this very simple. Without the workaround I'd have write a script to enumerate the information from the desired configmap and secretsmap belonging to the application and pass it to `--env` to reduce the potential for mistakes.  

A job almost gets us there but I'm not sure if we can run it interactively without running a second command to exec in.

2017-08-07 20:21 UTC, pwittrock commented
Why are you using kubectl run instead of config?

2017-08-07 20:55 UTC, nurus commented
@pwittrock what we're trying to do is inject environment variables stored in configmaps and secretmaps within the k8s cluster itself into containers created with `kubectl run`. I am not sure how we can do that with `config` which seems geared towards controlling the context and access to k8s clusters from the workstation.

2017-08-07 22:06 UTC, pwittrock commented
Sorry, I meant what is your usecase where you want to use run over [configuration files](https://kubernetes.io/docs/tutorials/object-management-kubectl/declarative-object-management-configuration/) to run your workloads.

2017-08-07 22:27 UTC, nurus commented
Thanks for clarifying. We actually do use config files for our deployments and services. However sometimes it's necessary to run a one off interactive session or a task within a container running  the same image as the deployed application. For that we don't want to have to create a config for a job or deployment and then exec in to the container. By using `--env-from` the image will have all the configuration it needs to mimic the deployed application. It's also nice to have the pod automatically terminate once the user exists or a one off task completes.

2017-08-08 01:29 UTC, pwittrock commented
@nurus Thanks for the explanation.  Are you using `run` to create a job or a deployment?  Is this primarily for development, debugging, or something else?  Are you doing this in the same cluster?  If so, have you considered orphaning a Pod and using that?

We definitely want to avoid supporting everything in the API as a flag, but want to support the most common / important use cases.

2017-08-08 12:00 UTC, lev-kuznetsov commented
> Why are you using kubectl run instead of config?

It's not possible to use `kubectl run -f file.yaml` as far as I'm aware. What should I be doing instead?

2017-08-08 16:29 UTC, nurus commented
No problem @pwittrock. We use `run` for development and diagnostics. We wouldn't use it to run 
a highly available application. Our applications usually consist of a web server and workers of various types which are all deployed using deployment configuration files to ensure high availability.

The applications tend to be monolithic and require the entire codebase to be baked into the image. The codebase contains methods and scripts related to the application usually for interacting with persistent storage (database, elasticsearch, etc.). The code itself relies on environment variables that it uses as parameters to connect to the persistent storage. 

For example someone many want to run a one off sql query wrapped up in a script just to glean some information from the database. `run` is perfect for this since we don't want to disrupt existing workers and prefer to spin up a one off pod to do this query which outputs to the users terminal. Pairing this with `--env-from` makes it easy just to hook into the configmap and secretsmaps which already contain the variables necessary to make the connection to the persistent storage.

We could simply exec into a pod that's part of a deployment and has all the environment variables already after orphaning it but we also don't want to endanger any work that pod is currently doing. Part of the problem is the nature of the work itself. It's much safer just to spin up a pod to do the one off task. 

I definitely see your point about not wanting to clutter up the `run` command with lots of options. As @lev-kuznetsov mentioned earlier the proper way to do with would be with overrides which reference the configmaps and secretsmaps. Unfortunately this seems to be broken. Our workaround has been to use a version of kubectl built from this branch. I'm not sure how others are using k8s but I think our use case is very common when running rails applications which have extensive configuration set as environment variables.

2017-08-10 16:09 UTC, pwittrock commented
@nurus Thanks for sticking with me.  I like to really try to understand our user's use cases as much as possible to make sure we are taking them into account in a holistic manner.

Is it correct that the main application is managed through config (`kubectl apply -f` I assume)?  If there was a simple way to spin up a new Deployment with a single Pod and change the name, Pod labels, replica, would that solve your use case?  One thing that I am thinking is that your proposed feature may make it easier to duplicate the original Pod, but still relies on the correct command line flags being supplied.

How big of a deal is the "create" + "attach" in one command vs a "create" then "attach or exec" workflow?  By adding flag to `run` it solves a limited set of usecases, whereas if it was added as a `set` command (`set env-from`) and piping it together with run (`kubectl run -o yaml --dry-run | set env-from ... | apply -f -`), it could be used for other use cases (modifying existing workloads, combining with other `kubectl create foo` commands, etc).

I'd like to talk through this more.  The deadline for 1.8 code freeze is just a couple weeks away.  How important to you that something lands in 1.8 vs 1.9?

2017-08-14 15:15 UTC, nurus commented
> Is it correct that the main application is managed through config (kubectl apply -f I assume)?

Yes, the application and its workers are deployed this way. 

>  If there was a simple way to spin up a new Deployment with a single Pod and change the name, Pod labels, replica, would that solve your use case?

Definitely, if we can spin up a pod from the same deployment and strip it of labels which are used as selectors this will work. If we're debugging a web worker we may not want it to be available to the service it would normally belong to. 

> How big of a deal is the "create" + "attach" in one command vs a "create" then "attach or exec" workflow?

Not a huge deal. We really like using `run` for pod self termination after the command completes but seems like this may be possible with piping and your proposed solution. 

>How important to you that something lands in 1.8 vs 1.9?

It's not critical that this lands in 1.8.

Thanks for your help on this @pwittrock.

2017-08-15 20:25 UTC, pwittrock commented
@nurus 

Thanks for the insight.  I will continue to work with you on this, but won't plan on it landing in 1.8 given the approaching code freeze.

One thing we have been talking about is a utility to easily apply basic transformations to a config file and emit the transformed result - e.g. something that can rename and relabel the objects in your config files and emit the transformed result.  We are prototyping this now, and it could be a helpful tool - e.g. run transform to change the labels and name on your deployment config, pipe to apply, profit.  This approach would allow you to capture things that might not be in the env piece of your config - e.g. initializers or beta fields driven off of annotations, the command and args, resource limits, etc

2017-08-17 17:27 UTC, nurus commented
@pwittrock that sounds useful and a more complete solution to replicating the environment of a deployment. I'll stay tuned.

2017-08-18 13:07 UTC, lev-kuznetsov commented
Would these transforms work on `kubectl run`? Because I really don't have a deployment to copy from

2017-10-12 18:01 UTC, toddgardner commented
Is there a decision on this change? We also ran into this not working, and have a similar use-case.

We want to run one off Jobs (like django's "python manage.py migrate" or "python manage.py shell") in the same environment variables as a running Deployment; since this is shared between multiple Deployments (like the web server and background workers), it uses envFrom in the deployment, and we'd like to just that in the Job created by kubectl run.

I don't think "run" in our use case is really just "create/apply" then "attach"; it's:

- create/apply
- wait for pod to be ready&running
- attach
- wait for final Job status
- set exit status appropriately

So you'd need more than just "set" to replicate the functionality, the "wait conditions" #1899 request would also be needed and some shell scripting around understanding status. I made a half-hearted stab at implementing that before doing the workaround mentioned above (some scripting to transform config maps and secrets to equivalent --env=FOO=bar invocations) This obviously has several drawbacks like a particularly lengthy command line and embedding secrets into a Job spec directly.

2017-10-23 18:24 UTC, nehresma commented
I landed here with the same use case as @toddgardner -- running migrations.  I'll also probably fall back to scripting to set the environment variables, but it would sure be handy to have envFrom support here.

2017-11-03 15:10 UTC, kvitajakub commented
Same use case/feature request here. We want to run separate pod with replicated environment and shell/console access (interactive) that is removed on finish.

2017-11-07 16:52 UTC, nurus commented
I've gotten envFrom to work with `--overrides` on kubectl v1.7.5. 
Here's an example of the override json:
```json       
{  
   "spec":{  
      "containers":[  
         {  
            "name": "podname",
            "image": "image",
            "args":[  
               "command"
            ],
            "envFrom":[  
               {  
                  "configMapRef":{  
                     "name": "configmap"
                  }
               },
               {  
                  "secretRef":{  
                     "name": "secrets"
                  }
               }
            ]
         }
      ]
   }
}
```
The final kubectl command looks like this:
```bash
kubectl run -i --rm --tty podname --image image  \
--namespace=namespace --restart=Never \
--overrides='{"spec": {"containers": [{"image": "image", "args": ["command"], "name": "podname", "envFrom": [{"configMapRef": {"name": "configmap"}}, {"secretRef": {"name": "secrets"}}]}]}}'
```
There's some redundancy needed to pass validation. 

This should meet the use case which brought most of us here. I ended up wrapping it up in a script to make it easier to form the command.

2017-11-08 13:39 UTC, kvitajakub commented
@nurus Thank you, that is definitely helpful. I managed to get the environment there, only problem I have is that I can't open console. There is no output, kubectl finishes and pod is not listed anywhere.
```
kubectl run -it --rm ubuntu --overrides='
{
  "spec": {
    "containers": [
      {
        "name": "ubuntu",
        "image": "ubuntu",
        "args": ["bash"],
        "envFrom": [
          {
            "configMapRef": {
              "name": "configmap-env"
            }
          }
        ]
      }
    ]
  }
}
'  --image=ubuntu --restart=Never
```
GIven the `configmap-env` exists, am I missing something?

2017-11-08 15:03 UTC, nurus commented
@kvitajakub it seems anything that isn't explicitly specified in the container spec reverts to the default option. For an interactive session add these fields to the container spec
```json
                    "stdin": True,
                    "stdinOnce": True,
                    "tty": True
```

2017-11-08 15:21 UTC, kvitajakub commented
@nurus Thank you, it works!
Final command that does get the shell with evnvars is
```

2018-04-17 16:04 UTC, javanthropus commented
This issue seems to have gone stale, but we have the same need where I work.  However, rather than add another option to the run command for each pod option now and in the future, we would be completely satisfied if there was an equivalent of the apply command that waited on the container in the pod just like the run command does.

In other words, given a full pod manifest (`pod.json`), the run command could work like this:

```
kubectl run -it --rm --restart=Never --filename pod.json
```

You can emulate this now by adding a dummy name, a dummy `--image` option, and using the `--overrides` option:

```
kubectl run -it --rm --restart=Never DUMMY --image dummy --overrides="$(cat pod.json)"
```

This seems a little backwards logically though because we want the manifest to be the base definition, where the additional command line options provide overrides.  It's also a mess to have to pass the entire manifest on the command line.

Going further, as with the create and apply commands, it would be great if the manifest could be supplied in either JSON or YAML formats.

2018-05-17 16:52 UTC, closed without merging

2020-05-21 20:40 UTC, nwsparks commented
This is a pretty useful addition, odd that is has been neglected and closed.

We have env and secret objects that are generated from terraform, things like rds connections and such.

We have requirements that prevent data from leaving the environment, so in order to interact with and view the data we would like to launch a container inside of the env via `kubectl run` and attach to the shell. These are not intended to be "deployed" services and they should exit when we are done with them so the use case fits into `kubectl run`. Being able to simply reference the terraform generated secret objects which are required to make the connections with this switch as opposed to condensed json would certainly be nice.

This seems like a simple and useful addition so I am wondering what the resistance is to adding it?