stop jsonpath panicing on negative array length
kubernetes/kubernetes pull request #48778
Opened 2017-07-11 19:12 UTC by juanvallejo

Related downstream issue: https://github.com/openshift/origin/issues/15075

Returns error if provided jsonpath value results in a negative slice index.

**Release note**:
```release-note
NONE
```

cc @fabianofranz

2017-07-11 19:20 UTC, fabianofranz commented
/ok-to-test

2017-07-11 19:29 UTC, davidopp commented
@kubernetes/sig-api-machinery-bugs

2017-07-13 16:08 UTC, juanvallejo commented
Copying related [downstream](https://github.com/openshift/origin/pull/15150#issuecomment-314999277) [discussion](https://github.com/openshift/origin/pull/15150#issuecomment-315119269):

@Miciah wrote:
> FWIW, it looks like http://goessner.net/articles/JsonPath/ is the specification for JSONPath, and it "borrows [...] the array slice syntax proposal `[start:end:step]` from ECMASCRIPT 4".  [The proposal](http://web.archive.org/web/20070828170503/http://developer.mozilla.org/es4/proposals/slice_syntax.html) states, "If `start` or `end` is negative, `seq.length` is added to it. After this step, any value not in `[0, seq.length]` is clamped to the nearest bound in that interval." ECMAScript 4 was never released, but the proposal seems consistent with [array slice semantics in ECMAScript 5](https://www.ecma-international.org/ecma-262/#sec-array.prototype.slice).

@juanvallejo wrote:
> @Miciah Thanks for that link.
>
> From the [proposal]?
 (http://web.archive.org/web/20070828170503/http://developer.mozilla.org/es4/proposals/slice_syntax.html)...
> > After this step, any value not in [0, seq.length] is clamped to the nearest bound in that interval." 

> ...and per our conversation, I think it would be best to ignore this part of the proposal, keep existing behavior for positive indices returning an "out of range" error when they are `>=` the slice length, and adopting a python-esque behavior of returning an "out of range" error when `-idx + sliceLength` falls outside of the bounds of the slice:
> 
> >
> > a := [0, 1, 2, 3]
> > b := a[-1:] // 3
> > c := a[-4:] // 0
> > d := a[-5:] // out of range error
 > > e := a[4:]  // out of range error
> 
> EDIT: also, per @Miciah 's suggestion, will update [jsonpath docs](https://kubernetes.io/docs/user-guide/jsonpath/) to reflect this

2017-07-13 17:40 UTC, juanvallejo commented
/test pull-kubernetes-federation-e2e-gce

2017-07-13 17:52 UTC, juanvallejo commented
Updated docs: https://github.com/kubernetes/kubernetes-docs-cn/pull/60

2017-07-13 18:49 UTC, juanvallejo commented
/test pull-kubernetes-federation-e2e-gce

2017-07-14 19:02 UTC, fabianofranz commented
/test pull-kubernetes-federation-e2e-gce

2017-07-17 14:19 UTC, juanvallejo commented
ping @mbohlool

2017-07-17 18:01 UTC, mbohlool requested changes

2017-07-17 18:01 UTC, mbohlool commented on staging/src/k8s.io/client-go/util/jsonpath/jsonpath.go
> +			if params[0].Value < 0 {
Did you mean to say `params[1]` here?

2017-07-17 18:01 UTC, mbohlool commented on staging/src/k8s.io/client-go/util/jsonpath/jsonpath.go
> +			if params[0].Value < 0 {
We are doing some validation down bellow (line 261 of old file). For both of these checks, should we just combine the new checks with those old checks?

```go
 			if params[0].Value >= sliceLength || params[0].Value < 0 {
 				return input, fmt.Errorf("array index out of bounds: index %d, length %d", params[0].Value, sliceLength)
 			}
 			if params[1].Value > sliceLength || params[1].Value < 0 {
 				return input, fmt.Errorf("array index out of bounds: index %d, length %d", params[1].Value-1, sliceLength)
 			}
```

2017-07-17 19:58 UTC, juanvallejo commented on staging/src/k8s.io/client-go/util/jsonpath/jsonpath.go
> +			if params[0].Value < 0 {
No, that was a mistake on my part. Will fix

2017-07-17 19:59 UTC, juanvallejo commented
@mbohlool thanks for the feedback. Went ahead and combined negative index check with the old out of bounds checks

2017-07-17 20:00 UTC, mbohlool approved these changes

2017-07-17 20:01 UTC, mbohlool commented
/lgtm

2017-07-19 21:21 UTC, juanvallejo commented
/test pull-kubernetes-kubemark-e2e-gce

2017-07-24 14:31 UTC, juanvallejo commented
@fabianofranz wondering if this is good to go? Thanks!

2017-07-24 15:15 UTC, juanvallejo commented
/test pull-kubernetes-e2e-kops-aws

2017-07-24 18:04 UTC, fabianofranz commented
/test pull-kubernetes-e2e-kops-aws

2017-07-24 18:07 UTC, fabianofranz commented
/approve no-issue

2017-07-24 18:11 UTC, fabianofranz commented
Actually @sttts @deads2k or @smarterclayton for approval.

2017-07-24 18:16 UTC, deads2k commented
/approve

2017-07-24 22:06 UTC, smarterclayton commented
/approve no-issue

On Mon, Jul 24, 2017 at 2:47 PM, Kubernetes Submit Queue <
notifications@github.com> wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> This pull-request has been approved by: *deads2k
> <https://github.com/kubernetes/kubernetes/pull/48778#issuecomment-317509338>*,
> *fabianofranz
> <https://github.com/kubernetes/kubernetes/pull/48778#issuecomment-317507052>*,
> *juanvallejo <https://github.com/kubernetes/kubernetes/pull/48778#>*, *mbohlool
> <https://github.com/kubernetes/kubernetes/pull/48778#issuecomment-315865990>*
>
> *No associated issue*. Update pull-request body to add a reference to an
> issue, or get approval with /approve no-issue
>
> The full list of commands accepted by this bot can be found here
> <https://github.com/kubernetes/test-infra/blob/master/commands.md>.
> Needs approval from an approver in each of these OWNERS Files:
>
>    - staging/src/k8s.io/client-go/OWNERS
>    <https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/OWNERS>
>    [deads2k]
>
> You can indicate your approval by writing /approve in a comment
> You can cancel your approval by writing /approve cancel in a comment
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/48778#issuecomment-317518108>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABG_pzoyRcn7JG5ngQmZk8ZNlCdCUwKuks5sRObAgaJpZM4OUr_k>
> .
>

2017-07-25 00:35 UTC, juanvallejo commented
/test pull-kubernetes-federation-e2e-gce

2017-07-25 01:04 UTC, merged