Correct the comment in PSP examples.
kubernetes/kubernetes pull request #48862
Opened 2017-07-13 08:59 UTC by gyliu513

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

2017-07-13 09:08 UTC, gyliu513 commented
/cc @liggitt @pweil-

2017-07-13 09:44 UTC, CaoShuFeng requested changes

2017-07-13 09:44 UTC, CaoShuFeng commented on examples/podsecuritypolicy/rbac/bindings.yaml
> +# restricted and privileged.
Good catch!
But I think the group names are:
privileged-psp-users and restricted-psp-users

2017-07-13 10:02 UTC, gyliu513 commented on examples/podsecuritypolicy/rbac/bindings.yaml
> +# restricted and privileged.
I think the whole file is using `restricted` and `privileged`, it is actually saying the group attribute here but not the group name

2017-07-13 10:03 UTC, gyliu513 commented
/retest

2017-07-13 10:44 UTC, CaoShuFeng commented on examples/podsecuritypolicy/rbac/bindings.yaml
> +# restricted and privileged.
LGTM

2017-07-13 11:24 UTC, thockin commented
/approve no-issue
/lgtm

2017-07-13 12:00 UTC, pweil- approved these changes

2017-07-13 14:04 UTC, gyliu513 commented
/test pull-kubernetes-federation-e2e-gce

2017-07-14 17:08 UTC, brendandburns commented
/test pull-kubernetes-federation-e2e-gce

2017-07-14 18:46 UTC, merged