Implement a preflight localhost check - rebase to 1.6
kubernetes/kubernetes pull request #48875
Opened 2017-07-13 14:00 UTC by craigtracey

**What this PR does / why we need it**:
There have been a few instances of users who have had failed kubeadm
runs due to 'localhost' not resolving to an address local to the machine
being deployed. This can happen when the environment's search domain has
an entry for localhost.

This case is addressed in apiserver pull request:
https://github.com/kubernetes/kubernetes/pull/46772

That said, checking for this scenario would be a valuable preflight
check. While this check is primarily implemented for checking the
"localhost," it may be used to check to check whether any name/ip is
local. This functionality could be leveraged by other checks in the
future, but this approach also helps to test this check now.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubeadm/issues/302

**Special notes for your reviewer**:

**Release note**:

```release-note
Add kubeadm preflight check for localhost resolution
```

2017-07-13 20:21 UTC, luxas reviewed
LGTM

I'd like @timothysc to take a look as well

2017-07-13 20:21 UTC, luxas commented on cmd/kubeadm/app/preflight/checks.go
> +		ip, _, err := net.ParseCIDR(li.String())
Why CIDR here? Why not ParseIP?

2017-07-13 20:21 UTC, luxas commented
/ok-to-test

2017-07-13 20:22 UTC, luxas commented
cc @enisoc 

This will warn some users when they have misconfigured DNS...

2017-07-13 20:46 UTC, craigtracey commented
/retest

2017-07-17 01:30 UTC, craigtracey commented on cmd/kubeadm/app/preflight/checks.go
> +		ip, _, err := net.ParseCIDR(li.String())
`net.InterfaceAddrs()` returns addresses in CIDR notation (ie. 172.18.0.1/16), therefore we need to use `net.ParseCIDR()` here.

2017-07-17 01:30 UTC, craigtracey commented
/retest

2017-07-17 21:54 UTC, timothysc requested changes

2017-07-17 21:54 UTC, timothysc commented on cmd/kubeadm/app/preflight/checks.go
> +			return warnings, errors
why do you pass back empty warning vs nil here like in other locations?

2017-07-17 21:54 UTC, timothysc commented on cmd/kubeadm/app/preflight/checks.go
> +				return warnings, errors
again same thing.. vs. nil, nil.

2017-07-18 16:39 UTC, craigtracey commented
@timothysc good catch on both accounts. Not sure how I missed it, but fixed now.

2017-07-18 17:31 UTC, luxas commented
@timothysc PTAL

2017-07-18 21:40 UTC, timothysc approved these changes
/lgtm

2017-07-18 21:44 UTC, timothysc commented
/retest

2017-07-18 23:28 UTC, craigtracey commented
/retest

2017-07-19 02:13 UTC, timothysc commented
/retest

2017-07-19 03:49 UTC, craigtracey commented
/retest

2017-07-19 13:11 UTC, craigtracey commented
/retest

2017-07-19 19:25 UTC, spiffxp commented
/test pull-kubernetes-e2e-kops-aws

2017-07-20 17:43 UTC, luxas commented
cc @enisoc for final approval for v1.6

2017-07-20 19:18 UTC, enisoc commented
This is approved for cherrypick, but it doesn't appear to be copied from master so it needs an `/approve` from someone in cmd/kubeadm/OWNERS.

2017-07-21 09:21 UTC, luxas commented
/approve

2017-07-21 09:21 UTC, luxas commented
@enisoc No, this was targeted directly at v1.6, as v1.7 has fixes this issue we're trying to warn users about

2017-07-21 10:24 UTC, merged