Add sorting to kubectl top
kubernetes/kubernetes pull request #48877
Opened 2017-07-13 14:53 UTC by RemingtonReackhof

```release-note
**What this PR does / why we need it**: This PR  adds functionality to the kubectl top command to sort by a given resource name: name, cpu, or memory.
**Which issue this PR fixes**: Addresses part of #30507
**Special notes for your reviewer**: Due to the way container metrics were added when displaying pods beforehand, I had to refactor the way in which it was being done. I believe it is clearer now than before.
```

2017-07-18 01:20 UTC, pwittrock commented
/unassign

2017-08-01 13:18 UTC, soltysh requested changes

2017-08-01 13:18 UTC, soltysh commented on pkg/kubectl/metricsutil/metrics_sorter.go
> +Copyright 2016 The Kubernetes Authors.
We're in 2017 right now ;)

2017-08-01 13:18 UTC, soltysh commented on pkg/kubectl/cmd/top_node.go
> +	if len(o.SortBy) > 0 && o.SortBy != "name" && o.SortBy != "cpu" && o.SortBy != "memory" {
Maybe use `api.Resource*` constants here.

2017-08-01 13:18 UTC, soltysh commented on pkg/kubectl/cmd/top_node.go
> +			sorting, err := cmd.Flags().GetString("sort-by")
I don't think you need to read that again manually. You've already assinged `SortBy` member to `sort-by` flag.

2017-08-01 13:18 UTC, soltysh commented on pkg/kubectl/cmd/top_node.go
> +			if err != nil {
Not needed, either.

2017-08-01 13:18 UTC, soltysh commented on pkg/kubectl/metricsutil/metrics_printer.go
> +		sort.Sort(containerMetricsSort{allContainers, sorting})
What if `sorting` is empty? Same thing in the else.

2017-08-01 13:19 UTC, soltysh commented
I've left some comments, but wrt overall design I'd defer to @piosz since he was mentoring the previous person working on it and @kubernetes/sig-cli-maintainers

2017-08-02 07:35 UTC, piosz commented
High level looks reasonable. I'm not an owner of this component so I'll let @kubernetes/sig-cli-maintainers to decide.

2017-08-17 10:58 UTC, dims commented
/ok-to-test

2018-01-19 11:08 UTC, jonaz commented
why was this not merged?

2018-01-19 12:23 UTC, dims commented
/reopen

2018-01-19 12:23 UTC, dims commented
looks like it timed out waiting for reviewers

2018-01-25 01:20 UTC, piosz commented
@kubernetes/kubectl-maintainers for review

2018-06-24 03:33 UTC, closed without merging