Use local PX endpoint for mount, unmount, detach and attach calls
kubernetes/kubernetes pull request #48898
Opened 2017-07-13 19:47 UTC by harsh-px

**What this PR does / why we need it**:
This PR fixes an issue with Setup and TearDown of Portworx volumes which has side-effects such a Pod using a Portworx volume not being able to start on the minion.

**Which issue this PR fixes**
This PR addresses an issue that fails to mount, attach, unmount or detach a volume when Kubernetes sends these requests to Portworx when it's API server on that particular minion is down. 

Portworx mount, unmount, attach and detach requests need to be received on the minion where the pod is running. So these calls need to talk to the Portworx API server running locally on that node (and NOT to the Portworx k8s service since it may route the request to any node in the cluster). This PR explicitly makes such requests local only.

**Release note**:
```release-note
NONE
```

2017-07-13 19:59 UTC, harsh-px commented
/assign @gnufied

2017-07-13 20:08 UTC, gnufied requested changes
Some minor nits - mostly lgtm

2017-07-13 20:08 UTC, gnufied commented on pkg/volume/portworx/portworx.go
> +	glog.Infof("Portworx Volume set up. Dir: %s %v %v", dir, !notMnt, err)
Do we really want to log these messages *always* in the log files? Looks to me that, older logging priority was more accurate.

2017-07-13 20:08 UTC, gnufied commented on pkg/volume/portworx/portworx_util.go
> +	driver, err := util.getPortworxDriver(d.plugin.host, false)
Everywhere we add a naked `true` or `false` argument - we should also add a comment of the form `true /*localOnly*/`

2017-07-13 20:08 UTC, gnufied commented on pkg/volume/portworx/portworx_util.go
> +func (util *PortworxVolumeUtil) getPortworxDriver(volumeHost volume.VolumeHost, localOnly bool) (volumeapi.VolumeDriver, error) {
Can you document - what that `localOnly` flag does? Why certain calls supply this as `true` while others as `false` ?

2017-07-13 20:08 UTC, gnufied commented on pkg/volume/portworx/portworx_util.go
> +			glog.Infof("Using portworx local service at: %v as api endpoint", volumeHost.GetHostName())
IMO -  this log message should only appear if verbosity is set to a lower level, not always.

2017-07-13 21:11 UTC, harsh-px commented on pkg/volume/portworx/portworx_util.go
> +	driver, err := util.getPortworxDriver(d.plugin.host, false)
Done in incremental diff

2017-07-13 21:11 UTC, harsh-px commented on pkg/volume/portworx/portworx_util.go
> +func (util *PortworxVolumeUtil) getPortworxDriver(volumeHost volume.VolumeHost, localOnly bool) (volumeapi.VolumeDriver, error) {
Added a function doc in the incremental

2017-07-13 21:12 UTC, harsh-px commented on pkg/volume/portworx/portworx_util.go
> +			glog.Infof("Using portworx local service at: %v as api endpoint", volumeHost.GetHostName())
Changed to `glog.V(4)` in the incremental

2017-07-13 21:15 UTC, harsh-px commented on pkg/volume/portworx/portworx.go
> +	glog.Infof("Portworx Volume set up. Dir: %s %v %v", dir, !notMnt, err)
We have found tracking down events for volume setup and teardown very important in debugging field issues and hence I've changed the logging level. `SetupAt` and `TearDownAt` get invoked only when pods get scheduled on a new node (new pod or existing pod getting re-scheduled). So these logs entries won't be very chatty.

2017-07-14 01:42 UTC, gnufied commented
@k8s-bot ok to test

2017-07-14 04:39 UTC, harsh-px commented
/test pull-kubernetes-node-e2e

2017-07-14 05:09 UTC, harsh-px commented
@gnufied the pull-kubernetes-node-e2e job is failing but this doesn't seem to anything to do with my change. How do we move forward with this?

2017-07-14 05:10 UTC, harsh-px commented
/test pull-kubernetes-node-e2e

2017-07-14 16:44 UTC, harsh-px commented
Re-run of the failing test succeeded.

2017-07-14 19:57 UTC, gnufied commented on pkg/volume/portworx/portworx_util.go
> +func (util *PortworxVolumeUtil) getPortworxDriver(volumeHost volume.VolumeHost, localOnly bool) (volumeapi.VolumeDriver, error) {
I read the docs - and I still don't understand why `CreateDisk` and `DeleteDisk` pass this flag as `false` while others as `true`.

2017-07-14 19:59 UTC, gnufied commented on pkg/volume/portworx/portworx_util.go
> +func (util *PortworxVolumeUtil) getPortworxDriver(volumeHost volume.VolumeHost, localOnly bool) (volumeapi.VolumeDriver, error) {
Feel free to link to some external docs if the context is large enough to fit in a code comment. We frequently do that in AWS and other volume plugins (or we should be doing that).

2017-07-14 20:36 UTC, harsh-px commented on pkg/volume/portworx/portworx_util.go
> +func (util *PortworxVolumeUtil) getPortworxDriver(volumeHost volume.VolumeHost, localOnly bool) (volumeapi.VolumeDriver, error) {
Please see if the update comment gives more context. I have given a high-level context on why create and delete calls can use localOnly as false while other's cannot.

Currently, we don't have external docs describing our internal algorithms (most of them are proprietary.)

2017-07-14 20:43 UTC, gnufied commented
/lgtm

2017-07-14 21:02 UTC, harsh-px commented
/test pull-kubernetes-kubemark-e2e-gce

2017-07-15 00:33 UTC, harsh-px commented
@gnufied Thanks for reviewing this. I am guessing you are the only who adds the approved label?

2017-07-17 14:57 UTC, gnufied commented
/approve

2017-07-17 14:57 UTC, gnufied commented
@harsh-px can you open a github issue and link this PR there?

2017-07-17 17:33 UTC, harsh-px commented
@gnufied Created issue and linked here.

2017-07-17 20:23 UTC, merged

2017-07-17 21:11 UTC, harsh-px commented
@gnufied I need to cherry-pick this into the next 1.7 and 1.6 release. However, the cherry-pick PR would need the milestone label set for these releases in this PR.

What is the process for getting these milestone labels?

2017-07-17 21:36 UTC, gnufied commented
@harsh-px you open the PRs against the branches. Since change here is mostly a bug fix, it would be cherry picked by release manager of those branches.

2017-07-18 15:57 UTC, harsh-px commented
/release-note Fixes an issue where a pod using a Portworx volume gets stuck in ContainerCreating phase.