Removed compatibality code for kubelet 1.2.
kubernetes/kubernetes pull request #48996
Opened 2017-07-16 08:20 UTC by k82cn

**What this PR does / why we need it**:
The next release is 1.8, it's time to remove the backward compatibility code for kubelet 1.2.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48995 

**Release note**:
```release-note
The NodeController will not support kubelet 1.2.
```

2017-07-16 11:24 UTC, xiangpengzhao requested changes
There may be also other v1.1.0 things we want to remove.

2017-07-16 11:24 UTC, xiangpengzhao commented on pkg/controller/node/nodecontroller.go
>  	gracefulDeletionVersion = utilversion.MustParseSemantic("v1.1.0")
Also remove this v1.1.0 thing? And an associated TODO here: https://github.com/k82cn/kubernetes/blob/f6161bffdc9436edc92d435fb2c5258d40ec567a/pkg/controller/node/controller_utils.go#L177

2017-07-17 12:45 UTC, smarterclayton commented
@kubernetes/sig-node-pr-reviews

2017-07-18 09:39 UTC, k82cn commented on pkg/controller/node/nodecontroller.go
>  	gracefulDeletionVersion = utilversion.MustParseSemantic("v1.1.0")
good point; i'll also remove them.

2017-07-24 07:10 UTC, k82cn commented on pkg/controller/node/nodecontroller.go
>  	gracefulDeletionVersion = utilversion.MustParseSemantic("v1.1.0")
done :).

2017-07-24 14:23 UTC, k82cn commented
/retest

2017-07-30 13:03 UTC, k82cn commented
/retest

2017-10-23 14:50 UTC, xiangpengzhao commented
I'm surprised this PR is still not merged :)

2017-10-23 17:27 UTC, yujuhong commented
Need to fix bazel. Otherwise, LGTM

/assign

2017-10-24 02:52 UTC, k82cn commented
done :).

2017-10-24 17:28 UTC, yujuhong commented
Thanks for the cleanup!

/lgtm

I don't have permission to approve though. Ping some folks for approval: @gmarek @dchen1107

2017-10-25 22:52 UTC, dchen1107 commented
/lgtm

2017-10-26 00:37 UTC, merged