Validate ref target
kubernetes/kubernetes pull request #49093
Opened 2017-07-18 08:18 UTC by resouer

Fixes: https://github.com/kubernetes/kubernetes/issues/48588

The usage is like:
```
cluster/kubectl.sh create -f ~/hpa.yaml 
The HorizontalPodAutoscaler "autoscale" is invalid: spec.scaleTargetRef.kind: Invalid value: "DaemonSet": This kind can not be used as auto scaling target
```

```release-note
NONE
```

2017-07-19 11:37 UTC, resouer commented
cc @caesarxuchao  take a look?

2017-07-20 05:10 UTC, thockin commented
Why does DaemonSet support /scale at all?

2017-07-20 08:35 UTC, resouer commented
@thockin I don't think DS support scale, it does not has `replica` filed indeed. Maybe validation is missing here?

2017-07-28 03:02 UTC, resouer commented
ping @caesarxuchao mind to take a look?

2017-07-30 09:12 UTC, resouer commented
ping @lavalamp mind take a look?

2017-07-31 13:56 UTC, dhilipkumars commented on pkg/apis/autoscaling/validation/validation.go
> +	invalidTargets = []string{
How about having a `map[string]struct{}` so that we can avoid the `for` and simply lookup ?

2017-07-31 14:37 UTC, resouer commented on pkg/apis/autoscaling/validation/validation.go
> +	invalidTargets = []string{
Right

2017-07-31 15:15 UTC, DirectXMan12 requested changes
I don't like this.  It seems weird to blacklist
DaemonSet specifically, and we *can't* ever (statically) know the entire list of objects that are scalable.

We could use discovery information, but that's probably a decent amount of refactoring to plumb discovery information down into the validation logic (plus, it makes validation less "constant").

As this stands, I do not think this should be merged.

2017-08-01 01:54 UTC, resouer commented
@DirectXMan12 Thanks for comment.

> we can't ever (statically) know the entire list of objects that are scalable.

Sorry, but isn't scalable a feature by design? I can't see what's vague here, please enlighten me.

>  (plus, it makes validation less "constant").

Exactly. 

Another approach is defining a object meta `unscalable` flag. If it's just a problem of `a decent amount of refactoring`. That's fine. WDYT?

2017-08-01 16:49 UTC, thockin commented
If daemonset doesn't syupport /scale, then HPA simply won't work, right?  Same as if I tried to target a pod or a service.  We're not blacklisting those, though...

if daemonset does support /scale - why?  That seems flat out wrong.

2017-08-01 16:54 UTC, thockin commented
I am closing this - let's discuss a solution in #48588 - I don't think this is the right answer.

2017-08-01 16:54 UTC, closed without merging