fix some typos in api/types
kubernetes/kubernetes pull request #49205
Opened 2017-07-19 14:12 UTC by dixudx

**What this PR does / why we need it**:
Fix some typos in api/types

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

2017-07-19 17:13 UTC, ericchiang commented
These fixes need to be applied to the external versioned APIs too: https://github.com/dixudx/kubernetes/blob/07c2010947d1354b1a917f10d416549e76802881/staging/src/k8s.io/api/core/v1/types.go#L4403

Also, running https://github.com/client9/misspell on that file indicates another spelling error.

```
$ wget https://raw.githubusercontent.com/dixudx/kubernetes/07c2010947d1354b1a917f10d416549e76802881/pkg/api/types.go
$ misspell types.go 
types.go:1126:28: "mulitple" is a misspelling of "multiple"
```

Mind updating the versioned API and running a spell checker against other types.go files as part of this PR?

2017-07-20 20:15 UTC, roberthbailey commented on pkg/api/types.go
> +		uppercase for backwards compatible (since it was falling back to var name of
compatibility

2017-07-20 20:15 UTC, roberthbailey commented
ok to test

2017-07-21 05:27 UTC, dixudx commented
/test pull-kubernetes-verify

2017-07-21 07:19 UTC, dixudx commented
/retest

2017-07-21 08:24 UTC, dixudx commented
@roberthbailey PTAL. Thanks.

2017-07-21 14:53 UTC, roberthbailey commented
/lgtm
/approve

2017-07-21 15:31 UTC, dixudx commented
@lavalamp @brendandburns @smarterclayton @colhom Needs your `/approve no-issue`. Thanks so much.

2017-07-24 23:59 UTC, dixudx commented
@lavalamp @brendandburns @smarterclayton @colhom Needs your /approve no-issue. Thanks so much.

2017-07-25 14:33 UTC, dixudx commented
/cc jbeda

2017-07-25 14:36 UTC, dixudx commented
/cc @jbeda

2017-07-26 01:29 UTC, dixudx commented
/retest

2017-07-26 05:41 UTC, dixudx commented
/retest

2017-07-28 01:15 UTC, dixudx commented
/retest

2017-08-05 10:34 UTC, dixudx commented
/assign @ericchiang

2017-08-05 17:57 UTC, ericchiang commented
/lgtm

2017-08-05 21:10 UTC, jbeda requested changes
We shouldn't be changing actual constants in this PR.

2017-08-05 21:10 UTC, jbeda commented on pkg/apis/certificates/types.go
> +	UsageContentCommittment KeyUsage = "content commitment"
This is more than just a comment and may have compatibility impact.  Note also that the const is misspelled also.

This also lines up with the cloudflare library that this string gets passed to: https://sourcegraph.com/github.com/kubernetes/kubernetes@886e04f1fffbb04faf8a9f9ee141143b2684ae68/-/blob/vendor/github.com/cloudflare/cfssl/config/config.go#L460-461.  I'm guessing that we don't want to change this one.

2017-08-05 21:11 UTC, jbeda commented
@mikedanese Looks like you added `contentCommittment`.  Want to weigh in here?

2017-08-07 01:36 UTC, dixudx commented on pkg/apis/certificates/types.go
> +	UsageContentCommittment KeyUsage = "content commitment"
@jbeda Updated. PTAL. Thanks.

2017-08-14 06:11 UTC, dixudx commented
@ericchiang @jbeda @roberthbailey Updated. PTAL. Thanks.

2017-09-26 05:09 UTC, dixudx commented
ping @ericchiang @jbeda @roberthbailey Rebased. PTAL. Thanks.

2017-10-03 21:13 UTC, jbeda approved these changes

2017-10-03 21:13 UTC, jbeda commented
/lgtm

2017-10-03 21:13 UTC, jbeda commented
Thanks!

2017-10-03 21:48 UTC, mikedanese commented
/approve

2017-10-04 01:44 UTC, dixudx commented
/retest

2017-10-04 01:50 UTC, dixudx commented
/retest

2017-10-04 03:17 UTC, merged

2017-10-04 03:28 UTC, roberthbailey commented
@dixudx - thanks for the fixes and sorry it was such an arduous process to get them merged.