Bailout if we dont find appropriate BlockStorage API
kubernetes/kubernetes pull request #49318
Opened 2017-07-20 18:51 UTC by dims

**What this PR does / why we need it**:

With latest devstack, v1 and v2 are DEPRECATED and v3 is marked
as CURRENT. So we fail to attach the disk, the error message is
shown when one does "kubectl describe pod" but the operator has
to dig into find the problem.

So let's bailout quickly if we can't find the appropriate version
of the API that we support with an explicit error message that
the operator can see how to fix the situation.

Note support for v3 block storage API is being added to gophercloud
and will take a bit of time before we can support it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-07-20 20:57 UTC, dims commented
/retest

2017-07-21 01:06 UTC, dims commented
/retest

2017-07-21 02:30 UTC, NickrenREN commented
/lgtm
/approve no-issue

2017-07-21 02:31 UTC, NickrenREN commented
/approve cancel

2017-07-21 02:32 UTC, NickrenREN commented
Sorry,  glog.Fatalf(...) ?

2017-07-21 02:33 UTC, NickrenREN commented on pkg/cloudprovider/providers/openstack/openstack.go
> +			glog.Fatalf(err_txt)
glog.Fatalf(...) ?

2017-07-21 10:33 UTC, dims commented on pkg/cloudprovider/providers/openstack/openstack.go
> +			glog.Fatalf(err_txt)
yes, basically exit the process as we cannot continue (calls os.Exit) according to
https://github.com/golang/glog/blob/master/glog.go#L1145

2017-07-21 10:34 UTC, dims commented on pkg/cloudprovider/providers/openstack/openstack.go
> +			glog.Fatalf(err_txt)
switched from Fatalf to Fatal since i don't pass any args

2017-07-21 10:53 UTC, dims commented
/retest

2017-07-21 13:53 UTC, NickrenREN commented on pkg/cloudprovider/providers/openstack/openstack.go
> +			glog.Fatalf(err_txt)
Since we exit , the next line ' return ' will not run, right? Is that expected?

2017-07-21 14:48 UTC, dims commented on pkg/cloudprovider/providers/openstack/openstack.go
> +			glog.Fatalf(err_txt)
Right, that's to make the compiler happy since we don't have a return statement at the end of the method

2017-07-22 09:10 UTC, FengyunPan commented
<<Note support for v3 block storage API is being added to gophercloud
<<and will take a bit of time before we can support it.

Currently, we just support v1 and v2, if cinder api version is v3, openstack cloudprovider will fall back to v2. But v1 and v2 are DEPRECATED now, we should support v3, I expect to support v3 as soon as possible. @dims

2017-07-22 12:15 UTC, dims commented
@FengyunPan Right, that's why i don't mention any specific version number in the commit. All we are saying in the log message is that, "auto" did not work and they have to use a specific version in the configuration file. Which will still be valid in the future when auto detection fails.

2017-07-26 01:55 UTC, anguslees commented on pkg/cloudprovider/providers/openstack/openstack.go
> +			glog.Fatal(err_txt)
concur with other reviewers - remove this line.

2017-07-26 01:56 UTC, anguslees requested changes
(otherwise lgtm - explanatory error messages are very useful)

2017-07-26 16:46 UTC, dims commented
/retest

2017-07-26 19:53 UTC, e0ne commented
/lgtm

2017-07-27 02:59 UTC, anguslees commented
/lgtm

2017-07-27 03:44 UTC, NickrenREN commented
/approve no-issue

2017-07-27 12:15 UTC, dims commented
/retest

2017-07-27 14:25 UTC, dims commented
/retest

2017-07-27 15:38 UTC, dims commented
/retest

2017-07-27 17:44 UTC, dims commented
/retest

2017-07-28 11:03 UTC, merged