allow the /version endpoint to pass through
kubernetes/kubernetes pull request #49312
Opened 2017-07-20 17:56 UTC by deads2k

Makes `/version` a normal endpoint which doesn't use gorestful to make it easier to predictably aggregate and pass through to servers which have `/version/foo` endpoints.

@kubernetes/sig-api-machinery-misc

2017-07-21 12:29 UTC, deads2k commented
/test pull-kubernetes-e2e-kops-aws

2017-07-22 00:19 UTC, mbohlool requested changes

2017-07-22 00:19 UTC, mbohlool commented on api/openapi-spec/swagger.json
> -   "/version/": {
Removing an endpoint from OpenAPI spec is a backward incompatible change. Is it possible that an OpenAPI client rely on this?

2017-07-22 23:28 UTC, deads2k commented on api/openapi-spec/swagger.json
> -   "/version/": {
> Removing an endpoint from OpenAPI spec is a backward incompatible change. Is it possible that an OpenAPI client rely on this?

Eh, maybe?  It's not our general intent.  How is generation from something other than gorestful coming?  That library is really problematic.

2017-07-23 05:41 UTC, mbohlool commented on api/openapi-spec/swagger.json
> -   "/version/": {
It is not only OpenAPI. It's old swagger 1.2 too. We need to support it 1.8. After 1.9 release we can remove gorestful along with old swagger 1.2 and have our inhouse http routers or some other libraries. Until then, I don't think it is a good idea to move endpoints outside of gorestful. Can you elaborate on the problem this causes for aggregation?

2017-07-24 11:44 UTC, deads2k commented on api/openapi-spec/swagger.json
> -   "/version/": {
> Can you elaborate on the problem this causes for aggregation?

Subpaths under `/version` are hidden when chaining servers together.  It means that you can't have `/version/apiextensions-apiserver` or `/version/openshift`.

2017-07-24 18:29 UTC, mbohlool commented on api/openapi-spec/swagger.json
> -   "/version/": {
That means those subpaths are not registered with a webservice and does not have Swagger/OpenAPI spec? From the code (both old and new) I can only see registering `/version`. Where do we register `/version/apiextensions-apiserver` etc?

2017-07-24 18:37 UTC, deads2k commented on api/openapi-spec/swagger.json
> -   "/version/": {
> That means those subpaths are not registered with a webservice and does not have Swagger/OpenAPI spec? From the code (both old and new) I can only see registering /version. Where do we register /version/apiextensions-apiserver etc?

`/version/apiextensions-apiserver` is theoretical, but probably necessary at somepoint.  `/version/openshift` exists in the openshift apiserver which is delegated in the chain.

2017-07-24 20:25 UTC, mbohlool commented on api/openapi-spec/swagger.json
> -   "/version/": {
Sorry if I still don't see the problem. `/version/openshift` and `/version/apiextensions-apiserver` can be registered the same way as `/version` in both cases. How gorestful hides those endpoints and the new implementation doesn't?

2017-07-25 13:32 UTC, deads2k commented on api/openapi-spec/swagger.json
> -   "/version/": {
> Sorry if I still don't see the problem. /version/openshift and /version/apiextensions-apiserver can be registered the same way as /version in both cases. How gorestful hides those endpoints and the new implementation doesn't?

gorestful forces a 404 when a request is made the webservice, but not matching a route. Our "normal" mux doesn't do that.

2017-08-02 04:57 UTC, mbohlool commented on api/openapi-spec/swagger.json
> -   "/version/": {
I see. I am going back to my previous question then. That means those subpaths are not registered with a webservice and does not have Swagger/OpenAPI spec? Is it not a better idea to just register them with a webservice?

2017-08-02 05:01 UTC, mbohlool commented on api/openapi-spec/swagger.json
> -   "/version/": {
or if we don't want to limit the tail of the url, we can always use `*` like this example: https://github.com/emicklei/go-restful/blob/master/examples/restful-path-tail.go.

2018-08-23 22:23 UTC, closed without merging