fix error message for pdb.go
kubernetes/kubernetes pull request #49439
Opened 2017-07-22 11:20 UTC by zhangxiaoyu-zidif

**What this PR does / why we need it**:
fix error message for pdb.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

2017-07-22 15:17 UTC, xiangpengzhao requested changes

2017-07-22 15:17 UTC, xiangpengzhao commented on pkg/kubectl/pdb.go
> +		return fmt.Errorf("minAvailable and maxUnavailable cannot be both specified")
It'd be better to use the param names `min-available` and `max-unavailable` here instead of var names in code.

2017-07-22 18:14 UTC, zhangxiaoyu-zidif commented on pkg/kubectl/pdb.go
> +		return fmt.Errorf("minAvailable and maxUnavailable cannot be both specified")
thanks , you are right.=)

2017-07-23 02:49 UTC, cblecker commented
/ok-to-test

2017-07-23 13:46 UTC, zhangxiaoyu-zidif commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-03 09:24 UTC, zhangxiaoyu-zidif commented
@smarterclayton
PTAL

2017-08-08 07:03 UTC, zhangxiaoyu-zidif commented
ping @deads2k 
PTAL

2017-08-09 18:36 UTC, deads2k commented on pkg/kubectl/pdb.go
> +		return fmt.Errorf("min-available and max-unavailable cannot be both specified")
@davidopp I'm not sure if the code is correct or if the string is correct.

2017-08-12 06:08 UTC, zhangxiaoyu-zidif commented on pkg/kubectl/pdb.go
> +		return fmt.Errorf("min-available and max-unavailable cannot be both specified")
/assign davidopp

2017-08-12 06:08 UTC, zhangxiaoyu-zidif commented
/assign davidopp

2017-08-13 08:35 UTC, zhangxiaoyu-zidif commented on pkg/kubectl/pdb.go
> +		return fmt.Errorf("min-available and max-unavailable cannot be both specified")
@deads2k 
![image](https://user-images.githubusercontent.com/5154334/29248217-3265b694-8045-11e7-8bdd-5b47ddac2abd.png)
from : https://kubernetes.io/docs/tasks/run-application/configure-pdb/
I think it is just string error. =)

2017-08-22 02:41 UTC, zhangxiaoyu-zidif commented
ping @davidopp  @deads2k 
PTAL

2017-08-24 09:26 UTC, zhangxiaoyu-zidif commented
@fabianofranz 
PTAL

2017-08-25 19:57 UTC, fabianofranz commented
/lgtm 
/approve no-issue

2017-08-25 21:32 UTC, cblecker commented
/retest

2017-08-25 23:34 UTC, zhangxiaoyu-zidif commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-26 10:24 UTC, merged