Do not try to run preStopHook when the gracePeriod is 0
kubernetes/kubernetes pull request #49449
Opened 2017-07-22 19:37 UTC by dhilipkumars

**What this PR does / why we need it**:
1. Sometimes when the user force deletes a POD with no gracePeriod, its possible that kubelet attempts to execute the preStopHook which will certainly fail.  This PR prevents this inavitable PreStopHook failure.
```
kubectl delete --force --grace-period=0 po/<pod-name>
```
2. This also adds UT for LifeCycle Hooks
```
go test -v --cover --run "Hook" ./pkg/kubelet/kuberuntime/
=== RUN   TestPreStopHook
=== RUN   TestPreStopHook/CMDExec
=== RUN   TestPreStopHook/HTTPGet
=== RUN   TestPreStopHook/NoTimeToRun
--- FAIL: TestPreStopHook (0.00s)
    --- PASS: TestPreStopHook/CMDExec (0.00s)
    --- PASS: TestPreStopHook/HTTPGet (0.00s)
    --- FAIL: TestPreStopHook/NoTimeToRun (0.00s)
        kuberuntime_container_test.go:380: HTTP Should not execute when gracePeriod is 0
FAIL
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
None
```

2017-07-22 19:38 UTC, dhilipkumars commented
cc: @dchen1107 and @derekwaynecarr

2017-07-22 19:42 UTC, dhilipkumars commented
/sig node
/sig app-lifecycle
/area app-lifecycle

2017-07-24 02:40 UTC, dixudx commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +	"strings"
Need running `gofmt`.

2017-07-25 04:18 UTC, dhilipkumars commented
/sig node-reviewers

2017-07-26 01:57 UTC, dhilipkumars commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +	"strings"
they are go fmt'ed but gofmt wouldnt re-arrange imports, now fixed.

2017-07-26 02:10 UTC, dixudx commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +	"strings"
This is not still right. Should use `gofmt` to update.

2017-07-26 02:41 UTC, dhilipkumars commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +	"strings"
okay got the problem, I was doing `go fmt` instead of `gofmt`, now fixed. PTAL

2017-07-28 02:08 UTC, dhilipkumars commented
/kind bug

2017-07-29 01:44 UTC, resouer commented
/ok-to-test

2017-07-29 03:06 UTC, resouer requested changes
Please fix CI first, then I will review

2017-07-29 10:22 UTC, dhilipkumars commented
/test pull-kubernetes-verify
/test pull-kubernetes-bazel

2017-07-29 11:17 UTC, dhilipkumars commented
/test pull-kubernetes-e2e-gce-etcd3

2017-07-29 13:33 UTC, dhilipkumars commented
/test pull-kubernetes-e2e-gce-etcd3

2017-07-29 14:33 UTC, dhilipkumars commented
/test pull-kubernetes-e2e-gce-etcd3

2017-07-29 16:48 UTC, dhilipkumars commented
@resouer looks like a flake the failures are unrelated. 

/test pull-kubernetes-e2e-gce-etcd3

2017-07-29 17:56 UTC, dhilipkumars commented
https://github.com/kubernetes/kubernetes/issues/49761

2017-07-30 07:17 UTC, dhilipkumars commented
/retest

2017-07-30 13:48 UTC, resouer commented
/test pull-kubernetes-e2e-gce-etcd3

2017-07-30 13:48 UTC, resouer approved these changes
lgtm, let's run test again

2017-07-30 14:43 UTC, dhilipkumars commented
@resouer thanks for reviewing.  If the PR is reasonable could you please `lgtm` and `approve no-issue` it, please?
also the recent ci failure looks like a flake again.

2017-07-30 14:50 UTC, resouer commented
/lgtm

2017-07-30 14:50 UTC, resouer commented
But it is required to ask @tallclair to take the final pass and approve this PR.

2017-07-30 14:51 UTC, resouer commented
And please squash your commits

2017-07-30 15:12 UTC, dhilipkumars commented
@resouer Thanks squashed the commits.

2017-07-30 15:52 UTC, dhilipkumars commented
More flakes this time.
/test pull-kubernetes-federation-e2e-gce
/test pull-kubernetes-e2e-kops-aws

2017-07-30 16:22 UTC, dhilipkumars commented
/test pull-kubernetes-e2e-kops-aw

2017-07-31 02:03 UTC, resouer commented
/lgtm

2017-07-31 02:04 UTC, resouer commented
Kindly ping @tallclair @Random-Liu , the code lgtm, please take a final look, thanks!

2017-07-31 02:36 UTC, dhilipkumars commented
/test pull-kubernetes-e2e-kops-aw

2017-08-01 05:34 UTC, dhilipkumars commented
/test pull-kubernetes-e2e-kops-aw

2017-08-01 05:36 UTC, dhilipkumars commented
/retest

2017-08-01 05:54 UTC, resouer commented
The pull-kubernetes-e2e-kops-aws is flake, I noticed it fails in many PRs.

2017-08-01 06:12 UTC, dhilipkumars commented
Flake: https://github.com/kubernetes/kubernetes/issues/48223

2017-08-01 10:37 UTC, dhilipkumars commented
/retest

2017-08-01 18:47 UTC, tallclair reviewed
Just needs a little cleanup, logic looks good.

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/fake_kuberuntime_manager.go
> -
nit: try not to include stray changes like this.

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +		//m.executePreStopHook(testPod, cID, &testPod.Spec.Containers[0], gracePeriod)
delete this

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +			t.Errorf("CMD Prestop hook is no invoked")
s/is no/was not/

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +	//TestCase 1:  Configured and works as expected
Nit: delete the enumeration in the comment (they just become annoying to update when test cases are added). Just the description part is sufficient.

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +		defer func() { gracePeriod = 30 }()
rather than overriding this, just define a local version

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +		//m.executePreStopHook(testPod, cID, &testPod.Spec.Containers[0], gracePeriod)
delete

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +		//Fake all the things you need before trying to create a container
nit: add a space after `//`, here and everywhere.

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +		//Now try to create a container, which should inturn invoke PostStart Hook
nit: s/inturn/in turn/

2017-08-01 18:47 UTC, tallclair commented on pkg/kubelet/kuberuntime/kuberuntime_container_test.go
> +	//TearDown
delete

2017-08-02 04:49 UTC, dhilipkumars commented
@tallclair Thanks for the review, could you PTAL now?

2017-08-02 22:10 UTC, tallclair commented
Thanks for the clean up.

/lgtm

2017-08-02 22:11 UTC, tallclair commented
/lgtm cancel

Please squash your commits.

2017-08-03 02:27 UTC, dhilipkumars commented
@tallclair Done.

2017-08-03 03:25 UTC, dhilipkumars commented
/test pull-kubernetes-e2e-kops-aws

2017-08-03 03:49 UTC, dhilipkumars commented
/retest

2017-08-03 18:16 UTC, tallclair commented
/lgtm

2017-08-03 18:17 UTC, tallclair commented
I've updated this with a release note, because it is user facing behavior.

/approve no-issue

2017-08-03 23:43 UTC, merged