kubeadm: Make sure --config can be mixed with --skip-* flags
kubernetes/kubernetes pull request #49498
Opened 2017-07-24 14:50 UTC by luxas

**What this PR does / why we need it**:

fixes: https://github.com/kubernetes/kubeadm/issues/352

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Should be a cherrypick candidate

**Release note**:

```release-note
kubeadm: Fixes a small bug where `--config` and `--skip-*` flags couldn't be passed at the same time in validation.
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @ericchiang @wojtek-t

2017-07-24 14:50 UTC, luxas commented
cc @mattmoyer

2017-07-24 15:13 UTC, timothysc requested changes
Minor comment, the code is not super friendly to read.  I would prefer to output the flags that were bad.

2017-07-24 15:13 UTC, timothysc commented on cmd/kubeadm/app/apis/kubeadm/validation/validation.go
> +		flagsAllowedToChangeWithConfig := []string{"skip-preflight-checks", "skip-token-print"}
Can't you just check to see if the flags are anything other then these two and output an error indicating the flags they specified?

2017-07-24 16:23 UTC, ericchiang commented on cmd/kubeadm/app/apis/kubeadm/validation/validation.go
> +		flagsAllowedToChangeWithConfig := []string{"skip-preflight-checks", "skip-token-print"}
You probably want Flagset.Visit https://godoc.org/github.com/spf13/pflag#FlagSet.Visit

```go
mixedFlags := []string{}
flag.Visit(func(f &pflag.Flag) {
    if f.Name == "config" || strings.HasPrefix(f.Name, "skip-") {
        // "skip=*" flags can be set with --config
        continue
    }
    mixedFlags = append(mixedFlags, f.Name)
})
```

2017-07-24 20:52 UTC, luxas commented
/retest

2017-07-24 21:56 UTC, timothysc approved these changes
/lgtm - thx for the change, much easier to read.

2017-07-24 21:56 UTC, luxas commented
/retest

2017-07-25 07:38 UTC, luxas commented
/retest

2017-07-25 09:43 UTC, merged