add some e2e for node authz
kubernetes/kubernetes pull request #49869
Opened 2017-07-31 10:48 UTC by wanghaoran1988

**What this PR does / why we need it**:
fix #47174
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47174

**Special notes for your reviewer**:

**Release note**:
```
None
```

2017-07-31 10:48 UTC, wanghaoran1988 commented
/cc @luxas

2017-07-31 10:49 UTC, wanghaoran1988 commented
/unassign @janetkuo
/unassign @spxtr
/assign @luxas

2017-07-31 15:08 UTC, luxas requested changes
Thanks @wanghaoran1988 for working on this!

When I wrote up the issue for this, I imagined that this would actually be written using the normal Go client, not exec out to kubectl. The kubectl commands I had there were for PoC and reference of something that could be implemented.

What does @kubernetes/sig-auth-pr-reviews think?
My opinion is that this should use the Go client as pretty much everything else.

2017-07-31 15:08 UTC, luxas commented
Please fix up bazel/verify/unit tests as well

2017-08-01 04:21 UTC, ericchiang commented
@wanghaoran1988 client-go has impersonation config that can be used to act as arbitrary users in the system. Might be a good place to start https://godoc.org/k8s.io/client-go/rest#Config

You can do actual inspection of the error codes that way and avoid patterns like inspecting the stderr.

```
Expect(err).ShouldNot(ContainSubstring("not found"))
```

2017-08-03 04:53 UTC, wanghaoran1988 commented
@ericchiang Thanks for your suggestions,  @luxas  Updated using the rest client, PTAL

2017-08-03 06:12 UTC, luxas approved these changes
Thanks @wanghaoran1988!
Overall looks great, increases our coverage drastically compared to what we have now (exactly 0 e2e tests on this) :smile:

I had some nits, please fixup and I'll re-review

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +		asUser = "system:node:" + nodeName
isn't there any helper function we can already use here for this task?

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +	var asGroup string = "system:nodes"
I'm pretty sure this exists as a constant somewhere

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +var _ = SIGDescribe("[Feature:NodeAuthz]", func() {
nit: spell out the whole `NodeAuthorizer`

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +		By("Creating a kubernetes client that impersonate a node")
nit: impersonates a node

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +	var c clientset.Interface
should this be more describing, like `nodeImpersonatedClient`? That's probably too long...
Maybe just add a comment above `c` about what it does...

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +	It("A node shouldn't be able to create/delete an other node", func() {
Can we split this in two separate cases please?

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +		f.ClientSet.CoreV1().Pods(ns).Create(pod)
maybe you should return err here and add one more `Expect(err).NotTo(HaveOccurred())`?

2017-08-03 06:12 UTC, luxas commented on test/e2e/auth/framework.go
> +func SIGDescribe(text string, body func()) bool {
Add `// SIGDescribe prepends the name of the current SIG (sig-auth) that is owning the e2e tests in this folder` or something like that

2017-08-03 06:12 UTC, luxas commented on hack/.golint_failures
> +test/e2e/auth
Can you please make golint pass for the new code here or is there anything blocking that?

2017-08-03 07:10 UTC, wanghaoran1988 commented on hack/.golint_failures
> +test/e2e/auth
I'd like to add here like other pkg, one problem is that golint do not allow dot impots like:
```
. "github.com/onsi/ginkgo"
. "github.com/onsi/gomega"
```

2017-08-03 07:14 UTC, wanghaoran1988 commented on test/e2e/auth/node_authz.go
> +	It("A node shouldn't be able to create/delete an other node", func() {
sure

2017-08-03 07:14 UTC, wanghaoran1988 commented on test/e2e/auth/node_authz.go
> +		f.ClientSet.CoreV1().Pods(ns).Create(pod)
good catch

2017-08-03 07:28 UTC, luxas commented on hack/.golint_failures
> +test/e2e/auth
Ah, ok, then I see why all other e2e's are here. Didn't know golint was so picky.

2017-08-03 07:30 UTC, luxas approved these changes
/lgtm
Thanks!

2017-08-03 16:07 UTC, luxas commented
cc @kubernetes/sig-auth-pr-reviews 
PTAL @liggitt

2017-08-03 17:00 UTC, liggitt commented on test/e2e/auth/node_authz.go
> +		err = f.WaitForPodRunning("pause")
the pod doesn't have to be running to verify the node has access

2017-08-03 17:00 UTC, liggitt commented on test/e2e/auth/node_authz.go
> +		_, err = c.CoreV1().Secrets(ns).Get(defaultSaSecret, metav1.GetOptions{})
should put this in a retry loop... access depends on the authorizer graph observing the pod

2017-08-03 17:02 UTC, liggitt commented on test/e2e/auth/node_authz.go
> +		pod := &v1.Pod{
I'm not sure how ginkgo parallelizes tests, but this should probably be more of a standalone test, which means creating a secret specifically for this test, ensuring the node has no access, then creating the pod and ensuring the node has access.

2017-08-03 17:03 UTC, liggitt commented on test/e2e/auth/node_authz.go
> +var _ = SIGDescribe("[Feature:NodeAuthorizer]", func() {
do any tests actually enable this feature? if not, this hasn't really increased our coverage.

2017-08-03 17:52 UTC, liggitt commented
https://github.com/kubernetes/kubernetes/pull/48966 moves auth-related e2e's into a subpackage... I would wait until that merges, then rebase on master

2017-08-03 18:09 UTC, luxas commented on test/e2e/auth/node_authz.go
> +var _ = SIGDescribe("[Feature:NodeAuthorizer]", func() {
@liggitt the kubeadm job will right after this is merged

2017-08-14 19:58 UTC, ericchiang commented
https://github.com/kubernetes/kubernetes/pull/48966 has now merged so I think this PR is unblocked once the merge conflicts are resolved.

2017-08-15 09:45 UTC, wanghaoran1988 commented
@luxas @liggitt PR rebased and addressed the comments

2017-08-15 11:28 UTC, luxas reviewed
Two comments that should be fixed before merge yet

2017-08-15 11:28 UTC, luxas commented on test/e2e/auth/node_authz.go
> +								SecretName: "node-auth-secret",
this should be `secret.ObjectMeta.Name`

2017-08-15 11:28 UTC, luxas commented on test/e2e/auth/node_authz.go
> +			_, err = c.CoreV1().Secrets(ns).Get(defaultSaSecret, metav1.GetOptions{})
this should be `secret.ObjectMeta.Name`

2017-08-15 23:28 UTC, ericchiang commented on test/e2e/auth/node_authz.go
> +				return false, err
Returning here will cause wait.Poll to exit with a non-nil error code. Same with Failf. Isn't the intent to retry after a first initial failure?

This should probably just log the error and `return false, nil`, right?

2017-08-16 02:44 UTC, wanghaoran1988 commented on test/e2e/auth/node_authz.go
> +				return false, err
Good catch, thanks.

2017-08-16 10:58 UTC, luxas approved these changes
/lgtm

2017-08-16 18:33 UTC, ericchiang commented on test/e2e/auth/node_authz.go
> +				framework.Failf("Failed to get secret %v, err: %v", secret.Name, err)
This is still Failf

2017-08-16 21:12 UTC, luxas commented on test/e2e/auth/node_authz.go
> +				framework.Failf("Failed to get secret %v, err: %v", secret.Name, err)
Yeah, that'd be a bug. Sharp eye. @wanghaoran1988 please fix

2017-08-16 21:16 UTC, ericchiang commented
Approving. Please feel free to lgtm once that bug is fixed.

/approve

2017-08-17 01:55 UTC, wanghaoran1988 commented
fixed

2017-08-17 06:17 UTC, luxas commented
/lgtm

Let's get this enabled for kubeadm and we'll see how it goes :)

2017-08-17 07:58 UTC, merged