adding kube-controller-manager starting option tests
kubernetes/kubernetes pull request #50006
Opened 2017-08-02 10:26 UTC by huangjiuyuan

**What this PR does / why we need it**:
The unit test for kube-controller-manager is missing in `cmd/kube-controller-manager/app/options`. I have added a unit test for checking kube-controller-manager starting options, which is similar to the unit test in `cmd/kube-apiserver/app/options/options_test.go`. This PR https://github.com/kubernetes/kubernetes/pull/49092 can be seen as a reference.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

`NONE`

2017-08-07 01:03 UTC, huangjiuyuan commented
Hi, @wojtek-t 
Could you please take a look at this one?

2017-08-17 16:20 UTC, xiangpengzhao commented
/release-note-none
/ok-to-test

2017-08-19 02:24 UTC, huangjiuyuan commented
Hi @xiangpengzhao 
Could you please take a quick look at this?

2017-08-19 02:58 UTC, xiangpengzhao requested changes
just one nit. otherwise LGTM.

2017-08-19 02:58 UTC, xiangpengzhao commented on cmd/kube-controller-manager/app/options/options_test.go
> +Copyright 2014 The Kubernetes Authors.
2017

2017-08-19 10:11 UTC, huangjiuyuan commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-19 12:19 UTC, huangjiuyuan commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-19 17:45 UTC, huangjiuyuan commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-20 01:34 UTC, huangjiuyuan commented
@xiangpengzhao Good to go?

2017-08-22 02:11 UTC, huangjiuyuan commented
@wojtek-t

2017-08-27 02:02 UTC, huangjiuyuan commented
@wojtek-t

2017-09-01 02:49 UTC, huangjiuyuan commented
/retest

2017-09-01 10:49 UTC, huangjiuyuan commented
/retest

2017-09-06 02:18 UTC, huangjiuyuan commented
Hi, @sttts 
Could you please take a look at this? Thank you!

2017-09-06 09:28 UTC, sttts commented
/ok-to-test

2017-09-06 09:28 UTC, sttts commented
/lgtm
/approve no-issue

2017-09-08 03:19 UTC, huangjiuyuan commented
/retest

2017-09-08 05:57 UTC, huangjiuyuan commented
@sttts Some tests failed and I had changed a little bit. Could you please approve again?

2017-09-08 08:05 UTC, sttts commented
/lgtm
/approve no-issue

2017-09-08 08:56 UTC, huangjiuyuan commented
@wojtek-t Could you please approve this one? It seems that This PR is still not approved.

2017-09-12 02:39 UTC, huangjiuyuan commented
/retest

2017-09-12 02:41 UTC, huangjiuyuan commented
/approve no-issue

2017-09-12 02:43 UTC, huangjiuyuan commented
/assign @wojtek-t

2017-09-12 05:23 UTC, huangjiuyuan commented
/retest

2017-09-13 06:10 UTC, huangjiuyuan commented
/retest

2017-09-13 13:38 UTC, wojtek-t commented
/approve no-issue

2017-09-23 11:02 UTC, merged