Hugetlbfs support based on empty dir volume plugin
kubernetes/kubernetes pull request #50072
Opened 2017-08-03 08:24 UTC by squall0gd

**What this PR does / why we need it**: Support for huge pages in empty dir volume plugin. More information about hugepages can be found [here](https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Support for Huge pages in empty_dir volume plugin
[Huge pages](https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt) can now be used with empty dir volume plugin.
```

2017-08-03 09:14 UTC, dixudx commented on pkg/volume/empty_dir/empty_dir.go
> +	if ed.size == "" {
Does this mean that if we are using `StorageMediumHugetlbfs`, the `size` is also needed alongside?

If so, you'd better add some validations in `pkg/api/validation/validation.go`.

2017-08-03 09:14 UTC, dixudx commented on pkg/api/types.go
> +	HugetlbfsSize string
It's kind of confusing to declare xxSize as `string`. May it be `int`?

2017-08-03 09:14 UTC, dixudx commented on pkg/volume/empty_dir/empty_dir.go
> +	size          string
Same as above. Maybe `int`?

2017-08-03 11:39 UTC, squall0gd commented on pkg/volume/empty_dir/empty_dir.go
> +	if ed.size == "" {
It's required in that case. I will move this validation to `pkg/api/validation/validation.go`

2017-08-03 11:39 UTC, squall0gd commented on pkg/volume/empty_dir/empty_dir.go
> +	size          string
I think it's better to use `Quantity` here b/c I need to keep unit.

2017-08-03 11:40 UTC, squall0gd commented on pkg/api/types.go
> +	HugetlbfsSize string
I'll use `Quantity` here :)

2017-08-03 11:41 UTC, squall0gd commented on staging/src/k8s.io/api/core/v1/types.go
> +	HugetlbfsSize string `json:"hugetlbfsSize,omitempty" protobuf:"bytes,3,opt,name=hugetlbfsSize"`
:+1:

2017-08-03 11:55 UTC, xiangpengzhao commented
@squall0gd FYI, there is a proposal on HugePages here: https://github.com/kubernetes/community/pull/837

/cc @derekwaynecarr

2017-08-09 04:15 UTC, derekwaynecarr commented
i want to make sure we have agreement on the proposal referenced before merging this, but thank you for your help!

2017-08-09 04:15 UTC, derekwaynecarr commented
/ok-to-test

2017-08-09 07:54 UTC, derekwaynecarr commented on pkg/api/types.go
> +	HugetlbfsSize string
+1 to quantity

2017-08-09 07:54 UTC, derekwaynecarr commented on pkg/api/types.go
> +	StorageMediumHugetlbfs StorageMedium = "Hugetlbfs" // use hugepages
prefer HugePages

2017-08-09 07:59 UTC, derekwaynecarr commented on pkg/volume/empty_dir/empty_dir.go
> +	mountOptions := []string{fmt.Sprintf("size=%s", ed.size)}
i don't understand why you have size.

size is bounded by sum resource requirement across containers on pod.

we need a new field specific for hugepages that aligns with pagesize. mount option.

2017-08-09 16:33 UTC, squall0gd commented on pkg/volume/empty_dir/empty_dir.go
> +	mountOptions := []string{fmt.Sprintf("size=%s", ed.size)}
well I've used `size` w/o any reason - just want some, easy to track parameter, to verify that passing mount options is working correctly. Actually I'm waiting for proposal's merge to finalize implementing mount options and to play with unit tests. :)

2017-08-17 14:03 UTC, PiotrProkop commented on pkg/volume/empty_dir/empty_dir.go
> +	"github.com/Azure/azure-sdk-for-go/arm/resources/resources"
Please fix this import.

2017-08-17 14:03 UTC, PiotrProkop commented on pkg/volume/empty_dir/empty_dir.go
> +	//pagesize := resource.Quantity{}
delete this line

2017-08-17 14:03 UTC, PiotrProkop commented on pkg/volume/empty_dir/empty_dir.go
> +	mountOptions := []string{}
Please add a comment why mountOptions are empty.

2017-08-17 16:47 UTC, rootfs commented on pkg/volume/empty_dir/empty_dir.go
> +
remove blank line

2017-08-17 16:53 UTC, rootfs commented
can you add unit test cases too?

2017-08-18 09:46 UTC, squall0gd commented
/test pull-kubernetes-e2e-kops-aws

2017-08-18 09:47 UTC, squall0gd commented
/test pull-kubernetes-unit

2017-08-18 11:37 UTC, squall0gd commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-18 12:33 UTC, squall0gd commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-22 11:52 UTC, squall0gd commented
/test pull-kubernetes-e2e-kops-aws

2017-08-22 13:48 UTC, squall0gd commented
/retest

2017-08-22 15:10 UTC, squall0gd commented
/retest

2017-08-25 13:22 UTC, derekwaynecarr commented
I would like https://github.com/kubernetes/kubernetes/pull/50859 to merge before this.

2017-08-31 11:38 UTC, squall0gd commented
/retest

2017-08-31 17:27 UTC, PiotrProkop commented
/retest

2017-08-31 19:34 UTC, derekwaynecarr requested changes
please rebase against https://github.com/kubernetes/kubernetes/pull/50859

as part of that rebase, ensure that usage of the HugePages medium in an EmptyDir is restricted by the feature gate flag during pod validation so we can prevent usage of the medium to only the feature being enabled.

2017-08-31 19:34 UTC, derekwaynecarr commented on examples/volumes/empty_dir/README.md
> +# EmptyDir volume plugin with HugePages medium
we can provide an example in a follow-on, split this into a separate pr that is a follow-on.

2017-08-31 19:34 UTC, derekwaynecarr commented on pkg/api/types.go
> +	StorageMediumHugepages StorageMedium = "Hugepages" // use hugepages
s/Hugepages/HugePages per https://github.com/kubernetes/community/blob/master/contributors/design-proposals/hugepages.md#pod-specification

2017-08-31 19:34 UTC, derekwaynecarr commented on pkg/volume/empty_dir/empty_dir.go
> +	// TODO: reuse this const from "pkg/api/types.go" when PR #50859 got merged
rebase against https://github.com/kubernetes/kubernetes/pull/50859 as it looks like its stabilized.

2017-08-31 19:35 UTC, derekwaynecarr commented
/assign @childsb @eparis -- once the updates above are made, i am going to need eyes here.

2017-08-31 21:55 UTC, PiotrProkop commented
I cherry-picked commits from #50859 and applied @derekwaynecarr comments.

2017-09-01 15:21 UTC, derekwaynecarr commented on pkg/volume/empty_dir/empty_dir.go
> +	// TODO: reuse this const from "pkg/api/types.go" when PR #50859 got merged
nit: this was missed.

2017-09-01 15:31 UTC, derekwaynecarr commented
just the one nit that can be done in follow-on, otherwise this is good for me.

will want someone from storage sig to look.

/cc @childsb @eparis

2017-09-01 15:32 UTC, derekwaynecarr approved these changes

2017-09-01 15:32 UTC, derekwaynecarr commented
/test pull-kubernetes-e2e-gce-bazel

2017-09-01 15:49 UTC, PiotrProkop commented
Thanks for review @derekwaynecarr , I have just deleted that const.

2017-09-01 15:52 UTC, wongma7 commented on pkg/volume/empty_dir/empty_dir.go
> +	// If the directory is a mountpoint with medium memory, there is no
"medium hugepages"

2017-09-01 15:55 UTC, wongma7 commented
emptydir changes lgtm, jsut comment nit

2017-09-01 15:57 UTC, PiotrProkop commented on pkg/volume/empty_dir/empty_dir.go
> +	// If the directory is a mountpoint with medium memory, there is no
OK fixing it :D

2017-09-01 18:55 UTC, squall0gd commented
/retest

2017-09-01 21:25 UTC, childsb commented
/approve

2017-09-01 21:51 UTC, derekwaynecarr commented
/lgtm

Thanks @squall0gd for your help getting this support.

2017-09-02 06:08 UTC, PiotrProkop commented
/retest

2017-09-02 08:36 UTC, PiotrProkop commented
/test pull-kubernetes-e2e-kops-aws

2017-09-02 11:49 UTC, squall0gd commented
/retest

2017-09-02 16:11 UTC, squall0gd commented
/retest

2017-09-05 15:29 UTC, eparis commented
/lgtm

2017-09-05 17:46 UTC, squall0gd commented
/retest

2017-09-05 20:28 UTC, merged

2017-09-05 21:48 UTC, jdumars commented
Curious how this got merged despite failing cross:
I0905 18:14:23.457] pkg/volume/empty_dir/empty_dir_linux.go:54: constant 2508478710 overflows int32
@squall0gd did this error always present in testing and it just got missed?

2017-09-05 21:55 UTC, squall0gd commented
@jdumars didn't notice this error before. Just some timeouts on e2e gates

2017-09-05 22:00 UTC, jdumars commented
The test will need to be updated in order to accommodate the change.

2017-09-05 22:12 UTC, squall0gd commented
@jdumars Well it looks like we need to add type to magic number constant. Sadly we need to do this in another PR.

2017-09-05 22:27 UTC, liggitt commented
opened https://github.com/kubernetes/kubernetes/pull/51984 to type-cast the comparison to the constant