Support AWS ECR credentials in China
kubernetes/kubernetes pull request #50108
Opened 2017-08-03 20:41 UTC by zzq889

**What this PR does / why we need it**:
Resolve AWS ECR credentials bug in China region

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Nope

**Special notes for your reviewer**:

**Release note**:

```release-note
```
Support AWS ECR credentials in AWS China region

2017-08-03 20:51 UTC, zzq889 commented
/assign @deads2k I have some problem with this PR. Could you help me to review it?

2017-08-03 21:07 UTC, therc commented
Whoa, it's kinda crazy that they went for a separate domain, but I can see why. Is there any Amazon documentation? Even amazonaws.cn does not mention it.

2017-08-03 21:08 UTC, therc commented on pkg/credentialprovider/aws/aws_credentials.go
> +const chinaRegistryURLTemplate = "*.dkr.ecr.%s.amazonaws.com.cn"
Is it amazonaws.com.cn or amazonaws.cn?

2017-08-03 21:14 UTC, zzq889 commented on pkg/credentialprovider/aws/aws_credentials.go
> +const chinaRegistryURLTemplate = "*.dkr.ecr.%s.amazonaws.com.cn"
I'm sure is `amazonaws.com.cn`.

<img width="531" alt="screen shot 2017-08-04 at 5 13 49 am" src="https://user-images.githubusercontent.com/685488/28944073-b869238a-78d3-11e7-8879-395967d625c2.png">

2017-08-03 21:32 UTC, therc commented on pkg/credentialprovider/aws/aws_credentials.go
> +const chinaRegistryURLTemplate = "*.dkr.ecr.%s.amazonaws.com.cn"
Thanks, it just looked weird, given that the site is on amazonaws.cn...

I kinda verified that at least the domain seems to resolve and point to a proxy to somewhere...
```

2017-08-03 21:33 UTC, therc approved these changes

2017-08-03 21:38 UTC, zzq889 commented on pkg/credentialprovider/aws/aws_credentials.go
> +const chinaRegistryURLTemplate = "*.dkr.ecr.%s.amazonaws.com.cn"
amazonaws.cn is kind like aws.amazon.com for web visit and amazonaws.com.cn is the mirror site for amazonaws.com. It's really painful here to deal with the GFW related problems.

2017-08-04 11:23 UTC, zzq889 commented
/assign @deads2k

2017-08-04 11:23 UTC, zzq889 commented
Should I wait for the ok-to-test?

2017-08-04 11:49 UTC, zzq889 commented
/approve no-issue

2017-08-05 03:57 UTC, zzq889 commented
/assign @erictune @liggitt

2017-08-07 08:51 UTC, zzq889 commented
/ok-to-test

2017-08-07 08:53 UTC, zzq889 commented
@therc can you type ok-to-test?

2017-08-07 12:19 UTC, therc commented
/ok-to-test

2017-08-07 12:27 UTC, therc commented
@k8s-bot ok to test

2017-08-07 12:28 UTC, therc commented
@k8s-bot test this

2017-08-07 13:08 UTC, liggitt commented
I'm not familiar enough with aws to know if this is reasonable to assume, or just happens to work (also, are there other geos this same change is needed for?). will defer to @kubernetes/sig-aws-misc

2017-08-07 13:35 UTC, therc commented on pkg/credentialprovider/aws/aws_credentials.go
> +	return fmt.Sprintf(chinaRegistryURLTemplate, region)
These are swapped

2017-08-07 13:37 UTC, therc commented
@liggitt this is reasonable to assume (I wrote the original ECR code). It shouldn't be needed for other regions. China is a special case, because of ICP licensing and so on. @zzq889 can you add a test?

2017-08-07 13:45 UTC, therc requested changes
You can add the .cn domain in otherRegistries in the aws_credentials_test.go:TestEcrProvide test. Even better, you can change the test to try verify that it works with both the existing lala-land-1 region and cn-foo-1.

2017-08-08 03:31 UTC, zzq889 commented
@therc Sure. I'm working on it.

2017-08-08 04:24 UTC, zzq889 commented
@liggitt depends on https://github.com/aws/aws-sdk-go/blob/b7eb6853a2d4bf9238b6613874d62006e0d6c27a/models/endpoints/endpoints.json aws currently has three kind of regions: `AWS Standard`, `AWS GovCloud (US)`, `AWS China`

2017-08-08 04:53 UTC, zzq889 commented
/retest

2017-08-08 04:57 UTC, zzq889 commented
@therc I've update the code and testcase. Is ok-to-test still required for retest?

2017-08-09 05:40 UTC, zzq889 commented
@therc Even if I revert the code I still got test fail:
```
--- FAIL: TestEcrProvide (0.00s)
	aws_credentials_test.go:83: Didn't find expected URL: 123456789012.dkr.ecr.lala-land-1.amazonaws.com/foo/bar
FAIL
```
Any ideas?

2017-08-31 15:13 UTC, justinsb commented
/lgtm

/retest

I also can't see the reason for the test failure, but if the restest doesn't get it I can fire it up in a debugger

2017-09-01 02:47 UTC, justinsb commented
@zzq889 awsStandardDNSSuffix should be amazonaws.com:

```
-const awsStandardDNSSuffix = "amazon.com"
+const awsStandardDNSSuffix = "amazonaws.com"
```

2017-09-04 15:55 UTC, lareeth commented
Any chance this can be added into a 1.6 release as well?

2017-10-16 09:41 UTC, lareeth commented
@deads2k Any idea when this can be approved? This is super critical for running in China.

2017-10-16 13:08 UTC, deads2k commented
> @deads2k Any idea when this can be approved? This is super critical for running in China.

I see the comment as outstanding: https://github.com/kubernetes/kubernetes/pull/50108#issuecomment-326473815

Also, needs a squash.

2017-10-16 13:14 UTC, lareeth commented
@zzq889 When do you plan to make this fix? #50108

2017-11-14 17:38 UTC, lareeth commented
@zzq889 Any update? Its been a month.

2017-11-15 08:27 UTC, zzq889 commented
I use this [container](https://github.com/mixslice/ecr-dockercfg-refresh) and wrote a [cronjob](https://github.com/mixslice/trident/blob/master/addons/ecr-dockercfg-refresh/ecr-dockercfg-refresh.yml) for replacement.

This pull request didn't pass the test with unknown reasons which may exist before I fork. I'll rebase and submit ag.

2017-11-15 08:41 UTC, zzq889 commented
/retest

2017-11-15 08:49 UTC, zzq889 commented
```
I1115 08:42:08.488] process 23 exited with code 0 after 0.1m
I1115 08:42:08.489] Call:  git checkout -B test c3e4084066105ff632668deb3732cdb276b0e622
W1115 08:42:08.713] Reset branch 'test'
I1115 08:42:08.716] process 35 exited with code 0 after 0.0m
I1115 08:42:08.717] Call:  git merge --no-ff -m 'Merge +refs/pull/50108/head:refs/pr/50108' 65bed1d982c10b386ddcc3ea899501df448f8565
W1115 08:42:08.732] merge: 65bed1d982c10b386ddcc3ea899501df448f8565 - not something we can merge
E1115 08:42:08.733] Command failed
```
What I need to do with this error? @justinsb

2017-11-17 02:33 UTC, justinsb commented
/retest

That just looks like a test flake

2017-11-17 02:35 UTC, justinsb commented
/lgtm

2017-11-17 09:12 UTC, zzq889 commented
/assign @deads2k

2017-11-17 15:43 UTC, deads2k commented
/approve no-issue

2017-11-17 21:34 UTC, merged