Fix typos in kubefed
kubernetes/kubernetes pull request #50131
Opened 2017-08-04 06:33 UTC by m1093782566

**What this PR does / why we need it**:

Fix some typos in kubefed.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-08-04 23:33 UTC, cblecker commented
/ok-to-test
/release-note-none

2017-08-08 03:21 UTC, m1093782566 commented
/assign @madhusudancs

2017-08-11 05:31 UTC, madhusudancs requested changes

2017-08-11 05:31 UTC, madhusudancs commented on federation/pkg/kubefed/init/init_test.go
> -		// We can't do a regular pointer deref shallow copy because
This is intentional and a well understood abbreviation. I would leave it as it was before.

2017-08-11 05:31 UTC, madhusudancs commented on federation/pkg/kubefed/init/init_test.go
> -		// We can't do a regular pointer deref shallow copy because
Same as above.

2017-08-11 05:31 UTC, madhusudancs commented on federation/pkg/kubefed/join.go
> -			// 2. `SecretGeneratorV1` requires LiteralSources in a string-ified
This is intentional too.  It means making something a string. I would leave this as it was before too.

2017-08-11 06:27 UTC, m1093782566 commented on federation/pkg/kubefed/init/init_test.go
> -		// We can't do a regular pointer deref shallow copy because
oops, I didn't realize it. It's fixed now. PTAL. Thnaks!

2017-08-11 06:27 UTC, m1093782566 commented on federation/pkg/kubefed/init/init_test.go
> -		// We can't do a regular pointer deref shallow copy because
oops, I didn't realize it. It's fixed now. PTAL. Thnaks!

2017-08-11 06:27 UTC, m1093782566 commented on federation/pkg/kubefed/join.go
> -			// 2. `SecretGeneratorV1` requires LiteralSources in a string-ified
oops, I didn't realize it. It's fixed now. PTAL. Thnaks!

2017-08-11 06:28 UTC, m1093782566 commented
Glad to receive your feedback, @madhusudancs 

Comments are fixed now. Could you please take a look again?

2017-08-11 07:10 UTC, m1093782566 commented
/test pull-kubernetes-kubemark-e2e-gce

2017-08-24 01:58 UTC, m1093782566 commented
ping @madhusudancs ~

2017-08-24 03:51 UTC, madhusudancs commented
/lgtm
/approve no-issue

2017-08-24 03:51 UTC, madhusudancs approved these changes

2017-08-25 10:16 UTC, merged