remove defaulting for obj.Spec.Selector
kubernetes/kubernetes pull request #50164
Opened 2017-08-04 18:57 UTC by crimsonfaith91

**What this PR does / why we need it**:
This PR removes defaulting codes for `obj.Spec.Selector`. Currently, `obj.Spec.Selector.MatchLabels` is set to `obj.Spec.Template.Labels` if `obj.Spec.Template.Labels != nil && obj.Spec.Selector == nil`. We should not perform this defaulting operation as controllers selectors are immutable.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This PR only removes the defaulting codes. Validation code changes will be addressed in another PR.

**Release note**:

```NONE
```

2017-08-04 18:58 UTC, crimsonfaith91 commented
/assign @kow3ns

2017-08-04 18:58 UTC, crimsonfaith91 commented
/unassign @jianhuiz @tallclair

2017-08-04 19:04 UTC, crimsonfaith91 commented on pkg/apis/apps/v1beta2/defaults_test.go
> -		if test.expectSelector != reflect.DeepEqual(rs2.Spec.Selector.MatchLabels, rs2.Spec.Template.Labels) {
@kow3ns I spent some time thinking whether to set `obj.Spec.Selector` to `nil` or `&metav1.LabelSelector{MatchLabels: map[string]string{}}`. In the end, i chose `nil` for simplicity. As a result, the test to compare `rs2.Spec.Selector.MatchLabels` and `rs2.Spec.Template.Labels` became unnecessary and was removed.

2017-08-04 20:01 UTC, crimsonfaith91 commented
/test pull-kubernetes-unit

2017-08-04 21:51 UTC, kow3ns requested changes
Don't set the labels on the specification objects based on the PodTemplateSpecs.

2017-08-04 21:51 UTC, kow3ns commented on pkg/apis/apps/v1beta2/defaults.go
> +	if labels != nil && len(obj.Labels) == 0 {
Delete this. You are setting the labels of the DaemonSet to the labels of the PodTemplateSpec. You do not want to do this.

2017-08-04 21:51 UTC, kow3ns commented on pkg/apis/apps/v1beta2/defaults.go
> +		obj.Labels = labels
Delete this. You are setting the labels of the StatefulSet to the labels of the PodTemplateSpec. You do not want to do this.

2017-08-04 21:51 UTC, kow3ns commented on pkg/apis/apps/v1beta2/defaults.go
> +	if labels != nil && len(obj.Labels) == 0 {
Delete this. You are setting the labels of the Deployment to the labels of the PodTemplateSpec. You do not want to do this.

2017-08-04 21:51 UTC, kow3ns commented on pkg/apis/apps/v1beta2/defaults.go
> +	if labels != nil && len(obj.Labels) == 0 {
Delete this. You are setting the labels of the ReplicaSet  to the labels of the PodTemplateSpec. You do not want to do this.

2017-08-04 21:51 UTC, kow3ns commented on pkg/apis/apps/v1beta2/defaults_test.go
> -		if test.expectSelector != reflect.DeepEqual(rs2.Spec.Selector.MatchLabels, rs2.Spec.Template.Labels) {
Do not default the selector to anything. We want to eliminate setting the Selector, or any field for that matter, based on another field of the same object. Doing so has caused us pain wrt apply and patch.

2017-08-04 22:12 UTC, crimsonfaith91 commented on pkg/apis/apps/v1beta2/defaults.go
> +	if labels != nil && len(obj.Labels) == 0 {
@kow3ns Noted! I will remove this. Same applies for other comments. :)

2017-08-04 22:15 UTC, crimsonfaith91 commented
@kow3ns The reason pull-kubernetes-unit failed is due to no change to validation codes. I will change the validation codes and remove label setting codes in next commit. Thanks for the guidance! :)

2017-08-04 23:46 UTC, crimsonfaith91 commented on pkg/apis/apps/v1beta2/defaults_test.go
> -		if test.expectSelector != reflect.DeepEqual(rs2.Spec.Selector.MatchLabels, rs2.Spec.Template.Labels) {
> Do not default the selector to anything. 
Did you mean `obj.Spec.Selector` should be `nil`? `obj.Spec.Selector` will be `nil` without explicitly setting it.

2017-08-07 17:42 UTC, crimsonfaith91 commented
/retest

2017-08-07 19:39 UTC, crimsonfaith91 commented on test/integration/etcd/etcd_storage_path_test.go
> +		stub:             `{"metadata": {"name": "ss1"}, "spec": {"selector": {"matchLabels": {"a": "b"}}, "template": {"metadata": {"labels": {"a": "b"}}}}}`,
@kow3ns The test case for statefulset did not have `spec.selector`, but similar test cases for deployments, daemonsets, and replicasets all have `spec.selector`. Hence, i modified the test case.

2017-08-07 19:39 UTC, crimsonfaith91 commented on test/integration/etcd/etcd_storage_path_test.go
> +		stub:             `{"metadata": {"name": "ss2"}, "spec": {"selector": {"matchLabels": {"a": "b"}}, "template": {"metadata": {"labels": {"a": "b"}}}}}`,
@kow3ns Same here.

2017-08-07 19:54 UTC, kow3ns approved these changes

2017-08-07 20:00 UTC, kow3ns commented
/lgtm

2017-08-08 20:57 UTC, kow3ns commented
/lgtm

2017-08-08 21:00 UTC, erictune commented
/approve

2017-08-09 13:08 UTC, liggitt commented
We still ensure the pod spec has labels and the selector matches the labels in validation, right?

2017-08-09 14:24 UTC, kow3ns commented
Current validation for apps and extensions is still in place. We will issue a subsequent PR for validation changes (where necessary) in the apps and extensions groups. As none of the controllers handle selector mutation in a sane way, we intend to make selectors immutable for v1.  We may lift this restriction at a future date when controllers can handle coordinated label updates and selector mutation. This PR for defaults has been done separately because it is isolated to the defaults in the v1beta2 group.

2017-08-09 17:28 UTC, kow3ns commented
/lgtm

2017-08-09 17:31 UTC, crimsonfaith91 commented
queue/multiple-rebases

2017-08-09 17:47 UTC, crimsonfaith91 commented
/test pull-kubernetes-unit

2017-08-09 19:10 UTC, crimsonfaith91 commented
/test pull-kubernetes-unit

2017-08-09 19:37 UTC, crimsonfaith91 commented
/retest

2017-08-09 20:17 UTC, kow3ns commented
/lgtm

2017-08-10 02:24 UTC, merged

2017-08-17 08:51 UTC, kargakis commented
@mfojtik @tnozicka