Add MemoryPressure/DiskPressure toleration for no BestEffort pod.
kubernetes/kubernetes pull request #50180
Opened 2017-08-05 02:23 UTC by k82cn

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: part of #42001 

**Release note**:
```release-note
If TaintByCondition was enabled, admission controller will add 'MemoryPressure' and 'DiskPressure' toleration to Guaranteed and Burstable pods.
```

2017-08-05 10:22 UTC, k82cn commented
/cc @gmarek

2017-08-07 08:08 UTC, gmarek commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +	if utilfeature.DefaultFeatureGate.Enabled(features.TaintNodesByCondition) {
Similarly as in other PR - I think it's fine to add those tolerations even if feature is not enabled.

2017-08-07 13:22 UTC, gmarek commented on plugin/pkg/admission/podtolerationrestriction/admission_test.go
> +		pod := test.pod
Add this explicitly to all test cases.

2017-08-08 13:43 UTC, k82cn commented on plugin/pkg/admission/podtolerationrestriction/admission_test.go
> +		pod := test.pod
done.

2017-08-08 13:44 UTC, k82cn commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +	if utilfeature.DefaultFeatureGate.Enabled(features.TaintNodesByCondition) {
done.

2017-08-08 13:55 UTC, gmarek commented
/lgtm

2017-08-08 14:30 UTC, k82cn commented
@derekwaynecarr , can you approve that ?

2017-08-09 05:41 UTC, derekwaynecarr commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +	if qoshelper.GetPodQOS(pod) != api.PodQOSBestEffort {
we need to ensure that this admission controller is run after all resource defaulting controllers.

2017-08-09 05:55 UTC, derekwaynecarr requested changes
i think the disk pressure toleration is more naunced.

i am fine with the memory pressure toleration.

2017-08-09 05:55 UTC, derekwaynecarr commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +				Key:      algorithm.TaintNodeDiskPressure,
at this time, cpu and memory are the only supported qos compute resources.

i think application of this toleration for disk pressure needs to be more nuanced.

/cc @vishh @jingxu97

2017-08-09 07:25 UTC, k82cn commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +				Key:      algorithm.TaintNodeDiskPressure,
@derekwaynecarr , thanks very much for your input. I also found this when handling taint for scheduler: the scheduler will filter out disk pressure nodes, but check QoS for memory pressure. Will remove DiskPressure toleration in this PR.

2017-08-09 14:34 UTC, k82cn commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +				Key:      algorithm.TaintNodeDiskPressure,
Removed 'DiskPressure' toleration.

2017-08-10 02:59 UTC, vishh reviewed
The current behavior for DiskPressure where no pods will be allowed on a node should continue to exist. So +1 on the decision of not tolerating DiskPressure for any pods.

2017-08-10 02:59 UTC, vishh commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +	if qoshelper.GetPodQOS(pod) != api.PodQOSBestEffort {
+1.

2017-08-10 03:10 UTC, k82cn commented
/retest

2017-08-10 03:51 UTC, k82cn commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +	if qoshelper.GetPodQOS(pod) != api.PodQOSBestEffort {
hm... , do you means this admission controller need to be the latest one in apiserver's args?

2017-08-10 09:54 UTC, gmarek commented
/retest

2017-08-10 09:56 UTC, gmarek commented
it looks good to me on my side, but @derekwaynecarr had good comment about order of admission controllers (which I don't know anything about).

2017-08-11 07:38 UTC, k82cn commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +				Key:      algorithm.TaintNodeDiskPressure,
@vishh , @derekwaynecarr , is latest PR OK for you?

2017-08-14 14:42 UTC, derekwaynecarr commented on plugin/pkg/admission/podtolerationrestriction/admission.go
> +	if qoshelper.GetPodQOS(pod) != api.PodQOSBestEffort {
its a doc issue.  you basically will want this controller to be the one that appears right before `ResourceQuota`

2017-08-14 14:42 UTC, derekwaynecarr approved these changes

2017-08-14 14:42 UTC, derekwaynecarr commented
/approve
/lgtm

2017-08-14 17:51 UTC, merged