Fix error message of statefulset test
kubernetes/kubernetes pull request #50219
Opened 2017-08-07 02:39 UTC by zhangxiaoyu-zidif

**What this PR does / why we need it**:
Fix error message of statefulset test
It should be 0 replocas in the error message.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-08-07 03:55 UTC, xiangpengzhao requested changes

2017-08-07 03:55 UTC, xiangpengzhao commented on pkg/controller/statefulset/stateful_set_test.go
> +		t.Error("Falied to scale statefulset to 0 replicas")
s/Falied/Failed

2017-08-07 04:35 UTC, zhangxiaoyu-zidif commented on pkg/controller/statefulset/stateful_set_test.go
> +		t.Error("Falied to scale statefulset to 0 replicas")
Thanks for that. =)

2017-08-11 16:23 UTC, xiangpengzhao requested changes
just one nit, otherwise LGTM.

2017-08-11 16:23 UTC, xiangpengzhao commented on pkg/controller/statefulset/stateful_set_test.go
> +		t.Error("Failed to scale statefulset to 3 replicas")
s/3/0

2017-08-11 16:23 UTC, xiangpengzhao commented
/ok-to-test

2017-08-11 20:26 UTC, enisoc commented on pkg/controller/statefulset/stateful_set_test.go
> +		t.Error("Failed to scale statefulset to 3 replicas")
Ideally these should be changed to match the conventional Go style:

https://github.com/golang/go/wiki/CodeReviewComments#useful-test-failures

```go
if got, want := set.Status.Replicas, 3; got != want {
  t.Errorf("set.Status.Replicas = %v; want %v", got, want)
}
```

Would you be willing to update the PR to that form?

2017-08-12 05:04 UTC, zhangxiaoyu-zidif commented on pkg/controller/statefulset/stateful_set_test.go
> +		t.Error("Failed to scale statefulset to 3 replicas")
yes, my pleasure. =) I will do it~

2017-08-12 05:34 UTC, zhangxiaoyu-zidif commented
@enisoc @xialonglee  PTAL

2017-08-12 05:35 UTC, zhangxiaoyu-zidif commented
@enisoc @xiangpengzhao 
PTAL

2017-08-15 23:12 UTC, enisoc commented
/lgtm
/approve no-issue

2017-08-16 00:00 UTC, merged