install_test.go of error message amending
kubernetes/kubernetes pull request #50354
Opened 2017-08-09 03:59 UTC by jianglingxia

**What this PR does / why we need it**:
amend the error message
ref: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/tags_test.go#L91
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-08-09 13:26 UTC, xiangpengzhao commented on federation/apis/federation/install/install_test.go
> +		t.Fatalf("expected an error: %v", err)
If so, what do you expect %v to output? note that `err==nil`.

2017-08-09 20:17 UTC, dims commented
/ok-to-test

2017-08-10 08:35 UTC, irfanurrehman commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-10 14:04 UTC, jianglingxia commented
PTAL @irfanurrehman
/assign @mwielgus

2017-08-10 15:26 UTC, irfanurrehman commented
/lgtm
/sig federation
cc @kubernetes/sig-federation-pr-reviews for approval

2017-08-11 08:51 UTC, marun commented
/lgtm cancel 

As per @xiangpengzhao's comment, the message shouldn't be attempting to format a nil error message.

2017-08-11 13:13 UTC, irfanurrehman commented
@marun My bad! My brain must have been absent from where its supposed to be when I half looked at it and passed for a simple string change. Thanks for having a look!
@jianglingxia please update the message as:
```
t.Fatalf("expected an error: got nil")
```

2017-08-11 13:32 UTC, xiangpengzhao commented
@irfanurrehman would it be better to use `expected an error but got nil`?

:)

2017-08-11 17:21 UTC, irfanurrehman commented
> @irfanurrehman would it be better to use expected an error but got nil?
> 
> :)

yes, or "expected an error, got nil" :)

2017-08-14 01:46 UTC, jianglingxia commented
thanks very much ,I have updated it! @irfanurrehman @xiangpengzhao

2017-08-14 02:24 UTC, xiangpengzhao requested changes

2017-08-14 02:24 UTC, xiangpengzhao commented on federation/apis/federation/install/install_test.go
> +		t.Fatalf("expected an error,but got nil")
please add a space after the comma. 
and amend the commit message to be a more meaningful one.

2017-08-16 09:30 UTC, jianglingxia commented
PTAL @xiangpengzhao 
@mwielgus

2017-08-17 02:28 UTC, jianglingxia commented
/test pull-kubernetes-unit
/test pull-kubernetes-verify

2017-08-17 03:19 UTC, jianglingxia commented
PTAL @irfanurrehman  @xiangpengzhao 
/assign @mwielgus

2017-08-24 14:06 UTC, jianglingxia commented
/assign @mwielgus
PTAL thanks

2017-08-25 02:09 UTC, jianglingxia commented
/assign @madhusudancs
PTAL

2017-10-02 18:44 UTC, quinton-hoole commented
/approve

2017-10-03 00:00 UTC, jianglingxia commented
please label 
/approve no-issue
thanks @quinton-hoole

2017-10-15 00:16 UTC, jianglingxia commented
the pr has 2 months 
please label
/approve no-issue
thanks @quinton-hoole

2017-10-16 07:55 UTC, irfanurrehman commented
/approve no-issue

2017-10-16 08:05 UTC, jianglingxia commented
thanks @irfanurrehman  trouble you again label lgtm
before label but removed it by robot.
![image](https://user-images.githubusercontent.com/25783555/31601203-a468725e-b28b-11e7-9856-487731a7263b.png)

2017-10-16 09:10 UTC, irfanurrehman commented
/lgtm

2017-10-16 09:13 UTC, irfanurrehman commented
/lgtm cancel
@jianglingxia, please put a proper message in the commit log in place of  "squash the commits into one"
and I will lgtm again

2017-10-16 09:36 UTC, jianglingxia commented
because of unknown repository,I can not update it in before branch,so I reopen the pr #50354,then I close the pr!thanks

2017-10-16 09:36 UTC, closed without merging