Add statefulset upgrade tests to cluster_upgrade
kubernetes/kubernetes pull request #50397
Opened 2017-08-09 21:32 UTC by bdbauer

**What this PR does / why we need it**:
Adds already created statefulset upgrade tests to cluster_upgrade.go. With further test infra changes, this will allow them to be continuously run, giving better signals.

**Release note**:

```release-note
NONE
```

2017-08-09 21:55 UTC, krousey requested changes
The Name() method of all the upgrade tests should also have a sig tag to indicate ownership.

2017-08-09 21:55 UTC, krousey commented on test/e2e/lifecycle/cluster_upgrade.go
> +var _ = SIGDescribe("stateful Upgrade [Feature:StatefulUpgrade]", func() {
This is going to put "[sig-cluster-lifecycle]" in the name when I don't think we're going to own it. Can you use the standard describe and add an owning sig here?

2017-08-09 21:55 UTC, krousey commented on test/e2e/lifecycle/cluster_upgrade.go
> +			statefulUpgradeTest := &junit.TestCase{Name: "stateful-upgrade", Classname: "upgrade_tests"}
Name needs a sig tag.

2017-08-15 20:38 UTC, pwittrock commented
/unassign @pwittrock

2017-08-15 20:38 UTC, pwittrock commented
/assign @foxish

2017-08-16 18:00 UTC, bdbauer commented
/cc @mml

2017-08-16 18:00 UTC, bdbauer commented
/cc @maisem

2017-08-22 23:01 UTC, foxish commented
Thanks!

/lgtm
/approve

A test of this setup being correct and working would be to detect the upgrade issue between 1.6 and 1.7 tracked in https://github.com/kubernetes/kubernetes/issues/48327.

2017-08-22 23:02 UTC, foxish commented
/approve

2017-08-24 06:16 UTC, merged