revemo annotation load-balancer-source-ranges
kubernetes/kubernetes pull request #50494
Opened 2017-08-11 05:14 UTC by x1957

**What this PR does / why we need it**:
revemo annotation load-balancer-source-ranges
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes #50491
**Special notes for your reviewer**:
@thockin

**Release note**:

```release-note
Beta annotation `service.beta.kubernetes.io/load-balancer-source-ranges` have been removed. Please use fields `service.spec.service.Spec.LoadBalancerSourceRanges` instead.
```

2017-08-11 05:30 UTC, xiangpengzhao commented
/ok-to-test
please run `hack/update-bazel.sh` to update BUILD file(s).

2017-08-11 07:14 UTC, x1957 commented
@xiangpengzhao  thanks, nothing to update

2017-08-11 07:30 UTC, x1957 commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-11 07:40 UTC, x1957 commented
/retest

2017-08-11 08:26 UTC, xiangpengzhao commented
yeah that's because you don't modify package import after rebasing. When I first saw this PR, some package import was modified. In that case, that script should be run:)

2017-08-11 08:33 UTC, x1957 commented
@xiangpengzhao thanks^_^
@thockin Could you please review the code?

2017-08-11 08:50 UTC, xiangpengzhao commented on pkg/api/annotation_key_constants.go
> -	AnnotationLoadBalancerSourceRangesKey = "service.beta.kubernetes.io/load-balancer-source-ranges"
please also remove `AnnotationLoadBalancerSourceRangesKey` in staging/src/k8s.io/api/core/v1/annotation_key_constants.go

2017-08-11 08:53 UTC, x1957 commented on pkg/api/annotation_key_constants.go
> -	AnnotationLoadBalancerSourceRangesKey = "service.beta.kubernetes.io/load-balancer-source-ranges"
ok， I will do it later.

2017-08-11 09:26 UTC, x1957 commented on pkg/api/service/util.go
> +		ipnets, _ = netsets.ParseIPNets(specs...)
Should I return error here?
I think there is no error when parse defaultLoadBalancerSourceRanges("0.0.0.0/0").

2017-08-11 10:57 UTC, xiangpengzhao requested changes
some nits, otherwise LGTM. Tim please take another review.

2017-08-11 10:57 UTC, xiangpengzhao commented on pkg/api/service/util.go
>  // GetLoadBalancerSourceRanges first try to parse and verify LoadBalancerSourceRanges field from a service.
this comment should be modified.

2017-08-11 10:57 UTC, xiangpengzhao commented on pkg/api/v1/service/util.go
>  // GetLoadBalancerSourceRanges first try to parse and verify LoadBalancerSourceRanges field from a service.
also this comment

2017-08-11 10:57 UTC, xiangpengzhao commented on pkg/api/validation/validation.go
>  		if len(service.Spec.LoadBalancerSourceRanges) > 0 {
this condition is redundant

2017-08-11 10:57 UTC, xiangpengzhao commented on pkg/api/service/util.go
>  // GetLoadBalancerSourceRanges first try to parse and verify LoadBalancerSourceRanges field from a service.
also remove the comment at L47. (not shown in review mode)

2017-08-11 10:57 UTC, xiangpengzhao commented on pkg/api/service/util.go
>  // GetLoadBalancerSourceRanges first try to parse and verify LoadBalancerSourceRanges field from a service.
i.e. `// if SourceRange field is specified, ignore sourceRange annotation`

2017-08-11 10:57 UTC, xiangpengzhao commented on pkg/api/v1/service/util.go
>  // GetLoadBalancerSourceRanges first try to parse and verify LoadBalancerSourceRanges field from a service.
and `// if SourceRange field is specified, ignore sourceRange annotation`

2017-08-11 10:57 UTC, xiangpengzhao commented on pkg/api/v1/service/util.go
> -	"strings"
run `hack/update-bazel.sh` due to this deletion

2017-08-11 15:06 UTC, x1957 commented
/retest

2017-08-12 14:17 UTC, x1957 commented
/retest

2017-08-14 03:08 UTC, xiangpengzhao commented
/release-note-action-required

2017-08-14 03:21 UTC, xiangpengzhao commented
@thockin `/release-note-action-required` in comment isn't supported yet. Do we need `/release-note-action-required` for this PR? If so, please help label it. Thanks!

2017-09-13 09:04 UTC, xiangpengzhao commented
/release-note-action-required

2017-12-13 08:13 UTC, closed without merging