Add flags for prometheus-to-sd components.
kubernetes/kubernetes pull request #50512
Opened 2017-08-11 10:22 UTC by loburm

Configure prometheus-to-sd-endpoint and prometheus-to-sd-prefix base on
the environment.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-08-14 07:09 UTC, loburm commented
/test pull-kubernetes-node-e2e
/test pull-kubernetes-unit
/test pull-kubernetes-e2e-gce-etcd3

2017-08-14 08:03 UTC, loburm commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-14 09:02 UTC, loburm commented
/test pull-kubernetes-e2e-gce-etcd3

2017-08-14 13:45 UTC, loburm commented
/assign @zmerlynn
/assign @piosz

2017-08-16 13:31 UTC, piosz requested changes
please apply comments in other places as well

2017-08-16 13:31 UTC, piosz commented on cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
> +{% set prometheus_to_sd_prefix = "custom.googleapis.com" -%}
As discussed offline please remove this.

2017-08-16 13:31 UTC, piosz commented on cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
> +            - --stackdriver-prefix={{ prometheus_to_sd_prefix }}/internal/addons
just addons

2017-08-17 09:15 UTC, loburm commented on cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
> +            - --stackdriver-prefix={{ prometheus_to_sd_prefix }}/internal/addons
That may be not a very good idea. It may happen that some people already configured alerts based on this name.

2017-08-17 09:16 UTC, loburm commented on cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
> +{% set prometheus_to_sd_prefix = "custom.googleapis.com" -%}
Removed

2017-08-17 09:17 UTC, loburm commented
Added one more env variable that allow user to completely disable prometheus-to-sd.

2017-08-17 10:08 UTC, loburm commented on cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
> +            - --stackdriver-prefix={{ prometheus_to_sd_prefix }}/internal/addons
Sorry, I haven't understood. We can still specify the correct prefix and metric name will not change.

Fixed.

2017-08-17 12:10 UTC, piosz approved these changes

2017-08-17 12:11 UTC, piosz commented
/lgtm
The logic does what we would like to achieve though it's a bit hack. Waiting for @mikedanese to review it.

2017-08-22 00:10 UTC, mikedanese commented
/lgtm

2017-08-22 00:10 UTC, mikedanese commented
/approve no-issue

2017-08-22 07:45 UTC, loburm commented
/test pull-kubernetes-unit
/test pull-kubernetes-e2e-kops-aws

2017-08-22 09:00 UTC, loburm commented
I have rebased PR (it was two weeks old). Can I get lgtm once again?

Thanks

2017-08-23 04:16 UTC, merged