kubeadm: Add node-cidr-mask-size to pass to kube-controller-manager for IPv6
kubernetes/kubernetes pull request #50523
Opened 2017-08-11 15:40 UTC by rpothier

Due to the increased size of subnets with IPv6, the node-cidr-mask-size needs to be passed to kube-controller-manager. If not specified it will default to 24 as it was previously.

**What this PR does / why we need it**:
If the user specifies the --pod-network-cidr with kubeadm init, this caused the kube-controller-manager manifest to include the "--allocate-node-cidrs" and "--cluster-cidr" flags to be set. The --node-cidr-mask-size is not set, and currently defaults to 24, which is fine for IPv4, but not appropriate for IPv6. This change adds a new arg for kubeadm and passes the value as the node-cidr-mask-size to the controller-manager. If it is not set, it still defaults to 24 as before.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50469

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-08-11 15:41 UTC, rpothier commented
/area ipv6

2017-08-11 18:34 UTC, pmichali approved these changes
/lgtm

2017-08-13 01:00 UTC, cblecker commented
/ok-to-test

2017-08-14 12:22 UTC, luxas requested changes
> The --node-cidr-mask-size is not set, and currently defaults to 24, which is fine for IPv4, but not appropriate for IPv6

I don't really want to add yet an other option here. Can't we just detect if `PodSubnet` is an IPv6 addr and set `--node-cidr-mask-size` accordingly?

2017-08-18 18:07 UTC, cblecker commented
/retest

2017-08-21 19:31 UTC, rpothier commented
@luxas I will make that change, there could be issues later that people would want to use a different
cidr-mask-size than is the default, since the IPv6 mask size is much larger.

2017-08-23 11:49 UTC, pmichali commented
Looks like the latest suggestion is to nail the subnet prefix to /64 for IPv6. If that's the case, then the commit description should be updated to reflect the actual direction.

Not sure if that is a good decision, as I would think we'd want the flexibility to have a different prefix.

Would an option be to change the definition of --pod-network-cidr to have it include the prefix? That would change the API, however.

2017-08-23 14:43 UTC, rpothier commented
@pmichali Yes, the request is detect the IP version, and choose an appropriate mask and then we don't need another arg added.

2017-08-24 13:41 UTC, rpothier commented
/test pull-kubernetes-e2e-gce-etcd3

2017-09-01 14:21 UTC, luxas commented
/lgtm
/retest

The code LGTM, but I'd like buy-in from @kubernetes/sig-network-pr-reviews and/or @kubernetes/sig-cluster-lifecycle-pr-reviews that this is actually a sane to do

2017-09-01 23:38 UTC, luxas commented
@caseydavenport LGTM'd this on Slack. Thanks!

/retest

2017-09-02 20:34 UTC, luxas commented
/retest

2017-09-02 23:06 UTC, merged