Use Fatalf instead of Errorf plus FailNow
kubernetes/kubernetes pull request #50549
Opened 2017-08-12 07:14 UTC by YuxiJin-tobeyjin

**What this PR does / why we need it**:
Use Fatalf instead of Errorf plus FailNow

**Release note**:
NONE
```release-note
```

2017-08-12 11:12 UTC, xiangpengzhao commented
/ok-to-test
/release-note-none

2017-08-17 01:12 UTC, YuxiJin-tobeyjin commented
ping @brendandburns @smarterclayton 
PTAL，thanks.

2017-08-17 02:13 UTC, smarterclayton commented
/lgtm

2017-08-17 03:06 UTC, YuxiJin-tobeyjin commented
/test pull-kubernetes-unit

2017-08-21 08:32 UTC, YuxiJin-tobeyjin commented
/assign @brendandburns

2017-08-21 09:21 UTC, YuxiJin-tobeyjin commented
/retest

2017-08-22 01:01 UTC, YuxiJin-tobeyjin commented
/test pull-kubernetes-kubemark-e2e-gce

2017-08-22 03:30 UTC, YuxiJin-tobeyjin commented
/assign @brendandburns

2017-08-22 04:24 UTC, brendandburns commented
/lgtm
/approve no issue

2017-08-22 05:45 UTC, YuxiJin-tobeyjin commented
ping @brendandburns 
Maybe a typo,pls use /approve no-issue,thanks a lot.

2017-08-23 06:03 UTC, YuxiJin-tobeyjin commented
/approve no-issue

2017-08-23 06:06 UTC, YuxiJin-tobeyjin commented
/assign @brendandburns

2017-08-24 08:46 UTC, YuxiJin-tobeyjin commented
ping @brendandburns 
Sorry to bother,PTAL
/approve no-issue

2017-08-25 01:16 UTC, YuxiJin-tobeyjin commented
/assign @brendandburns
/approve no-issue
sir,pls

2017-08-31 05:48 UTC, YuxiJin-tobeyjin commented
/retest

2017-08-31 10:36 UTC, YuxiJin-tobeyjin commented
/test pull-kubernetes-e2e-kops-aws

2017-09-01 01:12 UTC, YuxiJin-tobeyjin commented
/test pull-kubernetes-e2e-kops-aws

2017-09-05 21:45 UTC, brendandburns commented
/retest

2017-09-06 00:56 UTC, YuxiJin-tobeyjin commented
/test pull-kubernetes-e2e-kops-aws

2017-09-06 01:41 UTC, YuxiJin-tobeyjin commented
/retest

2017-09-06 03:35 UTC, YuxiJin-tobeyjin commented
ping @brendandburns

2017-09-25 01:19 UTC, YuxiJin-tobeyjin commented
/retest

2017-09-25 01:26 UTC, xiangpengzhao requested changes

2017-09-25 01:26 UTC, xiangpengzhao commented on pkg/kubectl/rolling_updater_test.go
> +		t.Fatalf("error decoding: %v", err)
s/error/Error

2017-09-26 10:59 UTC, YuxiJin-tobeyjin commented
/test pull-kubernetes-e2e-kubeadm-gce

2017-10-09 00:53 UTC, YuxiJin-tobeyjin commented
Close

2017-10-09 00:53 UTC, closed without merging