Update RegisterMandatoryFitPredicate to avoid doubel register.
kubernetes/kubernetes pull request #50581
Opened 2017-08-14 01:05 UTC by k82cn

**What this PR does / why we need it**:
In https://github.com/kubernetes/kubernetes/pull/50362 , we introduced `RegisterMandatoryFitPredicate` to make some predicates always included by scheduler. This PRs is to improve it by avoiding double register: `RegisterFitPredicate` and `RegisterMandatoryFitPredicate` 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50360 

**Release note**:

```release-note
None
```

2017-08-14 01:06 UTC, k82cn commented
/assign @bsalamat

2017-08-14 02:36 UTC, k82cn commented
/retest

2017-08-14 09:22 UTC, zhangxiaoyu-zidif commented
The title has a typo :)
s/doubel/double

2017-08-14 09:22 UTC, zhangxiaoyu-zidif requested changes
The title has a typo :)
s/doubel/double

2017-08-15 09:08 UTC, k82cn commented
@bsalamat , ping for review :).

2017-08-15 17:11 UTC, bsalamat commented on plugin/pkg/scheduler/factory/plugins.go
> +		if mandatory {
The current logic is correct, but I would remove checking the value of `mandatory`. `mandatoryFitPredicate` is basically a set. Anything in that set can be considered a mandatory predicate, regardless of the value of `bool`.

2017-08-15 23:58 UTC, k82cn commented on plugin/pkg/scheduler/factory/plugins.go
> +		if mandatory {
Good point ! Will update it today :).

2017-08-16 08:21 UTC, k82cn commented on plugin/pkg/scheduler/factory/plugins.go
> +		if mandatory {
done :).

2017-08-16 16:58 UTC, bsalamat commented on plugin/pkg/scheduler/factory/plugins.go
> +	for _, name := range mandatoryFitPredicates.List() {
Please do not use `List()` here. It first copies all the items of the map (set) into a slice and then sorts the items and returns the slice. We don't need a sorted list. Instead, just use:
`for name, _ := range mandatoryFitPredicates {`

2017-08-17 00:26 UTC, k82cn commented on plugin/pkg/scheduler/factory/plugins.go
> +	for _, name := range mandatoryFitPredicates.List() {
ops :). and done .

2017-08-17 01:04 UTC, bsalamat commented
/lgtm

Thanks, @k82cn!

2017-08-17 03:31 UTC, k82cn commented
/retest

2017-08-17 06:08 UTC, merged