WIP: update QEMU version to v2.9.1
kubernetes/kubernetes pull request #50597
Opened 2017-08-14 07:59 UTC by dixudx

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
xref #38067

**Special notes for your reviewer**:
/assign @luxas 

**Release note**:

```release-note
update QEMU version to v2.9.1
```

2017-08-14 08:59 UTC, dixudx commented
/assign @jbeda @zmerlynn
I think it's ready for a review. PTAL. Thanks.

2017-08-14 09:39 UTC, mkumatag requested changes

2017-08-14 09:39 UTC, mkumatag commented on test/images/Makefile
> +QEMUVERSION=v2.9.1
Not really sure whether we need to push all the images under `test/images` with this new qemu binary. @luxas WDYT?

2017-08-14 09:39 UTC, mkumatag commented on test/images/resource-consumer/BASEIMAGE
> +amd64=gcr.io/google-containers/debian-base-amd64:0.2
You may need to bump the version for resource-consumer image in `test/images/resource-consumer/VERSION`

2017-08-14 09:41 UTC, vabc3 commented on build/root/WORKSPACE
> +// TODO(dixudx): update the sha and tag (to v8) when the image get pushed
Should use `#` for comments? Or spawn an issue for tracking

2017-08-14 11:39 UTC, luxas reviewed
Thanks @dixudx for your PR!

I don't think we need to bump the versions.
1) It shouldn't affect the result (this is only syscall emulation)
2) There is no direct benefit we get from using a newer QEMU that would need an image bump. This setting will just be picked up the next time the image is built/pushed.

The rationale for upgrading is to hopefully get more stable and reliable builds, have better emulation support for s390x and pick up performance improvements tha have been made in recent versions.

2017-08-14 11:39 UTC, luxas commented
/ok-to-test

2017-08-14 15:18 UTC, dixudx commented
/retest

2017-08-15 08:09 UTC, dixudx commented
/retest

2017-08-16 04:22 UTC, dixudx commented
/retest

2017-08-16 13:15 UTC, dixudx commented
/retest

2017-08-16 19:56 UTC, luxas reviewed
ping @ixdy; think we need to bump versions for this?

2017-08-16 19:56 UTC, luxas commented on build/common.sh
> +  ## TODO(dixudx): update the tag to v8 when the image get pushed
Is this still valid; do we need to do this?

2017-08-17 02:17 UTC, dixudx commented on build/common.sh
> +  ## TODO(dixudx): update the tag to v8 when the image get pushed
Since the base image of `debian-iptables`, we'd better bump a new version.

2017-08-18 18:00 UTC, ixdy commented
QEMU is really only used when building the images, right? in that case, no, I don't think bumping the tags is needed.

2017-08-19 00:32 UTC, dixudx commented
> QEMU is really only used when building the images, right?

Yes, we are just using it during building.

@ixdy Actually since the `Dockerfile` has been changed, will the docker images be updated and pushed to `gcr.io`? And If the images have been updated and pushed, but we still bump the old tag, users may not get noticed by the change. The image with the same tag they pulled before is actually different from that on current `gcr.io`.

2017-08-19 06:20 UTC, dixudx commented
@ixdy @luxas @mkumatag 

> QEMU is really only used when building the images, right? in that case, no, I don't think bumping the tags is needed.

Updated. I've only bumped new version to QEMU. 

Since PR #50602 has to get bumped a new tag due to old stale base image. We just need to update it once.

2017-08-19 08:45 UTC, luxas commented
/lgtm

2017-08-19 10:45 UTC, mkumatag approved these changes

2017-08-20 02:08 UTC, dixudx commented
/retest

2017-08-23 09:24 UTC, dixudx commented
/retest

2017-08-23 15:08 UTC, luxas commented
@ixdy Please approve this. Thanks!

2017-08-28 10:08 UTC, dixudx commented
/retest

2017-08-28 14:40 UTC, dixudx commented
ping @ixdy Need your approval. PTAL. Thanks!

2017-09-01 14:08 UTC, luxas commented
/test

2017-09-01 14:10 UTC, luxas commented
/test all

2017-09-03 08:14 UTC, dixudx commented
/retest

2017-09-03 10:24 UTC, merged