Fix make cross build failure
kubernetes/kubernetes pull request #50694
Opened 2017-08-15 15:08 UTC by dims

had to fix the method getSecurityOpts in helpers_windows.go to
match the implementation in helpers_linux.go from commit:
bf01fa2f0010ae02d1ef3369ea268a2b4241619d

Fixes #50675

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-08-15 15:09 UTC, dims commented
/cc @luxas

2017-08-15 15:10 UTC, dims commented
/cc @feiskyer

2017-08-15 15:11 UTC, dims commented
/test pull-kubernetes-cross

2017-08-15 15:16 UTC, luxas reviewed
Don't have enough context on this to fully LGTM, but seems reasonable to be to just no-op on windows that doesn't support this feature...

2017-08-15 15:33 UTC, yujuhong requested changes

2017-08-15 15:33 UTC, yujuhong commented on pkg/kubelet/dockershim/helpers_windows.go
> +	glog.Warningf("seccomp annotations are not supported on windows")
Warning should only be logged if there are annotations. Removing the condition will lead to false warnings.

2017-08-15 16:19 UTC, dims commented on pkg/kubelet/dockershim/helpers_windows.go
> +	glog.Warningf("seccomp annotations are not supported on windows")
@yujuhong : did you see this? https://github.com/kubernetes/kubernetes/blob/b32639f9e7d47d0f69bb41b5535803ae4c9d835a/pkg/kubelet/dockershim/helpers_unsupported.go#L33

With the recent changes, the first parameter to that method is the `seccompProfile`, not `containerName` Also, please look at how the calls to getSecurityOpts are made from docker_container.go and docker_sandbox.go

Thanks,
Dims

2017-08-15 17:17 UTC, Random-Liu commented on pkg/kubelet/dockershim/helpers_windows.go
> +	glog.Warningf("seccomp annotations are not supported on windows")
Maybe only log the warning when `seccompProfile` is not empty.

2017-08-15 17:28 UTC, dims commented on pkg/kubelet/dockershim/helpers_windows.go
> +	glog.Warningf("seccomp annotations are not supported on windows")
Done @Random-Liu

2017-08-15 17:31 UTC, yujuhong commented on pkg/kubelet/dockershim/helpers_windows.go
> +	// return nil so docker will load the default seccomp profile
Is this comment true for windows containers?

2017-08-15 18:10 UTC, yujuhong commented on pkg/kubelet/dockershim/helpers_windows.go
> +	glog.Warningf("seccomp annotations are not supported on windows")
@Random-Liu's suggestion LGTM. I was going to suggest the same thing :-)

2017-08-15 18:15 UTC, dims commented on pkg/kubelet/dockershim/helpers_windows.go
> +	// return nil so docker will load the default seccomp profile
@yujuhong comment is true to the best of my knowledge. you can actually see it in helpers_linux.go as well

2017-08-15 18:17 UTC, yujuhong commented on pkg/kubelet/dockershim/helpers_windows.go
> +	// return nil so docker will load the default seccomp profile
Uh..how is seccomp supported on windows?

2017-08-15 18:24 UTC, yujuhong approved these changes

2017-08-15 18:25 UTC, yujuhong commented
/lgtm

/test pull-kubernetes-cross

2017-08-15 18:45 UTC, dims commented
Thanks @yujuhong

2017-08-15 19:48 UTC, dims commented
/retest

2017-08-15 21:28 UTC, merged

2017-08-16 01:30 UTC, feiskyer commented
@dims Thanks for the fix.