kubeadm: Get kube-dns based on the kubernetes version
kubernetes/kubernetes pull request #50965
Opened 2017-08-19 17:26 UTC by luxas

**What this PR does / why we need it**:

Makes the kube-dns version used dependent on the kubernetes version. This is required for upgrades as we have to be able to handle one kube-dns version per branch for instance...

Currently a no-op though, as both v1.7 and v1.8 seem to use 1.14.4

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Dependency for https://github.com/kubernetes/kubernetes/pull/48899 (kubeadm upgrades)

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews 

@kubernetes/dns-maintainers FYI; next time you bump DNS version, please update this func instead of the constant there...

2017-08-19 17:27 UTC, luxas commented
/approve no-issue
(part of the kubeadm upgrade proposal and issue, but does not solve everything)

2017-08-21 14:42 UTC, timothysc requested changes
Negative test, then lgtm.

2017-08-21 14:42 UTC, timothysc commented on cmd/kubeadm/app/phases/addons/dns/versions_test.go
> +		k8sVersion, expected string
Do you have a test that doesn't hit 1.14.4?

2017-08-21 14:42 UTC, timothysc commented on cmd/kubeadm/app/phases/addons/dns/versions.go
> +	kubeDNSv170AndAboveVersion = "1.14.4"
I kind of think we need to centralize the add-on version and plumb though the config.

2017-08-21 15:00 UTC, luxas commented on cmd/kubeadm/app/phases/addons/dns/versions_test.go
> +		k8sVersion, expected string
Currently the func is just `return "1.14.4"`; do you mean I should change that to get a negative unit test possibility?

2017-08-21 15:02 UTC, luxas commented on cmd/kubeadm/app/phases/addons/dns/versions.go
> +	kubeDNSv170AndAboveVersion = "1.14.4"
We need the Real Addon Manager (tm) here. We don't have that unfortunately.
That combined with HA is probably some of the next step for the SIG, but need to get this now for upgrades shorter-term.

2017-08-21 15:33 UTC, timothysc commented on cmd/kubeadm/app/phases/addons/dns/versions_test.go
> +		k8sVersion, expected string
We should verify a negative test case, if there is one.  What versions of kubedns do we support for each version of kubeadm that has gone out?

2017-08-21 15:41 UTC, timothysc commented on cmd/kubeadm/app/phases/addons/dns/versions.go
> +	kubeDNSv170AndAboveVersion = "1.14.4"
Do we have a tracking Addon Manager issue we can cross reference to this PR?

2017-08-21 15:42 UTC, luxas commented on cmd/kubeadm/app/phases/addons/dns/versions_test.go
> +		k8sVersion, expected string
For v1.7.0+ (which is the only version kubeadm v1.8 has to support), there is only one kube-dns version bundled by default: `1.14.2`. Hence my "hardcoding" in the function there. That means there are no negative unit tests right now.

2017-08-21 15:42 UTC, timothysc commented on cmd/kubeadm/app/phases/addons/dns/versions_test.go
> +		k8sVersion, expected string
Per support matrix discussion on slack, there is only 1.14.4 for supported version of 1.8 kubeadm.

2017-08-21 15:42 UTC, luxas commented
/retest

2017-08-21 15:43 UTC, timothysc approved these changes
/lgtm 

Please cross reference AddOn Manager issue(s)

2017-08-22 14:15 UTC, luxas commented
/retest

2017-08-22 14:53 UTC, luxas commented
/retest

2017-08-22 15:34 UTC, luxas commented
/retest

2017-08-22 17:07 UTC, luxas commented
/retest

2017-08-22 18:46 UTC, luxas commented
/retest

2017-08-22 20:28 UTC, luxas commented
/retest

2017-08-22 21:11 UTC, luxas commented
/retest

> On 22 Aug 2017, at 23:25, k8s-ci-robot <notifications@github.com> wrote:
> 
> @luxas: The following test failed, say /retest to rerun them all:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-e2e-kops-aws	6bc8ab3	link	/test pull-kubernetes-e2e-kops-aws
> Full PR test history. Your PR dashboard. Please help us cut down on flakes by linking to an open issue when you hit one in your PR.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-23 04:16 UTC, merged