code format in status_manager.go
kubernetes/kubernetes pull request #51100
Opened 2017-08-22 11:37 UTC by jinzhejz

**What this PR does / why we need it**:
code format

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #N/A

**Release note**:
```release-note
None
```

2017-08-23 03:55 UTC, xiangpengzhao commented
/ok-to-test
/lgtm

2017-08-23 04:55 UTC, xiangpengzhao commented
please fix the verification failure:

```
I0823 04:22:04.705] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I0823 04:22:16.896] diff ./pkg/kubelet/status/status_manager.go gofmt/./pkg/kubelet/status/status_manager.go
I0823 04:22:16.896] --- /tmp/gofmt964297618	2017-08-23 04:22:15.775462231 +0000
I0823 04:22:16.896] +++ /tmp/gofmt717048265	2017-08-23 04:22:15.775462231 +0000
I0823 04:22:16.896] @@ -23,8 +23,6 @@
I0823 04:22:16.896]  
I0823 04:22:16.897]  	"github.com/golang/glog"
I0823 04:22:16.897]  
I0823 04:22:16.897] -	clientset "k8s.io/client-go/kubernetes"
I0823 04:22:16.897] -	"k8s.io/client-go/kubernetes/scheme"
I0823 04:22:16.897]  	"k8s.io/api/core/v1"
I0823 04:22:16.897]  	apiequality "k8s.io/apimachinery/pkg/api/equality"
I0823 04:22:16.897]  	"k8s.io/apimachinery/pkg/api/errors"
I0823 04:22:16.898] @@ -32,6 +30,8 @@
I0823 04:22:16.898]  	"k8s.io/apimachinery/pkg/types"
I0823 04:22:16.898]  	"k8s.io/apimachinery/pkg/util/diff"
I0823 04:22:16.898]  	"k8s.io/apimachinery/pkg/util/wait"
I0823 04:22:16.898] +	clientset "k8s.io/client-go/kubernetes"
I0823 04:22:16.898] +	"k8s.io/client-go/kubernetes/scheme"
I0823 04:22:16.898]  	podutil "k8s.io/kubernetes/pkg/api/v1/pod"
I0823 04:22:16.899]  	kubecontainer "k8s.io/kubernetes/pkg/kubelet/container"
I0823 04:22:16.899]  	kubepod "k8s.io/kubernetes/pkg/kubelet/pod"
I0823 04:22:16.899] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	12s
```

2017-08-23 04:57 UTC, xiangpengzhao requested changes

2017-08-23 04:57 UTC, xiangpengzhao commented on pkg/kubelet/status/status_manager.go
>  	"k8s.io/client-go/kubernetes/scheme"
move the two lines after `k8s.io/apimachinery/pkg/util/wait` (L34)

2017-08-23 06:54 UTC, jinzhejz commented on pkg/kubelet/status/status_manager.go
>  	"k8s.io/client-go/kubernetes/scheme"
the commit is updated, thanks

2017-08-23 06:55 UTC, jinzhejz commented
commit is updated

2017-08-23 07:09 UTC, xiangpengzhao commented
/lgtm

2017-08-28 01:32 UTC, jinzhejz commented
/retest

2017-09-20 03:37 UTC, closed without merging