kubeadm: Fully implement --dry-run
kubernetes/kubernetes pull request #51122
Opened 2017-08-22 15:29 UTC by luxas

**What this PR does / why we need it**:

Finishes the work begun in #50631 
 - Implements dry-run functionality for phases certs/kubeconfig/controlplane/etcd as well by making the outDir configurable
 - Prints the controlplane manifests to stdout, but not the certs/kubeconfig files due to the sensitive nature. However, kubeadm outputs the directory to go and look in for those.
 - Fixes a small yaml marshal error where `apiVersion` and `kind` wasn't printed earlier.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes: https://github.com/kubernetes/kubeadm/issues/389

**Special notes for your reviewer**:

**Release note**:

```release-note
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @ncdc @sttts

2017-08-22 15:39 UTC, ncdc requested changes

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/cmd/init.go
> +
Remove blank line please

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/cmd/init.go
> +			return "", "", "", fmt.Errorf("couldn't create a temporary directory for the upgrade: %v")
Is this always for an upgrade?

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/cmd/init.go
> +func getDirectoriesToUse(dryRun bool, defaultPkiDir string) (string, string, string, error) {
I would like to find an alternative to a `bool` param but I don't have any great ideas (they're unintuitive).

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/cmd/init.go
> +func printFilesIfDryRunning(dryRun bool, manifestDir string) error {
Maybe don't take the bool in here, and do the if check where you call it?

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/cmd/init.go
> +	fmt.Println("[dryrun] Please go an examine the %q directory for details about what would be written\n", manifestDir)
Printf instead of Println.
Either remove "an" or change it to "and".

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/util/apiclient/dryrunclient.go
> +
Remove

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/util/dryrun/dryrun.go
> +
Remove

2017-08-22 15:39 UTC, ncdc commented on cmd/kubeadm/app/util/dryrun/dryrun.go
> +			return err
Do you want to stop on first error, or continue and try to do as many as you can?

2017-08-22 17:50 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> +func getDirectoriesToUse(dryRun bool, defaultPkiDir string) (string, string, string, error) {
I hope we can defer that until after code freeze. Agree that it would be nice to refactor this once we have the full picture afterwards.

2017-08-22 17:51 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> +			return "", "", "", fmt.Errorf("couldn't create a temporary directory for the upgrade: %v")
nope, oops. Copy-paste error :)

2017-08-22 17:53 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> +	fmt.Println("[dryrun] Please go an examine the %q directory for details about what would be written\n", manifestDir)
goh, should be `Printf` and `and`, thanks for catching

2017-08-22 18:58 UTC, luxas commented
@ncdc Thanks for the review! Should now be fixed up and ready to merge :+1:

2017-08-22 18:58 UTC, luxas commented on cmd/kubeadm/app/util/dryrun/dryrun.go
> +			return err
good idea, incorporated

2017-08-22 18:58 UTC, luxas commented on cmd/kubeadm/app/util/dryrun/dryrun.go
> +
done

2017-08-22 18:58 UTC, luxas commented on cmd/kubeadm/app/util/apiclient/dryrunclient.go
> +
done

2017-08-22 18:59 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> +func printFilesIfDryRunning(dryRun bool, manifestDir string) error {
deferring that to later

2017-08-22 18:59 UTC, luxas commented on cmd/kubeadm/app/cmd/init.go
> +
done

2017-08-22 19:07 UTC, ncdc commented on cmd/kubeadm/app/util/dryrun/dryrun.go
> +	if len(errors) != 0 {
You might just want to return `k8s.io/apimachinery/pkg/util/errors.NewAggregate(errors)`, which will do the right thing if len(errors) is 0.

2017-08-22 20:18 UTC, luxas commented on cmd/kubeadm/app/util/dryrun/dryrun.go
> +	if len(errors) != 0 {
fixed

2017-08-22 20:19 UTC, luxas commented
@ncdc fixed the nit; now things should be green :)

2017-08-22 20:21 UTC, ncdc approved these changes

2017-08-22 20:22 UTC, ncdc commented
I reviewed for anything that stood out to me, but as I'm not very familiar with this code, I think @timothysc should review too.

2017-08-23 11:46 UTC, lukemarsden commented
Please make this not say `Your Kubernetes master has initialized successfully!` 😆

2017-08-23 11:47 UTC, lukemarsden commented
Also `You can` and `You should` should probably be `You would be able to`...

2017-08-23 13:47 UTC, timothysc reviewed
Could you outline why you decided to switch from a central config to passing params around, I actually liked it better b4.

2017-08-23 13:47 UTC, timothysc commented on cmd/kubeadm/app/cmd/init.go
> +	// Get directories to write files to; can be faked if we're dry-running
I'm still kind of flummoxed why we are passing args around vs. having a centralized configuration object.  For example, for testing and validation I may want to dump the state of config during a dryRun for *, which would include the tempdirs b/c I want to inspect the certs.

2017-08-23 13:47 UTC, timothysc commented on cmd/kubeadm/app/phases/certs/certs.go
> +		pkiDir,
I fail to see why this is better?

2017-08-24 06:58 UTC, luxas commented
/retest

2017-08-24 20:36 UTC, timothysc reviewed
/lgtm

2017-08-25 11:15 UTC, luxas commented
Rebased to get it into the queue

2017-08-25 13:02 UTC, luxas commented
/retest

2017-08-25 17:32 UTC, luxas commented
rebased again

2017-08-25 18:20 UTC, pipejakob commented
/retest

2017-08-25 21:01 UTC, merged

2018-03-27 14:32 UTC, f0o commented
Judging by the title `fully implement` - shouldn't there by a `--dry-run` option for join or reset even? ;)

2018-03-29 08:18 UTC, luxas commented
@f0o hehe, right, this was "fully implement" for `kubeadm init` :)
feel free to send a PR for join and reset :wink: