Fix swallowed error in registrytest
kubernetes/kubernetes pull request #51239
Opened 2017-08-24 02:23 UTC by alrs

**What this PR does / why we need it**: Fixes a swallowed error in the registrytest package.

```release-note NONE
```

2017-08-24 02:33 UTC, xiangpengzhao commented on pkg/registry/registrytest/etcd.go
> +		if err != nil {
This `err` will be caught by `return err` in #L232, so seems like it's not necessary to check it here. WDYT?

2017-08-24 02:43 UTC, enj requested changes

2017-08-24 02:43 UTC, enj commented on pkg/registry/registrytest/etcd.go
> +		if err != nil {
Instead of special casing this error, rename the `err` from `Accessor` to `errAccessor` so it does not shadow the error we care about.

2017-08-24 02:43 UTC, enj commented on pkg/registry/registrytest/etcd.go
> +		if err != nil {
It is being shadowed on line 220.

2017-08-24 02:45 UTC, enj commented
/ok-to-test

2017-08-24 03:04 UTC, xiangpengzhao commented on pkg/registry/registrytest/etcd.go
> +		if err != nil {
Ah, agreed :)

2017-08-24 20:46 UTC, brendandburns commented on pkg/registry/registrytest/etcd.go
> +		if err != nil {
why not just eliminate the shadowing declaration on 220?

eg
```go
var accessor
accessor, err = ...
```

2017-08-25 21:32 UTC, alrs commented
/test pull-kubernetes-e2e-gce-bazel

2017-08-25 21:43 UTC, enj commented
/lgtm

2017-08-25 22:41 UTC, alrs commented
/test pull-kubernetes-e2e-gce-bazel

2017-08-26 00:14 UTC, alrs commented
/test pull-kubernetes-e2e-gce-bazel

2017-08-26 02:29 UTC, alrs commented
/assign @brendandburns

2017-08-28 15:37 UTC, alrs commented
I think I've addressed the reviewers concerns, @brendandburns. lgty?

2017-09-01 22:02 UTC, alrs commented
@brendandburns is there anything I can do to get this merged before code freeze?

2017-09-01 23:10 UTC, BenTheElder commented
/test pull-kubernetes-bazel-build
/test pull-kubernetes-bazel-test

2017-09-02 23:39 UTC, alrs commented
/test pull-kubernetes-e2e-kops-aws

2017-09-03 00:29 UTC, alrs commented
/test pull-kubernetes-e2e-kops-aws

2017-09-03 06:08 UTC, alrs commented
/test pull-kubernetes-e2e-kops-aws

2017-09-03 21:53 UTC, alrs commented
/test pull-kubernetes-e2e-kops-aws

2017-09-05 21:44 UTC, brendandburns commented
/test pull-kubernetes-e2e-kops-aws
/approve

2017-09-05 23:24 UTC, alrs commented
/test pull-kubernetes-e2e-kops-aws

On Sep 5, 2017 3:08 PM, "k8s-ci-robot" <notifications@github.com> wrote:

> @alrs <https://github.com/alrs>: The following test *failed*, say /retest
> to rerun them all:
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-kops-aws d73b3d0
> <https://github.com/kubernetes/kubernetes/commit/d73b3d049d66475968ecf10fa2769b747e38a207>
> link
> <https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51239/pull-kubernetes-e2e-kops-aws/47110/> /test
> pull-kubernetes-e2e-kops-aws
>
> Full PR test history <https://k8s-gubernator.appspot.com/pr/51239>. Your
> PR dashboard <https://k8s-gubernator.appspot.com/pr/alrs>. Please help us
> cut down on flakes by linking to
> <https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md>.
> If you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://github.com/kubernetes/test-infra/blob/master/commands.md>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/51239#issuecomment-327317473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AABva4hjoGMX0AkqFSPx3v5PEpv-OYQoks5sfcZtgaJpZM4PAz3L>
> .
>

2017-09-06 01:34 UTC, alrs commented
/test pull-kubernetes-e2e-kops-aws
/test pull-kubernetes-e2e-gce-bazel

On Tue, Sep 5, 2017 at 6:16 PM, k8s-ci-robot <notifications@github.com> wrote:
> @alrs: The following tests failed, say /retest to rerun them all:
>
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-kops-aws d73b3d0 link /test pull-kubernetes-e2e-kops-aws
> pull-kubernetes-e2e-gce-bazel d73b3d0 link /test
> pull-kubernetes-e2e-gce-bazel
>
> Full PR test history. Your PR dashboard. Please help us cut down on flakes
> by linking to an open issue when you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here.
> If you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra repository. I understand the
> commands that are listed here.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2017-09-06 17:19 UTC, alrs commented
/test pull-kubernetes-e2e-kops-aws

2017-09-07 18:41 UTC, lavalamp commented
/lgtm cancel

2017-09-07 18:42 UTC, lavalamp commented on pkg/registry/registrytest/etcd.go
> +		accessor, err = meta.Accessor(obj)
This would make sense (fix a shadowing bug) if it weren't for the if statement on the line below. This appears to be a no-op as it is.

2017-09-07 18:44 UTC, lavalamp commented on pkg/registry/registrytest/etcd.go
> +		accessor, err = meta.Accessor(obj)
Ah, I see. It is about the subsequent usage (github hid that diff)

2017-09-07 18:44 UTC, lavalamp commented
/lgtm
/approve no-issue

2017-09-07 21:31 UTC, merged