fix etcdv2 timeout about and gofmt
kubernetes/kubernetes pull request #51383
Opened 2017-08-26 02:03 UTC by chenpengdev

What this PR does / why we need it:
Set etcdv2 per request timeout.
In my test cluster, when I power off a host that running a etcd container, we wait for fifteen minutes, then the test cluster recover from unscheduled status.

Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #

Special notes for your reviewer:
Etcdv3 has the same problem, it need update "google.golang.org/grpc" and "google.golang.org/grpc/keepalive" package

2017-08-26 02:09 UTC, chenpengdev commented
@dims  I delete invalid commit. please review these changes. Thanks again. I am sorry about this. #50900

2017-08-26 10:26 UTC, dims commented
/ok-to-test

2017-08-26 10:26 UTC, dims commented
/release-note-none

2017-08-27 00:03 UTC, smarterclayton commented
@kubernetes/sig-api-machinery-bugs

2017-08-27 06:45 UTC, chenpengdev commented
/retest

2017-08-28 20:57 UTC, lavalamp commented
/assign @jpbetz

2017-08-30 22:34 UTC, jpbetz requested changes
Can we also rename this issue to something clearer like:

"Increase etcdv2 timeout from 1s to 10s"?

We don't need to mention gofmt in the title.

2017-09-11 10:59 UTC, chenpengdev commented on staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd2.go
> +		HeaderTimeoutPerRequest: 10 * time.Second,
Why 10 seconds?
This is a bit arbitrary，HeaderTimeoutPerRequest specifies the time limit to wait for response, I don't have a better timeout default overall. 

Can you describe a bit more about the situation that caused the default limit to be exceeded? 
Poweroff a host running a etcd container，etcd connection don't broken, api request for etcd data wait for fifteen minutes， becase there is no Checking for dead etcd peers. 

English is not very good, please forgive me

2017-09-30 09:02 UTC, closed without merging