remove unused code and fix bug not return when list pod failed
kubernetes/kubernetes pull request #51519
Opened 2017-08-29 12:19 UTC by hzxuzhonghu

**What this PR does / why we need it**:
remove some unused redundant code, and fix bug: when list pod failed, 
job still deleted but pod may still exist  in func `deleteJob`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-08-29 12:50 UTC, soltysh requested changes
One nit, do you think you could write a test case covering this part?

2017-08-29 12:50 UTC, soltysh commented on pkg/controller/cronjob/cronjob_controller.go
> -	}
Please change this back, we want to log only when more than one time was left behind.

2017-08-30 01:19 UTC, hzxuzhonghu commented
@soltysh yes, I will add cases cover this

2017-08-30 04:15 UTC, hzxuzhonghu commented
@soltysh done. But I do not know why put fakePodControl in injection.go, which only useful for test. I think it's better to move to cronjob_controller_test.go. What do you think?

2017-08-30 20:33 UTC, janetkuo approved these changes

2017-08-30 20:34 UTC, janetkuo commented
/ok-to-test

2017-08-30 20:35 UTC, janetkuo commented
This lgtm, @soltysh would you take another look?

2017-08-31 06:18 UTC, hzxuzhonghu reviewed
done、

2017-08-31 06:19 UTC, hzxuzhonghu commented
kindly ping @soltysh test case covered, would you please review?

2017-08-31 08:04 UTC, hzxuzhonghu commented
/test pull-kubernetes-e2e-kops-aws

2017-08-31 09:03 UTC, soltysh commented on pkg/controller/cronjob/cronjob_controller.go
> +		return false
Good catch, thx!

2017-08-31 09:04 UTC, soltysh approved these changes

2017-08-31 09:04 UTC, soltysh commented
/lgtm
/approve

2017-08-31 09:06 UTC, soltysh commented
/approve no-issue

2017-08-31 09:47 UTC, hzxuzhonghu commented
/retest

2017-08-31 12:33 UTC, hzxuzhonghu commented
/test pull-kubernetes-e2e-kops-aws

2017-08-31 13:48 UTC, hzxuzhonghu commented
/retest

2017-09-02 19:58 UTC, merged