kubectl: Move generators into a subpackage
kubernetes/kubernetes pull request #51630
Opened 2017-08-30 14:11 UTC by tcharding

**What this PR does / why we need it**:

There are a bunch of generators within `kubectl`. Code organization would improve if we had a sub-package for generators.

This PR creates a sub-package `generators` and moves generator code from `kubectl` into the newly created sub-package. Updates call sites within `kubectl/cmd`. 

Some other code had to be moved around also to maintain cycle free imports.

**Which issue this PR fixes** 

fixes #36805

**Special notes for your reviewer**:

This is a big PR, I could think of no clear way to split it up any smaller. Suggestions welcome. 

**Release note**:

```release-note
NONE
```
/sig cli
/kind cleanup

2017-09-04 11:30 UTC, xiangpengzhao requested changes
please be sure to fix all the conflicts when rebasing.

2017-09-04 11:30 UTC, xiangpengzhao commented on pkg/kubectl/BUILD
> +<<<<<<< HEAD
Please fix the conflict when rebasing.

2017-09-04 11:30 UTC, xiangpengzhao commented on pkg/kubectl/BUILD
> +<<<<<<< HEAD
and here.

2017-09-04 22:44 UTC, tcharding commented on pkg/kubectl/BUILD
> +<<<<<<< HEAD
My bad. Thanks for pointing it out.

2017-09-04 23:44 UTC, xiangpengzhao commented
/ok-to-test

2017-09-05 02:22 UTC, tcharding commented
lol, 14 `lint`ing pull requests last week and I forgot to run lint on this one.

2017-09-06 05:58 UTC, tcharding commented
I believe the visibility declaration needs updating. I am unsure how to go about this.
```
ERROR: /home/tobin/build/go/src/k8s.io/kubernetes/pkg/kubectl/generators/BUILD:3:1: Target '//pkg/kubectl/util:go_default_library' is not visible from target '//pkg/kubectl/generators:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

2017-09-06 07:25 UTC, tcharding commented
Why `pull-kubernetes-verify` is failing on `hack/verfiy-golint.sh` has me stumped. `golint` does not throw any errors when run on `pkg/kubernetes/generators/*.go` locally.

2017-09-06 07:58 UTC, xiangpengzhao commented
@tcharding you can check the details:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51630/pull-kubernetes-verify/50227/

```
I0906 06:03:32.287] Verifying hack/make-rules/../../hack/verify-golint.sh
W0906 06:04:38.400] Errors from golint:
W0906 06:04:38.401] pkg/kubectl/constants/constants.go:21:2: exported const ServiceAccountNameAnnotation should have comment (or a comment on this block) or be unexported
W0906 06:04:38.401] 
W0906 06:04:38.402] Please review the above warnings. You can test via "golint" and commit the result.
W0906 06:04:38.402] If the above warnings do not make sense, you can exempt this package from golint
W0906 06:04:38.402] checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
W0906 06:04:38.402] 
I0906 06:04:38.503] FAILED   hack/make-rules/../../hack/verify-golint.sh	66s
```

2017-10-08 05:09 UTC, closed without merging