Remove kargakis from OWNERS, add tnozicka
kubernetes/kubernetes pull request #51877
Opened 2017-09-03 19:43 UTC by kargakis

/assign @smarterclayton 
/cc @janetkuo @tnozicka

2017-09-03 19:46 UTC, kargakis commented
/release-note-none

2017-09-04 06:18 UTC, tnozicka commented
/lgtm

2017-09-12 20:32 UTC, kargakis commented
/retest

2017-09-13 21:07 UTC, kargakis commented
@smarterclayton needs an approval

2017-09-18 06:44 UTC, janetkuo commented
/lgtm

2017-09-18 06:44 UTC, janetkuo approved these changes

2017-09-18 06:47 UTC, janetkuo requested changes
@kargakis would you add tnozicka as reviewer but not as approver?

2017-09-18 08:31 UTC, kargakis commented
@janetkuo @tnozicka is added as a reviewer already. Did you mean that I should add him as an approver too?

2017-09-19 06:29 UTC, janetkuo commented
I meant reviewer only, but not approver

2017-09-19 08:18 UTC, kargakis commented
@janetkuo I already do that..

2017-09-19 09:01 UTC, janetkuo commented on test/integration/deployment/OWNERS
> +  - tnozicka
remove this line

2017-09-19 09:05 UTC, kargakis commented on test/integration/deployment/OWNERS
> +  - tnozicka
done

2017-09-19 21:44 UTC, kargakis commented
/retest

2017-09-20 14:15 UTC, janetkuo approved these changes

2017-09-20 14:15 UTC, janetkuo commented
/lgtm

2017-09-21 12:22 UTC, janetkuo commented
/approve no-issue

2017-09-21 12:29 UTC, kargakis commented
@smarterclayton needs an approval

2017-09-21 20:01 UTC, smarterclayton commented
/approve

2017-09-21 20:02 UTC, smarterclayton commented
/approve no-issue

2017-09-21 20:03 UTC, merged