amend about kubectl create secret of changelog
kubernetes/kubernetes pull request #51886
Opened 2017-09-04 08:46 UTC by jianglingxia

**What this PR does / why we need it**:
kubectl create secret has a new option --from-env-file that populates a configmap from file which follows a key=val format for each line.
maybe copy the above line ,need change the configmap to secret,thanks!
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2017-09-04 11:01 UTC, xiangpengzhao requested changes
some nits.

2017-09-04 11:01 UTC, xiangpengzhao commented on CHANGELOG.md
>  		* `kubectl create configmap` has a new option `--from-env-file` that populates a configmap from file which follows a key=val format for each line. ([#38882](https://github.com/kubernetes/kubernetes
Since you are here, please also delete the extra indent.

2017-09-04 11:01 UTC, xiangpengzhao commented on CHANGELOG.md
> +		* `kubectl create secret` has a new option `--from-env-file` that populates a secret from file which follows a key=val format for each line.
and the indent here.

2017-09-04 11:01 UTC, xiangpengzhao commented on CHANGELOG.md
> +    * kubectl create secret has a new option --from-env-file that populates a secret from file which follows a key=val format for each line.
and here.

2017-09-04 11:01 UTC, xiangpengzhao commented
/ok-to-test

2017-09-05 02:27 UTC, jianglingxia commented
/test pull-kubernetes-unit
/test pull-kubernetes-e2e-kops-aws
/test pull-kubernetes-e2e-gce-etcd3

2017-09-05 20:52 UTC, brendandburns commented
/test pull-kubernetes-e2e-kops-aws
/test pull-kubernetes-e2e-gce-etcd3

2017-09-22 03:20 UTC, jianglingxia commented
/test pull-kubernetes-e2e-kops-aws
/test pull-kubernetes-e2e-gce-etcd3

2017-09-22 23:08 UTC, jianglingxia commented
/assign @brendandburns 
for approve

2017-09-25 01:41 UTC, jianglingxia commented
PTAL @smarterclayton thanks very much!
just now add some nit and squash into one commit!

2017-09-26 03:44 UTC, jianglingxia commented
PTAL @smarterclayton  @thockin

2017-10-10 06:46 UTC, jianglingxia commented
/assign @wojtek-t

2017-10-10 06:52 UTC, wojtek-t commented
/lgtm
/approve no-issue

2017-10-10 07:19 UTC, jianglingxia commented
/retest

2017-10-10 07:34 UTC, merged