amend some small mistakes on annotation
kubernetes/kubernetes pull request #51923
Opened 2017-09-05 02:29 UTC by WanLinghao

modified:   pkg/kubelet/dockershim/libdocker/client.go
modified:   staging/src/k8s.io/apiserver/pkg/storage/etcd/util/doc.go

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-09-05 02:45 UTC, cblecker commented
/ok-to-test
/release-note-none

2017-09-05 03:40 UTC, WanLinghao commented
/test pull-kubernetes-e2e-kops-aws 
/test pull-kubernetes-unit

2017-09-05 05:57 UTC, WanLinghao commented
/test pull-kubernetes-e2e-kops-aws

2017-09-05 06:44 UTC, resouer commented
/test pull-kubernetes-e2e-kops-aws

2017-09-05 08:24 UTC, resouer commented
I believe this is due to test flake. But the fix make sense.

/lgtm

2017-09-05 08:25 UTC, resouer approved these changes

2017-09-05 08:58 UTC, WanLinghao commented
/test pull-kubernetes-e2e-kops-aws

2017-09-05 09:44 UTC, WanLinghao commented
/test pull-kubernetes-e2e-kops-aws

2017-09-06 01:21 UTC, WanLinghao commented
/test pull-kubernetes-e2e-kops-aws

2017-09-06 03:21 UTC, cblecker commented
@WanLinghao `pull-kubernetes-e2e-kops-aws` has a known failure at the moment. please disregard.

2017-09-07 01:19 UTC, WanLinghao commented
/test pull-kubernetes-e2e-kops-aws

2017-09-08 09:02 UTC, CaoShuFeng commented
/LGTM

2017-09-09 03:12 UTC, WanLinghao commented
/test pull-kubernetes-e2e-kops-aws

2017-09-11 02:24 UTC, WanLinghao commented
/retest

2017-09-12 01:29 UTC, WanLinghao commented
@yujuhong @xiang90  PTAL

2017-09-12 16:37 UTC, yujuhong commented on pkg/kubelet/dockershim/libdocker/client.go
> +	// docker version should be at least 1.22.x
This is not a mistake. Docker 1.10.x uses the 1.22 API.

2017-09-13 01:17 UTC, resouer requested changes
Close this due to misunderstanding.

2017-09-13 01:18 UTC, closed without merging