hugepage requests should only be allowed by G or Bu pods
kubernetes/kubernetes pull request #52327
Opened 2017-09-12 08:10 UTC by tanshanshan

**What this PR does / why we need it**:
When pod QoS is  BestEffort, no need to calculate hugepages. ref #44817

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-09-12 12:11 UTC, xiangpengzhao commented
/release-note-none
/ok-to-test

2017-09-12 12:11 UTC, xiangpengzhao commented
/cc @derekwaynecarr

2017-09-12 19:03 UTC, timothysc commented
/assign @davidopp

2017-09-18 08:17 UTC, xiangpengzhao commented
@tanshanshan  please check and fix the test failures :)

2017-09-18 11:14 UTC, xiangpengzhao commented on plugin/pkg/scheduler/algorithm/predicates/predicates.go
> +	if !podBestEffort {
How about changing this line to `if !isPodBestEffort(pod) {` and remove the above two lines?

2017-10-13 03:30 UTC, tanshanshan commented
@davidopp @derekwaynecarr , PTAL

2017-10-13 03:30 UTC, tanshanshan commented
/retest

2017-10-18 18:16 UTC, derekwaynecarr requested changes
my intention per https://github.com/kubernetes/kubernetes/issues/53672 is to prevent a pod from making a hugepage request if it does not make a corresponding cpu or memory request.  

the code change we actually need is in the apiserver validation code path.

2017-10-18 18:16 UTC, derekwaynecarr commented on plugin/pkg/scheduler/algorithm/predicates/predicates.go
> +		if isPodBestEffort(pod) && v1helper.IsHugePageResourceName(rName) {
no scheduler changes are needed.

2017-10-23 04:16 UTC, closed without merging