add FlagPersistent flag in nodePort and other situation
kubernetes/kubernetes pull request #52394
Opened 2017-09-13 07:25 UTC by Lion-Wei

**What this PR does / why we need it**:
For AffinityClientIP service, origin code in ipvs didn't add Persistent flag, which is a bug, so I added it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
add FlagPersistent flag in nodePort and other situation

**Release note**:
```release-note
NONE
```

2017-09-13 07:26 UTC, Lion-Wei commented
/sig network

2017-09-13 07:27 UTC, Lion-Wei commented
/assign @thockin 
/cc @m1093782566

2017-09-13 07:28 UTC, m1093782566 commented
/ok-to-test

2017-09-13 07:45 UTC, m1093782566 commented
Looks good to me overall, except some nits: 

var `flags` in https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L955 and below are no needed any more, please remove them.

2017-09-13 07:57 UTC, m1093782566 requested changes

2017-09-13 07:57 UTC, m1093782566 commented on pkg/proxy/ipvs/proxier.go
> -		var flags utilipvs.ServiceFlags
the var `flags` is used in somewhere below. Since you remove it, please remove them as well.

2017-09-13 08:35 UTC, m1093782566 commented
LGTM from my side, ping @thockin for phase-2 review :)

2017-09-13 09:13 UTC, Lion-Wei commented
/test pull-kubernetes-e2e-gce-bazel
/test pull-kubernetes-node-e2e

2017-09-15 20:37 UTC, thockin commented
This needs an associated issue and a `closes #12345` in the FIRST COMMENT, or it can not be approved.

2017-09-18 03:18 UTC, Lion-Wei commented
@thockin  Thanks for your reminding,

2017-09-20 03:50 UTC, thockin commented
/lgtm
/approve

2017-09-23 06:55 UTC, Lion-Wei commented
/test pull-kubernetes-e2e-kubeadm-gce

2017-09-24 03:55 UTC, merged