Get fallback termination msg from docker when using journald log driver
kubernetes/kubernetes pull request #52503
Opened 2017-09-14 20:15 UTC by joelsmith

**What this PR does / why we need it**:

When using the legacy docker container runtime and when a container has `terminationMessagePolicy=FallbackToLogsOnError` and when docker is configured with a log driver other than `json-log` (such as `journald`), the kubelet should not try to get the container's log from the json log file (since it's not there) but should instead ask docker for the logs.

**Which issue this PR fixes** fixes #52502

**Special notes for your reviewer**:

**Release note**:
```release-note
Fixed log fallback termination messages when using docker with journald log driver
```

2017-09-14 20:22 UTC, sjenning commented
/ok-to-test
/sig node

2017-09-15 14:17 UTC, sjenning commented
/cc @feiskyer @yujuhong @Random-Liu can we get review on this please?

@derekwaynecarr this is a bug fix when using the legacy docker runtime when docker is using a non json-file logging driver, namely journald.  Should it go in 1.8?

2017-09-15 17:52 UTC, derekwaynecarr commented
i am wondering if we can abstract this better and not have to pass the legacy service in

2017-09-15 17:56 UTC, derekwaynecarr commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
> +	dockerLegacyService dockershim.DockerLegacyService,
can we pass in an interface scoped to what this provides?  for example, `LegacyLogProvider` or something?  this way, we don't need to pass the full legacy service through?

2017-09-15 17:57 UTC, derekwaynecarr commented on pkg/kubelet/kuberuntime/kuberuntime_container.go
> +				if m.dockerLegacyService != nil {
in this area, if we do this, i would prefer we just have a callback function that is passed in if a LegacyLogProvider func is provided?

2017-09-15 17:57 UTC, derekwaynecarr commented on pkg/kubelet/kuberuntime/kuberuntime_container.go
> +func (m *kubeGenericRuntimeManager) readLastStringFromLegacyContainerLogs(uid kubetypes.UID, name, namespace, containerId string) string {
this could go in the legacy log provider and kept out of this package.

2017-09-15 20:31 UTC, smarterclayton commented
Note that I spotted another error in #52567

2017-09-15 20:40 UTC, joelsmith commented
@derekwaynecarr Is this what you had in mind? I haven't squashed yet so that it's easy to compare the two versions. I personally prefer the original version, but am mostly indifferent.

2017-09-18 14:00 UTC, derekwaynecarr requested changes
this is close to what i was looking for, a few requests.

2017-09-18 14:00 UTC, derekwaynecarr commented on pkg/kubelet/dockershim/docker_service.go
> +type LegacyLogProvider interface {
define this interface in the kuberuntime package and not dockershim.

2017-09-18 14:00 UTC, derekwaynecarr commented on pkg/kubelet/dockershim/docker_service.go
> +func NewLegacyLogProvider(dls DockerLegacyService) LegacyLogProvider {
you can keep the implementation here.  if it causes a cycle, i could see an argument to move it in pkg/kubelet, but hopefully that is not the case.

2017-09-19 05:55 UTC, joelsmith commented
@derekwaynecarr I have moved the interface to `kuberuntime` and worked around the cycle. Everything works in my testing. Rebased and squashed.

2017-09-26 21:08 UTC, joelsmith commented
/retest

2017-10-17 16:15 UTC, derekwaynecarr approved these changes

2017-10-17 16:15 UTC, derekwaynecarr commented
/approve
/lgtm

2017-10-17 17:22 UTC, joelsmith commented
/test pull-kubernetes-unit

2017-10-17 20:18 UTC, merged