fix broke link in api
kubernetes/kubernetes pull request #52731
Opened 2017-09-19 15:30 UTC by u2takey

**What this PR does / why we need it**:
fix some broken link
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2017-09-19 16:34 UTC, xiangpengzhao requested changes

2017-09-19 16:34 UTC, xiangpengzhao commented on staging/src/k8s.io/api/batch/v1/types.go
> +	// More info: https://git.k8s.io/community/blob/master/contributors/design-proposals/apps/selector-generation.md
Did you try to visit this link? It doesn't work. The `blob/master/` is redundant here.

2017-09-19 16:34 UTC, xiangpengzhao commented on staging/src/k8s.io/api/batch/v1/types.go
> +	// More info: https://git.k8s.io/community/blob/master/contributors/design-proposals/apps/selector-generation.md
Please modify other links below as well :)

2017-09-20 03:40 UTC, xiangpengzhao commented
/lgtm

Thanks!

2017-09-20 07:27 UTC, u2takey commented
/retest

2017-09-20 11:33 UTC, xiangpengzhao commented
/ok-to-test
/retest

2017-09-20 12:30 UTC, nikhita commented
These are legit errors. Example:

```
I0920 12:04:55.393] -      "description": "Items is a list of LimitRange objects. More info: https://git.k8s.io/community/contributors/design-proposals/resource-management/admission_control_limit_range.md",
I0920 12:04:55.394] +      "description": "Items is a list of LimitRange objects. More info: https://git.k8s.io/community/contributors/design-proposals/admission_control_limit_range.md",
```

The comments are also used in the generated files. You'll need to use the `hack/update-*` scripts to update the comments in the generated files as well.

2017-09-22 06:03 UTC, CaoShuFeng commented
I think https://github.com/kubernetes/community/pull/1010 breaks a lot others.
Can you fix them all?

Some links show in docstring, so we need to run hack/update-all.sh to regenerate some codes.

2017-09-22 06:05 UTC, CaoShuFeng commented
/assign @grodrigues3

2017-09-27 18:27 UTC, xiangpengzhao commented
/lgtm cancel

2017-10-04 23:12 UTC, janetkuo reviewed
@u2takey do you plan to continue on this PR? Auto-generated files need to be updated to make verification pass. The easiest way to do this is running `hack/update-all.sh`

Please update `staging/src/k8s.io/api/extensions/v1beta1/types.go` too (links to https://git.k8s.io/community/contributors/design-proposals/security_context.md)

2017-10-06 05:37 UTC, u2takey commented
Sorry for late update. Updated with hack/update-all.sh @janetkuo

2017-10-06 08:51 UTC, u2takey commented
/retest

2017-10-06 11:07 UTC, nikhita commented
I tried testing this locally - `verify-swagger-spec` passes. (maybe related to https://github.com/kubernetes/kubernetes/issues/53481?)

/retest

2017-10-09 01:52 UTC, u2takey commented
/retest

2017-10-10 05:23 UTC, u2takey commented
/retest

2017-10-10 06:17 UTC, CaoShuFeng commented
Please run:
hack/update-swagger-spec.sh

2017-10-10 06:57 UTC, u2takey commented
@CaoShuFeng not work, i need rebase first?

2017-10-10 07:00 UTC, CaoShuFeng commented
>  i need rebase first?

It's right direction, I guess.

2017-10-10 07:18 UTC, u2takey commented
> `It's right direction, I guess.`
not work still

2017-10-10 08:10 UTC, u2takey commented
> It's right direction, I guess.

still not work

2017-10-10 08:39 UTC, CaoShuFeng commented
But it works in my environment.
http://paste.openstack.org/show/623191/

2017-10-10 08:44 UTC, CaoShuFeng commented
I have a bad suggestion:
you can modify api/swagger-spec/apps_v1.json manually.

2017-10-10 14:29 UTC, nikhita commented
@u2takey I created a PR on your branch (https://github.com/u2takey/kubernetes/pull/1) to update the swagger spec. Can you please merge that and squash the commits into a single commit? Thanks!

2017-10-11 06:02 UTC, u2takey commented
/retest

2017-10-18 00:15 UTC, tallclair commented
/lgtm

2017-10-19 12:31 UTC, u2takey commented
ping @nikhita for approve

2017-10-19 12:42 UTC, nikhita commented
@u2takey I cannot give approval. :)

/assign @smarterclayton for approval

2017-10-19 16:08 UTC, u2takey commented
/assign @smarterclayton

2017-10-27 13:15 UTC, nikhita commented
@u2takey Sorry that fixing links is turning out to be a tedious experience. :(

2017-10-28 13:59 UTC, u2takey commented
@nikhita that's ok. I found some broken links already fixed in master, closed this one.

2017-10-28 13:59 UTC, closed without merging