restrict this to NotFound errors
kubernetes/kubernetes pull request #52769
Opened 2017-09-20 07:00 UTC by zouyee

**What this PR does / why we need it**:
restrict err  to NotFound errors

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-09-20 07:39 UTC, dixudx requested changes

2017-09-20 07:39 UTC, dixudx commented on staging/src/k8s.io/client-go/discovery/discovery_client.go
> +			if err != nil && errors.IsNotFound(err) {
Same as above

2017-09-20 07:39 UTC, dixudx commented on staging/src/k8s.io/client-go/discovery/discovery_client.go
> +			if err != nil && errors.IsNotFound(err) {
Simply changing to this is not correct.

What if `err` is not `nil`, but `errors.IsNotFound(err)` is false?

2017-09-20 09:53 UTC, zouyee commented
/release-note-none

2017-09-20 14:13 UTC, jsafrane commented
/ok-to-test

2017-09-20 14:13 UTC, jsafrane commented
I know very little about client-go
/unassign

2017-09-21 07:41 UTC, zouyee commented
/retest

2017-10-23 06:58 UTC, closed without merging