[limitranger] default resource policy validate request <= default.limit
kubernetes/kubernetes pull request #53045
Opened 2017-09-26 08:16 UTC by weiwei04

**What this PR does / why we need it**:

the LimitRanger AdmissionController enforce two limit policies:
* **default resource policy**: set the default resource request/limit if pod.Spec.resource is empty

* **min/max resource policy**: make sure resource.request/limit is in limit range [min, max] range.

fixes: #51430 when enforce default resource policy, check `default.limit > request.resource`,  and return a better error message if the policy are violated.

**Which issue this PR fixes**: fixes #51430

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

2017-09-26 08:18 UTC, weiwei04 commented
/assign @derekwaynecarr

2017-09-26 08:18 UTC, weiwei04 commented
@derekwaynecarr please take a look :)

2017-10-18 18:54 UTC, derekwaynecarr commented
/ok-to-test

2017-10-18 19:11 UTC, derekwaynecarr requested changes
some updates requested throughout.

thanks for picking up the work here to make things better for users.

2017-10-18 19:11 UTC, derekwaynecarr commented on plugin/pkg/admission/limitranger/admission.go
> +			request, found := container.Resources.Requests[k]
if the request is greater than the default limit, we should just not set the limit.

i do not see why we need to track errors.

2017-10-18 19:11 UTC, derekwaynecarr commented on plugin/pkg/admission/limitranger/admission.go
> +	subErrs := []error{}
we dont need to track subErrs... just dont do the merge per prior comment.

2017-10-18 19:11 UTC, derekwaynecarr commented on plugin/pkg/admission/limitranger/admission_test.go
> +	input = getResourceRequirements(getComputeResourceList("100m", "512Mi"), getComputeResourceList("", ""))
we shouldnt get an error per earlier comments.

2018-04-17 09:58 UTC, closed without merging