Fix kubeadm swallowed errors
kubernetes/kubernetes pull request #53072
Opened 2017-09-26 19:00 UTC by alrs

**What this PR does / why we need it**: Fixes nine swallowed errors in kubeadm, and adds descriptive error returns to Init.Run().

**Special notes for your reviewer**: I've resubmitted this PR after it required a rebase. Previously, I submitted this PR as https://github.com/kubernetes/kubernetes/pull/52591

```release-note NONE
```

2017-09-26 22:05 UTC, alrs commented
/test pull-kubernetes-e2e-gce-bazel
/test pull-kubernetes-e2e-gce-etcd3

2017-09-26 23:00 UTC, alrs commented
/test pull-kubernetes-e2e-gce-bazel
/test pull-kubernetes-e2e-gce-etcd3

2017-09-27 00:18 UTC, alrs commented
/approve

2017-10-05 00:13 UTC, errordeveloper commented
cc @luxas

2017-10-11 03:37 UTC, alrs commented
@errordeveloper, @luxas: Does this PR look merge-ready to you?

2017-10-11 16:40 UTC, luxas reviewed
Thanks for the ping, now noticed this PR among my ever-growing backlog of unread notifications.

Left a couple of comments, please fix.
Thank you for this contribution :smile:!

2017-10-11 16:40 UTC, luxas commented
(also, please squash all commits into one)

2017-10-16 15:47 UTC, timothysc requested changes
Please squash commits and address minor nits.

2017-10-16 15:47 UTC, timothysc commented on cmd/kubeadm/app/phases/upgrade/staticpods.go
> +		return err
Why did you not re-wrap here?

2017-10-18 00:39 UTC, alrs commented on cmd/kubeadm/app/phases/upgrade/staticpods.go
> +		return err
@timothysc got it, thanks.

2017-10-26 01:06 UTC, alrs commented on cmd/kubeadm/app/cmd/init.go
> +		return fmt.Errorf("error getting directories to use:%v", err)
I was mimicking the style found elsewhere in this file, I'll change it everywhere.

2017-10-26 02:23 UTC, alrs commented
@timothysc I think I've got this PR where you want it. The Github UI shows that "Required Github CI test is not green: pull-kubernetes-bazel-test", though I see that "pull-kubernetes-bazel-test" has a green checkmark, so 🤷

2017-10-28 13:11 UTC, luxas approved these changes
/lgtm

2017-10-28 13:11 UTC, luxas commented
/approve no-issue

2017-10-28 13:51 UTC, luxas commented
/retest

2017-10-28 14:26 UTC, merged