[OpenStack]Add codes to check the count of nodes(members)
kubernetes/kubernetes pull request #53197
Opened 2017-09-28 10:03 UTC by FengyunPan

After merging this PR(#53146), if there is no available nodes for
the loadbalancer service, UpdateLoadBalancer() will run panic.

**Release note**:
```release-note
NONE
```

2017-09-29 19:40 UTC, dims commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +		return nil, fmt.Errorf("There is no available nodes for LoadBalancer service %s/%s", apiService.Namespace, apiService.Name)
"There are" instead of "There is"

2017-09-29 19:41 UTC, dims commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +	if len(lbaas.opts.SubnetId) == 0 && len(nodes) != 0 {
`len(nodes) > 0`?

2017-09-29 19:41 UTC, dims commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +		return nil, fmt.Errorf("There is no available nodes for LoadBalancer service %s/%s", apiService.Namespace, apiService.Name)
"There are" like above

2017-09-29 19:41 UTC, dims requested changes
please see inline comments

2017-10-02 16:10 UTC, xsgordon commented
/sig openstack

2017-10-09 02:03 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +		return nil, fmt.Errorf("There is no available nodes for LoadBalancer service %s/%s", apiService.Namespace, apiService.Name)
Oops, done.

2017-10-09 02:03 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +		return nil, fmt.Errorf("There is no available nodes for LoadBalancer service %s/%s", apiService.Namespace, apiService.Name)
Done.

2017-10-09 02:03 UTC, FengyunPan commented on pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
> +	if len(lbaas.opts.SubnetId) == 0 && len(nodes) != 0 {
Right, Done.

2017-10-09 12:01 UTC, dims commented
/approve no-issue
/lgtm

2017-10-09 18:18 UTC, merged