improve error message for statefulset rollout status
kubernetes/kubernetes pull request #53375
Opened 2017-10-03 09:18 UTC by mfojtik

Change error message:

```
→ kubectl rollout status sts/testapp
error: OnDelete updateStrategy does not have a Status`
```
to:
```
→ kubectl rollout status sts/testapp
error: statefulset "testapp" update strategy "OnDelete" does not provide status
```

2017-10-03 09:18 UTC, mfojtik commented
/cc kargakis

2017-10-03 11:16 UTC, kargakis commented on pkg/kubectl/rollout_status.go
> +		return "", true, fmt.Errorf("statefulset %q update strategy %q does not provide status", name, apps.OnDeleteStatefulSetStrategyType)
This needs to be consistent with DaemonSets. Can you fix it there too?

2017-10-04 20:54 UTC, fabianofranz commented
/unassign

2017-10-04 20:57 UTC, 0xmichalis requested changes
This needs to be consistent with DaemonSets. Can you fix it there too?

2017-10-05 10:33 UTC, mfojtik commented
@kargakis done, good catch.

2017-10-05 10:45 UTC, kargakis commented on pkg/kubectl/rollout_status.go
>  	if daemon.Spec.UpdateStrategy.Type != extensions.RollingUpdateDaemonSetStrategyType {
There is a second DaemonSet strategy in the works (https://github.com/kubernetes/community/pull/977) that should provide status. In reality, we should never have a strategy that does not provide status so this check should really be like the StatefulSet check:
```go
if daemon.Spec.UpdateStrategy.Type == extensions.OnDeleteDaemonSetStrategyType {
```

2018-05-05 00:54 UTC, closed without merging