fix evict logic for critical pods and static pods
kubernetes/kubernetes pull request #53693
Opened 2017-10-11 03:20 UTC by dixudx

**What this PR does / why we need it**:
Do not evict critical pods even if they are not static pod when feature gate for `ExperimentalCriticalPodAnnotation` has been enabled.

Also critical pods and static pods are not usually coupled together.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53659

**Special notes for your reviewer**:
/assign @gyliu513 @dashpole 

**Release note**:

```release-note
fix evict logic for critical pods and static pods
```

2017-10-11 07:41 UTC, gyliu513 commented on pkg/kubelet/eviction/eviction_manager.go
> +		kubelettypes.IsCriticalPod(pod)) || kubepod.IsStaticPod(pod) {
Not only here, but also  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L380

2017-10-11 07:42 UTC, gyliu513 requested changes
Not only here, but also  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L380

2017-10-11 07:47 UTC, dixudx commented
@gyliu513 Updated. PTAL.

2017-10-11 07:53 UTC, gyliu513 commented on pkg/kubelet/eviction/eviction_manager.go
>  		// If the pod is marked as critical and static, and support for critical pod annotations is enabled,
comments also need some update, we will now do not evict static *or* critical pod.

2017-10-11 14:13 UTC, gyliu513 commented
/ok-to-test

2017-10-11 17:24 UTC, dashpole commented
We should definitely not merge this.  This would break kubernetes resource management guarantees.

2017-10-14 08:05 UTC, gyliu513 commented
@dashpole can you please show more detail for how does this PR  break kubernetes resource management guarantees? Thanks!

2017-10-30 18:52 UTC, dashpole commented
Say I have 2 pods with memory requests and limits on a node with Capacity=10G.
Pod1: Request=1G, Limit=1G
Pod2 (static): Request=0, Limit=10G

Pod2 can use all of the memory on the node and deny Pod1 its requests.  Part of the kuberentes resource guarantees are that pods can access resources they request.
The critical annotation was introduced with an extremely limited scope because of this.  We highly recommend not using the annotation with static pods, but it can be a tool to prevent permanent eviction of such pods.

2018-04-02 00:07 UTC, gyliu513 commented
@dixudx I think we can close this one

2018-04-02 01:01 UTC, closed without merging