Add pod related conformance annotations
kubernetes/kubernetes pull request #53899
Opened 2017-10-13 17:33 UTC by bradtopol

Signed-off-by: Brad Topol <btopol@us.ibm.com>

This PR adds pod related conformance annotations to the e2e test suite.

The PR fixes a portion of #53822.  It focuses on adding conformance annotations as defined by the Kubernetes Conformance Workgroup for a subset of the pod based e2e conformance tests. 
**Special notes for your reviewer**:
Please see https://docs.google.com/spreadsheets/d/1WWSOqFaG35VmmPOYbwetapj1VPOVMqjZfR9ih5To5gk/edit#gid=62929400
for the list of SIG Arch approved test names and descriptions that I am using.
**Release note**:

```release-note NONE
```

2017-10-13 18:19 UTC, brahmaroutu commented
ping @spxtr @fejta can you please review.

2017-10-15 17:31 UTC, dims commented
/ok-to-test

2017-10-16 14:50 UTC, bradtopol commented
/retest

2017-10-17 18:39 UTC, bradtopol commented
/test pull-kubernetes-unit

2017-10-17 18:40 UTC, bradtopol commented
/test pull-kubernetes-verify

2017-10-17 19:17 UTC, bradtopol commented
@spxtr @fejta Do you know how I can move past the test failure issue I keep encountering? All I did was add some comments to the code

2017-10-17 19:28 UTC, timothysc commented
/test pull-kubernetes-unit 
/test pull-kubernetes-verify

2017-10-18 02:32 UTC, timothysc requested changes
please squash commits then lgtm.

2017-10-18 15:00 UTC, timothysc approved these changes
/lgtm

2017-10-18 16:17 UTC, merged