flaky test: kubectl describeservice accout not stable sequence output…
kubernetes/kubernetes pull request #54563
Opened 2017-10-25 13:09 UTC by zjj2wry

…,so cause ci faild

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-10-25 13:15 UTC, zjj2wry commented
Fixes #54564

2017-10-25 13:39 UTC, zjj2wry commented
/test pull-kubernetes-unit

2017-10-25 14:08 UTC, zjj2wry commented
/kind flake
/kind cli

2017-10-25 14:45 UTC, dixudx requested changes

2017-10-25 14:45 UTC, dixudx commented on pkg/printers/internalversion/describe_test.go
> +	for _, expected := range expectedOut {
Well, I don't like changing to this, since `expectedOut` is exactly what we expect to see.

2017-10-25 17:20 UTC, ericchiang reviewed
Since the flake is that the lines can be out of order why not just sort the lines?

```diff
+       sortLines := func(s string) string {
+               lines := strings.Split(out, "\n")
+               sort.Strings(lines)
+               return strings.Join(lines, "\n")
+       }
+
+       out = sortLines(out)
+       expectedOut = sortLines(expectedOut)
```

2017-10-26 05:32 UTC, zjj2wry commented
/test pull-kubernetes-unit

2017-10-26 06:58 UTC, dixudx commented
/lgtm

2017-10-26 10:28 UTC, zjj2wry commented
/assign @fabianofranz ptal

2017-10-26 11:58 UTC, deads2k commented
I don't think this is the correct solution.  The describe itself should be predictable. See https://github.com/kubernetes/kubernetes/pull/54628

2017-10-26 13:06 UTC, zjj2wry commented
@deads2k got, will respect it in future, thank you ~

2017-10-26 14:58 UTC, closed without merging