test/integration: port etcd_storage_path_test.go to kube-apiserver testing
kubernetes/kubernetes pull request #55155
Opened 2017-11-06 11:40 UTC by sttts

This was moved out of https://github.com/kubernetes/kubernetes/pull/51685 to
unblock kube-apiserver refactoring.

2017-11-07 19:13 UTC, enj requested changes

2017-11-07 19:13 UTC, enj commented on test/integration/etcd/etcd_storage_path_test.go
> -			kubeAPIServerConfig.ExtraConfig.APIResourceConfigSource = &allResourceSource{} // force enable all resources
How do we get this behavior back?

2017-12-11 14:03 UTC, sttts commented
@enj do you want to take this over or do you have comments?

2017-12-11 18:30 UTC, enj commented
@sttts my previous comments stand.  I have too much going on ATM to take this over.  https://github.com/kubernetes/kubernetes/pull/55155#discussion_r149471818 is my main concern.

2017-12-11 18:32 UTC, sttts commented
@enj I keep this open for the moment. Maybe next year we have some more time to look at it again.

2019-05-10 19:38 UTC, spiffxp commented
/remove-lifecycle frozen
/close
I'm closing this due to inactivity.  Please /reopen if you wish to continue working on this

2019-05-10 19:38 UTC, closed without merging

2019-05-10 19:40 UTC, spiffxp commented
/lifecycle rotten