Allow to set DNS domain for e2e tests
kubernetes/kubernetes pull request #55315
Opened 2017-11-08 12:48 UTC by lukaszo

**What this PR does / why we need it**: PR allows to set dns domain for e2e tesst to use.  `cluster.local` was hardcoded in all tests. 
When cluster was deployed with different dns domain some e2e would fail. Especially 2 conformance tests.

**Release note**:
```release-note
Added --dns-domain option for e2e tests. Defaults to `cluster.local`
```

2017-11-08 18:39 UTC, lukaszo commented
/retest

2017-11-14 08:35 UTC, lukaszo commented
ping @soltysh @dnardo I'm not sure who else may be interested here

2017-11-15 12:46 UTC, dims commented
cc @kubernetes/sig-testing-pr-reviews

2017-11-15 14:40 UTC, spiffxp requested changes
/approve
I like the intent of the change

But I think there are few additional places that have the hardcode that aren't necessarily exercised by PR tests.  Might be able to just drop the cluster.local, since DNS doesn't always need the FQDN?

e.g.:
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/statefulset/cassandra/statefulset.yaml#L48
- https://github.com/kubernetes/kubernetes/blob/master/test/images/resource-consumer/controller/controller.go#L199

2018-04-14 15:53 UTC, closed without merging