Webhook e2e test: PUT and PATCH operations
kubernetes/kubernetes pull request #55533
Opened 2017-11-12 00:46 UTC by janetkuo

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: depends on #55127
@kubernetes/sig-api-machinery-api-reviews 

**Release note**:

```release-note
NONE
```

2017-11-13 01:58 UTC, janetkuo commented
/retest

2017-11-13 02:09 UTC, caesarxuchao commented
@janetkuo see https://github.com/kubernetes/kubernetes/pull/55127#issuecomment-343773245

Sorry, you'll have to rebase onto my latest code to get rid of the test failure.

2017-11-13 22:19 UTC, mml requested changes
Just some small changes.

2017-11-13 22:19 UTC, mml commented on test/e2e/apimachinery/webhook.go
> +	// Update the configmap (PUT), the request should be rejected
If we just mention PUT in the By() line, I think it will be more useful and we can delete this comment.

2017-11-13 22:19 UTC, mml commented on test/e2e/apimachinery/webhook.go
> +	// Update the configmap (PATCH), the request should be rejected
Similar as above.  Can we add a By() call that expalins this step and also mentions that we are issuing a PATCH, then delete the comment?

2017-11-13 22:59 UTC, janetkuo commented
@mml comments addressed, PTAL

2017-11-13 23:26 UTC, mml approved these changes

2017-11-13 23:26 UTC, mml commented
/lgtm

2017-11-13 23:41 UTC, lavalamp commented
/approve

2017-11-14 00:51 UTC, janetkuo commented
Rebased

2017-11-14 08:10 UTC, merged