Ensure GCE AlphaFeatureGate initialized
kubernetes/kubernetes pull request #55545
Opened 2017-11-12 06:51 UTC by osoriano

If no config file is specified for the controller-manager,
the GCE CloudConfig.AlphaFeatureGate property is not initialized.

This can cause a panic when checking for alpha features in the GCE
provider.

Closes #55544

2017-11-12 11:30 UTC, dixudx commented on pkg/cloudprovider/providers/gce/gce.go
> +		featureMap := make(map[string]bool)
Actually I would like to move these to [Line 242](https://github.com/kubernetes/kubernetes/blob/e93819049db49694718bc9c96e67050d366c6f63/pkg/cloudprovider/providers/gce/gce.go#L242).

2017-11-13 19:17 UTC, roberthbailey commented
@dixudx - please ensure that you sign the CLA. 

Also, moving that code to line 242 makes sense to me.

2017-11-14 01:32 UTC, dixudx commented
@osoriano Please sign the CLA. Thanks.

2017-11-14 05:18 UTC, osoriano commented
@dixudx I moved the AlphaFeatureGate initialization to its own block on line 242
Also, I signed the CLA, thanks

2017-11-14 06:17 UTC, dixudx requested changes

2017-11-14 06:17 UTC, dixudx commented on pkg/cloudprovider/providers/gce/gce.go
> +		featureMap := make(map[string]bool)
Actually I mean, 

```Go
featureMap := make(map[string]bool)
cloudConfig.AlphaFeatureGate = &AlphaFeatureGate{featureMap}
if configFile != nil {
   ...
   alphaFeatureGate, err := NewAlphaFeatureGate(configFile.Global.AlphaFeatures)
   if err != nil {
       ...
   }
   cloudConfig.AlphaFeatureGate = alphaFeatureGate
   ...
}
```

2017-11-14 06:18 UTC, dixudx commented on pkg/cloudprovider/providers/gce/gce.go
> +		featureMap := make(map[string]bool)
We don't need two blocks `if configFile != nil`.

Please also squash your commits. Thanks for your contribution.

2017-11-14 16:51 UTC, osoriano commented
Ok, makes sense. I moved the code from the else block to line 242.

I redeployed and the LoadBalancer was created.

2017-11-14 17:59 UTC, roberthbailey commented
/lgtm
/approve

2017-11-14 18:38 UTC, osoriano commented
/assign @saad-ali

2017-11-16 04:08 UTC, cblecker commented
/ok-to-test

2017-11-22 23:01 UTC, saad-ali commented
/lgtm
/approve

2017-11-23 00:02 UTC, jberkus commented
/priority critical-urgent

/remove-priority important-soon

adjusting priorities for code freeze.

2017-11-23 00:52 UTC, merged