Validate podDisruptionBudgetStatus updates
kubernetes/kubernetes pull request #56540
Opened 2017-11-29 03:23 UTC by zouyee

**What this PR does / why we need it**:

Validate podDisruptionBudgetStatus updates

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2017-12-05 02:40 UTC, dixudx requested changes

2017-12-05 02:40 UTC, dixudx commented on pkg/registry/policy/poddisruptionbudget/strategy.go
> +	return field.ValidatePodDisruptionBudgetUpdate(obj.(*policy.PodDisruptionBudget), old.(*policy.PodDisruptionBudget))
Should be `validation.ValidatePodDisruptionBudgetUpdate` here.

No method name `ValidatePodDisruptionBudgetUpdate` exists in package `field`.

2017-12-07 01:58 UTC, zouyee commented
gentle ping @dixudx

2017-12-07 02:49 UTC, dixudx commented
/ok-to-test

2018-04-08 06:18 UTC, closed without merging