Update eviction_manager.go
kubernetes/kubernetes pull request #56575
Opened 2017-11-29 14:27 UTC by eastlondoner

**What this PR does / why we need it**:
Demonstrates checking resource usage before evicting pods.
 - it's probably not as simple as this but I'm interested to find out more

**Which issue(s) this PR fixes**:
`fixes #56573`

**Special notes for your reviewer**:

**Release note**:
NONE

2017-11-30 03:33 UTC, dixudx commented
/ok-to-test

@eastlondoner Please squash your commits.

2017-11-30 10:19 UTC, eastlondoner commented
/retest

2017-11-30 11:20 UTC, eastlondoner commented
/retest

2017-11-30 11:56 UTC, eastlondoner commented
I don't understand why all these tests are failing because of a simple change. There's nothing more I can do here

2017-11-30 13:04 UTC, eastlondoner commented
making progress on not breaking the

2017-12-01 11:02 UTC, eastlondoner commented
@Random-Liu - so what do you think?

2017-12-11 20:39 UTC, dashpole commented
The issue with this is that stats collection is periodic, and occurs every 10 seconds.  `makeSignalObservations` currently retrieves these cached metrics.
This addition would, in nearly all cases, simply retrieves the same metrics that the eviction manager previously determined to indicate disk pressure.
Once we have on-demand metrics: https://github.com/kubernetes/kubernetes/pull/56112, this change is something we should consider.

2017-12-11 21:00 UTC, dashpole commented
/assign

2017-12-12 11:58 UTC, eastlondoner commented
Interesting! I'm not sure you've seen how long it takes to clean up docker images and containers when docker is using overlay (not overlay2) and the disk is a Google Persistent Disk (on some kind of SAN) when node consumption is high enough to trigger disk pressure. N.b. This is the setup of GKE - not some weird home brew.

Anyway it takes >30 minutes. So, I think there's a pragmatic argument to be made that this change is better than not making this change - as I think it will almost always result in better experience and performance, even if it is a bit non-deterministic

2017-12-12 14:59 UTC, ncdc commented
/unassign

2017-12-12 15:51 UTC, eastlondoner commented
@dashpole 
I've been thinking about this. When you say:
>This would, in nearly all cases, simply retrieves the same metrics that the eviction manager previously determined to indicate disk pressure.

I actually thing that in *most cases where it makes a difference* this will work.

Either the node cleanup did clear a load of space, in which case it will probably have taken some time and so checking again is worthwhile because the signal should have changed.

Or the node cleanup didn't clear a load of space, in which case it ran quickly so the fact that you are getting stale values is probably irrelevant because even if the values were live we probably want to proceed by evicting a pod.

2017-12-20 19:07 UTC, dashpole requested changes
I think I would prefer including this logic in `reclaimNodeLevelResources`.  That way we only re-check observations if we took some action to reclaim resources.  This would avoid an immediate double-query for metrics in the case where we do not have a reclaim function (e.g. memory evictions).  This also needs unit testing.

2017-12-20 19:07 UTC, dashpole commented on pkg/kubelet/eviction/eviction_manager.go
> +	if len(thresholdsMet(m.thresholdsMet, observations, true)) == 0 {
I think you need to use `thresholds` instead of `m.thresholdsMet` so that it only considers those which previously had updated stats.

2017-12-20 19:07 UTC, dashpole commented on pkg/kubelet/eviction/eviction_manager.go
> +	debugLogObservations("observations", observations)
can we differentiate this from the previous `debugLogObservations`?  Maybe call it "observations after resource reclaim".

2018-02-19 18:05 UTC, dashpole commented
I implemented something similar to this in #59841.  This PR is no longer required.

2018-02-19 18:05 UTC, closed without merging