using bool instead of error
kubernetes/kubernetes pull request #56602
Opened 2017-11-30 02:20 UTC by zouyee

**What this PR does / why we need it**:

CommonAccessor returns a Common interface for the provided object or a boolean value wether the object to provide list

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```NONE

```

2017-11-30 02:25 UTC, dims commented
/ok-to-test

2017-12-01 00:30 UTC, enj requested changes

2017-12-01 00:30 UTC, enj commented on pkg/api/ref/ref.go
> +		listMeta, boolean = meta.CommonAccessor(obj)
The convention is `foo, ok = ...`

2017-12-01 00:30 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/registry/rest/table.go
> +		if m, boolean := meta.CommonAccessor(object); err == nil {
Bug: `err == nil` is not valid, should be checking the bool.

2017-12-01 00:30 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/registry/rest/table.go
> +	if m, boolean := meta.ListAccessor(object); !boolean {
Check is inverted.

2017-12-01 00:30 UTC, enj commented on staging/src/k8s.io/apimachinery/pkg/api/meta/meta.go
> +// CommonAccessor returns a Common interface for the provided object or a boolean value wether the object to
```
CommonAccessor returns the metav1.Common interface for the provided object.
The bool must be used to determine if the object provides this interface.
```

2017-12-01 00:33 UTC, enj commented
@sttts @smarterclayton are we trying to prevent changes to the staging bits?

2017-12-01 08:44 UTC, sttts commented
> are we trying to prevent changes to the staging bits?

No, we don't. I don't expect many 3rdparty projects which use this functionality (none visible at https://github.com/search?p=1&q=CommonAccessor+language%3AGo&type=Code&utf8=%E2%9C%93). Moreover, the fix is obvious and golang complains.

2017-12-04 02:48 UTC, closed without merging