refactor NewMainKubelet func, extract QueryVariablesFromCloud func
kubernetes/kubernetes pull request #56697
Opened 2017-12-01 14:08 UTC by oulinbao

**What this PR does / why we need it**:
refactor long function and put the new func to cloud.go

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

2017-12-01 14:44 UTC, feiskyer requested changes
Could you add unit tests for the new function?

2017-12-01 14:58 UTC, oulinbao commented
OK，thank you. I will add it tomorrow.


发自网易邮箱大师
On 12/01/2017 22:44, Pengfei Ni wrote:

@feiskyer requested changes on this pull request.

Could you add unit tests for the new function?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-12-02 05:23 UTC, jhorwit2 commented
/area cloudprovider

2017-12-02 05:33 UTC, jhorwit2 requested changes
Thanks for the PR @oulinbao!

I'm not sure this is the best place for this code though. The reason I say that is this is not valuable to the external cloud controller manager since it cannot use the same methods as the kubelet to obtain node information, so this code would be removed once the providers are out-of-tree. The CCM uses methods already on the Instances interface to accomplish this and I don't think we should combine kubelet specific logic into the cloud provider that can't be reused by the CCM. 

cc @wlan0 @luxas

2017-12-02 13:45 UTC, oulinbao commented
@feiskyer, I have added unit test for this function.
@jhorwit2, I have move the new function back to kubelet.go.
Thanks a lot to you.

2017-12-02 14:16 UTC, jhorwit2 commented
/ok-to-test

2017-12-02 15:16 UTC, jhorwit2 requested changes

2017-12-02 15:16 UTC, jhorwit2 commented on pkg/kubelet/kubelet.go
> +func queryVariablesFromCloud(cloud cloudprovider.Interface, hostName string, nodeName *types.NodeName, cloudIPs *[]net.IP, cloudNames *[]string) (err error) {
The in/out parameters aren't a common pattern used in Kubernetes. We should use multiple return parameters instead. 

`queryVariablesFromCloud` is a little vague for a function name.

2017-12-03 13:59 UTC, oulinbao commented
@jhorwit2  I have changed the in/out parameters to return value format.

2017-12-04 02:41 UTC, oulinbao commented
/retest

2017-12-04 03:52 UTC, oulinbao commented
/retest

2017-12-04 05:53 UTC, jhorwit2 commented
@oulinbao you need to run `hack/update-bazel.sh`

2017-12-04 06:00 UTC, oulinbao commented
OK，thanks.




发自网易邮箱大师
On 12/04/2017 13:54, Josh Horwitz wrote:

@oulinbao you need to run hack/update-bazel.sh

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-12-04 13:42 UTC, oulinbao commented
/retest

2017-12-11 15:13 UTC, oulinbao commented
@feiskyer, I have added unit test for this function.

2018-01-04 03:18 UTC, feiskyer approved these changes
/lgtm

2018-01-05 09:10 UTC, feiskyer commented
/assign @vishh for approval

2018-01-28 07:42 UTC, oulinbao commented
/test all

2018-07-07 10:45 UTC, closed without merging