cloud-provider needs cluster-role to apply taint to the node
kubernetes/kubernetes pull request #56709
Opened 2017-12-01 17:27 UTC by gnufied

When volume is stuck in attaching state on AWS, cloud-provider
needs to taint the node. But the node can not be tainted
without proper access. Without this change https://github.com/kubernetes/kubernetes/pull/55558 will not work.

cc @jsafrane @liggitt 

/sig storage

2017-12-01 17:30 UTC, gnufied commented
/assign @liggitt

2017-12-01 17:36 UTC, gnufied commented
/test pull-kubernetes-bazel-build

2017-12-01 18:12 UTC, ericchiang commented
/sig auth

Probably want this for 1.9, right? cc @kubernetes/kubernetes-release-managers

2017-12-01 18:26 UTC, liggitt commented
/assign @deads2k

On Dec 1, 2017, at 12:31 PM, Hemant Kumar <notifications@github.com> wrote:

/assign @liggitt <https://github.com/liggitt>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/56709#issuecomment-348557139>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AA70cvn7OukIOGDCdFVDOjdO_dJgo9xUks5s8DfhgaJpZM4Qyqcu>
.

2017-12-01 19:00 UTC, gnufied commented
@ericchiang yes I will need this for 1.9, because without this already merged PR is non-functional.  When I tested my original PR, I tested on a cluster without RBAC. :(

Also, the AWS condition can not be easily reproduced - https://aws.amazon.com/premiumsupport/knowledge-center/ebs-stuck-attaching/ . It is however a well known problem that occurs and all subsequent attaches on nodes will fail too and that is why we decided to taint the node.

To test this, I locally modified attach function to always throw timeout error and after policy changes here everything works as expected.

2017-12-02 05:08 UTC, jhorwit2 commented
/area cloudprovider
/sig cluster-lifecycle

I feel we should be careful about introducing a `system:cloud-provider` service account when the requirement is specific to a single cloud provider; especially since the providers should be moving out of tree soonish. 

Does this impact the move to the external CCM? Can we deprecate this when the time comes so it can be moved to AWS specific implementation?

cc @wlan0 @luxas

2017-12-02 05:18 UTC, jhorwit2 requested changes

2017-12-02 05:18 UTC, jhorwit2 commented on plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
> +				rbac.NewRule("patch", "update").Groups(legacyGroup).Resources("nodes").RuleOrDie(),
Is `update` required? I only see `patch` being used in `controller.AddOrUpdateTaintOnNode`.

2017-12-02 12:46 UTC, gnufied commented
@jhorwit2 the `cloud-provider` service account already exists - https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/namespace_policy.go#L88 .

2017-12-02 13:33 UTC, jhorwit2 commented
Ah, you are correct. It appears GCE uses it. 

Should we have AWS use an alternative service account like aws-cloud-provider? Based on what you linked, the AWS provider now has create/read access to all configmaps in kube-system and vice versa the GCE provider gained all the abilities this PR adds. This doesn't keep with the principle of least privilege the other controllers have.

2017-12-02 13:55 UTC, gnufied commented
But cloud-providers are not tied to specific controllers. They are common to all controllers. If we are going to create `aws-cloud-provider` service account then we may as well create a `gce-service-account` because AWS cloudprovider does not need to read ConfigMaps.

2017-12-02 14:08 UTC, jhorwit2 commented
@gnufied I'm not following what you mean. A good chunk of the cloud provider logic is tied to specific controllers like the cloud node controller, service controller, and pvl controller. Those controllers have their own service accounts when the KCM or CCM is ran with `--use-service-account-credentials`. In those cases the SA token is never passed to the cloud provider code which the parent PR introduces. 

I do agree that the cloud-provider SA shouldn't be called just cloud-provider. I think there's other problems with fixing that for GCE since auto reconciliation for RBAC is only additive afaik. That doesn't mean we shouldn't do the right thing for AWS since this is the first time it's using the SA in the cloud provider code.

2017-12-02 14:38 UTC, liggitt commented
There was a request to make the existing service account and role gce specific since it is only used be gce and has gce specific permissions.

2017-12-02 14:45 UTC, gnufied commented
I meant - bootstrapping api-server with set of service accounts which give preferential treatment to certain cloudproviders seems backward.  Why should api-server have `aws-cloud-provider` service account built-in? Are we going to approve pull requests that create more cloudprovider specific service accounts? Like - `openstack-service-account` or `vmware-service-account` ?

You said:

> Based on what you linked, the AWS provider now has create/read access to all configmaps in kube-system and vice versa the GCE provider gained all the abilities this PR adds

I see this as  - *ALL* cloudproviders already had ability to create/list configmaps. It just happens that only GCE made use of that ability.  After this PR *ALL* cloudproviders get ability to get/update node objects.  

Tracing back original requirements that led to this PR, it seems sensible that a cloudprovider should be able to taint the nodes it providers. Afterall cloudprovider knows more about internal state of node that it owns.  But cloudprovider can also bubble up that information back to calling controller and then controller can be responsible for tainting the node rather than cloudprovider itself. In this particular case though - the reason we are tainting the node is VERY AWS specific and I am not sure there is any value in bubbling up the information to calling controller (in this case attach-detach-controller). But we can certainly revisit that, if there is a strong reason to not grant cloudprovider ability to get and update node objects.

2017-12-02 15:10 UTC, jhorwit2 commented
> Are we going to approve pull requests that create more cloudprovider specific service accounts? Like - openstack-service-account or vmware-service-account ?

The SA's will only be created if the cluster is using that provider. It's similar to how the apiserver creates a bunch of specific controller roles/bindings but the SA's to use those don't exist until you run the KCM or CCM with the service credentials flag. 

To answer your question, yes I think we would. It's not fair that GCE can do specific logic but other providers can't if they have a valid use case. This is why we're trying to move all providers to out-of-tree via the cloud controller manager.

>  ALL cloudproviders already had ability to create/list configmaps. It just happens that only GCE made use of that ability. After this PR ALL cloudproviders get ability to get/update node objects.

All cloud providers could have whatever abilities they require for their implementation whether that's updating nodes, services, getting secrets for load balancer certs, etc. That doesn't mean every cloud provider should have those abilities / should use the same generic SA. Clients shouldn't have more access than they require. 

> Tracing back original requirements that led to this PR, it seems sensible that a cloudprovider should be able to taint the nodes it providers.

To be clear, I'm not saying you shouldn't do this. I think this is a valid use case.

2017-12-02 15:19 UTC, gnufied commented
> To answer your question, yes I think we would. It's not fair that GCE can do specific logic but other providers can't if they have a valid use case. This is why we're trying to move all providers to out-of-tree via the cloud controller manager.

Okay thank you. If we agree to this, I can change this PR and referred service account in aws cloudprovider to `aws-cloud-provider` .  @liggitt does that work?

2017-12-02 15:23 UTC, liggitt commented
Keeping the roles and service accounts split by provider makes sense to me. The roles and bindings would currently always be created, which isn't ideal, but at the point the provider moved out of tree, I'd expect the bootstrapped role to be removed as well and be made part of the manifest file for provider. The service accounts are currently only created if used, which is what we want.

2017-12-04 15:58 UTC, gnufied commented
@liggitt @jhorwit2 fixed the PR to have `aws-cloud-provider` serviceaccount for applying taints.  PTAL

2017-12-04 15:59 UTC, gnufied commented
@justinsb this may need another round of approval from you, because we changed the serviceaccount that applies the taint.

2017-12-04 18:33 UTC, dims commented
/assign @justinsb

2017-12-04 20:09 UTC, liggitt commented
auth change LGTM

2017-12-04 20:09 UTC, liggitt commented
/approve

2017-12-04 22:15 UTC, ericchiang commented
/assign @justinsb

2017-12-04 22:21 UTC, justinsb commented
/lgtm

2017-12-04 22:22 UTC, justinsb commented
/approve no-issue

2017-12-05 01:14 UTC, merged

2018-07-17 22:42 UTC, tallclair commented
I just came across this. Provider-specific roles should not be part of the hardcoded universal bootstrap policy. The ClusterRole(Binding) should be created as part of the provider-specific cluster setup.