outdend err block
kubernetes/kubernetes pull request #56742
Opened 2017-12-02 08:39 UTC by zouyee

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2017-12-02 15:21 UTC, jhorwit2 requested changes
Thanks for the PR @zouyee! I think you have a syntax error but overall LGTM after that!

2017-12-02 15:21 UTC, jhorwit2 commented on pkg/volume/util.go
> +	} else
I think you forgot an `else` here.

2017-12-02 15:21 UTC, jhorwit2 commented
/area cleanup

2017-12-03 12:33 UTC, zouyee commented
ping @jhorwit2

2017-12-03 14:20 UTC, jhorwit2 commented
/ok-to-test

2017-12-03 22:41 UTC, davidz627 commented on pkg/volume/util.go
> +// GetPath Check if the path from the mounter is empty.
nit: GetPath {checks}

2017-12-03 22:43 UTC, davidz627 commented
please run hack/update-gofmt.sh on your changed files. I think it is failing the gofmt verify script.

2017-12-04 06:34 UTC, zouyee commented
ping @davidz627

2017-12-04 16:23 UTC, gnufied commented
/lgtm

2017-12-04 18:30 UTC, davidz627 commented on pkg/volume/util.go
> +// GetPath Checks if the path from the mounter is empty.
nit: lowercase *checks*

2017-12-04 18:30 UTC, davidz627 commented on pkg/volume/util.go
> +
nit: remove space

2017-12-04 18:30 UTC, davidz627 commented on pkg/volume/util.go
> +
nit: remove space.

2017-12-05 00:49 UTC, zouyee commented on pkg/volume/util.go
> +
It has been fixed, thanks again.

2017-12-05 01:38 UTC, davidz627 commented
/lgtm

2017-12-07 01:54 UTC, zouyee commented
ping @gnufied

2017-12-20 22:50 UTC, zouyee commented
/test pull-kubernetes-verify

2017-12-20 23:10 UTC, gnufied commented
/approve no-issue

2017-12-21 00:47 UTC, merged