Fix panic in deployment controller start
kubernetes/kubernetes pull request #57216
Opened 2017-12-14 22:46 UTC by derekwaynecarr

**What this PR does / why we need it**:
deployment controller can panic on startup

**Special notes for your reviewer**:
similar to https://github.com/kubernetes/kubernetes/pull/56941 but for deployments.

```release-note
fix potential panic on deployment controller start
```

2017-12-14 22:47 UTC, derekwaynecarr commented
fyi @ironcladlou @ncdc @gnufied 

have not had enough time to test this, but seeing similar symptoms as referenced pr but for deployments.

2017-12-14 22:59 UTC, ironcladlou requested changes

2017-12-14 22:59 UTC, ironcladlou commented on pkg/controller/deployment/deployment_controller.go
>  	dc.podListerSynced = podInformer.Informer().HasSynced
Looks like this is one of the bits of work that got lost when https://github.com/kubernetes/kubernetes/pull/51492 was closed. As a defensive maneuver, inline everything possible into the DeploymentController instance creation.

2017-12-14 23:00 UTC, ironcladlou commented
Another instance of https://github.com/kubernetes/kubernetes/issues/51013

2017-12-14 23:01 UTC, ironcladlou commented on pkg/controller/deployment/deployment_controller.go
>  	dc.podListerSynced = podInformer.Informer().HasSynced
And anything that's not inlined, move to lines preceding calls to `AddEventHandler`.

2017-12-15 22:20 UTC, derekwaynecarr commented
@ironcladlou -- think i captured your feedback, PTAL.

2017-12-18 15:08 UTC, derekwaynecarr commented
closing per discussion with @deads2k to fix this another way.

2017-12-18 15:08 UTC, closed without merging