[WIP] #57109 Verification of connection to apiserver in kube-proxy
kubernetes/kubernetes pull request #57288
Opened 2017-12-17 20:23 UTC by antoniaklja

**What this PR does / why we need it**:
Extended kube-proxy healthcheck to verify connection with apiserver.

regarding what @discordianfish said:
> When for whatever reason kube-proxy can't reach the apiserver, it retries but the pod stays in ready state.

> kube-proxy should fail or have a health check that would indicate such issues.

**Which issue(s) this PR fixes** 
Fixes #57109

2017-12-17 20:24 UTC, antoniaklja commented
Also I would like to add some unit and e2e tests in next few days.

2017-12-18 16:05 UTC, antoniaklja commented
hey @discordianfish I've added unit test with fakeClient but not sure how we can test failure flow

2017-12-19 13:36 UTC, antoniaklja commented
@lavalamp @dchen1107 @discordianfish  ready to review

2017-12-20 04:15 UTC, jhorwit2 commented
How is this going to impact services that rely on the kube-proxy healthcheck like cloud load balancers? I would not expect or want to have kube-proxy start failing healthchecks which causes a complete outage on all our load balancer services that don't use `externalTrafficPolicy: Local`.

2017-12-20 04:19 UTC, jhorwit2 commented
/sig network

2017-12-20 04:22 UTC, jhorwit2 requested changes

2017-12-20 04:22 UTC, jhorwit2 commented on pkg/proxy/healthcheck/healthcheck_test.go
> +func newFakeClient() clientset.Interface {
This check will cause outages for cloud provider load balancer services that already have or are being told to move to the kube-proxy healthz port for default healthchecks as discussed [here](https://github.com/kubernetes/kubernetes/issues/14661#issuecomment-348332432) during apiserver outages.

2017-12-20 04:23 UTC, jhorwit2 commented
cc @MrHohn

2017-12-20 09:27 UTC, antoniaklja commented
thanks @jhorwit2, I haven't known that. Looks like side effect of it is quite dangerous and we should figure out something different or close this PR.

2017-12-20 12:52 UTC, jhorwit2 commented
Agreed @antoniaklja. I think if this is something we need for kube-proxy then we may want to separate the health checks. Perhaps keep 10256 for cloud health and have a new port for kube proxy health flso we keep backwards compatibility.

2017-12-20 13:41 UTC, antoniaklja commented
yeah, separated health check just for cloud load balancers sounds fine because cluster in general it'll be more fault tolerant but on the other hand you know if something is going on with connection between kube-roxy and apiserver.

2017-12-21 11:07 UTC, discordianfish commented
@jhorwit2 I'm probably missing something here but why would a cloud load balancer be configured to check the kube-proxy health endpoint? I though kube-proxy is used only within the cluster and the cloud load balancer would access ports mapped by kube-proxy and used health endpoints exposed by kube-proxy but not kube-proxy's health endpoint itself?

Either way, my main concern is that kube-proxy starts up and resports as health even if it *never* reached the apiserver. At least in this case it should be save for the health endpoint to return failure, since kube-proxy can't do anything without getting some state first from apiserver.

2017-12-22 12:29 UTC, jhorwit2 commented
@discordianfish The original discussion around all that is here https://github.com/kubernetes/kubernetes/issues/14661. 

I understand where you are coming from but still have concerns especially when kube-proxy is running as a daemonset. This means that during an apiserver outage it will start failing kubelet checks for liveness and readiness.

2017-12-27 10:11 UTC, discordianfish commented
@jhorwit2 Oh I share your concern. Just as of today there doesn't seem to be anything depending on the health check. I agree that this would be a problem if #14661 uses kube-proxy's health endpoint.
So I don't care much about the implementation details, just that it's not reporting "health" if it never reached the apiserver.

2017-12-28 09:39 UTC, antoniaklja commented
what is the outcome of this discussion? It looks like guys from #14661 are implementing separate health checks for every cloud provider.

2018-04-27 11:17 UTC, discordianfish commented
/remove-lifecycle stale
/lifecycle freeze

2018-05-07 13:10 UTC, dims commented
@antoniaklja @discordianfish can we please close this? PR was last rebased a while ago.

2018-06-06 13:40 UTC, closed without merging