correct annotations of pkg/kubelet/rkt/config.go
kubernetes/kubernetes pull request #57363
Opened 2017-12-19 01:13 UTC by tianshapjq

**What this PR does / why we need it**:
the merge rule in the pkg/kubelet/rkt/config.go seems not match the code's behavior.

**Release note**:

```release-note

```NONE

2017-12-19 02:11 UTC, dixudx requested changes

2017-12-19 02:11 UTC, dixudx commented on pkg/kubelet/rkt/config.go
> +// that the fields in the provided config will be overridden by the
I don't think this should be changed.

2017-12-19 12:03 UTC, dims commented on pkg/kubelet/rkt/config.go
> +// that the fields in the provided config will be overridden by the
agree @dixudx

2017-12-27 15:17 UTC, dims commented
/close

2017-12-27 15:17 UTC, closed without merging