Fix kubectl misleading error
kubernetes/kubernetes pull request #58043
Opened 2018-01-10 05:01 UTC by niuzhenguo

**What this PR does / why we need it**:
This fixes the misleading kubectl error the server doesn't have a resource type "po" while API server is unreachable. Adds a check for "connection refused" err before fallback to hardcoded types.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57198 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-01-11 01:18 UTC, ericchiang commented on pkg/kubectl/cmd/util/factory_object_mapping.go
> +		if strings.Contains(err.Error(), "connection refused") {
Error strings change. Does:

```
if _, ok := err.(net.Error); ok {
}
```

do the same thing? Can we add a unit test?

2018-01-24 17:39 UTC, soltysh requested changes
I still don't see the test case Eric asked for this.

2018-01-25 08:19 UTC, niuzhenguo commented
@soltysh @ericchiang Sorry for the delay, but I don't find a proper way for testing this, could you please help here?

2018-01-27 02:14 UTC, niuzhenguo commented
/assign @liggitt

2018-01-27 19:19 UTC, liggitt commented on pkg/kubectl/cmd/util/factory_object_mapping.go
> +		if _, ok := err.(net.Error); ok {
checking for a particular error type here is extremely fragile with go's type system... wrapping errors would make this fail. Need a better way to check this, and a test exercising it if we want it to stick. I also think we'd still want to continue if we got any results (if `len(groupResources) > 0`)

2018-01-27 19:19 UTC, liggitt commented
/unassign
/assign @deads2k

2018-06-28 05:54 UTC, idealhack commented
@niuzhenguo Is this PR still needed?

2018-07-05 11:30 UTC, soltysh commented
The file is gone, so I'll close it. Feel free to re-open when you get to that.

2018-07-05 11:30 UTC, closed without merging