fix runtime-config issue  due to Initializers is enabled by kubeadm
kubernetes/kubernetes pull request #58254
Opened 2018-01-14 07:16 UTC by dixudx

**What this PR does / why we need it**:
`kubeadm` adds Initializers to `--admission-control` by default since v1.8, but doesn't enable its corresponding API `admissionregistration.k8s.io/v1alpha1` in `--runtime-config`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#629

**Special notes for your reviewer**:
/assign @luxas
/area kubeadm
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews 

**Release note**:

```release-note
add "admissionregistration.k8s.io/v1alpha1" to the --runtime-config flag due to Initializers is enabled by kubeadm
```

2018-01-14 10:24 UTC, zouyee commented
could not we config this value using apiServerExtraArgs?

2018-01-14 13:51 UTC, dixudx commented
> could not we config this value using apiServerExtraArgs?

This value should be set by default, since `Initializers` has already been added into `admission-control` by default. Of course we can use `apiServerExtraArgs` to set this. But `"admissionregistration.k8s.io/v1alpha1"` and `Initializers` are coupled now (v1alpha1 is not registered by default), it is not right to split them separately and let users manually input this value.

2018-01-14 17:22 UTC, jamiehannaford requested changes
just one nit. overall looks good, thanks for submitting

2018-01-14 17:22 UTC, jamiehannaford commented on cmd/kubeadm/app/phases/controlplane/manifests.go
> +		// add "admissionregistration.k8s.io/v1alpha1" to the --runtime-config flag due to Initializers is enabled
nit: replace `due to Initializers is enabled` with `because Initializers are enabled`

2018-01-14 18:33 UTC, fabriziopandini approved these changes
Thanks for fixing this!
/lgtm

2018-01-15 01:30 UTC, dixudx commented
@fabriziopandini  @jamiehannaford Update the nit. PTAL. Thanks.

2018-01-15 02:00 UTC, dixudx commented
/test pull-kubernetes-unit

2018-01-15 03:06 UTC, xiangpengzhao commented
@dixudx the admissionregistration API is beta and enabled by default in 1.9 (https://github.com/kubernetes/kubernetes/pull/56687), so we don't need to pass any admissionregistration API version to `--runtime-config`.

2018-01-15 03:21 UTC, dixudx commented
> the admissionregistration API is beta and enabled by default in 1.9 (#56687), so we don't need to pass any admissionregistration API version to --runtime-config.

@xiangpengzhao Thanks for raising this question. Currently we only graduate `admissionregistration` to `v1beta1`, but the [informer](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/initialization/initialization.go#L100) still uses `v1alpha1`. This fix is only for `release-1.9`.

You're right. For `master` branch, we may use `v1beta1` instead, which is registered by default. Will submit another PR to master.

2018-01-15 04:44 UTC, jamiehannaford approved these changes
/lgtm

2018-01-15 05:43 UTC, dixudx commented
/retest

2018-01-15 05:44 UTC, dixudx commented
/retest

2018-01-15 05:46 UTC, dixudx commented
/test pull-kubernetes-e2e-gke-gci
/test pull-kubernetes-unit

2018-01-15 06:07 UTC, dixudx commented
Can anybody remove the label `do-not-merge/cherry-pick-not-approved`. This PR is targeted for master branch. Thanks.

2018-01-15 06:16 UTC, dixudx commented
/test pull-kubernetes-e2e-gke-gci

2018-01-15 06:45 UTC, dixudx commented
/test pull-kubernetes-e2e-gke-gci

2018-01-15 07:03 UTC, fabriziopandini commented
/lgtm

2018-01-15 07:05 UTC, dixudx commented
ping @luxas for approval. Thanks.

2018-01-16 00:59 UTC, xiangpengzhao commented
/retest

2018-01-16 09:39 UTC, zouyee commented
/test pull-kubernetes-e2e-gke-gci

2018-01-17 01:54 UTC, dixudx commented
Seems `pull-kubernetes-e2e-gke-gci` is not happy with this PR.

Rebased. PTAL.

2018-01-17 02:14 UTC, dixudx commented
/test pull-kubernetes-e2e-kops-aws

2018-01-17 07:03 UTC, fabriziopandini commented
/lgtm

2018-01-17 23:38 UTC, timothysc commented
Umm do we want to support "Initializers?" or is is mutating web-hooks or bust? 

/cc @mattmoyer @ncdc

2018-01-17 23:49 UTC, jamiehannaford commented
This should probably tie in to a wider policy of how kubeadm promotes unstable/alpha features. I think initializers are a useful enough feature to have, plus users still have the choice of electing to use them.

2018-01-17 23:56 UTC, timothysc commented
@jamiehannaford ... Sure, but I think they are planned to be deprecated, but I want @kubernetes/sig-api-machinery-misc to chime in on the "official" stance on this feature.

2018-01-18 00:14 UTC, liggitt commented on cmd/kubeadm/app/phases/controlplane/manifests.go
> +		"runtime-config": "admissionregistration.k8s.io/v1alpha1",
Definitely don't enable alpha versions by default.

2018-01-18 00:16 UTC, liggitt commented
The alpha api version should not be enabled by default. 

It would be more appropriate to remove the initializers admission plugin from the default chain

/close

2018-01-18 00:16 UTC, closed without merging

2018-01-18 01:26 UTC, jamiehannaford commented
@dixudx Would you mind removing Initializers from the admission chain?

2018-01-18 03:34 UTC, dixudx commented
@jamiehannaford Remove `Initializers` in PR #58428. PTAL. Thanks.