Add criSocket to kubeadm MasterConfiguration manifest
kubernetes/kubernetes pull request #59057
Opened 2018-01-30 18:18 UTC by JordanFaust

**What this PR does / why we need it**:
Adds a criSocket field to the MasterConfiguration manifest used by kubeadm. This field configures the cri socket that kubeadm uses during preflight checks.  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # kubernetes/kubeadm#679

**Special notes for your reviewer**:

kubeadm does not allow the use of --config and the --cri-socket flag together. When using kubeadm to create a cluster that will not be using docker, the preflight checks fail since this is not configurable. This PR adds the criSocket to the MasterConfiguration manifest and uses that value within the MasterConfiguration if it was provided. 

Storing the value of the criSocket within the MasterConfiguration manifest will also make joining additional masters with the proposed 'kubeadm join --master' command by not requiring operators to remember to include an additional flag. This may not be the case if we instead relaxed the constraint of using additional flags when using the --config flag is set.

**Release note**:
/area kubeadm
/assign @luxas
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

```release-note
kubeadm: add criSocket field to MasterConfiguration manifiest
```

2018-01-31 08:10 UTC, fabriziopandini commented
@JordanFaust thanks for this PR!

I'm basically fine with what you are proposing.
However, after adding criSocket to the MasterConfiguration file, IMO we can get rid of the corresponding local variable in init.go and cleanup a bit the code. WDYT?

2018-01-31 09:32 UTC, jamiehannaford requested changes
thanks! I agree with @fabriziopandini, we can still refactor this a bit (e.g. by moving the flag to `AddInitConfigFlags`)

2018-01-31 09:32 UTC, jamiehannaford commented on cmd/kubeadm/app/apis/kubeadm/types.go
> +	CRISocket string
needs a comment

2018-01-31 09:32 UTC, jamiehannaford commented on cmd/kubeadm/app/apis/kubeadm/v1alpha1/defaults.go
> +	// DefaultCRISocket defines default cri socket
defines the

2018-01-31 20:06 UTC, JordanFaust commented
Thanks for the feedback @jamiehannaford and @fabriziopandini. If things look good I can rebase my commits.

2018-01-31 20:20 UTC, kargakis commented
/ok-to-test

2018-01-31 22:17 UTC, JordanFaust commented
/retest

2018-02-02 07:30 UTC, fabriziopandini approved these changes
/lgtm

@JordanFaust  it would be great if you send a twin PR for adding crisocket to NodeConfiguration as well (and then clean up kubeadm join from the local var) 😉

2018-02-02 14:49 UTC, JordanFaust commented
@fabriziopandini I can definitely do that. I might not get to it until early next week but if everything looks good here I can open a separate PR to make the changes for the NodeConfiguration

2018-02-05 05:52 UTC, fabriziopandini commented
/lgtm

2018-02-07 02:53 UTC, timothysc commented on cmd/kubeadm/app/cmd/init.go
> +	flagSet.StringVar(
@luxas I'd like us to make a policy on what is in<>out for cmdline flag additions.

2018-02-07 14:40 UTC, timothysc approved these changes
/approve - per slack discussion 

fabrizio.pandini 
@timothysc PR#59057 doesn't add a new flag to kubeadm init, but changes an already existing flag because it  adds the corresponding field to the master configuration file (now missing).
In other words this PR fixes an error (today you can't use CRI with the master configuration file) and creates the conditions for removing the crisocket flag in case we will decide that CRI is an exception

2018-02-07 16:52 UTC, timothysc reviewed
Please squash your commits.

2018-02-13 15:18 UTC, JordanFaust commented
Update the documentation on CRISocket as requested in https://github.com/kubernetes/kubernetes/pull/59292

2018-02-13 16:04 UTC, JordanFaust commented
/retest

2018-02-21 09:46 UTC, jamiehannaford commented
/lgtm

2018-02-21 12:22 UTC, merged