Implement --user option for 'kubectl exec'
kubernetes/kubernetes pull request #59092
Opened 2018-01-31 06:25 UTC by louyihua

**What this PR does / why we need it**:
This patch implements the `--user` option in `kubectl exec` command. With this patch, user can specify the user name/id in a `kubectl exec` command like `kubectl exec -it --user root pod-name command`.

**Release note**:

```release-note
Implement --user option for 'kubectl exec'
```

2018-01-31 18:47 UTC, ncdc reviewed
Please see the comments on #30656. That needs to be resolved first as to whether this is even something we can support, from a CRI perspective.

2018-01-31 18:47 UTC, ncdc commented on pkg/kubectl/cmd/exec.go
> -	// TODO support UID
This comment is about pod uid, not user uid

2018-01-31 18:47 UTC, ncdc commented
/hold

2018-01-31 18:47 UTC, ncdc commented
FYI @liggitt @yujuhong @derekwaynecarr @dchen1107 @Random-Liu @kubernetes/sig-node-pr-reviews

2018-05-04 12:56 UTC, louyihua commented
/remove-lifecycle stale

2018-08-31 17:00 UTC, Nowaker commented
@louyihua Would you mind finishing this up?

2018-08-31 18:56 UTC, louyihua commented
/remove-lifecycle stale

2018-11-08 05:47 UTC, resouer commented
/ok-to-test

2018-11-08 05:50 UTC, resouer requested changes
This PR changes the whole path from api, kubelet to cri, but lacks proper e2e test.

2018-12-19 16:09 UTC, davidxia commented
@louyihua were you planning on following up on this? If not, I can help take over if you'd like. If no response, I'll get started. :)

2019-01-24 21:18 UTC, tsunamireversal commented
Can we have a status on that ? Feature would be super useful

2019-03-15 16:17 UTC, liggitt commented
this change needs to have a associated [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md) in implementable state before being completed/reviewed

2019-07-30 20:03 UTC, davidxia commented
/remove-lifecycle stale

2019-11-27 22:58 UTC, Nowaker commented
It's a TOP3 most upvoted feature request... Can someone finish it up?

2019-11-27 23:05 UTC, smarterclayton commented
As mentioned above this really needs a KEP and discussion about the security implications.  It’s not that it’s necessarily a bad idea, it just has a significant impact to the system and needs a design before we can start coding.

I’d be happy to help review and shepherd a KEP for this, but this PR isnt really actionable yet.

For now,

/close

And we can follow up with a KEP

2019-11-27 23:05 UTC, closed without merging

2020-01-10 18:19 UTC, tsunamireversal commented
I don't understand your comment @smarterclayton 
Adding the --user feature would be much better for security, not worse. 
Unless we're missing something...?

Also, what's a KEP ?

2020-04-27 23:47 UTC, SimonHeimberg commented
There was a KEP: https://github.com/kubernetes/enhancements/pull/1224