Prevent IPv6 addresses to be v1.NodeInternalIP
kubernetes/kubernetes pull request #59502
Opened 2018-02-07 19:50 UTC by zioproto

**What this PR does / why we need it**:

This PR makes sure IPv6 address are set as v1.NodeExternalIP
We need it because setting IPv6 addresses as v1.NodeInternalIP breaks the current Kubernetes Neutron networking as described in issue #59421

**Which issue(s) this PR fixes**:
Fixes #59421
Fixes #55202
**Special notes for your reviewer**:

please note that already here https://github.com/zioproto/kubernetes/commit/60ab7cad665241684fc07bbb14ddd9f633d399cb#diff-694c675fe77b09923cc453e7228f8fa8R494 there is the assumption IPv6 = External IP

**Release note**:

```release-note
NONE
```

2018-02-07 21:16 UTC, zioproto commented
/assign @leblancd 
/assign @anguslees

2018-02-07 21:28 UTC, dims commented
/ok-to-test

reasonable approach i think until we are ready. can you please add a TODO/FIXME stating that we need to revisit this when we enable ipv6 support for openstack provider?

2018-02-07 21:38 UTC, leblancd commented
lgtm, although someone more recently familiar with OpenStack IPv6 addressing might be able to confirm that the assumption is valid that all IPv6 addresses processed here are externally accessible (i.e are in the GUA address range and are globally routed). Otherwise, looks like a good fix.

2018-02-07 22:31 UTC, zioproto commented
/test pull-kubernetes-e2e-kops-aws

2018-02-08 10:41 UTC, anguslees requested changes
This effectively implements a v4-addresses-only filter (since internalips are selected in preference to externalips), hurting v6 adoption, and fixing #59421 only for the ipv4 pod subnet case.

Better for #59421 would be to expose the IPVersion and allow us to fetch addresses for a specific family, or for all families.

The existing function should return any family (as before), but for some special cases like picking the router next hop, it only makes sense to use a node address from the same address family as the pod subnet.

2018-02-08 11:03 UTC, dims commented
/hold

2018-02-08 13:26 UTC, zioproto commented
/test cla/linuxfoundation

2018-02-09 13:56 UTC, zioproto commented
Hello all,
I tested the patch it works as expected:

```
Addresses:
  InternalIP:  10.8.10.7
  ExternalIP:  2001:620:5ca1:4005:f816:3eff:fe7d:f44d
  Hostname:    k8s-master
```
In the short term I am happy with this patch, because I can publish services in IPv6 using the `nginx-ingress-controller` because the VM running that container has an IPv6 address.

Of course in case of an IPv6 pod network this solution will not work.

There is a foundamental thing to decide before proposing any new patch. An IPv6 address assigned to a Openstack VM, should be threated as `InternalIP` or `ExternalIP` ?

thank you

2018-02-09 16:32 UTC, leblancd commented
@zioproto - That's a very good question! Again, I haven't worked with OpenStack IPv6 in a while, but this would be my take. As a straw man proposal, I would propose that the best we can do is to classify IPv6 VM addresses as internal/external based upon address range: LLA's get ignored (I assume these are already filtered out?), ULAs are internal, and GUA range addresses are external. So the overall logic would be:
```
if (addr is floatingIP) or (network is public) or (addr is IPv6 && is GUA range) {
    mark as external
} else {
    mark as internal
}
```
My reasoning is as follows. For IPv4, it's clear that only floating IPs or IPs on a public network would be externally accessible. For IPv6, it's a bit more fuzzy. Floating IPs are not typically (never?) used for IPv6 VMs (it used to be that IPv6 floating IPs weren't supported. Usually you want to avoid NAT66 translation). IPv6 addresses on a VM could be assigned in a variety of ways, if I remember correctly:
- Prefix delegation (using SLAAC)
- DHCP (stateless and stateful)
- Provider net
- Subnet pool (e.g. with external IPAM)
Whichever way that a VM's IP address might get assigned, the question of whether it's externally accessible would come down to whether:
- Address is in the Global unicast range, AND...
- The corresponding subnet is routed from the outside world (either by prefix delegation or by the provider network)
I would think that an operator would make sure that these bullets would be consistent, i.e. if there's an external route, then use GUA, If not, use ULA.

Typically, I think VM IPv6 addresses are going to be global (to avoid NAT66), so all addresses would get classified as externalIPs (except for the corner case where a VM subnet needs to be truly private). 

@anguslees - Do you happen to know what would happen if the OpenStack cloud provider plugin only returns external IPs (internal IP list is empty)?

2018-02-11 14:39 UTC, zioproto commented
Hello @anguslees ,
I am implementing a `getCIDRIpVersion` function to figure out if I need an IPv4 or IPv6 nexthop for the route, and filter the proposed addresses as needed.

once I get the addresses from Openstack and I figure out if they are IPv4 and IPv6 it would be great to pass on the IPVersion information here:
https://github.com/zioproto/kubernetes/blob/issues/59421/pkg/cloudprovider/providers/openstack/openstack.go#L475

However, who write the data type for the addresses did no think about an IPVersion field:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L3553-L3566

Should I add it here in `types.go` ? It is my first patch into Kubernetes and I am not sure what structs is okay to patch.

thanks

2018-02-12 01:38 UTC, anguslees commented
> However, who write the data type for the addresses did no think about an IPVersion field

On the golang side, you can guess by checking if `net.IP.{To4.To16}` returns non-nil (will do conversion to/from v4-mapped addresses, so the results aren't mutually exclusive).  Alternatively, just checking for a `:` should be sufficient (since we know these are address literal strings).

2018-02-12 01:44 UTC, anguslees commented
> @anguslees - Do you happen to know what would happen if the OpenStack cloud provider plugin only returns external IPs (internal IP list is empty)?

I believe it will all work fine.  The whole InternalIP vs ExternalIP thing was never specified at all and nobody has been able to tell me what actual semantics are expected.  The various bits of code I've seen (and written myself) just prefers InternalIPs over ExternalIPs, on the naive assumption that everyone has a split network infrastructure and billing model like AWS (ie: traffic to "internal" addresses is free).

2018-02-12 09:00 UTC, zioproto commented
According to what we discussed in this pull request a proposed a different new pull request do address the problem. https://github.com/kubernetes/kubernetes/pull/59749
thank you

2018-02-13 18:59 UTC, dims commented
/close 

in favor of #59749

2018-02-13 18:59 UTC, closed without merging