Fix broken systemd detection in containerized kubelet
kubernetes/kubernetes pull request #59770
Opened 2018-02-12 21:34 UTC by joelsmith

**What this PR does / why we need it**:
It appears that detection of whether the host has systemd is broken in the containerized kubelet code. The code returns true if the `systemd-run` entry is present in the `paths` map, but the entry is always present in the paths map, so it always returns true even if the host doesn't have the `systemd-run` binary.

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE

```

2018-02-12 21:36 UTC, joelsmith commented
@xudifsd PTAL

2018-02-13 06:58 UTC, dixudx approved these changes

2018-02-13 07:15 UTC, dixudx requested changes
I think the right way to do this is to see whether `/systemd-run` exists for the last check.

2018-02-13 07:15 UTC, dixudx commented on pkg/util/nsenter/nsenter.go
> +	return systemdRunPath, systemdRunPath != ""
Just recheck this.

The default `systemd-run` binary file will be `/systemd-run`, if not found in any of `/bin`, `/usr/sbin`, and `/usr/bin`.

So `ne.paths["systemd-run"]` will not be empty string.

2018-02-13 07:15 UTC, dixudx commented
/lgtm cancel

2018-02-13 07:51 UTC, dixudx commented
@joelsmith PTAL #59786

2018-02-23 22:41 UTC, lavalamp commented
/assign @yujuhong

2018-02-23 22:44 UTC, joelsmith commented
Closing in favor of #59786

2018-02-23 22:44 UTC, closed without merging