the grammar is 'be used for'
kubernetes/kubernetes pull request #59781
Opened 2018-02-13 01:17 UTC by liangwenguo

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2018-02-13 01:31 UTC, dixudx requested changes

2018-02-13 01:31 UTC, dixudx commented on cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
> -	// Image specifies which container image to use for running etcd.
I think the old one is okay.

2018-02-13 01:31 UTC, dixudx commented
/area kubeadm

2018-02-13 07:19 UTC, hzxuzhonghu commented on cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
> -	// Image specifies which container image to use for running etcd.
agree

2018-02-23 22:13 UTC, timothysc commented on cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
> -	// Image specifies which container image to use for running etcd.
agree closing this issue.

2018-02-23 22:13 UTC, closed without merging