kubeadm: Demote controlplane passthrough flags to phases alpha
kubernetes/kubernetes pull request #59882
Opened 2018-02-14 18:34 UTC by kris-nova

After a discussion in sig cluster lifecycle we agreed that the passthrough flags should live in phases alpha, and not be 1st class flags.

**What this PR does / why we need it**:

We introduced some flags as 1st class flags in #58080 and decided as a sig that the flags should only live in the `alpha` command. This PR removes the flags from the `init` command so they only exist in the `alpha` command

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

relates to #kubernetes/kubernetes/pull/58080
fixes #kubernetes/kubeadm/issues/676

**Special notes for your reviewer**:

This is a cosmetic change, and doesn't alter any functionality of the program, only the avenue in which a user access functionality in the program.

**Release note**:

```release-note
kubeadm: Demote controlplane passthrough flags to alpha flags
```

2018-02-15 06:39 UTC, kris-nova commented
/assign @timothysc

2018-02-21 23:39 UTC, timothysc commented
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

2018-02-21 23:42 UTC, timothysc requested changes
Wasn't there a flag also added to one of the phases that should also be removed?

2018-02-23 22:00 UTC, timothysc approved these changes
/lgtm 
/approve 

I'm going to greenlight this and we can fix as a bug any other removals.

2018-02-25 01:51 UTC, merged

2018-02-28 07:34 UTC, kris-nova commented
@timothysc should we open an issue about whatever flag needs to be removed?