Give UDP connections a chance to close gracefully
kubernetes/kubernetes pull request #60074
Opened 2018-02-20 14:08 UTC by jsravn

Delay UDP connection tracking flush on endpoint removal.

This gives termination grace period a chance to work, such as when
kube-dns is restarted or redeployed.

Otherwise in-flight requests will always time out whenever an endpoint
removal occurs.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2018-02-22 08:34 UTC, krmayankk commented
@jsravn  could we delay the udp connection flush by some other param like terminationGracePeriodSeconds rather than hard coding it ? May be some users want that, immediate flush ?

2018-02-22 09:29 UTC, jsravn commented
@krmayankk I added it as a flag to kube-proxy so it's configurable - setting to 0 disables, same as prior behavior. It is also similar to TCP connections in netfilter, they have a single timeout.

I did think about using terminationGracePeriodSeconds as described in the linked issue. The problem is kube-proxy only knows about endpoints - and terminationGracePeriodSeconds is a pod field. It's doable but would require an API change probably - adding a new field to endpoint that is filled in by the endpoints controller. I think this is a good idea actually, just a bit more work and API change (which I'm not that familiar with doing).

2018-02-22 09:31 UTC, jsravn commented
Using terminationGracePeriod also makes sense for the IPVS proxier (https://github.com/kubernetes/kubernetes/issues/57841).

2018-02-26 02:22 UTC, jhorwit2 requested changes

2018-02-28 10:41 UTC, jsravn commented on pkg/proxy/iptables/proxier.go
> +							if ep.String() == epSvcPair.Endpoint {
Fixed.

2018-03-01 08:44 UTC, bburket commented
@jsravn how did your testing go? We are facing some cantankerous issues with DNS timeouts in our cluster

2018-03-01 16:56 UTC, jsravn commented
@bburket Not great I'm afraid. I still am getting dns errors on restarts, with this change cherry picked to 1.8. Either my cherry pick is broken or there is something else going on I don't quite understand yet.

2018-03-02 06:45 UTC, BenTheElder commented
/ok-to-test

2018-04-17 09:02 UTC, tcolgate commented
We are seeing similar issues with kube-dns on cluster-autoscaler downscales. NodeJS seems to have particular pathological behaviour on DNS timeouts, so this is causing us some considerable pain.

2018-04-17 09:30 UTC, jsravn commented
Sorry I got pulled off on other work, so haven't had time to work on this further.

2018-06-06 05:39 UTC, m1093782566 commented
/assign 

Probably IPVS side needs a similar change.

2018-09-04 06:26 UTC, BenTheElder commented
@m1093782566 seems like we probably still want this...?
/remove-lifecycle stale

2018-09-04 06:34 UTC, m1093782566 commented
@BenTheElder 

Thanks but I would prefer #66012 which is up-to-date and fix both TCP and UDP issues.

2018-09-04 06:41 UTC, BenTheElder commented
It looks like https://github.com/kubernetes/kubernetes/pull/66012 only contains IPVS changes though, while this one has iptables?

2018-09-04 06:44 UTC, m1093782566 commented
oops, seems you are right. This PR covers iptables while  #66012 covers IPVS - they do the different thing.

2019-03-01 09:58 UTC, jsravn commented
/remove-lifecycle stale

2019-05-31 12:37 UTC, jsravn commented
Going to close this - as a lot of behavior currently relies on the UDP connections being dropped immediately. IPVS proxier has also done the same recently.

2019-05-31 12:37 UTC, closed without merging