Remove k8s prefix again from gcr.io/google_containers in e2e framework
kubernetes/kubernetes pull request #60311
Opened 2018-02-23 16:02 UTC by rramkumar1

This should be working, not sure why not but I am seeing ImagePullBackOff errors in the e2e tests so removing it for now.

**Release note**:
```release-note
None
```

/assign @bowei

2018-02-23 19:05 UTC, cblecker requested changes

2018-02-23 21:55 UTC, rramkumar1 commented on test/e2e/framework/nodes_util.go
> +		command = "sudo sed -i -re 's/(image:)(.*)/\\1 gcr.io\\/google_containers\\/glbc:0.9.7/' /etc/kubernetes/manifests/glbc.manifest"
Ah I see, done.

2018-02-23 21:58 UTC, cblecker approved these changes

2018-02-24 00:17 UTC, MrHohn approved these changes
/lgtm

2018-03-01 07:46 UTC, BenTheElder commented on test/e2e/framework/nodes_util.go
> +		command = "sudo sed -i -re 's/(image:)(.*)/\\1 gcr.io\\/google_containers\\/glbc:0.9.7/' /etc/kubernetes/manifests/glbc.manifest"
probably should update the PR title now?

2018-03-08 19:47 UTC, cblecker commented
@rramkumar1 can you please fix the commit message?

2018-03-20 19:21 UTC, rramkumar1 commented
/close
Fixing in another PR

2018-03-20 19:21 UTC, closed without merging