Increase loging verbosity for deleting stateful set pods
kubernetes/kubernetes pull request #60579
Opened 2018-02-28 11:35 UTC by gmarek

We should always log reasons for deleting StatefulSet Pods.

```release-note
NONE
```

2018-02-28 11:47 UTC, jdumars commented
Bug fixes are still accepted into the 1.10 release at the team's discretion. This one is slightly different, but seems in the spirit of cleanup/bug fix.  If you can get it approved and LGTM'd by someone specifically in SIG-Apps, I will add it to the milestone.

2018-02-28 17:38 UTC, kow3ns requested changes
I don't think we can do this based on our [logging conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md). Originally I had some of these log statements at V(2) and @smarterclayton and @kargakis talked me down to V(4).

2018-02-28 18:03 UTC, enisoc commented
Have the conventions changed since then? Currently under `V(2)` it lists exactly what we're doing here:

> System state changing (killing pod)

2018-02-28 20:48 UTC, kow3ns commented
@enisoc We already report Pod lifecycle events via the event_recorder. Again, I did initially have these statements at V(2), but the other controllers log such events at V(4). Certainly we should not use V(0), and we are going to change the log level, we should do so in a consistent way across the controller manager process imo.

2018-02-28 20:57 UTC, kargakis commented
Agreed with Ken. There is also the API audit log that can be introspected
if required.

On Wed, Feb 28, 2018 at 9:49 PM, Kenneth Owens <notifications@github.com>
wrote:

> @enisoc <https://github.com/enisoc> We already report Pod lifecycle
> events via the event_recorder. Again, I did initially have these statements
> at V(2), but the other controllers log such events at V(4). Certainly we
> should not use V(0), and we are going to change the log level, we should do
> so in a consistent way across the controller manager process imo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/60579#issuecomment-369377531>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADuFf0DAJ3iXXy-JLIXPNAKtdfgSIcujks5tZbvMgaJpZM4SWgij>
> .
>

2018-03-01 09:31 UTC, gmarek commented
No there's nothing that specifies a reason. I can only tell that the Pod got deleted, which is good and I wouldn't want to loose that, but I can't tell why. While I don't really care why normal Pods disappear as long as replacement ones get created, I generally do care a lot about StatefulSet Pods dying and I'd like to be able to understand why.

V(2) sounds fine.

2018-03-05 08:36 UTC, thockin commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.kubernetes.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60579)
<!-- Reviewable:end -->

2018-03-06 13:10 UTC, gmarek commented
@kow3ns PTAL

2018-03-09 11:48 UTC, mfojtik commented
@tnozicka FYI

2018-03-09 17:29 UTC, kow3ns approved these changes

2018-03-09 17:46 UTC, kow3ns commented
/approve

2018-03-09 17:55 UTC, erictune commented
observations:

Kubernetes binaries are recommended to log at `-v=2` per  [https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md]

Most Statefulsets are small.

Events are logged, so logging will not increase out of proportion if this change is merged.

If events are already logged, but are missing the reason, and events have a `reason` field, then why not fix the events to have the reason and not add this change?

2018-03-12 07:56 UTC, krmayankk commented
@gmarek @kow3ns agree with @erictune , if this reason is not available in events, we should fix that . it would be super useful to the user looking at `kubectl describe` to see the reason right there.

2018-03-12 22:05 UTC, gmarek commented
I'm fine with logging events, but there are no events being emitted on those cases, except very generic 'Deleting Pods' ones afaict.

If someone will enhance events before 1.10 we can close this pr. Otherwise I'd like to merge it.

2018-03-14 14:49 UTC, erictune commented
/lgtm

If someone wants to later revert this and improve the event, that is fine.  This seems to be providing real debugging value and has the benefit of having been written already.

2018-03-14 15:17 UTC, jdumars commented
Thank you very much @erictune

2018-03-14 16:49 UTC, merged