Critical pods shouldn't be restricted to kube-system
kubernetes/kubernetes pull request #60653
Opened 2018-03-01 16:33 UTC by ravisantoshgudimetla

**What this PR does / why we need it**:
To make sure that critical pods are not restricted to kube-system namespace.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60596

**Special notes for your reviewer**:
@bsalamat @liggitt @aveshagarwal 
**Release note**:

```release-note
NONE
```

2018-03-01 16:35 UTC, ravisantoshgudimetla commented
/hold

2018-03-03 00:15 UTC, vikaschoudhary16 requested changes
Thanks for making this change Ravi. 
1. Would it make sense to add a test case which checks if pod is critical and namespace is not kube-system, it gets admitted ? Namespace related thing is not being checked in the existing test cases.
2. Would you mind explaining that why it makes sense to hold this PR until "quota support on priorityclasses' PR gets merged. I am unable to see a link.

2018-03-03 00:48 UTC, liggitt commented
Agree on adding a test. I would go ahead and merge this, rather than shipping a release anyone would depend on limiting critical priority in this way.

2018-03-03 01:25 UTC, ravisantoshgudimetla commented
> Would it make sense to add a test case which checks if pod is critical and namespace is not kube-system, it gets admitted ? Namespace related thing is not being checked in the existing test cases.

We cannot check priorityClass in these test cases as the resolution would have happened at admission controller level. So, I need write one at priority admission controller level. By the time, I started writing this PR, I looked at https://github.com/kubernetes/kubernetes/pull/60519/files#diff-e35316a06970f9000b7b154addabda8cR315 and there is an e2e which tests creation of pod in test namespace(not in kube-system), so I thought of skipping it. I don't mind adding one if it makes this PR clear.

> Would you mind explaining that why it makes sense to hold this PR until "quota support on priorityclasses' PR gets merged. I am unable to see a link.

@vikaschoudhary16 -As @liggit explained here in this comment https://github.com/kubernetes/kubernetes/issues/60596#issuecomment-369437647, that PR brings in whitelisting and it is needed for a fully functional system, so wanted to hold this one till that merges. 

@liggit - I don't have strong opinion on this one either, I will remove the hold.

2018-03-03 01:45 UTC, ravisantoshgudimetla commented
/remove hold

2018-03-03 04:58 UTC, vikaschoudhary16 commented
>  I looked at the admission tests just now, we were not restricting system-critical-priority pods to kube-system. The checks we had were there for annotation based critical pods for backwards compatibility. For example, the pod at https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/priority/admission_test.go#L313-#L327 would correctly resolve at https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/priority/admission_test.go#L424 to a systemcritical priority value.

Should we add a unit test case to check if annotation based critical pod can be created in non-kube-system namespace?

2018-03-03 05:16 UTC, ravisantoshgudimetla commented
> Should we add a unit test case to check if annotation based critical pod can be created in non-kube-system namespace?

I don't think so, because the annotations based critical pods should be created in kube-system only. When priority classes are mentioned, we will let critical pods to be anywhere or else they should be restricted to kube-system.

2018-03-03 05:24 UTC, vikaschoudhary16 reviewed
Thanks for confirming. IsCriticalPod is actually used in eviction manager and preemption system. Therefore test cases in priority admission plugin does not depend on this PRs changes.

2018-03-03 06:11 UTC, ravisantoshgudimetla commented
> IsCriticalPod is actually used in eviction manager and preemption system. 

Yes but I need to ensure that, it works that way. As of now, it won't. I know couple of ways to achieve that but I want to confirm few things which I am working on.

2018-03-06 01:20 UTC, bsalamat reviewed
/lgtm

2018-03-06 01:20 UTC, bsalamat commented on pkg/kubelet/types/pod_update_test.go
> +			t.Errorf("IsCriticalPodBased on priority should have returned %v for test %v but got %v\n", test.expected, test.description, actual)
nit: please remove `\n` from the error string.

2018-03-06 18:55 UTC, liggitt commented
/retest

2018-03-06 20:21 UTC, ravisantoshgudimetla commented
/retest

2018-03-07 17:15 UTC, ravisantoshgudimetla commented
/retest

2018-03-09 15:54 UTC, ravisantoshgudimetla commented
/hold cancel

2018-03-09 15:56 UTC, ravisantoshgudimetla commented
/assign @derekwaynecarr for approval.

@liggit @bsalamat Do we want this to get into 1.10?

2018-03-10 02:26 UTC, bsalamat commented
> Do we want this to get into 1.10?

No, I don't think it is necessary. Also, it will change the behavior. So, I would leave it for 1.11.

2018-03-10 02:29 UTC, liggitt commented
As long as it is done before priority exits alpha, it can wait

2018-03-22 21:33 UTC, ravisantoshgudimetla commented
/retest

2018-03-23 00:36 UTC, ravisantoshgudimetla commented
/retest

2018-03-24 01:15 UTC, bsalamat commented
/lgtm

2018-03-27 18:27 UTC, derekwaynecarr commented
why lift this restriction now?  

i would prefer we limit critical pods to a set of valid namespace prefixes (i.e. kube-* or openshift-*) so we can keep its usage controlled to locked down namespaces and know it will not be abused in any arbitrary namespace.

see for example: https://github.com/openshift/origin/pull/19104

2018-03-27 18:30 UTC, liggitt commented
> why lift this restriction now?

this is only lifting the restriction on the field-based priority. the annotation-based critical pods are still limited to the kube-system namespace.

any system that wants to prevent pods in other namespaces being treated as critical pods must do so by disallowing them setting the priority field to a critical level, not by depending on this namespace restriction. otherwise, they are allowing "time-bomb" data to be persisted that could lead to those pods suddenly being treated as critical after a future upgrade.

2018-03-27 18:31 UTC, derekwaynecarr commented
ignore my prior comment.

the change in this PR was for priority and not for the annotation.  the annotation is still restricted to the kube-system namespace.  priority is open to any (which is good).

/approve
/lgtm

2018-03-27 19:27 UTC, ravisantoshgudimetla commented
/retest

2018-03-27 20:04 UTC, ravisantoshgudimetla commented
/retest

2018-03-27 21:27 UTC, ravisantoshgudimetla commented
/retest

2018-03-28 18:39 UTC, merged