Support --all flag for patch
kubernetes/kubernetes pull request #60723
Opened 2018-03-02 19:03 UTC by damemi

**What this PR does / why we need it**:
Adds a `--all` flag for `patch` allowing patching of all resources of the specified type

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
https://github.com/openshift/origin/issues/18644

**Special notes for your reviewer**:

**Release note**:
```release-note
kubectl now supports --all for `patch`
```

2018-03-02 19:19 UTC, juanvallejo commented
cc @soltysh

2018-03-02 19:59 UTC, jdumars commented
/ok-to-test

2018-03-02 20:49 UTC, damemi commented
Added test in `hack/make-rules/test-cmd-util.sh`

2018-03-02 21:02 UTC, damemi commented
looks like flaked on https://github.com/kubernetes/kubernetes/issues/60730

2018-03-02 21:23 UTC, juanvallejo commented
/lgtm

2018-03-02 22:39 UTC, damemi commented
/test pull-kubernetes-verify

2018-03-06 17:44 UTC, mengqiy commented on pkg/kubectl/cmd/patch.go
> +	cmd.Flags().Bool("all", false, "Select all resources in the namespace of the specified resource types")
Allowing the user to patch `all` resources in a namespace increases the change of the user blow up their cluster.
I'm not blocking this. But please add an example for it.

2018-03-16 15:33 UTC, damemi commented
/test pull-kubernetes-integration
/test pull-kubernetes-verify

2018-03-16 17:03 UTC, soltysh requested changes
I agree with @mengqiy here, selecting all is bad.

2018-03-16 17:03 UTC, soltysh commented
/hold

2018-03-16 17:03 UTC, soltysh commented
/lgtm cancel

2018-03-16 20:20 UTC, damemi commented
@soltysh is this just something that's unnecessary then? The use case provided in https://github.com/openshift/origin/issues/18644 seemed like a good example to me. Though I can see the risk of adding it, I think there is some responsibility on the user to wield flags like `--all` with care. Ultimately, would this be worth it?

2018-03-19 09:21 UTC, soltysh commented
@damemi introducing `--all` might open a pandora box for this command. I don't think neither of us wants to handle with a storm of problems that might appear after doing it. So yeah, I'd say not to do it.

2018-03-27 08:04 UTC, AuHau commented
I understand your worries, but if you decide to reject this, please at least document it as the CLI actually suggests usage of this flag (viz. the issue #18644)

2018-03-30 15:27 UTC, soltysh commented
Not sure which part of the linked issue suggests using it, sorry.

2018-07-18 20:17 UTC, apelisse commented
> Not sure which part of the linked issue suggests using it, sorry.

Would you be more open to a label selector rather than `--all`?

2018-12-15 22:42 UTC, closed without merging