Explicit HTTP link for the local proxy server
kubernetes/kubernetes pull request #61533
Opened 2018-03-22 10:04 UTC by fqsghostcloud

fix http link format

2018-03-22 10:05 UTC, fqsghostcloud commented
/assign @shyamjvs

2018-03-22 12:58 UTC, fqsghostcloud commented
/assign @dshulyak

2018-03-24 09:18 UTC, fqsghostcloud commented
@shyamjvs please merge this PR,thanks

2018-03-24 10:33 UTC, shyamjvs commented
/lgtm
/retest

For approval, you need someone from the OWNERS file to do it.

2018-03-24 15:20 UTC, fqsghostcloud commented
@jbeda  please merge this PR,thanks

2018-03-27 10:08 UTC, fqsghostcloud commented
/assign @soltysh

2018-03-30 15:31 UTC, soltysh requested changes
I don't think this kind of change is necessary.

2018-03-30 15:31 UTC, soltysh commented on pkg/kubectl/cmd/proxy.go
> +	fmt.Fprintf(out, "Starting to serve on http://%s\n", l.Addr().String())
This assumes it's always http, but that's not a good assumption.

2018-03-30 15:31 UTC, soltysh commented
/hold

2018-09-17 16:05 UTC, closed without merging