kubectl drain support --ignore-not-found
kubernetes/kubernetes pull request #61698
Opened 2018-03-26 09:33 UTC by zjj2wry

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/kind feature

**Release note**:

```release-note
kubectl drain support --ignore-not-found
```

2018-03-26 09:37 UTC, zjj2wry commented
ref #61699

2018-03-26 14:46 UTC, juanvallejo approved these changes

2018-03-26 14:47 UTC, juanvallejo commented
/lgtm
/test pull-kubernetes-e2e-gce

cc @soltysh for approval

2018-03-27 08:44 UTC, soltysh requested changes

2018-03-27 08:44 UTC, soltysh commented on pkg/kubectl/cmd/drain.go
> +	cmd.Flags().BoolVar(&options.IgnoreNotFound, "ignore-not-found", options.IgnoreNotFound, "Treat \"resource not found\" as a successful delete. Defaults to \"true\" when --all is specified.")
There's no `all` flag in drain that I know off, so please update this comment accordingly.

2018-04-02 02:02 UTC, zjj2wry commented
@soltysh @juanvallejo updated, ptal

2018-04-02 15:06 UTC, juanvallejo commented on hack/make-rules/test-cmd-util.sh
> +  kubectl drain UNKNOW --ignore-not-found=true
nit: s/UNKNOW/UNKNOWN

2018-04-02 15:06 UTC, juanvallejo commented
/lgtm

2018-04-03 02:02 UTC, zjj2wry commented
address, ptal

2018-04-08 05:50 UTC, zjj2wry commented
/retest

2018-04-16 05:26 UTC, zjj2wry commented
/retest
@soltysh for approve，thanks

2018-05-03 16:03 UTC, liggitt commented
can you clarify the case where you'd be draining a node you weren't sure existed?

2018-05-04 02:07 UTC, zjj2wry commented
I will drain the pod when I delete the node in the cluster. If the node no longer exists I hope my script returns exit 0. so ignore-node-find would be helpful do this, thanks

2018-05-22 13:15 UTC, soltysh commented
@zjj2wry we'll have a discussion about exit codes for kubectl during next sig-cli meeting, let's wait until after that.

2018-07-16 11:42 UTC, closed without merging

2019-07-17 20:46 UTC, seh commented
For both _kubectl cordon_ and _kubectl drain_, I've run into cases where in a program I collect a set of nodes that exist at some early point in time, and then later I want to cordon or drain all of those that still exist. They may have been deleted for some reason in the meantime, such as by the cluster autoscaler. It's quite inconvenient to catch the case of the intended node now being gone.

Even with _kubectl get node_, we don't necessarily want to use `--ignore-not-found`, because it succeeds whether the node exists or not. Perhaps we could run that, and if the output is empty, then we can conclude that the node doesn't exist. Without that flag, _kubectl get node_ fails if the node doesn't exist, but we don't know if that's why it failed; it could be that the node _does_ exist, but we failed to query the API server successfully.