Search using hostname not instance name
kubernetes/kubernetes pull request #61951
Opened 2018-03-30 19:06 UTC by dims

**What this PR does / why we need it**:

We have now switching entirely to using the hostname from the metadata
service or config drive. However we were still searching for the VM
using the server name and not the host name. In this commit, we use
the `hostname=xyz` instead of `name=xyz` which ensures that we make use
of the search using the sanitized name.

https://developer.openstack.org/api-ref/compute/#list-servers
(see hostname (Optional))

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-03-30 19:14 UTC, dims commented
cc @voelzmo @BugRoger please take a look

2018-04-02 00:49 UTC, dims commented
/hold

2018-04-02 14:18 UTC, dims commented
/test pull-kubernetes-e2e-kops-aws

2018-04-03 06:54 UTC, voelzmo requested changes

2018-04-03 06:54 UTC, voelzmo commented on pkg/cloudprovider/providers/openstack/openstack.go
> +	Hostname string `q:"hostname"`
I'm not sure if searching for a hostname works like this? I don't see `hostname` in https://godoc.org/github.com/rackspace/gophercloud/openstack/compute/v2/servers#ListOpts. The nova API says
> This parameter is only valid when specified by administrators. If non-admin users specify this parameter, it is ignored.

See https://developer.openstack.org/api-ref/compute/#list-server-request

So I don't think we can use this filter. It shouldn't be necessary or even recommended to provide an admin user for installing k8s on OpenStack

2018-04-03 09:29 UTC, closed without merging