[WIP] wire printflags through create commands
kubernetes/kubernetes pull request #62181
Opened 2018-04-05 22:40 UTC by juanvallejo

**Release note**:
```release-note
NONE
```

Depends on https://github.com/kubernetes/kubernetes/pull/62139

Begins wiring PrintFlags through create subcommands.
Opening now to begin gathering feedback.

cc @soltysh @deads2k

2018-04-06 20:38 UTC, soltysh requested changes
A few nits here and there, but mostly looks good.

2018-04-06 20:38 UTC, soltysh commented on pkg/kubectl/cmd/create.go
> +	OutputFormat     string
`OutputFormat` is not needed anymore.

2018-04-06 20:38 UTC, soltysh commented on pkg/kubectl/cmd/create_clusterrole.go
>  	return c.PrintObject(clusterRole)
Use `PrintObj` for consistency with all the changes.

2018-04-06 20:38 UTC, soltysh commented on pkg/kubectl/cmd/create_deployment.go
> +		CmdErr: cmdErr,
Put `CmdErr` into the common struct `CreateSubcommandOptions` even if not all use it, it still does make sense to be just there.

2018-04-06 22:08 UTC, juanvallejo commented
@soltysh thanks for the review, comments addressed.

2018-04-13 18:24 UTC, soltysh approved these changes
/lgtm
/approve no-issue

2018-04-13 22:03 UTC, merged