Kubeadm HA - make API.ControlPlaneEndpoint accept IP
kubernetes/kubernetes pull request #62667
Opened 2018-04-16 20:13 UTC by fabriziopandini

**What this PR does / why we need it**:
This PR implements one of the actions defined by https://github.com/kubernetes/kubeadm/issues/751 (checklist form implementing HA in kubeadm).

With this PR, the `API.ControlPlaneEndpoint` value in the kubeadm MasterConfiguration file now accepts both DNS and IP.

The `API.ControlPlaneEndpoint` should be used to set a stable IP address for the control plane; in an HA configuration, this should be the load balancer address (no matter if identified by a DNS name or by a stable IP).

**Special notes for your reviewer**:
/CC @kubernetes/sig-cluster-lifecycle-pr-reviews @timothysc 

**Release note**:
```release-note
API.ControlPlaneEndpoint in kubeadm init configuration file now accepts also IP addresses
```

2018-04-16 21:43 UTC, fabriziopandini commented
/test pull-kubernetes-verify

2018-04-17 02:58 UTC, xiangpengzhao commented
Test failure:
```
# k8s.io/kubernetes/cmd/kubeadm/app/util
cmd/kubeadm/app/util/endpoint.go:98: Errorf call has arguments but no formatting directives
cmd/kubeadm/app/util/endpoint.go:112: Errorf call has arguments but no formatting directives
cmd/kubeadm/app/util/endpoint.go:122: Errorf call has arguments but no formatting directives
make[1]: *** [vet] Error 1
```

2018-04-17 19:48 UTC, timothysc requested changes
We have utility overlap that we should reduce.  I think we should either reduce, eliminate, or rename e.g. - kubeadm/app/util/endpoint.go

2018-04-17 19:48 UTC, timothysc commented on cmd/kubeadm/app/apis/kubeadm/validation/validation.go
> +	if len(c.API.ControlPlaneEndpoint) > 0 {
GetMasterHostPort also has this logic, we should probably unify - https://github.com/kubernetes/kubernetes/pull/62314/files

2018-04-20 22:15 UTC, timothysc approved these changes
/lgtm 
/approve
/assign @timothysc

2018-04-22 10:00 UTC, closed without merging