[WIP] Etcd check
kubernetes/kubernetes pull request #62724
Opened 2018-04-17 10:19 UTC by detiber

**What this PR does / why we need it**:

This addresses the kubeadm 1.9 to 1.10 issue for tls-enabled etcd.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Release note**:

```release-note

```

2018-04-17 13:56 UTC, timothysc requested changes
This is more in line with a minimal back-patch that I was looking for but we need to test the heck out of it.  

There are minor things that need to be changed such as referencing the config.

2018-04-17 13:56 UTC, timothysc commented on cmd/kubeadm/app/phases/upgrade/staticpods.go
> +			CertFile:      "/etc/kubernetes/pki/etcd/peer.crt",
These are all config params that should be referenced.

2018-04-18 14:34 UTC, timothysc commented
@detiber @stealthybox - Can we merge this into a single PR and close this one please?

2018-04-18 14:51 UTC, closed without merging

2018-04-19 20:43 UTC, stealthybox commented
Moved to collab PR: https://github.com/stealthybox/kubernetes/pull/1