Add other prometheus monitoring components
kubernetes/kubernetes pull request #62849
Opened 2018-04-19 13:32 UTC by serathius

This PR adds core prometheus monitoring components like alertmanager, kube-state-metrics, node exporter.
Configuration for manifests is extracted from Helm manifests.
```release-note
NONE
```
/cc @kawych @brancz

2018-04-19 14:50 UTC, brancz requested changes
Regarding the Alertmanager, I would like us to seriously consider using the Prometheus Operator in this setup, there are a lot of factors like the ones described in my comment. Those are the kind things that we have been doing for the past two years, and it feel we should seriously consider using it.

2018-04-19 14:50 UTC, brancz commented on cluster/addons/prometheus/alertmanager-deployment.yaml
> +  name: alertmanager
This is another reason why the Prometheus Operator is a good idea here. Running the alertmanager as a deployment is a bad idea, it delivers notifications about alerts and therefore needs to be the most reliable thing in your cluster. With a simple `Deployment` you're not getting any of the high availability features that you want, such as persistent storage and controlled rolling deployments.

2018-04-19 14:50 UTC, brancz commented on cluster/addons/prometheus/alertmanager-deployment.yaml
> +      version: v0.13.0
Latest stable release is v0.14.0

2018-04-19 14:50 UTC, brancz commented on cluster/addons/prometheus/kube-state-metrics-deployment.yaml
> +apiVersion: apps/v1beta2
we're mixing the `apiVersion`s here, we should be consistent

2018-04-26 09:28 UTC, serathius commented
As currently prometheus addon is in experimental state, we don't want/need to introduce all prometheus operator features at once.
@brancz do you have any restrictions about starting with simpler helm setup, without going full HA for AlertManager?

2018-04-26 09:53 UTC, brancz commented
With it only being for testing purposes now I’m ok with this (although a short discussed even this should eventually move out of the Kubernetes repo)

/lgtm

2018-04-26 11:11 UTC, serathius commented
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-gke

2018-04-26 11:14 UTC, kawych commented
/ok-to-test

2018-04-26 11:14 UTC, serathius commented
/test pull-kubernetes-e2e-gke
/test pull-kubernetes-e2e-gce

2018-04-26 12:34 UTC, serathius commented
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-gke

2018-04-26 13:46 UTC, serathius commented
/test pull-kubernetes-e2e-gke

2018-04-27 07:41 UTC, serathius commented
/test pull-kubernetes-e2e-gke

2018-04-27 07:42 UTC, serathius commented
I rebased it to master

2018-04-27 07:54 UTC, brancz commented
/lgtm

2018-04-27 08:42 UTC, serathius commented
/test pull-kubernetes-e2e-gke

2018-04-27 09:03 UTC, merged