finish wiring PrintFlags
kubernetes/kubernetes pull request #63055
Opened 2018-04-24 04:45 UTC by juanvallejo

**Release note**:
```release-note
NONE
```

Finish wiring PrintFlags through commands

cc @deads2k @soltysh

2018-04-25 05:53 UTC, dixudx requested changes

2018-04-25 05:53 UTC, dixudx commented on pkg/kubectl/cmd/rollingupdate.go
> +	o.DeploymentKey = cmdutil.GetFlagString(cmd, "deployment-label-key")
You can bind these flags to struct `RollingUpdateOptions`, which will be easily unit tested with predictable default behavior. #60363 FYI.

/cc @soltysh

2018-04-25 10:42 UTC, soltysh requested changes

2018-04-25 10:42 UTC, soltysh commented on pkg/kubectl/cmd/rollingupdate.go
> +			cmdutil.CheckErr(o.Run(f, out, cmd, args))
Get rid of factory from `Run` at all costs!

2018-04-25 10:42 UTC, soltysh commented on pkg/kubectl/cmd/rollout/rollout_pause.go
> +		Out:        out,
Use `IOStreams`.

2018-04-25 10:42 UTC, soltysh commented on pkg/kubectl/cmd/rollout/rollout_resume.go
> +		Out:        out,
Use `IOStreams`.

2018-04-25 10:42 UTC, soltysh commented on pkg/kubectl/cmd/scale.go
> +	Out io.Writer
`IOStreams`

2018-04-25 10:42 UTC, soltysh commented on pkg/kubectl/cmd/taint.go
> +		out:        out,
`IOStreams`

2018-04-25 23:27 UTC, juanvallejo commented
@soltysh thanks for the review, comments addressed

2018-04-26 08:21 UTC, soltysh approved these changes
/approve no-issue

You just need to update bazel and this is good to go.

2018-04-26 19:03 UTC, juanvallejo commented
@soltysh thanks, tests are now passing

2018-04-26 19:18 UTC, soltysh approved these changes
/lgtm

2018-04-26 19:46 UTC, deads2k commented
/hold

conflicts with restmapping again.

2018-04-27 09:43 UTC, soltysh commented
/hold cancel
the restmapping pr (#63105) merged

2018-04-27 10:31 UTC, soltysh commented
Closed in favor of https://github.com/kubernetes/kubernetes/pull/63244

2018-04-27 10:31 UTC, closed without merging

2018-04-27 12:12 UTC, deads2k commented
/hold cancel