support simultaneous kubeadm --v and --config
kubernetes/kubernetes pull request #63159
Opened 2018-04-25 18:00 UTC by hh

**What this PR does / why we need it**:

Providing -v and --config parameters to increase verbosity while providing a kubeadm.config results in an error rather than providing the requested verbosity.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes https://github.com/kubernetes/kubeadm/issues/765

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-04-25 18:46 UTC, hh commented
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

2018-04-25 18:53 UTC, timothysc approved these changes
/lgtm 
/approve

2018-04-25 19:52 UTC, fabriziopandini requested changes
@hh thanks for this PR!
What about the other glog flags?

2018-04-25 21:03 UTC, merged

2018-04-26 00:44 UTC, hh commented
@fabriziopandini what flags are you referring to?

2018-04-26 06:10 UTC, fabriziopandini commented
@hh you can see all the log related flags executing `kubeadm --help`  or take a look at the glog source here https://github.com/kubernetes/kubernetes/blob/cc845246e4afe82271d4f8160badbe11f4c7a929/vendor/github.com/golang/glog/glog.go#L398