Improve Azure disk operations for vmas and vmss
kubernetes/kubernetes pull request #63179
Opened 2018-04-26 06:27 UTC by feiskyer

**What this PR does / why we need it**:

Today, VirtualMachineScaleSetVM and VirtualMachine are different data structures (because of different API versions), so the disk attach operation seems duplicate between vm and vmss. That means although disk operations are in same logic, some duplication is required then.

With #63063, they are using the same API now. This PR improves Azure disk operations by adding another `GetDataDisks()` interface in vmSet and moving common logics to controllerCommon.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59736

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-04-26 09:35 UTC, feiskyer commented
/retest

2018-04-27 02:25 UTC, andyzhangx requested changes
the following logic could be combined in one common function for func like AttachDisk, DetachDiskByName, that could make the code more clear:
```
	// 1. vmType is standard, get data disks with availabilitySet.GetDataDisks.
	if c.cloud.VMType == vmTypeStandard {
		return c.cloud.vmSet.GetDataDisks(nodeName)
	}

	// 2. vmType is Virtual Machine Scale Set (vmss), convert vmSet to scaleSet.
	ss, ok := c.cloud.vmSet.(*scaleSet)
	if !ok {
		return nil, fmt.Errorf("error of converting vmSet (%q) to scaleSet with vmType %q", c.cloud.vmSet, c.cloud.VMType)
	}

	// 3. If the node is managed by availability set, then get with availabilitySet.GetDataDisks.
	managedByAS, err := ss.isNodeManagedByAvailabilitySet(mapNodeNameToVMName(nodeName))
	if err != nil {
		return nil, err
	}
	if managedByAS {
		// vm is managed by availability set.
		return ss.availabilitySet.GetDataDisks(nodeName)
	}
```

2018-04-27 03:07 UTC, feiskyer commented
@andyzhangx Good catch. Added new `getNodeVMSet()` to address it. PTAL

2018-04-27 03:24 UTC, andyzhangx approved these changes
/lgtm

2018-04-27 05:59 UTC, feiskyer commented
/retest

2018-04-27 07:55 UTC, merged