Improve kubeadm upgrade path for CoreDNS
kubernetes/kubernetes pull request #63400
Opened 2018-05-03 15:03 UTC by rajansandeep

**What this PR does / why we need it**:
This PR achieves the following:
1. Retains the CoreDNS ConfigMap defined by the user during `kubeadm upgrade`.
2. Removes the CoreDNS deployment when user decides to install kube-dns during `kubeadm upgrade`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-05-09 01:53 UTC, timothysc requested changes

2018-05-09 01:53 UTC, timothysc commented on cmd/kubeadm/app/phases/upgrade/postupgrade.go
> +	return apiclient.TryRunCommand(func() error {
I don't see why this is written as a closure vs part of the function itself?

2018-05-09 13:47 UTC, neolit123 commented on cmd/kubeadm/app/util/apiclient/idempotency.go
> +}
i would do this do remove one level of indentation:
```php
func CreateOrRetainConfigMap(client clientset.Interface, cm *v1.ConfigMap, configMapName string) error {
	if _, err := client.CoreV1().ConfigMaps(cm.ObjectMeta.Namespace).Get(configMapName, metav1.GetOptions{}); err != nil {
		if !apierrors.IsNotFound(err) {
			return nil
		}
		if _, err := client.CoreV1().ConfigMaps(cm.ObjectMeta.Namespace).Create(cm); err != nil {
			if !apierrors.IsAlreadyExists(err) {
				return fmt.Errorf("unable to create configmap: %v", err)
			}
		}
	}
	return nil
}
```

2018-05-10 21:25 UTC, detiber commented
/lgtm

@timothysc I'm good with this merging separately, it does not conflict with https://github.com/kubernetes/kubernetes/pull/63509

2018-05-10 21:34 UTC, rajansandeep commented
/test pull-kubernetes-e2e-kops-aws

2018-05-14 19:17 UTC, timothysc approved these changes
/approve

2018-05-14 21:35 UTC, merged