Bump CoreDNS to GA in kubeadm
kubernetes/kubernetes pull request #63401
Opened 2018-05-03 15:07 UTC by rajansandeep

**What this PR does / why we need it**:
Graduates CoreDNS to GA.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-05-07 19:45 UTC, timothysc requested changes
/cc @luxas

2018-05-07 19:45 UTC, timothysc commented on cmd/kubeadm/app/features/features.go
> +	CoreDNS:              {FeatureSpec: utilfeature.FeatureSpec{Default: false, PreRelease: utilfeature.GA}, MinimumVersion: v190},
default - true please .

2018-05-08 00:40 UTC, detiber commented
I also cherry-picked this into my PR for defaulting the CoreDNS feature flag to true: https://github.com/kubernetes/kubernetes/pull/63509

2018-05-08 14:02 UTC, fturib commented
@timothysc @detiber @luxas : after talk with @thockin, @bowei - it was agreed that CoreDNS will go GA this version 1.11 of k8s, but will be the default DNS service only after some adoption by users - which means at earlieast v1.12

So, the KEP was changed to include only the GA part : https://github.com/kubernetes/community/pull/1956

Another KEP has to ne opened for the "Default" part.


and the initial feature description was also changes was now 2 features proposed opened:

- one for GA : https://github.com/kubernetes/features/issues/427
- one for Default : https://github.com/kubernetes/features/issues/566

2018-05-08 18:08 UTC, neolit123 commented
can be closed given it was cherry picked here #63509.

2018-05-09 14:26 UTC, luxas commented
@fturib We're enabling it by default in v1.11 anyway. That way we'll also be kind of a guinea pig (although that really shouldn't be the case for GA) and maybe catch potential issues before v1.12. It's probably better than the current kube-dns anyway.

2018-05-09 14:28 UTC, luxas commented
Closing in favor of #63509. Thanks!

2018-05-09 14:28 UTC, closed without merging