cleanup TODOs from PrintFlags wiring
kubernetes/kubernetes pull request #63511
Opened 2018-05-07 21:48 UTC by juanvallejo

**Release note**:
```release-note
NONE
```

Address TODOs from PrintFlags wiring

cc @soltysh @deads2k

2018-05-09 14:43 UTC, soltysh requested changes

2018-05-09 14:43 UTC, soltysh commented on pkg/kubectl/cmd/create/create_clusterrolebinding.go
>  func (o *ClusterRoleBindingOpts) Run(f cmdutil.Factory) error {
Remove the factory.

2018-05-09 14:43 UTC, soltysh commented on pkg/kubectl/cmd/create/create_pdb.go
>  func (o *PodDisruptionBudgetOpts) Run(f cmdutil.Factory) error {
This applies to all `create_*` commands.

2018-05-09 15:25 UTC, juanvallejo commented
@soltysh thanks, removed factory from Run method in create cmds

2018-05-10 18:53 UTC, ixdy commented
/retest

2018-05-10 19:30 UTC, soltysh approved these changes
/lgtm
/approve no-issue

2018-05-10 21:25 UTC, merged