Add option to run follow + label
kubernetes/kubernetes pull request #63614
Opened 2018-05-09 18:07 UTC by GabrielSVinha

**What this PR does / why we need it**:
Remove check for follow + selector when running kubectl logs -l <selector> -f

**Which issue(s) this PR fixes**
Fixes #52218

2018-05-09 18:38 UTC, dims commented
/ok-to-test

2018-05-10 01:48 UTC, GabrielSVinha commented
/release-note-none

2018-05-22 18:20 UTC, ereslibre commented
I have a comment regarding this feature. This patch won't work as-is (unless I'm wrong) because when you reach:

https://github.com/kubernetes/kubernetes/blob/10b8665a1c9dd5714b13130fcbf5c04f7f658178/pkg/kubectl/cmd/logs.go#L297

on the first pod, this operation will block, and you won't follow the rest of the pod logs, only the first one. I started to work on this a couple of days ago, and I have something very similar:

https://github.com/kubernetes/kubernetes/compare/master...ereslibre:follow-selector

However, I wanted to take more things into account before submitting a PR. Meaning: what happens if in the process of following a selector logs (e.g. `kubectl logs -f -lapp=myapp`) its pods are modified (e.g. killed because of a liveness probe and brought back). In this case, the patch I have won't work either, I don't know if that's within the scope of `kubectl logs` or we just want to ignore those edge cases. When you follow a specific pod in current kubernetes and it dies, you lose the follow and the process ends (obviously), but with a selector there's two viable options:

1. Ignore whatever happens in the future. We only follow the set of pods that matched the selector.
2. While you are following the logs, keep track of the pod changes and follow those too if new pods appear.

I think a simple approach could be the ideal case first, but as said, this PR won't actually follow a set of pods correctly because it'll lock on the first one.

2018-08-01 07:32 UTC, dixudx requested changes
I don't think this really does implement this.

2018-08-01 07:33 UTC, dixudx commented
Agree with @ereslibre. This PR does not really implement this feature.

2018-09-18 12:57 UTC, dims commented
/uncc

2019-02-15 14:21 UTC, closed without merging