Make kubectl could create clusterrole with aggregation rules
kubernetes/kubernetes pull request #63851
Opened 2018-05-15 09:06 UTC by WanLinghao

**What this PR does / why we need it**:
The clusterrole aggregation rule features are available since v1.9:
https://kubernetes.io/docs/admin/authorization/rbac/#aggregated-clusterroles
This patch makes kubectl could create clusterrole with aggregation rules.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-05-15 10:07 UTC, WanLinghao commented
/test pull-kubernetes-e2e-gce

2018-05-15 12:35 UTC, neolit123 requested changes
noticed some typos in the diff.

2018-05-15 12:35 UTC, neolit123 commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +	matchLabels := map[string]string{}
typo in the function name.

2018-05-15 12:35 UTC, neolit123 commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +			return nil, fmt.Errorf("wrong aggretation rule format.must be like xxx=yyy")
typo, also i would change it to:
`wrong aggregation rule format. It should be xxx=yyy"

2018-05-15 12:35 UTC, neolit123 commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +		aggretationRules, err := generateAggretaionRule(c.AggregationRule)
typo in the function name and in `aggretationRules`

2018-05-15 12:35 UTC, neolit123 commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +			return fmt.Errorf("aggregation rule must be specified without neither nonResourceURLs, verbs, resources or resourceNames.")
please change to:
`aggregation rule must be specified without nonResourceURLs, verbs, resources or resourceNames`
(notice no dot at the end)

2018-05-15 12:38 UTC, neolit123 commented
please, change the commit message title to something in the lines of:
```
kubectl: add aggregation rule support to clusterrole
```
right not it seems to span on a couple of lines.

@kubernetes/sig-cli-pr-reviews

2018-05-15 15:58 UTC, ericchiang commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +		parts := strings.Split(rule, "=")
You can just use the utilities in staging/src/k8s.io/apiserver/pkg/util/flag/map_string_string.go

2018-05-15 16:00 UTC, ericchiang commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +		kubectl create clusterrole aggregation --aggregation-rule="rbac.example.com/aggregate-to-monitoring=true"`))
Nit: change

> kubectl create clusterrole aggregation

To

> kubectl create clusterrole "monitoring"

Just to make sure that this isn't mistaken as an "aggregation" subcommand

2018-05-15 16:08 UTC, ericchiang commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +	cmd.Flags().StringArrayVar(&c.AggregationRule, "aggregation-rule", c.AggregationRule, "Aggregation rule is used to combine other ClusterRoles.")
Instead of:

> "Aggregation rule is used to combine other ClusterRoles."

Maybe:

> "An aggregation label selector for combining ClusterRoles."

2018-05-15 18:35 UTC, juanvallejo commented
/retest

2018-05-15 18:36 UTC, juanvallejo commented
lgtm, pending review comments

2018-05-18 02:11 UTC, WanLinghao commented
@soltysh PTAL

2018-05-18 03:20 UTC, dixudx reviewed
In addition, please try to add some e2e tests about this in https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-cmd-util.sh to verify the functionality.

2018-05-18 03:20 UTC, dixudx commented on pkg/kubectl/cmd/create/create_clusterrole.go
> +	if len(c.AggregationRule) > 0 {
Better add some unit tests on this.

2018-05-18 11:47 UTC, WanLinghao commented
@dixudx Done, PTAL

2018-05-19 02:25 UTC, dixudx commented
/lgtm

2018-05-21 03:05 UTC, WanLinghao commented
@soltysh  friendly ping

2018-05-22 08:56 UTC, WanLinghao commented
@deads2k PTAL

2018-05-22 12:52 UTC, soltysh approved these changes
/approve

2018-05-22 15:40 UTC, merged