Add a 'kubeadm config print-default' command
kubernetes/kubernetes pull request #63969
Opened 2018-05-17 13:59 UTC by luxas

**What this PR does / why we need it**:
Improves the UX around creating config files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
kubeadm: A `kubeadm config print-default` command has now been added that you can use as a starting point when writing your own kubeadm configuration files
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @liztio

2018-05-17 14:24 UTC, timothysc requested changes
minor nits and a question.

2018-05-17 14:25 UTC, mattkelly commented on cmd/kubeadm/app/cmd/config.go
> +func NewCmdConfigṔrintDefault(out io.Writer) *cobra.Command {
You used `Ṕ` here in `Print` but I think you wanted a `P`

2018-05-17 14:26 UTC, neolit123 commented on cmd/kubeadm/app/cmd/join.go
> +func NewValidJoin(cmd *cobra.Command, cfg *kubeadmapiv1alpha2.NodeConfiguration, args []string, skipPreFlight bool, cfgPath, featureGatesString string, ignorePreflightErrors []string) (*Join, error)
`join_test.go` needs a little change:
```
cmd := NewCmdJoin(&out)
join, err := NewValidJoin(cmd, cfg, tc.args, tc.skipPreFlight, tc.cfgPath, tc.featureGatesString, tc.ignorePreflightErrors)
//                         ^^ passing cmd as argument now
```

2018-05-17 14:30 UTC, neolit123 commented on cmd/kubeadm/app/cmd/join.go
> +	return &Join{cfg: internalcfg}, nil
welp, there is also this issue in `join_test.go`:
```
invalid operation: join (variable of type *Join) has no field or method Validate
````
possibly this and the related tests has to be removed:
https://github.com/luxas/kubernetes/blob/469532c49917bbecaf9d9b29ff5da5a4aa57209c/cmd/kubeadm/app/cmd/join_test.go#L177-L181

2018-05-17 14:45 UTC, chuckha approved these changes
This looks good to me, just one question:

This is printing the internal version of the config, shouldn't it be printing the external version of the config instead? Users should be defining the api extension version of the config, not the internal one.

2018-05-17 15:17 UTC, luxas commented
> This is printing the internal version of the config, shouldn't it be printing the external version of the config instead? Users should be defining the api extension version of the config, not the internal one.

@chuckha This is printing the external version of the config :sunglasses:. The line doing the magic is this one:

```go
kubeadmutil.MarshalToYamlForCodecs(internalcfg, kubeadmapiv1alpha2.SchemeGroupVersion, kubeadmscheme.Codecs)
```
Telling the API machinery framework to serialize it for the external v1alpha2 `GroupVersion`.
Not obvious I know, but kinda cool :wink:

2018-05-17 15:57 UTC, luxas commented
/retest

2018-05-17 17:34 UTC, neolit123 commented
/test pull-kubernetes-verify
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-kubemark-e2e-gce-big

2018-05-17 18:06 UTC, timothysc approved these changes
/lgtm

2018-05-17 21:39 UTC, neolit123 commented
@luxas 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63969/pull-kubernetes-verify/91406/

Chuck was getting this due to not generating the docs locally and including all files(?) i think it's the same PY stacktrace.
/cc @chuckha

2018-05-17 23:57 UTC, luxas commented
Yup, that's right @neolit123, thanks! Ran `./hack/update-generated-docs.sh` now.
Readding lgtm/approved.

2018-05-18 00:58 UTC, luxas commented
/retest

2018-05-18 08:43 UTC, luxas commented
/retest

2018-05-18 10:03 UTC, luxas commented
/retest

2018-05-18 22:59 UTC, merged

2018-05-22 20:01 UTC, neolit123 commented
/test pull-kubernetes-e2e-gce-device-plugin-gpu