Add a new check to PodFitsResources to guarantee the pod limits must be less than the selected node's allocatable resource
kubernetes/kubernetes pull request #64079
Opened 2018-05-21 06:52 UTC by ailusazh

…ble resource

**What this PR does / why we need it**:
When we create a burstable type pod, the pod requests may be much more smaller than the pod limits. If the other predicate conditions satisfied and the pod limits exceed the node's allocatable resource, currently the scheduler predicates can also pass. This may cause the pod cann't use resources as large as those set in the pod limit. This pr add a new check to PodFitsResources to guarantee the pod limits must be less than the selected node's allocatable resource.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2018-05-21 07:46 UTC, krmayankk commented
@ailusazh this is interesting , are you saying that so far the scheduler when fitting pods only accounted for requests and not limits ?

2018-05-21 08:06 UTC, xuxinkun commented
I also face this problem. My pod request is 6Cpu 6GB and limit is 6Cpu 10GB. And the pod is scheduled to the node with 8Cpu 8GB. But it can not be created normally because cgroup can not be set rightly.
This pr can solve this. It is necessary for filtering the not fit node at the predict time.

2018-05-21 12:33 UTC, k82cn commented on pkg/scheduler/algorithm/predicates/predicates.go
> +func PodLimitsFitsHostAllocatableResource(pod *v1.Pod, meta algorithm.PredicateMetadata, nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {
I'd like to enhance `PodFitsResources` instead of a new predicate.

2018-05-21 18:38 UTC, bsalamat reviewed
This should not be a predicate function. It does not make sense to schedule based on limits (unless a compelling use-case is provided). We already have a priority function that prefers a node whose allocatable resources are larger than the Pod limits. The priority function makes more sense.

2018-05-21 22:38 UTC, k82cn commented on pkg/scheduler/algorithm/predicates/predicates.go
> +func PodLimitsFitsHostAllocatableResource(pod *v1.Pod, meta algorithm.PredicateMetadata, nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {
and should be capability instead of allocatable.

2018-05-22 10:08 UTC, xuxinkun commented
@bsalamat  I think it is necessary to filter the not fit nodes in predict function. 
For example, if my pod request is 6Cpu 6GB and limit is 6Cpu 10GB. And the node with 6Cpu 8GB may be selected as the node of my pod. But in fact, if my pod is scheduled to that node, it can not be started because memory.limit_in_bytes of the pod can not be set correctly and will cause a 'write error: Invalid argument' error.

2018-05-22 12:44 UTC, ailusazh commented
@bsalamat if the limit of a container of the pod execced the selected node's allocatable limit, it will cause the a error when starting the container, like the following,
System error: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod16b5c716-5db5-11e8-92f8-e0db55136a58/c61d373dba858f1c4b0f123c7c2cc47c53f9836e489fbd43e9208c9b751d1e3d/cpu.cfs_quota_us: invalid argument

2018-05-22 14:31 UTC, k82cn commented
@ailusazh , would you help open an issue for this? I'd like to involve some developers from sig-node for this.

2018-05-22 21:30 UTC, bsalamat commented
> if the limit of a container of the pod execced the selected node's allocatable limit, it will cause the a error when starting the container

You should increase the resource requests of your pod then. Scheduling by limit still does not make sense to me.

2018-05-23 01:42 UTC, xuxinkun commented
@bsalamat I'm not mean to scheduling by limit, but limit should be taken into consideration. I think the `request` and `limit` should be set independently without node info.
Filtering the not fit node in predict function is necessary.
In my opinion, all the nodes in the list after predicting should be able to create and start the pod.

2018-05-23 07:34 UTC, ailusazh commented
@k82cn I hava already opened a issue [#64185](https://github.com/kubernetes/kubernetes/issues/64185)

2018-05-23 18:06 UTC, bsalamat commented
> Filtering the not fit node in predict function is necessary.

Kubernetes has been working fine without it so far. So, having a predicate is probably not so "necessary". On the node side, any pod that uses more than its requested resources is subject to eviction when the node runs out of resources. In other words, Kubernetes never provides any guarantees of availability of resources beyond a Pod's requests. This is why this function should be a priority function, not a predicate.

2018-05-24 05:49 UTC, ailusazh commented
OK :)

2018-05-24 08:58 UTC, davidopp commented
cc/ @kubernetes/sig-node-feature-requests

2018-05-24 10:02 UTC, ailusazh commented
We have used this pr [#61527](https://github.com/kubernetes/kubernetes/pull/61527) to limited the cpu subsystem of kubepod level cgroup to the node allocatable value in our environment, so it led to the error mentioned above.

2018-05-25 03:34 UTC, resouer commented
> On the node side, any pod that uses more than its requested resources is subject to eviction when the node runs out of resources.

+1 to Bobby's clarification. This should be a node issue if any unexpected behavior comes up.

2018-05-25 23:05 UTC, bsalamat commented
> We have used this pr #61527 which is unmarged to limited the cpu subsystem of kubepod level cgroup to the node allocatable value in our environment, so it led to the error mentioned above.

A better solution for the node side is to set the `min(container/pod limit, node capacity)` in cgroups.

2018-05-25 23:06 UTC, bsalamat requested changes
> We have used this pr #61527 which is unmarged to limited the cpu subsystem of kubepod level cgroup to the node allocatable value in our environment, so it led to the error mentioned above.

A better solution for the node side is to set the `min(container/pod limit, node capacity)` in cgroups.

2018-07-31 23:24 UTC, closed without merging