move f.Command out of the factory
kubernetes/kubernetes pull request #64114
Opened 2018-05-21 19:28 UTC by juanvallejo

**Release note**:
```release-note
NONE
```

Moves the "f.Command" method out of factory_client_access

cc @soltysh

2018-05-21 19:43 UTC, deads2k commented on pkg/kubectl/polymorphichelpers/helpers.go
> +func StringifyCommand(cmd *cobra.Command, showSecrets bool) string {
This should be in the same spot as the `RecordFlags`, right?

2018-05-21 19:44 UTC, deads2k commented
Good intent, wrong package.

/approve
/hold

2018-05-21 20:16 UTC, juanvallejo commented
@deads2k updated "StringifyCommand" to be a helper within record_flags

2018-05-21 21:59 UTC, deads2k commented on pkg/kubectl/genericclioptions/record_flags.go
> +func stringifyCommand(cmd *cobra.Command, showSecrets bool) string {
do you ever pass true?  If not, clean it up

2018-05-22 12:10 UTC, deads2k commented on pkg/kubectl/genericclioptions/record_flags.go
> +func (f *RecordFlags) Complete(cmd *cobra.Command) error {
When you rebase, create a second function that still takes the string directly.

2018-05-22 12:11 UTC, deads2k commented
/lgtm

2018-05-22 12:41 UTC, soltysh requested changes

2018-05-22 12:41 UTC, soltysh commented on pkg/kubectl/genericclioptions/record_flags.go
> +func stringifyCommand(cmd *cobra.Command) string {
We need a better name, please. `stringifyCommand` completely hides the functionality of this command.

2018-05-22 12:41 UTC, soltysh commented on pkg/kubectl/genericclioptions/record_flags.go
> +func stringifyCommand(cmd *cobra.Command) string {
`classifyCommandOutput`, `hideCommandSecrets` or something like that.

2018-05-22 12:41 UTC, soltysh commented on pkg/kubectl/genericclioptions/record_flags.go
> +func stringifyCommand(cmd *cobra.Command) string {
And I agree with David, move this to one of the general helpers and make it public.

2018-05-22 13:06 UTC, soltysh commented on pkg/kubectl/genericclioptions/record_flags.go
> +func stringifyCommand(cmd *cobra.Command) string {
Ignore what I said above, I thought about something else ;)

2018-05-22 15:41 UTC, juanvallejo commented
@deads2k @soltysh thanks, comments addressed

2018-05-22 19:43 UTC, deads2k commented
/lgtm

2018-05-23 12:06 UTC, deads2k commented
/hold cancel

2018-05-23 13:55 UTC, juanvallejo commented
/test pull-kubernetes-e2e-gce

2018-05-23 16:06 UTC, merged