Detach volume when node become NotReady
kubernetes/kubernetes pull request #64245
Opened 2018-05-24 07:12 UTC by FengyunPan2

Fix #53059
Currently if node's status become 'NotReady'(for example node is
'SHUTOFF'), kubernetes reschedules the pod automatically, but the
pod's volume has not been detached at cinder side. We should
detach the volume from instance and allow the volume is attached
to other instance.

**Release note**:
```release-note
NONE
```

/assign @dims 
/assign @zetaab

2018-05-24 07:18 UTC, FengyunPan2 commented
/hold

2018-05-24 07:39 UTC, FengyunPan2 commented
/unhold

2018-05-25 02:30 UTC, FengyunPan2 commented
/test pull-kubernetes-e2e-gce

2018-05-25 03:58 UTC, zetaab commented
How fast the failover is with this solution? If you have pod with pvc tunning in node x and you shutdown that node? Without this pr it is 6-10minutes but with this pr it should be something like 1 minute?

2018-05-29 01:43 UTC, FengyunPan2 commented
> Without this pr it is 6-10minutes

@zetaab When I test this latest kubernetes, I shutdown a node, its pod has been rescheduled, but the pvc of pod has not been detached.
So can you help me find the PR which fixs my issuse, or find the PR which detaches PVC after 6-10minutes?

2018-05-30 01:31 UTC, FengyunPan2 commented
/hold cancel

2018-05-31 06:46 UTC, FengyunPan2 commented
ping @zetaab

2018-05-31 15:56 UTC, zetaab commented
@FengyunPan2 ok here is how you can reproduce that hopefully:

Make cluster with two nodes at least:
1. deploy pod which have pvc to one node
2. shutdown that node from openstack cli/api
3. after 1min (we have 1 min evacuate time) kubernetes starts moving that pod to another node.
4. pod tries to start in another node, but it cannot because drive is not yet detached. In this step it will wait force detach volume. Wait like 10-15minutes it should detach(+attach to new node) the drive and pod should start

2018-05-31 15:58 UTC, zetaab commented
@FengyunPan2 check this my PR https://github.com/kubernetes/kubernetes/pull/58169 its not perfect and I think its not going to work like that. But with that I could decrease cinder volume pod failover from 10minutes to 1minute

2018-06-09 14:16 UTC, dims commented
/unassign
/uncc
/assign @hogepodge 
/assign @dklyle

2018-06-12 02:23 UTC, hogepodge requested changes

2018-07-11 08:33 UTC, FengyunPan2 commented
@zetaab I have read your PR, and I think it is the same as my PR on cinder side, right?
what's your better point? Thanks

2018-07-11 09:22 UTC, zetaab commented
@FengyunPan2 my PR is modifying core logic in all volume types. IMO this your pr is better if we can make it work with small modifications

2018-08-11 11:55 UTC, adampl commented
@zetaab IMHO your PR #58169 is better, because it's not just an Open Stack issue.

It should be addressed in a clean and unified manner across all volume drivers and cluster configs (including Bare Metal).

There's a lot of similar issues, so I think it's high time to fix it once and for all.

2018-08-13 23:45 UTC, hogepodge commented
/hold in favor of #58169

2018-08-22 05:54 UTC, closed without merging