Fix invalid unit test naming causes unit test not to be performed
kubernetes/kubernetes pull request #64488
Opened 2018-05-30 02:24 UTC by wgliang

**What this PR does / why we need it**:
Fix invalid unit test naming causes unit test not to be performed. Unit test function names must begin with `Test` to be executed
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/sig testing

**Release note**:

```release-note
NONE
```

2018-05-30 05:40 UTC, wgliang commented
/assign @jszczepkowski

2018-06-05 11:30 UTC, wgliang commented
/cc @mwielgus @DirectXMan12

PTAL,thanks.

2018-06-12 19:34 UTC, DirectXMan12 requested changes
minor nit inline, otherwise looks fine.

2018-06-12 19:34 UTC, DirectXMan12 commented on pkg/controller/podautoscaler/legacy_horizontal_test.go
> +		switch action.(type) {
what's up with the seemingly unrelated change?  Can you put this in a separate commit with a description?

2018-10-10 23:33 UTC, wgliang commented
/remove-lifecycle rotten

2018-10-10 23:34 UTC, wgliang commented
/remove-lifecycle stale

2018-11-07 20:44 UTC, DirectXMan12 commented
if you're still interested in this PR, please respond to the comment

2019-04-06 23:04 UTC, closed without merging