add job garbage collector support
kubernetes/kubernetes pull request #64955
Opened 2018-06-11 06:46 UTC by ceshihao

**What this PR does / why we need it**:
It's easy to make jobs and forget to delete them. I add jobgc controller similar to `podgc`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64470

**Special notes for your reviewer**:
cc @lavalamp 

**Release note**:

```release-note
Support finished job garbage collecting.
```

2018-06-11 09:01 UTC, yue9944882 commented
/ok-to-test

2018-06-11 09:25 UTC, yue9944882 requested changes
IMHO, job gc should be based on watches by informer instead of a constant checking period and corresponding events should also be recorded on gc.

2018-06-11 17:13 UTC, lavalamp commented
/assign @janetkuo 

I am OK with a second one-off GC like this. I don't consider this a good ultimate solution, but it's OK for now. I don't think this concept applies to resources other than pods and jobs?

2018-06-12 15:53 UTC, yue9944882 commented on pkg/controller/jobgc/gc_controller.go
> +	sort.Sort(byCreationTimestamp(finishedJobs))
No, an anonymous func should be enough without extra type definition and function definition.

2018-06-13 01:13 UTC, ceshihao commented
i see.

On Tue, Jun 12, 2018 at 11:54 PM Kim Min <notifications@github.com> wrote:

> *@yue9944882* commented on this pull request.
> ------------------------------
>
> In pkg/controller/jobgc/gc_controller.go
> <https://github.com/kubernetes/kubernetes/pull/64955#discussion_r194793990>
> :
>
> > +	if gcc.finishedJobThreshold > 0 {
> +		gcc.gcFinished(jobs)
> +	}
> +}
> +
> +// gcFinished deletes jobs that are finished.
> +func (gcc *JobGCController) gcFinished(jobs []*v1.Job) {
> +	finishedJobs := []*v1.Job{}
> +	for _, job := range jobs {
> +		if jobctrl.IsJobFinished(job) {
> +			finishedJobs = append(finishedJobs, job)
> +		}
> +	}
> +
> +	finishedJobCount := len(finishedJobs)
> +	sort.Sort(byCreationTimestamp(finishedJobs))
>
> No, an anonymous func should be enough without extra type definition and
> function definition.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/64955#discussion_r194793990>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHWsgyx4_Isf9GfLLQtz5SUiBuyitoq9ks5t7-RIgaJpZM4UiJM5>
> .
>

2018-06-13 01:14 UTC, ceshihao commented on pkg/controller/jobgc/gc_controller.go
> +	sort.Sort(byCreationTimestamp(finishedJobs))
I see. Thank you.

2018-06-22 01:17 UTC, janetkuo commented
Please hold off implementing another GC controller following the podgc pattern. Podgc has its own problem, it's designed that way because it was created before generic garbage collector. Now that we have generic garbage collector I'd like to solve Job GC in a more generic way. See my proposal: https://github.com/kubernetes/community/pull/2287

2018-06-22 01:18 UTC, janetkuo requested changes
Please hold off implementing another GC controller following the podgc pattern. Podgc has its own problem, it's designed that way because it was created before generic garbage collector. Now that we have generic garbage collector I'd like to solve Job GC in a more generic way. See my proposal: https://github.com/kubernetes/community/pull/2287

2018-06-27 07:03 UTC, ceshihao commented
/close

2018-06-27 07:03 UTC, closed without merging