kubeadm - fix local etcd grpc gateway
kubernetes/kubernetes pull request #65020
Opened 2018-06-12 15:31 UTC by detiber

**What this PR does / why we need it**:
etcd 3.2 uses the server certificate as the client cert for the grpc
gateway, this updates the generation of the etcd server certificate to
add client usage to resolve the issue.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubeadm/issues/910

**Release note**:
```release-note
NONE
```

2018-06-12 16:04 UTC, detiber commented
/kind bug
/priority critical-urgent

2018-06-12 16:05 UTC, detiber commented
/assign @luxas

2018-06-12 16:15 UTC, timothysc requested changes
/approve

2018-06-12 16:15 UTC, timothysc commented on cmd/kubeadm/app/phases/certs/certs.go
> +		Usages:     []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
Could you log an issue against etcd and add a //TODO to fix this in the future.

2018-06-12 17:03 UTC, luxas approved these changes
/lgtm

As discussed in the SIG meeting, we're gonna do this as it's the way to go right now using the current etcd versions, but talk to the etcd team to improve this security-wise in the future. As Tim said, please do open an issue against coreos/etcd

2018-06-12 18:24 UTC, merged

2018-09-04 06:46 UTC, guillaumerose commented
Do you have an update for the fix in etcd ? 

I'm looking at moving Docker Desktop from Kubernetes 1.10 to 1.11 and this certificate issue breaks the update process at the moment.