remove unuse todo
kubernetes/kubernetes pull request #65132
Opened 2018-06-15 08:05 UTC by stewart-yu

**What this PR does / why we need it**:
now that we have refactor to function `truncatePodHostnameIfNeeded()`, we should remove this unuse TODO

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-06-15 11:16 UTC, php-coder commented
/kind cleanup

2018-09-14 03:36 UTC, stewart-yu commented
/remove-lifecycle stale

2018-11-29 08:24 UTC, resouer requested changes
A minimal fix would be delete the TODO, and keep parameters as simple as it was.

2018-12-01 04:43 UTC, stewart-yu commented
/retest

2018-12-18 07:15 UTC, stewart-yu commented
/assign @dchen1107 @yujuhong 
for review, thanks

2018-12-18 19:42 UTC, yujuhong commented
/lgtm
/approve

2018-12-19 12:04 UTC, stewart-yu commented
/retest

2018-12-19 14:51 UTC, merged