Get rif of depends on kubectl in kubeadm
kubernetes/kubernetes pull request #65402
Opened 2018-06-23 07:02 UTC by hanxiaoshuai

**What this PR does / why we need it**:
Get rif of depends on kubectl in kubeadm
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-06-23 08:09 UTC, stewart-yu commented on cmd/kubeadm/app/cmd/completion.go
> +		Short:   kubeadmutil.T("Output shell completion code for the specified shell (bash or zsh)."),
Why not just grid of `i18n.T()` function, use `string` istead ?

2018-06-23 08:32 UTC, hanxiaoshuai commented
/test pull-kubernetes-e2e-gce

2018-06-23 22:23 UTC, fabriziopandini requested changes
@hanxiaoshuai thanks for this PR!
I'm in favour of removing this dependency, because `i18n` is basically not used in kubeadm.
However, I would like to align the two commands using ``i18n` to all the other kubeadm commands using `string` instead of introducing a new external library.

2018-06-30 09:16 UTC, luxas reviewed
Thanks @hanxiaoshuai for this PR.
Actually, as we don't support translation at all in kubeadm (yet!) I'm fine with just removing the deps totally, not adding the new `T` func and just using plain strings in these two places.

2018-06-30 09:28 UTC, hanxiaoshuai commented
@fabriziopandini @luxas Done

2018-06-30 09:43 UTC, luxas approved these changes
Thanks @hanxiaoshuai!
/lgtm
/approve

2018-06-30 17:50 UTC, merged