fix usage string for the kubectl logs command
kubernetes/kubernetes pull request #65545
Opened 2018-06-27 19:49 UTC by tvieira

Even though the use of an inline [CONTAINER] name is still accepted for,
legacy purpose the error message does not match what the documentation
or man page says. This commit aligns the usage string that is displayed
when the `kubectl logs` command is called with more than one container
name (with the use of the -c flag or not).

```release-note
NONE
```

2018-06-27 20:03 UTC, nikhita commented on pkg/kubectl/cmd/logs.go
> +	logsUsageStr = "expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.\nPOD or TYPE/NAME is a required argument for the logs command"
:+1:

2018-06-27 20:03 UTC, nikhita commented
/ok-to-test

2018-06-27 20:04 UTC, nikhita commented
@tvieira thanks for your first PR to Kubernetes! :)

2018-06-27 22:48 UTC, tvieira commented
/retest

2018-06-28 06:30 UTC, ceshihao requested changes

2018-06-28 06:30 UTC, ceshihao commented on pkg/kubectl/cmd/logs.go
> +	logsUsageStr = "expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.\nPOD or TYPE/NAME is a required argument for the logs command"
Perhaps, you can reuse the string here.
https://github.com/kubernetes/kubernetes/blob/c4ca6638c397e90a486d363a10b3e6411fa6a0e4/pkg/kubectl/cmd/logs.go#L103

You do not have to modify multiple strings if the usage is changed again.

2018-06-28 06:32 UTC, ceshihao commented
/sig cli

2018-07-02 13:33 UTC, soltysh requested changes

2018-07-02 13:33 UTC, soltysh commented on pkg/kubectl/cmd/logs_test.go
> +			expected: "'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.\nPOD or TYPE/NAME is a required argument for the logs command",
Honestly, these tests are worthless, they don't give any value. We don't guarantee output stability and this is testing just that. Please remove both.

2018-07-19 13:59 UTC, tvieira commented
Sorry the delay folks, a mixed of conferences & time off delayed this commit.

@ceshihao I created then a usage string that contains the usage format so it can be used in other places (such as doc), and replaced the previous string with a usage error string, which reuses the newly created usage format to display how it should be used.

@soltysh I removed both tests.

2018-08-03 16:36 UTC, tvieira commented
/test pull-kubernetes-integration

2018-08-03 16:36 UTC, tvieira commented
/test pull-kubernetes-e2e-gce-device-plugin-gpu

2018-08-03 19:13 UTC, tvieira commented
Hi @ceshihao , would you mind to review the changes based on your suggestion?

2018-08-07 17:55 UTC, tvieira commented
/test pull-kubernetes-e2e-gce-device-plugin-gpu

2018-08-20 13:13 UTC, tvieira commented
Hi @soltysh, would you mind to review the changes?

2018-08-20 13:19 UTC, dixudx requested changes

2018-08-20 13:19 UTC, dixudx commented on pkg/kubectl/cmd/logs_test.go
> -		{
Why removing these tests?

2018-08-20 13:42 UTC, tvieira commented on pkg/kubectl/cmd/logs_test.go
> -		{
@dixudx see @soltysh comments above: https://github.com/kubernetes/kubernetes/pull/65545#discussion_r199498125

2018-08-28 14:52 UTC, soltysh requested changes

2018-08-28 14:52 UTC, soltysh commented on pkg/kubectl/cmd/logs.go
> +			return cmdutil.UsageErrorf(cmd, "%s", logsUsageErrStr)
Don't, just print the error you think is valuable here, eg. `selector is required`, which btw. can be done with `cmd.MarkFlagRequired` function.

2018-08-28 14:52 UTC, soltysh commented
/approve

2018-09-01 08:22 UTC, dixudx approved these changes
/lgtm

2018-09-01 10:33 UTC, merged