cleanup / simplify convert command
kubernetes/kubernetes pull request #65542
Opened 2018-06-27 18:16 UTC by juanvallejo

Cleans up unnecessary pieces from the convert command, simplifyiing
command logic, and readability.

**Release note**:
```release-note
NONE
```

cc @soltysh @deads2k

2018-06-27 20:28 UTC, juanvallejo commented
/retest

2018-07-02 13:38 UTC, juanvallejo commented
cc @soltysh

2018-07-03 22:40 UTC, juanvallejo commented
cc @soltysh

2018-07-06 12:30 UTC, soltysh requested changes
I've left you comments that align this command with the current patterns we're implementing.

2018-07-06 12:30 UTC, soltysh commented on pkg/kubectl/cmd/convert.go
> +	"github.com/golang/glog"
Put a blank space between this and the next one.

2018-07-06 12:30 UTC, soltysh commented on pkg/kubectl/cmd/convert.go
> +	genericclioptions.IOStreams
Move this and `FilenameOptions` to the bottom, like we've started doing recently.

2018-07-06 12:30 UTC, soltysh commented on pkg/kubectl/cmd/convert.go
> +	cmd.Flags().StringVar(&options.OutputVersion, "output-version", "", i18n.T("Output the formatted object with the given group version (for ex: 'extensions/v1beta1').)"))
Use `o` instead of `options`, and wire the default value from `o.OutputVersion` as well.

2018-07-06 12:30 UTC, soltysh commented on pkg/kubectl/cmd/convert.go
>  	o.builder = f.NewBuilder().
Move the builder construction entirely to `Run`, I don't think it's needed here.

2018-07-12 22:12 UTC, juanvallejo commented
@soltysh thanks, comments addressed

cc @deads2k

2018-07-23 18:43 UTC, juanvallejo commented
@soltysh friendly ping

2018-07-27 11:41 UTC, soltysh approved these changes
/lgtm
/approve

2018-07-27 14:24 UTC, merged