kubeadm: Remove the v1alpha1 API
kubernetes/kubernetes pull request #65628
Opened 2018-06-29 10:23 UTC by luxas

**What this PR does / why we need it**:
In v1.10 and earlier, kubeadm only had the `v1alpha1` API.
In v1.11, kubeadm could read `v1alpha1` configs, but only write `v1alpha2` configs
In v1.12, kubeadm can read `v1alpha2` configs, but only write `v1alpha3` or `v1beta1` configs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: https://github.com/kubernetes/kubeadm/issues/911
Depends on: https://github.com/kubernetes/kubernetes/pull/65776

**Special notes for your reviewer**:

**Release note**:

```release-note
[action required] kubeadm: The `v1alpha1` config API has been removed.
Please convert your `v1alpha1` configuration files to `v1alpha2` using the
`kubeadm config migrate` command of kubeadm v1.11.x
```
@kubernetes/sig-cluster-lifecycle-pr-reviews

2018-06-29 10:30 UTC, luxas commented on cmd/kubeadm/app/cmd/config.go
> +			- TODO: kubeadm.k8s.io/v1beta1
Fixed in https://github.com/kubernetes/kubernetes/pull/65629

2018-06-29 10:42 UTC, fabriziopandini approved these changes
Looks great!
/approve
@timothysc I let you give the final lgtm

2018-06-29 15:06 UTC, neolit123 commented
@luxas @fabriziopandini @timothysc 
hm, so if someone tries to build from master somewhere before 1.12 is released and tries to `config migrate` an old `v1alpha1` laying around, it would not work, because `v1alpha1` is removed? he/she would have to move the HEAD before these commits got in or download the 1.11.x release binaries that still have the functionality?

2018-07-03 14:14 UTC, timothysc requested changes
Please extract the generic cleanup work into a separate PR.  It looks like there are separate distinct changes that can/should be reviewed separately.

2018-07-03 17:54 UTC, timothysc approved these changes
/lgtm 

on last two commits but will require a rebase 

/hold

2018-07-04 07:49 UTC, luxas commented
/hold cancel
Rebased on top of https://github.com/kubernetes/kubernetes/pull/65776

2018-07-04 10:29 UTC, merged