Fixed the wrong elasticsearch node counter
kubernetes/kubernetes pull request #65627
Opened 2018-06-29 10:10 UTC by IvanovOleg

**What this PR does / why we need it**:
I am experiencing the nasty bug during the deployment of the elasticsearch-logging statefulset on my custom Kubernetes in Azure (AzureDisk persistant storage). Let's imaging that we want two master nodes which our elasticsearch will try to find during the discovery procedure. Because of the delay between creation of the two nodes (azure disk creation) there will be a situation when only one node exists in the service endpoint list and it will be enough to pass the elasticsearch logging discovery step. Only one node will be written to the elasticsearch.yml, but it expects two. Then Kubernetes will terminate the first pod while the second pod is almost ready (remove that endpoint from service). Then it adds the ip of the second pod to the endpoint and discovery fails as well. This is the endless procedure.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Fixes the wrong elasticsearch node counter

```

2018-06-29 10:28 UTC, idealhack commented
@IvanovOleg Thanks for your work. Please sign the CLA for the email of commit author.

/kind bug
/sig azure
/ok-to-test

2018-06-29 10:32 UTC, idealhack commented
/assign @coffeepac

2018-06-29 10:39 UTC, idealhack requested changes

2018-06-29 10:39 UTC, idealhack commented on cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go
> +	count := os.Getenv("MINIMUM_MASTER_NODES")
`count` should be int

2018-06-29 10:57 UTC, IvanovOleg commented on cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go
> +	count := os.Getenv("MINIMUM_MASTER_NODES")
Fixed

2018-06-29 11:09 UTC, IvanovOleg commented
/retest

2018-06-29 13:36 UTC, IvanovOleg commented
/retest

2018-06-29 15:01 UTC, IvanovOleg commented
Looks like gce tests have been failed not because of my changes. Can anyone approve this PR?

2018-06-29 17:45 UTC, coffeepac commented on cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go
> +	count, _ := strconv.Atoi(os.Getenv("MINIMUM_MASTER_NODES"))
Where is this environment variable being set?   I would imagine it should be done in the elastic search pod spec but I don't see that change.

2018-06-29 17:50 UTC, coffeepac commented on cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go
> +	count, _ := strconv.Atoi(os.Getenv("MINIMUM_MASTER_NODES"))
Nevermind, I see it in `run.sh` now.

2018-06-29 17:53 UTC, coffeepac commented
/lgtm

2018-06-29 17:53 UTC, coffeepac commented
/approve

2018-06-29 17:55 UTC, coffeepac commented
@IvanovOleg PR is ready to go, the failing test isn't required so mergebot should merge with that test failing.  

But, you gotta fix the cncf release.  The first comment on this PR has a link for what to do.  

And thanks for the fix!

2018-06-30 03:30 UTC, idealhack commented
/lgtm
/retest

2018-06-30 09:29 UTC, IvanovOleg commented
/retest

2018-06-30 11:41 UTC, merged

2018-06-30 16:40 UTC, IvanovOleg commented
Which docker image version can I use to get this changes?

2018-07-03 07:53 UTC, idealhack commented
@IvanovOleg Maybe you could ask that on slack or build your own image?

2018-07-05 07:07 UTC, IvanovOleg commented
@coffeepac As far as I have understood, another PR is required for this, right? Current version of this image is 6.2.4 according to the elasticsearch version (6.2.4 is the latest in 6.2.*). Looks like the only way is to switch to the 6.3.0 to match elasticsearch versions. Or we can increase our image version to 6.2.5 and don't keep the match (use the same original es image). What do you think?

2018-07-06 16:04 UTC, coffeepac commented
Yes, another PR is required.

There shouldn't be a strict relationship between the k8s es version and upstream es.   

This is a bug fix so moving k8s es image to 6.2.5 is appropriate.