wire PrintFlags through rollout commands
kubernetes/kubernetes pull request #65880
Opened 2018-07-05 20:20 UTC by juanvallejo

Binds PrintFlags to rollout commands.
Adds tests ensuring --template printing is supported by rollout cmds.

Fixes https://github.com/kubernetes/kubernetes/issues/65778

**Release note**:
```release-note
NONE
```

cc @soltysh @deads2k

2018-07-05 22:57 UTC, neolit123 commented
not sure if `pull-kubernetes-integration` is flaking here or if there is an error with `template-output.sh`.
/test pull-kubernetes-integration

/cc @kubernetes/sig-cli-pr-reviews

2018-07-06 13:36 UTC, soltysh requested changes
A few nits...

2018-07-06 13:36 UTC, soltysh commented on pkg/kubectl/cmd/rollout/rollout.go
> +	cmd.AddCommand(NewCmdRolloutHistory(f, streams))
That's unfortunate, do we have more like these?

2018-07-06 13:36 UTC, soltysh commented on pkg/kubectl/cmd/rollout/rollout_history.go
> +	if o.Namespace, o.NamespaceRequired, err = f.ToRawKubeConfigLoader().Namespace(); err != nil {
s/`NamepaceRequired`/`ExplicitNamespace`

2018-07-06 13:36 UTC, soltysh commented on pkg/kubectl/cmd/rollout/rollout_resume.go
> +	o.Namespace, o.NamespaceRequired, err = f.ToRawKubeConfigLoader().Namespace()
`ExplicitNamespace`

2018-07-06 13:36 UTC, soltysh commented on pkg/kubectl/cmd/rollout/rollout_undo.go
> +	if o.Namespace, o.NamespaceRequired, err = f.ToRawKubeConfigLoader().Namespace(); err != nil {
`ExplicitNamespace`

2018-07-06 13:55 UTC, soltysh approved these changes
/lgtm
/approve

2018-07-06 22:24 UTC, juanvallejo commented
cc @deads2k for re-lgtm

2018-07-09 14:58 UTC, deads2k commented
just additional tests

/lgtm

2018-07-09 15:08 UTC, neolit123 commented
/test pull-kubernetes-e2e-gce

2018-07-09 19:16 UTC, merged