[WIP] Add user assigned MSI support
kubernetes/kubernetes pull request #66180
Opened 2018-07-13 21:14 UTC by kkmsft

**What this PR does / why we need it**:
Adds the support for generating tokens via user assigned MSI. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # 

**Special notes for your reviewer**:

**Release note**:

```release-note
Add support for using User Assigned MSI (https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview) with Kubernetes cluster on Azure.
```

2018-07-13 21:15 UTC, kkmsft commented
cc @khenidak

2018-07-16 02:55 UTC, feiskyer commented on pkg/cloudprovider/providers/azure/auth/azure_auth.go
> +	UserAssignedMSI string `json:"userAssignedMSI" yaml:"userAssignedMSI"`
use `UserAssignedIdentity` instead?  UserAssignedMSI seems overlapping with UseManagedIdentityExtension.

2018-07-16 02:58 UTC, feiskyer commented on pkg/cloudprovider/providers/azure/auth/azure_auth.go
> +	UserAssignedMSI string `json:"userAssignedMSI" yaml:"userAssignedMSI"`
use UserAssignedIdentityID for clear? UserAssignedMSI seems overlapping with UseManagedIdentityExtension.

2018-07-17 19:02 UTC, khenidak requested changes

2018-07-17 19:02 UTC, khenidak commented on pkg/cloudprovider/providers/azure/auth/azure_auth.go
> +			glog.V(2).Info("azure: using User Assigned MSI to retrieve access token")
nit: this is a bit too high verbosity. most clusters run with `2` -- can we make it `4`?

2018-07-17 19:02 UTC, khenidak commented on pkg/cloudprovider/providers/azure/auth/azure_auth.go
> +		glog.V(2).Info("azure: using System Assigned MSI to retrieve access token")
same as above. let us use `4`

2018-07-17 19:03 UTC, khenidak commented
Let us remove the `wip` tag and prep this for merge. Thanks a lot !

2018-07-20 16:01 UTC, khenidak commented
/approve

2018-07-20 16:55 UTC, khenidak commented
/retest

2018-07-23 02:11 UTC, feiskyer commented
/ok-to-test

2018-07-23 02:12 UTC, feiskyer reviewed
/lgtm

2018-07-23 05:37 UTC, kkmsft commented
/test pull-kubernetes-e2e-gce

2018-07-23 19:32 UTC, merged

2018-07-25 21:01 UTC, marpaia commented
/sig azure