update attach to use external objs
kubernetes/kubernetes pull request #66519
Opened 2018-07-23 20:44 UTC by juanvallejo

**Release note**:
```release-note
NONE
```

Updates attach command to use external versions.

cc @deads2k @soltysh

2018-07-31 02:17 UTC, juanvallejo commented
/retest

2018-07-31 18:30 UTC, juanvallejo commented
/retest

2018-08-01 10:20 UTC, soltysh requested changes
I left you some comments, also please squash that last commit into the first one.

2018-08-01 10:20 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> +	if len(args) == 0 {
You can use `o.Resources`, and don't pass `args` here at all. Maybe renaming then to `Args` would make it more obvious.

2018-08-01 10:20 UTC, soltysh commented on pkg/kubectl/cmd/attach.go
> +		o.ErrOut = nil
I'm hesitant about this action. We're modifying global `IOStreams` object. I'd prefer we make a local copy of `ErrOut` and pass that to `AttachFunc` as needed.

2018-08-01 10:20 UTC, soltysh commented on pkg/kubectl/cmd/run.go
>  	"k8s.io/client-go/dynamic"
Move this import to all k8s imports.

2018-08-01 10:20 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/attachablepodforobject.go
> +	coreclient "k8s.io/client-go/kubernetes/typed/core/v1"
`corev1client` is the preferred alias.

2018-08-01 10:20 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/helpers.go
> -		externalPod := &v1.Pod{}
One more down :+1:

2018-08-01 10:20 UTC, soltysh commented on pkg/kubectl/cmd/logs.go
> +func (o LogsOptions) Validate(args []string) error {
If you need pass `args` through `LogsOptions` struct. `Validate` should not accept input parameters.

2018-08-01 14:45 UTC, juanvallejo commented
@soltysh thanks, comments addressed

2018-08-01 15:02 UTC, soltysh approved these changes
/lgtm
/approve

2018-08-01 22:52 UTC, merged