Integration test for CronJob
kubernetes/kubernetes pull request #66937
Opened 2018-08-02 21:33 UTC by mortent

**What this PR does / why we need it**: There are no integration tests covering CronJob. This adds a test with the basic use case and we can add additional tests later.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2018-08-02 23:07 UTC, wgliang commented
/ok-to-test

2018-08-03 00:46 UTC, neolit123 commented
/sig testing

@mortent please add a release note in the first message under `Release note:` explaining what this change is - e.g. `test/integration: add a basic test for covering CronJobs`

2018-08-06 15:49 UTC, mortent commented
/assign @MrHohn

2018-08-06 17:10 UTC, MrHohn commented
Would be great to have folks from @kubernetes/sig-apps-pr-reviews to review.

2018-08-28 13:51 UTC, soltysh requested changes
I left you some comments.

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/cronjob_test.go
> +Copyright 2017 The Kubernetes Authors.
2018

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/cronjob_test.go
> +	"github.com/golang/glog"
Split the imports into following groups:
- builtin
- else
- all of kubernetes

See other files for how it's done.

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/cronjob_test.go
> +func setupGarbageCollector(t *testing.T, config rest.Config, clientSet clientset.Interface, informerset informers.SharedInformerFactory, stopCh chan struct{}) {
Why we need to setup GC for this test? From my pov this only complicates this test code.

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/cronjob_test.go
> +			glog.Info(string(bytes))
Remove this debug print, not needed here.

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/cronjob_test.go
> +		jobs := informerSet.Batch().V1().Jobs().Informer().GetIndexer().List()
Since you are listing jobs, why not just using regular client and list them each time, any particular reason for informer here?

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/cronjob_test.go
> +		pods := informerSet.Core().V1().Pods().Informer().GetIndexer().List()
Same here, wrt informers vs list?

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/cronjob_test.go
> +			glog.Info(string(bytes))
Ditto - remove.

2018-08-28 13:51 UTC, soltysh commented on test/integration/cronjob/main_test.go
> +Copyright 2017 The Kubernetes Authors.
2018

2018-09-03 18:59 UTC, mortent commented
/retest

2018-09-04 10:32 UTC, soltysh approved these changes
/lgtm
/approve

2018-09-24 20:19 UTC, merged