Do not count nodelost pods as unready in HPA controller
kubernetes/kubernetes pull request #67067
Opened 2018-08-07 08:42 UTC by moonek

**What this PR does / why we need it**:
Currently, when performing a scale up, any nodelost pods will be treated as unready.
Unready pods are treated as if they had 0% utilization which will slow down or even block scale up.
If the node is not ready forever, nodelost pod is counted as unready pods to prevent scale up.

Nodelost pods after scale up occurs immediately on another node by pod-eviction.
In this state, the newly created pod is counted in the replicas.

However, if the load occurs after nodelost pods is created, the nodelost pods is considered unready pod and does not scale up.
This is a different replicas result than the above situation.
The scale up requirement will depend on the order in which the nodelost occurs.

After this change, consider nodelost pods as computations like failed pods.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/62845

**Special notes for your reviewer**:

**Release note**:

```release-note
Stop counting nodelost pods as unready in HPA controller to avoid nodelost pods incorrectly affecting scale up replica count calculation.
```

2018-08-07 09:14 UTC, moonek commented
/assign @directxman12

2018-08-07 16:06 UTC, DirectXMan12 commented
@kubernetes/sig-api-machinery-pr-reviews

2018-08-07 19:55 UTC, DirectXMan12 commented
@kubernetes/sig-autoscaling-pr-reviews 

EDIT: the right SIG, sorry for the mistype

2018-08-08 01:25 UTC, MHBauer commented
/ok-to-test

2018-08-08 02:46 UTC, moonek commented
How can I pass the test?
My commit is not a breaking change.

2018-08-08 05:41 UTC, moonek commented
/retest

2018-08-08 08:15 UTC, moonek commented
How do I pass `pull-kubernetes-e2e-kops-aws`? I don't think this is a problem I can solve.

2018-08-08 13:13 UTC, moonek commented
/retest

2018-08-09 02:59 UTC, moonek commented
@MaciekPytel @jszczepkowski @DirectXMan12 ptal, this issue has been reported as a serious issue in the node failure test for production-grade k8s use.

2018-08-09 06:30 UTC, moonek commented
test code added.

2018-08-09 09:14 UTC, moonek commented
/retest

2018-08-09 20:11 UTC, fedebongio commented
/remove-sig api-machinery

2018-08-13 19:01 UTC, DirectXMan12 commented
The code looks fine here, but I want to clarify what happened.  AIUI, when the pods are set as nodelost, they should be deleted shortly thereafter by the node controller, so we shouldn't have an issue with them hanging around forever.    Perhaps someone from @kubernetes/sig-node-bugs can weigh in?

2018-08-22 05:35 UTC, moonek commented
@DirectXMan12 I want to know how the review is currently in progress. I want to avoid rebase.

2018-08-22 21:45 UTC, DirectXMan12 commented
@moonek sorry this took so long to get back to you.  I read over the issues you posted, and discussed a bit with some folks, and I'm hesitant to merge this as-is.

My concerns are:

If your cluster is in a node-lost state, something's gone wrong, and you should be taking admin action to get it back to normal, and once it gets back to a normal cluster state, the HPA will kick in normally.  Nodes probably shouldn't be left "lost" forever, but we probably also should be more proactive (as you're suggesting).

The replicaset controller considers pods to be "deleted" as soon as the `deletionTimestamp` is set.  We could mirror the behavior of the RS controller, but that means we're coding to the behavior of a specific scalable.  For instance, the StatefulSet controller re-uses pod names, so it doesn't do that, AFAIK.

However, I could see it making some amount of sense to consider "soft-deleted" pods in general to be deleted -- their metrics should *probably* not matter for scaling purposes, since they'll be gone "soon", whether they're nodelost or just normally delete.  So, the way I would move forward with this PR would be to make it not specific to nodelost, and just ignore metrics from soft-deleted pods in general. 

@kubernetes/sig-autoscaling-bugs @kubernetes/sig-node-pr-reviews anyone have any objections?

2018-08-23 08:55 UTC, moonek commented
@DirectXMan12  I have not been able to find an answer from the docs or the community about whether this is normal or bug, so I've been thinking a lot.

And I thought of this as a bug, and I wrote down my idea that it should be fixed.

a) This is a fundamental question. 
   Is it preferable to count the unused pods(removed from endpoint) in HPA?
   Is it correct that the definition of a `nodelost pod` has the meaning of a pod that is `unready`?

b) This is a question about consistency.
   The order of node failures results in different HPA results for the same load.
   scenario 1) initial pod: 2 -> constant load -> scaled pod: 3 -> node failure -> pod eviction -> final pod: 3
   scenario 2) initial pod: 2 -> node failure -> pod eviction -> pod: 2 -> constant load -> final pod: 2 (not scaled)

c) Problems with service continuity.
   The pods created on the faulty node can be pods that have 20~30% load of the total service without luck.   
   There is a fear that the normal service can not be performed due to a concentrated load on the remaining pods.
   **Despite the fact that the other normal nodes have plenty of resources.**

d) This is related to the purpose of the HPA.
   Why do we set up HPA?
   I think it is to make a complete automation system.
   Should cluster admin intervene to recover the node failure or force the service to be stabilized by forcibly deleting the unknown pod?
   How fast can a person be aware of a failure node and take action than the HPA algorithm?
   
e) Does soft-deleted mean `Terminating` state pod by deletion?
   There is no value in `status.reason` for such a pod.

f) `StatefulSet` is not scaled regardless of this PR because `StatefulSet` re-uses pod names as you know.
   The result of Statefulset HPA is the same as before PR. (both `OrderedReady` and `Parallel` podManagementPolicies)
   
g) This is a request.
   If this PR is not approved, please let us know about this issue in the official HPA documentation.
   A guide to why the nodelost pod should be counted by the HPA algorithm in case of a node failure and what action should be taken is required.
   It's easy to think of this as a bug because there is no official explanation.  

   
@kubernetes/sig-autoscaling-bugs @kubernetes/sig-node-pr-reviews I would like to receive any comments.

2018-08-23 12:17 UTC, moonek commented
Good!! I will change this PR based on `deletionTimestamp` during today.

2018-08-23 13:50 UTC, moonek commented
@DirectXMan12 please take a look. I modified the source, title, and description more simply. I quoted your advice.

2018-08-23 14:35 UTC, moonek commented
/retest

2018-08-23 15:12 UTC, moonek commented
/retest

2018-08-23 18:15 UTC, DirectXMan12 commented
looks good to me.  last thing we need is a unit test that sets deletion timestamp and confirms it doesn't factor, and then I'll approve this.  If you need help with the HPA unit tests, feel free to reach out to me on Kubernetes slack (I'm @directxman12 there as well).  Thanks for your patience and raising the issue! :-)

2018-08-24 05:17 UTC, moonek commented
@DirectXMan12 I added a unit test and re-committed it. I look forward to approval. :)

2018-08-25 04:57 UTC, moonek commented
/remove-sig api-machinery
/remove-sig cli
/remove-sig cloud-provider
/remove-sig cluster-lifecycle
/remove-sig release
/remove-sig scheduling

2018-08-25 04:58 UTC, moonek commented
/remove-area apiserver

2018-08-25 06:26 UTC, moonek commented
/retest

2018-08-27 16:56 UTC, moonek commented
@DirectXMan12 Is it difficult for this fix to be merged into 1.12?

2018-08-27 20:59 UTC, DirectXMan12 commented
@moonek I'd like to get it merged for 1.12.  I'm planning on doing one last review pass tomorrow, then approving it.

2018-08-28 14:02 UTC, DirectXMan12 requested changes
minor test-related change, otherwise this is good to go

2018-08-28 14:02 UTC, DirectXMan12 commented on pkg/controller/podautoscaler/horizontal_test.go
> +			} else {
you shouldn't be creating the entire object in the `if-else`, just setting the `DeletionTimestamp`:

```go
pod = v1.Pod{...}
if deletionTimestamp {
  pod.DeletionTimestamp = &metav1.Time{Time: time.Now()}
}
```

2018-08-28 14:02 UTC, DirectXMan12 commented on pkg/controller/podautoscaler/replica_calculator_test.go
> +			if podDeletionTimestamp == false {
ditto here

2018-08-28 16:38 UTC, moonek commented
@DirectXMan12 I was also concerned about that part. I modified and re-committed.

2018-08-28 17:05 UTC, DirectXMan12 commented
/lgtm
/approve

2018-08-28 17:33 UTC, DirectXMan12 commented
/retest

2018-08-28 18:27 UTC, moonek commented
/retest

2018-08-28 22:08 UTC, merged