begin a test framework so we can collect exhaustive test vectors
kubernetes/kubernetes pull request #67098
Opened 2018-08-07 22:01 UTC by lavalamp

It seems like we don't have something like this. I haven't done any hard work here yet--perhaps if we commit this we can do that in parallel?

2018-08-09 12:26 UTC, apelisse commented on staging/src/k8s.io/smd/README.md
> +# Structured Merge and Diff
Can we change the name of the package? `mergediff`? Something that is more easily to guess if you've never seen the full name first.

2018-08-09 18:20 UTC, kwiesmueller requested changes

2018-08-13 19:43 UTC, jennybuckley commented on staging/src/k8s.io/smd/testvectors/listordering.go
> +			LiveObject: YAMLObject(`
Should probably be "NewObject" here

2018-08-15 21:33 UTC, lavalamp commented
Update pushed, addressed comments and made it a lot better in other ways. PTAL

2018-08-22 20:01 UTC, lavalamp commented
I'm trying to figure out if this really must go in staging or if I can put it in its own repo. I think it depends on what type I use to represent a value and an OpenAPI schema--will those types come from k/k or staging dir?

Schema I suspect not. Value might plausibly be unstructured. Need to look into that.

2018-08-22 20:09 UTC, lavalamp commented
Looks like today's unstructured offers the ability to extract its contents in the form of map[string]interface{}, so I can be interoperable without actually needing to take on a dependency.

I'll (sigh) look into getting a separate repo for this.

2018-09-07 23:43 UTC, lavalamp commented
Moved to https://github.com/kubernetes-sigs/structured-merge-diff/pull/2

2018-09-07 23:43 UTC, closed without merging