fix some type of openstack_volumes.go
kubernetes/kubernetes pull request #67291
Opened 2018-08-11 02:44 UTC by jianglingxia

**What this PR does / why we need it**:
fix some type of openstack_volumes.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/assign @dims 
**Release note**:

```release-note
NONE
```

2018-08-12 22:16 UTC, neolit123 commented
/sig openstack

2018-08-13 08:10 UTC, jianglingxia commented
/cc @FengyunPan2 
thanks

2018-08-24 12:54 UTC, dims commented
/assign @NickrenREN 
/assign @FengyunPan2 
/unassign

2018-08-24 13:15 UTC, NickrenREN requested changes

2018-08-24 13:15 UTC, NickrenREN commented on pkg/cloudprovider/providers/openstack/openstack_volumes.go
> +		devicePath = os.getDevicePathFromInstanceMetadata(volumeID)
We want to get device path from `id` and if necessary from `metadata service`, if no one succeeds, then log error message. I don't think we need to do this change.

2018-10-02 01:29 UTC, dims commented
/close 

per last comment from @NickrenREN

2018-10-02 01:29 UTC, closed without merging