fix some minor mistakes in e2e
kubernetes/kubernetes pull request #67320
Opened 2018-08-13 02:42 UTC by hanxiaoshuai

**What this PR does / why we need it**:
fix some minor mistakes in e2e
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-08-13 05:06 UTC, dixudx approved these changes
/lgtm

2018-08-13 09:06 UTC, nikhita commented on test/e2e/instrumentation/monitoring/custom_metrics_stackdriver.go
> +		framework.Failf("Failed to create RoleBindings: %s", err)
`%v` instead of `%s`?

2018-08-13 09:07 UTC, nikhita commented
/assign @fabxc

2018-08-13 09:12 UTC, hanxiaoshuai commented on test/e2e/instrumentation/monitoring/custom_metrics_stackdriver.go
> +		framework.Failf("Failed to create RoleBindings: %s", err)
Done

2018-08-13 09:14 UTC, nikhita commented
@hanxiaoshuai thanks for fixing that so quick! :rocket: 

/lgtm

2018-08-13 16:58 UTC, spiffxp requested changes
Thanks for the fix!  The error message needs a quick change

2018-08-13 16:58 UTC, spiffxp commented on test/e2e/instrumentation/monitoring/custom_metrics_stackdriver.go
> +		framework.Failf("Failed to create RoleBindings: %v", err)
nit: should be ClusterRoleBindings instead of RoleBindings

2018-08-13 16:58 UTC, spiffxp commented on test/e2e/instrumentation/monitoring/custom_metrics_stackdriver.go
> +		framework.Failf("Failed to create RoleBindings: %v", err)
here too

2018-08-14 01:52 UTC, hanxiaoshuai commented
/test pull-kubernetes-integration

2018-08-14 02:42 UTC, hanxiaoshuai commented
/test pull-kubernetes-e2e-kops-aws

2018-08-14 03:49 UTC, hanxiaoshuai commented
/test pull-kubernetes-e2e-kops-aws

2018-08-14 08:59 UTC, nikhita commented
/lgtm

@hanxiaoshuai the kops test is completely red, so I don't think retesting will help for sometime. :(

2018-08-14 09:06 UTC, hanxiaoshuai commented
@nikhita Thanks

2018-08-14 18:18 UTC, krzyzacy commented
/retest

2018-08-14 21:48 UTC, spiffxp commented
/approve

2018-08-14 21:48 UTC, spiffxp approved these changes

2018-08-15 07:07 UTC, merged