Introduce KUBELET_CRIRUNTIME_ARGS to kubeadm drop-in
kubernetes/kubernetes pull request #67391
Opened 2018-08-14 13:44 UTC by sysrich

**What this PR does / why we need it**:
This PR introduces a KUBELET_CRIRUNTIME_ARGS parameter to be provided by a new (optional) /etc/kubernetes/runtime.conf configuration file.

The intention of the file is to give users, but also distributions, an easy place for defining the CRI runtime to be used by kubernetes

Instead of the current documentation, which advocates manually modifying KUBELET_EXTRA_ARGS, this approach will mean distributions (like openSUSE Kubic) can drop in a configuration file for cri-o, docker, or other runtime of their choice, potentially also making it a user choice from distribution packages.

Currently to be able to give such choice it often requires the installation of multiple runtimes alongside each other, to ensure that at least the 'default' is present..which is wasteful for users at scale who don't want to be filling up their hard disks with redundant CRI runtime binaries.

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

The runtime.conf file is not included by the kubernetes rpm/deb packages because the expectation it would be provided by the package providing the runtime, or a supplementary configuration package (eg. kubernetes-kubeadm-crio in openSUSE)

**Special notes for your reviewer**: This is my first PR, please be gentle :)

**Release note**:
```release-note
kubeadm now reads a `KUBELET_CRIRUNTIME_ARGS` parameter from `/etc/kubernetes/runtime.conf`. Users or distribution packagers can use this file to define which CRI runtime is used by kubeadm by populating the parameter with values such as `--container-runtime=remote --container-runtime-endpoint=$RUNTIME_ENDPOINT`. Distributions should package `/etc/kubernetes/runtime.conf` with or alongside their chosen CRI runtime(s), containing appropriate parameters.
```

2018-08-14 13:54 UTC, sysrich commented
Hey @k8s-ci-robot , I work for SUSE, and we signed the CLA, but my account wasn't associated properly - go check again please :)

2018-08-15 11:45 UTC, sysrich commented
/area kubeadm
/kind enhancement
@kubernetes/sig-cluster-lifecycle-pr-reviews

2018-08-16 13:15 UTC, neolit123 commented
/cc @kad 
/cc @bart0sh 
/cc @fabriziopandini 

thanks for the PR
@sysrich

2018-08-16 13:40 UTC, kad commented on build/debs/10-kubeadm.conf
> +EnvironmentFile=-/etc/kubernetes/runtime.conf
I would put more variables/arguments into file above. No need to create one more file.

2018-08-16 13:41 UTC, spiffxp commented
/ok-to-test

2018-08-16 13:51 UTC, neolit123 commented on build/debs/10-kubeadm.conf
> +EnvironmentFile=-/etc/kubernetes/runtime.conf
part of @sysrich 's suggestion seems to be:

> distributions (like openSUSE Kubic) can drop in a configuration file for cri-o, docker, or other runtime of their choice, potentially also making it a user choice from distribution packages.

@sysrich did you consider distributing (somehow) custom flags in `/etc/kubernetes/runtime.conf` instead?

2018-08-16 14:05 UTC, kad commented on build/debs/10-kubeadm.conf
> +EnvironmentFile=-/etc/kubernetes/runtime.conf
The question is Kubic is going to use directly those k8s packages as-is or make their own ?

2018-08-16 14:36 UTC, fabriziopandini commented
@sysrich Thank for your PR!
I have some background questions about the goal of your PR.

Since you are modifying kubeadm, I assume that 
- you will use kubeadm for creating your cluster/joining nodes
- you already know that kubeadm allows customisation of kubelet CRI via the kubeadm config file (that is translated to the `kubeadm-flags.env` passed to kubelet, see relevant code [here](https://github.com/kubernetes/kubernetes/blob/2744f264f5057be090406a782319697c9fb5a1b6/cmd/kubeadm/app/phases/kubelet/flags.go#L74)).

Could you kindly explain to ma what is the goal of your PR/what your PR add to the existing kubeadm behaviour?

2018-08-16 17:32 UTC, sysrich commented on build/debs/10-kubeadm.conf
> +EnvironmentFile=-/etc/kubernetes/runtime.conf
> @sysrich did you consider distributing (somehow) custom flags in /etc/default/kubelet instead?

@neolit123 @kad I did consider that option, but it is not viable. Consider the following scenario - Kubic contains packages for both CRI-O and Docker. 

We want a situation where if kubeadm is installed AND if CRI-O is installed then CRI-O is configured OR if CRI-O is not installed and Docker is installed, then Docker is configured.

This is best handled by having packages dependencies - only your package manager is going to easily know which runtime is installed plus whether or not kubeadm is installed (and therefore to include the config file which configures the runtime in kubeadm)

Therefore I strongly feel this config file SHOULD be separate from either `/etc/default/kubelet` (aka /etc/sysconfig/kubelet on openSUSE) or the kubeadm config file.

Those should be kept for users to set exactly what they want, the way they want, and how they want - packages should generally avoid touching user configuration files like the plague

> The question is Kubic is going to use directly those k8s packages as-is or make their own ?

Kubic, like all openSUSE projects, wants to keep as close to upstream as possible. Hence this PR. I already have packages carrying this patch that have been tested and worked, but I don't want to merge them into the main openSUSE codebase without consultation with the rest of you, like we're doing now :)

After all, if you persuade me to do it differently (a strong possibility) then I'll just have to rework everything anyway.. :)

2018-08-16 17:38 UTC, sysrich commented
@fabriziopandini 

> Thank you for your first k8s contribution

Thanks!

> you will use kubeadm for creating your cluster/joining nodes

That's the plan, yes. More context here: https://kubic.opensuse.org/blog/2018-08-09-newdirection/

Generally speaking I want to keep any openSUSE-specific customisation of kubeadm to a minimum. 

But we do have a pretty strong requirement to be able to support both CRI-O and Docker, and yet we want kubeadm to be configured to use whichever one the user has installed, with minimal user interaction required.

This is the first step in that direction (the next will be figuring out a nice way of `kubectl init` `join` and `reset` automatically knowing what to do about `--cri-socket` when Docker is not being used)

> you already considered using customisation of kubelet CRI via the kubeadm config file (that is translated to the kubeadm-flags.env passed to kubelet, see relevant code here).

> Could you kindly help me in understanding what doses work in the existing kubeadm behaviour (for CRI customization)?

[I think my comment to kad and neolit123 covers my answer to these questions](https://github.com/kubernetes/kubernetes/pull/67391#discussion_r210679753), so I won't repeat it here

But if I need to explain further, I'm more than happy to do so. I'm happy to keep talking here, or if things aren't cleared up by next Tues/Wed I intend to be in both the sig meeting and office hours.

2018-08-17 06:39 UTC, fabriziopandini commented
@sysrich I'm really happy to read the kubic news! 
Looking forward for the next sig-meeting!

2018-08-17 12:54 UTC, kad commented
@sysrich I think direction of this patch is not completely right. 
As @fabriziopandini mentioned, we have code in kubeadm which will put correct CRI options for kubelet into `kubeadm-flags.env`. Having two places where those options are defined (one by kubeadm code, one by one more file that comes from another package) is a path to the conflicting values.
I'd suggest that we better thing about way of reliably detect, do we have any CRI implementation running and available, and if not, fallback/check that Docker is available. If neither detected and validated -> error.

2018-08-20 05:38 UTC, dixudx requested changes

2018-08-20 05:38 UTC, dixudx commented on build/debs/10-kubeadm.conf
> +EnvironmentFile=-/etc/kubernetes/runtime.conf
Actually we could use current `/etc/default/kubelet` (debian) or `/etc/sysconfig/kubelet` (rpm). No need to have another new file.

2018-08-21 16:46 UTC, sysrich commented
Closing - immediate needs for openSUSE Kubic will be addressed by playing with /etc/sysconfig/kublet as suggested

But long term I'd like us to look at a more structured model for handling distro-provided config, user-provided config, and user-provided runtime switches. 

After the discussions on this topic in today's SIG-cluster-lifecycle meeting you can expect a long wordy Issue from me as soon as I get all my ideas down in some coherent prose.

Thanks all for making my first PR an enjoyable one :)

2018-08-21 16:46 UTC, closed without merging