Add e2e Test Filename:Linenumber and Description to User-Agent
kubernetes/kubernetes pull request #67550
Opened 2018-08-17 22:50 UTC by hh

This PR appends detail e2e test line number and test details to the User-Agent.
It's needed for https://github.com/kubernetes/community/pull/2363 and Conformance Data gathering.

```
e2e.test/v1.12.0 (linux/amd64) kubernetes/94c2c6c -- k8s.io/kubernetes/test/e2e/kubectl/portforward.go:496 -- [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects
e2e.test/v1.12.0 (linux/amd64) kubernetes/94c2c6c -- k8s.io/kubernetes/test/e2e/network/dns.go:158 -- [sig-network] DNS should provide DNS for ExternalName services
e2e.test/v1.12.0 (linux/amd64) kubernetes/94c2c6c -- /home/hh/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:710 -- [sig-cli] Kubectl client [k8s.io] Kubectl cluster-info should check if Kubernetes master services is included in cluster-info  [Conformance]
e2e.test/v1.12.0 (linux/amd64) kubernetes/94c2c6c -- /home/hh/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go:562 -- [sig-storage] PersistentVolumes-local  StatefulSet with pod affinity should use volumes on one node when pod has affinity
```

2018-08-20 14:27 UTC, hh commented
For tests that are not conformance tests, the line numbers show up fine:

```
k8s.io/kubernetes/test/e2e/kubectl/portforward.go:496 -- [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects
k8s.io/kubernetes/test/e2e/network/dns.go:158 -- [sig-network] DNS should provide DNS for ExternalName services
k8s.io/kubernetes/test/e2e/framework/framework.go:710 -- [sig-cli] Kubectl client [k8s.io] Kubectl cluster-info should check if Kubernetes master services is included in cluster-info  [Conformance]
k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go:562 -- [sig-storage] PersistentVolumes-local  StatefulSet with pod affinity should use volumes on one node when pod has affinity
```

However when we use the ConformanceIt() wrapper, we lose this context, as the source is always 'k8s.io/kubernetes/test/e2e/framework/framework.go:757' :

2018-08-21 18:51 UTC, spiffxp commented on test/e2e/framework/framework.go
> +				testDesc.LineNumber,
I'm not sure how interesting or useful it is to go as low level as file:line if we have access to the test description

2018-08-21 18:53 UTC, spiffxp commented
/release-note-none
/hold
for comment... I'm interested in getting this merged but I think I'd prefer removing the additional complexity of line numbers / files

2018-08-21 18:54 UTC, spiffxp commented
/approve
but no /lgtm due to above

2018-08-21 18:58 UTC, liggitt commented
> for comment... I'm interested in getting this merged but I think I'd prefer removing the additional complexity of line numbers / files

agree. api call by test seems useful

2018-08-21 19:08 UTC, hh commented
I removed file / line numbers.... henceforth tests will be known by `strings.Join(CurrentGinkoTestDesctription.ComponentTexts, " ")`

2018-08-21 19:10 UTC, dims commented
LGTM, please squash the commits and fix the description to drop the Filename:Linenumber and we should be good.

2018-08-21 19:59 UTC, hh commented
Squashed and pushed.

2018-08-21 20:27 UTC, mikedanese commented on test/e2e/framework/framework.go
> +		case len(testDesc.ComponentTexts) > 0:
use an if

2018-08-21 20:58 UTC, timothysc requested changes

2018-08-21 20:58 UTC, timothysc commented on test/e2e/framework/framework.go
> +		case len(testDesc.ComponentTexts) > 0:
can you just switch this to an if statement?  The switch case for a case of one makes little sense imo.

2018-08-22 02:12 UTC, spiffxp commented
/lgtm

2018-08-22 03:17 UTC, spiffxp commented
/test pull-kubernetes-kubemark-e2e-gce-big
submit queue claims this test is failing but I see all green here https://k8s-gubernator.appspot.com/pr/67550

2018-08-22 03:17 UTC, spiffxp commented
/hold cancel

2018-08-22 06:21 UTC, merged