remove deprecated option --show-all
kubernetes/kubernetes pull request #67746
Opened 2018-08-23 03:31 UTC by WanLinghao

show-all option has been deprecated in v1.10. I think it's time to clean it.
ref:https://github.com/kubernetes/kubernetes/pull/60210
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-08-23 03:31 UTC, WanLinghao commented
@deads2k PTAL

2018-08-23 06:42 UTC, dixudx approved these changes
/lgtm

2018-08-24 01:13 UTC, WanLinghao commented
/test pull-kubernetes-integration

2018-08-27 10:01 UTC, WanLinghao commented
friendly ping @deads2k

2018-08-27 14:00 UTC, dims commented
@deads2k we should try to do this in 1.12?

/milestone v1.12

2018-09-05 18:47 UTC, spiffxp commented
If this was a GA flag, it needs to stick around until 1.13 
https://kubernetes.io/docs/reference/using-api/deprecation-policy/

2018-09-17 22:32 UTC, tpepper commented
SIG leads, can we "/milestone clear" this?  It's much too late in the cycle now as we're truly working to only merge a few last critical bug fixes.

2018-09-17 22:45 UTC, spiffxp commented
/milestone clear
SIG Testing chair, I'm clearing as I don't think this should go in until next release per our deprecation policy

2018-10-25 04:32 UTC, gkop commented
Hey all - curious now what is the idiomatic way to filter out terminated pods once this patch is in? (IE a replacement for `kubectl get pods --show-all=false`, cf. https://github.com/kubernetes/kubectl/issues/537) Thank you!

2019-02-03 03:08 UTC, WanLinghao commented
@juanvallejo I think it's time to remove this code now

2019-02-04 15:49 UTC, soltysh requested changes
Please rebase since part of the commit is not relevant, we'll pick up the other change only.

2019-02-04 15:49 UTC, soltysh commented on pkg/kubectl/cmd/get/get_flags.go
> -	cmd.Flags().BoolP("show-all", "a", true, "When printing, show all resources (default show all pods including terminated one.)")
This was removed in https://github.com/kubernetes/kubernetes/pull/69255

2019-02-11 01:23 UTC, WanLinghao commented
@soltysh  comments addressed, PTAL

2019-02-12 20:29 UTC, soltysh approved these changes
/lgtm
/approve

2019-02-13 02:45 UTC, merged