Replace fmt.Errorf with errors.New when there are no values to format…
kubernetes/kubernetes pull request #67740
Opened 2018-08-23 01:38 UTC by natemurthy

The `fmt.Errorf` function is just a convenience wrapper around `errors.New`. If you just want to create an error string with no interpolation why not just use the latter?

2018-08-23 05:36 UTC, neolit123 commented
the `fmt.Errorf` -> `errors.New` change is not bad it has performance implications.
but the PR touches other areas especially in kubeadm, please rebase your commits against the latest master.

2018-08-23 05:37 UTC, neolit123 commented
/release-note-none

2018-08-23 15:58 UTC, natemurthy commented
@neolit123 Rebased. Any suggestions as to what I should put for release note?

Btw, this is approximately how many other `fmt.Errorf` expressions I could replace with `errors.New`:
```
nmurthy:kubernetes% rg "return fmt.Errorf\(\"(.*?)\"\)" | wc -l
    1692
```

2018-08-23 16:36 UTC, neolit123 commented
> @neolit123 Rebased. 

thanks but it seems that it still touches other code?

> Any suggestions as to what I should put for release note?

given this isn't user facing there is no need for a release note.

> nmurthy:kubernetes% rg "return fmt.Errorf\(\"(.*?)\"\)" | wc -l
    1692

these are bug numbers, but the problem is that if you submit it all in as a single PR it might take _a while_ before it's merged, unless a top level approver comes by.

2018-08-24 01:44 UTC, k82cn commented
/ok-to-test

2018-08-24 01:52 UTC, neolit123 requested changes
/hold
to clarify - please remove code changes unrelated to the PR (marked with [1]). thanks!

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/cmd/upgrade/node.go
> -}
[1]

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/cmd/upgrade/node.go
> -}
^ [1]

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/phases/upgrade/postupgrade.go
> +	if err := backupAPIServerCertIfNeeded(cfg, dryRun); err != nil {
[1]

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/phases/upgrade/postupgrade.go
> +func backupAPIServerCertIfNeeded(cfg *kubeadmapi.InitConfiguration, dryRun bool) error {
[1]

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/phases/upgrade/prepull.go
> -			},
[1]

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/phases/upgrade/staticpods.go
> +				return fmt.Errorf("failed to upgrade the %s %s-client certificate and key: %v", constants.KubeAPIServer, constants.Etcd, err)
[1]

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/phases/uploadconfig/uploadconfig.go
> +	BootstrapDiscoveryClusterRoleName = "kubeadm:bootstrap-discovery-kubeadm-config"
[1]

2018-08-24 01:52 UTC, neolit123 commented on cmd/kubeadm/app/cmd/upgrade/node.go
> -
[1]

2018-08-27 17:38 UTC, natemurthy commented
I recently ran a
```
git fetch upstream
git rebase upstream/master
git push -f origin master
```
I don't understand where all these other code changes came from.

2018-08-27 17:39 UTC, natemurthy commented
This isn't worth the effort to me any more to constantly keep my fork up-to-date with master upstream.

2018-08-27 17:39 UTC, closed without merging

2018-08-27 17:46 UTC, neolit123 commented
/hold
/uncc