implement InstanceShutdownByProviderID for azure
kubernetes/kubernetes pull request #68033
Opened 2018-08-29 22:40 UTC by yastij

**What this PR does / why we need it**: implements #66265

**Which issue(s) this PR fixes**: Fixes #66265

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2018-08-29 22:41 UTC, yastij commented
/assign @feiskyer @andyzhangx 

can you add this to the 1.12 milestone ? cc @saad-ali @jingxu97 @gnufied

2018-08-29 22:42 UTC, yastij commented
/sig azure

2018-08-30 03:37 UTC, andyzhangx approved these changes
/lgtm

2018-08-30 04:41 UTC, feiskyer requested changes
This doesn't work for vmss nodes and doesn't use caches which helps to reduces ARM API calls.

Could you add VMSS nodes support and use caches to get provisioning state? e.g. use `getVmssVM()` for VMSS and `getVirtualMachine()` for VMAS.

2018-08-30 04:42 UTC, feiskyer commented
/lgtm cancel

2018-09-04 05:30 UTC, andyzhangx commented on pkg/cloudprovider/providers/azure/azure_instances.go
> +	return provisioningState == "Stopped" || provisioningState == "Deallocated", nil
I would suggest all using lower case to do string comparison, to prevent case change in the future.

2018-09-04 05:30 UTC, andyzhangx commented on pkg/cloudprovider/providers/azure/azure_standard.go
> +
pls remove unncessary empty lines

2018-09-04 20:04 UTC, yastij commented
@feiskyer @andyzhangx - fixe PTAL so we can ship this for 1.12, Thanks !

2018-09-04 20:58 UTC, yastij commented
/retest  pull-kubernetes-e2e-kops-aws

2018-09-05 00:11 UTC, andyzhangx commented on pkg/cloudprovider/providers/azure/azure_standard.go
> +
remove this line

2018-09-05 00:11 UTC, andyzhangx commented on pkg/cloudprovider/providers/azure/azure_vmss.go
> +
remove this line

2018-09-05 00:11 UTC, andyzhangx commented on pkg/cloudprovider/providers/azure/azure_vmss.go
> +
remove this line

2018-09-05 00:11 UTC, andyzhangx commented on pkg/cloudprovider/providers/azure/azure_vmss.go
> +
remove this line

2018-09-05 02:47 UTC, feiskyer approved these changes
LGTM now, please remove the unnecessary empty lines.

2018-09-05 02:47 UTC, feiskyer commented
/milestone v1.12

2018-09-07 23:40 UTC, feiskyer commented
/lgtm
/retest

2018-09-08 16:38 UTC, yastij commented
/priority critical-urgent

2018-09-08 17:43 UTC, merged