Correct some errors in returned message
kubernetes/kubernetes pull request #68048
Opened 2018-08-30 08:16 UTC by AdamDang

Correct some errors in returned message:
coundn't->couldn't

2018-08-30 08:17 UTC, AdamDang commented
/assign @janetkuo @karataliu

2018-08-30 08:29 UTC, andyzhangx reviewed
is it `couldn't` ?

2018-08-30 08:39 UTC, AdamDang commented
@andyzhangx 
Taken in context, I think it should be "could not".

2018-08-30 08:52 UTC, tianshapjq commented on pkg/cloudprovider/providers/azure/azure_vmss.go
> +		glog.Errorf("could't find vmss virtual machine by scaleSetName (%q) and instanceID (%q)", scaleSetName, instanceID)
couldn't

2018-08-30 08:52 UTC, tianshapjq commented on pkg/controller/disruption/disruption.go
> +		glog.Errorf("Could't get key for PodDisruptionBudget object %+v: %v", pdb, err)
couldn't

2018-08-30 08:52 UTC, tianshapjq commented on pkg/controller/disruption/disruption.go
> +		glog.Errorf("Could't get key for PodDisruptionBudget object %+v: %v", pdb, err)
the same

2018-08-30 08:52 UTC, tianshapjq commented on pkg/controller/statefulset/stateful_set.go
> +		utilruntime.HandleError(fmt.Errorf("Could't get key for object %+v: %v", obj, err))
same

2018-08-30 08:54 UTC, tianshapjq commented on pkg/cloudprovider/providers/azure/azure_vmss.go
> +		glog.Errorf("could't find vmss virtual machine by scaleSetName (%q) and instanceID (%q)", scaleSetName, instanceID)
can we change the %q to %s? the scaleSetName and instanceID are all string type, and no need to print within '' IMO.

2018-08-30 10:38 UTC, andyzhangx requested changes
could you squash the commit into one? I will then approve, thanks.

2018-08-30 11:33 UTC, AdamDang commented
@andyzhangx
 I will try to squash them. I have 0 experience about squashing :)

2018-08-30 11:38 UTC, andyzhangx commented
`git rebase -i HEAD~6`
and then edit
after that, git push ... --force

2018-10-30 01:56 UTC, AdamDang commented
@andyzhangx 
I've tried to squash the commits into 1. I thinks it works now.
Thanks for your help.

2018-10-30 02:36 UTC, andyzhangx approved these changes
/lgtm
/approve

2018-10-30 02:37 UTC, andyzhangx commented
/ok-to-test

2018-10-30 18:19 UTC, janetkuo approved these changes

2018-10-30 18:19 UTC, janetkuo commented
/approve

2018-10-30 20:44 UTC, merged