[kubeadm] - Fix etcd CA usage during upgrade
kubernetes/kubernetes pull request #68485
Opened 2018-09-10 20:15 UTC by detiber

**What this PR does / why we need it**:

Ensure usage of existing CA on disk when attempting to create certificates

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubeadm/issues/1104

**Release note**:
```release-note
NONE
```

2018-09-10 20:15 UTC, detiber commented
/kind bug
/priority critical-urgent

2018-09-10 20:37 UTC, liztio commented
@detiber I know there's time crunch, but I don't think this is the best solution. The method doesn't make it all obvious that it has a substantial side effect

2018-09-11 08:47 UTC, rosti requested changes
I support @liztio's opinion.
How about introducing a simple wrapper func to both `TryLoadCertFromDisk` and `NewCACertAndKey` to basically try load certificate from disk and fall back to generating one if that fails? Then use this in the appropriate places.
This way the patch gets bigger, but `writeCertificateAuthorithyFilesIfNotExist` remains unmodified and still does nothing more, than what's expected of it.

2018-09-13 19:02 UTC, timothysc commented
/assign @timothysc

2018-09-14 07:59 UTC, fabriziopandini commented
/milestone v1.12

2018-09-14 19:36 UTC, timothysc commented
/hold 

@liztio When you submit a different PR for this can you please close this PR.

2018-09-17 17:34 UTC, liztio commented
Superceded by #68749

2018-09-17 17:34 UTC, liztio commented
/close

2018-09-17 17:34 UTC, closed without merging