Replace internal version of resource with external version for tests
kubernetes/kubernetes pull request #68634
Opened 2018-09-13 20:15 UTC by seans3

* Replaces the internal version of a resource within the test with an external version.

Helps address: Remove Kubectl dependencies on kubernetes/pkg/api and kubernetes/pkg/apis
https://github.com/kubernetes/kubectl/issues/83

```release-note
NONE
```

2018-09-13 20:15 UTC, seans3 commented
/sig cli

2018-09-13 20:19 UTC, seans3 commented
/kind cleanup

2018-09-14 01:03 UTC, seans3 commented
/test pull-kubernetes-e2e-kops-aws

2018-09-20 19:54 UTC, seans3 commented
/assign juanvallejo
/assign soltysh

2018-09-20 21:56 UTC, juanvallejo commented on pkg/kubectl/polymorphichelpers/canbeautoscaled.go
> +	apps "k8s.io/api/apps/v1"
nit: mind renaming to `appsv1`, `corev1`, `extensionsv1beta1` to keep consistency with other files? (e.g. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/polymorphichelpers/protocolsforobject.go#L23-L27 or https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/polymorphichelpers/updatepodspec.go#L22)

2018-09-20 21:56 UTC, juanvallejo commented on pkg/kubectl/polymorphichelpers/canbeexposed.go
> +	apps "k8s.io/api/apps/v1"
same nit as above: appsv1, corev1, etc

2018-09-20 21:57 UTC, juanvallejo commented
few nits, but otherwise lgtm

2018-09-24 18:01 UTC, juanvallejo commented
/lgtm

2018-09-24 19:34 UTC, seans3 commented
/retest

2018-09-24 22:32 UTC, juanvallejo commented
/lgtm

2018-09-25 15:52 UTC, soltysh requested changes

2018-09-25 15:52 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/canbeautoscaled.go
> +		schema.GroupKind{
`corev1.SchemeGroupVersion.WithKind("ReplicationController")` is the preferred way here.

2018-09-25 15:52 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/canbeautoscaled.go
> +		schema.GroupKind{
This applies to all of those.

2018-09-25 15:52 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/canbeautoscaled_test.go
> +			kind: schema.GroupKind{
Ditto.

2018-09-25 15:52 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/canbeexposed.go
> +		schema.GroupKind{
Ditto.

2018-09-25 15:52 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/mapbasedselectorforobject_test.go
> +	api "k8s.io/api/core/v1"
`corev1` is the preferred alias, to be explicit what we're working with in the code.

2018-09-25 15:52 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/mapbasedselectorforobject_test.go
> +	extensions "k8s.io/api/extensions/v1beta1"
Similarly `extensionsv1beta1`

2018-09-25 15:52 UTC, soltysh commented on pkg/kubectl/polymorphichelpers/mapbasedselectorforobject_test.go
> +	extensions "k8s.io/api/extensions/v1beta1"
I know this will require bigger changes, but in the long run it will simplify figuring out what's still left when externalizing commands.

2018-09-25 15:52 UTC, soltysh commented
/lgtm cancel

2018-09-27 11:35 UTC, soltysh approved these changes
/lgtm

2018-09-27 13:06 UTC, merged