[kubeadm] warn if the CIDR is missing
kubernetes/kubernetes pull request #68682
Opened 2018-09-14 16:24 UTC by xlgao-zju

**What this PR does / why we need it**:
warn if the CIDR is missing

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes [kubernetes/kubeadm/#1011](https://github.com/kubernetes/kubeadm/issues/1011)

**Special notes for your reviewer**:
/assign @stealthybox 
/assign @neolit123 

**Release note**:

```release-note
NONE
```

2018-09-14 21:09 UTC, neolit123 commented
@xlgao-zju thanks!
seems correct as per the issue.

LGTM

/kind bug
/test pull-kubernetes-e2e-kops-aws
/assign @timothysc

2018-09-15 13:00 UTC, fabriziopandini approved these changes
@xlgao-zju thanks for the fix!
/approve 
I let final lgtm to @neolit123 or @stealthybox who followed the issue

2018-09-17 03:13 UTC, xlgao-zju commented
Ping @neolit123 for `lgtm` label, since you have already given your LGTM.

2018-09-17 16:32 UTC, neolit123 commented
/hold
something else to note here.

i tested locally.
this will always show a preflight warning because we don't have a default `podSubnet` value in the config (which is understandable), but we do always set `serviceSubnet` to `10.96.0.0/12`.

so the question is - is it OK to show this warning?
or should we rather default to some value?

the verification is performed here:
https://github.com/kubernetes/kubernetes/blob/2f63238c478687276f9ce6d56f1364a0012275a6/cmd/kubeadm/app/preflight/checks.go#L869

/assign @kad 
for opinion on the subject.

2018-09-17 17:21 UTC, stealthybox commented
This is a good first stab at it @xlgao-zju.
The output of your patch currently looks like this.
```
kubeadm init
[init] using Kubernetes version: v1.11.3
[preflight] running pre-flight checks
	[WARNING HTTPProxyCIDR]: the CIDR is missing
[preflight/images] Pulling images required for setting up a Kubernetes cluster
[preflight/images] This might take a minute or two, depending on the speed of your internet connection
```

I recommend separating the CIDRMissing checks into their own dedicated checks instead of reusing the nil case for the Proxy check.

There should be a dedicated check for both `cfg.Networking.ServiceSubnet` and `cfg.Networking.PodSubnet`, so that the user can determine which fields they're being warned about and why they might want to define them explicitly.

2018-09-17 17:30 UTC, stealthybox commented
@neolit123 @kad I agree that it would be preferable to have default values for both subnets.

Poking around, this doesn't seem required to make kube-proxy work, but if we can default the `Notworking.PodSubnet` and set the kube-proxy `--cluster-cidr` all the time, we should.

2018-09-17 18:28 UTC, neolit123 commented
what value should we default to PodSubnet?

2018-09-19 11:13 UTC, dims commented
@timothysc @neolit123 what's the word on this? (needed for 1.12?)

2018-09-19 12:02 UTC, neolit123 commented
the PR is needed for 1.12 but it also needs discussion.
realistically, it might go in 1.12.1.

2018-09-19 19:31 UTC, kad commented
I don't think we really need that check. Or, we can do it differently. If that parameter is needed, let's create a separate check for presence of CIDR parameter instead of trying to hide it inside HTTP Proxy CIDR check.

2018-09-20 07:14 UTC, xlgao-zju commented
I think we can set the default value. And how about doing this check before using the default value. So users will know that we will use the default value, because he/she did not specify the CIDR.

2018-09-20 13:37 UTC, neolit123 commented
we should set a default value in all cases as we do for the service CIDR.

i think there are two options here:
A. set a default value, but only warn if the user removes it and makes the value empty.
(this is what we do for service CIDR)
B. (@xlgao-zju this is your suggestion) warn if the user does not set the pod CIDR and tell that a default value will be used.

i'm leaning towards A, but feedback  from others will be appreciated.
but we will probably delay this after 1.12.

2018-09-20 14:39 UTC, pmichali commented
For bridge and PTP plugins, a podSubnet is not used, right? Are we considering that case?

2018-09-22 07:30 UTC, stealthybox commented
Considering @pmichali's point about clearly supporting the bridge plugin, I propose:

When the podSubnet is empty, we should:
- notify the user it's empty
- indicate the general expected use-case(s)
- indicate that kube-proxy and any other components are not aware of podIP's -- (need further clarification here on all sensible component configurations)

**If** we default the podSubnet to some value, we should:
- notify the user of the default
- indicate the general expected use-case(s)
- indicate which use-cases don't function or benefit

___________________
The current default behavior is to leave the podSubnet implicitly empty.
We need to decide if we want to provide a default value for it.

A fair argument for providing a default is VXLAN CNI setups are common and will benefit from the option.
However, it's a breaking change for existing configs.

2018-09-23 16:09 UTC, kad commented
IMHO: keep value as currently empty. Create new check that will warn about cases where it will be problematic.

2018-11-06 22:44 UTC, kad requested changes
Create separate check for empty CIDRs if needed.

2019-03-27 14:32 UTC, bart0sh commented
@kubernetes/sig-cluster-lifecycle-pr-reviews this PR seems outdated? Should we close it?

2019-03-27 14:44 UTC, neolit123 commented
the original ticket is frozen and we didn't decide on the correct path for this.
/close

2019-03-27 14:44 UTC, closed without merging