add restartCountLimit for pod
kubernetes/kubernetes pull request #68745
Opened 2018-09-17 15:28 UTC by dixudx

**What this PR does / why we need it**:
When the pods exit with none zero or other reasons ,then it will be restarted according to restartPolicy. For pods with `Always` restart policy, there should a way to stop such infinite restart loop, which is wasting the resources and may cause undesired restarts.

This PR adds a new annotation `"io.kubernetes.pod.restartCountLimit"` for pod to limit pod restart count.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #49466

**Special notes for your reviewer**:
/sig node
/kind featue

**Release note**:

```release-note
add an annotation to limit pods restart count
```

2018-09-17 15:29 UTC, dixudx commented
/cc @kubernetes/sig-node-pr-reviews

2018-09-18 01:44 UTC, feiskyer commented
> may cause undesired restarts.

Sorry, I didn't get this. What do you mean by this?

2018-09-18 02:58 UTC, tianshapjq commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
> +						continue
doesn't it need to break and stop looping the rest containers?

2018-09-18 02:58 UTC, tianshapjq commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
> +						msg := fmt.Sprintf("Stop restarting container %+v in pod %v due to exceeding pod restart count limit", container, format.Pod(pod))
%v -> %s

2018-09-18 02:58 UTC, tianshapjq commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
> +					glog.V(5).Infof("Failed to parse restart count limit in pod %v: %+v", format.Pod(pod), err)
would it be better to put it into the event pool of pod? then I can describe pod to see what happens to this pod.

2018-09-18 03:00 UTC, mlmhl commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
> +						startContainerResult.Fail(errors.New("ExceededRestartCountLimit"), msg)
What's the status of Pod when `restartCountLimit` exceeded? Do we need to make it as `Failed`?

2018-09-18 16:58 UTC, yujuhong requested changes
@dixudx I think this may need a (short) proposal detailing what the desired behavior is, why is this set per pod (vs per node) and what goals the change is trying to achieve.

Besides, annotations are discouraged and API chaneg should be considered with feature gates if this is necessary.

2018-09-21 16:04 UTC, michaelfavia commented
As someone affected by this issue and found this PR looking for a builtin solution I can chime in here as well.

We run pods as part of a HPA and occasionally some of the pods get stuck in this restart loop. The cause varies from what I can tell. Maybe its due to initial filesystem instability during a initContainer step that copies the resources to the disk or some other reason. 

When this happens a simple manual deletion of the pod causes it to be instantly restored by the HPA/RS and is back to fully functioning. 

Perhaps this annotation is best put on the HPA (or ReplicaSet - the pod manager) because I struggle to think of a use case for restartCountLimit on a Pod of which I think the whole point is its resilience. It probably should be responsible for its own death in the same vein of it not being responsible for its creation. ;)

@yujuhong: Does this explanation help at all?

2018-09-21 18:53 UTC, yujuhong commented
@michaelfavia thanks for the explanation. I could think of ways that the feature would be useful, but I have some concerns about how it's implemented in the PR.

As you said, HPA or other controllers could detect the crashlooping, delete & re-create the pods based on it's only criteria. It might be an issue figuring out which controller should own this logic, and that's where implementing this in kubelet *might* be preferable. Another use case would be saving resources on the node, although with the current backoff mechanism, I haven't seen this being a performance bottleneck yet. Overall, I  think this deserves more discussion, and adding new annotations for kubelet to check and implement is probably not the way to go :-)

2018-09-25 03:16 UTC, mlmhl commented
Agree with @yujuhong , we need more discussion of this feature, such as:

1. Some use case or user story, this can help us better define our demand.
2. What should we do when `restartCountLimit` exceeded? Just skip creating the container or make the `Pod` failed, so that according controllers can re-create it.

2019-03-11 05:24 UTC, dixudx commented
/remove-lifecycle stale

2019-04-10 07:04 UTC, dixudx commented
/reopen
/remove-lifecycle stale

2019-05-11 13:34 UTC, dixudx commented
/reopen
/remove-lifecycle rotten

2019-09-15 08:10 UTC, dixudx commented
/remove-lifecycle rotten

2020-02-12 09:48 UTC, closed without merging