RESTMapper in NewRESTMetricsClient
kubernetes/kubernetes pull request #68800
Opened 2018-09-18 19:05 UTC by bartekzurawski

**What this PR does / why we need it**:
Use RESTMapper in NewRESTMetricsClient to determine that scope is namespaced or root. 

**Which issue(s) this PR fixes**:
Fixes #67777

**Special notes for your reviewer**:

**Release note**:

2018-09-18 19:06 UTC, bartekzurawski commented
/hold 

@DirectXMan12 Is this approach will be ok?

2018-09-18 19:06 UTC, bartekzurawski commented
/assign @DirectXMan12

2018-09-19 00:46 UTC, neolit123 commented
@bartekzurawski 
thank you for the PR!

please, squash your commits into one and add a release note as per the issue template here:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

/kind bug

2018-09-20 20:07 UTC, lavalamp commented
/assign @caesarxuchao

2018-09-21 23:19 UTC, caesarxuchao reviewed
/lgtm

one nit

2018-09-21 23:19 UTC, caesarxuchao commented on pkg/controller/podautoscaler/metrics/rest_metrics_client.go
>  		// handle namespace separately
This comment can be removed now.

2018-09-21 23:20 UTC, caesarxuchao commented
/ok-to-test

2018-09-30 20:03 UTC, bartekzurawski commented on pkg/controller/podautoscaler/metrics/rest_metrics_client.go
>  		// handle namespace separately
Done

2018-11-15 20:58 UTC, DirectXMan12 requested changes
needs a test to show that it's working.  Should be relatively easy to copy one of the other basic tests for the HPA.  Please also add a test that they can only metrics about the HPA's own namespace when we target the namespace itself.

Code otherwise looks good.

@kubernetes/sig-api-machinery-pr-reviews @kubernetes/sig-auth-pr-reviews this allows users to read aggregated forms of metrics values for metrics they might not be able to directly access through the API (but the HPA in general does this already, so I'm not sure how big the impact is).

Currently, all requests are scoped to the user's namespace from the HPA, so the user can effectively read aggregated metrics for objects they might not have direct RBAC access to, but only for things in their namespace.  If a cluster admin installs a more restrictive policy than the bootstrap, they can control which specific objects and metrics are affected.

This PR shouldn't allow them to read outside their namespace, but it will allow targeting cluster-scoped metrics.  Practically, I expect this should't be a huge deal, since you only get the aggregated form, and clsuter admins could write policy to restrict the individual metrics, but I want to be sure that there's not a broader concern.

2019-02-15 21:53 UTC, bartekzurawski commented
/remove-lifecycle stale

2019-03-22 07:34 UTC, Rajat-0 commented
Its been inactive from a long time, so I created new PR for this https://github.com/kubernetes/kubernetes/pull/74758

2019-07-04 07:54 UTC, akki commented
/close

2019-07-04 07:54 UTC, closed without merging