E2E: handling extra files
kubernetes/kubernetes pull request #69103
Opened 2018-09-26 15:31 UTC by pohly

**What this PR does / why we need it**:

There is an on-going effort to make test/e2e.test self-contained by building all files that are needed at runtime into the binary via bindata. Tests which support that do so by retrieving files from the test/e2e/generated package. The downside of that approach is that such tests only work in Kubernetes itself. As described in issue #66649, making tests reusable outside of Kubernetes is useful, for example for testing other CSI drivers.

This PR adds an API (test/e2e/framework/testfiles) that decouples tests from the actual code that retrieves files. In the test/e2e test suite, access via --repo-root is kept in addition to retrieval from bindata, so everything works as before.

The goal is *not* to get rid of --repo-root. However, by converting some tests to use the new API, those tests no longer depend on --repo-root, so we get a step closer to that goal - if it still is a goal. Some tests depend on extra files (for example, test/e2e/framework/ingress/ingress_utils.go for providing the optional secret.yaml) which cannot be built into the binary.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partial fix #66649 (main goal)
Partial fix #23987 (side effect)

**Special notes for your reviewer**:

This depends on PR #68187 getting merged first. The first commit here is from that PR.

This is a subset of PR#68483.

**Release note**:

```release-note
NONE
```

/sig testing

2018-09-26 15:39 UTC, timothysc commented
/ok-to-test

2018-09-26 19:32 UTC, timothysc requested changes
Minor comments + 2 commits, please. 

1 for changes 
1 for auto-generated.

2018-09-26 19:32 UTC, timothysc commented on test/e2e/framework/testfiles/testfiles.go
> +		ginkgo.Fail(fmt.Sprintf("No file sources registered (yet?), cannot retrieve test file %s.", filePath))
After looking at the call sites I think you wrap everything into an error handler and pass in a closure to call the ginkgo with the error without you having to take on owning ginkgo details in this sub-package.

2018-09-27 06:29 UTC, pohly commented on test/e2e/framework/testfiles/testfiles.go
> +var filesources = make([]FileSource, 0, 5)
No particular reason, I just thought that pre-allocating some memory might be useful. But I agree, that's something that the first append() can also do, so I'll make it nil.

2018-09-27 06:37 UTC, pohly commented on test/e2e/framework/testfiles/testfiles.go
> +		ginkgo.Fail(fmt.Sprintf("No file sources registered (yet?), cannot retrieve test file %s.", filePath))
This is part of test/e2e/framework, which already is tied to Ginkgo, so it seemed okay to use that also here. It makes the API a bit simpler. What about just calling `panic`? The effect will be the same (also get's caught by Ginkgo and logged).

It's not just `ReadOrDie`, `Exists` also fails on errors to simplify the call sites.

2018-09-27 11:35 UTC, pohly commented
@timothysc I force-pushed two commits, one for the source code changes and one for the Bazel BUILD files. I kept the test/e2e/examples.go changes because if we merge all of this at once, we do not need PR #68187 anymore.

This version uses `panic` in `test/e2e/framework/testfiles` instead of Ginkgo. I'd prefer to keep the API simple, but don't feel strongly about it and can also introduce an additional parameter which handles the errors.

Here's output for a test that triggers such a panic because the file name was changed such that the file isn't found. I've shortened the list of files. The original error lists all of the builtin files:
```
•! Panic in Spec Setup (BeforeEach) [6.161 seconds]
[sig-cli] Kubectl client
/nvme/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/framework.go:22
  [k8s.io] Update Demo
  /nvme/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:694
    should do a rolling update of a replication controller  [Conformance] [BeforeEach]
    /nvme/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:699

    Test Panicked
    Test file "test/fixtures/doc-yaml/user-guide/update-demo/nautilus-xxx-rc.yaml.in" was not found.
    Test files are expected in "/nvme/gopath/src/k8s.io/kubernetes/cluster/..".
    The following files are built into the test executable via gobindata. For questions on maintaining gobindata, contact the sig-testing group.
       test/e2e/testing-manifests/flexvolume/dummy
       test/e2e/testing-manifests/flexvolume/dummy-attachable
....
       test/images/webhook/patch_test.go
       test/images/webhook/pods.go
       test/images/webhook/scheme.go
    
    /usr/lib/go-1.10/src/runtime/panic.go:502

    Full Stack Trace
    	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
    k8s.io/kubernetes/test/e2e/framework/testfiles.ReadOrDie(0xc421f40410, 0x45, 0x2, 0xc421f40410, 0x45)
    	/nvme/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/testfiles/testfiles.go:90 +0x2e6
    k8s.io/kubernetes/test/e2e/kubectl.glob..func2.6.1()
    	/nvme/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:295 +0xad
    k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420f4f800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/nvme/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:306 +0x1fc
    k8s.io/kubernetes/test/e2e.TestE2E(0xc42056fa40)
    	/nvme/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:65 +0x2b
    testing.tRunner(0xc42056fa40, 0x45c7fe8)
    	/usr/lib/go-1.10/src/testing/testing.go:777 +0xd0
    created by testing.(*T).Run
    	/usr/lib/go-1.10/src/testing/testing.go:824 +0x2e0
```

2018-09-27 13:44 UTC, timothysc commented on test/e2e/framework/testfiles/testfiles.go
> +		ginkgo.Fail(fmt.Sprintf("No file sources registered (yet?), cannot retrieve test file %s.", filePath))
Passing via a well defined, simple closure it not too pesky and would meet the goal of minimizing the proliferation of ginkgo dependencies and being about to have the failure be clearly visible from the call sites.

2018-09-27 15:13 UTC, pohly commented
@timothysc I pushed a version which takes a callback that gets invoked on failures. To make the API still easy to use, the signature is exactly that of ginkgo.Fail. Otherwise callers would have to use a closure.

Some callers can handle an error and don't use Ginkgo. For those I added a `testfiles.Read` which returns the error.

2018-09-27 15:50 UTC, pohly commented
/retest

2018-10-01 18:48 UTC, timothysc approved these changes
/lgtm 
/approve 

Thanks for doing this!

2018-10-01 19:45 UTC, pohly commented
/kind feature

2018-10-02 10:12 UTC, pohly commented
@timothysc I had to rebase because https://github.com/kubernetes/kubernetes/commit/60f736ed3d617f4770dc76657dd75a31bffb03f0 introduced a new direct call to the `generated` package. Please add lgtm again.

There's also some test failure in pull-kubernetes-integration which I don't understand ("test-cmd run_rs_tests" fails) - a flake or does this PR really cause that test to fail now?

2018-10-02 11:58 UTC, pohly commented
/retest

2018-10-04 15:39 UTC, pohly commented
/retest

2018-10-04 18:07 UTC, pohly commented
/retest

2018-10-04 20:39 UTC, merged