remove --show-all
kubernetes/kubernetes pull request #69255
Opened 2018-09-29 09:11 UTC by Pingan2017

**What this PR does / why we need it**:
remove `show-all`, it is deprecated in 1.10
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-09-29 09:14 UTC, Pingan2017 commented
/kind cleanup 
/assign @adohe

2018-10-03 21:21 UTC, juanvallejo commented
/ok-to-test

2018-10-03 21:21 UTC, juanvallejo approved these changes

2018-10-03 21:22 UTC, juanvallejo commented
cc @soltysh for approval

2018-10-04 14:18 UTC, juanvallejo commented
/retest

2018-10-04 16:30 UTC, soltysh requested changes
/hold
/lgtm cancel
We can't remove it yet, based on https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli we need to wait until 12 months, so 1.14 at soonest.

2019-01-03 10:24 UTC, Pingan2017 commented
/hold cancel

2019-01-24 12:47 UTC, soltysh approved these changes
Yup, 1.14 is on now
/lgtm
/approve

2019-01-24 12:47 UTC, soltysh commented
/retest

2019-01-24 14:30 UTC, merged