Print sizeLimit
kubernetes/kubernetes pull request #69279
Opened 2018-10-01 12:13 UTC by dtaniwaki

**What this PR does / why we need it**:

Print `SizeLimit` of `EmptyDir` in `kubectl describe pod` outputs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

N/A

**Special notes for your reviewer**:

**Release note**:

```release-note
Print `SizeLimit` of `EmptyDir` in `kubectl describe pod` outputs.
```

2018-10-18 14:13 UTC, mcrute commented
/ok-to-test
/lgtm

2018-10-18 16:50 UTC, mcrute commented
Should be ready to merge... adding @smarterclayton for approval.

/unassign
/assign @smarterclayton

2018-10-20 02:50 UTC, smarterclayton commented
If emptydir sizelimit is empty, should we be displaying “Unlimited” instead of empty string / 0?

2018-10-27 08:04 UTC, dtaniwaki commented
@smarterclayton Can I make the change you suggested or are we going to have the conclusion after some discussion?

2018-11-17 14:55 UTC, dtaniwaki commented
/assign @smarterclayton

2018-11-21 15:53 UTC, soltysh requested changes
Also please squash your changes into single commit.

2018-11-21 15:53 UTC, soltysh commented on pkg/kubectl/describe/versioned/describe.go
> +		sizeLimit = "Unlimited"
`<unset>` will follow the pattern set across this file.

2018-11-21 15:54 UTC, soltysh commented
/kind cleanup
/assign

2018-11-27 04:41 UTC, dtaniwaki commented
@soltysh I updated the code based on your feedback. Could you check it again?

2018-12-03 11:19 UTC, dtaniwaki commented
@soltysh @dshulyak @seans3 Could someone review this PR?

2018-12-03 17:16 UTC, mcrute commented
/lgtm

Ping @soltysh for approval

2019-01-05 15:07 UTC, dtaniwaki commented
@soltysh Could you review this PR again?

2019-01-12 03:48 UTC, dtaniwaki commented
/test pull-kubernetes-godeps

2019-01-17 10:53 UTC, soltysh approved these changes
/approve

2019-01-17 12:06 UTC, merged