kubectl taint: copy core taintutil dependency into kubectl
kubernetes/kubernetes pull request #69446
Opened 2018-10-04 23:00 UTC by seans3

```
pkg/util/taints -> pkg/kubectl/util/taints
```
* Copies taintutil functions into kubectl
* Removes core dependency on taintutil
* The concept of copying utility code from core into kubectl has been discussed and approved for SIG CLI in order to move kubectl out of Kubernetes core.

Helps address:
https://github.com/kubernetes/kubectl/issues/80

```release-note
NONE
```

2018-10-04 23:00 UTC, seans3 commented
/kind cleanup
/assign

2018-10-04 23:00 UTC, seans3 commented
/sig slic
/area kubectl

2018-10-05 03:12 UTC, seans3 commented
/cc @soltysh

2018-10-05 11:09 UTC, soltysh requested changes
/hold
I'm putting together a PR reshuffling all the commands into separate directories. Then copy only the necessary utils for taint command into that dir.

2018-10-05 14:49 UTC, soltysh commented
See https://github.com/kubernetes/kubernetes/pull/69464 for the restructuring.

2018-10-08 21:44 UTC, seans3 commented
/hold

2018-10-09 15:06 UTC, soltysh requested changes
I've left you some comments. The rule of thumb is these should be private helpers to a specific command. We are already risking quite a bit by copying them, but we need to ensure that they should not escape from outside this command dir.

2018-10-09 15:06 UTC, soltysh commented on pkg/kubectl/cmd/taint/utils.go
> +func ParseTaints(spec []string) ([]corev1.Taint, []corev1.Taint, error) {
Can you make it private?

2018-10-09 15:06 UTC, soltysh commented on pkg/kubectl/cmd/taint/utils.go
> +func ReorganizeTaints(node *corev1.Node, overwrite bool, taintsToAdd []corev1.Taint, taintsToRemove []corev1.Taint) (string, []corev1.Taint, error) {
Ditto?

2018-10-09 15:06 UTC, soltysh commented on pkg/kubectl/cmd/taint/utils.go
> +func CheckIfTaintsAlreadyExists(oldTaints []corev1.Taint, taints []corev1.Taint) string {
Same here

2018-10-09 15:06 UTC, soltysh commented on pkg/kubectl/cmd/taint/utils.go
> +func DeleteTaintsByKey(taints []corev1.Taint, taintKey string) ([]corev1.Taint, bool) {
And here.

2018-10-09 15:06 UTC, soltysh commented on pkg/kubectl/cmd/taint/utils.go
> +func DeleteTaint(taints []corev1.Taint, taintToDelete *corev1.Taint) ([]corev1.Taint, bool) {
That too.

2018-10-09 15:06 UTC, soltysh commented on pkg/kubectl/cmd/taint/utils.go
> +Copyright 2016 The Kubernetes Authors.
Since this is a new file you might need to update the date to current year.

2018-10-12 13:52 UTC, juanvallejo approved these changes

2018-10-12 13:52 UTC, juanvallejo commented
/lgtm

2018-10-12 15:25 UTC, soltysh approved these changes
/lgtm

2018-10-12 20:57 UTC, juanvallejo commented
/lgtm

2018-10-12 23:01 UTC, merged