cleanup: delete duplicate lines
kubernetes/kubernetes pull request #69517
Opened 2018-10-08 09:23 UTC by SataQiu

**What this PR does / why we need it**:

I found that the `NewCmdInit` function in init.go has some codes that may be duplicated, so I submit this PR. If the redundant code is required, please close this PR!

/kind cleanup

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

2018-10-08 13:23 UTC, dixudx requested changes

2018-10-08 13:44 UTC, SataQiu commented on cmd/kubeadm/app/cmd/init.go
> -			kubeadmscheme.Scheme.Default(externalcfg)
@dixudx Because it is same as line 112. Why do we repeat this? Is it needed?

2018-10-09 14:32 UTC, dixudx approved these changes

2018-10-09 14:32 UTC, dixudx commented on cmd/kubeadm/app/cmd/init.go
> -			kubeadmscheme.Scheme.Default(externalcfg)
@SataQiu Sorry for missing that.

2018-10-09 14:32 UTC, dixudx commented
/ok-to-test

2018-10-09 14:32 UTC, dixudx commented
/lgtm

2018-10-10 19:49 UTC, timothysc approved these changes
/approve

2018-10-10 19:50 UTC, timothysc commented
/test pull-kubernetes-e2e-gce

2018-10-10 21:16 UTC, timothysc commented
/test pull-kubernetes-e2e-gce

2018-10-10 23:46 UTC, merged