Secret docker fix
kubernetes/kubernetes pull request #69546
Opened 2018-10-08 23:43 UTC by seans3

* Copies docker config structs into kubectl.
* Removes dependency on core credentialprovider

Helps Address:
https://github.com/kubernetes/kubectl/issues/80

```release-note
NONE
```

2018-10-08 23:43 UTC, seans3 commented
/kind cleanup
/assign

2018-10-09 17:21 UTC, seans3 commented
/cc @soltysh 
/cc @juanvallejo

2018-10-09 19:38 UTC, seans3 commented
/retest

2018-10-09 20:09 UTC, seans3 commented
/retest

2018-10-09 22:30 UTC, apelisse commented
That seems good to me.

2018-10-10 15:51 UTC, juanvallejo approved these changes

2018-10-10 15:52 UTC, juanvallejo commented
lgtm, will defer approval to @soltysh

2018-10-16 11:24 UTC, soltysh requested changes
/hold
This is already handled by https://github.com/kubernetes/kubernetes/pull/68441 which moves all of the generators.

2018-10-17 16:45 UTC, seans3 commented
This was addressed in another PR--closing.

2018-10-17 16:45 UTC, closed without merging