Fixes golint in test/utils/image
kubernetes/kubernetes pull request #69598
Opened 2018-10-09 21:58 UTC by jonfriesen

**What this PR does / why we need it**:
This change fixes the test/utils/image package golint errors.

**Which issue(s) this PR fixes**:
refer #68026

**Special notes for your reviewer**:
I renamed `ImageConfig` to `Config` to fix stuttering (eg. `image.ImageConfig`). I couldn't find a spot where this would break other packages. Though I'm not exactly sure what the best practice is on renaming a public struct. Guidance would be appreciated  :) 

**Release note**:
```release-note
NONE
```

2018-10-10 00:38 UTC, wgliang commented
/ok-to-test

2018-10-10 02:09 UTC, charrywanganthony commented
/retest

2018-10-10 03:22 UTC, mkumatag requested changes

2018-10-10 03:58 UTC, jonfriesen commented on test/utils/image/manifest.go
> +// When these values are updated, also update cmd/kubelet/app/options/container_runtime.go
ah thanks, that wasn't clear on that. updated the comment to be pause specific

2018-10-10 13:51 UTC, jonfriesen commented
/retest

2018-10-10 16:06 UTC, jonfriesen commented
/assign @ixdy

2018-10-10 16:13 UTC, mkumatag commented
/lgtm

2018-10-11 01:34 UTC, ixdy commented
/lgtm

2018-10-11 05:04 UTC, ixdy commented
/approve

Looks like this needs rebase, though.

2018-10-11 14:28 UTC, jonfriesen commented
oh... yeah I think I messed up this PR

2018-10-11 14:30 UTC, closed without merging