Clean up some golint errors unrelated to comments in kubeapiserver
kubernetes/kubernetes pull request #69765
Opened 2018-10-13 13:20 UTC by wgliang

**What this PR does / why we need it**:

Clean up some golint errors unrelated to comments in kubeapiserver.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/kind cleanup
/area apiserver

**Release note**:

```release-note
NONE
```

2018-10-15 07:03 UTC, yue9944882 requested changes
thx for fixing this @wgliang 

plz keep a minimal change w/ golint

2018-10-15 07:03 UTC, yue9944882 commented on pkg/kubeapiserver/admission/initializer_test.go
> +func (p *WantsCloudConfigAdmissionPlugin) SetCloudConfig(cloudConfig []byte) {
is this required by golint?

2018-10-15 20:13 UTC, fedebongio commented
/assign @yliaog

2018-10-15 20:31 UTC, yliaog commented on pkg/kubeapiserver/authenticator/config.go
> +type Config struct {
+1

2018-10-19 02:31 UTC, wgliang commented on pkg/kubeapiserver/authenticator/config.go
> +type Config struct {
OK, the issues reported by golint are mainly related to AuthenticatorConfig. Such as:

> type name will be used as authenticator.AuthenticatorConfig by other packages, and that stutters; consider calling this Config


If this is not necessary, I will close this PR.

2018-10-19 02:31 UTC, wgliang commented
/close

2018-10-19 02:31 UTC, closed without merging