kubeadm: fix config fetch via 'config view'
kubernetes/kubernetes pull request #69969
Opened 2018-10-18 10:23 UTC by neolit123

**What type of PR is this?**
/kind bug
/priority critical-urgent

**What this PR does / why we need it**:
fix a small issue in 1.12 where we need to use a new key to fetch the kubeadm config from the config map in case of a 1.12 cluster, but still handle the old config from 1.11.

**not a cherry pick** as our PRs that implement changes are huge.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#1174

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: fix an issue where 'config view' did not return a config in case of a 1.12 cluster
```

@kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @fabriziopandini @feiskyer 
/cc @rdodev

2018-10-18 12:40 UTC, detiber commented
/lgtm

2018-10-18 13:54 UTC, rdodev commented
/lgtm

2018-10-18 19:43 UTC, fabriziopandini requested changes
@neolit123 
I'm not 100% sure this is a safe cherry pick, because kueadm v1.12 must support also v1.11 clusters, where the config map key was called into configuration.
So IMo the backport should be a little bit more sophisticated:e.g. If a old key exist, output old key otherwise output new key

2018-10-18 19:52 UTC, neolit123 commented
@fabriziopandini 
i think you are right.
i will update it to handle the old key as well! :+1:

2018-10-18 19:52 UTC, neolit123 commented
/hold

2018-10-19 01:48 UTC, xiangpengzhao commented on cmd/kubeadm/app/cmd/config.go
> +		fmt.Fprintf(out, "%s", cfgConfigMap.Data[constants.ClusterConfigurationConfigMapKey])
Can we make sure that we can always get the data of `ClusterConfigurationConfigMapKey`? i.e., is it possible that the configmap doesn't have the data of such key?

2018-10-19 07:07 UTC, fabriziopandini approved these changes
@neolit123 
Thanks. IMO it is ok now
/approve

I let final cherry pick approval to @timothysc

2018-10-19 09:02 UTC, xiangpengzhao commented on cmd/kubeadm/app/cmd/config.go
> +		fmt.Fprintf(out, "%s", cfgConfigMap.Data[constants.ClusterConfigurationConfigMapKey])
Seems like it's impossible :)

2018-10-19 14:44 UTC, rdodev commented on cmd/kubeadm/app/cmd/config.go
> +	if value, ok := cfgConfigMap.Data[constants.InitConfigurationConfigMapKey]; ok {
@neolit123 I'm not super familiar with golang idioms, but the key here is that even when retrieving with the wrong key there was no error (simply returned empty string). So, I would think that we can use the same conditional but based on length of the string returned, not the 'ok' status?

2018-10-19 20:44 UTC, rdodev commented on cmd/kubeadm/app/cmd/config.go
> +	if value, ok := cfgConfigMap.Data[constants.InitConfigurationConfigMapKey]; ok {
@neolit123 thanks for the explanation!

2018-10-21 14:17 UTC, neolit123 commented
/assign @timothysc

2018-10-22 03:03 UTC, feiskyer commented
@neolit123 @timothysc Please get the PR approved (with both `lgtm` and `approved` label) by end of Tuesday, Oct 23th. Or else, it will miss v1.12.2.

2018-10-22 03:05 UTC, feiskyer commented
@neolit123 @timothysc Please get the PR approved (with both `lgtm` and `approved` label) by end of Tuesday, Oct 23th. Or else, it will miss v1.12.2.

2018-10-22 03:17 UTC, feiskyer commented
@neolit123 @timothysc Please get the PR approved (with both `lgtm` and `approved` label) by end of Tuesday, Oct 23th. Or else, it will miss v1.12.2.

2018-10-22 16:02 UTC, timothysc approved these changes
/lgtm 
/approve 

I'm ok with the fix, but we should be consistent with our index operations and I'd almost prefer an abstraction layer in the future.

2018-10-23 03:47 UTC, merged

2018-11-13 19:39 UTC, cristifalcas commented
Until a new version appears, you can get it like this:

```
kubectl get cm -n kube-system kubeadm-config -o json | jq '.data.ClusterConfiguration' -r
```