Add support for projected volume in describe function
kubernetes/kubernetes pull request #70158
Opened 2018-10-24 02:29 UTC by WanLinghao

> /kind bug

Currently, the output of `kubectl describe pod xxx` shows as below when it has projected volume bounds:
```
Volumes:
  token:
  <unknown>
  default-token-4wx7l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4wx7l
    Optional:    false
```
After this patch, the output will be like
```
Volumes:
  token:
    Type:  Projected (a volume that contains injected data)
           - Secret:
             Name:      dzd
             Optional:  false
           - Token:
             ExpirationSeconds:  4000
           - ConfigMap:
             Name:      kube-root-ca.crt
             Optional:  false
           - DownwardAPI
  default-token-4wx7l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4wx7l
    Optional:    false

```

```release-note
NONE
```

2018-10-24 13:42 UTC, juanvallejo commented
/sig cli

2018-10-24 15:28 UTC, juanvallejo commented on pkg/printers/internalversion/describe.go
> +			infos = append(infos, fmt.Sprintf("       - Secret:\n"+
Indent by 4 spaces here

2018-10-24 15:30 UTC, juanvallejo commented on pkg/printers/internalversion/describe.go
> +			infos = append(infos, fmt.Sprintf("       - Secret:\n"+
Also, to keep consistency with other volume describers, I'd be in favor of removing the `-` at the beginning of this section, and just squashing it down so it reads like:

```
    SecretName: ...
    SecretOptional: ...
    TokenExpirationSeconds:
    ...
```

2018-10-25 01:48 UTC, WanLinghao commented
@juanvallejo  Thanks for the review. Comments addressed, now the output looks like:
```
Volumes:
  token:
    Type:                    Projected (a volume that contains injected data)
    SecretName:              user
    SecretOptionalName:      true
    TokenExpirationSeconds:  4000
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       true
    DownwardAPI
```
DownwardAPI is special, since data in DownwardAPI is too complicate to print, so if DonwardAPI volume exists in the projected volume, just print "DownwardAPI"  with no data. WDYT

2018-10-25 01:48 UTC, WanLinghao commented
@neolit123  Done

2018-10-25 20:16 UTC, juanvallejo commented on pkg/printers/internalversion/describe.go
> +	w.Write(LEVEL_2, "Type:\tProjected (a volume that contains injected data)\n")
`s/a volume that contains injected data/a volume that contains injected data from multiple sources/` ?

2018-10-25 20:20 UTC, juanvallejo commented
>  if DonwardAPI volume exists in the projected volume, just print "DownwardAPI" with no data. WDYT

Sure, alternatively, we could print "true" or the amount of items referenced under downwardAPI 
```
DownwardAPI     true
``` 
or 
```
DownwardAPI     2 items
```

2018-10-25 20:20 UTC, juanvallejo commented
/lgtm

Thanks, cc @soltysh for approval

2018-10-25 20:20 UTC, juanvallejo approved these changes

2018-10-26 01:57 UTC, WanLinghao commented
@soltysh @juanvallejo comments addressed, now the output looks like:
```
Volumes:
  token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    SecretName:              user
    SecretOptionalName:      <nil>
    TokenExpirationSeconds:  4000
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
```

2018-10-26 02:09 UTC, WanLinghao commented
/test pull-kubernetes-verify

2018-10-26 13:27 UTC, soltysh requested changes
Also, please squash your changes into a single commit.

2018-10-29 05:03 UTC, WanLinghao commented
@soltysh Comments addressed, PTAL

2018-10-29 20:44 UTC, soltysh approved these changes
/lgtm
/approve

2018-10-29 22:54 UTC, merged