Fix overflow issue on renewal
kubernetes/kubernetes pull request #70551
Opened 2018-11-01 20:31 UTC by liztio

Co-authored by: Ruben Orduz <rubenoz@gmail.com>

**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

We were running into some weird issues (namely, stack overflows) when trying to call Cobra from inside Cobra. This fixes the `renew all` logic to not rely on Cobra at all.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#1190

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2018-11-01 23:21 UTC, timothysc requested changes
@liztio - this is weird needs more comments and details explaining "why"?

2018-11-02 14:14 UTC, liztio commented on cmd/kubeadm/app/cmd/alpha/certs.go
> +func generateCertCommand(name, longName, baseName, caCertBaseName string, cfg *renewConfig) (*cobra.Command, func()) {
Do the new changes make more sense?

2018-11-02 17:31 UTC, liztio commented
/test pull-kubernetes-kubemark-e2e-gce-big pull-kubernetes-e2e-gce-100-performance

2018-11-02 19:48 UTC, neolit123 reviewed
thanks @liztio 
added one minor comment.

2018-11-02 19:48 UTC, neolit123 commented on cmd/kubeadm/app/cmd/alpha/certs.go
> +			cmd.Run = func(*cobra.Command, []string) { renewalFunc() }
could generateRenewalFunction() return a function with the `func(*cobra.Command, []string)` signature?

2018-11-02 20:02 UTC, timothysc approved these changes
/lgtm 
/approve 

This is easier to reason about, thx @liztio

2018-11-02 23:44 UTC, merged