pkg/kubelet/logs: Add container log size metric
kubernetes/kubernetes pull request #70749
Opened 2018-11-07 15:01 UTC by brancz

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Unless an additional DaemonSet that has the same permissions as the kubelet is deployed there is currently no way to monitor the size and thus the amount of logs written by a Kubernetes cluster's pods/containers.

**Special notes for your reviewer**:

This is not technically a feature, but more of a small enhancement for monitoring logs, in my opinion it should be fine to merge for 1.13 as long as it merges until code-freeze.

**Does this PR introduce a user-facing change?**:

Not an end-user facing change, but an additional metrics to be used for monitoring by cluster admins.

```release-note
Add `kubelet_container_log_size_bytes` metric representing the log file size of a container.
```

/sig instrumentation

@kubernetes/sig-instrumentation-pr-reviews 
@kubernetes/sig-node-pr-reviews

2018-11-07 15:43 UTC, derekwaynecarr commented
/assign @derekwaynecarr 

i am wondering why we would not put some of this logic in cri stats provider so we can avoid listing containers all over code base, i need to take a deeper look to know pros/cons.

2018-11-07 15:56 UTC, metalmatze commented on pkg/kubelet/logs/metrics.go
> +		ch <- prometheus.MustNewConstMetric(descLogSize, prometheus.GaugeValue, float64(info.Size()), podMetadata.GetNamespace(), podMetadata.GetName(), container.GetMetadata().GetName(), id)
small nit: would you mind putting this across multiple lines? Thanks.

2018-11-07 18:08 UTC, brancz commented
I did indeed find something in the cri stats provider so I will rework this PR to reuse that logic.

2018-11-09 14:44 UTC, derekwaynecarr requested changes
a structural change, otherwise this is good for me.

2018-11-09 14:44 UTC, derekwaynecarr commented on pkg/kubelet/kubelet.go
> +		prometheus.MustRegister(klet.StatsProvider.Collector())
typically, we have put registration of collectors under kubelet/metrics/metrics.go, see the Register function there.

Can you move this under `initializeModules` where it `calls metrics.Register` and pass in the additional collector?

2018-11-12 19:33 UTC, brancz commented
/retest

2018-11-13 07:59 UTC, brancz commented
/test pull-kubernetes-local-e2e-containerized

2018-11-13 12:22 UTC, nikopen commented
/milestone v1.13

/priority important-soon

2018-11-13 14:47 UTC, merged