Add ProgressDeadlineSeconds to Job
kubernetes/kubernetes pull request #71563
Opened 2018-11-29 14:42 UTC by goodluckbot

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add ProgressDeadlineSeconds to Job, to deal with the situation when a job does not start within given time.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58384

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
progressDeadlineSeconds is added to JobSpec
```

2019-01-17 14:52 UTC, soltysh requested changes
I left you some comments. Also you'll need to open an issue in https://github.com/kubernetes/enhancements/ and accompanying KEP detailing the current feature. 
@kubernetes/api-approvers ptal since this is extending API

2019-01-17 14:52 UTC, soltysh commented on pkg/apis/batch/types.go
> +	// Optional duration in seconds relative to the startTime that the job needs to become active,
Explain in more details what it means for a job to become active.

2019-01-17 14:52 UTC, soltysh commented on pkg/controller/job/job_controller.go
> +		// enqueue a sync to check if job past ProgressDeadlineSeconds
Since this check is only for start move that to the top. I don't want that to be confused with other deadlines.

2019-01-17 14:52 UTC, soltysh commented on pkg/controller/job/job_controller.go
> +		failureReason = "ProgressDeadlineExceeded"
Use `DeadlineExceeded` too

2019-01-17 14:52 UTC, soltysh commented on pkg/controller/job/job_controller.go
> +		failureMessage = "Job has not started before ProgressDeadline"
Job has not started before progress deadline

2019-01-17 14:52 UTC, soltysh commented on pkg/controller/job/job_controller.go
> +func pastProgressDeadline(job *batch.Job) bool {
Squash this and `pastActiveDeadline` into one and pass `job.Spec.ProgressDeadlineSeconds` or `job.Spec.ActiveDeadlineSeconds` accordingly.

2019-02-15 05:38 UTC, liggitt commented
Thanks for the PR. API changes need an associated KEP. See https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md for details

/hold

2019-07-08 15:31 UTC, dims commented
/uncc

2019-12-05 16:58 UTC, closed without merging

2020-04-27 09:48 UTC, JacksChoco commented
Is this stopped?