add subcommand `kubectl create cronjob`
kubernetes/kubernetes pull request #71651
Opened 2018-12-03 07:23 UTC by Pingan2017

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71511

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
add subcommand `kubectl create cronjob`
```

2018-12-04 11:34 UTC, Pingan2017 commented
/assign @brendandburns

2018-12-10 06:31 UTC, Pingan2017 commented on pkg/kubectl/cmd/create/create_cronjob.go
> +		kubectl create cronjob test-job --iamge=busybox --schedule="*/1 * * * *"`)
updated. Thanks!

2018-12-10 06:33 UTC, Pingan2017 commented
ping @soltysh @smarterclayton @brendandburns for review, Thanks!

2019-01-17 15:01 UTC, soltysh requested changes
Left you some comments

2019-03-06 19:30 UTC, soltysh approved these changes
/lgtm
/approve
/ok-to-test
/priority important-longterm
/sig cli

2019-03-07 04:30 UTC, Pingan2017 commented
/test pull-kubernetes-e2e-gce-100-performance

2019-03-07 09:04 UTC, Pingan2017 commented
/test pull-kubernetes-e2e-gce

2019-03-07 09:07 UTC, merged