Increases sleep period for pods used for max backoff tests
kubernetes/kubernetes pull request #71950
Opened 2018-12-11 13:02 UTC by bclau

**What type of PR is this?**

/kind failing-test
/kind flake

/sig testing
/sig windows

**What this PR does / why we need it**:

Kubelet might miss reporting the new Running state when restarting
a pod after its backoff period expired, and thus, the pod will
continue to remain in CrashLoopBackOff state, causing the
"should cap back-off at MaxContainerBackOff" and
"should have their auto-restart back-off timer reset on image update"
tests to fail, since they're waiting the Pods to enter a Running state.

**Which issue(s) this PR fixes**:

Fixes #71949

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2018-12-11 13:11 UTC, bclau commented
/assign @zmerlynn

2018-12-11 16:55 UTC, PatrickLang commented
/lgtm

2018-12-11 19:59 UTC, bclau commented
/test pull-kubernetes-e2e-kops-aws

2018-12-14 21:57 UTC, yujuhong requested changes
Can we get a better understanding of why this is slower on Windows, before bumping the timeout?

2018-12-24 17:05 UTC, benmoss commented
I have tried reproducing this problem on my cluster and haven't seen it fail. How often do you all see this failure?

2019-01-23 01:19 UTC, PatrickLang commented
/milestone v1.14

2019-01-24 12:05 UTC, bclau commented
/test pull-kubernetes-e2e-kops-aws

2019-01-24 19:48 UTC, oomichi commented
The reason why this bumps the timeout to 10sec is the sleep time is 10 sec as syncLoopFrequency before waiting Running status of the pod like https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/pods.go#L647-L648 , right?
I also am not sure this yet, it is better to describe the e2e operation log which includes
```
"getRestartDelay: restartCount = %d, finishedAt=%s restartedAt=%s (%s)"
```
on the issue report or this change message to share that.

2019-01-24 19:48 UTC, oomichi commented
cc @oomichi

2019-03-01 17:39 UTC, nikopen commented
@bclau  @yujuhong any chance this is merged in the following 2 weeks? 
Code Freeze is in effect from next Friday.

2019-03-01 19:11 UTC, bclau commented
So, from what I've seen, this only happens when using azure-vnet-cni, including the latest release v1.0.18-rc1. This problem does not occur when using flannel l2bridge or overlay.

So, basically what happens is this:

- pod sandbox is setup.
- container image is pulled,
- container is created.
- container is **started**.
- the CNI plugin is called to setup the container's networking (HotAttaching the endpoint to the running container)
- Finally, after all that is done, the Container **should** be put in the Running state. But, because the previous step can take a few seconds, the Container finishes its execution before the endpoint is attached, so the state transition is ContainerStarting -> Terminated instead of ContainerStarting -> Running.

The test explicitly expects the the Container to enter a Running state and that the RestartCount to be incremented. IMO, just checking if the RestartCount increased should be sufficient. If it is not sufficient, this sleep period increase is long enough for the CNI operation to finish and the ContainerStarting -> Running state transition to occur.

2019-03-04 21:05 UTC, benmoss commented
Why does it only happen on the Azure CNI?

2019-03-04 22:26 UTC, spiffxp commented
>This sleep period increase is long enough for the CNI operation to finish and the ContainerStarting -> Running state transition to occur.

I feel like we're not happy with the idea of introducing a sleep just to get a test to pass.  Here lies the path to unending tests and more flakes.

>IMO, just checking if the RestartCount increased should be sufficient. 

This sounds like it could be better, what would this change look like?

2019-03-05 02:58 UTC, yujuhong commented
> * Finally, after all that is done, the Container **should** be put in the **Running** state. But, because the previous step can take a few seconds, the Container finishes its execution before the endpoint is attached, so the state transition is ContainerStarting -> Terminated instead of ContainerStarting -> Running.

@bclau the container you mentioned here, is it the regular user container or the pod sandbox? 

I don't understand fully why container would go into the terminated state *and then* became running. Could you explain a little bit more on what caused the state transition for the container?

2019-03-05 10:23 UTC, bclau commented
> 
> > IMO, just checking if the RestartCount increased should be sufficient.
> 
> This sounds like it could be better, what would this change look like?

I amended the commit. Now getRestartDelay waits for the next Terminated state instead of the next Running state (which can be missed). It is still a simple change and it makes it more reliable. See test run: https://paste.ubuntu.com/p/d2PckYv3BR/

> 
> 
> > * Finally, after all that is done, the Container **should** be put in the **Running** state. But, because the previous step can take a few seconds, the Container finishes its execution before the endpoint is attached, so the state transition is ContainerStarting -> Terminated instead of ContainerStarting -> Running.
> 
> @bclau the container you mentioned here, is it the regular user container or the pod sandbox?
> 
> I don't understand fully why container would go into the terminated state _and then_ became running. Could you explain a little bit more on what caused the state transition for the container?

The user container.

I never said it enters the (Kubernetes) ``Running`` state after entering the (Kubernetes) ``Terminated`` state.

There is a **distinction** between the container being started and running and the reported ``Running`` pod state in Kubernetes and they should not be confused with each other, they are not the same. I have already explained the steps that occur when spawning a new pod.

Basically, if the Container's command finishes fast enough, it might terminate before the Kubernetes ``Running`` state could be observed.

And just an FYI, because of this issue, the test is currently flaky on gce-windows: https://testgrid.k8s.io/sig-windows#gce-windows-master

2019-03-05 12:36 UTC, bclau commented
/priority important-soon

2019-03-05 19:56 UTC, yujuhong commented
The current fix looks reasonable.
/lgtm

2019-03-05 21:40 UTC, yujuhong approved these changes

2019-03-05 23:14 UTC, spiffxp commented
/approve
I was waiting for @yujuhong's take on this, thanks for your patience all

2019-03-06 01:10 UTC, michmike commented
nice fix @bclau

2019-03-06 08:21 UTC, nikopen commented
/retest

2019-03-06 11:26 UTC, merged