Bump golang to 1.11.3 (CVE-2018-16875)
kubernetes/kubernetes pull request #72035
Opened 2018-12-14 00:21 UTC by seemethere

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/72032

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2018-12-14 02:12 UTC, cblecker commented
@seemethere Has the Docker Hub tag for golang:1.11.3 been pushed yet?

/assign cblecker ixdy 
/uncc jbeda

2018-12-14 02:17 UTC, cblecker commented
We also need to bump the rules_go version. The new tags are in the referenced issue.

2018-12-14 02:31 UTC, seemethere commented
Yup images for amd64 we're pushed around 3pm PST

2018-12-14 06:17 UTC, ixdy commented
yeah, can you please bump rules_go (in the `WORKSPACE` file) to 0.16.4?

2018-12-14 17:07 UTC, seemethere commented
@cblecker @ixdy just pushed with `rules_go` updated to `0.16.4`

2018-12-14 17:15 UTC, cblecker requested changes

2018-12-14 17:15 UTC, cblecker commented on build/root/WORKSPACE
>      sha256 = "f87fa87475ea107b3c69196f39c82b7bbf58fe27c62a338684c20ca17d1d8613",
This also needs to be updated with the new hash of the new file.

2018-12-14 17:47 UTC, ixdy commented
also `test/images/Makefile`?

we definitely specify the Go version in too many places :\

/ok-to-test

2018-12-14 17:53 UTC, ixdy commented
I'm working on building the crossbuild image now.

2018-12-14 17:53 UTC, ixdy commented on build/root/WORKSPACE
> +    sha256 = "62ec3496a00445889a843062de9930c228b770218c735eca89c67949cd967c3f"
oh, a comma was dropped here

2018-12-14 17:58 UTC, seemethere commented on build/root/WORKSPACE
> +    sha256 = "62ec3496a00445889a843062de9930c228b770218c735eca89c67949cd967c3f"
re-added the comma

2018-12-14 18:11 UTC, ixdy commented
The cross-build image is failing to build:
```
```Step 7/12 : RUN echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" > /etc/apt/sources.list.d/cgocrosscompiling.list   && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32   && apt-get update   && apt-get install -y build-essential   && for platform in ${KUBE_DYNAMIC_CROSSPLATFORMS}; do apt-get install -y crossbuild-essential-${platform}; done   && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Running in 540f2d08fdbf
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.WdHS7PRkq5/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32
gpg: cannot open '/dev/tty': No such device or address
The command '/bin/sh -c echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" > /etc/apt/sources.list.d/cgocrosscompiling.list   && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32   && apt-get update   && apt-get install -y build-essential   && for platform in ${KUBE_DYNAMIC_CROSSPLATFORMS}; do apt-get install -y crossbuild-essential-${platform}; done   && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2
Makefile:24: recipe for target 'build' failed```
```

I'm not sure what is wrong. I can't build `cross-build:v1.11.2-1` anymore either, so I don't think it's related to this change.

2018-12-14 18:15 UTC, ixdy commented
aha, just found https://stackoverflow.com/questions/53371626/apt-key-command-works-on-shell-but-fails-on-dockerfile.

Can you add `--no-tty` to the `apt-key` command in the Dockerfile?

basically this:
```patch
diff --git a/build/build-image/cross/Dockerfile b/build/build-image/cross/Dockerfile
index 8e4bc0f884..70e42cf87e 100644
--- a/build/build-image/cross/Dockerfile
+++ b/build/build-image/cross/Dockerfile
@@ -44,7 +44,7 @@ RUN apt-get update \
 # Use dynamic cgo linking for architectures other than amd64 for the server platforms
 # To install crossbuild essential for other architectures add the following repository.
 RUN echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" > /etc/apt/sources.list.d/cgocrosscompiling.list \
-  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32 \
+  && apt-key adv --no-tty --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32 \
   && apt-get update \
   && apt-get install -y build-essential \
   && for platform in ${KUBE_DYNAMIC_CROSSPLATFORMS}; do apt-get install -y crossbuild-essential-${platform}; done \
```

2018-12-14 18:33 UTC, seemethere commented
/retest

2018-12-14 22:01 UTC, cblecker commented
/retest

2018-12-14 22:03 UTC, cblecker approved these changes

2018-12-15 00:13 UTC, ixdy commented
/lgtm
/priority important-soon

2018-12-15 00:13 UTC, ixdy commented
/approve

2018-12-15 01:28 UTC, merged