refactor(scheduler): Move priority types to priorities package
kubernetes/kubernetes pull request #72079
Opened 2018-12-15 13:10 UTC by sonasingh46

**What this PR does / why we need it**:
This moves the priority types from the algorithm package
to priorities package.
Idea is to move the type to the packages where it is
implemented. This will ease the future refactor process.

**What type of PR is this?**
/kind cleanup
/sig scheduling

**Which issue(s) this PR fixes**:
This fixes #71865 

**Does this PR introduce a user-facing change?**:
 "NONE"

2018-12-15 13:13 UTC, sonasingh46 commented
/assign @misterikkit

2018-12-16 01:44 UTC, wgliang commented on pkg/scheduler/algorithm/priorities/types.go
> +/*Copyright 2016 The Kubernetes Authors.
2016-> 2018

2018-12-16 01:44 UTC, wgliang commented
/ok-to-test
/release-note-none

2018-12-16 10:04 UTC, sonasingh46 commented on pkg/scheduler/algorithm/priorities/types.go
> +/*Copyright 2016 The Kubernetes Authors.
Done

2018-12-17 07:33 UTC, denkensk commented on pkg/scheduler/algorithm/priorities/types_test.go
> +	"testing"
move "testing" to top

2018-12-17 19:38 UTC, misterikkit requested changes
You will need to update all the call sites to use the new import path, and then run `./hack/update-bazel.sh` to fix the BUILD files.

2018-12-22 02:12 UTC, misterikkit requested changes
lgtm overall

one minor comment about import alias

please squash commits and then let's get it approved and merged.

(People might not be around next week to approve, but who knows?)

2018-12-22 09:43 UTC, sonasingh46 commented on pkg/scheduler/core/extender_test.go
> +	algorithmpriorities "k8s.io/kubernetes/pkg/scheduler/algorithm/priorities"
fixed

2018-12-22 10:04 UTC, sonasingh46 commented
/test pull-kubernetes-integration

2018-12-22 10:05 UTC, sonasingh46 commented
/retest

2019-01-02 21:10 UTC, misterikkit approved these changes
/lgtm

Let's get this rebased and approved! :confetti_ball:

2019-01-08 19:44 UTC, sonasingh46 commented
/retest

2019-01-13 20:56 UTC, sonasingh46 commented
/retest

2019-01-14 02:16 UTC, wgliang commented
/lgtm

2019-01-14 22:41 UTC, misterikkit approved these changes
/lgtm
/assign @bsalamat @k82cn for approval

2019-01-15 04:10 UTC, ravisantoshgudimetla approved these changes
Thanks @sonasingh46 for the cleanup

/approve

2019-01-15 17:24 UTC, merged