Fixes #68026: revise some errors about golint in audit packages #68113
kubernetes/kubernetes pull request #72189
Opened 2018-12-19 07:19 UTC by mourya007

What this PR does / why we need it:

According to this issue: #68026, I revise some errors about golint in audit ptackages as below

 staging/src/k8s.io/apiserver/pkg/audit
 staging/src/k8s.io/apiserver/pkg/audit/policy

Which issue(s) this PR fixes :

Ref #68026

2018-12-20 23:45 UTC, fedebongio commented
/cc @wenjiaswe

2018-12-20 23:46 UTC, wenjiaswe requested changes

2018-12-20 23:46 UTC, wenjiaswe commented on staging/src/k8s.io/apiserver/pkg/audit/policy/reader.go
> +	poicy := &auditinternal.Policy{}
This looks like a typo to me?

2018-12-20 23:47 UTC, wenjiaswe commented
/kind cleanup
/priority backlog

2018-12-20 23:50 UTC, wenjiaswe commented
/release-note-none

2018-12-22 17:54 UTC, liggitt commented
/ok-to-test

2018-12-26 08:11 UTC, mourya007 commented
/retest

2018-12-26 08:41 UTC, mourya007 commented
/test pull-kubernetes-verify

2019-01-07 04:41 UTC, mourya007 commented
/retest

2019-01-08 22:59 UTC, riaan53 commented
Hi @mourya007 , I noticed that there are some spaces in the middle of some of your comments and that some ends with a `.` and some dont. It looks like the standard is without `.`

2019-01-11 08:47 UTC, mourya007 commented
/retest

2019-07-25 00:32 UTC, closed without merging