Add request processing HPA into the queue after processing is finished.
kubernetes/kubernetes pull request #72373
Opened 2018-12-27 16:24 UTC by krzysztof-jastrzebski

This fixes a bug whth skipping request inserted by resync because previous one hasn't processed yet.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes a bug with skipping request inserted by resync because previous one hasn't processed yet.
**Which issue(s) this PR fixes**:

Fixes #72372

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2018-12-27 16:34 UTC, krzysztof-jastrzebski commented on pkg/controller/podautoscaler/horizontal.go
> +func (a *HorizontalController) reconcileKey(key string) (err error, deleted bool) {
done

2018-12-27 16:42 UTC, mwielgus commented
How was this PR tested?

2018-12-27 16:48 UTC, krzysztof-jastrzebski commented
I've created K8s build with debugs showing when HPAs are processed, created cluster and HPA. I observed how often HPA is updated. Next I removed HPA just after HPA was processed and verified that HPA is not processed anymore.

2018-12-27 16:48 UTC, mwielgus commented
/lgtm

2018-12-27 16:49 UTC, mwielgus commented
/ok-to-test

2018-12-28 07:46 UTC, krzysztof-jastrzebski commented
HPA controller uses rate limiter which always returns ResyncPeriod (currently 15 seconds).
Rate Limiter:
https://github.com/kubernetes/kubernetes/blob/16fb54ef7c10e3865ef5f0af69b2479a084b85c5/pkg/controller/podautoscaler/rate_limiters.go#L38
Creation:
https://github.com/kubernetes/kubernetes/blob/a6ba2ebf85d8673f78220c089aba1290437de2be/pkg/controller/podautoscaler/horizontal.go#L120
In that case every request inserted to queue waits 15 seconds in the queue. If we insert one request then it stays in queue for 15 seconds and all request inserted during 15 seconds are skipped as they would be executed after request which is in queue. After 15 seconds next request can be inserted and it also stays in queue for 15 seconds etc.
All redundant request are skipped, HPA is updated at most every 15 seconds.

I see this is not the best way of using RateLimitingQueue but I would like to do small fix so I can backport it to 1.12. If you think we should use  queue in other way then I'm happy to fix it next PR. Do you have any suggestion how to do that?

2018-12-28 07:47 UTC, krzysztof-jastrzebski commented on pkg/controller/podautoscaler/horizontal.go
> +	if !deleted {
yes, see comment below

2018-12-28 19:36 UTC, liggitt commented
This is a strange use of the rate limiting queue trying to achieve tight guarantees about retry interval.

I'm concerned about doubling the number of queue insertions for systems with large numbers of HPAs. Attempting to enqueue all HPAs in the system every 15 seconds is already very aggressive... this change would attempt to enqueue them all twice every 15 seconds.

Until the structure of this controller can be revisited, can we do something simpler and less likely to impact performance like one of the following:
* set up the HPA `AddEventHandlerWithResyncPeriod` with `resyncPeriod+time.Second`
* set up `NewDefaultHPARateLimiter(resyncPeriod-time.Second)`

Either of those approaches would give `delayingType#waitingLoop` a second to move ready HPA items from `waitingForQueue` into the queue. If that takes longer than a second (for example, under load), HPA processing could still skip a resync interval, but that actually seems like a better outcome to me than doubling queue attempts in pursuit of exact retry intervals.

2018-12-28 21:05 UTC, krzysztof-jastrzebski commented
I was thinking about similar solution. The problem with it is why to add/subtract 1 second. resyncPeriod is defined by a flag. Default is 15 seconds but someone can use 1 second resuncPeriod. If we added 1 second then HPAs would be refreshed every 2 seconds instead of 1, we would also process HPA on every change of the objects (rate limiter set to 0) which can be in some cases very often. 
I don't think that adding HPA to queue after processing it is a problem as current implementation of HPA(it is single-threaded) can process less than 10 HPAs per second. Adding 10 request every second to local queue shouldn't be a big deal.

2019-01-02 17:39 UTC, liggitt commented
> Default is 15 seconds but someone can use 1 second resyncPeriod. If we added 1 second then HPAs would be refreshed every 2 seconds instead of 1, we would also process HPA on every change of the objects (rate limiter set to 0) which can be in some cases very often.

Setting a 1 second resyncPeriod isn't likely to work well in general, but I agree we wouldn't want to drop that to 0. Setting to a percentage or capping at a minimum value would prevent that.

Unconditional requeuing is confusing to anyone who is familiar with all the other controllers. I'd prefer the smallest change we can make that doesn't take this controller even further away from standard usage of the queue components, so I'm not in favor of the current PR, but will defer to @kubernetes/sig-autoscaling-pr-reviews 

/hold cancel

2019-01-04 00:42 UTC, DirectXMan12 requested changes
can you expand a bit on why this occurs in the comment?  Use your example from above

2019-01-04 00:42 UTC, DirectXMan12 commented on pkg/controller/podautoscaler/horizontal.go
> +	deleted, err := a.reconcileKey(key.(string))
you should still have a comment as to why we're not forgetting the key, since this works significantly different from normal controllers.

2019-01-04 00:43 UTC, DirectXMan12 commented
please also fix the PR description to remove the unused flags.

2019-01-04 00:46 UTC, DirectXMan12 commented
I'm inclined to go with @liggitt's suggestion short-term, and think up a better long-term fix (e.g. don't watch HPA, and instead just reconcile every 15 seconds, staggered, or something).

2019-01-04 11:01 UTC, krzysztof-jastrzebski commented
@mwielgus done

2019-01-04 11:46 UTC, krzysztof-jastrzebski commented
/test pull-kubernetes-e2e-kops-aws
/test pull-kubernetes-kubemark-e2e-gce-big

2019-01-04 11:57 UTC, krzysztof-jastrzebski commented
/test pull-kubernetes-e2e-gce-100-performance

2019-01-04 12:34 UTC, krzysztof-jastrzebski commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-01-04 13:09 UTC, krzysztof-jastrzebski commented
/test pull-kubernetes-e2e-gce-100-performance

2019-01-04 14:12 UTC, mwielgus commented
/lgtm

2019-01-04 19:09 UTC, merged