kubeadm selfhosting: fix pod spec mutation for controller-mamanger
kubernetes/kubernetes pull request #72518
Opened 2019-01-03 13:42 UTC by bart0sh

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Modified command line options --authentication-kubeconfig and
--authorization-kubeconfig to point out to the correct location
of the controller-manager.conf

This should fix this controller-manager crash:
```
    failed to get delegated authentication kubeconfig: failed to get
    delegated authentication kubeconfig: stat
    /etc/kubernetes/controller-manager.conf: no such file or directory
```

Related issue: kubernetes/kubeadm#1281

**Special notes for your reviewer**:

This is a second commit of a series aiming to fix kubernetes/kubeadm#1281

**Does this PR introduce a user-facing change?**:
```release-note
kubeadm: fixed incorrect controller manager pod mutations during selfhosting pivoting
```

2019-01-03 13:44 UTC, bart0sh commented
/cc @neolit123

2019-01-03 13:47 UTC, neolit123 approved these changes
LGTM but i will leave the review to others.

/cc @fabriziopandini @ereslibre

2019-01-03 13:48 UTC, neolit123 commented
/priority backlog

2019-01-03 15:11 UTC, yagonobre approved these changes
lgtm

2019-01-03 16:47 UTC, ereslibre approved these changes
LGTM

2019-01-04 08:45 UTC, fabriziopandini requested changes
@bart0sh 
I'm ok with the change but I think that this behavior must be supervised by a unit test in `TestMutatePodSpec`. Do you agree?

2019-01-07 13:02 UTC, fabriziopandini commented
@bart0sh great! if you can squash the two commits then I will lgtm & approve

2019-01-07 13:21 UTC, bart0sh commented
@fabriziopandini done

2019-01-07 13:38 UTC, fabriziopandini commented
thanks!
/approve
/lgtm

2019-01-07 13:50 UTC, fabriziopandini commented
/test pull-kubernetes-integration

2019-01-07 13:56 UTC, bart0sh commented
/test pull-kubernetes-integration

2019-01-07 20:09 UTC, merged