Delete predicates.PodToleratesNodeTaintsPred from defaultPredicates
kubernetes/kubernetes pull request #72812
Opened 2019-01-11 09:21 UTC by ping035627

**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
I think predicates.PodToleratesNodeTaintsPred should be controlled by features.TaintNodesByCondition, and it should be deleted from defaultPredicates.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

/release-note-none
/priority backlog

2019-01-11 13:45 UTC, wgliang commented
@ping035627 Why is there such a change?

2019-01-11 13:45 UTC, wgliang commented
/hold

2019-01-11 14:21 UTC, ping035627 commented
@wgliang I think predicates.PodToleratesNodeTaintsPred should be controlled by features.TaintNodesByCondition, needn't add to defaultPredicates.

2019-01-11 17:36 UTC, bsalamat requested changes
We do need this predicate. It cannot be deleted.

2019-01-11 23:06 UTC, ping035627 commented
When features.TaintNodesByCondition is opened, we will add the predicate, why need to add it to the default?

2019-01-11 23:32 UTC, ping035627 commented
@bsalamat  When features.TaintNodesByCondition is opened predicates, we removed the predictes.CheckNodeConditionPred and add the predicates.PodToleratesNodeTaintsPred. It means either PodToleratesNodeTaintsPred or CheckNodeConditionPred, so the defaultPredicates needn't add PodToleratesNodeTaintsPred, I think. Avoid redundancy.

2019-01-12 02:15 UTC, ping035627 commented
I know what the PodToleratesNodeTaintsPred do, I just think PodToleratesNodeTaintsPred should be controlled by features.TaintNodesByCondition. Just when features.TaintNodesByCondition is turned on, we add PodToleratesNodeTaintsPred, we needn't add it to defaultPredicates.

2019-01-12 02:56 UTC, ping035627 commented
predicates.PodToleratesNodeTaintsPred add to defaultPredicates, it means PodToleratesNodeTaintsPred will be work anytime when DefaultProvider, then why use features.TaintNodesByCondition? they use the same predicatesFuns. If they are different predicatesFuns, it will be understand easily.

2019-01-17 21:47 UTC, resouer requested changes
> I know what the PodToleratesNodeTaintsPred do, I just think PodToleratesNodeTaintsPred should be controlled by features.TaintNodesByCondition. Just when features.TaintNodesByCondition is turned on, we add PodToleratesNodeTaintsPred, we needn't add it to defaultPredicates.

> predicates.PodToleratesNodeTaintsPred add to defaultPredicates, it means PodToleratesNodeTaintsPred will be work anytime when DefaultProvider, then why use features.TaintNodesByCondition? they use the same predicatesFuns. If they are different predicatesFuns, it will be understand easily.

PodToleratesNodeTaintsPred and TaintNodesByCondition are totally two different things, the later is not even a predicate ...

2019-01-18 00:49 UTC, ping035627 commented
@resouer, I know they are two different things, I just think PodToleratesNodeTaintsPred should be controlled by features.TaintNodesByCondition. If not, why use features.TaintNodesByCondition? Can you explain? I'm a little confused. Thanks very much.

2019-01-25 18:41 UTC, bsalamat commented
> @resouer, I know they are two different things, I just think PodToleratesNodeTaintsPred should be controlled by features.TaintNodesByCondition. If not, why use features.TaintNodesByCondition? Can you explain? I'm a little confused. Thanks very much.

`PodToleratesNodeTaintsPred` is the predicate for taints and tolerations which is the main feature to support taints. `TaintNodesByCondition` is a different feature that uses taints and tolerations. `TaintNodesByCondition` is not a really a scheduler feature. It is actually a node feature. `TaintNodesByCondition` should not be confused with taints and tolerations.

2019-01-28 01:49 UTC, ping035627 commented
@bsalamat oh, I understand now, thanks for your explanation. I will close this pr.

2019-01-28 01:49 UTC, closed without merging