Fix Kubelet hostAliases should write entries to /etc/hosts test
kubernetes/kubernetes pull request #72869
Opened 2019-01-13 07:35 UTC by povilasv

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
When running a pod with HostAliases and checking whether hosts file contains specified hostnames, conformance test checks for:
```
123.45.67.89   foo bar
```
but this version is also valid:
```
123.45.67.89   foo
123.45.67.89   bar
```

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-01-16 08:36 UTC, k-toyoda-pi commented
My test environment's pod has only "123.45.67.89    foo     bar".
Therefore, I think that it is not necessary to check "123.45.67.89   foo" and "123.45.67.89   bar".
Does your test fail?

2019-01-16 08:40 UTC, povilasv commented
> My test environment's pod has only "123.45.67.89 foo bar".
> Therefore, I think that it is not necessary to check "123.45.67.89 foo" and "123.45.67.89 bar".
> Does your test fail?

Yup I get this output on a kubeadm setup'ed cluster:

```
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:699
Timed out after 60.000s.
Expected
    <*errors.errorString | 0xc001479a50>: {
        s: "expected hosts file to contain entries from HostAliases. Got:\n# Kubernetes-managed hosts file.\n127.0.0.1\tlocalhost\n::1\tlocalhost ip6-localhost ip6-loopback\nfe00::0\tip6-localnet\nfe00::0\tip6-mcastprefix\nfe00::1\tip6-allnodes\nfe00::2\tip6-allrouters\n192.168.3.12\tbusybox-host-aliases2a5b7d18-1681-11e9-a614-5e73695a6c15\n\n# Entries added by HostAliases.\n123.45.67.89\tfoo\n123.45.67.89\tbar\n",
    }
to be nil
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/kubelet.go:183
```

2019-01-16 19:52 UTC, oomichi commented
/ok-to-test

2019-01-16 20:00 UTC, oomichi reviewed
HostAliases entry format has been changed since https://github.com/kubernetes/kubernetes/commit/ab507dfc1f0c824386ea6ca0efc1abe7968981fd
On the commit, the e2e test code also is changed.
So I guess you are running different versions between your target k8s cluster and e2e test code on conformance test.

2019-01-16 20:03 UTC, oomichi requested changes
The above comment means we don't need this change, if we are using the same versions.

2019-01-16 20:19 UTC, oomichi commented
BTW the official doc gets old, https://github.com/kubernetes/website/pull/12251 could update it.

2019-01-17 19:01 UTC, povilasv commented
> HostAliases entry format has been changed since [ab507df](https://github.com/kubernetes/kubernetes/commit/ab507dfc1f0c824386ea6ca0efc1abe7968981fd)
> On the commit, the e2e test code also is changed.
> So I guess you are running different versions between your target k8s cluster and e2e test code on conformance test.

Yeah, that was the issue thanks!

From the conformance standpoint shouldn't we be checking that the host aliases are populated rather than the specific way it's done?

I'll close the PR, if it's not needed. Thanks again for the help!

2019-01-17 19:01 UTC, closed without merging

2019-01-30 12:05 UTC, dims commented
/area conformance