Mark the kubectl flag as alpha
kubernetes/kubernetes pull request #73228
Opened 2019-01-23 22:43 UTC by apelisse

**What type of PR is this?**
/kind feature
/sig api-machinery
/priority important-soon
/assign @jennybuckley @kwiesmueller 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2019-01-24 03:57 UTC, apelisse commented
@soltysh

2019-01-24 12:51 UTC, soltysh requested changes

2019-01-24 12:51 UTC, soltysh commented on pkg/kubectl/cmd/util/helpers.go
> +	cmd.Flags().Bool("server-side", false, "ALPHA -- If true, apply runs in the server instead of the client.")
Change this to `This is an alpha feature and flag` similarly to how we do it in https://github.com/kubernetes/kubernetes/blob/00eab3c40bcda9ee73eac060242d36602e627fec/pkg/kubectl/cmd/apply/apply.go#L179

2019-01-24 12:52 UTC, soltysh commented
> @soltysh do you mind looking at this? Bear in mind that this is for the feature branch and we're trying to get the branch back in master by the end of the week, thanks

Yup, I'm about to look into it too :)

2019-01-25 14:37 UTC, soltysh approved these changes
/lgtm

2019-01-25 14:39 UTC, merged