fix smb remount issue on Windows
kubernetes/kubernetes pull request #73661
Opened 2019-02-02 12:54 UTC by andyzhangx

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix smb remount issue on Windows
Without this PR, smb remount on same windows node would fail since original mount already exists

**Which issue(s) this PR fixes**:

Fixes #73087

**Special notes for your reviewer**:
 - move part of the code from `mounter.Mount` func and add following code to check check whether remotepath has already been mapped
```
		cmd := exec.Command("powershell", "/c", `Get-SmbGlobalMapping -RemotePath $Env:smbremotepath`)
		cmd.Env = append(os.Environ(), fmt.Sprintf("smbremotepath=%s", remotepath))
		output, err = cmd.CombinedOutput()
```

**Does this PR introduce a user-facing change?**:

```
fix smb remount issue on Windows
```

/sig windows

/assign @msau42 @jsafrane 
cc @jingxu97

2019-02-02 12:56 UTC, andyzhangx commented
/pull-kubernetes-cross

2019-02-05 02:42 UTC, PatrickLang commented
/milestone v1.14

2019-02-06 00:25 UTC, PatrickLang requested changes

2019-02-14 14:21 UTC, andyzhangx commented
/pull-kubernetes-cross

2019-02-14 14:25 UTC, andyzhangx commented
@PatrickLang I have changed the PR according to your comments, test with `delete pod of k8s deployment` on windows shows good

2019-02-15 01:00 UTC, msau42 commented
/assign @jingxu97 
to help take a look

2019-02-15 01:21 UTC, PatrickLang commented
/LGTM
thanks!

2019-02-15 16:13 UTC, jsafrane commented
/approve

2019-02-15 22:05 UTC, merged

2019-04-24 15:00 UTC, andyzhangx commented
this issue is finally fixed in 1.11.8, 1.12.6, 1.13.4, and 1.14.0