kubeadm: graduate kubelet start join phase
kubernetes/kubernetes pull request #73732
Opened 2019-02-05 07:16 UTC by yagonobre

**What this PR does / why we need it**:
Graduate kubelet start phase

**Which issue(s) this PR fixes**:
Refs [kubernetes/kubeadm#1204](https://github.com/kubernetes/kubeadm/issues/1204)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/kind cleanup
/priority important-soon
@kubernetes/sig-cluster-lifecycle-pr-reviews

2019-02-05 11:48 UTC, rosti commented
/assign @fabriziopandini

2019-02-05 15:15 UTC, fabriziopandini requested changes
@yagonobre this is already a great start!
After rebase, please address some nits and whenever possible take advantage of the joinData structure for sharing clients across phases

2019-02-05 15:15 UTC, fabriziopandini commented on cmd/kubeadm/app/cmd/join.go
> +Copyright 2018 The Kubernetes Authors.
2019 😉

2019-02-05 15:15 UTC, fabriziopandini commented on cmd/kubeadm/app/cmd/phases/kubelet.go
>  package phases
This should go under `phases/join`

2019-02-05 15:15 UTC, fabriziopandini commented on cmd/kubeadm/app/cmd/phases/kubelet.go
> +type kubeletStartJoinData interface {
Once this is is in a separated file under `phases\join` this name can be simplified into `kubeletStartData`

2019-02-05 15:15 UTC, fabriziopandini commented on cmd/kubeadm/app/cmd/phases/kubelet.go
> +func NewKubeletStartJoinPhase() workflow.Phase {
Once this is is in a separated file under `phases\join` this name can be simplified into `NewKubeletStartPhase `

2019-02-05 15:15 UTC, fabriziopandini commented on cmd/kubeadm/app/cmd/phases/kubelet.go
> +	bootstrapClient, err := kubeconfigutil.ClientSetFromFile(bootstrapKubeConfigFile)
might be I'm wrong, but joinData should always carry a client created using the bootstrapKubeConfigFile. If this is the case, please use it

2019-02-05 15:15 UTC, fabriziopandini commented on cmd/kubeadm/app/cmd/phases/kubelet.go
> +	client, err := kubeconfigutil.ClientSetFromFile(kubeadmconstants.GetKubeletKubeConfigPath())
This client IMO should be part of joinData, so it can be reused by other phases

2019-02-05 15:15 UTC, fabriziopandini commented on cmd/kubeadm/app/cmd/phases/kubelet.go
> +	klog.V(1).Infoln("[join] writing bootstrap kubelet config file at", bootstrapKubeConfigFile)
s\[join]\[kubelet-start] in all logs + fmt.Printf

2019-02-06 03:38 UTC, yagonobre commented on cmd/kubeadm/app/cmd/phases/join/controlplane.go
> -	ClientSetFromFile(string) (*clientset.Clientset, error)
I removed this because it's not used, and IMO we no need a pr only for that.

2019-02-06 03:39 UTC, yagonobre commented
@rosti @fabriziopandini updated

2019-02-06 20:43 UTC, neolit123 approved these changes
@yagonobre thanks,
sort of delayed on the review but this LGTM.

/lgtm
/approve
/hold

@rosti @fabriziopandini feel free to unhold after a final pass.

2019-02-06 20:49 UTC, fabriziopandini commented
@yagonobre Well done!
/approve
/lgtm

As per @neolit123 comment
/hold cancel

2019-02-06 22:34 UTC, merged