kubectl: error logging as string instead of []byte
kubernetes/kubernetes pull request #73970
Opened 2019-02-12 19:57 UTC by droslean

Changes the error output when duplicate keys found while creating `secret` or `configMap` (BinaryData)

Show the data of the duplicated secret as `string` instead of `[]byte`
Removes error output of binary data in `configMaps`

closes #73969

2019-02-12 19:58 UTC, droslean commented
/release-note-none

2019-02-12 19:59 UTC, droslean commented
/kind bug

2019-02-12 20:02 UTC, droslean commented
/cc @soltysh

2019-02-12 20:19 UTC, soltysh commented
/ok-to-test

2019-02-12 20:33 UTC, dims commented
@soltysh when we have say self signed cert as a secret, will printing as a string still be advisable?

2019-02-12 23:48 UTC, kargakis commented
We should avoid printing secret data altogether

2019-02-13 08:37 UTC, droslean commented
IMHO, I think that we shouldn't include the data from the duplicated key in any case. There is no use for the user, since the data can be different than the other key.

2019-03-20 08:41 UTC, droslean commented
as @dims and @kargakis suggested, I removed showing the secret's data. 

Removing showing the binary's data also solves #73969 bug.

2019-03-20 08:58 UTC, droslean commented
/priority critical-urgent

2019-03-20 09:01 UTC, neolit123 reviewed
i don't think we should print the cm data, too. :)
added some comments on how i think this should look like.

2019-03-20 09:01 UTC, neolit123 commented on pkg/kubectl/generate/versioned/secret.go
> +		return fmt.Errorf("cannot add key %s, another key by that name already exists", keyName)
```
("cannot add key %q, another key by that name already exists in Data for Secret %q in namespace %q",
keyName, secret.Name, secret.Namespace)
```

2019-03-20 09:01 UTC, neolit123 commented
/remove priority-backlog

2019-03-20 09:02 UTC, neolit123 commented
/remove-priority backlog

2019-03-20 09:03 UTC, droslean commented
@neolit123 Thanks for the review. I added the critical priority because of the bug #73969. I will make the changes.

2019-03-20 09:07 UTC, droslean commented on pkg/kubectl/generate/versioned/configmap.go
> +		return fmt.Errorf("cannot add key %s, another key by that name already exists in data with value:\n %v", keyName, configMap.Data)
But this will happen when a new configmap will be created and it will the duplicated `--from-file`. Is it orthogonal to log also the namespace?

2019-03-20 09:15 UTC, neolit123 commented on pkg/kubectl/generate/versioned/configmap.go
> +		return fmt.Errorf("cannot add key %s, another key by that name already exists in data with value:\n %v", keyName, configMap.Data)
i didn't check TBH. if it's created just now, we shouldn't log namespace.

2019-03-20 09:33 UTC, droslean commented on pkg/kubectl/generate/versioned/configmap.go
> +		return fmt.Errorf("cannot add key %s, another key by that name already exists in data with value:\n %v", keyName, configMap.Data)
addressed

2019-03-20 09:34 UTC, dims commented on pkg/kubectl/generate/versioned/configmap.go
> +		return fmt.Errorf("cannot add key %s, another key by that name already exists in data with value:\n %v", keyName, configMap.Data)
i like that @neolit123

2019-03-20 09:37 UTC, dims commented
/assign @janetkuo @soltysh

(for approval)

/lgtm

2019-03-20 09:40 UTC, droslean commented on pkg/kubectl/generate/versioned/configmap.go
> +		return fmt.Errorf("cannot add key %s, another key by that name already exists in data with value:\n %v", keyName, configMap.Data)
the duplicated key can contain different data, so printing the data isn't helpful for the user. I agree with @neolit123

2019-03-20 10:21 UTC, droslean commented
/test pull-kubernetes-verify

2019-03-20 16:06 UTC, soltysh requested changes
/lgtm cancel

2019-03-20 16:06 UTC, soltysh commented on pkg/kubectl/generate/versioned/configmap.go
> +		return fmt.Errorf("cannot add key %s, another key by that name already exists in data with value:\n %v", keyName, configMap.Data)
@droslean let's make this error similar to the others by **not** adding the value in the error. The reason for that is that I frequently work with config maps containing entire configs (longer or shorter), in which case this error might trash my screen with data from that config. Let's make it short and simple, and consistent with other errors by just stating that a duplicate entry exist. If you're curious what's the value check it for yourself.

2019-03-20 16:14 UTC, soltysh approved these changes
My bad, I had old revision of the PR opened in a tab. It's all good now. Sorry for the unnecessary noise.
/lgtm
/approve

2019-03-20 18:08 UTC, merged