Issue #70020; Flush Conntrack entities for SCTP
kubernetes/kubernetes pull request #74073
Opened 2019-02-14 11:33 UTC by uablrek

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Lingering SCTP conntrack entries prevent reestablishment. Please see the issue #70020

**Which issue(s) this PR fixes**:

Fixes #70020

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-02-14 21:35 UTC, dcbw commented
/ok-to-test

2019-02-14 21:36 UTC, dcbw commented
/lgtm

2019-02-25 14:12 UTC, KomorkinMikhail commented
Hi @janosi 
Just letting you know about this PR. Think you will be interested. It's regarding conntrack issue in SCTP.

2019-02-25 14:46 UTC, janosi commented
Hi @KomorkinMikhail,
Thank you for the notification! I appreciate it! Also thank you for the effort @uablrek !

2019-03-04 13:08 UTC, KomorkinMikhail commented
@dcbw @brendandburns 
If you have any questions regarding implementation of this PR do not hesitate to ask me or @uablrek. We are looking forward to merge this one

2019-04-08 12:36 UTC, KomorkinMikhail commented
@dcbw @brendanburns 
Hi guys. Have you had any chance to review the changes? We highly anticipate this fix to be on the main branch.

2019-05-28 12:16 UTC, MaximProshin commented
@dcbw @brendandburns, do you plan to review it? Do you have any forecast?
It seems to be pretty simple correction as the same was fixed for UDP.

2019-07-11 20:55 UTC, dcbw requested changes
@uablrek also needs a rebase to fix the conflict.

2019-07-11 20:55 UTC, dcbw commented on pkg/proxy/iptables/proxier.go
> -
@uablrek unecessary whitespace removal?

2019-07-11 20:55 UTC, dcbw commented on pkg/proxy/iptables/proxier.go
> +		if svcInfo, ok := proxier.serviceMap[epSvcPair.ServicePortName]; ok && (svcInfo.GetProtocol() == v1.ProtocolUDP || svcInfo.GetProtocol() == v1.ProtocolSCTP) {
Might make sense to create a separate function like "needsClearConntrack(proto v1.Protocol) bool" for this and use it in both places here, *and* in proxier_test.go below.

2019-10-10 04:53 UTC, uablrek commented
/remove-lifecycle stale

2019-12-12 22:08 UTC, danwinship commented
@uablrek can you rebase?

2020-03-04 21:34 UTC, aojea commented on pkg/util/conntrack/conntrack.go
> +	if proto == v1.ProtocolUDP || proto == v1.ProtocolSCTP {
nit, I guess this can be reduced to
```
return proto == v1.ProtocolUDP || proto == v1.ProtocolSCTP
```

2020-03-04 21:36 UTC, aojea commented on pkg/util/conntrack/conntrack_test.go
> +			name:   "IPv4 success",
I guess we should update the name of the tests with the protocol to differentiate them

2020-03-04 21:36 UTC, aojea commented on pkg/util/conntrack/conntrack_test.go
> +			name:  "IPv4 success",
ditto, updating the name with the protocol?

2020-03-05 14:28 UTC, aojea commented
/lgtm
/assign @danwinship

2020-03-09 19:31 UTC, danwinship reviewed
just one nit

2020-03-09 19:31 UTC, danwinship commented on pkg/proxy/ipvs/graceful_termination.go
> +			if proto != "UDP" && proto != "SCTP" && rs.ActiveConn+rs.InactiveConn != 0 {
should this use `conntrack.IsClearConntrackNeeded`? it's not quite the same thing, but...

either way, the comment above is wrong now

2020-03-11 08:59 UTC, uablrek commented
Updated after comments and squashed.

2020-03-11 13:50 UTC, aojea commented
/lgtm
/retest

2020-03-11 18:56 UTC, aojea commented
/test pull-kubernetes-e2e-kind

2020-03-17 14:18 UTC, danwinship commented
/approve

2020-03-30 09:01 UTC, uablrek commented
@brendanburns Can you please review so this can be merged?

2020-03-30 09:08 UTC, aojea commented
/assign @thockin 
he's been more active :smile:

2020-04-01 22:13 UTC, thockin reviewed
Thanks!

/lgtm
/approve

2020-04-02 05:14 UTC, merged