Promote DNS e2e verifying DNS resolution for externalName services
kubernetes/kubernetes pull request #74983
Opened 2019-03-05 19:11 UTC by mgdevstack

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Promotes DNS e2e which is verifying DNS resolution behavior for externalName services and clusterIP services.

**Which issue(s) this PR fixes**:

Fixes #73425

**Special notes for your reviewer**:
- Maybe failing for windows.
- Not Flaking
- Promoting to Conformance as it verifies important functional scenario of resolving DNS for services pointing to the external domain and for service of type clusterIP.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/area conformance
/sig testing
@kubernetes/sig-network-pr-reviews

2019-03-07 00:01 UTC, spiffxp commented
/priority important-soon
/lgtm

2019-03-07 22:13 UTC, brahmaroutu commented
/assign @smarterclayton

2019-03-26 21:00 UTC, johnbelamaric requested changes

2019-03-26 21:02 UTC, johnbelamaric commented
/assign

2019-03-27 05:18 UTC, mgdevstack commented on test/e2e/network/dns.go
> +		Description: Create an service with externalName. Pod MUST be able to resolve DNS for this service by serving CNAME. When externalName of this service is changed, Pod MUST resolve to new DNS entry
Thanks for reviewing. Included suggested changes.

2019-03-27 05:18 UTC, mgdevstack commented on test/e2e/network/dns.go
> +		Testname: DNS, for ExternamName Services
Done.

2019-03-27 05:18 UTC, mgdevstack commented on test/e2e/network/dns.go
> +		Release: v1.14
Done.

2019-03-28 11:36 UTC, bclau commented
This test is known to pass on Windows on Azure (azure-vnet-cni), GCE, vsphere, flannel overlay and l2bridge. LGTM.

/lgtm

2019-04-02 19:36 UTC, smarterclayton commented on test/e2e/network/dns.go
> +		Change the service type from externalName to ClusterIP, Pod MUST resolve DNS to the service by serving A records.
This is an excellent description!

2019-04-02 22:02 UTC, johnbelamaric commented
/lgtm

2019-04-12 19:14 UTC, smarterclayton commented
/approve

2019-04-12 21:30 UTC, merged