Promote E2E test to verify job does not exceed activeDeadlineSeconds limit to conformance
kubernetes/kubernetes pull request #75018
Opened 2019-03-06 06:02 UTC by globervinodhn

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: This PR requests to promote the existing e2e test to verify JOB behaviour with respect to "activeDeadlineSeconds" option to conformance. The job should be terminated once "activeDeadlineSeconds" limit is reached. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**: Aas per definition, "The activeDeadlineSeconds applies to the duration of the job, no matter how many Pods are created. Once a Job reaches activeDeadlineSeconds, all of its Pods are terminated and the Job status will become type: Failed with reason: DeadlineExceeded.". The defined behaviour is verified in the concerned E2E test. This PR request to promote the test to conformance. The E2E test takes approximately 8 seconds to execute and is non-flaky and non-disruptive.

**Does this PR introduce a user-facing change?**: NONE

release-note-none

cc @brahmaroutu @mgdevstack 

/area conformance

2019-03-06 07:55 UTC, globervinodhn commented
/release-note-none

2019-03-06 10:32 UTC, mgdevstack commented
/ok-to-test

2019-03-06 21:54 UTC, spiffxp commented
/retest

2019-03-06 22:12 UTC, brahmaroutu commented
/test pull-kubernetes-integration
/test pull-kubernetes-bazel-test

2019-03-07 09:15 UTC, globervinodhn commented
/pull-kubernetes-e2e-gce-100-performance 
/pull-kubernetes-kubemark-e2e-gce-big

2019-03-12 07:19 UTC, globervinodhn commented
Description updated to reflect commit version as v1.15 as the deadline for v1.14 is already breached

2019-03-13 08:33 UTC, mgdevstack requested changes
Test name is a bit ambiguous. Can we change e2e name to something like "should fail when exceeds activeDeadlineSecond"?

Note: Suggesting this name change as in future this may be part of Conformance suite. Name and behavior should be clear to read and understand correctly.

2019-03-13 08:45 UTC, mgdevstack requested changes
Not meeting Conformance requirement [Ref](https://github.com/kubernetes/community/blob/20d3fe4cd54d65f74a13b37d2648ffefa067a4c9/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements) as it is using failure Reason `DeadlineExceeded`.

>Examples of tests which are not eligible for promotion to conformance:

>- anything that checks specific Events are generated, as we make no guarantees about the contents of events, nor their delivery
>- anything that checks optional Condition fields, such as Reason or Message, as these may change over time (however it is reasonable to verify these fields exist or are non-empty)

2019-03-22 01:18 UTC, spiffxp commented
/close
Agree this can't be promoted because it relies on a Reason check, maybe there is other way you can rewrite this test to meet conformance requirements?

2019-03-22 01:18 UTC, closed without merging

2019-03-26 11:35 UTC, mgdevstack commented
>maybe there is other way you can rewrite this test to meet conformance requirements?

xref: https://github.com/kubernetes/kubernetes/issues/75324#issuecomment-476477501

2019-05-07 05:39 UTC, bgrant0607 commented
WaitForJobFailure shouldn't wait for a specific reason