Convert interface type check %#v into %T for clarity and brevity
kubernetes/kubernetes pull request #75574
Opened 2019-03-22 01:48 UTC by smarterclayton

While reviewing the codebase for the use of `%#v` in `fmt.Errorf()`
which recently caused a performance regression there were many places
where we were inconsistent about using %T with type checks. This corrects
most of the controllers and core code to be consistent where the only
info that matters when debugging the problem is what the input type is

/kind cleanup

```release-note
NONE
```

2019-03-22 06:48 UTC, Rajat-0 commented
LGTM

2019-03-22 07:11 UTC, Rajat-0 requested changes

2019-03-22 07:11 UTC, Rajat-0 commented on pkg/controller/job/job_controller.go
> +		utilruntime.HandleError(fmt.Errorf("Couldn't get key for job T: %v", job, err))
nit: %T

2019-03-25 21:01 UTC, caesarxuchao commented
/assign @jennybuckley

2019-03-25 22:14 UTC, jennybuckley commented on pkg/kubectl/polymorphichelpers/helpers.go
> +		return nil, 0, fmt.Errorf("%T is not a pod event", event)
This will always give the type event, it should be event.Object

2019-03-25 22:14 UTC, jennybuckley commented on pkg/controller/certificates/rootcacertpublisher/publisher.go
> +			return nil, fmt.Errorf("Tombstone contained object that is not a ConfigMap %T", obj)
I think it should be tombstone.Obj instead of obj here, and all the other places where a tombstone's contained object is type checked.

2019-05-02 19:11 UTC, smarterclayton commented
Updated, PTAL

2019-09-30 06:02 UTC, closed without merging