Move kubectl apply to staging
kubernetes/kubernetes pull request #75787
Opened 2019-03-27 18:52 UTC by Liujingfang1

**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
This PR moves pkg/kubectl/cmd/apply into staging so that it can be used as a library in other tools or packages.

**Special notes for your reviewer**:
There are several packages that are moved together with apply:
  - cmd/delete
  - cmd/testing
  - cmd/wait
  - cmd/util
  - util
  - generated
  - scheme
  - validation

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @seans3 @pwittrock

2019-03-27 18:55 UTC, seans3 commented
/ok-to-test

2019-03-27 18:55 UTC, BenTheElder commented
To be clear the list of packages in the PR body are all previously under `pkg/kubectl/...` ?

2019-03-27 18:58 UTC, seans3 commented
/assign @soltysh

2019-03-27 18:58 UTC, seans3 commented
/assign @juanvallejo

2019-03-27 18:58 UTC, seans3 commented
/kind cleanup

2019-03-27 19:16 UTC, seans3 commented
Need to run `hack/update-bazel.sh`

2019-03-28 19:55 UTC, Liujingfang1 commented
/test pull-kubernetes-integration

2019-03-28 20:09 UTC, Liujingfang1 commented
> To be clear the list of packages in the PR body are all previously under pkg/kubectl/... ?

Yes.

2019-03-29 08:10 UTC, juanvallejo commented
/lgtm

2019-03-29 20:13 UTC, Liujingfang1 commented
/priority important-soon

2019-04-01 12:50 UTC, soltysh requested changes
/lgtm cancel
I have one objection wrt publishing all the rest lgtm.

2019-04-01 12:50 UTC, soltysh commented on staging/publishing/rules.yaml
> +- destination: kubectl
We should not update the publishing rules, yet. There's still some code in our kubectl repo which does not exist in the main k/k code. I want to ensure we bring those back but deprecated and not to break people. Also, the publishing should happen not sooner than when we're close to finishing the move.

2019-06-24 16:16 UTC, closed without merging