Fix nodeSelector hostname
kubernetes/kubernetes pull request #75909
Opened 2019-03-30 00:03 UTC by ravisantoshgudimetla

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

 /kind bug
> /kind cleanup

**What this PR does / why we need it**:
As of now, we are hardcoding the hostname to node.Name which might not be the case always.
/cc @Huang-Wei @bsalamat @sjenning 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig scheduling

2019-03-30 00:04 UTC, ravisantoshgudimetla commented
/kind bug

2019-04-01 08:34 UTC, k82cn commented
any background for this PR?

2019-04-01 13:21 UTC, ravisantoshgudimetla commented
@k82cn - Our assumption that `kubernetes.io/hostname` is always mapped to `node.Name` might not be always true and it varies for different distributions, for example OpenShift uses a different name, so I am trying to get it in a generic way instead of the hardcoding that we have currently.

2019-04-01 14:19 UTC, SataQiu commented on test/e2e/scheduling/taints.go
> +		node, err := cs.CoreV1().Nodes().Get(nodeName, metav1.GetOptions{})
One suggestion.  You may need to move `framework.ExpectNoError(err)`  from line 419 to line 413 to check the error of `nodeName, err := testutils.RunPodAndGetNodeName(cs, pod1, 2*time.Minute)`

2019-04-01 19:26 UTC, sjenning commented
second time I've seen the assumption made in e2e tests :disappointed: https://github.com/kubernetes/kubernetes/pull/75335

2019-04-01 22:45 UTC, Huang-Wei requested changes
I'd suggest to change `nodeSelector` to `nodeAffinity` like this:

```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - 127.0.0.1
```

So that we can have following benefits:

1. don't need extra run to fetch `k8s.io/hostname` label
2. don't need to fail the whole test if `k8s.io/hostname` label is not set
3. `RunPodAndGetNodeName()` is still valid as `spec.nodeName` is always set, and that's to ensure our assumption to be consistent with internal scheduling logic

2019-04-02 01:11 UTC, ravisantoshgudimetla commented
@Huang-Wei - I like the idea but I think there are other tests that have the same assumption too, perhaps having a separate PR to address this issue in all other tests might help?

2019-04-02 01:45 UTC, Huang-Wei commented
@ravisantoshgudimetla That makes sense.

2019-04-03 18:35 UTC, ravisantoshgudimetla commented
@Huang-Wei - Can you lgtm?

2019-04-03 18:38 UTC, Huang-Wei reviewed
/lgtm

Thanks, @ravisantoshgudimetla !

2019-04-03 21:55 UTC, merged

2019-04-04 00:50 UTC, k82cn commented
> for example OpenShift uses a different name, so I am trying to get it in a generic way instead of the hardcoding that we have currently.

Sorry for the delay :) I'm ok with that, thanks.