allow for non-fatal errors when requesting and following multiple log streams
kubernetes/kubernetes pull request #75903
Opened 2019-03-29 21:24 UTC by juanvallejo

/kind cleanup
/sig cli

cc @soltysh @seans3 

When watching multiple log streams, encountering a single error while trying to reach logs for pods kills the whole command. This PR allows you to obtain and follow (`-f`) multiple streams, and keep the command going even if errors are encountered. Any errors are simply appended to the log stream. 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2019-03-29 21:38 UTC, igaskin commented
/lgtm

2019-04-01 13:03 UTC, soltysh requested changes

2019-04-01 13:03 UTC, soltysh commented on pkg/kubectl/cmd/logs/logs.go
> +	cmd.Flags().BoolVar(&o.AllowPodErrors, "allow-errors", o.AllowPodErrors, "If watching / following pod logs, allow for any errors that occur to be non-fatal")
Nit: I think `ignore-errors` is more appropriate and in-line with other `ignore-not-found` flags.

2019-04-01 20:06 UTC, juanvallejo commented
@soltysh thanks, comment addressed

2019-04-02 14:51 UTC, soltysh approved these changes
/lgtm
/approve

2019-04-02 18:49 UTC, merged