Add operation name for other volume operations
kubernetes/kubernetes pull request #75926
Opened 2019-03-31 16:17 UTC by cwdsuzhou

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind feature
/kind bug

**What this PR does / why we need it**:
Though, [this pr](https://github.com/kubernetes/kubernetes/pull/75213) allows different operation names of the same pod and volume, currently this is only effective for `mount, unmount`. Other volume operations' names have not been set.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2019-03-31 16:19 UTC, cwdsuzhou commented
/assign @gnufied

2019-04-04 00:18 UTC, cwdsuzhou commented
@gnufied @jingxu97 @rootfs

PTAL

2019-04-04 00:26 UTC, gnufied commented
/ok-to-test

2019-04-04 02:08 UTC, cwdsuzhou commented
/retest

2019-04-04 04:36 UTC, cwdsuzhou commented
/retest

2019-04-04 15:10 UTC, cwdsuzhou commented
/assign @saad-ali

2019-04-04 18:47 UTC, gnufied commented
/lgtm

2019-04-05 03:44 UTC, cwdsuzhou commented
ping @saad-ali for approve

2019-04-11 20:32 UTC, saad-ali requested changes

2019-04-11 20:32 UTC, saad-ali commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		OperationName:     "map_volume",
typo: `unmap_volume`

2019-04-12 03:11 UTC, cwdsuzhou commented on pkg/volume/util/operationexecutor/operation_generator.go
> +		OperationName:     "map_volume",
my mistake, updated,  thanks

2019-04-12 04:30 UTC, cwdsuzhou commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-04-12 05:40 UTC, cwdsuzhou commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-04-12 07:39 UTC, cwdsuzhou commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-04-13 02:26 UTC, cwdsuzhou commented
ping @gnufied @saad-ali

PTAL again

2019-04-18 01:24 UTC, gnufied commented
/approve

2019-04-18 01:39 UTC, cwdsuzhou commented
Thanks @gnufied , could you add LGTM since I have changed the PR

2019-04-18 03:08 UTC, gnufied commented
/lgtm

2019-04-18 07:26 UTC, merged