Update fluentd 1.4.1
kubernetes/kubernetes pull request #75967
Opened 2019-04-01 14:18 UTC by ialidzhikov

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:
- Update fluentd to 1.4.1. `gcr.io/fluentd-elasticsearch/fluentd:v2.5.0` is already with fluentd 1.4.1, so just keep in sync the pushed image with the Dockerfile.
- Update image README.md with the correct links to the image repository.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-04-01 14:19 UTC, ialidzhikov commented
/assign @monotek

2019-04-01 15:02 UTC, monotek requested changes
Update of version in makefile is missing.

2019-04-01 15:29 UTC, ialidzhikov commented
Everything is fine with docker run gcr.io/fluentd-elasticsearch/fluentd:v2.5.0 - the fluentd version is 1.4.0. I updated the PR description.
```bash
$ docker run gcr.io/fluentd-elasticsearch/fluentd:v2.5.0
[...]
2019-04-01 15:26:52 +0000 [info]: gem 'fluentd' version '1.4.0'
[...]
```

2019-04-01 15:35 UTC, monotek commented
/ok-to-test

2019-04-05 17:08 UTC, coffeepac commented on cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml
> +        image: gcr.io/fluentd-elasticsearch/fluentd:v2.5.1
whoa, thanks for that!  I missed it during the switch over originally.

2019-04-05 17:12 UTC, coffeepac commented
/approve
/lgtm

2019-04-05 17:12 UTC, coffeepac commented
pushing the new image now, should be available in ~5 minutes.

2019-04-05 18:51 UTC, merged

2019-04-06 15:06 UTC, ialidzhikov commented
Thank you!