test coverage for pod QOS Burstable
kubernetes/kubernetes pull request #76128
Opened 2019-04-04 07:16 UTC by pontiyaraja

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> 
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:This PR to cover test case for pod QOS Burstable scenario.

**Which issue(s) this PR fixes**: It a part of an umbrella issue #75935 

Fixes # a part of #75935 

**Special notes for your reviewer**: 
If requests or optionally limits are set (not equal to 0) for one or more resources across one or more containers, and they are not equal, then the pod is classified as Burstable. The pods QOSClass set to Burstable.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/area testing
/area node
/area conformance
@kubernetes/sig-node-pr-reviews

2019-04-04 08:50 UTC, pontiyaraja commented
/test pull-kubernetes-e2e-gce-100-performance

2019-04-06 16:54 UTC, mattjmcnaughton reviewed
Hi @pontiyaraja :)

I made a more detailed comment in https://github.com/kubernetes/kubernetes/pull/76129#pullrequestreview-223548067, so perhaps we should have the discussion there... but at a high level, I'm wondering if this test coverage could be better provided via a unit test instead of a e2e test.

2019-04-07 03:50 UTC, pontiyaraja commented
@mattjmcnaughton please refer my comment https://github.com/kubernetes/kubernetes/pull/76129#issuecomment-480556675

2019-05-20 13:11 UTC, mgdevstack commented
@pontiyaraja, Would this https://github.com/kubernetes/kubernetes/issues/75935#issuecomment-493030622, satisfy to validate Pod qosClass assignment behaviour as an e2e supporting @mattjmcnaughton's https://github.com/kubernetes/kubernetes/pull/76129#issuecomment-480597922?

2019-08-05 20:41 UTC, spiffxp requested changes
some suggestions and questions

2019-08-05 20:41 UTC, spiffxp commented on test/e2e/node/pods.go
> +func getResourcePod(name string, resorces v1.ResourceRequirements) *v1.Pod {
```suggestion
func getResourcePod(name string, resources v1.ResourceRequirements) *v1.Pod {
```

2019-08-05 20:41 UTC, spiffxp commented on test/e2e/node/pods.go
> +					Resources: resorces,
```suggestion
					Resources: resources,
```

2019-08-05 20:41 UTC, spiffxp commented on test/e2e/node/pods.go
> +		It("should be set on Pods with matching resource requests and limits for memory", func() {
I would prefer to see one test case for `PodQOSBurstable` and another for `PodQOSBestEffort`; it's unclear to me what the benefit is of having them both in a single test case

2019-08-05 20:41 UTC, spiffxp commented on test/e2e/node/pods.go
> +					Image:     imageutils.GetE2EImage(imageutils.Nginx),
Does this need to be nginx? Could we use agnhost instead?

2019-08-21 00:06 UTC, spiffxp commented
pinging for signs of life

2019-08-21 00:08 UTC, spiffxp commented
/lifecycle stale

2019-10-20 01:46 UTC, closed without merging