Remove kubectl exec deprecated -p/--pod flag
kubernetes/kubernetes pull request #76713
Opened 2019-04-17 15:14 UTC by prksu

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

`--pod/-p` flag was marked as deprecated flag since https://github.com/kubernetes/kubernetes/pull/66558 now it's enough time to remove it after marking the flag as deprecated.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

ping @soltysh 

**Does this PR introduce a user-facing change?**:

```release-note
Remove kubectl exec -p/--pod flag
```

2019-04-17 15:16 UTC, prksu commented
/assign @soltysh

2019-04-17 17:44 UTC, neolit123 reviewed
/priority important-longterm
/ok-to-test

@prksu 
it would be best if you explain in the release note that the flag was deprecated since k8s version x.y.
thanks.

2019-04-17 19:20 UTC, prksu commented
@neolit123 
updated. thanks

2019-05-09 13:13 UTC, prksu commented
/cc @soltysh need an approval

2019-05-22 22:32 UTC, prksu commented
/cc @kargakis

2019-05-22 23:19 UTC, 0xmichalis requested changes
Some code paths in Complete, Validate, and Run can be simplified as a result of this removal.

2019-05-23 13:45 UTC, prksu commented
> Some code paths in Complete, Validate, and Run can be simplified as a result of this removal.

@kargakis 

the `p.PodName` is still used in `kubectl cp`

https://github.com/kubernetes/kubernetes/blob/bf75d500f5edd2e3e6ed091c0fc3412ab78132c4/pkg/kubectl/cmd/exec/exec.go#L223-L225

and

https://github.com/kubernetes/kubernetes/blob/bf75d500f5edd2e3e6ed091c0fc3412ab78132c4/pkg/kubectl/cmd/exec/exec.go#L290-L297

maybe we need change `legacy pod getter` in `kubectl cp` to use `resource.Builder` first, so we can remove unused code above.

2019-05-23 15:23 UTC, prksu commented
/retest

2019-05-23 16:01 UTC, kargakis commented
@prksu hrm, now I see. Don't feel strongly in any way, leaving this up to @soltysh.

2019-05-23 17:18 UTC, prksu commented
/retest

2019-05-23 17:18 UTC, prksu commented
ping @soltysh

2019-05-30 19:39 UTC, soltysh approved these changes
/lgtm
/approve

2019-05-31 04:58 UTC, prksu commented
/retest

2019-05-31 20:28 UTC, claurence commented
/milestone v1.15

2019-05-31 21:07 UTC, prksu commented
pull-kubernetes-bazel-build test status is successed, but tide say it's not successed :confused:

2019-05-31 21:19 UTC, prksu commented
/retest

2019-05-31 21:20 UTC, prksu commented
/test pull-kubernetes-bazel-build

2019-06-01 03:16 UTC, prksu commented
/retest

2019-06-01 08:02 UTC, merged

2019-06-01 14:47 UTC, prksu commented
@soltysh @kargakis thanks