images: Adds GOARM to images' Makefiles
kubernetes/kubernetes pull request #76828
Opened 2019-04-19 14:14 UTC by bclau

**What type of PR is this?**

/kind bug
/sig testing

**What this PR does / why we need it**:

In order to build the image binaries, the GOARM variable is required,
but not all Makefiles have it defined, causing the make to fail on
those images.

This adds the require GOARM variable to the Makefiles in question.

**Which issue(s) this PR fixes**:

Fixes #76827

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-04-19 22:21 UTC, neolit123 commented
/priority important-longterm
/assign @mkumatag

2019-04-23 15:03 UTC, adelina-t commented
/cc @PatrickLang

2019-04-23 16:28 UTC, mkumatag requested changes
Instead of setting this variable everywhere, I'm wondering whether we can just set it in the https://github.com/kubernetes/kubernetes/blob/master/test/images/image-util.sh if the value does not change across the images.

2019-04-23 17:16 UTC, bclau commented
> 
> 
> Instead of setting this variable everywhere, I'm wondering whether we can just set it in the https://github.com/kubernetes/kubernetes/blob/master/test/images/image-util.sh if the value does not change across the images.

True, that also works, but having it into the individual Makefiles will make it more self-documenting. Looking at just the ``Makefile``, you wouldn't know that ``GOARM`` is something that is configurable and that can be set.

2019-05-08 17:52 UTC, bclau commented
/test pull-kubernetes-e2e-gce-100-performance

2019-06-14 13:51 UTC, bclau commented
/test pull-kubernetes-e2e-gce-device-plugin-gpu
/test pull-kubernetes-e2e-gce-100-performance

2019-06-17 20:32 UTC, bclau commented
/test pull-kubernetes-bazel-build

2019-06-18 08:46 UTC, bclau commented
/test pull-kubernetes-bazel-build

2019-07-01 13:36 UTC, adelina-t commented
/test pull-kubernetes-e2e-aks-engine-azure-windows

2019-07-11 09:32 UTC, bclau commented
/test pull-kubernetes-e2e-gce

2019-07-17 13:38 UTC, bclau commented
/test pull-kubernetes-e2e-aks-engine-azure-windows

2019-09-06 10:24 UTC, bclau commented
/test pull-kubernetes-e2e-aks-engine-azure-windows

2019-11-12 16:47 UTC, bclau commented
/test pull-kubernetes-e2e-aks-engine-azure-windows

2019-11-12 19:15 UTC, bclau commented
/test pull-kubernetes-node-e2e-containerd

2019-12-06 12:49 UTC, bclau commented
/test pull-kubernetes-e2e-aks-engine-azure-windows

2019-12-19 14:41 UTC, claudiubelu commented
/test pull-kubernetes-e2e-aks-engine-azure-windows

2020-01-29 13:30 UTC, claudiubelu commented
/retest

2020-01-29 16:54 UTC, claudiubelu commented
/retest

2020-01-30 12:43 UTC, claudiubelu commented
/test pull-kubernetes-e2e-gce

2020-05-04 08:55 UTC, claudiubelu commented
/remove-lifecycle stale

2020-06-29 12:45 UTC, luxas approved these changes
/lgtm
/approve

Thanks!

2020-06-29 12:46 UTC, luxas commented
/retest

2020-06-29 12:47 UTC, luxas commented
cc @mkumatag

2020-06-29 12:57 UTC, mkumatag commented
/approve

2020-07-01 14:10 UTC, merged