Enable paging and quorum reads by default, by feature gate in sample-apiserver
kubernetes/kubernetes pull request #77278
Opened 2019-04-30 20:48 UTC by liggitt

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Enable paging and quorum reads by default in etcd storage, and by feature gate in sample-apiserver

**Does this PR introduce a user-facing change?**:
```release-note
API paging is now enabled by default in k8s.io/apiserver recommended options, and in k8s.io/sample-apiserver
```

/cc MikeSpreitzer
/sig api-machinery

2019-04-30 21:24 UTC, MikeSpreitzer commented
Yikes, I thought quorum reads were the norm in all servers!
Do I understand correctly that before this change, sample-apiserver _does not_ doing quorum reads, and after this change, sample-apiserver _does_ do quorum reads --- and no command line flags affect whether sample-apiserver does quorum reads?

2019-04-30 21:31 UTC, liggitt commented
> Yikes, I thought quorum reads were the norm in all servers!
> Do I understand correctly that before this change, sample-apiserver _does not_ do quorum reads, and after this change, sample-apiserver _does_ do quorum reads --- and no command line flags affect whether sample-apiserver does quorum reads?

that is mostly for completeness... the etcd3 driver ignores whatever you put in that options struct and forces quorum

2019-04-30 21:31 UTC, liggitt commented
would actually be good to drop that options field in a follow up

2019-04-30 21:38 UTC, liggitt commented
on second thought, I just dropped the quorum change and limited this to the paging bit

2019-04-30 21:40 UTC, liggitt commented
dropped the Quorum field from that config struct in https://github.com/kubernetes/kubernetes/pull/77281

2019-04-30 21:44 UTC, MikeSpreitzer approved these changes

2019-04-30 21:44 UTC, MikeSpreitzer requested changes
On second thought, maybe not.  Doesn't this read the feature gate before the command line flags are parsed?

2019-04-30 21:50 UTC, liggitt commented
> On second thought, maybe not. Doesn't this read the feature gate before the command line flags are parsed?

you're right, good catch.

2019-04-30 21:56 UTC, MikeSpreitzer approved these changes
This time, for sure

2019-05-01 02:42 UTC, liggitt commented
/retest

2019-05-01 02:42 UTC, liggitt commented
/priority important-soon

2019-05-02 20:14 UTC, apelisse commented
/assign @jpbetz

2019-05-02 22:48 UTC, jpbetz commented
Looks right.

/lgtm

2019-05-03 02:43 UTC, liggitt commented
/retest

2019-05-03 06:36 UTC, merged