fix race condition
kubernetes/kubernetes pull request #77779
Opened 2019-05-11 17:09 UTC by JieJhih

*What type of PR is this?**
> /kind design
> /kind failing-test

**What this PR does / why we need it**:
Run ``go test -race k8s.io/kubernetes/pkg/scheduler`` you will see some errors below.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
The race condition cause ``pull-kubernetes-bazel-test`` failed.
Ref. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/77501/pull-kubernetes-bazel-test/1127119916156063745/build-log.txt
**Does this PR introduce a user-facing change?**:

```release-note
None
```

2019-05-11 17:09 UTC, JieJhih commented
/assign @bsalamat @misterikkit

2019-05-11 23:49 UTC, k82cn commented on pkg/scheduler/scheduler_test.go
> +			scheduler.mu.Unlock()
IMO, we're waiting for `queuePodStore` here, we just need to make sure `queuePodStore` is thread-safe instead of `Run()`.

2019-05-12 01:55 UTC, wgliang requested changes

2019-05-12 01:55 UTC, wgliang commented on pkg/scheduler/scheduler_test.go
> +			scheduler.mu.Lock()
This can lead to deadlock.

2019-05-12 01:56 UTC, wgliang commented on pkg/scheduler/scheduler_test.go
> +			scheduler.mu.Lock()
Because there is already a lock operation in the scheduler.Run().

2019-05-13 23:06 UTC, bsalamat commented on pkg/scheduler/scheduler.go
> +		sched.mu.Lock()
The `Run` function is not called by multiple threads. Why do we need synchronization here?

2019-05-14 07:09 UTC, JieJhih commented
/close

2019-05-14 07:09 UTC, closed without merging