Increase coverage for e2e Network Policy tests
kubernetes/kubernetes pull request #77937
Opened 2019-05-15 16:31 UTC by MaysaMacedo

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Validates correct behavior when :
- NetworkPolicyIngressRule contains PodSelector with MatchExpressions
- NetworkPolicyIngressRule contains NamespaceSelector with MatchExpressions
- Network Policy is enforced based on PodSelector and NamespaceSelector
- Network Policy is enforced based on PodSelector or NamespaceSelector

```release-note
NONE
```
/area testing
/sig-testing

2019-05-15 20:07 UTC, MaysaMacedo commented
I signed it

2019-05-15 21:55 UTC, neolit123 reviewed
thanks for the PR @MaysaMacedo 
better test coverage is much appreciated.

i'm adding @kubernetes/sig-network-pr-reviews 
for approval.

in the meantime i've added some comments to not use a pattern we are currently trying to refactor.
thanks.

2019-05-15 21:55 UTC, neolit123 commented on test/e2e/network/network_policy.go
> +                        gomega.Expect(err).NotTo(gomega.HaveOccurred())
please use `ExpectNoError()` see this PR as example:
https://github.com/kubernetes/kubernetes/pull/77955

but also for new tests we should add a description of why it failed.
[1]

2019-05-15 21:55 UTC, neolit123 commented on test/e2e/network/network_policy.go
> +			gomega.Expect(err).NotTo(gomega.HaveOccurred())
[1]

2019-05-15 21:55 UTC, neolit123 commented on test/e2e/network/network_policy.go
> +                        gomega.Expect(err).NotTo(gomega.HaveOccurred())
[1]

2019-05-15 21:55 UTC, neolit123 commented on test/e2e/network/network_policy.go
> +                        gomega.Expect(err).NotTo(gomega.HaveOccurred())
[1]

2019-05-15 21:55 UTC, neolit123 commented on test/e2e/network/network_policy.go
> +                        gomega.Expect(err).NotTo(gomega.HaveOccurred())
[1]

2019-05-15 21:55 UTC, neolit123 commented on test/e2e/network/network_policy.go
> +                        gomega.Expect(err).NotTo(gomega.HaveOccurred())
[1]

2019-05-15 21:55 UTC, neolit123 commented on test/e2e/network/network_policy.go
> +                        gomega.Expect(err).NotTo(gomega.HaveOccurred())
[1]

2019-05-15 21:55 UTC, neolit123 commented
/kind feature
/priority important-longterm

2019-05-16 10:02 UTC, MaysaMacedo commented
Thank you for the review @neolit123 .

2019-05-16 12:54 UTC, neolit123 reviewed
thanks for the update
/lgtm
/ok-to-test

2019-05-16 15:42 UTC, cmluciano requested changes
Couple of small typo fixes requested to keep the comments uniform but generally this looks good

2019-05-16 15:42 UTC, cmluciano commented on test/e2e/network/network_policy.go
> +                ginkgo.It("should enforce policy based on podSelector or NamespaceSelector [Feature:NetworkPolicy]", func() {
```suggestion
                ginkgo.It("should enforce policy based on PodSelector or NamespaceSelector [Feature:NetworkPolicy]", func() {
```

2019-05-16 15:42 UTC, cmluciano commented on test/e2e/network/network_policy.go
> +                ginkgo.It("should enforce policy based on podSelector and NamespaceSelector [Feature:NetworkPolicy]", func() {
```suggestion
                ginkgo.It("should enforce policy based on PodSelector and NamespaceSelector [Feature:NetworkPolicy]", func() {
```

2019-05-17 07:46 UTC, MaysaMacedo commented
Thank you @cmluciano .

2019-05-17 16:03 UTC, cmluciano commented
@MaysaMacedo Looks like verify is hitting a go-fmt issue. Please run `./hack/update-gofmt.sh` to fix these.

2019-05-17 16:24 UTC, MaysaMacedo commented
@cmluciano Just fixed. Thanks!

2019-05-17 17:08 UTC, cmluciano commented
/lgtm

2019-05-20 04:24 UTC, saiyan86 commented
Should we delete the namespaces after the tests are finished? Leftover namespaces may create confusions for other tests.

2019-05-20 07:52 UTC, MaysaMacedo commented
@saiyan86 Namespaces are being deleted after test is completed. [1]

[1] https://github.com/kubernetes/kubernetes/blob/a404238d1c90ee00827624249b9223e7644e3f99/test/e2e/framework/framework.go#L404

2019-05-21 14:42 UTC, cmluciano commented
/retest

2019-05-27 09:10 UTC, MaysaMacedo commented
/retest

2019-05-27 15:45 UTC, MaysaMacedo commented
@cmluciano  Just to raise awareness. I've updated the tests `should enforce policy based on NamespaceSelector with MatchExpressions` because I was using the framework
namespace to match the expression, and this namespace does not have a label `ns-name`. Thus, when using the operator `NotIn` the connection would be allowed to the pod "client-a" in the framework's namespace resulting in test failure.

2019-05-28 16:23 UTC, cmluciano commented
> @cmluciano Just to raise awareness. I've updated the test should enforce policy based on NamespaceSelector with MatchExpressions because I was using the framework
> namespace to match the expression, and this namespace does not have a label ns-name. Thus, when using the operator NotIn the connection would be allowed to the pod client-a in the framework's namespace resulting in test failure.

Good catch, that would explain the ns-cleanup errors. 

/lgtm

2019-05-28 16:24 UTC, cmluciano commented
/assign @caseydavenport @dcbw

2019-05-29 15:42 UTC, dcbw commented
/approve

2019-05-29 18:26 UTC, merged