Add test demonstrates http2 client not detecting inactive tcp connection
kubernetes/kubernetes pull request #77957
Opened 2019-05-15 22:24 UTC by roycaihw

ref: https://github.com/kubernetes/client-go/issues/374#issuecomment-484623876, https://github.com/kubernetes/kubernetes/issues/65012

HTTP client is able to detect if the underlying TCP connection is inactive and bypass the firewall, while HTTP2 client may block until TCP connection times out.

Note that a proper fix may require change in golang `x/net/http2` standard library: https://github.com/kubernetes/client-go/issues/374#issuecomment-487437365.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig api-machinery
/area client-libraries

2019-05-16 03:18 UTC, gaorong requested changes

2019-05-16 03:18 UTC, gaorong commented on test/integration/client/connection_test.go
> +	utiliptables "k8s.io/kubernetes/pkg/util/iptables"
this import is duplicated

2019-05-16 04:06 UTC, xichengliudui commented
/priority backlog
need merged commit

2019-05-16 20:15 UTC, fedebongio commented
/assign @cheftako

2019-05-17 23:05 UTC, roycaihw commented on test/integration/client/connection_test.go
> +	connections, err := exec.Command("ss", "-t").Output()
updated. thanks

2019-09-27 20:29 UTC, roycaihw commented on test/integration/client/connection_test.go
> +	sport := ports[1]
@caesarxuchao pointed out that in HTTP/1.1 scenario there are multiple ports talking to apiserver and this line doesn't necessarily capture the watch connection

2019-09-27 20:29 UTC, roycaihw commented on test/integration/client/connection_test.go
> +			switch o := got.Object.(type) {
No auto-reconnecting behavior is expected. The watch should fail instead of hanging

2019-10-27 20:49 UTC, closed without merging