Use Service Control Manager as the Windows Initsystem
kubernetes/kubernetes pull request #78189
Opened 2019-05-21 19:42 UTC by ksubrmnn

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR updates the initsystem implementation for Windows to use golang.org/x/sys/windows/svc/mgr. This package allows us to make calls to the Windows Service Control Manager
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-05-21 19:42 UTC, ksubrmnn commented
/assign @neolit123 
/assign @rosti

2019-05-21 22:55 UTC, ksubrmnn commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-05-22 08:57 UTC, rosti approved these changes
/approve
For kubeadm changes

2019-05-22 18:28 UTC, ksubrmnn commented
/assign @brendandburns

2019-05-25 13:29 UTC, neolit123 requested changes
@ksubrmnn , i've added a couple of comments and questions, but the file split and new service manager LGTM.
thanks

2019-05-25 13:29 UTC, neolit123 commented on pkg/util/initsystem/initsystem_windows.go
> +// if we cannot detect a supported init system for pre-flight checks.
preflight checks are mostly CLi specific (e.g. for kubeadm), we should probably omit them from here.
i would change `supported init system for pre-flight checks.` -> `supported init system.`

2019-05-25 13:29 UTC, neolit123 commented on pkg/util/initsystem/initsystem_windows.go
> +	return nil, fmt.Errorf("no supported init system detected, skipping checking for services")
i'd suggest this modification:
```
	m, err := mgr.Connect()
	if err != nil {
		return nil, fmt.Errorf("no supported init system detected: %v", err)
	}
	defer m.Disconnect()
	return &WindowsInitSystem{}, nil
```
this also includes the `err` from `Connect()`, which can be useful for debug.

`skipping checking for services` should be on the CLI side.

2019-05-25 13:29 UTC, neolit123 commented on pkg/util/initsystem/initsystem_windows.go
> +	err = s.Start("is", "manual-started")
would this return an error if the service is already started?

2019-05-25 13:29 UTC, neolit123 commented on pkg/util/initsystem/initsystem_windows.go
> +	return c.StartType == mgr.StartAutomatic
wouldn't this return `false` in case we started the service from `ServiceStart()` with `err = s.Start("is", "manual-started")`?

2019-05-25 13:29 UTC, neolit123 commented
/unassign @thockin

2019-05-27 17:18 UTC, neolit123 commented
/priority important-longterm

2019-05-30 00:00 UTC, dineshgovindasamy requested changes

2019-05-30 00:00 UTC, dineshgovindasamy commented on pkg/util/initsystem/initsystem_windows.go
> +	if status.State == svc.Stopped {
You should check stoppending as well...

2019-05-30 00:00 UTC, dineshgovindasamy commented on pkg/util/initsystem/initsystem_windows.go
> +
I think it will be good to check the status of the services before issuing a start.

2019-05-30 00:00 UTC, dineshgovindasamy commented on pkg/util/initsystem/initsystem_windows.go
> +	for status.State != svc.Stopped {
check for stoppending as well

2019-05-30 00:39 UTC, dineshgovindasamy approved these changes
Thanks for making the changes quickly. Looks good.

/LGTM

2019-05-30 03:17 UTC, brendandburns commented
I took a quick scan, this looks good to me. I'm happy to approve if we think the right reviewers have gotten a look at it...

2019-05-30 11:15 UTC, dineshgovindasamy commented
/retest

2019-05-30 16:33 UTC, neolit123 commented
/lgtm
/approve

@brendanburns this is good to go.
thanks.

we should probably add a separate owners file here with sig-node / cluster-lifecycle.

2019-05-30 18:28 UTC, ksubrmnn commented
/milestone v1.15

2019-05-30 18:33 UTC, brendandburns commented
/approve

2019-05-30 21:48 UTC, PatrickLang commented
/milestone v1.15

2019-05-31 20:31 UTC, ksubrmnn commented
@PatrickLang let's keep an eye on this so it gets merged

2019-06-01 05:02 UTC, merged