Fix nil pointer dereference in metrics value calculator.
kubernetes/kubernetes pull request #78222
Opened 2019-05-22 19:37 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2019-05-23 14:18 UTC, mattjmcnaughton requested changes
Thanks for thinking about this :)

Overall, I think the nil check is a great idea - we just need to ensure that we're at least initializing the variables to a default value. See my comment and the test suite failures for more info.

Also, could you please fill in the information in your pr? Specifically, the why we need this pull request section (i.e. desc of bug you're fixing, the impact of the bug, etc...) Thanks!

2019-05-24 13:21 UTC, humblec commented
>Thanks for thinking about this :)
yw :)

>Overall, I think the nil check is a great idea - we just need to ensure that we're at least initializing the variables to a default value. See my comment and the test suite failures for more info.
>

Done. Updated the patch set.

>
Also, could you please fill in the information in your pr? Specifically, the why we need this pull request section (i.e. desc of bug you're fixing, the impact of the bug, etc...) Thanks!
>

Updated commit message with the details on how did I find the culprit :)

2019-05-24 15:30 UTC, mattjmcnaughton commented
/test pull-kubernetes-typecheck

2019-05-24 15:30 UTC, mattjmcnaughton commented
/test pull-kubernetes-verify

2019-05-24 15:44 UTC, mattjmcnaughton commented
> > Thanks for thinking about this :)
> > yw :)
> 
> > Overall, I think the nil check is a great idea - we just need to ensure that we're at least initializing the variables to a default value. See my comment and the test suite failures for more info.
> 
> Done. Updated the patch set.
> 
> > 
> 
> Also, could you please fill in the information in your pr? Specifically, the why we need this pull request section (i.e. desc of bug you're fixing, the impact of the bug, etc...) Thanks!
> 
> > 
> 
> Updated commit message with the details on how did I find the culprit :)

Thanks for the updated commit message :)

Unfortunately, looks like there are still typecheck errors (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78222/pull-kubernetes-typecheck/1131945681234169856). You can run `./hack/verify-typecheck.sh` to test these locally.

Other than getting the test suite to pass, I think this is looking great :)

2019-05-27 11:08 UTC, humblec commented
>Unfortunately, looks like there are still typecheck errors (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78222/pull-kubernetes-typecheck/1131945681234169856). >

@mattjmcnaughton  Ah.. my bad, was in hurry to push the change while boarding the flight :), corrected it.  Thanks ! PTAL.

2019-05-27 11:39 UTC, mattjmcnaughton approved these changes
/lgtm

thank you for this fix and for making the updates to get it to pass all the checks :)

2019-05-27 13:58 UTC, humblec commented
/release-note-none

2019-05-27 13:58 UTC, humblec commented
/retest

2019-05-27 14:25 UTC, humblec commented
@mattjmcnaughton Thanks , not sure who can approve this PR :)

2019-05-28 07:28 UTC, humblec commented
@tallclair may be you can approve this ? :)

2019-05-28 14:19 UTC, mattjmcnaughton commented
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[humblec](https://github.com/kubernetes/kubernetes/pull/78222#)_
> To fully approve this pull request, please assign additional approvers.
> We suggest the following additional approver: **tallclair**
> 
> If they are not already assigned, you can assign the PR to them by writing `/assign @tallclair` in a comment when ready.
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Fkubernetes).
> 
> The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)
> 
> Needs approval from an approver in each of these files:
> * **[pkg/kubelet/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment
> Approvers can cancel approval by writing `/approve cancel` in a comment

This message from the prow robot suggests an approver :)

/assign @tallclair

2019-05-30 04:18 UTC, humblec commented
May be @thockin can also help  :) . He has helped in many PRs :)

2019-05-31 15:23 UTC, humblec commented
/assign @dchen1107

2019-05-31 15:24 UTC, humblec commented
/assign @Random-Liu

2019-06-11 22:32 UTC, tallclair reviewed
/approve

2019-06-11 22:32 UTC, tallclair commented on pkg/kubelet/server/stats/volume_stat_calculator.go
> +	}
alternatively, you could make a helper function:
```
func getMetricValue(r *resource.Quantity) uint64 {
  if r != nil {
    return uint64(r.Value())
  }
  return 0
```

2019-06-17 06:37 UTC, nikhita commented
/kind bug

2019-06-17 11:36 UTC, merged

2019-07-19 15:47 UTC, jieyu commented
Will this be backported to prior supported releases?

2019-07-25 18:20 UTC, gnufied commented
@humblec can we open a backport request for 1.15 please?

2019-07-26 04:02 UTC, humblec commented
> @humblec can we open a backport request for 1.15 please?

@gnufied filed https://github.com/kubernetes/kubernetes/pull/80616