Delay sorting of evictUnits slice in kuberuntime_gc
kubernetes/kubernetes pull request #78369
Opened 2019-05-26 21:59 UTC by tedyu

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Currently the sorting of evictUnits slices is done in cgc.evictableContainers

This PR delays the sorting to when the sorting is needed in enforceMaxContainersPerEvictUnit

```release-note
NONE
```

2019-05-26 22:47 UTC, tedyu commented
/test pull-kubernetes-integration

2019-05-27 00:14 UTC, vllry commented
/cc @vllry

2019-05-27 12:14 UTC, mattjmcnaughton requested changes
Overall, looks good to me! Just requiring one small readability change.

2019-05-27 12:14 UTC, mattjmcnaughton commented on pkg/kubelet/kuberuntime/kuberuntime_gc.go
> +			if len(evictUnits[key]) > toRemove {
Could we instead move this to `removeOldestN` similar to `removeOldestNSandboxes`?

2019-05-27 14:22 UTC, tedyu commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-05-27 15:30 UTC, tedyu commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-05-27 16:30 UTC, tedyu commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-05-27 17:43 UTC, tedyu commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-05-27 19:39 UTC, tedyu commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-05-28 14:58 UTC, tedyu commented
@yujuhong @tallclair 
Please review.

2019-05-29 14:00 UTC, tedyu commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-05-29 14:01 UTC, tedyu commented
@derekwaynecarr 
Please review

2019-07-15 20:40 UTC, tedyu commented
@derekwaynecarr
Please review

2019-07-17 16:04 UTC, tedyu commented
cc @vishh

2019-07-22 17:36 UTC, tedyu commented
@vishh
Please review.

2019-07-23 13:45 UTC, tedyu commented
cc @mattjmcnaughton

2019-07-24 13:45 UTC, mattjmcnaughton approved these changes
/lgtm

2019-07-25 17:53 UTC, tedyu commented
ping @dchen1107 for review

2019-07-26 19:14 UTC, tedyu commented
ping @vishh for review

2019-07-29 15:31 UTC, tedyu commented
@vishh
Please review.

2019-07-30 15:43 UTC, tedyu commented
@vishh
Please review.

2019-07-30 19:27 UTC, tedyu commented
ping @derekwaynecarr for review

2019-07-31 15:07 UTC, tedyu commented
ping @vishh for review

2019-08-05 14:18 UTC, tedyu commented
ping @vishh for review

2019-08-06 20:28 UTC, tedyu commented
ping @vishh for review

2019-08-08 21:41 UTC, tedyu commented
ping @vishh for review

2019-08-09 20:25 UTC, tedyu commented
ping @vishh for review

2019-08-12 15:46 UTC, tedyu commented
ping @yujuhong for review.

2019-08-15 22:29 UTC, tedyu commented
ping @vishh for review

2019-08-19 20:58 UTC, tedyu commented
@vishh
please review

2019-08-22 17:36 UTC, tedyu commented
@vishh
please review

2019-09-16 15:16 UTC, tedyu commented
@vishh
please review

2019-09-27 15:06 UTC, tedyu commented
@dchen1107
Can you take a look ?

2019-10-17 23:23 UTC, vllry commented
/assign @Random-Liu
/assign @derekwaynecarr

2020-01-08 19:23 UTC, closed without merging