Promote existing E2Es for SchedulerPreemption to conformance
kubernetes/kubernetes pull request #78364
Opened 2019-05-26 20:09 UTC by globervinodhn

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: This PR is a request for promotion of the existing E2Es to conformance:
1. "validates basic preemption works"
2. "validates lower priority pod preemption by critical pod"
3. "validates pod anti-affinity works in preemption"

**Which issue(s) this PR fixes**: NONE - Promotion of existing E2Es is requested via this PR
Fixes #

**Special notes for your reviewer**:
1. "validates basic preemption works":
         --- Takes approximately 92 seconds for successful execution.
         --- The test verifies that the basic preemption logic is validated i.e. when a lower priority pod is 
         removed to schedule a higher priority pod when no nodes with the necessary resources can be 
         found to schedule the higher priority pod.

2. "validates lower priority pod preemption by critical pod":
         --- Takes approximately 80 seconds for successful execution.
         --- The test validates that the lower priority pod is vacated when no nodes are available to schedule
         a critical pod.

3. "validates pod anti-affinity works in preemption":
         --- Takes approximately 88 seconds for successful execution.
         --- The test validates that the anti-affinity rules are taken into account during pod preemption.

All three existing tests are found to be on-disruptive and non-flaky in nature.

**Does this PR introduce a user-facing change?**: NONE

/release-note-none

/area conformance

cc @mgdevstack @brahmaroutu

2019-05-26 20:13 UTC, globervinodhn commented
/release-note-none

2019-05-26 20:13 UTC, globervinodhn commented
/sig scheduling

2019-05-31 23:23 UTC, johnbelamaric requested changes
I reviewed the metadata but still haven't looked into the tests themselves to make sure they are working as intended.

2019-05-31 23:23 UTC, johnbelamaric commented on test/e2e/scheduling/preemption.go
> +		Release : v1.15
1.16 now

"The test SHOULD pass" is not a useful way to word these. The MUST/SHOULD etc. needs to be about the behavior, not about the test. How about this instead:

```
Description: When a higher priority pod is created and no node with enough resources is found, scheduler MUST preempt a lower priority pod and schedule the high priority pod.
```

2019-05-31 23:23 UTC, johnbelamaric commented on test/e2e/scheduling/preemption.go
> +		Release : v1.15
Ditto 1.16 and

```
Description: When a critical pod is created and no node with enough resources is found, the scheduler MUST preempt a lower priority pod to schedule the critical pod.
```

2019-05-31 23:23 UTC, johnbelamaric commented on test/e2e/scheduling/preemption.go
> +		Release : v1.15
1.16
Again description should describe the desired behavior.

```
Description: When a high priority pod is pending and its scheduling violates a medium priority pod anti-affinity,
the medium priority pod MUST be preempted to allow the higher priority pod schedule.
Existing low priority pods MUST NOT be preempted as their preemption wouldn't help.
```

2019-05-31 23:28 UTC, johnbelamaric commented
/assign
/priority important-longterm

2019-06-05 12:50 UTC, bclau commented
/retest

FWIW, the tests pass on Windows.

2019-06-20 21:09 UTC, spiffxp commented
/cc

2019-07-08 11:34 UTC, johnbelamaric commented
@bsalamat can you confirm that these tests are correct? If you can confirm, then I am good with promoting them.

2019-07-17 18:38 UTC, bsalamat reviewed
/lgtm
/approve

2019-07-17 18:46 UTC, johnbelamaric commented
@globervinodhn So, functionally these seem to be OK, but somehow this v1 -> corev1 change got put in there and it is failing to build.

2019-07-17 18:55 UTC, johnbelamaric commented on test/e2e/scheduling/preemption.go
> +		var podRes corev1.ResourceList
what is this?

2019-07-24 20:53 UTC, spiffxp commented
/ok-to-test
needs rebase

2019-07-24 20:54 UTC, spiffxp commented
I'm kicking this back to in-progress since @johnbelamaric's comments haven't been addressed

2019-07-24 20:56 UTC, spiffxp commented
/lgtm cancel

2019-07-24 23:48 UTC, spiffxp commented
/close
Closing in favor of https://github.com/kubernetes/kubernetes/pull/80545

2019-07-24 23:48 UTC, closed without merging