Update the TopologyManager interfaces
kubernetes/kubernetes pull request #78516
Opened 2019-05-30 11:38 UTC by klueska

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
This PR updates the core `TopologyManager` interfaces. These updates are based on discussions had about the preferred semantics of the `TopologyManager` and will be reflected in changes to PR https://github.com/kubernetes/kubernetes/pull/73580 that adds the actual `TopologyManager` implementation.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-05-30 11:38 UTC, klueska commented
/sig node

2019-05-30 12:36 UTC, ConnorDoyle commented
/ok-to-test

2019-05-30 12:42 UTC, ConnorDoyle requested changes

2019-05-30 12:42 UTC, ConnorDoyle commented on pkg/kubelet/cm/topologymanager/topology_manager.go
> +// a container and a bool indicating whether this SocketMask encodes a
Could we move detailed comments on field semantics to directly precede the field declaration?

e.g.

```go
// Preferred is set when...
Preferred bool
```

2019-05-30 13:00 UTC, ConnorDoyle commented
/approve

2019-05-30 15:26 UTC, derekwaynecarr commented
This is a nice clean-up.

/approve
/lgtm

2019-05-30 15:27 UTC, derekwaynecarr commented
/milestone v1.15

2019-06-01 14:24 UTC, klueska commented
/test pull-kubernetes-integration

2019-06-01 14:57 UTC, klueska commented
/retest

2019-06-01 15:00 UTC, merged