Move test/e2e use to v1 APIs
kubernetes/kubernetes pull request #78614
Opened 2019-06-01 01:59 UTC by liggitt

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Many of the APIs we use for e2e setup have graduated to v1. Switch to the v1 APIs.

**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/kubernetes/issues/78613

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @oomichi 
/area conformance

2019-06-01 03:46 UTC, liggitt commented
/retest

2019-06-01 12:28 UTC, liggitt commented
/retest

2019-06-02 15:55 UTC, oomichi commented
/retest

2019-06-02 15:59 UTC, oomichi commented on test/e2e/auth/pod_security_policy.go
> +	rbacv1beta1 "k8s.io/api/rbac/v1"
You might want to update here by removing “beta1”

2019-06-03 17:13 UTC, liggitt commented
/retest

2019-06-03 18:17 UTC, oomichi reviewed
/lgtm

Thanks for doing this.

2019-06-03 18:17 UTC, oomichi commented on cluster/addons/metrics-server/metrics-apiservice.yaml
> +apiVersion: apiregistration.k8s.io/v1
LGTM because of https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#apiservice-v1-apiregistration-k8s-io

2019-06-03 18:17 UTC, oomichi commented on cluster/addons/kube-proxy/kube-proxy-rbac.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
LGTM because of https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#clusterrole-v1-rbac-authorization-k8s-io

2019-06-03 18:23 UTC, oomichi commented
/retest

2019-06-03 18:46 UTC, spiffxp requested changes
While we're here can we bring test/e2e into consistency as far as api imports?  Noted one in a review comment, there other is:
```
test/e2e/auth/certificates.go
25:	"k8s.io/api/certificates/v1beta1"
```

There are lots of other imports of `"k8s.io/api/core/v1"` instead of the `v1 "k8s.io/api/core/v1"` style you have going here, but those seem too equivalent to bother noting here.

(found via `ag '^[ \t]*\"[.a-z0-9/]*v1[a-z0-9]*\"' test/e2e`)

2019-06-03 18:46 UTC, spiffxp commented on test/e2e/apimachinery/webhook.go
>  	"k8s.io/api/admissionregistration/v1beta1"
while we're here, `admissionregistrationv1beta1`?

2019-06-03 18:48 UTC, liggitt commented
> While we're here can we bring test/e2e into consistency as far as api imports?

I'd prefer a no-op import rename be separate if you don't mind

2019-06-03 20:46 UTC, spiffxp commented
/priority important-soon

>I'd prefer a no-op import rename be separate if you don't mind
fair enough

/lgtm

2019-06-03 21:07 UTC, fedebongio commented
/remove-sig api-machinery

2019-06-06 20:36 UTC, spiffxp approved these changes

2019-06-14 14:58 UTC, merged