fixing kubectl cp with wildcards
kubernetes/kubernetes pull request #78928
Opened 2019-06-12 05:49 UTC by dixudx

**What type of PR is this?**
/kind bug
/priority critical-urgent 

**What this PR does / why we need it**:
The wildcards will get expansion automatically by bash/sh.

The PR fixes,
* copyFromPod: use sh subcommand to avoid wildcards getting expansion;
* copyToPod: for command line, should use `'foo*'` instead of `foo*` to avoid getting expansion by shell automatically; 

**Which issue(s) this PR fixes**:
Fixes #78854

**Special notes for your reviewer**:
/cc @kubernetes/sig-cli-bugs 

This fix should get into 1.15 ASAP. 
This fix should be cherry-picked to release-1.14 as well.

**Does this PR introduce a user-facing change?**:

```release-note
fixing kubectl cp with wildcards, due to the files glob automatically made by sh/bash
```

2019-06-12 05:55 UTC, dixudx commented
/cc @soltysh

2019-06-12 12:44 UTC, dixudx commented
/cc @kubernetes/sig-cli-maintainers PTAL.

2019-06-12 13:54 UTC, liggitt commented
this is effectively a rewrite of the cp code which requires extremely close review to avoid reintroducing security issues with traversal. it also adds an assumption that `sh` is on the container path

2019-06-12 13:56 UTC, liggitt commented
as far as I can tell, https://github.com/kubernetes/kubernetes/issues/78854 is not a regression. lowering priority

/priority important-longterm

2019-06-12 13:57 UTC, liggitt commented
If this is enabling a new feature to work properly, I also don't anticipate this getting backported

2019-06-12 16:20 UTC, siosphere commented
Copying without using single quotes errors (you mentioned this earlier, it does shell expansion which puts too many arguments), with single quotes it works. 
`kubectl cp ./dist/* titan-v1-7d95b6f499-xv2cq:/assets/
[BIG_FILE_LIST_HERE]
error: one of src or dest must be a remote file specification
`
`kubectl cp './dist/*' titan-v1-7d95b6f499-xv2cq:/assets/
[./dist/* titan-v1-7d95b6f499-xv2cq:/assets/]
`
Help message needs to be updated with wildcard examples, and there is a rogue fmt.Println left in the code that prints out the arguments.

2019-06-13 06:02 UTC, dixudx commented
> If this is enabling a new feature to work properly, I also don't anticipate this getting backported

This is not a new feature. Copying with wildcards has been added since 1.14. This PR is a bugfix. @liggitt

2019-06-13 06:04 UTC, dixudx commented
> Copying without using single quotes errors (you mentioned this earlier, it does shell expansion which puts too many arguments), with single quotes it works.

@siosphere  Thanks for helping verifying. 

> Help message needs to be updated with wildcard examples, and there is a rogue fmt.Println left in the code that prints out the arguments.

Nice catch out.

2019-06-16 14:22 UTC, dixudx commented
/retest

2019-06-17 15:58 UTC, dixudx commented
/cc @liggitt

2019-06-20 02:47 UTC, dixudx commented
/retest

2019-06-28 00:16 UTC, liggitt commented
unfortunately I don't have bandwidth to review this. since this is effectively rewriting a functional area we've had many security-related issues in, this requires extremely close review. I also don't see this adding any `*` tests exercising the use cases of the issue it is fixing.

2019-06-28 17:09 UTC, soltysh requested changes
/hold
I agree with Jordan here, I won't be able to look into it sooner than in Auguest when I'm back and I'll be super careful adding new functionality/expanding the current one given the recent problems in this area.

2019-12-09 05:42 UTC, dixudx commented
/remove-lifecycle rotten

2020-04-14 07:48 UTC, dixudx commented
/remove-lifecycle stale

2020-04-14 11:20 UTC, dixudx commented
/remove-lifecycle rotten

2020-09-13 05:12 UTC, closed without merging