[kubeadm] refactor k8s.io/kubernetes/pkg/version -> k8s.io/client-go/pkg/version
kubernetes/kubernetes pull request #78929
Opened 2019-06-12 07:24 UTC by SataQiu

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Refactor k8s.io/kubernetes/pkg/version -> k8s.io/client-go/pkg/version

**Which issue(s) this PR fixes**:

Ref kubernetes/kubeadm#1600

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-06-13 17:20 UTC, yagonobre reviewed
@SataQiu please batch the changes, so we can fix this issue with few prs.

2019-06-14 03:18 UTC, SataQiu commented
/hold
@yagonobre 
Thanks! I will try to add more changes.

2019-06-14 13:24 UTC, neolit123 commented on cmd/kubeadm/.import-restrictions
> +				"k8s.io/client-go/pkg/version"
there is already a rule about client-go near the top of the file.

2019-06-14 13:24 UTC, neolit123 commented
/priority backlog
/approve

2019-06-14 15:33 UTC, rosti approved these changes
Thanks @SataQiu !
I think, that dropping off the `//pkg/version` dependency is good enough for a single PR.
Let's however fix the last dependency in `./cmd/kubeadm/BUILD`. We should probably do what kubectl did and have a local copy of `version_x_defs`.

2019-06-15 15:31 UTC, SataQiu commented
/test pull-kubernetes-bazel-test

2019-06-16 08:48 UTC, SataQiu commented
/test pull-kubernetes-bazel-build

2019-06-16 08:50 UTC, SataQiu commented
/test pull-kubernetes-e2e-gce-device-plugin-gpu
/test pull-kubernetes-integration
/test pull-kubernetes-kubemark-e2e-gce-big

2019-06-17 03:40 UTC, SataQiu commented
/test pull-kubernetes-bazel-build

2019-06-17 03:42 UTC, SataQiu commented
/hold cancel

2019-06-17 03:55 UTC, SataQiu commented
/test pull-kubernetes-e2e-gce-device-plugin-gpu

2019-06-17 03:56 UTC, SataQiu commented
/assign @fejta

2019-06-17 10:35 UTC, neolit123 requested changes

2019-06-17 10:35 UTC, neolit123 commented on cmd/kubeadm/app/version/base.go
> +	gitVersion   = "v0.0.0-master+$Format:%h$"
/hold
i'm not convinced we need a local copy of a format that is already defined in client-go.

2019-06-17 11:05 UTC, SataQiu commented
@neolit123 What puzzles me is how do we resolve the dependency on pkg/version for cmd/kubeadm/BUILD

2019-06-18 03:18 UTC, SataQiu commented
/unassign @fejta

2019-06-18 04:57 UTC, SataQiu commented
@neolit123  Updated!

2019-06-18 12:08 UTC, neolit123 reviewed
/hold cancel
thanks. LGTM this is much better.

final `/lgtm` on @rosti
/assign @rosti

2019-06-20 02:14 UTC, SataQiu commented
@rosti Could you please look at it again?

2019-06-24 09:13 UTC, rosti approved these changes
Thanks @SataQiu !
/lgtm

2019-06-24 13:32 UTC, neolit123 commented
/retest

2019-06-24 19:21 UTC, neolit123 commented
/retest

2019-06-25 02:28 UTC, merged