Remove unnecessary if statement in pv_controller.go
kubernetes/kubernetes pull request #79173
Opened 2019-06-19 15:09 UTC by mysunshine92

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-06-19 15:18 UTC, mysunshine92 commented
/kind cleanup

2019-06-19 15:18 UTC, mysunshine92 commented
/assign @saad-ali

2019-06-19 15:21 UTC, mysunshine92 commented
/priority backlog

2019-06-19 16:25 UTC, mysunshine92 commented
cc @mattjmcnaughton

2019-06-20 12:04 UTC, mattjmcnaughton requested changes
/ok-to-test

Thanks for this change :)

Overall, the code looks good to me. My one concern is that I think some of the existing comments are quite confusing now. Mind updating them? I included some ideas in my review.

2019-06-20 12:04 UTC, mattjmcnaughton commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +			// Objects not saved, next syncPV or syncClaim will try again
My concern is that the lack of if statement now makes it look as if this `// Objects not saved...` comment is always true. It is only the case if the `ctrl.bind` command fails (i.e. returns an error).

Could you update the comment to indicate that?

2019-06-20 12:04 UTC, mattjmcnaughton commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +			// Objects not saved, next syncPV or syncClaim will try again
Same as above

2019-06-20 12:04 UTC, mattjmcnaughton commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +		_, err := ctrl.updateVolumePhase(volume, v1.VolumeAvailable, "")
Samve as above - it appears that it's always the case that nothing was saved.

2019-06-20 12:04 UTC, mattjmcnaughton commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +			// Nothing was saved; we will fall back into the same
Same as above.

2019-06-20 12:04 UTC, mattjmcnaughton commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +			// Release failed, we will fall back into the same condition
Same as above.

2019-06-20 12:04 UTC, mattjmcnaughton commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +			// Nothing was saved; we will fall back into the same
Same as above.

2019-06-20 12:04 UTC, mattjmcnaughton commented on pkg/controller/volume/persistentvolume/pv_controller.go
> +				// Deletion failed, we will fall back into the same condition
Same as above.

2019-11-17 13:53 UTC, closed without merging