Moving pkg/kubectl/util to staging
kubernetes/kubernetes pull request #79246
Opened 2019-06-20 23:23 UTC by pswica

-  Moves pkg/kubectl/util  to staging.
- Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/util
- Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl
/priority important-longterm
/hold
/assign @seans3 

```release-note
NONE
```

2019-06-28 17:39 UTC, seans3 commented
/ok-to-test

2019-06-28 20:58 UTC, pswica commented
/hold cancel

2019-06-28 22:14 UTC, seans3 requested changes
Files outside of the `pkg/kubectl` tree should not reference into this tree. Conceptually, we are moving into an entire new repository `kubernetes/kubectl`. So any references will go bad once we move out of staging and into our own repository. We need to update these references so that they are under `staging/src/k8s.io/kubectl`.

2019-06-28 22:14 UTC, seans3 commented on hack/boilerplate/boilerplate.py
> +                "staging/src/k8s.io/kubectl/pkg/generated/bindata.go"]
This file should not have references to files within staging.

2019-06-28 22:14 UTC, seans3 commented on hack/generate-bindata.sh
> +BINDATA_OUTPUT="staging/src/k8s.io/kubectl/pkg/generated/bindata.go"
This file should not have references to files within staging.

2019-06-29 01:13 UTC, pswica commented
/retest

2019-06-30 19:11 UTC, pswica commented
/cc @nikhita /cc @apelisse 
PTAL
This is the last thing to move in pkg/kubectl/util except some sensitive generated code

2019-07-08 15:44 UTC, dims commented
/uncc

2020-01-21 15:51 UTC, apelisse commented
/close

I think this PR is obsolete, since a lot of things moved to staging already. Feel free to re-open if needed.

2020-01-21 15:51 UTC, closed without merging