Make Admission and Webhook context-aware
kubernetes/kubernetes pull request #79376
Opened 2019-06-25 16:42 UTC by answer1991

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Add a method called `GetContext` which can get the request context in admission.Attributes. With this method, we can make Admission and Webhook context-aware to fix goruntine backlog in large-scale scene.

**Which issue(s) this PR fixes**:

Fixes #78783

**Special notes for your reviewer**:

Nothing yet.

**Does this PR introduce a user-facing change?**:

```release-note
Add a method called GetContext which can get the request context in admission.Attributes. With this method, we can make Admission and Webhook context-aware to fix goruntine backlog in large-scale scene.
```

2019-06-26 07:25 UTC, zhangxiaoyu-zidif commented
/ok-to-test

2019-06-27 20:08 UTC, fedebongio commented
/assign @caesarxuchao @jpbetz

2019-06-30 03:09 UTC, gaorong requested changes

2019-07-01 03:02 UTC, answer1991 commented on staging/src/k8s.io/apiserver/pkg/admission/attributes.go
> +func NewAttributesRecordWithContext(object runtime.Object, oldObject runtime.Object, kind schema.GroupVersionKind, namespace, name string, resource schema.GroupVersionResource, subresource string, op
It is a constructed function, also need to follow that specification?

2019-07-01 11:52 UTC, gaorong commented on staging/src/k8s.io/apiserver/pkg/admission/attributes.go
> +func NewAttributesRecordWithContext(object runtime.Object, oldObject runtime.Object, kind schema.GroupVersionKind, namespace, name string, resource schema.GroupVersionResource, subresource string, op
oh sorry, I saw it wrong, I'm okay with this.

2019-08-19 15:28 UTC, liggitt commented
> I think context should be passed directly to Admit/Validate as the first arg

in progress in https://github.com/kubernetes/kubernetes/pull/81602

2019-08-20 04:05 UTC, answer1991 commented
@liggitt 

> I think context should be passed directly to Admit/Validate as the first arg

yes, it looks better to me too. I did plumbing context in attributes just want to avoid breaking interface and changing too much codes.

I will close this PR

2019-08-20 04:05 UTC, closed without merging