RateLimiter context aware and fix request may hang issue
kubernetes/kubernetes pull request #79375
Opened 2019-06-25 15:40 UTC by answer1991

**What type of PR is this?**

/kind bug
/kind feature

**What this PR does / why we need it**:

1. RateLimiter add a context-aware method which is really necessary in async scene
2. fix client-go request goruntine backlog in async scene

**Which issue(s) this PR fixes**:

Fixes #78766

**Special notes for your reviewer**:

The new method added in RateLimiter called `Wait`, it's context-aware, which is recommended to replace method `Accept` if the caller has context.

**Does this PR introduce a user-facing change?**:

Interface RateLimiter in `client-go/util/flowcontrol` package add a context-aware method called `Wait`.

```release-note
RateLimiter add a context-aware method, fix client-go request goruntine backlog in async timeout scene.
```

2019-06-25 16:22 UTC, draveness requested changes
/ok-to-test
/priority backlog

2019-06-25 17:04 UTC, answer1991 commented on staging/src/k8s.io/client-go/rest/request.go
> +	var err error
This method will be called frequently when QPS is high, using defer will influence performance.

2019-06-26 03:16 UTC, answer1991 commented
/reset

2019-06-26 07:42 UTC, zhangxiaoyu-zidif commented
/retest

2019-06-27 20:07 UTC, fedebongio commented
/assign @aaron-prindle

2019-06-27 20:07 UTC, yliaog commented
/cc

2019-06-27 22:28 UTC, liggitt commented
based on POC in https://github.com/liggitt/kubernetes/commit/08dbd4ecc25554a868ec50f6693479f3acd708c5

/lgtm
/approve

2019-06-28 00:43 UTC, merged

2019-06-28 06:23 UTC, tedyu commented on staging/src/k8s.io/client-go/util/flowcontrol/throttle.go
> +	return errors.New("can not be accept")
can not be accept -> cannot be accepted