move images from gcr.io to quay.io
kubernetes/kubernetes pull request #79390
Opened 2019-06-25 21:39 UTC by coffeepac

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
moves images from being hosted in `gcr.io` to `quay.io`.  The reason for this move is that `gcr.io` isn't free, `quay.io` is and I don't have a personal budget to host these images.

Once this is merged I'm going to turn off access to the existing images.  If people need older images I can rebuild specific versions when asked.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-06-25 21:41 UTC, monotek commented
/ok-to-test

2019-06-25 22:53 UTC, coffeepac commented
/test pull-kubernetes-e2e-gce-100-performance
/test pull-kubernetes-kubemark-e2e-gce-big

2019-06-26 06:09 UTC, cblecker commented
/hold

@coffeepac Can we deprecate this code completely? Is it used somewhere? It's concerning that binary images in k/k are in repos that aren't in the project's control.

cc: @kubernetes/sig-cluster-lifecycle-pr-reviews

2019-06-26 09:15 UTC, monotek commented
@cblecker 

Also the current gcr.io docker repo (gcr.io/fluentd-elasticsearch/fluentd) is not in the projects control.
The problem now is that gcr.io is charging to much (private) money so we decided to move to a free registry (https://quay.io/organization/fluentd_elasticsearch).

The reason for the move away from the the original repo (gcr.io/google-containers/fluentd-elasticsearch) has been, that only Google employees we're able to build the images manually and we sometimes had to wait for several weeks to get this done, when we liked to release a new version of the image. 

/test pull-kubernetes-e2e-gce-100-performance

2019-06-26 09:22 UTC, monotek requested changes

2019-06-26 09:22 UTC, monotek commented on cluster/addons/fluentd-elasticsearch/es-image/Makefile
> +    docker push ${PREFIX}/${IMAGE}:${TAG}
please add push with latest tag too...

2019-06-26 09:22 UTC, monotek commented on cluster/addons/fluentd-elasticsearch/fluentd-es-image/Makefile
> +	docker push ${PREFIX}/${IMAGE}:${TAG}
please add push with latest tag too...

2019-06-26 13:26 UTC, neolit123 commented
/hold
/assign @spiffxp @dims 
PTAL WRT code organization - GCP / cluster + k8s-infra related.

2019-06-26 13:32 UTC, neolit123 commented
> What code do you want to deprecate? The whole monitoring stuff? Imho this is used a lot. The image is also used in the fluentd-elasticsearch helm chart: https://hub.helm.sh/charts/kiwigrid/fluentd-elasticsearch

`/cluster` is deprecated and tools like juju-charms moved out already.
if `/cluster/addons/fluentd-elasticsearch` is widely used then this is a signal for this addon to move out of the directory.

2019-06-26 13:36 UTC, monotek commented
> `/cluster` is deprecated and tools like juju-charms moved out already.
> if `/cluster/addons/fluentd-elasticsearch` is widely used then this is a signal for this addon to move out of the directory.

What would be the right directory now?

2019-06-26 13:42 UTC, neolit123 commented
> What would be the right directory now?

juju moved out of k/k.

2019-06-26 14:06 UTC, monotek commented
@piosz what are your thougts?

2019-06-26 14:11 UTC, detiber commented
Assuming there is a SIG to provide sponsorship, `github.com/kubernetes-sigs` is probably the best home.

2019-06-26 16:40 UTC, coffeepac commented
a. this is owned by sig-instrumentation.  
b. I have opened this feature request https://github.com/kubernetes/kubernetes/issues/79432 to make the move

however, I request both @cblecker and @neolit123 release their holds on this PR as I am spending money I shouldn't be to continue to host these images.  I do not have stats for how large an impact it would be if I cut off access to these images but it wouldn't be non-zero.  please see: https://github.com/kubernetes/kubernetes/issues/78684

2019-06-26 16:43 UTC, cblecker commented
@coffeepac I'm poking some folks to see what we can do here. I don't want you to keep having to pay for things, but I also don't want to thrash where this image is located.

I understand this is urgent for cost reasons, and I'll be circling back with an answer ASAP.

2019-06-26 16:44 UTC, coffeepac commented
thanks @cblecker.  this is entirely my own fault for incurring these charges as well.  I'm bad at reading fine print apparently.

2019-06-26 20:06 UTC, monotek approved these changes

2019-06-27 11:44 UTC, monotek commented
/lgtm

2019-06-28 16:48 UTC, coffeepac commented
@cblecker any progress on this or can we do a bit of location thrash while we sort out a long term solution?

2019-06-28 18:10 UTC, spiffxp commented
/hold cancel
The wg-k8s-infra way (which I highly encourage and will eventually get pushy that someone use because it would also allow you to do this for "free") would be to request a staging repo, and using that for now.  https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#creating-staging-repos

This would also result in location thrash though, as we don't currently promote from staging repos to `k8s.gcr.io`.  So, let's thrash away.

2019-06-28 18:19 UTC, cblecker commented
@coffeepac Immediate term, yeah, we can just move the reference location.

The next step after this is I'd like to have a plan for moving this code out, I think. The manifests look stale, this is just the image generation piece, while other pieces like the helm chart for installation https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L2 exist elsewhere.

There's also a couple other references to the old image location in our code base: https://cs.k8s.io/?q=gcr.io%2Ffluentd-elasticsearch

WDYT?

2019-06-28 18:28 UTC, coffeepac commented
Happy to move the code into a sig-inst repo.  I tried doing that 6 months ago and it wasn't possible for some reason, I think it was tied to the build process for the add-on manager?  But k8s infra has come along since then so I'm happy to do it.  

I'll get a plan onto the feature ticket early next week for discussion. 

Thanks for the help friends, I know this is a poor solution and I appreciate you taking it to help out my old poor decision.

2019-06-28 19:43 UTC, merged

2019-06-29 21:08 UTC, monotek commented
If it helps I'm willing to move fluentd-elasticsearch helm chart out of the Kiwigrid repo. Is there already an official k8s org helm registry available somewhere or would we need to create one?

2019-07-17 18:41 UTC, vguaglione commented
Where is this image on quay.io? I've tried the following:

docker pull quay.io/fluentd-elasticsearch/fluentd:v2.5.1
docker pull quay.io/fluentd-elasticsearch/fluentd:latest
docker pull quay.io/fluentd-elasticsearch/fluentd

and all three return the following error:

Error response from daemon: unauthorized: access to the requested resource is not authorized

2019-07-18 11:29 UTC, monotek commented
https://quay.io/repository/fluentd_elasticsearch/fluentd?tab=tags