Short-circuit the evaluation of `cpuFraction` and `memoryFraction`
kubernetes/kubernetes pull request #79453
Opened 2019-06-27 02:47 UTC by chendave

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
refactor the code to make it more efficient.

```release-note
NONE
```

2019-06-27 02:52 UTC, chendave commented
/assign @bsalamat

2019-06-27 02:53 UTC, chendave commented
pls help to trigger the test, thanks!

2019-06-27 05:17 UTC, draveness requested changes
/ok-to-test
/priority backlog
/sig scheduling

please take a look at the comments, others LGTM

2019-06-27 05:17 UTC, draveness commented on pkg/scheduler/algorithm/priorities/balanced_resource_allocation.go
>  			// if requested >= capacity, the corresponding host should never be preferred.
You could remove the comment here

2019-06-27 05:56 UTC, chendave commented on pkg/scheduler/algorithm/priorities/balanced_resource_allocation.go
>  			// if requested >= capacity, the corresponding host should never be preferred.
sure, will update.

2019-06-27 05:58 UTC, chendave commented
@draveness thanks for the review, pls take another look, thanks!

2019-06-27 06:56 UTC, draveness approved these changes
/lgtm

Thanks!

2019-07-10 13:16 UTC, draveness reviewed
Kindly ping @bsalamat for approval, this is an easy one.

2019-07-10 21:09 UTC, bsalamat reviewed
/lgtm
/approve

Thanks, @chendave!

2019-07-10 23:24 UTC, merged