Pass desiredPods to CleanupPods
kubernetes/kubernetes pull request #79681
Opened 2019-07-03 01:51 UTC by tedyu

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In manager#CleanupPods, activePods is traversed to produce desiredPods.

However, the caller has already computed desiredPods.

This PR passes the desiredPods to CleanupPods, eliminating the unneeded traversal.

```release-note
NONE
```

2019-07-03 02:02 UTC, draveness requested changes

2019-07-03 02:02 UTC, draveness commented on pkg/kubelet/prober/prober_manager.go
>  	// It takes a list of "active pods" which should not be cleaned up.
This comment should be updated if we change the method arguments.

2019-07-03 02:36 UTC, tedyu commented
@tallclair
Can you take a look ?

2019-07-03 13:52 UTC, mattjmcnaughton approved these changes
/lgtm

Confirming that the change from using `empty` to `sets.Empty` is necessary for this PR? If not, could I ask that we have two separate diffs - one to pass `desiredPods` to `CleanupPods` and another to replace `empty` with `sets.Empty`?

2019-07-03 16:48 UTC, tedyu commented
The change from using empty to sets.Empty is necessary.
I first tried passing empty which resulted in circular dependency.

2019-07-03 16:49 UTC, tedyu commented
/assign @yujuhong

2019-07-05 06:16 UTC, tedyu commented
@tallclair
Can you take a look ?

2019-07-08 13:35 UTC, tedyu commented
ping @derekwaynecarr for review

2019-07-08 19:24 UTC, tedyu commented
@tallclair
Can you take a look ?

2019-07-09 13:25 UTC, tedyu commented
ping @tallclair for review

2019-07-10 13:13 UTC, tedyu commented
@tallclair
Please review

2019-07-11 14:38 UTC, tedyu commented
@derekwaynecarr
Please review

2019-07-11 18:44 UTC, vishh approved these changes
/approve

2019-07-12 00:01 UTC, merged