[Failing Tests - GH- 79533] use apps/v1 instead apps/v1beta1 since that is deprecated
kubernetes/kubernetes pull request #79747
Opened 2019-07-03 21:18 UTC by cpanato

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
update tests to use apps/v1 for deployments instead of apps/v1beta1

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/79533

**Special notes for your reviewer**:

2019-07-03 21:19 UTC, cpanato commented
/cc @alejandrox1

2019-07-04 10:47 UTC, hoegaarden commented
@cpanato

Some questions:
- Can you point me somewhere to a failing dashboard that shows this issue for 1.15?
- We don't fix in master first and cherry-pick back to older releases (if needed) via the [cherry pick process]?

[cherry pick process]: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

2019-07-04 11:16 UTC, cpanato commented
@hoegaarden I was thinking this only applies for 1.15 based on this comment: https://github.com/kubernetes/kubernetes/issues/79533#issuecomment-507053235
but looks like I misunderstanding, sorry. If this is not correct can you help me or give some directions?

2019-07-04 14:52 UTC, cpanato commented
maybe @liggitt can take a look here as well since it is similar to https://github.com/kubernetes/kubernetes/pull/79778

2019-07-04 14:59 UTC, liggitt commented
Same comment as https://github.com/kubernetes/kubernetes/pull/79778#issuecomment-508492964 applies here

Did you run this test against a master API server and verify it passes?

/lgtm
/approve

2019-07-05 13:49 UTC, alejandrox1 requested changes
Thank you @cpanato for taking a look at this so promptly.
You code change to the test should be the solution to the problem we have been seeing in [master-informing](https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-master-parallel).

However, you are making this PR against 1.15 branch which doesn't have the failures reported in #79533
see https://testgrid.k8s.io/sig-release-1.15-blocking#gce-cos-k8sbeta-default

Could you please redo your PR against master?

2019-07-05 14:35 UTC, liggitt commented
@alejandrox1 this test is failing in the upgrade suite (https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-master-parallel) because the release-1.15 tests are being run against a 1.16 API server. This test has already been changed in master. This fix against the release-1.15 branch is required.

2019-07-05 14:54 UTC, alejandrox1 commented
Thank you @liggitt for the clarification. 

/lgtm
/priority critical-urgent
/release-note-none
/cc @kubernetes/patch-release-team

2019-07-05 15:23 UTC, liggitt commented
/retest

2019-07-05 16:08 UTC, merged