[Failing tests] skip test if the server does not serve extensions/v1beta1 since this is deprecated
kubernetes/kubernetes pull request #79778
Opened 2019-07-04 08:47 UTC by cpanato

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
skip `deployment should support rollback` test if the server does not serve the extensions/v1beta1 api

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/79740

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

/cc @alejandrox1

2019-07-04 11:03 UTC, hoegaarden commented
@cpanato

Some questions:
- Can you point me somewhere to a failing dashboard that shows this issue for 1.15?
- Why don't we fix in master first and cherry-pick back to older releases (if needed) via the [cherry pick process]?

[cherry pick process]: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

2019-07-04 14:00 UTC, liggitt commented
The test was already changed in master as part of removing the deprecated API. Picking the entire change back to 1.15 is not appropriate

2019-07-04 14:01 UTC, liggitt commented
/lgtm
/approve
/retest

2019-07-05 06:51 UTC, cpanato commented
@liggitt do we need to add any release notes? the label `do-not-merge/release-note-label-needed` is in place and also de ` do-not-merge/cherry-pick-not-approved` what is the process for those? thanks!

2019-07-05 13:53 UTC, alejandrox1 requested changes
Same as https://github.com/kubernetes/kubernetes/pull/79747#pullrequestreview-258414847
We need to evaluate this change against master.
`[sig-apps] Deployment deployment should support rollback` is passing in 1.15 https://testgrid.k8s.io/sig-release-1.15-blocking#gce-cos-k8sbeta-default

2019-07-05 14:35 UTC, liggitt commented
@alejandrox1 this test is failing in the upgrade suite (https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-master-parallel) because the release-1.15 tests are being run against a 1.16 API server. This test has already been changed in master. This fix against the release-1.15 branch is required.

2019-07-05 14:56 UTC, alejandrox1 commented
Again, thank you @liggitt for the clarification.

/lgtm
/priority critical-urgent
/release-note-none
/cc @kubernetes/patch-release-team

2019-07-05 16:08 UTC, merged