Add CSIDriver creation factory to e2e framework
kubernetes/kubernetes pull request #80375
Opened 2019-07-19 19:56 UTC by wongma7

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**: Now that we expect drivers to include these with their install manifests, this will be useful: https://github.com/kubernetes-csi/docs/pull/183/files

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-07-19 19:57 UTC, wongma7 commented
/sig storage
/cc @pohly 
/cc @jsafrane 
thanks all.

2019-07-19 20:30 UTC, wongma7 commented
/retest

2019-07-19 21:25 UTC, wongma7 commented
/retest

2019-07-20 14:23 UTC, cwdsuzhou commented on test/e2e/framework/create.go
> +	{"CSIDriver"}:          &csiDriverFactory{},
Can we add it in alphabetical order?

2019-07-22 10:18 UTC, pohly requested changes
Makes sense, but as @cwdsuzhou said, please keep the `factories` map sorted by name.

2019-07-22 17:21 UTC, wongma7 commented on test/e2e/framework/create.go
> +	{"CSIDriver"}:          &csiDriverFactory{},
fixed

2019-07-22 18:04 UTC, wongma7 commented
/retest

2019-07-22 23:16 UTC, wongma7 commented
/retest

2019-07-23 00:09 UTC, wongma7 commented
/retest

2019-07-23 07:04 UTC, pohly approved these changes
/lgtm
/approve

2019-07-23 08:28 UTC, merged