Fix es initial cluster formation & update es to 7.2.0
kubernetes/kubernetes pull request #80421
Opened 2019-07-22 10:00 UTC by lostick

**What type of PR is this?**
/kind bug
/kind feature

**What this PR does / why we need it**:
• Fix `elasticseatch` broken service discovery `7.1.1` upgrade
• Bump `elasticsearch` / `kibana` to latest stable (`7.2.0`)
• Fix makefile indentation

**Which issue(s) this PR fixes**:
Fixes #80282

**Special notes for your reviewer**:
• We need to wait for @monotek to push the changes on `quay.io/fluentd_elasticsearch/elasticsearch`

• Both `7.1.1` and `7.2.0` were built and tested with [lostick/fluentd-elasticsearch](https://cloud.docker.com/repository/docker/lostick/fluentd-elasticsearch) image.
```bash
# elasticsearch health endpoint
$ curl -s  http://elasticsearch-logging:9200/_cluster/health | jq .
{
  "cluster_name": "kubernetes-logging",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 2,
  "number_of_data_nodes": 2,
  "active_primary_shards": 4,
  "active_shards": 8,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}

# kibana health endpoint
$ curl -s http://kibana-logging:5601/api/status | jq .status.overall
{
  "state": "green",
  "title": "Green",
  "nickname": "Looking good",
  "icon": "success",
  "uiColor": "secondary",
  "since": "2019-07-22T09:25:01.239Z"
}
```

**Does this PR introduce a user-facing change?**:
```release-note
Kibana has been slightly revamped/improved in the latest version
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
```

2019-07-22 10:01 UTC, lostick commented
/hold

@monotek , could you push the changes on quay.io ? thanks.

2019-07-23 08:52 UTC, lostick commented
/assign @monotek

2019-07-24 10:03 UTC, monotek commented
/ok-to-test

2019-07-24 10:04 UTC, monotek commented
/assign @coffeepac

2019-07-24 10:52 UTC, lostick commented
@monotek did you push a `7.2.0` tag with the fixes in https://quay.io/repository/fluentd_elasticsearch/elasticsearch?

2019-07-24 14:16 UTC, monotek requested changes

2019-07-24 14:16 UTC, monotek commented on cluster/addons/fluentd-elasticsearch/es-image/Makefile
> +	docker build --tag ${PREFIX}/${IMAGE}:${TAG} .
please add:

```docker build --tag ${PREFIX}/${IMAGE}:latest .```

2019-07-24 14:17 UTC, monotek commented
> @monotek did you push a `7.2.0` tag with the fixes in https://quay.io/repository/fluentd_elasticsearch/elasticsearch?

latest tag was missing... therefore push failed...
added latest tag and repushed it...

2019-07-24 15:44 UTC, lostick commented
/hold cancel


> > @monotek did you push a `7.2.0` tag with the fixes in https://quay.io/repository/fluentd_elasticsearch/elasticsearch?
> 
> latest tag was missing... therefore push failed...
> added latest tag and repushed it...

Thanks heaps!

/hold cancel

2019-07-24 20:39 UTC, monotek approved these changes
/lgtm

2019-07-25 07:18 UTC, monotek commented
/approve

2019-07-25 08:38 UTC, merged