doc: update guide to make the command works as expected
kubernetes/kubernetes pull request #80424
Opened 2019-07-22 10:33 UTC by chendave

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
user can run commands successfully by following the guide. 
**Which issue(s) this PR fixes**:
Fixes #80422

```release-note
NONE
```

2019-07-23 02:06 UTC, ping035627 commented
/ok-to-test

2019-07-23 05:18 UTC, chendave commented
/assign @mkumatag

2019-07-23 14:07 UTC, neolit123 commented
/cc @bclau

2019-07-23 15:53 UTC, mkumatag commented
/lgtm

2019-07-26 22:52 UTC, spiffxp requested changes
When I try cloning with no name, I end up cloning into `localhost`.  I don't think this ever cloned into `8000` since it was added via https://github.com/kubernetes/kubernetes/pull/19857
```
spiffxp@spiffxp-macbookpro:agnhost (master %)$ go run agnhost.go fake-gitserver&
[1] 33375
spiffxp@spiffxp-macbookpro:agnhost (master %)$ git clone http://localhost:8000
Cloning into 'localhost'...
warning: You appear to have cloned an empty repository.
spiffxp@spiffxp-macbookpro:agnhost (master %)$ git version
git version 2.18.0
```

2019-07-26 22:52 UTC, spiffxp commented on test/images/agnhost/fakegitserver/gitserver.go
> +	Long: `When doing "git clone http://localhost:8000", you will clone an empty git repo named "8000" on local.
```suggestion
	Long: `When doing "git clone http://localhost:8000", you will clone an empty git repo named "localhost" on local.
```

2019-07-26 22:52 UTC, spiffxp commented on test/images/agnhost/README.md
> +repo named `8000` on local. You can also use `git clone http://localhost:8000 my-repo-name` to
```suggestion
repo named `localhost` on local. You can also use `git clone http://localhost:8000 my-repo-name` to
```

2019-07-27 09:37 UTC, chendave commented on test/images/agnhost/fakegitserver/gitserver.go
> +	Long: `When doing "git clone http://localhost:8000", you will clone an empty git repo named "8000" on local.
Good catch!

2019-07-29 18:46 UTC, spiffxp commented
/priority important-longterm
/lgtm
/approve

2019-07-29 22:05 UTC, spiffxp approved these changes

2019-07-30 00:33 UTC, spiffxp commented
/retest

2019-07-30 02:13 UTC, chendave commented
/test pull-kubernetes-dependencies

2019-07-30 02:13 UTC, chendave commented
/test pull-kubernetes-e2e-gce

2019-07-30 02:45 UTC, chendave commented
/test pull-kubernetes-e2e-gce

2019-07-30 05:06 UTC, chendave commented
/test pull-kubernetes-dependencies

2019-07-30 06:27 UTC, chendave commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-07-30 11:26 UTC, claudiubelu approved these changes

2019-07-30 12:33 UTC, merged