Fix error collides with imported package name
kubernetes/kubernetes pull request #80953
Opened 2019-08-03 18:33 UTC by Moriadry

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
Fix error collides with imported package name for e2e test

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

2019-08-03 19:23 UTC, BenTheElder commented
/ok-to-test

2019-08-03 19:23 UTC, BenTheElder commented
/priority backlog

2019-08-03 19:46 UTC, BenTheElder requested changes
Hi, thanks for the PR, I see at least one change that is bad though and am suggestion a number of possibly more idiomatic / informative names 😅

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/kubelet_stats.go
> +	kubeletstatsv1alpha1str := string(raw)
what about just `kubeletStats` ? or `heapStats`? it's unusual to put the type in a variable name in go and this is pretty long. 

https://github.com/golang/go/wiki/CodeReviewComments#variable-names

```suggestion
	heapStats := string(raw)
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/kubelet_stats.go
> +	kubeletstatsv1alpha1map := make(e2ekubelet.ResourceUsagePerContainer)
`usagePerContainer`?
```suggestion
	usagePerContainer := make(e2ekubelet.ResourceUsagePerContainer)
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/framework.go
> +	labelmaps := map[string]string{
nit: It's only one map, not "maps", `podLabels` would be more descriptive
```suggestion
	podLabels := map[string]string{
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/lifecycle/upgrade.go
> +	traceroutepath, err := exec.LookPath("traceroute")
for the `exec.Command` below which appears to be the only usage, `exec.Command(traceroute, ...)` is very readable but a bit less verbose

```suggestion
	traceroute, err := exec.LookPath("traceroute")
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/providers/gce/gce.go
> +		e2ecomputeservice := p.gceCloud.ComputeServices().GA
```suggestion
		computeService := p.gceCloud.ComputeServices().GA
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/test_context.go
> +	configcmd := clientcmdapi.NewConfig()
```suggestion
	configCmd := clientcmdapi.NewConfig()
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/util.go
> +	hosturl, err := url.Parse(TestContext.Host)
```suggestion
	hostURL, err := url.Parse(TestContext.Host)
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/util.go
> +	var dscontroller appsv1.DaemonSet
this is a daemonset, not a controller?
```suggestion
	var ds appsv1.DaemonSet
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/viperconfig/viperconfig_test.go
> +	viperconfig := `
```suggestion
	viperConfig := `
```

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/util.go
> +	for _, containerruntime := range runtimes {
```suggestion
	for _, containerRuntime := range runtimes {
```

or just
```suggestion
	for _, rt := range runtimes {
```

go encourages short names for local variables with limited scope

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/util.go
> +				e2elog.Logf("Conflict when trying to add/update avoidPonds %v to %v", avoidPods, nodeName)
why was this changed? ponds? please revert this line

2019-08-03 19:46 UTC, BenTheElder commented on test/e2e/framework/util.go
> +	jsondata, err := utilyaml.ToJSON(data)
```suggestion
	dataJSON, err := utilyaml.ToJSON(data)
```

2019-08-04 05:05 UTC, Moriadry commented
Thanks for your review. I'm not familiar with variable name style in go, and  will fix it ASAP.

2019-08-04 07:38 UTC, Moriadry commented
/retest

2019-08-05 23:27 UTC, BenTheElder approved these changes
/approve
needs a rebase, sorry about that, and thanks for the PR!

2019-08-06 02:59 UTC, Moriadry commented
@BenTheElder 
Hi, I used wrong command `git merge` to resolve it, It's okay then.
So, will it be done if I squash my commits?

2019-08-06 21:29 UTC, BenTheElder commented
/retest
/lgtm

2019-08-06 21:30 UTC, BenTheElder commented
the current git state looks fine I think

2019-08-07 06:57 UTC, merged