kubectl: add port-forward svc/ completion
kubernetes/kubernetes pull request #81221
Opened 2019-08-09 12:57 UTC by sroskelley

/kind feature
/sig cli
**What this PR does / why we need it**:
adds bash completion for `kubectl port-forward svc/<tab>`

**Which issue(s) this PR fixes**:
Fixes # NONE

**Special notes for your reviewer**:
Thanks for your work. 

**Does this PR introduce a user-facing change?**:
```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

2019-08-15 01:11 UTC, sroskelley commented
/assign @adohe

2019-11-13 09:19 UTC, soltysh requested changes

2019-11-13 09:19 UTC, soltysh commented on pkg/kubectl/cmd/cmd.go
> +	    __kubectl_parse_get "deploy" "{{ range .items  }}deploy/{{ .metadata.name }} {{ end }}"
You'd need to use long names, not aliases. You didn't cover all possible controllers.

2019-11-19 17:28 UTC, sroskelley commented on pkg/kubectl/cmd/cmd.go
>              __kubectl_parse_get "jobs" "{{ range .items  }}job/{{ .metadata.name }} {{ end }}"
Use long controller names per @soltysh request. But I'm not aware of any other controllers that have support for fetching logs.

2019-11-20 00:49 UTC, closed without merging