more e2eservice.TestJig cleanups
kubernetes/kubernetes pull request #81479
Opened 2019-08-15 17:50 UTC by danwinship

**What this PR does / why we need it:**
A bit more `e2eservice` cleanup: When `test/e2e/framework/service` was first created, a lot of service test code got crammed into `TestJig` even though it didn't use any of `TestJig`'s members. Make that code available outside of `TestJig`.

(There are other functions in `TestJig` that don't currently make much use of it, but I have further cleanup plans that will make them fit better there.)

/kind cleanup
/priority important-longterm
/sig network

```release-note
NONE
```

2019-08-15 18:24 UTC, neolit123 commented
+1 on the cleanup. CI seems to be reporting some errors (e.g. the bazel jobs).

2019-08-15 23:07 UTC, fejta commented
/uncc
/cc @timothysc

2019-08-16 11:01 UTC, danwinship commented
@neolit123 build error fixed, tests pass now

2019-08-16 12:09 UTC, neolit123 commented
/assign @andrewsykim 
PTAL for /test approval. thanks!

2019-08-16 12:09 UTC, neolit123 commented
/lgtm

2019-08-16 15:11 UTC, danwinship commented
/test pull-kubernetes-e2e-gce

2019-09-03 16:25 UTC, timothysc requested changes
/hold 

This is just a code shuffle vs. breaking up into logical units.  The work we are doing in the testing commons is to break apart the framework into logic sub-packages that can be be vendored whose transitive dep-graph is logical and sound.

2019-09-03 16:25 UTC, timothysc commented on test/e2e/framework/service/affinity_checker.go
> +func CheckAffinity(execPod *v1.Pod, targetIP string, targetPort int, shouldHold bool) bool {
So I don't think this shuffling makes sense to this package.  I know they were lumped before, but as we are breaking apart the framework they should go into logical sub-packages that make sense to vendor independently.  I'd argue that this should really be in the pod library.

2019-09-03 16:25 UTC, timothysc commented on test/e2e/framework/service/resource.go
> +func CreatePausePodDeployment(cs clientset.Interface, name, ns string, replica int32) *appsv1.Deployment {
this should be in the deployment library.

2019-09-03 16:25 UTC, timothysc commented on test/e2e/framework/service/util.go
> +func GetNodes(cs clientset.Interface, maxNodesForTest int) (nodes *v1.NodeList) {
This should not be in service.

2019-09-03 17:47 UTC, danwinship commented
> This is just a code shuffle vs. breaking up into logical units.

Sure, this was not intended to be part of the e2e-wide cleanup effort (which I didn't even know was happening when I started this). I was just trying to make `e2eservice.TestJig` less of a dumpster fire while minimizing unrelated changes.

>  I'd argue that [`CheckAffinity`] should really be in the pod library.

It is testing Service-specific functionality (`SessionAffinity`). Maybe the `targetIP` and `targetPort` parameters should be renamed `serviceIP` and `servicePort` to make that clearer. (It can't just take a `v1.Service` as the argument because on some tests we want to use the service's cluster IP but in others we want to use an ingress IP.)

> [`CreatePausePodDeployment`] should be in the deployment library.

Hm... it looks like `e2edeployment.NewDeployment` covers 80% of it, and the rest is very specific to the 2 `test/e2e/network/service.go` tests that currently use it, so that could be put in a small helper function there.

> [`GetNodes` with `maxNodes`] should not be in service.

Yes, it looks like the idea of `GetReadySchedulableNodesOrDie`-but-not-too-many pops up in a bunch of places throughout e2e...

2019-09-03 18:59 UTC, andrewsykim commented
Agreed with Tim that the Deployment / Node utilities should probably be somewhere else (though to be fair they already exist in the TestJig so maybe it's okay to address this in a follow-up PR), but +1 on decoupling generally usable functions from Service TestJig.

2019-09-05 15:48 UTC, danwinship commented
- rebased around `e2elog` removal
- renamed `CheckAffinity` args to make it clearer that it's service-specific
- made `CreatePausePodDeployment` a local function in `test/e2e/network/service.go` (and used `e2edeployment` helper functions)
- dropped the changes related to `GetNodes`/`GetNodesNames`, which will instead be removed by #82291

2019-09-05 16:52 UTC, andrewsykim commented
/hold cancel 
/approve
/lgtm

2019-09-10 21:31 UTC, merged