Fixes missing authenticated group for apiserver loopback connection
kubernetes/kubernetes pull request #81503
Opened 2019-08-16 07:36 UTC by yue9944882

the groups `system:authenticated` and `system:unauthenticated` are supposed to cover all users requesting apiserver, but it doesn't work for apiserver's bearer loopback client. for now it's merely `["system:masters"]`. 

moving the authenticated-group-appender to generic-apiserver so that it works after loopback authn..

/sig api-machinery

@lavalamp @deads2k @MikeSpreitzer @aaron-prindle @mars1024 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-08-16 14:18 UTC, yue9944882 commented
/retest

2019-08-22 03:09 UTC, MikeSpreitzer commented
/retest

2019-08-22 19:10 UTC, MikeSpreitzer approved these changes
Sorry, confusion, I attached a review to the wrong PR.  Never mind me here.

2019-08-22 20:40 UTC, deads2k commented
/assign @mo

@mo, ptal

2019-08-22 20:44 UTC, deads2k commented
/assign @enj

@enj sneaky

2019-08-23 17:22 UTC, enj requested changes
While I do think it is inconsistent for the group to be missing, it should cause no issues from an authorization perspective.

2019-08-23 17:22 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/server/config.go
>  	AuthorizeClientBearerToken(c.LoopbackClientConfig, &c.Authentication, &c.Authorization)
`AuthorizeClientBearerToken` is used in multiple places with distinct `Complete` flows.  The only way to keep it consistently working (in the sense of adding the authenticated group) is to wrap the `tokenAuthenticator := authenticatorfactory.NewFromTokens(tokens)` in `AuthorizeClientBearerToken` with a `group.NewAuthenticatedGroupAdder`.

`pkg/kubeapiserver/authenticator/config.go` and `staging/src/k8s.io/apiserver/pkg/server/config.go` should be left unchanged.

2019-08-24 00:39 UTC, MikeSpreitzer commented
@enj: thanks for looking at this.  We need a fix because we are developing a new filter and it relies on the promise that the groups `system:authenticated` and `system:unauthenticated` cover everything.

2020-01-21 03:07 UTC, closed without merging

2020-01-21 20:34 UTC, lavalamp commented
@yue9944882 @MikeSpreitzer did we come up with another solution for this?

2020-01-22 17:00 UTC, MikeSpreitzer commented
Yes, it is already in place.