Add new test for PodTemplates
kubernetes/kubernetes pull request #81689
Opened 2019-08-20 22:44 UTC by BobyMCbobs

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Add new test for PodTemplate creation

**Special notes for your reviewer**:
Test created as per comments from @spiffxp, found [here](https://github.com/kubernetes/kubernetes/pull/79871#issuecomment-514854868)

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/area test
@kubernetes/sig-apimachinery-pr-reviews
@kubernetes/sig-architecture-pr-reviews

2019-08-21 00:35 UTC, ping035627 commented
/ok-to-test

2019-08-21 03:47 UTC, spiffxp requested changes
this is a good start but doesn't feel like enough of a test for pure CRUD semantics

if we're looking to test more than CRUD, I'm not actually sure what behaviors are expected of a pod template on its own?

2019-08-21 03:47 UTC, spiffxp commented on test/e2e/common/pods.go
> +		_, err = f.ClientSet.CoreV1().PodTemplates(f.Namespace.Name).Get("pod-template-test", metav1.GetOptions{})
this only tests that the Get call won't error, you probably want to verify that what you get back is a pod template, and that its contents match what you expect given what you created above

2019-08-21 03:59 UTC, bgrant0607 commented
Does anyone use the PodTemplate API? It was created for #170, which was never implemented. I'd bet a lot of clusters disable this API or set ResourceQuota to 0 so that it's not a DoS vector.

This should NOT be added to conformance.

cc @johnbelamaric

2019-08-21 03:59 UTC, bgrant0607 commented
/hold

2019-08-21 04:09 UTC, liggitt commented
> Does anyone use the PodTemplate API? It was created for #170, which was never implemented.

I have never seen it used anywhere.

2019-08-22 19:04 UTC, johnbelamaric commented
Can it be deprecated?

2019-08-29 21:41 UTC, devaips commented
@BobyMCbobs let's close this PR on account of the PodTemplate API being unused/on-the-way-to-deprecated.

2019-09-02 01:37 UTC, BobyMCbobs commented
> @BobyMCbobs let's close this PR on account of the PodTemplate API being unused/on-the-way-to-deprecated.

Closing because of deprecation.
/close

2019-09-02 01:37 UTC, closed without merging