fix staticcheck faulures in 'cmd' pkg
kubernetes/kubernetes pull request #81928
Opened 2019-08-26 07:15 UTC by carlory

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

```
Errors from staticcheck:

cmd/kube-controller-manager/app/controllermanager.go:422:22: discoveryClient.ServerResources is deprecated: use ServerGroupsAndResources instead.  (SA1019)

cmd/kube-proxy/app/server.go:552:31: prometheus.Handler is deprecated: Please note the issues described in the doc comment of InstrumentHandler. You might want to consider using promhttp.Handler instead.  (SA1019)

cmd/linkcheck/links.go:75:49: argument err is overwritten before first use (SA4009)

cmd/preferredimports/preferredimports.go:54:2: field errors is unused (U1000)
```

**Which issue(s) this PR fixes**:

Ref: #81657

**Special notes for your reviewer**:

```
NONE
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

2019-08-26 07:17 UTC, carlory commented
/assign @lavalamp

2019-08-26 17:07 UTC, johnSchnake requested changes
I'd much rather we change the `err error` parameter name to something else instead of updating the references to try and not shadow it/reassign it.

2019-08-26 23:32 UTC, carlory commented on cmd/linkcheck/links.go
> -		fileBytes, err := ioutil.ReadFile(filePath)
thanks for your review, I'll change it later.

2019-08-26 23:40 UTC, carlory commented on cmd/linkcheck/links.go
> -		fileBytes, err := ioutil.ReadFile(filePath)
@johnSchnake fixed!

2019-09-03 23:33 UTC, mnogu commented
I didn’t noticed that your PR conflicts with #81667. I should’ve commented at #81657.
Would you mind removing the changes to controller-manager?

2019-09-04 03:06 UTC, carlory commented
I will remove those changes later

2019-09-04 04:07 UTC, carlory commented
@mnogu removed

2019-09-04 06:36 UTC, carlory commented
@johnSchnake @cheftako @dcbw 

Can you give me an ok-to-test label on this pr ?

2019-09-04 11:41 UTC, mnogu commented
> @mnogu removed

Thanks.

2019-09-26 03:33 UTC, hwdef commented
/ok-to-test

2019-09-26 06:38 UTC, cheftako commented
/lgtm

2019-12-12 22:49 UTC, danwinship commented
/assign @thockin
/unassign @lavalamp

2019-12-16 22:34 UTC, thockin commented
Thanks!

/lgtm
/approve

2019-12-16 22:35 UTC, thockin commented
/retest

2019-12-17 05:37 UTC, merged