clean up test code
kubernetes/kubernetes pull request #81974
Opened 2019-08-27 00:19 UTC by carlory

**What type of PR is this?**

/kind cleanup
/kind testing

**What this PR does / why we need it**:

Use log functions of core e2e framework instead of e2elog sub package

```
test/utils/crd/crd_util.go
test/e2e/gke_local_ssd.go
test/e2e/examples.go
test/e2e_node/*.go
```

**Which issue(s) this PR fixes**:

refer #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

2019-08-27 00:22 UTC, carlory commented
/assign @shyamjvs

2019-08-27 00:26 UTC, carlory commented
/hold

2019-08-27 00:39 UTC, carlory commented
/hold cancel

2019-08-27 01:15 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6

2019-08-27 01:19 UTC, carlory commented
/retest

2019-08-27 02:12 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6

2019-08-27 07:10 UTC, k-toyoda-pi commented
/lgtm
But, conflicting file is appeared.

2019-08-27 09:05 UTC, carlory commented
/hold

2019-08-27 09:22 UTC, carlory commented
/hold cancel

2019-08-27 11:10 UTC, carlory commented
/retest

2019-08-28 00:46 UTC, carlory commented
/retest

2019-08-28 15:47 UTC, neolit123 commented
/remove-area kubeadm

2019-08-28 16:39 UTC, carlory commented
/test pull-kubernetes-conformance-image-test

2019-08-29 20:03 UTC, roycaihw commented
/cc

2019-08-29 22:15 UTC, oomichi commented
I am guessing old version of this changed unrelated files then it has multiple unrelated labels.
We need to remove the labels for reviewing.

/remove-area apiserver
/remove-area code-generation
/remove-kind api-change
/remove-sig api-machinery
/remove-sig apps
/remove-sig auth
/remove-sig autoscalling
/remove-sig lifecycle
/remove-sig network
/remove-sig storage

2019-08-29 22:25 UTC, oomichi requested changes
Please don't change unrelated files.

2019-08-29 22:25 UTC, oomichi commented on test/e2e/node/events.go
> +	"github.com/onsi/ginkgo"
This is not necessary to be moved in this PR.
The original sort order is common in e2e tests.
That means we need to keep like
```
...
	"k8s.io/kubernetes/test/e2e/framework"

	"github.com/onsi/ginkgo"
```
with a single blank line between framework and ginkgo.

2019-08-29 22:25 UTC, oomichi commented on test/e2e/node/pods.go
> +	"github.com/onsi/ginkgo"
ditto

2019-08-29 22:25 UTC, oomichi commented on test/e2e/node/ttlafterfinished.go
> +	"github.com/onsi/ginkgo"
ditto

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/dynamic_kubelet_config_test.go
> +	frameworkmetrics "k8s.io/kubernetes/test/e2e/framework/metrics"
We don't need to change here in this PR at all.

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/environment/conformance.go
> -
ditto: We don't need to change this file at all for the PR scope.

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/hugepages_test.go
> -
I think the original blank line here is for separating k8s.io/kubernetes repo and other k8s.io repos, so we don't need to remove this blank line.

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/pids_test.go
> -
ditto: unnecessary to remove a blank line.

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/pods_container_manager_test.go
> -	"k8s.io/klog"
We don't need to change this file at all.

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/remote/node_conformance.go
> -
ditto: don't change..

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/remote/node_e2e.go
> -
ditto

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/runner/local/run_local.go
> -	"k8s.io/klog"
ditto: don't change unrelated file.

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/services/internal_services.go
> +	"k8s.io/kubernetes/test/e2e/framework"
ditto

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/services/kubelet.go
> +	"k8s.io/klog"
ditto

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/services/server.go
> -
ditto

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/services/services.go
> +	"k8s.io/klog"
ditto

2019-08-29 22:25 UTC, oomichi commented on test/e2e_node/volume_manager_test.go
> -	"fmt"
ditto

2019-09-01 04:37 UTC, carlory commented
removed unrelated changes

2019-09-04 23:07 UTC, oomichi commented
We need to replace e2e_log in test/e2e_node/startup_probe_test.go also as
```
compile: missing strict dependencies:
	/b/f/w/test/e2e_node/startup_probe_test.go: import of "k8s.io/kubernetes/test/e2e/framework/log"
```
according to https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/81974/pull-kubernetes-bazel-build/1168019699871518721/build-log.txt

2019-09-05 15:46 UTC, carlory commented
@oomichi thanks for your guide. It's fixed!

2019-09-05 17:35 UTC, oomichi reviewed
Thanks for updating

/lgtm
/approve

2019-09-11 06:49 UTC, merged