cleanup test code in upgrades and autoscaling pkg
kubernetes/kubernetes pull request #81978
Opened 2019-08-27 01:22 UTC by carlory

**What type of PR is this?**

/kind cleanup
/kind testing 

**What this PR does / why we need it**:

Use log functions of core e2e framework instead of e2elog sub package

```
test/e2e/autoscaling/*.go
test/e2e/upgrades/apps/daemonsets.go
test/e2e/upgrades/*.go
test/e2e/upgrades/storage/persistent_volumes.go
```

**Which issue(s) this PR fixes**:

refer #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

2019-08-27 01:25 UTC, carlory commented
/assign @krzyzacy

2019-08-27 02:10 UTC, krzyzacy approved these changes

2019-08-27 03:56 UTC, carlory commented
@krzyzacy Thanks for your approval. Can you give me a ok-to-test label on this pr?

2019-08-27 07:51 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6

2019-08-27 08:56 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6

2019-08-27 11:09 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6

2019-08-27 11:43 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6

2019-08-27 12:41 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6

2019-08-28 00:46 UTC, carlory commented
/test pull-kubernetes-conformance-kind-ipv6
/test pull-kubernetes-kubemark-e2e-gce-big

2019-08-29 01:39 UTC, carlory commented
/test pull-kubernetes-integration

2019-08-29 15:46 UTC, carlory commented
ping @krzyzacy @carlory 

It' s ready for review. Could you take a quick look at it?

2019-08-29 22:29 UTC, oomichi requested changes
This also changed unrelated files.
Please keep the PR scope simple and clean for the PR message and the corresponding issue.

2019-08-29 22:29 UTC, oomichi commented on test/e2e/upgrades/apps/deployments.go
> -	imageutils "k8s.io/kubernetes/test/utils/image"
Please don't change unrelated file.
This doesn't contain e2elog.

2019-08-29 22:29 UTC, oomichi commented on test/e2e/upgrades/apps/replicasets.go
> -	imageutils "k8s.io/kubernetes/test/utils/image"
ditto

2019-08-29 22:29 UTC, oomichi commented on test/e2e/upgrades/apps/statefulset.go
> -
ditto

2019-08-29 22:29 UTC, oomichi commented on test/e2e/upgrades/sysctl.go
> -
ditto

2019-09-01 04:54 UTC, carlory commented
/test pull-kubernetes-integration

2019-09-04 08:46 UTC, carlory commented
/test pull-kubernetes-integration

2019-09-16 08:56 UTC, carlory commented
@oomichi 

It's ready for re-review.  Could you take a quick look at it?

2019-09-17 18:31 UTC, oomichi commented
@carlory Thanks for updating, but unfortunately we need to rebase this patch again for the latest master?
Could you do that?

2019-09-18 05:53 UTC, carlory commented
@oomichi  done!

2019-09-18 07:24 UTC, carlory commented
/test pull-kubernetes-e2e-gce-device-plugin-gpu

2019-09-19 07:48 UTC, carlory commented
/test pull-kubernetes-integration

2019-09-23 21:55 UTC, oomichi reviewed
/lgtm

2019-09-24 01:03 UTC, oomichi commented
/test pull-kubernetes-e2e-gce-100-performance

2019-09-24 04:14 UTC, carlory commented
/test pull-kubernetes-bazel-build
/test pull-kubernetes-e2e-gce-100-performance

2019-09-24 15:57 UTC, merged