WIP e2e: migrate to e2enode.GetReadySchedulableNodes, add bounded version
kubernetes/kubernetes pull request #82291
Opened 2019-09-03 19:15 UTC by danwinship

**What this PR does / why we need it**:
1. Migrates tests from `framework.GetReadySchedulableNodesOrDie` to `e2enode.GetReadySchedulableNodes` (WIP)
2. Adds `e2e.GetBoundedReadySchedulableNodes` for places where a test wants a minimum or maximum number of nodes. ie, either it wants to assert that there are at least a certain number of nodes, or it wants to restrict itself to a subset of available nodes.
3. Gets rid of a function in `e2eservice` that is equivalent to the new `GetBoundedReadySchedulableNodes`. (Spinoff from #81479)

I'm happy to take naming suggestions on `GetBoundedReadySchedulableNodes`.

Also, having started the porting, I'm thinking that maybe having the `min` argument doesn't make sense, and that both `GetBoundedReadySchedulableNodes` and plain `GetReadySchedulableNodes` should impose a minimum of `1` all the time. Right now, tests generally only check `len(nodes.Items)` if they're planning to look at `nodes.Items[0]`. But in any test where you care about the list of ready, schedulable nodes, it seems unlikely that the test could non-false-positively pass if there wasn't at least 1 node.

(And maybe in that case we could just merge `GetBoundedReadyScheduleableNodes` into `GetReadySchedulableNodes` and everyone could just pass `-1` when they don't want to impose a maximum?)

I'll finish the PR up after initial review/sanity checking.

```release-note
NONE
```

/kind cleanup
/assign timothysc

2019-09-10 20:46 UTC, danwinship commented
/retest

2019-09-11 15:47 UTC, timothysc requested changes

2019-09-11 15:47 UTC, timothysc commented on test/e2e/framework/node/resource.go
> +	if max != -1 && len(nodes.Items) > max {
This is kind of a weird behavior IMO.  I would almost prefer a wrapper around this function that is used on a limited number of call sites vs. a number of calls passing -1.

2019-09-15 19:29 UTC, danwinship commented
Updated; there's now a separate `GetBoundedReadySchedulableNodes`.

If you want I can split out all the actual test fixes into smaller PRs and make this one be just the framework changes, to make it easier to review...

2019-09-20 20:24 UTC, timothysc approved these changes
/lgtm 
/approve 

thanks for making the change.

2019-09-21 18:40 UTC, danwinship commented
/test pull-kubernetes-kubemark-e2e-gce-big

2019-09-23 11:54 UTC, danwinship commented
@timothysc needs a re-/lgtm after being rebased (twice) around other changes

2019-09-24 15:27 UTC, timothysc commented
@danwinship - looks like it needs another rebase :-(

2019-09-24 17:08 UTC, danwinship commented
@timothysc rebased. If this misses again I'll split everything but the core stuff out into separate PRs...

2019-09-24 17:11 UTC, timothysc approved these changes
/lgtm

2019-09-25 18:04 UTC, merged