[PR Template] Add codeblock to capture deprecation note associated with PR
kubernetes/kubernetes pull request #82450
Opened 2019-09-07 02:23 UTC by paulbouwer

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Adds a code block to the PR Template for the **kubernetes/kubernetes** repo to capture the **deprecation note** information as requested in [Issue kubernetes/sig-release#668](https://github.com/kubernetes/sig-release/issues/668)

**Which issue(s) this PR fixes**:

Refers to Issue [kubernetes/sig-release#668](https://github.com/kubernetes/sig-release/issues/668)

**Special notes for your reviewer**:

This is a smaller focused PR that was extracted from [PR kubernetes/kubernetes #81278](https://github.com/kubernetes/kubernetes/pull/81278)

This will require an update to the [release notes tool](https://github.com/kubernetes/release/tree/master/cmd/release-notes) for the next release cycle (1.17) to ensure that the **deprecation note** information is parsed and processed.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

/cc @saschagrunert @onyiny-ang
/sig release

2019-09-09 06:47 UTC, saschagrunert requested changes
@paulbouwer thanks, I have two comments.

2019-09-09 06:47 UTC, saschagrunert commented on .github/PULL_REQUEST_TEMPLATE.md
> +Indicate whether this PR implements a change that requires users to be informed of a deprecation of behaviour.
```suggestion
Indicate whether this PR implements a change that requires users to be informed of a deprecation of an API.
```

2019-09-09 06:47 UTC, saschagrunert commented on .github/PULL_REQUEST_TEMPLATE.md
> +None
I would leave this empty to keep consistency with the other blocks:

```suggestion
```

2019-10-15 08:00 UTC, saschagrunert commented
@paulbouwer are you still around to work on this or should I take it over? 
(I'll assume that the overall direction will change a bit)

2019-10-31 12:04 UTC, justaugustus commented
I've mentioned on a few SIG Release calls, so adding here as well...
I think the right path forward might be to introduce a new label, `kind/deprecation`, which when applied along with a release note, our release notes tooling will treat as a deprecation note.

I've opened a PR to discuss and make that change here: https://github.com/kubernetes/test-infra/pull/15040

Let's see where that discussion leads before moving on this.
/hold
/priority important-longterm
/kind feature
/milestone v1.17

2019-10-31 12:50 UTC, saschagrunert commented
Thanks @justaugustus, do we want to do the same for the primary SIG? (https://github.com/kubernetes/kubernetes/pull/82449)

2019-11-11 00:14 UTC, josiahbjorgaard commented
@justaugustus Will this be making it into v1.17 before code freeze this Thursday or can we change the milestone?

2019-11-15 16:53 UTC, justaugustus commented
Consensus seems to be leaning towards the `kind/deprecation` label, so I'm going to close this PR.
We can come back to any template updates once that lands in https://github.com/kubernetes/test-infra/pull/15040.

/close

2019-11-15 16:53 UTC, closed without merging