Refactor `kubectl proxy` command to have similar design pattern as other kubectl commands.
kubernetes/kubernetes pull request #82971
Opened 2019-09-21 19:48 UTC by AnishShah

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

All kubectl commands follow similar design pattern.

**Which issue(s) this PR fixes**:

Fixes one of the items in #82970.

**Special notes for your reviewer**:

I haven't added any tests because I'm just refactoring the code. Also, there are no unit tests for `kubectl proxy` command. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-09-21 20:02 UTC, AnishShah commented
/assign @monopole

2019-09-25 09:13 UTC, m1kola reviewed
@AnishShah congratulations on your first Kubernetes PR! 🎉 

I had a very brief look, so I don't have any comments about changes yet. But I'm happy to start tests for this.

/ok-to-test

2019-09-25 19:09 UTC, AnishShah commented
/test pull-kubernetes-verify

2019-09-26 16:56 UTC, AnishShah commented
All e2e tests pass are passing now.

2019-10-08 04:54 UTC, AnishShah commented
kind ping

2019-11-07 09:38 UTC, soltysh requested changes

2019-11-07 09:38 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/proxy/proxy.go
> +			cmdutil.CheckErr(o.Complete(f))
The order is wrong, first you complete the `ProxyOptions` struct, then you validate it and finally run the command.

2019-11-07 09:38 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/proxy/proxy.go
> +	cmd.Flags().IntVarP(&o.port, "port", "p", defaultPort, "The port on which to run the proxy. Set to 0 to pick a random port.")
The defaults should be set in `NewProxyOptions` in case someone re-uses your code they should have the same set of defaults as this command.

2019-11-07 09:38 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/proxy/proxy.go
> +	cmd.Flags().IntVarP(&o.port, "port", "p", defaultPort, "The port on which to run the proxy. Set to 0 to pick a random port.")
In general you should be always pointing to `ProxyOptions` here for both defaults and the value actually being set.

2019-11-07 09:38 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/proxy/proxy.go
> +	cmd.Flags().IntVarP(&o.port, "port", "p", defaultPort, "The port on which to run the proxy. Set to 0 to pick a random port.")
See https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/attach/attach.go as an example.

2019-11-07 09:38 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/proxy/proxy.go
> +		return errors.New("Don't specify both --unix-socket and --port")
Errors should be always lowercased.

2019-11-07 09:38 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/proxy/proxy.go
> +		return errors.New("Don't specify both --unix-socket and --port")
`cannot set --unix-socket and --port at the same time`

2019-11-07 09:38 UTC, soltysh commented
/priority backlog

2019-11-11 02:52 UTC, AnishShah commented
@soltysh, Fixed!

2019-12-16 16:12 UTC, soltysh approved these changes
/lgtm
/approve

2019-12-16 16:12 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/proxy/proxy.go
> +	defaultAddress      = "127.0.0.1"
Those could be const or just directly used in `NewProxyOptions`.

2019-12-17 06:39 UTC, AnishShah commented
/retest

2019-12-17 10:31 UTC, AnishShah commented
@soltysh need LGTM again.

2019-12-17 10:53 UTC, soltysh approved these changes
/lgtm

2019-12-17 19:59 UTC, merged