fix doc about watcher timeout
kubernetes/kubernetes pull request #83417
Opened 2019-10-02 18:21 UTC by ramonberrutti

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Better describe the watch functionality.
After some tests, I figured out that the timeout option is bad explained.

2019-10-02 18:24 UTC, ramonberrutti commented
/ok-to-test

2019-10-03 20:07 UTC, fedebongio commented
/assign @caesarxuchao

2019-10-07 19:25 UTC, caesarxuchao reviewed
You need to run hack/update-all.sh to update generated API docs, otherwise the CI will fail.

2019-10-07 19:25 UTC, caesarxuchao commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
> +	// This timeout don't change the client timeout.
How about just modify line 369 to "This limits the duration of the call on the server-side"

2019-10-07 19:25 UTC, caesarxuchao commented on staging/src/k8s.io/client-go/tools/cache/reflector.go
> +			// Stop the watcher after the time window.
How about "Stop the watchers after the timeout seconds".

2019-10-07 19:25 UTC, caesarxuchao commented
/ok-to-test

2019-10-08 01:42 UTC, ramonberrutti commented
@caesarxuchao I'm getting this error running make update.
`
can't load package: package k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen: no matching versions for query "latest"
`

2019-10-09 15:45 UTC, neolit123 commented
/remove-area kubeadm

2019-10-09 19:17 UTC, caesarxuchao commented
Why are there many commits about updating dependencies? Maybe you need a rebase?

2019-10-14 15:32 UTC, alejandrox1 commented
/remove-area e2e-test-framework

2019-10-14 15:38 UTC, alejandrox1 requested changes
@ramonberrutti 
thank you very much for working on this.
This PR got labeled with a ton of stuff since you modified some key files so we need some cleanup (this will also fix the test failures).
Could you please run 
* `./hack/update-generated-protobuf.sh`
* `./update-generated-swagger-docs.sh`

These can be found here https://github.com/kubernetes/kubernetes/tree/master/hack

/priority important-soon
/milestone v1.17

2019-10-14 15:41 UTC, alejandrox1 commented
/remove-area kubelet
/remove-area kubectl
/remove-area ipvs
/remove-area cloudprovider
/remove-area code-generation
/remove-area dependency
/remove-area test
/remove-sig apps
/remove-sig auth
/remove-sig cli
/remove-sig autoscaling
/remove-sig cloud-provider
/remove-sig cluster-lifecycle
/remove-sig network
/remove-sig node
/remove-sig storage
/remove-sig scheduling
/remove-sig testing

2019-10-15 15:50 UTC, ramonberrutti commented
@alejandrox1 thanks, I rebase with master and run make update. Thanks again :)

2019-10-16 21:47 UTC, ramonberrutti commented
/assign @lavalamp

2019-10-26 18:59 UTC, kikisdeliveryservice commented
Bug Triage Release Team checking in. Code freeze for the 1.17 release is on November 18. Is this still intended for 1.17? Thanks!

2019-11-10 20:51 UTC, kikisdeliveryservice commented
@lavalamp @ramonberrutti 

Is this still intended for 1.17 or being bumped to 1.18? Code freeze is Nov 14th.

2019-11-11 20:29 UTC, ramonberrutti commented
@kikisdeliveryservice This is just a document fix.

2019-11-11 20:30 UTC, ramonberrutti commented
I will rebase to fix the conflict.

2019-11-11 20:47 UTC, lavalamp commented on staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
> +	// This timeout don't change the client timeout.
> This timeout don't change the client timeout

What is the client timeout, and how does one change it?

grammar: s/don't/doesn't/

2019-11-15 04:06 UTC, josiahbjorgaard commented
/milestone v1.18

(Code freeze v1.17)

2020-01-30 17:06 UTC, jtslear commented
Hello @ramonberrutti, @lavalamp, and @caesarxuchao 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this PR still intended for milestone 1.18?  I see we have a few conflicts that need to be addressed.

2020-02-28 16:53 UTC, jtslear commented
Hello @ramonberrutti,
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. I see we have a few conflicts and requested changes that need to be addressed.  Are we still trying to accomplish this work in time for code freeze?

2020-02-29 04:38 UTC, ramonberrutti commented
Ty for the remainder :)

2020-03-05 18:26 UTC, jtslear commented
Due to reaching the code freeze deadline, I'm going to bump this to the next release.

/milestone v1.19

2020-05-29 12:38 UTC, bai commented
👋 Hello from Bug Triage team! This PR has not been updated for a while, so I'd like to check its status. The code freeze is starting June 25th (about 4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.19, is it still planned for this release?

2020-12-17 20:31 UTC, closed without merging