Refactored e2e-test-framework logging
kubernetes/kubernetes pull request #83512
Opened 2019-10-04 19:01 UTC by alejandrox1

Signed-off-by: alejandrox1 <alarcj137@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updated the framework's logging methods with those found in e2elog
(framework/log) pkg. Also added the unit tests found in e2elog pkg into
the framework.

Because we eventually want to use framework for logging, instead of
e2elog. We need to make all the current methods in e2elog available in
the framework itself.

**Which issue(s) this PR fixes**:
tangentially related to #77095

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/area e2e-test-framework
/sig testing
/priority backlog
/milestone v1.17

2019-10-04 19:02 UTC, alejandrox1 commented
/assign @oomichi @andrewsykim @timothysc
ptal

/hold
I think this also has to go in after #82176

2019-10-04 20:01 UTC, timothysc requested changes

2019-10-04 20:01 UTC, timothysc commented on test/e2e/framework/log_test.go
> +	//"k8s.io/kubernetes/test/e2e/framework"
can you update to remove the commented sections. 

Also this code looks like it was shuffled from somewhere else, but I don't see the remove in this diff.

2019-10-05 17:31 UTC, closed without merging

2019-10-05 17:32 UTC, alejandrox1 commented
The patch proposed here was essentially a duplicate of #82176