Close the file after reading
kubernetes/kubernetes pull request #84108
Opened 2019-10-19 11:29 UTC by tedyu

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
For verifydependencies, after the file is done being read, we should close it.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-10-19 11:29 UTC, tedyu commented
/priority important-soon

2019-10-19 11:30 UTC, tedyu commented
cc @neolit123

2019-10-19 11:33 UTC, tedyu commented
/sig release

2019-10-19 11:34 UTC, neolit123 commented
/lgtm
/remove-priority important-soon
/priority backlog

2019-10-19 11:35 UTC, neolit123 commented
/assign @dims

2019-10-19 17:16 UTC, justaugustus requested changes
@tedyu -- hey, can you update the commit message and PR title to be explicit about what file you're referring to?

2019-10-19 17:32 UTC, tedyu commented
@justaugustus 
I have updated commit message, the subject and the description.

2019-10-19 17:42 UTC, justaugustus commented
Thanks!
/lgtm
/approve

2019-10-19 18:20 UTC, neolit123 commented on cmd/verifydependencies/verifydependencies.go
> +			func() {
nit: i would have declared a function for this instead of using a lambda.
/lgtm

2019-10-21 12:06 UTC, dims commented
/approve
/lgtm

2019-10-21 13:04 UTC, tedyu commented
/test pull-kubernetes-integration

2019-10-21 13:11 UTC, tedyu commented
/test pull-kubernetes-integration

2019-10-21 13:43 UTC, merged