fix build issue on s390x
kubernetes/kubernetes pull request #84270
Opened 2019-10-24 02:36 UTC by hchenxa

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubernetes/kubernetes/issues/84269

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-10-24 02:37 UTC, hchenxa commented
/assign @listx

2019-10-24 07:55 UTC, mkumatag requested changes

2019-10-24 08:10 UTC, hchenxa commented on test/images/echoserver/Dockerfile
> +       apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.8/main openssl nginx-mod-http-lua nginx-mod-http-lua-upstream ;\
@mkumatag the package `nginx-mod-http-lua` and `nginx-mod-http-lua-upstream` only exist in v3.8 repo for s390x so far.

2019-10-29 06:07 UTC, hchenxa commented
@mkumatag @listx I need to change the s390 base image to use nginx:1.13-alpine as:

1) the nginx:1.13-alpine using v3.8 alpine apk repo and have the nginx lua module
2) the nginx:1.15-apline did not have nginx lua module in default alpine apk repo
3) the nginx lua module in v3.8 alpine apk repo have compatibility issues on nginx:1.15-alpine, after some test, only nginx:1.13-alpine can be used now.

2019-10-29 06:08 UTC, hchenxa commented
/retest

2019-10-29 06:16 UTC, mkumatag requested changes

2019-10-29 06:16 UTC, mkumatag commented on test/images/echoserver/Dockerfile
> +
why this extra space?

2019-10-29 08:13 UTC, hchenxa commented
close this PR and recreate another https://github.com/kubernetes/kubernetes/pull/84502/files

2019-10-29 08:13 UTC, closed without merging