Continue killing containers in case of error
kubernetes/kubernetes pull request #84416
Opened 2019-10-27 14:41 UTC by tedyu

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In kubeGenericRuntimeManager#SyncPod, when error is encountered killing container(s), we should continue killing the remaining running containers in this pod which are not to keep.

**Which issue(s) this PR fixes**:
Fixes #

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-10-27 14:43 UTC, tedyu commented
@mattjmcnaughton 
I have addressed the first two points from:
https://github.com/kubernetes/kubernetes/pull/77173#pullrequestreview-231698661

Working on the unit test.

cc @feiskyer

2019-10-27 16:06 UTC, tedyu commented
@mattjmcnaughton 
I have added a new test.

2019-10-28 14:15 UTC, mattjmcnaughton approved these changes
/lgtm

For whoever ends up approving this, the original author (@feiskyer) stated that they believe it is a good idea to continue trying to kill containers even if one fails. See https://github.com/kubernetes/kubernetes/pull/77173 for the original context.

Thanks @tedyu for closing the loop on this!

/assign @derekwaynecarr

2019-10-29 18:42 UTC, tedyu commented
/assign @tallclair

2019-11-08 02:50 UTC, tedyu commented
/priority backlog

2019-11-12 17:56 UTC, tedyu commented
ping @derekwaynecarr for review

2019-12-06 15:00 UTC, tedyu commented
/assign @tallclair

2019-12-08 09:46 UTC, haosdent commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
> +// We will continue killing containers in the case of error return from killContainer
s/killContainer/killContainer./g

2019-12-08 09:51 UTC, haosdent commented
/lgtm

2020-03-07 11:46 UTC, tedyu commented
/remove-lifecycle stale

2020-03-09 19:01 UTC, derekwaynecarr requested changes
seems like we have an extraneous log.

2020-03-09 19:10 UTC, tedyu commented on pkg/kubelet/kuberuntime/kuberuntime_manager.go
> +			klog.V(3).Infof("Killing unwanted container %q(id=%q) for pod %q", containerInfo.name, containerID, format.Pod(pod))
Addressed over #88978

2020-03-09 19:11 UTC, tedyu commented
In favor of #88978

2020-03-09 19:11 UTC, closed without merging