Fix golint issues in pkg/util/removeall
kubernetes/kubernetes pull request #84753
Opened 2019-11-04 23:12 UTC by hvaara

Co-Authored-By: Christian Schlotter <christian.schlotter@daimler.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes golint issues in `pkg/util/removeall`

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:
These changes was originally introduced by @chrischdi in #69761

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-11-04 23:15 UTC, hvaara commented
/priority backlog
/area code-organization

2019-11-05 15:40 UTC, mattjmcnaughton requested changes
/ok-to-test

Thanks for your pr! I suggested a different approach that I feel may be a little cleaner. Let me know what you think :)

2019-11-05 16:18 UTC, hvaara commented on pkg/util/removeall/removeall.go
> +// OneFilesystem removes path and any children it contains.
Great idea! I'll do this

2019-11-05 19:32 UTC, hvaara commented on pkg/util/removeall/removeall.go
> +// OneFilesystem removes path and any children it contains.
@mattjmcnaughton I've pushed the changes. Thanks a lot for the suggestion - I think it's much cleaner 😄

2019-11-05 19:36 UTC, hvaara commented
Thanks again @mattjmcnaughton! Could you PTAL?

/retitle Fix golint issues and move RemoveAllOneFilesystem

2019-11-05 23:45 UTC, hvaara commented
/assign @lavalamp

2019-11-06 15:18 UTC, mattjmcnaughton approved these changes
/lgtm

+1 this is cleaner :) Thanks!

2019-11-17 01:26 UTC, hvaara commented
`mount` has been moved out of tree. Will rebase and fixing conflicts

2020-02-21 11:48 UTC, hvaara commented
Will have another go at this soon
/remove-lifecycle stale

2020-06-19 15:55 UTC, SergeyKanzhelev commented
@hvaara do you want to rebase PR? If not - I will be happy to take it over.

2020-08-18 17:15 UTC, closed without merging