omit namespace to avoid ambiguity
kubernetes/kubernetes pull request #84967
Opened 2019-11-08 04:08 UTC by donggangcj

**What type of PR is this?**

> /area kubectl
> /kind cleanup

**What this PR does / why we need it**:This PR resolve eliminate the ambiguity `kubectl get` returnd.

**Which issue(s) this PR fixes**:https://github.com/kubernetes/kubectl/issues/757

**Special notes for your reviewer**:
/assign @deads2k @juanvallejo

**Does this PR introduce a user-facing change?**:Yes

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-11-11 02:01 UTC, donggangcj commented
/assign @smarterclayton

2019-11-11 05:38 UTC, zhouya0 commented
Thanks a lot, this might be the sulotion. But i think if we want to reserve namespace we can use a bool variable like `printWithNamespace`  in `Run` function.
Like in many resources, once we found a resource `printWithNamespace` is false, we are not going to print namespace.

2019-11-11 10:29 UTC, donggangcj commented
@zhouya0 Thanks. The `get` command can get namespaced and nonamespaced resource at the same time。if Command `kubectl get nodes,pods --printWithNamespace=true`  return `No resouce  found in default namespace`,it is still ambiguous.It is wise to ignore the namespace information in the old version. This namespace information is of no value to the user because when necessary, the user will specify the flag `--namesapce`.
My english is pool.😂

2019-11-12 02:06 UTC, smarterclayton commented
/ok-to-test

The message shouldn't be relying on "all-namespaces".  We might want to base the message on whether all resources listed are namespaced (which wouldn't work for files from disk) and allNamespaces is set.  What does it look like to determine whether all resource info inputs are namespaced from this part of the code?

2019-11-13 06:33 UTC, donggangcj commented
I think it is not worth determine whether all resource info inputs are namespaced from this part of the code. Users don't seem to  care about the result message whether cotain the namespace info. 🙂

2019-11-15 01:26 UTC, donggangcj commented
/retest

2020-01-23 15:27 UTC, soltysh requested changes
@donggangcj I agree with what Clayton said earlier, can you look into how much work it is not to change that message, I know the user base a bit and I know we'll get complains as soon as this lands. Also, when working with a default namespace (not `default` but one that you have hardcoded in your configfile) you don want to know the name of it if you just invoke `kubectl get` w/o specifying the namespace. That's why before we make the final call for removing this I want to know the cost.

2020-02-20 14:27 UTC, rccrdpccl commented
Hi @donggangcj - are you still interested in working on this issue?

2020-04-02 05:01 UTC, closed without merging

2020-04-04 21:29 UTC, rccrdpccl commented
I've continued @donggangcj work at https://github.com/kubernetes/kubernetes/pull/89861 that should fix the original issue