Fix underscore linting issue in /pkg/volume/azure_dd/azure_common_lin…
kubernetes/kubernetes pull request #85063
Opened 2019-11-10 07:46 UTC by hazel-shen

…ux.go

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-01-28 21:51 UTC, matthyx commented
@hazel-shen can you rebase your PR?
/cc

2020-01-29 12:25 UTC, hazel-shen commented
> @hazel-shen can you rebase your PR?
> /cc

@matthyx 
I've also fixed the conflict, please take a look, thank you!

2020-01-29 15:39 UTC, matthyx commented
/ok-to-test

2020-01-31 14:51 UTC, hazel-shen commented
/retest

2020-02-01 21:52 UTC, matthyx requested changes

2020-02-01 21:52 UTC, matthyx commented on pkg/volume/azure_dd/azure_common_linux.go
>  	scsi_path := "/sys/class/scsi_host/"
Can you change it here too?

2020-02-01 21:52 UTC, matthyx commented on pkg/volume/azure_dd/azure_common_linux.go
>  	if dirs, err := io.ReadDir(scsi_path); err == nil {
And here?

2020-02-03 07:23 UTC, matthyx commented
/test pull-kubernetes-verify

2020-02-03 12:10 UTC, matthyx commented
/lgtm
/assign @khenidak

2020-02-05 17:31 UTC, neolit123 commented
/remove-area kubeadm

2020-05-15 19:38 UTC, khenidak commented
/retest
/lgtm

2020-07-14 22:43 UTC, closed without merging