Add expired Job to queue when TTLSecondsAfterFinished is zero
kubernetes/kubernetes pull request #85141
Opened 2019-11-12 16:32 UTC by tedyu

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes #74741

**Which issue(s) this PR fixes**:
Fixes #74741

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-11-12 16:35 UTC, tedyu commented
/priority backlog

2019-11-12 17:40 UTC, tedyu commented
@cheftako 
Please take a look.

2019-11-12 17:57 UTC, tedyu commented
/test pull-kubernetes-node-e2e-containerd

2019-11-13 09:06 UTC, soltysh commented
This fix is not related to #74741 b/c ttl controller is different from cronjob. ttl controller is meant to clean standalone jobs. Jobs managed by the cronjob controller are cleaned per policy defined in the cronjob.

2019-11-13 09:16 UTC, soltysh requested changes

2019-11-13 09:16 UTC, soltysh commented on pkg/controller/ttlafterfinished/ttlafterfinished_controller.go
> +	if *t == 0 {
This is not needed, since `enqueueAfter` will just add the item w/o wait when the time is 0.

2019-11-13 09:16 UTC, soltysh commented on pkg/controller/ttlafterfinished/ttlafterfinished_controller.go
> +	if *t < 0 {
Not needed, imo.

2019-11-14 15:14 UTC, closed without merging