Fix benchmark artifact parsing.
kubernetes/kubernetes pull request #85513
Opened 2019-11-21 18:32 UTC by liu-cong

* If ARTIFACTS env var is set, the logs will be printed in a different format, which cannot be parsed by benchmark parser.
* Added --timeout=2h which should be enough.
* Also added -alsologtostderr=false -logtostderr=false to reduce noisy logs.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The [scheduler benchmark test job](https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler) has been succeeding however no result is shown on the [perfdash](http://perf-dash.k8s.io/#/?jobname=scheduler-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkResults&benchmark=BenchmarkSchedulingInTreePVs%2F1000Nodes%2F1000Pods-8&metricName=time). This is because the log parser failed to parse test logs due to unexpected log format.
Interestingly enough, when the test fails, it actually (partially) prints the normal log format. As a result, the results we see on the perf dash are those failed tests...

**Detailed explanation**:
For some reason, if the `ARTIFACTS` env var is set, logs will be printed in a different format, which cannot be parsed by benchmark parser.  
* no `ARTIFACTS` env var
```
BenchmarkSchedulingCSIPVs/1000Nodes/1000Pods-12                              500          19287608 ns/op         1768107 B/op      46612 allocs/op
```

* with `export ARTIFACTS="something"`
``` 
{"Time":"2019-11-06T03:28:24.143461139Z","Action":"output","Package":"k8s.io/kubernetes/test/integration/scheduler_perf","Output":"BenchmarkSchedulingV/100Nodes/0Pods-8    \t"}
{"Time":"2019-11-06T03:28:24.143478Z","Action":"output","Package":"k8s.io/kubernetes/test/integration/scheduler_perf","Output":"     100\t  14863193 ns/op\t  563863 B/op\t    6973 allocs/op\n"}
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This script is currently only used by scheduler benchmark tests.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2019-11-21 18:33 UTC, liu-cong commented
/sig-testing

2019-11-21 18:34 UTC, liu-cong commented
cc @ahg-g

2019-11-25 15:26 UTC, liu-cong commented
/assign fejta

2019-11-25 19:46 UTC, fejta requested changes
`ARTIFACTS` is the correct name

https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#what-the-test-container-can-expect

2019-11-25 19:51 UTC, liu-cong commented
> `ARTIFACTS` is the correct name
> 
> https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#what-the-test-container-can-expect

Do you know why the log output format is changed once the `ARTIFACTS` env variable is set? The format confuses downstream log parser.

2019-11-25 20:00 UTC, fejta commented
Not exactly you'll need to trace through `make test-integration` looking for things that behave differently when `ARTIFACTS` is set.

It is probably doing something that winds up outputting the junit data into artifacts that testgrid.k8s.io and prow expect

2019-11-26 17:57 UTC, liu-cong commented
@fejta , thanks for pointing out the `ARTIFACTS` env var is required.

I have updated the PR to extract raw log from json format before passing to the benchmark parser. This will make the benchmark dashboard work and won't affect other tests.

2019-11-26 19:43 UTC, liu-cong commented
/retest

2019-11-27 20:34 UTC, liu-cong commented
BTW, I tested this locally and verified that benchmark metrics are correctly parsed.

2019-11-27 20:42 UTC, fejta reviewed
/lgtm
/approve

2019-11-28 00:41 UTC, merged