Fix pkg/controller typos in some error messages, comments etc
kubernetes/kubernetes pull request #88447
Opened 2020-02-24 04:08 UTC by taesunny

**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
> To fix pkg/controller 34 Typos in comments, error messages

**Which issue(s) this PR fixes**:

> Fixes #

**Special notes for your reviewer**:
> NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
> NONE

2020-02-24 04:11 UTC, taesunny commented
I make an assignment from k8s-ci-robot APPROVALNOTIFIER info.

/assign @derekwaynecarr

2020-02-25 21:07 UTC, fedebongio commented
/assign @sanchezl

2020-02-26 05:45 UTC, taesunny commented
/kind cleanup
/priority backlog

2020-02-26 14:32 UTC, sanchezl requested changes

2020-02-26 14:32 UTC, sanchezl commented on pkg/controller/daemon/daemon_controller_test.go
> +			t.Fatalf("did not found pods on nodes %+v", nodeMap)
```suggestion
			t.Fatalf("did not find pods on nodes %+v", nodeMap)
```

2020-02-26 14:32 UTC, sanchezl commented on pkg/controller/replicaset/replica_set_test.go
> +		t.Errorf("There should be unfulfilled expectation for creating new pods for ReplicaSet %q", oldRSKey)
```suggestion
		t.Errorf("There should be unfulfilled expectations for creating new pods for ReplicaSet %q", oldRSKey)
```

2020-02-26 14:32 UTC, sanchezl commented on pkg/controller/replicaset/replica_set_test.go
> +		t.Errorf("There should be unfulfilled expectation for creating new pods for ReplicaSet %q", oldRSKey)
```suggestion
		t.Errorf("There should be unfulfilled expectations for creating new pods for ReplicaSet %q", oldRSKey)
```

2020-02-26 15:08 UTC, taesunny commented
Thank you so much for your review!!
I add a commit applying your suggestions.
I'll squash two commits!
@sanchezl

2020-02-26 15:20 UTC, taesunny commented
I squashed a commit applying review result into the original commit.
And I pushed.

2020-02-26 20:05 UTC, sanchezl approved these changes
/lgtm

2020-02-26 20:13 UTC, deads2k commented
/lgtm
/ok-to-test

2020-02-26 21:09 UTC, deads2k commented
/approve

2020-02-27 00:03 UTC, taesunny commented
/test pull-kubernetes-e2e-gce

2020-02-27 00:03 UTC, taesunny commented
/test pull-kubernetes-e2e-gce-storage-slow

2020-02-27 03:39 UTC, merged