Makefile.generates-files: fix package typo
kubernetes/kubernetes pull request #89255
Opened 2020-03-19 13:26 UTC by sttts

2020-03-19 13:30 UTC, p0lyn0mial commented
/lgtm

2020-03-19 14:07 UTC, p0lyn0mial commented
/lgtm

2020-03-19 14:54 UTC, justaugustus requested changes
@sttts -- This mentions a typo fix, but resulted in a change to `api/api-rules/apiextensions_violation_exceptions.list`.

Can you provide some details in the commit messages, PR title, and PR description about how/why this was done + a link to issue (if there's an existing one)?
Maybe a release note too, if it's user-facing?

/hold

2020-03-19 21:12 UTC, cblecker commented
/approve
Approving for build. You'll need to actually regenerate things too, so that verify passes.

To be clear for api reviewers, there is no `k8s.io/apiextensions` so this fixes the reference to `k8s.io/apiextensions-apiserver` which is an actual repo :)

2020-03-19 21:13 UTC, cblecker commented
/assign

2020-03-21 03:27 UTC, justaugustus commented
Thanks for updating the description!
/hold cancel
/retest

2020-03-21 04:38 UTC, cblecker commented
/lgtm
/approve
/assign @lavalamp @liggitt 
for API approval

2020-03-23 13:00 UTC, liggitt commented on api/api-rules/apiextensions_violation_exceptions.list
> +API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1,CustomResourceColumnDefinition,JSONPath
this is the only warning we would have actually wanted to know about, and we already found/fixed it in v1 (https://github.com/kubernetes/kubernetes/issues/66531)

2020-03-23 13:00 UTC, liggitt commented
/approve

2020-04-20 01:31 UTC, justaugustus commented
@sttts -- Needs rebase

2020-09-17 03:43 UTC, closed without merging