test images: Adds Windows Container image support for etcd, pause
kubernetes/kubernetes pull request #89424
Opened 2020-03-24 13:09 UTC by claudiubelu

**What type of PR is this?**

/kind feature

/sig testing
/sig windows

Commit was separated from #77269

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Partially Fixes #77268

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-06-26 21:18 UTC, marosset commented
/retest

2020-06-27 11:04 UTC, mkumatag commented
@claudiubelu 
etcd and pause images are maintained in a different location under here https://github.com/kubernetes/kubernetes/tree/master/build/pause and https://github.com/kubernetes/kubernetes/tree/master/cluster/images/etcd, so I'm just wondering whether we can enable there only is no concerns.

2020-06-27 11:05 UTC, mkumatag requested changes
@claudiubelu
etcd and pause images are maintained in a different location under here https://github.com/kubernetes/kubernetes/tree/master/build/pause and https://github.com/kubernetes/kubernetes/tree/master/cluster/images/etcd, so I'm just wondering whether we can enable there only is no concerns.

2020-06-29 14:20 UTC, claudiubelu commented
> 
> 
> @claudiubelu
> etcd and pause images are maintained in a different location under here https://github.com/kubernetes/kubernetes/tree/master/build/pause and https://github.com/kubernetes/kubernetes/tree/master/cluster/images/etcd, so I'm just wondering whether we can enable there only is no concerns.

Indeed.

I've sent PRs for those here:

pause image: https://github.com/kubernetes/kubernetes/pull/91452
etcd image: https://github.com/kubernetes/kubernetes/pull/92433

2020-08-13 18:30 UTC, marosset commented
/milestone v1.20

2020-10-16 11:37 UTC, droslean commented
/retest

2020-10-16 17:54 UTC, marosset commented
@claudiubelu Looksl like `./hack/update-bazel.sh` needs to be run again

2020-10-20 07:16 UTC, mkorbi commented
Hello @claudiubelu
This PR has been updated frequently, but it looks like it stuck/needs a retest, so I'd like to check what's the status. The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.
As the PR is tagged for 1.20, is it still planned for this release?

2020-10-20 08:54 UTC, droslean commented
/retest

2020-10-20 10:30 UTC, droslean commented on test/images/pause/BUILD
> +    "go_library"
```suggestion
    "go_library",
```

2020-11-09 17:36 UTC, MonzElmasry commented
@claudiubelu can you add the suggested code change if this pr is planned for 1.20. we have 3 days left for code freeze

2020-11-10 14:55 UTC, mkorbi commented
Hey @claudiubelu short reminder, code freeze will be by today

2020-11-11 07:24 UTC, ravisantoshgudimetla commented
@claudiubelu  - You can run  `./hack/update-bazel.sh` for it to be updated. Can you please run it so that we get this merged?

2020-11-18 16:31 UTC, erismaster commented
/milestone v1.21

2020-11-19 14:38 UTC, jeremyrickard commented
Hello, 👋 , 1.20 release lead here! We've moved this to the 1.21 release since we have passed [code freeze](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#code-freeze) and are nearing the end of the release. If you feel that this is otherwise required for the release, please reach out in #sig-release on the kubernetes slack!

2021-03-03 17:45 UTC, erismaster commented
Hello! I am from the Bug Triage team! This PR has not been updated for a long time, so I'd like to check on the status. The code freeze is starting March 9th, 2021 (about 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.
As the PR is tagged for 1.21, is it still planned for this release?

2021-03-09 18:03 UTC, dims commented
has not been touched in a while dropping milestone

/milestone clear

2021-03-10 07:38 UTC, mkumatag commented
> > @claudiubelu
> > etcd and pause images are maintained in a different location under here https://github.com/kubernetes/kubernetes/tree/master/build/pause and https://github.com/kubernetes/kubernetes/tree/master/cluster/images/etcd, so I'm just wondering whether we can enable there only is no concerns.
> 
> Indeed.
> 
> I've sent PRs for those here:
> 
> pause image: #91452
> etcd image: #92433

This is not required any more I feel because of the above 2 PRs, 

/close

2021-03-10 07:38 UTC, closed without merging