test/e2e/framework:remove direct k8s.io/kubernetes depedencies
kubernetes/kubernetes pull request #89806
Opened 2020-04-03 06:54 UTC by tanjunchen

**What type of PR is this?**
 
  /kind cleanup 

**What this PR does / why we need it**:

test/e2e/framework:remove direct k8s.io/kubernetes depedencies  for staging

/cc  @oomichi 
/cc @neolit123 

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/74352

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

2020-04-03 06:58 UTC, tanjunchen commented
/priority backlog
/priority important-longterm
/kind cleanup

2020-04-03 15:58 UTC, gavinfish reviewed
/lgtm

2020-04-03 18:18 UTC, oomichi requested changes

2020-04-04 00:52 UTC, gavinfish commented on test/e2e/framework/util.go
> +	ExpectNoError(e2enode.RemoveTaintOffNode(c, nodeName, nil, &taint))
I think `RemoveTaintOffNode` here should be moved into e2e node fw in the end. So keep it here temporarily may make sense 🤔

2020-04-04 01:55 UTC, tanjunchen commented on test/e2e/framework/util.go
> +	ExpectNoError(e2enode.RemoveTaintOffNode(c, nodeName, nil, &taint))
@oomichi 
 Yes, this change will lead to more dependency on e2enode, I will eventually move them to e2e/node, the purpose of this pr is https://github.com/kubernetes/kubernetes/issues/74352.

@gavinfish  i agree your opinion.

2020-04-04 17:27 UTC, oomichi commented on test/e2e/framework/util.go
> +	ExpectNoError(e2enode.RemoveTaintOffNode(c, nodeName, nil, &taint))
How about moving RemoveTaintOffNode into e2enode package at first before this PR to avoid any issues?

2020-04-05 01:23 UTC, tanjunchen commented on test/e2e/framework/util.go
> +	ExpectNoError(e2enode.RemoveTaintOffNode(c, nodeName, nil, &taint))
ok  i will do it . Thanks

2020-04-11 05:50 UTC, tanjunchen commented
/cc @oomichi 
/cc @gavinfish 
after https://github.com/kubernetes/kubernetes/pull/89889  merged.
for review. Thanks

2020-04-12 00:22 UTC, tanjunchen commented
/retest

2020-04-14 01:42 UTC, oomichi commented
Thanks for your work.

/lgtm

2020-04-14 08:29 UTC, gavinfish reviewed
/lgtm

2020-04-14 14:58 UTC, oomichi commented
/approve

2020-04-15 01:41 UTC, tanjunchen commented
I have deal with the conflicts.

2020-04-15 04:44 UTC, tanjunchen commented
@gavinfish

2020-04-15 09:27 UTC, gavinfish commented
/lgtm

2020-04-15 11:00 UTC, merged