[KUBECTL-808] kubectl logs command with label selector option doesn't…
kubernetes/kubernetes pull request #89815
Opened 2020-04-03 11:12 UTC by bseenu

… print error messages

**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes # https://github.com/kubernetes/kubectl/issues/808

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```
None
```

2020-07-09 11:36 UTC, soltysh requested changes
Sync with @cprayer about https://github.com/kubernetes/kubernetes/pull/89688

2020-07-09 11:36 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/logs/logs.go
> +			return errors.New(fmt.Sprintf("no resources found in %s namespace", o.Namespace))
`fmt.Errorf`

2020-08-09 04:14 UTC, bseenu commented
/remove-lifecycle rotten.

2020-08-09 04:22 UTC, bseenu commented on staging/src/k8s.io/kubectl/pkg/cmd/logs/logs.go
> +			return errors.New(fmt.Sprintf("no resources found in %s namespace", o.Namespace))
👍

2020-09-08 05:15 UTC, closed without merging