Add error messages to IPVS module
kubernetes/kubernetes pull request #89896
Opened 2020-04-06 15:28 UTC by carlosedp

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR improves error messages on IPVS module.

**Which issue(s) this PR fixes**:

Improve IPVS module by adding error messages on convertion functions.

Fixes #89597.

Signed-off-by: Carlos de Paula <me@carlosedp.com>

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2020-04-06 15:39 UTC, carlosedp commented
/assign @m1093782566

2020-04-06 15:48 UTC, aojea commented
/assign @rikatz @andrewsykim

2020-04-06 15:48 UTC, aojea commented
/ok-to-test

2020-04-06 17:05 UTC, rikatz commented
@carlosedp thank you for the PR.

I think maybe you forgot also this: https://github.com/kubernetes/kubernetes/blob/518be88e7274942089abbfb3f5678fc6625d4e4b/pkg/util/ipvs/ipvs_linux.go#L109

2020-04-06 17:06 UTC, rikatz requested changes
In https://github.com/kubernetes/kubernetes/blob/518be88e7274942089abbfb3f5678fc6625d4e4b/pkg/util/ipvs/ipvs_linux.go#L109 also needs an Error Message

2020-04-06 17:20 UTC, carlosedp commented
Oops, my bad... done.

2020-04-06 18:07 UTC, andrewsykim reviewed
We already log errors in the places where the ipvs util methods are called from the proxier. Wondering why those logs are not sufficient?

2020-04-06 18:10 UTC, rikatz commented
@andrewsykim I've raised this as an issue because of https://github.com/kubernetes/kubernetes/issues/89520

It wasn't clear where the error was occurring, it just occurs in the outer functions but was pretty hard to identify in which part of the IPVS library (at least for me).

2020-04-06 18:13 UTC, andrewsykim commented
I see, thanks for the context. I have concerns about logging the same error multiple times and making the logs harder to read. I wonder if instead we should be wrapping the errors with better descriptions so it's easier to find them. What do you think?

2020-04-06 18:18 UTC, rikatz commented
sounds good to me :)

2020-04-06 19:40 UTC, rikatz commented
@carlosedp as per the idea of Andrew, can you change the log errors and instead wrap them with better descriptions instead?

@andrewsykim just to confir, the idea is to "concatenate" the returned error, right?

2020-04-07 07:12 UTC, SataQiu commented
+1 for @andrewsykim 
Wrapping the errors with descriptions is better :)

2020-04-07 08:10 UTC, aojea commented on pkg/util/ipvs/ipvs_linux.go
>  		return err
```suggestion
		return errors.Wrap(err, "Could not convert IPVS while adding server")
```

2020-04-07 21:42 UTC, carlosedp commented
That's much better. Thanks for the suggestion.

2020-04-07 22:56 UTC, aojea commented
@carlosedp I thought it was already importing `"github.com/pkg/errors"` , 
you have to import it and run `hack/update-bazel.sh`

2020-04-07 23:14 UTC, carlosedp commented
Should I replace Golang's "error" with "github.com/pkg/errors" or import it naming it something else?

2020-04-08 08:47 UTC, aojea commented
> Should I replace Golang's "error" with "github.com/pkg/errors" or import it naming it something else?

 replace Golang's "errors" with "github.com/pkg/errors" IIRC

2020-04-08 17:20 UTC, carlosedp commented
/test pull-kubernetes-e2e-kind

2020-04-08 18:55 UTC, aojea commented
/lgtm 
thanks

2020-04-13 21:57 UTC, carlosedp commented
Any news on this?

2020-04-22 18:00 UTC, carlosedp commented
Ping @andrewsykim :)

2020-04-22 18:10 UTC, andrewsykim reviewed
Sorry for the delay, had mostly nits around formatting.

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS while adding server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS while updating server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS while deleting server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return nil, errors.Wrap(err, "Could not convert IPVS while getting server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return nil, errors.Wrap(err, "Could not get IPVS service")
nit: start errors with lower case

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return nil, errors.Wrap(err, "Could not convert IPVS service to virtual server")
"could not convert IPVS service to local virtual server"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return nil, errors.Wrap(err, "Could not get IPVS services")
nit: start with lower case

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +			return nil, errors.Wrap(err, "Could not convert IPVS service to virtual server")
"could not convert IPVS service to local virtual server"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS while adding real server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS service to real destination")
"could not convert local real server to IPVS destination"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS while deleting real server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS service to real destination")
"could not convert local real server to IPVS destination"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS while updating real server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return errors.Wrap(err, "Could not convert IPVS service to IPVS destination")
"could not convert local real server to IPVS destination"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return nil, errors.Wrap(err, "Could not convert IPVS while getting real server")
"could not convert local virtual server to IPVS service"

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +		return nil, errors.Wrap(err, "Could not get IPVS destination for service")
nit: start with lower case

2020-04-22 18:10 UTC, andrewsykim commented on pkg/util/ipvs/ipvs_linux.go
> +			return nil, errors.Wrap(err, "Could not convert IPVS destination to real destination")
"could not convert IPVS destination to local real server"

2020-04-22 19:06 UTC, andrewsykim reviewed
/approve
/lgtm

Thank you @carlosedp

2020-04-22 20:15 UTC, carlosedp commented
/test pull-kubernetes-conformance-kind-ga-only-parallel

2020-04-22 21:41 UTC, carlosedp commented
All good now!

2020-04-23 00:02 UTC, merged

2020-04-23 01:59 UTC, rikatz commented
@carlosedp tks for taking this one :)