Bazelhack
kubernetes/kubernetes pull request #90199
Opened 2020-04-16 07:14 UTC by aojea

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Supress warning on the `hack/update-bazel.sh` script

**Which issue(s) this PR fixes**:

Fixes #79499

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-04-16 07:16 UTC, aojea commented
/assign @BenTheElder 
/sig testing

2020-04-16 07:18 UTC, tanjunchen commented on hack/update-bazel.sh
> +    2>&1 | grep -Ev "vendor/github.com/seccomp/libseccomp-golang/seccomp(_internal)?.go: pkg-config not supported: #cgo pkg-config: libseccomp" \
see https://github.com/kubernetes/kubernetes/pull/79502/files#diff-fa58360a7125fddab9491c80bb3f1a87R72

2020-04-16 07:20 UTC, tanjunchen commented on hack/update-bazel.sh
> +    2>&1 | grep -Ev "vendor/github.com/seccomp/libseccomp-golang/seccomp(_internal)?.go: pkg-config not supported: #cgo pkg-config: libseccomp" \
@aojea  Thank  you. This output is a bit annoying.

https://github.com/kubernetes/kubernetes/issues/79499#issuecomment-614459419

2020-04-16 08:10 UTC, BenTheElder requested changes
Please see the previous PR chain. We did NOT just suppress the warnings.

2020-04-16 08:11 UTC, BenTheElder commented
/hold

2020-04-16 08:12 UTC, BenTheElder commented
https://github.com/kubernetes/kubernetes/pull/79287

2020-04-17 21:35 UTC, aojea commented
/close

these modules dependencies are hard to me to deal with 🙃

2020-04-17 21:35 UTC, closed without merging