revert flaky conformance test
kubernetes/kubernetes pull request #90509
Opened 2020-04-27 03:29 UTC by knight42

**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:
Revert the flaky conformance test about `kubectl explain`.

**Which issue(s) this PR fixes**:

Fixes #90506 

**Special notes for your reviewer**:
Not sure where to place the non-conformace test, so I decided to simply remove it.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-04-27 03:29 UTC, knight42 commented
/cc @liggitt 
/assign @liggitt

2020-04-27 03:46 UTC, knight42 commented
/cc @soltysh

2020-04-27 12:11 UTC, hasheddan approved these changes
/lgtm

2020-04-27 12:21 UTC, soltysh requested changes
I was under the impression we don't want to remove those bits, but rather move it to separate test which won't be part of conformance. Iow. you'll need to create a separate test exercising this functionality but don't add it to conformance.

2020-04-27 13:03 UTC, soltysh commented
/hold

2020-04-27 15:33 UTC, knight42 commented
@soltysh @liggitt PTAL

2020-04-28 13:10 UTC, liggitt commented on test/e2e/apimachinery/crd_publish_openapi.go
> +		ginkgo.By("kubectl explain works for CR with the same resource name as built-in object.")
this is still inside the conformance test

2020-04-28 13:12 UTC, liggitt commented
this is still modifying a conformance test. please restore that test to the state it was in prior to https://github.com/kubernetes/kubernetes/pull/89505

2020-04-28 13:13 UTC, knight42 commented
@liggitt @soltysh 

I have found out that the root cause of the problem `the server doesn't have a resource type "ksvc"` is `CachedDiscoveryClient` trying to expand the short name `ksvc` using the stale local cache.

As far as I am concerned, we have two plans to solve this problem:
1. Force `CachedDiscoveryClient` to invalidate local cache just before https://github.com/kubernetes/client-go/blob/5159cff060fb98cd98592f6663f322c982066d7e/restmapper/shortcut.go#L87
2. Run `kubectl explain ksvc` twice in conformance test so that local cache can get refreshed.

Since Plan 1 may have influence that I cannot forsee, I chose Plan 2 here.

2020-04-28 13:15 UTC, liggitt commented
that issue was tracked in https://github.com/kubernetes/kubernetes/issues/65517

I don't think it's a good idea to add workarounds for bugs into conformance tests like that...

2020-04-28 13:19 UTC, knight42 commented
@liggitt well yes... then what do you think of plan 1 I mentioned above?

2020-04-28 13:26 UTC, liggitt commented
> @liggitt well yes... then what do you think of plan 1 I mentioned above?

Unconditional invalidation doesn't seem like a good idea. Let's get the flaky test isolated and out of conformance, then pursue fixing the issue in https://github.com/kubernetes/kubernetes/issues/65517

2020-04-28 13:36 UTC, knight42 commented
@liggitt PTAL now

2020-04-28 13:50 UTC, liggitt commented
/ok-to-test
/priority important-soon

2020-04-28 14:25 UTC, soltysh commented
/hold cancel

2020-04-28 15:06 UTC, knight42 commented
spurious errors?

/retest

2020-04-28 15:49 UTC, knight42 commented
look like that we have bumped into other flaky tests?

2020-04-28 20:14 UTC, fedebongio commented
/cc @Jefftree @johnbelamaric

2020-04-30 09:53 UTC, knight42 commented
/test pull-kubernetes-e2e-kind

2020-04-30 15:50 UTC, liggitt commented
/lgtm
/approve

2020-04-30 23:21 UTC, spiffxp commented
/test pull-kubernetes-files-remake

2020-05-01 07:40 UTC, merged