[WIP] Switch core master base images from debian to distroless
kubernetes/kubernetes pull request #90674
Opened 2020-05-01 15:26 UTC by dims

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Borrowed from https://github.com/kubernetes/kubernetes/pull/75306

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-05-02 02:23 UTC, dims commented
/test pull-kubernetes-conformance-kind-ga-only-parallel

2020-05-02 13:38 UTC, dims commented
/test pull-kubernetes-e2e-kind-ipv6

2020-05-02 13:45 UTC, dims commented
/priority important-soon

2020-05-02 13:45 UTC, dims commented
/kind feature

2020-05-02 13:45 UTC, dims commented
/assign @tallclair @yuwenma @wojtek-t @mm4tt

2020-05-02 13:52 UTC, dims commented
/sig scalability

2020-05-02 14:17 UTC, liggitt commented
Does the go-runner behave the same as the bash redirection with interleaving stdout/stderr lines coherently?

I vaguely remember running into related issues with the way go launches sub processes for tests and combines the stdout/stderr output (https://github.com/golang/go/issues/33419#issuecomment-517800582)

If bash redirection already interleaves lines incoherently, I guess this is no worse. If it interleaves line-by-line, then we need to figure out a way to do the same here.

2020-05-02 18:20 UTC, dims commented
@liggitt bash already interleaves. Just tried this test https://gist.github.com/dims/da574174817135b5ddf100b9ee89e8e6

2020-05-04 09:29 UTC, mm4tt commented
Nice, I'll see what we can do to scale test it

2020-05-04 10:03 UTC, mm4tt commented
+ @tosi3k, who will help with running the tests

2020-05-04 10:22 UTC, dims commented
@mm4tt @tosi3k awesome! thanks.

2020-05-04 10:50 UTC, tosi3k commented
@dims just to confirm before tests execution - is c80b2c6 the commit we want the tests to run on top of?

If so, we will run the tests tomorrow and come back here with conclusions on the day after tomorrow (on Wednesday, to be precise).

2020-05-04 13:59 UTC, dims commented
@tosi3k confirmed. yes please!

2020-05-04 18:48 UTC, dekkagaijin commented
If this gives good enough performance at scale, LGTM. We'd want to move the `go-runner` base image to a more secure repo, but it does qualify as `distroless` as far as security is concerned

2020-05-04 19:23 UTC, tallclair commented
I haven't had a chance to carefully read through go-runner, but can someone (@dims ?) give me a quick explanation of why go-runner solves the performance problems, and the solution can't just be integrated back into klog? In other words, why does writing to the log files in a separate process solve the problems?

2020-05-04 19:27 UTC, liggitt commented
we are not guaranteed all stderr/stdout output is generated via klog

2020-05-04 19:31 UTC, tallclair commented
@liggitt klog could "seize control" of stdout/err by replacing the global stdout/stderr variable with a pipe.

2020-05-04 20:20 UTC, dims commented
@tallclair the scalability team is running a test with this PR, let's see if it actually works. go-runner just mimics what we used to do with bash redirection as closely as possible in the hope that it works at this point until we have confirmation that it does.

2020-05-04 20:24 UTC, dims commented
> If this gives good enough performance at scale, LGTM. We'd want to move the `go-runner` base image to a more secure repo, but it does qualify as `distroless` as far as security is concerned

Yes of course. +1 @dekkagaijin

2020-05-04 21:23 UTC, immutableT commented
/cc @immutableT

2020-05-04 21:29 UTC, immutableT commented
> Keep the same behavior we have now with redirection of stdout/stderr 1>>/var/log/kube-apiserver.log 2>&1

Why is this required/desirable?

2020-05-04 21:48 UTC, dims commented
@immutableT I am assuming capturing kube-apiserver logs is desirable :)

ideally we want to use klog's `log-file` to capture the api server logs (see [here](https://github.com/kubernetes/kubernetes/pull/78466/files#diff-6e3b476b9225d1213dc6ad13e453fc16R1863-R1865)) but that ran into scalability issues with log rotation, but that attempt got reverted in https://github.com/kubernetes/kubernetes/pull/83390 (see discussion there). Also see https://github.com/kubernetes/kubernetes/pull/75306 which we would have needed after 78466 landed.

So this PR is an attempt to get us to distroless images by picking up pieces from the attempts above but using go-runner instead of bash.

2020-05-04 22:33 UTC, immutableT commented
Yes, I agree :)
I was trying to ask whether we considered/tested the use of kubelet's log rotation feature (#59898) since the root cause of failures of #83390 seems to be related to that?

2020-05-05 00:09 UTC, dims commented
@immutableT that feature does not work for the majority of the CI jobs that use docker shim (it's specific to non-docker CRI based impls), also there's a serious problem with files cleanup that is still being worked on in https://github.com/kubernetes/kubernetes/issues/90334

2020-05-06 08:24 UTC, tosi3k commented
@dims the experimental 5k test run passed. Here are Grafana dashboards from a [baseline run](http://35.226.146.156:3000/d/uzJNy03Wk/master-dashboard?orgId=1&var-source=distroless-images-baseline&var-etcd_type=All&var-etcd_operation=All&var-verb=All&var-resource=All) and the [experimental run](http://35.226.146.156:3000/d/uzJNy03Wk/master-dashboard?orgId=1&var-source=distroless-images-experiment&var-etcd_type=All&var-etcd_operation=All&var-verb=All&var-resource=All).

The results look good - I don't see any distinct differences between the runs but that's just from my novice's perspective :).

2020-05-06 09:40 UTC, mm4tt commented
Thanks, @tosi3k!
I double checked and I can confirm what @tosi3k wrote, I don't see any significant performance impact of this PR. Looks like this approach will work

2020-05-06 09:54 UTC, dims commented
@tosi3k @mm4tt Excellent News!!! wow. will add another PR for `go-runner`, get that into k8s.gcr.io and then revise this PR to use the image

2020-05-06 17:04 UTC, justaugustus commented
/sig release
/area release-eng security dependency
/assign

2020-05-07 20:57 UTC, justaugustus commented
Explicit hold on this, until I review (as it affects the releases). Please do not remove it.
/hold

I should be able to get to this later today. Worst case tomorrow.

2020-05-08 09:55 UTC, justaugustus requested changes
@dims -- Made some code suggestions.

You'll also need to make entries in `build/dependencies.yaml`: https://github.com/kubernetes/kubernetes/blob/90f7ae54acbbab22460fe5fabded02d9b912b834/build/dependencies.yaml#L78-L104

Also, can we pull this into its own Dockerfile? :point_down: 
https://github.com/kubernetes/kubernetes/blob/90f7ae54acbbab22460fe5fabded02d9b912b834/build/lib/release.sh#L378-L379

...and make sure the :point_up: `${base_image}` references the go-runner image.

2020-05-08 09:55 UTC, justaugustus commented on build/common.sh
> +    "kube-apiserver,gcr.io/k8s-staging-kubernetes/go-runner:0.1.0"
```suggestion
    "kube-apiserver,${KUBE_BASE_IMAGE_REGISTRY}/go-runner:v0.1.1"
```

2020-05-08 09:55 UTC, justaugustus commented on build/common.sh
> +    "kube-controller-manager,k8s-staging-kubernetes/go-runner:0.1.0"
```suggestion
    "kube-controller-manager,${KUBE_BASE_IMAGE_REGISTRY}/go-runner:v0.1.1"
```

2020-05-08 09:55 UTC, justaugustus commented on build/common.sh
> +    "kube-scheduler,gcr.io/k8s-staging-kubernetes/go-runner:0.1.0"
```suggestion
    "kube-scheduler,${KUBE_BASE_IMAGE_REGISTRY}/go-runner:v0.1.1"
```

2020-05-08 09:55 UTC, justaugustus commented on build/workspace.bzl
```suggestion

# Use skopeo to find these values: https://github.com/containers/skopeo
#
# Example
# Manifest: skopeo inspect docker://gcr.io/k8s-staging-build-image/go-runner:v0.1.1
# Arches: skopeo inspect --raw docker://gcr.io/k8s-staging-build-image/go-runner:v0.1.1
```

2020-05-08 09:55 UTC, justaugustus commented on build/workspace.bzl
> +    "manifest": "sha256:cd2b441f045c70cc5f0b48914ffa88a2c05a9de563dae6db3163b0d67ed67558",
Needs the v0.1.1 digests once promoted.
Same w/ the arch digests :point_down:

2020-05-08 09:55 UTC, justaugustus commented on build/workspace.bzl
> +            tag = "0.1.0",  # ignored, but kept here for documentation
```suggestion
            tag = "v0.1.1",  # ignored, but kept here for documentation
```

2020-05-08 09:55 UTC, justaugustus commented on build/workspace.bzl
> +            registry = "gcr.io/k8s-staging-kubernetes",
```suggestion
            registry = "us.gcr.io/k8s-artifacts-prod/build-image",
```

2020-05-08 09:55 UTC, justaugustus commented
/retest

2020-05-08 12:50 UTC, dims commented on build/common.sh
> +    "kube-apiserver,gcr.io/k8s-staging-kubernetes/go-runner:0.1.0"
fixing

2020-05-08 14:19 UTC, dims commented
/test pull-kubernetes-conformance-kind-ga-only-parallel

2020-05-08 14:25 UTC, dims commented
/test pull-kubernetes-e2e-kind

2020-05-08 14:34 UTC, dims commented
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-kind-ipv6

2020-05-08 15:22 UTC, dims commented
/retest

2020-05-08 18:02 UTC, dims commented
/test pull-kubernetes-e2e-gce

2020-05-08 18:26 UTC, justaugustus commented
@dims -- This is looking really great! I'll run a mock stage/release once this merges as well to make sure we're in good shape.

/lgtm
/approve
/assign @BenTheElder @cblecker @fejta

2020-05-08 18:28 UTC, fejta reviewed
/approve

2020-05-08 18:39 UTC, dims commented
/hold cancel

2020-05-08 19:22 UTC, dims commented
/test pull-kubernetes-e2e-gce

2020-05-08 20:23 UTC, justaugustus commented
/test pull-kubernetes-e2e-gce

2020-05-08 21:28 UTC, justaugustus commented
/test pull-kubernetes-e2e-gce

2020-05-08 23:05 UTC, justaugustus commented
/retest

2020-05-09 00:06 UTC, dims commented
/retest

2020-05-09 00:37 UTC, justaugustus commented
(the suspense is killing me!)

2020-05-09 01:02 UTC, BenTheElder commented
/retest
flexvolume gce flake

2020-05-09 01:04 UTC, BenTheElder commented
/lgtm
/approve
quite exciting.

2020-05-09 02:28 UTC, dekkagaijin commented
/retest

2020-05-09 03:46 UTC, justaugustus commented
/retest

2020-05-09 05:22 UTC, justaugustus commented
`[sig-storage] Flexvolumes should be mountable when attachable`
/retest

Hmmm... https://github.com/kubernetes/kubernetes/issues/78737
FYI @kubernetes/sig-storage-bugs

2020-05-09 05:53 UTC, BenTheElder commented
Uh `pull-kubernetes-e2e-gce` has not passed even once on the current commit.
In fact, it has failed 10 times in a row.
/hold

2020-05-09 05:57 UTC, BenTheElder commented
I remember this now. The controller manager runs flexvolume plugins, and flexvolume plugins include our e2e plugins may be shell scripts. You can't rip out the userspace from controller manager without breaking flexvolume.
/lgtm cancel

2020-05-09 05:57 UTC, BenTheElder commented
/approve cancel

2020-05-09 05:59 UTC, BenTheElder commented
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-storage/flexvolume.md

init, attach, detach, wait for attach, checking if attached are all called from the controller manager, which is done via an exec model. While the binary called comes from a path on the host, it is invoked in the controller-manager container filesystem (or kubelet).

Currently they can reasonably expect a generic linux userspace ... debian specifically for controller manager.

2020-05-09 06:48 UTC, justaugustus requested changes
@BenTheElder -- would I be correct in the assumption that removing the controller-manager changes should get us back in a good state?

If so, @dims, I've made a few code suggestions on what to revert.

EDIT: @dims -- In places where we can't/shouldn't use `go-runner` e.g., `kube-controller-manager`, `kube-proxy`, can you add a note referencing the [base image exception list](https://git.k8s.io/sig-release/release-engineering/baseimage-exception-list.md)?

2020-05-09 06:48 UTC, justaugustus commented on build/BUILD
> +        "base": "@go-runner-linux-{ARCH}//image",
```suggestion
        "base": "@debian-base-{ARCH}//image",
```

2020-05-09 06:48 UTC, justaugustus commented on build/common.sh
> +    "kube-controller-manager,${KUBE_BASE_IMAGE_REGISTRY}/go-runner:${go_runner_version}"
```suggestion
    "kube-controller-manager,${KUBE_BASE_IMAGE_REGISTRY}/debian-base-${arch}:${debian_base_version}"
```

2020-05-09 06:48 UTC, justaugustus commented on cluster/gce/manifests/kube-controller-manager.manifest
> +                 "/go-runner", "--log-file=/var/log/kube-controller-manager.log", "--also-stdout=false", "--redirect-stderr=true",
Revert this change.

2020-05-09 06:55 UTC, BenTheElder commented
As far as I know controller-manager / flexvolume is the only thing like this, reverting it should be sufficient but unfortunate, we'll still be stuck shipping these images ...

I had some conversations with @yuwenma and the GKE node team about this in the past when we were trying to figure out @yuwenma's attempt at this.

IIRC per @msau42 the idea was that eventually flexvolume could be deprecated out, but probably not until CSI was further along, or something along those lines ...

2020-05-09 08:24 UTC, justaugustus commented
> As far as I know controller-manager / flexvolume is the only thing like this, reverting it should be sufficient but unfortunate, we'll still be stuck shipping these images ...

Okay, that was what I was getting from skimming through some of the docs/issues.
FWIW, we'll be still be required to ship `debian-base` (to support `debian-iptables` and others on the [exceptions list](https://github.com/kubernetes/sig-release/blob/master/release-engineering/baseimage-exception-list.md)).

2020-05-09 08:52 UTC, dims commented
/retest

2020-05-09 10:58 UTC, dims commented
/hold cancel

@justaugustus @BenTheElder removed controller-manager from this PR. Let's deal with that later.

2020-05-09 11:06 UTC, justaugustus commented
> EDIT: @dims -- In places where we can't/shouldn't use `go-runner` e.g., `kube-controller-manager`, `kube-proxy`, can you add a note referencing the [base image exception list](https://git.k8s.io/sig-release/release-engineering/baseimage-exception-list.md)?

@dims -- Can you address this as well? I want to make sure we deter changes to the images and provide context about why.

2020-05-09 14:01 UTC, dims commented
@justaugustus not yet. i want this to merge and i am looking at options for controller-manager, looking at logs now.

2020-05-09 14:03 UTC, justaugustus commented
/lgtm

2020-05-09 19:02 UTC, merged