kubectl describe: print toleration tolerating everything
kubernetes/kubernetes pull request #91024
Opened 2020-05-12 14:08 UTC by ingvagabund

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
An empty key with operator Exists matches all keys, values
and effects which means this will tolerate everything:
tolerations:
- operator: "Exists"

as stated in https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/.

However, the current printTolerationsMultilineWithIndent implementation ignores
this case. As the toleration is valid, there's no reason
to skip it when writing the list of all pod's tolerations.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-05-13 07:41 UTC, ingvagabund commented
/retest

2020-05-13 11:31 UTC, ingvagabund commented
/test pull-kubernetes-verify

2020-05-13 15:03 UTC, soltysh requested changes
One nit and you're good to go.

2020-05-13 15:06 UTC, ingvagabund commented on staging/src/k8s.io/kubectl/pkg/describe/describe.go
> +		if toleration.Operator == corev1.TolerationOpExists && len(toleration.Value) == 0 && len(toleration.Key) == 0 {
True. Updated.

2020-05-14 14:43 UTC, soltysh approved these changes
/approve
But you need to fix unit test in https://github.com/kubernetes/kubernetes/blob/438debfb7263619d444c2eb9f6b52747415a9f24/staging/src/k8s.io/kubectl/pkg/describe/describe_test.go#L196

2020-05-14 15:19 UTC, soltysh approved these changes
/lgtm
/priority backlog

2020-05-14 20:58 UTC, ingvagabund commented
/retest

2020-05-15 08:34 UTC, ingvagabund commented
/test pull-kubernetes-e2e-kind-ipv6

2020-05-15 09:48 UTC, merged