reduce race risk in kubelet for missing KUBERNETES_SERVICE_HOST
kubernetes/kubernetes pull request #91500
Opened 2020-05-27 15:46 UTC by deads2k

related to https://github.com/kubernetes/kubernetes/issues/40973

If the pod originates from the kube-api, when we know that the kube-apiserver is responding and the kubelet's credentials are valid. Knowing this, it is reasonable to wait until the service lister has synchronized at least once before attempting to build a service env var map.  This doesn't present the race below from happening entirely, but it does prevent the "obvious" failure case of services simply not having completed a list operation that can reasonably be expected to succeed. One common case this prevents is a kubelet restart reading pods before services and some pod not having the KUBERNETES_SERVICE_HOST injected because we didn't wait a short time for services to sync before proceeding. The KUBERNETES_SERVICE_HOST link is special because it is unconditionally injected into pods and is read by the in-cluster-config for pod clients

/kind bug
/priority important-soon
@kubernetes/sig-node-bugs 
@sjenning @rphillips @sttts @tnozicka 
@liggitt you were on the original thread

```release-note
NONE
```

2020-05-27 15:54 UTC, rphillips commented
/assign @derekwaynecarr

2020-05-27 17:34 UTC, rphillips commented
My only concern is with the side-effect of rebooting and the node comes back up not attached to the cluster, so the cache sync cannot be performed. It looks like the tests pass, so it may not be relevant to this change.

2020-05-27 21:01 UTC, deads2k commented
> My only concern is with the side-effect of rebooting and the node comes back up not attached to the cluster, so the cache sync cannot be performed. It looks like the tests pass, so it may not be relevant to this change.

If the kubelet isn't attached to the cluster, I would not expect it to need to set env vars until after it found *new* pods.  I would expect containers for existing pods to run using their existing env vars.

2020-05-29 14:18 UTC, derekwaynecarr requested changes
please add a test case, but this will eliminate a race that most apps would not expect a race to occur.

2020-05-29 14:18 UTC, derekwaynecarr commented on pkg/kubelet/kubelet_pods.go
> +	if !kubetypes.IsStaticPod(pod) && !kl.serviceHasSynced() {
can you update `TestMakeEnvironmentVariables` to test a scenario where serviceHasSynced returns false to ensure this does error?

2020-05-29 14:20 UTC, derekwaynecarr commented on pkg/kubelet/kubelet_pods.go
> +	if !kubetypes.IsStaticPod(pod) && !kl.serviceHasSynced() {
the test case has a way of identifying a nil lister, if we can update it to have a case of service not synced on one additional scenario, that would be great.

2020-05-29 21:13 UTC, deads2k commented
test cases added.  please review with ?w=1 .  I fixed the test to use a table based test because it was easier to read

2020-05-29 21:19 UTC, derekwaynecarr approved these changes

2020-05-29 21:19 UTC, derekwaynecarr commented
/approve
/lgtm

2020-05-29 22:21 UTC, merged

2020-05-29 23:43 UTC, tedyu commented
```
This doesn't present the race below from happening entirely
```
typo: present

2020-06-04 16:03 UTC, derekwaynecarr commented
@tedyu agree it does not eliminate it entirely, but it reduces the incidence.