docs: cleanup all whitenoise
kubernetes/kubernetes pull request #91554
Opened 2020-05-29 01:54 UTC by daixiang0

Signed-off-by: Xiang Dai <long0dai@foxmail.com>

/kind cleanup

2020-05-29 05:32 UTC, bsdnet approved these changes
Thanks for cleaning them up.

2020-05-29 17:57 UTC, neolit123 reviewed
/ok-to-test
/kind cleanup
/priority backlog

2020-05-29 17:57 UTC, neolit123 commented
/release-note-none

2020-05-30 00:40 UTC, neolit123 reviewed
/lgtm

2020-06-02 03:26 UTC, dixudx approved these changes

2020-06-02 20:04 UTC, fedebongio commented
/lgtm

2020-06-02 20:04 UTC, kensipe reviewed
/lgtm

2020-06-09 03:27 UTC, daixiang0 commented
/retest

2020-06-09 06:16 UTC, daixiang0 commented
/retest

2020-06-10 08:03 UTC, daixiang0 commented
/cc @ bsdnet

2020-06-11 03:54 UTC, bsdnet commented
/lgtm

thanks for the clean up.

I am wonder whether we can write some verify test to make sure new commits do not create such issue in future.

2020-06-21 01:19 UTC, daixiang0 commented
/cc @bsdnet

2020-06-24 07:52 UTC, daixiang0 commented
ping @neolit123

2020-06-24 14:55 UTC, neolit123 commented
@daixiang0 i cannot merge / approve this PR.
see the bot comment above.

2020-06-28 00:57 UTC, daixiang0 commented
ping @fedebongio

2020-08-25 06:01 UTC, daixiang0 commented
ping @neolit123

2020-08-25 06:06 UTC, daixiang0 commented
/release-note-none

2020-08-25 09:13 UTC, neolit123 commented
Try asking in the #pr-reviews channel of k8s slack.

2020-11-04 16:16 UTC, justaugustus requested changes
@daixiang0 -- thanks for the docs cleanup!

Can you rebase this? That should take care of the one review comment I have.
Everything else looks good to me once that is fixed.

2020-11-04 16:16 UTC, justaugustus commented on build/go-runner/README.md
> +# Kubernetes go-runner image
Remove this file.
The go-runner image building is now described here: https://github.com/kubernetes/release/blob/master/images/build/go-runner/README.md

2021-01-19 15:45 UTC, puerco commented
/assign

2021-01-19 15:55 UTC, puerco commented
Pinged the author on slack to see if we're moving forward with this one.

2021-01-20 01:59 UTC, daixiang0 commented
/retest

2021-01-20 02:09 UTC, daixiang0 commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-01-20 06:13 UTC, daixiang0 commented
ping @puerco

2021-01-20 19:08 UTC, puerco commented
Thank you @daixiang0 ! it is now correctly rebased. As your PR edits documents across a very wide spectrum of the project, it has to get approval from a lot of people in order to merge (check out the message from the bot). As neolit said above, the next step will be to request approvals from #pr-reviews.

/lgtm from my part

2021-02-16 13:48 UTC, hasheddan approved these changes
/lgtm

2021-05-18 01:09 UTC, closed without merging