Conformance Behavior Mapping sig-network
kubernetes/kubernetes pull request #91647
Opened 2020-06-01 23:09 UTC by Jefftree

**What type of PR is this?**

 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

I'm not as familiar with this area as the other sigs. Feel free to scritinize.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/area conformance
/assign @johnbelamaric 
/assign @spiffxp

2020-06-02 21:15 UTC, Jefftree commented
/cc @hh

2020-06-09 00:43 UTC, spiffxp commented
/test pull-kubernetes-conformance-kind-ga-only-parallel

2020-06-16 20:01 UTC, johnbelamaric requested changes
First pass, I need to dig deeper on some of these.

2020-06-16 20:53 UTC, Jefftree commented on test/conformance/behaviors/sig-network/common.yaml
> +  description: Node to pod networking should function over HTTP. hostNetwork must be enabled.
We would need a separate test for each configuration. The test currently only tests with hostNetwork enabled. I think what you mentioned should be a separate behavior?

2020-06-16 20:56 UTC, Jefftree commented on test/conformance/behaviors/sig-network/service.yaml
> +  description: Service endpoint latency must not exceed 20s for p50 and 50s for p90.
I agree, but I think it'd be best to do the behaviors mapping and adding/removing/changing conformance tests in separate PRs

2020-06-16 23:04 UTC, johnbelamaric commented on test/conformance/behaviors/sig-network/service.yaml
> +  description: Service endpoint latency must not exceed 20s for p50 and 50s for p90.
We shouldn't add the behavior though. After we get the behaviors we want, we can take our list of "extra tests" and verify that we want to demote them.

2020-06-16 23:04 UTC, johnbelamaric commented on test/conformance/behaviors/sig-network/common.yaml
> +  description: Node to pod networking should function over HTTP. hostNetwork must be enabled.
yes, add the behavior. do we have the `provisional` status yet?

2020-06-16 23:05 UTC, johnbelamaric commented on test/conformance/behaviors/sig-network/common.yaml
> +  description: Node to pod networking should function over HTTP. hostNetwork must be enabled.
(or `pending` maybe is better?)

2020-06-16 23:12 UTC, Jefftree commented on test/conformance/behaviors/sig-network/service.yaml
> +  description: Service endpoint latency must not exceed 20s for p50 and 50s for p90.
ack, I think for this first pass, I'll omit any convoluted tests that need in depth digging into the test implementation so we can iterate faster.

2020-06-23 21:34 UTC, Jefftree commented on test/conformance/behaviors/sig-network/dns.yaml
> +  description: A pod in the cluster must be able to resolve cluster DNS entries such as kubernetes.default via /etc/hosts/.
Thanks for the catch! This behavior was accidentally attached to the wrong test.

2020-06-23 21:40 UTC, Jefftree commented on test/conformance/behaviors/sig-network/service.yaml
> +  description: When a Pod is created or updated to have its label matching a Service's label selector, the Service's Endpoint object must show all ports exposed by the pod.
As described in the comment earlier, I'll omit this test from our first pass since it requires further investigation.

2020-06-23 21:43 UTC, Jefftree commented on test/conformance/behaviors/sig-network/common.yaml
> +  description: Node to pod networking should function over HTTP. hostNetwork must be enabled.
I'll include that with a separate PR for adding provisional behaviors.

2020-06-24 19:52 UTC, spiffxp commented
/retest
the verify job is failing on what to me appear to be issues related to upgrading to 1.14, I'm curious if a retest will solve this

2020-07-28 22:40 UTC, Jefftree commented
Closing per https://github.com/kubernetes/enhancements/pull/1910

/close

2020-07-28 22:40 UTC, closed without merging