fix staticcheck failures from /cmd/scale/scale.go
kubernetes/kubernetes pull request #92416
Opened 2020-06-23 11:08 UTC by Cweiping

[fix staticcheck failures #92402
](https://github.com/kubernetes/kubernetes/issues/92402)

2020-06-23 11:23 UTC, dixudx requested changes

2020-06-23 11:23 UTC, dixudx commented on staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go
> -	err = r.Visit(func(info *resource.Info, err error) error {
Better not remove these lines.

2020-06-23 11:23 UTC, dixudx commented on staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go
> -	})
Add error handling here.

2020-06-23 12:01 UTC, Cweiping commented on staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go
> -	})
Done.Looking forward to your review.

2020-06-30 12:01 UTC, dixudx requested changes
Please remove `vendor/k8s.io/kubectl/pkg/cmd/scale` from `hack/.staticcheck_failures` as  well.

2020-06-30 12:06 UTC, Cweiping commented
> Please remove `vendor/k8s.io/kubectl/pkg/cmd/scale` from `hack/.staticcheck_failures` as well.

Done.

2020-07-02 13:51 UTC, wawa0210 commented
/ok-to-test

2020-07-04 07:43 UTC, Cweiping commented
/test pull-kubernetes-integration
/test pull-kubernetes-node-e2e
/test pull-kubernetes-e2e-kind

2020-07-04 10:14 UTC, Cweiping commented
/test pull-kubernetes-integration

2020-07-04 13:36 UTC, Cweiping commented
/test pull-kubernetes-integration

2020-07-05 00:54 UTC, Cweiping commented
/test pull-kubernetes-integration

2020-07-06 02:47 UTC, dixudx approved these changes
/lgtm

2020-07-06 02:47 UTC, dixudx commented
/retest

2020-07-12 05:20 UTC, Cweiping commented
/test pull-kubernetes-integration

2020-07-18 08:44 UTC, Cweiping commented
/test pull-kubernetes-integration

2020-07-26 01:58 UTC, Cweiping commented
/test pull-kubernetes-integration

2020-09-05 10:48 UTC, Cweiping commented
/test pull-kubernetes-integration

2020-12-15 03:05 UTC, closed without merging