Make nested /volume/ repo images overridable
kubernetes/kubernetes pull request #92957
Opened 2020-07-10 06:56 UTC by r4f4

The multi-arch container images used in tests live in quay.io which
doesn't support nesting. By making the /volume/ images repo configurable,
we are able to override them despite our current limitation.

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**: It helps us overcome a limitation of quay.io, no nesting, regarding multi-arch container images used in testing.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: No

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-07-10 06:58 UTC, r4f4 commented
This change will need to be backported to all releases down to 1.16. The 1.16 release affects OCP-4.3 which is supported until late October.

2020-07-10 08:19 UTC, mkumatag requested changes
It is a fair ask, that registry can stay anywhere even outside the GCR. Code looks to me, it will be great if you can enhance the test coverage for the volume repos here: https://github.com/kubernetes/kubernetes/blob/2d327ac4558d78c744004db178dacb80bd6e0b9e/test/utils/image/manifest_test.go#L114

2020-07-10 11:39 UTC, r4f4 commented
I added a test and fixed an indentation issue.

2020-07-10 13:42 UTC, mkumatag commented
/ok-to-test

2020-07-10 13:44 UTC, mkumatag commented
/assign
/priority important-soon

2020-07-10 15:41 UTC, mkumatag commented
/lgtm
/approve
/retest

2020-07-16 02:02 UTC, mkumatag commented
@kubernetes/milestone-maintainers can someone help us adding the 1.19 milestone to this PR?

2020-07-16 11:20 UTC, droslean commented
/milestone v1.19

2020-07-16 13:31 UTC, merged