publishing: use go 1.14.5 for master and release-1.19
kubernetes/kubernetes pull request #93138
Opened 2020-07-16 07:01 UTC by nikhita

https://github.com/kubernetes/publishing-bot/pull/232 adds the `default-go-version` field to the rules file and https://github.com/kubernetes/kubernetes/pull/93088 updates go version to 1.14.5.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/kind cleanup
/hold
this should not merge until https://github.com/kubernetes/publishing-bot/pull/232 is deployed

/assign @sttts @dims @justaugustus

2020-07-16 09:35 UTC, justaugustus commented
/lgtm
/milestone v1.19

2020-07-16 09:35 UTC, justaugustus commented
/retest

2020-07-16 10:24 UTC, nikhita commented
/retest

On Thu, Jul 16, 2020 at 3:38 PM Kubernetes Prow Robot <
notifications@github.com> wrote:

> @nikhita <https://github.com/nikhita>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-gce-100-performance 7746d8d
> <https://github.com/kubernetes/kubernetes/commit/7746d8dd0acb9083aa7f40394742457c917440e3>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-100-performance/1283657994248130560/> /test
> pull-kubernetes-e2e-gce-100-performance
> pull-kubernetes-typecheck 7746d8d
> <https://github.com/kubernetes/kubernetes/commit/7746d8dd0acb9083aa7f40394742457c917440e3>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-typecheck/1283696875022585856> /test
> pull-kubernetes-typecheck
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=93138>. Your
> PR dashboard. Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/93138#issuecomment-659313189>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD24BUEBYRQ74Q32F7TQE43R33GRLANCNFSM4O3VZ3EA>
> .
>

2020-07-16 10:46 UTC, nikhita commented
/retest

On Thu, Jul 16, 2020 at 4:12 PM Kubernetes Prow Robot <
notifications@github.com> wrote:

> @nikhita <https://github.com/nikhita>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-typecheck 7746d8d
> <https://github.com/kubernetes/kubernetes/commit/7746d8dd0acb9083aa7f40394742457c917440e3>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-typecheck/1283696875022585856> /test
> pull-kubernetes-typecheck
> pull-kubernetes-e2e-gce-100-performance 7746d8d
> <https://github.com/kubernetes/kubernetes/commit/7746d8dd0acb9083aa7f40394742457c917440e3>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-100-performance/1283696875035168768/> /test
> pull-kubernetes-e2e-gce-100-performance
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=93138>. Your
> PR dashboard. Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/93138#issuecomment-659329413>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD24BUCU27MZCIUWQ3O6FRTR33KQVANCNFSM4O3VZ3EA>
> .
>

2020-07-19 19:02 UTC, justaugustus requested changes
@nikhita -- We've just bumped to go1.14.6 in https://github.com/kubernetes/kubernetes/pull/93198, so we can update that here too when you have a chance.

2020-07-20 08:45 UTC, nikhita commented
/hold cancel
https://github.com/kubernetes/publishing-bot/pull/232 has been deployed

2020-07-20 09:34 UTC, nikhita commented
/retest

2020-07-20 10:29 UTC, nikhita commented
/retest

2020-07-20 10:58 UTC, nikhita commented
/retest

2020-07-20 11:10 UTC, nikhita commented
/retest

On Mon, Jul 20, 2020 at 4:33 PM Kubernetes Prow Robot <
notifications@github.com> wrote:

> @nikhita <https://github.com/nikhita>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-gce c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce/1285130736206090240/> /test
> pull-kubernetes-e2e-gce
> pull-kubernetes-e2e-gce-100-performance c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-100-performance/1285146211707260928/> /test
> pull-kubernetes-e2e-gce-100-performance
> pull-kubernetes-e2e-gce-device-plugin-gpu c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-device-plugin-gpu/1285160053090816000/> /test
> pull-kubernetes-e2e-gce-device-plugin-gpu
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=93138>. Your
> PR dashboard. Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/93138#issuecomment-660959804>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD24BUFYMHNSKF3LJ5PVOTDR4QQB3ANCNFSM4O3VZ3EA>
> .
>

2020-07-20 13:13 UTC, justaugustus commented
`pull-kubernetes-e2e-gce-device-plugin-gpu` is a known flake.
/skip
/lgtm
/approve

2020-07-20 13:53 UTC, justaugustus commented
/test pull-kubernetes-e2e-kind

2020-07-20 15:43 UTC, nikhita commented
/retest

On Mon, Jul 20, 2020 at 8:52 PM Kubernetes Prow Robot <
notifications@github.com> wrote:

> @nikhita <https://github.com/nikhita>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-gce-device-plugin-gpu c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-device-plugin-gpu/1285170371334508544/> /test
> pull-kubernetes-e2e-gce-device-plugin-gpu
> pull-kubernetes-integration c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-integration/1285201576843022340> /test
> pull-kubernetes-integration
> pull-kubernetes-kubemark-e2e-gce-big c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-kubemark-e2e-gce-big/1285201576863993856/> /test
> pull-kubernetes-kubemark-e2e-gce-big
> pull-kubernetes-verify c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-verify/1285201702978326528> /test
> pull-kubernetes-verify
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=93138>. Your
> PR dashboard. Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/93138#issuecomment-661106580>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD24BUEELKHHKMCDC3PJIIDR4ROJRANCNFSM4O3VZ3EA>
> .
>

2020-07-20 16:56 UTC, justaugustus commented
/test pull-kubernetes-integration

2020-07-21 06:55 UTC, nikhita commented
/test pull-kubernetes-e2e-gce

2020-07-21 07:07 UTC, nikhita commented
/test pull-kubernetes-kubemark-e2e-gce-big

2020-07-21 10:03 UTC, nikhita commented
/test pull-kubernetes-integration

On Tue, 21 Jul, 2020, 3:28 PM Kubernetes Prow Robot, <
notifications@github.com> wrote:

> @nikhita <https://github.com/nikhita>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-gce-device-plugin-gpu c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-device-plugin-gpu/1285170371334508544/> /test
> pull-kubernetes-e2e-gce-device-plugin-gpu
> pull-kubernetes-integration c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-integration/1285504169477672960> /test
> pull-kubernetes-integration
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=93138>. Your
> PR dashboard. Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/93138#issuecomment-661760285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD24BUAALXYA5LMQOSW2EQ3R4VRD3ANCNFSM4O3VZ3EA>
> .
>

2020-07-21 15:49 UTC, nikhita commented
/test pull-kubernetes-e2e-gce

2020-07-21 18:21 UTC, nikhita commented
/test pull-kubernetes-integration

On Tue, Jul 21, 2020 at 11:21 PM Kubernetes Prow Robot <
notifications@github.com> wrote:

> @nikhita <https://github.com/nikhita>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-gce-device-plugin-gpu c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-device-plugin-gpu/1285170371334508544/> /test
> pull-kubernetes-e2e-gce-device-plugin-gpu
> pull-kubernetes-integration c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-integration/1285623958103658499> /test
> pull-kubernetes-integration
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=93138>. Your
> PR dashboard. Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/93138#issuecomment-662012220>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD24BUAV46YEDX4O37STGXLR4XIRTANCNFSM4O3VZ3EA>
> .
>

2020-07-21 18:25 UTC, nikhita commented
/test pull-kubernetes-e2e-gce-100-performance

On Tue, Jul 21, 2020 at 11:53 PM Kubernetes Prow Robot <
notifications@github.com> wrote:

> @nikhita <https://github.com/nikhita>: The following tests *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-e2e-gce-device-plugin-gpu c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-device-plugin-gpu/1285170371334508544/> /test
> pull-kubernetes-e2e-gce-device-plugin-gpu
> pull-kubernetes-integration c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-integration/1285623958103658499> /test
> pull-kubernetes-integration
> pull-kubernetes-e2e-gce-100-performance c3b7541
> <https://github.com/kubernetes/kubernetes/commit/c3b75416a8a9e6f41c9e01484697b3027c3ad21f>
> link
> <https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93138/pull-kubernetes-e2e-gce-100-performance/1285623958112047104/> /test
> pull-kubernetes-e2e-gce-100-performance
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=93138>. Your
> PR dashboard. Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/93138#issuecomment-662029274>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD24BUFRSMI5OKK3K35OFRTR4XMLLANCNFSM4O3VZ3EA>
> .
>

2020-07-21 21:23 UTC, justaugustus commented
/test pull-kubernetes-integration

2020-07-21 22:21 UTC, justaugustus commented
/test pull-kubernetes-integration

2020-07-22 02:52 UTC, merged