fix kubectl --local flag bug across all commands
kubernetes/kubernetes pull request #93298
Opened 2020-07-21 15:09 UTC by SaiHarshaK

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Kubectl "local" flag won't ask for kubeconfig after deprecated functionality in [#90243](https://github.com/kubernetes/kubernetes/pull/90243) is removed.

**Which issue(s) this PR fixes**:
Fixes #93188

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-07-21 20:21 UTC, fedebongio commented
/assign @deads2k @soltysh

2020-07-22 09:17 UTC, SaiHarshaK commented on staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
> -func getDefaultServer() string {
I'll revert the changes to this file

2020-07-22 10:18 UTC, SaiHarshaK commented on staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
> -func getDefaultServer() string {
Ill squash the commits?

2020-07-22 22:40 UTC, deads2k commented
/ok-to-test

2020-07-23 10:39 UTC, SaiHarshaK commented
/retest

2020-07-26 11:15 UTC, soltysh requested changes
/hold

2020-07-26 11:15 UTC, soltysh commented on pkg/kubectl/cmd/convert/convert.go
> +	if !o.local {
Although this solves the problem, that's not the right approach. See what I wrote in https://github.com/kubernetes/kubernetes/issues/93188, towards the bottom. You picked the hacky solution which we don't want to happen. The entire sig including the tech leads would like to see a more general solution, rather this one off.

2020-08-26 15:35 UTC, soltysh commented
/close
Let's discuss possible approaches in #93188, and only open PRs once we have a general consensus about it.

2020-08-26 15:35 UTC, closed without merging