Automated cherry pick of #93207: Use local daemonset manifest for installing Nvidia drivers
kubernetes/kubernetes pull request #93453
Opened 2020-07-26 17:32 UTC by hasheddan

Cherry pick of #93207 on release-1.17.

#93207: Use local daemonset manifest for installing Nvidia drivers

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

2020-07-26 17:34 UTC, hasheddan commented
/release-note-none

2020-07-26 17:43 UTC, hasheddan commented
/assign @ahg-g @Huang-Wei 

This one is still failing on `1.17-blocking` due to the issue with using `latest` installer image https://testgrid.k8s.io/sig-release-1.17-blocking#gce-device-plugin-gpu-1.17

2020-07-26 18:43 UTC, hasheddan commented
/test pull-kubernetes-kubemark-e2e-gce-big

2020-07-26 20:01 UTC, hasheddan commented
/retest

2020-07-26 20:10 UTC, hasheddan commented
/retest

2020-07-26 20:28 UTC, hasheddan commented
@kubernetes/release-managers

2020-07-26 21:13 UTC, justaugustus requested changes
One image reference to fix.

2020-07-26 21:13 UTC, justaugustus commented on test/e2e/testing-manifests/scheduling/nvidia-driver-installer.yaml
> +      - image: "gcr.io/google-containers/pause:3.2"
```suggestion
      - image: "k8s.gcr.io/pause:3.2"
```

ref: https://github.com/kubernetes/kubernetes/pull/93356

2020-07-26 21:20 UTC, hasheddan commented
/assign @mikedanese

2020-07-26 21:23 UTC, justaugustus commented
/assign @alejandrox1 @andrewsykim @cblecker

2020-07-26 23:46 UTC, hasheddan commented
/retest

2020-07-27 16:56 UTC, Huang-Wei commented
/lgtm
/approve

Thanks!

2020-07-28 13:22 UTC, hasheddan commented
/cc @liggitt

2020-07-28 14:17 UTC, liggitt commented
/approve

2020-07-28 21:30 UTC, tpepper commented
/kind failing-test
/priority critical-urgent
from parent PR

2020-07-28 22:51 UTC, merged