`exec` completion should behave the same as `logs`
kubernetes/kubernetes pull request #94219
Opened 2020-08-25 11:54 UTC by rayw000

1. `kubectl exec` command completion should have a similar behavior like
`kubectl logs`. That is, when you hit `TAB` after `kubectl exec <flags> <pod
name> <with/without -c>`, container completion should always be triggered.
2. Previously the `exec` command doesn't take inline [Container] argument, this
commit fixed it.

Fix https://github.com/kubernetes/kubectl/issues/890

#### What not fixed yet:
Still cannot stop completing even if a `-c <container_name>` argument has already existed. Seems the completion always expects an inline [Container] argument. This is the same to `kubectl logs`.

2020-08-25 12:59 UTC, thomas-riccardi commented
Until `--` is mandatory to separate the commandline to be executed in the pod, I'm not sure it's OK to accept container name without `-c`.

2020-08-25 16:25 UTC, eddiezane commented
/ok-to-test

2020-08-26 03:15 UTC, rayw000 commented
@thomas-riccardi 
Thanks for your reply. Actually in this commit, `exec` command will accept inline CONTAINER argument in a very strict situation, which must satisfy both the following two conditions simultaneously (refer: https://github.com/kubernetes/kubernetes/pull/94219/files#diff-5c46adf16c80aadcd66a4fd20ee6ad59R177).
- `len(argsIn) > 1`: there are at least two inline arguments (include inline arguments both before and after `--`)
- `argsLenAtDash > 1`: `--` detected and there are at least two inline arguments before `--`

> Perhaps `len(argsIn) > 1` could be removed.


If there is no `--` detected, `argsLenAtDash` will always be `-1`.
`argsLenAtDash > COUNT` means there are `COUNT + 1` inline argument(s) after `exec` before `--`.

So, only commands in the following format would accept inline CONTAINER argument as container name.
```
kubectl exec POD [flags] CONTAINER -- [COMMAND] [...]
```

Hope it is useful. 🙂

2020-08-26 03:20 UTC, rayw000 commented
Hi @eddiesimeon
Would you please give me some advice about why this PR is failed? 
I'm confused that it is an IPv6 network failure, but diff shows nothing related to network. What could I do to pass this test?
Thanks a lot!

2020-08-26 03:34 UTC, rayw000 commented
I've removed `len(argsIn) > 1` because it is always true when `argsLenAtDash > 1`.

2020-08-26 03:46 UTC, rayw000 commented
/retest

2020-08-26 04:46 UTC, rayw000 commented
/kind cleanup

2020-08-26 15:53 UTC, soltysh requested changes
/hold
I agree with @thomas-riccardi on this one, I'd prefer consistency to go towards deprecating that functionality in logs rather than adding it in exec.

2020-08-27 02:19 UTC, rayw000 commented
@soltysh No problem. Currently I'm working on the issue mentioned in top of my description _What's not fixed yet_.

2021-01-24 04:06 UTC, closed without merging