[WIP] Manifest based webhooks implementation
kubernetes/kubernetes pull request #94617
Opened 2020-09-08 13:08 UTC by vivekbagade

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

https://github.com/kubernetes/enhancements/issues/1872

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-09-08 20:09 UTC, caesarxuchao commented
/assign @liggitt @deads2k @lavalamp

2020-11-25 11:50 UTC, donmeganotz requested changes

2020-11-25 11:50 UTC, donmeganotz commented on pkg/kubeapiserver/admission/BUILD
> +        "//pkg/apis/admissionregistration:go_default_library",
![image](https://user-images.githubusercontent.com/10736514/100224016-dae6a500-2ee1-11eb-8a2b-d8b1a24e1444.png)
```suggestion
     srcs = [
         "config.go",
         "initializer.go",
        "webhook_defaulting_validation.go",
     ],
     importpath = "k8s.io/kubernetes/pkg/kubeapiserver/admission",
     visibility = ["//visibility:public"],
     deps = [
#        "//pkg/apis/admissionregistration:go_default_library",
```

2020-11-25 11:54 UTC, donmeganotz approved these changes

2020-11-25 11:54 UTC, donmeganotz commented on pkg/kubeapiserver/admission/initializer.go
>  // PluginInitializer is used for initialization of the Kubernetes specific admission plugins.
Oic@

2020-11-25 12:36 UTC, donmeganotz requested changes
**](( @@megate ott```

```

2021-02-16 17:23 UTC, liggitt commented
closing per https://github.com/kubernetes/enhancements/issues/1872#issuecomment-767158504

/close

2021-02-16 17:23 UTC, closed without merging