fix staticcheck failures for kubectl scale
kubernetes/kubernetes pull request #95270
Opened 2020-10-03 08:46 UTC by SaiHarshaK

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fixes pkg/kubectl static checks for
- staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go

**Which issue(s) this PR fixes**:
Part of #92402

**Special notes for your reviewer**:
Is the err [here](https://github.com/kubernetes/kubernetes/blob/b2730aa48321d55ec166329f9d33782a054b9aba/staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go#L212) ignored intentionally or is a check needed?
/cc @soltysh 
/cc @seans3 
tagging as suggested by @liggitt in [PR](https://github.com/kubernetes/kubernetes/pull/95180)
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-10-03 16:11 UTC, liggitt commented on staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go
> +	_ = r.Visit(func(info *resource.Info, err error) error {
copying comment from earlier PR...

ignoring the error here seems like a mistake. was that intentional or should we return early if one of the objects could not be resolved?

2020-10-12 10:40 UTC, zhouya0 commented
I think this error should not be ignored. Just add the error check :)

2020-10-13 08:43 UTC, zhouya0 reviewed
/lgtm

2020-10-13 08:43 UTC, zhouya0 commented
/ok-to-test

2020-10-13 10:20 UTC, SaiHarshaK commented
/retest

2020-10-13 11:05 UTC, SaiHarshaK commented
/test pull-kubernetes-integration

2020-10-14 03:30 UTC, SaiHarshaK commented
/test pull-kubernetes-integration

2020-10-14 04:02 UTC, SaiHarshaK commented
It seems the error check is intentionally ignored, I get this error [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/95270/pull-kubernetes-integration/1316219802628395008), `Object 'Kind' is missing` to be more precise.

2020-10-15 11:48 UTC, soltysh requested changes
Also it looks like your change is causing test failures, you need to fix that too.

2020-10-15 11:48 UTC, soltysh commented on staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go
>  		if err == nil {
It's preferred to fail fast, so 
```go
if err != nil {
    return err
}
infos = append(infos, info)
```

2020-10-15 11:48 UTC, soltysh commented
/lgtm cancel

2020-10-15 11:49 UTC, soltysh commented
/priority backlog
/triage accepted

2020-10-15 15:12 UTC, SaiHarshaK commented
> Also it looks like your change is causing test failures, you need to fix that too.

Actually i think we can just ignore this error instead of returning it. Returning the error is already handled in another `Visit()` function [below](https://github.com/kubernetes/kubernetes/blob/b540a6abb6e4fab68b5164a3d4db2747f387f6fd/staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go#L241), here this loop is only for counting the len(infos) in [here](https://github.com/kubernetes/kubernetes/blob/b540a6abb6e4fab68b5164a3d4db2747f387f6fd/staging/src/k8s.io/kubectl/pkg/cmd/scale/scale.go#L222).

2020-10-15 16:04 UTC, SaiHarshaK commented
/retest

2021-02-03 17:25 UTC, SaiHarshaK commented
it seems somebody else's PR was merged regarding this issue, so I'll close this.

2021-02-03 17:25 UTC, closed without merging