kubectl: allow users to use args with KUBECTL_EXTERNAL_DIFF
kubernetes/kubernetes pull request #95292
Opened 2020-10-05 03:44 UTC by dougsland

Currently, if users try to use external diff command with arguments
will fail because the entire command won't be available through $PATH.
This patch allow users to use external diff tools with args (or not)
via KUBECTL_EXTERNAL_DIFF env.

Reference: https://github.com/kubernetes/kubectl/issues/937

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

/kind feature

**What this PR does / why we need it**:
Allow kubectl users provide external diff commands with args.

**Which issue(s) this PR fixes**:
Fixes # https://github.com/kubernetes/kubectl/issues/937

**Does this PR introduce a user-facing change?**:
```release-note
kubectl: Previously users cannot provide arguments to a external diff tool via KUBECTL_EXTERNAL_DIFF env. This release now allow users to specify args to KUBECTL_EXTERNAL_DIFF env.
```

2020-10-14 16:18 UTC, eddiezane commented
/ok-to-test

2020-10-14 19:05 UTC, seans3 requested changes
This looks good. Thanks for taking the initiative to add this.

Let's add at least a unit test to prove this works. You may have to move this code into its own function.

2020-10-14 19:05 UTC, seans3 commented
/triage accepted
/priority backlog

2020-10-14 19:06 UTC, seans3 commented
/retest

2020-10-15 11:12 UTC, soltysh requested changes
Two things:
1. what Sean mentioned - please add test
2. update the description of the command to mention the fact that through `KUBECTL_EXTERNAL_DIFF` you can also specify additional arguments passed to `diff`.

2020-10-17 13:51 UTC, dougsland commented
Not related to the change
/retest

2020-11-04 21:04 UTC, soltysh approved these changes
/lgtm
/approve

2020-11-04 22:43 UTC, dougsland commented
/retest error not related

2020-11-04 22:44 UTC, dougsland commented
/retest

2020-11-05 04:28 UTC, eddiezane commented
Failure is https://github.com/kubernetes/kubernetes/issues/96168

/retest

2020-11-05 14:00 UTC, dougsland commented
/retest

2020-11-05 17:24 UTC, merged