bump bazel to 3.4.1
kubernetes/kubernetes pull request #96011
Opened 2020-10-29 17:52 UTC by mikedanese

opening to get some CI coverage

/kind cleanup
/sig release

```release-note
NONE
```

2020-10-29 18:14 UTC, mikedanese commented
/retest

2020-10-29 18:23 UTC, mikedanese commented
/test pull-kubernetes-bazel-test-canary

2020-10-29 20:26 UTC, mikedanese commented
/test pull-kubernetes-bazel-test-canary

2020-10-30 00:30 UTC, mikedanese commented
/test pull-kubernetes-bazel-test-canary

2020-11-03 01:43 UTC, mikedanese commented
/retest

2020-11-03 01:44 UTC, mikedanese commented
I don't think we need this until after code freeze, but I'll let @justaugustus say when.

cc @BenTheElder @fejta

2020-11-03 16:54 UTC, dims commented
/retitle WIP: bump bazel to 3.4.1

2020-11-03 16:56 UTC, mikedanese commented
Oops, forgot to push.

2020-11-03 18:14 UTC, mikedanese commented
/retest

2020-11-04 00:00 UTC, justaugustus requested changes
Chatted with @mikedanese and we'll want to first:
- bump the bazel version in k/repo-infra
- update any required deps in k/repo-infra
- cut a new k/repo-infra release
- target the new k/repo-infra in this PR
- play whack-a-mole with any failures
- ~curl up in a ball and cry~
- ...
- PROFIT

An additional vector is the go1.16 release that is "imminent", so overall, I think I'd prefer for this to wait until 1.21.

/hold
/milestone v1.21
/area release-eng
cc: @kubernetes/release-engineering

2020-11-04 13:28 UTC, dims commented
/uncc

2021-01-05 20:45 UTC, mikedanese commented
Are we ready?

/hold cancel

2021-01-05 20:49 UTC, mikedanese commented
Sorry, just reread you comment after vacation. We can tie this up with a repo-infra version bump if that's desirable.

2021-01-05 21:33 UTC, MushuEE commented
@amwat you might have some insight as to why kubetest is failing on bazel bump

2021-01-06 00:58 UTC, mikedanese commented
/retest

Looks like it failed due to flaky networking in the build cluster.

2021-01-06 05:49 UTC, mikedanese commented
/retest

2021-01-06 08:05 UTC, mikedanese commented
/retest

2021-01-06 18:46 UTC, BenTheElder commented
looks to me like the bazel sandbox is newly interfering with unix sockets skimming https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96011/pull-kubernetes-bazel-test/1346729597261058048

2021-01-06 20:28 UTC, mikedanese commented
Yup, appears to be something in rules_go. I'll investigate.

2021-01-07 02:31 UTC, mikedanese commented
Here's the issue: https://github.com/bazelbuild/rules_go/issues/2776
And a fix: https://github.com/bazelbuild/rules_go/pull/2777

2021-01-07 23:29 UTC, mikedanese commented on staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/fixtures/fixtures.go
> +func pkgPath() (string, error) {
This is copied from https://github.com/kubernetes/kubernetes/pull/90872/

2021-01-07 23:32 UTC, mikedanese commented
/retest

2021-01-08 00:37 UTC, mikedanese commented
For staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/fixtures/fixtures.go change:

/assign @andrewsykim

2021-01-08 02:21 UTC, justaugustus commented
/lgtm
/approve

2021-01-08 02:30 UTC, dims commented
/approve

(For code organization / dependency updates only) :)

2021-01-08 02:31 UTC, dims commented
/hold

( for @andrewsykim )

2021-01-08 16:04 UTC, andrewsykim reviewed
lgtm for `staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/fixtures/fixtures.go`

2021-01-08 16:14 UTC, justaugustus commented
/hold cancel

2021-01-08 16:50 UTC, justaugustus commented
/retest

2021-01-08 17:24 UTC, merged

2021-01-08 17:27 UTC, justaugustus commented
Awesome work, @mikedanese!!!