sig-cli: Add --token-file flag to kubectl
kubernetes/kubernetes pull request #96608
Opened 2020-11-16 14:33 UTC by jjulien

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds the `--token-file` flag to the `kubectl` CLI, providing a more secure way of providing tokens on the command line.  This extends the existing support within the SDK for using token files to the CLI.

This also would now allow all in-cluster config options to be specified on the CLI, which would allow a user to utilize in-cluster config with additional options as a work around to problems like https://github.com/kubernetes/kubernetes/issues/49343

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
/sig cli

**Does this PR introduce a user-facing change?**:
```release-note
Adds the --token-file flag to kubectl for reading a bearer token from file
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2020-11-16 23:17 UTC, jjulien commented
/check-cla

2020-11-17 10:10 UTC, RA489 commented
/check-cla

2020-11-17 14:11 UTC, jjulien commented
/check-cla

2020-11-17 21:14 UTC, leilajal commented
/remove-sig api-machinery

2020-11-26 18:07 UTC, soltysh requested changes
/hold 
This was discussed several times already https://github.com/kubernetes/kubectl/issues/927#issuecomment-693483957, tl;dr there's already `--token` flag and multiple options how to inject tokens into it.

2020-11-26 19:40 UTC, jjulien commented
I was thinking `--token-file` would be more secure than `--token`, because it keeps you from having to put sensitive information on the command line which would show up in the process tree.  I was hoping from a security perspective alone, this feature would be useful.

In addition though, it provides a work around to the problem described in https://github.com/kubernetes/kubernetes/issues/49343 by allowing all of the native in-cluster config options to be provided on the CLI, which then would allow you to append other options to `kubectl` as well.  Today, if in-cluster config is detected, it does not merge other config options that are passed on the command line.  In fact, if it detects other config options on the command line, it just reverts to a default client config, and no in-cluster config is used at all.

While  `--token=$(cat var/run/secrets/kubernetes.io/serviceaccount/token)` is a work around to providing a token file via args, it seems less secure, and does not work in every environment.  Specifically environments where you are using another tool to provide arguments to `kubectl`, and that tool is shell escaping those arguments which prevents a subshell like this from being provided as an extra arg.

Hopefully my reference to that issue doesn't make it look like this patch is to provide a workaround.  My intent was for this to be a feature to make `kubectl` more secure when using tokens, and also extend CLI support for an option that is currently supported by the go-client.

2020-12-04 02:29 UTC, jjulien commented
@soltysh Are you looking for more feedback on this, or are you saying you don't think this feature should be included in the CLI?

2021-01-06 16:59 UTC, jjulien commented
@soltysh I originally proposed a solution to https://github.com/kubernetes/kubernetes/issues/49343 where in-cluster config is merged with any other config provided by the user, with in-cluster config taking the lowest precedence.  As I started to work on it I thought of a couple issues.

1. It looked to require quite a bit of code refactoring in client-go to make it so that in-cluster would be able to tell if a config value was explicitly set to a default value, or if the config value was only default because a user had not provided one.   You would not want  an implicit in-cluster config taking precedence over an explicit value set by a user simply because that value happened to be the same as a default.
2. I  also wondered if this would then be a breaking change.  Is there a scenario where a user is running `kubectl` on a cluster, and they are providing some config arguments, but relying on defaults as well?  Today, if any config arguments are provided, in-cluster config is never even attempted, but if we started merging config arguments with in-cluster, then in-cluster config would override the default values that the user had previously relied upon.

I'm honestly not even sure if the second concern there could actually be a thing, because I would expect if you weren't communicating to the cluster you are running on, you would have to provide overrides for all of the in-cluster config, and that defaults would not work for you, but lack of experience has me wondering at least.  You never know what users are going to do.

Given these concerns, would you be able to provide any feedback or guidance on the proposal I made in my [comment on issue 49343](https://github.com/kubernetes/kubernetes/issues/49343#issuecomment-717368002)?

2021-01-30 13:38 UTC, dougsland commented
/cc

2021-02-11 12:15 UTC, soltysh commented
/close
@jjulien I left you a comment in https://github.com/kubernetes/kubernetes/issues/49343#issuecomment-777409756 I'd love to have those bits around config loading cleaned up a bit.

2021-02-11 12:15 UTC, closed without merging