e2e test regression image multiarch
kubernetes/kubernetes pull request #96792
Opened 2020-11-22 09:47 UTC by aojea

**What type of PR is this?**

As part of fixing   #93281 with https://github.com/kubernetes/kubernetes/pull/95351, we need to promote the new image used in the test first.

This PR it also builds it for multiple architectures

/kind cleanup
/kind failing-test

```release-note
NONE
```

2020-11-22 09:47 UTC, aojea commented
/assign @spiffxp 
This also will allow us to check the new postsumbit jobs for image promotions

2020-11-22 09:47 UTC, aojea commented
/sig testing

2020-11-23 06:48 UTC, aojea commented
/retest

2020-11-23 07:51 UTC, aojea commented
/retest

2020-11-23 18:22 UTC, spiffxp commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd
flake? [sig-api-machinery] API priority and fairness should ensure that requests can be classified by testing flow-schemas/priority-levels

2020-11-23 19:12 UTC, aojea commented
/retest
```

Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can't be drowned out (fairness) expand_more35s | Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can't be drowned out (fairness) expand_more | 35s
-- | -- | --
Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can't be drowned out (fairness) expand_more | 35s
Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can't be drowned out (priority) expand_more51s | Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can't be drowned out (priority) expand_more | 51s
Kubernetes e2e suite: [sig-api-machinery] API priority and fairness should ensure that requests can't be drowned out (priority) expand_more | 51s
Kubernetes e2e suite: [sig-apps] CronJob should delete successful finished jobs with limit of one successful job expand_more | Kubernetes e2e suite: [sig-apps] CronJob should delete successful finished jobs with limit of one successful job expand_more
Kubernetes e2e suite: [sig-apps] CronJob should delete successful finished jobs with limit of one successful job expand_more


```

2020-11-23 19:46 UTC, spiffxp requested changes
Needs version bump. I'm not sure how I feel about trying to land this the day of test freeze.  In theory impact is restricted to one test

2020-11-23 20:14 UTC, aojea commented
> Needs version bump. I'm not sure how I feel about trying to land this the day of test freeze. In theory impact is restricted to one test

let' s wait then, because it has to merge, the postsubmit has to work and I have to land the new test using the new image ... and is not really such important

2020-11-23 20:26 UTC, spiffxp commented
/milestone v1.21

2020-11-23 20:27 UTC, spiffxp commented
/triage accepted

2020-12-10 18:37 UTC, aojea commented
/retest

2020-12-14 20:52 UTC, aojea commented
ping @spiffxp , 
this is needed to close the last failing test in sig-network testgrid :)
https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20IPv6,%20master

2021-01-07 20:30 UTC, aojea commented
ping @BenTheElder @spiffxp

2021-01-08 22:28 UTC, spiffxp approved these changes
/lgtm

2021-01-08 23:39 UTC, merged