Support change the LB selection mode on the existing serivces
kubernetes/kubernetes pull request #96937
Opened 2020-11-29 09:22 UTC by nilo19

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Support change the LB selection mode annotation on the existing services.

**Which issue(s) this PR fixes**:

Fixes: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/416
Ref: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Support change the LB selection mode on the existing serivces
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig cloud-provider
/area provider/azure
/priority important-soon
/triage accepted

2020-11-30 02:47 UTC, nilo19 commented
/retest

2020-12-03 05:00 UTC, feiskyer requested changes

2020-12-03 05:00 UTC, feiskyer commented on staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
> +func (az *Cloud) getServiceLoadBalancerMode(service *v1.Service) (hasMode bool, isAuto bool, vmSetName string) {
would `AS1,AS2"` be still supported?

2020-12-03 05:10 UTC, nilo19 commented on staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
> +	klog.V(2).Infof("shouldChangeLoadBalancer(%s, %s, %s): change the LB to another one", service.Name, currLBName, clusterName)
the new lb name is not defined here

2020-12-03 05:14 UTC, nilo19 commented on staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
> +func (az *Cloud) getServiceLoadBalancerMode(service *v1.Service) (hasMode bool, isAuto bool, vmSetName string) {
no, it would failed in `GetVMSetNames`

2020-12-03 07:50 UTC, nilo19 commented
/retest

2020-12-07 03:25 UTC, feiskyer approved these changes
/lgtm
/retest

2020-12-07 05:50 UTC, nilo19 commented
/retest

2020-12-08 14:56 UTC, andrewsykim reviewed
Is this a really bug or a feature? It sounds like _not_ supporting the annotation for existing Services was an intentional behavior from the start.

2020-12-08 15:04 UTC, andrewsykim commented
I'm putting a temporary hold on this to discuss this further. As previously mentioned, we are freezing features to legacy-cloud-providers starting in v1.21 so I would like to understand if this is really a bug fix or feature. 

/hold

2020-12-09 00:35 UTC, nilo19 commented
@andrewsykim this is not an intentional behavior at the beginning. This is a bug. We found it during the code freeze.

2020-12-09 06:37 UTC, feiskyer commented
yes, this is a bug fix for the annotation that exists for a long time.

2020-12-11 02:56 UTC, nilo19 commented
If we cannot merge the bugfix, I would close it and do it in our fork in out-of-tree repo.

2020-12-11 03:07 UTC, andrewsykim commented
What's the implication of changing a load balancer's "mode"? Does that provision a new load balancer instance or change some configuration on an existing one?

2020-12-11 03:14 UTC, nilo19 commented
> What's the implication of changing a load balancer's "mode"? Does that provision a new load balancer instance or change some configuration on an existing one?

It would re-associate the lb of the service to a new one. Actually, there is one lb per agent pool, and changing the mode means we could change the service's lb instance.

2020-12-20 01:06 UTC, closed without merging