Migrate staging/src/k8s.io/kube-aggregator/pkg/controllers/cache.go structured logging
kubernetes/kubernetes pull request #97585
Opened 2020-12-30 04:09 UTC by gaoguangze111

In staging/src/k8s.io/kube-aggregator/pkg/controllers/cache.go

- Change log to structured logging

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Migrate some logs in staging/src/k8s.io/kube-aggregator/pkg/controllers/cache.go to structured logging.

**Which issue(s) this PR fixes**:

Fixes #

Ref:
- keps/sig-instrumentation/1602-structured-logging
- Structured Logging migration instructions

2020-12-30 04:10 UTC, gaoguangze111 commented
/assign @smarterclayton

2021-01-05 21:27 UTC, fedebongio commented
/assign @deads2k 
/triage accepted

2021-03-05 16:23 UTC, shubheksha requested changes

2021-03-05 16:23 UTC, shubheksha commented on staging/src/k8s.io/kube-aggregator/pkg/controllers/cache.go
> +	klog.InfoS("Waiting for caches to sync", "controller", controllerName)
```suggestion
	klog.InfoS("Waiting for caches to sync", "controlleNamer", controllerName)
```

Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments

2021-03-05 16:23 UTC, shubheksha commented on staging/src/k8s.io/kube-aggregator/pkg/controllers/cache.go
> +	klog.InfoS("Caches are synced", "controller", controllerName)
```suggestion
	klog.InfoS("Caches are synced", "controllerName", controllerName)
```
Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments

2021-05-11 12:56 UTC, shubheksha commented
/priority backlog

2021-05-28 03:24 UTC, yangjunmyfm192085 commented
May be this pr is repeated with #97595, you need keep only one?

2021-05-28 03:26 UTC, yangjunmyfm192085 commented
/wg structured-logging

2021-10-25 05:09 UTC, closed without merging