edit cmd/kubelet/app/init_windows.go to structured Log
kubernetes/kubernetes pull request #97604
Opened 2020-12-30 09:21 UTC by LinshanYu

/kind documentation

edit cmd/kubelet/app/init_windows.go to structured Log，https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

2021-01-07 21:18 UTC, kikisdeliveryservice requested changes

2021-01-07 21:18 UTC, kikisdeliveryservice commented on cmd/kubelet/app/init_windows.go
> +	klog.InfoS("Setting the priority of kubelet process to %s", windowsPriorityClass)
Please see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#remove-string-formatting-from-log-message specifically: "All string formatting (%d, %v, %w, %s) should be removed and log message string simplified."

This means that the changes in this PR are incomplete and the messages need to be updated as per the guidelines above.

2021-01-07 21:40 UTC, kikisdeliveryservice commented
/ok-to-test

2021-01-07 23:43 UTC, kikisdeliveryservice commented
/release-note-none

2021-01-07 23:53 UTC, kikisdeliveryservice commented
/triage accepted
/kind cleanup

2021-01-08 00:14 UTC, kikisdeliveryservice commented
This is a user facing change so if it requires a release note, the original post needs to be edited to include text.

2021-01-26 19:22 UTC, ehashman commented
/priority backlog
/hold

since this probably needs a release note

2021-02-27 09:50 UTC, closed without merging