edit cmd/kubelet/app/plugins_providers.go to structured Log
kubernetes/kubernetes pull request #97608
Opened 2020-12-30 09:37 UTC by LinshanYu

/kind documentation

edit cmd/kubelet/app/plugins_providers.go to structured Log，https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

2021-01-06 12:54 UTC, Aut0R3V commented
/assign

2021-01-06 12:54 UTC, Aut0R3V commented
/unassign

2021-01-07 21:08 UTC, kikisdeliveryservice commented on cmd/kubelet/app/plugins_providers.go
> +		klog.InfoS("Unexpected CSI Migration Feature Flags combination detected: %v. CSI Migration may not take effect", err)
are we intending on changing from warning to info?

2021-01-07 21:10 UTC, kikisdeliveryservice commented
@ehashman this seems like incorrect label should be kind/cleanup not kind/documentation no?

/ok-to-test

2021-01-07 21:13 UTC, kikisdeliveryservice commented on cmd/kubelet/app/plugins_providers.go
> +		klog.InfoS("Unexpected CSI Migration Feature Flags combination detected: %v. CSI Migration may not take effect", err)
ah according to: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#change-log-functions-to-structured-equivalent the answer is yes :+1:

2021-01-07 21:16 UTC, kikisdeliveryservice requested changes
Please see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#remove-string-formatting-from-log-message specifically: "All string formatting (%d, %v, %w, %s) should be removed and log message string simplified."

This means that the changes in this PR are incomplete and the messages need to be updated as per the guidelines above.

2021-01-07 21:16 UTC, kikisdeliveryservice commented on cmd/kubelet/app/plugins_providers.go
> +		klog.InfoS("Skip registration of plugin %s since feature flag %v is enabled", inTreePluginName, pluginMigrationComplete)
as per https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#remove-string-formatting-from-log-message this needs to be reconfigured

2021-01-07 23:41 UTC, kikisdeliveryservice commented
/release-note-none

2021-01-07 23:52 UTC, kikisdeliveryservice commented
/triage accepted
/kind cleanup

2021-01-07 23:52 UTC, ehashman commented
/cc @serathius

2021-01-08 00:12 UTC, kikisdeliveryservice commented
As this is a user facing change adding release-note to be safe, please feel free to modify if this is incorrect

/release-note

2021-01-08 09:36 UTC, serathius commented on cmd/kubelet/app/plugins_providers.go
> +		klog.InfoS("Unexpected CSI Migration Feature Flags combination detected: %v. CSI Migration may not take effect", err)
Printf syntax like `%v` is not supported by `InfoS` method.
Please check out documentation about updating messages and removing formatting https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#remove-string-formatting-from-log-message

2021-01-26 19:20 UTC, ehashman commented
/priority backlog

2021-01-31 07:11 UTC, closed without merging