update aws.go
kubernetes/kubernetes pull request #97633
Opened 2020-12-31 08:31 UTC by lovebaby979

klog

**What this PR does / why we need it**:
Structured Logging migration
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Structured Logging migration
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
Structured Logging migration
```

2021-01-04 20:01 UTC, gnufied commented
/ok-to-test

2021-04-07 19:13 UTC, nckturner requested changes
Thanks, have some fixes around variable names, and questions on when we are using ErrorS vs InfoS.

2021-04-07 19:13 UTC, nckturner commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +			klog.InfoS("Found multiple subnets in AZ", " AZ ",az, "choosingSubnetId", *subnet.SubnetId, "existingSubnetId", *existing.SubnetId,  "subnetId2", *subnet.SubnetId)
`choosingSubnetId` -> `chosenSubnetId`
`existingSubnetId` -> `firstSubnet`
`subnetId2` -> `secondSubnet`

2021-04-07 19:13 UTC, nckturner commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +		klog.InfoS("Found multiple subnets in AZ", " AZ ",az, "choosingSubnetId", *existing.SubnetId,"existingSubnetId", *existing.SubnetId,  "subnetId2",*subnet.SubnetId)
`Found multiple subnets in AZ.` -> `Found multiple subnets in AZ. Choosing one.`
`choosingSubnetId` -> `chosenSubnetId`
`existingSubnetId` -> `firstSubnet`
`subnetId2` -> `secondSubnet`

2021-04-07 19:13 UTC, nckturner commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +	klog.V(2).InfoS("EnsureLoadBalancer",
Missing variable names: `clusterName`, `serviceNamespace`, `serviceName`, `region`, `serviceLoadbalancerIp`, `servicePorts`, `serviceAnnotations`.

2021-04-07 19:13 UTC, nckturner commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +			klog.ErrorS(nil,"Ignoring port without NodePort defined", "nodePort", port)
`nodePort` -> `port`

2021-04-07 19:13 UTC, nckturner commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +			klog.InfoS("Error opening ingress rules for the load balancer to the instances.","error", err)
`klog.ErrorS`?

2021-04-07 19:13 UTC, nckturner commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +		klog.V(4).InfoS("service needs health checks.", "serviceName", apiService.Name, "loadBalancerName", loadBalancerName, "nodePort", healthCheckNodePort, "path", path)
`nodePort` -> `healthCheckNodePort`

2021-04-07 19:13 UTC, nckturner commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +		klog.InfoS("Error registering instances with the load balancer.", "error", err)
`klog.ErrorS`?

2021-04-07 19:14 UTC, nckturner commented
/area provider/aws

2021-05-14 05:00 UTC, yangjunmyfm192085 commented on staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
> +				klog.InfoS("Bad device-number",numStr,"interface", macID)
please ensure gofmt.
run hack/update-gofmt.sh and check hack/verify-gofmt.sh.

2021-06-13 05:07 UTC, closed without merging