Have kubectl drain ignore DaemonSets by default
kubernetes/kubernetes pull request #97667
Opened 2021-01-04 05:23 UTC by yuhaohaoyu

Signed-off-by: Hao Yu <yuh@us.ibm.com>

**What type of PR is this?**

**What this PR does / why we need it**:

`kubectl drain` allows cluster administrators to safely evict pods from a node for maintenance or replacement. If there are pods belonging to a DaemonSet on the node, the drain command will return a fatal error without evicting or deleting any pods if the `--ignore-daemonsets` flag is set to `false`. The drain command will ignore the DaemonSet-managed pods and proceed on evicting or deleting other eligible pods if the `--inore-daemonsets` flag is set to `true`. The default value of the `--ignore-daemonsets` is `false`.

Most Kubernetes clusters have DaemonSet-managed pods running on the worker nodes. The invocations of `kubectl drain` command with the default setting of the `--gnore-daemonsets` argument will mostly fail with a fatal error. Developers and users almost always carry the `--gnore-daemonsets` flag when using `kubectl drain` command to avoid the unnecessary errors. 

Here, we propose a simple code change to set the default value of the `--ignore-daemonsets` argument for the `kubectl drain` command to be `true` so that most usages of `kubectl drain` need not to carry the lengthy argument. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubectl drain ignores running DaemonSets-managed pods by default
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-06 17:10 UTC, eddiezane commented
/ok-to-test
/priority backlog
/triage accepted

2021-01-06 17:10 UTC, eddiezane commented
ref: https://github.com/kubernetes/enhancements/pull/2230

2021-01-06 18:36 UTC, yuhaohaoyu commented
/retest

2021-01-28 12:13 UTC, soltysh requested changes
/hold
Based on the discussion we've had in sig-cli (https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#heading=h.ele88vtcf4ul) we've 
agreed that we'll reach out to k-dev and sig-architecture and ask for feedback with two questions:
1. We want to change the default flag value, and most of our flags are false by default, should we deprecate old flag and introduce new one with reverted meaning. Eg. switch from `--ignore-daemonset` to `--include-daemonsets`? 
2. Is there anyone actually using this flag, and instead of changing it's better to just deprecate it.

Based on the received feedback we'll proceed with actions, but in either case this PR should be only about adding a deprecation warning about the flag.

2021-01-28 12:15 UTC, soltysh commented
/assign

2021-01-28 21:10 UTC, dougsland commented
/cc

2021-01-28 22:06 UTC, dougsland reviewed
just a nit comment until waiting k-dev and sig-architecture

2021-01-28 22:06 UTC, dougsland commented on staging/src/k8s.io/kubectl/pkg/cmd/drain/drain.go
> +			GracePeriodSeconds:  -1,
I would not change the spacing/order for GracePeriodSeconds, Out, ErrOut to avoid show-up in the diff.

2021-04-09 18:15 UTC, michaelgugino commented
> /hold
> Based on the discussion we've had in sig-cli (https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#heading=h.ele88vtcf4ul) we've
> agreed that we'll reach out to k-dev and sig-architecture and ask for feedback with two questions:
> 
>     1. We want to change the default flag value, and most of our flags are false by default, should we deprecate old flag and introduce new one with reverted meaning. Eg. switch from `--ignore-daemonset` to `--include-daemonsets`?
> 
>     2. Is there anyone actually using this flag, and instead of changing it's better to just deprecate it.
> 
> 
> Based on the received feedback we'll proceed with actions, but in either case this PR should be only about adding a deprecation warning about the flag.

Today, daemonsets aren't included, they just cause the drain to fail early if any are found on the node without specifying `--ignore-daemonsets`  "Include" would be the wrong option IMO.  Having to specify ignore-daemonsets=false seems odd, but I like it better than the alternatives.

2021-09-10 05:55 UTC, closed without merging