Fix 'kubectl logs --all-containers --previous' - failure to report all logs before erroring
kubernetes/kubernetes pull request #97686
Opened 2021-01-04 11:07 UTC by wzshiming

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #97530

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Does this PR before, exit if there are any errors
```
> kubectl logs --previous deploy/random-crash --all-containers
error: previous terminated container "bash" in pod "random-crash-67858b7cdc-kwc6z" not found
```

Does this PR after, be consistent with parallelConsumeRequest behavior
```
> kubectl logs --previous deploy/random-crash --all-containers
error: previous terminated container "bash" in pod "random-crash-67858b7cdc-kwc6z" not found
error: previous terminated container "error-container" in pod "random-crash-67858b7cdc-kwc6z" not found
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-04 11:59 UTC, pacoxu commented
/ok-to-test

2021-01-04 12:55 UTC, pacoxu commented
/retest

2021-01-05 01:49 UTC, wzshiming commented
/retest

2021-01-05 07:14 UTC, pacoxu commented
/lgtm

2021-01-06 03:20 UTC, pacoxu commented
/triage accepted

2021-01-06 17:53 UTC, seans3 requested changes
Thanks for sending this PR. Please add a unit test, and consider an integration test to prove that this code is doing what it claims. Thanks.

2021-01-06 17:53 UTC, seans3 commented
/priority backlog

2021-01-07 08:43 UTC, wzshiming commented
/retest

2021-01-07 10:26 UTC, wzshiming commented
/retest

2021-01-07 15:04 UTC, pacoxu approved these changes

2021-01-11 07:36 UTC, wzshiming commented
/assign @liggitt

2021-01-11 13:21 UTC, liggitt commented
/unassign
/assign @soltysh

2021-01-20 10:15 UTC, wzshiming commented
@soltysh @seans3 @dixudx PTAL

2021-01-25 15:27 UTC, dougsland commented
/cc

2021-02-05 10:02 UTC, wzshiming commented
@seans3  Hi
How should I continue this PR?

2021-02-22 02:36 UTC, wzshiming commented
@brendandburns @deads2k @janetkuo @monopole @droot @apelisse @mengqiy @smarterclayton @pwittrock @eddiezane
Could you have a time to take a look, how should I continue this PR?

2021-02-25 19:47 UTC, soltysh approved these changes
/lgtm
/approve

2021-02-25 22:44 UTC, pacoxu commented
/retest

2021-02-26 01:59 UTC, wzshiming commented
/retest

2021-02-26 02:46 UTC, wzshiming commented
/retest

2021-02-26 07:19 UTC, wzshiming commented
/retest

2021-02-26 07:50 UTC, merged

2021-02-26 11:44 UTC, bl-ue commented
Wow&mdash;great job @wzshiming! 🚀

2021-02-26 12:54 UTC, wzshiming commented
Hi @bl-ue 
Thanks, your notes are very helpful.