Update SIG Release Owners Aliases
kubernetes/kubernetes pull request #97700
Opened 2021-01-05 01:42 UTC by hasheddan

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates SIG Release Owners Aliases to reflect:

- @tpepper offboarding
- @saschagrunert to SIG Chair
- @hasheddan to SIG Technical Lead

**Which issue(s) this PR fixes**:

xref https://github.com/kubernetes/sig-release/issues/1322

**Special notes for your reviewer**:

/assign @justaugustus @saschagrunert 
/hold
/sig release
/area release-engineering

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-05 01:43 UTC, hasheddan commented
/area release-eng

2021-01-11 10:38 UTC, saschagrunert approved these changes
/lgtm

2021-01-13 04:22 UTC, justaugustus requested changes
Add @jeremyrickard in, as he'll be confirmed as TL by EOD tomorrow.
ref: https://groups.google.com/g/kubernetes-dev/c/78E3IobBKH0

2021-01-13 04:33 UTC, justaugustus requested changes
@hasheddan -- One more thing...
Can you pull in the changes from https://github.com/kubernetes/kubernetes/pull/97135?

2021-01-13 15:12 UTC, hasheddan commented
@justaugustus I believe this is ready to go now :+1:

2021-01-13 17:19 UTC, saschagrunert approved these changes
/lgtm

2021-01-25 10:58 UTC, justaugustus commented
For 1.21 relnotes shadows:
/verify-owners

2021-01-25 11:00 UTC, justaugustus commented
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
>     * ashnehete
>       
>       * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

@wilsonehusin -- Please work w/ @ashnehete on org membership.

2021-01-25 11:16 UTC, justaugustus commented
@hasheddan -- I tweaked some things and updated the description to reflect.

cc: @kubernetes/sig-release-leads (for review)

For CHANGELOG:
/cc @wilsonehusin

/triage accepted
/hold cancel

2021-01-25 11:17 UTC, justaugustus commented
Also:
/lgtm
/approve

2021-01-25 11:22 UTC, saschagrunert approved these changes
/lgtm

2021-01-25 11:41 UTC, justaugustus commented
For top-level approve:
/assign @liggitt @thockin @smarterclayton

2021-01-25 12:09 UTC, xmudrii approved these changes
/lgtm

2021-01-25 12:21 UTC, cpanato approved these changes
/lgtm

2021-01-25 14:17 UTC, liggitt commented
/approve

2021-01-25 16:15 UTC, merged