fix problem that NewReplicaSet shows <none> when describing deployments
kubernetes/kubernetes pull request #97752
Opened 2021-01-06 03:45 UTC by borgerli

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #97750

**Special notes for your reviewer**:
The cause of issue #97750 is that the `sort.Sort` calls in  `describeDeployment->DescribePodTemplate->describeContainers->describeContainerVolumes` could change the orders of the itersm in  volume mounts array of containers, which will fail the `equalIgnoreHash` comparison in `findNewReplicaSet`. And as a result, the NewReplicaSet  will show as <none>. 

So the fix is just pass the deep copy of the deployment object when calling `describeDeployment`

2021-01-06 20:39 UTC, rikatz commented
/cc
/ok-to-test

2021-01-07 02:21 UTC, borgerli commented
/retest

2021-01-07 07:59 UTC, borgerli commented
/assign @eddiezane

2021-01-07 19:29 UTC, rikatz commented
* Please add the Release Note block
* As this generated the issue #97750 can you please improve the unit test for `TestDescribeDeployment`? My suggestion is to follow the `TestDescribeIngressNetworkPolicies` func, maybe having some improvements in the tests with the expected output other then only if the command runs or not would be really better 

@eddiezane Other than the above, lgtm. Will wait your opinion about improving the unit tests so future bugs can be catched earlier :)

2021-01-08 02:57 UTC, borgerli commented
> * Please add the Release Note block
> * As this generated the issue #97750 can you please improve the unit test for `TestDescribeDeployment`? My suggestion is to follow the `TestDescribeIngressNetworkPolicies` func, maybe having some improvements in the tests with the expected output other then only if the command runs or not would be really better
> 
> @eddiezane Other than the above, lgtm. Will wait your opinion about improving the unit tests so future bugs can be catched earlier :)

Thanks for the comment. I'll add the unit test.

2021-01-08 11:55 UTC, borgerli commented
@rikatz   I just modified the test case of TestDescribeDeployment by covering the NewReplicaSet info verification. Please review. Thanks.

2021-01-08 17:42 UTC, rikatz commented
@borgerli Thanks, will review.

Can you please edit the RELEASE NOTE block on the description of the PR and add a "NONE" into that?

Thanks

2021-01-08 19:48 UTC, rikatz requested changes
@borgerli thank you again.

I've left one review about the test. To be honest, I would expect that we test the whole output instead of only one field, so we can detect other deviations / bugs caused by future changes, there's some example on the test I've mentioned before.

If you need some help with that please let me know.

Thank you!

2021-01-09 14:00 UTC, borgerli commented
/release-note-none

2021-01-09 14:03 UTC, borgerli commented on staging/src/k8s.io/kubectl/pkg/describe/describe_test.go
> +	if !strings.Contains(out, expectedNewReplicaSet) {
Yes, agreed. I'll improve the rest case to validate all computed fields. Thank you.

2021-01-13 12:41 UTC, rikatz commented
@borgerli let me know when the tests are ready :)

2021-01-14 01:57 UTC, borgerli commented
@rikatz Sorry that I'm busy with work this week. I'll try to get tests ready by this Sunday.

2021-01-16 06:37 UTC, borgerli commented
/retest

2021-01-16 09:33 UTC, borgerli commented
/retest

2021-01-16 10:24 UTC, borgerli commented
@rikatz I improved the test case. Please help review. Thanks.

2021-01-19 15:31 UTC, rikatz commented
Will review today

2021-01-19 16:46 UTC, rikatz commented
/triage accepted
/priority important-soon

2021-01-19 16:59 UTC, rikatz commented
/lgtm

Thanks!

2021-01-19 17:11 UTC, rikatz commented
/cc

2021-01-20 15:57 UTC, pwittrock commented
/approve

2021-01-20 16:21 UTC, rikatz commented
/retest

Em qua., 20 de jan. de 2021 às 13:09, Kubernetes Prow Robot <
notifications@github.com> escreveu:

> @borgerli <https://github.com/borgerli>: The following test *failed*, say
> /retest to rerun all failed tests:
> Test name Commit Details Rerun command
> pull-kubernetes-bazel-build a286455
> <https://github.com/kubernetes/kubernetes/commit/a286455a3e230eb1373002b302669c6999c949f1>
> link
> <https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97752/pull-kubernetes-bazel-build/1351922938080661504> /test
> pull-kubernetes-bazel-build
>
> Full PR test history
> <https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=97752>. Your
> PR dashboard
> <https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aborgerli>.
> Please help us cut down on flakes by linking to
> <https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests>
> an open issue
> <https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open> when
> you hit one in your PR.
>
> Instructions for interacting with me using PR comments are available here
> <https://git.k8s.io/community/contributors/guide/pull-requests.md>. If
> you have questions or suggestions related to my behavior, please file an
> issue against the kubernetes/test-infra
> <https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:>
> repository. I understand the commands that are listed here
> <https://go.k8s.io/bot-commands>.
>
> —
>
>
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/97752#issuecomment-763739917>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWZQBIVUDDGTKJKXNMFCQTS2353JANCNFSM4VW3PITA>
> .
>

2021-01-20 17:02 UTC, rikatz commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-01-20 18:38 UTC, merged