pause: encode Windows OS version in image tag instead of repository
kubernetes/kubernetes pull request #97782
Opened 2021-01-06 22:18 UTC by chewong

Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**What type of PR is this?**

Fixes #97780 

cloud build output: https://pastebin.ubuntu.com/p/QgrFfpW97k/
`docker manifest inspect`: https://pastebin.ubuntu.com/p/h3ZcCW28pz/

/sig windows
/kind cleanup
/assign @claudiubelu 
/release-note-none

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-06 22:23 UTC, chewong commented
/release-note-none

2021-01-07 16:57 UTC, chewong commented
/retest

2021-01-08 13:55 UTC, dims commented
/assign @justaugustus 
/approve

2021-01-08 13:56 UTC, dims commented
/triage accepted
/priority important-soon

2021-01-08 16:27 UTC, claudiubelu commented
FWIW, indeed, this PR fixes the issue. LGTM!

2021-01-08 22:22 UTC, justaugustus requested changes
LGTM, but let's bump the tag here as well.

2021-01-08 22:22 UTC, justaugustus commented on build/pause/Makefile
>  TAG = 3.4
```suggestion
TAG = 3.4.1
```

2021-01-08 22:23 UTC, justaugustus commented
/sig release
/area release-eng

2021-01-12 18:39 UTC, jsturtevant commented
/lgtm

2021-01-12 21:27 UTC, chewong commented
/retest

2021-01-12 21:48 UTC, merged