97657: Removed "FromPort" in netpol tests
kubernetes/kubernetes pull request #97863
Opened 2021-01-08 19:50 UTC by qfen

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removed unused and misleading field in a test structure

**Which issue(s) this PR fixes**:

Fixes #97657 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-08 20:49 UTC, mattfenwick commented
/ok-to-test

2021-01-08 22:57 UTC, mattfenwick requested changes
Looking good -- couple of changes, squash the commits and I'll lgtm it!

2021-01-08 22:57 UTC, mattfenwick commented on test/e2e/network/netpol/probe.go
> +		connected, command, err := k8s.probeConnectivity(
not sure if this was meant to be reformatted or not, I think generally it's done in one line in kube !

2021-01-08 22:57 UTC, mattfenwick commented on test/e2e/network/netpol/probe.go
> -		containerFrom, err := podFrom.FindContainer(int32(job.FromPort), job.Protocol)
Is this the only place `FindContainer` was used ?  If so, probably best to remove it.

2021-01-08 22:57 UTC, mattfenwick commented on test/e2e/network/netpol/probe.go
> -		if err != nil {
👍 nice one less error case to worry about now!

2021-01-28 02:23 UTC, jayunit100 commented
this looks ok but we just had a major regression ... see #98341...  so lets hold on it for a few days while tests restabilize, then look at it sunday after looking at testgrid  ?

2021-02-04 15:41 UTC, knabben commented
tests stabilized, nice catch.

/lgtm

2021-02-04 15:59 UTC, mattfenwick commented
/approve

2021-02-04 17:07 UTC, mattfenwick commented
/test pull-kubernetes-e2e-kind-ipv6

2021-02-04 19:35 UTC, mattfenwick commented
/retest

2021-02-04 20:55 UTC, knabben commented
/test pull-kubernetes-e2e-kind-ipv6

2021-02-04 23:02 UTC, merged