Update kuberuntime_container.go
kubernetes/kubernetes pull request #98163
Opened 2021-01-19 07:45 UTC by jikunbupt

graceperiod may exceed 1 second

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-19 07:51 UTC, jikunbupt commented
/assign @sjenning

2021-01-22 01:38 UTC, kikisdeliveryservice requested changes

2021-01-22 01:38 UTC, kikisdeliveryservice commented on pkg/kubelet/kuberuntime/kuberuntime_container.go
> +	klog.V(2).Infof("Killing container %q with a %d second(s) grace period", containerID.String(), gracePeriod)
I don't think this change is correct or necessary.

you'd say: "a 15 second grace period" or "a 1 second grace period" 

second would not be plural in either case.

2021-01-26 18:46 UTC, ehashman reviewed
Thanks for your first contribution to Kubernetes!

Please review our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). Getting this PR merged will require much more reviewer time than the value that it provides. Additionally, it makes a log change, which users may rely on as an interface, so it is breaking.

You can always reach out on Slack for more help!

/close

2021-01-26 18:46 UTC, closed without merging