Change log:Fix  hyperlink of description [kube-controller-manager-kube-scheduler-and-cloud-controller-manager]
kubernetes/kubernetes pull request #98209
Opened 2021-01-20 08:39 UTC by yangjunmyfm192085

…e-scheduler-and-cloud-controller-manager]

Signed-off-by: JunYang <yang.jun22@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Change log:Fix  hyperlink of description [kube-controller-manager-kube-scheduler-and-cloud-controller-manager] 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

2021-01-21 18:35 UTC, tpepper commented
/ok-to-test
/triage accepted
/lgtm

2021-01-21 18:48 UTC, tpepper commented
This is funky.  Looking at where these came from so it can be fixed upstream of the generated .md file.

@yangjunmyfm192085 there are a couple other instances of `/&#35;` in the file.  Can you fix those in this PR also?

2021-01-21 19:15 UTC, tpepper commented
/assign @wilsonehusin

2021-01-21 22:37 UTC, yangjunmyfm192085 commented
/retest

2021-01-22 00:44 UTC, yangjunmyfm192085 commented
will be mentioned next time pr

> This is funky. Looking at where these came from so it can be fixed upstream of the generated .md file.
> 
> @yangjunmyfm192085 there are a couple other instances of `/&#35;` in the file. Can you fix those in this PR also?
Thanks for attention。
I noticed this now，and found other errors。
I'm still reading the rest changelogs。I‘ll try fix them all in next pr。
Let's merge this pr first

2021-01-22 18:43 UTC, tpepper commented
> > I'm still reading the rest changelogs。I‘ll try fix them all in next pr。
> > Let's merge this pr first

There's just a small bit of additional:
```
$ git grep "/&#35;" | wc -l
       7
$ git grep -l "/&#35;"
CHANGELOG/CHANGELOG-1.18.md
CHANGELOG/CHANGELOG-1.19.md
CHANGELOG/CHANGELOG-1.20.md
```

There's little urgency on this individual change and it would be more efficient from a review perspective to get the situation fully addressed by fixing all 7 instances of the error in the 3 files via one commit in one PR.  Separately we've got eyes looking at the generator to make sure no new ones are added.

Can you please make that minor amendment to this PR?

2021-01-22 19:27 UTC, tpepper commented
Also @yangjunmyfm192085 if you're new the workflow of amending existing git commits and GitHub PRs, poke me on Slack (same userid as here) and I'm happy to help walk you through it.  It's super quick and easy!

2021-01-22 21:33 UTC, wilsonehusin commented
+1 to Tim's comment, I'd like to get it resolved at once while I investigate for this not to happen again in new ones being generated.

2021-01-23 01:33 UTC, yangjunmyfm192085 commented
ok.
Thank you for reminding,I have corrected all the incorrect use of  “/&#35;”(Not all need to be modified).

2021-01-23 01:47 UTC, yangjunmyfm192085 commented
Thank you very much. I really like kubernetes and I have just started researching it.
I really hope get help in the future work.

2021-01-23 02:02 UTC, yangjunmyfm192085 commented
> Also @yangjunmyfm192085 if you're new the workflow of amending existing git commits and GitHub PRs, poke me on Slack (same userid as here) and I'm happy to help walk you through it. It's super quick and easy!



> Also @yangjunmyfm192085 if you're new the workflow of amending existing git commits and GitHub PRs, poke me on Slack (same userid as here) and I'm happy to help walk you through it. It's super quick and easy!

Thank you very much. I'm interested in kubernetes and learning it recently,I hope to get some help in the future works,thanks again.

2021-01-23 02:57 UTC, wilsonehusin commented
thanks @yangjunmyfm192085!

/lgtm

2021-01-25 21:03 UTC, tpepper commented
/retitle Change log: fix broken page anchor url encodings

/lgtm

It turns our there are another 17 or so additional instances of `https:/f.q.d.n/file.md&#35;anchor` and `https:/f.q.d.n/string&#35;anchor` which also need fixed up.  And a few cases of ` &#35; ` in text (not urls) which does render correctly.

```bash
git grep -l -e "&#35;"
CHANGELOG/CHANGELOG-1.17.md
CHANGELOG/CHANGELOG-1.18.md
CHANGELOG/CHANGELOG-1.19.md
CHANGELOG/CHANGELOG-1.20.md
```
Putting the leading '/' in the regex was hiding a few. :\  

If @yangjunmyfm192085 can fix those in this same PR too that would be awesome, else I've left a note of the oddity in https://github.com/kubernetes/release/issues/1873.

2021-01-26 23:00 UTC, wilsonehusin commented
hi @yangjunmyfm192085, would you be able to incorporate the changes mentioned by Tim above as well in this PR?

2021-01-27 00:54 UTC, yangjunmyfm192085 commented
> hi @yangjunmyfm192085, would you be able to incorporate the changes mentioned by Tim above as well in this PR?

I'm doing it,but there are some problems.
For example:
- Bug fixes: Make sure we include latest packages node &#35;351 (@caseydavenport)
I can not find issue 351 or pr 351 about caseydavenport,Cannot add hyperlink.
I need only remove extra  "&#35;"?
But remaining  "&#35;" would not be displayed on the page.

2021-01-27 16:49 UTC, wilsonehusin commented
@yangjunmyfm192085 heh I don't know what `#351` is in reference to either. if you wrap it back ticks I'll be okay with it and move on. something like:
```
Make sure we include latest packages node `#351`
```

2021-01-28 07:42 UTC, yangjunmyfm192085 commented
Hi，@wilsonehusin @tpepper ，I have checked all " \&#35"".
Could you review it again? Thank you very much.
Any questions,I'll deal with it at once.

2021-01-28 07:58 UTC, wilsonehusin requested changes
We're getting close, thanks for looking into this and let's get this done! :)

2021-01-28 07:58 UTC, wilsonehusin commented on CHANGELOG/CHANGELOG-1.19.md
> +- Added pod version skew strategy for seccomp profile to synchronize the deprecated annotations with the new API Server fields. Please see the corresponding section [in the KEP](https://github.com/ku
the new path is correct, but I think the `&#35;` still needs to be fixed here 😄

2021-01-28 07:58 UTC, wilsonehusin commented on CHANGELOG/CHANGELOG-1.19.md
> +    - cachingMode: None #ReadOnly host caching is not available for premium SSDs with maxShares>1
missing space between `#` and the first character, this should be
```
    - skuname: Premium_LRS  # Currently only available with premium SSDs.
    - cachingMode: None # ReadOnly host caching is not available for premium SSDs with maxShares>1
```

2021-01-28 07:58 UTC, wilsonehusin commented on CHANGELOG/CHANGELOG-1.19.md
> +    - cachingMode: None  #ReadOnly host caching is not available for premium SSDs with maxShares>1
same as above, need space after `#`

2021-01-28 07:58 UTC, wilsonehusin commented on CHANGELOG/CHANGELOG-1.20.md
> +- Added pod version skew strategy for seccomp profile to synchronize the deprecated annotations with the new API Server fields. Please see the corresponding section [in the KEP](https://github.com/ku
same as above, need to convert `&#35;` --> `#`

2021-01-28 09:02 UTC, yangjunmyfm192085 commented
@wilsonehusin
Sorry,my mistake,already corrected.
thanks.

2021-01-28 16:56 UTC, wilsonehusin approved these changes
Thanks for contributing!

/lgtm
/approve

2021-01-28 17:47 UTC, merged