migrate scheduler/taint_manager.go structured logging
kubernetes/kubernetes pull request #98259
Opened 2021-01-21 10:10 UTC by tanjing2020

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Ref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

**Which issue(s) this PR fixes**:

Verify log output (taint_manager.go):
```
before
taint_manager.go:106] NoExecuteTaintManager is deleting Pod: default/pod1
taint_manager.go:163] Sending events to api server.
taint_manager.go:166] kubeClient is nil when starting NodeController
taint_manager.go:187] Starting NoExecuteTaintManager
taint_manager.go:352] Not all taints are tolerated after update for Pod default/pod1 on node1
taint_manager.go:361] Current tolerations for default/pod1 tolerate forever, cancelling any scheduled deletion.
taint_manager.go:385] Noticed pod deletion: types.NamespacedName{Namespace:"default", Name:"pod1"}
taint_manager.go:400] Noticed pod update: types.NamespacedName{Namespace:"default", Name:"pod1"}
taint_manager.go:424] Noticed node deletion: "node1"
taint_manager.go:435] Noticed node update: scheduler.nodeUpdateItem{nodeName:"node1"}
taint_manager.go:440] Updating known taints on node node1: [{testTaint1 test1 NoExecute 2021-01-21 17:32:28.9701214 +0800 CST m=+0.016594301}]
taint_manager.go:453] failed to get Pods assigned to node node1
taint_manager.go:461] All taints were removed from the Node node1. Cancelling all evictions...
```
```
after
taint_manager.go:106] "NoExecuteTaintManager is deleting Pod" pod="default/pod1"
taint_manager.go:163] "Sending events to api server."
taint_manager.go:166] "kubeClient is nil when starting NodeController"
taint_manager.go:187] "Starting NoExecuteTaintManager"
taint_manager.go:352] "Not all taints are tolerated after update for Pod on node" pod="default/pod1" node="node1"
taint_manager.go:361] "Current tolerations for pod tolerate forever, cancelling any scheduled deletion." pod="default/pod1"
taint_manager.go:385] "Noticed pod deletion" pod="default/pod1"
taint_manager.go:400] "Noticed pod update" pod="default/pod1"
taint_manager.go:424] "Noticed node deletion" node="node1"
taint_manager.go:435] "Noticed node update" node={nodeName:node1}
taint_manager.go:440] "Updating known taints on node" node="node1" taints=[{Key:testTaint1 Value:test1 Effect:NoExecute TimeAdded:2021-01-21 17:33:14.1921732 +0800 CST m=+0.016589601}]
taint_manager.go:453] "Failed to get Pods assigned to node" err="failed to get Pods assigned to node node1" node="node1"
taint_manager.go:461] "All taints were removed from the Node. Cancelling all evictions..." node="node1"
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

2021-01-22 10:27 UTC, ingvagabund commented on pkg/controller/nodelifecycle/scheduler/taint_manager.go
> +		klog.ErrorS(nil, "kubeClient is nil when starting NodeController")
```
// Fatalf logs to the FATAL, ERROR, WARNING, and INFO logs,
// including a stack trace of all running goroutines, then calls os.Exit(255).
// Arguments are handled in the manner of fmt.Printf; a newline is appended if missing.
```

```
// ErrorS is equivalent to the global Error function, guarded by the value of v.
// See the documentation of V for usage.
```

`ErrorS` does not call `os.Exit` so the change is not equivalent

2021-01-22 10:42 UTC, ingvagabund requested changes

2021-01-22 10:42 UTC, ingvagabund commented on pkg/controller/nodelifecycle/scheduler/taint_manager.go
> +		klog.V(0).InfoS("NoExecuteTaintManager is deleting Pod", "pod", args.NamespacedName.String())
s/Pod/pod

There are more place changes that have pod rather than Pod

2021-01-22 10:42 UTC, ingvagabund commented on pkg/controller/nodelifecycle/scheduler/taint_manager.go
> +		klog.V(2).InfoS("Not all taints are tolerated after update for Pod on node", "pod", podNamespacedName.String(), "node", nodeName)
s/Pod/pod

2021-01-22 10:42 UTC, ingvagabund commented on pkg/controller/nodelifecycle/scheduler/taint_manager.go
> +		klog.V(4).InfoS("Current tolerations for pod tolerate forever, cancelling any scheduled deletion.", "pod", podNamespacedName.String())
You can drop the ending dot.

2021-01-22 10:42 UTC, ingvagabund commented on pkg/controller/nodelifecycle/scheduler/taint_manager.go
> +		klog.V(0).InfoS("Sending events to api server.")
You can drop the ending dot

2021-01-22 10:42 UTC, ingvagabund commented on pkg/controller/nodelifecycle/scheduler/taint_manager.go
> +		klog.ErrorS(err, "Failed to get Pods assigned to node", "node", node.Name)
s/Pods/pods

2021-01-22 10:42 UTC, ingvagabund commented on pkg/controller/nodelifecycle/scheduler/taint_manager.go
> +		klog.V(4).InfoS("All taints were removed from the Node. Cancelling all evictions...", "node", node.Name)
s/Node/node

2021-01-22 10:42 UTC, ingvagabund commented
@tanjing2020 is the PR ready for review?

2021-01-25 10:48 UTC, ingvagabund commented
/ok-to-test

2021-01-26 11:16 UTC, ingvagabund commented
cc @k82cn @gmarek

2021-01-26 11:20 UTC, ingvagabund approved these changes

2021-01-28 02:04 UTC, tanjing2020 commented
/cc @gmarek

2021-02-05 06:29 UTC, k82cn commented
/lgtm
/approve

Thanks for the contribution :)

2021-02-05 07:27 UTC, tanjing2020 commented
/test pull-kubernetes-bazel-test

2021-02-05 07:50 UTC, merged