update metadata-concealment to 1.5 for removing legacy checking
kubernetes/kubernetes pull request #98336
Opened 2021-01-24 07:31 UTC by pacoxu

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
https://github.com/kubernetes/kubernetes/pull/97789#issuecomment-763977809

- #97789 is merged
- image build successfully in [sig-testing-images#post-kubernetes-push-e2e-metadata-concealment-test-images](https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-metadata-concealment-test-images) 
- Promote PR merged in k8s.io: https://github.com/kubernetes/k8s.io/pull/1566 
So update the image using here to fix #97789.

**Which issue(s) this PR fixes**:
Fixes #94791

**Does this PR introduce a user-facing change?**:
```release-note
None
```

2021-01-25 14:49 UTC, pacoxu commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-01-25 21:33 UTC, pacoxu commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-01-25 22:55 UTC, spiffxp requested changes
https://github.com/kubernetes/kubernetes/pull/97789/files#diff-290686a2e46d3bbf83bfd02b63accdbc904ca86f6b10de33e871429e8f5d13b4R1 - I think you'll need to update to 1.6, both a k8s.io promotion PR, and updating this PR

2021-01-26 01:59 UTC, pacoxu commented
> https://github.com/kubernetes/kubernetes/pull/97789/files#diff-290686a2e46d3bbf83bfd02b63accdbc904ca86f6b10de33e871429e8f5d13b4R1 - I think you'll need to update to 1.6, both a k8s.io promotion PR, and updating this PR

@spiffxp Sorry for the misunderstanding. Thanks.
I opened 1.6 promote PR kubernetes/k8s.io#1577.

2021-01-27 14:12 UTC, pacoxu commented
/retest
as the image was promoted.

2021-01-28 04:13 UTC, pacoxu commented
As k8s.gcr.io/e2e-test-images/metadata-concealment:1.6  is promoted, this pr can be reviewed now.
@spiffxp would you take a look again? Thanks.

2021-01-28 09:33 UTC, pacoxu commented
``` 
Jan 28 08:32:14.501: FAIL: failed to ensure job completion (metadata-concealment-8415:check-metadata-concealment)
Unexpected error:
    <*errors.errorString | 0xc0001fe1d0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred 
```

Hope the flake failure would be fixed after this is merged.

2021-01-28 18:43 UTC, spiffxp approved these changes
/approve
/lgtm

2021-01-28 22:42 UTC, merged

2021-03-22 20:53 UTC, liggitt commented
https://github.com/kubernetes/kubernetes/pull/100407 fixes this in 1.18

can this also be picked to 1.20 and 1.19? the test is blocking cherry-pick PRs on all release branches

2021-03-22 20:56 UTC, liggitt commented
actually, I can open the picks

2021-03-23 04:38 UTC, pacoxu commented
just see the comment. Thanks @liggitt