start e2e_node test with host swap off
kubernetes/kubernetes pull request #98470
Opened 2021-01-27 09:59 UTC by zhanghe9702

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
in some host , swap space is default on, when run e2e node test, ginkgo node will timeout and has no prompt, because systemd-run will output kubelet startup log to different place

**Which issue(s) this PR fixes**:

Fixes #make test-e2e-node

**Special notes for your reviewer**:
NONE
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-28 18:47 UTC, oomichi commented
> in some host , swap space is default on, when run e2e node test, ginkgo node will timeout and has no prompt, because systemd-run will output kubelet startup log to different place

That seems mis-configuration on the host.
I feel a test suite can detect such thing but it should not fix it automatically because of just a test suite.

/cc @oomichi

2021-02-08 18:21 UTC, SergeyKanzhelev commented
/ok-to-test

2021-02-08 18:21 UTC, SergeyKanzhelev commented
CC: @karan

2021-02-09 01:42 UTC, zhanghe9702 commented
/retest

2021-02-24 18:12 UTC, SergeyKanzhelev commented
/cc @ehashman 
/triage accepted

2021-02-24 21:47 UTC, ehashman requested changes
From the `swapoff` manpage (`swapon(8)`):

```
       Calls  to  swapon  normally occur in the system boot scripts making all
       swap devices available, so that the paging and swapping activity is in‐
       terleaved across several devices and files.
```

The original comment says that this PR is intended to fix `make test-e2e-node`. I don't think a user locally running a makefile would want to trigger this. The test suite doesn't seem like the right place for this change.

/hold

2021-02-24 21:47 UTC, ehashman commented on test/e2e_node/runner/local/run_local.go
> +	// prepare to start kubelet with swap off, avoid ginkgo node timeout
Why does this avoid a ginkgo node timeout?

2021-02-24 21:47 UTC, ehashman commented on test/e2e_node/runner/local/run_local.go
> +	if err := runCommand(swapoff, "-a"); err != nil {
Do we run tests as a privileged user? `swapoff` needs to be run as root in order to not throw an error:

```
ehashman@red-dot:~$ swapoff -a
swapoff: Not superuser.
```

2021-04-14 16:46 UTC, SergeyKanzhelev commented
/close

I'd suggest a different approach - fail the test with the warning and let user disable swap before execution. Please feel free to re-open if you want to go this route.

2021-04-14 16:46 UTC, closed without merging