update tags log
kubernetes/kubernetes pull request #98559
Opened 2021-01-29 03:16 UTC by lovebaby979

/kind Structured Logging migration

Fixes #
update aws tag log

**Does this PR introduce a user-facing change?**:
NONE

```release-note
 Structured Logging migration
```

-->
```docs
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
```

2021-05-11 13:06 UTC, shubheksha requested changes
Minor changes but looks good otherwise 👍

2021-05-11 13:06 UTC, shubheksha commented on staging/src/k8s.io/legacy-cloud-providers/aws/tags.go
> +		klog.ErrorS(err,"Tag legacy nor prefix not found; Kubernetes may behave unexpectedly.", "TagNameKubernetesClusterLegacy", TagNameKubernetesClusterLegacy, " TagNameKubernetesClusterPrefix", TagNameK
I'd change the error message to `Cluster legacy and prefix tags  not found; Kubernetes may behave unexpectedly"

2021-05-11 13:06 UTC, shubheksha commented on staging/src/k8s.io/legacy-cloud-providers/aws/tags.go
> +			klog.InfoS("Resource was missing expected cluster tag .  Will add (with value)", "resourceID",  resourceID, "expectClusterTag", k, "addTag", expected)
`expectClusterTag` -> `expectedClusterTag`

2021-05-14 05:14 UTC, yangjunmyfm192085 commented on staging/src/k8s.io/legacy-cloud-providers/aws/tags.go
> +		klog.V(2).InfoS("Failed to create tags; will retry.","Error", err)
please ensure gofmt.
run hack/update-gofmt.sh and check hack/verify-gofmt.sh.
and use "err", err

2021-05-28 05:43 UTC, yangjunmyfm192085 commented
/wg structured-logging

2021-07-27 06:22 UTC, closed without merging