Allow "Never" value to the RestartPolicy of ReplicaSets
kubernetes/kubernetes pull request #98618
Opened 2021-01-31 06:35 UTC by gjkim42

**What type of PR is this?**

/kind feature
/kind api-change

**What this PR does / why we need it**:

This PR allows "Never" value to the replicaset.spec.template.spec.restartPolicy.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/98539

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Allow "Never" value to the RestartPolicy of Replicasets
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-01-31 07:29 UTC, gjkim42 commented
/remove-kind api-change

2021-02-01 14:56 UTC, sftim commented
This _is_ an API change, right?

2021-02-01 15:44 UTC, gjkim42 commented
This PR adds the new option "Never" to RestartPolicy of ReplicaSet. I think yes. Do we need an API review?

2021-02-08 17:49 UTC, soltysh requested changes
/hold
This is changing one of the fundamental concepts. It should not merge w/o broader agreement from sig-architecture and sig-apps.

2021-02-08 17:51 UTC, sftim commented
/kind api-change

2021-02-08 21:32 UTC, gjkim42 commented
> /hold
> This is changing one of the fundamental concepts. It should not merge w/o broader agreement from sig-architecture and sig-apps.

@soltysh
Thanks for your comment!
Just curious, what is the proper way to get agreements from sig?
sig-meetings? making issue? KEP? or something else?

2021-03-27 03:00 UTC, gjkim42 commented
/close

2021-03-27 03:00 UTC, closed without merging

2021-06-24 13:26 UTC, cynepco3hahue commented
> Thanks for your comment!
> Just curious, what is the proper way to get agreements from sig?
> sig-meetings? making issue? KEP? or something else?

Preparing KEP and join relevant sig meeting.