migrate pkg/authentication/request/headerrequest/requestheader_contro…
kubernetes/kubernetes pull request #98686
Opened 2021-02-02 08:55 UTC by wangkai1994

…ller.go to structured logs

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

xref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-02-02 09:02 UTC, wangkai1994 commented
/sig auth

2021-02-02 09:06 UTC, Cweiping commented
/ok-to-test

2021-02-02 09:44 UTC, wangkai1994 commented
/assign deads2k
/assign wojtek-t

some fix, thanks

2021-02-02 21:26 UTC, fedebongio commented
/triage accepted

2021-02-05 05:22 UTC, wangkai1994 commented
/cc sig-auth-authenticators-approvers

2021-02-19 08:46 UTC, wangkai1994 commented
@enj small cleanup, please have a quick look, Thanks

2021-04-09 06:24 UTC, yangjunmyfm192085 commented
I think you need to confirm the  format of migrate logs again.
Maybe the following description is helpful.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

2021-04-21 02:46 UTC, enj commented on staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
> +		klog.V(2).InfoS("Loaded a new request header values for", c.name)
Wrong format.

```suggestion
		klog.V(2).InfoS("Loaded new request header values", "name", c.name)
```

2021-04-23 03:33 UTC, wangkai1994 commented on staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
> +		klog.V(2).InfoS("Loaded a new request header values for", c.name)
thanks for your help! you are so nice

2021-04-23 05:05 UTC, yangjunmyfm192085 commented on staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
> +		klog.V(2).InfoS("Loaded new request header values", "name", c.name)
Line193，please modify together,thanks.

2021-05-27 13:02 UTC, shubheksha requested changes

2021-05-27 13:02 UTC, shubheksha commented on staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
> +	klog.InfoS("Starting", c.name)
```suggestion
	klog.InfoS("Starting", "controllerName", c.name)
```

2021-05-27 13:02 UTC, shubheksha commented on staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
> +	defer klog.InfoS("Shutting down", c.name)
```suggestion
	defer klog.InfoS("Shutting down", "controllerName", c.name)
```

2021-05-27 13:02 UTC, shubheksha commented on staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
> +		klog.V(2).InfoS("Loaded new request header values", "name", c.name)
```suggestion
		klog.V(2).InfoS("Loaded new request header values", "controllerName", c.name)
```

2021-05-27 13:02 UTC, shubheksha commented
/priority backlog

2021-05-28 05:57 UTC, yangjunmyfm192085 commented
/wg structured-logging

2021-05-28 06:49 UTC, wangkai1994 commented
@yangjunmyfm192085 @shubheksha thank you guys. i am so busy in my job.

2021-06-01 09:32 UTC, wangkai1994 commented
/test pull-kubernetes-e2e-gce-ubuntu-containerd

2021-10-29 11:52 UTC, closed without merging