kubectl lint: generate errors if kubernetes best practises are not followed
kubernetes/kubernetes pull request #98767
Opened 2021-02-04 14:24 UTC by ChaturvediSulabh

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR adds a subcommand `lint` to `kubectl`.  Currently `kubectl lint` only generates the errors if any pods or containers are running as `root`. Although going forward this would become a goto linter to run against Kubernetes manifests. 

- Discussed in [#sig-cli meeting 16 Dec 2020 ](https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#)

**Which issue(s) this PR fixes**:
[This Issue](https://github.com/kubernetes/enhancements/pull/2168)
![kubectl-lint-upstream](https://user-images.githubusercontent.com/36038036/106905931-956e0180-66f4-11eb-9d4a-188c812bb496.png)

2021-02-04 14:44 UTC, ChaturvediSulabh commented
> here



> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

/retest

2021-02-04 14:47 UTC, ChaturvediSulabh commented
/check-cla

2021-02-04 14:54 UTC, ChaturvediSulabh commented
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

update commit author (email and name with which CLA was signed)
/check-cla

2021-02-04 17:36 UTC, MushuEE commented
Thanks! I ran into an issue where I was accidentally double defining a volume claim. Would love to add some linting checks in the future

2021-02-04 17:56 UTC, dougsland commented
/cc

2021-02-04 18:41 UTC, kfox1111 commented
I ran into this https://github.com/FairwindsOps/pluto/ not too long ago. Has proven very useful. Kind of related.

2021-02-05 12:51 UTC, droslean commented
/cc @soltysh

2021-02-10 17:12 UTC, soltysh requested changes
/hold
Adding new commands requires KEP and linting was mentioned during that December call as one of potential solutions brought by @thockin in https://twitter.com/thockin/status/1333892204490735617 I'd prefer, this be initially implemented as a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) and proofed useful before adding that one to core kubectl.

2021-02-10 19:26 UTC, pwittrock commented
I was confused about the state at the meeting in December and suggested @ChaturvediSulabh pick this up as a new-contributor issue since it was relatively self contained and unlikely to have unforeseen issues.

Doing this as a plugin for an alpha release and publishing a KEP seems like a reasonable approach.  We will need a better mechanism for making alpha commands which are plugins discoverable from the kubectl cli.  Perhaps a command stub with installation instructions.  We also need a better structure around the process so that we can provide adequate mentoring and guidance for new contributors.

WDYT of the following?

1. move this to `kubernetes-sigs/cli-experimental` as a plugin
2. write a KEP for this as an alpha command
3. once the KEP is accepted, we can make the plugin discoverable from the `kubectl alpha` subcommand so users can see what is coming down the pipe and better engage with us

2021-02-10 19:31 UTC, pwittrock commented
FYI our docs tell users to come to a bug scrub to pick up an issue: https://kubectl.docs.k8s.io/contributing/kubectl/ and don't give any guidance beyond that.  I feel like our process failed a bit here.

2021-02-11 12:39 UTC, soltysh commented
Yes, that'd be ideal! Thanks a lot :heart:

2021-02-11 21:10 UTC, ChaturvediSulabh commented
Thanks, I'll move this to `kubernetes-sigs/cli-experimental` as a plugin. Once, done, I'll update here and close the PR

2021-03-01 16:05 UTC, ChaturvediSulabh commented
Closing this PR, moved to cli-experimetal, https://github.com/kubernetes-sigs/cli-experimental/pull/109

2021-03-01 16:05 UTC, closed without merging