Automated cherry pick of #94087: node sync at least once
kubernetes/kubernetes pull request #98848
Opened 2021-02-07 07:05 UTC by cwdsuzhou

Cherry pick of #94087 on release-1.18.

#94087: node sync at least once

For details on the cherry pick process, see the cherry pick requests page.

2021-02-07 07:06 UTC, cwdsuzhou commented
/assign @sjenning

2021-02-08 18:29 UTC, ehashman commented
/assign
/kind bug
/release-note-none
/triage accepted
/priority important-soon

2021-02-09 14:31 UTC, alculquicondor commented
Can you highlight in the PR description what is the difference between this and the original PR?

2021-02-09 14:33 UTC, alculquicondor commented
add a release note

2021-02-11 23:23 UTC, ehashman commented
@cwdsuzhou I'm using the following release-note for the other cherry-picks:

```release-note
Avoid marking node as Ready until node has synced with API servers at least once
```

2021-02-11 23:27 UTC, ehashman requested changes
Other than my blocking comment, LGTM. Thanks for fixing the cherry-pick for 1.18.

2021-02-11 23:27 UTC, ehashman commented on pkg/kubelet/kubelet.go
> +				klog.Infof("kubelet nodes sync")
Please remove this log line. It causes logspam (see #98137).

2021-02-12 16:49 UTC, ehashman commented
Cherry-pick deadline is EOD, I will pick this up and try to add the changes

2021-02-12 20:12 UTC, merged

2021-02-12 20:12 UTC, ehashman commented
/close
superseded by #99034 

I built on top of your commit so we could get this in today!