e2e test: update timeout for deployment lifecycle watch context
kubernetes/kubernetes pull request #99323
Opened 2021-02-22 21:29 UTC by heyste

This PR looks to address the issues raised in #98180 and deflake the conformance e2e test `[sig-apps] Deployment should run the lifecycle of a Deployment` 

The test looks to be passing without any issues on [gce-cos-master-default](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=Deployment%20should%20run&width=5) but is having a number of failures with presubmits
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&include-filter-by-regex=should.run.the.lifecycle.of.a.Deployment&width=5
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind-ipv6&sort-by-flakiness=20&include-filter-by-regex=should.run.the.lifecycle.of.a.Deployment&width=5

Reviewing the `build-log.txt` for a number of the flakes shows the test is timing out in two different locations. The common error message is

```
Unexpected error:
    <*errors.errorString | 0xc0002b2230>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```
These timeouts are addressed by adding a new timeout constant and updating all `context.WithTimeout` references in the test.

/kind flake

2021-02-22 21:41 UTC, heyste commented
/release-note-none

2021-02-22 22:22 UTC, heyste commented
/test pull-kubernetes-e2e-kind
flakes x14

Common error around `timed out waiting for the condition`

2021-02-22 22:28 UTC, heyste commented
/test pull-kubernetes-e2e-kind-ipv6 
flake

```
Kubernetes e2e suite: [k8s.io] Pods should run through the lifecycle of Pods and PodStatus [Conformance]   | 2m1s

test/e2e/framework/framework.go:640 
Feb 22 21:48:15.168: failed to see Pod pod-test in namespace pods-4542 running
Unexpected error:
     <*errors.errorString  | 0xc00023e250>: {
         s: "timed out waiting for the condition",
     }
     timed out waiting for the condition
 occurred
 test/e2e/common/pods.go:952
```
```

2021-02-22 22:31 UTC, heyste commented
/test  pull-kubernetes-bazel-test
flake ? `go_test: //staging/src/k8s.io/apiserver/pkg/server/filters:go_default_test`
```
 net/http.(*http2serverConn).runHandler.func1(0xc0000d6050, 0xc0005e3f4f, 0xc000030900)
	GOROOT/src/net/http/h2_bundle.go:5712 +0x23a
panic(0x2031b00, 0xc00003c520)
	GOROOT/src/runtime/panic.go:975 +0x47a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc0005e3c38, 0x1, 0x1)
	staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x169
panic(0x2031b00, 0xc00003c520)
	GOROOT/src/runtime/panic.go:975 +0x47a 
```

2021-02-23 19:35 UTC, hh commented
/lgtm

2021-02-24 17:53 UTC, dims commented
/assign @soltysh @smarterclayton

2021-02-24 21:01 UTC, soltysh requested changes
/hold
Although I'm usually not against bumping timeouts this particular one rises my eyebrow and made me looking deeper into why it suddenly started failing. From what I observed looking at the 2 instances linked in the original issue I've notice a pattern:
1. It takes ~6s to get the first pod running.
2. 2nd pod is created and scheduled at the same time as the first one, but never transitions to running thus leading to a test failure 1 minute later.

This begs a question, what has changed in the runtime that prevented the pod from running? Why it got stuck waiting to be run? Shouldn't we check the kubelet looking for evidence what has changed that is preventing the 2nd pod from transitioning to running promptly? 

I'd like to see some deeper analysis before we bump these times up.

2021-03-02 18:48 UTC, heyste commented
> This begs a question, what has changed in the runtime that prevented the pod from running? Why it got stuck waiting to be run? Shouldn't we check the kubelet looking for evidence what has changed that is preventing the 2nd pod from transitioning to running promptly?

I've had discussions with @BobyMCbobs offline about this and he has given some [feedback](https://github.com/kubernetes/kubernetes/issues/98180#issuecomment-787569135) about what looks to be happening with kubelet.

> it appears that there's an issue with mounting the volume kube-api-access-bj92j into the test-deployment container in the Pod. This operation does not complete and of course it fails.

@soltysh Does this give enough clarify about the test failures and we merge the current change to the test timeout

2021-03-02 21:29 UTC, soltysh commented
> @soltysh Does this give enough clarify about the test failures and we merge the current change to the test timeout

If the problem is with mounter, specifically this one:
```
kubelet_pods.go:159] Mount cannot be satisfied for container "test-deployment", because the volume is missing (ok=false) or the volume mounter (vol.Mounter) is nil (vol={Mounter:<nil> BlockVolumeMapper:<nil> SELinuxLabeled:false ReadOnly:false InnerVolumeSpecName:}): {Name:kube-api-access-bj92j ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil> SubPathExpr:}
```
from https://github.com/kubernetes/kubernetes/issues/98180#issuecomment-787569135 I'm worried that we'll only delay the problem and not solve them. I just checked testgrid and it's not that much pressing issue to skip digging through those bits, please :smile:

2021-03-10 20:53 UTC, closed without merging