migrate logs.
kubernetes/kubernetes pull request #99529
Opened 2021-02-27 10:03 UTC by jialaijun

in /pkg/util/netsh/netsh.go

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it:**

Ref:

- [keps/sig-instrumentation/1602-structured-logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging)

- [Structured Logging migration instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md)

**Does this PR introduce a user-facing change?:**

`Migrate some log messages to structured logging `

2021-03-03 00:26 UTC, ehashman commented
/retitle Structured log migration for pkg/util/netsh
/priority backlog

2021-03-05 16:03 UTC, shubheksha requested changes

2021-03-05 16:03 UTC, shubheksha commented on pkg/util/netsh/netsh.go
> +	klog.V(4).InfoS("running netsh interface portproxy add v4tov4", "args", args)
```suggestion
	klog.V(4).InfoS("Running netsh interface portproxy add v4tov4", "args", args)
```

2021-03-05 16:03 UTC, shubheksha commented on pkg/util/netsh/netsh.go
> +	klog.V(4).InfoS("running netsh interface portproxy delete v4tov4", "args", args)
```suggestion
	klog.V(4).InfoS("Running netsh interface portproxy delete v4tov4", "args", args)
```

2021-03-05 16:03 UTC, shubheksha commented on pkg/util/netsh/netsh.go
> +		klog.V(4).InfoS("not adding IP address, as it already exists", "ipToCheck", ipToCheck)
```suggestion
		klog.V(4).InfoS("Not adding IP address, as it already exists", "IP", ipToCheck)
```

2021-03-05 16:03 UTC, shubheksha commented on pkg/util/netsh/netsh.go
> +	klog.V(4).InfoS("running netsh interface ipv4 add address", "address", args)
```suggestion
	klog.V(4).InfoS("Running netsh interface ipv4 add address", "args", args)
```

2021-03-05 16:03 UTC, shubheksha commented
/triage accepted

2021-03-10 20:23 UTC, caseydavenport approved these changes
/lgtm

2021-03-10 20:23 UTC, caseydavenport commented
/ok-to-test

2021-04-23 08:26 UTC, pacoxu commented
/hold
as there are still some comments.

/release-note-none

2021-08-05 10:28 UTC, dims commented
/retest

2021-08-06 01:45 UTC, dims commented
@pacoxu is this ready?

2021-08-06 02:13 UTC, pacoxu commented
> @pacoxu is this ready?

`running -> Running` Only waiting for this. Not sure if it can be a follow up as the author is not active for about 4 months.

2021-09-14 08:30 UTC, pacoxu commented
/hold cancel
/good-first-issue 
to do a cleanup as the author has no response.

2021-09-14 09:41 UTC, merged

2021-09-15 04:56 UTC, calvin0327 commented
I would like to work in this and submitted a PR as a supplement.