update structured logs.
kubernetes/kubernetes pull request #99544
Opened 2021-02-28 02:45 UTC by jialaijun

in pkg/util/bandwidth/linux.go
in pkg/util/conntrack/conntrack.go
in pkg/util/coverage/coverage.go

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it:**

Ref:

- [keps/sig-instrumentation/1602-structured-logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging)

- [Structured Logging migration instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md)

**Does this PR introduce a user-facing change?:**

`Migrate some log messages to structured logging `

2021-03-02 07:51 UTC, lala123912 commented on pkg/util/bandwidth/linux.go
> +	klog.V(6).InfoS("print Output from tc", "out", string(out))
print Output->Print output

2021-03-05 15:52 UTC, shubheksha requested changes

2021-03-05 15:52 UTC, shubheksha commented on pkg/util/coverage/coverage.go
> +		klog.ErrorS(err, "Couldn't move coverage file", "from", coverageFile, "to", tempCoveragePath())
```suggestion
		klog.ErrorS(err, "Couldn't move coverage file", "sourcePath", coverageFile, "destinationPath", tempCoveragePath())
```

2021-03-05 15:52 UTC, shubheksha commented on pkg/util/bandwidth/linux.go
> +	klog.V(6).InfoS("print Output from tc", "out", string(out))
```suggestion
	klog.V(6).InfoS("print Output from tc", "printOutput", string(out))
```

2021-03-05 15:52 UTC, shubheksha commented
/retitle Migrate to structured logs pkg/util/bandwidth/ and /conntrack

2021-03-05 15:53 UTC, shubheksha commented
/triage accepted

2021-03-05 15:54 UTC, shubheksha commented
/sig instrumentation

2021-03-24 16:03 UTC, logicalhan commented
/assign @serathius

2021-03-24 16:03 UTC, logicalhan commented
/triage accepted

2021-05-28 09:56 UTC, yangjunmyfm192085 commented
/wg structured-logging

2021-07-15 16:42 UTC, dashpole commented
/assign @shubheksha @serathius

2021-07-15 17:53 UTC, serathius commented
/cc @kubernetes/wg-structured-logging-reviews

2021-10-13 22:37 UTC, aojea commented
/ok-to-test
please address the comments and we'll wait for @shubheksha lgtm

2021-12-12 23:44 UTC, closed without merging