update azure_armclient log
kubernetes/kubernetes pull request #99543
Opened 2021-02-28 02:39 UTC by lovebaby979

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
update azure_armclient log
```

2021-02-28 02:59 UTC, nilo19 commented
/ok-to-test

2021-03-02 07:55 UTC, lala123912 commented on staging/src/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go
> +		klog.V(5).InfoS("Send.sendRegionalRequest failed to get response from regional host. Ignoring the result.", "error", regionalErrStr)
error->err, suggested in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

```
With the exception of acronyms like "IP" and the standard "err", don't shorten names. Don't use addr, do use address.
```

2021-03-05 16:18 UTC, shubheksha requested changes

2021-03-05 16:18 UTC, shubheksha commented on staging/src/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go
> +					klog.V(5).Infof("Received error in WaitForAsyncOperationResult, no response", "erroor",err.Error())
Typo

2021-03-05 16:18 UTC, shubheksha commented on staging/src/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go
> +			klog.V(5).InfoS("Received error in WaitForAsyncOperationResult, no response", "erro", err.Error())
Typo

2021-03-05 16:18 UTC, shubheksha commented on staging/src/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go
> +			klog.V(5).InfoS("Received error in WaitForAsyncOperationResult", "error", err.Error(), "response code %d", response.StatusCode)
```suggestion
			klog.V(5).InfoS("Received error in WaitForAsyncOperationResult", "error", err.Error(), "responseCode", response.StatusCode)
```

2021-03-05 16:18 UTC, shubheksha commented on staging/src/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go
>  	if e := json.Unmarshal(bodyBytes, &body); e != nil {
If you're up for it, it'd be great to change the `e` to `err` to make it clearer

2021-03-29 09:10 UTC, closed without merging