update structured logging.
kubernetes/kubernetes pull request #99545
Opened 2021-02-28 02:49 UTC by jialaijun

in pkg/probe/exec/exec.go
in pkg/probe/http/http.go
in pkg/probe/tcp/tcp.go

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it:**

Ref:

- [keps/sig-instrumentation/1602-structured-logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging)

- [Structured Logging migration instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md)

**Does this PR introduce a user-facing change?:**

`Migrate some log messages to structured logging `

2021-03-03 00:31 UTC, ehashman commented
/retitle Structured log migration for pkg/probe
/sig node

2021-03-04 16:43 UTC, ehashman requested changes
/triage accepted
/priority important-soon
/ok-to-test

Please fix your release note. It needs to begin with ```release-note

2021-03-04 16:43 UTC, ehashman commented on pkg/probe/tcp/tcp.go
> +		klog.ErrorS(fmt.Errorf("%v (%#v)", err, err), "Unexpected error closing TCP probe socket")
```suggestion
		klog.ErrorS(err, "Unexpected error closing TCP probe socket")
```

2021-03-04 20:19 UTC, ehashman commented
/remove-priority important-soon
/priority backlog

Since this is against pkg/probe we didn't commit to migrating it this release, I'm going to remove this from the milestone for now (although it'd be great if we could get this merged)

2021-05-28 09:57 UTC, yangjunmyfm192085 commented
/wg structured-logging

2021-07-06 09:28 UTC, pacoxu commented
subset of #100834 which was reviewed.

2021-12-03 11:03 UTC, closed without merging