e2e testing for hugepages downward api
kubernetes/kubernetes pull request #99612
Opened 2021-03-01 22:34 UTC by derekwaynecarr

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add e2e testing for hugepages in downward API.

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:
Related KEP:
https://github.com/kubernetes/enhancements/pull/2352

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2053-downward-api-hugepages
```

2021-03-01 22:45 UTC, derekwaynecarr commented
I am hoping either of the following can assist here with review.

/assign @liggitt 
/assign @tallclair

2021-03-01 22:45 UTC, derekwaynecarr commented
/milestone v1.21

2021-03-01 23:09 UTC, sjenning requested changes

2021-03-01 23:09 UTC, sjenning commented on test/e2e/common/downwardapi.go
> +				"HUGEPAGES_LIMIT=[0-9]",
Seems like this would only pass on nodes with 0-9 allocated hugepages. What if there are more?

2021-03-04 20:35 UTC, desponda commented
👋 Hello! I am from the Bug Triage team! Friendly reminder that code freeze is starting March 9th, 2021 (about 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.
As the PR is tagged for 1.21, is it still planned for this release?

2021-03-04 22:19 UTC, sjenning commented
/lgtm

2021-03-04 22:46 UTC, ehashman reviewed
/priority important-soon
/triage accepted

2021-03-04 22:46 UTC, ehashman commented on test/e2e/common/node/downwardapi.go
> +var _ = framework.KubeDescribe("Downward API [Serial] [Disruptive] [NodeFeature:DownwardAPIHugePages]", func() {
Use SIGDescribe instead?

2021-03-04 22:46 UTC, ehashman commented on test/e2e/common/node/downwardapi.go
> +			e2eskipper.SkipUnlessDownwardAPIHugePagesEnabled()
Needs import I think.

2021-03-05 06:53 UTC, wojtek-t commented on test/e2e/common/node/downwardapi.go
> +var _ = framework.KubeDescribe("Downward API [Serial] [Disruptive] [NodeFeature:DownwardAPIHugePages]", func() {
KubeDescribe no longer exists after: https://github.com/kubernetes/kubernetes/pull/99700

Please use SIGDescribe as Elana suggested.

2021-03-05 15:35 UTC, derekwaynecarr commented
oops, pushed a mess when addressing a rebase conflict.

2021-03-05 16:27 UTC, wojtek-t commented
/lgtm
/approve

Thanks!

2021-03-06 18:47 UTC, merged