increase discovery burst for kube-controller-manager
kubernetes/kubernetes pull request #99660
Opened 2021-03-02 21:40 UTC by deads2k

fixes https://github.com/kubernetes/kubernetes/issues/99503

Discovery is known to be bursty, we even have defaults set to bump the burst if no particular burst has already been set. However, the kube-controller-manager common runs with a burst.  Since discovery usage is limited, we simply increase the burst quite large to accommodate it regardless of the suggested per-client qps.  As a side-effect, this ensures that discovery can never starve the controllers themselves.

/kind bug
/priority important-soon
@kubernetes/sig-api-machinery-bugs 

```release-note
NONE
```

2021-03-03 14:22 UTC, enj requested changes
Copy paste errors.

2021-03-03 14:22 UTC, enj commented on cmd/kube-controller-manager/app/core_test.go
> +	return nil, nil
```suggestion
func (m TestClientBuilder) DiscoveryClient(name string) (discovery.DiscoveryInterface, error) {
	return m.clientset.Discovery(), nil
```

2021-03-03 14:22 UTC, enj commented on staging/src/k8s.io/controller-manager/pkg/clientbuilder/client_builder.go
> +	client, err := b.Client(name)
```suggestion
	client, err := b.DiscoveryClient(name)
```

2021-03-03 14:22 UTC, enj commented on staging/src/k8s.io/controller-manager/pkg/clientbuilder/client_builder_dynamic.go
> +	client, err := t.Client(name)
```suggestion
	client, err := t.DiscoveryClient(name)
```

2021-03-03 14:22 UTC, enj commented
/triage accepted

2021-03-03 15:43 UTC, deads2k commented
> Copy paste errors.

fixed

2021-03-03 20:17 UTC, deads2k commented
/retest

2021-03-03 20:21 UTC, enj commented
/lgtm

2021-03-04 02:08 UTC, dims commented
/hold

2021-03-04 02:12 UTC, dims commented
/hold cancel
/retest

2021-03-04 08:28 UTC, merged