migrate volume/csi/csi_mounter.go logs into structured logging
kubernetes/kubernetes pull request #99689
Opened 2021-03-03 08:32 UTC by CKchen0726

What type of PR is this?
/kind cleanup

What this PR does / why we need it:
part of kubernetes/enhancements#1602

Which issue(s) this PR fixes:
keps/sig-instrumentation/1602-structured-logging

Structured Logging migration instructions

Special notes for your reviewer:

Does this PR introduce a user-facing change?
```release-note
migrate volume/csi/csi_mounter.go logs into structured logging
```

2021-03-03 09:29 UTC, saikat-royc commented
/ok-to-test

2021-03-03 12:50 UTC, CKchen0726 commented
/retest

2021-03-05 15:42 UTC, shubheksha requested changes
Left a few comments around naming arguments, looks good otherwise 👍

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +	klog.V(4).InfoS(log("Mounter.SetUpAt"), "dir", dir)
```suggestion
	klog.V(4).InfoS(log("Mounter.SetUpAt"), "path", dir)
```

Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +	klog.V(4).InfoS(log("Created target path successfully"), "parentDir", parentDir)
```suggestion
	klog.V(4).InfoS(log("Created target path successfully"), "path", parentDir)
```

Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +				klog.ErrorS(removeMountDirErr, log("Mounter.SetUpAt failed to remove mount dir after a NodePublishVolume()"), "dir", dir)
```suggestion
				klog.ErrorS(removeMountDirErr, log("Mounter.SetUpAt failed to remove mount dir after a NodePublishVolume()"), "path", dir)
				
``````
Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +		klog.V(4).InfoS(log("Mounter.SetUpAt fsGroup applied successfully to volume"), "group", *mounterArgs.FsGroup, "volume", c.volumeID)
```suggestion
		klog.V(4).InfoS(log("Mounter.SetUpAt fsGroup applied successfully to volume"), "group", *mounterArgs.FsGroup, "volumeID", c.volumeID)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +	klog.V(4).InfoS(log("Mounter.SetUpAt successfully requested NodePublishVolume"), "dir", dir)
```suggestion
	klog.V(4).InfoS(log("Mounter.SetUpAt successfully requested NodePublishVolume"), "path", dir)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +			klog.V(4).InfoS(log("CSIDriver not found, not adding pod information"), "driver", c.driverName)
```suggestion
			klog.V(4).InfoS(log("CSIDriver not found, not adding pod information"), "driverName", c.driverName)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +		klog.V(4).InfoS(log("CSIDriver does not require pod information"), "driver", c.driverName)
```suggestion
		klog.V(4).InfoS(log("CSIDriver does not require pod information"), "driverName", c.driverName)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +	klog.V(4).InfoS(log("CSIDriver requires pod information"), "driver", c.driverName)
```suggestion
	klog.V(4).InfoS(log("CSIDriver requires pod information"), "driverName", c.driverName)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +			klog.V(5).InfoS(log("CSIDriver not found, not adding service account token information"), "driver", c.driverName)
```suggestion
			klog.V(5).InfoS(log("CSIDriver not found, not adding service account token information"), "driverName", c.driverName)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +	klog.V(4).InfoS(log("Fetched service account token attrs for CSIDriver"), "driver", c.driverName)
```suggestion
	klog.V(4).InfoS(log("Fetched service account token attrs for CSIDriver"), "driverName", c.driverName)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +	klog.V(4).InfoS(log("Unmounter.TearDownAt"), "dir", dir)
```suggestion
	klog.V(4).InfoS(log("Unmounter.TearDownAt"), "path", dir)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +	klog.V(4).InfoS(log("Unmounter.TearDownAt successfully unmounted dir"), "dir", dir)
```suggestion
	klog.V(4).InfoS(log("Unmounter.TearDownAt successfully unmounted dir"), "path", dir)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +		klog.ErrorS(err, log("IsLikelyNotMountPoint check failed for dir"), "dir", dir)
```suggestion
		klog.ErrorS(err, log("IsLikelyNotMountPoint check failed for dir"), "path", dir)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +		klog.V(4).InfoS(log("Remove volume info data file"), "dataFile", dataFile)
```suggestion
		klog.V(4).InfoS(log("Remove volume info data file"), "dataFilePath", dataFile)
```

2021-03-05 15:42 UTC, shubheksha commented on pkg/volume/csi/csi_mounter.go
> +		klog.V(4).InfoS(log("Remove volume path"), "volPath", volPath)
```suggestion
		klog.V(4).InfoS(log("Remove volume path"), "volumePath", volPath)
```

2021-05-07 08:48 UTC, yangjunmyfm192085 commented on pkg/volume/csi/csi_mounter.go
> +		klog.V(2).ErrorS(err, log("Failed to check SELinux support"))
Do we need to modify Info to ErrorS here?
May be InfoS is ok?

2021-05-11 12:54 UTC, shubheksha commented
@CKchen0726 are you still planning to work on this?

2021-05-11 12:56 UTC, shubheksha commented
/triage accepted

2021-05-13 13:55 UTC, CKchen0726 commented on pkg/volume/csi/csi_mounter.go
> +			klog.V(5).InfoS(log("CSIDriver not found, not adding service account token information"), "driver", c.driverName)
Thanks, I will update it later.

2021-07-13 08:03 UTC, closed without merging

2021-08-19 15:23 UTC, shubheksha commented
@CKchen0726 are you still planning to work on this?