Migrate pkg/kubelet/server to structured logging
kubernetes/kubernetes pull request #99838
Opened 2021-03-05 12:10 UTC by adisky

Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Migrate pkg/kubelet/server to structured logging.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2021-03-05 12:18 UTC, serathius commented on pkg/kubelet/server/server.go
> +		klog.ErrorS(err, "Failed to create listener for podResources endpoint")
When replacing `Fatalf`  we should add `os.Exit(1)` to maintain exit. Same as you did above when replacing `Fatal`

2021-03-05 12:19 UTC, adisky commented
/cc @serathius @ehashman 
Can you review? Not sure how to migrate` Fatal` calls to `ErrorS`

2021-03-05 12:19 UTC, serathius commented on pkg/kubelet/server/server.go
> +		klog.ErrorS(err, "Failed to Serve")
When replacing `Fatalf`  we should add `os.Exit(1)` to maintain exit. Same as you did above when replacing `Fatal`

2021-03-05 12:21 UTC, navidshaikh requested changes

2021-03-05 12:21 UTC, navidshaikh commented on pkg/kubelet/server/server.go
> +		klog.ErrorS(err, "Failed to listen amd serve")
```suggestion
		klog.ErrorS(err, "Failed to listen and serve")
```

2021-03-05 12:21 UTC, navidshaikh commented on pkg/kubelet/server/server.go
> +			klog.ErrorS(err, "Failed to listen and serve.")
```suggestion
			klog.ErrorS(err, "Failed to listen and serve")
```

2021-03-05 12:21 UTC, navidshaikh commented on pkg/kubelet/server/server.go
> +		klog.ErrorS(err, "Failed to Serve")
```suggestion
		klog.ErrorS(err, "Failed to serve")
```

2021-03-05 12:47 UTC, adisky commented
Thanks for the review @serathius @navidshaikh 
Addressed review comments PTAL

2021-03-05 13:24 UTC, navidshaikh approved these changes
lgtm

2021-03-05 13:24 UTC, navidshaikh commented
/test pull-kubernetes-e2e-kind

2021-03-05 15:15 UTC, shubheksha commented
/triage accepted 
/priority important-soon

2021-03-05 15:19 UTC, serathius commented
/lgtm
/assign @tallclair

2021-03-08 22:05 UTC, mrunalp commented
/approve

2021-03-09 00:27 UTC, merged