Migrate pkg/kubelet/cm/topologymanager to structure logging
kubernetes/kubernetes pull request #99969
Opened 2021-03-09 00:32 UTC by knabben

#### What type of PR is this?
/kind feature
/sig instrumentation
/sig node

#### What this PR does / why we need it:
Migrate `pkg/kubelet/cm/topologymanager/`

#### Which issue(s) this PR fixes:

Rels https://github.com/kubernetes/kubernetes/issues/98976

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-03-09 11:15 UTC, shubheksha requested changes

2021-03-09 11:15 UTC, shubheksha commented on pkg/kubelet/cm/topologymanager/topology_manager.go
> +	klog.InfoS("[topologymanager] Creating topology manager with policy per scope", "topology", topologyPolicyName, "scope", topologyScopeName)
```suggestion
	klog.InfoS("[topologymanager] Creating topology manager with policy per scope", "topologyPolicyName", topologyPolicyName, "topologyScopeName", topologyScopeName)
```

2021-03-09 11:15 UTC, shubheksha commented on pkg/kubelet/cm/topologymanager/scope_pod.go
> +		klog.InfoS("[topologymanager] TopologyHints", "hints", hints, "pod", format.Pod(pod))
```suggestion
		klog.InfoS("[topologymanager] TopologyHints", "hints", hints, "pod", klog.KObj(pod))
```

2021-03-09 11:49 UTC, shubheksha commented
/triage accepted
/priority important-soon

2021-03-10 00:34 UTC, ehashman requested changes

2021-03-10 00:34 UTC, ehashman commented on pkg/kubelet/cm/topologymanager/fake_topology_manager.go
> +	klog.InfoS("[fake topologymanager] NewFakeManager")
```suggestion
	klog.InfoS("NewFakeManager")
```

Please remove log prefixes

2021-03-10 00:34 UTC, ehashman commented on pkg/kubelet/cm/topologymanager/fake_topology_manager.go
> +	klog.InfoS("[fake topologymanager] AddContainer", "pod", format.Pod(pod), "containerId", containerID)
```suggestion
	klog.InfoS("AddContainer", "pod", klog.KObj(pod), "containerID", containerID)
```

2021-03-10 00:34 UTC, ehashman commented on pkg/kubelet/cm/topologymanager/fake_topology_manager.go
> +	klog.InfoS("[fake topologymanager] RemoveContainer", "containerId", containerID)
```suggestion
	klog.InfoS("RemoveContainer", "containerID", containerID)
```

2021-03-10 00:34 UTC, ehashman commented on pkg/kubelet/cm/topologymanager/scope.go
> +	klog.InfoS("[topologymanager] RemoveContainer", "containerId", containerID)
```suggestion
	klog.InfoS("RemoveContainer", "containerID", containerID)
```

2021-03-11 21:16 UTC, kikisdeliveryservice requested changes, later dismissed
this is a user facing change, please update description so this gets a release note. thanks!

2021-03-12 01:07 UTC, knabben commented
/retest

2021-03-12 01:16 UTC, kikisdeliveryservice commented on pkg/kubelet/cm/topologymanager/scope_container.go
> +		klog.InfoS("Best TopologyHint", "bestHint", bestHint, "pod", klog.KObj(pod), "containerName", container.Name, bestHint)
an extra bestHint at the end here ;)

2021-03-12 01:18 UTC, kikisdeliveryservice reviewed
caught one thing going thru

2021-03-12 01:18 UTC, kikisdeliveryservice commented on pkg/kubelet/cm/topologymanager/scope_container.go
> +		klog.InfoS("Topology Affinity", "bestHint", bestHint, "pod", klog.KObj(pod), "containerName", container.Name, bestHint)
extra bestHint

2021-03-12 19:07 UTC, kikisdeliveryservice reviewed
re-reviewed and all requested changes made. thank you!

/lgtm

2021-03-12 21:43 UTC, ehashman commented
/milestone v1.21

2021-03-16 20:34 UTC, mrunalp approved these changes

2021-03-16 21:49 UTC, merged